// Shared pronunciation helper used by Flashcards, the reading/highlight
// tap-to-hear feature, and lesson drills. Every call first tries a
// cached, natural-sounding clip generated by Google Cloud TTS (rendered
// once, the first time anyone anywhere ever asks for that exact text --
// see hashKey()/audioUrl() below and the website's /api/pronounce route,
// which both apps share), and falls back to the device's own iOS/Android
// TTS engine (expo-speech) whenever that's unavailable: offline, a
// network hiccup, or a brand-new bit of text nobody's triggered
// generation for yet. The web app tried the browser's free
// speechSynthesis for this same job and shelved it (see
// lengo/src/lib/speech.ts's history) because those voices didn't sound
// native enough -- Google's cloud voices are what actually solve that,
// with expo-speech only as the safety net so nothing ever goes silent.
import * as Speech from "expo-speech";
import { createAudioPlayer, type AudioPlayer, type AudioStatus } from "expo-audio";
import { supabase } from "@/lib/supabase/client";
import {
  DEFAULT_PRONUNCIATION_VOICE,
  DEFAULT_PRONUNCIATION_ENABLED,
  type PronunciationVoice,
} from "@/lib/pronunciationVoice";

export type SpeechLang = "es-ES" | "ja-JP" | "en-US";

// Spanish dialect choice: es-ES (Castilian), matching the language tag
// the web prototype already used. Nothing in the lesson content commits
// to a dialect either way -- revisit if the curriculum's Spanish leans
// more Latin American in practice.
export const SPANISH_LANG: SpeechLang = "es-ES";
export const JAPANESE_LANG: SpeechLang = "ja-JP";
export const ENGLISH_LANG: SpeechLang = "en-US";

// The two ways language is keyed elsewhere in the app: a flashcard/story
// "levelPath" like "a1" or "ja-a1", or a Lesson's own "level" like "A1"
// or "JA-A1"/"JA-Alphabets"/"JA-B1".
export function langForLevelPath(levelPath: string): SpeechLang {
  return levelPath.startsWith("ja") ? JAPANESE_LANG : SPANISH_LANG;
}

export function langForLevel(level: string): SpeechLang {
  return level.startsWith("JA") ? JAPANESE_LANG : SPANISH_LANG;
}

// Voice availability is a real per-device concern, mainly for Japanese:
// iOS ships a Japanese voice by default on most locales, but Android
// devices vary and some have no ja-JP voice installed at all. Kept as a
// pure device-voice check (not cloud-aware) for whatever UI wants to
// know that specifically; it no longer needs to gate pronunciation
// controls generally, since the cloud path below works regardless of
// what's installed on-device.
const availabilityCache = new Map<SpeechLang, Promise<boolean>>();

export function isLanguageAvailable(lang: SpeechLang): Promise<boolean> {
  let cached = availabilityCache.get(lang);
  if (!cached) {
    cached = Speech.getAvailableVoicesAsync()
      .then((voices) => voices.some((v) => v.language?.toLowerCase().startsWith(lang.slice(0, 2))))
      // If the platform can't even report voices, assume available rather
      // than hide every pronunciation control over one failed check --
      // speak() itself will simply no-op/fail silently in that case.
      .catch(() => true);
    availabilityCache.set(lang, cached);
  }
  return cached;
}

// Strips the punctuation tokenize() in HighlightableText leaves attached
// to a word (it splits on whitespace only, not word boundaries) so it
// doesn't get read aloud or thrown off by a trailing "." or "¿" -- and so
// two requests differing only in trailing punctuation share one cached
// clip instead of generating (and paying for) two.
export function stripForSpeech(text: string): string {
  return text.replace(/[.,;:!?¿¡"'“”()\[\]]/g, "").trim();
}

// ---- Cached cloud pronunciation ------------------------------------

// Deterministic, dependency-free hash used to name cached pronunciation
// audio files. The identical algorithm is duplicated in the website's
// src/lib/speech.ts and its /api/pronounce route (see each file's own
// copy) so all three compute the same storage path for the same
// (text, lang) pair without a shared package or a network round trip
// just to agree on a filename. Two independent 32-bit FNV-1a passes
// combined into a 64-bit-equivalent hex string -- plain 32-bit FNV-1a
// alone starts to carry a non-negligible collision chance once the
// corpus reaches the thousands of unique strings this app has across two
// full language tracks; doubling it makes a collision practically
// impossible at any size this app will reach.
function fnv1a(str: string, seed: number): number {
  let h = seed;
  for (let i = 0; i < str.length; i++) {
    h ^= str.charCodeAt(i);
    h = Math.imul(h, 0x01000193);
  }
  return h >>> 0;
}

function hashKey(text: string, lang: string, voice: PronunciationVoice): string {
  const input = `${lang}\u0000${voice}\u0000${text.normalize("NFC")}`;
  const a = fnv1a(input, 0x811c9dc5);
  const b = fnv1a(input, 0x9e3779b9);
  return a.toString(16).padStart(8, "0") + b.toString(16).padStart(8, "0");
}

const SUPABASE_URL = process.env.EXPO_PUBLIC_SUPABASE_URL ?? "";
const STORAGE_BASE = `${SUPABASE_URL}/storage/v1/object/public/pronunciation-audio`;
const PRONOUNCE_API_URL = "https://deependspanish.com/api/pronounce";

function audioUrl(text: string, lang: SpeechLang, voice: PronunciationVoice): string {
  return `${STORAGE_BASE}/${lang}/${hashKey(text, lang, voice)}.mp3`;
}

// In-memory cache of the signed-in learner's saved pronunciation voice
// (profiles.pronunciation_voice). Loaded lazily -- the first speak() of
// a session awaits it -- rather than threaded as a prop through every
// screen that calls speak() (flashcards, exercises, tap-to-hear text),
// since it's one account-level setting, not something any of those call
// sites need to know about individually.
let preferredVoice: PronunciationVoice = DEFAULT_PRONUNCIATION_VOICE;
let pronunciationEnabled: boolean = DEFAULT_PRONUNCIATION_ENABLED;
let prefsLoaded = false;
let prefsLoadPromise: Promise<void> | null = null;

// Called by SettingsScreen the instant the learner changes their pick,
// so speak() reflects it immediately this session instead of waiting on
// a fresh profile fetch.
export function setPreferredVoice(voice: PronunciationVoice): void {
  preferredVoice = voice;
  prefsLoaded = true;
}

// Called by SettingsScreen the instant the learner flips pronunciation
// off -- also stops anything already playing right away, rather than
// waiting for the next tap to notice.
export function setPronunciationEnabled(enabled: boolean): void {
  pronunciationEnabled = enabled;
  prefsLoaded = true;
  if (!enabled) {
    currentPlayer?.remove();
    currentPlayer = null;
    Speech.stop();
  }
}

function loadPronunciationPrefs(): Promise<void> {
  if (prefsLoaded) return Promise.resolve();
  if (prefsLoadPromise) return prefsLoadPromise;
  prefsLoadPromise = (async () => {
    try {
      const {
        data: { user },
      } = await supabase.auth.getUser();
      if (!user) return;
      const { data } = await supabase
        .from("profiles")
        .select("pronunciation_voice, pronunciation_enabled")
        .eq("id", user.id)
        .single();
      const v = data?.pronunciation_voice;
      if (v === "male" || v === "female") preferredVoice = v;
      if (typeof data?.pronunciation_enabled === "boolean") pronunciationEnabled = data.pronunciation_enabled;
    } catch {
      // Network hiccup or logged out -- stick with the defaults rather
      // than block speech on this.
    } finally {
      prefsLoaded = true;
    }
  })();
  return prefsLoadPromise;
}

// Only Spanish and Japanese get generated cloud audio -- English UI text
// (flashcard backs, glosses, etc.) always uses the device voice, which is
// already fine for English and isn't worth paying to regenerate.
function hasCloudVoice(lang: SpeechLang): boolean {
  return lang === SPANISH_LANG || lang === JAPANESE_LANG;
}

let currentPlayer: AudioPlayer | null = null;

// Tries to play a clip at `url`. Resolves true once playback has actually
// started, false if it 404s, errors, or takes too long to load -- a
// timeout rather than an indefinite wait, so a slow or dead connection
// always falls through to the device voice instead of leaving a tap
// silent.
function tryPlayRemote(url: string): Promise<boolean> {
  return new Promise((resolve) => {
    let settled = false;
    let started = false;
    const finish = (ok: boolean) => {
      if (settled) return;
      settled = true;
      resolve(ok);
    };
    let player: AudioPlayer;
    try {
      player = createAudioPlayer(url);
    } catch {
      finish(false);
      return;
    }
    currentPlayer = player;
    const sub = player.addListener("playbackStatusUpdate", (status: AudioStatus) => {
      if (status.error) {
        finish(false);
        return;
      }
      if (status.isLoaded && !started) {
        started = true;
        player.play();
        finish(true);
      }
      if (status.didJustFinish) {
        player.remove();
        sub.remove();
      }
    });
    setTimeout(() => finish(false), 4000);
  });
}

// Asks the website's shared /api/pronounce route to render this exact
// text (it isn't cached yet), uploading the result to storage for every
// future request -- mobile and web alike -- to find already cached.
// Requires the learner's own session (same auth model as the in-app
// translator, src/lib/translate/api.ts) so this costed call isn't wide
// open to anyone who isn't using the app.
async function requestGeneration(text: string, lang: SpeechLang, voice: PronunciationVoice): Promise<string | null> {
  try {
    const { data } = await supabase.auth.getSession();
    const token = data.session?.access_token;
    if (!token) return null;
    const res = await fetch(
      `${PRONOUNCE_API_URL}?text=${encodeURIComponent(text)}&lang=${encodeURIComponent(lang)}&voice=${voice}`,
      { headers: { Authorization: `Bearer ${token}` } }
    );
    if (!res.ok) return null;
    const json = await res.json();
    return typeof json?.url === "string" ? json.url : null;
  } catch {
    return null;
  }
}

function speakOnDevice(clean: string, lang: SpeechLang) {
  Speech.stop();
  Speech.speak(clean, {
    language: lang,
    pitch: 1.0,
    // Slightly slower for Japanese -- kana/kanji run together with no
    // spaces, so full native rate reads as a blur for a learner.
    rate: lang === JAPANESE_LANG ? 0.85 : 1.0,
  });
}

// Speaks `text` in `lang`: plays the cached cloud recording when one
// exists, generates it on the fly the first time this exact text is ever
// requested anywhere, and falls back to the device's own voice if the
// cloud path fails or isn't offered for this language. Cancels anything
// already playing/speaking first so rapid taps (flipping through
// flashcards, tapping several words) don't pile up overlapping audio.
export function speak(text: string, lang: SpeechLang) {
  const clean = stripForSpeech(text);
  if (!clean) return;

  currentPlayer?.remove();
  currentPlayer = null;
  Speech.stop();

  void (async () => {
    await loadPronunciationPrefs();
    if (!pronunciationEnabled) return;

    if (!hasCloudVoice(lang)) {
      speakOnDevice(clean, lang);
      return;
    }

    const voice = preferredVoice;
    if (await tryPlayRemote(audioUrl(clean, lang, voice))) return;
    const generatedUrl = await requestGeneration(clean, lang, voice);
    if (generatedUrl && (await tryPlayRemote(generatedUrl))) return;
    speakOnDevice(clean, lang);
  })();
}

export function stopSpeaking() {
  currentPlayer?.remove();
  currentPlayer = null;
  Speech.stop();
}
