// Shared pronunciation helper used by Flashcards, the reading/highlight
// tap-to-hear feature, and lesson drills. Every call first tries a
// cached, natural-sounding clip generated by Google Cloud TTS (rendered
// once, the first time anyone anywhere ever asks for that exact text --
// see hashKey()/audioUrl() below and the website's /api/pronounce route,
// which both apps share), and falls back to the device's own iOS/Android
// TTS engine (expo-speech) whenever that's unavailable: offline, a
// network hiccup, or a brand-new bit of text nobody's triggered
// generation for yet. The web app tried the browser's free
// speechSynthesis for this same job and shelved it (see
// lengo/src/lib/speech.ts's history) because those voices didn't sound
// native enough -- Google's cloud voices are what actually solve that,
// with expo-speech only as the safety net so nothing ever goes silent.
import * as Speech from "expo-speech";
import { createAudioPlayer, setAudioModeAsync, type AudioPlayer, type AudioStatus } from "expo-audio";
import { supabase } from "@/lib/supabase/client";
import {
  DEFAULT_PRONUNCIATION_VOICE,
  DEFAULT_PRONUNCIATION_ENABLED,
  type PronunciationVoice,
} from "@/lib/pronunciationVoice";
import { getSpanishVariety, loadSpanishVariety, spanishSpeechLang } from "@/lib/spanishVariety";

export type SpeechLang = "es-ES" | "es-US" | "ja-JP" | "en-US";

// Screens ask for Spanish as SPANISH_LANG (es-ES); the learner's "Spanish
// I want to learn" setting decides which voice actually speaks it --
// Castilian (es-ES) or Latin American (es-US). See voiceLang() below and
// spanishVariety.ts.
export const SPANISH_LANG: SpeechLang = "es-ES";
export const JAPANESE_LANG: SpeechLang = "ja-JP";
export const ENGLISH_LANG: SpeechLang = "en-US";

// The two ways language is keyed elsewhere in the app: a flashcard/story
// "levelPath" like "a1" or "ja-a1", or a Lesson's own "level" like "A1"
// or "JA-A1"/"JA-Alphabets"/"JA-B1".
export function langForLevelPath(levelPath: string): SpeechLang {
  return levelPath.startsWith("ja") ? JAPANESE_LANG : SPANISH_LANG;
}

export function langForLevel(level: string): SpeechLang {
  return level.startsWith("JA") ? JAPANESE_LANG : SPANISH_LANG;
}

// Voice availability is a real per-device concern, mainly for Japanese:
// iOS ships a Japanese voice by default on most locales, but Android
// devices vary and some have no ja-JP voice installed at all. Kept as a
// pure device-voice check (not cloud-aware) for whatever UI wants to
// know that specifically; it no longer needs to gate pronunciation
// controls generally, since the cloud path below works regardless of
// what's installed on-device.
const availabilityCache = new Map<SpeechLang, Promise<boolean>>();

export function isLanguageAvailable(lang: SpeechLang): Promise<boolean> {
  let cached = availabilityCache.get(lang);
  if (!cached) {
    cached = Speech.getAvailableVoicesAsync()
      .then((voices) => voices.some((v) => v.language?.toLowerCase().startsWith(lang.slice(0, 2))))
      // If the platform can't even report voices, assume available rather
      // than hide every pronunciation control over one failed check --
      // speak() itself will simply no-op/fail silently in that case.
      .catch(() => true);
    availabilityCache.set(lang, cached);
  }
  return cached;
}

// Strips the punctuation tokenize() in HighlightableText leaves attached
// to a word (it splits on whitespace only, not word boundaries) so it
// doesn't get read aloud or thrown off by a trailing "." or "¿" -- and so
// two requests differing only in trailing punctuation share one cached
// clip instead of generating (and paying for) two.
export function stripForSpeech(text: string): string {
  return text.replace(/[.,;:!?¿¡"'“”()\[\]]/g, "").trim();
}

// ---- Cached cloud pronunciation ------------------------------------

// Deterministic, dependency-free hash used to name cached pronunciation
// audio files. The identical algorithm is duplicated in the website's
// src/lib/speech.ts and its /api/pronounce route (see each file's own
// copy) so all three compute the same storage path for the same
// (text, lang) pair without a shared package or a network round trip
// just to agree on a filename. Two independent 32-bit FNV-1a passes
// combined into a 64-bit-equivalent hex string -- plain 32-bit FNV-1a
// alone starts to carry a non-negligible collision chance once the
// corpus reaches the thousands of unique strings this app has across two
// full language tracks; doubling it makes a collision practically
// impossible at any size this app will reach.
function fnv1a(str: string, seed: number): number {
  let h = seed;
  for (let i = 0; i < str.length; i++) {
    h ^= str.charCodeAt(i);
    h = Math.imul(h, 0x01000193);
  }
  return h >>> 0;
}

function hashKey(text: string, lang: string, voice: PronunciationVoice): string {
  const input = `${lang}\u0000${voice}\u0000${text.normalize("NFC")}`;
  const a = fnv1a(input, 0x811c9dc5);
  const b = fnv1a(input, 0x9e3779b9);
  return a.toString(16).padStart(8, "0") + b.toString(16).padStart(8, "0");
}

const SUPABASE_URL = process.env.EXPO_PUBLIC_SUPABASE_URL ?? "";
const STORAGE_BASE = `${SUPABASE_URL}/storage/v1/object/public/pronunciation-audio`;
const PRONOUNCE_API_URL = "https://deependspanish.com/api/pronounce";

function audioUrl(text: string, lang: SpeechLang, voice: PronunciationVoice): string {
  return `${STORAGE_BASE}/${lang}/${hashKey(text, lang, voice)}.mp3`;
}

// In-memory cache of the signed-in learner's saved pronunciation voice
// (profiles.pronunciation_voice). Loaded lazily -- the first speak() of
// a session awaits it -- rather than threaded as a prop through every
// screen that calls speak() (flashcards, exercises, tap-to-hear text),
// since it's one account-level setting, not something any of those call
// sites need to know about individually.
let preferredVoice: PronunciationVoice = DEFAULT_PRONUNCIATION_VOICE;
let pronunciationEnabled: boolean = DEFAULT_PRONUNCIATION_ENABLED;
let prefsLoaded = false;
let prefsLoadPromise: Promise<void> | null = null;

// Called by SettingsScreen the instant the learner changes their pick,
// so speak() reflects it immediately this session instead of waiting on
// a fresh profile fetch.
export function setPreferredVoice(voice: PronunciationVoice): void {
  preferredVoice = voice;
  prefsLoaded = true;
}

// Called by SettingsScreen the instant the learner flips pronunciation
// off -- also stops anything already playing right away, rather than
// waiting for the next tap to notice.
export function setPronunciationEnabled(enabled: boolean): void {
  pronunciationEnabled = enabled;
  prefsLoaded = true;
  if (!enabled) {
    currentPlayer?.remove();
    currentPlayer = null;
    Speech.stop();
  }
}

function loadPronunciationPrefs(): Promise<void> {
  if (prefsLoaded) return Promise.resolve();
  if (prefsLoadPromise) return prefsLoadPromise;
  prefsLoadPromise = (async () => {
    try {
      const {
        data: { user },
      } = await supabase.auth.getUser();
      if (!user) return;
      const { data } = await supabase
        .from("profiles")
        .select("pronunciation_voice, pronunciation_enabled")
        .eq("id", user.id)
        .single();
      const v = data?.pronunciation_voice;
      if (v === "male" || v === "female") preferredVoice = v;
      if (typeof data?.pronunciation_enabled === "boolean") pronunciationEnabled = data.pronunciation_enabled;
    } catch {
      // Network hiccup or logged out -- stick with the defaults rather
      // than block speech on this.
    } finally {
      prefsLoaded = true;
    }
  })();
  return prefsLoadPromise;
}

// Only Spanish and Japanese get generated cloud audio -- English UI text
// (flashcard backs, glosses, etc.) always uses the device voice, which is
// already fine for English and isn't worth paying to regenerate.
function hasCloudVoice(lang: SpeechLang): boolean {
  return lang === "es-ES" || lang === "es-US" || lang === JAPANESE_LANG;
}

function voiceLang(lang: SpeechLang): SpeechLang {
  return lang.startsWith("es") ? spanishSpeechLang(getSpanishVariety()) : lang;
}

// The device voice for Latin American Spanish: a US Spanish voice, else
// Mexican, else Latin American, else any Spanish voice that isn't
// Castilian. undefined leaves the choice to the platform (by language).
const LATAM_FALLBACKS = ["es-us", "es-mx", "es-419"];
let latamDeviceVoice: Promise<string | undefined> | null = null;
function deviceVoiceFor(lang: SpeechLang): Promise<string | undefined> {
  if (lang !== "es-US") return Promise.resolve(undefined);
  if (!latamDeviceVoice) {
    latamDeviceVoice = Speech.getAvailableVoicesAsync()
      .then((voices) => {
        const norm = (l: string | undefined) => (l ?? "").toLowerCase().replace("_", "-");
        for (const tag of LATAM_FALLBACKS) {
          const match = voices.find((v) => norm(v.language) === tag);
          if (match) return match.identifier;
        }
        return voices.find((v) => norm(v.language).startsWith("es-") && norm(v.language) !== "es-es")?.identifier;
      })
      .catch(() => undefined);
  }
  return latamDeviceVoice;
}

let currentPlayer: AudioPlayer | null = null;

// iOS mutes app audio while the ring/silent switch is on silent unless the
// app opts out -- which left every Google clip silent on a phone in silent
// mode (the device voice, which ignores the switch, still spoke). A
// pronunciation tap is a deliberate request to hear something, so play
// through the switch. Set once, before the first clip.
let audioModePromise: Promise<void> | null = null;
function ensureAudioMode(): Promise<void> {
  if (!audioModePromise) {
    audioModePromise = setAudioModeAsync({ playsInSilentMode: true, interruptionMode: "duckOthers" }).catch(() => {});
  }
  return audioModePromise;
}

// A quick HEAD request says whether a clip is cached at all. Without it, a
// clip nobody has requested yet sat in the player until its 4-second
// timeout before generation even started, so a first tap stayed silent
// long enough to look broken.
async function clipExists(url: string): Promise<boolean> {
  try {
    const res = await fetch(url, { method: "HEAD" });
    return res.ok;
  } catch {
    return false;
  }
}

// Tries to play a clip at `url`. Resolves true once playback has actually
// started, false if it 404s, errors, or takes too long to load -- a
// timeout rather than an indefinite wait, so a slow or dead connection
// always falls through to the device voice instead of leaving a tap
// silent.
function tryPlayRemote(url: string, rate = 1): Promise<boolean> {
  return new Promise((resolve) => {
    let settled = false;
    let started = false;
    const finish = (ok: boolean) => {
      if (settled) return;
      settled = true;
      resolve(ok);
    };
    let player: AudioPlayer;
    try {
      player = createAudioPlayer(url);
    } catch {
      finish(false);
      return;
    }
    currentPlayer = player;
    const sub = player.addListener("playbackStatusUpdate", (status: AudioStatus) => {
      if (status.error) {
        finish(false);
        return;
      }
      if (status.isLoaded && !started) {
        started = true;
        // Pitch-corrected, so slowed-down speech doesn't sound deeper.
        if (rate !== 1) player.setPlaybackRate(rate, "high");
        player.play();
        finish(true);
      }
      if (status.didJustFinish) {
        player.remove();
        sub.remove();
      }
    });
    setTimeout(() => finish(false), 4000);
  });
}

// Asks the website's shared /api/pronounce route to render this exact
// text (it isn't cached yet), uploading the result to storage for every
// future request -- mobile and web alike -- to find already cached.
// Requires the learner's own session (same auth model as the in-app
// translator, src/lib/translate/api.ts) so this costed call isn't wide
// open to anyone who isn't using the app.
async function requestGeneration(text: string, lang: SpeechLang, voice: PronunciationVoice): Promise<string | null> {
  try {
    const { data } = await supabase.auth.getSession();
    const token = data.session?.access_token;
    if (!token) return null;
    const res = await fetch(
      `${PRONOUNCE_API_URL}?text=${encodeURIComponent(text)}&lang=${encodeURIComponent(lang)}&voice=${voice}`,
      { headers: { Authorization: `Bearer ${token}` } }
    );
    if (!res.ok) return null;
    const json = await res.json();
    return typeof json?.url === "string" ? json.url : null;
  } catch {
    return null;
  }
}

async function speakOnDevice(clean: string, lang: SpeechLang, rate = 1) {
  const voice = await deviceVoiceFor(lang);
  Speech.stop();
  Speech.speak(clean, {
    language: lang,
    voice,
    pitch: 1.0,
    // Slightly slower for Japanese -- kana/kanji run together with no
    // spaces, so full native rate reads as a blur for a learner.
    rate: (lang === JAPANESE_LANG ? 0.85 : 1.0) * rate,
  });
}

// Speaks `text` in `lang`: plays the cached cloud recording when one
// exists, generates it on the fly the first time this exact text is ever
// requested anywhere, and falls back to the device's own voice if the
// cloud path fails or isn't offered for this language. Cancels anything
// already playing/speaking first so rapid taps (flipping through
// flashcards, tapping several words) don't pile up overlapping audio.
// `rate` below 1 slows playback down (dictation's "slow" replay).
export function speak(text: string, requestedLang: SpeechLang, rate = 1) {
  const clean = stripForSpeech(text);
  if (!clean) return;

  stopReadAloud();
  currentPlayer?.remove();
  currentPlayer = null;
  Speech.stop();
  // stopReadAloud() just bumped this; a later tap bumps it again, so a
  // tap still waiting on the network can tell it's been superseded.
  const run = readAloudRun;

  void (async () => {
    await Promise.all([loadPronunciationPrefs(), loadSpanishVariety()]);
    if (!pronunciationEnabled) return;
    const lang = voiceLang(requestedLang);

    if (!hasCloudVoice(lang)) {
      void speakOnDevice(clean, lang, rate);
      return;
    }

    await ensureAudioMode();
    const voice = preferredVoice;
    const cachedUrl = audioUrl(clean, lang, voice);
    const cached = await clipExists(cachedUrl);
    if (run !== readAloudRun) return;
    if (cached && (await tryPlayRemote(cachedUrl, rate))) return;
    const generatedUrl = await requestGeneration(clean, lang, voice);
    if (run !== readAloudRun) return;
    if (generatedUrl && (await tryPlayRemote(generatedUrl, rate))) return;
    if (run !== readAloudRun) return;
    void speakOnDevice(clean, lang, rate);
  })();
}

// iOS only records while the audio session allows it, and while it does,
// playback goes to the quiet earpiece -- so the speak exercise turns
// recording on just for the recording and off again straight after.
export async function setRecordingMode(on: boolean): Promise<void> {
  try {
    await setAudioModeAsync(
      on
        ? { playsInSilentMode: true, allowsRecording: true, interruptionMode: "doNotMix" }
        : { playsInSilentMode: true, allowsRecording: false, interruptionMode: "duckOthers" }
    );
  } catch {
    // The recorder reports its own failure; playback keeps its last mode.
  }
}

export function stopSpeaking() {
  stopReadAloud();
  currentPlayer?.remove();
  currentPlayer = null;
  Speech.stop();
}

// ---- Reading a whole text aloud ------------------------------------
// Mirrors readAloud() in the website's src/lib/speech.ts.

// /api/pronounce renders at most 200 characters per clip, and a clip per
// sentence also lets a listener hear the story in natural pieces. Unlike
// speak(), punctuation is kept: it's what gives the voice its pauses and
// question intonation.
const MAX_CLIP_CHARS = 200;

/** Splits a paragraph into sentence-sized pieces for readAloud(). */
export function speechChunks(paragraph: string): string[] {
  const sentences = paragraph.match(/[^.!?…]+(?:[.!?…]+["”»')\]]*|$)/g) ?? [];
  const chunks: string[] = [];
  for (const raw of sentences) {
    let rest = raw.trim();
    while (rest.length > MAX_CLIP_CHARS) {
      const window = rest.slice(0, MAX_CLIP_CHARS);
      const cut = Math.max(window.lastIndexOf(", "), window.lastIndexOf("; "), window.lastIndexOf(": "));
      const at = cut > 40 ? cut + 1 : window.lastIndexOf(" ");
      chunks.push(rest.slice(0, at).trim());
      rest = rest.slice(at).trim();
    }
    if (/[A-Za-zÁÉÍÓÚÜÑáéíóúüñ\u3040-\u30ff\u4e00-\u9fff]/.test(rest)) chunks.push(rest);
  }
  return chunks;
}

type ClipResult = "ended" | "failed" | "stopped";

// Bumped by every new readAloud(), stopReadAloud(), speak() and
// stopSpeaking(), so a read-aloud loop can tell it has been replaced.
let readAloudRun = 0;
// Resolves the clip that's playing right now as "stopped".
let stopCurrentClip: (() => void) | null = null;

export function stopReadAloud(): void {
  readAloudRun++;
  const stop = stopCurrentClip;
  stopCurrentClip = null;
  stop?.();
}

function playClipToEnd(url: string): Promise<ClipResult> {
  return new Promise((resolve) => {
    let settled = false;
    let started = false;
    let player: AudioPlayer | null = null;
    const finish = (result: ClipResult) => {
      if (settled) return;
      settled = true;
      if (stopCurrentClip === stop) stopCurrentClip = null;
      player?.remove();
      if (currentPlayer === player) currentPlayer = null;
      resolve(result);
    };
    const stop = () => finish("stopped");
    stopCurrentClip = stop;
    try {
      player = createAudioPlayer(url);
    } catch {
      finish("failed");
      return;
    }
    currentPlayer = player;
    player.addListener("playbackStatusUpdate", (status: AudioStatus) => {
      if (status.error) {
        finish(started ? "ended" : "failed");
        return;
      }
      if (status.isLoaded && !started) {
        started = true;
        player?.play();
      }
      if (status.didJustFinish) finish("ended");
    });
    setTimeout(() => {
      if (!started) finish("failed");
    }, 4000);
  });
}

async function speakOnDeviceToEnd(text: string, lang: SpeechLang): Promise<ClipResult> {
  const voice = await deviceVoiceFor(lang);
  return new Promise((resolve) => {
    let settled = false;
    const finish = (result: ClipResult) => {
      if (settled) return;
      settled = true;
      if (stopCurrentClip === stop) stopCurrentClip = null;
      resolve(result);
    };
    const stop = () => {
      Speech.stop();
      finish("stopped");
    };
    stopCurrentClip = stop;
    Speech.stop();
    Speech.speak(text, {
      language: lang,
      voice,
      rate: lang === JAPANESE_LANG ? 0.85 : 0.95,
      onDone: () => finish("ended"),
      onError: () => finish("ended"),
      onStopped: () => finish("stopped"),
    });
  });
}

// Makes sure the next clip is already generated and cached while the
// current one plays, so there's no pause between sentences on a story
// nobody has listened to before.
function warmClip(text: string, lang: SpeechLang, voice: PronunciationVoice): void {
  if (!hasCloudVoice(lang)) return;
  void fetch(audioUrl(text, lang, voice), { method: "HEAD" })
    .then((res) => (res.ok ? null : requestGeneration(text, lang, voice)))
    .catch(() => null);
}

async function playChunk(text: string, lang: SpeechLang, run: number): Promise<ClipResult> {
  if (!hasCloudVoice(lang)) return speakOnDeviceToEnd(text, lang);
  await ensureAudioMode();
  const voice = preferredVoice;
  const cachedUrl = audioUrl(text, lang, voice);
  const cached = await clipExists(cachedUrl);
  if (run !== readAloudRun) return "stopped";
  let result: ClipResult = cached ? await playClipToEnd(cachedUrl) : "failed";
  if (result !== "failed") return result;
  const generatedUrl = await requestGeneration(text, lang, voice);
  if (generatedUrl) {
    result = await playClipToEnd(generatedUrl);
    if (result !== "failed") return result;
  }
  return speakOnDeviceToEnd(text, lang);
}

/**
 * Reads `chunks` aloud one after another (see speechChunks), with the
 * same cached cloud voice speak() uses and the same device-voice
 * fallback. Calls onChunk(i) as each chunk starts and onChunk(null) when
 * it finishes. Any later speak(), readAloud(), stopReadAloud() or
 * stopSpeaking() call stops it.
 */
export function readAloud(chunks: string[], requestedLang: SpeechLang, onChunk: (index: number | null) => void): void {
  stopReadAloud();
  currentPlayer?.remove();
  currentPlayer = null;
  Speech.stop();
  const run = readAloudRun;
  void (async () => {
    await Promise.all([loadPronunciationPrefs(), loadSpanishVariety()]);
    if (run !== readAloudRun) return;
    if (!pronunciationEnabled) {
      onChunk(null);
      return;
    }
    const lang = voiceLang(requestedLang);
    for (let i = 0; i < chunks.length; i++) {
      if (run !== readAloudRun) return;
      onChunk(i);
      if (i + 1 < chunks.length) warmClip(chunks[i + 1], lang, preferredVoice);
      const result = await playChunk(chunks[i], lang, run);
      if (result === "stopped" || run !== readAloudRun) return;
    }
    onChunk(null);
  })();
}
