// Synced from cheneygross-afk/lengo:src/lib/stories/fr/batches/fr-a2-s01.ts by scripts/sync-content.mjs -- edit it there, not here.
import type { Story, StoryGloss } from "../../types";

// FR-A2 stories, batch 1 (see ../fr-a1.ts for the conventions).

export const FR_A2_S01_STORIES: Story[] = [
  {
    slug: "fr-a2-le-portefeuille-oublie",
    level: "FR-A2",
    title: `Le portefeuille oublié`,
    subtitle: `After a great dinner in a Lyon bouchon, Julien realizes he has left his wallet at home.`,
    paragraphs: [
      `Vendredi dernier, Julien a invité son amie Sarah au restaurant. Ils sont allés dans un bouchon, un petit restaurant traditionnel du vieux Lyon. La salle était petite et chaleureuse, avec des nappes à carreaux rouges et blancs.`,
      `Ils ont très bien mangé : une salade lyonnaise, des quenelles et une tarte aux pralines. Le patron, un homme grand avec une moustache blanche, racontait des histoires sur le quartier. Sarah riait beaucoup. C'était une soirée parfaite.`,
      `Puis le patron a apporté l'addition. Julien a mis la main dans sa poche... rien. Il a cherché dans sa veste, dans son sac... toujours rien. Il a oublié son portefeuille chez lui ! Il est devenu tout rouge. Sarah n'avait pas sa carte bancaire non plus.`,
      `Julien a expliqué la situation au patron. Il avait très honte. Le patron l'a regardé un moment, puis il a souri. « Ce n'est pas grave, jeune homme. Vous allez revenir demain. Je vous fais confiance. »`,
      `Le lendemain matin, Julien est revenu avec l'argent et un beau bouquet de fleurs pour le patron. Le patron a ri. « Des fleurs ? C'est la première fois ! Revenez quand vous voulez. » Depuis, Julien et Sarah dînent là-bas tous les mois.`,
    ],
    questions: [
      {
        question: `What is a "bouchon" in this story?`,
        options: [`A bottle of wine`, `A small traditional restaurant in Lyon`, `A kind of cake`, `A street in old Lyon`],
        correctIndex: 1,
        explanation: `The story says "un bouchon, un petit restaurant traditionnel du vieux Lyon".`,
      },
      {
        question: `What was the problem at the end of the meal?`,
        options: [`The food was cold.`, `Sarah was sick.`, `Julien had forgotten his wallet.`, `The restaurant was closing.`],
        correctIndex: 2,
        explanation: `"Il a oublié son portefeuille chez lui !"`,
      },
      {
        question: `How did the owner react?`,
        options: [`He called the police.`, `He trusted Julien to come back the next day.`, `He asked Sarah to pay.`, `He got angry.`],
        correctIndex: 1,
        explanation: `He said "Vous allez revenir demain. Je vous fais confiance."`,
      },
      {
        question: `What did Julien bring the next morning?`,
        options: [`The money and some flowers`, `Only the money`, `A bottle of wine`, `A cake`],
        correctIndex: 0,
        explanation: `"Julien est revenu avec l'argent et un beau bouquet de fleurs."`,
      },
    ],
  },
  {
    slug: "fr-a2-quand-j-etais-petit",
    level: "FR-A2",
    title: `Quand j'étais petit`,
    subtitle: `Grandpa Robert tells his granddaughter about his childhood on a farm in Normandy in the 1950s.`,
    paragraphs: [
      `« Papi, comment c'était, quand tu étais petit ? » demande Lucie. Son grand-père, Robert, pose son journal et sourit.`,
      `« Quand j'étais petit, j'habitais dans une ferme en Normandie, près de Bayeux. Nous n'avions pas de télévision et pas de voiture. Mon père avait des vaches et des pommiers. Ma mère faisait du beurre et du fromage. »`,
      `« Tous les matins, je me levais à six heures pour aider mon père. Je donnais à manger aux poules et je ramassais les œufs. Ensuite, j'allais à l'école à pied. C'était à trois kilomètres ! L'hiver, il faisait froid et il pleuvait souvent. »`,
      `« À l'école, nous étions vingt élèves dans une seule classe. Le maître était sévère, mais juste. J'aimais beaucoup la géographie. Je rêvais de voyager dans le monde entier. »`,
      `« Et tu as voyagé ? » demande Lucie. Robert rit. « Un peu. Je suis allé à Paris une fois, en 1962. J'ai trouvé la ville trop grande et trop bruyante ! Je suis rentré en Normandie et je ne suis jamais reparti. » Lucie réfléchit. « Moi, je vais voyager partout. Et je vais t'envoyer des cartes postales ! »`,
    ],
    questions: [
      {
        question: `Where did Robert live as a child?`,
        options: [`In Paris`, `On a farm in Normandy`, `In a big town`, `By the sea in Brittany`],
        correctIndex: 1,
        explanation: `"J'habitais dans une ferme en Normandie, près de Bayeux."`,
      },
      {
        question: `What did Robert do every morning before school?`,
        options: [`He watched television.`, `He made butter.`, `He fed the hens and collected the eggs.`, `He drove the car.`],
        correctIndex: 2,
        explanation: `"Je donnais à manger aux poules et je ramassais les œufs."`,
      },
      {
        question: `What did Robert think of Paris?`,
        options: [`Too big and too noisy`, `Beautiful and calm`, `Cheap`, `He never went there.`],
        correctIndex: 0,
        explanation: `"J'ai trouvé la ville trop grande et trop bruyante !"`,
      },
      {
        question: `What does Lucie promise at the end?`,
        options: [`To live on a farm`, `To visit Bayeux`, `To become a teacher`, `To travel everywhere and send him postcards`],
        correctIndex: 3,
        explanation: `"Je vais voyager partout. Et je vais t'envoyer des cartes postales !"`,
      },
    ],
  },
  {
    slug: "fr-a2-le-pneu-creve",
    level: "FR-A2",
    title: `Le pneu crevé`,
    subtitle: `On a hot summer day in Provence, a couple gets a flat tire on a small country road.`,
    paragraphs: [
      `En juillet, Clara et son mari, Benoît, ont loué une voiture pour visiter la Provence. Un après-midi, ils roulaient sur une petite route entre deux villages. Il faisait trente-cinq degrés et les champs de lavande étaient magnifiques.`,
      `Soudain, ils ont entendu un grand bruit. La voiture s'est arrêtée au bord de la route. Benoît est sorti et il a regardé : le pneu avant était crevé. « Pas de problème, il y a une roue de secours », a-t-il dit. Mais dans le coffre, il n'y avait pas de cric.`,
      `Clara a pris son téléphone. Pas de réseau ! Il n'y avait personne sur la route, seulement des cigales qui chantaient très fort. Ils ont attendu sous un arbre pendant une demi-heure.`,
      `Enfin, un vieux tracteur est arrivé. Le conducteur, un agriculteur aux cheveux blancs, s'est arrêté. « Vous avez un souci ? » Il avait tous les outils nécessaires. En dix minutes, il a changé la roue.`,
      `Benoît voulait lui donner de l'argent, mais l'agriculteur a refusé. « Venez plutôt boire un verre à la ferme. » Ils ont passé la soirée avec lui et sa femme, sous les platanes. Ils ont mangé du melon et des olives. Clara a dit plus tard : « C'était le meilleur moment des vacances. »`,
    ],
    questions: [
      {
        question: `What was missing in the car?`,
        options: [`A jack`, `A spare wheel`, `A map`, `Water`],
        correctIndex: 0,
        explanation: `"Il y a une roue de secours", but "il n'y avait pas de cric": there was no jack.`,
      },
      {
        question: `Why couldn't Clara call for help?`,
        options: [`Her phone had no battery.`, `There was no network.`, `She didn't know the number.`, `She lost her phone.`],
        correctIndex: 1,
        explanation: `"Clara a pris son téléphone. Pas de réseau !"`,
      },
      {
        question: `What did the farmer ask for in return?`,
        options: [`Money`, `Help on the farm`, `A lift to the village`, `Nothing; he invited them for a drink`],
        correctIndex: 3,
        explanation: `He refused the money and said "Venez plutôt boire un verre à la ferme."`,
      },
    ],
  },
  {
    slug: "fr-a2-le-gateau-rate",
    level: "FR-A2",
    title: `Le gâteau raté`,
    subtitle: `Antoine wanted to make the perfect birthday cake for his mother. Nothing went as planned.`,
    paragraphs: [
      `Dimanche dernier, c'était l'anniversaire de la mère d'Antoine. Antoine a seize ans et il ne cuisine jamais. Mais cette année, il voulait faire une surprise : un gâteau au chocolat, fait maison.`,
      `Le samedi soir, il a cherché une recette sur Internet. Elle avait l'air facile. Le dimanche matin, pendant que sa mère faisait les courses, il a commencé. Il a fait fondre le chocolat avec le beurre, il a ajouté le sucre, les œufs et la farine.`,
      `Malheureusement, il n'a pas bien lu la recette. Il a mis deux cents grammes de sel à la place du sucre ! Ensuite, il a oublié le gâteau dans le four pendant une heure, au lieu de vingt-cinq minutes, parce qu'il jouait aux jeux vidéo.`,
      `Quand il a ouvert le four, une fumée noire est sortie. Le gâteau était dur comme une pierre. À ce moment-là, sa mère est rentrée. « Qu'est-ce qui se passe ici ? Ça sent le brûlé ! »`,
      `Antoine a tout expliqué. Il était très déçu. Sa mère a regardé le gâteau, puis son fils, et elle a éclaté de rire. « C'est le plus beau cadeau du monde. » L'après-midi, ils sont allés ensemble à la pâtisserie. Et le soir, Antoine a promis : « L'année prochaine, je vais prendre des cours de cuisine ! »`,
    ],
    questions: [
      {
        question: `What mistake did Antoine make with the ingredients?`,
        options: [`He forgot the eggs.`, `He used salt instead of sugar.`, `He used too much chocolate.`, `He forgot the flour.`],
        correctIndex: 1,
        explanation: `"Il a mis deux cents grammes de sel à la place du sucre !"`,
      },
      {
        question: `Why did he leave the cake in the oven for too long?`,
        options: [`He was playing video games.`, `He fell asleep.`, `He went shopping.`, `The recipe said one hour.`],
        correctIndex: 0,
        explanation: `"Il a oublié le gâteau dans le four... parce qu'il jouait aux jeux vidéo."`,
      },
      {
        question: `How did his mother react?`,
        options: [`She was angry.`, `She cried.`, `She burst out laughing.`, `She threw the cake away without a word.`],
        correctIndex: 2,
        explanation: `"Elle a éclaté de rire": she burst out laughing.`,
      },
      {
        question: `What is Antoine going to do next year?`,
        options: [`Buy a cake`, `Take cooking classes`, `Forget the birthday`, `Make the same cake`],
        correctIndex: 1,
        explanation: `"L'année prochaine, je vais prendre des cours de cuisine !"`,
      },
    ],
  },
  {
    slug: "fr-a2-l-entretien-d-embauche",
    level: "FR-A2",
    title: `L'entretien d'embauche`,
    subtitle: `Yasmine had a job interview at a bookshop in Toulouse. The morning started badly.`,
    paragraphs: [
      `Yasmine cherchait du travail depuis trois mois. Un lundi, elle a reçu un mail : une grande librairie de Toulouse voulait la rencontrer pour un poste de vendeuse. L'entretien était le jeudi suivant, à dix heures.`,
      `Le jeudi matin, Yasmine était très nerveuse. Elle a mis sa plus belle chemise blanche et elle a pris un café dans un bar près de la librairie. Mais quand elle s'est levée, elle a renversé sa tasse. Une grosse tache marron est apparue sur sa chemise !`,
      `Elle n'avait pas le temps de rentrer chez elle. Elle a acheté un foulard dans une boutique et elle l'a mis autour de son cou pour cacher la tache. Elle est arrivée à la librairie à dix heures pile.`,
      `La directrice, Madame Fabre, lui a posé beaucoup de questions. Yasmine a parlé de ses livres préférés, de son expérience dans un supermarché et de ses idées pour les enfants. Puis Madame Fabre a dit : « Votre foulard est très joli. » Yasmine a rougi et elle a raconté l'histoire du café.`,
      `Madame Fabre a ri. « Vous savez garder votre calme et trouver des solutions. C'est exactement ce que je cherche. » Une semaine plus tard, Yasmine a commencé son nouveau travail. Elle porte souvent le foulard. C'est son porte-bonheur.`,
    ],
    questions: [
      {
        question: `What job did Yasmine apply for?`,
        options: [`Waitress in a bar`, `Sales assistant in a bookshop`, `Teacher`, `Cashier in a supermarket`],
        correctIndex: 1,
        explanation: `The bookshop wanted to meet her "pour un poste de vendeuse".`,
      },
      {
        question: `What happened in the café?`,
        options: [`She spilled her coffee on her shirt.`, `She lost her bag.`, `She met the director.`, `She forgot the time.`],
        correctIndex: 0,
        explanation: `"Elle a renversé sa tasse. Une grosse tache marron est apparue sur sa chemise !"`,
      },
      {
        question: `Why did Madame Fabre like Yasmine?`,
        options: [`Because of her shirt`, `Because she loves coffee`, `Because she stays calm and finds solutions`, `Because she knows her family`],
        correctIndex: 2,
        explanation: `"Vous savez garder votre calme et trouver des solutions."`,
      },
      {
        question: `What is the scarf for Yasmine now?`,
        options: [`A present for her mother`, `Her lucky charm`, `Part of her uniform`, `Something she wants to sell`],
        correctIndex: 1,
        explanation: `"C'est son porte-bonheur": her lucky charm.`,
      },
    ],
  },
];

export const FR_A2_S01_ENGLISH: Record<string, string[]> = {
  "fr-a2-le-portefeuille-oublie": [
    `Last Friday, Julien took his friend Sarah out to a restaurant. They went to a bouchon, a small traditional restaurant in old Lyon. The dining room was small and cozy, with red and white checked tablecloths.`,
    `They ate very well: a Lyon salad, quenelles and a praline tart. The owner, a tall man with a white mustache, told stories about the neighborhood. Sarah laughed a lot. It was a perfect evening.`,
    `Then the owner brought the bill. Julien put his hand in his pocket... nothing. He looked in his jacket, in his bag... still nothing. He had forgotten his wallet at home! He went bright red. Sarah didn't have her bank card either.`,
    `Julien explained the situation to the owner. He was very ashamed. The owner looked at him for a moment, then he smiled. "It doesn't matter, young man. You'll come back tomorrow. I trust you."`,
    `The next morning, Julien came back with the money and a beautiful bunch of flowers for the owner. The owner laughed. "Flowers? That's a first! Come back whenever you like." Since then, Julien and Sarah have had dinner there every month.`,
  ],
  "fr-a2-quand-j-etais-petit": [
    `"Grandpa, what was it like when you were little?" asks Lucie. Her grandfather, Robert, puts down his newspaper and smiles.`,
    `"When I was little, I lived on a farm in Normandy, near Bayeux. We didn't have a television or a car. My father had cows and apple trees. My mother made butter and cheese."`,
    `"Every morning, I got up at six o'clock to help my father. I fed the hens and collected the eggs. Then I walked to school. It was three kilometers away! In winter, it was cold and it often rained."`,
    `"At school, there were twenty of us pupils in a single class. The teacher was strict, but fair. I really liked geography. I dreamed of traveling all over the world."`,
    `"And did you travel?" asks Lucie. Robert laughs. "A little. I went to Paris once, in 1962. I found the city too big and too noisy! I came back to Normandy and I never left again." Lucie thinks. "I'm going to travel everywhere. And I'm going to send you postcards!"`,
  ],
  "fr-a2-le-pneu-creve": [
    `In July, Clara and her husband, Benoît, rented a car to visit Provence. One afternoon, they were driving on a small road between two villages. It was thirty-five degrees and the lavender fields were magnificent.`,
    `Suddenly, they heard a loud noise. The car stopped at the side of the road. Benoît got out and looked: the front tire was flat. "No problem, there's a spare wheel," he said. But in the trunk, there was no jack.`,
    `Clara took out her phone. No signal! There was nobody on the road, only cicadas singing very loudly. They waited under a tree for half an hour.`,
    `At last, an old tractor arrived. The driver, a white-haired farmer, stopped. "Got a problem?" He had all the tools they needed. In ten minutes, he changed the wheel.`,
    `Benoît wanted to give him some money, but the farmer refused. "Come and have a drink at the farm instead." They spent the evening with him and his wife, under the plane trees. They ate melon and olives. Clara said later: "It was the best moment of the holiday."`,
  ],
  "fr-a2-le-gateau-rate": [
    `Last Sunday was Antoine's mother's birthday. Antoine is sixteen and he never cooks. But this year, he wanted to give her a surprise: a homemade chocolate cake.`,
    `On Saturday evening, he looked for a recipe online. It looked easy. On Sunday morning, while his mother was doing the shopping, he started. He melted the chocolate with the butter, he added the sugar, the eggs and the flour.`,
    `Unfortunately, he didn't read the recipe properly. He put in two hundred grams of salt instead of sugar! Then he forgot the cake in the oven for an hour instead of twenty-five minutes, because he was playing video games.`,
    `When he opened the oven, black smoke came out. The cake was as hard as a stone. At that moment, his mother came home. "What's going on here? It smells burnt!"`,
    `Antoine explained everything. He was very disappointed. His mother looked at the cake, then at her son, and she burst out laughing. "It's the most beautiful present in the world." In the afternoon, they went to the pastry shop together. And in the evening, Antoine promised: "Next year, I'm going to take cooking classes!"`,
  ],
  "fr-a2-l-entretien-d-embauche": [
    `Yasmine had been looking for work for three months. One Monday, she received an email: a big bookshop in Toulouse wanted to meet her for a sales assistant job. The interview was the following Thursday, at ten o'clock.`,
    `On Thursday morning, Yasmine was very nervous. She put on her nicest white shirt and had a coffee in a café near the bookshop. But when she stood up, she knocked over her cup. A big brown stain appeared on her shirt!`,
    `She didn't have time to go home. She bought a scarf in a shop and put it around her neck to hide the stain. She arrived at the bookshop at ten o'clock on the dot.`,
    `The manager, Madame Fabre, asked her lots of questions. Yasmine talked about her favorite books, her experience in a supermarket and her ideas for children. Then Madame Fabre said: "Your scarf is very pretty." Yasmine blushed and told her the story of the coffee.`,
    `Madame Fabre laughed. "You know how to stay calm and find solutions. That's exactly what I'm looking for." A week later, Yasmine started her new job. She often wears the scarf. It's her lucky charm.`,
  ],
};

export const FR_A2_S01_GLOSSES: Record<string, StoryGloss[]> = {
  "fr-a2-le-portefeuille-oublie": [
    { es: "le portefeuille", en: "wallet", forms: ["portefeuille"] },
    { es: "chaleureux, chaleureuse", en: "warm, cozy", forms: ["chaleureuse"] },
    { es: "la nappe", en: "tablecloth", forms: ["nappes"] },
    { es: "à carreaux", en: "checked", forms: ["carreaux"] },
    { es: "le patron", en: "owner, boss", forms: ["patron"] },
    { es: "l'addition", en: "the bill, the check", forms: ["l'addition"] },
    { es: "la poche", en: "pocket", forms: ["poche"] },
    { es: "avoir honte", en: "to be ashamed", forms: ["honte"] },
    { es: "faire confiance à", en: "to trust", forms: ["confiance"] },
    { es: "le lendemain", en: "the next day", forms: ["lendemain"] },
  ],
  "fr-a2-quand-j-etais-petit": [
    { es: "la ferme", en: "farm", forms: ["ferme"] },
    { es: "la vache", en: "cow", forms: ["vaches"] },
    { es: "le pommier", en: "apple tree", forms: ["pommiers"] },
    { es: "la poule", en: "hen", forms: ["poules"] },
    { es: "ramasser", en: "to pick up, to collect", forms: ["ramassais"] },
    { es: "l'élève", en: "pupil, student", forms: ["élèves"] },
    { es: "le maître", en: "(primary school) teacher", forms: ["maître"] },
    { es: "sévère", en: "strict", forms: ["sévère"] },
    { es: "juste", en: "fair", forms: ["juste"] },
    { es: "rêver de", en: "to dream of", forms: ["rêvais"] },
    { es: "repartir", en: "to leave again", forms: ["reparti"] },
  ],
  "fr-a2-le-pneu-creve": [
    { es: "le pneu", en: "tire", forms: ["pneu"] },
    { es: "crevé, crevée", en: "flat, punctured", forms: ["crevé"] },
    { es: "rouler", en: "to drive (along)", forms: ["roulaient"] },
    { es: "le champ", en: "field", forms: ["champs"] },
    { es: "la roue de secours", en: "spare wheel", forms: ["roue", "secours"] },
    { es: "le coffre", en: "trunk (of a car)", forms: ["coffre"] },
    { es: "le cric", en: "jack (for a car)", forms: ["cric"] },
    { es: "le réseau", en: "network, phone signal", forms: ["réseau"] },
    { es: "la cigale", en: "cicada", forms: ["cigales"] },
    { es: "un agriculteur", en: "farmer", forms: ["agriculteur"] },
    { es: "un souci", en: "a problem, a worry", forms: ["souci"] },
    { es: "le platane", en: "plane tree", forms: ["platanes"] },
  ],
  "fr-a2-le-gateau-rate": [
    { es: "fait maison", en: "homemade", forms: ["maison"] },
    { es: "la recette", en: "recipe", forms: ["recette"] },
    { es: "faire fondre", en: "to melt", forms: ["fondre"] },
    { es: "malheureusement", en: "unfortunately", forms: ["malheureusement"] },
    { es: "à la place de", en: "instead of", forms: ["place"] },
    { es: "au lieu de", en: "instead of", forms: ["lieu"] },
    { es: "la fumée", en: "smoke", forms: ["fumée"] },
    { es: "le brûlé", en: "burning (ça sent le brûlé: it smells burnt)", forms: ["brûlé"] },
    { es: "déçu, déçue", en: "disappointed", forms: ["déçu"] },
    { es: "éclater de rire", en: "to burst out laughing", forms: ["éclaté"] },
  ],
  "fr-a2-l-entretien-d-embauche": [
    { es: "un entretien d'embauche", en: "job interview", forms: ["l'entretien"] },
    { es: "le poste", en: "job, position", forms: ["poste"] },
    { es: "le vendeur, la vendeuse", en: "sales assistant", forms: ["vendeuse"] },
    { es: "renverser", en: "to knock over, to spill", forms: ["renversé"] },
    { es: "la tache", en: "stain", forms: ["tache"] },
    { es: "le foulard", en: "scarf", forms: ["foulard"] },
    { es: "cacher", en: "to hide", forms: ["cacher"] },
    { es: "pile", en: "exactly, on the dot (time)", forms: ["pile"] },
    { es: "rougir", en: "to blush", forms: ["rougi"] },
    { es: "le porte-bonheur", en: "lucky charm", forms: ["porte-bonheur"] },
  ],
};
