// Synced from cheneygross-afk/lengo:src/lib/stories/fr/batches/fr-b2-s03.ts by scripts/sync-content.mjs -- edit it there, not here.
import type { Story, StoryGloss } from "../../types";

// FR-B2 stories, batch 3 (see ../fr-a1.ts for the conventions).

export const FR_B2_S03_STORIES: Story[] = [
  {
    slug: "fr-la-famille-sans-voiture",
    level: "FR-B2",
    title: `La famille sans voiture`,
    subtitle: `When their old car dies on the motorway, a Strasbourg father talks his family into living for a year with a cargo bike instead.`,
    paragraphs: [
      `Le jour où la vieille Clio des Muller a rendu l'âme sur l'autoroute, entre Strasbourg et Colmar, dans un nuage de fumée noire, Pierre a pris une décision qui allait bouleverser la vie de toute la famille. Plutôt que d'acheter une nouvelle voiture, ils allaient essayer de vivre sans. Pendant un an. « Strasbourg est la capitale française du vélo, a-t-il déclaré au dîner. Si on n'y arrive pas ici, on n'y arrivera nulle part. » Sa femme, Aurélie, a levé un sourcil. Leurs trois enfants ont levé les yeux au ciel.`,
      `Pierre, qui n'était pas monté sur un vélo depuis son adolescence, s'est lancé dans le projet avec l'enthousiasme d'un converti. Il a passé des soirées entières sur des forums spécialisés, a comparé des dizaines de modèles et a fini par acheter, grâce à une aide de la métropole, un vélo-cargo électrique à l'avant duquel trônait une grande caisse en bois capable de transporter deux enfants, les courses de la semaine et, selon le vendeur, « un petit réfrigérateur ».`,
      `Les premières semaines ont été épiques. Pierre a découvert que le vélo-cargo, une fois chargé, pesait plus lourd qu'un cheval et tournait à peu près aussi bien qu'un camion. Il a renversé un étal de marché place Broglie, il a coincé sa roue avant dans un rail de tram et il s'est fait doubler par un retraité de quatre-vingts ans sur un vélo hollandais. Le jour où la batterie l'a lâché en pleine côte, il a dû pousser l'engin, ses deux plus jeunes enfants et six packs d'eau sous les regards amusés des automobilistes.`,
      `Aurélie, quant à elle, a pris le tram et un vélo d'occasion, sans faire d'histoires. Les enfants se sont adaptés plus vite que leurs parents. Jules, quatorze ans, qui avait juré qu'on ne le verrait jamais dans « la brouette de papa », a découvert qu'il pouvait aller seul au collège à vélo et il y a gagné une liberté inattendue. Les jumelles, elles, adoraient trôner dans la caisse en saluant les passants comme des reines dans un carrosse.`,
      `Il y a eu des moments plus difficiles. En février, sous une pluie glaciale, rien n'est moins romantique que de pédaler quarante minutes jusqu'à un rendez-vous chez l'orthodontiste. Et lorsque la grand-mère d'Aurélie, qui habitait un village des Vosges mal desservi, est tombée malade, ils ont dû louer une voiture plusieurs week-ends de suite. Pierre a dû reconnaître, à contrecœur, que tout le monde ne pouvait pas vivre sans voiture, et que la question dépendait beaucoup de l'endroit où l'on habitait.`,
      `Au bout de l'année, Aurélie a fait les comptes. Entre l'assurance, le carburant, l'entretien et le parking qu'ils ne payaient plus, ils avaient économisé plus de quatre mille euros, même en comptant les locations. Pierre avait perdu sept kilos. Personne dans la famille n'avait été malade de l'hiver. Il ne restait plus qu'à voter : allait-on racheter une voiture, oui ou non ?`,
      `Le vote a eu lieu à main levée, autour de la table de la cuisine. Pierre, qui s'attendait à une révolte, avait préparé un long argumentaire. Il n'en a pas eu besoin : les cinq mains sont restées baissées. Seule Aurélie a ajouté une condition, avec un sourire en coin : « On garde le vélo-cargo. Mais à partir de maintenant, c'est moi qui conduis. »`,
    ],
    questions: [
      {
        question: `What made Pierre decide to try living without a car?`,
        options: [`A doctor's advice`, `A city ban on cars`, `A bet with his son`, `Their old car broke down for good on the motorway`],
        correctIndex: 3,
        explanation: `"Le jour où la vieille Clio des Muller a rendu l'âme sur l'autoroute... Pierre a pris une décision."`,
      },
      {
        question: `Which of these mishaps happened to Pierre in the first weeks?`,
        options: [`He was overtaken by an eighty-year-old on a Dutch bike.`, `He lost one of the twins.`, `He crashed into a tram.`, `His bike was stolen.`],
        correctIndex: 0,
        explanation: `"Il s'est fait doubler par un retraité de quatre-vingts ans sur un vélo hollandais."`,
      },
      {
        question: `What did Pierre have to admit, reluctantly?`,
        options: [`That the cargo bike was a mistake`, `That not everyone can live without a car, depending on where they live`, `That Aurélie was a better cyclist`, `That the experiment cost more than a car`],
        correctIndex: 1,
        explanation: `"Pierre a dû reconnaître, à contrecœur, que tout le monde ne pouvait pas vivre sans voiture, et que la question dépendait beaucoup de l'endroit où l'on habitait."`,
      },
      {
        question: `What was the result of the family vote?`,
        options: [`They bought an electric car.`, `They rented a car permanently.`, `Nobody wanted a car again.`, `Only Jules voted for a car.`],
        correctIndex: 2,
        explanation: `"Les cinq mains sont restées baissées."`,
      },
    ],
  },
  {
    slug: "fr-desactive",
    level: "FR-B2",
    title: `Désactivé`,
    subtitle: `A top-rated food delivery rider in Montpellier is suddenly cut off by the app he works for, with no explanation and no one to call.`,
    paragraphs: [
      `Le message est arrivé un mardi soir, à 21 h 47, alors que Yacine attendait une commande de sushis devant un restaurant de l'Écusson, le vieux centre de Montpellier. Une notification sobre, presque polie : « Suite à un examen de votre activité, votre compte a été désactivé. Cette décision est définitive. » Pas de nom, pas de signature, pas d'explication. Il a relu la phrase trois fois, puis il a regardé son vélo, son sac isotherme, ses mains. En une seconde, il venait de perdre son seul revenu.`,
      `Yacine avait vingt-quatre ans et livrait des repas depuis deux ans pour la même plateforme. Officiellement, il était auto-entrepreneur, libre d'organiser son temps comme il le souhaitait. En pratique, c'était l'application qui décidait de tout : quelles commandes il recevait, combien elles étaient payées, à quelle vitesse il devait pédaler. Les livreurs les mieux notés avaient accès aux meilleurs créneaux ; les autres se contentaient des miettes. Yacine faisait partie des meilleurs. Il travaillait cinquante heures par semaine, sous la pluie comme en pleine canicule.`,
      `Il a d'abord essayé de comprendre. Dans l'application, il n'y avait aucun numéro de téléphone, seulement un assistant automatique qui répondait invariablement : « Je comprends votre frustration. Pour toute question relative à votre compte, consultez notre foire aux questions. » Il a envoyé des courriels, puis une lettre recommandée au siège de la société, à Paris. Personne ne lui a jamais répondu. C'était comme se disputer avec un mur, sauf qu'un mur, au moins, ne vous souhaite pas une excellente journée.`,
      `Ce sont les autres livreurs qui l'ont aidé. Sur le groupe de discussion qu'ils partageaient, son message a suscité des dizaines de réponses. Beaucoup avaient vécu la même chose ou connaissaient quelqu'un à qui c'était arrivé. Une étudiante en droit, qui livrait le week-end pour payer ses études, a proposé de l'aider. En reconstituant ses dernières courses, ils ont fini par trouver une explication probable : trois jours plus tôt, un client avait signalé qu'il n'avait jamais reçu sa commande, alors que Yacine avait une photo prouvant qu'il l'avait déposée devant la bonne porte.`,
      `Le samedi suivant, une centaine de livreurs se sont rassemblés devant les locaux régionaux de la plateforme, un bureau anonyme dans une zone d'activités, dont la porte est restée close. Ils n'ont pas crié, ils n'ont rien cassé. Ils ont simplement garé leurs vélos en rang, sacs ouverts, et déployé une banderole : « Un algorithme ne peut pas nous licencier sans nous regarder dans les yeux ». Un journaliste de la presse locale est venu, puis une équipe de télévision. Le reportage a été diffusé le soir même.`,
      `Le lundi matin, Yacine a reçu un nouveau message, aussi impersonnel que le premier : « Après un nouvel examen, votre compte a été réactivé. Nous vous prions de nous excuser pour la gêne occasionnée. » Il ne savait pas s'il devait rire ou pleurer. Personne ne lui expliquait ce qui s'était passé, ni pourquoi on lui donnait soudain raison. Il soupçonnait que ce n'était pas la photo qui avait convaincu la société, mais la caméra de télévision.`,
      `Il ne s'est pas reconnecté. Avec six autres livreurs et l'étudiante en droit, il a fondé quelques mois plus tard une petite coopérative de livraison à vélo, où chacun est salarié et où les décisions sont prises en assemblée, autour d'une table, entre êtres humains. Ils gagnent un peu moins, travaillent un peu moins aussi, et livrent surtout pour les commerces du quartier. Sur la porte du local, Yacine a punaisé une feuille sur laquelle il a écrit à la main : « Ici, on répond au téléphone. »`,
    ],
    questions: [
      {
        question: `What does the story say about Yacine's "independence" as a self-employed rider?`,
        options: [`He could choose his own prices.`, `In practice, the app decided everything.`, `He worked only when he wanted.`, `He had a manager he could call.`],
        correctIndex: 1,
        explanation: `"Officiellement, il était auto-entrepreneur... En pratique, c'était l'application qui décidait de tout."`,
      },
      {
        question: `What was the probable reason for the deactivation?`,
        options: [`He had been too slow.`, `He had refused too many orders.`, `He had been rude to a restaurant.`, `A customer falsely reported an order as not delivered.`],
        correctIndex: 3,
        explanation: `"Un client avait signalé qu'il n'avait jamais reçu sa commande, alors que Yacine avait une photo prouvant qu'il l'avait déposée."`,
      },
      {
        question: `What does Yacine suspect made the company reactivate his account?`,
        options: [`The television coverage`, `His registered letter`, `The photo of the delivery`, `A court decision`],
        correctIndex: 0,
        explanation: `"Il soupçonnait que ce n'était pas la photo qui avait convaincu la société, mais la caméra de télévision."`,
      },
      {
        question: `What does the sign on the cooperative's door suggest?`,
        options: [`That they deliver only by phone order`, `That they are always open`, `That, unlike the platform, real people answer`, `That they are looking for new riders`],
        correctIndex: 2,
        explanation: `"Ici, on répond au téléphone": a contrast with the platform, where "il n'y avait aucun numéro de téléphone".`,
      },
    ],
  },
  {
    slug: "fr-l-affaire-du-platane",
    level: "FR-B2",
    title: `L'affaire du platane`,
    subtitle: `A plan to cut down a century-old plane tree for a new cycle lane sets a Nantes neighbourhood at war with itself.`,
    paragraphs: [
      `Personne, dans le quartier, n'avait jamais vraiment prêté attention au grand platane qui se dressait au carrefour de la rue des Cordiers, à Nantes. Il était là depuis cent vingt ans, il faisait de l'ombre l'été, perdait ses feuilles l'automne et servait de point de rendez-vous aux adolescents. Puis, un matin de mars, une affiche municipale est apparue sur son tronc : dans le cadre de l'aménagement d'une nouvelle piste cyclable, l'arbre serait abattu le 15 avril.`,
      `En quarante-huit heures, le platane est devenu la personnalité la plus célèbre du quartier. Une pétition en ligne a recueilli quatre mille signatures. Des enfants ont accroché des dessins à son écorce. Quelqu'un lui a même ouvert un compte sur les réseaux sociaux, où il s'exprimait à la première personne : « J'ai vu passer deux guerres et trois tramways. Je ne me laisserai pas abattre par une piste cyclable. » Le conseil de quartier, qui réunissait d'habitude une douzaine de retraités, a dû organiser une séance extraordinaire dans le gymnase.`,
      `La réunion a commencé dans le calme et a vite dégénéré. D'un côté, l'association des cyclistes, qui réclamait cette piste depuis dix ans et rappelait qu'un enfant avait été renversé au carrefour l'hiver précédent. De l'autre, les défenseurs de l'arbre, qui accusaient la mairie de « massacrer la nature au nom de l'écologie ». Entre les deux, les commerçants, qui ne voulaient surtout pas qu'on touche aux places de stationnement, et un monsieur qui était venu se plaindre des pigeons et qui ne comprenait pas pourquoi personne ne l'écoutait.`,
      `Chacun citait des études. Une botaniste à la retraite a expliqué qu'un platane centenaire stockait chaque année des centaines de kilos de carbone et rafraîchissait la rue de plusieurs degrés en été. Le président de l'association cycliste a répliqué que la piste permettrait d'éviter des milliers de trajets en voiture. L'adjointe au maire, qui avait apporté un diaporama de soixante pages, s'est vu reprocher successivement de mépriser les arbres, les cyclistes, les commerçants et les pigeons.`,
      `Vers vingt-trois heures, alors que tout le monde criait en même temps, une petite fille de neuf ans, venue avec son père, a levé la main. Comme personne ne la voyait, elle est montée sur une chaise. « Pourquoi on ne fait pas passer la piste de l'autre côté de la rue ? Là où il y a les voitures garées ? » Il y a eu un silence. L'adjointe a feuilleté son diaporama. La solution n'y figurait pas, pour la simple raison qu'elle supposait de supprimer quatorze places de stationnement, ce qu'aucun élu n'avait osé proposer.`,
      `Il a fallu encore deux réunions, une concertation avec les commerçants et la promesse d'un parking pour vélos-cargos devant la boulangerie, mais le projet a finalement été modifié. La piste passe désormais de l'autre côté. Les commerçants, qui prédisaient leur faillite, ont constaté avec étonnement que les cyclistes s'arrêtaient plus volontiers devant leurs vitrines que les automobilistes. Le monsieur aux pigeons, lui, continue de venir à chaque conseil de quartier.`,
      `Quant au platane, il a survécu. Au printemps suivant, la mairie a fixé sur son tronc une petite plaque en laiton : « Arbre sauvé par la concertation citoyenne ». Les habitants trouvent que c'est un peu exagéré. La petite fille, elle, passe devant tous les matins sur son vélo, en empruntant la nouvelle piste, et elle ne manque jamais de saluer l'arbre d'un geste de la main, comme on salue un vieil ami qu'on a aidé à se tirer d'un mauvais pas.`,
    ],
    questions: [
      {
        question: `Why was the plane tree going to be cut down?`,
        options: [`It was diseased.`, `It was in the way of a new cycle lane.`, `Its roots were damaging houses.`, `Shopkeepers complained about its leaves.`],
        correctIndex: 1,
        explanation: `"Dans le cadre de l'aménagement d'une nouvelle piste cyclable, l'arbre serait abattu le 15 avril."`,
      },
      {
        question: `What did the tree's defenders accuse the town hall of?`,
        options: [`Destroying nature in the name of ecology`, `Wasting public money`, `Ignoring the cyclists`, `Favouring the shopkeepers`],
        correctIndex: 0,
        explanation: `They accused the town hall of "massacrer la nature au nom de l'écologie".`,
      },
      {
        question: `Why hadn't the solution proposed by the little girl appeared in the official presentation?`,
        options: [`It was too expensive.`, `It was illegal.`, `Nobody had thought of the other side of the street.`, `It meant removing parking spaces, which no politician dared propose.`],
        correctIndex: 3,
        explanation: `"Elle supposait de supprimer quatorze places de stationnement, ce qu'aucun élu n'avait osé proposer."`,
      },
      {
        question: `What surprised the shopkeepers after the cycle lane opened?`,
        options: [`Their rents went down.`, `The pigeons disappeared.`, `Cyclists stopped at their shop windows more readily than drivers.`, `They lost many customers.`],
        correctIndex: 2,
        explanation: `"Les cyclistes s'arrêtaient plus volontiers devant leurs vitrines que les automobilistes."`,
      },
    ],
  },
  {
    slug: "fr-la-poubelle-de-l-annee",
    level: "FR-B2",
    title: `La poubelle de l'année`,
    subtitle: `An Angers family signs up for a zero-waste challenge, and the father turns it into a fierce competition with the neighbours.`,
    paragraphs: [
      `Quand l'agglomération d'Angers a lancé son défi « Familles zéro déchet », Fatima Lambert s'y est inscrite pour de bonnes raisons : elle trouvait que la poubelle de la famille se remplissait trop vite, et elle voulait que ses enfants prennent conscience de ce qu'ils jetaient. Elle n'avait pas prévu que son mari, Olivier, contrôleur de gestion de son état, y verrait non pas une démarche écologique, mais une compétition. Et Olivier, quand il était en compétition, devenait un autre homme.`,
      `Le principe était simple : chaque semaine, les familles participantes pesaient leurs déchets et envoyaient les résultats à l'agglomération. Dès le premier soir, Olivier a créé un tableur avec des graphiques en couleur. Il a acheté une balance de précision. Il a découvert que la famille Morin, qui habitait en face et participait aussi au défi, avait produit huit cents grammes de moins que les Lambert la première semaine. À partir de ce moment, la guerre était déclarée.`,
      `En un mois, la maison s'est transformée. Les placards se sont remplis de bocaux en verre achetés en vrac. Olivier fabriquait lui-même le dentifrice, à base d'argile et de bicarbonate, que les enfants jugeaient immonde. Il refusait les prospectus, les sacs plastique, les tickets de caisse et même les cadeaux d'anniversaire, à moins qu'ils ne soient emballés dans du tissu. Il a installé dans le salon un lombricomposteur, une sorte de tour en plastique dans laquelle des centaines de vers de terre étaient censés dévorer les épluchures.`,
      `Noah, seize ans, vivait cela comme une humiliation permanente. Ses copains l'appelaient « l'homme des cavernes » depuis qu'il apportait son goûter dans un bocal. Fatima, de son côté, partageait la plupart des objectifs de son mari, mais pas son fanatisme. Elle a commencé à s'inquiéter le jour où elle l'a surpris en train de fouiller la poubelle de la salle de bains pour vérifier que personne n'y avait jeté un coton-tige en cachette.`,
      `Le point culminant a eu lieu un dimanche matin, quand les vers ont décidé de quitter le lombricomposteur. Personne n'a jamais compris comment ils étaient sortis, mais on en a retrouvé sous le canapé, dans les chaussons de Noah et jusque dans la baignoire. La grand-mère, venue déjeuner ce jour-là, a poussé un cri que tout le quartier a entendu. Olivier, à quatre pattes, ramassait ses vers un par un en leur parlant doucement, comme à des employés qu'il aurait fallu remotiver.`,
      `Au bout de six mois, les résultats ont été proclamés lors d'une cérémonie à l'hôtel de ville. Les Lambert avaient réduit leurs déchets de soixante-dix pour cent et devançaient les Morin de trois cents grammes. Olivier est monté sur l'estrade, ému comme un champion olympique. On lui a remis son prix : un trophée en plastique doré, emballé sous film plastique dans une boîte en carton, accompagné d'un sac rempli de brochures sur papier glacé expliquant comment réduire ses déchets.`,
      `Il y a eu un long silence. Puis Fatima a éclaté de rire, et bientôt toute la salle a ri avec elle, y compris les Morin, y compris l'élu chargé de l'environnement, qui était devenu écarlate. Olivier a fini par rire aussi. En rentrant, il a pesé le trophée et son emballage : quatre cent douze grammes. Il l'a noté dans son tableur, avec un commentaire : « Victoire à la Pyrrhus ». La famille a gardé les bocaux et le vrac, mais elle a renoncé au dentifrice maison. Les vers, eux, vivent désormais au jardin.`,
    ],
    questions: [
      {
        question: `Why did Fatima sign the family up for the challenge?`,
        options: [`To beat the Morin family`, `To win a prize`, `Because the bin filled too fast and she wanted the children to become aware of their waste`, `Because her husband asked her to`],
        correctIndex: 2,
        explanation: `"Elle trouvait que la poubelle de la famille se remplissait trop vite, et elle voulait que ses enfants prennent conscience de ce qu'ils jetaient."`,
      },
      {
        question: `What started the "war" with the Morin family?`,
        options: [`They had produced less waste than the Lambert family in the first week.`, `They complained about the Lamberts' worms.`, `They mocked Noah at school.`, `They refused to take part.`],
        correctIndex: 0,
        explanation: `The Morins "avait produit huit cents grammes de moins que les Lambert la première semaine. À partir de ce moment, la guerre était déclarée."`,
      },
      {
        question: `What made Fatima start to worry about Olivier?`,
        options: [`He stopped eating.`, `He went through the bathroom bin to check for a hidden cotton bud.`, `He wanted to move to the countryside.`, `He gave away the children's presents.`],
        correctIndex: 1,
        explanation: `She caught him "en train de fouiller la poubelle de la salle de bains pour vérifier que personne n'y avait jeté un coton-tige en cachette".`,
      },
      {
        question: `Why did everyone laugh at the ceremony?`,
        options: [`Olivier fell off the stage.`, `The Morins had cheated.`, `The worms escaped again.`, `The zero-waste prize came wrapped in lots of plastic and packaging.`],
        correctIndex: 3,
        explanation: `The prize was "un trophée en plastique doré, emballé sous film plastique dans une boîte en carton, accompagné d'un sac rempli de brochures".`,
      },
    ],
  },
  {
    slug: "fr-le-recruteur-virtuel",
    level: "FR-B2",
    title: `Le recruteur virtuel`,
    subtitle: `A laid-off logistics manager in her fifties faces a job interview conducted by an artificial intelligence.`,
    paragraphs: [
      `Sylvie Le Goff avait cinquante-six ans, trente ans d'expérience dans la logistique portuaire et, depuis huit mois, une lettre de licenciement économique punaisée au-dessus de son bureau, au Havre, pour ne pas oublier qu'elle devait se battre. Elle avait envoyé cent quarante candidatures et obtenu trois entretiens, chaque fois avec des recruteurs de l'âge de son fils, qui lui avaient demandé avec beaucoup de délicatesse si elle « se voyait encore évoluer ».`,
      `Aussi, quand elle a été invitée à postuler à un poste de responsable d'entrepôt dans une grande entreprise de transport, elle a été ravie, jusqu'à ce qu'elle lise la suite du message. Le premier entretien serait mené par « Léo, notre assistant de recrutement intelligent ». Il lui suffisait de se connecter à l'heure de son choix, d'activer sa caméra et de répondre à une série de questions. Ses réponses, son vocabulaire et même les expressions de son visage seraient analysés afin d'évaluer son « adéquation au poste ».`,
      `Le jour J, Sylvie s'est installée devant son ordinateur portable, en veste de tailleur et en baskets, puisque Léo ne verrait que le haut. Un jeune homme souriant, aux traits trop parfaits pour être vrais, est apparu à l'écran. « Bonjour Sylvie ! Je suis ravi de faire votre connaissance. Pouvez-vous me parler d'un moment où vous avez fait preuve de résilience ? » Sylvie a raconté la grève des dockers, le navire bloqué au large pendant trois semaines et les cinquante conteneurs de bananes qu'elle avait réussi à sauver. Léo a hoché la tête exactement toutes les quatre secondes.`,
      `Puis est venue l'épreuve pratique : un exercice dans lequel elle devait organiser le chargement de plusieurs camions. Sylvie a tout de suite remarqué quelque chose d'étrange. Les données comportaient une erreur : le poids total des marchandises dépassait la charge autorisée des camions. Il n'existait donc aucune solution légale. Au lieu de tricher, comme l'auraient sans doute fait la plupart des candidats, elle l'a signalé dans la case des commentaires, en précisant que dans la vraie vie, ce genre d'erreur coûtait une amende, et parfois un accident.`,
      `À la fin, Léo lui a demandé de citer son principal défaut. Sylvie a regardé la caméra bien en face. « Je ne suis pas un robot, a-t-elle répondu. Quand quelque chose ne va pas, je le dis. » Léo a souri, a hoché la tête et lui a souhaité une excellente journée. Deux jours plus tard, elle a reçu un courriel automatique : sa candidature n'avait « malheureusement pas été retenue ». Elle n'en a pas été surprise. Elle a simplement ajouté une ligne à son tableau : cent quarante et un.`,
      `Une semaine après, son téléphone a sonné. C'était le directeur des ressources humaines de l'entreprise, un homme d'une soixantaine d'années à la voix enrouée. Il lui a expliqué que le logiciel l'avait classée dernière sur deux cents candidats, notamment parce qu'elle avait « insuffisamment souri » et qu'elle n'avait pas fourni de réponse à l'exercice. Mais son commentaire avait déclenché une alerte technique, qui avait atterri sur son bureau. Il avait vérifié : l'erreur existait bel et bien, et personne d'autre ne l'avait signalée. Cent quatre-vingt-dix-neuf candidats avaient surchargé des camions sans broncher.`,
      `Sylvie a été embauchée le mois suivant. Le jour de son arrivée, le directeur lui a confié, en plus de son entrepôt, une mission un peu particulière : participer au groupe de travail chargé de décider si l'entreprise allait conserver son assistant de recrutement. Elle a accepté avec plaisir. Elle avait déjà rédigé ses premières remarques, et la première ligne disait : « Léo hoche la tête toutes les quatre secondes, même quand on lui raconte une catastrophe. »`,
    ],
    questions: [
      {
        question: `What did young recruiters tactfully ask Sylvie in earlier interviews?`,
        options: [`Whether she could still see herself progressing in her career`, `Whether she spoke English`, `Whether she could move to Paris`, `Whether she had a driving licence`],
        correctIndex: 0,
        explanation: `They asked whether she "se voyait encore évoluer", a polite allusion to her age.`,
      },
      {
        question: `What was wrong with the practical exercise?`,
        options: [`It was in English.`, `It had no time limit.`, `The goods weighed more than the trucks were allowed to carry, so there was no legal solution.`, `The software crashed.`],
        correctIndex: 2,
        explanation: `"Le poids total des marchandises dépassait la charge autorisée des camions. Il n'existait donc aucune solution légale."`,
      },
      {
        question: `Why did the software rank Sylvie last?`,
        options: [`She was too old.`, `She logged in late.`, `She had too little experience.`, `She hadn't smiled enough and gave no answer to the exercise.`],
        correctIndex: 3,
        explanation: `She had "insuffisamment souri" and "elle n'avait pas fourni de réponse à l'exercice".`,
      },
      {
        question: `What special task was Sylvie given after being hired?`,
        options: [`Training new drivers`, `Helping decide whether to keep the AI recruitment assistant`, `Rewriting the practical exercise`, `Recruiting her own team with Léo`],
        correctIndex: 1,
        explanation: `She was to join "le groupe de travail chargé de décider si l'entreprise allait conserver son assistant de recrutement".`,
      },
    ],
  },
];

export const FR_B2_S03_ENGLISH: Record<string, string[]> = {
  "fr-la-famille-sans-voiture": [
    `The day the Mullers' old Clio gave up the ghost on the motorway between Strasbourg and Colmar, in a cloud of black smoke, Pierre made a decision that would turn the whole family's life upside down. Rather than buy a new car, they would try to live without one. For a year. "Strasbourg is France's cycling capital," he announced at dinner. "If we can't manage it here, we won't manage it anywhere." His wife, Aurélie, raised an eyebrow. Their three children rolled their eyes.`,
    `Pierre, who hadn't been on a bike since he was a teenager, threw himself into the project with the enthusiasm of a convert. He spent whole evenings on specialist forums, compared dozens of models and finally bought, with a grant from the metropolitan authority, an electric cargo bike with a big wooden box enthroned at the front, able to carry two children, the week's shopping and, according to the salesman, "a small fridge".`,
    `The first weeks were epic. Pierre discovered that the cargo bike, once loaded, weighed more than a horse and turned about as well as a lorry. He knocked over a market stall on Place Broglie, got his front wheel stuck in a tram rail and was overtaken by an eighty-year-old pensioner on a Dutch bike. The day the battery gave out halfway up a hill, he had to push the contraption, his two youngest children and six packs of water under the amused eyes of motorists.`,
    `Aurélie, for her part, took the tram and a second-hand bike without making a fuss. The children adapted faster than their parents. Jules, fourteen, who had sworn he would never be seen in "Dad's wheelbarrow", discovered he could cycle to school on his own and gained an unexpected freedom. The twins loved sitting enthroned in the box, waving to passers-by like queens in a carriage.`,
    `There were harder moments. In February, in freezing rain, nothing is less romantic than pedalling forty minutes to an orthodontist's appointment. And when Aurélie's grandmother, who lived in a poorly served village in the Vosges, fell ill, they had to rent a car several weekends in a row. Pierre had to admit, reluctantly, that not everyone could live without a car, and that it depended a lot on where you lived.`,
    `At the end of the year, Aurélie did the sums. Between the insurance, fuel, maintenance and parking they no longer paid, they had saved over four thousand euros, even counting the rentals. Pierre had lost seven kilos. Nobody in the family had been ill all winter. All that remained was to vote: would they buy a car again, yes or no?`,
    `The vote was held by show of hands around the kitchen table. Pierre, who was expecting a revolt, had prepared a long argument. He didn't need it: all five hands stayed down. Only Aurélie added a condition, with a half-smile: "We're keeping the cargo bike. But from now on, I'm driving."`,
  ],
  "fr-desactive": [
    `The message arrived one Tuesday evening at 9:47 p.m., while Yacine was waiting for a sushi order outside a restaurant in the Écusson, Montpellier's old centre. A plain notification, almost polite: "Following a review of your activity, your account has been deactivated. This decision is final." No name, no signature, no explanation. He read the sentence three times, then looked at his bike, his insulated bag, his hands. In one second he had lost his only income.`,
    `Yacine was twenty-four and had been delivering meals for the same platform for two years. Officially he was self-employed, free to organise his time as he wished. In practice, the app decided everything: which orders he got, how much they paid, how fast he had to pedal. The best-rated riders had access to the best time slots; the others made do with the crumbs. Yacine was one of the best. He worked fifty hours a week, in rain and in heatwaves.`,
    `First he tried to understand. In the app there was no phone number, only an automated assistant that invariably replied: "I understand your frustration. For any question about your account, please see our FAQ." He sent emails, then a registered letter to the company's head office in Paris. Nobody ever answered. It was like arguing with a wall, except that a wall, at least, doesn't wish you a wonderful day.`,
    `It was the other riders who helped him. In the group chat they shared, his message drew dozens of replies. Many had been through the same thing or knew someone it had happened to. A law student who delivered at weekends to pay for her studies offered to help. By reconstructing his last deliveries, they eventually found a likely explanation: three days earlier, a customer had reported never receiving his order, even though Yacine had a photo proving he had left it at the right door.`,
    `The following Saturday, about a hundred riders gathered outside the platform's regional office, an anonymous building on a business park, whose door stayed shut. They didn't shout, they didn't break anything. They simply parked their bikes in a row, bags open, and unfurled a banner: "An algorithm can't fire us without looking us in the eye". A journalist from the local paper came, then a TV crew. The report was broadcast that same evening.`,
    `On Monday morning Yacine received a new message, as impersonal as the first: "After a further review, your account has been reactivated. We apologise for any inconvenience caused." He didn't know whether to laugh or cry. No one explained what had happened, or why he was suddenly being proved right. He suspected that it wasn't the photo that had convinced the company, but the TV camera.`,
    `He didn't log back in. A few months later, with six other riders and the law student, he founded a small cycle delivery cooperative, where everyone is an employee and decisions are made in meetings, around a table, between human beings. They earn a little less, work a little less too, and deliver mostly for local shops. On the office door, Yacine pinned a sheet of paper on which he had written by hand: "Here, we answer the phone."`,
  ],
  "fr-l-affaire-du-platane": [
    `Nobody in the neighbourhood had ever really paid attention to the big plane tree standing at the crossroads of rue des Cordiers in Nantes. It had been there for a hundred and twenty years; it gave shade in summer, shed its leaves in autumn and served as a meeting point for teenagers. Then one March morning a municipal notice appeared on its trunk: as part of the construction of a new cycle lane, the tree would be felled on 15 April.`,
    `Within forty-eight hours the plane tree had become the most famous personality in the neighbourhood. An online petition gathered four thousand signatures. Children hung drawings on its bark. Someone even opened a social media account for it, where it spoke in the first person: "I've seen two wars and three tramways go by. I won't be brought down by a cycle lane." The neighbourhood council, which usually gathered a dozen pensioners, had to hold an extraordinary session in the gym.`,
    `The meeting began calmly and quickly degenerated. On one side, the cyclists' association, which had been demanding this lane for ten years and pointed out that a child had been knocked down at the crossroads the previous winter. On the other, the tree's defenders, who accused the town hall of "massacring nature in the name of ecology". In between, the shopkeepers, who above all didn't want anyone touching the parking spaces, and a gentleman who had come to complain about pigeons and couldn't understand why nobody was listening to him.`,
    `Everyone cited studies. A retired botanist explained that a century-old plane tree stored hundreds of kilos of carbon every year and cooled the street by several degrees in summer. The president of the cycling association retorted that the lane would prevent thousands of car journeys. The deputy mayor, who had brought a sixty-page slideshow, was accused in turn of despising trees, cyclists, shopkeepers and pigeons.`,
    `At around eleven at night, while everyone was shouting at once, a nine-year-old girl who had come with her father raised her hand. As nobody saw her, she climbed onto a chair. "Why don't you put the lane on the other side of the street? Where the parked cars are?" There was silence. The deputy mayor leafed through her slideshow. The solution wasn't in it, for the simple reason that it meant removing fourteen parking spaces, which no elected official had dared to propose.`,
    `It took two more meetings, a consultation with the shopkeepers and the promise of a cargo-bike parking area in front of the bakery, but the project was finally changed. The lane now runs on the other side. The shopkeepers, who had predicted they would go bust, noticed with astonishment that cyclists stopped at their windows more readily than drivers did. The pigeon gentleman still comes to every neighbourhood council.`,
    `As for the plane tree, it survived. The following spring the town hall fixed a small brass plaque to its trunk: "Tree saved by citizen consultation". The residents think that's a bit much. The little girl rides past it every morning on her bike, using the new lane, and never fails to wave to the tree, the way you greet an old friend you once helped out of a tight spot.`,
  ],
  "fr-la-poubelle-de-l-annee": [
    `When the Angers metropolitan area launched its "Zero-Waste Families" challenge, Fatima Lambert signed up for good reasons: she felt the family bin filled up too fast, and she wanted her children to become aware of what they threw away. She hadn't foreseen that her husband, Olivier, a management controller by trade, would see it not as an environmental project but as a competition. And Olivier, in competition, became a different man.`,
    `The principle was simple: every week, participating families weighed their waste and sent the results to the authority. From the very first evening, Olivier created a spreadsheet with coloured charts. He bought a precision scale. He discovered that the Morin family, who lived opposite and were also taking part, had produced eight hundred grams less than the Lamberts in the first week. From that moment, war was declared.`,
    `In a month the house was transformed. The cupboards filled up with glass jars of loose goods bought in bulk. Olivier made his own toothpaste from clay and bicarbonate, which the children found disgusting. He refused flyers, plastic bags, receipts and even birthday presents unless they were wrapped in cloth. He installed a wormery in the living room, a sort of plastic tower in which hundreds of earthworms were supposed to devour the peelings.`,
    `Noah, sixteen, experienced all this as a permanent humiliation. His friends had called him "the caveman" ever since he started bringing his snack in a jar. Fatima, for her part, shared most of her husband's goals but not his fanaticism. She began to worry the day she caught him rummaging through the bathroom bin to check that nobody had secretly thrown away a cotton bud.`,
    `The climax came one Sunday morning, when the worms decided to leave the wormery. Nobody ever understood how they got out, but they were found under the sofa, in Noah's slippers and even in the bath. Grandma, who had come for lunch that day, let out a scream the whole neighbourhood heard. Olivier, on all fours, picked his worms up one by one, talking to them gently, like employees who needed remotivating.`,
    `After six months, the results were announced at a ceremony at the town hall. The Lamberts had cut their waste by seventy per cent and beat the Morins by three hundred grams. Olivier went up onto the stage, as moved as an Olympic champion. He was handed his prize: a gilded plastic trophy, shrink-wrapped in a cardboard box, along with a bag full of glossy brochures explaining how to reduce your waste.`,
    `There was a long silence. Then Fatima burst out laughing, and soon the whole room was laughing with her, including the Morins, including the councillor for the environment, who had turned scarlet. Olivier ended up laughing too. Back home, he weighed the trophy and its packaging: four hundred and twelve grams. He entered it in his spreadsheet with a comment: "Pyrrhic victory". The family kept the jars and the bulk buying but gave up the home-made toothpaste. The worms now live in the garden.`,
  ],
  "fr-le-recruteur-virtuel": [
    `Sylvie Le Goff was fifty-six, had thirty years' experience in port logistics and, for eight months, had had a redundancy letter pinned above her desk in Le Havre so she wouldn't forget that she had to fight. She had sent off a hundred and forty applications and had three interviews, each time with recruiters her son's age, who had asked her very tactfully whether she "still saw herself progressing".`,
    `So when she was invited to apply for a warehouse manager's job at a large transport company, she was delighted, until she read the rest of the message. The first interview would be conducted by "Léo, our intelligent recruitment assistant". All she had to do was log in at a time of her choosing, switch on her camera and answer a series of questions. Her answers, her vocabulary and even her facial expressions would be analysed to assess her "fit for the role".`,
    `On the big day, Sylvie sat down at her laptop in a suit jacket and trainers, since Léo would only see the top half. A smiling young man with features too perfect to be real appeared on the screen. "Hello Sylvie! I'm delighted to meet you. Can you tell me about a time when you showed resilience?" Sylvie described the dockers' strike, the ship stuck offshore for three weeks and the fifty containers of bananas she had managed to save. Léo nodded exactly every four seconds.`,
    `Then came the practical test: an exercise in which she had to organise the loading of several trucks. Sylvie immediately noticed something odd. The data contained an error: the total weight of the goods exceeded the trucks' authorised load. So there was no legal solution. Instead of cheating, as most candidates would no doubt have done, she pointed it out in the comments box, adding that in real life this sort of error cost you a fine, and sometimes an accident.`,
    `At the end, Léo asked her to name her main weakness. Sylvie looked the camera straight in the eye. "I'm not a robot," she replied. "When something's wrong, I say so." Léo smiled, nodded and wished her a wonderful day. Two days later she received an automatic email: her application had "unfortunately not been successful". She wasn't surprised. She simply added a line to her table: one hundred and forty-one.`,
    `A week later her phone rang. It was the company's human resources director, a man of about sixty with a hoarse voice. He explained that the software had ranked her last out of two hundred candidates, partly because she had "not smiled enough" and had not provided an answer to the exercise. But her comment had triggered a technical alert, which had landed on his desk. He had checked: the error really did exist, and nobody else had reported it. A hundred and ninety-nine candidates had overloaded trucks without batting an eyelid.`,
    `Sylvie was hired the following month. On her first day, the director gave her, on top of her warehouse, a rather special assignment: to sit on the working group that would decide whether the company would keep its recruitment assistant. She accepted with pleasure. She had already written her first remarks, and the first line read: "Léo nods every four seconds, even when you're telling him about a disaster."`,
  ],
};

export const FR_B2_S03_GLOSSES: Record<string, StoryGloss[]> = {
  "fr-la-famille-sans-voiture": [
    { es: "rendre l'âme", en: "to give up the ghost, to die", forms: ["l'âme"] },
    { es: "bouleverser", en: "to turn upside down", forms: ["bouleverser"] },
    { es: "trôner", en: "to sit enthroned, to take pride of place", forms: ["trônait", "trôner"] },
    { es: "l'étal", en: "market stall", forms: ["étal"] },
    { es: "doubler", en: "to overtake", forms: ["doubler"] },
    { es: "lâcher quelqu'un", en: "to give out on someone", forms: ["lâché"] },
    { es: "l'engin", en: "contraption, machine", forms: ["l'engin"] },
    { es: "la brouette", en: "wheelbarrow", forms: ["brouette"] },
    { es: "desservi", en: "served (by public transport)", forms: ["desservi"] },
    { es: "à contrecœur", en: "reluctantly", forms: ["contrecœur"] },
    { es: "à main levée", en: "by show of hands", forms: ["levée"] },
  ],
  "fr-desactive": [
    { es: "le sac isotherme", en: "insulated bag", forms: ["isotherme"] },
    { es: "l'auto-entrepreneur", en: "self-employed worker", forms: ["auto-entrepreneur"] },
    { es: "le créneau", en: "time slot", forms: ["créneaux"] },
    { es: "les miettes", en: "crumbs, scraps", forms: ["miettes"] },
    { es: "la foire aux questions", en: "FAQ", forms: ["foire"] },
    { es: "la lettre recommandée", en: "registered letter", forms: ["recommandée"] },
    { es: "susciter", en: "to provoke, to give rise to", forms: ["suscité"] },
    { es: "la course", en: "(delivery) run, job", forms: ["courses"] },
    { es: "déployer", en: "to unfurl", forms: ["déployé"] },
    { es: "donner raison à quelqu'un", en: "to side with someone, to prove someone right", forms: ["raison"] },
    { es: "soupçonner", en: "to suspect", forms: ["soupçonnait"] },
  ],
  "fr-l-affaire-du-platane": [
    { es: "le platane", en: "plane tree", forms: ["platane"] },
    { es: "se dresser", en: "to stand, to rise up", forms: ["dressait"] },
    { es: "l'aménagement", en: "development, construction work", forms: ["l'aménagement"] },
    { es: "abattre", en: "to fell, to bring down", forms: ["abattu", "abattre"] },
    { es: "l'écorce", en: "bark", forms: ["écorce"] },
    { es: "dégénérer", en: "to get out of hand", forms: ["dégénéré"] },
    { es: "renverser", en: "to knock down", forms: ["renversé"] },
    { es: "l'adjointe au maire", en: "deputy mayor", forms: ["l'adjointe"] },
    { es: "la concertation", en: "consultation", forms: ["concertation"] },
    { es: "le laiton", en: "brass", forms: ["laiton"] },
    { es: "se tirer d'un mauvais pas", en: "to get out of a tight spot", forms: ["pas"] },
  ],
  "fr-la-poubelle-de-l-annee": [
    { es: "prendre conscience de", en: "to become aware of", forms: ["conscience"] },
    { es: "la démarche", en: "approach, initiative", forms: ["démarche"] },
    { es: "en vrac", en: "loose, in bulk", forms: ["vrac"] },
    { es: "immonde", en: "disgusting", forms: ["immonde"] },
    { es: "le lombricomposteur", en: "wormery", forms: ["lombricomposteur"] },
    { es: "l'épluchure", en: "peeling", forms: ["épluchures"] },
    { es: "fouiller", en: "to rummage through", forms: ["fouiller"] },
    { es: "le coton-tige", en: "cotton bud", forms: ["coton-tige"] },
    { es: "à quatre pattes", en: "on all fours", forms: ["pattes"] },
    { es: "devancer", en: "to be ahead of", forms: ["devançaient"] },
    { es: "l'estrade", en: "stage, platform", forms: ["l'estrade"] },
  ],
  "fr-le-recruteur-virtuel": [
    { es: "le licenciement économique", en: "redundancy", forms: ["licenciement"] },
    { es: "évoluer", en: "to progress (in one's career)", forms: ["évoluer"] },
    { es: "postuler", en: "to apply (for a job)", forms: ["postuler"] },
    { es: "l'entrepôt", en: "warehouse", forms: ["d'entrepôt", "entrepôt"] },
    { es: "l'adéquation", en: "fit, suitability", forms: ["adéquation"] },
    { es: "le jour J", en: "the big day", forms: ["j"] },
    { es: "au large", en: "offshore", forms: ["large"] },
    { es: "tricher", en: "to cheat", forms: ["tricher"] },
    { es: "enroué", en: "hoarse", forms: ["enrouée"] },
    { es: "bel et bien", en: "really, well and truly", forms: ["bel"] },
    { es: "sans broncher", en: "without batting an eyelid", forms: ["broncher"] },
  ],
};
