// Synced from cheneygross-afk/lengo:src/lib/stories/fr/batches/fr-b2-s02.ts by scripts/sync-content.mjs -- edit it there, not here.
import type { Story, StoryGloss } from "../../types";

// FR-B2 stories, batch 2 (see ../fr-a1.ts for the conventions).

export const FR_B2_S02_STORIES: Story[] = [
  {
    slug: "fr-mamie-josette",
    level: "FR-B2",
    title: `Mamie Josette, deux millions d'abonnés`,
    subtitle: `A Toulouse grandmother becomes an internet star while making her cassoulet, and a frozen-food brand comes knocking.`,
    paragraphs: [
      `Tout a commencé un dimanche de pluie, à Toulouse. Léa, vingt-deux ans, étudiante en communication, s'ennuyait chez sa grand-mère pendant que celle-ci préparait son cassoulet, comme chaque premier dimanche du mois depuis 1971. Pour passer le temps, Léa a filmé Josette avec son téléphone : ses mains noueuses qui écrasaient l'ail, ses commentaires bougons sur les haricots « qu'on vend aujourd'hui et qui n'ont plus de goût », et sa colère sincère lorsque Léa a osé demander si l'on pouvait remplacer la saucisse par du tofu.`,
      `« Du tofu ? Dans un cassoulet ? Ma pauvre fille, autant mettre de la confiture dans la soupe ! » Léa a monté la vidéo dans le métro, a ajouté des sous-titres et l'a publiée sans réfléchir. Le lendemain matin, elle avait été vue trois cent mille fois. Le surlendemain, deux millions. Les commentaires affluaient de partout : du Québec, de Belgique, de Dakar, et même d'un chef étoilé qui demandait humblement à Josette le temps de cuisson exact de ses haricots.`,
      `Josette, elle, n'y comprenait rien. Elle n'avait pas de smartphone et confondait encore Internet avec la télévision. Quand Léa lui a montré le nombre d'abonnés, elle a haussé les épaules : « Deux millions de personnes qui me regardent écraser de l'ail ? Ils n'ont rien d'autre à faire, ces gens-là ? » Pourtant, elle a accepté de tourner une deuxième vidéo, puis une troisième, à condition qu'on ne la maquille pas et qu'on la laisse dire ce qu'elle pensait.`,
      `Et elle en disait, des choses. Sur les plats préparés, qu'elle qualifiait de « nourriture pour astronautes ». Sur les jeunes qui photographient leur assiette au lieu de la manger chaude. Sur les gens qui gaspillent : « Le pain rassis, ça se met dans la soupe, pas à la poubelle ! » Plus elle grondait, plus les internautes l'adoraient. Les adolescents l'appelaient « la reine du cassoulet » et reprenaient ses expressions dans leurs propres vidéos.`,
      `Inévitablement, les marques se sont manifestées. Une entreprise de plats cuisinés a proposé une somme qui a fait pâlir Léa : il suffisait que Josette goûte leur cassoulet en conserve devant la caméra et déclare qu'il était « presque aussi bon que le sien ». Léa, qui avait un prêt étudiant à rembourser, a présenté l'offre avec beaucoup de précautions, en insistant sur le fait qu'il ne s'agissait que d'une petite phrase.`,
      `Josette a écouté jusqu'au bout, puis elle a ouvert la boîte que l'entreprise avait envoyée. Elle a reniflé le contenu, l'a goûté du bout de la cuillère et l'a recraché dans l'évier. « Ma chérie, a-t-elle dit, je veux bien qu'on rie de moi, mais je ne mentirai pas pour de l'argent. Si tu as besoin d'argent, on va en gagner honnêtement. »`,
      `Trois mois plus tard, Josette et Léa animaient chaque samedi, dans la salle des fêtes du quartier, un atelier de cuisine payant pour les touristes et les étudiants. Les places partaient en dix minutes. Les recettes servaient à payer les études de Léa et à offrir un repas, le dimanche, aux personnes âgées isolées du quartier. Josette tenait elle-même les comptes dans un cahier d'écolier. Et quand un journaliste lui a demandé le secret de son succès, elle a simplement répondu : « Du temps, du gras et de la mauvaise humeur. »`,
    ],
    questions: [
      {
        question: `What made Josette angry in the first video?`,
        options: [`Léa filming without asking`, `The price of beans`, `Léa asking whether the sausage could be replaced with tofu`, `The rain`],
        correctIndex: 2,
        explanation: `She got angry "lorsque Léa a osé demander si l'on pouvait remplacer la saucisse par du tofu".`,
      },
      {
        question: `On what condition did Josette agree to make more videos?`,
        options: [`That she wouldn't wear make-up and could say what she thought`, `That she would be paid`, `That the videos would only be shown in Toulouse`, `That Léa would cook instead of her`],
        correctIndex: 0,
        explanation: `"À condition qu'on ne la maquille pas et qu'on la laisse dire ce qu'elle pensait."`,
      },
      {
        question: `What did the company ask Josette to do?`,
        options: [`Write a cookbook`, `Sell them her recipe`, `Appear in a TV advert with a chef`, `Say on camera that their tinned cassoulet was almost as good as hers`],
        correctIndex: 3,
        explanation: `She only had to taste it on camera and declare that it was "presque aussi bon que le sien".`,
      },
      {
        question: `How did Josette and Léa end up earning money?`,
        options: [`Through brand sponsorships`, `By running paid cooking workshops`, `By opening a restaurant`, `By selling tinned cassoulet`],
        correctIndex: 1,
        explanation: `"Josette et Léa animaient chaque samedi... un atelier de cuisine payant pour les touristes et les étudiants."`,
      },
    ],
  },
  {
    slug: "fr-cherche-appartement-desesperement",
    level: "FR-B2",
    title: `Cherche appartement désespérément`,
    subtitle: `A young night nurse who cannot find a flat in Paris tries intergenerational housing with a very demanding old man.`,
    paragraphs: [
      `Le studio faisait dix-huit mètres carrés, donnait sur une cour sombre du onzième arrondissement et coûtait neuf cent cinquante euros par mois, charges non comprises. Quand Awa est arrivée pour la visite, à dix-huit heures précises, la file d'attente descendait déjà l'escalier et se prolongeait sur le trottoir. Elle a compté trente-sept personnes, presque toutes munies d'une chemise cartonnée contenant le fameux dossier, ce mille-feuille de bulletins de salaire, d'avis d'imposition et d'attestations en tout genre sans lequel on ne peut rien louer à Paris.`,
      `Awa avait vingt-sept ans et elle était infirmière de nuit dans un hôpital du nord de Paris. Elle gagnait correctement sa vie, mais pas trois fois le montant du loyer, comme l'exigeaient la plupart des propriétaires. Quant au garant, ses parents vivaient à Dakar, ce qui suffisait à faire grimacer les agents immobiliers. Depuis six mois, elle dormait sur le canapé d'une amie à Saint-Denis et passait trois heures par jour dans les transports. Elle commençait à se demander s'il existait dans cette ville un seul propriétaire qui veuille bien d'elle.`,
      `C'est une collègue qui lui a parlé du logement intergénérationnel. Le principe était simple : une association mettait en relation des personnes âgées vivant seules dans de grands appartements et des jeunes qui cherchaient à se loger. En échange d'un loyer modeste, le jeune s'engageait à être présent quelques soirs par semaine et à rendre de petits services. Awa a rempli le formulaire sans trop y croire. Une semaine plus tard, l'association l'a appelée : un monsieur de quatre-vingt-quatre ans, dans le dixième, acceptait de la rencontrer.`,
      `Monsieur Fabre l'a reçue dans un salon encombré d'affiches de cinéma et de bobines de film. Ancien projectionniste, veuf depuis trois ans, il vivait seul dans un cinq-pièces que sa fille, installée à Bordeaux, voulait lui faire quitter pour une maison de retraite. Il a fait asseoir Awa, a chaussé ses lunettes et a sorti un carnet. « Bien, mademoiselle. Moi aussi, j'ai mes exigences. Avez-vous déjà vu un film de Jacques Tati ? »`,
      `Awa, qui s'attendait à des questions sur ses revenus, a éclaté de rire. Non, elle n'avait jamais vu de film de Tati. Monsieur Fabre a pris un air grave, a noté quelque chose dans son carnet, puis il lui a demandé si elle ronflait, si elle savait changer une ampoule et si elle supportait le bruit d'un vieux projecteur à minuit. Au bout d'une heure d'interrogatoire, il a refermé son carnet. « Dossier incomplet, a-t-il conclu, mais candidate intéressante. Vous emménagez quand ? »`,
      `Les premières semaines n'ont pas été simples. Awa rentrait à sept heures du matin au moment où Monsieur Fabre se levait, et il avait la manie de vouloir lui raconter ses rêves pendant qu'elle cherchait désespérément à dormir. Il laissait traîner des tasses partout et changeait les clés de place tous les jours. Mais il lui laissait aussi des petits mots sur la table de la cuisine, il lui gardait de la soupe au chaud et, le dimanche soir, il projetait un vieux film sur le mur du salon, rien que pour elle.`,
      `Au printemps, sa fille est venue de Bordeaux, bien décidée à visiter des maisons de retraite. Elle a trouvé son père rasé de près, l'appartement rangé et le réfrigérateur plein. Elle a aussi trouvé, punaisé sur la porte du salon, un programme écrit à la main : « Ciné-club Fabre-Diallo, saison 1 ». Elle a regardé Awa longtemps, puis elle lui a simplement demandé, la voix un peu tremblante, si elle comptait rester encore un an. Awa a souri. Il lui restait encore tous les films de Tati à voir.`,
    ],
    questions: [
      {
        question: `Why was it so hard for Awa to rent a flat?`,
        options: [`She had a bad rental history.`, `She did not earn three times the rent and had no guarantor in France.`, `She refused to live outside the 11th arrondissement.`, `She had a dog.`],
        correctIndex: 1,
        explanation: `She did not earn "trois fois le montant du loyer", and her parents, the possible guarantors, "vivaient à Dakar".`,
      },
      {
        question: `How does intergenerational housing work in the story?`,
        options: [`The young person pays the elderly person's care home fees.`, `The elderly person moves into the young person's flat.`, `The association pays the rent for both.`, `The young person pays a modest rent and is present some evenings and helps out.`],
        correctIndex: 3,
        explanation: `"En échange d'un loyer modeste, le jeune s'engageait à être présent quelques soirs par semaine et à rendre de petits services."`,
      },
      {
        question: `What surprised Awa about Monsieur Fabre's interview?`,
        options: [`He asked about films and her habits, not her income.`, `He asked for a large deposit.`, `He refused to meet her in person.`, `He already knew her parents.`],
        correctIndex: 0,
        explanation: `"Awa, qui s'attendait à des questions sur ses revenus, a éclaté de rire" when he asked about Jacques Tati.`,
      },
      {
        question: `What did the daughter find when she came from Bordeaux?`,
        options: [`Her father ill in bed`, `The flat in a mess`, `Her father clean-shaven, a tidy flat and a home-made film club programme`, `A letter from the association ending the arrangement`],
        correctIndex: 2,
        explanation: `"Elle a trouvé son père rasé de près, l'appartement rangé et le réfrigérateur plein", plus the "Ciné-club Fabre-Diallo" programme.`,
      },
    ],
  },
  {
    slug: "fr-un-mois-sans-smartphone",
    level: "FR-B2",
    title: `Un mois sans smartphone`,
    subtitle: `A Lyon journalist accepts his editor's challenge to spend a month with an old flip phone and keeps a diary of the experience.`,
    paragraphs: [
      `Jour 1. Mon rédacteur en chef m'a lancé le défi lundi, entre deux cafés : « Un mois sans smartphone, et tu nous en fais un papier. » J'ai accepté par orgueil. Ce matin, j'ai donc rangé mon téléphone dans un tiroir et je l'ai remplacé par un vieux modèle à clapet acheté huit euros dans une ressourcerie, qui ne sait faire que deux choses : téléphoner et envoyer des SMS, à condition d'appuyer quatre fois sur la même touche pour écrire un « s ». Ma fille Zoé, quinze ans, m'a regardé comme si je partais en Antarctique. « Tu vas tenir deux jours », a-t-elle prédit.`,
      `Jour 3. Je n'avais pas mesuré à quel point mon téléphone pensait à ma place. Je ne connais plus aucun numéro par cœur, sauf celui de ma mère, qui n'a pas changé depuis 1987. Hier, je me suis perdu à la Croix-Rousse, où j'habite pourtant depuis dix ans, parce que je n'avais jamais vraiment regardé les rues : je suivais une flèche bleue. J'ai dû demander mon chemin à une dame qui promenait son chien. Elle a été si surprise qu'elle m'a accompagné jusqu'au bout de la rue.`,
      `Jour 8. Le plus dur, ce ne sont ni les cartes ni les messages, ce sont les temps morts. Dans la file d'attente de la boulangerie, au feu rouge, aux toilettes (soyons honnêtes), ma main cherche toute seule la poche où se trouvait le téléphone. Je ressens une sorte de démangeaison, un vide que je ne sais pas remplir. Alors je regarde les gens. Je constate que presque tous ont les yeux baissés sur un écran, et je me demande depuis combien de temps je ressemble à ça.`,
      `Jour 15. Quelque chose est en train de changer. Je m'ennuie, et cet ennui, curieusement, n'est pas désagréable. Dans le tram, au lieu de faire défiler des vidéos, j'ai lu un roman entier, ce qui ne m'était pas arrivé depuis des années. J'ai repris l'habitude de noter des idées dans un carnet. Mes articles sont plus longs, et mon rédacteur en chef prétend qu'ils sont meilleurs, bien qu'il soit sans doute de parti pris, puisque l'expérience était son idée.`,
      `Jour 22. Tout n'est pas rose. J'ai raté un rendez-vous chez le dentiste parce que le rappel se trouvait dans une application. Les parents d'élèves de la classe de mon fils ont organisé une sortie sans moi, puisque je n'existe plus dans leur messagerie. Et payer le stationnement est devenu une aventure, maintenant que les horodateurs du quartier renvoient à une application. Notre société n'est pas seulement connectée, elle exige qu'on le soit. Ceux qui n'ont pas de smartphone, par choix ou faute d'argent, sont peu à peu exclus de la vie ordinaire, et personne ne semble s'en émouvoir.`,
      `Jour 30. Ce soir, j'avais le droit de rallumer mon téléphone. Je l'ai sorti du tiroir. Il affichait quatre cent douze notifications. Je les ai fait défiler pendant cinq minutes, puis je me suis rendu compte qu'aucune n'était importante. Rien de grave ne s'était passé en mon absence. Le monde avait continué de tourner sans que j'aie besoin de le surveiller.`,
      `Je ne suis pas devenu un ermite pour autant. J'ai réinstallé l'essentiel : la banque, les cartes, le stationnement. Mais j'ai supprimé les réseaux sociaux, et le téléphone dort désormais dans l'entrée. Le vrai dénouement de cette expérience, cependant, ne vient pas de moi. Ce matin, Zoé est entrée dans mon bureau, un peu gênée, et m'a demandé si je pouvais lui prêter le téléphone à clapet pour le week-end. « Juste pour voir », a-t-elle dit. J'ai fait semblant de ne pas être fier.`,
    ],
    questions: [
      {
        question: `Why did the narrator get lost in his own neighbourhood?`,
        options: [`The streets had been renamed.`, `He had never really looked at the streets, just followed his phone's arrow.`, `It was dark.`, `He had just moved there.`],
        correctIndex: 1,
        explanation: `"Je n'avais jamais vraiment regardé les rues : je suivais une flèche bleue."`,
      },
      {
        question: `What does the narrator find hardest on day 8?`,
        options: [`The idle moments`, `Not being able to read the news`, `Sending text messages`, `Finding his way`],
        correctIndex: 0,
        explanation: `"Le plus dur, ce ne sont ni les cartes ni les messages, ce sont les temps morts."`,
      },
      {
        question: `What social criticism does he make on day 22?`,
        options: [`That dentists are always late`, `That parents' groups are too noisy`, `That parking is too expensive`, `That society expects everyone to have a smartphone and excludes those who don't`],
        correctIndex: 3,
        explanation: `"Notre société n'est pas seulement connectée, elle exige qu'on le soit. Ceux qui n'ont pas de smartphone... sont peu à peu exclus de la vie ordinaire."`,
      },
      {
        question: `What does Zoé ask at the end?`,
        options: [`For a new smartphone`, `For her father to read her his article`, `To borrow the flip phone for the weekend`, `To go back to using social media`],
        correctIndex: 2,
        explanation: `She asked "si je pouvais lui prêter le téléphone à clapet pour le week-end".`,
      },
    ],
  },
  {
    slug: "fr-candidat-malgre-lui",
    level: "FR-B2",
    title: `Candidat malgré lui`,
    subtitle: `When nobody in his Jura village will stand for mayor, a painfully shy cheesemaker is pushed into the race.`,
    paragraphs: [
      `Dans le petit village du haut Jura où vivait Bastien Vuillemin (trois cent douze habitants, une église, une fromagerie coopérative et un bistrot ouvert quatre jours par semaine), la nouvelle a fait l'effet d'une tempête de neige en juillet : après trente et un ans de mandat, Madame Girod, la maire, ne se représenterait pas. « J'ai quatre-vingts ans, a-t-elle déclaré au conseil municipal. Je voudrais voir la mer avant de mourir. »`,
      `Le problème, c'est que personne ne voulait lui succéder. Être maire d'un village, cela veut dire être réveillé à minuit parce qu'une vache s'est échappée sur la route, recevoir les plaintes sur le déneigement, remplir des formulaires pour la préfecture, et tout cela pour une indemnité qui couvre à peine l'essence. À trois mois de l'élection, aucune liste n'avait été déposée. On commençait à murmurer que, faute de candidat, le village finirait par être rattaché à la commune voisine, ce que tout le monde considérait comme une humiliation historique.`,
      `C'est alors que les regards se sont tournés vers Bastien. Il avait trente-huit ans, il était fromager à la coopérative depuis quinze ans, et tous les habitants passaient au moins une fois par semaine devant son comptoir. Il connaissait le prénom de chaque enfant, la santé de chaque grand-mère et les rancunes de chaque famille. Il n'avait qu'un défaut, mais de taille : il était d'une timidité maladive. Dès qu'il devait parler devant plus de quatre personnes, il bégayait et devenait écarlate.`,
      `Pendant des semaines, il a refusé. Mais les clients revenaient à la charge en achetant leur comté. La boulangère lui glissait des listes de soutiens dans son pain, le curé priait ostensiblement pour lui, et Madame Girod en personne est venue lui dire qu'elle ne partirait pas tranquille tant qu'il n'aurait pas accepté. Il a fini par céder, à condition de ne pas avoir à faire de discours. Il a rédigé son programme au dos d'un papier d'emballage de la fromagerie : réparer le toit de l'école, rouvrir le bistrot le lundi, installer un banc devant la poste.`,
      `Coup de théâtre deux semaines avant la date limite : une seconde liste a été déposée. Elle était menée par Monsieur Duval-Ferrand, un consultant parisien qui possédait une résidence secondaire au bord du lac et qui n'y venait que pour les vacances de février. Ses tracts, imprimés sur papier glacé, promettaient un golf, un parc d'aventures et « une stratégie d'attractivité territoriale ». Une partie du village était impressionnée. L'autre se demandait ce que pouvait bien être l'attractivité territoriale.`,
      `Le débat a eu lieu dans la salle des fêtes, devant cent cinquante personnes. Monsieur Duval-Ferrand a parlé quarante minutes, diapositives à l'appui. Puis est venu le tour de Bastien. Il s'est levé, rouge comme une tomate, a ouvert la bouche, l'a refermée. Le silence est devenu insupportable. Finalement, il a dit, d'une voix à peine audible : « Un bon comté, il lui faut dix-huit mois de cave. On ne peut pas le presser. Un village, c'est pareil. » Puis il s'est rassis. Pendant une seconde, personne n'a bougé, puis les applaudissements ont éclaté.`,
      `Le soir du scrutin, après le dépouillement, la liste de Bastien l'a emporté avec une seule voix d'avance. Le lendemain, au comptoir, il a avoué à Madame Girod, à voix basse, qu'il avait voté pour son adversaire. « Par politesse, a-t-il expliqué. Ça me semblait plus juste. » L'ancienne maire l'a regardé avec un mélange de stupeur et de tendresse. « Mon pauvre Bastien, a-t-elle soupiré, tu vas faire un excellent maire. »`,
    ],
    questions: [
      {
        question: `What did villagers fear would happen if nobody stood for mayor?`,
        options: [`The school would close.`, `The cheese cooperative would be sold.`, `The village would be merged with the neighbouring one.`, `Madame Girod would have to stay.`],
        correctIndex: 2,
        explanation: `"Faute de candidat, le village finirait par être rattaché à la commune voisine."`,
      },
      {
        question: `What was Bastien's big weakness as a candidate?`,
        options: [`He was extremely shy and stammered in public.`, `Nobody in the village knew him.`, `He was too young.`, `He had a conflict with the priest.`],
        correctIndex: 0,
        explanation: `"Il était d'une timidité maladive. Dès qu'il devait parler devant plus de quatre personnes, il bégayait et devenait écarlate."`,
      },
      {
        question: `What was the point of Bastien's short speech about comté?`,
        options: [`That the village should sell more cheese`, `That he would rather stay a cheesemaker`, `That the golf course was a good idea`, `That a village, like good cheese, needs time and can't be rushed`],
        correctIndex: 3,
        explanation: `"Un bon comté, il lui faut dix-huit mois de cave. On ne peut pas le presser. Un village, c'est pareil."`,
      },
      {
        question: `Why did Madame Girod think Bastien would be an excellent mayor?`,
        options: [`Because he won by a large majority`, `Because he had voted for his opponent out of fairness`, `Because he had promised a golf course`, `Because he gave a long speech`],
        correctIndex: 1,
        explanation: `He confessed "qu'il avait voté pour son adversaire", explaining "Ça me semblait plus juste", and she said "tu vas faire un excellent maire".`,
      },
    ],
  },
  {
    slug: "fr-du-haut-fourneau-a-l-eolienne",
    level: "FR-B2",
    title: `Du haut-fourneau à l'éolienne`,
    subtitle: `A report on a former Lorraine steelworker, afraid of heights, who retrained to maintain wind turbines.`,
    paragraphs: [
      `À cent vingt mètres au-dessus des plateaux de la Meuse, Franck Kieffer accroche son mousqueton à la rambarde et reprend son souffle. Le vent siffle autour de la nacelle de l'éolienne, qui oscille doucement. « La première fois que je suis monté ici, j'ai cru que j'allais mourir, nous dit-il en riant. Maintenant, c'est mon bureau. Avec la plus belle vue de Lorraine. »`,
      `Rien ne prédestinait cet homme de cinquante-deux ans aux énergies renouvelables. Fils et petit-fils de sidérurgistes, Franck est entré à dix-huit ans à l'aciérie de la vallée de la Fensch, comme presque tous les garçons de son quartier. Pendant vingt-cinq ans, il a travaillé au pied des hauts-fourneaux, dans la chaleur, la poussière et le vacarme. « C'était dur, mais on était fiers. On faisait de l'acier. On avait le sentiment de construire quelque chose. »`,
      `Quand l'usine a définitivement fermé, il a vécu ce que beaucoup de ses collègues ont vécu : la colère, puis la honte, puis une longue période de flottement. « Pendant un an, je ne suis presque pas sorti de chez moi. Je me sentais inutile. Ma femme travaillait, et moi, je regardais la télé. » Les propositions de reclassement qu'on lui faisait ne l'intéressaient pas : magasinier, agent de sécurité, chauffeur-livreur. Il avait l'impression qu'on lui demandait de disparaître poliment.`,
      `C'est une conseillère de l'agence pour l'emploi qui lui a parlé, presque par hasard, d'une formation de technicien de maintenance éolienne. Franck a d'abord ri : il avait le vertige depuis l'enfance et n'était jamais monté plus haut qu'un troisième étage. Mais la conseillère a insisté : la mécanique, l'électricité, le travail d'équipe dans des conditions difficiles, il connaissait tout cela mieux que personne. Bien qu'il ait été le plus âgé de sa promotion, avec vingt ans de plus que la moyenne, il a obtenu son certificat du premier coup.`,
      `Le plus difficile a été de vaincre sa peur. Lors des premiers exercices, sur une tour d'entraînement, il s'est figé à mi-hauteur, incapable de monter ou de descendre. Un jeune formateur, à peine plus âgé que son propre fils, est resté à côté de lui pendant vingt minutes, sans le brusquer, en lui parlant de football. « Je ne l'oublierai jamais, ce gamin. Il m'a dit : la peur, c'est normal, c'est elle qui te garde en vie ; il faut juste qu'elle ne prenne pas le volant. »`,
      `Aujourd'hui, Franck intervient sur une trentaine d'éoliennes réparties sur le plateau. Il change des pièces, inspecte les pales, graisse les engrenages, souvent par des températures négatives. Il gagne un peu moins qu'à l'usine, et il reconnaît que le métier n'a pas la même dimension collective : « À l'aciérie, on était trois mille. Ici, on est deux dans la nacelle. » Certains anciens collègues lui reprochent d'avoir « changé de camp », eux qui accusent l'écologie d'avoir tué l'industrie. Lui hausse les épaules : il ne croit pas qu'on doive choisir entre les ouvriers et la planète.`,
      `Avant de redescendre, il nous montre l'horizon. Par temps clair, on aperçoit au loin les silhouettes rouillées des anciens hauts-fourneaux, conservés comme un monument. « Mon grand-père faisait de l'acier avec du charbon, dit-il. Moi, je fais de l'électricité avec du vent. Peut-être que mon petit-fils fera quelque chose qu'on n'imagine même pas encore. » Puis il vérifie son harnais et entame la longue descente, un barreau après l'autre.`,
    ],
    questions: [
      {
        question: `How did Franck feel about his years at the steelworks?`,
        options: [`It was hard work, but he was proud of it.`, `He hated every minute.`, `He found it boring.`, `He regretted not studying instead.`],
        correctIndex: 0,
        explanation: `"C'était dur, mais on était fiers. On faisait de l'acier."`,
      },
      {
        question: `Why didn't the first job offers after the closure appeal to him?`,
        options: [`They were too far away.`, `They were too well paid to be true.`, `They required a university degree.`, `He felt he was being asked to disappear politely.`],
        correctIndex: 3,
        explanation: `"Il avait l'impression qu'on lui demandait de disparaître poliment."`,
      },
      {
        question: `Why did Franck laugh when the wind-turbine training was suggested?`,
        options: [`He thought wind power was useless.`, `He had been afraid of heights since childhood.`, `He was too old to train.`, `He didn't know anything about mechanics.`],
        correctIndex: 1,
        explanation: `"Franck a d'abord ri : il avait le vertige depuis l'enfance."`,
      },
      {
        question: `What does Franck say he misses compared with the steelworks?`,
        options: [`The higher wages above all`, `Working indoors`, `The collective dimension of working with thousands of people`, `The heat of the blast furnaces`],
        correctIndex: 2,
        explanation: `"Le métier n'a pas la même dimension collective": "À l'aciérie, on était trois mille. Ici, on est deux dans la nacelle."`,
      },
    ],
  },
];

export const FR_B2_S02_ENGLISH: Record<string, string[]> = {
  "fr-mamie-josette": [
    `It all began on a rainy Sunday in Toulouse. Léa, twenty-two, a communications student, was bored at her grandmother's while the old lady made her cassoulet, as she had done on the first Sunday of every month since 1971. To pass the time, Léa filmed Josette on her phone: her gnarled hands crushing garlic, her grumpy remarks about the beans "they sell nowadays, which have no taste any more", and her genuine anger when Léa dared to ask whether you could replace the sausage with tofu.`,
    `"Tofu? In a cassoulet? My poor girl, you might as well put jam in soup!" Léa edited the video on the metro, added subtitles and posted it without thinking. By the next morning it had been watched three hundred thousand times. The day after, two million. Comments poured in from everywhere: from Quebec, from Belgium, from Dakar, and even from a Michelin-starred chef humbly asking Josette for the exact cooking time of her beans.`,
    `Josette herself understood none of it. She didn't have a smartphone and still confused the internet with television. When Léa showed her the number of followers, she shrugged: "Two million people watching me crush garlic? Have these people got nothing better to do?" Still, she agreed to shoot a second video, then a third, on condition that nobody put make-up on her and that she was allowed to say what she thought.`,
    `And she certainly had things to say. About ready meals, which she called "food for astronauts". About young people who photograph their plate instead of eating it hot. About people who waste food: "Stale bread goes in the soup, not in the bin!" The more she scolded, the more internet users adored her. Teenagers called her "the queen of cassoulet" and borrowed her expressions in their own videos.`,
    `Inevitably, the brands came forward. A ready-meal company offered a sum that made Léa turn pale: all Josette had to do was taste their tinned cassoulet on camera and declare that it was "almost as good as her own". Léa, who had a student loan to pay back, presented the offer very cautiously, stressing that it was only one little sentence.`,
    `Josette listened to the end, then opened the tin the company had sent. She sniffed the contents, tasted it from the tip of the spoon and spat it out into the sink. "Darling," she said, "I don't mind people laughing at me, but I won't lie for money. If you need money, we'll earn it honestly."`,
    `Three months later, every Saturday, Josette and Léa were running a paid cooking workshop for tourists and students in the neighbourhood community hall. The places went in ten minutes. The takings paid for Léa's studies and for a Sunday meal for isolated elderly people in the area. Josette kept the accounts herself in a school exercise book. And when a journalist asked her the secret of her success, she simply replied: "Time, fat and a bad temper."`,
  ],
  "fr-cherche-appartement-desesperement": [
    `The studio was eighteen square metres, looked onto a dark courtyard in the 11th arrondissement and cost nine hundred and fifty euros a month, not including service charges. When Awa arrived for the viewing at six o'clock sharp, the queue already ran down the stairs and out onto the pavement. She counted thirty-seven people, nearly all holding a cardboard folder containing the famous rental file, that thick pile of payslips, tax notices and certificates of every kind without which you can rent nothing in Paris.`,
    `Awa was twenty-seven and a night nurse at a hospital in the north of Paris. She earned a decent living, but not three times the rent, as most landlords required. As for a guarantor, her parents lived in Dakar, which was enough to make estate agents wince. For six months she had been sleeping on a friend's sofa in Saint-Denis and spending three hours a day on public transport. She was starting to wonder whether there was a single landlord in this city who would have her.`,
    `It was a colleague who told her about intergenerational housing. The principle was simple: an association put elderly people living alone in large flats in touch with young people looking for somewhere to live. In exchange for a modest rent, the young person agreed to be at home a few evenings a week and to do small favours. Awa filled in the form without much hope. A week later the association called her: an eighty-four-year-old gentleman in the 10th arrondissement had agreed to meet her.`,
    `Monsieur Fabre received her in a living room cluttered with film posters and reels. A former projectionist, widowed for three years, he lived alone in a five-room flat that his daughter, who lived in Bordeaux, wanted him to leave for a retirement home. He had Awa sit down, put on his glasses and took out a notebook. "Right, young lady. I have my requirements too. Have you ever seen a Jacques Tati film?"`,
    `Awa, who had been expecting questions about her income, burst out laughing. No, she had never seen a Tati film. Monsieur Fabre looked grave, wrote something in his notebook, then asked whether she snored, whether she could change a light bulb and whether she could put up with the noise of an old projector at midnight. After an hour of interrogation, he closed his notebook. "Incomplete file," he concluded, "but an interesting candidate. When can you move in?"`,
    `The first weeks were not easy. Awa came home at seven in the morning just as Monsieur Fabre was getting up, and he had a habit of wanting to tell her his dreams while she was desperately trying to sleep. He left cups lying around everywhere and moved the keys every day. But he also left her little notes on the kitchen table, kept soup warm for her and, on Sunday evenings, projected an old film onto the living-room wall just for her.`,
    `In spring his daughter came up from Bordeaux, determined to visit retirement homes. She found her father clean-shaven, the flat tidy and the fridge full. She also found, pinned to the living-room door, a hand-written programme: "Fabre-Diallo Film Club, season 1". She looked at Awa for a long time, then simply asked her, her voice trembling a little, whether she intended to stay another year. Awa smiled. She still had all of Tati's films left to see.`,
  ],
  "fr-un-mois-sans-smartphone": [
    `Day 1. My editor threw down the challenge on Monday, between two coffees: "A month without a smartphone, and you write us a piece about it." I accepted out of pride. So this morning I put my phone away in a drawer and replaced it with an old flip phone bought for eight euros at a second-hand charity shop, which can do only two things: make calls and send texts, provided you press the same key four times to type an "s". My daughter Zoé, fifteen, looked at me as if I were leaving for Antarctica. "You'll last two days," she predicted.`,
    `Day 3. I hadn't realised how much my phone did my thinking for me. I no longer know a single number by heart, except my mother's, which hasn't changed since 1987. Yesterday I got lost in the Croix-Rousse, where I've lived for ten years, because I had never really looked at the streets: I just followed a blue arrow. I had to ask the way from a lady walking her dog. She was so surprised that she walked me to the end of the street.`,
    `Day 8. The hardest thing isn't the maps or the messages, it's the dead time. In the queue at the bakery, at red lights, in the toilet (let's be honest), my hand reaches on its own for the pocket where the phone used to be. I feel a sort of itch, an emptiness I don't know how to fill. So I watch people. I notice that almost all of them have their eyes lowered to a screen, and I wonder how long I've looked like that.`,
    `Day 15. Something is changing. I'm bored, and this boredom, oddly, isn't unpleasant. On the tram, instead of scrolling through videos, I read an entire novel, which hadn't happened to me in years. I've got back into the habit of jotting down ideas in a notebook. My articles are longer, and my editor claims they are better, although he is no doubt biased, since the experiment was his idea.`,
    `Day 22. Not everything is rosy. I missed a dentist's appointment because the reminder was in an app. The parents in my son's class organised an outing without me, since I no longer exist in their group chat. And paying for parking has become an adventure, now that the local meters send you to an app. Our society isn't just connected, it demands that we be connected. People without a smartphone, by choice or for lack of money, are gradually shut out of ordinary life, and nobody seems to care.`,
    `Day 30. This evening I was allowed to switch my phone back on. I took it out of the drawer. It showed four hundred and twelve notifications. I scrolled through them for five minutes, then realised none of them mattered. Nothing serious had happened while I was away. The world had kept on turning without my needing to watch over it.`,
    `I haven't become a hermit for all that. I've reinstalled the essentials: the bank, maps, parking. But I've deleted social media, and the phone now sleeps in the hallway. The real ending of this experiment, however, doesn't come from me. This morning Zoé came into my study, a bit embarrassed, and asked if I could lend her the flip phone for the weekend. "Just to see," she said. I pretended not to be proud.`,
  ],
  "fr-candidat-malgre-lui": [
    `In the little village in the high Jura where Bastien Vuillemin lived (three hundred and twelve inhabitants, a church, a cooperative cheese dairy and a bistro open four days a week), the news hit like a snowstorm in July: after thirty-one years in office, Madame Girod, the mayor, would not stand again. "I'm eighty," she told the municipal council. "I'd like to see the sea before I die."`,
    `The problem was that nobody wanted to succeed her. Being mayor of a village means being woken at midnight because a cow has got out onto the road, receiving complaints about snow clearing, filling in forms for the prefecture, and all that for an allowance that barely covers the petrol. Three months before the election, no list had been submitted. People were starting to whisper that, for lack of a candidate, the village would end up being merged with the neighbouring commune, which everyone considered a historic humiliation.`,
    `That was when all eyes turned to Bastien. He was thirty-eight, he had been a cheesemaker at the cooperative for fifteen years, and every inhabitant passed his counter at least once a week. He knew every child's first name, every grandmother's health and every family's grudges. He had only one flaw, but a big one: he was painfully shy. As soon as he had to speak in front of more than four people, he stammered and turned scarlet.`,
    `For weeks he refused. But customers kept coming back to it as they bought their comté. The baker slipped lists of supporters into his bread, the priest prayed conspicuously for him, and Madame Girod herself came to tell him she would not leave in peace until he had agreed. He finally gave in, on condition he wouldn't have to make speeches. He wrote his manifesto on the back of a sheet of the dairy's wrapping paper: repair the school roof, reopen the bistro on Mondays, put a bench in front of the post office.`,
    `A dramatic twist two weeks before the deadline: a second list was submitted. It was led by Monsieur Duval-Ferrand, a Parisian consultant who owned a holiday home by the lake and only came for the February holidays. His leaflets, printed on glossy paper, promised a golf course, an adventure park and "a territorial attractiveness strategy". Part of the village was impressed. The other part wondered what on earth territorial attractiveness might be.`,
    `The debate took place in the village hall, in front of a hundred and fifty people. Monsieur Duval-Ferrand spoke for forty minutes, with slides. Then it was Bastien's turn. He stood up, red as a tomato, opened his mouth, closed it again. The silence became unbearable. Finally he said, in a barely audible voice: "A good comté needs eighteen months in the cellar. You can't rush it. A village is the same." Then he sat down. For a second nobody moved, then the applause broke out.`,
    `On election night, after the count, Bastien's list won by a single vote. The next day, at the counter, he confessed to Madame Girod in a low voice that he had voted for his opponent. "Out of politeness," he explained. "It seemed fairer." The former mayor looked at him with a mixture of astonishment and tenderness. "My poor Bastien," she sighed, "you're going to make an excellent mayor."`,
  ],
  "fr-du-haut-fourneau-a-l-eolienne": [
    `A hundred and twenty metres above the plateaus of the Meuse, Franck Kieffer clips his carabiner to the railing and catches his breath. The wind whistles around the nacelle of the wind turbine, which sways gently. "The first time I came up here, I thought I was going to die," he tells us, laughing. "Now it's my office. With the best view in Lorraine."`,
    `Nothing destined this fifty-two-year-old for renewable energy. The son and grandson of steelworkers, Franck joined the steelworks in the Fensch valley at eighteen, like almost all the boys in his neighbourhood. For twenty-five years he worked at the foot of the blast furnaces, in the heat, the dust and the din. "It was hard, but we were proud. We made steel. We felt we were building something."`,
    `When the plant closed for good, he went through what many of his colleagues went through: anger, then shame, then a long period of drifting. "For a year I hardly left the house. I felt useless. My wife was working, and I watched TV." The redeployment offers he received did not interest him: warehouse worker, security guard, delivery driver. He felt he was being asked to disappear politely.`,
    `It was an adviser at the employment agency who mentioned, almost by chance, a training course for wind turbine maintenance technicians. Franck laughed at first: he had been afraid of heights since childhood and had never been higher than a third floor. But the adviser insisted: mechanics, electrics, teamwork in tough conditions, he knew all that better than anyone. Although he was the oldest in his group, twenty years above the average, he passed his certificate first time.`,
    `The hardest part was overcoming his fear. During the first exercises, on a training tower, he froze halfway up, unable to climb up or down. A young instructor, barely older than his own son, stayed beside him for twenty minutes without rushing him, talking to him about football. "I'll never forget that kid. He told me: fear is normal, it's what keeps you alive; you just mustn't let it take the wheel."`,
    `Today Franck works on some thirty turbines spread across the plateau. He changes parts, inspects blades, greases gears, often in sub-zero temperatures. He earns a little less than at the plant, and he admits the job lacks the same collective dimension: "At the steelworks there were three thousand of us. Here there are two of us in the nacelle." Some former colleagues accuse him of having "changed sides", blaming ecology for killing industry. He shrugs: he doesn't believe you have to choose between workers and the planet.`,
    `Before heading down, he points out the horizon. On a clear day you can make out in the distance the rusty silhouettes of the old blast furnaces, preserved as a monument. "My grandfather made steel with coal," he says. "I make electricity with wind. Maybe my grandson will do something we can't even imagine yet." Then he checks his harness and begins the long descent, one rung after another.`,
  ],
};

export const FR_B2_S02_GLOSSES: Record<string, StoryGloss[]> = {
  "fr-mamie-josette": [
    { es: "noueux", en: "gnarled", forms: ["noueuses"] },
    { es: "bougon", en: "grumpy", forms: ["bougons"] },
    { es: "affluer", en: "to pour in, to flood in", forms: ["affluaient"] },
    { es: "étoilé", en: "Michelin-starred", forms: ["étoilé"] },
    { es: "hausser les épaules", en: "to shrug", forms: ["haussé"] },
    { es: "rassis", en: "stale", forms: ["rassis"] },
    { es: "gronder", en: "to scold, to grumble", forms: ["grondait"] },
    { es: "pâlir", en: "to turn pale", forms: ["pâlir"] },
    { es: "renifler", en: "to sniff", forms: ["reniflé"] },
    { es: "recracher", en: "to spit out", forms: ["recraché"] },
    { es: "les recettes", en: "takings, income", forms: ["recettes"] },
  ],
  "fr-cherche-appartement-desesperement": [
    { es: "les charges", en: "service charges (on rent)", forms: ["charges"] },
    { es: "la chemise cartonnée", en: "cardboard folder", forms: ["chemise"] },
    { es: "le bulletin de salaire", en: "payslip", forms: ["bulletins"] },
    { es: "l'avis d'imposition", en: "tax notice", forms: ["d'imposition"] },
    { es: "le garant", en: "guarantor", forms: ["garant"] },
    { es: "grimacer", en: "to wince, to pull a face", forms: ["grimacer"] },
    { es: "la bobine", en: "reel", forms: ["bobines"] },
    { es: "chausser ses lunettes", en: "to put on one's glasses", forms: ["chaussé"] },
    { es: "emménager", en: "to move in", forms: ["emménagez"] },
    { es: "la manie", en: "odd habit", forms: ["manie"] },
    { es: "punaiser", en: "to pin (with a drawing pin)", forms: ["punaisé"] },
  ],
  "fr-un-mois-sans-smartphone": [
    { es: "le rédacteur en chef", en: "editor-in-chief", forms: ["rédacteur"] },
    { es: "le papier", en: "(newspaper) piece, article", forms: ["papier"] },
    { es: "l'orgueil", en: "pride", forms: ["orgueil"] },
    { es: "le clapet", en: "flip (of a flip phone)", forms: ["clapet"] },
    { es: "la ressourcerie", en: "second-hand reuse shop", forms: ["ressourcerie"] },
    { es: "la démangeaison", en: "itch", forms: ["démangeaison"] },
    { es: "faire défiler", en: "to scroll through", forms: ["défiler"] },
    { es: "de parti pris", en: "biased", forms: ["parti"] },
    { es: "l'horodateur", en: "parking meter", forms: ["horodateurs"] },
    { es: "s'émouvoir de", en: "to be concerned about", forms: ["émouvoir"] },
    { es: "l'ermite", en: "hermit", forms: ["ermite"] },
    { es: "le dénouement", en: "outcome, ending", forms: ["dénouement"] },
  ],
  "fr-candidat-malgre-lui": [
    { es: "le mandat", en: "term of office", forms: ["mandat"] },
    { es: "se représenter", en: "to stand for re-election", forms: ["représenterait"] },
    { es: "le déneigement", en: "snow clearing", forms: ["déneigement"] },
    { es: "l'indemnité", en: "allowance", forms: ["indemnité"] },
    { es: "rattacher", en: "to attach, to merge", forms: ["rattaché"] },
    { es: "la rancune", en: "grudge", forms: ["rancunes"] },
    { es: "bégayer", en: "to stammer", forms: ["bégayait"] },
    { es: "revenir à la charge", en: "to keep pressing the point", forms: ["charge"] },
    { es: "le tract", en: "leaflet", forms: ["tracts"] },
    { es: "le scrutin", en: "vote, ballot", forms: ["scrutin"] },
    { es: "le dépouillement", en: "counting of the votes", forms: ["dépouillement"] },
  ],
  "fr-du-haut-fourneau-a-l-eolienne": [
    { es: "le mousqueton", en: "carabiner", forms: ["mousqueton"] },
    { es: "la nacelle", en: "nacelle (housing at the top of a turbine)", forms: ["nacelle"] },
    { es: "le sidérurgiste", en: "steelworker", forms: ["sidérurgistes"] },
    { es: "l'aciérie", en: "steelworks", forms: ["l'aciérie"] },
    { es: "le haut-fourneau", en: "blast furnace", forms: ["hauts-fourneaux"] },
    { es: "le vacarme", en: "din, racket", forms: ["vacarme"] },
    { es: "le flottement", en: "drifting, indecision", forms: ["flottement"] },
    { es: "le reclassement", en: "redeployment (to a new job)", forms: ["reclassement"] },
    { es: "avoir le vertige", en: "to be afraid of heights", forms: ["vertige"] },
    { es: "brusquer", en: "to rush, to be rough with", forms: ["brusquer"] },
    { es: "la pale", en: "(turbine) blade", forms: ["pales"] },
    { es: "l'engrenage", en: "gear", forms: ["engrenages"] },
  ],
};
