// Synced from cheneygross-afk/lengo:src/lib/stories/fr/batches/fr-c2-s03.ts by scripts/sync-content.mjs -- edit it there, not here.
import type { Story, StoryGloss } from "../../types";

// FR-C2 stories, batch 3 (see ../fr-a1.ts for the conventions).

export const FR_C2_S03_STORIES: Story[] = [
  {
    slug: "fr-c2-le-vin-etait-trop-noir",
    level: "FR-C2",
    title: `Le vin était trop noir`,
    subtitle: `A roman noir set in Burgundy: a former sommelier turned private detective is hired to find who is counterfeiting a famous estate's wine, and tastes something he did not expect.`,
    paragraphs: [
      `Beaune, novembre. Les vendanges étaient finies depuis un mois, et la ville avait cette gueule de lendemain de fête qu'ont les salles des ventes quand les enchères sont tombées. J'avais été sommelier pendant quinze ans dans un trois-étoiles de Lyon, jusqu'au soir où j'avais dit à un ministre que son vin était bouchonné. Il l'était. Ça ne m'avait pas sauvé. Depuis, je louais mon nez au plus offrant : assureurs, cavistes floués, héritiers soupçonneux. On m'appelait Ndongo, ou le Nez, selon qu'on me payait ou non.`,
      `Elle entra sans frapper, ce qui, à Beaune, est une manière de dire qu'on possède des vignes. Clothilde Royer-Vergy, quarante ans, manteau de cachemire, bottes propres comme on n'en voit jamais pendant les vendanges. Elle dirigeait le Domaine des Vergy depuis la mort de son père, en 2015, et elle l'avait modernisé de fond en comble : fûts neufs, œnologue-conseil, des vins plus ronds, plus boisés, qui plaisaient aux Américains. Elle posa une bouteille sur mon bureau. Nuits-Saint-Georges premier cru, millésime 2005. « Saisie à Hong Kong. L'étiquette est parfaite, le bouchon est parfait. C'est un faux. Je veux savoir qui. »`,
      `J'ouvris la bouteille le soir même, seul, avec le respect qu'on doit aux suspects. La robe était sombre, presque noire. Je la humai longtemps. Puis je la goûtai, je la gardai en bouche, je la laissai partir. Et je compris que j'avais un problème. Ce faux était meilleur que le vrai. Il y avait là-dedans du cassis, du sous-bois, une pointe de fer, et cette austérité un peu sauvage que je n'avais plus rencontrée dans un Vergy depuis dix ans. Je connaissais ce vin. Je l'avais servi à Lyon, du temps du vieux Royer. Quelqu'un, quelque part, faisait encore le vin du père.`,
      `Il me fallut quatre jours et autant de cafés-calva dans les bistrots de Nuits pour remonter la piste. Elle menait à Villers-la-Faye, dans les Hautes-Côtes, à un garage au fond d'une cour où une vieille camionnette rouillait sous un noyer. Lucien Bichot, soixante-quatorze ans, avait été pendant trente ans le maître de chai du Domaine des Vergy. Clothilde l'avait remercié la première année, avec une indemnité et une poignée de main. Il louait depuis une parcelle à une cousine, vinifiait dans son garage, à l'ancienne, grappes entières, vieux fûts, et vendait ses barriques à un intermédiaire de Dijon qui, lui, se chargeait des étiquettes. « Je ne lui vole rien, me dit-il en me tendant un verre. Je lui rends ce qu'elle a jeté. »`,
      `J'aurais pu rédiger mon rapport là, sur le capot de la camionnette. Les noms, les dates, l'intermédiaire, la répression des fraudes. C'est ce qu'on attend d'un privé : qu'il rapporte des coupables comme un chien rapporte des perdrix. Mais je ne suis pas un chien. Je suis un nez, et un nez a ses fidélités. Je rentrai à Beaune avec trois bouteilles sans étiquette dans le coffre.`,
      `Je la reçus le lendemain dans mon bureau, les volets tirés, trois verres alignés sur un torchon blanc. Une dégustation à l'aveugle, lui dis-je, pour la méthode. Le premier verre était son 2005 authentique ; le deuxième, son dernier millésime ; le troisième, le faux. Elle prit son temps. Elle était bonne, il faut le dire, meilleure que ses vins. Au troisième verre, elle s'arrêta. Elle reposa le verre, le reprit, et je vis quelque chose se défaire sur son visage, comme un nœud qu'on tire. « C'est celui de mon père », dit-elle tout bas.`,
      `Elle ne porta pas plainte contre Lucien. L'intermédiaire de Dijon eut moins de chance : on le retrouva dans les journaux, rubrique des fraudes, entre un trafic de truffes et une affaire de faux miel. Le lundi suivant, un gros quatre-quatre noir remonta la route des Hautes-Côtes et s'arrêta devant un garage à Villers-la-Faye. Je ne sais pas ce qui se dit sous le noyer. Je sais seulement qu'au printemps le Domaine des Vergy mit en vente une nouvelle cuvée, en petite quantité, grappes entières, vieux fûts. Elle s'appelait la cuvée Lucien.`,
      `On me paya mes honoraires, plus une caisse. Je l'ai encore, au fond d'un placard, entre mon revolver et mes mauvais souvenirs. Dans ce métier, la vérité a toujours un arrière-goût. Celle-là avait un goût de cassis et de sous-bois, avec une pointe de fer.`,
    ],
    questions: [
      {
        question: `How did Ndongo lose his job as a sommelier?`,
        options: [`He was caught drinking the restaurant's wine.`, `He sold fake bottles to customers.`, `He told a government minister that his wine was corked.`, `He refused to work during the grape harvest.`],
        correctIndex: 2,
        explanation: `"Jusqu'au soir où j'avais dit à un ministre que son vin était bouchonné."`,
      },
      {
        question: `What troubling discovery does Ndongo make when he tastes the fake?`,
        options: [`It is better than the genuine wine.`, `It is not wine at all.`, `It comes from Hong Kong.`, `It is identical to Clothilde's latest vintage.`],
        correctIndex: 0,
        explanation: `"Je compris que j'avais un problème. Ce faux était meilleur que le vrai."`,
      },
      {
        question: `Who is making the wine sold as fake Vergy?`,
        options: [`Clothilde's consultant oenologist`, `A chemist in Lyon`, `Clothilde's cousin`, `The estate's former cellar master, whom Clothilde had let go`],
        correctIndex: 3,
        explanation: `"Lucien Bichot [...] avait été pendant trente ans le maître de chai du Domaine des Vergy. Clothilde l'avait remercié la première année."`,
      },
      {
        question: `How does Ndongo reveal the truth to Clothilde?`,
        options: [`He gives her a written report with all the names.`, `He makes her taste three wines blind.`, `He takes her to Lucien's garage.`, `He shows her an article in the newspaper.`],
        correctIndex: 1,
        explanation: `"Trois verres alignés sur un torchon blanc. Une dégustation à l'aveugle."`,
      },
    ],
  },
  {
    slug: "fr-c2-l-homme-qui-perdait-ses-mots",
    level: "FR-C2",
    title: `L'Homme qui perdait ses mots`,
    subtitle: `A conte fantastique: in Brussels, a conference interpreter finds that each morning one word has vanished from the language, and the thing it named has vanished from the world.`,
    paragraphs: [
      `Le premier mot que perdit Thomas Delvaux fut cuillère. Il s'en aperçut un mardi matin, dans sa cuisine d'Ixelles, devant son café : il voulut le remuer et ne trouva rien pour le faire, ni dans le tiroir, ni dans sa tête. Il y avait des fourchettes, des couteaux, et entre les deux un vide, propre et net, comme une dent qu'on vient d'arracher. Il remua son café avec le manche d'un couteau et se dit qu'il était fatigué. Il était interprète au Parlement européen depuis vingt-deux ans ; il passait ses journées à attraper au vol les mots des autres, et il arrive, pensa-t-il, que les filets craquent.`,
      `Au bureau, il demanda à une collègue comment on appelait l'objet avec lequel on mange la soupe. Elle le regarda sans comprendre. La soupe, lui dit-elle, se boit au bol, comme partout, comme toujours. Dans les cabines de traduction, sur les menus de la cantine, dans les dictionnaires de quatre langues qu'il consulta fébrilement à la pause, le mot n'existait plus, ni la chose. Personne n'en avait jamais eu besoin. Le monde s'était refermé sur l'absence avec une politesse effrayante.`,
      `Le lendemain, ce fut dimanche. Il se réveilla, consulta son téléphone et constata que la semaine comptait désormais six jours, du lundi au samedi, et que personne ne s'en plaignait. Le surlendemain disparut le mot drache, ce mot belge pour les grosses pluies, et il plut, à Bruxelles, pour la première fois de mémoire d'homme, d'une pluie fine et raisonnable. Puis ce fut le tour de nonante, qui emporta avec lui le chiffre lui-même : on comptait désormais jusqu'à quatre-vingt-neuf, on sautait poliment une dizaine, et l'on reprenait à cent.`,
      `Il commença à tenir une liste. Les mots partaient la nuit, un par un, sans ordre apparent, et emportaient leurs objets comme des locataires emportent leurs meubles. Au bout d'une semaine, il crut découvrir une logique. Il n'avait pas pris de soupe depuis la mort de sa mère. Il ne faisait plus rien le dimanche depuis des années. Il ne disait plus drache depuis qu'il s'appliquait, en cabine, à parler un français de Paris. Les mots qui s'en allaient étaient ceux qu'il n'employait plus. Il les avait laissés à l'abandon ; ils en tiraient la seule conclusion qui s'imposait.`,
      `Cette nuit-là, il dressa en tremblant l'inventaire de ce qu'il ne disait plus. Il y trouva des choses sans importance, cerf-volant, gaufre de Liège, et d'autres qui le glacèrent. Pardon, qu'il n'avait pas prononcé depuis longtemps sans le faire suivre d'un mais. Et sœur. Il avait une sœur, Hélène, à Liège. Ils ne s'étaient pas parlé depuis l'enterrement de leur mère, pour une histoire de maison, de meubles, de ces choses qui paraissent énormes pendant trois mois et qui ne pèsent plus rien au bout de dix ans. Cela faisait onze ans.`,
      `Il était quatre heures du matin. Il comprit que, si le mot partait cette nuit, Hélène partirait avec lui, non pas morte, mais jamais née, effacée, et que personne, pas même lui au réveil, ne s'en souviendrait. Il chercha son numéro dans un vieux carnet. Il le composa. Le téléphone sonna longtemps dans une maison de Liège, et il répétait à voix basse, pour le retenir, comme on retient quelqu'un par la manche au bord d'un quai : sœur, sœur, sœur.`,
      `Une voix ensommeillée et furieuse répondit. Il ne savait pas quoi dire. Il dit le premier mot qui lui vint, et ce fut le bon : « Pardon. » Il y eut un long silence. Puis Hélène dit : « Tu sais quelle heure il est, idiot ? » Et elle se mit à pleurer, et lui aussi, et ils parlèrent jusqu'à ce que le jour se lève sur Ixelles.`,
      `Le dimanche ne revint jamais tout à fait. Mais le samedi suivant, Thomas prit le train pour Liège, et sa sœur lui servit une soupe aux pois dans un bol, et lui tendit, sans y penser, un petit objet de métal qu'il regarda longtemps avant de retrouver son nom.`,
    ],
    questions: [
      {
        question: `What is the first word, and thing, that disappears?`,
        options: [`Fork`, `Sunday`, `Spoon`, `Rain`],
        correctIndex: 2,
        explanation: `"Le premier mot que perdit Thomas Delvaux fut cuillère."`,
      },
      {
        question: `What pattern does Thomas discover?`,
        options: [`The words that vanish are the ones he no longer uses.`, `The words vanish in alphabetical order.`, `Only Belgian words are vanishing.`, `The words vanish whenever he translates them.`],
        correctIndex: 0,
        explanation: `"Les mots qui s'en allaient étaient ceux qu'il n'employait plus."`,
      },
      {
        question: `Why does Thomas panic at four in the morning?`,
        options: [`He has lost his job at the Parliament.`, `He cannot remember his own name.`, `It has started to rain again.`, `He fears the word "sister" will vanish and his sister with it.`],
        correctIndex: 3,
        explanation: `"Si le mot partait cette nuit, Hélène partirait avec lui, non pas morte, mais jamais née."`,
      },
      {
        question: `What is the first thing Thomas says to his sister?`,
        options: [`"Sœur."`, `"Pardon."`, `"Bonjour."`, `"Je t'aime."`],
        correctIndex: 1,
        explanation: `"Il dit le premier mot qui lui vint, et ce fut le bon", and that word is "Pardon".`,
      },
    ],
  },
  {
    slug: "fr-c2-une-vie-a-rebours",
    level: "FR-C2",
    title: `Une vie à rebours`,
    subtitle: `The story of a Dakar couple is told backwards, from a widow's evening on the corniche to the morning, forty-five years earlier, when everything began.`,
    paragraphs: [
      `2023. Sur la corniche de Dakar, à l'heure où le soleil tombe dans l'Atlantique comme une pièce dans une tirelire, Aïssatou Ndiaye, soixante et onze ans, s'assoit seule sur le banc de béton face aux Mamelles. Elle a apporté le vieux transistor d'Ousmane. Elle l'allume, cherche la station, tombe sur une chanson de l'Orchestra Baobab. Elle sourit. Ils ne se sont jamais mis d'accord sur cette chanson. Il la trouvait sublime ; elle la trouvait trop longue. Elle l'écoute jusqu'au bout, pour la première fois, et pour la première fois elle ne la trouve pas trop longue.`,
      `2009. Pot de départ à la retraite de M. Ousmane Diallo, professeur d'histoire au lycée Blaise-Diagne. Dans son discours, après avoir remercié l'inspecteur, les collègues et trente-quatre promotions d'élèves, il se tourne vers le premier rang : « Je remercie enfin ma femme, qui m'a contredit tous les jours depuis trente ans, et qui avait raison une fois sur deux, ce qui, pour un historien, est une moyenne exceptionnelle. » Le proviseur lui offre une montre ; les élèves, un ballon dédicacé ; Aïssatou, rien du tout, puisqu'elle lui a déjà tout dit. Toute la salle rit. Aïssatou ne rit pas. Elle compte, sur ses doigts, et trouve qu'il a sous-estimé la moyenne.`,
      `1994. Le franc CFA vient de perdre la moitié de sa valeur, et la ville entière fait ses comptes à voix haute. Au marché Sandaga, on efface les prix à la craie pour en écrire de nouveaux, et le pain a doublé en une nuit. Dans une maternité de la Médina, pendant une coupure de courant, une petite fille vient au monde à la lueur d'une bougie qu'Ousmane tient au-dessus de la sage-femme d'une main qui tremble. On la prénommera Mariama, comme la grand-mère d'Aïssatou. Ousmane voulait Khady. Ils en discuteront plus tard, de longues années, avec beaucoup de plaisir.`,
      `1981. Mariage à Saint-Louis, dans la cour de la maison familiale, sous les fromagers. La mère d'Aïssatou fait la tête : un professeur, sans fortune, qui parle trop et qui écrit mal. Le marié a exigé l'Orchestra Baobab ; la mariée a exigé qu'on ne joue pas plus de trois fois la même chanson. On la joue sept fois. À la septième, elle danse quand même, et c'est la photo qui restera sur le buffet pendant quarante ans.`,
      `1979. Une lettre arrive de Paris, où Ousmane prépare l'agrégation dans une chambre de bonne du cinquième arrondissement. Elle fait quatre pages. Il y parle de la neige, du froid, de la solitude, et il y avoue, au détour d'une phrase compliquée, qu'il pense à elle. Aïssatou la lit deux fois. Puis elle prend un stylo rouge, corrige onze fautes d'orthographe, et la lui renvoie, sans un mot de plus. Il répond par retour du courrier : douze pages, zéro faute. Elle les relit trois fois, pour vérifier.`,
      `1978. Dans un car rapide qui file de Rufisque vers le Plateau, bondé, brinquebalant, peint de couleurs vives, un jeune homme en chemise blanche se lève pour céder sa place à une jeune femme chargée de livres. Elle refuse. Elle ne s'assoit pas, dit-elle, sur la politesse d'un inconnu. Il insiste ; elle s'entête ; ils se disputent jusqu'au marché Sandaga sur la question de savoir si la galanterie est une forme de respect ou de condescendance. Elle descend furieuse. Sur la banquette, elle a oublié un livre. Il l'ouvre. Sur la page de garde, une écriture appliquée : Aïssatou Ndiaye, et une adresse.`,
      `1978, le même jour, à sept heures du matin. Dans une petite maison de Rufisque, une jeune femme de vingt-six ans attrape son sac, ses livres, une mangue, et cherche ses chaussures en maugréant. Elle va être en retard. Sa mère, depuis la cuisine, lui crie : « Prends au moins un livre de moins, tu vas te casser le dos ! » Aïssatou ne l'écoute pas. Elle ne l'a jamais écoutée. Elle sort dans la lumière, sans savoir qu'elle a toute la vie devant elle, ou derrière elle, selon le sens dans lequel on la lit.`,
    ],
    questions: [
      {
        question: `What does Aïssatou do differently in 2023 with the Orchestra Baobab song?`,
        options: [`She switches it off at once.`, `She listens to the end and no longer finds it too long.`, `She sings it to her daughter.`, `She dances to it on the beach.`],
        correctIndex: 1,
        explanation: `"Elle l'écoute jusqu'au bout, pour la première fois, et pour la première fois elle ne la trouve pas trop longue."`,
      },
      {
        question: `How does Aïssatou respond to Ousmane's first love letter?`,
        options: [`She tears it up.`, `She shows it to her mother.`, `She corrects his spelling mistakes in red and sends it back.`, `She writes back twelve pages.`],
        correctIndex: 2,
        explanation: `"Elle prend un stylo rouge, corrige onze fautes d'orthographe, et la lui renvoie."`,
      },
      {
        question: `What do they argue about on the bus when they first meet?`,
        options: [`Whether gallantry is a form of respect or of condescension`, `Which band is the best`, `The price of the fare`, `Who should get off first`],
        correctIndex: 0,
        explanation: `"Ils se disputent [...] sur la question de savoir si la galanterie est une forme de respect ou de condescendance."`,
      },
      {
        question: `How did Ousmane find out Aïssatou's name and address?`,
        options: [`The bus driver told him.`, `He followed her to the market.`, `Her mother wrote to him.`, `She left a book on the seat with her name and address in it.`],
        correctIndex: 3,
        explanation: `"Sur la banquette, elle a oublié un livre [...] Aïssatou Ndiaye, et une adresse."`,
      },
    ],
  },
  {
    slug: "fr-c2-le-mot-de-la-fin",
    level: "FR-C2",
    title: `Le Mot de la fin`,
    subtitle: `A grand old actor of the Comédie-Française has spent forty years polishing his last words, but death keeps failing to show up on cue.`,
    paragraphs: [
      `Maxence Dulac-Ferrand, sociétaire honoraire de la Comédie-Française, avait joué six fois le Misanthrope, onze fois l'Avare et une fois, au festival d'Avignon, un arbre, ce qu'il considérait comme le sommet de sa carrière. Mais l'œuvre de sa vie, celle à laquelle il travaillait en secret depuis l'âge de quarante-cinq ans, tenait en une phrase : ses dernières paroles. Il les avait écrites, raturées, réécrites, essayées devant le miroir, en alexandrins, en prose, en latin. Il avait fini par arrêter une version, qu'il gardait pliée dans son portefeuille, derrière sa carte Vitale : « Le rideau tombe ; ce n'est pas une raison pour que le public s'en aille. »`,
      `La première fois qu'il crut mourir, ce fut en 2009, d'un infarctus, dans sa loge, pendant l'entracte. Il eut le temps de saisir la main d'une habilleuse, de la regarder dans les yeux et de prononcer la phrase avec une diction admirable. L'habilleuse pleura. Le Samu arriva. On le sauva. Trois semaines plus tard, il remontait sur scène, et l'habilleuse, qui avait raconté l'anecdote à tout le monde, ne lui adressa plus la parole qu'avec une froideur de veuve trompée.`,
      `La deuxième fois, ce fut à quatre-vingt-un ans, d'une pneumonie, à l'hôpital Lariboisière. Il avait, cette fois, un public plus nombreux : deux neveux, un ancien partenaire de scène et un journaliste du Figaro, prévenu par un neveu qui pensait à l'héritage. Il dit sa phrase. Le journaliste la nota. Le lendemain matin, la fièvre tomba. L'article, déjà rédigé, ne parut jamais, mais la phrase, elle, fit le tour de Paris, et l'on vit des comédiens débutants la citer en riant au bar du Café de la Régence. Le neveu, lui, ne revint jamais : il avait, disait-il, déjà fait son deuil.`,
      `La troisième fois fut la pire. Une chute dans l'escalier de son immeuble, rue de Richelieu, une nuit de verglas. Il eut le temps, avant de perdre connaissance, de déclamer la phrase au gardien de l'immeuble, qui lui répondit : « Oui, monsieur Dulac, je sais, vous me l'avez déjà faite. » Il s'en remit, du crâne. De la réplique, beaucoup moins. Une dernière parole qu'on a prononcée trois fois, songeait-il, n'est plus une dernière parole : c'est un numéro.`,
      `Il entra, à quatre-vingt-huit ans, dans une maison de retraite de Neuilly où on le traitait avec la déférence un peu lasse qu'on réserve aux monuments historiques. Une seule personne lui parlait vraiment : une aide-soignante de trente ans, Fatoumata Camara, qui lui apportait son thé à quatre heures et lui faisait réciter du Racine pour lui entretenir la mémoire. Il lui racontait en échange des histoires de coulisses dont les trois quarts étaient inventés et le dernier quart, pire encore. Elle connaissait la phrase, bien sûr. Tout le monde la connaissait. Un jour, elle lui demanda s'il avait pensé à en écrire une autre. Il la regarda longuement. « Ma chère enfant, dit-il, on n'a qu'une seule dernière réplique. Le problème, c'est qu'on ne sait jamais laquelle c'est. »`,
      `Il mourut un mardi de mars, à seize heures, sans prévenir personne. Fatoumata était seule avec lui. Elle venait de poser le thé. Il porta la tasse à ses lèvres, fit la grimace, la reposa, et dit avec une immense lassitude d'artiste, en levant la main comme pour arrêter une répétition : « Attendez, je la refais. » Puis il ferma les yeux, et ce fut tout.`,
      `Le lendemain, un journaliste appela la maison de retraite. Il voulait savoir quelles avaient été les dernières paroles du grand Dulac-Ferrand. Fatoumata réfléchit un instant, la main sur le combiné. Elle pensa au portefeuille, à la carte Vitale, aux quarante ans de travail. Puis elle répondit, d'une voix ferme, sans une hésitation : « Il a dit : Le rideau tombe ; ce n'est pas une raison pour que le public s'en aille. » Le journaliste nota. On grava la phrase sur sa tombe, au cimetière Montmartre. Et Fatoumata garda pour elle la vraie, qu'elle trouvait bien meilleure. Elle ne la confia qu'une fois, à sa mère, qui en rit pendant une semaine.`,
    ],
    questions: [
      {
        question: `What does Maxence consider the summit of his career?`,
        options: [`Playing a tree at the Avignon festival`, `Playing the Misanthrope six times`, `Writing his last words`, `Becoming a sociétaire of the Comédie-Française`],
        correctIndex: 0,
        explanation: `He played "une fois, au festival d'Avignon, un arbre, ce qu'il considérait comme le sommet de sa carrière".`,
      },
      {
        question: `Why does the building's caretaker spoil Maxence's third "last words"?`,
        options: [`He does not hear them.`, `He laughs at them.`, `He says Maxence has already performed them for him.`, `He calls a journalist.`],
        correctIndex: 2,
        explanation: `"Oui, monsieur Dulac, je sais, vous me l'avez déjà faite."`,
      },
      {
        question: `What were Maxence's real last words?`,
        options: [`The line folded in his wallet`, `A verse from Racine`, `"Merci, Fatoumata."`, `"Attendez, je la refais."`],
        correctIndex: 3,
        explanation: `Lifting his hand "comme pour arrêter une répétition", he said "Attendez, je la refais."`,
      },
      {
        question: `What does Fatoumata tell the journalist?`,
        options: [`The truth about his last words`, `The line he had prepared for forty years`, `That she was not with him when he died`, `That he died without saying anything`],
        correctIndex: 1,
        explanation: `She answers "sans une hésitation" with the prepared line, "Le rideau tombe ; ce n'est pas une raison pour que le public s'en aille", and keeps the real words to herself.`,
      },
    ],
  },
  {
    slug: "fr-c2-les-liaisons-numeriques",
    level: "FR-C2",
    title: `Les Liaisons numériques`,
    subtitle: `In the style of an eighteenth-century epistolary novel, two Lyon friends who call each other "la Marquise" and "le Vicomte" exchange messages about a seduction wager on a dating app.`,
    paragraphs: [
      `Message premier. La Marquise au Vicomte, envoyé à 23 h 47. Vous vous ennuyez, Vicomte, et un homme qui s'ennuie devient dangereux pour lui-même. Je vous propose une distraction digne de vos talents. Il existe sur cette application que vous fréquentez sans honte une certaine Clémence, architecte, trente-trois ans, qui a pour toute présentation ces mots terribles : Ni sport, ni voyages, ni rires. Personne, à ma connaissance, n'a obtenu d'elle plus de trois messages. Je vous défie d'obtenir un dîner avant la fin du mois. L'enjeu ? Si vous perdez, vous m'accompagnerez au mariage de ma cousine, en costume, et vous danserez.`,
      `Message second. Le Vicomte à la Marquise, envoyé à 0 h 12. Madame, j'accepte, et je vous plains. Vous ignorez sans doute que la froideur affichée n'est que la pudeur des âmes trop sensibles, et que la place la mieux défendue est souvent celle qui n'attend qu'un siège en règle. Je commencerai par l'esprit, je poursuivrai par la constance, je finirai par l'indifférence, qui est la seule arme à laquelle on ne résiste jamais. Je vous enverrai chaque soir le bulletin de mes progrès, comme un général à son roi. Préparez votre cousine à danser avec un autre.`,
      `Message troisième. Le Vicomte à la Marquise, quatre jours plus tard. Je dois vous rendre compte de ma campagne avec une franchise qui me coûte. J'ai ouvert par un trait d'esprit sur Le Corbusier ; elle m'a répondu en corrigeant une faute d'accord dans ma phrase. J'ai fait valoir une citation de Diderot ; elle m'en a signalé l'attribution fautive. J'ai feint l'indifférence pendant quarante-huit heures ; elle ne s'en est pas aperçue. Hier soir, enfin, elle m'a écrit spontanément pour me demander mon avis sur la restauration d'une traboule de la Croix-Rousse. Nous avons échangé jusqu'à trois heures du matin. Je ne sais pas encore si c'est une victoire.`,
      `Message quatrième. La Marquise au Vicomte. Mon pauvre ami, vous me parlez de traboules. Il y a quinze ans que je vous connais, et je ne vous ai jamais vu parler d'une traboule à une femme, ni à personne, vous qui n'ouvriez un livre que pour y glisser un numéro de téléphone. Prenez garde : on commence par vouloir gagner un pari, et l'on finit par apprendre l'histoire de l'urbanisme lyonnais. Il me revient d'ailleurs que vous avez été vu, samedi, à la bibliothèque de la Part-Dieu, au rayon architecture. Je ne vous reconnais plus. Dites-moi que c'est une ruse.`,
      `Message cinquième. Le Vicomte à la Marquise, envoyé à 2 h 03. Ce n'est pas une ruse. Je l'ai vue ce soir. Ce n'était pas un dîner, au sens où vous l'entendiez : nous avons marché quatre heures dans les pentes, elle m'a montré des escaliers, des cours, des portes, et je n'ai pas fait un seul trait d'esprit. Elle n'a pas ri une seule fois, elle me l'avait promis. Elle a seulement souri, deux fois, et je donnerais toutes les conquêtes dont je me suis vanté auprès de vous pour savoir ce qui a provoqué la seconde. J'ai perdu le pari, Marquise. Je ne l'ai pas gagné, puisqu'il n'y eut pas de dîner. J'ai perdu bien davantage.`,
      `Message sixième. La Marquise au Vicomte. Alors, apprenez la vérité, puisque vous voilà sincère, et que cela vous va si mal. Clémence est ma cousine. Celle qui se marie. Pardonnez-moi : il n'y a pas de mariage. Il y avait un pari entre elle et moi, à votre sujet. Je soutenais qu'aucune femme ne pourrait jamais vous rendre sincère ; elle soutenait le contraire. Il paraît que j'ai perdu. Je m'en console mal. On ne joue pas impunément avec les cœurs, même avec ceux qu'on croyait en carton.`,
      `Message septième et dernier. Clémence à la Marquise. Ma chère cousine, je te remercie de m'avoir fait gagner. Nous partons samedi à Annecy. Ne nous écris pas. Il est en train d'apprendre à danser. Il est très mauvais. J'ai ri, pour la première fois depuis longtemps.`,
    ],
    questions: [
      {
        question: `What is the wager in the Marquise's first message?`,
        options: [`To get Clémence to laugh`, `To get a dinner with Clémence before the end of the month`, `To make Clémence fall in love within a week`, `To get Clémence to delete her profile`],
        correctIndex: 1,
        explanation: `"Je vous défie d'obtenir un dîner avant la fin du mois."`,
      },
      {
        question: `How does Clémence respond to the Vicomte's first witty message?`,
        options: [`She corrects a grammatical agreement in his sentence.`, `She blocks him.`, `She laughs and invites him out.`, `She sends him a quotation from Diderot.`],
        correctIndex: 0,
        explanation: `"Elle m'a répondu en corrigeant une faute d'accord dans ma phrase."`,
      },
      {
        question: `Why does the Vicomte say he has "lost" even though he has seen Clémence?`,
        options: [`She refused to see him again.`, `She laughed at him.`, `There was no dinner, and he has fallen genuinely in love.`, `He was seen at the library.`],
        correctIndex: 2,
        explanation: `"Je ne l'ai pas gagné, puisqu'il n'y eut pas de dîner. J'ai perdu bien davantage."`,
      },
      {
        question: `What does the Marquise reveal in her last message?`,
        options: [`She is secretly engaged to the Vicomte.`, `Clémence does not really exist.`, `She invented the dating app.`, `Clémence is her cousin, and the two women had their own bet about him.`],
        correctIndex: 3,
        explanation: `"Clémence est ma cousine [...] Il y avait un pari entre elle et moi, à votre sujet."`,
      },
    ],
  },
];

export const FR_C2_S03_ENGLISH: Record<string, string[]> = {
  "fr-c2-le-vin-etait-trop-noir": [
    `Beaune, November. The harvest had been over for a month, and the town had that morning-after look that auction rooms have once the bidding has stopped. I had been a sommelier for fifteen years in a three-star restaurant in Lyon, until the evening I told a minister his wine was corked. It was. That hadn't saved me. Since then I had been hiring out my nose to the highest bidder: insurers, swindled wine merchants, suspicious heirs. People called me Ndongo, or the Nose, depending on whether or not they were paying me.`,
    `She came in without knocking, which in Beaune is a way of saying you own vineyards. Clothilde Royer-Vergy, forty, cashmere coat, boots as clean as you never see during the harvest. She had run the Domaine des Vergy since her father's death in 2015, and she had modernised it from top to bottom: new barrels, a consultant oenologist, rounder, oakier wines that the Americans liked. She put a bottle on my desk. Nuits-Saint-Georges premier cru, 2005 vintage. "Seized in Hong Kong. The label is perfect, the cork is perfect. It's a fake. I want to know who."`,
    `I opened the bottle that same evening, alone, with the respect one owes to suspects. The colour was dark, almost black. I smelled it for a long time. Then I tasted it, held it in my mouth, let it go. And I understood that I had a problem. This fake was better than the real thing. There was blackcurrant in it, forest floor, a hint of iron, and that slightly wild austerity I hadn't found in a Vergy for ten years. I knew this wine. I had served it in Lyon, in old Royer's day. Someone, somewhere, was still making the father's wine.`,
    `It took me four days and as many coffees laced with calvados in the bistros of Nuits to follow the trail. It led to Villers-la-Faye, in the Hautes-Côtes, to a garage at the back of a yard where an old van was rusting under a walnut tree. Lucien Bichot, seventy-four, had been the cellar master of the Domaine des Vergy for thirty years. Clothilde had let him go in her first year, with a severance payment and a handshake. Since then he had been renting a plot from a cousin, making wine in his garage the old way, whole bunches, old barrels, and selling his casks to a middleman in Dijon who took care of the labels. "I'm not stealing anything from her," he told me, handing me a glass. "I'm giving back what she threw away."`,
    `I could have written my report right there, on the bonnet of the van. The names, the dates, the middleman, the fraud squad. That's what people expect of a private eye: that he bring back culprits the way a dog brings back partridges. But I'm not a dog. I'm a nose, and a nose has its loyalties. I drove back to Beaune with three unlabelled bottles in the boot.`,
    `I received her the next day in my office, shutters closed, three glasses lined up on a white cloth. A blind tasting, I told her, for the sake of method. The first glass was her genuine 2005; the second, her latest vintage; the third, the fake. She took her time. She was good, it must be said, better than her wines. At the third glass she stopped. She put the glass down, picked it up again, and I saw something come undone in her face, like a knot being pulled. "It's my father's," she said quietly.`,
    `She didn't press charges against Lucien. The middleman in Dijon was less lucky: he turned up in the papers, in the fraud column, between a truffle-smuggling ring and a fake-honey case. The following Monday, a big black four-by-four drove up the Hautes-Côtes road and stopped in front of a garage in Villers-la-Faye. I don't know what was said under the walnut tree. I only know that in the spring the Domaine des Vergy released a new cuvée, in small quantities, whole bunches, old barrels. It was called the Cuvée Lucien.`,
    `They paid my fee, plus a case. I still have it, at the back of a cupboard, between my revolver and my bad memories. In this line of work, the truth always has an aftertaste. That one tasted of blackcurrant and forest floor, with a hint of iron.`,
  ],
  "fr-c2-l-homme-qui-perdait-ses-mots": [
    `The first word Thomas Delvaux lost was "spoon". He noticed it one Tuesday morning, in his kitchen in Ixelles, in front of his coffee: he wanted to stir it and found nothing to do it with, either in the drawer or in his head. There were forks, knives, and between them a gap, clean and neat, like a tooth that has just been pulled. He stirred his coffee with the handle of a knife and told himself he was tired. He had been an interpreter at the European Parliament for twenty-two years; he spent his days catching other people's words on the fly, and sometimes, he thought, the nets give way.`,
    `At the office he asked a colleague what the object you eat soup with was called. She looked at him blankly. Soup, she told him, is drunk from the bowl, as everywhere, as always. In the interpreting booths, on the canteen menus, in the dictionaries of four languages that he feverishly consulted during the break, the word no longer existed, nor did the thing. No one had ever needed it. The world had closed over the absence with a frightening politeness.`,
    `The next day it was Sunday. He woke up, checked his phone and saw that the week now had six days, from Monday to Saturday, and that no one was complaining. The day after that, the word "drache" disappeared, that Belgian word for heavy downpours, and in Brussels, for the first time in living memory, it rained a fine, reasonable rain. Then it was the turn of "nonante", which took the number itself away with it: people now counted up to eighty-nine, politely skipped ten, and started again at a hundred.`,
    `He began to keep a list. The words left at night, one by one, in no apparent order, and took their objects with them the way tenants take their furniture. After a week he thought he had found a logic. He had not had soup since his mother died. He had done nothing on Sundays for years. He no longer said "drache" since he had been making a point, in the booth, of speaking Parisian French. The words that were leaving were the ones he no longer used. He had neglected them; they were drawing the only possible conclusion.`,
    `That night, trembling, he drew up an inventory of what he no longer said. He found things of no importance, kite, Liège waffle, and others that chilled him. "Sorry", which he had not uttered for a long time without following it with a "but". And "sister". He had a sister, Hélène, in Liège. They had not spoken since their mother's funeral, over a matter of a house, of furniture, of those things that seem enormous for three months and weigh nothing at all after ten years. It had been eleven years.`,
    `It was four in the morning. He understood that if the word left that night, Hélène would leave with it, not dead but never born, erased, and that no one, not even he when he woke, would remember her. He looked for her number in an old notebook. He dialled it. The phone rang for a long time in a house in Liège, and he repeated under his breath, to hold on to it, the way you hold someone back by the sleeve at the edge of a platform: sister, sister, sister.`,
    `A sleepy, furious voice answered. He did not know what to say. He said the first word that came to him, and it was the right one: "Sorry." There was a long silence. Then Hélène said: "Do you know what time it is, you idiot?" And she began to cry, and so did he, and they talked until day broke over Ixelles.`,
    `Sunday never quite came back. But the following Saturday Thomas took the train to Liège, and his sister served him pea soup in a bowl and, without thinking, handed him a small metal object that he looked at for a long time before finding its name again.`,
  ],
  "fr-c2-une-vie-a-rebours": [
    `2023. On the Dakar corniche, at the hour when the sun drops into the Atlantic like a coin into a piggy bank, Aïssatou Ndiaye, seventy-one, sits alone on the concrete bench facing the Mamelles. She has brought Ousmane's old transistor radio. She switches it on, looks for the station, comes across a song by Orchestra Baobab. She smiles. They never agreed about that song. He found it sublime; she found it too long. She listens to it to the end, for the first time, and for the first time she does not find it too long.`,
    `2009. Retirement drinks for M. Ousmane Diallo, history teacher at the Lycée Blaise-Diagne. In his speech, after thanking the inspector, his colleagues and thirty-four year groups of pupils, he turns to the front row: "Finally, I thank my wife, who has contradicted me every day for thirty years, and who was right half the time, which, for a historian, is an exceptional average." The headmaster gives him a watch; the pupils, a signed football; Aïssatou, nothing at all, since she has already told him everything. The whole room laughs. Aïssatou does not laugh. She counts on her fingers and finds he has underestimated the average.`,
    `1994. The CFA franc has just lost half its value, and the whole city is doing its sums out loud. At the Sandaga market, prices are rubbed out in chalk and new ones written up, and bread has doubled overnight. In a maternity ward in the Medina, during a power cut, a baby girl comes into the world by the light of a candle that Ousmane holds above the midwife with a trembling hand. She will be named Mariama, like Aïssatou's grandmother. Ousmane wanted Khady. They will discuss it later, for many years, with great pleasure.`,
    `1981. A wedding in Saint-Louis, in the courtyard of the family house, under the kapok trees. Aïssatou's mother is sulking: a teacher, with no money, who talks too much and writes badly. The groom insisted on Orchestra Baobab; the bride insisted that the same song not be played more than three times. They play it seven times. On the seventh she dances anyway, and that is the photo that will stay on the sideboard for forty years.`,
    `1979. A letter arrives from Paris, where Ousmane is preparing for the agrégation in a maid's room in the fifth arrondissement. It is four pages long. He writes about the snow, the cold, loneliness, and, in the turn of a complicated sentence, he admits that he thinks about her. Aïssatou reads it twice. Then she takes a red pen, corrects eleven spelling mistakes, and sends it back to him without another word. He replies by return of post: twelve pages, no mistakes. She rereads them three times, to check.`,
    `1978. In a car rapide racing from Rufisque towards the Plateau, packed, rattling, painted in bright colours, a young man in a white shirt stands up to give his seat to a young woman laden with books. She refuses. She does not sit, she says, on a stranger's politeness. He insists; she digs in her heels; they argue all the way to the Sandaga market about whether gallantry is a form of respect or of condescension. She gets off in a fury. On the seat she has left a book behind. He opens it. On the flyleaf, in careful handwriting: Aïssatou Ndiaye, and an address.`,
    `1978, the same day, at seven in the morning. In a small house in Rufisque, a young woman of twenty-six grabs her bag, her books, a mango, and looks for her shoes, grumbling. She is going to be late. Her mother shouts from the kitchen: "At least take one book fewer, you'll break your back!" Aïssatou does not listen to her. She never has. She steps out into the light, not knowing that she has her whole life ahead of her, or behind her, depending on which way you read it.`,
  ],
  "fr-c2-le-mot-de-la-fin": [
    `Maxence Dulac-Ferrand, honorary sociétaire of the Comédie-Française, had played the Misanthrope six times, the Miser eleven times and, once, at the Avignon festival, a tree, which he considered the summit of his career. But his life's work, the one he had been secretly working on since the age of forty-five, fitted into a single sentence: his last words. He had written them, crossed them out, rewritten them, tried them out in front of the mirror, in alexandrines, in prose, in Latin. He had finally settled on a version, which he kept folded in his wallet, behind his health insurance card: "The curtain falls; that is no reason for the audience to leave."`,
    `The first time he thought he was dying was in 2009, of a heart attack, in his dressing room, during the interval. He had time to seize the hand of a dresser, look her in the eyes and deliver the line with admirable diction. The dresser wept. The ambulance arrived. He was saved. Three weeks later he was back on stage, and the dresser, who had told the story to everyone, spoke to him thereafter only with the coldness of a deceived widow.`,
    `The second time was at eighty-one, from pneumonia, at the Lariboisière hospital. This time he had a larger audience: two nephews, a former stage partner and a journalist from Le Figaro, alerted by a nephew who had the inheritance in mind. He said his line. The journalist wrote it down. The next morning, the fever broke. The article, already written, never appeared, but the line itself went all round Paris, and young actors could be seen quoting it, laughing, at the bar of the Café de la Régence. The nephew never came back: he had, he said, already done his grieving.`,
    `The third time was the worst. A fall on the stairs of his building on the rue de Richelieu, one icy night. Before losing consciousness he had time to declaim the line to the caretaker, who answered: "Yes, Monsieur Dulac, I know, you've already done that one for me." He recovered, as far as his skull was concerned. As for the line, much less so. A last word you have said three times, he reflected, is no longer a last word: it's a routine.`,
    `At eighty-eight he moved into a retirement home in Neuilly, where he was treated with the slightly weary deference reserved for historic monuments. Only one person really talked to him: a thirty-year-old care assistant, Fatoumata Camara, who brought him his tea at four o'clock and made him recite Racine to keep his memory in trim. In return he told her backstage stories, three quarters of which were invented and the last quarter worse still. She knew the line, of course. Everybody did. One day she asked him whether he had thought of writing another one. He looked at her for a long time. "My dear child," he said, "one only has one last line. The problem is that one never knows which one it is."`,
    `He died on a Tuesday in March, at four in the afternoon, without warning anyone. Fatoumata was alone with him. She had just put down the tea. He raised the cup to his lips, grimaced, put it down, and said with an artist's immense weariness, lifting his hand as if to stop a rehearsal: "Wait, I'll do it again." Then he closed his eyes, and that was all.`,
    `The next day a journalist rang the retirement home. He wanted to know what the great Dulac-Ferrand's last words had been. Fatoumata thought for a moment, her hand on the receiver. She thought of the wallet, the health card, the forty years of work. Then she answered, in a firm voice, without the slightest hesitation: "He said: The curtain falls; that is no reason for the audience to leave." The journalist wrote it down. The line was engraved on his tomb in the Montmartre cemetery. And Fatoumata kept the real one to herself; she thought it was much better. She told it only once, to her mother, who laughed about it for a week.`,
  ],
  "fr-c2-les-liaisons-numeriques": [
    `First message. The Marquise to the Vicomte, sent at 11:47 p.m. You are bored, Vicomte, and a bored man becomes a danger to himself. I propose a diversion worthy of your talents. On that app you frequent without shame there is a certain Clémence, an architect, thirty-three, whose only introduction is these terrible words: No sport, no travel, no laughs. No one, to my knowledge, has had more than three messages out of her. I challenge you to get a dinner before the end of the month. The stakes? If you lose, you will accompany me to my cousin's wedding, in a suit, and you will dance.`,
    `Second message. The Vicomte to the Marquise, sent at 12:12 a.m. Madame, I accept, and I pity you. You are no doubt unaware that a display of coldness is only the modesty of overly sensitive souls, and that the best-defended stronghold is often the one awaiting only a proper siege. I shall begin with wit, continue with constancy and finish with indifference, the only weapon no one ever resists. I shall send you a bulletin of my progress every evening, like a general to his king. Prepare your cousin to dance with someone else.`,
    `Third message. The Vicomte to the Marquise, four days later. I must report on my campaign with a frankness that costs me. I opened with a witticism about Le Corbusier; she replied by correcting a grammatical agreement in my sentence. I put forward a quotation from Diderot; she pointed out that it was misattributed. I feigned indifference for forty-eight hours; she did not notice. Last night, at last, she wrote to me of her own accord to ask my opinion on the restoration of a traboule in the Croix-Rousse. We messaged until three in the morning. I do not yet know whether it is a victory.`,
    `Fourth message. The Marquise to the Vicomte. My poor friend, you are talking to me about traboules. I have known you for fifteen years, and I have never seen you talk about a traboule to a woman, or to anyone, you who only ever opened a book to slip a phone number into it. Take care: one begins by wanting to win a bet and ends up learning the history of Lyon's town planning. It has moreover come to my ears that you were seen on Saturday at the Part-Dieu library, in the architecture section. I no longer recognise you. Tell me it is a ruse.`,
    `Fifth message. The Vicomte to the Marquise, sent at 2:03 a.m. It is not a ruse. I saw her this evening. It was not a dinner, in the sense you meant: we walked for four hours on the slopes, she showed me staircases, courtyards, doors, and I did not make a single witticism. She did not laugh once, she had promised me as much. She only smiled, twice, and I would give all the conquests I have boasted of to you to know what caused the second. I have lost the bet, Marquise. I did not win it, since there was no dinner. I have lost far more.`,
    `Sixth message. The Marquise to the Vicomte. Then learn the truth, since here you are being sincere, and it suits you so poorly. Clémence is my cousin. The one who is getting married. Forgive me: there is no wedding. There was a bet between her and me, about you. I maintained that no woman could ever make you sincere; she maintained the opposite. It seems I have lost. I am taking it badly. One does not play with hearts with impunity, even with those one thought were made of cardboard.`,
    `Seventh and last message. Clémence to the Marquise. My dear cousin, thank you for letting me win. We are leaving for Annecy on Saturday. Don't write to us. He is learning to dance. He is very bad at it. I laughed, for the first time in a long while.`,
  ],
};

export const FR_C2_S03_GLOSSES: Record<string, StoryGloss[]> = {
  "fr-c2-le-vin-etait-trop-noir": [
    { es: "la gueule", en: "look, face (slang)", forms: ["gueule"] },
    { es: "flouer", en: "to swindle", forms: ["floués"] },
    { es: "le fût", en: "barrel, cask", forms: ["fûts"] },
    { es: "le millésime", en: "vintage", forms: ["millésime"] },
    { es: "le sous-bois", en: "forest floor (wine aroma)", forms: ["sous-bois"] },
    { es: "le noyer", en: "walnut tree", forms: ["noyer"] },
    { es: "le maître de chai", en: "cellar master", forms: ["chai"] },
    { es: "remercier", en: "to dismiss, let go (euphemism)", forms: ["remercié"] },
    { es: "la barrique", en: "wine cask", forms: ["barriques"] },
    { es: "la répression des fraudes", en: "the fraud squad (consumer authority)", forms: ["répression"] },
    { es: "à l'aveugle", en: "blind (tasting)", forms: ["l'aveugle"] },
    { es: "l'arrière-goût", en: "aftertaste", forms: ["arrière-goût"] },
  ],
  "fr-c2-l-homme-qui-perdait-ses-mots": [
    { es: "remuer", en: "to stir", forms: ["remuer", "remua"] },
    { es: "le manche", en: "handle", forms: ["manche"] },
    { es: "attraper au vol", en: "to catch on the fly", forms: ["vol"] },
    { es: "fébrilement", en: "feverishly", forms: ["fébrilement"] },
    { es: "la drache", en: "downpour (Belgian)", forms: ["drache"] },
    { es: "nonante", en: "ninety (Belgian, Swiss)", forms: ["nonante"] },
    { es: "laisser à l'abandon", en: "to neglect", forms: ["l'abandon"] },
    { es: "dresser l'inventaire", en: "to draw up a list", forms: ["dressa"] },
    { es: "glacer", en: "to chill, freeze (with fear)", forms: ["glacèrent"] },
    { es: "le cerf-volant", en: "kite", forms: ["cerf-volant"] },
    { es: "ensommeillé", en: "sleepy", forms: ["ensommeillée"] },
  ],
  "fr-c2-une-vie-a-rebours": [
    { es: "la tirelire", en: "piggy bank", forms: ["tirelire"] },
    { es: "le pot de départ", en: "leaving drinks", forms: ["pot"] },
    { es: "la promotion", en: "year group, class", forms: ["promotions"] },
    { es: "la lueur", en: "glow, glimmer", forms: ["lueur"] },
    { es: "la sage-femme", en: "midwife", forms: ["sage-femme"] },
    { es: "le fromager", en: "kapok tree", forms: ["fromagers"] },
    { es: "faire la tête", en: "to sulk", forms: ["tête"] },
    { es: "la chambre de bonne", en: "maid's room, attic room", forms: ["bonne"] },
    { es: "brinquebalant", en: "rattling, rickety", forms: ["brinquebalant"] },
    { es: "s'entêter", en: "to dig in one's heels", forms: ["s'entête"] },
    { es: "la page de garde", en: "flyleaf", forms: ["garde"] },
    { es: "maugréer", en: "to grumble", forms: ["maugréant"] },
  ],
  "fr-c2-le-mot-de-la-fin": [
    { es: "le sociétaire", en: "full member (of the Comédie-Française)", forms: ["sociétaire"] },
    { es: "raturer", en: "to cross out", forms: ["raturées"] },
    { es: "arrêter", en: "to settle on, fix", forms: ["arrêter"] },
    { es: "l'entracte", en: "interval, intermission", forms: ["l'entracte"] },
    { es: "l'habilleuse", en: "dresser (theatre)", forms: ["habilleuse", "l'habilleuse"] },
    { es: "le verglas", en: "black ice", forms: ["verglas"] },
    { es: "la réplique", en: "line (theatre); retort", forms: ["réplique"] },
    { es: "la déférence", en: "deference", forms: ["déférence"] },
    { es: "l'aide-soignante", en: "care assistant", forms: ["aide-soignante"] },
    { es: "la lassitude", en: "weariness", forms: ["lassitude"] },
    { es: "le combiné", en: "telephone receiver", forms: ["combiné"] },
  ],
  "fr-c2-les-liaisons-numeriques": [
    { es: "l'enjeu", en: "stakes", forms: ["l'enjeu"] },
    { es: "la pudeur", en: "modesty, reserve", forms: ["pudeur"] },
    { es: "le siège en règle", en: "a proper siege", forms: ["siège"] },
    { es: "la constance", en: "constancy, perseverance", forms: ["constance"] },
    { es: "le trait d'esprit", en: "witticism", forms: ["trait"] },
    { es: "feindre", en: "to feign, pretend", forms: ["feint"] },
    { es: "la traboule", en: "covered passage through Lyon buildings", forms: ["traboule"] },
    { es: "la ruse", en: "trick, ruse", forms: ["ruse"] },
    { es: "se vanter", en: "to boast", forms: ["vanté"] },
    { es: "impunément", en: "with impunity", forms: ["impunément"] },
  ],
};
