// Synced from cheneygross-afk/lengo:src/lib/stories/fr/batches/fr-c1-s04.ts by scripts/sync-content.mjs -- edit it there, not here.
import type { Story, StoryGloss } from "../../types";

// FR-C1 stories, batch 4 (see ../fr-a1.ts for the conventions).

export const FR_C1_S04_STORIES: Story[] = [
  {
    slug: "fr-c1-la-file-d-attente",
    level: "FR-C1",
    title: `La file d'attente`,
    subtitle: `A Parisian woman joins a long queue in the Marais without knowing what it is for.`,
    paragraphs: [
      `Je n'avais rien à faire ce samedi-là, ce qui, à Paris, est une situation suspecte qu'il convient de dissimuler au plus vite. Je remontais la rue Vieille-du-Temple quand j'ai vu la file. Une soixantaine de personnes, alignées le long du trottoir avec cette patience particulière qui signale, chez le Parisien, la proximité d'un produit rare. Je me suis placée derrière un jeune homme en veste de velours. Je ne savais pas ce qu'on attendait. C'était précisément ce qui rendait la chose irrésistible.`,
      `« C'est bien ici, pour le croissant ? » ai-je demandé au jeune homme, sur un ton dégagé. Il m'a regardée avec une pitié polie. Non, ce n'était pas pour le croissant, c'était pour la nouvelle collection d'une créatrice de sacs anversoise, en édition limitée. La dame devant lui s'est retournée : pas du tout, c'était une dégustation gratuite de vins orange. Un monsieur plus loin a affirmé qu'il s'agissait d'un casting pour une série. Chacun défendait sa version avec la certitude des gens qui n'en savent rien.`,
      `Au bout d'une heure, nous avions avancé de quatre mètres et nous étions devenus une petite société. Le jeune homme en velours s'appelait Ismaël et faisait une thèse sur les lichens. La dame aux vins orange, Mme Duchesne, avait été professeure de latin à Versailles et nous corrigeait la grammaire par réflexe. Le monsieur du casting, Patrick, avait apporté un thermos de café qu'il faisait circuler avec une générosité de chef de tribu. Derrière nous, la file s'était allongée jusqu'au coin de la rue des Rosiers.`,
      `Vers la deuxième heure, une rumeur a remonté la file : quelqu'un, devant, aurait aperçu une célébrité. On n'a jamais su laquelle. Puis une autre : il ne resterait plus que cinquante exemplaires. De quoi ? Peu importait. L'angoisse de la pénurie a soudé notre groupe d'une manière que je n'avais connue qu'aux enterrements et aux soldes. Mme Duchesne a fait le serment, si elle obtenait l'objet mystère avant nous, de le partager. Ismaël a demandé, très sérieusement, comment on partage un sac à main.`,
      `Vers la troisième heure, nous avons tourné le coin et découvert la porte. C'était l'entrée d'une petite galerie aux murs blancs. À l'intérieur, il n'y avait rien. Absolument rien, sinon une jeune femme assise sur un tabouret, qui tenait un compteur mécanique et appuyait dessus chaque fois que quelqu'un franchissait le seuil. Sur le mur, une plaque discrète : « La File. Performance participative. Du 1er au 30 juin. » Nous étions, sans le savoir, l'œuvre.`,
      `Patrick a protesté très fort qu'on se moquait du monde. Mme Duchesne a déclaré que c'était parfaitement scandaleux et, d'ailleurs, assez intelligent. Ismaël riait si fort qu'il a dû s'asseoir sur le trottoir. L'artiste, impassible, a cliqué quatre fois sur son compteur. Elle nous a dit qu'elle s'intéressait à « ce qui naît entre les gens quand ils attendent ensemble quelque chose qui n'existe pas ». J'ai pensé que c'était la définition la plus exacte qu'on m'ait jamais donnée de la vie à Paris, et peut-être de la vie tout court.`,
      `Nous sommes sortis par l'autre porte, un peu étourdis. Sur le trottoir, personne n'avait envie de partir. Patrick a proposé un verre ; Mme Duchesne a accepté à condition qu'il ne soit pas orange. Nous avons passé la soirée dans un bistrot de la rue de Bretagne, à refaire le monde et la file. Ismaël m'a expliqué les lichens pendant une heure, et je l'ai écouté avec un intérêt qui m'a étonnée moi-même.`,
      `Je ne dirai pas combien de fois je suis retournée faire la queue, ce mois-là. Disons que l'artiste me salue désormais d'un petit signe de tête, et qu'elle ne clique plus quand je passe. Ismaël et moi, nous arrivons généralement ensemble. Nous ne savons toujours pas ce que nous attendons. C'est, je crois, ce qui nous plaît.`,
    ],
    questions: [
      {
        question: `Why does the narrator join the queue?`,
        options: [
          `She wants a famous croissant.`,
          `Not knowing what it is for makes it irresistible.`,
          `A friend asked her to come.`,
          `She is going to an art exhibition.`,
        ],
        correctIndex: 1,
        explanation: `"Je ne savais pas ce qu'on attendait. C'était précisément ce qui rendait la chose irrésistible."`,
      },
      {
        question: `What does the narrator say about the people in the queue arguing over what it is for?`,
        options: [
          `They all agree it is a bakery.`,
          `They have read about it in the newspaper.`,
          `Each defends a version with the certainty of people who know nothing.`,
          `They ask the police.`,
        ],
        correctIndex: 2,
        explanation: `"Chacun défendait sa version avec la certitude des gens qui n'en savent rien."`,
      },
      {
        question: `What is behind the door?`,
        options: [
          `An empty gallery where the queue itself is the artwork`,
          `A shop selling limited-edition handbags`,
          `A free wine tasting`,
          `A casting for a TV series`,
        ],
        correctIndex: 0,
        explanation: `"À l'intérieur, il n'y avait rien... La File. Performance participative... Nous étions, sans le savoir, l'œuvre."`,
      },
      {
        question: `What does the ending suggest?`,
        options: [
          `The narrator is angry and never goes back.`,
          `The artist is arrested.`,
          `The narrator finally discovers what she was waiting for.`,
          `The narrator keeps coming back, enjoying the queue and Ismaël's company.`,
        ],
        correctIndex: 3,
        explanation: `She went back many times, and "Ismaël et moi, nous arrivons généralement ensemble."`,
      },
    ],
  },
  {
    slug: "fr-c1-le-tailleur-de-la-rue-blanchot",
    level: "FR-C1",
    title: `Le tailleur de la rue Blanchot`,
    subtitle: `A Dakar tailor knows that his most demanding customer is not the important man he claims to be.`,
    paragraphs: [
      `Mon atelier se trouve rue Blanchot, à Dakar, entre une boutique de téléphones et un marchand de café Touba. J'y couds depuis trente ans, d'abord avec mon père, puis seul, puis avec mes deux neveux, qui sont plus doués que moi pour les réseaux sociaux et moins doués pour les ourlets. Un bon tailleur, disait mon père, doit savoir deux choses : prendre les mesures d'un homme, et ne jamais les répéter. J'ai appliqué ce principe toute ma vie. Je vais faire une exception, puisque l'homme dont je parle ne lira jamais ceci.`,
      `Il s'appelle Amadou Fall. Il est entré chez moi pour la première fois il y a sept ans, en boubou froissé, et il m'a annoncé qu'il était conseiller au ministère de l'Équipement. Il lui fallait un costume pour une réception à la présidence, et vite. Il m'a parlé longuement de ses responsabilités, de ses voyages à Paris, des routes qu'il allait inaugurer. Je l'ai écouté en prenant ses mesures. Un tailleur sait beaucoup de choses par les mesures. Celui-là avait les épaules d'un homme qui porte des cartons, et le dos d'un homme qui passe ses journées assis au volant.`,
      `Je l'ai su avec certitude un mois plus tard. Je l'ai vu, par hasard, devant le ministère, en casquette, qui tenait la portière d'une grosse voiture noire pendant qu'en sortait un homme plus petit que lui, et beaucoup moins élégant, parce que ce n'était pas moi qui l'habillais. Amadou était chauffeur. Il m'a aperçu. Il a détourné les yeux. Le lendemain, il est venu chercher son costume comme si de rien n'était, et il m'a demandé, avec une assurance magnifique, si je pouvais lui faire un prix « entre gens de qualité ».`,
      `Je lui ai fait un prix. Je lui en ai fait pendant sept ans. Il commandait deux tenues par an, pour la Tabaski et pour la fin du Ramadan, toujours en bazin riche, toujours dans des couleurs que seul un ministre oserait porter, et il payait en trois fois, parfois en quatre. Mes neveux se moquaient de lui derrière son dos. Ils l'appelaient « Son Excellence ». Je les ai grondés. Un homme qui a besoin d'un titre pour entrer dans une boutique est un homme qui a souffert de ne pas en avoir, et ce n'est pas un sujet de plaisanterie.`,
      `Cette année, en septembre, il est arrivé avec un air que je ne lui connaissais pas. Sa fille aînée, Mariama, se mariait en décembre. Elle épousait le fils d'une famille importante de Saint-Louis, une vraie, avec un grand-père député et des oncles dans la magistrature. Amadou voulait un grand boubou brodé, le plus beau que j'aie jamais fait. Il m'a dit qu'il paierait tout, cette fois, d'avance. Il a posé une enveloppe sur ma table. Je savais ce que contenait cette enveloppe : six mois de salaire d'un chauffeur.`,
      `J'ai pris l'enveloppe et je l'ai rangée dans le tiroir. Puis j'ai travaillé six semaines sur ce boubou, la nuit, après la fermeture. Du bazin bleu indigo, des broderies d'or au col et aux manches, un motif que mon père m'avait appris et que je n'avais jamais utilisé pour personne. Mes neveux ne riaient plus. Ils venaient le soir me regarder coudre, sans rien dire, et l'un d'eux a fini par me demander pourquoi je me donnais tant de mal pour Son Excellence. Je lui ai répondu que je ne cousais pas pour Son Excellence, mais pour un père.`,
      `Le jour du mariage, j'étais invité. Je suis arrivé tard, discrètement. Amadou se tenait au milieu de la cour, dans son boubou bleu, et il était, je le dis sans orgueil, l'homme le plus élégant de la fête, plus élégant que le député. Quand il m'a vu, il a traversé la foule, m'a pris par le bras et m'a présenté à la famille du marié. « Mon ami Ousmane, a-t-il dit, le tailleur des ministres. » J'ai salué tout le monde, et je n'ai pas démenti. Un tailleur ne répète jamais les mesures.`,
      `Le lendemain, j'ai glissé l'enveloppe, intacte, dans la boîte aux lettres de Mariama, avec un mot : « Cadeau du tailleur des ministres. » Amadou n'en a jamais parlé. Mais il est revenu en janvier, en boubou froissé, et pour la première fois depuis sept ans, il ne m'a pas parlé du ministère. Il m'a parlé de sa fille. Nous avons pris un café Touba devant la boutique, comme deux hommes de qualité.`,
    ],
    questions: [
      {
        question: `How does Ousmane first guess that Amadou is not a ministry adviser?`,
        options: [
          `From his body: shoulders that carry boxes and a back that sits at the wheel all day`,
          `From his bad French`,
          `From his cheap shoes`,
          `From a phone call he overhears`,
        ],
        correctIndex: 0,
        explanation: `"Celui-là avait les épaules d'un homme qui porte des cartons, et le dos d'un homme qui passe ses journées assis au volant."`,
      },
      {
        question: `Why does Ousmane scold his nephews?`,
        options: [
          `They are bad at hemming.`,
          `They spend too much time on social media.`,
          `They mock Amadou, though a man who needs a title has suffered from lacking one.`,
          `They forget to take payment.`,
        ],
        correctIndex: 2,
        explanation: `"Un homme qui a besoin d'un titre... est un homme qui a souffert de ne pas en avoir, et ce n'est pas un sujet de plaisanterie."`,
      },
      {
        question: `What does Ousmane do with the envelope of money?`,
        options: [
          `He keeps it as payment.`,
          `He gives it back to Amadou in person.`,
          `He spends it on fabric.`,
          `He slips it unopened into the bride's letterbox as a gift.`,
        ],
        correctIndex: 3,
        explanation: `"j'ai glissé l'enveloppe, intacte, dans la boîte aux lettres de Mariama, avec un mot : Cadeau du tailleur des ministres."`,
      },
      {
        question: `What changes in Amadou's behavior at the end?`,
        options: [
          `He stops coming to the shop.`,
          `He no longer talks about the ministry; he talks about his daughter.`,
          `He becomes a real adviser.`,
          `He orders a new suit for himself.`,
        ],
        correctIndex: 1,
        explanation: `"pour la première fois depuis sept ans, il ne m'a pas parlé du ministère. Il m'a parlé de sa fille."`,
      },
    ],
  },
  {
    slug: "fr-c1-l-ete-des-cerises",
    level: "FR-C1",
    title: `L'été des cerises`,
    subtitle: `An old cherry grower in the Ardèche reluctantly hires a Syrian engineer for the harvest.`,
    paragraphs: [
      `Fernand Chabert avait soixante-dix-neuf ans, quatre hectares de cerisiers sur les pentes de Saint-Péray et une conviction inébranlable : personne, hormis lui, ne savait cueillir une cerise. Il fallait la prendre par la queue, d'un coup de pouce sec, sans meurtrir le fruit ni arracher l'œil qui donnerait la récolte suivante. Ses enfants étaient partis à Lyon, sa femme au cimetière, et les saisonniers, d'année en année, se faisaient plus rares et plus maladroits. Ce printemps-là, son genou lui interdit les échelles. Il dut se résoudre à embaucher.`,
      `L'association de Tournon lui envoya un homme d'une quarantaine d'années, grand, maigre, qui s'appelait Rami et qui avait été ingénieur en hydraulique à Alep. Fernand le considéra des pieds à la tête, avec la méfiance de ceux qui n'ont jamais quitté leur vallée. Il lui demanda s'il avait déjà cueilli des cerises. Rami répondit que non, mais qu'il avait, dans son enfance, cueilli des abricots chez son grand-père, près de Hama. Fernand grommela que l'abricot était un fruit de feignant, et lui tendit un panier.`,
      `Les premiers jours furent pénibles. Fernand suivait Rami d'arbre en arbre, en boitant, pour lui reprocher sa lenteur, puis sa précipitation, puis la manière dont il posait l'échelle. Rami ne répondait rien. Il écoutait, il recommençait. Au bout d'une semaine, Fernand dut admettre, à part lui, que l'homme cueillait mieux que ses propres fils ne l'avaient jamais fait. Il ne le lui dit pas. Il se contenta de lui laisser, un midi, la moitié de son saucisson, ce qui, dans la langue de Fernand, valait un discours.`,
      `Il y avait, au bout du verger, un vieux cerisier que Fernand ne laissait toucher à personne. C'était un bigarreau planté en 1971, l'année de la naissance de son fils aîné, Jean-Pierre. Jean-Pierre était mort à vingt ans, sur la route de Valence, un soir de brouillard. L'arbre, depuis quelques années, dépérissait : les branches noircissaient, les fruits se faisaient rares. Fernand refusait de l'arracher. Il passait devant chaque matin sans le regarder, comme on passe devant une porte qu'on ne veut plus ouvrir.`,
      `Ce fut Rami qui posa la question, un soir, en buvant le vin de noix que Fernand avait fini par lui offrir. Fernand ne répondit pas tout de suite. Puis il raconta, à sa manière, par fragments, en regardant ailleurs. Rami l'écouta sans l'interrompre. Quand le vieil homme eut fini, il dit seulement que chez lui aussi, à Alep, il y avait eu un arbre planté pour un enfant, et qu'il n'avait pas pu l'emporter. Ils restèrent longtemps silencieux, deux hommes qui ne se ressemblaient en rien et qui savaient exactement la même chose.`,
      `Le lendemain, Rami demanda la permission d'essayer quelque chose. Il avait appris de son grand-père l'art de la greffe. Il prit sur le vieux bigarreau les rares rameaux encore sains et les greffa, avec une patience d'horloger, sur un jeune porte-greffe vigoureux que Fernand gardait en pépinière. Fernand le regarda faire, appuyé sur sa canne, l'air sceptique. Il fit remarquer que ce n'était pas la saison, que ça ne prendrait jamais, que les ingénieurs croyaient tout savoir. Puis il alla chercher de la ficelle et du mastic.`,
      `La récolte s'acheva à la mi-juillet. Rami partit pour Valence, où on lui proposait un poste dans un bureau d'études. Les deux hommes se serrèrent la main dans la cour, longuement, sans un mot de trop. Fernand lui donna un cageot de cerises et une bouteille de vin de noix, et lui dit de revenir l'année suivante, s'il n'avait rien de mieux à faire, ce qui, dans sa langue, voulait dire qu'il l'attendrait.`,
      `Au printemps suivant, le jeune arbre greffé se couvrit de fleurs blanches. Elles étaient un peu fragiles, un peu tardives, mais elles étaient bien là. Fernand les photographia avec le téléphone que ses enfants lui avaient offert et dont il ne s'était jamais servi. Il mit deux jours à trouver comment envoyer la photo. Il n'écrivit rien d'autre. Rami répondit le soir même, et la réponse ne contenait qu'un mot, que Fernand ne comprit pas et qu'il se fit traduire par sa petite-fille : en arabe, cela voulait dire « vivant ».`,
    ],
    questions: [
      {
        question: `Why does Fernand have to hire someone this year?`,
        options: [
          `His sons have refused to help.`,
          `His knee no longer lets him climb ladders.`,
          `He has bought more land.`,
          `The association ordered him to.`,
        ],
        correctIndex: 1,
        explanation: `"Ce printemps-là, son genou lui interdit les échelles. Il dut se résoudre à embaucher."`,
      },
      {
        question: `How does Fernand show his approval of Rami's work?`,
        options: [
          `He thanks him warmly.`,
          `He raises his pay.`,
          `He gives him half his sausage, which for him is like a speech.`,
          `He lets him pick the old tree.`,
        ],
        correctIndex: 2,
        explanation: `"Il se contenta de lui laisser, un midi, la moitié de son saucisson, ce qui, dans la langue de Fernand, valait un discours."`,
      },
      {
        question: `Why won't Fernand cut down the old cherry tree?`,
        options: [
          `It was planted the year his son, who later died, was born.`,
          `It produces his best cherries.`,
          `His wife planted it.`,
          `The law forbids it.`,
        ],
        correctIndex: 0,
        explanation: `It was planted "en 1971, l'année de la naissance de son fils aîné, Jean-Pierre", who "était mort à vingt ans".`,
      },
      {
        question: `What does Fernand's final reaction to the grafting show?`,
        options: [
          `He has always trusted engineers.`,
          `He forbids Rami to touch the tree.`,
          `He thinks the graft will work in summer.`,
          `Despite his skeptical words, he helps by fetching string and grafting wax.`,
        ],
        correctIndex: 3,
        explanation: `After his objections, "il alla chercher de la ficelle et du mastic".`,
      },
    ],
  },
  {
    slug: "fr-c1-le-double",
    level: "FR-C1",
    title: `Le double`,
    subtitle: `A cautious Geneva actuary keeps being told he was seen in places he has never been.`,
    paragraphs: [
      `La première fois, Thomas Reymond n'y prêta pas attention. Une collègue lui dit, un lundi, qu'elle l'avait vu samedi aux Bains des Pâquis, en maillot, en train de plonger du grand plongeoir. Thomas, actuaire dans une banque privée de la rue du Rhône, n'avait jamais plongé de sa vie. Il ne se baignait pas dans le lac, qu'il jugeait froid et statistiquement imprudent. Il répondit qu'elle avait dû se tromper. Elle haussa les épaules. « Il te ressemblait drôlement, en tout cas. Il riait. »`,
      `La deuxième fois, ce fut sa voisine de palier, Mme Golay, qui le remercia pour les fleurs. Quelles fleurs ? Celles qu'il avait achetées au marché de Plainpalais, jeudi, et qu'il avait offertes, en passant, à la vieille dame du rez-de-chaussée. Thomas, jeudi, avait travaillé jusqu'à vingt et une heures sur un modèle de risque de longévité. Il n'achetait jamais de fleurs. Il trouvait le rapport entre leur prix et leur durée de vie difficilement justifiable.`,
      `Les signalements se multiplièrent pendant tout l'été. On l'avait vu danser, pendant la Fête de la musique, sur une place de Carouge. On l'avait vu au bord de l'Arve, en train de lire de la poésie à voix haute à une femme rousse. On l'avait vu dans un café de la vieille ville engager la conversation avec des inconnus, éclater de rire, payer la tournée. Chaque fois, les témoins décrivaient le même homme : son visage, sa taille, sa coupe de cheveux, mais un homme qui semblait, disait-on, « plus vivant ». Personne ne disait « plus heureux ». C'était pire.`,
      `Thomas tint un registre, comme il l'aurait fait d'une série de sinistres. Il nota les dates, les lieux, les heures. Il calcula des probabilités. Il consulta, en se sentant ridicule, un médecin, qui lui demanda s'il lui arrivait d'avoir des absences, de perdre la notion du temps. Il répondit que non, bien sûr. Puis il rentra chez lui, ouvrit son agenda et constata qu'il était incapable de se rappeler ce qu'il avait fait les samedis précédents. Il les avait passés, supposait-il, à travailler. Il n'en gardait aucun souvenir, ce qui, à la réflexion, était peut-être la même chose.`,
      `Il décida de le traquer. Un dimanche de septembre, sur la foi d'un renseignement, il se posta sur le pont du Mont-Blanc, à l'heure où le jet d'eau s'illumine. Il attendit deux heures. Puis il le vit. L'homme marchait vers lui, de l'autre côté du pont, en chemise claire, une veste sur l'épaule. Il avait exactement son visage, son allure un peu raide, et pourtant quelque chose différait, que Thomas mit un long moment à identifier : l'homme regardait le lac, les mouettes, les passants, comme s'il les voyait pour la première fois.`,
      `Thomas traversa. Il s'arrêta à deux mètres de lui. L'autre le regarda à son tour, sans surprise, avec une sorte de bienveillance amusée, comme on regarde un ami qui arrive en retard à un rendez-vous fixé depuis longtemps. Ni l'un ni l'autre ne parla. Un tramway passa derrière eux. Quand Thomas reporta les yeux sur le trottoir, il n'y avait plus personne, sinon une mouette sur la rambarde et, dans la vitre d'un bus arrêté au feu, son propre reflet, en chemise claire, une veste sur l'épaule.`,
      `Il ne raconta cette scène à personne. Le lundi suivant, il ne prit pas le tram. Il marcha jusqu'à la banque, en passant par le marché, et il acheta un bouquet de dahlias qu'il posa sur le bureau de sa collègue, sans explication. À midi, il alla aux Bains des Pâquis. Il n'osa pas monter au grand plongeoir. Il se contenta de descendre l'échelle, marche après marche, dans l'eau froide et statistiquement imprudente du lac. Il resta longtemps à flotter, les yeux ouverts sur le ciel.`,
      `Depuis cet automne-là, plus personne ne signale à Thomas Reymond qu'on l'a vu ailleurs. Ses collègues trouvent qu'il a changé, sans savoir dire en quoi. Mme Golay prétend qu'il siffle dans l'escalier. Lui, il a cessé de tenir son registre. Il lui arrive seulement, certains soirs, de croiser son reflet dans une vitre et de lui adresser un petit signe de tête, comme à quelqu'un qui aurait enfin trouvé où loger.`,
    ],
    questions: [
      {
        question: `Why is the colleague's sighting at the Bains des Pâquis surprising to Thomas?`,
        options: [
          `He was abroad that weekend.`,
          `He never swims in the lake, which he considers cold and statistically risky.`,
          `He doesn't know the colleague.`,
          `The baths were closed.`,
        ],
        correctIndex: 1,
        explanation: `"Il ne se baignait pas dans le lac, qu'il jugeait froid et statistiquement imprudent."`,
      },
      {
        question: `What do all the witnesses say about the double?`,
        options: [
          `He looks like Thomas but seems "more alive".`,
          `He is older than Thomas.`,
          `He has a different haircut.`,
          `He looks sad and tired.`,
        ],
        correctIndex: 0,
        explanation: `They describe the same man, "mais un homme qui semblait, disait-on, plus vivant".`,
      },
      {
        question: `What troubling discovery does Thomas make after seeing the doctor?`,
        options: [
          `He has lost his diary.`,
          `He has been sleepwalking.`,
          `He has a twin brother.`,
          `He cannot remember what he did on previous Saturdays.`,
        ],
        correctIndex: 3,
        explanation: `"il était incapable de se rappeler ce qu'il avait fait les samedis précédents".`,
      },
      {
        question: `What does Thomas do after the encounter on the bridge?`,
        options: [
          `He reports the double to the police.`,
          `He moves to another city.`,
          `He starts doing the things the double did: buying flowers, swimming in the lake.`,
          `He stops going to work.`,
        ],
        correctIndex: 2,
        explanation: `He buys "un bouquet de dahlias" and goes to the Bains des Pâquis, into "l'eau froide et statistiquement imprudente du lac".`,
      },
    ],
  },
  {
    slug: "fr-c1-le-silence-de-monsieur-lambert",
    level: "FR-C1",
    title: `Le silence de monsieur Lambert`,
    subtitle: `A notoriously talkative retired notary loses a bet and must stay silent for a whole family holiday in Saint-Malo.`,
    paragraphs: [
      `Maître Jean-Paul Lambert, notaire honoraire à Rennes, était connu dans toute l'Ille-et-Vilaine pour deux choses : la rigueur de ses actes et l'interminable longueur de ses phrases. On disait de lui qu'il pouvait lire un testament de trois pages en une heure et demie, tant il avait d'anecdotes à placer entre les alinéas. Sa famille l'aimait beaucoup, de loin de préférence, et l'écoutait peu. Il ne s'en était jamais aperçu, car il n'avait jamais laissé à personne le temps de le lui dire.`,
      `Ce fut son petit-fils Noé, douze ans, qui provoqua la catastrophe. Le premier soir des vacances, dans la grande maison louée face aux remparts de Saint-Malo, il paria avec son grand-père qu'il était incapable de se taire une semaine entière. L'enjeu était considérable : si Jean-Paul gagnait, Noé lirait les Mémoires d'outre-tombe pendant l'été ; s'il perdait, Jean-Paul ferait le saut du plongeoir de la piscine de Bon-Secours, à marée haute, devant toute la famille. Le notaire, piqué au vif, accepta, et commença aussitôt un discours sur la valeur juridique du pari, que Noé interrompit en déclenchant le chronomètre.`,
      `Les deux premiers jours furent un supplice. Jean-Paul ouvrait la bouche cent fois par heure, la refermait, rougissait, griffonnait sur un carnet des remarques que personne ne lisait. Le troisième jour, il se produisit une chose étrange : on commença à lui parler. Puisqu'il ne pouvait pas répondre, ni commenter, ni enchaîner sur un souvenir de 1987, chacun se mit à lui confier ce qu'il n'avait jamais pu dire. Sa fille lui avoua qu'elle détestait son métier d'expert-comptable et rêvait d'ouvrir une librairie. Son gendre lui raconta sa peur de vieillir. Noé lui montra des poèmes qu'il écrivait en cachette.`,
      `Jean-Paul écoutait. Il découvrait, avec un étonnement croissant, que sa famille était peuplée d'inconnus passionnants. Il découvrit surtout qu'écouter était un acte physique, épuisant, qui demandait de ne pas préparer sa réponse pendant que l'autre parlait. Le soir, sur les remparts, il regardait le soleil se coucher derrière le Grand Bé, et il lui semblait entendre, pour la première fois depuis des années, le bruit de la mer, que sa propre voix avait toujours couvert.`,
      `Seule sa femme, Monique, ne lui confia rien. Elle se contentait de le regarder, avec un sourire un peu triste, un peu moqueur, comme si elle attendait quelque chose. Le sixième soir, alors qu'ils marchaient seuls sur la plage du Sillon, elle s'arrêta et lui dit qu'en quarante-deux ans de mariage, elle n'avait jamais réussi à lui dire une chose, une seule, parce qu'il parlait toujours au moment où elle allait la dire. Elle voulait apprendre à naviguer. Elle en rêvait depuis l'enfance. Elle voulait qu'ils prennent ensemble, à la rentrée, des cours de voile aux Glénan.`,
      `Jean-Paul la regarda. Il avait dans la bouche, toute prête, une phrase de vingt lignes sur son mal de mer, sur l'âge, sur le prix des stages, sur un client qui s'était noyé à Dinard en 1994. Il sentit cette phrase monter comme une marée. Il pensa au pari, au plongeoir, à Noé. Puis il pensa qu'il n'avait jamais rien entendu de plus important en quarante-deux ans, et que le pari, au fond, n'avait plus aucune importance.`,
      `Il ouvrit la bouche et dit : « Oui. » Ce fut tout. Monique éclata de rire, puis de larmes, puis les deux à la fois. Le lendemain matin, devant toute la famille réunie, maître Jean-Paul Lambert, notaire honoraire, soixante-quatorze ans, en maillot de bain à rayures, sauta du plongeoir de Bon-Secours dans une eau à quinze degrés. Il remonta à la surface en hurlant de froid et, pour la première fois de sa vie, sans rien ajouter.`,
    ],
    questions: [
      {
        question: `Why had Jean-Paul never realized that his family didn't listen to him?`,
        options: [
          `Because they pretended to be interested`,
          `Because he never gave anyone time to tell him`,
          `Because he was deaf`,
          `Because he rarely saw them`,
        ],
        correctIndex: 1,
        explanation: `"il n'avait jamais laissé à personne le temps de le lui dire".`,
      },
      {
        question: `What happens on the third day of his silence?`,
        options: [
          `He gives up the bet.`,
          `He falls ill.`,
          `His family starts confiding things they had never been able to tell him.`,
          `He writes a long letter to his wife.`,
        ],
        correctIndex: 2,
        explanation: `"chacun se mit à lui confier ce qu'il n'avait jamais pu dire".`,
      },
      {
        question: `What had Monique never managed to tell him?`,
        options: [
          `That she wanted to learn to sail with him`,
          `That she wanted a divorce`,
          `That she hated Saint-Malo`,
          `That she had written poems`,
        ],
        correctIndex: 0,
        explanation: `"Elle voulait apprendre à naviguer... Elle voulait qu'ils prennent ensemble... des cours de voile aux Glénan."`,
      },
      {
        question: `Why does Jean-Paul jump off the diving board at the end?`,
        options: [
          `To impress his grandson`,
          `Because he enjoys cold water`,
          `To win a second bet`,
          `Because by answering "Oui" to his wife he lost the bet, and he accepts the forfeit`,
        ],
        correctIndex: 3,
        explanation: `He broke his silence with "Oui", so he does the forfeit: he "sauta du plongeoir de Bon-Secours".`,
      },
    ],
  },
];

export const FR_C1_S04_ENGLISH: Record<string, string[]> = {
  "fr-c1-la-file-d-attente": [
    `I had nothing to do that Saturday, which in Paris is a suspicious situation best concealed as quickly as possible. I was walking up the rue Vieille-du-Temple when I saw the queue. About sixty people, lined up along the pavement with that particular patience which, in a Parisian, signals the nearness of a rare product. I took my place behind a young man in a corduroy jacket. I didn't know what we were waiting for. That was precisely what made it irresistible.`,
    `"Is this the right place for the croissant?" I asked the young man, in a casual tone. He looked at me with polite pity. No, it wasn't for the croissant, it was for the new limited-edition collection of a handbag designer from Antwerp. The lady in front of him turned round: not at all, it was a free tasting of orange wines. A gentleman further along stated that it was a casting for a TV series. Each defended their version with the certainty of people who know nothing about it.`,
    `After an hour, we had moved forward four meters and had become a little society. The young man in corduroy was called Ismaël and was doing a doctorate on lichens. The orange-wine lady, Mme Duchesne, had taught Latin in Versailles and corrected our grammar out of reflex. The casting gentleman, Patrick, had brought a thermos of coffee which he passed round with the generosity of a tribal chief. Behind us, the queue had grown as far as the corner of the rue des Rosiers.`,
    `Around the second hour, a rumor came back down the queue: someone at the front had apparently spotted a celebrity. We never found out who. Then another: there were supposedly only fifty left. Of what? It didn't matter. The fear of scarcity bound our group together in a way I had only known at funerals and sales. Mme Duchesne swore that if she got the mystery object before us, she would share it. Ismaël asked, very seriously, how you share a handbag.`,
    `Around the third hour we turned the corner and discovered the door. It was the entrance to a small white-walled gallery. Inside, there was nothing. Absolutely nothing, except a young woman sitting on a stool, holding a mechanical counter and pressing it each time someone crossed the threshold. On the wall, a discreet plaque: "The Queue. Participatory performance. June 1 to 30." Without knowing it, we were the artwork.`,
    `Patrick protested very loudly that this was taking people for fools. Mme Duchesne declared that it was utterly scandalous and, for that matter, rather clever. Ismaël laughed so hard he had to sit down on the pavement. The artist, impassive, clicked her counter four times. She told us she was interested in "what is born between people when they wait together for something that doesn't exist". I thought it was the most accurate definition anyone had ever given me of life in Paris, and perhaps of life, full stop.`,
    `We left by the other door, a little dazed. On the pavement, nobody felt like leaving. Patrick suggested a drink; Mme Duchesne accepted on condition it wasn't orange. We spent the evening in a bistro on the rue de Bretagne, putting the world and the queue to rights. Ismaël explained lichens to me for an hour, and I listened with an interest that surprised even me.`,
    `I won't say how many times I went back to queue that month. Let's just say the artist now greets me with a little nod and no longer clicks when I go through. Ismaël and I usually arrive together. We still don't know what we're waiting for. That, I think, is what we like about it.`,
  ],
  "fr-c1-le-tailleur-de-la-rue-blanchot": [
    `My workshop is on the rue Blanchot in Dakar, between a phone shop and a café Touba seller. I've been sewing there for thirty years, first with my father, then alone, then with my two nephews, who are better than me at social media and worse at hems. A good tailor, my father used to say, must know two things: how to take a man's measurements, and never to repeat them. I've applied that principle all my life. I'm going to make an exception, since the man I'm talking about will never read this.`,
    `His name is Amadou Fall. He came into my shop for the first time seven years ago, in a crumpled boubou, and announced that he was an adviser at the Ministry of Infrastructure. He needed a suit for a reception at the presidential palace, and fast. He talked at length about his responsibilities, his trips to Paris, the roads he was going to open. I listened to him while taking his measurements. A tailor learns a lot from measurements. This one had the shoulders of a man who carries boxes and the back of a man who spends his days sitting at the wheel.`,
    `I knew for certain a month later. I saw him, by chance, outside the ministry, in a cap, holding the door of a big black car while a man stepped out who was shorter than him, and much less elegant, because I wasn't the one dressing him. Amadou was a driver. He saw me. He looked away. The next day he came to collect his suit as if nothing had happened and asked me, with magnificent self-assurance, whether I could give him a price "between people of quality".`,
    `I gave him a price. I gave him prices for seven years. He ordered two outfits a year, for Tabaski and for the end of Ramadan, always in bazin riche, always in colors only a minister would dare to wear, and he paid in three installments, sometimes four. My nephews made fun of him behind his back. They called him "His Excellency". I scolded them. A man who needs a title to walk into a shop is a man who has suffered from not having one, and that is no joking matter.`,
    `This year, in September, he arrived with a look I'd never seen on him. His eldest daughter, Mariama, was getting married in December. She was marrying the son of an important family from Saint-Louis, a real one, with a grandfather in parliament and uncles in the judiciary. Amadou wanted a grand embroidered boubou, the most beautiful I had ever made. He told me he would pay for everything this time, in advance. He put an envelope on my table. I knew what that envelope held: six months of a driver's wages.`,
    `I took the envelope and put it away in the drawer. Then I worked for six weeks on that boubou, at night, after closing. Indigo-blue bazin, gold embroidery at the collar and sleeves, a pattern my father had taught me and that I had never used for anyone. My nephews stopped laughing. They came in the evenings to watch me sew, without a word, and one of them finally asked why I was going to so much trouble for His Excellency. I told him I wasn't sewing for His Excellency, but for a father.`,
    `On the wedding day I was invited. I arrived late, discreetly. Amadou was standing in the middle of the courtyard in his blue boubou, and he was, I say it without pride, the most elegant man at the celebration, more elegant than the member of parliament. When he saw me, he crossed the crowd, took me by the arm and introduced me to the groom's family. "My friend Ousmane," he said, "tailor to ministers." I greeted everyone, and I didn't deny it. A tailor never repeats the measurements.`,
    `The next day I slipped the envelope, untouched, into Mariama's letterbox, with a note: "A gift from the tailor to ministers." Amadou never mentioned it. But he came back in January, in a crumpled boubou, and for the first time in seven years he didn't talk to me about the ministry. He talked to me about his daughter. We drank a café Touba outside the shop, like two men of quality.`,
  ],
  "fr-c1-l-ete-des-cerises": [
    `Fernand Chabert was seventy-nine, had four hectares of cherry trees on the slopes of Saint-Péray and an unshakable conviction: nobody but him knew how to pick a cherry. You had to take it by the stalk, with a sharp flick of the thumb, without bruising the fruit or tearing off the bud that would give the next harvest. His children had left for Lyon, his wife for the cemetery, and the seasonal workers, year after year, grew scarcer and clumsier. That spring his knee forbade him ladders. He had to resign himself to hiring someone.`,
    `The association in Tournon sent him a man of about forty, tall and thin, called Rami, who had been a hydraulic engineer in Aleppo. Fernand looked him up and down with the distrust of those who have never left their valley. He asked if he had ever picked cherries. Rami said no, but that as a child he had picked apricots at his grandfather's, near Hama. Fernand grumbled that the apricot was a lazy man's fruit, and handed him a basket.`,
    `The first days were hard going. Fernand followed Rami from tree to tree, limping, to criticize his slowness, then his haste, then the way he set up the ladder. Rami said nothing. He listened, he started again. After a week, Fernand had to admit, privately, that the man picked better than his own sons ever had. He didn't tell him. He merely left him, one lunchtime, half of his saucisson, which, in Fernand's language, was worth a speech.`,
    `At the end of the orchard was an old cherry tree that Fernand let no one touch. It was a bigarreau planted in 1971, the year his eldest son, Jean-Pierre, was born. Jean-Pierre had died at twenty, on the Valence road, one foggy evening. For some years the tree had been withering: the branches were blackening, the fruit growing scarce. Fernand refused to pull it up. He walked past it every morning without looking at it, the way you walk past a door you no longer want to open.`,
    `It was Rami who asked the question, one evening, drinking the walnut wine Fernand had eventually offered him. Fernand didn't answer straight away. Then he told the story, in his own way, in fragments, looking elsewhere. Rami listened without interrupting. When the old man had finished, he said only that back home too, in Aleppo, there had been a tree planted for a child, and that he hadn't been able to take it with him. They sat in silence for a long time, two men who had nothing in common and who knew exactly the same thing.`,
    `The next day Rami asked permission to try something. He had learned the art of grafting from his grandfather. He took the few still-healthy shoots from the old bigarreau and grafted them, with a watchmaker's patience, onto a vigorous young rootstock that Fernand kept in his nursery. Fernand watched him, leaning on his stick, looking skeptical. He pointed out that it wasn't the season, that it would never take, that engineers thought they knew everything. Then he went to fetch string and grafting wax.`,
    `The harvest ended in mid-July. Rami left for Valence, where he had been offered a job in an engineering consultancy. The two men shook hands in the yard, for a long time, without a word too many. Fernand gave him a crate of cherries and a bottle of walnut wine, and told him to come back the following year if he had nothing better to do, which, in his language, meant he would be waiting for him.`,
    `The following spring, the young grafted tree was covered in white blossom. It was a little fragile, a little late, but it was there. Fernand photographed it with the phone his children had given him and had never used. It took him two days to work out how to send the photo. He wrote nothing else. Rami replied that same evening, and the reply contained only one word, which Fernand didn't understand and had his granddaughter translate: in Arabic, it meant "alive".`,
  ],
  "fr-c1-le-double": [
    `The first time, Thomas Reymond paid no attention. A colleague told him one Monday that she had seen him on Saturday at the Bains des Pâquis, in swimming trunks, diving off the high board. Thomas, an actuary at a private bank on the rue du Rhône, had never dived in his life. He didn't swim in the lake, which he considered cold and statistically imprudent. He replied that she must have been mistaken. She shrugged. "Well, he looked an awful lot like you. He was laughing."`,
    `The second time, it was his neighbor across the landing, Mme Golay, who thanked him for the flowers. What flowers? The ones he had bought at the Plainpalais market on Thursday and given, in passing, to the old lady on the ground floor. On Thursday, Thomas had worked until nine in the evening on a longevity risk model. He never bought flowers. He found the ratio between their price and their lifespan hard to justify.`,
    `The reports multiplied all summer. He had been seen dancing, during the Fête de la musique, on a square in Carouge. He had been seen on the banks of the Arve reading poetry aloud to a red-haired woman. He had been seen in a café in the old town striking up conversations with strangers, bursting out laughing, buying a round. Each time, the witnesses described the same man: his face, his height, his haircut, but a man who seemed, people said, "more alive". Nobody said "happier". That was worse.`,
    `Thomas kept a register, as he would have done for a series of insurance claims. He noted the dates, the places, the times. He calculated probabilities. Feeling ridiculous, he consulted a doctor, who asked him whether he ever had blackouts, lost track of time. He said no, of course. Then he went home, opened his diary and found that he was unable to remember what he had done on the previous Saturdays. He had spent them, he supposed, working. He had no memory of them, which, on reflection, was perhaps the same thing.`,
    `He decided to track him down. One Sunday in September, acting on a tip, he stationed himself on the Mont-Blanc bridge at the hour when the Jet d'Eau lights up. He waited two hours. Then he saw him. The man was walking toward him on the other side of the bridge, in a pale shirt, a jacket over his shoulder. He had exactly his face, his slightly stiff bearing, and yet something was different, which Thomas took a long time to identify: the man was looking at the lake, the gulls, the passers-by, as if he were seeing them for the first time.`,
    `Thomas crossed over. He stopped two meters from him. The other man looked back at him, without surprise, with a kind of amused kindness, the way you look at a friend who turns up late for a long-standing appointment. Neither of them spoke. A tram passed behind them. When Thomas looked back at the pavement, there was no one there, except a gull on the railing and, in the window of a bus stopped at the lights, his own reflection, in a pale shirt, a jacket over his shoulder.`,
    `He told no one about this scene. The following Monday he didn't take the tram. He walked to the bank by way of the market and bought a bunch of dahlias, which he put on his colleague's desk without explanation. At lunchtime he went to the Bains des Pâquis. He didn't dare climb to the high board. He simply went down the ladder, rung by rung, into the cold and statistically imprudent water of the lake. He stayed floating for a long time, his eyes open to the sky.`,
    `Since that autumn, nobody has told Thomas Reymond that he was seen somewhere else. His colleagues think he has changed, without being able to say how. Mme Golay claims he whistles on the stairs. He has stopped keeping his register. Just sometimes, in the evening, he catches his reflection in a window and gives it a little nod, as to someone who has at last found a place to live.`,
  ],
  "fr-c1-le-silence-de-monsieur-lambert": [
    `Maître Jean-Paul Lambert, honorary notary in Rennes, was known throughout the Ille-et-Vilaine for two things: the rigor of his deeds and the interminable length of his sentences. It was said that he could read a three-page will in an hour and a half, so many anecdotes did he have to slip in between the clauses. His family loved him dearly, preferably from a distance, and listened to him little. He had never noticed, because he had never left anyone the time to tell him.`,
    `It was his grandson Noé, twelve, who brought about the catastrophe. On the first evening of the holiday, in the big rented house facing the ramparts of Saint-Malo, he bet his grandfather that he couldn't keep quiet for a whole week. The stakes were considerable: if Jean-Paul won, Noé would read Chateaubriand's Mémoires d'outre-tombe over the summer; if he lost, Jean-Paul would jump off the diving board of the Bon-Secours pool, at high tide, in front of the whole family. The notary, stung to the quick, accepted, and immediately began a speech on the legal validity of bets, which Noé interrupted by starting the stopwatch.`,
    `The first two days were torture. Jean-Paul opened his mouth a hundred times an hour, closed it again, blushed, scribbled remarks in a notebook that nobody read. On the third day something strange happened: people began to talk to him. Since he couldn't reply, or comment, or launch into a memory from 1987, each of them began to confide in him what they had never been able to say. His daughter admitted she hated her job as an accountant and dreamed of opening a bookshop. His son-in-law told him about his fear of growing old. Noé showed him poems he had been writing in secret.`,
    `Jean-Paul listened. He discovered, with growing astonishment, that his family was full of fascinating strangers. Above all he discovered that listening was a physical act, exhausting, which required you not to prepare your answer while the other person was talking. In the evenings, on the ramparts, he watched the sun set behind the Grand Bé, and it seemed to him that he could hear, for the first time in years, the sound of the sea, which his own voice had always drowned out.`,
    `Only his wife, Monique, confided nothing. She simply looked at him with a slightly sad, slightly mocking smile, as if she were waiting for something. On the sixth evening, as they walked alone on the Sillon beach, she stopped and told him that in forty-two years of marriage she had never managed to tell him one thing, just one, because he was always talking at the moment she was about to say it. She wanted to learn to sail. She had dreamed of it since childhood. She wanted them to take sailing lessons together at the Glénan school in the autumn.`,
    `Jean-Paul looked at her. He had in his mouth, all ready, a twenty-line sentence about his seasickness, about age, about the price of courses, about a client who had drowned in Dinard in 1994. He felt the sentence rising like a tide. He thought of the bet, of the diving board, of Noé. Then he thought that he had never heard anything more important in forty-two years, and that the bet, deep down, no longer mattered at all.`,
    `He opened his mouth and said: "Yes." That was all. Monique burst out laughing, then into tears, then both at once. The next morning, in front of the whole family, Maître Jean-Paul Lambert, honorary notary, seventy-four, in striped swimming trunks, jumped off the Bon-Secours diving board into water at fifteen degrees. He came back to the surface howling with cold and, for the first time in his life, without adding anything.`,
  ],
};

export const FR_C1_S04_GLOSSES: Record<string, StoryGloss[]> = {
  "fr-c1-la-file-d-attente": [
    { es: "la file d'attente", en: "queue, line", forms: ["file"] },
    { es: "dissimuler", en: "to conceal", forms: ["dissimuler"] },
    { es: "le velours", en: "corduroy, velvet", forms: ["velours"] },
    { es: "dégagé", en: "casual, offhand", forms: ["dégagé"] },
    { es: "la pénurie", en: "shortage, scarcity", forms: ["pénurie"] },
    { es: "souder", en: "to bind together (literally 'to weld')", forms: ["soudé"] },
    { es: "le seuil", en: "threshold", forms: ["seuil"] },
    { es: "se moquer du monde", en: "to take people for fools", forms: ["moquait"] },
    { es: "étourdi", en: "dazed", forms: ["étourdis"] },
    { es: "refaire le monde", en: "to put the world to rights", forms: ["refaire"] },
  ],
  "fr-c1-le-tailleur-de-la-rue-blanchot": [
    { es: "coudre", en: "to sew", forms: ["couds", "coudre"] },
    { es: "l'ourlet", en: "hem", forms: ["ourlets"] },
    { es: "le boubou", en: "boubou, long flowing West African robe", forms: ["boubou"] },
    { es: "froissé", en: "crumpled", forms: ["froissé"] },
    { es: "comme si de rien n'était", en: "as if nothing had happened", forms: ["n'était"] },
    { es: "le bazin", en: "bazin, damask cotton fabric", forms: ["bazin"] },
    { es: "gronder", en: "to scold", forms: ["grondés"] },
    { es: "la magistrature", en: "the judiciary", forms: ["magistrature"] },
    { es: "la broderie", en: "embroidery", forms: ["broderies"] },
    { es: "se donner du mal", en: "to go to a lot of trouble", forms: ["mal"] },
    { es: "démentir", en: "to deny", forms: ["démenti"] },
  ],
  "fr-c1-l-ete-des-cerises": [
    { es: "inébranlable", en: "unshakable", forms: ["inébranlable"] },
    { es: "meurtrir", en: "to bruise", forms: ["meurtrir"] },
    { es: "le saisonnier", en: "seasonal worker", forms: ["saisonniers"] },
    { es: "grommeler", en: "to grumble", forms: ["grommela"] },
    { es: "le/la feignant(e)", en: "lazy person, idler", forms: ["feignant"] },
    { es: "boiter", en: "to limp", forms: ["boitant"] },
    { es: "le bigarreau", en: "bigarreau, a firm sweet cherry", forms: ["bigarreau"] },
    { es: "dépérir", en: "to wither, to waste away", forms: ["dépérissait"] },
    { es: "la greffe", en: "graft, grafting", forms: ["greffe"] },
    { es: "la pépinière", en: "(plant) nursery", forms: ["pépinière"] },
    { es: "le mastic", en: "grafting wax, putty", forms: ["mastic"] },
    { es: "le cageot", en: "crate", forms: ["cageot"] },
  ],
  "fr-c1-le-double": [
    { es: "l'actuaire", en: "actuary", forms: ["actuaire"] },
    { es: "le plongeoir", en: "diving board", forms: ["plongeoir"] },
    { es: "drôlement", en: "really, awfully (informal)", forms: ["drôlement"] },
    { es: "le signalement", en: "report, sighting", forms: ["signalements"] },
    { es: "la tournée", en: "round (of drinks)", forms: ["tournée"] },
    { es: "le sinistre", en: "insurance claim, loss", forms: ["sinistres"] },
    { es: "l'absence", en: "blackout, lapse of memory", forms: ["absences"] },
    { es: "traquer", en: "to track down", forms: ["traquer"] },
    { es: "se poster", en: "to station oneself", forms: ["posta"] },
    { es: "la rambarde", en: "railing", forms: ["rambarde"] },
    { es: "loger", en: "to live, to find lodging", forms: ["loger"] },
  ],
  "fr-c1-le-silence-de-monsieur-lambert": [
    { es: "honoraire", en: "honorary (retired but keeping the title)", forms: ["honoraire"] },
    { es: "l'acte", en: "deed, legal document", forms: ["actes"] },
    { es: "l'alinéa", en: "paragraph, clause", forms: ["alinéas"] },
    { es: "l'enjeu", en: "stake(s)", forms: ["l'enjeu"] },
    { es: "piqué au vif", en: "stung to the quick", forms: ["vif"] },
    { es: "le supplice", en: "torture, ordeal", forms: ["supplice"] },
    { es: "griffonner", en: "to scribble", forms: ["griffonnait"] },
    { es: "enchaîner sur", en: "to move straight on to", forms: ["enchaîner"] },
    { es: "en cachette", en: "in secret", forms: ["cachette"] },
    { es: "le gendre", en: "son-in-law", forms: ["gendre"] },
    { es: "la voile", en: "sailing", forms: ["voile"] },
  ],
};
