// Synced from cheneygross-afk/lengo:src/lib/stories/a1-glosses.ts by scripts/sync-content.mjs -- edit it there, not here.
import { A1_STARTER_GLOSSES } from "./a1-starter";
import type { StoryGloss } from "./types";

// English glosses for the A1 stories, keyed by story slug. See glosses.ts.
export const A1_STORY_GLOSSES: Record<string, StoryGloss[]> = {
  ...A1_STARTER_GLOSSES,
  "school-day-math-test": [
    { es: "la señal", en: "sign", forms: ["señales"] },
    { es: "conducir", en: "to drive", forms: ["conduce", "conducir"] },
    { es: "decir", en: "to say", forms: ["dice"] },
    { es: "aprobar", en: "to pass (a test)", forms: ["aprobar", "aprueba"] },
    { es: "apto", en: "pass (exam result)", forms: ["apto"] },
    { es: "la autoescuela", en: "driving school", forms: ["autoescuela"] },
    { es: "la calma", en: "calm", forms: ["calma"] },
    { es: "entregar", en: "to hand in", forms: ["entrega"] },
    { es: "esperar", en: "to wait", forms: ["espera"] },
    { es: "el monstruo", en: "monster", forms: ["monstruo"] },
    { es: "respirar profundo", en: "to take a deep breath", forms: ["profundo"] },
    { es: "repartir", en: "to hand out", forms: ["reparte"] },
    { es: "responder", en: "to answer", forms: ["responde"] },
    { es: "la respuesta", en: "answer", forms: ["respuestas"] },
    { es: "revisar", en: "to check", forms: ["revisa"] },
    { es: "sonreír", en: "to smile", forms: ["sonríe"] },
    { es: "la sonrisa", en: "smile", forms: ["sonrisa"] },
    { es: "tanto", en: "so much", forms: ["tanto"] },
    { es: "teórico", en: "theory (test)", forms: ["teórico"] },
    { es: "todavía", en: "still", forms: ["todavía"] },
    { es: "el carné de conducir", en: "driver's license", forms: ["carné"] },
  ],
  "family-beach-trip": [
    { es: "la concha", en: "seashell", forms: ["concha", "conchas"] },
    { es: "el castillo", en: "castle", forms: ["castillo"] },
    { es: "el balde", en: "bucket", forms: ["balde"] },
    { es: "el cielo", en: "sky", forms: ["cielo"] },
    { es: "hacia", en: "toward", forms: ["hacia"] },
    { es: "la arena", en: "sand", forms: ["arena"] },
    { es: "brillar", en: "to shine", forms: ["brilla"] },
    { es: "cambiar", en: "to change", forms: ["cambia"] },
    { es: "construir", en: "to build", forms: ["construyen"] },
    { es: "decorar", en: "to decorate", forms: ["decora"] },
    { es: "decir", en: "to say", forms: ["dice"] },
    { es: "especial", en: "special", forms: ["especial"] },
    { es: "flotar", en: "to float", forms: ["flotar"] },
    { es: "guardar", en: "to keep", forms: ["guarda"] },
    { es: "la pala", en: "shovel", forms: ["pala"] },
    { es: "la pared", en: "wall", forms: ["paredes"] },
    { es: "poner", en: "to put", forms: ["pone"] },
    { es: "recoger", en: "to pick up", forms: ["recoge"] },
    { es: "recordar", en: "to remember", forms: ["recordar"] },
  ],
  "new-puppy-first-trick": [
    { es: "el cachorro", en: "puppy", forms: ["cachorro", "cachorros"] },
    { es: "el truco", en: "trick", forms: ["truco", "trucos"] },
    { es: "dar", en: "to give", forms: ["da"] },
    { es: "decir", en: "to say", forms: ["dice"] },
    { es: "al principio", en: "at first", forms: ["principio"] },
    { es: "abrazar", en: "to hug", forms: ["abraza"] },
    { es: "la alegría", en: "joy", forms: ["alegría"] },
    { es: "celebrar", en: "to celebrate", forms: ["celebra"] },
    { es: "la cola", en: "tail", forms: ["cola"] },
    { es: "conocer", en: "to get to know", forms: ["conocer"] },
    { es: "enseñar", en: "to teach", forms: ["enseñar"] },
    { es: "especial", en: "special", forms: ["especial"] },
    { es: "gritar", en: "to shout", forms: ["grita"] },
    { es: "oler", en: "to smell", forms: ["huele"] },
    { es: "al instante", en: "instantly", forms: ["instante"] },
    { es: "marrón", en: "brown", forms: ["marrón"] },
    { es: "el mueble", en: "piece of furniture", forms: ["muebles"] },
    { es: "mover", en: "to move, to wag", forms: ["mueve"] },
    { es: "orgulloso", en: "proud", forms: ["orgulloso"] },
    { es: "la paciencia", en: "patience", forms: ["paciencia"] },
    { es: "el premio", en: "treat, reward", forms: ["premio"] },
    { es: "rápidamente", en: "quickly", forms: ["rápidamente"] },
    { es: "el refugio", en: "shelter", forms: ["refugio"] },
    { es: "sonreír", en: "to smile", forms: ["sonríe"] },
  ],
  "surprise-birthday-party": [
    { es: "dar", en: "to give", forms: ["da"] },
    { es: "la sorpresa", en: "surprise", forms: ["sorpresa"] },
    { es: "olvidar", en: "to forget", forms: ["olvida"] },
    { es: "en realidad", en: "actually", forms: ["realidad"] },
    { es: "el secreto", en: "secret", forms: ["secreto"] },
    { es: "ver", en: "to see", forms: ["ve"] },
    { es: "abrazar", en: "to hug", forms: ["abraza"] },
    { es: "aceptar", en: "to accept", forms: ["acepta"] },
    { es: "apagado", en: "off (lights)", forms: ["apagadas"] },
    { es: "despacio", en: "slowly", forms: ["despacio"] },
    { es: "decir", en: "to say", forms: ["dice"] },
    { es: "encenderse", en: "to turn on", forms: ["encienden"] },
    { es: "la energía", en: "energy", forms: ["energía"] },
    { es: "especial", en: "special", forms: ["especial"] },
    { es: "el globo", en: "balloon", forms: ["globos"] },
    { es: "gritar", en: "to shout", forms: ["gritan"] },
    { es: "guardar", en: "to keep", forms: ["guardan"] },
    { es: "la invitación", en: "invitation", forms: ["invitación"] },
    { es: "planear", en: "to plan", forms: ["planean"] },
    { es: "reír", en: "to laugh", forms: ["reír"] },
    { es: "de repente", en: "suddenly", forms: ["repente"] },
  ],
  "grandmothers-soup-recipe": [
    { es: "decir", en: "to say", forms: ["dice"] },
    { es: "el secreto", en: "secret", forms: ["secreto"] },
    { es: "sonreír", en: "to smile", forms: ["sonríe"] },
    { es: "la hierba", en: "herb", forms: ["hierbas"] },
    { es: "poner", en: "to put", forms: ["pone"] },
    { es: "el abrazo", en: "hug", forms: ["abrazo"] },
    { es: "agregar", en: "to add", forms: ["agrega"] },
    { es: "la boca", en: "mouth", forms: ["boca"] },
    { es: "la cebolla", en: "onion", forms: ["cebollas"] },
    { es: "conocer", en: "to know", forms: ["conoce"] },
    { es: "cortar", en: "to cut", forms: ["corta"] },
    { es: "dar", en: "to give", forms: ["da"] },
    { es: "el frasco", en: "jar", forms: ["frasco"] },
    { es: "oler", en: "to smell", forms: ["huele"] },
    { es: "lavar", en: "to wash", forms: ["lavan"] },
    { es: "lleno", en: "full", forms: ["llena"] },
    { es: "el mundo", en: "world", forms: ["mundo"] },
    { es: "la olla", en: "pot", forms: ["olla"] },
    { es: "la pimienta", en: "pepper", forms: ["pimienta"] },
    { es: "el plato", en: "dish, bowl", forms: ["platos"] },
    { es: "probar", en: "to taste", forms: ["prueba"] },
    { es: "responder", en: "to answer", forms: ["responde"] },
  ],
  "first-soccer-goal": [
    { es: "el balón", en: "ball", forms: ["balón"] },
    { es: "el gol", en: "goal", forms: ["gol"] },
    { es: "gritar", en: "to shout", forms: ["grita"] },
    { es: "abrazar", en: "to hug", forms: ["abrazan"] },
    { es: "el abrazo", en: "hug", forms: ["abrazo"] },
    { es: "entrar", en: "to go in", forms: ["entra"] },
    { es: "el equipo", en: "team", forms: ["equipo"] },
    { es: "hacia", en: "toward", forms: ["hacia"] },
    { es: "la portería", en: "goal", forms: ["portería"] },
    { es: "acelerado", en: "racing", forms: ["acelerado"] },
    { es: "afuera", en: "outside", forms: ["afuera"] },
    { es: "la alegría", en: "joy", forms: ["alegría"] },
    { es: "algún día", en: "someday", forms: ["algún"] },
    { es: "animar", en: "to cheer on", forms: ["anima"] },
    { es: "aplaudir", en: "to clap", forms: ["aplaude"] },
    { es: "casi", en: "almost", forms: ["casi"] },
    { es: "el corazón", en: "heart", forms: ["corazón"] },
    { es: "dar", en: "to give", forms: ["da"] },
    { es: "desde", en: "from", forms: ["desde"] },
    { es: "decir", en: "to say", forms: ["dice"] },
    { es: "esperar", en: "to wait for", forms: ["espera"] },
    { es: "el estadio", en: "stadium", forms: ["estadio"] },
    { es: "la fuerza", en: "force, strength", forms: ["fuerza"] },
    { es: "el jugador", en: "player", forms: ["jugadores"] },
    { es: "orgulloso", en: "proud", forms: ["orgulloso"] },
    { es: "patear", en: "to kick", forms: ["patea"] },
    { es: "profundo", en: "deeply", forms: ["profundo"] },
    { es: "el público", en: "crowd", forms: ["público"] },
    { es: "de repente", en: "suddenly", forms: ["repente"] },
    { es: "respirar", en: "to breathe", forms: ["respira"] },
    { es: "sonreír", en: "to smile", forms: ["sonríe"] },
    { es: "la sonrisa", en: "smile", forms: ["sonrisa"] },
  ],
  "autumn-leaves-adventure": [
    { es: "la hoja", en: "leaf", forms: ["hoja", "hojas"] },
    { es: "el proyecto", en: "project", forms: ["proyecto"] },
    { es: "diferente", en: "different", forms: ["diferentes"] },
    { es: "especial", en: "special", forms: ["especial"] },
    { es: "la maestra", en: "teacher", forms: ["maestra"] },
    { es: "el otoño", en: "fall, autumn", forms: ["otoño"] },
    { es: "poner", en: "to put", forms: ["ponen"] },
    { es: "la bellota", en: "acorn", forms: ["bellotas"] },
    { es: "la búsqueda", en: "search", forms: ["búsqueda"] },
    { es: "caer", en: "to fall", forms: ["caen"] },
    { es: "cambiar", en: "to change", forms: ["cambian"] },
    { es: "el cartón", en: "cardboard", forms: ["cartón"] },
    { es: "el cielo", en: "sky", forms: ["cielo"] },
    { es: "continuar", en: "to continue", forms: ["continúan"] },
    { es: "decir", en: "to say", forms: ["dice"] },
    { es: "el lago", en: "lake", forms: ["lago"] },
    { es: "pegar", en: "to glue", forms: ["pegar"] },
    { es: "presentar", en: "to present", forms: ["presenta"] },
    { es: "recoger", en: "to collect", forms: ["recoger"] },
    { es: "de repente", en: "suddenly", forms: ["repente"] },
    { es: "reírse", en: "to laugh", forms: ["ríen"] },
  ],
  "helping-mr-martin": [
    { es: "ver", en: "to see", forms: ["ve"] },
    { es: "aceptar", en: "to accept", forms: ["acepta"] },
    { es: "agradecido", en: "grateful", forms: ["agradecido"] },
    { es: "el ajedrez", en: "chess", forms: ["ajedrez"] },
    { es: "la amistad", en: "friendship", forms: ["amistad"] },
    { es: "arreglar", en: "to fix", forms: ["arreglarla"] },
    { es: "la atención", en: "attention", forms: ["atención"] },
    { es: "decir", en: "to say", forms: ["dice"] },
    { es: "enseñar", en: "to teach", forms: ["enseña"] },
    { es: "especial", en: "special", forms: ["especial"] },
    { es: "la limonada", en: "lemonade", forms: ["limonada"] },
    { es: "la madera", en: "wood", forms: ["madera"] },
    { es: "el martillo", en: "hammer", forms: ["martillo"] },
    { es: "mientras", en: "while", forms: ["mientras"] },
    { es: "orgulloso", en: "proud", forms: ["orgullosos"] },
    { es: "reparado", en: "repaired", forms: ["reparada"] },
  ],
  "grandpas-garden": [
    { es: "la semilla", en: "seed", forms: ["semillas"] },
    { es: "la tierra", en: "soil", forms: ["tierra"] },
    { es: "crecer", en: "to grow", forms: ["crecen"] },
    { es: "la alegría", en: "joy", forms: ["alegría"] },
    { es: "cambiar", en: "to change", forms: ["cambian"] },
    { es: "cosechar", en: "to harvest", forms: ["cosechan"] },
    { es: "cubrir", en: "to cover", forms: ["cubre"] },
    { es: "dar", en: "to give", forms: ["da"] },
    { es: "decir", en: "to say", forms: ["dice"] },
    { es: "la emoción", en: "excitement", forms: ["emoción"] },
    { es: "enseñar", en: "to teach", forms: ["enseña"] },
    { es: "explicar", en: "to explain", forms: ["explica"] },
    { es: "gritar", en: "to shout", forms: ["grita"] },
    { es: "la hierba", en: "weed (hierba mala)", forms: ["hierbas"] },
    { es: "la hoja", en: "leaf", forms: ["hojas"] },
    { es: "orgulloso", en: "proud", forms: ["orgullosa"] },
    { es: "poner", en: "to put", forms: ["pone"] },
    { es: "la primavera", en: "spring", forms: ["primavera"] },
  ],
  "the-lost-teddy-bear": [
    { es: "la entrevista", en: "interview", forms: ["entrevista"] },
    { es: "el bolígrafo", en: "pen", forms: ["bolígrafo"] },
    { es: "el bolsillo", en: "pocket", forms: ["bolsillos"] },
    { es: "la cafetera", en: "coffee maker", forms: ["cafetera"] },
    { es: "el cajón", en: "drawer", forms: ["cajones"] },
    { es: "la cerradura", en: "lock", forms: ["cerradura"] },
    { es: "el cojín", en: "cushion", forms: ["cojines"] },
    { es: "el currículum", en: "CV, résumé", forms: ["currículum"] },
    { es: "decir", en: "to say", forms: ["dice"] },
    { es: "la moneda", en: "coin", forms: ["moneda"] },
    { es: "organizado", en: "organized", forms: ["organizada"] },
    { es: "posible", en: "possible", forms: ["posible"] },
    { es: "reír", en: "to laugh", forms: ["ríe"] },
    { es: "el salón", en: "living room", forms: ["salón"] },
    { es: "el calcetín", en: "sock", forms: ["calcetín"] },
  ],
  "a-day-at-the-zoo": [
    { es: "bromista", en: "joker, prankster", forms: ["bromista", "bromistas"] },
    { es: "mojado", en: "wet", forms: ["mojado"] },
    { es: "la palabra", en: "word", forms: ["palabra"] },
    { es: "reír", en: "to laugh", forms: ["ríe", "ríen"] },
    { es: "aplaudir", en: "to clap", forms: ["aplauden"] },
    { es: "el barro", en: "mud", forms: ["barro"] },
    { es: "la cuidadora", en: "keeper", forms: ["cuidadora"] },
    { es: "curioso", en: "curious", forms: ["curiosa"] },
    { es: "dar", en: "to give", forms: ["dan"] },
    { es: "decir", en: "to say", forms: ["dice"] },
    { es: "duro", en: "hard", forms: ["duro"] },
    { es: "echar", en: "to throw", forms: ["echa"] },
    { es: "la elefanta", en: "female elephant", forms: ["elefanta"] },
    { es: "la experiencia", en: "experience", forms: ["experiencia"] },
    { es: "hacia", en: "toward", forms: ["hacia"] },
    { es: "la manguera", en: "hose", forms: ["manguera"] },
    { es: "el plátano", en: "banana", forms: ["plátanos"] },
    { es: "de repente", en: "suddenly", forms: ["repente"] },
    { es: "la trompa", en: "trunk (of an elephant)", forms: ["trompa"] },
    { es: "último", en: "last", forms: ["última"] },
    { es: "la zanahoria", en: "carrot", forms: ["zanahorias"] },
    { es: "el zoológico", en: "zoo", forms: ["zoológico"] },
    { es: "el ayudante", en: "assistant", forms: ["ayudante"] },
  ],
  "saturday-at-the-market": [
    { es: "el puesto", en: "stall", forms: ["puesto", "puestos"] },
    { es: "lleno", en: "full", forms: ["llena", "llenas", "lleno"] },
    { es: "el vendedor", en: "vendor", forms: ["vendedor"] },
    { es: "dulce", en: "sweet", forms: ["dulce"] },
    { es: "sonreír", en: "to smile", forms: ["sonríe"] },
    { es: "cargar", en: "to carry", forms: ["carga"] },
    { es: "el clima", en: "weather", forms: ["clima"] },
    { es: "conocer", en: "to know", forms: ["conoce"] },
    { es: "la curiosidad", en: "curiosity", forms: ["curiosidad"] },
    { es: "desde hace", en: "for (a time)", forms: ["desde"] },
    { es: "decir", en: "to say", forms: ["dice"] },
    { es: "escoger", en: "to choose", forms: ["escoge"] },
    { es: "hacia", en: "toward", forms: ["hacia"] },
    { es: "oler", en: "to smell", forms: ["huelen"] },
    { es: "el olor", en: "smell", forms: ["olores"] },
    { es: "el plátano", en: "banana", forms: ["plátanos"] },
    { es: "probar", en: "to taste", forms: ["prueba"] },
    { es: "responder", en: "to answer", forms: ["responde"] },
  ],
  "kite-in-the-park": [
    { es: "la cometa", en: "kite", forms: ["cometa"] },
    { es: "la cuerda", en: "string", forms: ["cuerda"] },
    { es: "decir", en: "to say", forms: ["dice"] },
    { es: "sostener", en: "to hold", forms: ["sostiene"] },
    { es: "el palo", en: "stick", forms: ["palos"] },
    { es: "el papel", en: "paper", forms: ["papel"] },
    { es: "volar", en: "to fly", forms: ["volar"] },
    { es: "el abrazo", en: "hug", forms: ["abrazo"] },
    { es: "la admiración", en: "admiration", forms: ["admiración"] },
    { es: "la alegría", en: "joy", forms: ["alegría"] },
    { es: "atar", en: "to tie", forms: ["ata"] },
    { es: "el cielo", en: "sky", forms: ["cielo"] },
    { es: "la cola", en: "tail", forms: ["cola"] },
    { es: "dar", en: "to give", forms: ["da"] },
    { es: "desde hace", en: "for (a time)", forms: ["desde"] },
    { es: "la emoción", en: "excitement", forms: ["emoción"] },
    { es: "el entusiasmo", en: "enthusiasm", forms: ["entusiasmo"] },
    { es: "especial", en: "special", forms: ["especial"] },
    { es: "la estrella", en: "star", forms: ["estrellas"] },
    { es: "la fuerza", en: "strength", forms: ["fuerza"] },
    { es: "gritar", en: "to shout", forms: ["grita"] },
    { es: "hacia", en: "toward", forms: ["hacia"] },
    { es: "hecho", en: "made", forms: ["hecha"] },
    { es: "levantar", en: "to lift", forms: ["levanta"] },
    { es: "el material", en: "material", forms: ["madera"] },
    { es: "la madera", en: "wood", forms: ["materiales"] },
    { es: "mientras", en: "while", forms: ["mientras"] },
    { es: "orgulloso", en: "proud", forms: ["orgullosa"] },
    { es: "otra vez", en: "again", forms: ["otra"] },
  ],
  "learning-to-swim": [
    { es: "profundo", en: "deep", forms: ["profunda", "profundo"] },
    { es: "decir", en: "to say", forms: ["dice"] },
    { es: "el brazo", en: "arm", forms: ["brazos"] },
    { es: "otro", en: "other", forms: ["otro"] },
    { es: "poner", en: "to put", forms: ["pone", "poner"] },
    { es: "la alegría", en: "joy", forms: ["alegría"] },
    { es: "aplaudir", en: "to clap", forms: ["aplauden"] },
    { es: "el borde", en: "edge", forms: ["borde"] },
    { es: "desde", en: "from", forms: ["desde"] },
    { es: "enseñar", en: "to teach", forms: ["enseña"] },
    { es: "el esfuerzo", en: "effort", forms: ["esfuerzo"] },
    { es: "flotar", en: "to float", forms: ["flotar"] },
    { es: "la fuerza", en: "strength, force", forms: ["fuerza"] },
    { es: "gritar", en: "to shout", forms: ["grita"] },
    { es: "inscribir", en: "to sign up", forms: ["inscriben"] },
    { es: "moverse", en: "to move", forms: ["mueven"] },
    { es: "la natación", en: "swimming", forms: ["natación"] },
    { es: "orgulloso", en: "proud", forms: ["orgullosa"] },
    { es: "la paciencia", en: "patience", forms: ["paciencia"] },
    { es: "paciente", en: "patient", forms: ["paciente"] },
    { es: "patalear", en: "to kick (legs)", forms: ["patalean"] },
    { es: "el pez", en: "fish", forms: ["pez"] },
    { es: "al principio", en: "at first", forms: ["principio"] },
    { es: "el progreso", en: "progress", forms: ["progreso"] },
  ],
  "sunday-family-dinner": [
    { es: "otro", en: "other, another", forms: ["otra"] },
    { es: "el plato", en: "plate", forms: ["plato", "platos"] },
    { es: "poner", en: "to put", forms: ["pone", "poner"] },
    { es: "reírse", en: "to laugh", forms: ["ríen"] },
    { es: "el abrazo", en: "hug", forms: ["abrazos"] },
    { es: "alegre", en: "cheerful", forms: ["alegres"] },
    { es: "el chiste", en: "joke", forms: ["chiste"] },
    { es: "conocer", en: "to know", forms: ["conoce"] },
    { es: "la conversación", en: "conversation", forms: ["conversaciones"] },
    { es: "despedirse", en: "to say goodbye", forms: ["despide"] },
    { es: "decir", en: "to say", forms: ["dice"] },
    { es: "esconderse", en: "to hide", forms: ["esconde"] },
    { es: "especial", en: "special", forms: ["especial"] },
    { es: "oler", en: "to smell", forms: ["huele"] },
    { es: "mientras", en: "while", forms: ["mientras"] },
    { es: "la pelota", en: "ball", forms: ["pelota"] },
    { es: "rápidamente", en: "quickly", forms: ["rápidamente"] },
    { es: "reunirse", en: "to get together", forms: ["reúne"] },
  ],
  "rainy-day-blanket-fort": [
    { es: "la vela", en: "candle", forms: ["velas"] },
    { es: "ganar", en: "to win", forms: ["gana"] },
    { es: "apagar", en: "to turn off", forms: ["apaga"] },
    { es: "la batería", en: "battery", forms: ["batería"] },
    { es: "el bocadillo", en: "sandwich", forms: ["bocadillos"] },
    { es: "la botella", en: "bottle", forms: ["botella"] },
    { es: "la caja", en: "box", forms: ["caja"] },
    { es: "el cajón", en: "drawer", forms: ["cajón"] },
    { es: "la cerilla", en: "match", forms: ["cerillas"] },
    { es: "desde hace", en: "for (time)", forms: ["desde"] },
    { es: "eléctrico", en: "electric", forms: ["eléctrica"] },
    { es: "el salón", en: "living room", forms: ["salón"] },
    { es: "sonreír", en: "to smile", forms: ["sonríe"] },
    { es: "viejo", en: "old", forms: ["viejo"] },
    { es: "la partida", en: "game, round", forms: ["partida"] },
    { es: "compartir", en: "to share", forms: ["comparten"] },
  ],
  "the-new-student": [
    { es: "sonreír", en: "to smile", forms: ["sonríe", "sonríen"] },
    { es: "la sonrisa", en: "smile", forms: ["sonrisa"] },
    { es: "aceptar", en: "to accept", forms: ["acepta"] },
    { es: "acercarse", en: "to come closer", forms: ["acerca"] },
    { es: "la confianza", en: "confidence", forms: ["confianza"] },
    { es: "conocer", en: "to know", forms: ["conoce"] },
    { es: "la curiosidad", en: "curiosity", forms: ["curiosidad"] },
    { es: "desde", en: "from", forms: ["desde"] },
    { es: "decir", en: "to say", forms: ["dice"] },
    { es: "la invitación", en: "invitation", forms: ["invitación"] },
    { es: "la maestra", en: "teacher", forms: ["maestra"] },
    { es: "desde hace", en: "for (a length of time)", forms: ["hace"] },
    { es: "otro", en: "another", forms: ["otra"] },
    { es: "otro", en: "other", forms: ["otras"] },
    { es: "el patio", en: "schoolyard", forms: ["patio"] },
    { es: "presentar", en: "to introduce", forms: ["presenta"] },
    { es: "propio", en: "own", forms: ["propio"] },
    { es: "el recreo", en: "recess", forms: ["recreo"] },
  ],
  "camping-in-the-mountains": [
    { es: "el cielo", en: "sky", forms: ["cielo"] },
    { es: "la estrella", en: "star", forms: ["estrellas"] },
    { es: "acampar", en: "to camp", forms: ["acampar"] },
    { es: "arriba", en: "up", forms: ["arriba"] },
    { es: "la tienda de campaña", en: "tent", forms: ["campaña"] },
    { es: "emocionado", en: "excited", forms: ["emocionado", "emocionados"] },
    { es: "hacia", en: "toward", forms: ["hacia"] },
    { es: "el río", en: "river", forms: ["río"] },
    { es: "estar de acuerdo", en: "to agree", forms: ["acuerdo"] },
    { es: "armar", en: "to set up, to pitch", forms: ["arma"] },
    { es: "la aventura", en: "adventure", forms: ["aventura"] },
    { es: "el bosque", en: "forest", forms: ["bosque"] },
    { es: "brillante", en: "bright", forms: ["brillantes"] },
    { es: "el campamento", en: "campsite", forms: ["campamento"] },
    { es: "casi", en: "almost", forms: ["casi"] },
    { es: "completamente", en: "completely", forms: ["completamente"] },
    { es: "decir", en: "to say", forms: ["dice"] },
    { es: "durar", en: "to last", forms: ["dura"] },
    { es: "explorar", en: "to explore", forms: ["explora"] },
    { es: "la fogata", en: "campfire", forms: ["fogata"] },
    { es: "el fuego", en: "fire", forms: ["fuego"] },
    { es: "gritar", en: "to shout", forms: ["grita"] },
    { es: "hermoso", en: "beautiful", forms: ["hermoso"] },
    { es: "la linterna", en: "flashlight", forms: ["linternas"] },
    { es: "lleno", en: "full", forms: ["lleno"] },
    { es: "mientras", en: "while", forms: ["mientras"] },
    { es: "otra vez", en: "again", forms: ["otra"] },
    { es: "la piedra", en: "stone", forms: ["piedras"] },
    { es: "próximo", en: "next", forms: ["próximo"] },
    { es: "la rama", en: "branch", forms: ["ramas"] },
    { es: "recoger", en: "to gather", forms: ["recoger"] },
    { es: "de repente", en: "suddenly", forms: ["repente"] },
    { es: "la salchicha", en: "sausage", forms: ["salchichas"] },
  ],
  "the-guitar-lesson": [
    { es: "el acorde", en: "chord", forms: ["acorde", "acordes"] },
    { es: "el dedo", en: "finger", forms: ["dedos"] },
    { es: "decir", en: "to say", forms: ["dice"] },
    { es: "enseñar", en: "to teach", forms: ["enseña"] },
    { es: "el maestro", en: "teacher", forms: ["maestro"] },
    { es: "aplaudir", en: "to clap", forms: ["aplaude"] },
    { es: "aunque", en: "although", forms: ["aunque"] },
    { es: "la calma", en: "calm", forms: ["calma"] },
    { es: "completo", en: "whole, complete", forms: ["completa"] },
    { es: "la cuerda", en: "string", forms: ["cuerdas"] },
    { es: "dejar", en: "to quit, to give up", forms: ["dejar"] },
    { es: "emocionado", en: "excited", forms: ["emocionado"] },
    { es: "el entusiasmo", en: "enthusiasm", forms: ["entusiasmo"] },
    { es: "frustrarse", en: "to get frustrated", forms: ["frustra"] },
    { es: "la frustración", en: "frustration", forms: ["frustración"] },
    { es: "inscribir", en: "to sign up", forms: ["inscriben"] },
    { es: "mostrar", en: "to show", forms: ["muestra"] },
    { es: "ni", en: "not even", forms: ["ni"] },
    { es: "orgulloso", en: "proud", forms: ["orgulloso"] },
    { es: "la paciencia", en: "patience", forms: ["paciencia"] },
    { es: "al principio", en: "at first", forms: ["principio"] },
    { es: "el progreso", en: "progress", forms: ["progreso"] },
    { es: "siguiente", en: "next", forms: ["siguiente"] },
    { es: "simple", en: "simple", forms: ["simples"] },
  ],
  "the-first-snow": [
    { es: "el muñeco de nieve", en: "snowman", forms: ["muñeco"] },
    { es: "la bola", en: "ball", forms: ["bola"] },
    { es: "ver", en: "to see", forms: ["ve"] },
    { es: "la alegría", en: "joy", forms: ["alegría"] },
    { es: "brillante", en: "bright", forms: ["brillante"] },
    { es: "el cielo", en: "sky", forms: ["cielo"] },
    { es: "completamente", en: "completely", forms: ["completamente"] },
    { es: "construir", en: "to build", forms: ["construir"] },
    { es: "cubierto", en: "covered", forms: ["cubierto"] },
    { es: "el cuerpo", en: "body", forms: ["cuerpo"] },
    { es: "despertar", en: "to wake (someone) up", forms: ["despierta"] },
    { es: "diferente", en: "different", forms: ["diferente"] },
    { es: "entrar", en: "to come in", forms: ["entra"] },
    { es: "gritar", en: "to shout", forms: ["grita"] },
    { es: "el guante", en: "glove", forms: ["guantes"] },
    { es: "mágico", en: "magical", forms: ["mágico"] },
    { es: "mudarse", en: "to move (house)", forms: ["muda"] },
    { es: "la nariz", en: "nose", forms: ["nariz"] },
    { es: "la piedra", en: "stone", forms: ["piedras"] },
    { es: "ponerse", en: "to put on", forms: ["pone"] },
    { es: "la posibilidad", en: "possibility", forms: ["posibilidad"] },
  ],
  "el-pastel-de-cumpleanos-de-mama": [
    { es: "decir", en: "to say", forms: ["dice"] },
    { es: "la harina", en: "flour", forms: ["harina"] },
    { es: "el horno", en: "oven", forms: ["horno"] },
    { es: "decorar", en: "to decorate", forms: ["decora"] },
    { es: "entrar", en: "to come in", forms: ["entra"] },
    { es: "especial", en: "special", forms: ["especial"] },
    { es: "esperar", en: "to wait", forms: ["esperan"] },
    { es: "oler", en: "to smell", forms: ["huele"] },
    { es: "marrón", en: "brown", forms: ["marrón"] },
    { es: "mezclar", en: "to mix", forms: ["mezcla"] },
    { es: "el mundo", en: "world", forms: ["mundo"] },
    { es: "la paciencia", en: "patience", forms: ["paciencia"] },
    { es: "el plan", en: "plan", forms: ["plan"] },
    { es: "poner", en: "to put", forms: ["pone"] },
  ],
  "el-loro-parlanchin": [
    { es: "decir", en: "to say", forms: ["dice"] },
    { es: "el loro", en: "parrot", forms: ["loro"] },
    { es: "la palabra", en: "word", forms: ["palabras"] },
    { es: "la atención", en: "attention", forms: ["atención"] },
    { es: "enseñar", en: "to teach", forms: ["enseña"] },
    { es: "la jaula", en: "cage", forms: ["jaula"] },
    { es: "de repente", en: "suddenly", forms: ["repente"] },
  ],
  "el-gato-no-quiere-el-bano": [
    { es: "entrar", en: "to go in", forms: ["entrar"] },
    { es: "esconderse", en: "to hide", forms: ["esconde"] },
    { es: "especial", en: "special", forms: ["especial"] },
    { es: "el jabón", en: "soap", forms: ["jabón"] },
    { es: "lavar", en: "to wash", forms: ["lava"] },
    { es: "maullar", en: "to meow", forms: ["maúlla"] },
    { es: "mojado", en: "wet", forms: ["mojado"] },
    { es: "la paciencia", en: "patience", forms: ["paciencia"] },
    { es: "rápidamente", en: "quickly", forms: ["rápidamente"] },
    { es: "el rincón", en: "corner", forms: ["rincón"] },
    { es: "secarse", en: "to dry off", forms: ["seca"] },
  ],
  "panqueques-del-sabado": [
    { es: "el panqueque", en: "pancake", forms: ["panqueque", "panqueques"] },
    { es: "poner", en: "to put", forms: ["pone"] },
    { es: "especial", en: "special", forms: ["especial", "especiales"] },
    { es: "la mantequilla", en: "butter", forms: ["mantequilla"] },
    { es: "mezclar", en: "to mix; la mezcla = mixture, batter", forms: ["mezcla"] },
    { es: "la sartén", en: "frying pan", forms: ["sartén"] },
    { es: "el bol", en: "bowl", forms: ["bol"] },
    { es: "el corazón", en: "heart", forms: ["corazón"] },
    { es: "la cuchara", en: "spoon", forms: ["cuchara"] },
    { es: "la forma", en: "shape", forms: ["forma"] },
    { es: "el fuego", en: "stove, heat", forms: ["fuego"] },
    { es: "la harina", en: "flour", forms: ["harina"] },
    { es: "oler", en: "to smell", forms: ["huele"] },
    { es: "la miel", en: "honey", forms: ["miel"] },
    { es: "otra vez", en: "again", forms: ["otra"] },
    { es: "redondo", en: "round", forms: ["redondos"] },
  ],
  "el-jardin-de-tomates": [
    { es: "la cesta", en: "basket", forms: ["cesta"] },
    { es: "recoger", en: "to pick", forms: ["recogen", "recogerlos"] },
    { es: "regar", en: "to water", forms: ["riega", "riegan"] },
    { es: "la albahaca", en: "basil", forms: ["albahaca"] },
    { es: "bastante", en: "quite a lot", forms: ["bastante"] },
    { es: "crecer", en: "to grow", forms: ["crecen"] },
    { es: "cultivar", en: "to grow", forms: ["cultiva"] },
    { es: "decir", en: "to say", forms: ["dicen"] },
    { es: "oler", en: "to smell", forms: ["huele"] },
    { es: "la jardinería", en: "gardening", forms: ["jardinería"] },
    { es: "lleno", en: "full", forms: ["llena"] },
    { es: "menor", en: "youngest", forms: ["menor"] },
    { es: "orgulloso", en: "proud", forms: ["orgullosa"] },
    { es: "el patio", en: "backyard", forms: ["patio"] },
  ],
  "la-tormenta-de-la-noche": [
    { es: "la tormenta", en: "storm", forms: ["tormenta"] },
    { es: "el trueno", en: "thunder", forms: ["trueno", "truenos"] },
    { es: "afuera", en: "outside", forms: ["afuera"] },
    { es: "el cielo", en: "sky", forms: ["cielo"] },
    { es: "decir", en: "to say", forms: ["dice"] },
    { es: "abrazar", en: "to hug", forms: ["abraza"] },
    { es: "mi amor", en: "sweetheart", forms: ["amor"] },
    { es: "la atención", en: "attention", forms: ["atención"] },
    { es: "caer", en: "to fall", forms: ["cae"] },
    { es: "distraer", en: "to distract", forms: ["distraer"] },
    { es: "encender", en: "to light", forms: ["enciende"] },
    { es: "entrar", en: "to come in", forms: ["entrar"] },
    { es: "oscuro", en: "dark", forms: ["oscuro"] },
    { es: "oír", en: "to hear", forms: ["oyen"] },
    { es: "el rato", en: "while", forms: ["rato"] },
    { es: "el relámpago", en: "lightning", forms: ["relámpago"] },
  ],
  "el-conejo-en-el-jardin": [
    { es: "la jaula", en: "cage", forms: ["jaula"] },
    { es: "la zanahoria", en: "carrot", forms: ["zanahorias"] },
    { es: "el conejo", en: "rabbit", forms: ["conejo"] },
    { es: "el huerto", en: "vegetable garden", forms: ["huerto"] },
    { es: "ver", en: "to see", forms: ["ve"] },
    { es: "la aventura", en: "adventure", forms: ["aventura"] },
    { es: "entrar", en: "to go in", forms: ["entra"] },
    { es: "explorar", en: "to explore", forms: ["explora"] },
    { es: "gritar", en: "to shout", forms: ["grita"] },
    { es: "hacia", en: "toward", forms: ["hacia"] },
    { es: "otra vez", en: "again", forms: ["otra"] },
    { es: "poner", en: "to put", forms: ["pone"] },
    { es: "próximo", en: "next", forms: ["próxima"] },
    { es: "reírse", en: "to laugh", forms: ["ríe"] },
    { es: "seguir", en: "to keep (doing)", forms: ["sigue"] },
  ],
  "un-dia-de-mucho-viento": [
    { es: "atrapar", en: "to catch", forms: ["atrapa", "atrapar"] },
    { es: "moverse", en: "to move", forms: ["mueven"] },
    { es: "el patio", en: "backyard", forms: ["patio"] },
    { es: "volar", en: "to fly", forms: ["vuela"] },
    { es: "caer", en: "to fall", forms: ["cae"] },
    { es: "la cesta", en: "basket", forms: ["cesta"] },
    { es: "el cielo", en: "sky", forms: ["cielo"] },
    { es: "la cuerda", en: "clothesline", forms: ["cuerda"] },
    { es: "entrar", en: "to go in", forms: ["entra"] },
    { es: "la escalera", en: "ladder", forms: ["escalera"] },
    { es: "otro", en: "other", forms: ["otro"] },
    { es: "poner", en: "to put", forms: ["pone"] },
    { es: "recoger", en: "to pick up", forms: ["recoge"] },
    { es: "de repente", en: "suddenly", forms: ["repente"] },
    { es: "reírse", en: "to laugh", forms: ["ríe"] },
  ],
  "la-abuela-teje-una-bufanda": [
    { es: "decir", en: "to say", forms: ["dice"] },
    { es: "la vuelta", en: "row (in knitting)", forms: ["vuelta"] },
    { es: "el movimiento", en: "movement", forms: ["movimientos"] },
    { es: "tejer", en: "to knit", forms: ["teje", "tejer"] },
    { es: "la aguja", en: "knitting needle", forms: ["agujas"] },
    { es: "mi amor", en: "sweetheart", forms: ["amor"] },
    { es: "corto", en: "short", forms: ["corta"] },
    { es: "crecer", en: "to grow", forms: ["crecer"] },
    { es: "dar", en: "to give", forms: ["da"] },
    { es: "elegir", en: "to choose", forms: ["elige"] },
    { es: "emocionado", en: "excited", forms: ["emocionada"] },
    { es: "enseñar", en: "to teach", forms: ["enseñarle"] },
    { es: "especial", en: "special", forms: ["especial"] },
    { es: "el invierno", en: "winter", forms: ["inviernos"] },
    { es: "la lana", en: "wool", forms: ["lana"] },
    { es: "mostrar", en: "to show", forms: ["muestra"] },
    { es: "orgulloso", en: "proud", forms: ["orgullosa"] },
  ],
  "el-desayuno-en-la-cama": [
    { es: "la bandeja", en: "tray", forms: ["bandeja"] },
    { es: "decir", en: "to say", forms: ["dice"] },
    { es: "el plato", en: "plate", forms: ["plato"] },
    { es: "poner", en: "to put", forms: ["pone"] },
    { es: "la tostada", en: "toast", forms: ["tostadas"] },
    { es: "cortar", en: "to cut", forms: ["corta"] },
    { es: "derramar", en: "to spill", forms: ["derramar"] },
    { es: "despacio", en: "slowly", forms: ["despacio"] },
    { es: "despertarse", en: "to wake up", forms: ["despiertan"] },
    { es: "hacia", en: "toward", forms: ["hacia"] },
    { es: "el plan", en: "plan", forms: ["plan"] },
    { es: "el plátano", en: "banana", forms: ["plátano"] },
    { es: "secreto", en: "secret", forms: ["secreto"] },
    { es: "suavemente", en: "softly", forms: ["suavemente"] },
    { es: "todavía", en: "still", forms: ["todavía"] },
  ],
  "la-tortuga-lenta": [
    { es: "la caja", en: "box", forms: ["caja"] },
    { es: "la tortuga", en: "turtle", forms: ["tortuga"] },
    { es: "decir", en: "to say", forms: ["dice"] },
    { es: "el plato", en: "plate", forms: ["plato"] },
    { es: "la cortina", en: "curtain", forms: ["cortinas"] },
    { es: "despacio", en: "slowly", forms: ["despacio"] },
    { es: "otra vez", en: "again", forms: ["otra"] },
    { es: "perder", en: "to lose", forms: ["perder"] },
    { es: "la piedra", en: "stone", forms: ["piedras"] },
    { es: "la sonrisa", en: "smile", forms: ["sonrisa"] },
    { es: "el suelo", en: "floor", forms: ["suelo"] },
  ],
  "galletas-para-el-vecino": [
    { es: "la galleta", en: "cookie", forms: ["galletas"] },
    { es: "la caja", en: "box", forms: ["caja"] },
    { es: "el horno", en: "oven", forms: ["horno"] },
    { es: "oler", en: "to smell", forms: ["huele", "huelen"] },
    { es: "poner", en: "to put", forms: ["pone"] },
    { es: "dar la bienvenida", en: "to welcome", forms: ["darle"] },
    { es: "decir", en: "to say", forms: ["dice"] },
    { es: "esperar", en: "to wait", forms: ["esperan"] },
    { es: "la harina", en: "flour", forms: ["harina"] },
    { es: "la impaciencia", en: "impatience", forms: ["impaciencia"] },
    { es: "la mantequilla", en: "butter", forms: ["mantequilla"] },
    { es: "mezclar", en: "to mix", forms: ["mezcla"] },
    { es: "la sonrisa", en: "smile", forms: ["sonrisa"] },
  ],
  "el-pez-dorado": [
    { es: "la piedra", en: "stone", forms: ["piedras"] },
    { es: "poner", en: "to put", forms: ["pone"] },
    { es: "el pez", en: "fish", forms: ["pez"] },
    { es: "el espacio", en: "space", forms: ["espacio"] },
    { es: "lavar", en: "to wash", forms: ["lava"] },
    { es: "la mascota", en: "pet", forms: ["mascotas"] },
  ],
  "la-manana-con-niebla": [
    { es: "la niebla", en: "fog", forms: ["niebla"] },
    { es: "ver", en: "to see", forms: ["ve"] },
    { es: "la acera", en: "sidewalk", forms: ["acera"] },
    { es: "afuera", en: "outside", forms: ["afuera"] },
    { es: "mi amor", en: "sweetheart", forms: ["amor"] },
    { es: "aparecer", en: "to appear", forms: ["aparecen"] },
    { es: "la aventura", en: "adventure", forms: ["aventura"] },
    { es: "casi", en: "almost", forms: ["casi"] },
    { es: "el cielo", en: "sky", forms: ["cielo"] },
    { es: "desaparecer", en: "to disappear", forms: ["desaparece"] },
    { es: "despacio", en: "slowly", forms: ["despacio"] },
    { es: "decir", en: "to say", forms: ["dice"] },
    { es: "diferente", en: "different", forms: ["diferente"] },
    { es: "especial", en: "special", forms: ["especial"] },
    { es: "la forma", en: "shape", forms: ["forma"] },
    { es: "húmedo", en: "damp", forms: ["húmedo"] },
    { es: "otra vez", en: "again", forms: ["otra"] },
  ],
  "papa-arregla-la-silla": [
    { es: "la pata", en: "leg (of furniture)", forms: ["pata"] },
    { es: "arreglar", en: "to fix", forms: ["arreglada", "arreglar"] },
    { es: "el clavo", en: "nail", forms: ["clavos"] },
    { es: "la madera", en: "wood", forms: ["madera"] },
    { es: "el martillo", en: "hammer", forms: ["martillo"] },
    { es: "el pegamento", en: "glue", forms: ["pegamento"] },
    { es: "la atención", en: "attention", forms: ["atención"] },
    { es: "decir", en: "to say", forms: ["dice"] },
    { es: "especial", en: "special", forms: ["especial"] },
    { es: "la herramienta", en: "tool", forms: ["herramientas"] },
    { es: "mientras", en: "while", forms: ["mientras"] },
    { es: "el movimiento", en: "movement", forms: ["movimiento"] },
    { es: "orgulloso", en: "proud", forms: ["orgulloso"] },
    { es: "otra vez", en: "again", forms: ["otra"] },
    { es: "el patio", en: "backyard", forms: ["patio"] },
    { es: "poner", en: "to put in", forms: ["poner"] },
    { es: "probar", en: "to test", forms: ["prueba"] },
    { es: "sentarse", en: "to sit down", forms: ["sentarse"] },
    { es: "sostener", en: "to hold", forms: ["sostiene"] },
    { es: "el suelo", en: "floor, ground", forms: ["suelo"] },
    { es: "usar", en: "to use", forms: ["usa"] },
  ],
  "el-chocolate-caliente": [
    { es: "decir", en: "to say", forms: ["dice"] },
    { es: "afuera", en: "outside", forms: ["afuera"] },
    { es: "la olla", en: "pot", forms: ["olla"] },
    { es: "poner", en: "to put", forms: ["pone"] },
    { es: "abrazar", en: "to hug", forms: ["abraza"] },
    { es: "adentro", en: "inside", forms: ["adentro"] },
    { es: "el cielo", en: "sky", forms: ["cielo"] },
    { es: "la crema", en: "cream", forms: ["crema"] },
    { es: "la curiosidad", en: "curiosity", forms: ["curiosidad"] },
    { es: "desde", en: "from", forms: ["desde"] },
    { es: "despacio", en: "slowly", forms: ["despacio"] },
    { es: "dulce", en: "sweet", forms: ["dulce"] },
    { es: "especial", en: "special", forms: ["especial"] },
    { es: "el mundo", en: "world", forms: ["mundo"] },
    { es: "oler", en: "to smell", forms: ["oler"] },
    { es: "calentito", en: "nice and warm, cosy", forms: ["calentitos"] },
  ],
  "las-flores-de-primavera": [
    { es: "la semilla", en: "seed", forms: ["semillas"] },
    { es: "la primavera", en: "spring", forms: ["primavera"] },
    { es: "aparecer", en: "to appear", forms: ["aparecen"] },
    { es: "brillar", en: "to shine", forms: ["brilla"] },
    { es: "cálido", en: "warm", forms: ["cálidos"] },
    { es: "crecer", en: "to grow", forms: ["crecer"] },
    { es: "disfrutar", en: "to enjoy", forms: ["disfruta"] },
    { es: "emocionado", en: "excited", forms: ["emocionada"] },
    { es: "lleno", en: "full", forms: ["lleno"] },
    { es: "pacientemente", en: "patiently", forms: ["pacientemente"] },
    { es: "el pájaro", en: "bird", forms: ["pájaros"] },
    { es: "el paquete", en: "packet", forms: ["paquetes"] },
  ],
  "el-hamster-escapa": [
    { es: "la jaula", en: "cage", forms: ["jaula"] },
    { es: "poner", en: "to put", forms: ["pone"] },
    { es: "la semilla", en: "seed", forms: ["semillas"] },
    { es: "agarrar", en: "to grab, to hold", forms: ["agarra"] },
    { es: "asustado", en: "scared", forms: ["asustado"] },
    { es: "la caja", en: "box", forms: ["caja"] },
    { es: "dar", en: "to give", forms: ["darle"] },
    { es: "despacio", en: "slowly", forms: ["despacio"] },
    { es: "decir", en: "to say", forms: ["dice"] },
    { es: "esperar", en: "to wait", forms: ["esperan"] },
    { es: "gritar", en: "to shout", forms: ["grita"] },
    { es: "hacia", en: "toward", forms: ["hacia"] },
    { es: "el hámster", en: "hamster", forms: ["hámsters"] },
    { es: "la linterna", en: "flashlight", forms: ["linterna"] },
    { es: "el mueble", en: "piece of furniture", forms: ["muebles"] },
    { es: "otra vez", en: "again", forms: ["otra"] },
    { es: "propio", en: "own", forms: ["propio"] },
  ],
  "la-pizza-familiar": [
    { es: "poner", en: "to put", forms: ["pone"] },
    { es: "el ingrediente", en: "ingredient, topping", forms: ["ingredientes"] },
    { es: "el jamón", en: "ham", forms: ["jamón"] },
    { es: "burbujeante", en: "bubbly", forms: ["burbujeante"] },
    { es: "el champiñón", en: "mushroom", forms: ["champiñones"] },
    { es: "decir", en: "to say", forms: ["dice"] },
    { es: "elástico", en: "stretchy", forms: ["elástica"] },
    { es: "elegir", en: "to choose", forms: ["elige"] },
    { es: "especial", en: "special", forms: ["especiales"] },
    { es: "esperar", en: "to wait", forms: ["espera"] },
    { es: "estirar", en: "to stretch out", forms: ["estirarla"] },
    { es: "la harina", en: "flour", forms: ["harina"] },
    { es: "el horno", en: "oven", forms: ["horno"] },
    { es: "llenar", en: "to fill", forms: ["llena"] },
    { es: "el olor", en: "smell", forms: ["olor"] },
  ],
  "ventana-con-hielo": [
    { es: "el hielo", en: "ice", forms: ["hielo"] },
    { es: "el cristal", en: "glass", forms: ["cristal"] },
    { es: "decir", en: "to say", forms: ["dice"] },
    { es: "la estrella", en: "star", forms: ["estrellas"] },
    { es: "formar", en: "to form", forms: ["forma"] },
    { es: "la forma", en: "shape", forms: ["formas"] },
    { es: "estar de acuerdo", en: "to agree", forms: ["acuerdo"] },
    { es: "afuera", en: "outside", forms: ["afuera"] },
    { es: "congelarse", en: "to freeze", forms: ["congela"] },
    { es: "el dedo", en: "finger", forms: ["dedo"] },
    { es: "derretirse", en: "to melt", forms: ["derrite"] },
    { es: "desaparecer", en: "to disappear", forms: ["desaparece"] },
    { es: "despertarse", en: "to wake up", forms: ["despierta"] },
    { es: "especial", en: "special", forms: ["especial"] },
    { es: "explicar", en: "to explain", forms: ["explica"] },
    { es: "extraño", en: "strange", forms: ["extraño"] },
    { es: "guardar", en: "to keep", forms: ["guardarlo"] },
    { es: "la hoja", en: "sheet of paper", forms: ["hoja"] },
    { es: "el papel", en: "paper", forms: ["papel"] },
  ],
  "el-club-de-lectura": [
    { es: "el club", en: "club", forms: ["club"] },
    { es: "la aventura", en: "adventure", forms: ["aventuras"] },
    { es: "decir", en: "to say", forms: ["dice"] },
    { es: "diferente", en: "different", forms: ["diferente"] },
    { es: "entrar", en: "to go in", forms: ["entra"] },
    { es: "próximo", en: "next", forms: ["próximo"] },
    { es: "responder", en: "to answer", forms: ["responde"] },
    { es: "la respuesta", en: "answer", forms: ["respuesta"] },
  ],
  "la-feria-de-ciencias": [
    { es: "la empresa", en: "company", forms: ["empresa", "empresas"] },
    { es: "la galleta", en: "biscuit, cookie", forms: ["galleta", "galletas"] },
    { es: "la caja", en: "box", forms: ["caja"] },
    { es: "decir", en: "to say", forms: ["dice"] },
    { es: "la energía", en: "energy", forms: ["energía"] },
    { es: "la feria de empleo", en: "job fair", forms: ["feria", "empleo"] },
    { es: "la prueba", en: "trial (shift); probar = to taste", forms: ["prueba"] },
    { es: "solar", en: "solar", forms: ["solares"] },
    { es: "la cadena", en: "chain", forms: ["cadena"] },
    { es: "la carpeta", en: "folder", forms: ["carpeta"] },
    { es: "celebrar", en: "to celebrate", forms: ["celebran"] },
    { es: "la cocinera", en: "cook", forms: ["cocinera"] },
    { es: "el currículum", en: "CV, résumé", forms: ["currículum", "currículums"] },
    { es: "la entrevista", en: "interview", forms: ["entrevista"] },
    { es: "próximo", en: "next", forms: ["próxima"] },
    { es: "el proyecto", en: "project", forms: ["proyectos"] },
    { es: "el puesto", en: "stand", forms: ["puesto"] },
    { es: "reír", en: "to laugh", forms: ["ríe"] },
    { es: "el ingeniero", en: "engineer", forms: ["ingeniero"] },
  ],
  "el-actor-nuevo": [
    { es: "la obra", en: "play", forms: ["obra"] },
    { es: "anunciar", en: "to announce", forms: ["anuncia"] },
    { es: "la audición", en: "audition", forms: ["audiciones", "audición"] },
    { es: "el teatro", en: "theater", forms: ["teatro"] },
    { es: "actuar", en: "to act", forms: ["actuar"] },
    { es: "la atención", en: "attention", forms: ["atención"] },
    { es: "decir", en: "to say", forms: ["dice"] },
    { es: "felicitar", en: "to congratulate", forms: ["felicitan"] },
    { es: "frente a", en: "in front of", forms: ["frente"] },
    { es: "organizar", en: "to organize", forms: ["organiza"] },
    { es: "el papel", en: "role", forms: ["papel"] },
    { es: "profundo", en: "deeply", forms: ["profundo"] },
    { es: "respirar", en: "to breathe", forms: ["respira"] },
    { es: "siguiente", en: "next, following", forms: ["siguiente"] },
    { es: "sonreír", en: "to smile", forms: ["sonríe"] },
  ],
  "la-competencia-de-deletreo": [
    { es: "el equipo", en: "team", forms: ["equipo", "equipos"] },
    { es: "la capital", en: "capital city", forms: ["capital"] },
    { es: "la capitana", en: "captain", forms: ["capitana"] },
    { es: "el concurso", en: "quiz, contest", forms: ["concurso"] },
    { es: "el cuerpo", en: "body", forms: ["cuerpo"] },
    { es: "decir", en: "to say", forms: ["dice"] },
    { es: "el dueño", en: "owner", forms: ["dueño"] },
    { es: "la geografía", en: "geography", forms: ["geografía"] },
    { es: "el hueso", en: "bone", forms: ["huesos"] },
    { es: "humano", en: "human", forms: ["humano"] },
    { es: "el premio", en: "prize", forms: ["premio"] },
    { es: "la respuesta", en: "answer", forms: ["respuesta"] },
    { es: "reír", en: "to laugh", forms: ["ríe"] },
    { es: "último", en: "last", forms: ["última"] },
  ],
  "el-estuche-perdido": [
    { es: "el estuche", en: "pencil case", forms: ["estuche"] },
    { es: "adentro", en: "inside", forms: ["adentro"] },
    { es: "ahí", en: "there", forms: ["ahí"] },
    { es: "devolver", en: "to return, give back", forms: ["devolver"] },
    { es: "durante", en: "during", forms: ["durante"] },
    { es: "especial", en: "special", forms: ["especial"] },
    { es: "explicar", en: "to explain", forms: ["explica"] },
    { es: "la goma", en: "eraser", forms: ["goma"] },
    { es: "hacia", en: "toward", forms: ["hacia"] },
    { es: "ninguno", en: "no, not any", forms: ["ningún"] },
    { es: "olvidar", en: "to forget", forms: ["olvidó"] },
    { es: "otra vez", en: "again", forms: ["otra"] },
    { es: "el papel", en: "piece of paper", forms: ["papel"] },
    { es: "el patio", en: "schoolyard", forms: ["patio"] },
    { es: "prestar", en: "to lend", forms: ["prestaste", "prestó"] },
    { es: "recordar", en: "to remember", forms: ["recuerda"] },
  ],
  "la-clase-de-ajedrez": [
    { es: "el ajedrez", en: "chess", forms: ["ajedrez"] },
    { es: "el caballo", en: "knight", forms: ["caballo"] },
    { es: "la pieza", en: "piece", forms: ["pieza", "piezas"] },
    { es: "contra", en: "against", forms: ["contra"] },
    { es: "decir", en: "to say", forms: ["dice"] },
    { es: "durar", en: "to last", forms: ["dura"] },
    { es: "enseñar", en: "to teach", forms: ["enseña"] },
    { es: "la estrategia", en: "strategy", forms: ["estrategia"] },
    { es: "ganar", en: "to win", forms: ["gana"] },
    { es: "el interés", en: "interest", forms: ["interés"] },
    { es: "la jugadora", en: "player", forms: ["jugadora"] },
    { es: "mover", en: "to move", forms: ["mueve"] },
  ],
  "el-equipo-de-baloncesto": [
    { es: "el equipo", en: "team", forms: ["equipo"] },
    { es: "la prueba", en: "tryout", forms: ["pruebas"] },
    { es: "el balón", en: "ball", forms: ["balón"] },
    { es: "anotar", en: "to score", forms: ["anota"] },
    { es: "la atención", en: "attention", forms: ["atención"] },
    { es: "la cancha", en: "court", forms: ["cancha"] },
    { es: "el comentario", en: "comment", forms: ["comentario"] },
    { es: "decir", en: "to say", forms: ["dice"] },
    { es: "explicar", en: "to explain", forms: ["explica"] },
    { es: "los nervios", en: "nerves", forms: ["nervios"] },
    { es: "observar", en: "to watch", forms: ["observa"] },
    { es: "orgulloso", en: "proud", forms: ["orgullosa"] },
    { es: "el papel", en: "paper", forms: ["papel"] },
    { es: "publicar", en: "to post", forms: ["publica"] },
    { es: "siguiente", en: "next, following", forms: ["siguiente"] },
  ],
  "la-bicicleta-nueva": [
    { es: "montar", en: "to ride", forms: ["monta", "montando", "montar"] },
    { es: "hacia", en: "toward", forms: ["hacia"] },
    { es: "sostener", en: "to hold", forms: ["sostiene"] },
    { es: "adelante", en: "ahead", forms: ["adelante"] },
    { es: "el asiento", en: "seat", forms: ["asiento"] },
    { es: "atrás", en: "behind, back", forms: ["atrás"] },
    { es: "la confianza", en: "confidence", forms: ["confianza"] },
    { es: "decir", en: "to say", forms: ["decir", "dice"] },
    { es: "despacio", en: "slowly", forms: ["despacio"] },
    { es: "emocionado", en: "excited", forms: ["emocionada"] },
    { es: "gritar", en: "to shout", forms: ["grita"] },
    { es: "mientras", en: "while", forms: ["mientras"] },
    { es: "orgulloso", en: "proud", forms: ["orgullosa"] },
    { es: "pedalear", en: "to pedal", forms: ["pedalea"] },
    { es: "plano", en: "flat", forms: ["plano"] },
    { es: "poner", en: "to put", forms: ["pone"] },
    { es: "al principio", en: "at first", forms: ["principio"] },
    { es: "de repente", en: "suddenly", forms: ["repente"] },
    { es: "la rueda", en: "wheel", forms: ["ruedas"] },
    { es: "el suelo", en: "ground", forms: ["suelo"] },
    { es: "soltar", en: "to let go of", forms: ["suelta"] },
    { es: "el talento", en: "talent", forms: ["talento"] },
  ],
  "el-concurso-de-dibujo": [
    { es: "el concurso", en: "contest", forms: ["concurso"] },
    { es: "el certificado", en: "certificate", forms: ["certificado"] },
    { es: "el juez", en: "judge", forms: ["jueces"] },
    { es: "poner", en: "to put", forms: ["pone"] },
    { es: "anunciar", en: "to announce", forms: ["anuncian"] },
    { es: "el delfín", en: "dolphin", forms: ["delfín"] },
    { es: "esperar", en: "to wait", forms: ["espera"] },
    { es: "ganar", en: "to win", forms: ["gana"] },
    { es: "el ganador", en: "winner", forms: ["ganadores"] },
    { es: "el grupo", en: "group", forms: ["grupo"] },
    { es: "el león", en: "lion", forms: ["leones"] },
    { es: "marino", en: "sea, marine", forms: ["marina"] },
    { es: "organizar", en: "to organize", forms: ["organiza"] },
    { es: "otro", en: "other", forms: ["otros"] },
    { es: "el pájaro", en: "bird", forms: ["pájaros"] },
    { es: "el premio", en: "prize", forms: ["premio"] },
    { es: "próximo", en: "next", forms: ["próximo"] },
    { es: "la sorpresa", en: "surprise", forms: ["sorpresa"] },
  ],
  "la-clase-de-baile": [
    { es: "el espectáculo", en: "show", forms: ["espectáculo"] },
    { es: "el giro", en: "turn, spin", forms: ["giro", "giros"] },
    { es: "la alegría", en: "joy", forms: ["alegría"] },
    { es: "algunos", en: "some", forms: ["algunos"] },
    { es: "anunciar", en: "to announce", forms: ["anuncia"] },
    { es: "aplaudir", en: "to clap", forms: ["aplauden"] },
    { es: "cometer", en: "to make (a mistake)", forms: ["comete"] },
    { es: "comunitario", en: "community", forms: ["comunitario"] },
    { es: "el corazón", en: "heart", forms: ["corazón"] },
    { es: "decir", en: "to say", forms: ["dice"] },
    { es: "emocionado", en: "excited", forms: ["emocionada"] },
    { es: "el error", en: "mistake", forms: ["errores"] },
    { es: "especial", en: "special", forms: ["especial"] },
    { es: "la fila", en: "row", forms: ["fila"] },
    { es: "frente a", en: "in front of", forms: ["frente"] },
    { es: "lleno", en: "full", forms: ["lleno"] },
    { es: "orgulloso", en: "proud", forms: ["orgullosa"] },
    { es: "otra vez", en: "again", forms: ["otra"] },
    { es: "la paciencia", en: "patience", forms: ["paciencia"] },
    { es: "al principio", en: "at first", forms: ["principio"] },
    { es: "el progreso", en: "progress", forms: ["progreso"] },
    { es: "el salón", en: "hall", forms: ["salón"] },
  ],
  "la-biblioteca-del-barrio": [
    { es: "el bibliotecario", en: "librarian", forms: ["bibliotecario"] },
    { es: "el espacio", en: "space, area", forms: ["espacio"] },
    { es: "el planeta", en: "planet", forms: ["planetas"] },
    { es: "el ratón", en: "mouse", forms: ["ratón"] },
    { es: "la atención", en: "attention", forms: ["atención"] },
    { es: "escanear", en: "to scan", forms: ["escanea"] },
    { es: "especial", en: "special", forms: ["especial"] },
    { es: "la estrella", en: "star", forms: ["estrellas"] },
    { es: "explicar", en: "to explain", forms: ["explica"] },
    { es: "guardar", en: "to put away", forms: ["guarda"] },
    { es: "el mundo", en: "world", forms: ["mundo"] },
    { es: "la portada", en: "cover", forms: ["portada"] },
    { es: "el préstamo", en: "loan, lending", forms: ["préstamos"] },
    { es: "propio", en: "own", forms: ["propios"] },
    { es: "próximo", en: "next", forms: ["próximo"] },
    { es: "el sillón", en: "armchair", forms: ["sillones"] },
  ],
  "el-desfile-del-pueblo": [
    { es: "el desfile", en: "parade", forms: ["desfile"] },
    { es: "el bombero", en: "firefighter", forms: ["bomberos"] },
    { es: "el tambor", en: "drum", forms: ["tambor", "tambores"] },
    { es: "la acera", en: "sidewalk", forms: ["acera"] },
    { es: "aplaudir", en: "to clap", forms: ["aplaude"] },
    { es: "el bailarín", en: "dancer", forms: ["bailarines"] },
    { es: "la bandera", en: "flag", forms: ["banderas"] },
    { es: "el barco", en: "boat", forms: ["barco"] },
    { es: "el camión", en: "truck", forms: ["camión"] },
    { es: "decorado", en: "decorated", forms: ["decoradas"] },
    { es: "decir", en: "to say", forms: ["dice"] },
    { es: "la emoción", en: "excitement", forms: ["emoción"] },
    { es: "esperar", en: "to wait", forms: ["esperan"] },
    { es: "la forma", en: "shape", forms: ["forma"] },
    { es: "el globo", en: "balloon", forms: ["globos"] },
    { es: "el grupo", en: "group", forms: ["grupo"] },
    { es: "mientras", en: "while", forms: ["mientras"] },
    { es: "organizar", en: "to organize", forms: ["organiza"] },
    { es: "otro", en: "other", forms: ["otras"] },
    { es: "principal", en: "main", forms: ["principal"] },
    { es: "el puesto", en: "stand, stall", forms: ["puesto"] },
    { es: "reconocer", en: "to recognize", forms: ["reconoce"] },
    { es: "sonreír", en: "to smile", forms: ["sonríen"] },
    { es: "tradicional", en: "traditional", forms: ["tradicionales"] },
    { es: "el traje", en: "costume", forms: ["trajes"] },
    { es: "la trompeta", en: "trumpet", forms: ["trompetas"] },
    { es: "la carroza", en: "float (in a parade)", forms: ["carroza", "carrozas"] },
  ],
  "la-panaderia-de-la-esquina": [
    { es: "decir", en: "to say", forms: ["dice"] },
    { es: "el bolsillo", en: "pocket", forms: ["bolsillo"] },
    { es: "el cambio", en: "change (money)", forms: ["cambio"] },
    { es: "corto", en: "short", forms: ["corta"] },
    { es: "enseñar", en: "to teach", forms: ["enseña"] },
    { es: "la esquina", en: "corner", forms: ["esquina"] },
    { es: "la forma", en: "shape", forms: ["formas"] },
    { es: "guardar", en: "to put away", forms: ["guarda"] },
    { es: "la moneda", en: "coin", forms: ["monedas"] },
    { es: "el olor", en: "smell", forms: ["olor"] },
    { es: "orgulloso", en: "proud", forms: ["orgullosa"] },
    { es: "el papel", en: "paper", forms: ["papel"] },
    { es: "poner", en: "to put", forms: ["pone"] },
    { es: "señalar", en: "to point at", forms: ["señala"] },
    { es: "sonreír", en: "to smile", forms: ["sonríe"] },
    { es: "la sonrisa", en: "smile", forms: ["sonrisa"] },
  ],
  "la-estacion-de-bomberos": [
    { es: "el bombero", en: "firefighter", forms: ["bombero", "bomberos"] },
    { es: "el camión", en: "truck", forms: ["camión"] },
    { es: "el fuego", en: "fire", forms: ["fuego"] },
    { es: "la insignia", en: "badge", forms: ["insignia"] },
    { es: "la sirena", en: "siren", forms: ["sirena"] },
    { es: "el uniforme", en: "uniform", forms: ["uniforme"] },
    { es: "la atención", en: "attention", forms: ["atención"] },
    { es: "la calma", en: "calm", forms: ["calma"] },
    { es: "desde hace", en: "for (a time)", forms: ["desde"] },
    { es: "emocionado", en: "excited", forms: ["emocionado"] },
    { es: "la escalera", en: "ladder", forms: ["escalera"] },
    { es: "explicar", en: "to explain", forms: ["explica"] },
    { es: "guardar", en: "to keep", forms: ["guarda"] },
    { es: "la manguera", en: "hose", forms: ["mangueras"] },
    { es: "mostrar", en: "to show", forms: ["muestra"] },
    { es: "el papel", en: "paper", forms: ["papel"] },
    { es: "el permiso", en: "permission", forms: ["permiso"] },
    { es: "resistente", en: "resistant", forms: ["resistente"] },
    { es: "responder", en: "to answer", forms: ["responde"] },
    { es: "reír", en: "to laugh", forms: ["ríen"] },
    { es: "la sonrisa", en: "smile", forms: ["sonrisa"] },
    { es: "sonar", en: "to sound", forms: ["suena"] },
  ],
  "el-autobus-numero-diez": [
    { es: "decir", en: "to say", forms: ["dice"] },
    { es: "la maestra", en: "teacher", forms: ["maestra"] },
    { es: "la sonrisa", en: "smile", forms: ["sonrisa"] },
    { es: "el asiento", en: "seat", forms: ["asiento"] },
    { es: "despedirse", en: "to say goodbye", forms: ["despide"] },
    { es: "durar", en: "to last", forms: ["dura"] },
    { es: "durante", en: "during", forms: ["durante"] },
    { es: "el espacio", en: "room, space", forms: ["espacio"] },
    { es: "el interés", en: "interest", forms: ["interés"] },
    { es: "el joven", en: "young man", forms: ["joven"] },
    { es: "levantarse", en: "to stand up", forms: ["levanta"] },
    { es: "lleno", en: "full", forms: ["lleno"] },
    { es: "ofrecer", en: "to offer", forms: ["ofrece"] },
    { es: "orgulloso", en: "proud", forms: ["orgulloso"] },
    { es: "otro", en: "other", forms: ["otros"] },
  ],
  "el-viaje-en-tren": [
    { es: "el asiento", en: "seat", forms: ["asiento"] },
    { es: "durante", en: "during", forms: ["durante"] },
    { es: "ver", en: "to see", forms: ["ve"] },
    { es: "el andén", en: "platform", forms: ["andén"] },
    { es: "la aventura", en: "adventure", forms: ["aventura"] },
    { es: "desde", en: "from", forms: ["desde"] },
    { es: "diferente", en: "different", forms: ["diferentes"] },
    { es: "durar", en: "to last", forms: ["dura"] },
    { es: "emocionado", en: "excited", forms: ["emocionada"] },
    { es: "explorar", en: "to explore", forms: ["explorar"] },
    { es: "hacia", en: "toward", forms: ["hacia"] },
    { es: "el horario", en: "schedule", forms: ["horarios"] },
    { es: "la maleta", en: "suitcase", forms: ["maletas"] },
    { es: "oscuro", en: "dark", forms: ["oscuro"] },
    { es: "el paisaje", en: "landscape", forms: ["paisaje"] },
  ],
  "vacaciones-en-la-ciudad": [
    { es: "ver", en: "to see", forms: ["ve"] },
    { es: "desde", en: "from", forms: ["desde"] },
    { es: "arriba", en: "above, up top", forms: ["arriba"] },
    { es: "conocer", en: "to get to know", forms: ["conocer"] },
    { es: "la esquina", en: "corner", forms: ["esquinas"] },
    { es: "explicar", en: "to explain", forms: ["explica"] },
    { es: "el lago", en: "lake", forms: ["lago"] },
  ],
  "el-acuario": [
    { es: "el acuario", en: "aquarium", forms: ["acuario"] },
    { es: "la estrella de mar", en: "starfish", forms: ["estrella", "estrellas"] },
    { es: "el pingüino", en: "penguin", forms: ["pingüino", "pingüinos"] },
    { es: "el pulpo", en: "octopus", forms: ["pulpo", "pulpos"] },
    { es: "el tanque", en: "tank", forms: ["tanque"] },
    { es: "la tortuga", en: "turtle", forms: ["tortuga", "tortugas"] },
    { es: "el tiburón", en: "shark", forms: ["tiburones"] },
    { es: "áspero", en: "rough", forms: ["áspera"] },
    { es: "cambiar", en: "to change", forms: ["cambia"] },
    { es: "despacio", en: "slowly", forms: ["despacio"] },
    { es: "decir", en: "to say", forms: ["dice"] },
    { es: "emocionado", en: "excited", forms: ["emocionados"] },
    { es: "especial", en: "special", forms: ["especial"] },
    { es: "fascinado", en: "fascinated", forms: ["fascinada"] },
    { es: "frente a", en: "in front of", forms: ["frente"] },
    { es: "hacia", en: "toward", forms: ["hacia"] },
    { es: "mágico", en: "magical", forms: ["mágico"] },
    { es: "marino", en: "sea, marine", forms: ["marinas"] },
    { es: "mientras", en: "while", forms: ["mientras"] },
    { es: "observar", en: "to watch", forms: ["observa"] },
    { es: "otro", en: "other", forms: ["otra"] },
    { es: "el pez", en: "fish", forms: ["peces"] },
    { es: "el peluche", en: "stuffed animal", forms: ["peluche"] },
    { es: "reír", en: "to laugh", forms: ["ríe"] },
  ],
  "el-parque-de-atracciones": [
    { es: "la montaña rusa", en: "roller coaster", forms: ["rusa"] },
    { es: "el algodón de azúcar", en: "cotton candy", forms: ["algodón"] },
    { es: "el parque de atracciones", en: "amusement park", forms: ["atracciones"] },
    { es: "ver", en: "to see", forms: ["ve"] },
    { es: "arriba", en: "above, up top", forms: ["arriba"] },
    { es: "brillante", en: "bright", forms: ["brillantes"] },
    { es: "dar las gracias", en: "to thank", forms: ["da"] },
    { es: "elegir", en: "to choose", forms: ["elige"] },
    { es: "especial", en: "special", forms: ["especial"] },
    { es: "la rueda de la fortuna", en: "Ferris wheel", forms: ["fortuna", "rueda"] },
    { es: "ganar", en: "to win", forms: ["gana"] },
    { es: "gritar", en: "to scream", forms: ["grita"] },
    { es: "hacia", en: "toward", forms: ["hacia"] },
    { es: "inmediatamente", en: "immediately", forms: ["inmediatamente"] },
    { es: "lanzar", en: "to throw", forms: ["lanzar"] },
    { es: "el maíz", en: "corn", forms: ["maíz"] },
    { es: "orgulloso", en: "proud", forms: ["orgulloso"] },
    { es: "el oso", en: "bear", forms: ["oso"] },
    { es: "otra vez", en: "again", forms: ["otra"] },
    { es: "las palomitas de maíz", en: "popcorn", forms: ["palomitas"] },
    { es: "la pelota", en: "ball", forms: ["pelotas"] },
    { es: "el peluche", en: "stuffed animal", forms: ["peluche"] },
    { es: "el premio", en: "prize", forms: ["premio"] },
    { es: "próximo", en: "next", forms: ["próxima"] },
    { es: "el puesto", en: "booth, stand", forms: ["puestos"] },
  ],
  "el-barco-pequeno": [
    { es: "el barco", en: "boat", forms: ["barco"] },
    { es: "el delfín", en: "dolphin", forms: ["delfines"] },
    { es: "acelerar", en: "to speed up", forms: ["acelera"] },
    { es: "la alegría", en: "joy", forms: ["alegría"] },
    { es: "la aventura", en: "adventure", forms: ["aventura"] },
    { es: "el chaleco", en: "vest", forms: ["chaleco"] },
    { es: "dar las gracias", en: "to thank", forms: ["da"] },
    { es: "despacio", en: "slowly", forms: ["despacio"] },
    { es: "emocionado", en: "excited", forms: ["emocionada"] },
    { es: "especial", en: "special", forms: ["especial"] },
    { es: "explicar", en: "to explain", forms: ["explica"] },
    { es: "gritar", en: "to shout", forms: ["grita"] },
    { es: "el grupo", en: "group", forms: ["grupo"] },
    { es: "observar", en: "to watch", forms: ["observan"] },
    { es: "la ola", en: "wave", forms: ["olas"] },
    { es: "otra vez", en: "again", forms: ["otra"] },
    { es: "el paseo", en: "trip, outing", forms: ["paseo"] },
    { es: "próximo", en: "next", forms: ["próximo"] },
    { es: "la regla", en: "rule", forms: ["reglas"] },
    { es: "regresar", en: "to return", forms: ["regresar"] },
    { es: "reírse", en: "to laugh", forms: ["ríe"] },
    { es: "el chaleco salvavidas", en: "life jacket", forms: ["salvavidas"] },
  ],
  "visit-to-the-dentist": [
    { es: "el diente", en: "tooth", forms: ["dientes"] },
    { es: "decir", en: "to say", forms: ["dice"] },
    { es: "el dentista", en: "dentist", forms: ["dentista"] },
    { es: "el cepillo de dientes", en: "toothbrush", forms: ["cepillo"] },
    { es: "el pez", en: "fish", forms: ["peces", "pez"] },
    { es: "abrazar", en: "to hug", forms: ["abraza"] },
    { es: "el acuario", en: "aquarium", forms: ["acuario"] },
    { es: "la boca", en: "mouth", forms: ["boca"] },
    { es: "la cita", en: "appointment", forms: ["cita"] },
    { es: "dar", en: "to give", forms: ["da"] },
    { es: "la sala de espera", en: "waiting room", forms: ["espera"] },
    { es: "el juguete", en: "toy", forms: ["juguetes"] },
    { es: "lavarse", en: "to brush, to wash", forms: ["lava"] },
    { es: "el león", en: "lion", forms: ["león"] },
    { es: "la pegatina", en: "sticker", forms: ["pegatina"] },
    { es: "el peluche", en: "stuffed animal", forms: ["peluche"] },
  ],
  "moving-day": [
    { es: "la caja", en: "box", forms: ["caja", "cajas"] },
    { es: "el camión", en: "truck", forms: ["camión"] },
    { es: "la galleta", en: "cookie", forms: ["galletas"] },
    { es: "viejo", en: "old", forms: ["vieja"] },
    { es: "amar", en: "to love", forms: ["ama"] },
    { es: "diferente", en: "different", forms: ["diferente"] },
    { es: "especial", en: "special", forms: ["especial"] },
    { es: "el juguete", en: "toy", forms: ["juguetes"] },
    { es: "la mudanza", en: "move (house)", forms: ["mudanza"] },
    { es: "los muebles", en: "furniture", forms: ["muebles"] },
    { es: "otro", en: "other", forms: ["otra"] },
    { es: "el pájaro", en: "bird", forms: ["pájaros"] },
    { es: "la pared", en: "wall", forms: ["paredes"] },
    { es: "el plato", en: "plate", forms: ["plato"] },
    { es: "poner", en: "to put", forms: ["pone"] },
  ],
  "picnic-by-the-river": [
    { es: "el pato", en: "duck", forms: ["pato", "patos"] },
    { es: "el río", en: "river", forms: ["río"] },
    { es: "la cesta", en: "basket", forms: ["cesta"] },
    { es: "cuac", en: "quack", forms: ["cuac"] },
    { es: "decir", en: "to say", forms: ["dice"] },
    { es: "la pelota", en: "ball", forms: ["pelota"] },
    { es: "regresar", en: "to return", forms: ["regresa", "regresan"] },
    { es: "adelante", en: "ahead", forms: ["adelante"] },
    { es: "dar", en: "to give", forms: ["da", "dar"] },
    { es: "explicar", en: "to explain", forms: ["explica"] },
    { es: "gritar", en: "to shout", forms: ["grita"] },
    { es: "hacia", en: "toward", forms: ["hacia"] },
    { es: "el picnic", en: "picnic", forms: ["picnic"] },
    { es: "poner", en: "to put", forms: ["pone"] },
    { es: "próximo", en: "next", forms: ["próximo"] },
    { es: "de repente", en: "suddenly", forms: ["repente"] },
  ],
  "night-at-the-movies": [
    { es: "el oso", en: "bear", forms: ["oso"] },
    { es: "decir", en: "to say", forms: ["dice"] },
    { es: "las palomitas", en: "popcorn", forms: ["palomitas"] },
    { es: "aplaudir", en: "to clap", forms: ["aplaude", "aplauden"] },
    { es: "dar la mano", en: "to take someone's hand", forms: ["da"] },
    { es: "entrar", en: "to go in", forms: ["entrar"] },
    { es: "abrazar", en: "to hug", forms: ["abraza"] },
    { es: "el bosque", en: "forest", forms: ["bosque"] },
    { es: "la entrada", en: "ticket", forms: ["entradas"] },
    { es: "gritar", en: "to shout", forms: ["grita"] },
    { es: "oscuro", en: "dark", forms: ["oscura"] },
    { es: "la pantalla", en: "screen", forms: ["pantalla"] },
    { es: "el pañuelo", en: "tissue", forms: ["pañuelo"] },
  ],
  "a-day-on-the-farm": [
    { es: "la granja", en: "farm", forms: ["granja"] },
    { es: "el caballo", en: "horse", forms: ["caballo"] },
    { es: "la gallina", en: "hen", forms: ["gallinas"] },
    { es: "el ternero", en: "calf", forms: ["ternero"] },
    { es: "levantarse", en: "to get up", forms: ["levanta"] },
    { es: "la botella", en: "bottle", forms: ["botella"] },
    { es: "el cerdo", en: "pig", forms: ["cerdos"] },
    { es: "dar", en: "to give", forms: ["dar"] },
    { es: "despacio", en: "slowly", forms: ["despacio"] },
    { es: "decir", en: "to say", forms: ["dice"] },
    { es: "emocionado", en: "excited", forms: ["emocionada"] },
    { es: "enseñar", en: "to teach", forms: ["enseña"] },
    { es: "el gallinero", en: "henhouse", forms: ["gallinero"] },
    { es: "marrón", en: "brown", forms: ["marrón"] },
    { es: "montar", en: "to ride", forms: ["monta"] },
    { es: "la paja", en: "straw", forms: ["paja"] },
    { es: "responder", en: "to answer", forms: ["responde"] },
    { es: "reírse", en: "to laugh", forms: ["ríe"] },
    { es: "la vaca", en: "cow", forms: ["vacas"] },
    { es: "ver", en: "to see", forms: ["ve"] },
  ],
  "haircut-at-the-barber": [
    { es: "el pelo", en: "hair", forms: ["pelo"] },
    { es: "cortar", en: "to cut; cortarse el pelo = to get a haircut", forms: ["corta", "cortarse"] },
    { es: "el corte de pelo", en: "haircut", forms: ["corte"] },
    { es: "corto", en: "short", forms: ["corto"] },
    { es: "decir", en: "to say", forms: ["dice"] },
    { es: "ver", en: "to see", forms: ["ve"] },
    { es: "la peluquería", en: "barbershop", forms: ["peluquería"] },
    { es: "la pizarra", en: "board, chalkboard", forms: ["pizarra"] },
    { es: "caer", en: "to fall", forms: ["cae"] },
    { es: "cubrir", en: "to cover", forms: ["cubre"] },
    { es: "diferente", en: "different", forms: ["diferente"] },
    { es: "la máquina", en: "clippers", forms: ["máquina"] },
    { es: "la pared", en: "wall", forms: ["paredes"] },
    { es: "reírse de", en: "to laugh at", forms: ["reírse"] },
    { es: "reírse", en: "to laugh", forms: ["ríen"] },
    { es: "sonreír", en: "to smile", forms: ["sonríe"] },
  ],
  "letter-from-grandma": [
    { es: "el buzón", en: "mailbox", forms: ["buzón"] },
    { es: "responder", en: "to answer", forms: ["responde", "responder"] },
    { es: "el bolígrafo", en: "pen", forms: ["bolígrafo"] },
    { es: "la amiga por correspondencia", en: "pen pal", forms: ["correspondencia"] },
    { es: "dar", en: "to give", forms: ["da"] },
    { es: "especial", en: "special", forms: ["especial"] },
    { es: "la factura", en: "bill", forms: ["facturas"] },
    { es: "el móvil", en: "cell phone", forms: ["móvil"] },
    { es: "la natación", en: "swimming", forms: ["natación"] },
    { es: "otro", en: "another", forms: ["otro"] },
    { es: "el papel", en: "paper", forms: ["papel"] },
    { es: "poner", en: "to put", forms: ["pone"] },
    { es: "la publicidad", en: "advertising, junk mail", forms: ["publicidad"] },
    { es: "reírse", en: "to laugh", forms: ["ríe"] },
  ],
  "dinner-at-the-restaurant": [
    { es: "el camarero", en: "waiter", forms: ["camarero"] },
    { es: "decir", en: "to say", forms: ["dice"] },
    { es: "el mole", en: "mole (Mexican sauce)", forms: ["mole"] },
    { es: "la palabra", en: "word", forms: ["palabra", "palabras"] },
    { es: "el plato", en: "plate, dish", forms: ["plato"] },
    { es: "probar", en: "to taste", forms: ["prueba"] },
    { es: "la quesadilla", en: "quesadilla", forms: ["quesadilla", "quesadillas"] },
    { es: "alegre", en: "cheerful", forms: ["alegre"] },
    { es: "el aniversario", en: "anniversary", forms: ["aniversario"] },
    { es: "la atención", en: "attention", forms: ["atención"] },
    { es: "celebrar", en: "to celebrate", forms: ["celebrar"] },
    { es: "conocer", en: "to know", forms: ["conoce"] },
    { es: "dar", en: "to give", forms: ["da"] },
    { es: "descubrir", en: "to discover", forms: ["descubre"] },
    { es: "dulce", en: "sweet", forms: ["dulce"] },
    { es: "la enchilada", en: "enchilada", forms: ["enchiladas"] },
    { es: "explicar", en: "to explain", forms: ["explica"] },
    { es: "la libreta", en: "notepad", forms: ["libreta"] },
    { es: "marrón", en: "brown", forms: ["marrón"] },
    { es: "el menú", en: "menu", forms: ["menú", "menús"] },
    { es: "orgulloso", en: "proud", forms: ["orgullosa"] },
    { es: "oscuro", en: "dark", forms: ["oscura"] },
    { es: "la piñata", en: "piñata", forms: ["piñatas"] },
    { es: "la sorpresa", en: "surprise", forms: ["sorpresa"] },
  ],
  "the-red-balloon": [
    { es: "el globo", en: "balloon", forms: ["globo", "globos"] },
    { es: "la feria", en: "fair", forms: ["feria"] },
    { es: "la cuerda", en: "string", forms: ["cuerda"] },
    { es: "ver", en: "to see", forms: ["ve"] },
    { es: "el algodón de azúcar", en: "cotton candy", forms: ["algodón"] },
    { es: "atar", en: "to tie", forms: ["ata"] },
    { es: "los caballitos", en: "merry-go-round", forms: ["caballitos"] },
    { es: "el cielo", en: "sky", forms: ["cielo"] },
    { es: "dar", en: "to give", forms: ["da"] },
    { es: "la escalera", en: "ladder", forms: ["escalera"] },
    { es: "el payaso", en: "clown", forms: ["payasos"] },
    { es: "la rama", en: "branch", forms: ["rama"] },
  ],
  "strawberry-ice-cream": [
    { es: "decir", en: "to say", forms: ["dice"] },
    { es: "la heladería", en: "ice cream shop", forms: ["heladería"] },
    { es: "el sabor", en: "flavor", forms: ["sabor", "sabores"] },
    { es: "el bolsillo", en: "pocket", forms: ["bolsillo"] },
    { es: "caer", en: "to fall", forms: ["cae"] },
    { es: "la cucharada", en: "spoonful", forms: ["cucharada"] },
    { es: "dar", en: "to give", forms: ["da"] },
    { es: "derretirse", en: "to melt", forms: ["derrite"] },
    { es: "dulce", en: "sweet", forms: ["dulce"] },
    { es: "entrar", en: "to go in", forms: ["entra"] },
    { es: "el grado", en: "degree", forms: ["grados"] },
    { es: "el limón", en: "lemon", forms: ["limón"] },
    { es: "otra vez", en: "again", forms: ["otra"] },
    { es: "responder", en: "to answer", forms: ["responde"] },
    { es: "reírse", en: "to laugh", forms: ["ríen"] },
    { es: "sentado", en: "sitting", forms: ["sentado"] },
    { es: "sonreír", en: "to smile", forms: ["sonríe"] },
  ],
  "the-yellow-butterfly": [
    { es: "la mariposa", en: "butterfly", forms: ["mariposa"] },
    { es: "el frasco", en: "jar", forms: ["frasco"] },
    { es: "el insecto", en: "insect", forms: ["insecto", "insectos"] },
    { es: "volar", en: "to fly", forms: ["vuela"] },
    { es: "la lupa", en: "magnifying glass", forms: ["lupa"] },
    { es: "poner", en: "to put", forms: ["pone"] },
    { es: "el ala", en: "wing", forms: ["alas"] },
    { es: "el cristal", en: "glass", forms: ["cristal"] },
    { es: "despacio", en: "slowly", forms: ["despacio"] },
    { es: "decir", en: "to say", forms: ["dice"] },
    { es: "explicar", en: "to explain", forms: ["explica"] },
    { es: "el fondo", en: "bottom", forms: ["fondo"] },
    { es: "otra vez", en: "again", forms: ["otra"] },
    { es: "la primavera", en: "spring", forms: ["primavera"] },
    { es: "quieto", en: "still", forms: ["quieta"] },
    { es: "de repente", en: "suddenly", forms: ["repente"] },
    { es: "sonreír", en: "to smile", forms: ["sonríe"] },
  ],
  "treasure-map-in-the-attic": [
    { es: "viejo", en: "old", forms: ["vieja", "viejo", "viejos"] },
    { es: "la caja", en: "box", forms: ["caja", "cajas"] },
    { es: "el tesoro", en: "treasure", forms: ["tesoro"] },
    { es: "el pozo", en: "well", forms: ["pozo"] },
    { es: "el ático", en: "attic", forms: ["ático"] },
    { es: "el baúl", en: "trunk, chest", forms: ["baúl"] },
    { es: "la canica", en: "marble", forms: ["canicas"] },
    { es: "decir", en: "to say", forms: ["dice"] },
    { es: "la piedra", en: "stone", forms: ["piedra"] },
    { es: "la emoción", en: "excitement", forms: ["emoción"] },
    { es: "el esfuerzo", en: "effort", forms: ["esfuerzo"] },
    { es: "llover", en: "to rain", forms: ["llueve"] },
    { es: "la madera", en: "wood", forms: ["madera"] },
    { es: "mover", en: "to move", forms: ["mueven"] },
    { es: "ni", en: "nor", forms: ["ni"] },
    { es: "el oro", en: "gold", forms: ["oro"] },
    { es: "oscuro", en: "dark", forms: ["oscuro"] },
    { es: "la palabra", en: "word", forms: ["palabras"] },
    { es: "el papel", en: "paper", forms: ["papel"] },
    { es: "plano", en: "flat", forms: ["plana"] },
    { es: "el polvo", en: "dust", forms: ["polvo"] },
  ],
  "dads-new-job": [
    { es: "el conductor", en: "driver", forms: ["conductor"] },
    { es: "decir", en: "to say", forms: ["dice"] },
    { es: "el bolsillo", en: "pocket", forms: ["bolsillo"] },
    { es: "conducir", en: "to drive", forms: ["conduce"] },
    { es: "guiñar", en: "to wink", forms: ["guiña"] },
    { es: "el ojo", en: "eye", forms: ["ojo"] },
    { es: "orgulloso", en: "proud", forms: ["orgullosa"] },
    { es: "poner", en: "to put", forms: ["pone"] },
    { es: "la sonrisa", en: "smile", forms: ["sonrisa"] },
  ],
  "my-little-brother": [
    { es: "el concurso", en: "contest", forms: ["concurso"] },
    { es: "dar", en: "to give", forms: ["doy"] },
    { es: "entrar", en: "to go in", forms: ["entra", "entro"] },
    { es: "mojado", en: "wet", forms: ["mojada", "mojado"] },
    { es: "el abrazo", en: "hug", forms: ["abrazo"] },
    { es: "el barco", en: "boat", forms: ["barcos"] },
    { es: "decir", en: "to say", forms: ["dice"] },
    { es: "enfadarse", en: "to get angry", forms: ["enfado"] },
    { es: "ganar", en: "to win", forms: ["gana"] },
    { es: "natural", en: "natural", forms: ["natural"] },
    { es: "el papel", en: "paper", forms: ["papel"] },
    { es: "el pez", en: "fish", forms: ["peces"] },
    { es: "el pelo", en: "hair", forms: ["pelo"] },
    { es: "poner", en: "to put", forms: ["pongo"] },
    { es: "el premio", en: "prize", forms: ["premio"] },
  ],
  "laundry-day": [
    { es: "decir", en: "to say", forms: ["dice"] },
    { es: "la lavadora", en: "washing machine", forms: ["lavadora"] },
    { es: "poner", en: "to put", forms: ["pone"] },
    { es: "la sábana", en: "sheet", forms: ["sábana", "sábanas"] },
    { es: "ver", en: "to see", forms: ["ve"] },
    { es: "alegre", en: "cheerful", forms: ["alegre"] },
    { es: "apretar", en: "to press", forms: ["aprieta"] },
    { es: "el botón", en: "button", forms: ["botón"] },
    { es: "el colegio", en: "school", forms: ["colegio"] },
    { es: "dar vueltas", en: "to spin", forms: ["da"] },
    { es: "explicar", en: "to explain", forms: ["explica"] },
    { es: "el fondo", en: "bottom", forms: ["fondo"] },
    { es: "el jabón", en: "soap", forms: ["jabón"] },
    { es: "lavar", en: "to wash", forms: ["lavar"] },
    { es: "orgulloso", en: "proud", forms: ["orgulloso"] },
    { es: "regresar", en: "to return", forms: ["regresa"] },
    { es: "reírse", en: "to laugh", forms: ["ríe"] },
    { es: "separar", en: "to separate", forms: ["separa"] },
  ],
  "painting-class-in-the-park": [
    { es: "el lago", en: "lake", forms: ["lago"] },
    { es: "el papel", en: "paper", forms: ["papel"] },
    { es: "decir", en: "to say", forms: ["dice"] },
    { es: "el pato", en: "duck", forms: ["patos"] },
    { es: "el puente", en: "bridge", forms: ["puente"] },
    { es: "el cielo", en: "sky", forms: ["cielo"] },
    { es: "dar", en: "to give", forms: ["da"] },
    { es: "especial", en: "special", forms: ["especial"] },
    { es: "la fantasía", en: "fantasy", forms: ["fantasía"] },
    { es: "frustrado", en: "frustrated", forms: ["frustrada"] },
    { es: "la línea", en: "line", forms: ["línea"] },
    { es: "otro", en: "other", forms: ["otras"] },
    { es: "la personalidad", en: "personality", forms: ["personalidad"] },
    { es: "el pincel", en: "paintbrush", forms: ["pinceles"] },
  ],
  "used-book-sale": [
    { es: "decir", en: "to say", forms: ["dice"] },
    { es: "la aventura", en: "adventure", forms: ["aventuras"] },
    { es: "la caja", en: "box", forms: ["caja"] },
    { es: "las condiciones", en: "condition", forms: ["condiciones"] },
    { es: "doblado", en: "folded", forms: ["doblado"] },
    { es: "emocionante", en: "exciting", forms: ["emocionante"] },
    { es: "escrito", en: "written", forms: ["escrita"] },
    { es: "el lector", en: "reader", forms: ["lector"] },
    { es: "otro", en: "another", forms: ["otra"] },
    { es: "otro", en: "other", forms: ["otros"] },
    { es: "el papel", en: "piece of paper", forms: ["papel"] },
    { es: "el pirata", en: "pirate", forms: ["piratas"] },
    { es: "la portada", en: "cover", forms: ["portada"] },
    { es: "la sonrisa", en: "smile", forms: ["sonrisa"] },
    { es: "el título", en: "title", forms: ["título"] },
    { es: "usado", en: "used", forms: ["usados"] },
    { es: "ver", en: "to see", forms: ["ve"] },
  ],
  "spider-in-the-bathroom": [
    { es: "la araña", en: "spider", forms: ["araña", "arañas"] },
    { es: "decir", en: "to say", forms: ["dice"] },
    { es: "el papel", en: "paper", forms: ["papel"] },
    { es: "la bañera", en: "bathtub", forms: ["bañera"] },
    { es: "aplaudir", en: "to clap", forms: ["aplauden"] },
    { es: "dejar", en: "to leave", forms: ["deja"] },
    { es: "desde", en: "from", forms: ["desde"] },
    { es: "despacio", en: "slowly", forms: ["despacio"] },
    { es: "entrar", en: "to go in", forms: ["entra", "entrar"] },
    { es: "la experta", en: "expert", forms: ["experta"] },
    { es: "gritar", en: "to shout", forms: ["grita"] },
    { es: "hacia", en: "toward", forms: ["hacia"] },
    { es: "la hoja", en: "sheet (of paper)", forms: ["hoja"] },
    { es: "el mosquito", en: "mosquito", forms: ["mosquitos"] },
    { es: "moverse", en: "to move", forms: ["mueve"] },
    { es: "la pata", en: "leg (of an animal)", forms: ["patas"] },
    { es: "el plan", en: "plan", forms: ["plan"] },
  ],
  "a-night-of-stars": [
    { es: "la estrella", en: "star", forms: ["estrella", "estrellas"] },
    { es: "decir", en: "to say", forms: ["dice", "dicen"] },
    { es: "el cielo", en: "sky", forms: ["cielo"] },
    { es: "la estrella fugaz", en: "shooting star", forms: ["fugaces", "fugaz"] },
    { es: "otro", en: "another", forms: ["otra"] },
    { es: "sonreír", en: "to smile", forms: ["sonríe"] },
    { es: "ver", en: "to see", forms: ["ves"] },
    { es: "algunos", en: "some", forms: ["algunas"] },
    { es: "contigo", en: "with you", forms: ["contigo"] },
    { es: "cruzar", en: "to cross", forms: ["cruza"] },
    { es: "enseñar", en: "to show", forms: ["enseña"] },
    { es: "especial", en: "special", forms: ["especial"] },
    { es: "explicar", en: "to explain", forms: ["explica"] },
    { es: "formar", en: "to form", forms: ["forman"] },
    { es: "gritar", en: "to shout", forms: ["grita"] },
    { es: "oscuro", en: "dark", forms: ["oscuro"] },
  ],
  "bird-nest-in-the-window": [
    { es: "el nido", en: "nest", forms: ["nido"] },
    { es: "el pájaro", en: "bird", forms: ["pájaro", "pájaros"] },
    { es: "el pajarito", en: "baby bird", forms: ["pajaritos"] },
    { es: "pío", en: "tweet", forms: ["pío"] },
    { es: "volar", en: "to fly", forms: ["vuelan"] },
    { es: "decir", en: "to say", forms: ["dice"] },
    { es: "traer", en: "to bring", forms: ["trae", "traen"] },
    { es: "ver", en: "to see", forms: ["ve"] },
    { es: "la boca", en: "mouth", forms: ["boca"] },
    { es: "construir", en: "to build", forms: ["construyendo"] },
    { es: "crecer", en: "to grow", forms: ["crecen"] },
    { es: "esperar", en: "to wait for", forms: ["esperar"] },
    { es: "la forma", en: "shape", forms: ["forma"] },
    { es: "guardar", en: "to put away", forms: ["guarda"] },
    { es: "el gusano", en: "worm", forms: ["gusanos"] },
    { es: "la hoja", en: "leaf", forms: ["hojas"] },
    { es: "el insecto", en: "insect", forms: ["insectos"] },
    { es: "el palito", en: "little stick, twig", forms: ["palitos"] },
    { es: "el pico", en: "beak", forms: ["pico"] },
    { es: "la primavera", en: "spring", forms: ["primavera"] },
    { es: "seco", en: "dry", forms: ["secas"] },
    { es: "sentado", en: "sitting", forms: ["sentada"] },
  ],
  "the-costume-party": [
    { es: "la caja", en: "box", forms: ["caja", "cajas"] },
    { es: "el disfraz", en: "costume", forms: ["disfraces", "disfraz"] },
    { es: "el aluminio", en: "aluminum", forms: ["aluminio"] },
    { es: "el astronauta", en: "astronaut", forms: ["astronauta"] },
    { es: "la botella", en: "bottle", forms: ["botellas"] },
    { es: "el casco", en: "helmet", forms: ["casco"] },
    { es: "decir", en: "to say", forms: ["dice"] },
    { es: "el papel de aluminio", en: "aluminum foil", forms: ["papel"] },
    { es: "poner", en: "to put", forms: ["pone", "ponen"] },
    { es: "el premio", en: "prize", forms: ["premio"] },
    { es: "el traje", en: "suit", forms: ["traje"] },
    { es: "el cartón", en: "cardboard", forms: ["cartón"] },
    { es: "el cuerpo", en: "body", forms: ["cuerpo"] },
    { es: "dar", en: "to give", forms: ["da"] },
    { es: "la estantería", en: "shelf", forms: ["estantería"] },
    { es: "original", en: "original", forms: ["original"] },
    { es: "el oxígeno", en: "oxygen", forms: ["oxígeno"] },
    { es: "el pirata", en: "pirate", forms: ["pirata"] },
    { es: "la princesa", en: "princess", forms: ["princesa"] },
    { es: "responder", en: "to answer", forms: ["responde"] },
  ],
  "the-forgotten-umbrella": [
    { es: "el paraguas", en: "umbrella", forms: ["paraguas"] },
    { es: "el asiento", en: "seat", forms: ["asiento"] },
    { es: "decir", en: "to say", forms: ["dice"] },
    { es: "la juventud", en: "youth", forms: ["juventud"] },
    { es: "llover", en: "to rain", forms: ["llueve"] },
    { es: "mojado", en: "wet", forms: ["mojada"] },
    { es: "olvidar", en: "to forget", forms: ["olvidar"] },
    { es: "volver a + inf.", en: "to do (something) again", forms: ["vuelve"] },
    { es: "sentado", en: "sitting", forms: ["sentado"] },
  ],
  "checkup-at-the-doctor": [
    { es: "decir", en: "to say", forms: ["dice"] },
    { es: "aaa", en: "ahh", forms: ["aaa"] },
    { es: "el centímetro", en: "centimeter", forms: ["centímetros"] },
    { es: "el estetoscopio", en: "stethoscope", forms: ["estetoscopio"] },
    { es: "respirar", en: "to breathe", forms: ["respira"] },
    { es: "la revisión", en: "checkup", forms: ["revisiones", "revisión"] },
    { es: "la altura", en: "height", forms: ["altura"] },
    { es: "la báscula", en: "scale", forms: ["báscula"] },
    { es: "la bata", en: "coat, lab coat", forms: ["bata"] },
    { es: "la boca", en: "mouth", forms: ["boca"] },
    { es: "conocer", en: "to know", forms: ["conoce"] },
    { es: "contra", en: "against", forms: ["contra"] },
    { es: "el corazón", en: "heart", forms: ["corazón"] },
    { es: "crecer", en: "to grow (ha crecido = has grown)", forms: ["crecido"] },
    { es: "desde", en: "since", forms: ["desde"] },
    { es: "la garganta", en: "throat", forms: ["garganta"] },
    { es: "el metro", en: "meter", forms: ["metro"] },
    { es: "medir", en: "to measure", forms: ["mide"] },
    { es: "el oído", en: "ear", forms: ["oídos"] },
    { es: "orgulloso", en: "proud", forms: ["orgulloso"] },
    { es: "ponerse de pie", en: "to stand up", forms: ["pone"] },
  ],
  "the-neighbors-dog": [
    { es: "despacio", en: "slowly", forms: ["despacio"] },
    { es: "decir", en: "to say", forms: ["decir", "dice"] },
    { es: "el corazón", en: "heart", forms: ["corazón"] },
    { es: "cruzar", en: "to cross", forms: ["cruza"] },
    { es: "dar miedo", en: "to scare", forms: ["dan"] },
    { es: "la hierba", en: "grass", forms: ["hierba"] },
    { es: "marrón", en: "brown", forms: ["marrón"] },
    { es: "otro", en: "other", forms: ["otro", "otros"] },
    { es: "el pelo", en: "fur", forms: ["pelo"] },
    { es: "poner", en: "to put", forms: ["pone"] },
    { es: "sonreír", en: "to smile", forms: ["sonríe"] },
    { es: "suave", en: "soft", forms: ["suave"] },
    { es: "tembloroso", en: "shaking, trembling", forms: ["temblorosa"] },
    { es: "todavía", en: "still", forms: ["todavía"] },
  ],
  "saturday-house-cleaning": [
    { es: "la basura", en: "trash", forms: ["basura"] },
    { es: "el plato", en: "dish", forms: ["platos"] },
    { es: "barrer", en: "to sweep", forms: ["barre", "barrer"] },
    { es: "decir", en: "to say", forms: ["dice", "dicen"] },
    { es: "elegir", en: "to choose", forms: ["elige"] },
    { es: "la limpieza", en: "cleaning", forms: ["limpieza"] },
    { es: "ordenar", en: "to tidy", forms: ["ordena", "ordenar"] },
    { es: "brillante", en: "shiny", forms: ["brillante"] },
    { es: "la caja", en: "box", forms: ["caja"] },
    { es: "casero", en: "homemade", forms: ["casera"] },
    { es: "el cojín", en: "cushion", forms: ["cojines"] },
    { es: "la escoba", en: "broom", forms: ["escoba"] },
    { es: "lavar", en: "to wash", forms: ["lavar"] },
    { es: "mientras", en: "while", forms: ["mientras"] },
    { es: "otra vez", en: "again", forms: ["otra"] },
    { es: "poner", en: "to put on", forms: ["pone"] },
    { es: "próximo", en: "next", forms: ["próximo"] },
    { es: "regar", en: "to water", forms: ["regar"] },
  ],
  "the-new-backpack": [
    { es: "el bolsillo", en: "pocket", forms: ["bolsillo", "bolsillos"] },
    { es: "decir", en: "to say", forms: ["dice"] },
    { es: "viejo", en: "old", forms: ["vieja", "viejo"] },
    { es: "la atención", en: "attention", forms: ["atención"] },
    { es: "atrás", en: "at the back", forms: ["atrás"] },
    { es: "conocer", en: "to know", forms: ["conoce"] },
    { es: "el cuero", en: "leather", forms: ["cuero"] },
    { es: "explicar", en: "to explain", forms: ["explica"] },
    { es: "feo", en: "ugly", forms: ["fea"] },
    { es: "marrón", en: "brown", forms: ["marrón"] },
    { es: "moderno", en: "modern", forms: ["modernas"] },
    { es: "el ordenador", en: "computer", forms: ["ordenador"] },
    { es: "orgulloso", en: "proud", forms: ["orgulloso"] },
    { es: "responder", en: "to answer", forms: ["responde"] },
    { es: "el río", en: "river", forms: ["río"] },
    { es: "siguiente", en: "next", forms: ["siguiente"] },
    { es: "sonreír", en: "to smile", forms: ["sonríen"] },
  ],
  "aunt-rosas-piano": [
    { es: "decir", en: "to say", forms: ["dice"] },
    { es: "abrazar", en: "to hug", forms: ["abraza"] },
    { es: "aplaudir", en: "to clap", forms: ["aplauden"] },
    { es: "el colegio", en: "school", forms: ["colegio"] },
    { es: "completo", en: "whole, complete", forms: ["completa"] },
    { es: "el dedo", en: "finger", forms: ["dedos"] },
    { es: "enseñar", en: "to teach", forms: ["enseña"] },
    { es: "el error", en: "mistake", forms: ["errores"] },
    { es: "frustrado", en: "frustrated", forms: ["frustrada"] },
    { es: "la lágrima", en: "tear", forms: ["lágrimas"] },
    { es: "la paciencia", en: "patience", forms: ["paciencia"] },
    { es: "al principio", en: "at first", forms: ["principio"] },
    { es: "próximo", en: "next", forms: ["próximo"] },
    { es: "el teclado", en: "keyboard", forms: ["teclado"] },
  ],
  "field-trip-to-the-castle": [
    { es: "el castillo", en: "castle", forms: ["castillo", "castillos"] },
    { es: "decir", en: "to say", forms: ["dice"] },
    { es: "el caballero", en: "knight", forms: ["caballeros"] },
    { es: "el foso", en: "moat", forms: ["foso"] },
    { es: "responder", en: "to answer", forms: ["responde"] },
    { es: "la armadura", en: "armor", forms: ["armaduras"] },
    { es: "dar", en: "to give", forms: ["da"] },
    { es: "la espada", en: "sword", forms: ["espadas"] },
    { es: "esperar", en: "to wait for", forms: ["espera"] },
    { es: "la excursión", en: "field trip", forms: ["excursión"] },
    { es: "el experto", en: "expert", forms: ["experto"] },
    { es: "explicar", en: "to explain", forms: ["explica"] },
    { es: "el grado", en: "grade", forms: ["grado"] },
    { es: "impresionante", en: "impressive", forms: ["impresionante"] },
    { es: "levantar", en: "to raise", forms: ["levanta"] },
    { es: "el muro", en: "wall", forms: ["muros"] },
    { es: "ochocientos", en: "eight hundred", forms: ["ochocientos"] },
    { es: "la piedra", en: "stone", forms: ["piedra"] },
    { es: "el puente", en: "bridge", forms: ["puente"] },
    { es: "la sorpresa", en: "surprise", forms: ["sorpresa"] },
  ],
  "grandpas-toy-train": [
    { es: "la locomotora", en: "locomotive", forms: ["locomotora"] },
    { es: "decir", en: "to say", forms: ["dice"] },
    { es: "la vía", en: "track", forms: ["vías"] },
    { es: "el cable", en: "cable, wire", forms: ["cable", "cables"] },
    { es: "la caja", en: "box", forms: ["caja"] },
    { es: "chu", en: "choo", forms: ["chu"] },
    { es: "el vagón", en: "train car", forms: ["vagones"] },
    { es: "apretar", en: "to press", forms: ["aprieta"] },
    { es: "arreglar", en: "to fix", forms: ["arreglarlo"] },
    { es: "el botón", en: "button", forms: ["botón"] },
    { es: "el círculo", en: "circle", forms: ["círculo"] },
    { es: "conectar", en: "to connect", forms: ["conecta"] },
    { es: "desde", en: "since", forms: ["desde"] },
    { es: "emocionado", en: "excited", forms: ["emocionado"] },
    { es: "la forma", en: "shape", forms: ["forma"] },
    { es: "la herramienta", en: "tool", forms: ["herramientas"] },
    { es: "el juguete", en: "toy", forms: ["juguetes"] },
    { es: "la linterna", en: "flashlight", forms: ["linterna"] },
    { es: "el motor", en: "motor", forms: ["motor"] },
    { es: "moverse", en: "to move", forms: ["mueve"] },
    { es: "la pieza", en: "part, piece", forms: ["piezas"] },
    { es: "el recuerdo", en: "memory", forms: ["recuerdo"] },
    { es: "sonreír", en: "to smile", forms: ["sonríe"] },
    { es: "la sonrisa", en: "smile", forms: ["sonrisa"] },
    { es: "el suelo", en: "floor", forms: ["suelo"] },
    { es: "usar", en: "to use, to wear", forms: ["usa"] },
  ],
  "rainbow-after-the-storm": [
    { es: "el arcoíris", en: "rainbow", forms: ["arcoíris"] },
    { es: "la gota", en: "drop", forms: ["gotas"] },
    { es: "el balcón", en: "balcony", forms: ["balcón"] },
    { es: "decir", en: "to say", forms: ["dice"] },
    { es: "añil", en: "indigo", forms: ["añil"] },
    { es: "aparecer", en: "to appear", forms: ["aparece"] },
    { es: "el cielo", en: "sky", forms: ["cielo"] },
    { es: "el cristal", en: "glass, windowpane", forms: ["cristal"] },
    { es: "formarse", en: "to form", forms: ["forma"] },
    { es: "gritar", en: "to shout", forms: ["grita"] },
    { es: "la linterna", en: "flashlight", forms: ["linterna"] },
    { es: "llover", en: "to rain", forms: ["llueve"] },
    { es: "moverse", en: "to move", forms: ["mueven"] },
    { es: "otra vez", en: "again", forms: ["otra"] },
    { es: "poner", en: "to put", forms: ["pone"] },
    { es: "de repente", en: "suddenly", forms: ["repente"] },
    { es: "responder", en: "to answer", forms: ["responde"] },
    { es: "separar", en: "to separate", forms: ["separan"] },
    { es: "el suspiro", en: "sigh", forms: ["suspiro"] },
  ],
};
