// Synced from cheneygross-afk/lengo:src/lib/decks/types.ts by scripts/sync-content.mjs -- edit it there, not here.
// One card of a premade frequency deck (src/lib/decks/frequency-*.ts,
// generated by scripts/build-frequency-decks.ts).
export type DeckCard = {
  /** Frequency rank in spoken Spanish (film and TV subtitles), 1 = most frequent. */
  rank: number;
  /** Dictionary form, with the article for nouns ("el cuerpo") and both
   * endings for adjectives ("lindo/a"). */
  es: string;
  en: string;
  /** Part of speech label ("n.", "v.", "adj."...), "" when not obvious. */
  pos: string;
  /** Example sentence, from the course's lessons where one fits. */
  exEs?: string;
  exEn?: string;
};

export type DeckLevel = "A1" | "A2" | "B1" | "B2" | "C1";

export type DeckInfo = {
  /** Stable id, also used in the ids of the flashcards a deck adds. */
  id: string;
  level: DeckLevel;
  title: string;
  description: string;
  /** Frequency ranks covered, inclusive. */
  from: number;
  to: number;
};
