// Synced from cheneygross-afk/lengo:src/lib/lessons/de-a1-u05.ts by scripts/sync-content.mjs -- edit it there, not here.
import type { Lesson, WriteExercise } from "./types";

// German A1, Unit 5: Questions, Negation & Word Order.
export const DE_A1_U05: Lesson[] = [
  {
    slug: "a1-w-questions-1",
    level: "DE-A1",
    number: 1,
    title: "W-Questions, Part 1 of 2",
    summary: "Ask who, what, how, where, where from, where to and when, with the verb in second place.",
    duration: "12 min",
    sections: [
      {
        heading: "Wer, was, wie: question word first, verb second",
        body: [
          "Most German question words start with w, which is why they're called W-Fragen: \"wer\" (who), \"was ist das?\" (what is that?), \"wie\" (how), \"wo\" (where), \"woher\" (where from), \"wohin\" (where to), \"wann\" (when). Watch out: \"wer\" looks like English where but means who, and \"wo\" is where. Drill it until it's automatic: \"wer\" = who, \"wo\" = where.",
          "The word order is the verb-second rule you already know. The question word takes position 1, the conjugated verb comes straight after it, then the subject: \"Wie heißt du?\", \"Was machst du?\", \"Wer ist das?\"",
          "English needs the helper do in most questions (What do you drink?). German never does: the main verb itself moves into second place. \"Was trinkst du?\" is literally what drink you? and it covers what do you drink and what are you drinking.",
        ],
        examples: [
          { es: "Wie heißt du?", en: "What's your name? (literally: how are you called?)" },
          { es: "Wer ist das?", en: "Who's that?" },
          { es: "Was machst du heute?", en: "What are you doing today?" },
          { es: "Was trinken Sie?", en: "What are you drinking? (polite)" },
          { es: "Wie geht es Ihnen?", en: "How are you? (polite)" },
          { es: "Wer kommt heute Abend?", en: "Who's coming tonight?" },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "Who's that?",
            answer: "Wer ist das?",
            explanation: "\"Wer\" means who (not where). The verb \"ist\" comes second, and \"das\" (that) is the subject.",
          },
          {
            type: "multiple-choice",
            question: "You want to ask a new colleague (polite) what she's drinking. What do you say?",
            options: ["Was trinken Sie?", "Was Sie trinken?", "Was tun Sie trinken?", "Wer trinken Sie?"],
            correctIndex: 0,
            explanation: "Question word, then the verb, then the subject: \"Was trinken Sie?\". German has no helper do, and \"wer\" would mean who.",
          },
        ],
      },
      {
        heading: "Wo, woher, wohin: three words for where",
        body: [
          "English uses one word, where, for three different questions; German splits it. \"Wo\" asks about location (where something is or happens), \"woher\" about origin (where from) and \"wohin\" about direction (where to). The answers match: \"Wo?\" — \"In Köln.\" \"Woher?\" — \"Aus Spanien.\" \"Wohin?\" — \"Nach Berlin.\"",
          "A quick test: if you could add to at the end of the English question (where are you going to?), it's \"wohin\". If you could add from, it's \"woher\". Otherwise it's \"wo\". Old English had the same split: whence and whither.",
          "With verbs of movement such as \"fahren\" and \"gehen\", \"Wo fährst du?\" sounds wrong to a German ear: use \"Wohin fährst du?\". Going home is \"nach Hause\": \"Wohin gehst du? — Nach Hause.\"",
        ],
        examples: [
          { es: "Wo wohnst du?", en: "Where do you live?" },
          { es: "Wo ist der Bahnhof?", en: "Where's the station?" },
          { es: "Woher kommen Sie?", en: "Where are you from? (polite)" },
          { es: "Woher kommt Mehmet? — Aus Izmir.", en: "Where's Mehmet from? — From Izmir." },
          { es: "Wohin fahrt ihr? — Nach München.", en: "Where are you going? — To Munich. (to friends)" },
          { es: "Wohin gehst du? — Nach Hause.", en: "Where are you going? — Home." },
        ],
        checkpoint: [
          {
            type: "fill-blank",
            prompt: "Write the German for the bold words.",
            en: "[Where] are you driving to? (to a friend)",
            sentence: "___ fährst du?",
            answer: "Wohin",
            explanation: "A direction (driving to somewhere) needs \"wohin\". \"Wo\" only asks where something is.",
          },
          {
            type: "listen-choose",
            audio: "Woher kommst du?",
            question: "What does it mean?",
            options: ["Where are you from?", "Where do you live?", "Where are you going?", "Who's coming?"],
            correctIndex: 0,
            explanation: "\"Woher\" = where from, and \"kommen\" + woher asks about origin. Where do you live would be \"Wo wohnst du?\".",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "Where do you live? (polite)",
            answer: "Wo wohnen Sie?",
            explanation: "Location, so \"wo\". Polite \"Sie\" takes the verb form \"wohnen\", which comes second, before the subject.",
          },
        ],
      },
      {
        heading: "Wann, and the trap: the verb must be second",
        body: [
          "\"Wann\" asks when: \"Wann kommst du?\", \"Wann beginnt der Kurs?\". Answers can be any time word you know: \"Heute.\" \"Morgen.\" \"Am Montag.\"",
          "The classic beginner slip is to keep English statement order after the question word: *\"Wo du wohnst?\". In a German question the verb must come second, so the subject goes after it: \"Wo wohnst du?\". It's the same rule as \"Heute arbeite ich\".",
          "Modal verbs follow the same pattern: the modal is second and the infinitive goes to the very end. \"Wann kannst du kommen?\", \"Was möchten Sie trinken?\", \"Wohin wollt ihr fahren?\"",
        ],
        examples: [
          { es: "Wann kommst du?", en: "When are you coming?" },
          { es: "Wann beginnt der Kurs?", en: "When does the course start?" },
          { es: "Wann kannst du kommen?", en: "When can you come?" },
          { es: "Was möchten Sie trinken?", en: "What would you like to drink? (polite)" },
          { es: "Wohin wollt ihr fahren?", en: "Where do you want to go? (to friends)" },
        ],
        checkpoint: [
          {
            type: "word-order",
            prompt: "Put the words in order to say: When does the film start?",
            words: ["Wann", "beginnt", "der", "Film?"],
            translation: "When does the film start?",
            explanation: "Question word, verb, subject: \"Wann beginnt der Film?\". No helper does in German.",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "When can you come? (to a friend)",
            answer: "Wann kannst du kommen?",
            explanation: "The modal \"kannst\" is second, the infinitive \"kommen\" goes to the end.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "Where are you from? (to a friend)",
        answer: "Woher kommst du?",
        explanation: "Origin is \"woher\", with \"kommen\". The verb \"kommst\" comes second, before \"du\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "What are you doing?",
        answer: "Was machst du?",
        altAnswers: ["Was macht ihr?", "Was machen Sie?"],
        explanation: "\"Was machst du?\": the question word, then the verb second. One German present covers what are you doing and what do you do.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "Where's the station?",
        answer: "Wo ist der Bahnhof?",
        explanation: "Location, so \"wo\". \"Der Bahnhof\" is the subject, after the verb \"ist\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "[Who] lives in Hamburg?",
        sentence: "___ wohnt in Hamburg?",
        answer: "Wer",
        explanation: "Who is \"wer\". It looks like where, but where is \"wo\". \"Wer\" takes the er/sie/es verb form: \"wohnt\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "Where are you going? (to two friends)",
        answer: "Wohin geht ihr?",
        altAnswers: ["Wohin fahrt ihr?"],
        explanation: "A direction needs \"wohin\". Two friends are \"ihr\", and the ihr form ends in -t: \"geht\".",
      },
      {
        type: "multiple-choice",
        question: "Which question is correct German for 'Where do you work?'",
        options: ["Wo arbeitest du?", "Wo du arbeitest?", "Wohin arbeitest du?", "Wer arbeitest du?"],
        correctIndex: 0,
        explanation: "Location is \"wo\", and the verb comes second: \"Wo arbeitest du?\". *\"Wo du arbeitest?\" keeps English order.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: What would you like to drink? (polite)",
        words: ["Was", "möchten", "Sie", "trinken?"],
        translation: "What would you like to drink?",
        explanation: "\"Möchten\" is second and the infinitive \"trinken\" closes the sentence.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "How are you? (polite)",
        answer: "Wie geht es Ihnen?",
        explanation: "The set phrase: literally how goes it to you. The polite form uses \"Ihnen\" with a capital I.",
      },
      {
        type: "listen-choose",
        audio: "Wo ist Lena?",
        question: "What did you hear?",
        options: ["Wo ist Lena?", "Wer ist Lena?", "Wie ist Lena?", "Wohin geht Lena?"],
        correctIndex: 0,
        explanation: "\"Wo\" (where) has a long o; \"wer\" (who) has an e sound. Listen for the vowel.",
      },
      {
        type: "speak",
        text: "Woher kommen Sie?",
        prompt: "Say it in German: Where are you from? (polite)",
        tip: "Stress the second part: wo-HER. The w is an English v.",
        explanation: "\"Woher\" for origin, then the verb, then polite \"Sie\".",
      },
    ],
  },
  {
    slug: "a1-w-questions-2",
    level: "DE-A1",
    number: 2,
    title: "W-Questions, Part 2 of 2",
    summary: "Ask how much, how many, how old, how long, why, which and what kind of, with the verb still in second place.",
    duration: "13 min",
    sections: [
      {
        heading: "Wie viel, wie viele, wie alt, wie lange",
        body: [
          "\"Wie\" combines with other words to make new questions, and the whole group counts as position 1, so the verb still comes next: \"Wie alt bist du?\", \"Wie lange bleibst du?\"",
          "How much and how many: \"wie viel\" goes with things you can't count (\"wie viel Geld\", \"wie viel Zeit\", \"wie viel Kaffee\"), \"wie viele\" with plurals (\"wie viele Kinder\", \"wie viele Bücher\"). It's the same split as much and many in English. \"Wie viel kostet das?\" (How much is that?) is a fixed phrase.",
          "Age uses \"sein\", as in English: \"Wie alt bist du? — Ich bin 25.\" Never *\"Ich habe 25 Jahre\". \"Wie lange\" asks how long something lasts: \"Wie lange lernst du schon Deutsch?\" is literally how long learn you already German.",
        ],
        examples: [
          { es: "Wie alt sind Sie?", en: "How old are you? (polite)" },
          { es: "Wie viel Geld hast du?", en: "How much money do you have?" },
          { es: "Wie viele Kinder haben Sie?", en: "How many children do you have? (polite)" },
          { es: "Wie viel kostet das?", en: "How much is that?" },
          { es: "Wie lange bleibst du in Leipzig?", en: "How long are you staying in Leipzig?" },
          { es: "Wie viele Leute kommen?", en: "How many people are coming?" },
        ],
        checkpoint: [
          {
            type: "fill-blank",
            prompt: "Write the German for the bold words.",
            en: "[How many] brothers and sisters do you have?",
            sentence: "___ Geschwister hast du?",
            answer: "Wie viele",
            explanation: "\"Geschwister\" is plural, so \"wie viele\". \"Wie viel\" is for things you can't count, like money or time.",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "How old is Jonas?",
            answer: "Wie alt ist Jonas?",
            explanation: "Age takes \"sein\": \"Wie alt ist...?\". \"Wie alt\" is one block in position 1, so the verb comes next.",
          },
        ],
      },
      {
        heading: "Warum: asking why",
        body: [
          "\"Warum\" means why: \"Warum lernst du Deutsch?\", \"Warum kommt Mia nicht?\". \"Wieso\" means the same and is very common in speech.",
          "The answer often starts with \"weil\" (because), and here German does something new: the verb jumps to the end. \"Weil ich in Berlin arbeite.\" \"Weil sie krank ist.\" You'll learn the rule properly at A2; for now, copy the pattern as a chunk. A short answer with no verb is also fine: \"Für die Arbeit.\" (For work.)",
        ],
        examples: [
          { es: "Warum lernst du Deutsch?", en: "Why are you learning German?" },
          { es: "Weil ich in Berlin arbeite.", en: "Because I work in Berlin." },
          { es: "Warum kommt Mia nicht?", en: "Why isn't Mia coming?" },
          { es: "Weil sie krank ist.", en: "Because she's ill." },
          { es: "Wieso bist du so müde?", en: "Why are you so tired?" },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "Why are you learning German? (to a friend)",
            answer: "Warum lernst du Deutsch?",
            altAnswers: ["Wieso lernst du Deutsch?"],
            explanation: "\"Warum\" (or \"wieso\") in position 1, then the verb \"lernst\". German has one present for are learning and learn.",
          },
          {
            type: "listen-choose",
            audio: "Weil sie krank ist.",
            question: "What does it mean?",
            options: ["Because she's ill.", "Why is she ill?", "Because they're ill.", "She isn't ill."],
            correctIndex: 0,
            explanation: "\"Weil\" = because, and the verb \"ist\" sits at the end. \"Sie ist\" (singular verb) means she is.",
          },
        ],
      },
      {
        heading: "Welcher and was für ein: which one, what kind",
        body: [
          "\"Welcher\" (which) takes the same endings as the definite article: der → \"welcher\", die → \"welche\", das → \"welches\", plural die → \"welche\". \"Welcher Bus fährt nach Köln?\", \"Welche Straße ist das?\", \"Welches Buch liest du?\"",
          "Use \"welcher\" when you're choosing from a known set (which bus, of the ones here). Use \"was für ein\" (literally what for a) when you ask about the kind of thing: \"Was für ein Auto hast du? — Einen VW.\" \"Was für eine Wohnung ist das?\" With plurals or uncountables, drop \"ein\": \"Was für Musik hörst du?\"",
          "Don't be fooled by \"für\" here: \"was für\" has nothing to do with for, it's simply what kind of.",
        ],
        examples: [
          { es: "Welcher Bus fährt nach Köln?", en: "Which bus goes to Cologne?" },
          { es: "Welche Straße ist das?", en: "Which street is that?" },
          { es: "Welches Buch liest du?", en: "Which book are you reading?" },
          { es: "Welche Sprachen sprichst du?", en: "Which languages do you speak?" },
          { es: "Was für ein Auto hast du?", en: "What kind of car do you have?" },
          { es: "Was für Musik hörst du gern?", en: "What kind of music do you like listening to?" },
        ],
        checkpoint: [
          {
            type: "fill-blank",
            prompt: "Write the German for the bold words.",
            en: "[Which] train goes to Hamburg?",
            sentence: "___ Zug fährt nach Hamburg?",
            answer: "Welcher",
            explanation: "\"Der Zug\" is masculine and it's the subject, so \"welcher\" with the -er of \"der\".",
          },
          {
            type: "multiple-choice",
            question: "A friend says she has a new flat. You want to know what kind of flat it is. What do you ask?",
            options: ["Was für eine Wohnung ist das?", "Welcher Wohnung ist das?", "Was für ein Wohnung ist das?", "Wie viel Wohnung ist das?"],
            correctIndex: 0,
            explanation: "\"Was für ein\" asks about the kind, and \"Wohnung\" is feminine, so \"eine\". Which one would be \"welche\", not *\"welcher\".",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "Which languages do you speak? (to a friend)",
            answer: "Welche Sprachen sprichst du?",
            explanation: "Plural nouns take \"welche\". \"Sprechen\" changes e → i in the du form: \"sprichst\".",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "How much is that?",
        answer: "Wie viel kostet das?",
        altAnswers: ["Was kostet das?"],
        explanation: "The fixed shop question: \"Wie viel kostet das?\" or simply \"Was kostet das?\" (what does that cost).",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "How many children do you have? (polite)",
        answer: "Wie viele Kinder haben Sie?",
        explanation: "\"Kinder\" is plural, so \"wie viele\". The verb \"haben\" comes before \"Sie\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "How much time do you have?",
        answer: "Wie viel Zeit hast du?",
        altAnswers: ["Wie viel Zeit habt ihr?", "Wie viel Zeit haben Sie?"],
        explanation: "Time can't be counted, so \"wie viel\" (no -e).",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "How long are you staying in Berlin? (to a friend)",
        answer: "Wie lange bleibst du in Berlin?",
        explanation: "\"Wie lange\" for duration, then the verb. \"Bleiben\" means stay, and one present covers are staying.",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "[Which] book are you reading?",
        sentence: "___ Buch liest du?",
        answer: "Welches",
        explanation: "\"Das Buch\" is neuter, so \"welches\", with the -s of \"das\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "What kind of music do you like? (to a friend)",
        answer: "Was für Musik magst du?",
        altAnswers: ["Was für Musik hörst du gern?"],
        explanation: "\"Was für\" asks for the kind; \"Musik\" is uncountable, so no \"ein\".",
      },
      {
        type: "multiple-choice",
        question: "Which question asks about money correctly?",
        options: ["Wie viel Geld brauchst du?", "Wie viele Geld brauchst du?", "Wie viel Geld du brauchst?", "Welches Geld viel brauchst du?"],
        correctIndex: 0,
        explanation: "Money is uncountable: \"wie viel\". Then the verb second: \"brauchst du\".",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: Why isn't Mia coming?",
        words: ["Warum", "kommt", "Mia", "nicht?"],
        translation: "Why isn't Mia coming?",
        explanation: "\"Warum\" first, verb second, subject, then \"nicht\" at the end of this short sentence.",
      },
      {
        type: "dictation",
        audio: "Wie alt bist du?",
        explanation: "\"Wie alt bist du?\": age with \"sein\", and the verb right after \"wie alt\".",
      },
      {
        type: "speak",
        text: "Welcher Bus fährt nach Köln?",
        prompt: "Say it in German: Which bus goes to Cologne?",
        tip: "Köln has a long rounded ö: say e with your lips pushed forward.",
        explanation: "\"Der Bus\" is masculine, so \"welcher\". \"Fahren\" changes to \"fährt\" for er/sie/es.",
      },
    ],
  },
  {
    slug: "a1-yes-no-questions-doch",
    level: "DE-A1",
    number: 3,
    title: "Yes/No Questions and Ja, Nein, Doch",
    summary: "Ask yes/no questions by putting the verb first, and use doch to contradict a negative.",
    duration: "12 min",
    sections: [
      {
        heading: "Verb first: Kommst du aus Berlin?",
        body: [
          "A yes/no question has no question word, so the conjugated verb jumps to position 1 and the subject follows: \"Kommst du aus Berlin?\", \"Hast du Zeit?\", \"Sind Sie Frau Meier?\". Your voice rises at the end, as in English.",
          "English adds do or does (Do you have time?), but German has no helper verb. *\"Machst du sprechen Deutsch?\" is a word-for-word translation of do you speak and is meaningless: just move the main verb: \"Sprichst du Deutsch?\"",
          "With a modal, the modal goes first and the infinitive to the end: \"Kannst du schwimmen?\", \"Möchten Sie bestellen?\"",
        ],
        examples: [
          { es: "Hast du heute Zeit?", en: "Do you have time today?" },
          { es: "Sprechen Sie Englisch?", en: "Do you speak English? (polite)" },
          { es: "Ist das Fahrrad neu?", en: "Is the bike new?" },
          { es: "Wohnt Ayşe in Hamburg?", en: "Does Ayşe live in Hamburg?" },
          { es: "Kannst du schwimmen?", en: "Can you swim?" },
          { es: "Möchten Sie bestellen?", en: "Would you like to order? (polite)" },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "Do you speak German? (to a friend)",
            answer: "Sprichst du Deutsch?",
            explanation: "Verb first, no helper do. \"Sprechen\" changes e → i in the du form: \"sprichst\".",
          },
          {
            type: "multiple-choice",
            question: "How do you ask a stranger whether he lives in Leipzig?",
            options: ["Wohnen Sie in Leipzig?", "Machen Sie wohnen in Leipzig?", "Sie wohnen in Leipzig, ja nein?", "Wohnst Sie in Leipzig?"],
            correctIndex: 0,
            explanation: "The verb first, in the Sie form: \"Wohnen Sie...?\". German never uses a helper like \"machen\" for do.",
          },
        ],
      },
      {
        heading: "Ja and nein",
        body: [
          "To a normal (positive) question, answer \"ja\" (yes) or \"nein\" (no), as in English: \"Hast du Zeit? — Ja, ich habe Zeit.\" / \"Nein, ich habe keine Zeit.\"",
          "Short answers are short: Germans don't repeat the verb like English yes, I do. \"Kommst du mit? — Ja!\" or \"Ja, gern!\" (yes, gladly). A full answer repeats the whole sentence with the verb second: \"Ja, ich komme mit.\"",
        ],
        examples: [
          { es: "Bist du müde? — Ja, sehr.", en: "Are you tired? — Yes, very." },
          { es: "Hast du Hunger? — Nein, danke.", en: "Are you hungry? — No, thanks." },
          { es: "Trinken Sie Kaffee? — Ja, gern.", en: "Do you drink coffee? — Yes, please. / Yes, I'd love one." },
          { es: "Ist Herr Becker da? — Nein, er ist heute nicht da.", en: "Is Mr Becker in? — No, he isn't in today." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "Are you hungry? — No, thanks. (to a friend)",
            answer: "Hast du Hunger? — Nein, danke.",
            altAnswers: ["Hast du Hunger? Nein, danke."],
            explanation: "Hungry is \"Hunger haben\" in German, so the question starts with \"Hast du\".",
          },
          {
            type: "speak",
            text: "Ja, gern!",
            prompt: "Your friend asks if you want to come along. Say: Yes, I'd love to!",
            tip: "The g in gern is always hard, as in go.",
            explanation: "\"Ja, gern!\" is the friendliest short yes to an offer or invitation.",
          },
        ],
      },
      {
        heading: "Doch: yes, actually!",
        body: [
          "German has a third answer word that English lacks: \"doch\". It contradicts a negative question or statement. \"Hast du keine Zeit? — Doch!\" means Yes I do! (I do have time). \"Du kommst nicht mit? — Doch, ich komme mit!\"",
          "Here's the trap. After a negative question, \"ja\" sounds like agreement with the negative, so it's confusing; Germans say \"doch\" to mean the opposite, and \"nein\" to agree: \"Hast du keine Zeit? — Nein\" means No, I don't have time.",
          "So the rule: positive question → \"ja\" or \"nein\". Negative question or statement → \"doch\" (contradict) or \"nein\" (agree). Doch is usually stressed and said with some energy.",
        ],
        examples: [
          { es: "Hast du keine Zeit? — Doch!", en: "Don't you have time? — Yes, I do!" },
          { es: "Du kommst nicht mit? — Doch, ich komme mit.", en: "You're not coming? — Yes, I am coming." },
          { es: "Sprichst du kein Deutsch? — Doch, ein bisschen.", en: "Don't you speak any German? — Yes, I do, a little." },
          { es: "Ist Leon nicht da? — Nein, er ist krank.", en: "Isn't Leon here? — No, he's ill." },
          { es: "Das ist nicht teuer. — Doch, das ist sehr teuer!", en: "That's not expensive. — Yes it is, it's very expensive!" },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "'Hast du keinen Hunger?' You ARE hungry. What do you answer?",
            options: ["Doch!", "Ja!", "Nein!", "Nicht!"],
            correctIndex: 0,
            explanation: "After a negative question, \"doch\" contradicts it: yes, I am hungry. \"Nein\" would agree (no, I'm not).",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "You don't work today? — Yes, I do, I work today. (to a friend)",
            answer: "Du arbeitest heute nicht? — Doch, ich arbeite heute.",
            altAnswers: ["Arbeitest du heute nicht? — Doch, ich arbeite heute.", "Du arbeitest heute nicht? Doch, ich arbeite heute.", "Arbeitest du heute nicht? Doch, ich arbeite heute.", "Du arbeitest heute nicht? — Doch, heute arbeite ich.", "Arbeitest du heute nicht? — Doch, heute arbeite ich."],
            explanation: "The question is negative, so contradicting it takes \"doch\", never \"ja\".",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "Do you have time today?",
        answer: "Hast du heute Zeit?",
        altAnswers: ["Habt ihr heute Zeit?", "Haben Sie heute Zeit?"],
        explanation: "Verb first for a yes/no question. Time words like \"heute\" usually come before \"Zeit\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "Does Lena live in Cologne?",
        answer: "Wohnt Lena in Köln?",
        explanation: "No does in German: the main verb \"wohnt\" goes first, then the subject \"Lena\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "Can you help me? (to a friend)",
        answer: "Kannst du mir helfen?",
        explanation: "The modal first, the infinitive \"helfen\" at the end. \"Mir helfen\" (help me) is a chunk.",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "Aren't you coming? — [Yes, I am], I'm coming!",
        sentence: "Kommst du nicht? — ___, ich komme!",
        answer: "Doch",
        explanation: "Contradicting a negative question needs \"doch\". \"Ja\" here would be unclear.",
      },
      {
        type: "multiple-choice",
        question: "'Kommst du mit?' You want to say no. What do you answer?",
        options: ["Nein, ich komme nicht mit.", "Doch, ich komme nicht mit.", "Ja, ich komme nicht mit.", "Nein, ich nicht komme mit."],
        correctIndex: 0,
        explanation: "A positive question takes a plain \"nein\". \"Doch\" is only for contradicting a negative.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "Is that expensive?",
        answer: "Ist das teuer?",
        explanation: "\"Sein\" goes first in the question: \"Ist das...?\". The adjective after sein has no ending.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: Would you like to order? (polite)",
        words: ["Möchten", "Sie", "bestellen?"],
        translation: "Would you like to order?",
        explanation: "\"Möchten\" first, then \"Sie\", then the infinitive at the end.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "Don't you have a car? — Yes, I do!",
        answer: "Hast du kein Auto? — Doch!",
        altAnswers: ["Hast du kein Auto? Doch!", "Habt ihr kein Auto? — Doch!", "Haben Sie kein Auto? — Doch!", "Habt ihr kein Auto? Doch!", "Haben Sie kein Auto? Doch!"],
        explanation: "\"Kein Auto\" makes the question negative, so the contradicting answer is \"doch\".",
      },
      {
        type: "listen-choose",
        audio: "Sprichst du kein Deutsch? — Doch, ein bisschen.",
        question: "What does the second person mean?",
        options: ["Yes, I do speak a little German.", "No, I don't speak German.", "No, only a little English.", "Yes, a lot."],
        correctIndex: 0,
        explanation: "\"Doch\" contradicts the negative question: yes, I do speak German, \"ein bisschen\" (a little).",
      },
      {
        type: "speak",
        text: "Doch, ich habe Zeit!",
        prompt: "Your friend says 'Du hast keine Zeit, oder?' Contradict her: Yes I do, I have time!",
        tip: "Doch has a short o and the ach-sound at the end, from the back of the throat.",
        explanation: "\"Doch\" contradicts the negative statement \"Du hast keine Zeit\".",
      },
    ],
  },
  {
    slug: "a1-answer-first-build-question",
    level: "DE-A1",
    number: 4,
    title: "Answer First: Build the Question",
    summary: "Work backwards from an answer to the right W-question or yes/no question, switching the verb to the right person.",
    duration: "12 min",
    sections: [
      {
        heading: "Find the missing piece, pick the W-word",
        body: [
          "Building a question from an answer is a two-step job. First, find the piece of information the question is after and choose its W-word: a place → \"wo\", a city you come from → \"woher\", a destination → \"wohin\", a time or day → \"wann\", a person → \"wer\", a thing or activity → \"was ist...?\" or \"was machst du?\", a name or manner → \"wie\", an age → \"wie alt\".",
          "Second, flip the person. If the answer says \"ich\", the question says \"du\" or \"Sie\", and the verb ending changes with it: \"Ich wohne in Köln.\" → \"Wo wohnst du?\" / \"Wo wohnen Sie?\". If the answer says \"wir\", the question usually says \"ihr\": \"Wir fahren nach Wien.\" → \"Wohin fahrt ihr?\"",
          "Stem-changing verbs change back too: \"Ich spreche Englisch.\" → \"Was sprichst du?\", \"Ich nehme den Bus.\" → \"Was nimmst du?\"",
        ],
        examples: [
          { es: "Ich wohne in Köln. → Wo wohnst du?", en: "I live in Cologne. → Where do you live?" },
          { es: "Ich komme aus Leeds. → Woher kommen Sie?", en: "I'm from Leeds. → Where are you from? (polite)" },
          { es: "Wir fahren nach Wien. → Wohin fahrt ihr?", en: "We're going to Vienna. → Where are you going?" },
          { es: "Ich bin 30. → Wie alt bist du?", en: "I'm 30. → How old are you?" },
          { es: "Der Kurs beginnt am Montag. → Wann beginnt der Kurs?", en: "The course starts on Monday. → When does the course start?" },
          { es: "Das ist Herr Becker. → Wer ist das?", en: "That's Mr Becker. → Who's that?" },
        ],
        checkpoint: [
          {
            type: "fill-blank",
            prompt: "Write the German for the bold words.",
            en: "[Where are you going]? — We're going to Hamburg. (to two friends)",
            sentence: "___? — Wir fahren nach Hamburg.",
            answer: "Wohin fahrt ihr",
            explanation: "A destination needs \"wohin\", and the answer's \"wir\" becomes \"ihr\" in the question, with the ihr form \"fahrt\" (no umlaut).",
          },
          {
            type: "multiple-choice",
            question: "The answer is 'Ich bin 30.' Which question was asked?",
            options: ["Wie alt bist du?", "Wie alt hast du?", "Wie viele bist du?", "Wann bist du?"],
            correctIndex: 0,
            explanation: "Age is \"wie alt\" + \"sein\", just as the answer uses \"ich bin\".",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "What languages do you speak? — I speak English and German. (to a friend)",
            answer: "Welche Sprachen sprichst du? — Ich spreche Englisch und Deutsch.",
            altAnswers: ["Welche Sprachen sprichst du? Ich spreche Englisch und Deutsch.", "Was sprichst du? — Ich spreche Englisch und Deutsch.", "Was sprichst du? Ich spreche Englisch und Deutsch."],
            explanation: "\"Sprechen\" has the e → i change in the du form: \"sprichst\", but not in the ich form: \"spreche\".",
          },
        ],
      },
      {
        heading: "Ja, nein or doch: build the yes/no question",
        body: [
          "If the answer starts with \"ja\" or \"nein\", the question had no W-word: it starts with the verb. \"Ja, ich habe Zeit.\" → \"Hast du Zeit?\"",
          "If the answer starts with \"doch\", the question was negative: it contained \"nicht\" or \"kein\". \"Doch, ich komme!\" → \"Kommst du nicht?\". \"Doch, ich habe ein Auto.\" → \"Hast du kein Auto?\"",
          "A \"nein\" answer can follow either kind of question, so look at the rest: \"Nein, ich habe keine Zeit.\" fits \"Hast du Zeit?\" (a plain no) and also \"Hast du keine Zeit?\" (agreeing).",
        ],
        examples: [
          { es: "Ja, ich habe Zeit. → Hast du Zeit?", en: "Yes, I have time. → Do you have time?" },
          { es: "Nein, ich spreche kein Französisch. → Sprichst du Französisch?", en: "No, I don't speak French. → Do you speak French?" },
          { es: "Doch, ich komme! → Kommst du nicht?", en: "Yes, I am coming! → Aren't you coming?" },
          { es: "Doch, ich habe Hunger. → Hast du keinen Hunger?", en: "Yes, I am hungry. → Aren't you hungry?" },
          { es: "Ja, wir können schwimmen. → Könnt ihr schwimmen?", en: "Yes, we can swim. → Can you swim? (to friends)" },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "The answer is 'Doch, ich arbeite heute.' Which question was asked?",
            options: ["Arbeitest du heute nicht?", "Arbeitest du heute?", "Wann arbeitest du?", "Wo arbeitest du heute?"],
            correctIndex: 0,
            explanation: "\"Doch\" only answers a negative question, so the question contained \"nicht\".",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "Can you swim? — Yes, we can swim. (to two friends)",
            answer: "Könnt ihr schwimmen? — Ja, wir können schwimmen.",
            altAnswers: ["Könnt ihr schwimmen? Ja, wir können schwimmen."],
            explanation: "The modal first in the question, the infinitive at the end. \"Ihr\" in the question becomes \"wir\" in the answer.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "Where do you work? — I work in Munich. (polite)",
        answer: "Wo arbeiten Sie? — Ich arbeite in München.",
        altAnswers: ["Wo arbeiten Sie? Ich arbeite in München."],
        explanation: "Location → \"wo\". The question uses the Sie form \"arbeiten\", the answer the ich form \"arbeite\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "[When] does the train leave? — At ten.",
        sentence: "___ fährt der Zug? — Um zehn.",
        answer: "Wann",
        explanation: "A time answer (\"um zehn\") means the question asked \"wann\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "[What's your name]? — My name is Mia. (to a child)",
        sentence: "___? — Ich heiße Mia.",
        answer: "Wie heißt du",
        explanation: "German asks for a name with \"wie\" (how are you called): \"Wie heißt du?\". Stems in -ß just add -t in the du form.",
      },
      {
        type: "multiple-choice",
        question: "The answer is 'Aus Istanbul.' Which question was asked?",
        options: ["Woher kommt Ayşe?", "Wo wohnt Ayşe?", "Wohin fährt Ayşe?", "Wer ist Ayşe?"],
        correctIndex: 0,
        explanation: "\"Aus\" + a city answers \"woher\" (where from).",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "Who's coming tonight? — Jonas and Lena.",
        answer: "Wer kommt heute Abend? — Jonas und Lena.",
        altAnswers: ["Wer kommt heute Abend? Jonas und Lena."],
        explanation: "People → \"wer\". \"Wer\" always takes the singular verb, even when the answer is two people: \"Wer kommt?\"",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "Isn't Leon coming? — Yes, he is!",
        answer: "Kommt Leon nicht? — Doch!",
        altAnswers: ["Kommt Leon nicht? Doch!", "Kommt Leon nicht? — Doch, er kommt!", "Kommt Leon nicht? Doch, er kommt!"],
        explanation: "The question is negative (\"nicht\"), so the contradicting answer is \"doch\".",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: What are you doing tomorrow? (to a friend)",
        words: ["Was", "machst", "du", "morgen?"],
        translation: "What are you doing tomorrow?",
        explanation: "The question word first, the verb \"machst\" second, then the subject and the time word.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "What are you drinking? — I'm drinking tea. (polite)",
        answer: "Was trinken Sie? — Ich trinke Tee.",
        altAnswers: ["Was trinken Sie? Ich trinke Tee."],
        explanation: "\"Was trinken Sie?\" asks for the thing, and no article before an uncountable drink: \"Ich trinke Tee\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "How long are you staying? — Two weeks.",
        answer: "Wie lange bleibst du? — Zwei Wochen.",
        altAnswers: ["Wie lange bleibst du? Zwei Wochen.", "Wie lange bleibt ihr? — Zwei Wochen.", "Wie lange bleibt ihr? Zwei Wochen.", "Wie lange bleiben Sie? — Zwei Wochen.", "Wie lange bleiben Sie? Zwei Wochen."],
        explanation: "A duration answer means the question was \"wie lange\".",
      },
      {
        type: "listen-choose",
        audio: "Wohin fahrt ihr?",
        question: "Which answer fits?",
        options: ["Nach Berlin.", "Aus Berlin.", "In Berlin.", "Um acht."],
        correctIndex: 0,
        explanation: "\"Wohin\" asks where to, and a city destination is \"nach\" + the city.",
      },
      {
        type: "speak",
        text: "Wo wohnst du?",
        prompt: "Your new classmate says: 'Ich wohne in Leipzig. Und du?' Ask a different classmate the same question: Where do you live?",
        tip: "Wo and wohnst both start with an English v sound.",
        explanation: "Location → \"wo\", with the du form \"wohnst\" right after it.",
      },
    ],
  },
  {
    slug: "a1-accusative-1",
    level: "DE-A1",
    number: 5,
    title: "The Accusative Case, Part 1 of 2",
    summary: "Mark the direct object: der becomes den, ein becomes einen, kein becomes keinen, and everything else stays the same.",
    duration: "14 min",
    sections: [
      {
        heading: "Subject and object",
        body: [
          "In \"Der Mann kauft den Tisch\" (The man buys the table), the man does the buying: he's the subject, in the nominative case. The table is what gets bought: it's the direct object, and German puts it in the accusative case.",
          "English still has case, but only in pronouns: he sees him, she sees her, I see me. German marks case on the article in front of a noun as well. That's why \"Ich habe einen Bruder\", which you learned as a chunk, has \"einen\": the brother is the object of \"haben\".",
          "To find the object, ask what or whom the verb acts on: I buy what? the table. I have what? a brother. The answer to that question goes in the accusative.",
        ],
        examples: [
          { es: "Der Mann kauft den Tisch.", en: "The man is buying the table." },
          { es: "Ich habe einen Bruder.", en: "I have a brother." },
          { es: "Leon sucht den Bahnhof.", en: "Leon is looking for the station." },
          { es: "Wir brauchen einen Tisch.", en: "We need a table." },
          { es: "Ich möchte einen Kaffee, bitte.", en: "I'd like a coffee, please." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "I'm looking for the station.",
            answer: "Ich suche den Bahnhof.",
            explanation: "\"Der Bahnhof\" is the object of \"suchen\", so \"der\" becomes \"den\". English look for is one word in German: \"suchen\".",
          },
          {
            type: "multiple-choice",
            question: "Which sentence means 'We need a table'?",
            options: ["Wir brauchen einen Tisch.", "Wir brauchen ein Tisch.", "Wir brauchen der Tisch.", "Einen Tisch brauchen wir nicht."],
            correctIndex: 0,
            explanation: "\"Der Tisch\" is masculine and the object, so \"ein\" becomes \"einen\".",
          },
        ],
      },
      {
        heading: "Only the masculine changes",
        body: [
          "Here's the good news: in the accusative only masculine nouns change. \"Der\" → \"den\", \"ein\" → \"einen\", \"kein\" → \"keinen\". Feminine (\"die\", \"eine\", \"keine\"), neuter (\"das\", \"ein\", \"kein\") and plurals (\"die\", \"keine\") look exactly as they do as subjects.",
          "So: \"Ich kaufe den Tisch / die Lampe / das Buch / die Stühle.\" Only the first one changes. The ending -en is the signal: whenever you see \"den\", \"einen\" or \"keinen\" before a singular noun, you're looking at a masculine object.",
          "This is why learning every noun with its article pays off: you can't put \"der Kuchen\" in the accusative unless you know it's \"der\".",
        ],
        examples: [
          { es: "Ich kaufe den Tisch.", en: "I'm buying the table." },
          { es: "Ich kaufe die Lampe.", en: "I'm buying the lamp." },
          { es: "Ich kaufe das Buch.", en: "I'm buying the book." },
          { es: "Ich kaufe die Stühle.", en: "I'm buying the chairs." },
          { es: "Mia hat keinen Hund, aber eine Katze.", en: "Mia doesn't have a dog, but she has a cat." },
          { es: "Nimmst du den Bus oder das Fahrrad?", en: "Are you taking the bus or the bike?" },
        ],
        checkpoint: [
          {
            type: "fill-blank",
            prompt: "Write the German for the bold words.",
            en: "Jonas doesn't have a car, but he has [a] bike.",
            sentence: "Jonas hat kein Auto, aber er hat ___ Fahrrad.",
            answer: "ein",
            explanation: "\"Das Fahrrad\" is neuter, and neuter doesn't change in the accusative: \"ein Fahrrad\".",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "I don't have a dog.",
            answer: "Ich habe keinen Hund.",
            explanation: "\"Der Hund\" is masculine and the object of \"haben\": \"kein\" becomes \"keinen\".",
          },
          {
            type: "listen-choose",
            audio: "Ich kaufe den Tisch.",
            question: "What did you hear?",
            options: ["Ich kaufe den Tisch.", "Ich kaufe der Tisch.", "Ich kaufe die Tische.", "Ich kaufe einen Tisch."],
            correctIndex: 0,
            explanation: "\"Den Tisch\": the masculine object. Listen for the n at the end of the article.",
          },
        ],
      },
      {
        heading: "Wer or wen?",
        body: [
          "The question words have cases too. \"Wer\" (who) asks for the subject; \"wen\" (whom) asks for the object. English mostly says who for both, but German keeps them apart, just like formal English who and whom.",
          "\"Wer fragt den Lehrer?\" (Who is asking the teacher? the answer is the asker). \"Wen fragt Mia?\" (Who is Mia asking? the answer is the person being asked: \"Den Lehrer.\"). For things, the same word works for both cases: \"Was ist das?\" (subject), \"Was siehst du?\" (object).",
        ],
        examples: [
          { es: "Wer kennt den Chef?", en: "Who knows the boss?" },
          { es: "Wen kennst du hier?", en: "Who do you know here?" },
          { es: "Wen fragt Mia? — Den Lehrer.", en: "Who is Mia asking? — The teacher." },
          { es: "Was suchst du? — Den Schlüssel.", en: "What are you looking for? — The key." },
        ],
        checkpoint: [
          {
            type: "fill-blank",
            prompt: "Write the German for the bold words.",
            en: "[Who] do you know in Berlin?",
            sentence: "___ kennst du in Berlin?",
            answer: "Wen",
            explanation: "\"Du\" is the subject, so the person asked about is the object: \"wen\".",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "What are you looking for? — The key.",
            answer: "Was suchst du? — Den Schlüssel.",
            altAnswers: ["Was suchst du? Den Schlüssel.", "Was sucht ihr? — Den Schlüssel.", "Was sucht ihr? Den Schlüssel.", "Was suchen Sie? — Den Schlüssel.", "Was suchen Sie? Den Schlüssel."],
            explanation: "Even in a short answer the masculine object keeps its accusative: \"den Schlüssel\".",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "I have a brother and a sister.",
        answer: "Ich habe einen Bruder und eine Schwester.",
        explanation: "\"Der Bruder\" → \"einen Bruder\"; \"die Schwester\" doesn't change: \"eine Schwester\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "We're buying the table.",
        answer: "Wir kaufen den Tisch.",
        explanation: "The table is the object, and \"der Tisch\" is masculine, so \"den\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "Lena needs a computer.",
        answer: "Lena braucht einen Computer.",
        explanation: "\"Der Computer\" is masculine and the object of \"brauchen\": \"einen Computer\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "Do you want [the] lamp?",
        sentence: "Möchtest du ___ Lampe?",
        answer: "die",
        explanation: "\"Die Lampe\" is feminine, and feminine doesn't change in the accusative.",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "Mehmet needs [no] coat today.",
        sentence: "Mehmet braucht heute ___ Mantel.",
        answer: "keinen",
        explanation: "\"Der Mantel\" is masculine and the object, so \"kein\" becomes \"keinen\".",
      },
      {
        type: "multiple-choice",
        question: "Which sentence is correct?",
        options: ["Ich nehme den Zug.", "Ich nehme der Zug.", "Ich nehme dem Zug.", "Ich nehme die Zug."],
        correctIndex: 0,
        explanation: "\"Der Zug\" is the object of \"nehmen\", so it becomes \"den Zug\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "Who do you know here? (to a friend)",
        answer: "Wen kennst du hier?",
        explanation: "The person you know is the object, so the question word is \"wen\", not \"wer\".",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: Are you taking the bus? (to a friend)",
        words: ["Nimmst", "du", "den", "Bus?"],
        translation: "Are you taking the bus?",
        explanation: "Verb first for a yes/no question; \"der Bus\" as an object is \"den Bus\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "I'd like a tea and a coffee, please.",
        answer: "Ich möchte einen Tee und einen Kaffee, bitte.",
        altAnswers: ["Ich möchte bitte einen Tee und einen Kaffee.", "Einen Tee und einen Kaffee, bitte."],
        explanation: "\"Der Tee\" and \"der Kaffee\" are both masculine, so both take \"einen\".",
      },
      {
        type: "dictation",
        audio: "Ich habe keinen Hund.",
        explanation: "\"Keinen\": the accusative of \"kein\" before a masculine noun.",
      },
      {
        type: "speak",
        text: "Ich suche den Bahnhof.",
        prompt: "Say it in German: I'm looking for the station.",
        tip: "The h in Bahnhof is silent the first time (it makes the a long) and spoken the second: BAHN-hohf.",
        explanation: "\"Der Bahnhof\" becomes \"den Bahnhof\" as the object of \"suchen\".",
      },
    ],
  },
  {
    slug: "a1-accusative-2",
    level: "DE-A1",
    number: 6,
    title: "The Accusative Case, Part 2 of 2",
    summary: "Use the accusative to see who does what whatever the word order, after the everyday verbs that take it, and in welchen and wen questions.",
    duration: "14 min",
    sections: [
      {
        heading: "Case, not position, shows who does what",
        body: [
          "In English the order tells you who does what: The dog sees the man and The man sees the dog mean different things. In German the case endings do that job, so the words can move. \"Der Hund sieht den Mann\" and \"Den Mann sieht der Hund\" mean the same: the dog sees the man. \"Den\" marks the object wherever it stands.",
          "Germans often put the object first to stress it or link to what was just said: \"Den Kaffee trinke ich gern, aber den Tee nicht.\" The verb stays in second place, and the subject moves behind it, exactly as after \"heute\".",
          "With feminine, neuter and plural nouns the article doesn't show the case, so German falls back on common sense and the usual order (subject first): \"Die Frau sieht das Kind\" is normally read as the woman sees the child.",
        ],
        examples: [
          { es: "Der Hund sieht den Mann.", en: "The dog sees the man." },
          { es: "Den Mann sieht der Hund.", en: "The dog sees the man. (stress on the man)" },
          { es: "Den Kaffee trinke ich gern.", en: "I like drinking the coffee. / The coffee, I like." },
          { es: "Einen Garten haben wir nicht.", en: "A garden, we don't have." },
          { es: "Den Film kenne ich schon.", en: "I already know that film." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "What does 'Den Lehrer fragt der Student' mean?",
            options: ["The student asks the teacher.", "The teacher asks the student.", "The teacher and the student ask.", "Does the student ask the teacher?"],
            correctIndex: 0,
            explanation: "\"Den Lehrer\" is accusative, so the teacher is the one being asked, even though he comes first. \"Der Student\" is the subject.",
          },
          {
            type: "word-order",
            prompt: "Put the words in order to say: I already know the film. (start with the film)",
            words: ["Den", "Film", "kenne", "ich", "schon."],
            translation: "I already know the film.",
            altOrders: [["Ich", "kenne", "den", "Film", "schon."]],
            explanation: "The object \"den Film\" can come first; the verb \"kenne\" stays second and \"ich\" follows it.",
          },
        ],
      },
      {
        heading: "Verbs that take an accusative object, and one that doesn't",
        body: [
          "Most everyday verbs take a direct object in the accusative: \"haben\", \"brauchen\", \"kaufen\", \"möchten\", \"suchen\", \"nehmen\", \"sehen\", \"finden\", \"kennen\", \"mögen\", \"bestellen\", \"essen\", \"trinken\". \"Ich finde den Film gut\" (I like the film) is a very common way to give an opinion.",
          "\"Sein\" is different: it links two things that are the same person or thing, so both stay in the nominative. \"Das ist ein Tisch\", never *\"Das ist einen Tisch\". \"Er ist der Chef.\" The same goes for \"werden\": \"Das wird ein Problem.\"",
        ],
        examples: [
          { es: "Ich finde den Film gut.", en: "I think the film is good." },
          { es: "Wir bestellen einen Salat.", en: "We're ordering a salad." },
          { es: "Siehst du den Bus?", en: "Can you see the bus?" },
          { es: "Magst du den Käse?", en: "Do you like the cheese?" },
          { es: "Das ist ein Tisch.", en: "That's a table." },
          { es: "Das ist der Chef.", en: "That's the boss." },
        ],
        checkpoint: [
          {
            type: "fill-blank",
            prompt: "Write the German for the bold words.",
            en: "That's [a] dog, not a cat.",
            sentence: "Das ist ___ Hund, keine Katze.",
            answer: "ein",
            explanation: "\"Der Hund\" is masculine, but after \"sein\" there is no accusative: \"ein Hund\", never *\"einen Hund\".",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "Can you see the bus? (to a friend)",
            answer: "Siehst du den Bus?",
            explanation: "\"Der Bus\" is the object of \"sehen\": \"den Bus\". \"Sehen\" changes e → ie in the du form. German doesn't need can here.",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "That's the boss.",
            answer: "Das ist der Chef.",
            altAnswers: ["Das ist die Chefin."],
            explanation: "\"Sein\" never takes an accusative: \"der Chef\" stays \"der\".",
          },
        ],
      },
      {
        heading: "Welchen? Wen? Was für einen?",
        body: [
          "Question words that point at an object take the accusative too. \"Welcher\" becomes \"welchen\" with a masculine object: \"Welchen Film siehst du?\" Feminine \"welche\", neuter \"welches\" and plural \"welche\" don't change.",
          "\"Was für ein\" follows \"ein\": \"Was für einen Hund hast du?\" (masculine object), \"Was für eine Wohnung suchst du?\". And for people, the object question is \"wen\": \"Wen besuchst du?\"",
        ],
        examples: [
          { es: "Welchen Film siehst du heute?", en: "Which film are you watching today?" },
          { es: "Welchen Bus nimmst du?", en: "Which bus are you taking?" },
          { es: "Welche Jacke kaufst du?", en: "Which jacket are you buying?" },
          { es: "Was für einen Hund habt ihr?", en: "What kind of dog do you have? (to friends)" },
          { es: "Wen besuchst du am Sonntag?", en: "Who are you visiting on Sunday?" },
        ],
        checkpoint: [
          {
            type: "fill-blank",
            prompt: "Write the German for the bold words.",
            en: "[Which] train are you taking? (to a friend)",
            sentence: "___ Zug nimmst du?",
            answer: "Welchen",
            explanation: "\"Der Zug\" is the object of \"nehmen\", so \"welcher\" becomes \"welchen\".",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "What kind of dog do you have? (to a friend)",
            answer: "Was für einen Hund hast du?",
            explanation: "\"Was für ein\" takes the ending of \"ein\", and \"der Hund\" as an object becomes \"einen\".",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "I like the film.",
        answer: "Ich finde den Film gut.",
        altAnswers: ["Ich mag den Film.", "Den Film finde ich gut.", "Den Film mag ich."],
        explanation: "\"Finden\" + object + adjective gives an opinion. \"Der Film\" as the object is \"den Film\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "That's not a dog, that's a cat!",
        answer: "Das ist kein Hund, das ist eine Katze!",
        explanation: "After \"sein\" everything stays nominative: \"kein Hund\", not *\"keinen Hund\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "We're ordering a salad and a soup.",
        answer: "Wir bestellen einen Salat und eine Suppe.",
        explanation: "\"Der Salat\" → \"einen Salat\"; \"die Suppe\" stays \"eine Suppe\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "[Which] jacket do you like?",
        sentence: "___ Jacke magst du?",
        answer: "Welche",
        explanation: "\"Die Jacke\" is feminine: \"welche\" doesn't change in the accusative.",
      },
      {
        type: "multiple-choice",
        question: "Which sentence means 'The man sees the dog'?",
        options: ["Den Hund sieht der Mann.", "Der Hund sieht den Mann.", "Den Mann sieht der Hund.", "Der Hund sieht der Mann."],
        correctIndex: 0,
        explanation: "\"Der Mann\" (nominative) is the subject and \"den Hund\" (accusative) the object, whatever the order.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "Which bus are you taking?",
        answer: "Welchen Bus nimmst du?",
        altAnswers: ["Welchen Bus nehmt ihr?", "Welchen Bus nehmen Sie?"],
        explanation: "\"Der Bus\" is the object, so \"welchen\". \"Nehmen\" becomes \"nimmst\" in the du form.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: We don't have a garden.",
        words: ["Wir", "haben", "keinen", "Garten."],
        translation: "We don't have a garden.",
        altOrders: [["Keinen", "Garten", "haben", "wir."]],
        explanation: "\"Der Garten\" → \"keinen Garten\". The object can also come first, with the verb still second.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "Who are you visiting tomorrow? (to a friend)",
        answer: "Wen besuchst du morgen?",
        explanation: "The person visited is the object, so \"wen\". *\"Wer besuchst du?\" is a common slip.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "Do you like the cheese? (to a friend)",
        answer: "Magst du den Käse?",
        explanation: "\"Der Käse\" (a noun to memorise as masculine) is the object of \"mögen\": \"den Käse\".",
      },
      {
        type: "listen-choose",
        audio: "Den Kaffee trinke ich gern.",
        question: "What does it mean?",
        options: ["I like drinking the coffee.", "The coffee likes me.", "Do I like the coffee?", "I don't like coffee."],
        correctIndex: 0,
        explanation: "\"Den Kaffee\" is the object even though it's first; \"ich\" after the verb is the subject.",
      },
      {
        type: "speak",
        text: "Welchen Film siehst du?",
        prompt: "Say it in German: Which film are you watching? (to a friend)",
        tip: "The -ch in welchen is the soft ich-sound, never a k.",
        explanation: "\"Welchen\" for a masculine object, then the verb \"siehst\" second.",
      },
    ],
  },
  {
    slug: "a1-es-gibt",
    level: "DE-A1",
    number: 7,
    title: "Es Gibt: There Is, There Are",
    summary: "Say what exists or is available with es gibt + accusative, always singular gibt, and tell it apart from da ist.",
    duration: "12 min",
    sections: [
      {
        heading: "Es gibt + accusative",
        body: [
          "English there is / there are becomes \"es gibt\", literally it gives. Because \"geben\" takes an object, what follows is in the accusative: \"Es gibt einen Park\" (der Park), \"Es gibt eine Bäckerei\", \"Es gibt ein Kino\".",
          "\"Gibt\" never changes for the plural. English switches from is to are, but German stays singular: \"Es gibt zwei Hotels\", \"Es gibt viele Cafés\". The \"es\" is a dummy subject, like it in it's raining, and it's always singular.",
          "Saying something doesn't exist uses \"kein\": \"Es gibt hier keine Bäckerei\", \"Es gibt keinen Supermarkt\".",
        ],
        examples: [
          { es: "Hier gibt es einen Park.", en: "There's a park here." },
          { es: "Es gibt eine Bäckerei an der Ecke.", en: "There's a bakery on the corner." },
          { es: "In Leipzig gibt es viele Cafés.", en: "There are lots of cafés in Leipzig." },
          { es: "Es gibt zwei Hotels.", en: "There are two hotels." },
          { es: "Hier gibt es keinen Supermarkt.", en: "There's no supermarket here." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "There's a park here.",
            answer: "Hier gibt es einen Park.",
            altAnswers: ["Es gibt hier einen Park."],
            explanation: "\"Es gibt\" + accusative: \"der Park\" becomes \"einen Park\". If \"hier\" comes first, the verb stays second and \"es\" follows it.",
          },
          {
            type: "multiple-choice",
            question: "How do you say 'There are three restaurants'?",
            options: ["Es gibt drei Restaurants.", "Es geben drei Restaurants.", "Es sind drei Restaurants.", "Es gibt drei Restaurant."],
            correctIndex: 0,
            explanation: "\"Es gibt\" is always singular, even with plural nouns. *\"Es sind\" is a common mistake for existence.",
          },
        ],
      },
      {
        heading: "Questions: Gibt es WLAN? Was gibt es?",
        body: [
          "For a yes/no question, put \"gibt\" first: \"Gibt es hier WLAN?\" \"Gibt es noch Kaffee?\" (Is there any coffee left?)",
          "\"Was gibt es?\" asks what's on offer, and in speech \"gibt es\" shortens to \"gibt’s\", and \"Und, was gibt's?\" also means so, what's up?. \"Was gibt es zum Essen?\" (What's for dinner?) and \"Was gibt es heute im Kino?\" (What's on at the cinema today?) are everyday chunks.",
        ],
        examples: [
          { es: "Gibt es hier WLAN?", en: "Is there Wi-Fi here?" },
          { es: "Gibt es noch Kaffee?", en: "Is there any coffee left?" },
          { es: "Was gibt es zum Essen?", en: "What's for dinner? / What is there to eat?" },
          { es: "Und, was gibt's?", en: "So, what's up?" },
          { es: "Gibt es einen Bus nach Potsdam?", en: "Is there a bus to Potsdam?" },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "Is there Wi-Fi here?",
            answer: "Gibt es hier WLAN?",
            altAnswers: ["Gibt es hier W-LAN?", "Gibt es hier Wi-Fi?"],
            explanation: "Verb first for the yes/no question: \"Gibt es...?\". Germans call Wi-Fi \"WLAN\" (vay-lahn).",
          },
          {
            type: "listen-choose",
            audio: "Was gibt es zum Essen?",
            question: "What does it mean?",
            options: ["What's for dinner?", "Who's eating?", "Is there any food?", "Where do we eat?"],
            correctIndex: 0,
            explanation: "\"Was gibt es zum Essen?\" asks what there is to eat: what's for dinner (or lunch).",
          },
        ],
      },
      {
        heading: "Es gibt or da ist?",
        body: [
          "\"Es gibt\" is about what exists in general or is available somewhere: \"In Hamburg gibt es einen Hafen.\" When you point at something you can see right now, use \"da ist\" / \"da sind\" (there is / there are, over there): \"Da ist der Bus!\", \"Da sind die Kinder!\"",
          "\"Da ist\" takes the nominative, because \"sein\" never takes an object: \"Da ist der Bus\", but \"Es gibt einen Bus.\"",
        ],
        examples: [
          { es: "Da ist der Bus!", en: "There's the bus!" },
          { es: "Da sind Jonas und Mia.", en: "There are Jonas and Mia." },
          { es: "In Hamburg gibt es einen Hafen.", en: "There's a port in Hamburg." },
          { es: "Es gibt einen Bus um acht.", en: "There's a bus at eight." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "You see your train arriving. What do you shout?",
            options: ["Da ist der Zug!", "Es gibt den Zug!", "Es gibt einen Zug!", "Da gibt der Zug!"],
            correctIndex: 0,
            explanation: "Pointing at something you can see: \"da ist\" + nominative.",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "There's a bus at eight.",
            answer: "Es gibt einen Bus um acht.",
            altAnswers: ["Um acht gibt es einen Bus.", "Es gibt um acht einen Bus."],
            explanation: "A bus that exists in the timetable: \"es gibt\" + accusative \"einen Bus\".",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "There's no bakery here.",
        answer: "Hier gibt es keine Bäckerei.",
        altAnswers: ["Es gibt hier keine Bäckerei."],
        explanation: "No + noun is \"kein\"; \"die Bäckerei\" is feminine, so \"keine\" (unchanged in the accusative).",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "There are two hotels.",
        answer: "Es gibt zwei Hotels.",
        explanation: "\"Gibt\" stays singular with a plural noun.",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "There's [a] supermarket in Köpenick Street.",
        sentence: "In der Köpenicker Straße gibt es ___ Supermarkt.",
        answer: "einen",
        explanation: "\"Der Supermarkt\" is the object of \"gibt\": \"einen Supermarkt\". *\"Es gibt ein Supermarkt\" is a very common slip.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "Is there any coffee left?",
        answer: "Gibt es noch Kaffee?",
        explanation: "\"Noch\" means still or left; no article for an amount of coffee.",
      },
      {
        type: "multiple-choice",
        question: "Which sentence is correct?",
        options: ["In Köln gibt es einen Dom.", "In Köln es gibt einen Dom.", "In Köln gibt es ein Dom.", "In Köln gibt es der Dom."],
        correctIndex: 0,
        explanation: "Verb second (\"gibt\"), then \"es\", then the accusative \"einen Dom\" (der Dom).",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "What's for dinner?",
        answer: "Was gibt es zum Essen?",
        altAnswers: ["Was gibt es heute zum Essen?", "Was gibt's zum Essen?", "Was gibt es zum Abendessen?", "Was gibt's zum Abendessen?"],
        explanation: "The everyday chunk \"Was gibt es zum Essen?\": what is there to eat.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: Is there a bus to Potsdam?",
        words: ["Gibt", "es", "einen", "Bus", "nach", "Potsdam?"],
        translation: "Is there a bus to Potsdam?",
        explanation: "Yes/no question: the verb \"gibt\" first. \"Einen Bus\" is accusative.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "There's the bus!",
        answer: "Da ist der Bus!",
        altAnswers: ["Da kommt der Bus!"],
        explanation: "You can see it right now, so \"da ist\" + nominative \"der Bus\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "There are lots of cafés in Berlin.",
        answer: "In Berlin gibt es viele Cafés.",
        altAnswers: ["Es gibt viele Cafés in Berlin.", "Es gibt in Berlin viele Cafés."],
        explanation: "\"Es gibt\" stays singular; if \"in Berlin\" comes first, \"gibt\" is second and \"es\" follows.",
      },
      {
        type: "dictation",
        audio: "Gibt es hier WLAN?",
        explanation: "\"Gibt es hier WLAN?\": the verb first in the yes/no question.",
      },
      {
        type: "speak",
        text: "Hier gibt es keinen Supermarkt.",
        prompt: "Say it in German: There's no supermarket here.",
        tip: "Stress SU-per-markt on the first syllable, and say the final t clearly.",
        explanation: "\"Der Supermarkt\" in the accusative with \"kein\": \"keinen Supermarkt\".",
      },
    ],
  },
  {
    slug: "a1-negation-in-depth",
    level: "DE-A1",
    number: 8,
    title: "Negation in Depth: Nicht, Nie, Nichts, Niemand",
    summary: "Place nicht correctly, say never, nothing and nobody, and say no more and not yet.",
    duration: "14 min",
    sections: [
      {
        heading: "Where nicht goes",
        body: [
          "You already know that \"nicht\" negates verbs, adjectives and things with the definite article, while \"kein\" negates nouns with \"ein\" or no article. Now for the position of \"nicht\".",
          "When \"nicht\" negates the whole sentence, it goes after the definite object and after time words, often right at the end: \"Ich kaufe den Mantel nicht.\" \"Ich arbeite heute nicht.\" \"Ich kenne den Mann nicht.\"",
          "But \"nicht\" goes before an adjective, a place and an infinitive at the end: \"Das ist nicht teuer.\", \"Er wohnt nicht in Berlin.\", \"Ich kann heute nicht kommen.\". To negate one specific word, put \"nicht\" right before it: \"Nicht ich, Jonas kocht heute.\"",
        ],
        examples: [
          { es: "Ich kaufe den Mantel nicht.", en: "I'm not buying the coat." },
          { es: "Ich kenne den Mann nicht.", en: "I don't know the man." },
          { es: "Das Hotel ist nicht teuer.", en: "The hotel isn't expensive." },
          { es: "Er wohnt nicht in Berlin.", en: "He doesn't live in Berlin." },
          { es: "Wir können heute nicht kommen.", en: "We can't come today." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "I don't know the man.",
            answer: "Ich kenne den Mann nicht.",
            explanation: "\"Nicht\" comes after a definite object: \"den Mann nicht\". No do in German.",
          },
          {
            type: "word-order",
            prompt: "Put the words in order to say: She can't come today.",
            words: ["Sie", "kann", "heute", "nicht", "kommen."],
            translation: "She can't come today.",
            altOrders: [["Heute", "kann", "sie", "nicht", "kommen."]],
            explanation: "\"Nicht\" goes right before the infinitive at the end.",
          },
        ],
      },
      {
        heading: "Nie, nichts, niemand",
        body: [
          "Three words carry their own negation: \"nie\" (never), \"nichts\" (nothing) and \"niemand\" (nobody, no one). \"Ich esse nie Fleisch.\" \"Ich sehe nichts.\" \"Niemand ist da.\"",
          "German doesn't allow double negatives, just like standard English: *\"Ich sehe nicht nichts\" is wrong. English often says not anything or not anybody; German uses the single negative word: I don't see anything = \"Ich sehe nichts\", I don't know anybody here = \"Ich kenne hier niemand\". (In careful writing the object form is \"niemanden\": \"Ich kenne hier niemanden\"; both are correct.)",
          "These words make great one-word answers: \"Was machst du? — Nichts!\" \"Wer kommt? — Niemand.\"",
        ],
        examples: [
          { es: "Ich esse nie Fleisch.", en: "I never eat meat." },
          { es: "Ich sehe nichts.", en: "I can't see anything." },
          { es: "Niemand ist da.", en: "Nobody's there." },
          { es: "Ich kenne hier niemand.", en: "I don't know anyone here." },
          { es: "Was machst du heute? — Nichts!", en: "What are you doing today? — Nothing!" },
          { es: "Leon trinkt nie Kaffee.", en: "Leon never drinks coffee." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "I don't understand anything.",
            answer: "Ich verstehe nichts.",
            explanation: "Not anything is one word in German: \"nichts\". Never combine it with \"nicht\".",
          },
          {
            type: "multiple-choice",
            question: "How do you say 'Nobody is coming'?",
            options: ["Niemand kommt.", "Niemand kommt nicht.", "Nicht jemand kommt.", "Keiner nicht kommt."],
            correctIndex: 0,
            explanation: "\"Niemand\" already contains the negation; adding \"nicht\" would make a double negative.",
          },
          {
            type: "listen-choose",
            audio: "Ich esse nie Fleisch.",
            question: "What does it mean?",
            options: ["I never eat meat.", "I don't eat meat now.", "I don't eat fish.", "I eat nothing."],
            correctIndex: 0,
            explanation: "\"Nie\" = never. \"Fleisch\" = meat; fish would be \"Fisch\".",
          },
        ],
      },
      {
        heading: "Nicht mehr, kein ... mehr, noch nicht",
        body: [
          "No longer / not any more is \"nicht mehr\": \"Ich wohne nicht mehr in Bonn.\" \"Er raucht nicht mehr.\"",
          "With a noun, use \"kein ... mehr\": \"Ich habe kein Geld mehr\" (I have no money left), \"Es gibt keinen Kaffee mehr.\" A common slip is *\"Ich habe nicht mehr Geld\", which means I don't have more money.",
          "Not yet is \"noch nicht\": \"Ich bin noch nicht fertig.\" \"Lena ist noch nicht da.\". With a noun, \"noch kein\": \"Ich habe noch keinen Job.\"",
        ],
        examples: [
          { es: "Ich wohne nicht mehr in Bonn.", en: "I don't live in Bonn any more." },
          { es: "Ich habe kein Geld mehr.", en: "I've got no money left." },
          { es: "Es gibt keinen Kaffee mehr.", en: "There's no more coffee." },
          { es: "Lena ist noch nicht da.", en: "Lena isn't here yet." },
          { es: "Ich habe noch keinen Job.", en: "I don't have a job yet." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "There's no more coffee.",
            answer: "Es gibt keinen Kaffee mehr.",
            altAnswers: ["Es gibt keinen Kaffee mehr da."],
            explanation: "No more + noun is \"kein ... mehr\", and \"der Kaffee\" is the accusative object of \"gibt\": \"keinen\".",
          },
          {
            type: "fill-blank",
            prompt: "Write the German for the bold words.",
            en: "Jonas is [not] here [yet].",
            sentence: "Jonas ist ___ da.",
            answer: "noch nicht",
            explanation: "Not yet is \"noch nicht\", in that order.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "I'm not buying the coat.",
        answer: "Ich kaufe den Mantel nicht.",
        explanation: "\"Nicht\" goes after the definite object. With \"a coat\" you'd use \"keinen Mantel\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "Mia never drinks coffee.",
        answer: "Mia trinkt nie Kaffee.",
        explanation: "\"Nie\" = never, placed after the verb. No article before \"Kaffee\" in general.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "I can't see anything.",
        answer: "Ich sehe nichts.",
        altAnswers: ["Ich kann nichts sehen."],
        explanation: "German just says I see nothing: \"Ich sehe nichts\". Never *\"nicht nichts\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "I don't live in Hamburg any more.",
        answer: "Ich wohne nicht mehr in Hamburg.",
        explanation: "\"Nicht mehr\" (no longer) goes before the place.",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "I've got [no] money [left].",
        sentence: "Ich habe ___ Geld mehr.",
        answer: "kein",
        explanation: "With a noun, no more is \"kein ... mehr\". \"Das Geld\" is neuter: \"kein\".",
      },
      {
        type: "multiple-choice",
        question: "Which sentence is correct for 'The flat isn't expensive'?",
        options: ["Die Wohnung ist nicht teuer.", "Die Wohnung ist teuer nicht.", "Die Wohnung ist kein teuer.", "Die Wohnung nicht ist teuer."],
        correctIndex: 0,
        explanation: "\"Nicht\" goes before an adjective. \"Kein\" is only for nouns.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "Nobody's at home.",
        answer: "Niemand ist zu Hause.",
        altAnswers: ["Keiner ist zu Hause.", "Es ist niemand zu Hause."],
        explanation: "\"Niemand\" is the subject and takes the singular verb \"ist\". At home is \"zu Hause\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "I'm not ready yet.",
        answer: "Ich bin noch nicht fertig.",
        explanation: "\"Noch nicht\" = not yet, before the adjective \"fertig\".",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: I don't know anyone here.",
        words: ["Ich", "kenne", "hier", "niemand."],
        translation: "I don't know anyone here.",
        altOrders: [["Hier", "kenne", "ich", "niemand."]],
        explanation: "Not anyone = \"niemand\", a single negative word.",
      },
      {
        type: "listen-choose",
        audio: "Ich habe noch keinen Job.",
        question: "What does it mean?",
        options: ["I don't have a job yet.", "I don't have a job any more.", "I never have a job.", "I still have a job."],
        correctIndex: 0,
        explanation: "\"Noch kein\" = not ... yet with a noun. Any more would be \"keinen Job mehr\".",
      },
      {
        type: "speak",
        text: "Nichts! Ich mache heute nichts.",
        prompt: "A friend asks what you're doing today. Say: Nothing! I'm not doing anything today.",
        tip: "The ch in nichts is the soft ich-sound.",
        explanation: "\"Nichts\" works as a one-word answer and inside the sentence.",
      },
    ],
  },
  {
    slug: "a1-error-hunt-questions-accusative",
    level: "DE-A1",
    number: 9,
    title: "Error Hunt: Questions, Accusative & Doch",
    summary: "Find and fix the typical mistakes English speakers make with question order, doch, the accusative and es gibt.",
    duration: "13 min",
    sections: [
      {
        heading: "Question slips",
        body: [
          "Each sentence below has one mistake. First, *\"Wo du wohnst?\": English statement order after a question word. The verb must be second: \"Wo wohnst du?\"",
          "Next, *\"Wer siehst du?\": the person seen is the object, so the question word must be \"wen\": \"Wen siehst du?\". The verb ending gives it away: \"siehst\" belongs to \"du\", so \"du\" is the subject.",
          "Third, a dialogue: \"Hast du nicht Zeit? — Ja!\" meant as yes, I do. Two mistakes in one: no time is \"keine Zeit\", and contradicting a negative takes \"doch\": \"Hast du keine Zeit? — Doch!\"",
        ],
        examples: [
          { es: "Wo wohnst du?", en: "Where do you live? (not *Wo du wohnst?)" },
          { es: "Wen siehst du?", en: "Who do you see? (not *Wer siehst du?)" },
          { es: "Hast du keine Zeit? — Doch!", en: "Don't you have time? — Yes, I do!" },
          { es: "Was machst du heute?", en: "What are you doing today? (not *Was du machst heute?)" },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "A learner wrote *Wann du kommst? Write the correct German for: When are you coming?",
            source: "When are you coming? (to a friend)",
            answer: "Wann kommst du?",
            explanation: "After a question word, the verb comes second and the subject follows: \"Wann kommst du?\"",
          },
          {
            type: "fill-blank",
            prompt: "Write the German for the bold words.",
            en: "[Who] are you asking? (a learner wrote *Wer fragst du?)",
            sentence: "___ fragst du?",
            answer: "Wen",
            explanation: "\"Du\" is the subject (look at \"fragst\"), so the person asked is the object: \"wen\".",
          },
        ],
      },
      {
        heading: "Accusative slips",
        body: [
          "*\"Ich habe ein Bruder.\" \"Der Bruder\" is masculine and the object of \"haben\", so \"ein\" must become \"einen\": \"Ich habe einen Bruder.\"",
          "*\"Ich suche der Bahnhof.\" Same problem with the definite article: \"Ich suche den Bahnhof.\"",
          "*\"Das ist einen Hund.\" Overcorrection! \"Sein\" never takes an accusative: \"Das ist ein Hund.\". And *\"Es gibt ein Supermarkt\": \"geben\" does take one, so \"Es gibt einen Supermarkt.\"",
        ],
        examples: [
          { es: "Ich habe einen Bruder.", en: "I have a brother. (not *ein Bruder)" },
          { es: "Ich suche den Bahnhof.", en: "I'm looking for the station. (not *der Bahnhof)" },
          { es: "Das ist ein Hund.", en: "That's a dog. (not *einen Hund)" },
          { es: "Es gibt einen Supermarkt.", en: "There's a supermarket. (not *ein Supermarkt)" },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "A learner wrote *Es gibt ein Park hier. Write the correct German.",
            source: "There's a park here.",
            answer: "Es gibt hier einen Park.",
            altAnswers: ["Hier gibt es einen Park.", "Es gibt einen Park hier."],
            explanation: "\"Es gibt\" takes the accusative, and \"der Park\" is masculine: \"einen Park\".",
          },
          {
            type: "multiple-choice",
            question: "Which sentence has NO mistake?",
            options: ["Das ist ein Hund.", "Das ist einen Hund.", "Ich habe ein Hund.", "Es gibt ein Hund."],
            correctIndex: 0,
            explanation: "After \"sein\", nominative: \"ein Hund\". After \"haben\" and \"es gibt\" it would be \"einen Hund\".",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "A learner wrote *Woher du kommst? Write the correct German.",
        source: "Where are you from? (to a friend)",
        answer: "Woher kommst du?",
        explanation: "The verb must be second, right after the question word.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "A learner wrote *Ich brauche ein Schlüssel. Write the correct German.",
        source: "I need a key.",
        answer: "Ich brauche einen Schlüssel.",
        explanation: "\"Der Schlüssel\" is masculine and the object of \"brauchen\": \"einen\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "A learner wrote *Das ist keinen Problem. Write the correct German.",
        source: "That's no problem.",
        answer: "Das ist kein Problem.",
        explanation: "\"Sein\" takes no accusative, and \"das Problem\" is neuter anyway: \"kein Problem\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "You're not coming? — [Yes, I am]! (a learner answered *Ja!)",
        sentence: "Du kommst nicht? — ___!",
        answer: "Doch",
        explanation: "Contradicting a negative statement needs \"doch\"; \"ja\" would be unclear.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "A learner wrote *Es sind zwei Supermärkte hier. Write the correct German.",
        source: "There are two supermarkets here.",
        answer: "Es gibt hier zwei Supermärkte.",
        altAnswers: ["Hier gibt es zwei Supermärkte.", "Es gibt zwei Supermärkte hier."],
        explanation: "Existence is \"es gibt\", always singular, even with a plural noun.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "A learner wrote *Ich sehe nicht nichts. Write the correct German.",
        source: "I can't see anything.",
        answer: "Ich sehe nichts.",
        altAnswers: ["Ich kann nichts sehen."],
        explanation: "No double negatives in German: \"nichts\" on its own.",
      },
      {
        type: "multiple-choice",
        question: "Which question is correct for 'Who is visiting Lena?'",
        options: ["Wer besucht Lena?", "Wen besucht Lena?", "Wer besuchst Lena?", "Lena besucht wer?"],
        correctIndex: 0,
        explanation: "The visitor is the subject, so \"wer\". \"Wen besucht Lena?\" would mean who is Lena visiting.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "A learner wrote *Ich habe nicht Zeit heute. Write the correct German.",
        source: "I don't have time today.",
        answer: "Ich habe heute keine Zeit.",
        altAnswers: ["Heute habe ich keine Zeit."],
        explanation: "A noun without an article is negated with \"kein\", and the time word usually comes before the object.",
      },
      {
        type: "word-order",
        prompt: "A learner wrote *Was trinkst du gern Kaffee? Put the words in order to say: Which coffee do you like drinking?",
        words: ["Welchen", "Kaffee", "trinkst", "du", "gern?"],
        translation: "Which coffee do you like drinking?",
        explanation: "\"Welchen Kaffee\" is one block in position 1; the verb \"trinkst\" is second.",
      },
      {
        type: "dictation",
        audio: "Wen siehst du?",
        explanation: "\"Wen\" for the object (the person seen); \"du\" is the subject.",
      },
      {
        type: "speak",
        text: "Ich habe einen Bruder.",
        prompt: "Fix the sentence and say it: *Ich habe ein Bruder (I have a brother).",
        tip: "Make the -en of einen clear: EI-nen.",
        explanation: "\"Einen Bruder\": masculine object of \"haben\".",
      },
    ],
  },
  {
    slug: "a1-spiral-questions-negation-accusative",
    level: "DE-A1",
    number: 10,
    title: "Spiral Review: Questions, Negation & the Accusative",
    summary: "Interview a new colleague and report back, using every kind of question, doch, the accusative, es gibt and negation.",
    duration: "14 min",
    sections: [
      {
        heading: "The interview: asking",
        body: [
          "A new colleague, Ayşe Yılmaz, starts at your office in Köln, and you're writing a short profile of her for the team. You start with Sie and polite questions: \"Woher kommen Sie?\", \"Wo wohnen Sie?\", \"Was machen Sie gern?\"",
          "Mix all the question types: W-questions with the verb second, yes/no questions with the verb first, and modals with the infinitive at the end. Remember \"welchen\" and \"wen\" for objects.",
        ],
        examples: [
          { es: "Woher kommen Sie, Frau Yılmaz?", en: "Where are you from, Ms Yılmaz?" },
          { es: "Wie lange wohnen Sie schon in Köln?", en: "How long have you been living in Cologne?" },
          { es: "Haben Sie Kinder?", en: "Do you have children?" },
          { es: "Welche Sprachen sprechen Sie?", en: "Which languages do you speak?" },
          { es: "Was für ein Auto fahren Sie?", en: "What kind of car do you drive?" },
          { es: "Kennen Sie hier schon jemand?", en: "Do you already know anyone here?" },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "Which languages do you speak? (polite)",
            answer: "Welche Sprachen sprechen Sie?",
            explanation: "Plural \"Sprachen\" takes \"welche\"; the Sie form \"sprechen\" has no vowel change.",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "Do you have children? (polite)",
            answer: "Haben Sie Kinder?",
            explanation: "Yes/no question: the verb first. No article before an indefinite plural.",
          },
        ],
      },
      {
        heading: "The interview: her answers",
        body: [
          "Ayşe answers. Notice the accusatives (\"einen Sohn\", \"keinen Hund\"), the negations and her \"doch\".",
          "\"Ich komme aus Izmir, aber ich wohne schon zehn Jahre in Deutschland. Ich habe einen Sohn, aber keinen Hund. Ich spreche Türkisch, Deutsch und Englisch. Ein Auto habe ich nicht, ich nehme immer das Fahrrad. In Köln kenne ich noch niemand.\"",
          "Then a colleague says: \"Sie sprechen kein Französisch, oder?\" and Ayşe laughs: \"Doch, ein bisschen!\"",
        ],
        examples: [
          { es: "Ich habe einen Sohn, aber keinen Hund.", en: "I have a son but no dog." },
          { es: "Ein Auto habe ich nicht.", en: "I don't have a car." },
          { es: "Ich nehme immer das Fahrrad.", en: "I always take the bike." },
          { es: "In Köln kenne ich noch niemand.", en: "I don't know anyone in Cologne yet." },
          { es: "Sie sprechen kein Französisch, oder? — Doch, ein bisschen!", en: "You don't speak French, do you? — Yes I do, a little!" },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "What does Ayşe mean by 'Doch, ein bisschen!'?",
            options: ["She does speak a little French.", "She doesn't speak French.", "She speaks a lot of French.", "She wants to learn French."],
            correctIndex: 0,
            explanation: "\"Doch\" contradicts the negative statement \"Sie sprechen kein Französisch\".",
          },
          {
            type: "listen-choose",
            audio: "Ich habe einen Sohn, aber keinen Hund.",
            question: "What does it mean?",
            options: ["I have a son but no dog.", "I have a dog but no son.", "I have no son and no dog.", "I have a son and a dog."],
            correctIndex: 0,
            explanation: "\"Einen Sohn\" (accusative of ein) and \"keinen Hund\" (accusative of kein): both nouns are masculine.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "Where do you live, Ms Yılmaz?",
        answer: "Wo wohnen Sie, Frau Yılmaz?",
        explanation: "A colleague you call Frau Yılmaz gets \"Sie\". Location → \"wo\", verb second.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "She has a son but no dog.",
        answer: "Sie hat einen Sohn, aber keinen Hund.",
        explanation: "Both nouns are masculine objects of \"haben\": \"einen Sohn\", \"keinen Hund\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "She doesn't have a car; she always takes the bike.",
        answer: "Sie hat kein Auto, sie nimmt immer das Fahrrad.",
        altAnswers: ["Sie hat kein Auto. Sie nimmt immer das Fahrrad.", "Ein Auto hat sie nicht, sie nimmt immer das Fahrrad."],
        explanation: "\"Das Auto\" is neuter: \"kein Auto\". \"Nehmen\" changes to \"nimmt\" for sie.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "She doesn't know anyone in Cologne yet.",
        answer: "Sie kennt in Köln noch niemand.",
        altAnswers: ["In Köln kennt sie noch niemand.", "Sie kennt noch niemand in Köln.", "Sie kennt in Köln noch niemanden.", "In Köln kennt sie noch niemanden."],
        explanation: "Not anyone yet is \"noch niemand\" (also \"niemanden\" as an object). One negative word only.",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "[Is there] a canteen here?",
        sentence: "___ hier eine Kantine?",
        answer: "Gibt es",
        explanation: "Existence is \"es gibt\"; in a yes/no question \"gibt\" goes first: \"Gibt es...?\"",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "[Which] train do you take in the morning? (polite)",
        sentence: "___ Zug nehmen Sie morgens?",
        answer: "Welchen",
        explanation: "\"Der Zug\" is the object of \"nehmen\": \"welchen\".",
      },
      {
        type: "multiple-choice",
        question: "Your colleague says: 'Sie haben keine Kinder, oder?' Ayşe has a son. What does she say?",
        options: ["Doch, einen Sohn.", "Ja, einen Sohn.", "Nein, einen Sohn.", "Doch, ein Sohn."],
        correctIndex: 0,
        explanation: "\"Doch\" contradicts the negative; \"einen Sohn\" stays accusative as the object of the understood \"habe\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "There's no coffee any more!",
        answer: "Es gibt keinen Kaffee mehr!",
        explanation: "\"Kein ... mehr\" with a noun, and \"der Kaffee\" as the object of \"gibt\": \"keinen\".",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: Who does Ayşe know here?",
        words: ["Wen", "kennt", "Ayşe", "hier?"],
        translation: "Who does Ayşe know here?",
        explanation: "The person known is the object: \"wen\". Verb second, then the subject.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "Can you speak French? — Yes, a little. (polite)",
        answer: "Können Sie Französisch? — Ja, ein bisschen.",
        altAnswers: ["Können Sie Französisch sprechen? — Ja, ein bisschen.", "Sprechen Sie Französisch? — Ja, ein bisschen.", "Können Sie Französisch? Ja, ein bisschen.", "Können Sie Französisch sprechen? Ja, ein bisschen.", "Sprechen Sie Französisch? Ja, ein bisschen."],
        explanation: "\"Können\" + a language needs no infinitive. A positive question gets a plain \"ja\".",
      },
      {
        type: "dictation",
        audio: "Wie lange wohnen Sie schon hier?",
        explanation: "\"Wie lange ... schon\" asks how long something has been going on, with the present tense.",
      },
      {
        type: "speak",
        text: "Haben Sie heute Zeit?",
        prompt: "Ask your new colleague (polite): Do you have time today?",
        tip: "Let your voice rise at the end, as in an English yes/no question.",
        explanation: "Verb first for a yes/no question: \"Haben Sie...?\"",
      },
    ],
  },
];

export const DE_A1_U05_WRITING: WriteExercise = {
  type: "write",
  prompt: "You're moving into a shared flat in Leipzig. Write a short message to your new flatmate, Jonas: say what you have and don't have for the flat, and ask him four or five questions (about the flat, the area and what there is nearby).",
  minWords: 30,
  maxWords: 60,
  rubric: [
    "At least two W-questions with the verb second (\"Wo...?\", \"Wann...?\", \"Welchen...?\")",
    "At least one yes/no question with the verb first (\"Hast du...?\", \"Gibt es...?\")",
    "Masculine objects in the accusative (\"einen\", \"keinen\", \"den\")",
    "At least one negation with \"nicht\", \"kein\" or \"nie\"",
  ],
  modelAnswer: "Hallo Jonas, ich komme am Samstag! Ich habe einen Tisch und eine Lampe, aber ich habe keinen Stuhl. Hast du noch einen Stuhl? Gibt es in der Wohnung WLAN? Wo ist der Supermarkt? Gibt es auch eine Bäckerei? Welchen Bus nehme ich vom Bahnhof? Und wann bist du zu Hause? Ich koche gern, aber ich esse nie Fleisch. Bis Samstag! Mia",
  explanation: "W-questions put the verb second (\"Wo ist...?\", \"Welchen Bus nehme ich...?\"), yes/no questions put it first (\"Hast du...?\", \"Gibt es...?\"). Masculine objects take the accusative: \"einen Tisch\", \"keinen Stuhl\", \"noch einen Stuhl\", \"welchen Bus\", while feminine \"eine Lampe\" doesn't change.",
};
