// Synced from cheneygross-afk/lengo:src/lib/lessons/de-a2-u06.ts by scripts/sync-content.mjs -- edit it there, not here.
import type { Lesson, WriteExercise } from "./types";
// German A2, Unit 6: Telling Stories in the Past.

export const DE_A2_U06: Lesson[] = [
  {
    slug: "a2-story-connectors",
    level: "DE-A2",
    number: 1,
    title: "Sequencing a Story: Zuerst, Dann, Danach, Zum Schluss",
    summary: "Put events in order with zuerst, dann, danach, später, schließlich and zum Schluss, keeping the verb in second place.",
    duration: "13 min",
    sections: [
      {
        heading: "First, then, after that",
        body: [
          "A story needs signposts: \"zuerst\" (first), \"dann\" (then), \"danach\" (after that), \"später\" (later), \"schließlich\" (finally, in the end) and \"zum Schluss\" (at the end, finally). They tell the listener what came before what.",
          "In German each of these words fills position 1 of the sentence. Since the verb must be in position 2, it comes straight after the connector, and the subject moves behind it: \"Dann sind wir ins Restaurant gegangen\". In the Perfekt that means the auxiliary sits right after the connector and the participle stays at the end.",
          "English puts the subject first (Then we went...), so the most common mistake is *Dann wir sind gegangen*. Train your ear: connector, verb, subject.",
        ],
        examples: [
          { es: "Zuerst haben wir gefrühstückt.", en: "First we had breakfast." },
          { es: "Dann sind wir in die Stadt gefahren.", en: "Then we drove into town." },
          { es: "Danach haben wir das Museum besucht.", en: "After that we visited the museum." },
          { es: "Später sind wir ins Restaurant gegangen.", en: "Later we went to a restaurant." },
          { es: "Zum Schluss waren wir alle sehr müde.", en: "At the end we were all very tired." },
          { es: "Schließlich hat Mehmet den Schlüssel gefunden.", en: "In the end Mehmet found the key." },
        ],
        checkpoint: [
          {
            type: "word-order",
            prompt: "Put the words in order to say: Then we went to the cinema.",
            words: ["Dann", "sind", "wir", "ins", "Kino", "gegangen."],
            translation: "Then we went to the cinema.",
            explanation: "\"Dann\" is position 1, so the auxiliary \"sind\" follows and \"wir\" comes third.",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "After that I took a shower.",
            answer: "Danach habe ich geduscht.",
            explanation: "\"Danach\" + verb + subject: \"Danach habe ich...\". \"Duschen\" is regular: \"geduscht\".",
          },
        ],
      },
      {
        heading: "Und and aber don't count",
        body: [
          "Not every linking word takes a position. \"Und\" (and), \"aber\" (but), \"oder\" (or) and \"denn\" (because) sit in front of the sentence in position 0, outside the count. After them, the sentence starts normally: \"Und wir sind nach Hause gegangen\", \"Aber ich hatte keine Zeit\".",
          "So compare: \"Dann sind wir gegangen\" (dann takes position 1, verb next) but \"Und wir sind gegangen\" (und doesn't count, subject first). You can also combine them: \"Und dann sind wir gegangen\": \"und\" is outside, \"dann\" is position 1.",
          "\"Und dann\" is probably the most-used phrase in spoken German storytelling. Children's stories are strings of \"und dann... und dann...\".",
        ],
        examples: [
          { es: "Und dann hat es angefangen zu regnen.", en: "And then it started to rain." },
          { es: "Wir wollten schwimmen, aber das Wasser war zu kalt.", en: "We wanted to swim, but the water was too cold." },
          { es: "Ich habe gekocht und Lena hat den Tisch gedeckt.", en: "I cooked and Lena set the table." },
          { es: "Zuerst war alles gut, aber dann ist der Bus nicht gekommen.", en: "At first everything was fine, but then the bus didn't come." },
          { es: "Und danach? Was habt ihr dann gemacht?", en: "And after that? What did you do then?" },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "Which sentence has the correct word order?",
            options: ["Aber dann ist der Zug nicht gekommen.", "Aber dann der Zug ist nicht gekommen.", "Aber ist dann der Zug nicht gekommen.", "Dann aber der Zug ist nicht gekommen."],
            correctIndex: 0,
            explanation: "\"Aber\" is position 0, \"dann\" is position 1, so the verb \"ist\" comes next.",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "And then we went home.",
            answer: "Und dann sind wir nach Hause gegangen.",
            altAnswers: ["Und dann sind wir heimgegangen.", "Und dann sind wir nach Hause gefahren."],
            explanation: "\"Und\" doesn't count, \"dann\" does: \"Und dann sind wir...\".",
          },
        ],
      },
      {
        heading: "Telling a whole day",
        body: [
          "With four or five connectors you can tell any sequence of events. Vary them: \"zuerst... dann... danach... später... zum Schluss\". Using only \"dann\" works, but sounds childish after the third time.",
          "Mix in time phrases too: \"um acht Uhr\", \"am Nachmittag\", \"am Abend\". They also take position 1: \"Am Abend haben wir gegrillt\".",
          "\"Zuerst\" vs \"erst\": \"zuerst\" means first (before anything else); \"erst\" usually means only / not until (\"erst um zehn\" = not until ten). Keep them apart.",
        ],
        examples: [
          { es: "Um acht Uhr bin ich aufgestanden.", en: "I got up at eight." },
          { es: "Zuerst habe ich Kaffee getrunken, dann habe ich die Zeitung gelesen.", en: "First I drank coffee, then I read the paper." },
          { es: "Am Nachmittag hat Jonas angerufen.", en: "In the afternoon Jonas called." },
          { es: "Später haben wir zusammen gekocht.", en: "Later we cooked together." },
          { es: "Ich bin erst um Mitternacht ins Bett gegangen.", en: "I didn't go to bed until midnight." },
        ],
        checkpoint: [
          {
            type: "fill-blank",
            prompt: "Write the German for the bold words.",
            en: "[Later we] cooked together.",
            sentence: "___ zusammen gekocht.",
            answer: "Später haben wir",
            explanation: "\"Später\" takes position 1, the auxiliary \"haben\" comes second, then \"wir\".",
          },
          {
            type: "listen-choose",
            audio: "Zum Schluss waren alle müde.",
            question: "What does it mean?",
            options: ["In the end everyone was tired.", "At first everyone was tired.", "Then nobody was tired.", "In the end everyone went home."],
            correctIndex: 0,
            explanation: "\"Zum Schluss\" = at the end; \"waren alle müde\" = everyone was tired (verb second after the connector).",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "First we had breakfast.",
        answer: "Zuerst haben wir gefrühstückt.",
        altAnswers: ["Wir haben zuerst gefrühstückt."],
        explanation: "\"Zuerst\" in position 1, then the auxiliary \"haben\", then \"wir\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "Then I called my sister.",
        answer: "Dann habe ich meine Schwester angerufen.",
        altAnswers: ["Ich habe dann meine Schwester angerufen."],
        explanation: "\"Dann habe ich...\": verb second. \"Anrufen\" is separable, so \"angerufen\".",
      },
      {
        type: "multiple-choice",
        question: "Which is correct?",
        options: ["Danach sind wir spazieren gegangen.", "Danach wir sind spazieren gegangen.", "Danach wir haben spazieren gegangen.", "Danach sind spazieren wir gegangen."],
        correctIndex: 0,
        explanation: "Connector, verb, subject: \"Danach sind wir...\"; \"gehen\" takes \"sein\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "Later it started to rain.",
        answer: "Später hat es angefangen zu regnen.",
        altAnswers: ["Später fing es an zu regnen.", "Später hat es zu regnen angefangen.", "Es hat später angefangen zu regnen."],
        explanation: "\"Später\" + auxiliary + \"es\". \"Anfangen\" → \"angefangen\", followed by \"zu regnen\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "We wanted to go to the beach, [but] it was too cold.",
        sentence: "Wir wollten an den Strand, ___ es war zu kalt.",
        answer: "aber",
        explanation: "\"Aber\" sits in position 0, so the next clause keeps normal order: \"es war\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "In the end we were very happy.",
        answer: "Zum Schluss waren wir sehr glücklich.",
        altAnswers: ["Schließlich waren wir sehr glücklich.", "Am Ende waren wir sehr glücklich.", "Zum Schluss waren wir sehr froh.", "Am Ende waren wir sehr froh.", "Schließlich waren wir sehr froh."],
        explanation: "\"Zum Schluss\" / \"schließlich\" / \"am Ende\" all take position 1: then \"waren wir\".",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: And then the bus didn't come.",
        words: ["Und", "dann", "ist", "der", "Bus", "nicht", "gekommen."],
        translation: "And then the bus didn't come.",
        explanation: "\"Und\" doesn't count, \"dann\" is position 1, \"ist\" second, \"nicht\" before the participle.",
      },
      {
        type: "listen-choose",
        audio: "Dann sind wir nach Hause gefahren.",
        question: "What did you hear?",
        options: ["Dann sind wir nach Hause gefahren.", "Dann wir sind nach Hause gefahren.", "Denn wir sind nach Hause gefahren.", "Dann sind wir zu Hause geblieben."],
        correctIndex: 0,
        explanation: "\"Dann\" (then, with a) is followed by the verb. \"Denn\" (because, with e) is position 0 and is followed by the subject.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "I didn't get home until eleven.",
        answer: "Ich bin erst um elf nach Hause gekommen.",
        altAnswers: ["Ich bin erst um elf Uhr nach Hause gekommen.", "Erst um elf bin ich nach Hause gekommen.", "Ich war erst um elf zu Hause.", "Ich war erst um elf Uhr zu Hause."],
        explanation: "\"Erst um elf\" = not until eleven. Don't confuse \"erst\" with \"zuerst\" (first).",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "After that we watched a film.",
        answer: "Danach haben wir einen Film gesehen.",
        altAnswers: ["Danach haben wir einen Film geguckt.", "Danach haben wir einen Film angeschaut.", "Danach haben wir einen Film angesehen.", "Dann haben wir einen Film gesehen.", "Dann haben wir einen Film geguckt."],
        explanation: "\"Danach\" (after that) in position 1, \"haben\" second.",
      },
      {
        type: "speak",
        text: "Zuerst haben wir gegessen, und dann sind wir tanzen gegangen.",
        prompt: "Say it in German: First we ate, and then we went dancing.",
        tip: "\"Zuerst\": the z is ts, as in cats: tsu-ERST.",
        explanation: "Two connectors, each followed by the verb; \"und\" doesn't count.",
      },
      {
        type: "dictation",
        audio: "Danach habe ich geduscht.",
        explanation: "\"Danach\" + \"habe ich\": verb second after the connector.",
      },
    ],
  },
  {
    slug: "a2-seit-present",
    level: "DE-A2",
    number: 2,
    title: "Seit: How Long Have You...?",
    summary: "Use seit + dative with the present tense for things still going on, and ask seit wann? and wie lange schon?",
    duration: "13 min",
    sections: [
      {
        heading: "Seit + present: still going on",
        body: [
          "You met this in Unit 5: for something that started in the past and is still true, German uses the present tense plus \"seit\" (since / for). \"Ich lerne seit zwei Jahren Deutsch\" = I've been learning German for two years. English needs have been learning; German just says I learn, since two years.",
          "\"Seit\" works for both English since and for: \"seit Montag\" (since Monday), \"seit 2021\" (since 2021), \"seit drei Wochen\" (for three weeks). One word, one rule.",
          "The trap is copying the English tense: *Ich habe seit zwei Jahren Deutsch gelernt* sounds as if you've stopped. If it's still happening, keep the verb in the present.",
        ],
        examples: [
          { es: "Ich lerne seit zwei Jahren Deutsch.", en: "I've been learning German for two years." },
          { es: "Sie wohnt seit einem Monat in Wien.", en: "She's been living in Vienna for a month." },
          { es: "Wir sind seit 2019 verheiratet.", en: "We've been married since 2019." },
          { es: "Der Laden ist seit Montag geschlossen.", en: "The shop has been closed since Monday." },
          { es: "Leon spielt seit seiner Kindheit Gitarre.", en: "Leon has played the guitar since he was a child." },
          { es: "Ich habe seit gestern Fieber.", en: "I've had a temperature since yesterday." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "She has been living in Vienna for a month.",
            answer: "Sie wohnt seit einem Monat in Wien.",
            altAnswers: ["Sie lebt seit einem Monat in Wien.", "Seit einem Monat wohnt sie in Wien.", "Seit einem Monat lebt sie in Wien."],
            explanation: "Still true: present \"wohnt\" + \"seit einem Monat\" (der Monat → einem in the dative).",
          },
          {
            type: "multiple-choice",
            question: "How do you say: We've been married since 2019?",
            options: ["Wir sind seit 2019 verheiratet.", "Wir waren seit 2019 verheiratet.", "Wir haben seit 2019 verheiratet.", "Wir sind 2019 seit verheiratet."],
            correctIndex: 0,
            explanation: "Still married: present \"sind\" + \"seit 2019\".",
          },
        ],
      },
      {
        heading: "Seit takes the dative",
        body: [
          "\"Seit\" is a dative preposition, like \"mit\" and \"bei\". With time words that means: \"seit einem Jahr\" (das Jahr), \"seit einem Monat\" (der Monat), \"seit einer Woche\" (die Woche), \"seit einer Stunde\".",
          "In the plural, the dative adds -n to the noun if it doesn't already end in -n or -s: \"seit zwei Jahren\", \"seit drei Tagen\", \"seit vier Monaten\". \"Wochen\", \"Stunden\" and \"Minuten\" already end in -n, so nothing changes. You'll study the whole dative in Unit 7; for now, learn these time phrases as fixed chunks.",
          "Days, months and years need no article: \"seit Montag\", \"seit Januar\", \"seit 2020\". And \"seit gestern\", \"seit heute Morgen\", \"seit letzter Woche\".",
        ],
        examples: [
          { es: "Ich warte seit einer Stunde.", en: "I've been waiting for an hour." },
          { es: "Es schneit seit drei Tagen.", en: "It's been snowing for three days." },
          { es: "Mein Opa ist seit vier Monaten in Rente.", en: "My grandad has been retired for four months." },
          { es: "Die Heizung ist seit letzter Woche kaputt.", en: "The heating has been broken since last week." },
          { es: "Ayşe arbeitet seit Januar in Frankfurt.", en: "Ayşe has been working in Frankfurt since January." },
        ],
        checkpoint: [
          {
            type: "fill-blank",
            prompt: "Write the German for the bold words.",
            en: "It's been snowing [for three days].",
            sentence: "Es schneit ___.",
            answer: "seit drei Tagen",
            explanation: "\"Seit\" + dative plural: \"Tage\" + n = \"Tagen\".",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "I've been waiting for an hour.",
            answer: "Ich warte seit einer Stunde.",
            altAnswers: ["Ich warte schon seit einer Stunde.", "Ich warte schon eine Stunde."],
            explanation: "\"Die Stunde\" → \"seit einer Stunde\" (dative feminine). Still waiting, so present.",
          },
        ],
      },
      {
        heading: "Seit wann? Wie lange schon?",
        body: [
          "Two ways to ask: \"Seit wann wohnst du hier?\" (Since when / How long have you lived here?) and \"Wie lange wohnst du schon hier?\" (How long have you already been living here?). Both use the present tense.",
          "\"Schon\" (already) often joins \"seit\" in the answer to stress that it's been a long time: \"Ich warte schon seit zwanzig Minuten!\" And it can replace \"seit\" with a plain length: \"Ich warte schon zwanzig Minuten\".",
          "The opposite, \"erst seit\", means only since / only for: \"Ich wohne erst seit einer Woche hier\" (I've only lived here for a week).",
        ],
        examples: [
          { es: "Seit wann wohnst du in Leipzig?", en: "How long have you been living in Leipzig?" },
          { es: "Wie lange lernst du schon Deutsch?", en: "How long have you been learning German?" },
          { es: "Ich warte schon seit zwanzig Minuten!", en: "I've been waiting for twenty minutes already!" },
          { es: "Ich wohne erst seit einer Woche hier.", en: "I've only been living here for a week." },
          { es: "Wie lange kennt ihr euch schon?", en: "How long have you known each other?" },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "How long have you been learning German? (to a friend)",
            answer: "Wie lange lernst du schon Deutsch?",
            altAnswers: ["Seit wann lernst du Deutsch?", "Wie lange lernst du Deutsch schon?", "Seit wann lernst du schon Deutsch?"],
            explanation: "Present tense with \"wie lange ... schon\" or \"seit wann\": the learning is still going on.",
          },
          {
            type: "speak",
            text: "Ich wohne erst seit einer Woche hier.",
            prompt: "Say it in German: I've only been living here for a week.",
            explanation: "\"Erst seit\" = only for (so far). Present tense, because you still live there.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "I've been working here since March.",
        answer: "Ich arbeite seit März hier.",
        altAnswers: ["Seit März arbeite ich hier.", "Ich arbeite hier seit März."],
        explanation: "Present \"arbeite\" + \"seit März\": months need no article.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "The heating has been broken for two days.",
        answer: "Die Heizung ist seit zwei Tagen kaputt.",
        altAnswers: ["Seit zwei Tagen ist die Heizung kaputt."],
        explanation: "Still broken: \"ist ... kaputt\" + \"seit zwei Tagen\" (dative plural -n).",
      },
      {
        type: "multiple-choice",
        question: "Which sentence means I've known Lena for five years (and still do)?",
        options: ["Ich kenne Lena seit fünf Jahren.", "Ich habe Lena seit fünf Jahren gekannt.", "Ich kannte Lena fünf Jahre.", "Ich kenne Lena vor fünf Jahren."],
        correctIndex: 0,
        explanation: "Present + \"seit\". \"Vor fünf Jahren\" would mean five years ago.",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "[How long have you been living] in Munich? (to a friend)",
        sentence: "___ in München?",
        answer: "Seit wann wohnst du",
        altAnswers: ["Wie lange wohnst du schon", "Seit wann lebst du", "Wie lange lebst du schon"],
        explanation: "\"Seit wann\" + present tense, or \"Wie lange ... schon\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "I've had a cold since Monday.",
        answer: "Ich habe seit Montag eine Erkältung.",
        altAnswers: ["Seit Montag habe ich eine Erkältung.", "Ich bin seit Montag erkältet.", "Seit Montag bin ich erkältet."],
        explanation: "Present \"habe\" (I still have it) + \"seit Montag\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "We've been waiting for ten minutes already!",
        answer: "Wir warten schon seit zehn Minuten!",
        altAnswers: ["Wir warten schon zehn Minuten!", "Wir warten seit zehn Minuten!"],
        explanation: "\"Schon seit\" stresses that it's been a while. \"Minuten\" already ends in -n.",
      },
      {
        type: "listen-choose",
        audio: "Er spielt seit einem Jahr Klavier.",
        question: "What does it mean?",
        options: ["He's been playing the piano for a year.", "He played the piano a year ago.", "He played the piano for a year.", "He'll play the piano for a year."],
        correctIndex: 0,
        explanation: "Present \"spielt\" + \"seit einem Jahr\" = has been playing for a year (and still does).",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: My parents have been living in Bremen since 2015.",
        words: ["Meine", "Eltern", "wohnen", "seit", "2015", "in", "Bremen."],
        translation: "My parents have been living in Bremen since 2015.",
        altOrders: [["Seit", "2015", "wohnen", "meine", "Eltern", "in", "Bremen."]],
        explanation: "Present tense \"wohnen\"; \"seit 2015\" goes before the place, following the German time-before-place habit.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "She's only been working here for a week.",
        answer: "Sie arbeitet erst seit einer Woche hier.",
        altAnswers: ["Sie arbeitet hier erst seit einer Woche."],
        explanation: "\"Erst seit\" = only for (so far); \"die Woche\" → \"einer Woche\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "How long have you known each other? (to two friends)",
        answer: "Wie lange kennt ihr euch schon?",
        altAnswers: ["Seit wann kennt ihr euch?", "Wie lange kennt ihr euch?", "Seit wann kennt ihr euch schon?"],
        explanation: "\"Ihr\" for two friends; \"euch\" = each other. Present tense, because they still know each other.",
      },
      {
        type: "speak",
        text: "Ich lerne seit zwei Jahren Deutsch.",
        prompt: "Say it in German: I've been learning German for two years.",
        explanation: "The most useful seit-sentence of all: present tense + \"seit zwei Jahren\".",
      },
      {
        type: "dictation",
        audio: "Es regnet seit gestern.",
        explanation: "Still raining, so present: \"es regnet seit gestern\".",
      },
    ],
  },
  {
    slug: "a2-vor-dative-ago",
    level: "DE-A2",
    number: 3,
    title: "Vor and Lang: Ago and For",
    summary: "Say how long ago something happened with vor + dative, and how long a finished period lasted with lang, or a planned one with für.",
    duration: "13 min",
    sections: [
      {
        heading: "Vor zwei Tagen: ago",
        body: [
          "English ago comes after the time: two days ago. German \"vor\" comes before it: \"vor zwei Tagen\". Think of it as before two days.",
          "\"Vor\" here takes the dative, so the forms are the same chunks you learned for \"seit\": \"vor einem Jahr\" (a year ago), \"vor einem Monat\", \"vor einer Woche\", \"vor einer Stunde\", and plurals with -n: \"vor zwei Jahren\", \"vor drei Tagen\", \"vor zehn Minuten\". Also \"vor Kurzem\" (recently) and \"vor langer Zeit\" (a long time ago).",
          "It points to a moment in the past, so the verb is in the past: Perfekt for most verbs, Präteritum for sein, haben and the modals. \"Ich bin vor zwei Jahren nach Berlin gezogen\" (I moved to Berlin two years ago).",
        ],
        examples: [
          { es: "Ich bin vor zwei Jahren nach Berlin gezogen.", en: "I moved to Berlin two years ago." },
          { es: "Der Zug ist vor fünf Minuten abgefahren.", en: "The train left five minutes ago." },
          { es: "Vor einer Woche war ich noch in Spanien.", en: "A week ago I was still in Spain." },
          { es: "Wir haben uns vor einem Jahr kennengelernt.", en: "We met a year ago." },
          { es: "Sie hat vor Kurzem ein Baby bekommen.", en: "She recently had a baby." },
          { es: "Vor langer Zeit gab es hier eine Burg.", en: "A long time ago there was a castle here." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "The train left five minutes ago.",
            answer: "Der Zug ist vor fünf Minuten abgefahren.",
            altAnswers: ["Der Zug ist vor fünf Minuten weggefahren.", "Der Zug ist vor fünf Minuten gefahren.", "Vor fünf Minuten ist der Zug abgefahren."],
            explanation: "\"Vor\" before the time: \"vor fünf Minuten\". \"Abfahren\" takes \"sein\" and is separable: \"ist ... abgefahren\".",
          },
          {
            type: "fill-blank",
            prompt: "Write the German for the bold words.",
            en: "I was in Hamburg [a week ago].",
            sentence: "Ich war ___ in Hamburg.",
            answer: "vor einer Woche",
            explanation: "\"Die Woche\" → dative \"einer Woche\" after \"vor\".",
          },
        ],
      },
      {
        heading: "Drei Jahre lang: a finished period",
        body: [
          "For how long something lasted, when it's over, German uses the length on its own, often with \"lang\" after it: \"Ich habe drei Jahre lang in Bonn gewohnt\" (I lived in Bonn for three years). \"Lang\" is optional but makes the duration clear: \"Ich habe zwei Stunden gewartet\" = \"Ich habe zwei Stunden lang gewartet\".",
          "Here the time phrase is accusative, not dative: \"einen Monat lang\", \"eine Woche lang\", \"ein Jahr lang\", \"drei Tage lang\" (no -n!). Compare \"seit drei Tagen\" (dative, -n) with \"drei Tage lang\" (accusative, no -n).",
          "Never use \"seit\" for a finished period, and never use English for literally: *für drei Jahre gewohnt* is a common English-speaker mistake. For a past duration, use \"lang\" or nothing.",
        ],
        examples: [
          { es: "Ich habe drei Jahre lang in Bonn gewohnt.", en: "I lived in Bonn for three years." },
          { es: "Wir haben zwei Stunden auf den Bus gewartet.", en: "We waited two hours for the bus." },
          { es: "Es hat eine Woche lang geregnet.", en: "It rained for a week." },
          { es: "Er war einen Monat lang krank.", en: "He was ill for a month." },
          { es: "Sie hat ein Jahr in Australien gearbeitet.", en: "She worked in Australia for a year." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "It rained for a week.",
            answer: "Es hat eine Woche lang geregnet.",
            altAnswers: ["Es hat eine Woche geregnet.", "Eine Woche lang hat es geregnet."],
            explanation: "Finished: Perfekt + \"eine Woche lang\" (accusative). Not *seit einer Woche* and not *für eine Woche*.",
          },
          {
            type: "multiple-choice",
            question: "How do you say: He was ill for a month (it's over)?",
            options: ["Er war einen Monat lang krank.", "Er ist seit einem Monat krank.", "Er war vor einem Monat krank.", "Er war für einen Monat krank gewesen."],
            correctIndex: 0,
            explanation: "A finished period: past tense + \"einen Monat lang\". \"Seit\" means he's still ill; \"vor\" means a month ago.",
          },
        ],
      },
      {
        heading: "Für eine Woche: a planned period",
        body: [
          "\"Für\" + accusative does exist for durations, but only for a period that is planned or intended, usually with verbs of going or staying: \"Ich fahre für eine Woche nach Rom\" (I'm going to Rome for a week), \"Sie ist für drei Tage hier\" (She's here for three days: that's the plan).",
          "So \"für\" looks forward: it describes the intended length of a stay. That's why \"Ich bin für zwei Wochen hier\" (I'm here for two weeks, then I leave) and \"Ich bin seit zwei Wochen hier\" (I've been here for two weeks, so far) mean different things.",
        ],
        examples: [
          { es: "Ich fahre für eine Woche nach Rom.", en: "I'm going to Rome for a week." },
          { es: "Meine Mutter kommt für drei Tage zu Besuch.", en: "My mother is coming to visit for three days." },
          { es: "Wir sind nur für ein Wochenende in Hamburg.", en: "We're only in Hamburg for a weekend." },
          { es: "Er ist für ein Jahr nach Kanada gegangen.", en: "He went to Canada for a year." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "I'm going to Vienna for a week.",
            answer: "Ich fahre für eine Woche nach Wien.",
            altAnswers: ["Ich fliege für eine Woche nach Wien.", "Ich fahre eine Woche nach Wien.", "Ich fliege eine Woche nach Wien.", "Für eine Woche fahre ich nach Wien."],
            explanation: "A planned period: \"für eine Woche\" (accusative). German uses the present for a plan.",
          },
          {
            type: "listen-choose",
            audio: "Ich bin für zwei Wochen hier.",
            question: "What does it mean?",
            options: ["I'm here for two weeks (that's the plan).", "I've been here for two weeks.", "I was here two weeks ago.", "I was here for two weeks."],
            correctIndex: 0,
            explanation: "\"Für\" = the planned length of the stay. \"Seit zwei Wochen\" would mean I've been here for two weeks so far.",
          },
          {
            type: "speak",
            text: "Ich bin vor zwei Jahren nach Berlin gezogen.",
            prompt: "Say it in German: I moved to Berlin two years ago.",
            explanation: "\"Vor zwei Jahren\" = two years ago; \"ziehen\" (to move house) takes \"sein\": \"bin ... gezogen\".",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "We met three years ago.",
        answer: "Wir haben uns vor drei Jahren kennengelernt.",
        altAnswers: ["Vor drei Jahren haben wir uns kennengelernt."],
        explanation: "\"Vor drei Jahren\" (dative plural -n) for ago. \"Sich kennenlernen\" = to meet for the first time.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "I worked in a café for two years.",
        answer: "Ich habe zwei Jahre lang in einem Café gearbeitet.",
        altAnswers: ["Ich habe zwei Jahre in einem Café gearbeitet.", "Zwei Jahre lang habe ich in einem Café gearbeitet."],
        explanation: "Finished period: Perfekt + \"zwei Jahre lang\" (accusative, no -n).",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "Jonas called [ten minutes ago].",
        sentence: "Jonas hat ___ angerufen.",
        answer: "vor zehn Minuten",
        explanation: "\"Vor\" + the time: \"vor zehn Minuten\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "My sister is coming for a weekend.",
        answer: "Meine Schwester kommt für ein Wochenende.",
        altAnswers: ["Meine Schwester kommt für ein Wochenende zu Besuch.", "Meine Schwester kommt ein Wochenende zu Besuch."],
        explanation: "A planned stay: \"für ein Wochenende\".",
      },
      {
        type: "multiple-choice",
        question: "Which sentence means I waited for an hour?",
        options: ["Ich habe eine Stunde lang gewartet.", "Ich warte seit einer Stunde.", "Ich habe vor einer Stunde gewartet.", "Ich warte für eine Stunde."],
        correctIndex: 0,
        explanation: "Finished duration: \"eine Stunde lang\" + Perfekt. The second means I've been waiting for an hour (still waiting).",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "A month ago I was in Italy.",
        answer: "Vor einem Monat war ich in Italien.",
        altAnswers: ["Ich war vor einem Monat in Italien."],
        explanation: "\"Der Monat\" → dative \"einem Monat\" after \"vor\". \"Sein\" in the Präteritum: \"war\".",
      },
      {
        type: "listen-choose",
        audio: "Vor einem Jahr hatte ich noch kein Auto.",
        question: "What does it mean?",
        options: ["A year ago I didn't have a car yet.", "I haven't had a car for a year.", "For a year I didn't have a car.", "Next year I won't have a car."],
        correctIndex: 0,
        explanation: "\"Vor einem Jahr\" = a year ago; \"noch kein\" = not yet a / no ... yet.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "He lived in London for six months.",
        answer: "Er hat sechs Monate lang in London gewohnt.",
        altAnswers: ["Er hat sechs Monate in London gewohnt.", "Er hat ein halbes Jahr in London gewohnt.", "Er hat ein halbes Jahr lang in London gewohnt.", "Er hat sechs Monate lang in London gelebt.", "Er hat sechs Monate in London gelebt."],
        explanation: "A closed period: \"sechs Monate lang\" + Perfekt, no \"seit\" and no \"für\".",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: She recently got a new job.",
        words: ["Sie", "hat", "vor", "Kurzem", "einen", "neuen", "Job", "bekommen."],
        translation: "She recently got a new job.",
        explanation: "\"Vor Kurzem\" = recently; \"bekommen\" has no ge- because be- is inseparable.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "We're only here for three days.",
        answer: "Wir sind nur für drei Tage hier.",
        altAnswers: ["Wir sind nur drei Tage hier."],
        explanation: "The planned length: \"für drei Tage\" (accusative plural, no -n).",
      },
      {
        type: "speak",
        text: "Es hat eine Woche lang geregnet.",
        prompt: "Say it in German: It rained for a week.",
        explanation: "\"Eine Woche lang\" for a finished period, with the Perfekt \"hat ... geregnet\".",
      },
      {
        type: "dictation",
        audio: "Ich war vor einer Woche in Köln.",
        explanation: "\"Vor einer Woche\" = a week ago: \"vor\" + dative feminine.",
      },
    ],
  },
  {
    slug: "a2-contrast-seit-vor-lang",
    level: "DE-A2",
    number: 4,
    title: "Contrast Clinic: Seit, Vor or Lang?",
    summary: "Three ways to say for and ago: seit + present for still true, lang + past for a finished period, vor + dative for a point in the past, and für for a plan.",
    duration: "12 min",
    sections: [
      {
        heading: "The decision tree",
        body: [
          "English for hides three different German ideas. Ask: is it still going on? Then \"seit\" + present (\"Ich wohne seit drei Jahren hier\"). Is it over? Then the length + \"lang\" and a past tense (\"Ich habe drei Jahre lang dort gewohnt\"). Is it a plan? Then \"für\" (\"Ich bin für drei Tage hier\").",
          "And ago is always \"vor\" + dative, pointing to a moment: \"Ich bin vor drei Jahren hierhergezogen\".",
          "One story can need all of them: \"Vor fünf Jahren bin ich nach Köln gezogen. Ich habe zwei Jahre lang in einer WG gewohnt. Seit drei Jahren wohne ich allein.\"",
        ],
        examples: [
          { es: "Vor fünf Jahren bin ich nach Köln gezogen.", en: "Five years ago I moved to Cologne." },
          { es: "Ich habe zwei Jahre lang in einer WG gewohnt.", en: "I lived in a flatshare for two years." },
          { es: "Seit drei Jahren wohne ich allein.", en: "I've lived alone for three years." },
          { es: "Im Sommer fahre ich für zwei Wochen nach Polen.", en: "In summer I'm going to Poland for two weeks." },
          { es: "Ich bin seit zwei Wochen hier.", en: "I've been here for two weeks." },
          { es: "Ich bin für zwei Wochen hier.", en: "I'm here for two weeks." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "You arrived in Berlin two weeks ago and you're still there. What do you say?",
            options: ["Ich bin seit zwei Wochen in Berlin.", "Ich war zwei Wochen lang in Berlin.", "Ich bin vor zwei Wochen in Berlin.", "Ich bin für zwei Wochen in Berlin gewesen."],
            correctIndex: 0,
            explanation: "Still true: \"seit\" + present. \"Zwei Wochen lang\" would mean the stay is over.",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "Five years ago I moved to Cologne.",
            answer: "Vor fünf Jahren bin ich nach Köln gezogen.",
            altAnswers: ["Ich bin vor fünf Jahren nach Köln gezogen."],
            explanation: "A point in the past: \"vor fünf Jahren\". \"Ziehen\" (to move) takes \"sein\".",
          },
        ],
      },
      {
        heading: "The endings tell you too",
        body: [
          "\"Seit\" and \"vor\" take the dative: \"seit / vor drei Tagen\", \"seit / vor einem Jahr\", \"seit / vor einer Woche\". \"Lang\" and \"für\" go with the accusative: \"drei Tage lang\", \"ein Jahr lang\", \"für eine Woche\", \"einen Monat lang\".",
          "So the -n on \"Tagen\", \"Jahren\", \"Monaten\" is a good clue: if you hear it, the speaker said \"seit\" or \"vor\". \"Drei Jahren lang\" or \"für drei Jahren\" are mistakes.",
        ],
        examples: [
          { es: "Seit drei Tagen esse ich kein Fleisch.", en: "I haven't eaten meat for three days." },
          { es: "Vor drei Tagen habe ich Fleisch gegessen.", en: "Three days ago I ate meat." },
          { es: "Ich habe drei Tage lang kein Fleisch gegessen.", en: "I didn't eat meat for three days." },
          { es: "Ich fahre für drei Tage nach Prag.", en: "I'm going to Prague for three days. (the plan)" },
        ],
        checkpoint: [
          {
            type: "fill-blank",
            prompt: "Write the German for the bold words.",
            en: "I didn't eat meat [for three days]. (it's over now)",
            sentence: "Ich habe ___ kein Fleisch gegessen.",
            answer: "drei Tage lang",
            explanation: "Finished period: \"drei Tage lang\", accusative, no -n.",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "I haven't eaten meat for three days.",
            answer: "Ich esse seit drei Tagen kein Fleisch.",
            altAnswers: ["Seit drei Tagen esse ich kein Fleisch.", "Ich habe seit drei Tagen kein Fleisch gegessen.", "Seit drei Tagen habe ich kein Fleisch gegessen."],
            explanation: "Still true: present + \"seit drei Tagen\". With a negative, the Perfekt is also natural (nothing has happened since), so both are accepted.",
          },
        ],
      },
      {
        heading: "Common slips",
        body: [
          "*Ich wohne hier für drei Jahre*: English for copied word for word. If you still live there: \"seit drei Jahren\". *Ich habe seit drei Jahren hier gewohnt*: the Perfekt says it's over, \"seit\" says it isn't. *Vor zwei Tage*: missing dative -n: \"vor zwei Tagen\". *Zwei Tage vor*: English word order: \"vor\" comes first.",
          "And one more: \"bis\" means until: \"Ich bleibe bis Freitag\" (I'm staying until Friday). Don't mix it up with \"seit\" (since).",
        ],
        examples: [
          { es: "Ich wohne seit drei Jahren hier.", en: "I've lived here for three years." },
          { es: "Ich war vor zwei Tagen beim Arzt.", en: "I was at the doctor's two days ago." },
          { es: "Ich bleibe bis Freitag.", en: "I'm staying until Friday." },
          { es: "Ich bin seit Freitag hier.", en: "I've been here since Friday." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "I was at the doctor's two days ago.",
            answer: "Ich war vor zwei Tagen beim Arzt.",
            altAnswers: ["Vor zwei Tagen war ich beim Arzt.", "Ich war vor zwei Tagen bei der Ärztin.", "Vor zwei Tagen war ich bei der Ärztin."],
            explanation: "\"Vor\" first, and the dative plural -n: \"vor zwei Tagen\".",
          },
          {
            type: "listen-choose",
            audio: "Ich bleibe bis Freitag.",
            question: "What does it mean?",
            options: ["I'm staying until Friday.", "I've been staying here since Friday.", "I stayed on Friday.", "I'm staying for Friday."],
            correctIndex: 0,
            explanation: "\"Bis\" = until. Since Friday would be \"seit Freitag\".",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "I've been living here for three years.",
        answer: "Ich wohne seit drei Jahren hier.",
        altAnswers: ["Ich lebe seit drei Jahren hier.", "Seit drei Jahren wohne ich hier.", "Seit drei Jahren lebe ich hier.", "Ich wohne hier seit drei Jahren.", "Ich wohne schon seit drei Jahren hier."],
        explanation: "Still true: \"seit\" + present.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "I lived there for three years.",
        answer: "Ich habe drei Jahre lang dort gewohnt.",
        altAnswers: ["Ich habe drei Jahre dort gewohnt.", "Ich habe dort drei Jahre lang gewohnt.", "Ich habe dort drei Jahre gewohnt.", "Ich habe drei Jahre lang da gewohnt.", "Ich habe drei Jahre lang dort gelebt.", "Ich habe drei Jahre dort gelebt."],
        explanation: "Over: Perfekt + \"drei Jahre lang\" (accusative).",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "I moved here three years ago.",
        answer: "Ich bin vor drei Jahren hierhergezogen.",
        altAnswers: ["Vor drei Jahren bin ich hierhergezogen.", "Ich bin vor drei Jahren hierher gezogen.", "Ich bin vor drei Jahren hergezogen."],
        explanation: "A point in the past: \"vor drei Jahren\" + Perfekt with \"sein\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "I'm going to Spain for two weeks.",
        answer: "Ich fahre für zwei Wochen nach Spanien.",
        altAnswers: ["Ich fliege für zwei Wochen nach Spanien.", "Ich fahre zwei Wochen nach Spanien.", "Ich fliege zwei Wochen nach Spanien."],
        explanation: "A plan: \"für zwei Wochen\".",
      },
      {
        type: "multiple-choice",
        question: "Which sentence is wrong?",
        options: ["Ich habe seit zwei Jahren in Bonn gewohnt.", "Ich wohne seit zwei Jahren in Bonn.", "Ich habe zwei Jahre lang in Bonn gewohnt.", "Ich bin vor zwei Jahren nach Bonn gezogen."],
        correctIndex: 0,
        explanation: "\"Seit\" (still going on) clashes with the Perfekt \"habe gewohnt\" (finished). The others are all correct.",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "She's been ill [since Tuesday].",
        sentence: "Sie ist ___ krank.",
        answer: "seit Dienstag",
        explanation: "Still ill: \"seit Dienstag\" with the present \"ist\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "She was ill [two weeks ago].",
        sentence: "Sie war ___ krank.",
        answer: "vor zwei Wochen",
        explanation: "A point in the past: \"vor zwei Wochen\".",
      },
      {
        type: "listen-choose",
        audio: "Wir haben eine Stunde lang gewartet.",
        question: "What does it mean?",
        options: ["We waited for an hour.", "We've been waiting for an hour.", "We waited an hour ago.", "We'll wait for an hour."],
        correctIndex: 0,
        explanation: "\"Eine Stunde lang\" + Perfekt = a finished hour of waiting.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: I've known him for ten years.",
        words: ["Ich", "kenne", "ihn", "seit", "zehn", "Jahren."],
        translation: "I've known him for ten years.",
        explanation: "Still true: \"kenne\" (present) + \"seit zehn Jahren\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "My grandma is visiting for a week.",
        answer: "Meine Oma kommt für eine Woche zu Besuch.",
        altAnswers: ["Meine Oma ist für eine Woche zu Besuch.", "Meine Oma besucht uns für eine Woche.", "Meine Großmutter kommt für eine Woche zu Besuch.", "Meine Großmutter ist für eine Woche zu Besuch.", "Meine Oma ist eine Woche zu Besuch."],
        explanation: "A planned visit: \"für eine Woche\".",
      },
      {
        type: "speak",
        text: "Ich bin seit zwei Wochen hier.",
        prompt: "Say it in German: I've been here for two weeks.",
        explanation: "Still here: \"seit\" + present \"bin\".",
      },
      {
        type: "dictation",
        audio: "Er war vor drei Tagen hier.",
        explanation: "\"Vor drei Tagen\" = three days ago, with the dative -n on \"Tagen\".",
      },
    ],
  },
  {
    slug: "a2-pattern-als-wenn-preview",
    level: "DE-A2",
    number: 5,
    title: "Pattern Practice: Als Ich Klein War, Immer Wenn",
    summary: "Two story frames with the verb at the end, learned as chunks: als ich klein war (once in the past) and immer wenn (every time), followed by verb-first main clauses.",
    duration: "13 min",
    sections: [
      {
        heading: "Als ich klein war, ...",
        body: [
          "\"Als\" means when, for a single moment or period in the past: \"Als ich klein war\" (when I was little), \"Als ich zehn war\" (when I was ten), \"Als wir in Hamburg waren\" (when we were in Hamburg). Notice that the verb \"war\" has moved to the end of the clause: that's how German subordinate clauses work. You'll learn the full rule in Unit 14; for now, learn these frames as whole chunks.",
          "The surprise comes next. The whole \"als\" clause counts as position 1 of the sentence, so the main clause must start with its verb: \"Als ich klein war, hatte ich einen Hund\". The verb \"hatte\" is in position 2, right after the comma, and the subject \"ich\" comes after it.",
          "So the pattern is: clause, comma, verb, subject: \"Als ich zehn war, bin ich nach Bremen gezogen.\" Saying *Als ich klein war, ich hatte einen Hund* is the English-order mistake.",
        ],
        examples: [
          { es: "Als ich klein war, hatte ich einen Hund.", en: "When I was little, I had a dog." },
          { es: "Als ich zehn war, sind wir nach Bremen gezogen.", en: "When I was ten, we moved to Bremen." },
          { es: "Als ich Student war, hatte ich nie Geld.", en: "When I was a student, I never had any money." },
          { es: "Als wir in Hamburg waren, hat es nur geregnet.", en: "When we were in Hamburg, it did nothing but rain." },
          { es: "Als meine Oma jung war, gab es kein Internet.", en: "When my grandma was young, there was no internet." },
        ],
        checkpoint: [
          {
            type: "word-order",
            prompt: "Put the words in order to say: When I was little, I had a cat.",
            words: ["Als", "ich", "klein", "war,", "hatte", "ich", "eine", "Katze."],
            translation: "When I was little, I had a cat.",
            explanation: "The \"als\" clause ends with \"war\"; then the main clause starts with its verb: \"hatte ich\".",
          },
          {
            type: "fill-blank",
            prompt: "Write the German for the bold words.",
            en: "When I was ten, [we moved] to Bremen.",
            sentence: "Als ich zehn war, ___ nach Bremen gezogen.",
            answer: "sind wir",
            explanation: "After the als clause, verb first: \"sind wir ... gezogen\". \"Ziehen\" (to move house) takes \"sein\".",
          },
        ],
      },
      {
        heading: "Immer wenn: every time",
        body: [
          "For something that happened again and again in the past, German uses \"wenn\", often with \"immer\": \"Immer wenn ich Zeit hatte, habe ich gelesen\" (Whenever I had time, I read). \"Als\" is one time; \"wenn\" is every time.",
          "Again, the verb of the wenn-clause goes to the end (\"hatte\", \"war\"), and the main clause starts with its verb. The frames to learn: \"Immer wenn ich Zeit hatte\", \"Immer wenn wir Ferien hatten\", \"Immer wenn ich müde war\", \"Immer wenn es kalt war\".",
          "\"Wenn\" also works in the present for habits now: \"Immer wenn ich müde bin, trinke ich Kaffee\". \"Als\" never does: it's only for the past.",
        ],
        examples: [
          { es: "Immer wenn ich Zeit hatte, habe ich gelesen.", en: "Whenever I had time, I read." },
          { es: "Immer wenn wir Ferien hatten, sind wir an die Ostsee gefahren.", en: "Whenever we had holidays, we went to the Baltic." },
          { es: "Immer wenn es kalt war, hat meine Mutter Suppe gekocht.", en: "Whenever it was cold, my mother made soup." },
          { es: "Immer wenn ich müde bin, trinke ich Kaffee.", en: "Whenever I'm tired, I drink coffee." },
          { es: "Immer wenn Opa da war, durften wir lange aufbleiben.", en: "Whenever Grandpa was there, we were allowed to stay up late." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "Whenever I had time, I read.",
            answer: "Immer wenn ich Zeit hatte, habe ich gelesen.",
            altAnswers: ["Wenn ich Zeit hatte, habe ich gelesen.", "Immer wenn ich Zeit hatte, las ich.", "Wenn ich Zeit hatte, las ich."],
            explanation: "Repeated: \"immer wenn\" + verb at the end (\"hatte\"), then the main clause starts with the verb: \"habe ich gelesen\".",
          },
          {
            type: "multiple-choice",
            question: "When I was a child, I lived in Munich (one period). Which word starts the sentence?",
            options: ["Als", "Wenn", "Immer wenn", "Wann"],
            correctIndex: 0,
            explanation: "One period in the past = \"als\": \"Als ich ein Kind war, habe ich in München gewohnt\". \"Wann\" is only for questions.",
          },
        ],
      },
      {
        heading: "Als, wenn or wann?",
        body: [
          "Three German words for English when. \"Als\": once, in the past (\"Als ich 18 war...\"). \"Wenn\": every time (past or present), or if (\"Wenn ich Zeit habe, komme ich\"). \"Wann\": only in questions, direct or indirect (\"Wann kommst du?\").",
          "A quick test: can you put whenever or every time in the English? Then \"wenn\". Is it a question? Then \"wann\". A one-off past event or period? Then \"als\".",
        ],
        examples: [
          { es: "Als ich 18 war, habe ich den Führerschein gemacht.", en: "When I was 18, I got my driving licence." },
          { es: "Wenn ich Zeit habe, komme ich vorbei.", en: "If I have time, I'll drop by." },
          { es: "Wann bist du nach Deutschland gekommen?", en: "When did you come to Germany?" },
          { es: "Immer wenn ich Mia sehe, lacht sie.", en: "Every time I see Mia, she laughs." },
        ],
        checkpoint: [
          {
            type: "fill-blank",
            prompt: "Write the German for the bold words.",
            en: "[When] did you arrive? (a question)",
            sentence: "___ bist du angekommen?",
            answer: "Wann",
            explanation: "Questions use \"wann\". \"Als\" and \"wenn\" start statements.",
          },
          {
            type: "listen-choose",
            audio: "Als ich jung war, hatte ich lange Haare.",
            question: "What does it mean?",
            options: ["When I was young, I had long hair.", "Whenever I'm young, I have long hair.", "If I were young, I'd have long hair.", "When was I young? I had long hair."],
            correctIndex: 0,
            explanation: "\"Als\" + past = when (once, in the past). The main clause starts with its verb: \"hatte ich\".",
          },
          {
            type: "speak",
            text: "Als ich klein war, hatte ich einen Hund.",
            prompt: "Say it in German: When I was little, I had a dog.",
            tip: "Pause slightly at the comma; then go straight to the verb \"hatte\".",
            explanation: "The als clause ends in \"war\"; the main clause begins with \"hatte\".",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "When I was ten, I had a bike.",
        answer: "Als ich zehn war, hatte ich ein Fahrrad.",
        altAnswers: ["Als ich zehn Jahre alt war, hatte ich ein Fahrrad.", "Als ich zehn war, hatte ich ein Rad.", "Als ich zehn Jahre alt war, hatte ich ein Rad."],
        explanation: "\"Als ich zehn war\", comma, then verb first: \"hatte ich\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "When I was a student, I worked in a bar.",
        answer: "Als ich Student war, habe ich in einer Bar gearbeitet.",
        altAnswers: ["Als ich Studentin war, habe ich in einer Bar gearbeitet.", "Als ich Student war, arbeitete ich in einer Bar.", "Als ich Studentin war, arbeitete ich in einer Bar.", "Als ich Student war, habe ich in einer Kneipe gearbeitet.", "Als ich Studentin war, habe ich in einer Kneipe gearbeitet."],
        explanation: "No article before \"Student\" after \"war\". The main clause begins with \"habe\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "Whenever we had holidays, [we went] to the sea.",
        sentence: "Immer wenn wir Ferien hatten, ___ ans Meer gefahren.",
        answer: "sind wir",
        explanation: "Verb first after the wenn clause: \"sind wir ... gefahren\".",
      },
      {
        type: "multiple-choice",
        question: "Which sentence is correct?",
        options: ["Als ich klein war, wohnte ich in Köln.", "Als ich klein war, ich wohnte in Köln.", "Als ich war klein, wohnte ich in Köln.", "Wenn ich klein war, ich habe in Köln gewohnt."],
        correctIndex: 0,
        explanation: "Verb at the end of the als clause (\"war\"), then verb first in the main clause (\"wohnte ich\"). One period in the past needs \"als\", not \"wenn\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "Whenever it was cold, we stayed at home.",
        answer: "Immer wenn es kalt war, sind wir zu Hause geblieben.",
        altAnswers: ["Wenn es kalt war, sind wir zu Hause geblieben.", "Immer wenn es kalt war, blieben wir zu Hause.", "Wenn es kalt war, blieben wir zu Hause.", "Immer wenn es kalt war, waren wir zu Hause."],
        explanation: "Repeated past: \"immer wenn\". \"Bleiben\" takes \"sein\": \"sind ... geblieben\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "When my dad was young, there were no mobile phones.",
        answer: "Als mein Vater jung war, gab es keine Handys.",
        altAnswers: ["Als mein Papa jung war, gab es keine Handys.", "Als mein Vater jung war, gab es keine Mobiltelefone.", "Als mein Vater jung war, gab es noch keine Handys.", "Als mein Papa jung war, gab es noch keine Handys."],
        explanation: "\"Als\" + one period in the past; the main clause starts with \"gab\" (from \"es gab\").",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: Whenever I'm tired, I drink tea.",
        words: ["Immer", "wenn", "ich", "müde", "bin,", "trinke", "ich", "Tee."],
        translation: "Whenever I'm tired, I drink tea.",
        explanation: "\"Wenn\" also works for habits in the present. Verb at the end of the wenn clause, verb first in the main clause.",
      },
      {
        type: "listen-choose",
        audio: "Immer wenn Oma da war, haben wir Kuchen gegessen.",
        question: "What does it mean?",
        options: ["Whenever Grandma was there, we ate cake.", "When Grandma was there once, we ate cake.", "If Grandma is there, we'll eat cake.", "When will Grandma be there to eat cake?"],
        correctIndex: 0,
        explanation: "\"Immer wenn\" = whenever, every time; the main clause begins with the verb \"haben\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "[When] I was 18, I moved to Berlin.",
        sentence: "___ ich 18 war, bin ich nach Berlin gezogen.",
        answer: "Als",
        explanation: "A single event at one time in the past: \"als\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "When we were in Vienna, it was very hot.",
        answer: "Als wir in Wien waren, war es sehr heiß.",
        explanation: "\"Als wir in Wien waren\", then the main clause verb first: \"war es\".",
      },
      {
        type: "speak",
        text: "Immer wenn ich Zeit hatte, bin ich schwimmen gegangen.",
        prompt: "Say it in German: Whenever I had time, I went swimming.",
        explanation: "\"Immer wenn\" for a repeated habit; main clause verb first: \"bin ich\".",
      },
      {
        type: "dictation",
        audio: "Als ich klein war, war ich oft krank.",
        explanation: "Two \"war\"s side by side: the first ends the als clause, the second starts the main clause.",
      },
    ],
  },
  {
    slug: "a2-mission-zeitungsmeldung",
    level: "DE-A2",
    number: 6,
    title: "Real-World Mission: A Short News Report",
    summary: "Read and write a three-line local news item with the Perfekt and Präteritum, time phrases and sequencing words.",
    duration: "14 min",
    sections: [
      {
        heading: "Reading a Zeitungsmeldung",
        body: [
          "A \"Meldung\" is a short news item, the kind you find in the local paper or on a city news website. It answers the W-questions: \"Was ist passiert?\" (what), \"wann?\" (when), \"wo?\" (where), \"wer?\" (who) and what happened next.",
          "News items often open in the Perfekt, to announce the news (\"Gestern Abend ist in der Hauptstraße ein Unfall passiert\"), and then continue in the Präteritum, the written storytelling tense (\"Ein Radfahrer stürzte\"). At A2, recognise both; when you write your own, the Perfekt plus war / hatte is fine.",
          "Key vocabulary: \"der Unfall\" (accident), \"der Radfahrer\" (cyclist), \"stürzen\" (to fall, crash: \"ist gestürzt\"), \"verletzt\" (injured), \"leicht / schwer verletzt\" (slightly / seriously injured), \"die Feuerwehr\" (fire brigade), \"die Polizei\", \"das Krankenhaus\" (hospital), \"der Zeuge / die Zeugin\" (witness).",
        ],
        examples: [
          { es: "Gestern Abend ist in der Hauptstraße ein Unfall passiert.", en: "Yesterday evening there was an accident on the high street." },
          { es: "Ein Radfahrer ist gegen 19 Uhr gestürzt.", en: "A cyclist came off his bike at around 7 p.m." },
          { es: "Er war leicht verletzt.", en: "He was slightly injured." },
          { es: "Ein Krankenwagen brachte ihn ins Krankenhaus.", en: "An ambulance took him to hospital." },
          { es: "Die Polizei sucht jetzt Zeugen.", en: "The police are now looking for witnesses." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "\"Er war leicht verletzt.\" What does it mean?",
            options: ["He was slightly injured.", "He was easily hurt.", "He was seriously injured.", "He was lightly dressed."],
            correctIndex: 0,
            explanation: "\"Leicht verletzt\" = slightly injured; seriously would be \"schwer verletzt\". \"Leicht\" literally means light or easy.",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "Yesterday there was an accident.",
            answer: "Gestern ist ein Unfall passiert.",
            altAnswers: ["Gestern gab es einen Unfall.", "Gestern hat es einen Unfall gegeben.", "Es gab gestern einen Unfall.", "Gestern ist ein Unfall geschehen."],
            explanation: "\"Passieren\" takes \"sein\" and has no ge-: \"ist passiert\". \"Es gab einen Unfall\" is just as natural.",
          },
        ],
      },
      {
        heading: "The order of a report",
        body: [
          "A report follows a clear sequence, using the connectors from this unit: \"zuerst\", \"dann\", \"danach\", \"später\", \"schließlich\". Each connector is position 1, so the verb follows: \"Dann kam die Feuerwehr\", \"Schließlich ist die Straße wieder frei gewesen\".",
          "Time and place come early. German likes the order time, then manner, then place: \"Ein Auto ist gestern Nachmittag mit hoher Geschwindigkeit gegen einen Baum gefahren\". At A2, keep it simple: time phrase in position 1, place later.",
          "Our second report: a kitchen fire. Read it as a chain of events.",
        ],
        examples: [
          { es: "Am Montagmorgen hat es in einer Wohnung in der Goethestraße gebrannt.", en: "On Monday morning there was a fire in a flat on Goethe Street." },
          { es: "Zuerst hat eine Nachbarin den Rauch gesehen.", en: "First a neighbour saw the smoke." },
          { es: "Dann hat sie die Feuerwehr gerufen.", en: "Then she called the fire brigade." },
          { es: "Die Feuerwehr war nach zehn Minuten da.", en: "The fire brigade was there after ten minutes." },
          { es: "Niemand war verletzt.", en: "Nobody was injured." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "Then she called the fire brigade.",
            answer: "Dann hat sie die Feuerwehr gerufen.",
            altAnswers: ["Dann hat sie die Feuerwehr angerufen.", "Dann rief sie die Feuerwehr."],
            explanation: "\"Dann\" + auxiliary + subject. \"Rufen\" → \"gerufen\" (to call for help).",
          },
          {
            type: "word-order",
            prompt: "Put the words in order to say: Nobody was injured.",
            words: ["Niemand", "war", "verletzt."],
            translation: "Nobody was injured.",
            explanation: "\"Niemand\" (nobody) + \"war\" + \"verletzt\": the standard closing line of a German accident report.",
          },
        ],
      },
      {
        heading: "Your mission: write three lines",
        body: [
          "Now write your own Meldung in three lines: line 1 what, when and where (\"Gestern Abend ist im Stadtpark...\"); line 2 what happened next, with a connector (\"Dann...\"); line 3 the result (\"Niemand war verletzt\", \"Die Polizei sucht Zeugen\").",
          "Keep it factual and short. Use the Perfekt for actions, \"war\" and \"hatte\" for states, and remember the verb in position 2 after every time phrase or connector.",
        ],
        examples: [
          { es: "Gestern Nachmittag ist im Stadtpark ein Hund in den See gesprungen.", en: "Yesterday afternoon a dog jumped into the lake in the city park." },
          { es: "Dann ist ein Junge ins Wasser gegangen und hat den Hund gerettet.", en: "Then a boy went into the water and rescued the dog." },
          { es: "Der Hund war nass, aber glücklich.", en: "The dog was wet, but happy." },
          { es: "Am Samstag hat ein Mann in der U-Bahn 5000 Euro gefunden.", en: "On Saturday a man found 5,000 euros on the underground." },
          { es: "Er hat das Geld zur Polizei gebracht.", en: "He took the money to the police." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "A man found 5,000 euros.",
            answer: "Ein Mann hat 5000 Euro gefunden.",
            altAnswers: ["Ein Mann hat 5.000 Euro gefunden.", "Ein Mann fand 5000 Euro.", "Ein Mann fand 5.000 Euro.", "Ein Mann hat fünftausend Euro gefunden."],
            explanation: "\"Finden\" → \"gefunden\". Germans write thousands with a dot or nothing: 5.000 or 5000.",
          },
          {
            type: "listen-choose",
            audio: "Die Polizei sucht Zeugen.",
            question: "What does it mean?",
            options: ["The police are looking for witnesses.", "The police found witnesses.", "The police are questioning the witnesses.", "The witnesses are looking for the police."],
            correctIndex: 0,
            explanation: "\"Suchen\" = to look for; \"Zeugen\" = witnesses (der Zeuge, die Zeugen).",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "A cyclist fell off his bike.",
        answer: "Ein Radfahrer ist gestürzt.",
        altAnswers: ["Ein Radfahrer ist vom Fahrrad gefallen.", "Ein Radfahrer ist vom Rad gestürzt.", "Ein Radfahrer stürzte.", "Ein Fahrradfahrer ist gestürzt.", "Ein Radfahrer ist vom Fahrrad gestürzt."],
        explanation: "\"Stürzen\" (to fall, crash) takes \"sein\": \"ist gestürzt\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "She was seriously injured.",
        answer: "Sie war schwer verletzt.",
        altAnswers: ["Sie wurde schwer verletzt."],
        explanation: "\"Schwer verletzt\" = seriously injured; \"war\" for the state.",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "The fire brigade [was there] after ten minutes.",
        sentence: "Die Feuerwehr ___ nach zehn Minuten da.",
        answer: "war",
        explanation: "\"Da sein\" = to be there; Präteritum \"war\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "The police are looking for witnesses.",
        answer: "Die Polizei sucht Zeugen.",
        altAnswers: ["Die Polizei sucht nach Zeugen."],
        explanation: "\"Die Polizei\" is singular in German (it takes \"sucht\"), unlike English the police are.",
      },
      {
        type: "multiple-choice",
        question: "A report says: \"Ein Krankenwagen brachte die Frau ins Krankenhaus.\" What happened?",
        options: ["An ambulance took the woman to hospital.", "The woman brought an ambulance to the hospital.", "The woman drove to hospital.", "An ambulance is taking the woman to hospital."],
        correctIndex: 0,
        explanation: "\"Brachte\" is the Präteritum of \"bringen\" (spoken: \"hat ... gebracht\").",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "First a neighbour saw the smoke.",
        answer: "Zuerst hat eine Nachbarin den Rauch gesehen.",
        altAnswers: ["Zuerst hat ein Nachbar den Rauch gesehen.", "Zuerst sah eine Nachbarin den Rauch.", "Zuerst sah ein Nachbar den Rauch."],
        explanation: "\"Zuerst\" + auxiliary + subject. \"Der Rauch\" → accusative \"den Rauch\".",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: Then the police came.",
        words: ["Dann", "ist", "die", "Polizei", "gekommen."],
        translation: "Then the police came.",
        altOrders: [["Dann", "ist", "gekommen", "die", "Polizei."]],
        explanation: "\"Dann\" first, auxiliary \"ist\" second (kommen takes sein), participle at the end.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "Nobody was injured.",
        answer: "Niemand war verletzt.",
        altAnswers: ["Niemand wurde verletzt.", "Keiner war verletzt.", "Keiner wurde verletzt."],
        explanation: "\"Niemand\" = nobody, with \"war\" + \"verletzt\".",
      },
      {
        type: "listen-choose",
        audio: "Gestern Abend ist in der Hauptstraße ein Unfall passiert.",
        question: "What does it mean?",
        options: ["Yesterday evening there was an accident on the high street.", "Yesterday evening an accident was avoided on the high street.", "This evening there's been an accident on the high street.", "Yesterday evening someone passed the high street."],
        correctIndex: 0,
        explanation: "\"Ist ... passiert\" = happened. \"Passieren\" is a false-friend trap: it means happen, not pass.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "He took the money to the police.",
        answer: "Er hat das Geld zur Polizei gebracht.",
        altAnswers: ["Er brachte das Geld zur Polizei."],
        explanation: "\"Bringen\" is a mixed verb: \"gebracht\". \"Zur\" = zu der.",
      },
      {
        type: "speak",
        text: "Gestern ist ein Unfall passiert. Niemand war verletzt.",
        prompt: "Say it in German, like a radio newsreader: Yesterday there was an accident. Nobody was injured.",
        tip: "\"Unfall\" stresses the first syllable: UN-fall.",
        explanation: "The two classic lines of a local news item: the event in the Perfekt, the result with \"war\".",
      },
      {
        type: "dictation",
        audio: "Er war leicht verletzt.",
        explanation: "\"Leicht verletzt\" = slightly injured.",
      },
    ],
  },
  {
    slug: "a2-common-words-history-conflict",
    level: "DE-A2",
    number: 7,
    title: "Common Words: History, Conflict and Survival",
    summary: "Talk about the past of a country or a family with Krieg, Frieden, Mauer, Grenze, fliehen, überleben and damals, and say years the German way.",
    duration: "13 min",
    sections: [
      {
        heading: "War, peace and borders",
        body: [
          "Core nouns: \"der Krieg, die Kriege\" (war), \"der Frieden\" (peace), \"die Mauer, die Mauern\" (wall: \"die Mauer\" means the Berlin Wall), \"die Grenze, die Grenzen\" (border), \"das Land, die Länder\" (country), \"die Geschichte, die Geschichten\" (history, and also story).",
          "That last one is useful: \"Geschichte\" means both the subject at school and a story you tell. \"Ich mag Geschichte\" (I like history) vs \"Erzähl mir eine Geschichte!\" (Tell me a story!).",
          "Time words for history: \"damals\" (back then, at that time), \"das Jahrhundert, die Jahrhunderte\" (century), \"früher\" (in the past), \"heute\" (today). \"Damals\" refers to a specific period you've already mentioned; \"früher\" is in general, the old days.",
        ],
        examples: [
          { es: "Der Krieg war 1945 zu Ende.", en: "The war ended in 1945." },
          { es: "Die Mauer stand 28 Jahre lang.", en: "The Wall stood for 28 years." },
          { es: "Damals gab es eine Grenze zwischen Ost und West.", en: "Back then there was a border between East and West." },
          { es: "Seit 1990 ist Deutschland wieder ein Land.", en: "Germany has been one country again since 1990." },
          { es: "Mein Opa hat mir viele Geschichten erzählt.", en: "My grandad told me lots of stories." },
          { es: "Wir leben seit vielen Jahren in Frieden.", en: "We've been living in peace for many years." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "Back then there was a border here.",
            answer: "Damals gab es hier eine Grenze.",
            altAnswers: ["Damals war hier eine Grenze.", "Hier gab es damals eine Grenze."],
            explanation: "\"Damals\" in position 1, then \"gab es\". \"Die Grenze\" is feminine.",
          },
          {
            type: "multiple-choice",
            question: "\"Erzähl mir eine Geschichte!\" What does it mean?",
            options: ["Tell me a story!", "Tell me some history!", "Write me a story!", "Tell me what happened!"],
            correctIndex: 0,
            explanation: "\"Geschichte\" means both history and story; \"erzählen\" + \"eine Geschichte\" = tell a story.",
          },
        ],
      },
      {
        heading: "Fliehen, überleben, kämpfen",
        body: [
          "Three verbs for hard times. \"Fliehen\" (to flee, escape) is movement, so it takes \"sein\": \"Sie ist 1961 nach Westberlin geflohen\". \"Überleben\" (to survive) has the inseparable prefix über-, so no ge-: \"Er hat den Krieg überlebt\". \"Kämpfen\" (to fight) is regular: \"Sie haben für die Freiheit gekämpft\".",
          "Related nouns: \"die Flucht\" (escape, flight), \"der Flüchtling\" (refugee), \"die Freiheit\" (freedom), \"der Soldat, die Soldaten\" (soldier).",
          "These verbs belong to serious family stories as well as history. \"Meine Großeltern sind nach dem Krieg aus Schlesien geflohen\" is a sentence many Germans could say about their own family.",
        ],
        examples: [
          { es: "Sie ist 1961 nach Westberlin geflohen.", en: "She fled to West Berlin in 1961." },
          { es: "Mein Uropa hat den Krieg überlebt.", en: "My great-grandfather survived the war." },
          { es: "Die Menschen haben für die Freiheit gekämpft.", en: "The people fought for freedom." },
          { es: "Nach dem Krieg mussten viele Familien fliehen.", en: "After the war many families had to flee." },
          { es: "Die Flucht war sehr gefährlich.", en: "The escape was very dangerous." },
        ],
        checkpoint: [
          {
            type: "fill-blank",
            prompt: "Write the German for the bold words.",
            en: "My grandmother [survived] the war.",
            sentence: "Meine Großmutter hat den Krieg ___.",
            answer: "überlebt",
            explanation: "\"Überleben\" is inseparable, so no ge-: \"überlebt\".",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "They fled to the West.",
            answer: "Sie sind in den Westen geflohen.",
            altAnswers: ["Sie flohen in den Westen.", "Sie sind nach Westen geflohen."],
            explanation: "\"Fliehen\" is movement: \"sind ... geflohen\". \"Der Westen\" → \"in den Westen\" (direction: accusative).",
          },
        ],
      },
      {
        heading: "Saying years: no \"in\"!",
        body: [
          "Years before 2000 are said in hundreds: 1989 = \"neunzehnhundertneunundachtzig\" (nineteen hundred eighty-nine). From 2000: \"zweitausend\", 2015 = \"zweitausendfünfzehn\".",
          "The big trap: German doesn't use \"in\" before a year. Say \"1989 ist die Mauer gefallen\" or \"im Jahr 1989\", never *in 1989*. This is one of the most common mistakes English speakers make, even at advanced levels.",
          "For centuries, use \"im\" + ordinal: \"im 20. Jahrhundert\" (\"im zwanzigsten Jahrhundert\"). For decades: \"in den Achtzigerjahren\" / \"in den 80ern\" (in the eighties).",
        ],
        examples: [
          { es: "1989 ist die Mauer gefallen.", en: "The Wall fell in 1989." },
          { es: "Im Jahr 1990 ist Deutschland wieder ein Land geworden.", en: "In 1990 Germany became one country again." },
          { es: "Meine Eltern haben 1995 geheiratet.", en: "My parents got married in 1995." },
          { es: "Im 19. Jahrhundert sind viele Deutsche nach Amerika gegangen.", en: "In the 19th century many Germans went to America." },
          { es: "In den Achtzigerjahren gab es noch keine Handys.", en: "In the eighties there were no mobile phones yet." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "The Wall fell in 1989.",
            answer: "1989 ist die Mauer gefallen.",
            altAnswers: ["Die Mauer ist 1989 gefallen.", "Im Jahr 1989 ist die Mauer gefallen.", "Die Mauer ist im Jahr 1989 gefallen.", "Die Mauer fiel 1989.", "1989 fiel die Mauer."],
            explanation: "No \"in\" before a year: just \"1989\" or \"im Jahr 1989\". \"Fallen\" takes \"sein\".",
          },
          {
            type: "listen-choose",
            audio: "neunzehnhundertneunundachtzig",
            question: "What year did you hear?",
            options: ["1989", "1998", "1899", "1889"],
            correctIndex: 0,
            explanation: "\"Neunzehnhundert\" (1900) + \"neunundachtzig\" (89, units first: nine-and-eighty).",
          },
          {
            type: "speak",
            text: "Meine Eltern haben 1995 geheiratet.",
            prompt: "Say it in German: My parents got married in 1995.",
            tip: "1995 = neunzehnhundertfünfundneunzig.",
            explanation: "No \"in\" before the year; \"heiraten\" → \"geheiratet\" with haben.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "My grandfather survived the war.",
        answer: "Mein Großvater hat den Krieg überlebt.",
        altAnswers: ["Mein Opa hat den Krieg überlebt.", "Mein Großvater überlebte den Krieg.", "Mein Opa überlebte den Krieg."],
        explanation: "\"Der Krieg\" → \"den Krieg\" (accusative); \"überlebt\" without ge-.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "I was born in 1990.",
        answer: "Ich bin 1990 geboren.",
        altAnswers: ["Ich wurde 1990 geboren.", "Ich bin im Jahr 1990 geboren.", "Ich wurde im Jahr 1990 geboren."],
        explanation: "No \"in\" before the year. \"Ich bin ... geboren\" is the everyday way to give your birth year.",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "Many people [fled] across the border.",
        sentence: "Viele Menschen sind über die Grenze ___.",
        answer: "geflohen",
        explanation: "\"Fliehen\" → \"geflohen\", with \"sein\" because it's movement.",
      },
      {
        type: "multiple-choice",
        question: "Which sentence is correct?",
        options: ["Wir sind 2012 nach Leipzig gezogen.", "Wir sind in 2012 nach Leipzig gezogen.", "Wir sind am 2012 nach Leipzig gezogen.", "Wir sind um 2012 nach Leipzig gezogen gewesen."],
        correctIndex: 0,
        explanation: "A bare year with no preposition (or \"im Jahr 2012\"). *In 2012* is the classic English-speaker error.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "I like history.",
        answer: "Ich mag Geschichte.",
        altAnswers: ["Ich finde Geschichte interessant.", "Ich habe Geschichte gern.", "Geschichte gefällt mir."],
        explanation: "\"Geschichte\" without an article = history as a subject.",
      },
      {
        type: "matching",
        instructions: "Match the German to the English.",
        pairs: [
          { left: "der Krieg", right: "war" },
          { left: "der Frieden", right: "peace" },
          { left: "die Grenze", right: "border" },
          { left: "das Jahrhundert", right: "century" },
          { left: "die Freiheit", right: "freedom" },
          { left: "damals", right: "back then" },
        ],
        explanation: "Learn each noun with its article: \"der Krieg\", \"der Frieden\", \"die Grenze\", \"das Jahrhundert\", \"die Freiheit\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "They fought for freedom.",
        answer: "Sie haben für die Freiheit gekämpft.",
        altAnswers: ["Sie kämpften für die Freiheit.", "Sie haben für Freiheit gekämpft."],
        explanation: "\"Kämpfen\" is regular: \"gekämpft\"; \"für\" + accusative \"die Freiheit\".",
      },
      {
        type: "listen-choose",
        audio: "Damals war alles anders.",
        question: "What does it mean?",
        options: ["Back then everything was different.", "Today everything is different.", "Everything was the same back then.", "Everything else was there."],
        correctIndex: 0,
        explanation: "\"Damals\" = back then; \"anders\" = different.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: In the 20th century there were two world wars.",
        words: ["Im", "20.", "Jahrhundert", "gab", "es", "zwei", "Weltkriege."],
        translation: "In the 20th century there were two world wars.",
        explanation: "\"Im 20. Jahrhundert\" (im zwanzigsten) in position 1, then \"gab es\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "The escape was very dangerous.",
        answer: "Die Flucht war sehr gefährlich.",
        explanation: "\"Die Flucht\" = escape, flight (from \"fliehen\"). \"Gefährlich\" = dangerous.",
      },
      {
        type: "speak",
        text: "Neunzehnhundertneunundachtzig ist die Mauer gefallen.",
        prompt: "Say it in German: The Wall fell in 1989.",
        explanation: "The year with no \"in\", then verb second: \"ist die Mauer gefallen\".",
      },
      {
        type: "dictation",
        audio: "Mein Opa hat den Krieg überlebt.",
        explanation: "\"Überlebt\": inseparable über-, so no ge-.",
      },
    ],
  },
  {
    slug: "a2-practice-tell-a-story",
    level: "DE-A2",
    number: 8,
    title: "Practice: Tell a Story from Start to Finish",
    summary: "Recombine the Perfekt and Präteritum, connectors with verb-second, seit, vor and lang in a complete story about a holiday that went wrong.",
    duration: "15 min",
    sections: [
      {
        heading: "The setup",
        body: [
          "Jonas tells his friends about last summer's holiday. Every good story starts by setting the scene: when (\"vor einem Jahr\", \"letzten Sommer\"), who, where, and how things were (\"war\", \"hatte\", \"es gab\").",
          "Notice the verb in position 2 after every time phrase: \"Letzten Sommer sind Lena und ich...\".",
        ],
        examples: [
          { es: "Letzten Sommer sind Lena und ich nach Italien gefahren.", en: "Last summer Lena and I went to Italy." },
          { es: "Wir hatten zwei Wochen Urlaub.", en: "We had two weeks' holiday." },
          { es: "Wir wollten zuerst nach Rom und dann ans Meer.", en: "We wanted to go to Rome first and then to the sea." },
          { es: "Das Wetter war wunderbar.", en: "The weather was wonderful." },
          { es: "Aber dann hat das Chaos angefangen.", en: "But then the chaos started." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "Last summer we went to Italy.",
            answer: "Letzten Sommer sind wir nach Italien gefahren.",
            altAnswers: ["Wir sind letzten Sommer nach Italien gefahren.", "Letzten Sommer sind wir nach Italien geflogen.", "Wir sind letzten Sommer nach Italien geflogen."],
            explanation: "Time phrase first, auxiliary \"sind\" second. \"Letzten Sommer\" (der Sommer) is accusative of time.",
          },
          {
            type: "fill-blank",
            prompt: "Write the German for the bold words.",
            en: "We [had] two weeks' holiday.",
            sentence: "Wir ___ zwei Wochen Urlaub.",
            answer: "hatten",
            explanation: "\"Haben\" in the Präteritum for wir: \"hatten\".",
          },
        ],
      },
      {
        heading: "What went wrong",
        body: [
          "The middle of the story is a chain of events, so connectors carry it: \"zuerst\", \"dann\", \"danach\", \"später\". Actions go in the Perfekt, states and modals in the Präteritum.",
          "Durations matter here too: \"Wir haben drei Stunden lang gewartet\" (finished), \"vor dem Hotel\", \"nach zwei Tagen\".",
        ],
        examples: [
          { es: "Zuerst hatte unser Zug acht Stunden Verspätung.", en: "First our train was eight hours late." },
          { es: "Dann haben wir in Rom unseren Koffer verloren.", en: "Then we lost our suitcase in Rome." },
          { es: "Wir haben drei Stunden lang am Bahnhof gewartet.", en: "We waited at the station for three hours." },
          { es: "Danach war Lena krank und musste zwei Tage im Bett bleiben.", en: "After that Lena was ill and had to stay in bed for two days." },
          { es: "Und am Strand hat es fünf Tage lang geregnet!", en: "And at the beach it rained for five days!" },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "Then we lost our suitcase.",
            answer: "Dann haben wir unseren Koffer verloren.",
            explanation: "\"Dann\" + \"haben wir\"; \"der Koffer\" → \"unseren Koffer\"; \"verlieren\" → \"verloren\" (no ge-).",
          },
          {
            type: "word-order",
            prompt: "Put the words in order to say: It rained for five days.",
            words: ["Es", "hat", "fünf", "Tage", "lang", "geregnet."],
            translation: "It rained for five days.",
            explanation: "A finished period: \"fünf Tage lang\" (accusative, no -n) + Perfekt.",
          },
          {
            type: "listen-choose",
            audio: "Lena musste zwei Tage im Bett bleiben.",
            question: "What does it mean?",
            options: ["Lena had to stay in bed for two days.", "Lena wanted to stay in bed for two days.", "Lena stayed in bed two days ago.", "Lena has been in bed for two days."],
            correctIndex: 0,
            explanation: "\"Musste\" = had to; \"zwei Tage\" = for two days (a finished period).",
          },
        ],
      },
      {
        heading: "The ending and today",
        body: [
          "A good story ends with the outcome and a link to now: \"Zum Schluss...\", \"Seitdem...\" (since then) or \"Seit dem Urlaub...\". The link to now uses \"seit\" + present: \"Seit dem Urlaub fahre ich nur noch mit dem Auto\".",
          "And remember the classic closer for a disaster: \"Aber es war trotzdem ein schöner Urlaub\" (But it was still a lovely holiday), or the opposite: \"Nie wieder!\" (Never again!).",
        ],
        examples: [
          { es: "Zum Schluss haben wir den Koffer zurückbekommen.", en: "In the end we got the suitcase back." },
          { es: "Aber es war trotzdem ein schöner Urlaub.", en: "But it was still a lovely holiday." },
          { es: "Seitdem nehme ich immer nur Handgepäck mit.", en: "Since then I only ever take hand luggage." },
          { es: "Nie wieder Zug!", en: "Never again by train!" },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "But it was still a lovely holiday.",
            answer: "Aber es war trotzdem ein schöner Urlaub.",
            altAnswers: ["Aber es war trotzdem ein toller Urlaub.", "Es war aber trotzdem ein schöner Urlaub.", "Aber trotzdem war es ein schöner Urlaub."],
            explanation: "\"Aber\" doesn't count for word order; \"trotzdem\" = still, nevertheless.",
          },
          {
            type: "speak",
            text: "Seitdem nehme ich nur Handgepäck mit.",
            prompt: "Say it in German: Since then I only take hand luggage.",
            explanation: "\"Seitdem\" + present, because it's still true. \"Mitnehmen\" separates: \"nehme ... mit\".",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "A year ago we went to Spain.",
        answer: "Vor einem Jahr sind wir nach Spanien gefahren.",
        altAnswers: ["Wir sind vor einem Jahr nach Spanien gefahren.", "Vor einem Jahr sind wir nach Spanien geflogen.", "Wir sind vor einem Jahr nach Spanien geflogen."],
        explanation: "\"Vor einem Jahr\" (ago, dative), then verb second: \"sind wir\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "First the flight was late.",
        answer: "Zuerst hatte der Flug Verspätung.",
        altAnswers: ["Zuerst war der Flug verspätet.", "Zuerst hat der Flug Verspätung gehabt.", "Zuerst war der Flug zu spät."],
        explanation: "\"Zuerst\" + verb + subject. \"Verspätung haben\" = to be late (of transport).",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "Then we waited for two hours.",
        answer: "Dann haben wir zwei Stunden lang gewartet.",
        altAnswers: ["Dann haben wir zwei Stunden gewartet."],
        explanation: "\"Dann\" + auxiliary; a finished period with \"lang\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "After that the hotel [had] no rooms.",
        sentence: "Danach ___ das Hotel keine Zimmer.",
        answer: "hatte",
        explanation: "\"Haben\" → Präteritum \"hatte\", verb second after \"danach\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "When we arrived, it was raining.",
        answer: "Als wir angekommen sind, hat es geregnet.",
        altAnswers: ["Als wir ankamen, hat es geregnet.", "Als wir angekommen sind, regnete es.", "Als wir ankamen, regnete es."],
        explanation: "\"Als\" + one moment in the past; the auxiliary goes to the very end of the als clause, and the main clause starts with its verb.",
      },
      {
        type: "multiple-choice",
        question: "Which sentence is correct?",
        options: ["Seit dem Urlaub fahre ich nicht mehr Zug.", "Seit dem Urlaub bin ich nicht mehr Zug gefahren gewesen.", "Seit dem Urlaub ich fahre nicht mehr Zug.", "Vor dem Urlaub fahre ich seit nicht mehr Zug."],
        correctIndex: 0,
        explanation: "\"Seit\" + present for something still true, and verb second after the time phrase.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "Lena was ill and had to stay at the hotel.",
        answer: "Lena war krank und musste im Hotel bleiben.",
        explanation: "Two Präteritum forms, \"war\" and \"musste\", with \"bleiben\" at the end.",
      },
      {
        type: "listen-choose",
        audio: "Zum Schluss haben wir den Koffer zurückbekommen.",
        question: "What does it mean?",
        options: ["In the end we got the suitcase back.", "At first we got the suitcase back.", "In the end we sent the suitcase back.", "In the end we lost the suitcase."],
        correctIndex: 0,
        explanation: "\"Zurückbekommen\" = to get back; separable \"zurück\" + \"bekommen\", which has no ge-.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: Later we found a nice restaurant.",
        words: ["Später", "haben", "wir", "ein", "schönes", "Restaurant", "gefunden."],
        translation: "Later we found a nice restaurant.",
        explanation: "\"Später\" in position 1, \"haben\" second, \"gefunden\" last.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "It was a disaster, but we laughed a lot.",
        answer: "Es war eine Katastrophe, aber wir haben viel gelacht.",
        altAnswers: ["Es war ein Desaster, aber wir haben viel gelacht.", "Es war eine Katastrophe, aber wir lachten viel."],
        explanation: "\"War\" for the state, Perfekt \"haben ... gelacht\" for the action; \"aber\" doesn't affect word order.",
      },
      {
        type: "speak",
        text: "Zuerst war alles gut, aber dann hat das Chaos angefangen.",
        prompt: "Say it in German: At first everything was fine, but then the chaos started.",
        explanation: "Two connectors: \"zuerst\" and \"dann\", each followed by the verb; \"aber\" doesn't count.",
      },
      {
        type: "dictation",
        audio: "Nie wieder Zug!",
        explanation: "\"Nie wieder\" = never again.",
      },
    ],
  },
];

export const DE_A2_U06_WRITING: WriteExercise = {
  type: "write",
  prompt: "Write a short story for a German blog about an important day or event in your life (a move, a trip, a first day at a new job). Say how long ago it happened, tell the events in order, and say what has been different since then.",
  minWords: 50,
  maxWords: 100,
  rubric: [
    "Says when it happened with \"vor\" + dative (\"vor drei Jahren\") or a year without \"in\"",
    "Orders the events with connectors and the verb right after them (\"Zuerst habe ich...\", \"Dann bin ich...\", \"Zum Schluss...\")",
    "Uses \"seit\" + present for what is still true (\"Seitdem wohne ich...\", \"seit zwei Jahren\") and \"... lang\" for a finished period",
    "Uses the Perfekt for actions and \"war\", \"hatte\" and the modals in the Präteritum",
  ],
  modelAnswer: "Vor vier Jahren bin ich von London nach Hamburg gezogen. Zuerst war alles schwierig: Ich hatte keine Wohnung und konnte kaum Deutsch. Ich habe drei Wochen lang bei einer Freundin gewohnt. Dann habe ich endlich eine kleine Wohnung in Altona gefunden. Danach habe ich einen Deutschkurs gemacht und viele nette Leute kennengelernt. Als ich meine erste Arbeit hatte, war ich sehr glücklich. Seit zwei Jahren arbeite ich jetzt in einem Hotel, und seitdem spreche ich jeden Tag Deutsch.",
  explanation: "\"Vor vier Jahren\" points to the start, the connectors (\"zuerst\", \"dann\", \"danach\") are each followed by the verb, \"drei Wochen lang\" is a finished period, and \"seit zwei Jahren arbeite ich\" uses the present because it's still true. The als clause sends \"hatte\" to the end and the main clause starts with \"war\".",
};

