// Synced from cheneygross-afk/lengo:src/lib/lessons/de-a1.ts by scripts/sync-content.mjs -- edit it there, not here.
import type { Lesson } from "./types";
import type { UnitOutline } from "./units";
import { buildGermanLevel, type GermanUnitDef } from "./de-units";
import { DE_A1_U01, DE_A1_U01_WRITING } from "./de-a1-u01";
import { DE_A1_U01_EXTRA } from "./de-a1-u01-extra";
import { DE_A1_U02, DE_A1_U02_WRITING } from "./de-a1-u02";
import { DE_A1_U03, DE_A1_U03_WRITING } from "./de-a1-u03";
import { DE_A1_U03_EXTRA } from "./de-a1-u03-extra";
import { DE_A1_U04, DE_A1_U04_WRITING } from "./de-a1-u04";
import { DE_A1_U05, DE_A1_U05_WRITING } from "./de-a1-u05";
import { DE_A1_U05_EXTRA } from "./de-a1-u05-extra";
import { DE_A1_U06, DE_A1_U06_WRITING } from "./de-a1-u06";
import { DE_A1_U06_EXTRA } from "./de-a1-u06-extra";
import { DE_A1_U07, DE_A1_U07_WRITING } from "./de-a1-u07";
import { DE_A1_U07_EXTRA } from "./de-a1-u07-extra";
import { DE_A1_U08, DE_A1_U08_WRITING } from "./de-a1-u08";
import { DE_A1_U08_EXTRA } from "./de-a1-u08-extra";
import { DE_A1_U09, DE_A1_U09_WRITING } from "./de-a1-u09";
import { DE_A1_U10, DE_A1_U10_WRITING } from "./de-a1-u10";

// German A1: generated by scripts/gen-german-level.ts from
// docs/german-course/syllabus-a1.md and the unit files
// (de-a1-u<NN>.ts, de-a1-u<NN>-extra.ts). Don't edit by hand;
// re-run the script when a unit file is added.
const UNITS: GermanUnitDef[] = [
  { id: "u01", title: "Sein, Articles & Nouns", description: "Greet people, introduce yourself, say who and what people and things are, and describe them with simple adjectives after sein.", lessons: DE_A1_U01, extra: DE_A1_U01_EXTRA, writing: DE_A1_U01_WRITING },
  { id: "u02", title: "Sounds of German", description: "Hear and pronounce the sounds that make German German, read words aloud from their spelling, and spell your name.", lessons: DE_A1_U02, writing: DE_A1_U02_WRITING },
  { id: "u03", title: "Present Tense & Haben", description: "Talk about what you do every day, what you have and how you feel, put the verb in second place, and say what you do not do or have.", lessons: DE_A1_U03, extra: DE_A1_U03_EXTRA, writing: DE_A1_U03_WRITING },
  { id: "u04", title: "Everyday Irregulars & Modal Verbs", description: "Say what you become, know and would like, and use can, must, want, may and should with a second verb at the end of the sentence.", lessons: DE_A1_U04, writing: DE_A1_U04_WRITING },
  { id: "u05", title: "Questions, Negation & Word Order", description: "Ask every kind of question, answer and contradict, say what or who you see, have or need with the accusative, and say what there is.", lessons: DE_A1_U05, extra: DE_A1_U05_EXTRA, writing: DE_A1_U05_WRITING },
  { id: "u06", title: "Possessives, Numbers & Time", description: "Say what belongs to whom, talk about your family, count, handle prices and phone numbers, tell the time, and buy food in quantities.", lessons: DE_A1_U06, extra: DE_A1_U06_EXTRA, writing: DE_A1_U06_WRITING },
  { id: "u07", title: "Dates, Weather & Places", description: "Give the date, talk about the weather and the seasons, say which city or country you live in, go to and come from, and how you get there.", lessons: DE_A1_U07, extra: DE_A1_U07_EXTRA, writing: DE_A1_U07_WRITING },
  { id: "u08", title: "Likes & Separable Verbs", description: "Talk about what you like doing and like best, describe your daily routine, make plans and appointments, and tell people what to do.", lessons: DE_A1_U08, extra: DE_A1_U08_EXTRA, writing: DE_A1_U08_WRITING },
  { id: "u09", title: "This & That, and the Beginner Level So Far", description: "Point things out, say where things are, replace people and things with pronouns, ask the way, shop for clothes, and pull the whole Beginner level together.", lessons: DE_A1_U09, writing: DE_A1_U09_WRITING },
  { id: "u10", title: "Beginner Final Review", description: "Show that you can handle every Beginner topic together and pass a Goethe-Zertifikat A1-style test of listening, reading, writing and speaking.", lessons: DE_A1_U10, writing: DE_A1_U10_WRITING },
];

const LEVEL = buildGermanLevel("A1", UNITS);
export const DE_A1_LESSONS: Lesson[] = LEVEL.lessons;
export const DE_A1_UNITS: UnitOutline[] = LEVEL.units;
