// Synced from cheneygross-afk/lengo:src/lib/lessons/de-b1-u16-extra.ts by scripts/sync-content.mjs -- edit it there, not here.
import type { Lesson } from "./types";
// German B1, Unit 16 extra practice: Verbs with Prepositions.

export const DE_B1_U16_EXTRA: Lesson[] = [
  {
    slug: "b1-verbs-prepositions-extra-1",
    level: "DE-B1",
    number: 1,
    optional: true,
    title: "Extra Practice: Verbs with Prepositions, Part 1 of 3",
    summary: "Accusative prepositional verbs in fresh everyday sentences.",
    duration: "12 min",
    sections: [
      {
        heading: "Recap: the accusative group",
        body: [
          "These verbs take the accusative after their preposition: \"warten auf\", \"denken an\", \"sich erinnern an\", \"sich gewöhnen an\", \"sich freuen auf / über\", \"sich ärgern über\", \"sprechen über\", \"sich interessieren für\", \"sich kümmern um\", \"sich bewerben um\", \"bitten um\", \"sich verlassen auf\", \"sich vorbereiten auf\".",
          "Only masculine singular changes visibly: \"den\", \"einen\", \"meinen\" + adjective -en. Pronouns: \"auf mich, dich, ihn, sie, uns, euch, Sie\".",
        ],
        examples: [
          { es: "Wir warten schon seit einer Stunde auf den Techniker.", en: "We've been waiting for the technician for an hour." },
          { es: "Erinnerst du dich an unseren Lehrer aus der Grundschule?", en: "Do you remember our primary school teacher?" },
          { es: "Mehmet bereitet sich auf einen Halbmarathon vor.", en: "Mehmet is training for a half marathon." },
          { es: "Ich habe mich schnell an das neue Handy gewöhnt.", en: "I quickly got used to the new phone." },
          { es: "Sie bittet ihren Chef um einen Tag Urlaub.", en: "She's asking her boss for a day off." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "I'm waiting for my brother.",
            answer: "Ich warte auf meinen Bruder.",
            explanation: "\"Warten auf\" + accusative: \"meinen Bruder\".",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "Do you remember me? (to a friend)",
            answer: "Erinnerst du dich an mich?",
            altAnswers: ["Erinnert ihr euch an mich?"],
            explanation: "\"Sich erinnern an\" + accusative: \"an mich\".",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "She's interested in old cars.",
        answer: "Sie interessiert sich für alte Autos.",
        explanation: "\"Sich interessieren für\" + accusative plural: \"alte Autos\" (no article, strong ending -e).",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "We're looking forward to the concert.",
        answer: "Wir freuen uns auf das Konzert.",
        altAnswers: ["Wir freuen uns aufs Konzert.", "Wir freuen uns schon auf das Konzert."],
        explanation: "Future event: \"sich freuen auf\" + accusative.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "My grandmother often talks about the war.",
        answer: "Meine Oma spricht oft über den Krieg.",
        altAnswers: ["Meine Großmutter spricht oft über den Krieg.", "Meine Oma erzählt oft vom Krieg.", "Meine Großmutter erzählt oft vom Krieg."],
        explanation: "\"Sprechen über\" + accusative: masculine \"den Krieg\". (\"Erzählen von\" + dative is also natural.)",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "Who's looking after the plants when you're away? (to a friend)",
        answer: "Wer kümmert sich um die Pflanzen, wenn du weg bist?",
        altAnswers: ["Wer kümmert sich um die Pflanzen, wenn ihr weg seid?", "Wer kümmert sich um die Pflanzen, wenn du nicht da bist?", "Wer kümmert sich um die Pflanzen, wenn du verreist bist?"],
        explanation: "\"Sich kümmern um\" + accusative; in the wenn-clause the verb goes to the end.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "I'm annoyed about the high prices.",
        answer: "Ich ärgere mich über die hohen Preise.",
        explanation: "\"Sich ärgern über\" + accusative; \"hoch\" loses its c before an ending: \"hohen\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "He has applied for a job in Munich.",
        answer: "Er hat sich um eine Stelle in München beworben.",
        altAnswers: ["Er hat sich um einen Job in München beworben.", "Er hat sich für eine Stelle in München beworben."],
        explanation: "\"Sich bewerben um\" + accusative; Perfekt \"hat sich ... beworben\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "You can always rely [on your sister].",
        sentence: "Du kannst dich immer ___ verlassen.",
        answer: "auf deine Schwester",
        explanation: "\"Sich verlassen auf\" + accusative: feminine \"deine Schwester\" unchanged.",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "I'm still thinking [about the film].",
        sentence: "Ich denke immer noch ___.",
        answer: "an den Film",
        explanation: "\"Denken an\" + accusative: \"an den Film\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "Have you got used to the noise? (to a friend)",
        answer: "Hast du dich an den Lärm gewöhnt?",
        altAnswers: ["Habt ihr euch an den Lärm gewöhnt?", "Hast du dich schon an den Lärm gewöhnt?"],
        explanation: "\"Sich gewöhnen an\" + accusative, Perfekt with \"haben\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "The waiter asked us for patience.",
        answer: "Der Kellner hat uns um Geduld gebeten.",
        altAnswers: ["Der Kellner bat uns um Geduld.", "Die Kellnerin hat uns um Geduld gebeten.", "Die Kellnerin bat uns um Geduld."],
        explanation: "\"Jemanden um etwas bitten\": person in the accusative (\"uns\"), thing with \"um\".",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: We're preparing for the trip.",
        words: ["Wir", "bereiten", "uns", "auf", "die", "Reise", "vor."],
        translation: "We're preparing for the trip.",
        explanation: "Separable \"sich vorbereiten auf\": \"vor\" at the end.",
      },
      {
        type: "multiple-choice",
        question: "Which sentence is correct?",
        options: ["Ich erinnere mich an den Sommer 2015.", "Ich erinnere mich an dem Sommer 2015.", "Ich erinnere den Sommer 2015.", "Ich erinnere mich über den Sommer 2015."],
        correctIndex: 0,
        explanation: "\"Sich erinnern an\" + accusative, and the verb needs the reflexive pronoun.",
      },
      {
        type: "listen-choose",
        audio: "Ich habe mich sehr über deine Nachricht gefreut.",
        question: "What does it mean?",
        options: ["I was really pleased about your message.", "I'm really looking forward to your message.", "I was really annoyed about your message.", "I thought a lot about your message."],
        correctIndex: 0,
        explanation: "\"Sich freuen über\" in the Perfekt: you've already got the message.",
      },
      {
        type: "speak",
        text: "Ich warte auf eine Antwort.",
        prompt: "Say it in German: I'm waiting for an answer.",
        tip: "\"Antwort\": stress the first syllable, AN-twort.",
        explanation: "\"Warten auf\" + accusative: \"auf eine Antwort\".",
      },
    ],
  },
  {
    slug: "b1-verbs-prepositions-extra-2",
    level: "DE-B1",
    number: 2,
    optional: true,
    title: "Extra Practice: Verbs with Prepositions, Part 2 of 3",
    summary: "Dative prepositional verbs in fresh everyday sentences.",
    duration: "12 min",
    sections: [
      {
        heading: "Recap: the dative group",
        body: [
          "These verbs take the dative: \"teilnehmen an\", \"leiden an / unter\", \"zweifeln an\", \"Angst haben vor\", \"sich fürchten vor\", \"träumen von\", \"abhängen von\", \"sich verabschieden von\", \"sich erholen von\", \"erzählen von\", \"fragen nach\", \"gratulieren zu\", \"einladen zu\", \"helfen bei\", \"sich bedanken bei\", \"bestehen aus\", \"sich beschäftigen mit\", \"telefonieren mit\".",
          "Dative endings: \"dem / einem\" (m, n), \"der / einer\" (f), \"den\" + -n (plural). Contractions: \"am, beim, vom, zum, zur\".",
        ],
        examples: [
          { es: "Hast du schon mal an einem Marathon teilgenommen?", en: "Have you ever run a marathon?" },
          { es: "Unsere Reise hängt vom Geld ab.", en: "Our trip depends on money." },
          { es: "Sie hat ihm zum Abschluss gratuliert.", en: "She congratulated him on his degree." },
          { es: "Ich beschäftige mich gerade mit der deutschen Geschichte.", en: "I'm reading up on German history at the moment." },
          { es: "Die Kinder fürchten sich vor dem Gewitter.", en: "The children are scared of the thunderstorm." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "Thank you for helping me with the move! (to a friend)",
            answer: "Danke, dass du mir beim Umzug geholfen hast!",
            altAnswers: ["Danke, dass ihr mir beim Umzug geholfen habt!", "Danke für deine Hilfe beim Umzug!", "Danke für eure Hilfe beim Umzug!"],
            explanation: "\"Helfen bei\" + dative: \"beim Umzug\"; the dass-clause ends with \"geholfen hast\".",
          },
          {
            type: "fill-blank",
            prompt: "Write the German for the bold words.",
            en: "She's afraid [of the dark].",
            sentence: "Sie hat Angst ___.",
            answer: "vor der Dunkelheit",
            altAnswers: ["im Dunkeln"],
            explanation: "\"Angst haben vor\" + dative: \"vor der Dunkelheit\".",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "I took part in a cooking course.",
        answer: "Ich habe an einem Kochkurs teilgenommen.",
        altAnswers: ["Ich nahm an einem Kochkurs teil."],
        explanation: "\"Teilnehmen an\" + dative: \"an einem Kochkurs\"; participle \"teilgenommen\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "He dreams of his own restaurant.",
        answer: "Er träumt von einem eigenen Restaurant.",
        explanation: "\"Träumen von\" + dative: \"von einem eigenen Restaurant\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "We said goodbye to our neighbours.",
        answer: "Wir haben uns von unseren Nachbarn verabschiedet.",
        altAnswers: ["Wir verabschiedeten uns von unseren Nachbarn."],
        explanation: "\"Sich verabschieden von\" + dative plural: \"unseren Nachbarn\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "The tourist asked about the museum.",
        answer: "Der Tourist hat nach dem Museum gefragt.",
        altAnswers: ["Der Tourist fragte nach dem Museum.", "Die Touristin hat nach dem Museum gefragt.", "Die Touristin fragte nach dem Museum."],
        explanation: "\"Fragen nach\" + dative: inquire about, ask the way to.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "The menu consists of three courses.",
        answer: "Das Menü besteht aus drei Gängen.",
        explanation: "\"Bestehen aus\" + dative plural: \"drei Gängen\" with -n.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "I phoned my grandma yesterday.",
        answer: "Ich habe gestern mit meiner Oma telefoniert.",
        altAnswers: ["Ich habe gestern mit meiner Großmutter telefoniert.", "Gestern habe ich mit meiner Oma telefoniert.", "Ich habe gestern meine Oma angerufen."],
        explanation: "\"Telefonieren mit\" + dative: \"mit meiner Oma\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "She has recovered [from the operation].",
        sentence: "Sie hat sich gut ___ erholt.",
        answer: "von der Operation",
        explanation: "\"Sich erholen von\" + dative.",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "We invited them [to dinner].",
        sentence: "Wir haben sie ___ eingeladen.",
        answer: "zum Essen",
        altAnswers: ["zum Abendessen"],
        explanation: "\"Einladen zu\" + dative: \"zum Essen\" (zu + dem).",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "I doubt his story.",
        answer: "Ich zweifle an seiner Geschichte.",
        altAnswers: ["Ich zweifele an seiner Geschichte."],
        explanation: "\"Zweifeln an\" + dative: \"an seiner Geschichte\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "Can you help me with the shopping? (to a friend)",
        answer: "Kannst du mir beim Einkaufen helfen?",
        altAnswers: ["Könntest du mir beim Einkaufen helfen?", "Könnt ihr mir beim Einkaufen helfen?"],
        explanation: "\"Helfen bei\" + dative: \"beim Einkaufen\" (a nominalised verb, neuter).",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: It depends on the price.",
        words: ["Es", "hängt", "vom", "Preis", "ab."],
        translation: "It depends on the price.",
        explanation: "\"Abhängen von\" + dative; \"ab\" at the end.",
      },
      {
        type: "multiple-choice",
        question: "Which sentence is correct?",
        options: ["Er leidet an einer Allergie.", "Er leidet an eine Allergie.", "Er leidet von einer Allergie.", "Er leidet mit einer Allergie."],
        correctIndex: 0,
        explanation: "An illness: \"leiden an\" + dative: \"an einer Allergie\".",
      },
      {
        type: "listen-choose",
        audio: "Wir nehmen an der Demo teil.",
        question: "What does it mean?",
        options: ["We're taking part in the demo.", "We're taking the demo apart.", "We're talking about the demo.", "We're afraid of the demo."],
        correctIndex: 0,
        explanation: "\"Teilnehmen an\" + dative: take part in.",
      },
      {
        type: "speak",
        text: "Ich habe mich von allen verabschiedet.",
        prompt: "Say it in German: I said goodbye to everyone.",
        tip: "\"Verabschiedet\": fer-AP-shee-det.",
        explanation: "\"Sich verabschieden von\" + dative.",
      },
    ],
  },
  {
    slug: "b1-verbs-prepositions-extra-3",
    level: "DE-B1",
    number: 3,
    optional: true,
    title: "Extra Practice: Verbs with Prepositions, Part 3 of 3",
    summary: "Adjectives and nouns with fixed prepositions in fresh sentences.",
    duration: "12 min",
    sections: [
      {
        heading: "Recap: adjectives and nouns",
        body: [
          "Accusative: \"stolz auf\", \"gespannt auf\", \"neugierig auf\", \"sauer auf\", \"böse auf\", \"verliebt in\", \"froh über\", \"Lust auf\", \"Freude über\". Dative: \"zufrieden mit\", \"fertig mit\", \"verheiratet mit\", \"begeistert von\", \"enttäuscht von\", \"abhängig von\", \"interessiert an\", \"Interesse an\", \"Angst vor\".",
          "The adjective usually goes at the end of the clause, after the prepositional phrase: \"Ich bin mit der Arbeit fertig\". Putting the phrase after the adjective is also fine in speech: \"Ich bin fertig mit der Arbeit\".",
        ],
        examples: [
          { es: "Bist du schon mit den Hausaufgaben fertig?", en: "Have you finished your homework yet?" },
          { es: "Ich bin enttäuscht von dem Hotel.", en: "I'm disappointed with the hotel." },
          { es: "Sie ist sauer auf ihren Bruder.", en: "She's cross with her brother." },
          { es: "Wir sind sehr froh über die Entscheidung.", en: "We're very glad about the decision." },
          { es: "Hast du Interesse an einem Job in Leipzig?", en: "Are you interested in a job in Leipzig?" },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "I've finished the report.",
            answer: "Ich bin mit dem Bericht fertig.",
            altAnswers: ["Ich bin fertig mit dem Bericht."],
            explanation: "\"Fertig mit\" + dative: \"mit dem Bericht\". Using \"haben\" here (*Ich habe fertig*) is a calque from English.",
          },
          {
            type: "speak",
            text: "Ich bin sehr stolz auf dich.",
            prompt: "Say it in German: I'm very proud of you.",
            tip: "\"Stolz\": st at the start sounds like sht.",
            explanation: "\"Stolz auf\" + accusative: \"auf dich\".",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "She's proud of her new flat.",
        answer: "Sie ist stolz auf ihre neue Wohnung.",
        explanation: "\"Stolz auf\" + accusative.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "We're disappointed with the service.",
        answer: "Wir sind vom Service enttäuscht.",
        altAnswers: ["Wir sind von dem Service enttäuscht.", "Wir sind enttäuscht vom Service.", "Wir sind enttäuscht von dem Service.", "Wir sind mit dem Service unzufrieden."],
        explanation: "\"Enttäuscht von\" + dative: \"vom Service\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "Do you fancy a coffee? (to a friend)",
        answer: "Hast du Lust auf einen Kaffee?",
        altAnswers: ["Habt ihr Lust auf einen Kaffee?"],
        explanation: "\"Lust auf\" + accusative: masculine \"einen Kaffee\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "He's married to a Spanish woman.",
        answer: "Er ist mit einer Spanierin verheiratet.",
        altAnswers: ["Er ist verheiratet mit einer Spanierin."],
        explanation: "\"Verheiratet mit\" + dative: \"mit einer Spanierin\". Not *verheiratet zu*.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "I'm curious about your new boyfriend.",
        answer: "Ich bin neugierig auf deinen neuen Freund.",
        altAnswers: ["Ich bin gespannt auf deinen neuen Freund.", "Ich bin neugierig auf euren neuen Freund."],
        explanation: "\"Neugierig auf\" or \"gespannt auf\" + accusative: \"deinen neuen Freund\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "The company is interested in new ideas.",
        answer: "Die Firma ist an neuen Ideen interessiert.",
        altAnswers: ["Die Firma interessiert sich für neue Ideen.", "Das Unternehmen ist an neuen Ideen interessiert."],
        explanation: "Adjective \"interessiert an\" + dative plural: \"an neuen Ideen\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "Are you cross [with me]? (to a friend)",
        sentence: "Bist du sauer ___?",
        answer: "auf mich",
        explanation: "\"Sauer auf\" + accusative: \"auf mich\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "She's very happy [with her new car].",
        sentence: "Sie ist sehr zufrieden ___.",
        answer: "mit ihrem neuen Auto",
        explanation: "\"Zufrieden mit\" + dative: \"mit ihrem neuen Auto\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "Many people are dependent on their cars.",
        answer: "Viele Menschen sind von ihren Autos abhängig.",
        altAnswers: ["Viele Leute sind von ihren Autos abhängig.", "Viele Menschen sind abhängig von ihren Autos.", "Viele Menschen sind von ihrem Auto abhängig."],
        explanation: "\"Abhängig von\" + dative plural: \"von ihren Autos\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "We were thrilled with the concert.",
        answer: "Wir waren von dem Konzert begeistert.",
        altAnswers: ["Wir waren vom Konzert begeistert.", "Wir waren begeistert vom Konzert.", "Wir waren begeistert von dem Konzert."],
        explanation: "\"Begeistert von\" + dative; \"sein\" in the Präteritum: \"waren\".",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: I'm glad about your decision.",
        words: ["Ich", "bin", "froh", "über", "deine", "Entscheidung."],
        translation: "I'm glad about your decision.",
        altOrders: [["Ich", "bin", "über", "deine", "Entscheidung", "froh."]],
        explanation: "\"Froh über\" + accusative; the adjective can go before or after the phrase.",
      },
      {
        type: "multiple-choice",
        question: "Which sentence is correct?",
        options: ["Er ist in seine Kollegin verliebt.", "Er ist in seiner Kollegin verliebt.", "Er ist mit seiner Kollegin verliebt.", "Er ist von seiner Kollegin verliebt."],
        correctIndex: 0,
        explanation: "\"Verliebt in\" + accusative: \"in seine Kollegin\". English in love with tempts \"mit\".",
      },
      {
        type: "listen-choose",
        audio: "Ich habe keine Lust auf Arbeit.",
        question: "What does it mean?",
        options: ["I don't feel like working.", "I've got no work.", "I'm not afraid of work.", "I'm not interested in my job."],
        correctIndex: 0,
        explanation: "\"Keine Lust auf\" + accusative: not in the mood for.",
      },
      {
        type: "speak",
        text: "Bist du mit dem Ergebnis zufrieden?",
        prompt: "Say it in German: Are you happy with the result?",
        tip: "\"Zufrieden\": z = ts, and ie is a long ee.",
        explanation: "\"Zufrieden mit\" + dative: \"mit dem Ergebnis\".",
      },
    ],
  },
  {
    slug: "b1-verbs-prepositions-extra-4",
    level: "DE-B1",
    number: 4,
    optional: true,
    title: "Extra Practice: Real-World Mission, An Event Invitation",
    summary: "Write and answer an invitation with sich freuen auf, teilnehmen an and sich anmelden für.",
    duration: "12 min",
    sections: [
      {
        heading: "Recap: inviting and replying",
        body: [
          "The sports club in Leipzig is inviting members to a summer festival. The language of invitations: \"Wir laden Sie herzlich zu unserem Sommerfest ein\", \"Bitte melden Sie sich bis zum 10. Juni für das Fest an\", \"Wir freuen uns auf Ihre Teilnahme\".",
          "Replies: \"Vielen Dank für die Einladung\", \"Ich nehme gern am Fest teil\", \"Leider kann ich nicht an dem Fest teilnehmen\". \"Sich anmelden für\" + Akk (sign up for) can also be \"sich anmelden zu\" + Dat; both are correct.",
        ],
        examples: [
          { es: "Wir laden Sie herzlich zu unserem Sommerfest ein.", en: "We warmly invite you to our summer festival." },
          { es: "Bitte melden Sie sich bis Freitag für das Fest an.", en: "Please sign up for the festival by Friday." },
          { es: "Wir freuen uns auf Ihre Teilnahme.", en: "We look forward to your participation." },
          { es: "Vielen Dank für die nette Einladung!", en: "Many thanks for the kind invitation!" },
          { es: "Leider kann ich nicht an dem Fest teilnehmen.", en: "Unfortunately I can't come to the festival." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "Thank you for the invitation.",
            answer: "Danke für die Einladung.",
            altAnswers: ["Vielen Dank für die Einladung.", "Herzlichen Dank für die Einladung."],
            explanation: "\"Danke für\" + accusative.",
          },
          {
            type: "listen-choose",
            audio: "Wir freuen uns auf Ihre Teilnahme.",
            question: "What does it mean?",
            options: ["We look forward to your participation.", "We're pleased you took part.", "Thank you for taking part.", "We're expecting your answer."],
            correctIndex: 0,
            explanation: "\"Sich freuen auf\" + accusative: look forward to. A standard closing line in invitations.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "We'd like to invite you to our party. (polite)",
        answer: "Wir möchten Sie zu unserer Party einladen.",
        altAnswers: ["Wir möchten Sie zu unserem Fest einladen.", "Wir würden Sie gern zu unserer Party einladen.", "Wir möchten Sie zu unserer Feier einladen."],
        explanation: "\"Einladen zu\" + dative: \"zu unserer Party\"; the infinitive goes last after \"möchten\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "Please sign up for the course by Monday.",
        answer: "Bitte melden Sie sich bis Montag für den Kurs an.",
        altAnswers: ["Bitte melden Sie sich bis Montag zum Kurs an.", "Bitte meldet euch bis Montag für den Kurs an.", "Bitte melde dich bis Montag für den Kurs an."],
        explanation: "\"Sich anmelden für\" + accusative (or \"zu\" + dative); \"an\" goes to the end.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "I'd be happy to take part in the festival.",
        answer: "Ich nehme gern am Fest teil.",
        altAnswers: ["Ich nehme gern an dem Fest teil.", "Ich würde gern am Fest teilnehmen.", "Ich würde gern an dem Fest teilnehmen."],
        explanation: "\"Teilnehmen an\" + dative: \"am Fest\"; \"gern\" adds happily.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "Unfortunately I can't come because I'm going to a wedding.",
        answer: "Leider kann ich nicht kommen, weil ich zu einer Hochzeit gehe.",
        altAnswers: ["Leider kann ich nicht kommen, weil ich auf eine Hochzeit gehe.", "Leider kann ich nicht kommen, da ich zu einer Hochzeit gehe."],
        explanation: "Weil-clause with the verb at the end; going to a wedding is \"zu einer Hochzeit\" or \"auf eine Hochzeit\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "We're looking forward to seeing you.",
        answer: "Wir freuen uns auf Sie.",
        altAnswers: ["Wir freuen uns auf dich.", "Wir freuen uns auf euch.", "Wir freuen uns auf Ihren Besuch.", "Wir freuen uns auf deinen Besuch.", "Wir freuen uns auf euren Besuch."],
        explanation: "German says we're looking forward to you: \"sich freuen auf\" + the person.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "Who's responsible for the food?",
        answer: "Wer ist für das Essen zuständig?",
        altAnswers: ["Wer kümmert sich um das Essen?", "Wer ist für das Essen verantwortlich?", "Wer ist zuständig für das Essen?"],
        explanation: "\"Zuständig für\" + accusative, or \"sich kümmern um\" + accusative.",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "Many thanks [for your quick reply].",
        sentence: "Vielen Dank ___.",
        answer: "für Ihre schnelle Antwort",
        altAnswers: ["für deine schnelle Antwort", "für eure schnelle Antwort"],
        explanation: "\"Danke für\" + accusative: \"für Ihre schnelle Antwort\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "I'll [take care of] the dessert.",
        sentence: "Ich ___ mich um den Nachtisch.",
        answer: "kümmere",
        explanation: "\"Sich kümmern um\" + accusative.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "Can I bring my partner too?",
        answer: "Darf ich auch meinen Partner mitbringen?",
        altAnswers: ["Darf ich auch meine Partnerin mitbringen?", "Kann ich auch meinen Partner mitbringen?", "Kann ich auch meine Partnerin mitbringen?"],
        explanation: "\"Mitbringen\" is separable and stays together after a modal.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "Over fifty people have signed up for the festival.",
        answer: "Über fünfzig Leute haben sich für das Fest angemeldet.",
        altAnswers: ["Über fünfzig Personen haben sich für das Fest angemeldet.", "Mehr als fünfzig Leute haben sich für das Fest angemeldet.", "Über fünfzig Leute haben sich zum Fest angemeldet."],
        explanation: "Perfekt of \"sich anmelden für\": \"haben sich ... angemeldet\".",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: We warmly invite you to our summer festival.",
        words: ["Wir", "laden", "Sie", "herzlich", "zu", "unserem", "Sommerfest", "ein."],
        translation: "We warmly invite you to our summer festival.",
        explanation: "\"Einladen zu\" + dative; the prefix \"ein\" at the end.",
      },
      {
        type: "multiple-choice",
        question: "You want to decline politely. What do you write?",
        options: ["Leider kann ich nicht an dem Fest teilnehmen.", "Leider kann ich nicht an das Fest teilnehmen.", "Leider kann ich nicht bei dem Fest teilnehmen.", "Leider kann ich nicht dem Fest teilnehmen."],
        correctIndex: 0,
        explanation: "\"Teilnehmen an\" + dative: \"an dem Fest\".",
      },
      {
        type: "dictation",
        audio: "Vielen Dank für die nette Einladung!",
        explanation: "\"Danke für\" + accusative; \"nette\" with -e after \"die\".",
      },
      {
        type: "speak",
        text: "Ich nehme gern an dem Fest teil.",
        prompt: "Say it in German: I'd be glad to take part in the festival.",
        tip: "\"Teil\": the ei is like English eye.",
        explanation: "\"Teilnehmen an\" + dative.",
      },
    ],
  },
  {
    slug: "b1-verbs-prepositions-extra-5",
    level: "DE-B1",
    number: 5,
    optional: true,
    title: "Extra Practice: Accusative or Dative?",
    summary: "Choose the case after an and auf in fixed verbs: denken an den Urlaub, but teilnehmen an dem Kurs.",
    duration: "12 min",
    sections: [
      {
        heading: "Recap: an and auf in fixed verbs",
        body: [
          "\"Auf\" in fixed verbs is almost always accusative: \"warten auf\", \"sich freuen auf\", \"sich verlassen auf\", \"achten auf\", \"stolz auf\", \"Lust auf\". (The rare dative exception, \"bestehen auf\" + Dat, insist on, you can learn later.)",
          "\"An\" splits: accusative with \"denken an\", \"sich erinnern an\", \"sich gewöhnen an\", \"glauben an\", \"schreiben an\" (write to); dative with \"teilnehmen an\", \"leiden an\", \"zweifeln an\", \"interessiert an\", \"arbeiten an\" (work on).",
        ],
        examples: [
          { es: "Ich denke an den Termin.", en: "I'm remembering the appointment." },
          { es: "Ich nehme an dem Termin teil.", en: "I'm attending the appointment." },
          { es: "Sie schreibt einen Brief an ihren Großvater.", en: "She's writing a letter to her grandfather." },
          { es: "Er arbeitet seit Monaten an seinem Buch.", en: "He's been working on his book for months." },
          { es: "Achte bitte auf den Verkehr!", en: "Please watch out for the traffic!" },
        ],
        checkpoint: [
          {
            type: "fill-blank",
            prompt: "Write the German for the bold words.",
            en: "She's working [on a new project].",
            sentence: "Sie arbeitet ___.",
            answer: "an einem neuen Projekt",
            explanation: "\"Arbeiten an\" + dative: \"an einem neuen Projekt\".",
          },
          {
            type: "fill-blank",
            prompt: "Write the German for the bold words.",
            en: "I still remember [the first kiss].",
            sentence: "Ich erinnere mich noch ___.",
            answer: "an den ersten Kuss",
            explanation: "\"Sich erinnern an\" + accusative: \"an den ersten Kuss\".",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "I'm thinking about the meeting.",
        answer: "Ich denke an die Besprechung.",
        altAnswers: ["Ich denke an das Meeting.", "Ich denke an das Treffen."],
        explanation: "\"Denken an\" + accusative.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "I'm taking part in the meeting.",
        answer: "Ich nehme an der Besprechung teil.",
        altAnswers: ["Ich nehme an dem Meeting teil.", "Ich nehme am Meeting teil.", "Ich nehme an dem Treffen teil.", "Ich nehme am Treffen teil."],
        explanation: "\"Teilnehmen an\" + dative: feminine \"der Besprechung\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "He's got used to the German winter.",
        answer: "Er hat sich an den deutschen Winter gewöhnt.",
        explanation: "\"Sich gewöhnen an\" + accusative: \"an den deutschen Winter\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "My father suffers from asthma.",
        answer: "Mein Vater leidet an Asthma.",
        altAnswers: ["Mein Vater hat Asthma.", "Mein Papa leidet an Asthma."],
        explanation: "\"Leiden an\" + dative for an illness.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "Pay attention to the signs.",
        answer: "Achten Sie auf die Schilder.",
        altAnswers: ["Achte auf die Schilder.", "Achtet auf die Schilder."],
        explanation: "\"Achten auf\" + accusative: pay attention to.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "I wrote an email to the landlord.",
        answer: "Ich habe eine E-Mail an den Vermieter geschrieben.",
        altAnswers: ["Ich habe dem Vermieter eine E-Mail geschrieben.", "Ich schrieb eine E-Mail an den Vermieter.", "Ich habe eine E-Mail an die Vermieterin geschrieben."],
        explanation: "\"Schreiben an\" + accusative, or simply the dative person \"dem Vermieter\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "Nobody doubts her talent.",
        answer: "Niemand zweifelt an ihrem Talent.",
        altAnswers: ["Keiner zweifelt an ihrem Talent."],
        explanation: "\"Zweifeln an\" + dative: \"an ihrem Talent\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "Do you believe [in God]?",
        sentence: "Glaubst du ___?",
        answer: "an Gott",
        explanation: "\"Glauben an\" + accusative; \"Gott\" has no article here.",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "We're waiting [for the result].",
        sentence: "Wir warten ___.",
        answer: "auf das Ergebnis",
        explanation: "\"Warten auf\" + accusative.",
      },
      {
        type: "multiple-choice",
        question: "Which sentence is correct?",
        options: ["Er nimmt am Wettbewerb teil und denkt an den Preis.", "Er nimmt an den Wettbewerb teil und denkt an dem Preis.", "Er nimmt am Wettbewerb teil und denkt an dem Preis.", "Er nimmt an den Wettbewerb teil und denkt an den Preis."],
        correctIndex: 0,
        explanation: "\"Teilnehmen an\" + dative (\"am\"), but \"denken an\" + accusative (\"an den\").",
      },
      {
        type: "multiple-choice",
        question: "Which sentence is correct?",
        options: ["Ich verlasse mich auf meinen Kollegen.", "Ich verlasse mich auf meinem Kollegen.", "Ich verlasse mich an meinen Kollegen.", "Ich verlasse auf meinen Kollegen."],
        correctIndex: 0,
        explanation: "\"Sich verlassen auf\" + accusative: \"meinen Kollegen\".",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: We're working on a solution.",
        words: ["Wir", "arbeiten", "an", "einer", "Lösung."],
        translation: "We're working on a solution.",
        explanation: "\"Arbeiten an\" + dative: \"an einer Lösung\".",
      },
      {
        type: "listen-choose",
        audio: "Ich erinnere mich an den Tag.",
        question: "What did you hear?",
        options: ["Ich erinnere mich an den Tag.", "Ich erinnere mich an dem Tag.", "Ich erinnere mich an die Tage.", "Ich erinnere dich an den Tag."],
        correctIndex: 0,
        explanation: "\"An den Tag\": accusative after \"sich erinnern an\".",
      },
      {
        type: "speak",
        text: "Ich arbeite gerade an einem Projekt.",
        prompt: "Say it in German: I'm working on a project at the moment.",
        tip: "\"Projekt\": the j is like English y, and stress the second syllable.",
        explanation: "\"Arbeiten an\" + dative.",
      },
    ],
  },
  {
    slug: "b1-verbs-prepositions-extra-6",
    level: "DE-B1",
    number: 6,
    optional: true,
    title: "Extra Practice: Dialogue Lab, The Worried Parent",
    summary: "A mother talks to a teacher about her son: sich Sorgen machen um, Angst haben vor, sich kümmern um.",
    duration: "12 min",
    sections: [
      {
        heading: "Recap: talking about worries",
        body: [
          "Frau Becker meets her son's class teacher, Herr Schneider. The key phrases: \"sich Sorgen machen um\" + Akk (with a dative reflexive: \"ich mache mir Sorgen\"), \"Angst haben vor\" + Dat, \"sich kümmern um\" + Akk, \"sich konzentrieren auf\" + Akk, \"sich interessieren für\" + Akk.",
          "They use \"Sie\", so the reflexive for the teacher is \"sich\": \"Machen Sie sich keine Sorgen\".",
        ],
        examples: [
          { es: "Ich mache mir Sorgen um meinen Sohn.", en: "I'm worried about my son." },
          { es: "Er kann sich nicht auf die Hausaufgaben konzentrieren.", en: "He can't concentrate on his homework." },
          { es: "Er hat Angst vor der Mathearbeit.", en: "He's scared of the maths test." },
          { es: "Machen Sie sich keine Sorgen, wir kümmern uns um ihn.", en: "Don't worry, we'll look after him." },
          { es: "Er interessiert sich sehr für Biologie.", en: "He's very interested in biology." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "Don't worry. (polite)",
            answer: "Machen Sie sich keine Sorgen.",
            explanation: "Polite imperative: verb first, \"Sie\", then the reflexive \"sich\".",
          },
          {
            type: "listen-choose",
            audio: "Er hat Angst vor der Mathearbeit.",
            question: "What does it mean?",
            options: ["He's scared of the maths test.", "He's working on his maths homework.", "He's annoyed about the maths test.", "He's looking forward to the maths test."],
            correctIndex: 0,
            explanation: "\"Angst haben vor\" + dative: be afraid of.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "I'm worried about my daughter.",
        answer: "Ich mache mir Sorgen um meine Tochter.",
        explanation: "\"Sich Sorgen machen um\" + accusative, with dative \"mir\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "She can't concentrate on school.",
        answer: "Sie kann sich nicht auf die Schule konzentrieren.",
        explanation: "\"Sich konzentrieren auf\" + accusative; the infinitive at the end after \"kann\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "He's afraid of the other children.",
        answer: "Er hat Angst vor den anderen Kindern.",
        explanation: "\"Angst haben vor\" + dative plural: \"den anderen Kindern\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "I'll talk to the other teachers.",
        answer: "Ich spreche mit den anderen Lehrern.",
        altAnswers: ["Ich werde mit den anderen Lehrern sprechen.", "Ich rede mit den anderen Lehrern.", "Ich spreche mit den anderen Lehrerinnen und Lehrern."],
        explanation: "\"Sprechen mit\" + dative plural: \"den anderen Lehrern\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "Has he complained about a classmate?",
        answer: "Hat er sich über einen Mitschüler beschwert?",
        altAnswers: ["Hat er sich über eine Mitschülerin beschwert?"],
        explanation: "\"Sich beschweren über\" + accusative: \"einen Mitschüler\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "We'll take care of your son.",
        answer: "Wir kümmern uns um Ihren Sohn.",
        altAnswers: ["Wir werden uns um Ihren Sohn kümmern.", "Wir kümmern uns um deinen Sohn."],
        explanation: "\"Sich kümmern um\" + accusative: \"Ihren Sohn\" (polite your).",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "He's interested [in animals].",
        sentence: "Er interessiert sich ___.",
        answer: "für Tiere",
        explanation: "\"Sich interessieren für\" + accusative plural.",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "I'm proud [of him], but I'm worried.",
        sentence: "Ich bin stolz ___, aber ich mache mir Sorgen.",
        answer: "auf ihn",
        explanation: "\"Stolz auf\" + accusative: \"auf ihn\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "Thank you for your time, Mr Schneider.",
        answer: "Vielen Dank für Ihre Zeit, Herr Schneider.",
        altAnswers: ["Danke für Ihre Zeit, Herr Schneider."],
        explanation: "\"Danke für\" + accusative.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "I wish he were more interested in maths.",
        answer: "Ich wünschte, er würde sich mehr für Mathe interessieren.",
        altAnswers: ["Ich wünschte, er würde sich mehr für Mathematik interessieren.", "Ich wünschte, er interessierte sich mehr für Mathe."],
        explanation: "Konjunktiv II wish: \"würde ... interessieren\" with \"sich\" and \"für Mathe\".",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: Don't worry about him.",
        words: ["Machen", "Sie", "sich", "keine", "Sorgen", "um", "ihn."],
        translation: "Don't worry about him.",
        explanation: "Polite imperative: \"Machen Sie sich\"; \"um ihn\" in the accusative.",
      },
      {
        type: "multiple-choice",
        question: "Which sentence means: I'm worried about him?",
        options: ["Ich mache mir Sorgen um ihn.", "Ich mache mich Sorgen um ihn.", "Ich mache mir Sorgen um ihm.", "Ich mache mir Sorgen für ihn."],
        correctIndex: 0,
        explanation: "Dative reflexive \"mir\" (\"Sorgen\" is the object) and \"um\" + accusative \"ihn\".",
      },
      {
        type: "dictation",
        audio: "Ich mache mir Sorgen um meinen Sohn.",
        explanation: "\"Sich Sorgen machen um\" + accusative: \"meinen Sohn\".",
      },
      {
        type: "speak",
        text: "Machen Sie sich keine Sorgen.",
        prompt: "Say it in German: Don't worry. (polite)",
        tip: "\"Sorgen\": voiced s, like z.",
        explanation: "The polite imperative of \"sich Sorgen machen\".",
      },
    ],
  },
  {
    slug: "b1-verbs-prepositions-extra-7",
    level: "DE-B1",
    number: 7,
    optional: true,
    title: "Extra Practice: Twelve Verbs Without Hints",
    summary: "Recall the preposition and case for twelve frequent verbs with no hints.",
    duration: "12 min",
    sections: [
      {
        heading: "Recap: the twelve",
        body: [
          "The twelve verbs in this practice: \"warten auf\" (A), \"denken an\" (A), \"sich freuen auf\" (A), \"sich interessieren für\" (A), \"sich kümmern um\" (A), \"sich ärgern über\" (A), \"teilnehmen an\" (D), \"Angst haben vor\" (D), \"träumen von\" (D), \"abhängen von\" (D), \"helfen bei\" (D), \"sprechen mit\" (D).",
          "Say each one aloud with an example before you start; then cover this list and translate.",
        ],
        examples: [
          { es: "Ich warte auf den Zug.", en: "I'm waiting for the train." },
          { es: "Sie träumt von einer Weltreise.", en: "She dreams of a trip around the world." },
          { es: "Er spricht mit dem Chef.", en: "He's speaking to the boss." },
          { es: "Wir kümmern uns um den Garten.", en: "We look after the garden." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "It depends on the weather.",
            answer: "Es hängt vom Wetter ab.",
            altAnswers: ["Das hängt vom Wetter ab.", "Es hängt von dem Wetter ab."],
            explanation: "\"Abhängen von\" + dative.",
          },
          {
            type: "speak",
            text: "Ich interessiere mich für Fußball.",
            prompt: "Say it in German: I'm interested in football.",
            tip: "\"Fußball\": long u before ß.",
            explanation: "\"Sich interessieren für\" + accusative.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "We're waiting for the taxi.",
        answer: "Wir warten auf das Taxi.",
        explanation: "\"Warten auf\" + accusative.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "I often think of my grandfather.",
        answer: "Ich denke oft an meinen Großvater.",
        altAnswers: ["Ich denke oft an meinen Opa."],
        explanation: "\"Denken an\" + accusative.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "The kids are looking forward to the snow.",
        answer: "Die Kinder freuen sich auf den Schnee.",
        explanation: "\"Sich freuen auf\" + accusative: \"den Schnee\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "My brother is interested in cars.",
        answer: "Mein Bruder interessiert sich für Autos.",
        explanation: "\"Sich interessieren für\" + accusative.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "Who's looking after the children tonight?",
        answer: "Wer kümmert sich heute Abend um die Kinder?",
        altAnswers: ["Wer kümmert sich heute Abend um die Kids?"],
        explanation: "\"Sich kümmern um\" + accusative; time before the prepositional phrase.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "She's annoyed about the bad weather.",
        answer: "Sie ärgert sich über das schlechte Wetter.",
        explanation: "\"Sich ärgern über\" + accusative.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "Are you taking part in the trip? (to a friend)",
        answer: "Nimmst du an der Reise teil?",
        altAnswers: ["Nehmt ihr an der Reise teil?", "Nimmst du am Ausflug teil?", "Nehmt ihr am Ausflug teil?"],
        explanation: "\"Teilnehmen an\" + dative.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "I'm afraid of the exam.",
        answer: "Ich habe Angst vor der Prüfung.",
        explanation: "\"Angst haben vor\" + dative.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "He dreams of a quiet life in the country.",
        answer: "Er träumt von einem ruhigen Leben auf dem Land.",
        explanation: "\"Träumen von\" + dative: \"von einem ruhigen Leben\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "My colleague helped me with the presentation.",
        answer: "Mein Kollege hat mir bei der Präsentation geholfen.",
        altAnswers: ["Meine Kollegin hat mir bei der Präsentation geholfen.", "Mein Kollege half mir bei der Präsentation."],
        explanation: "\"Helfen\" + dative person + \"bei\" + dative thing.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "I need to speak to the doctor.",
        answer: "Ich muss mit dem Arzt sprechen.",
        altAnswers: ["Ich muss mit der Ärztin sprechen.", "Ich muss mit dem Arzt reden."],
        explanation: "\"Sprechen mit\" + dative.",
      },
      {
        type: "multiple-choice",
        question: "Which sentence is correct?",
        options: ["Das hängt von dir ab.", "Das hängt auf dich ab.", "Das hängt von dich ab.", "Das hängt an dir ab."],
        correctIndex: 0,
        explanation: "\"Abhängen von\" + dative: \"von dir\".",
      },
      {
        type: "matching",
        instructions: "Match the German to the English.",
        pairs: [
          { left: "sich kümmern um", right: "look after" },
          { left: "sich ärgern über", right: "be annoyed about" },
          { left: "träumen von", right: "dream of" },
          { left: "Angst haben vor", right: "be afraid of" },
        ],
        explanation: "Two accusative blocks (um, über) and two dative ones (von, vor).",
      },
      {
        type: "listen-choose",
        audio: "Wir kümmern uns um den Garten.",
        question: "What does it mean?",
        options: ["We look after the garden.", "We're worried about the garden.", "We're annoyed about the garden.", "We're talking about the garden."],
        correctIndex: 0,
        explanation: "\"Sich kümmern um\": look after, take care of.",
      },
      {
        type: "speak",
        text: "Ich träume von einem Haus am Meer.",
        prompt: "Say it in German: I dream of a house by the sea.",
        tip: "\"Träume\": äu sounds like oy.",
        explanation: "\"Träumen von\" + dative.",
      },
    ],
  },
  {
    slug: "b1-verbs-prepositions-extra-8",
    level: "DE-B1",
    number: 8,
    optional: true,
    title: "Extra Practice: Sich freuen auf, über, Sich ärgern über",
    summary: "Meaning pairs in context: looking forward to, pleased about, annoyed about.",
    duration: "12 min",
    sections: [
      {
        heading: "Recap: reacting and anticipating",
        body: [
          "\"Sich freuen auf\" + Akk: looking forward to something to come. \"Sich freuen über\" + Akk: pleased about something that has happened or is here. \"Sich ärgern über\" + Akk: the opposite reaction, annoyed about. \"Sich freuen für\" + Akk: happy for someone.",
          "All four take the accusative, so the only decision is the preposition, and it depends on time and meaning.",
        ],
        examples: [
          { es: "Ich freue mich auf die Hochzeit meiner Schwester.", en: "I'm looking forward to my sister's wedding." },
          { es: "Sie freut sich über das gute Zeugnis.", en: "She's pleased with her good school report." },
          { es: "Er ärgert sich über den Strafzettel.", en: "He's annoyed about the parking ticket." },
          { es: "Wir freuen uns für euch!", en: "We're happy for you!" },
          { es: "Ich habe mich über den Stau geärgert.", en: "The traffic jam annoyed me." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "I'm pleased about the good weather.",
            answer: "Ich freue mich über das gute Wetter.",
            explanation: "The weather is here now: \"sich freuen über\".",
          },
          {
            type: "listen-choose",
            audio: "Er ärgert sich über den Strafzettel.",
            question: "What does it mean?",
            options: ["He's annoyed about the parking ticket.", "He's pleased about the parking ticket.", "He's waiting for the parking ticket.", "He's paying the parking ticket."],
            correctIndex: 0,
            explanation: "\"Sich ärgern über\": be annoyed about.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "I'm looking forward to my birthday.",
        answer: "Ich freue mich auf meinen Geburtstag.",
        explanation: "Future: \"auf\" + accusative \"meinen Geburtstag\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "I was pleased about the birthday presents.",
        answer: "Ich habe mich über die Geburtstagsgeschenke gefreut.",
        altAnswers: ["Ich freute mich über die Geburtstagsgeschenke."],
        explanation: "Already received: \"über\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "She was annoyed about the delay.",
        answer: "Sie hat sich über die Verspätung geärgert.",
        altAnswers: ["Sie ärgerte sich über die Verspätung."],
        explanation: "\"Sich ärgern über\" + accusative.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "We're looking forward to the summer holidays.",
        answer: "Wir freuen uns auf die Sommerferien.",
        explanation: "Future: \"auf die Sommerferien\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "My parents are happy for me.",
        answer: "Meine Eltern freuen sich für mich.",
        explanation: "\"Sich freuen für\" + accusative: happy for someone.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "Don't get annoyed! (to a friend)",
        answer: "Ärger dich nicht!",
        altAnswers: ["Ärgere dich nicht!", "Ärgert euch nicht!", "Ärger dich nicht darüber!", "Ärgere dich nicht darüber!"],
        explanation: "Imperative of the reflexive verb: \"Ärger(e) dich nicht!\"",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "He was very [pleased about] the compliment.",
        sentence: "Er hat sich sehr ___ das Kompliment gefreut.",
        answer: "über",
        explanation: "He's already received it: \"über\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "We're already [looking forward to] the weekend.",
        sentence: "Wir freuen uns schon ___ das Wochenende.",
        answer: "auf",
        explanation: "\"Schon\" + future: \"auf\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "I'm annoyed with myself.",
        answer: "Ich ärgere mich über mich selbst.",
        explanation: "\"Sich ärgern über\" + accusative: \"über mich selbst\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "The grandparents were delighted with the photos.",
        answer: "Die Großeltern haben sich über die Fotos gefreut.",
        altAnswers: ["Die Großeltern freuten sich über die Fotos.", "Die Großeltern haben sich sehr über die Fotos gefreut.", "Die Großeltern haben sich riesig über die Fotos gefreut."],
        explanation: "Reaction to photos received: \"sich freuen über\".",
      },
      {
        type: "multiple-choice",
        question: "Your friend's baby was born yesterday. What do you write?",
        options: ["Wir freuen uns so für euch!", "Wir freuen uns so auf euch!", "Wir ärgern uns so für euch!", "Wir freuen uns so an euch!"],
        correctIndex: 0,
        explanation: "Happy for someone: \"sich freuen für\".",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: I'm looking forward to the holiday.",
        words: ["Ich", "freue", "mich", "auf", "den", "Urlaub."],
        translation: "I'm looking forward to the holiday.",
        explanation: "\"Auf den Urlaub\": masculine accusative.",
      },
      {
        type: "dictation",
        audio: "Sie freut sich über das Geschenk.",
        explanation: "\"Über das Geschenk\": she has the present.",
      },
      {
        type: "speak",
        text: "Ich habe mich über den Stau geärgert.",
        prompt: "Say it in German: The traffic jam annoyed me.",
        tip: "\"Stau\": st = sht, au like ow in cow.",
        explanation: "German makes the person the subject: \"Ich habe mich ... geärgert\".",
      },
    ],
  },
  {
    slug: "b1-verbs-prepositions-extra-9",
    level: "DE-B1",
    number: 9,
    optional: true,
    title: "Extra Practice: What Are You Interested In?",
    summary: "Talk about you: your interests, fears and dreams with prepositional verbs.",
    duration: "12 min",
    sections: [
      {
        heading: "Recap: talking about yourself",
        body: [
          "Interests: \"Ich interessiere mich für...\", \"Ich beschäftige mich gern mit...\", \"Ich bin begeistert von...\". Fears: \"Ich habe Angst vor...\". Dreams: \"Ich träume von...\". Plans: \"Ich freue mich auf...\".",
          "Use them with nouns (\"für Musik\") or nominalised verbs (\"vor dem Fliegen\", \"vom Reisen\").",
        ],
        examples: [
          { es: "Ich interessiere mich vor allem für Geschichte.", en: "I'm mainly interested in history." },
          { es: "In meiner Freizeit beschäftige ich mich mit Fotografie.", en: "In my free time I do photography." },
          { es: "Ich habe Angst vor Spinnen und vor dem Zahnarzt.", en: "I'm scared of spiders and of the dentist." },
          { es: "Ich träume von einem Jahr in Australien.", en: "I dream of a year in Australia." },
          { es: "Ich bin total begeistert vom Klettern.", en: "I'm totally into climbing." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "I'm mainly interested in music.",
            answer: "Ich interessiere mich vor allem für Musik.",
            altAnswers: ["Ich interessiere mich hauptsächlich für Musik."],
            explanation: "\"Vor allem\" (mainly) goes before \"für Musik\".",
          },
          {
            type: "speak",
            text: "Ich träume von einem Jahr in Australien.",
            prompt: "Say it in German: I dream of a year in Australia.",
            tip: "\"Australien\": au like ow, stress on -STRA-.",
            explanation: "\"Träumen von\" + dative.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "I'm interested in languages and literature.",
        answer: "Ich interessiere mich für Sprachen und Literatur.",
        explanation: "\"Sich interessieren für\" + accusative, no articles for general subjects.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "I'm scared of heights.",
        answer: "Ich habe Höhenangst.",
        altAnswers: ["Ich habe Angst vor der Höhe.", "Ich habe Angst vor großen Höhen."],
        explanation: "German has the compound \"Höhenangst\"; \"Angst vor\" + dative also works.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "I dream of a house with a garden.",
        answer: "Ich träume von einem Haus mit Garten.",
        altAnswers: ["Ich träume von einem Haus mit einem Garten."],
        explanation: "\"Träumen von\" + dative.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "In my free time I'm into cooking.",
        answer: "In meiner Freizeit beschäftige ich mich mit Kochen.",
        altAnswers: ["In meiner Freizeit beschäftige ich mich mit dem Kochen.", "In meiner Freizeit koche ich gern."],
        explanation: "\"Sich beschäftigen mit\" + dative; with \"In meiner Freizeit\" first, the verb comes second.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "I'm looking forward to my holiday in Italy.",
        answer: "Ich freue mich auf meinen Urlaub in Italien.",
        explanation: "\"Sich freuen auf\" + accusative.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "I'm not interested in football at all.",
        answer: "Ich interessiere mich überhaupt nicht für Fußball.",
        altAnswers: ["Ich interessiere mich gar nicht für Fußball.", "Fußball interessiert mich überhaupt nicht.", "Fußball interessiert mich gar nicht."],
        explanation: "\"Überhaupt nicht\" goes before the prepositional phrase.",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "I'm really [keen on] hiking.",
        sentence: "Ich bin total ___ Wandern begeistert.",
        answer: "vom",
        altAnswers: ["von dem"],
        explanation: "\"Begeistert von\" + dative: \"vom Wandern\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "As a child I was afraid [of the dark].",
        sentence: "Als Kind hatte ich Angst ___.",
        answer: "vor der Dunkelheit",
        altAnswers: ["im Dunkeln"],
        explanation: "\"Angst haben vor\" + dative; \"hatte\" because of \"als Kind\" (past).",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "When I was young, I dreamed of a career as a pilot.",
        answer: "Als ich jung war, träumte ich von einer Karriere als Pilot.",
        altAnswers: ["Als ich jung war, habe ich von einer Karriere als Pilot geträumt.", "Als ich jung war, träumte ich von einer Karriere als Pilotin.", "Als ich jung war, habe ich von einer Karriere als Pilotin geträumt."],
        explanation: "Als-clause for a single past period, then the main clause starts with its verb; \"träumen von\" + dative: \"von einer Karriere\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "What I'm most interested in is art.",
        answer: "Am meisten interessiere ich mich für Kunst.",
        altAnswers: ["Ich interessiere mich am meisten für Kunst."],
        explanation: "\"Am meisten\" (most of all) at the front, then the verb second.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: I'm scared of spiders.",
        words: ["Ich", "habe", "Angst", "vor", "Spinnen."],
        translation: "I'm scared of spiders.",
        explanation: "\"Angst haben vor\" + dative plural.",
      },
      {
        type: "multiple-choice",
        question: "Which sentence is correct?",
        options: ["Ich beschäftige mich mit der Fotografie.", "Ich beschäftige mich mit die Fotografie.", "Ich beschäftige mich für die Fotografie.", "Ich beschäftige mit der Fotografie."],
        correctIndex: 0,
        explanation: "\"Sich beschäftigen mit\" + dative, reflexive.",
      },
      {
        type: "listen-choose",
        audio: "Ich interessiere mich vor allem für Geschichte.",
        question: "What does it mean?",
        options: ["I'm mainly interested in history.", "I'm interested in stories before bedtime.", "I'm not interested in history.", "I used to be interested in history."],
        correctIndex: 0,
        explanation: "\"Vor allem\" means above all, mainly; \"Geschichte\" is history (or story).",
      },
      {
        type: "speak",
        text: "Ich interessiere mich für Fotografie.",
        prompt: "Say it in German: I'm interested in photography.",
        tip: "\"Fotografie\": stress the last syllable, -FIE.",
        explanation: "\"Sich interessieren für\" + accusative.",
      },
    ],
  },
  {
    slug: "b1-verbs-prepositions-extra-10",
    level: "DE-B1",
    number: 10,
    optional: true,
    title: "Extra Practice: Fix the Paragraph, English Prepositions",
    summary: "Correct a text full of calques from English: *warten für, *abhängen auf, *Angst von.",
    duration: "12 min",
    sections: [
      {
        heading: "Recap: the calques to avoid",
        body: [
          "Jonas wrote this about his job search, translating every preposition from English: *Ich warte für eine Antwort. Es hängt auf der Firma ab. Ich habe Angst von dem Interview. Ich suche für eine neue Stelle. Ich bin stolz von meinem Lebenslauf.*",
          "Corrected: \"Ich warte auf eine Antwort. Es hängt von der Firma ab. Ich habe Angst vor dem Interview. Ich suche eine neue Stelle. Ich bin stolz auf meinen Lebenslauf.\" Every one of his mistakes came from English for, on, of.",
        ],
        examples: [
          { es: "Ich warte auf eine Antwort.", en: "I'm waiting for an answer." },
          { es: "Es hängt von der Firma ab.", en: "It depends on the company." },
          { es: "Ich habe Angst vor dem Interview.", en: "I'm afraid of the interview." },
          { es: "Ich suche eine neue Stelle.", en: "I'm looking for a new job." },
          { es: "Ich bin stolz auf meinen Lebenslauf.", en: "I'm proud of my CV." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "I'm waiting for an answer.",
            answer: "Ich warte auf eine Antwort.",
            explanation: "*warten für* is the calque; German says \"warten auf\" + accusative.",
          },
          {
            type: "listen-choose",
            audio: "Es hängt von der Firma ab.",
            question: "What did you hear?",
            options: ["Es hängt von der Firma ab.", "Es hängt auf der Firma ab.", "Es hängt an der Firma.", "Es hängt von die Firma ab."],
            correctIndex: 0,
            explanation: "\"Abhängen von\" + dative: \"von der Firma\".",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Fix this sentence: *Wir warten für den Bus.* Write the correct German for: We're waiting for the bus.",
        source: "We're waiting for the bus.",
        answer: "Wir warten auf den Bus.",
        explanation: "\"Warten auf\" + accusative, never \"für\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Fix this sentence: *Das hängt auf dem Preis ab.* Write the correct German for: That depends on the price.",
        source: "That depends on the price.",
        answer: "Das hängt vom Preis ab.",
        altAnswers: ["Das hängt von dem Preis ab.", "Es hängt vom Preis ab."],
        explanation: "\"Abhängen von\" + dative; English on misleads.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Fix this sentence: *Sie hat Angst von Hunden.* Write the correct German for: She's afraid of dogs.",
        source: "She's afraid of dogs.",
        answer: "Sie hat Angst vor Hunden.",
        explanation: "\"Angst haben vor\" + dative, not \"von\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Fix this sentence: *Ich suche für meine Brille.* Write the correct German for: I'm looking for my glasses.",
        source: "I'm looking for my glasses.",
        answer: "Ich suche meine Brille.",
        altAnswers: ["Ich suche nach meiner Brille."],
        explanation: "\"Suchen\" + accusative with no preposition.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Fix this sentence: *Er ist stolz von seiner Tochter.* Write the correct German for: He's proud of his daughter.",
        source: "He's proud of his daughter.",
        answer: "Er ist stolz auf seine Tochter.",
        explanation: "\"Stolz auf\" + accusative: \"auf seine Tochter\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Fix this sentence: *Das Team besteht von acht Personen.* Write the correct German for: The team consists of eight people.",
        source: "The team consists of eight people.",
        answer: "Das Team besteht aus acht Personen.",
        altAnswers: ["Das Team besteht aus acht Leuten."],
        explanation: "\"Bestehen aus\" + dative.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Fix this sentence: *Ich bin verheiratet zu einem Arzt.* Write the correct German for: I'm married to a doctor.",
        source: "I'm married to a doctor.",
        answer: "Ich bin mit einem Arzt verheiratet.",
        altAnswers: ["Ich bin mit einer Ärztin verheiratet.", "Ich bin verheiratet mit einem Arzt.", "Ich bin verheiratet mit einer Ärztin."],
        explanation: "\"Verheiratet mit\" + dative.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Fix this sentence: *Ich höre zu der Musik.* Write the correct German for: I'm listening to the music.",
        source: "I'm listening to the music.",
        answer: "Ich höre die Musik.",
        altAnswers: ["Ich höre Musik.", "Ich höre der Musik zu."],
        explanation: "\"Hören\" + accusative, or \"zuhören\" + dative; never \"zu\" as a preposition here.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Fix this sentence: *Er hat für Hilfe gefragt.* Write the correct German for: He asked for help.",
        source: "He asked for help.",
        answer: "Er hat um Hilfe gebeten.",
        altAnswers: ["Er bat um Hilfe."],
        explanation: "Ask for is \"bitten um\" + accusative.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Fix this sentence: *Ich denke von dir.* Write the correct German for: I'm thinking of you.",
        source: "I'm thinking of you.",
        answer: "Ich denke an dich.",
        altAnswers: ["Ich denke an euch.", "Ich denke an Sie."],
        explanation: "\"Denken an\" + accusative.",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "She concentrates [on her work].",
        sentence: "Sie konzentriert sich ___.",
        answer: "auf ihre Arbeit",
        explanation: "\"Sich konzentrieren auf\" + accusative; English on happens to match \"auf\" here.",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "We congratulated her [on her birthday].",
        sentence: "Wir haben ihr ___ gratuliert.",
        answer: "zum Geburtstag",
        explanation: "\"Gratulieren zu\" + dative, not \"auf\".",
      },
      {
        type: "multiple-choice",
        question: "Which sentence has no mistake?",
        options: ["Ich interessiere mich für Politik.", "Ich interessiere mich in Politik.", "Ich bin interessiert in Politik.", "Ich interessiere in Politik."],
        correctIndex: 0,
        explanation: "\"Sich interessieren für\" or \"interessiert an\"; never \"in\".",
      },
      {
        type: "speak",
        text: "Ich habe Angst vor dem Interview.",
        prompt: "Say it in German: I'm afraid of the interview.",
        tip: "\"Vor\": the v is pronounced like f.",
        explanation: "\"Angst haben vor\" + dative.",
      },
    ],
  },
  {
    slug: "b1-verbs-prepositions-extra-11",
    level: "DE-B1",
    number: 11,
    optional: true,
    title: "Extra Practice: Stolz auf, Zufrieden mit",
    summary: "Adjectives with prepositions: stolz auf, zufrieden mit, gespannt auf, enttäuscht von and more.",
    duration: "12 min",
    sections: [
      {
        heading: "Recap: adjective + preposition",
        body: [
          "The adjective and its preposition belong together just like a verb and its preposition: \"stolz auf\" + A, \"gespannt auf\" + A, \"böse auf\" + A, \"froh über\" + A, \"verliebt in\" + A; \"zufrieden mit\" + D, \"fertig mit\" + D, \"einverstanden mit\" + D (agree with), \"enttäuscht von\" + D, \"überzeugt von\" + D (convinced of), \"bekannt für\" + A (known for).",
          "Usual order: prepositional phrase first, adjective last: \"Ich bin mit dem Vorschlag einverstanden\".",
        ],
        examples: [
          { es: "Ich bin mit dem Vorschlag einverstanden.", en: "I agree with the proposal." },
          { es: "Leipzig ist bekannt für seine Musikgeschichte.", en: "Leipzig is known for its musical history." },
          { es: "Wir sind von der Idee überzeugt.", en: "We're convinced by the idea." },
          { es: "Die Kinder sind gespannt auf die Geschenke.", en: "The kids can't wait to see the presents." },
          { es: "Bist du böse auf mich?", en: "Are you angry with me?" },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "I agree with your plan. (to a friend)",
            answer: "Ich bin mit deinem Plan einverstanden.",
            altAnswers: ["Ich bin mit eurem Plan einverstanden.", "Ich bin einverstanden mit deinem Plan."],
            explanation: "\"Einverstanden mit\" + dative: \"mit deinem Plan\".",
          },
          {
            type: "speak",
            text: "Bist du böse auf mich?",
            prompt: "Say it in German: Are you angry with me?",
            tip: "\"Böse\": long ö, and the s is voiced.",
            explanation: "\"Böse auf\" + accusative.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "We're proud of our team.",
        answer: "Wir sind stolz auf unser Team.",
        altAnswers: ["Wir sind stolz auf unsere Mannschaft."],
        explanation: "\"Stolz auf\" + accusative.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "Is the boss satisfied with the result?",
        answer: "Ist der Chef mit dem Ergebnis zufrieden?",
        altAnswers: ["Ist die Chefin mit dem Ergebnis zufrieden?", "Ist der Chef zufrieden mit dem Ergebnis?"],
        explanation: "\"Zufrieden mit\" + dative.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "Munich is known for its beer gardens.",
        answer: "München ist bekannt für seine Biergärten.",
        altAnswers: ["München ist für seine Biergärten bekannt."],
        explanation: "\"Bekannt für\" + accusative.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "I'm disappointed with the film.",
        answer: "Ich bin von dem Film enttäuscht.",
        altAnswers: ["Ich bin vom Film enttäuscht.", "Ich bin enttäuscht von dem Film.", "Ich bin enttäuscht vom Film."],
        explanation: "\"Enttäuscht von\" + dative.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "Have you finished the book?",
        answer: "Bist du mit dem Buch fertig?",
        altAnswers: ["Seid ihr mit dem Buch fertig?", "Sind Sie mit dem Buch fertig?", "Bist du fertig mit dem Buch?"],
        explanation: "\"Fertig sein mit\" + dative: German uses sein, not haben.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "She's angry with her brother.",
        answer: "Sie ist böse auf ihren Bruder.",
        altAnswers: ["Sie ist sauer auf ihren Bruder.", "Sie ist wütend auf ihren Bruder."],
        explanation: "\"Böse / sauer / wütend auf\" + accusative.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "We're convinced of his innocence.",
        answer: "Wir sind von seiner Unschuld überzeugt.",
        altAnswers: ["Wir sind überzeugt von seiner Unschuld."],
        explanation: "\"Überzeugt von\" + dative.",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "I'm glad [about the good news].",
        sentence: "Ich bin froh ___.",
        answer: "über die guten Nachrichten",
        altAnswers: ["über die gute Nachricht"],
        explanation: "\"Froh über\" + accusative.",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "We can't wait [for the new season].",
        sentence: "Wir sind gespannt ___.",
        answer: "auf die neue Staffel",
        altAnswers: ["auf die neue Saison"],
        explanation: "\"Gespannt auf\" + accusative.",
      },
      {
        type: "multiple-choice",
        question: "Which sentence is correct?",
        options: ["Ich bin mit der Arbeit fertig.", "Ich habe mit der Arbeit fertig.", "Ich bin mit die Arbeit fertig.", "Ich bin von der Arbeit fertig."],
        correctIndex: 0,
        explanation: "\"Fertig sein mit\" + dative.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: My parents are proud of me.",
        words: ["Meine", "Eltern", "sind", "stolz", "auf", "mich."],
        translation: "My parents are proud of me.",
        explanation: "\"Stolz auf\" + accusative pronoun.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "He's in love with a woman from Hamburg.",
        answer: "Er ist in eine Frau aus Hamburg verliebt.",
        altAnswers: ["Er ist verliebt in eine Frau aus Hamburg.", "Er ist in eine Hamburgerin verliebt."],
        explanation: "\"Verliebt in\" + accusative.",
      },
      {
        type: "listen-choose",
        audio: "Wir sind mit dem Hotel sehr zufrieden.",
        question: "What does it mean?",
        options: ["We're very happy with the hotel.", "We're very disappointed with the hotel.", "We're very proud of the hotel.", "We've finished with the hotel."],
        correctIndex: 0,
        explanation: "\"Zufrieden mit\": satisfied with.",
      },
      {
        type: "speak",
        text: "Ich bin mit dem Vorschlag einverstanden.",
        prompt: "Say it in German: I agree with the proposal.",
        tip: "\"Einverstanden\": stress the first syllable, EIN-.",
        explanation: "\"Einverstanden mit\" + dative.",
      },
    ],
  },
  {
    slug: "b1-verbs-prepositions-extra-12",
    level: "DE-B1",
    number: 12,
    optional: true,
    title: "Extra Practice: Dictation, A Letter of Thanks",
    summary: "A dictated thank-you letter with sich bedanken für and danken für.",
    duration: "12 min",
    sections: [
      {
        heading: "Recap: saying thank you",
        body: [
          "Three ways to thank someone: \"danken\" + Dat person + \"für\" + Akk (\"Ich danke Ihnen für die Hilfe\"), \"sich bedanken bei\" + Dat person + \"für\" + Akk (\"Ich bedanke mich bei Ihnen für die Hilfe\"), and \"Danke für\" / \"Vielen Dank für\" + Akk.",
          "A thank-you letter often adds \"sich freuen über\": \"Wir haben uns sehr über das Geschenk gefreut\".",
        ],
        examples: [
          { es: "Liebe Frau Schneider, vielen Dank für Ihre Hilfe.", en: "Dear Mrs Schneider, many thanks for your help." },
          { es: "Wir haben uns sehr über die Blumen gefreut.", en: "We were very pleased with the flowers." },
          { es: "Ich möchte mich bei Ihnen für alles bedanken.", en: "I'd like to thank you for everything." },
          { es: "Ich danke dir für deine Geduld.", en: "Thank you for your patience." },
          { es: "Wir freuen uns schon auf Ihren nächsten Besuch.", en: "We're already looking forward to your next visit." },
        ],
        checkpoint: [
          {
            type: "dictation",
            audio: "Vielen Dank für Ihre Hilfe.",
            explanation: "\"Danke für\" + accusative; \"Ihre\" with a capital I is polite your.",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "Thank you for your patience. (to a friend)",
            answer: "Ich danke dir für deine Geduld.",
            altAnswers: ["Danke für deine Geduld.", "Vielen Dank für deine Geduld.", "Ich danke euch für eure Geduld."],
            explanation: "\"Danken\" + dative person + \"für\" + accusative.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "dictation",
        audio: "Wir haben uns sehr über die Blumen gefreut.",
        explanation: "\"Sich freuen über\" in the Perfekt.",
      },
      {
        type: "dictation",
        audio: "Ich möchte mich bei Ihnen bedanken.",
        explanation: "\"Sich bedanken bei\" + dative: \"bei Ihnen\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "Thanks for the lovely time in Cologne.",
        answer: "Danke für die schöne Zeit in Köln.",
        altAnswers: ["Vielen Dank für die schöne Zeit in Köln.", "Danke für die tolle Zeit in Köln."],
        explanation: "\"Danke für\" + accusative; \"Köln\" with ö.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "Many thanks for the lovely evening.",
        answer: "Vielen Dank für den schönen Abend.",
        altAnswers: ["Vielen Dank für den netten Abend.", "Danke für den schönen Abend."],
        explanation: "\"Für\" + accusative: masculine \"den schönen Abend\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "I'd like to thank you for the invitation. (polite)",
        answer: "Ich möchte mich bei Ihnen für die Einladung bedanken.",
        altAnswers: ["Ich möchte Ihnen für die Einladung danken.", "Ich bedanke mich bei Ihnen für die Einladung."],
        explanation: "\"Sich bedanken bei\" + Dat + \"für\" + Akk.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "We thank all the helpers.",
        answer: "Wir danken allen Helfern.",
        altAnswers: ["Wir bedanken uns bei allen Helfern.", "Wir danken allen Helferinnen und Helfern."],
        explanation: "\"Danken\" + dative plural: \"allen Helfern\" with -n.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "The children were thrilled with the books.",
        answer: "Die Kinder haben sich über die Bücher gefreut.",
        altAnswers: ["Die Kinder freuten sich über die Bücher.", "Die Kinder waren von den Büchern begeistert.", "Die Kinder haben sich riesig über die Bücher gefreut."],
        explanation: "\"Sich freuen über\" + accusative, or \"begeistert von\" + dative.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "We're looking forward to seeing you again.",
        answer: "Wir freuen uns auf ein Wiedersehen.",
        altAnswers: ["Wir freuen uns auf das Wiedersehen.", "Wir freuen uns aufs Wiedersehen.", "Wir freuen uns auf ein Wiedersehen mit Ihnen.", "Wir freuen uns auf ein Wiedersehen mit dir.", "Wir freuen uns auf ein Wiedersehen mit euch."],
        explanation: "\"Sich freuen auf\" + accusative; \"das Wiedersehen\" is the noun for meeting again.",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "Thank you [for everything]!",
        sentence: "Danke ___!",
        answer: "für alles",
        explanation: "\"Danke für\" + accusative.",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "I thanked [the neighbours] for their help.",
        sentence: "Ich habe mich ___ für ihre Hilfe bedankt.",
        answer: "bei den Nachbarn",
        explanation: "\"Sich bedanken bei\" + dative plural.",
      },
      {
        type: "multiple-choice",
        question: "Which sentence is correct?",
        options: ["Ich danke Ihnen für das Geschenk.", "Ich danke Sie für das Geschenk.", "Ich danke Ihnen über das Geschenk.", "Ich bedanke Ihnen für das Geschenk."],
        correctIndex: 0,
        explanation: "\"Danken\" + dative \"Ihnen\" + \"für\". \"Bedanken\" needs \"sich\" and \"bei\".",
      },
      {
        type: "listen-choose",
        audio: "Ich bedanke mich bei euch.",
        question: "What does it mean?",
        options: ["I thank you all.", "I'm happy for you all.", "I'm waiting for you all.", "I'll say goodbye to you all."],
        correctIndex: 0,
        explanation: "\"Sich bedanken bei\" + dative: thank someone.",
      },
      {
        type: "speak",
        text: "Vielen Dank für Ihre Hilfe.",
        prompt: "Say it in German: Many thanks for your help. (polite)",
        tip: "\"Vielen\": v sounds like f.",
        explanation: "\"Danke für\" + accusative.",
      },
    ],
  },
  {
    slug: "b1-verbs-prepositions-extra-13",
    level: "DE-B1",
    number: 13,
    optional: true,
    title: "Extra Practice: Prepositional Verbs in Every Tense",
    summary: "Perfekt, Präteritum and Konjunktiv II with prepositional verbs.",
    duration: "12 min",
    sections: [
      {
        heading: "Recap: the block stays, the verb changes",
        body: [
          "The preposition and case never change with the tense; only the verb form does. Perfekt: \"Ich habe auf dich gewartet\". Präteritum (writing): \"Ich wartete auf dich\". Plusquamperfekt: \"Ich hatte auf dich gewartet\". Konjunktiv II: \"Ich würde auf dich warten\".",
          "Reflexive prepositional verbs all take \"haben\" in the Perfekt, and the reflexive pronoun stays early: \"Er hat sich über das Essen beschwert\".",
        ],
        examples: [
          { es: "Ich habe zwei Stunden auf dich gewartet.", en: "I waited two hours for you." },
          { es: "Damals interessierte sie sich sehr für Politik.", en: "Back then she was very interested in politics." },
          { es: "Wir hatten uns so auf den Urlaub gefreut.", en: "We'd been looking forward to the holiday so much." },
          { es: "Ich würde mich gern um die Stelle bewerben.", en: "I'd like to apply for the job." },
          { es: "Hättest du an meiner Stelle an dem Kurs teilgenommen?", en: "Would you have taken the course in my place?" },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "I waited for you for two hours. (to a friend)",
            answer: "Ich habe zwei Stunden auf dich gewartet.",
            altAnswers: ["Ich wartete zwei Stunden auf dich.", "Ich habe zwei Stunden auf euch gewartet."],
            explanation: "Perfekt \"habe ... gewartet\"; \"auf dich\" accusative.",
          },
          {
            type: "speak",
            text: "Ich würde mich gern um die Stelle bewerben.",
            prompt: "Say it in German: I'd like to apply for the job.",
            tip: "\"Würde\" with a rounded ü.",
            explanation: "Konjunktiv II \"würde\" + infinitive at the end.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "She looked after her grandmother for years.",
        answer: "Sie hat sich jahrelang um ihre Großmutter gekümmert.",
        altAnswers: ["Sie kümmerte sich jahrelang um ihre Großmutter.", "Sie hat sich jahrelang um ihre Oma gekümmert.", "Sie kümmerte sich jahrelang um ihre Oma."],
        explanation: "Perfekt with \"haben\", or Präteritum in writing.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "We took part in the competition last year.",
        answer: "Wir haben letztes Jahr am Wettbewerb teilgenommen.",
        altAnswers: ["Wir nahmen letztes Jahr am Wettbewerb teil.", "Letztes Jahr haben wir am Wettbewerb teilgenommen.", "Wir haben letztes Jahr an dem Wettbewerb teilgenommen."],
        explanation: "\"Teilnehmen an\" + dative; participle \"teilgenommen\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "He had been afraid of the operation.",
        answer: "Er hatte Angst vor der Operation gehabt.",
        explanation: "Plusquamperfekt: \"hatte ... gehabt\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "I'd look after the children if I had time.",
        answer: "Ich würde mich um die Kinder kümmern, wenn ich Zeit hätte.",
        altAnswers: ["Wenn ich Zeit hätte, würde ich mich um die Kinder kümmern."],
        explanation: "Konjunktiv II in both clauses: \"würde ... kümmern\", \"hätte\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "Back then they dreamed of a better life.",
        answer: "Damals träumten sie von einem besseren Leben.",
        altAnswers: ["Damals haben sie von einem besseren Leben geträumt."],
        explanation: "Präteritum for narration; \"von einem besseren Leben\" dative with comparative ending.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "We had been looking forward to the concert so much.",
        answer: "Wir hatten uns so auf das Konzert gefreut.",
        altAnswers: ["Wir hatten uns so sehr auf das Konzert gefreut.", "Wir hatten uns so aufs Konzert gefreut."],
        explanation: "Plusquamperfekt of \"sich freuen auf\": \"hatten uns ... gefreut\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "If I were you, I wouldn't wait for him.",
        answer: "An deiner Stelle würde ich nicht auf ihn warten.",
        altAnswers: ["An Ihrer Stelle würde ich nicht auf ihn warten.", "Ich an deiner Stelle würde nicht auf ihn warten.", "An eurer Stelle würde ich nicht auf ihn warten."],
        explanation: "\"An deiner Stelle\" + \"würde\" + infinitive; \"auf ihn\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "She [complained] about the room yesterday.",
        sentence: "Sie hat sich gestern über das Zimmer ___.",
        answer: "beschwert",
        explanation: "Participle of \"beschweren\": no ge-.",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "I [would have applied] for the job.",
        sentence: "Ich ___ mich um die Stelle beworben.",
        answer: "hätte",
        explanation: "Past Konjunktiv II: \"hätte\" + participle.",
      },
      {
        type: "multiple-choice",
        question: "Which sentence is correct?",
        options: ["Er hat sich an das Klima gewöhnt.", "Er ist sich an das Klima gewöhnt.", "Er hat sich an dem Klima gewöhnt.", "Er hat an das Klima sich gewöhnt."],
        correctIndex: 0,
        explanation: "Reflexive verbs take \"haben\"; \"an\" + accusative; \"sich\" early.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: We had prepared for the exam.",
        words: ["Wir", "hatten", "uns", "auf", "die", "Prüfung", "vorbereitet."],
        translation: "We had prepared for the exam.",
        explanation: "Plusquamperfekt: \"hatten ... vorbereitet\".",
      },
      {
        type: "listen-choose",
        audio: "Ich hätte mich über eine Karte gefreut.",
        question: "What does it mean?",
        options: ["I would have been pleased to get a card.", "I was pleased to get a card.", "I had been pleased to get a card.", "I'm looking forward to a card."],
        correctIndex: 0,
        explanation: "\"Hätte\" + participle: past Konjunktiv II, would have.",
      },
      {
        type: "speak",
        text: "Ich habe zwei Stunden auf dich gewartet.",
        prompt: "Say it in German: I waited two hours for you.",
        tip: "\"Gewartet\": stress the second syllable, ge-WAR-tet.",
        explanation: "Perfekt of \"warten auf\".",
      },
    ],
  },
];
