// Synced from cheneygross-afk/lengo:src/lib/lessons/de-b1-u02.ts by scripts/sync-content.mjs -- edit it there, not here.
import type { Lesson, WriteExercise } from "./types";
// German B1, Unit 2: The Präteritum in Writing.

export const DE_B1_U02: Lesson[] = [
  {
    slug: "b1-praeteritum-writing-1",
    level: "DE-B1",
    number: 1,
    title: "The Präteritum in Writing, Part 1 of 2: Weak Verbs",
    summary: "Why written German tells stories in the Präteritum, and the recipe for regular (weak) verbs: stem + -te + endings.",
    duration: "15 min",
    sections: [
      {
        heading: "Why writing switches tense",
        body: [
          "Open a German novel, a newspaper report or a Wikipedia biography and the past is told in the Präteritum: \"Sie wohnte in Hamburg und arbeitete als Ärztin.\" The Perfekt you use in conversation would sound chatty there, like a text message.",
          "So the Präteritum is mainly a written tense (and the tense of formal speech: news broadcasts, speeches, fairy tales read aloud). You met \"war\", \"hatte\" and the modals already; this unit adds all the other verbs.",
          "The English simple past is the closest match: \"Sie wohnte\" is she lived, \"er kaufte\" he bought. Unlike in speech, here the one-to-one translation is correct.",
        ],
        examples: [
          { es: "Sie wohnte zehn Jahre in Hamburg.", en: "She lived in Hamburg for ten years." },
          { es: "Er arbeitete als Koch in einem Hotel.", en: "He worked as a chef in a hotel." },
          { es: "Die Polizei suchte den Fahrer zwei Tage lang.", en: "The police searched for the driver for two days." },
          { es: "Am Montag regnete es in ganz Norddeutschland.", en: "On Monday it rained across northern Germany." },
          { es: "Die Kinder spielten im Garten.", en: "The children were playing in the garden." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "Which sentence sounds like a newspaper report?",
            options: ["Der Fahrer wartete zwei Stunden auf Hilfe.", "Der Fahrer hat zwei Stunden auf Hilfe gewartet, echt!", "Der Fahrer wartet seit zwei Stunden auf Hilfe, oder?", "Der Fahrer, der hat zwei Stunden gewartet."],
            correctIndex: 0,
            explanation: "Written reports use the Präteritum: \"wartete\". The others are chatty spoken German.",
          },
          {
            type: "listen-choose",
            audio: "Die Kinder spielten im Garten.",
            question: "What does it mean?",
            options: ["The children were playing in the garden.", "The children play in the garden.", "The children have played in the garden.", "The child was playing in the garden."],
            correctIndex: 0,
            explanation: "\"Spielten\": plural Präteritum. German has no separate continuous form, so it covers were playing too.",
          },
        ],
      },
      {
        heading: "The recipe: stem + -te + ending",
        body: [
          "Weak verbs (the regular ones, those with a participle in -t) form the Präteritum by adding -te to the stem, then the person endings: \"ich machte, du machtest, er/sie/es machte, wir machten, ihr machtet, sie/Sie machten\".",
          "The endings are the same as for \"wollte\" and \"konnte\": nothing for ich and er, -st for du, -n for wir and sie, -t for ihr. Notice that ich and er are identical: \"ich wohnte, er wohnte\".",
          "The most common error is adding a -t to the er form by analogy with the present (\"er macht\"): *er machtet* is wrong; \"er machte\" is right.",
        ],
        examples: [
          { es: "Ich kaufte ein altes Haus auf dem Land.", en: "I bought an old house in the country." },
          { es: "Du sagtest, du kommst um acht.", en: "You said you'd come at eight." },
          { es: "Er lernte schnell Deutsch.", en: "He learned German quickly." },
          { es: "Wir machten jeden Sommer Urlaub an der Nordsee.", en: "We went on holiday to the North Sea every summer." },
          { es: "Ihr spieltet damals in einer Band.", en: "You played in a band back then. (to friends)" },
          { es: "Meine Großeltern lebten in einem kleinen Dorf.", en: "My grandparents lived in a small village." },
        ],
        checkpoint: [
          {
            type: "fill-blank",
            prompt: "Write the German for the bold words.",
            en: "He [learned] German quickly.",
            sentence: "Er ___ schnell Deutsch.",
            answer: "lernte",
            explanation: "Stem \"lern\" + -te, no ending for er: \"lernte\" (not *lerntet*).",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German, in the written past (Präteritum).",
            source: "My grandparents lived in a small village.",
            answer: "Meine Großeltern lebten in einem kleinen Dorf.",
            altAnswers: ["Meine Großeltern wohnten in einem kleinen Dorf."],
            explanation: "Plural: stem + -te + -n: \"lebten\" or \"wohnten\".",
          },
        ],
      },
      {
        heading: "-ete after d, t and some n",
        body: [
          "If the stem ends in d or t, you couldn't hear a plain -te, so German adds an e: \"arbeiten → arbeitete\", \"reden → redete\", \"warten → wartete\", \"antworten → antwortete\", \"heiraten → heiratete\".",
          "The same happens after a consonant + m or n: \"öffnen → öffnete\", \"regnen → regnete\", \"atmen → atmete\", \"rechnen → rechnete\". These are the verbs whose present also has an extra e (\"er arbeitet\", \"es regnet\", \"sie öffnet\").",
          "So \"er arbeitete\" really has three syllables of -te-ish sound: ar-bei-te-te. Don't swallow one in writing (*er arbeitte*).",
        ],
        examples: [
          { es: "Sie arbeitete als Lehrerin in Leipzig.", en: "She worked as a teacher in Leipzig." },
          { es: "Wir warteten eine halbe Stunde auf den Zug.", en: "We waited half an hour for the train." },
          { es: "Er antwortete nicht auf meine E-Mail.", en: "He didn't answer my email." },
          { es: "Es regnete den ganzen Tag.", en: "It rained all day." },
          { es: "Der Kellner öffnete die Flasche.", en: "The waiter opened the bottle." },
          { es: "Meine Eltern heirateten 1985 in Köln.", en: "My parents got married in Cologne in 1985." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German, in the written past (Präteritum).",
            source: "It rained all day.",
            answer: "Es regnete den ganzen Tag.",
            explanation: "\"Regnen\": stem ends in consonant + n, so -ete: \"regnete\".",
          },
          {
            type: "multiple-choice",
            question: "How do you write: She worked as a teacher?",
            options: ["Sie arbeitete als Lehrerin.", "Sie arbeitte als Lehrerin.", "Sie arbeitet als Lehrerin.", "Sie arbeitetete als Lehrerin."],
            correctIndex: 0,
            explanation: "Stem \"arbeit\" + -ete: \"arbeitete\". \"Arbeitet\" is the present.",
          },
          {
            type: "speak",
            text: "Sie arbeitete als Lehrerin in Leipzig.",
            tip: "Say every syllable: AR-bei-te-te.",
            explanation: "The extra e after t makes the past audible.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German, in the written past (Präteritum).",
        source: "He worked as a chef in a hotel.",
        answer: "Er arbeitete als Koch in einem Hotel.",
        explanation: "-ete after the t of \"arbeit\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German, in the written past (Präteritum).",
        source: "We waited for the bus.",
        answer: "Wir warteten auf den Bus.",
        explanation: "\"Warten\": -ete + -n for wir.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German, in the written past (Präteritum).",
        source: "I bought a new bike.",
        answer: "Ich kaufte ein neues Fahrrad.",
        explanation: "\"Kauf\" + -te, no ending for ich.",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "My parents [got married] in 1985.",
        sentence: "Meine Eltern ___ 1985.",
        answer: "heirateten",
        explanation: "\"Heiraten\" ends in t: \"heirate-te-n\". No \"in\" before a year.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German, in the written past (Präteritum).",
        source: "Did you play in a band? (to a friend)",
        answer: "Spieltest du in einer Band?",
        altAnswers: ["Spieltet ihr in einer Band?", "Spielten Sie in einer Band?"],
        explanation: "du: -te + -st: \"spieltest\".",
      },
      {
        type: "multiple-choice",
        question: "Which form is correct for: He opened the window?",
        options: ["Er öffnete das Fenster.", "Er öffnte das Fenster.", "Er öffnetet das Fenster.", "Er geöffnete das Fenster."],
        correctIndex: 0,
        explanation: "Consonant + n in the stem: -ete, \"öffnete\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German, in the written past (Präteritum).",
        source: "He didn't answer.",
        answer: "Er antwortete nicht.",
        explanation: "\"Antworten\": -ete after t.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: The children played in the garden every day.",
        words: ["Die", "Kinder", "spielten", "jeden", "Tag", "im", "Garten."],
        translation: "The children played in the garden every day.",
        altOrders: [["Jeden", "Tag", "spielten", "die", "Kinder", "im", "Garten."]],
        explanation: "\"Spielten\" in position 2; time before place.",
      },
      {
        type: "listen-choose",
        audio: "Wir warteten eine halbe Stunde.",
        question: "What did you hear?",
        options: ["Wir warteten eine halbe Stunde.", "Wir warten eine halbe Stunde.", "Wir warteten eine ganze Stunde.", "Wir werden eine halbe Stunde warten."],
        correctIndex: 0,
        explanation: "\"Warteten\": four syllables, war-te-ten. The present \"warten\" has two.",
      },
      {
        type: "dictation",
        audio: "Es regnete den ganzen Tag.",
        explanation: "\"Regnete\" with -ete; \"den ganzen Tag\" in the accusative.",
      },
      {
        type: "speak",
        text: "Meine Großeltern lebten in einem kleinen Dorf.",
        prompt: "Say it in German (written past): My grandparents lived in a small village.",
        explanation: "\"Lebten\": weak Präteritum plural.",
      },
    ],
  },
  {
    slug: "b1-pattern-praeteritum-weak-verbs",
    level: "DE-B1",
    number: 2,
    title: "Pattern Practice: Wohnte, Kaufte, Wartete",
    summary: "Drill weak verbs in every person through short news items: wohnen, kaufen, suchen, warten, heiraten, studieren and hatte.",
    duration: "13 min",
    sections: [
      {
        heading: "Every person, one pattern",
        body: [
          "Run one verb through all persons until the endings feel automatic: \"ich suchte, du suchtest, er suchte, wir suchten, ihr suchtet, sie suchten\". With -ete: \"ich wartete, du wartetest, er wartete, wir warteten, ihr wartetet, sie warteten\".",
          "Verbs in -ieren are weak too: \"studieren → studierte\", \"telefonieren → telefonierte\", \"reparieren → reparierte\". No surprises there.",
          "\"Haben\" is weak but slightly irregular: \"hatte\", not *habte*. You already know it from speech.",
        ],
        examples: [
          { es: "Ich suchte zwei Monate eine Wohnung.", en: "I looked for a flat for two months." },
          { es: "Du suchtest doch einen Job, oder?", en: "You were looking for a job, weren't you?" },
          { es: "Wir studierten beide in Heidelberg.", en: "We both studied in Heidelberg." },
          { es: "Ihr wohntet damals in Bremen.", en: "You lived in Bremen back then. (to friends)" },
          { es: "Sie hatten zwei Kinder und einen Hund.", en: "They had two children and a dog." },
          { es: "Er reparierte das Fahrrad selbst.", en: "He repaired the bike himself." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German, in the written past (Präteritum).",
            source: "We both studied in Heidelberg.",
            answer: "Wir studierten beide in Heidelberg.",
            explanation: "-ieren verbs are weak: \"studierten\".",
          },
          {
            type: "fill-blank",
            prompt: "Write the German for the bold words.",
            en: "They [had] two children.",
            sentence: "Sie ___ zwei Kinder.",
            answer: "hatten",
            explanation: "\"Haben → hatte\", plural \"hatten\" (never *habten*).",
          },
        ],
      },
      {
        heading: "News in brief",
        body: [
          "Short local news items (Kurzmeldungen) are full of weak Präteritum forms. Read these as they'd appear in a regional paper like the Kölner Stadt-Anzeiger: compact, factual, every verb in the Präteritum.",
          "Typical news verbs: \"melden\" (to report), \"retten\" (to rescue: \"rettete\"), \"suchen\", \"stoppen\", \"landen\", \"zahlen\", \"erklären\".",
        ],
        examples: [
          { es: "Ein Mann aus Bonn zahlte mit falschem Geld.", en: "A man from Bonn paid with counterfeit money." },
          { es: "Die Feuerwehr rettete eine Katze vom Dach.", en: "The fire brigade rescued a cat from the roof." },
          { es: "Die Polizei stoppte den Fahrer auf der A3.", en: "The police stopped the driver on the A3." },
          { es: "Das Flugzeug landete mit zwei Stunden Verspätung.", en: "The plane landed two hours late." },
          { es: "Der Bürgermeister erklärte, dass die Brücke sicher ist.", en: "The mayor said the bridge is safe." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German, in the written past (Präteritum).",
            source: "The fire brigade rescued a cat.",
            answer: "Die Feuerwehr rettete eine Katze.",
            explanation: "\"Retten\": stem ends in t, so -ete.",
          },
          {
            type: "multiple-choice",
            question: "Which is the correct news sentence: The plane landed late?",
            options: ["Das Flugzeug landete verspätet.", "Das Flugzeug landte verspätet.", "Das Flugzeug landetet verspätet.", "Das Flugzeug gelandete verspätet."],
            correctIndex: 0,
            explanation: "\"Landen\": stem ends in d, so -ete: \"landete\".",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German, in the written past (Präteritum).",
        source: "I looked for a flat for two months.",
        answer: "Ich suchte zwei Monate eine Wohnung.",
        altAnswers: ["Ich suchte zwei Monate lang eine Wohnung.", "Zwei Monate lang suchte ich eine Wohnung."],
        explanation: "\"Suchte\": no ending for ich.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German, in the written past (Präteritum).",
        source: "The police stopped the driver.",
        answer: "Die Polizei stoppte den Fahrer.",
        altAnswers: ["Die Polizei hielt den Fahrer an."],
        explanation: "\"Die Polizei\" is singular in German: \"stoppte\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German, in the written past (Präteritum).",
        source: "You lived in Bremen back then. (to friends)",
        answer: "Ihr wohntet damals in Bremen.",
        explanation: "ihr: -te + -t: \"wohntet\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "A man [paid] with counterfeit money.",
        sentence: "Ein Mann ___ mit falschem Geld.",
        answer: "zahlte",
        altAnswers: ["bezahlte"],
        explanation: "\"Zahlen → zahlte\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German, in the written past (Präteritum).",
        source: "She phoned her sister.",
        answer: "Sie telefonierte mit ihrer Schwester.",
        altAnswers: ["Sie rief ihre Schwester an."],
        explanation: "\"Telefonieren mit\" + dative; -ieren verbs are weak: \"telefonierte\".",
      },
      {
        type: "multiple-choice",
        question: "Which form is wrong?",
        options: ["er habte", "ich hatte", "wir hatten", "du hattest"],
        correctIndex: 0,
        explanation: "\"Haben\" → \"hatte\": *habte* doesn't exist.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German, in the written past (Präteritum).",
        source: "The waiters waited outside.",
        answer: "Die Kellner warteten draußen.",
        explanation: "\"Warteten\": -ete + -n.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: He repaired the bike himself.",
        words: ["Er", "reparierte", "das", "Fahrrad", "selbst."],
        translation: "He repaired the bike himself.",
        explanation: "\"Reparierte\": -ieren verb, weak Präteritum.",
      },
      {
        type: "listen-choose",
        audio: "Die Feuerwehr rettete eine Katze vom Dach.",
        question: "What does it mean?",
        options: ["The fire brigade rescued a cat from the roof.", "The fire brigade rescues a cat from the roof.", "The fire brigade looked for a cat on the roof.", "The fire brigade has to rescue a cat from the roof."],
        correctIndex: 0,
        explanation: "\"Rettete\": past of \"retten\".",
      },
      {
        type: "dictation",
        audio: "Das Flugzeug landete mit Verspätung.",
        explanation: "\"Landete\" with -ete after d.",
      },
      {
        type: "speak",
        text: "Wir studierten beide in Heidelberg.",
        prompt: "Say it in German (written past): We both studied in Heidelberg.",
        explanation: "\"Studierten\": weak -ieren verb.",
      },
    ],
  },
  {
    slug: "b1-pattern-praeteritum-strong-verbs",
    level: "DE-B1",
    number: 3,
    title: "Pattern Practice: Ging, Kam, Sah",
    summary: "Strong verbs change their vowel and take no ending in the ich and er forms: ging, kam, sah, fand, schrieb, blieb, nahm, sprach, fuhr, lief, rief.",
    duration: "15 min",
    sections: [
      {
        heading: "New vowel, no -te",
        body: [
          "Strong verbs don't take -te. Instead the stem vowel changes, and the ich and er forms have no ending at all: \"gehen → ich ging, er ging\", \"kommen → ich kam\", \"sehen → ich sah\". The other persons add the usual endings: \"du gingst, wir gingen, ihr gingt, sie gingen\".",
          "Most of these verbs have English cousins that are also irregular, which helps: \"sehen/sah\" (see/saw), \"kommen/kam\" (come/came), \"finden/fand\" (find/found), \"singen/sang\" (sing/sang), \"trinken/trank\" (drink/drank).",
        ],
        examples: [
          { es: "Sie ging jeden Morgen in den Park.", en: "She went to the park every morning." },
          { es: "Um acht kam der Arzt.", en: "At eight the doctor came." },
          { es: "Ich sah einen Fuchs im Garten.", en: "I saw a fox in the garden." },
          { es: "Wir fanden den Schlüssel unter dem Sofa.", en: "We found the key under the sofa." },
          { es: "Sie sangen bis spät in die Nacht.", en: "They sang until late at night." },
          { es: "Gingt ihr auch zu Fuß?", en: "Did you walk too? (to friends)" },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German, in the written past (Präteritum).",
            source: "I saw a fox in the garden.",
            answer: "Ich sah einen Fuchs im Garten.",
            explanation: "\"Sehen → sah\", no ending for ich.",
          },
          {
            type: "fill-blank",
            prompt: "Write the German for the bold words.",
            en: "We [found] the key under the sofa.",
            sentence: "Wir ___ den Schlüssel unter dem Sofa.",
            answer: "fanden",
            explanation: "\"Finden → fand\", plural + -en: \"fanden\".",
          },
        ],
      },
      {
        heading: "Vowel groups: ie, a, u",
        body: [
          "Group the high-frequency ones by their new vowel. ie: \"schreiben → schrieb\", \"bleiben → blieb\", \"laufen → lief\", \"rufen → rief\", \"schlafen → schlief\", \"fallen → fiel\". a: \"nehmen → nahm\", \"sprechen → sprach\", \"geben → gab\", \"essen → aß\", \"sitzen → saß\", \"finden → fand\". u: \"fahren → fuhr\", \"tragen → trug\", \"waschen → wusch\". i: \"gehen → ging\", \"hängen → hing\".",
          "Watch the trap: the Präteritum vowel is often not the participle vowel. \"Schreiben → schrieb → geschrieben\" (same), but \"nehmen → nahm → genommen\", \"sprechen → sprach → gesprochen\", \"helfen → half → geholfen\". Learn the three forms together.",
        ],
        examples: [
          { es: "Er schrieb jeden Tag in sein Tagebuch.", en: "He wrote in his diary every day." },
          { es: "Wir blieben bis Mitternacht.", en: "We stayed until midnight." },
          { es: "Die Lehrerin sprach sehr schnell.", en: "The teacher spoke very fast." },
          { es: "Sie nahm ihre Tasche und lief zum Bahnhof.", en: "She took her bag and ran to the station." },
          { es: "Wir fuhren mit dem Zug nach Dresden.", en: "We went to Dresden by train." },
          { es: "Jemand rief laut meinen Namen.", en: "Somebody called my name loudly." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German, in the written past (Präteritum).",
            source: "She took her bag.",
            answer: "Sie nahm ihre Tasche.",
            explanation: "\"Nehmen → nahm\" (participle \"genommen\": a different vowel).",
          },
          {
            type: "multiple-choice",
            question: "How do you write: We went to Dresden by train?",
            options: ["Wir fuhren mit dem Zug nach Dresden.", "Wir fahrten mit dem Zug nach Dresden.", "Wir fuhrten mit dem Zug nach Dresden.", "Wir fahren mit dem Zug nach Dresden gefahren."],
            correctIndex: 0,
            explanation: "\"Fahren → fuhr\", plural \"fuhren\". Strong verbs never take -te.",
          },
          {
            type: "speak",
            text: "Wir blieben bis Mitternacht.",
            tip: "\"Blieben\": ie is a long ee.",
            explanation: "\"Bleiben → blieb\": ei → ie.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German, in the written past (Präteritum).",
        source: "At eight the doctor came.",
        answer: "Um acht kam der Arzt.",
        altAnswers: ["Der Arzt kam um acht.", "Um acht Uhr kam der Arzt.", "Um acht kam die Ärztin.", "Die Ärztin kam um acht."],
        explanation: "\"Kommen → kam\"; verb second after \"um acht\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German, in the written past (Präteritum).",
        source: "He wrote a long letter.",
        answer: "Er schrieb einen langen Brief.",
        explanation: "ei → ie: \"schrieb\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German, in the written past (Präteritum).",
        source: "The teacher spoke very fast.",
        answer: "Die Lehrerin sprach sehr schnell.",
        altAnswers: ["Der Lehrer sprach sehr schnell."],
        explanation: "\"Sprechen → sprach\" (participle \"gesprochen\").",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "Somebody [called] my name.",
        sentence: "Jemand ___ meinen Namen.",
        answer: "rief",
        explanation: "\"Rufen → rief\": u → ie.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German, in the written past (Präteritum).",
        source: "We ate fish and drank white wine.",
        answer: "Wir aßen Fisch und tranken Weißwein.",
        explanation: "\"Essen → aß\" (ß after long a), \"trinken → trank\"; plural -en.",
      },
      {
        type: "matching",
        instructions: "Match the Präteritum form to its meaning.",
        pairs: [
          { left: "sie lief", right: "she ran" },
          { left: "sie fiel", right: "she fell" },
          { left: "sie schlief", right: "she slept" },
          { left: "sie gab", right: "she gave" },
          { left: "sie trug", right: "she carried" },
        ],
        explanation: "\"Laufen → lief\", \"fallen → fiel\", \"schlafen → schlief\", \"geben → gab\", \"tragen → trug\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German, in the written past (Präteritum).",
        source: "They stayed until midnight.",
        answer: "Sie blieben bis Mitternacht.",
        explanation: "\"Bleiben → blieb\", plural \"blieben\".",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: She went to the park every morning.",
        words: ["Sie", "ging", "jeden", "Morgen", "in", "den", "Park."],
        translation: "She went to the park every morning.",
        altOrders: [["Jeden", "Morgen", "ging", "sie", "in", "den", "Park."]],
        explanation: "\"Gehen → ging\"; time before place.",
      },
      {
        type: "listen-choose",
        audio: "Er nahm den letzten Zug.",
        question: "What did you hear?",
        options: ["Er nahm den letzten Zug.", "Er nimmt den letzten Zug.", "Er kam mit dem letzten Zug.", "Er hat den letzten Zug genommen."],
        correctIndex: 0,
        explanation: "\"Nahm\" (long a): the Präteritum of \"nehmen\".",
      },
      {
        type: "dictation",
        audio: "Sie nahm ihre Tasche und lief zum Bahnhof.",
        explanation: "Two strong verbs: \"nahm\", \"lief\".",
      },
      {
        type: "speak",
        text: "Ich sah einen Fuchs im Garten.",
        prompt: "Say it in German (written past): I saw a fox in the garden.",
        explanation: "\"Sah\": strong, no ending for ich.",
      },
    ],
  },
  {
    slug: "b1-minimal-pairs-er-macht-er-machte",
    level: "DE-B1",
    number: 4,
    title: "Minimal Pairs: Er macht / Er machte, Er kommt / Er kam",
    summary: "Train ear and eye on present vs Präteritum: one extra syllable or one changed vowel is all that tells them apart.",
    duration: "12 min",
    sections: [
      {
        heading: "Weak verbs: one syllable",
        body: [
          "With weak verbs the difference is an extra -te-: \"er macht\" / \"er machte\", \"sie wohnt\" / \"sie wohnte\". With -ete verbs it's \"er wartet\" / \"er wartete\", \"sie redet\" / \"sie redete\": two syllables against three or four.",
          "In the plural it's especially easy to miss: \"wir machen\" / \"wir machten\". Listen for the t before the final -en.",
        ],
        examples: [
          { es: "Er macht die Tür zu.", en: "He closes the door." },
          { es: "Er machte die Tür zu.", en: "He closed the door." },
          { es: "Sie wartet auf ihre Freundin.", en: "She's waiting for her friend." },
          { es: "Sie wartete auf ihre Freundin.", en: "She was waiting for her friend." },
          { es: "Wir reden über die Arbeit.", en: "We talk about work." },
          { es: "Wir redeten über die Arbeit.", en: "We talked about work." },
        ],
        checkpoint: [
          {
            type: "listen-choose",
            audio: "Sie wartete auf ihre Freundin.",
            question: "What did you hear?",
            options: ["Sie wartete auf ihre Freundin.", "Sie wartet auf ihre Freundin.", "Sie warten auf ihre Freundin.", "Sie wartet auf ihren Freund."],
            correctIndex: 0,
            explanation: "Three syllables in the verb, war-te-te: the Präteritum.",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German, in the written past (Präteritum).",
            source: "We talked about work.",
            answer: "Wir redeten über die Arbeit.",
            altAnswers: ["Wir sprachen über die Arbeit."],
            explanation: "\"Reden\": -ete after d, plus -n for wir.",
          },
        ],
      },
      {
        heading: "Strong verbs: one vowel",
        body: [
          "Strong verbs show the past only in the vowel: \"er kommt\" / \"er kam\", \"er liest\" / \"er las\", \"sie gibt\" / \"sie gab\", \"er fällt\" / \"er fiel\", \"sie läuft\" / \"sie lief\".",
          "Some present forms already change their vowel (\"er liest\", \"sie gibt\", \"er fällt\"), so don't build the past from them: it's \"las\", not *liest-te*.",
        ],
        examples: [
          { es: "Er liest die Zeitung.", en: "He reads the paper." },
          { es: "Er las die Zeitung.", en: "He read the paper." },
          { es: "Sie gibt mir das Buch.", en: "She gives me the book." },
          { es: "Sie gab mir das Buch.", en: "She gave me the book." },
          { es: "Das Kind fällt hin.", en: "The child falls over." },
          { es: "Das Kind fiel hin.", en: "The child fell over." },
        ],
        checkpoint: [
          {
            type: "listen-choose",
            audio: "Er las die Zeitung.",
            question: "What does it mean?",
            options: ["He read the paper.", "He reads the paper.", "He's reading the paper aloud.", "He let the paper fall."],
            correctIndex: 0,
            explanation: "\"Las\" (long a) is the past of \"lesen\"; the present would be \"liest\".",
          },
          {
            type: "fill-blank",
            prompt: "Write the German for the bold words.",
            en: "She [gave] me the book.",
            sentence: "Sie ___ mir das Buch.",
            answer: "gab",
            explanation: "\"Geben → gab\": the vowel alone marks the past.",
          },
          {
            type: "speak",
            text: "Er liest. Er las.",
            tip: "\"Liest\" has a long ee; \"las\" a long ah.",
            explanation: "One vowel separates present and past.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "listen-choose",
        audio: "Er kam spät nach Hause.",
        question: "What does it mean?",
        options: ["He came home late.", "He comes home late.", "He can come home late.", "He's coming home later."],
        correctIndex: 0,
        explanation: "\"Kam\": past of \"kommen\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German, in the written past (Präteritum).",
        source: "We took a break.",
        answer: "Wir machten eine Pause.",
        explanation: "A break is \"eine Pause machen\"; the t before -en marks the past: \"machten\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German, in the written past (Präteritum).",
        source: "He closed the door.",
        answer: "Er machte die Tür zu.",
        altAnswers: ["Er schloss die Tür."],
        explanation: "\"Zumachen\" is separable: \"machte ... zu\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German, in the written past (Präteritum).",
        source: "The child fell over.",
        answer: "Das Kind fiel hin.",
        explanation: "\"Hinfallen\": \"fiel ... hin\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German, in the written past (Präteritum).",
        source: "She ran to the station.",
        answer: "Sie lief zum Bahnhof.",
        altAnswers: ["Sie rannte zum Bahnhof."],
        explanation: "\"Laufen → lief\" (not *läufte*).",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "He [was waiting] at the door.",
        sentence: "Er ___ an der Tür.",
        answer: "wartete",
        explanation: "One German form for was waiting: \"wartete\".",
      },
      {
        type: "multiple-choice",
        question: "Which sentence is in the past?",
        options: ["Sie redete lange mit dem Chef.", "Sie redet lange mit dem Chef.", "Sie reden lange mit dem Chef.", "Sie wird lange mit dem Chef reden."],
        correctIndex: 0,
        explanation: "\"Redete\": -ete marks the Präteritum.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German, in the written past (Präteritum).",
        source: "He read the paper.",
        answer: "Er las die Zeitung.",
        explanation: "\"Lesen → las\".",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: She gave me the book.",
        words: ["Sie", "gab", "mir", "das", "Buch."],
        translation: "She gave me the book.",
        explanation: "Dative pronoun before the accusative noun.",
      },
      {
        type: "dictation",
        audio: "Er wartete eine Stunde auf sie.",
        explanation: "\"Wartete\": -ete after t.",
      },
      {
        type: "speak",
        text: "Wir redeten über die Arbeit.",
        prompt: "Say it in German (written past): We talked about work.",
        explanation: "\"Redeten\": re-de-ten.",
      },
    ],
  },
  {
    slug: "b1-praeteritum-writing-2",
    level: "DE-B1",
    number: 5,
    title: "The Präteritum in Writing, Part 2 of 2: Mixed and Separable Verbs",
    summary: "Mixed verbs change their vowel and add -te (brachte, dachte, kannte, wusste); separable verbs split in main clauses and rejoin in subordinate ones.",
    duration: "15 min",
    sections: [
      {
        heading: "Mixed verbs: vowel change + -te",
        body: [
          "A small group combines both systems: a new vowel like strong verbs, and -te like weak verbs. \"Bringen → brachte\", \"denken → dachte\", \"kennen → kannte\", \"nennen → nannte\", \"rennen → rannte\", \"wissen → wusste\". Their participles match: \"gebracht\", \"gedacht\", \"gekannt\", \"genannt\", \"gerannt\", \"gewusst\".",
          "The Präteritum and participle share the vowel, so if you know one, you know the other. The invented *er denkte* and *sie bringte* are the typical slips.",
          "English helps here too: bring/brought, think/thought, both with a vowel change and a t.",
        ],
        examples: [
          { es: "Der Kellner brachte die Rechnung.", en: "The waiter brought the bill." },
          { es: "Ich dachte an meine Großmutter.", en: "I thought of my grandmother." },
          { es: "Niemand kannte den Mann.", en: "Nobody knew the man." },
          { es: "Sie nannten ihre Tochter Emma.", en: "They called their daughter Emma." },
          { es: "Der Hund rannte über die Straße.", en: "The dog ran across the road." },
          { es: "Wir wussten nicht, wo das Hotel ist.", en: "We didn't know where the hotel was." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German, in the written past (Präteritum).",
            source: "The waiter brought the bill.",
            answer: "Der Kellner brachte die Rechnung.",
            altAnswers: ["Die Kellnerin brachte die Rechnung."],
            explanation: "Mixed verb: \"bringen → brachte\" (never *bringte*).",
          },
          {
            type: "multiple-choice",
            question: "How do you write: Nobody knew the man?",
            options: ["Niemand kannte den Mann.", "Niemand kennte den Mann.", "Niemand wusste den Mann.", "Niemand kann den Mann."],
            correctIndex: 0,
            explanation: "Knowing a person is \"kennen\", Präteritum \"kannte\". \"Wissen\" is for facts.",
          },
        ],
      },
      {
        heading: "Separable verbs in main clauses",
        body: [
          "In a main clause a separable verb splits in the Präteritum exactly as in the present: the conjugated part in position 2, the prefix at the end. \"Sie stand um sechs auf\", \"Der Zug kam pünktlich an\", \"Er rief seine Mutter an\".",
          "The prefix sits at the very end, after all objects and adverbs: \"Wir kauften am Samstag auf dem Markt frisches Gemüse ein.\"",
        ],
        examples: [
          { es: "Sie stand jeden Tag um sechs auf.", en: "She got up at six every day." },
          { es: "Der Zug kam pünktlich in München an.", en: "The train arrived in Munich on time." },
          { es: "Er rief am Abend seine Mutter an.", en: "He called his mother in the evening." },
          { es: "Wir kauften auf dem Markt frisches Gemüse ein.", en: "We bought fresh vegetables at the market." },
          { es: "Der Film fing um acht an.", en: "The film started at eight." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German, in the written past (Präteritum).",
            source: "The train arrived on time.",
            answer: "Der Zug kam pünktlich an.",
            explanation: "\"Ankommen\": \"kam\" in position 2, \"an\" at the end.",
          },
          {
            type: "word-order",
            prompt: "Put the words in order to say: He called his mother in the evening.",
            words: ["Er", "rief", "am", "Abend", "seine", "Mutter", "an."],
            translation: "He called his mother in the evening.",
            altOrders: [["Am", "Abend", "rief", "er", "seine", "Mutter", "an."]],
            explanation: "\"Rief ... an\": the prefix goes last.",
          },
        ],
      },
      {
        heading: "Separable verbs in subordinate clauses",
        body: [
          "In a subordinate clause (after \"weil\", \"dass\", \"ob\", \"wenn\") the verb goes to the end, and the separable verb joins up again into one word: \"..., weil der Zug zu spät ankam\", \"..., dass sie um sechs aufstand\".",
          "Compare: \"Der Zug kam zu spät an\" (main clause, split) / \"Ich war sauer, weil der Zug zu spät ankam\" (subordinate, joined). In Unit 4 you'll use the same pattern with \"als\": \"Als der Zug ankam, ...\".",
        ],
        examples: [
          { es: "Ich war sauer, weil der Zug zu spät ankam.", en: "I was annoyed because the train arrived late." },
          { es: "Sie erzählte, dass sie jeden Tag um fünf aufstand.", en: "She said that she got up at five every day." },
          { es: "Niemand wusste, warum er so früh aufhörte.", en: "Nobody knew why he stopped so early." },
          { es: "Wir waren froh, dass der Regen endlich aufhörte.", en: "We were glad that the rain finally stopped." },
          { es: "Er kam zu spät, weil er den Bus verpasste.", en: "He was late because he missed the bus." },
        ],
        checkpoint: [
          {
            type: "fill-blank",
            prompt: "Write the German for the bold words.",
            en: "I was annoyed because the train [arrived] late.",
            sentence: "Ich war sauer, weil der Zug zu spät ___.",
            answer: "ankam",
            explanation: "In a subordinate clause the separable verb is one word at the end: \"ankam\".",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German, in the written past (Präteritum).",
            source: "We were glad that the rain stopped.",
            answer: "Wir waren froh, dass der Regen aufhörte.",
            altAnswers: ["Wir waren froh, dass der Regen endlich aufhörte."],
            explanation: "\"Aufhören\" rejoins at the end after \"dass\".",
          },
          {
            type: "listen-choose",
            audio: "Sie erzählte, dass sie um fünf aufstand.",
            question: "What does it mean?",
            options: ["She said that she got up at five.", "She said that she gets up at five.", "She said that she stopped at five.", "She said that she stood there at five."],
            correctIndex: 0,
            explanation: "\"Aufstand\": joined form of \"stand ... auf\", past of \"aufstehen\".",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German, in the written past (Präteritum).",
        source: "I thought of my grandmother.",
        answer: "Ich dachte an meine Großmutter.",
        altAnswers: ["Ich dachte an meine Oma."],
        explanation: "\"Denken an\" + accusative; \"dachte\" (never *denkte*).",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German, in the written past (Präteritum).",
        source: "We didn't know the answer.",
        answer: "Wir wussten die Antwort nicht.",
        explanation: "\"Wissen → wusste\", plural \"wussten\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German, in the written past (Präteritum).",
        source: "She got up at six.",
        answer: "Sie stand um sechs auf.",
        altAnswers: ["Sie stand um sechs Uhr auf.", "Um sechs stand sie auf."],
        explanation: "\"Aufstehen\": \"stand ... auf\" in a main clause.",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "The film [started] at eight.",
        sentence: "Der Film ___ um acht an.",
        answer: "fing",
        explanation: "\"Anfangen → fing ... an\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German, in the written past (Präteritum).",
        source: "He was late because he missed the bus.",
        answer: "Er kam zu spät, weil er den Bus verpasste.",
        altAnswers: ["Er war zu spät, weil er den Bus verpasste.", "Er kam zu spät, weil er den Bus verpasst hatte."],
        explanation: "\"Verpassen\" is weak and inseparable: \"verpasste\" at the end of the weil-clause.",
      },
      {
        type: "multiple-choice",
        question: "Which sentence is correct?",
        options: ["Wir waren froh, dass der Zug pünktlich ankam.", "Wir waren froh, dass der Zug pünktlich kam an.", "Wir waren froh, dass der Zug kam pünktlich an.", "Wir waren froh, dass ankam der Zug pünktlich."],
        correctIndex: 0,
        explanation: "After \"dass\" the joined verb \"ankam\" goes to the end.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German, in the written past (Präteritum).",
        source: "The dog ran across the road.",
        answer: "Der Hund rannte über die Straße.",
        altAnswers: ["Der Hund lief über die Straße."],
        explanation: "\"Rennen → rannte\": mixed.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: We bought vegetables at the market.",
        words: ["Wir", "kauften", "auf", "dem", "Markt", "Gemüse", "ein."],
        translation: "We bought vegetables at the market.",
        explanation: "\"Einkaufen\": \"kauften ... ein\", prefix at the end.",
      },
      {
        type: "listen-choose",
        audio: "Sie nannten ihre Tochter Emma.",
        question: "What does it mean?",
        options: ["They called their daughter Emma.", "They call their daughter Emma.", "They knew their daughter Emma.", "They named their son Emma."],
        correctIndex: 0,
        explanation: "\"Nennen → nannte\": to name or call.",
      },
      {
        type: "dictation",
        audio: "Der Kellner brachte die Rechnung.",
        explanation: "\"Brachte\": mixed verb, vowel change + -te.",
      },
      {
        type: "speak",
        text: "Der Zug kam pünktlich in München an.",
        prompt: "Say it in German (written past): The train arrived in Munich on time.",
        tip: "\"Pünktlich\": round your lips for ü.",
        explanation: "\"Kam ... an\": separable verb split in a main clause.",
      },
    ],
  },
  {
    slug: "b1-transformations-perfekt-to-praeteritum",
    level: "DE-B1",
    number: 6,
    title: "Transformations: From Perfekt to Präteritum",
    summary: "Turn a spoken account into a written report: one verb in position 2 replaces the auxiliary and the participle.",
    duration: "14 min",
    sections: [
      {
        heading: "Two words become one",
        body: [
          "Going from Perfekt to Präteritum, the auxiliary and participle merge into one Präteritum verb, which takes the auxiliary's place in position 2. Everything else stays put: \"Wir haben lange gewartet\" → \"Wir warteten lange\"; \"Er hat nichts gesagt\" → \"Er sagte nichts\".",
          "The haben/sein choice disappears entirely: \"Sie ist nach Berlin gefahren\" → \"Sie fuhr nach Berlin\". One less thing to get wrong.",
          "To transform, you need the participle's verb family: weak (-te), strong (new vowel), mixed (both). \"Gesagt\" → weak \"sagte\"; \"gefahren\" → strong \"fuhr\"; \"gebracht\" → mixed \"brachte\".",
        ],
        examples: [
          { es: "Wir haben lange gewartet. → Wir warteten lange.", en: "We waited a long time." },
          { es: "Er hat nichts gesagt. → Er sagte nichts.", en: "He didn't say anything." },
          { es: "Sie ist nach Berlin gefahren. → Sie fuhr nach Berlin.", en: "She went to Berlin." },
          { es: "Ich habe ihm Blumen gebracht. → Ich brachte ihm Blumen.", en: "I brought him flowers." },
          { es: "Das Kind hat geweint. → Das Kind weinte.", en: "The child cried." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Rewrite Er hat nichts gesagt in the Präteritum: He didn't say anything.",
            source: "He didn't say anything.",
            answer: "Er sagte nichts.",
            explanation: "\"Hat ... gesagt\" → \"sagte\" in position 2.",
          },
          {
            type: "fill-blank",
            prompt: "Write the German for the bold words.",
            en: "She [went] to Berlin. (written)",
            sentence: "Sie ___ nach Berlin.",
            answer: "fuhr",
            explanation: "\"Ist ... gefahren\" → \"fuhr\": strong, no auxiliary.",
          },
        ],
      },
      {
        heading: "Separable verbs: the prefix moves out",
        body: [
          "A separable participle splits again in the Präteritum: \"Ich bin um sieben aufgestanden\" → \"Ich stand um sieben auf\". The prefix goes to the end, where the participle was.",
          "\"Wir haben im Supermarkt eingekauft\" → \"Wir kauften im Supermarkt ein\". \"Der Bus ist pünktlich abgefahren\" → \"Der Bus fuhr pünktlich ab\".",
        ],
        examples: [
          { es: "Ich bin um sieben aufgestanden. → Ich stand um sieben auf.", en: "I got up at seven." },
          { es: "Wir haben im Supermarkt eingekauft. → Wir kauften im Supermarkt ein.", en: "We did the shopping at the supermarket." },
          { es: "Der Bus ist pünktlich abgefahren. → Der Bus fuhr pünktlich ab.", en: "The bus left on time." },
          { es: "Sie hat das Fenster aufgemacht. → Sie machte das Fenster auf.", en: "She opened the window." },
          { es: "Mehmet hat mich abgeholt. → Mehmet holte mich ab.", en: "Mehmet picked me up." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Rewrite Der Bus ist pünktlich abgefahren in the Präteritum: The bus left on time.",
            source: "The bus left on time.",
            answer: "Der Bus fuhr pünktlich ab.",
            explanation: "\"Fuhr\" in position 2, \"ab\" at the end.",
          },
          {
            type: "multiple-choice",
            question: "Mehmet hat mich abgeholt in the Präteritum?",
            options: ["Mehmet holte mich ab.", "Mehmet abholte mich.", "Mehmet holt mich ab.", "Mehmet hielt mich ab."],
            correctIndex: 0,
            explanation: "\"Abholen\" is weak: \"holte ... ab\". (\"Hielt ab\" is from \"abhalten\", to hold back.)",
          },
        ],
      },
      {
        heading: "A whole account",
        body: [
          "Spoken (Leon tells a friend): \"Ich bin am Freitag nach Leipzig gefahren. Ich habe im Zug ein Buch gelesen und bin eingeschlafen. Ein Mann hat mich geweckt und gesagt, dass wir schon in Leipzig sind.\"",
          "Written (Leon's diary): \"Am Freitag fuhr ich nach Leipzig. Im Zug las ich ein Buch und schlief ein. Ein Mann weckte mich und sagte, dass wir schon in Leipzig waren.\" Note \"waren\" in the dass-clause: in writing the whole story shifts into the past.",
        ],
        examples: [
          { es: "Am Freitag fuhr ich nach Leipzig.", en: "On Friday I went to Leipzig." },
          { es: "Im Zug las ich ein Buch und schlief ein.", en: "On the train I read a book and fell asleep." },
          { es: "Ein Mann weckte mich.", en: "A man woke me up." },
          { es: "Er sagte, dass wir schon in Leipzig waren.", en: "He said that we were already in Leipzig." },
          { es: "Ich stieg schnell aus.", en: "I quickly got off." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Rewrite Ich habe ein Buch gelesen und bin eingeschlafen in the Präteritum: I read a book and fell asleep.",
            source: "I read a book and fell asleep.",
            answer: "Ich las ein Buch und schlief ein.",
            explanation: "\"Las\" (strong), \"schlief ... ein\" (strong, separable).",
          },
          {
            type: "speak",
            text: "Am Freitag fuhr ich nach Leipzig.",
            prompt: "Say it in German (written past): On Friday I went to Leipzig.",
            explanation: "Verb \"fuhr\" second after the time phrase.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Rewrite Wir haben lange gewartet in the Präteritum: We waited a long time.",
        source: "We waited a long time.",
        answer: "Wir warteten lange.",
        explanation: "\"Warteten\": weak with -ete.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Rewrite Ich habe ihm Blumen gebracht in the Präteritum: I brought him flowers.",
        source: "I brought him flowers.",
        answer: "Ich brachte ihm Blumen.",
        explanation: "Mixed verb: \"brachte\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Rewrite Sie hat das Fenster aufgemacht in the Präteritum: She opened the window.",
        source: "She opened the window.",
        answer: "Sie machte das Fenster auf.",
        altAnswers: ["Sie öffnete das Fenster."],
        explanation: "\"Machte ... auf\": the prefix moves to the end.",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "I quickly [got off].",
        sentence: "Ich ___ schnell aus.",
        answer: "stieg",
        explanation: "\"Aussteigen → stieg ... aus\": ei → ie.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Rewrite Wir sind im Hotel geblieben in the Präteritum: We stayed at the hotel.",
        source: "We stayed at the hotel.",
        answer: "Wir blieben im Hotel.",
        explanation: "\"Sind ... geblieben\" → \"blieben\".",
      },
      {
        type: "multiple-choice",
        question: "Er hat seinen Bruder angerufen in the Präteritum?",
        options: ["Er rief seinen Bruder an.", "Er anrief seinen Bruder.", "Er rufte seinen Bruder an.", "Er rief an seinen Bruder."],
        correctIndex: 0,
        explanation: "\"Anrufen\" is strong: \"rief\", with \"an\" at the end.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Rewrite Das Kind hat lange geweint in the Präteritum: The child cried for a long time.",
        source: "The child cried for a long time.",
        answer: "Das Kind weinte lange.",
        explanation: "Weak: \"weinte\".",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: A man woke me up.",
        words: ["Ein", "Mann", "weckte", "mich."],
        translation: "A man woke me up.",
        explanation: "\"Wecken → weckte\": weak.",
      },
      {
        type: "listen-choose",
        audio: "Im Zug las ich ein Buch und schlief ein.",
        question: "What does it mean?",
        options: ["On the train I read a book and fell asleep.", "On the train I read a book and slept well.", "On the train I'm reading a book and falling asleep.", "On the train I let a book fall."],
        correctIndex: 0,
        explanation: "\"Las\" and \"schlief ... ein\": strong Präteritum forms.",
      },
      {
        type: "dictation",
        audio: "Der Bus fuhr pünktlich ab.",
        explanation: "\"Fuhr ... ab\": separable, strong.",
      },
      {
        type: "speak",
        text: "Wir kauften im Supermarkt ein.",
        prompt: "Say it in German (written past): We did the shopping at the supermarket.",
        explanation: "\"Kauften ... ein\": weak, separable.",
      },
    ],
  },
  {
    slug: "b1-minimal-pairs-lag-legte-sass-setzte",
    level: "DE-B1",
    number: 7,
    title: "Minimal Pairs: Lag / Legte, Saß / Setzte",
    summary: "Strong position verbs (lag, saß, stand, hing) against weak placing verbs (legte, setzte, stellte, hängte) in the past.",
    duration: "14 min",
    sections: [
      {
        heading: "Being somewhere vs putting something somewhere",
        body: [
          "You know the pairs from A2: \"liegen\" (to lie, be lying) vs \"legen\" (to lay, put flat); \"sitzen\" vs \"setzen\"; \"stehen\" vs \"stellen\". The position verbs are strong, the placing verbs are weak, and that shows clearly in the past.",
          "Position (strong, wo? + dative): \"liegen → lag\", \"sitzen → saß\", \"stehen → stand\". Placing (weak, wohin? + accusative): \"legen → legte\", \"setzen → setzte\", \"stellen → stellte\".",
          "So: \"Das Buch lag auf dem Tisch\" (where it was) vs \"Sie legte das Buch auf den Tisch\" (what she did with it). The case after the preposition flips too.",
        ],
        examples: [
          { es: "Das Buch lag auf dem Tisch.", en: "The book was lying on the table." },
          { es: "Sie legte das Buch auf den Tisch.", en: "She put the book on the table." },
          { es: "Er saß am Fenster.", en: "He was sitting by the window." },
          { es: "Er setzte sich ans Fenster.", en: "He sat down by the window." },
          { es: "Die Vase stand auf dem Regal.", en: "The vase stood on the shelf." },
          { es: "Sie stellte die Vase auf das Regal.", en: "She put the vase on the shelf." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German, in the written past (Präteritum).",
            source: "She put the book on the table.",
            answer: "Sie legte das Buch auf den Tisch.",
            explanation: "Placing flat: weak \"legte\" + accusative \"auf den Tisch\".",
          },
          {
            type: "fill-blank",
            prompt: "Write the German for the bold words.",
            en: "He [was sitting] by the window.",
            sentence: "Er ___ am Fenster.",
            answer: "saß",
            explanation: "Position: strong \"sitzen → saß\" + dative \"am Fenster\".",
          },
        ],
      },
      {
        heading: "Sich setzen and sich legen",
        body: [
          "Sitting down and lying down are reflexive placing verbs: you put yourself somewhere. \"Er setzte sich aufs Sofa\" (he sat down on the sofa), \"Sie legte sich ins Bett\" (she lay down in bed). Then the state: \"Er saß auf dem Sofa\", \"Sie lag im Bett\".",
          "English sat is both \"saß\" and \"setzte sich\": was he already there, or did he move there? German always tells you.",
        ],
        examples: [
          { es: "Er setzte sich aufs Sofa.", en: "He sat down on the sofa." },
          { es: "Er saß stundenlang auf dem Sofa.", en: "He sat on the sofa for hours." },
          { es: "Sie legte sich früh ins Bett.", en: "She went to bed early." },
          { es: "Sie lag mit Fieber im Bett.", en: "She was in bed with a fever." },
          { es: "Wir setzten uns in die erste Reihe.", en: "We sat down in the front row." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "How do you write: He sat down on the sofa?",
            options: ["Er setzte sich aufs Sofa.", "Er saß sich aufs Sofa.", "Er setzte auf dem Sofa.", "Er saß aufs Sofa."],
            correctIndex: 0,
            explanation: "Movement into a position: \"sich setzen\" + accusative.",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German, in the written past (Präteritum).",
            source: "She was in bed with a fever.",
            answer: "Sie lag mit Fieber im Bett.",
            explanation: "State: strong \"lag\" + dative \"im Bett\".",
          },
        ],
      },
      {
        heading: "Hängen: hing or hängte",
        body: [
          "\"Hängen\" is one infinitive with two pasts. Something hanging (position) is strong: \"Das Bild hing an der Wand\". Someone hanging something up (placing) is weak: \"Sie hängte das Bild an die Wand\".",
          "Participles follow the same split: \"Das Bild hat an der Wand gehangen\" / \"Sie hat das Bild an die Wand gehängt\".",
        ],
        examples: [
          { es: "Das Bild hing an der Wand.", en: "The picture was hanging on the wall." },
          { es: "Sie hängte das Bild an die Wand.", en: "She hung the picture on the wall." },
          { es: "Die Jacke hing an der Tür.", en: "The jacket was hanging on the door." },
          { es: "Er hängte seine Jacke an die Garderobe.", en: "He hung his jacket on the coat rack." },
          { es: "Über dem Tisch hing eine alte Lampe.", en: "An old lamp hung over the table." },
        ],
        checkpoint: [
          {
            type: "fill-blank",
            prompt: "Write the German for the bold words.",
            en: "He [hung] his jacket on the coat rack.",
            sentence: "Er ___ seine Jacke an die Garderobe.",
            answer: "hängte",
            explanation: "Placing: weak \"hängte\" + accusative.",
          },
          {
            type: "listen-choose",
            audio: "Das Bild hing an der Wand.",
            question: "What does it mean?",
            options: ["The picture was hanging on the wall.", "Someone hung the picture on the wall.", "The picture is hanging on the wall.", "The picture fell off the wall."],
            correctIndex: 0,
            explanation: "\"Hing\": strong, position.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German, in the written past (Präteritum).",
        source: "The vase was on the shelf.",
        answer: "Die Vase stand auf dem Regal.",
        explanation: "Upright position: \"stand\" + dative.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German, in the written past (Präteritum).",
        source: "She put the vase on the shelf.",
        answer: "Sie stellte die Vase auf das Regal.",
        altAnswers: ["Sie stellte die Vase aufs Regal."],
        explanation: "Placing upright: weak \"stellte\" + accusative.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German, in the written past (Präteritum).",
        source: "We sat down in the front row.",
        answer: "Wir setzten uns in die erste Reihe.",
        explanation: "\"Sich setzen\" + accusative \"in die erste Reihe\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "The keys [were lying] in the car.",
        sentence: "Die Schlüssel ___ im Auto.",
        answer: "lagen",
        explanation: "Position: \"lagen\" + dative \"im Auto\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German, in the written past (Präteritum).",
        source: "She hung the picture on the wall.",
        answer: "Sie hängte das Bild an die Wand.",
        explanation: "Placing: weak \"hängte\" + accusative.",
      },
      {
        type: "multiple-choice",
        question: "Which sentence is correct?",
        options: ["Die Katze lag auf dem Sofa.", "Die Katze legte auf dem Sofa.", "Die Katze lag auf das Sofa.", "Die Katze liegte auf dem Sofa."],
        correctIndex: 0,
        explanation: "Position: strong \"lag\" + dative.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German, in the written past (Präteritum).",
        source: "He was sitting at the table.",
        answer: "Er saß am Tisch.",
        explanation: "\"Saß\" + dative \"am Tisch\".",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: An old lamp hung over the table.",
        words: ["Über", "dem", "Tisch", "hing", "eine", "alte", "Lampe."],
        translation: "An old lamp hung over the table.",
        altOrders: [["Eine", "alte", "Lampe", "hing", "über", "dem", "Tisch."]],
        explanation: "\"Hing\": strong, position; \"über dem Tisch\" in the dative.",
      },
      {
        type: "listen-choose",
        audio: "Er setzte sich ans Fenster.",
        question: "What does it mean?",
        options: ["He sat down by the window.", "He was sitting by the window.", "He put something by the window.", "He stood by the window."],
        correctIndex: 0,
        explanation: "\"Setzte sich\": movement into a seat.",
      },
      {
        type: "dictation",
        audio: "Sie legte sich früh ins Bett.",
        explanation: "\"Legte sich\" + accusative \"ins Bett\".",
      },
      {
        type: "speak",
        text: "Das Buch lag auf dem Tisch.",
        prompt: "Say it in German (written past): The book was lying on the table.",
        explanation: "\"Lag\" + dative: position.",
      },
    ],
  },
  {
    slug: "b1-error-hunt-praeteritum-forms",
    level: "DE-B1",
    number: 8,
    title: "Error Hunt: Präteritum Forms",
    summary: "Find and fix invented Präteritum forms: gingte, kamte, denkte, sahten, wuste, arbeitte, and participles used as past tenses.",
    duration: "14 min",
    sections: [
      {
        heading: "Strong verbs with a weak ending",
        body: [
          "The commonest invented forms come from adding -te to a strong verb: *er gingte*, *ich kamte*, *wir sahten*. Strong verbs never take -te; the vowel change is enough: \"er ging\", \"ich kam\", \"wir sahen\".",
          "The opposite also happens with mixed verbs, which need both: *sie denkte* misses the vowel change (\"dachte\"), *er brang* misses the -te (\"brachte\").",
        ],
        examples: [
          { es: "Er ging nach Hause.", en: "He went home. (not: er gingte)" },
          { es: "Ich kam zu spät.", en: "I was late. (not: ich kamte)" },
          { es: "Wir sahen einen tollen Film.", en: "We saw a great film. (not: wir sahten)" },
          { es: "Sie dachte an ihre Kinder.", en: "She thought of her children. (not: sie denkte)" },
          { es: "Er brachte Wein mit.", en: "He brought some wine. (not: er bringte)" },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "A learner wrote: Wir sahten einen tollen Film. Write the corrected sentence (written past).",
            source: "We saw a great film.",
            answer: "Wir sahen einen tollen Film.",
            explanation: "Strong verb: \"sahen\", no -te.",
          },
          {
            type: "fill-blank",
            prompt: "A learner wrote: Sie denkte an ihre Kinder. Write the German for the bold word.",
            en: "She [thought] of her children.",
            sentence: "Sie ___ an ihre Kinder.",
            answer: "dachte",
            explanation: "Mixed verb: vowel change + -te.",
          },
        ],
      },
      {
        heading: "Spelling slips and the participle trap",
        body: [
          "*Ich wuste*: \"wissen → wusste\" keeps the double s (short u). *Er arbeitte*: after t you need the e, \"arbeitete\". *Er habte*: \"hatte\".",
          "Another trap is using a participle as if it were a past tense: *Er gefahren nach Hamburg*. A participle alone is never a finite verb. Either \"Er ist nach Hamburg gefahren\" (Perfekt) or \"Er fuhr nach Hamburg\" (Präteritum).",
        ],
        examples: [
          { es: "Ich wusste das nicht.", en: "I didn't know that. (not: ich wuste)" },
          { es: "Er arbeitete bei der Post.", en: "He worked at the post office. (not: er arbeitte)" },
          { es: "Sie hatte keine Zeit.", en: "She had no time. (not: sie habte)" },
          { es: "Er fuhr nach Hamburg.", en: "He went to Hamburg. (not: er gefahren)" },
          { es: "Wir aßen im Garten.", en: "We ate in the garden. (not: wir gegessen)" },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "A learner wrote: Er gefahren nach Hamburg. Write the corrected sentence in the Präteritum.",
            source: "He went to Hamburg.",
            answer: "Er fuhr nach Hamburg.",
            explanation: "A participle can't stand alone: Präteritum \"fuhr\".",
          },
          {
            type: "multiple-choice",
            question: "Which spelling is correct?",
            options: ["Er arbeitete bei der Post.", "Er arbeitte bei der Post.", "Er arbeite bei der Post.", "Er arbeitetete bei der Post."],
            correctIndex: 0,
            explanation: "Stem \"arbeit\" + -ete.",
          },
        ],
      },
      {
        heading: "Separable verbs in the wrong place",
        body: [
          "*Er aufstand um sieben* keeps the verb joined in a main clause. In a main clause it splits: \"Er stand um sieben auf\". The joined form belongs only at the end of a subordinate clause: \"..., weil er um sieben aufstand\".",
          "And the reverse slip: *..., weil er stand um sieben auf* keeps main-clause order after \"weil\". The verb goes to the end, joined.",
        ],
        examples: [
          { es: "Er stand um sieben auf.", en: "He got up at seven. (not: er aufstand)" },
          { es: "Ich war müde, weil ich um fünf aufstand.", en: "I was tired because I got up at five." },
          { es: "Der Laden machte um neun zu.", en: "The shop closed at nine." },
          { es: "Sie rief ihren Vater an.", en: "She called her father." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "A learner wrote: Er aufstand um sieben. Write the corrected sentence (written past).",
            source: "He got up at seven.",
            answer: "Er stand um sieben auf.",
            altAnswers: ["Er stand um sieben Uhr auf.", "Um sieben stand er auf."],
            explanation: "Main clause: the separable verb splits.",
          },
          {
            type: "word-order",
            prompt: "Put the words in order to say: I was tired because I got up at five.",
            words: ["Ich", "war", "müde,", "weil", "ich", "um", "fünf", "aufstand."],
            translation: "I was tired because I got up at five.",
            explanation: "After \"weil\" the joined verb \"aufstand\" goes last.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "A learner wrote: Er gingte nach Hause. Write the corrected sentence (written past).",
        source: "He went home.",
        answer: "Er ging nach Hause.",
        explanation: "Strong: \"ging\", no -te.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "A learner wrote: Ich kamte zu spät. Write the corrected sentence (written past).",
        source: "I was late.",
        answer: "Ich kam zu spät.",
        explanation: "Strong: \"kam\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "A learner wrote: Ich wuste das nicht. Write the corrected sentence (written past).",
        source: "I didn't know that.",
        answer: "Ich wusste das nicht.",
        altAnswers: ["Das wusste ich nicht."],
        explanation: "Short u, double s: \"wusste\".",
      },
      {
        type: "fill-blank",
        prompt: "A learner wrote: Er bringte Wein mit. Write the German for the bold word.",
        en: "He [brought] some wine.",
        sentence: "Er ___ Wein mit.",
        answer: "brachte",
        explanation: "Mixed verb: \"brachte\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "A learner wrote: Wir gegessen im Garten. Write the corrected sentence (written past).",
        source: "We ate in the garden.",
        answer: "Wir aßen im Garten.",
        explanation: "Präteritum \"aßen\"; a participle can't stand alone.",
      },
      {
        type: "multiple-choice",
        question: "Which sentence has no mistake?",
        options: ["Sie hatte keine Zeit.", "Sie habte keine Zeit.", "Sie hattet keine Zeit.", "Sie gehabt keine Zeit."],
        correctIndex: 0,
        explanation: "\"Haben → hatte\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "A learner wrote: Der Laden zumachte um neun. Write the corrected sentence (written past).",
        source: "The shop closed at nine.",
        answer: "Der Laden machte um neun zu.",
        altAnswers: ["Der Laden schloss um neun.", "Das Geschäft machte um neun zu."],
        explanation: "Main clause: \"machte ... zu\".",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: She called her father.",
        words: ["Sie", "rief", "ihren", "Vater", "an."],
        translation: "She called her father.",
        explanation: "\"Rief ... an\": separable, strong.",
      },
      {
        type: "listen-choose",
        audio: "Wir sahen einen tollen Film.",
        question: "What did you hear?",
        options: ["Wir sahen einen tollen Film.", "Wir sehen einen tollen Film.", "Wir sahten einen tollen Film.", "Wir haben einen tollen Film gesehen."],
        correctIndex: 0,
        explanation: "\"Sahen\": the correct strong plural.",
      },
      {
        type: "dictation",
        audio: "Er arbeitete bei der Post.",
        explanation: "\"Arbeitete\" with -ete.",
      },
      {
        type: "speak",
        text: "Er stand um sieben auf.",
        prompt: "Say it in German (written past): He got up at seven.",
        explanation: "Main clause: \"stand ... auf\".",
      },
    ],
  },
  {
    slug: "b1-contrast-clinic-speech-or-writing",
    level: "DE-B1",
    number: 9,
    title: "Contrast Clinic: Speech or Writing?",
    summary: "The same event told twice: a WhatsApp message in the Perfekt and a newspaper notice or diary entry in the Präteritum.",
    duration: "14 min",
    sections: [
      {
        heading: "The message",
        body: [
          "Mia saw a minor accident on her way to work and texts her friend Leon: \"Stell dir vor, heute Morgen ist vor mir ein Radfahrer gestürzt! Ein Auto hat ihn fast angefahren. Ich habe sofort den Krankenwagen gerufen. Zum Glück war er nicht schlimm verletzt.\"",
          "Perfekt for the actions (\"ist gestürzt\", \"hat angefahren\", \"habe gerufen\"), Präteritum only for \"war\". That's how people tell things in messages and conversation.",
        ],
        examples: [
          { es: "Heute Morgen ist vor mir ein Radfahrer gestürzt!", en: "This morning a cyclist fell off his bike right in front of me!" },
          { es: "Ein Auto hat ihn fast angefahren.", en: "A car nearly hit him." },
          { es: "Ich habe sofort den Krankenwagen gerufen.", en: "I called an ambulance straight away." },
          { es: "Zum Glück war er nicht schlimm verletzt.", en: "Luckily he wasn't badly hurt." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German, as Mia would say it in a message.",
            source: "I called an ambulance straight away.",
            answer: "Ich habe sofort den Krankenwagen gerufen.",
            altAnswers: ["Ich habe sofort einen Krankenwagen gerufen."],
            explanation: "Spoken style: Perfekt \"habe ... gerufen\".",
          },
          {
            type: "multiple-choice",
            question: "Which sentence fits a WhatsApp message to a friend?",
            options: ["Ich bin heute total spät aufgestanden!", "Ich stand heute total spät auf!", "Ich stehe heute total spät auf gewesen!", "Heute stand ich spät auf, berichtete ich."],
            correctIndex: 0,
            explanation: "Messages use the Perfekt for most verbs; \"stand ... auf\" sounds like a written story.",
          },
        ],
      },
      {
        heading: "The newspaper notice",
        body: [
          "The local paper reports the same event: \"Am Dienstagmorgen stürzte in der Bahnhofstraße ein Radfahrer. Ein Auto erfasste ihn beinahe. Eine Passantin rief sofort den Rettungsdienst. Der Mann war nur leicht verletzt.\"",
          "Every verb is in the Präteritum, and the vocabulary is more formal: \"beinahe\" (nearly) for \"fast\", \"der Rettungsdienst\" for \"der Krankenwagen\", \"eine Passantin\" (a passer-by) instead of \"ich\".",
        ],
        examples: [
          { es: "Am Dienstagmorgen stürzte in der Bahnhofstraße ein Radfahrer.", en: "On Tuesday morning a cyclist fell in the street by the station." },
          { es: "Ein Auto erfasste ihn beinahe.", en: "A car nearly hit him." },
          { es: "Eine Passantin rief sofort den Rettungsdienst.", en: "A passer-by immediately called the emergency services." },
          { es: "Der Mann war nur leicht verletzt.", en: "The man was only slightly injured." },
          { es: "Die Polizei sperrte die Straße für eine Stunde.", en: "The police closed the road for an hour." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German, as a newspaper would write it.",
            source: "A passer-by called the emergency services.",
            answer: "Eine Passantin rief den Rettungsdienst.",
            altAnswers: ["Ein Passant rief den Rettungsdienst.", "Eine Passantin rief sofort den Rettungsdienst.", "Ein Passant rief sofort den Rettungsdienst.", "Eine Passantin rief den Notarzt.", "Ein Passant rief den Notarzt."],
            explanation: "Written style: Präteritum \"rief\".",
          },
          {
            type: "fill-blank",
            prompt: "Write the German for the bold words.",
            en: "The police [closed] the road.",
            sentence: "Die Polizei ___ die Straße.",
            answer: "sperrte",
            explanation: "Weak \"sperren → sperrte\".",
          },
        ],
      },
      {
        heading: "What stays the same everywhere",
        body: [
          "Some verbs are in the Präteritum in both styles: \"war\", \"hatte\", the modals (\"wollte\", \"musste\", \"konnte\") and \"es gab\". That's why the message and the notice both say \"war ... verletzt\".",
          "Using the written Präteritum in casual speech can sound stiff or literary: if you tell a friend \"Gestern ging ich ins Kino und sah einen Film\", it sounds as if you're reading a novel aloud. Northern Germans do use some of these forms more, but the safe choice in speech is the Perfekt.",
          "And the reverse: a Perfekt-heavy text in an official report or a CV sounds too casual. Match the tense to the register.",
        ],
        examples: [
          { es: "Ich konnte nicht schlafen, weil es so heiß war.", en: "I couldn't sleep because it was so hot." },
          { es: "Es gab einen Unfall auf der A1.", en: "There was an accident on the A1." },
          { es: "Gestern bin ich ins Kino gegangen.", en: "I went to the cinema yesterday. (spoken)" },
          { es: "Am Abend ging er ins Kino.", en: "In the evening he went to the cinema. (written)" },
          { es: "Wir mussten den Termin verschieben.", en: "We had to postpone the appointment." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German (natural in both speech and writing).",
            source: "There was an accident on the A1.",
            answer: "Es gab einen Unfall auf der A1.",
            explanation: "\"Es gab\" is used in every register.",
          },
          {
            type: "speak",
            text: "Gestern bin ich ins Kino gegangen.",
            prompt: "Tell a friend: I went to the cinema yesterday.",
            explanation: "Speech: Perfekt.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German, as you'd say it to a friend.",
        source: "A car nearly hit him.",
        answer: "Ein Auto hat ihn fast angefahren.",
        altAnswers: ["Ein Auto hat ihn beinahe angefahren."],
        explanation: "Spoken: Perfekt with \"haben\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German, as a newspaper would write it.",
        source: "A cyclist fell on Bahnhofstraße.",
        answer: "In der Bahnhofstraße stürzte ein Radfahrer.",
        altAnswers: ["Ein Radfahrer stürzte in der Bahnhofstraße."],
        explanation: "Written: Präteritum \"stürzte\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "Luckily he wasn't badly hurt.",
        answer: "Zum Glück war er nicht schlimm verletzt.",
        altAnswers: ["Zum Glück war er nicht schwer verletzt.", "Glücklicherweise war er nicht schwer verletzt.", "Glücklicherweise war er nicht schlimm verletzt."],
        explanation: "\"War\" in every register.",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "We [had to] postpone the appointment.",
        sentence: "Wir ___ den Termin verschieben.",
        answer: "mussten",
        explanation: "Modal: Präteritum in speech and writing.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German, as a diary entry (written past).",
        source: "In the evening I went to the cinema.",
        answer: "Am Abend ging ich ins Kino.",
        altAnswers: ["Abends ging ich ins Kino."],
        explanation: "Written: \"ging\".",
      },
      {
        type: "multiple-choice",
        question: "Which sentence suits a police report?",
        options: ["Der Täter floh mit einem Fahrrad.", "Der Täter ist mit einem Fahrrad abgehauen, krass.", "Der Täter, der ist mit dem Rad weg.", "Der Täter hat sich mit dem Rad verdrückt."],
        correctIndex: 0,
        explanation: "Reports use the Präteritum (\"floh\", from \"fliehen\") and neutral vocabulary.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German, as you'd say it to a friend.",
        source: "I saw an accident this morning.",
        answer: "Ich habe heute Morgen einen Unfall gesehen.",
        altAnswers: ["Heute Morgen habe ich einen Unfall gesehen."],
        explanation: "Spoken: Perfekt.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say (written past): The man was only slightly injured.",
        words: ["Der", "Mann", "war", "nur", "leicht", "verletzt."],
        translation: "The man was only slightly injured.",
        explanation: "\"War\" + \"verletzt\" (an adjective here).",
      },
      {
        type: "listen-choose",
        audio: "Eine Passantin rief sofort den Rettungsdienst.",
        question: "What does it mean?",
        options: ["A passer-by immediately called the emergency services.", "A passer-by immediately ran to the rescue.", "A passenger called the emergency services.", "A passer-by is calling the emergency services."],
        correctIndex: 0,
        explanation: "\"Passantin\": passer-by (false friend: a passenger is \"Fahrgast\" or \"Passagier\").",
      },
      {
        type: "dictation",
        audio: "Es gab einen Unfall in der Bahnhofstraße.",
        explanation: "\"Es gab\": past in every register.",
      },
      {
        type: "speak",
        text: "Stell dir vor, heute Morgen ist ein Radfahrer gestürzt!",
        prompt: "Say it to a friend: Imagine, a cyclist fell this morning!",
        explanation: "Spoken: Perfekt \"ist gestürzt\".",
      },
    ],
  },
];

export const DE_B1_U02_WRITING: WriteExercise = {
  type: "write",
  prompt: "Write a short article for your town's newsletter about an unusual event that happened last week (a lost animal, a surprise concert, a storm...). Write it in the Präteritum, like a newspaper report: what happened, when and where, who did what, and how it ended.",
  minWords: 80,
  maxWords: 150,
  rubric: [
    "Uses weak Präteritum forms, including -ete after d/t (\"wartete\", \"meldete\", \"arbeitete\").",
    "Uses strong and mixed forms correctly (\"kam\", \"fand\", \"lief\", \"brachte\", \"wusste\").",
    "Splits separable verbs in main clauses (\"Sie rief die Polizei an\") and joins them at the end of subordinate clauses (\"..., weil der Bus nicht ankam\").",
    "Keeps the whole report in the Präteritum, with \"war\", \"hatte\" and \"es gab\" for the background.",
  ],
  modelAnswer: "Hund im Supermarkt\n\nAm letzten Donnerstag gab es im Rewe in der Lindenstraße eine Überraschung. Gegen zehn Uhr kam ein kleiner brauner Hund durch die automatische Tür und lief direkt in die Fleischabteilung. Die Kunden lachten, aber niemand wusste, wem der Hund gehörte. Eine Verkäuferin brachte ihm Wasser und rief das Tierheim an. Der Hund hatte kein Halsband, aber er war sehr freundlich. Nach einer Stunde meldete sich eine ältere Dame. Sie suchte den Hund schon den ganzen Morgen: Das Gartentor stand offen, und er lief einfach weg. Sie war sehr glücklich und dankte der Verkäuferin, weil sie so schnell beim Tierheim anrief. Zum Abschied bekam der Hund eine Wurst.",
  explanation: "A written report keeps every verb in the Präteritum: weak \"lachten\", \"meldete\" (-ete after d), \"dankte\"; strong \"kam\", \"lief\", \"stand\", \"bekam\"; mixed \"wusste\", \"brachte\". Separable verbs split in main clauses (\"rief ... an\") and join at the end of a subordinate clause (\"anrief\"). \"Es gab\", \"war\" and \"hatte\" set the scene.",
};
