// Synced from cheneygross-afk/lengo:src/lib/lessons/de-b1-u14-extra.ts by scripts/sync-content.mjs -- edit it there, not here.
import type { Lesson } from "./types";
// German B1, Unit 14 extra practice: The Passive: Present and Präteritum.

export const DE_B1_U14_EXTRA: Lesson[] = [
  {
    slug: "b1-passive-extra-1",
    level: "DE-B1",
    number: 1,
    optional: true,
    title: "Extra Practice: The Passive, Part 1 of 3",
    summary: "More practice with the present passive and singular and plural subjects.",
    duration: "10 min",
    sections: [
      {
        heading: "Recap: wird / werden + participle",
        body: [
          "Present passive: \"wird\" (singular) or \"werden\" (plural) in position 2 and the participle at the very end. The active object becomes the subject: \"Man wäscht das Auto\" → \"Das Auto wird gewaschen\". English is done and is being done are both \"wird gemacht\". Never \"sein\" for a process.",
        ],
        examples: [
          { es: "Das Auto wird gewaschen.", en: "The car is being washed." },
          { es: "Die Teller werden abgespült.", en: "The plates are being washed up." },
          { es: "Hier wird Englisch gesprochen.", en: "English is spoken here." },
          { es: "Die Zeitung wird jeden Morgen gebracht.", en: "The newspaper is delivered every morning." },
          { es: "Werden die Kinder abgeholt?", en: "Are the children being picked up?" },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "The car is being washed.",
            answer: "Das Auto wird gewaschen.",
            altAnswers: ["Das Auto wird gerade gewaschen."],
            explanation: "Singular: \"wird\" + \"gewaschen\".",
          },
          {
            type: "listen-choose",
            audio: "Die Teller werden abgespült.",
            question: "What does it mean?",
            options: ["The plates are being washed up.", "The plates were washed up.", "Wash up the plates.", "The plates will break."],
            correctIndex: 0,
            explanation: "Plural: \"werden\" + participle.",
          },
        ],
      },
    ],
    exercises: [
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "The newspaper is delivered at six.", answer: "Die Zeitung wird um sechs gebracht.", altAnswers: ["Die Zeitung wird um sechs geliefert.", "Die Zeitung wird um sechs zugestellt.", "Um sechs wird die Zeitung gebracht."], explanation: "Singular: \"wird\"." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "The newspapers are delivered at six.", answer: "Die Zeitungen werden um sechs gebracht.", altAnswers: ["Die Zeitungen werden um sechs geliefert.", "Die Zeitungen werden um sechs zugestellt.", "Um sechs werden die Zeitungen gebracht."], explanation: "Plural: \"werden\"." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "The dishes are being washed.", answer: "Das Geschirr wird gespült.", altAnswers: ["Das Geschirr wird abgewaschen.", "Das Geschirr wird gerade gespült.", "Das Geschirr wird abgespült."], explanation: "\"Das Geschirr\" is singular in German: \"wird\"." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "Coffee is served in the garden.", answer: "Der Kaffee wird im Garten serviert.", altAnswers: ["Kaffee wird im Garten serviert.", "Im Garten wird Kaffee serviert."], explanation: "\"Serviert\": -ieren verb, no ge-." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "The tickets are checked at the entrance.", answer: "Die Tickets werden am Eingang kontrolliert.", altAnswers: ["Die Karten werden am Eingang kontrolliert.", "Am Eingang werden die Tickets kontrolliert.", "Die Eintrittskarten werden am Eingang kontrolliert."], explanation: "Plural: \"werden ... kontrolliert\"." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "Is the room cleaned every day?", answer: "Wird das Zimmer jeden Tag geputzt?", altAnswers: ["Wird das Zimmer jeden Tag gereinigt?", "Wird das Zimmer täglich gereinigt?", "Wird das Zimmer täglich geputzt?"], explanation: "Yes/no question: \"Wird\" first." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "The shop is closed at eight.", answer: "Der Laden wird um acht geschlossen.", altAnswers: ["Das Geschäft wird um acht geschlossen.", "Um acht wird der Laden geschlossen."], explanation: "The action of closing: \"wird geschlossen\"." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "Where are the bags stored?", answer: "Wo werden die Taschen aufbewahrt?", altAnswers: ["Wo werden die Koffer aufbewahrt?", "Wo werden die Taschen gelagert?"], explanation: "Plural: \"werden ... aufbewahrt\"." },
      { type: "fill-blank", prompt: "Write the German for the bold words.", en: "The lawn [is] mown on Saturdays.", sentence: "Der Rasen ___ samstags gemäht.", answer: "wird", explanation: "Singular \"der Rasen\"." },
      { type: "fill-blank", prompt: "Write the German for the bold words.", en: "The guests [are] welcomed at the door.", sentence: "Die Gäste ___ an der Tür begrüßt.", answer: "werden", explanation: "Plural \"die Gäste\"." },
      { type: "fill-blank", prompt: "Write the German for the bold words.", en: "The flowers are [watered] every day.", sentence: "Die Blumen werden jeden Tag ___.", answer: "gegossen", explanation: "\"Gießen\" → \"gegossen\"." },
      { type: "word-order", prompt: "Put the words in order to say: English is spoken here.", words: ["Hier", "wird", "Englisch", "gesprochen."], translation: "English is spoken here.", explanation: "\"Hier\" first, \"wird\" second." },
      { type: "multiple-choice", question: "Which sentence means: The house is being built?", options: ["Das Haus wird gebaut.", "Das Haus ist gebaut.", "Das Haus wurde gebaut.", "Das Haus baut."], correctIndex: 0, explanation: "Process: \"wird gebaut\"." },
      { type: "dictation", audio: "Die Zeitung wird jeden Morgen gebracht.", explanation: "\"Wird ... gebracht\"." },
      { type: "speak", text: "Hier werden Fahrräder repariert.", prompt: "Say it in German: Bikes are repaired here.", explanation: "Plural: \"werden\"." },
    ],
  },
  {
    slug: "b1-passive-extra-2",
    level: "DE-B1",
    number: 2,
    optional: true,
    title: "Extra Practice: The Passive, Part 2 of 3",
    summary: "More practice with the Präteritum passive in history and news.",
    duration: "10 min",
    sections: [
      {
        heading: "Recap: wurde / wurden + participle",
        body: [
          "Past passive: \"wurde\" (singular) or \"wurden\" (plural) + participle at the end. It's the standard form for history and news: \"Das Rathaus wurde 1350 gebaut\", \"Zwei Personen wurden verletzt\". Years stand alone, without \"in\".",
        ],
        examples: [
          { es: "Das Rathaus wurde 1350 gebaut.", en: "The town hall was built in 1350." },
          { es: "Zwei Personen wurden leicht verletzt.", en: "Two people were slightly injured." },
          { es: "Der Flughafen wurde 2020 eröffnet.", en: "The airport was opened in 2020." },
          { es: "Die Stadt wurde im Krieg fast völlig zerstört.", en: "The city was almost completely destroyed in the war." },
          { es: "Der Dieb wurde am Bahnhof festgenommen.", en: "The thief was arrested at the station." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "The airport was opened in 2020.",
            answer: "Der Flughafen wurde 2020 eröffnet.",
            altAnswers: ["2020 wurde der Flughafen eröffnet.", "Der Flughafen wurde im Jahr 2020 eröffnet."],
            explanation: "\"Wurde eröffnet\"; no \"in\" before the year.",
          },
          {
            type: "listen-choose",
            audio: "Zwei Personen wurden leicht verletzt.",
            question: "What does it mean?",
            options: ["Two people were slightly injured.", "Two people are slightly injured.", "Two people were seriously injured.", "Two people injured themselves slightly."],
            correctIndex: 0,
            explanation: "\"Wurden ... verletzt\": past passive, plural; \"leicht\" is slightly.",
          },
        ],
      },
    ],
    exercises: [
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "The town hall was built in the 14th century.", answer: "Das Rathaus wurde im 14. Jahrhundert gebaut.", altAnswers: ["Das Rathaus wurde im vierzehnten Jahrhundert gebaut."], explanation: "\"Wurde gebaut\"; centuries with \"im\"." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "Nobody was injured.", answer: "Niemand wurde verletzt.", altAnswers: ["Es wurde niemand verletzt.", "Keiner wurde verletzt."], explanation: "Singular \"niemand\": \"wurde\"." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "The thief was arrested yesterday.", answer: "Der Dieb wurde gestern festgenommen.", altAnswers: ["Der Dieb wurde gestern verhaftet.", "Gestern wurde der Dieb festgenommen."], explanation: "\"Festnehmen\" → \"festgenommen\"." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "The university was founded in 1409.", answer: "Die Universität wurde 1409 gegründet.", altAnswers: ["1409 wurde die Universität gegründet.", "Die Uni wurde 1409 gegründet."], explanation: "\"Gründen\" → \"gegründet\"." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "The new president was elected on Sunday.", answer: "Der neue Präsident wurde am Sonntag gewählt.", altAnswers: ["Die neue Präsidentin wurde am Sonntag gewählt.", "Am Sonntag wurde der neue Präsident gewählt."], explanation: "\"Wählen\" → \"gewählt\"." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "The roads were closed because of the snow.", answer: "Die Straßen wurden wegen des Schnees gesperrt.", altAnswers: ["Die Straßen wurden wegen dem Schnee gesperrt.", "Wegen des Schnees wurden die Straßen gesperrt."], explanation: "Plural: \"wurden\"; \"wegen\" + genitive (dative in speech)." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "The paintings were stolen at night.", answer: "Die Bilder wurden nachts gestohlen.", altAnswers: ["Die Gemälde wurden nachts gestohlen.", "Die Bilder wurden in der Nacht gestohlen.", "Die Gemälde wurden in der Nacht gestohlen."], explanation: "\"Stehlen\" → \"gestohlen\"." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "The concert was cancelled.", answer: "Das Konzert wurde abgesagt.", explanation: "\"Absagen\" → \"abgesagt\"." },
      { type: "fill-blank", prompt: "Write the German for the bold words.", en: "The castle [was] destroyed in 1689.", sentence: "Das Schloss ___ 1689 zerstört.", answer: "wurde", explanation: "Singular past: \"wurde\"." },
      { type: "fill-blank", prompt: "Write the German for the bold words.", en: "The houses [were] built after the war.", sentence: "Die Häuser ___ nach dem Krieg gebaut.", answer: "wurden", explanation: "Plural past: \"wurden\"." },
      { type: "fill-blank", prompt: "Write the German for the bold words.", en: "The bridge was [opened] in 1910.", sentence: "Die Brücke wurde 1910 ___.", answer: "eröffnet", altAnswers: ["eingeweiht"], explanation: "\"Eröffnen\" → \"eröffnet\" (no ge-)." },
      { type: "word-order", prompt: "Put the words in order to say: The thief was arrested at the station.", words: ["Der Dieb", "wurde", "am", "Bahnhof", "festgenommen."], translation: "The thief was arrested at the station.", explanation: "Participle last." },
      { type: "multiple-choice", question: "Which is a news headline sentence in the past passive?", options: ["Drei Personen wurden verletzt.", "Drei Personen werden verletzt.", "Drei Personen würden verletzt.", "Drei Personen sind verletzt worden werden."], correctIndex: 0, explanation: "\"Wurden\" + participle: past passive." },
      { type: "dictation", audio: "Die Stadt wurde im Krieg fast völlig zerstört.", explanation: "\"Wurde ... zerstört\"." },
      { type: "speak", text: "Das Rathaus wurde 1350 gebaut.", prompt: "Say it in German: The town hall was built in 1350.", tip: "Say the year as dreizehnhundertfünfzig.", explanation: "Past passive with a year." },
    ],
  },
  {
    slug: "b1-passive-extra-3",
    level: "DE-B1",
    number: 3,
    optional: true,
    title: "Extra Practice: The Passive, Part 3 of 3",
    summary: "More practice with the passive in subordinate clauses.",
    duration: "10 min",
    sections: [
      {
        heading: "Recap: participle + wird / wurde at the end",
        body: [
          "In weil-, dass-, ob-, wenn- and relative clauses the conjugated \"wird\" / \"wurde\" goes to the very end, after the participle: \"..., weil die Straße gesperrt wird\", \"..., dass der Dieb gefunden wurde\", \"das Haus, das 1900 gebaut wurde\".",
        ],
        examples: [
          { es: "Wir müssen umsteigen, weil die Strecke gesperrt wird.", en: "We have to change because the line is being closed." },
          { es: "Ich habe gelesen, dass der Dieb gefunden wurde.", en: "I read that the thief was found." },
          { es: "Weißt du, ob das Paket schon abgeholt wurde?", en: "Do you know if the parcel has been collected yet?" },
          { es: "Das ist die Kirche, die 1200 gebaut wurde.", en: "That's the church that was built in 1200." },
          { es: "Wenn die Kinder abgeholt werden, ist es ruhig.", en: "When the children are picked up, it's quiet." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "I read that the thief was found.",
            answer: "Ich habe gelesen, dass der Dieb gefunden wurde.",
            altAnswers: ["Ich las, dass der Dieb gefunden wurde."],
            explanation: "Dass-clause: \"gefunden wurde\" at the end.",
          },
          {
            type: "listen-choose",
            audio: "Weißt du, ob das Paket schon abgeholt wurde?",
            question: "What does it mean?",
            options: ["Do you know if the parcel has been collected yet?", "Do you know where the parcel was collected?", "Have you collected the parcel?", "Do you know if the parcel will be delivered?"],
            correctIndex: 0,
            explanation: "\"Ob\" + past passive at the end.",
          },
        ],
      },
    ],
    exercises: [
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "I'm working at home because my office is being renovated.", answer: "Ich arbeite zu Hause, weil mein Büro renoviert wird.", altAnswers: ["Ich arbeite von zu Hause, weil mein Büro renoviert wird.", "Ich arbeite zu Hause, weil mein Büro gerade renoviert wird."], explanation: "\"Renoviert wird\" at the end." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "Do you know when the station was built?", answer: "Weißt du, wann der Bahnhof gebaut wurde?", altAnswers: ["Wissen Sie, wann der Bahnhof gebaut wurde?", "Wisst ihr, wann der Bahnhof gebaut wurde?"], explanation: "Indirect question: \"gebaut wurde\" at the end." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "That's the bridge that was destroyed in the war.", answer: "Das ist die Brücke, die im Krieg zerstört wurde.", explanation: "Relative clause with past passive." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "I hope that my bike is repaired soon.", answer: "Ich hoffe, dass mein Fahrrad bald repariert wird.", altAnswers: ["Ich hoffe, mein Fahrrad wird bald repariert.", "Ich hoffe, dass mein Rad bald repariert wird."], explanation: "\"Repariert wird\" at the end." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "We didn't know that the shop was closed on Mondays.", answer: "Wir wussten nicht, dass der Laden montags geschlossen wird.", altAnswers: ["Wir wussten nicht, dass das Geschäft montags geschlossen wird.", "Wir wussten nicht, dass der Laden montags geschlossen ist.", "Wir haben nicht gewusst, dass der Laden montags geschlossen ist."], explanation: "\"Geschlossen wird\" at the end; with a state, \"geschlossen ist\" also works." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "The cake that was baked by my aunt was delicious.", answer: "Der Kuchen, der von meiner Tante gebacken wurde, war lecker.", altAnswers: ["Der Kuchen, der von meiner Tante gebacken wurde, war köstlich."], explanation: "Relative clause in the middle; \"gebacken wurde\" before the comma." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "Call me when the results are published.", answer: "Ruf mich an, wenn die Ergebnisse veröffentlicht werden.", altAnswers: ["Rufen Sie mich an, wenn die Ergebnisse veröffentlicht werden.", "Ruft mich an, wenn die Ergebnisse veröffentlicht werden."], explanation: "Plural in the wenn-clause: \"veröffentlicht werden\"." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "I don't know if the letter was sent.", answer: "Ich weiß nicht, ob der Brief geschickt wurde.", altAnswers: ["Ich weiß nicht, ob der Brief abgeschickt wurde.", "Ich weiß nicht, ob der Brief verschickt wurde."], explanation: "\"Ob\" + \"geschickt wurde\" at the end." },
      { type: "fill-blank", prompt: "Write the German for the bold words.", en: "I've heard that the film [is being shown] again.", sentence: "Ich habe gehört, dass der Film wieder ___.", answer: "gezeigt wird", explanation: "Participle + \"wird\" at the end." },
      { type: "fill-blank", prompt: "Write the German for the bold words.", en: "That's the house that [was sold] last year.", sentence: "Das ist das Haus, das letztes Jahr ___.", answer: "verkauft wurde", explanation: "Relative clause: \"verkauft wurde\"." },
      { type: "multiple-choice", question: "Which sentence is correct?", options: ["Ich weiß, dass das Problem gelöst wurde.", "Ich weiß, dass das Problem wurde gelöst.", "Ich weiß, dass wurde das Problem gelöst.", "Ich weiß, dass das Problem gelöst wird wurde."], correctIndex: 0, explanation: "Participle, then \"wurde\" at the end." },
      { type: "word-order", prompt: "Put the words in order to say: We're late because the road is being repaired.", words: ["Wir", "sind", "spät dran,", "weil", "die Straße", "repariert", "wird."], translation: "We're late because the road is being repaired.", explanation: "\"Repariert wird\" at the end of the weil-clause." },
      { type: "dictation", audio: "Das ist die Kirche, die 1200 gebaut wurde.", explanation: "Relative clause with past passive." },
      { type: "speak", text: "Ich habe gelesen, dass der Dieb gefunden wurde.", prompt: "Say it in German: I read that the thief was found.", explanation: "Dass-clause with \"gefunden wurde\" at the end." },
    ],
  },
  {
    slug: "b1-passive-extra-4",
    level: "DE-B1",
    number: 4,
    optional: true,
    title: "Extra Practice: Real-World Mission, The Newspaper Article",
    summary: "Write a local news report in the passive.",
    duration: "12 min",
    sections: [
      {
        heading: "Recap: the language of news",
        body: [
          "Local news reports use the Präteritum passive for what happened (\"wurde gemeldet\", \"wurden verletzt\") and the present passive for what is happening or planned (\"wird ermittelt\", \"wird repariert\"). Your mission: report a small incident in your town, a fire in a bakery, using the passive throughout.",
        ],
        examples: [
          { es: "Am Montagmorgen wurde ein Brand in einer Bäckerei gemeldet.", en: "On Monday morning a fire in a bakery was reported." },
          { es: "Die Feuerwehr wurde um 5 Uhr alarmiert.", en: "The fire brigade was alerted at 5 am." },
          { es: "Niemand wurde verletzt.", en: "Nobody was injured." },
          { es: "Die Ursache wird noch untersucht.", en: "The cause is still being investigated." },
          { es: "Die Bäckerei wird nächste Woche wieder geöffnet.", en: "The bakery will reopen next week." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "The cause is still being investigated.",
            answer: "Die Ursache wird noch untersucht.",
            altAnswers: ["Die Ursache wird noch ermittelt."],
            explanation: "Present passive for an ongoing process.",
          },
          {
            type: "listen-choose",
            audio: "Die Feuerwehr wurde um 5 Uhr alarmiert.",
            question: "What does it mean?",
            options: ["The fire brigade was alerted at 5 am.", "The fire brigade raised the alarm at 5 am.", "The fire brigade will be alerted at 5.", "The fire alarm rang at 5 am."],
            correctIndex: 0,
            explanation: "Past passive: \"wurde ... alarmiert\".",
          },
        ],
      },
    ],
    exercises: [
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "A fire was reported on Monday.", answer: "Am Montag wurde ein Brand gemeldet.", altAnswers: ["Ein Brand wurde am Montag gemeldet.", "Am Montag wurde ein Feuer gemeldet."], explanation: "\"Melden\" → \"gemeldet\"." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "The fire was quickly put out.", answer: "Das Feuer wurde schnell gelöscht.", altAnswers: ["Der Brand wurde schnell gelöscht."], explanation: "\"Löschen\" → \"gelöscht\"." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "Two firefighters were slightly injured.", answer: "Zwei Feuerwehrleute wurden leicht verletzt.", altAnswers: ["Zwei Feuerwehrmänner wurden leicht verletzt."], explanation: "Plural: \"wurden\"." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "The street was closed for three hours.", answer: "Die Straße wurde drei Stunden lang gesperrt.", altAnswers: ["Die Straße wurde für drei Stunden gesperrt."], explanation: "Duration: \"drei Stunden lang\"." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "The neighbours were evacuated.", answer: "Die Nachbarn wurden evakuiert.", explanation: "-ieren: \"evakuiert\"." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "The damage is estimated at 50,000 euros.", answer: "Der Schaden wird auf 50.000 Euro geschätzt.", explanation: "\"Schätzen auf\" + accusative: estimate at." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "The bakery is being renovated.", answer: "Die Bäckerei wird renoviert.", altAnswers: ["Die Bäckerei wird gerade renoviert."], explanation: "Present passive for an ongoing process." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "The owner was interviewed by our newspaper.", answer: "Der Besitzer wurde von unserer Zeitung interviewt.", altAnswers: ["Die Besitzerin wurde von unserer Zeitung interviewt.", "Der Inhaber wurde von unserer Zeitung interviewt.", "Die Inhaberin wurde von unserer Zeitung interviewt."], explanation: "Agent with \"von\" + dative." },
      { type: "fill-blank", prompt: "Write the German for the bold words.", en: "Nobody [was injured].", sentence: "Niemand ___.", answer: "wurde verletzt", explanation: "Past passive." },
      { type: "fill-blank", prompt: "Write the German for the bold words.", en: "The police said that the cause [is being investigated].", sentence: "Die Polizei sagte, dass die Ursache ___.", answer: "untersucht wird", altAnswers: ["ermittelt wird"], explanation: "Dass-clause: participle + \"wird\"." },
      { type: "matching", instructions: "Match the German with the English.", pairs: [{ left: "der Brand", right: "fire" }, { left: "löschen", right: "to put out" }, { left: "die Ursache", right: "cause" }, { left: "der Schaden", right: "damage" }, { left: "evakuieren", right: "to evacuate" }], explanation: "News vocabulary." },
      { type: "word-order", prompt: "Put the words in order to say: The bakery will be reopened next week.", words: ["Die Bäckerei", "wird", "nächste Woche", "wieder", "geöffnet."], translation: "The bakery will be reopened next week.", explanation: "Present passive with a future time." },
      { type: "dictation", audio: "Am Montagmorgen wurde ein Brand gemeldet.", explanation: "Past passive." },
      { type: "speak", text: "Niemand wurde verletzt, aber der Schaden ist groß.", prompt: "Say it in German: Nobody was injured, but the damage is great.", explanation: "Past passive + present active." },
    ],
  },
  {
    slug: "b1-passive-extra-5",
    level: "DE-B1",
    number: 5,
    optional: true,
    title: "Extra Practice: Error Hunt, The Passive",
    summary: "Fix typical passive mistakes: wird gebaut werden, ist gebaut for a process, and von der Sturm.",
    duration: "10 min",
    sections: [
      {
        heading: "Recap: three classic slips",
        body: [
          "Slip 1: *Das Haus wird gebaut werden*. One \"werden\" is enough in the present: \"Das Haus wird gebaut\". Slip 2: *Das Haus ist gebaut* for a process: use \"wird gebaut\". Slip 3: *Das Dach wurde von der Sturm zerstört*. \"Von\" takes the dative and \"der Sturm\" is masculine: \"vom Sturm\" (von dem). Also check \"wird\" vs \"werden\" agreement and the participle at the end.",
        ],
        examples: [
          { es: "Das Haus wird gebaut.", en: "The house is being built." },
          { es: "Das Dach wurde vom Sturm zerstört.", en: "The roof was destroyed by the storm." },
          { es: "Die Briefe werden morgen geschickt.", en: "The letters are being sent tomorrow." },
          { es: "Die Straße wird gerade repariert.", en: "The road is being repaired right now." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "A learner wrote \"Das Dach wurde von der Sturm zerstört.\" Translate the corrected sentence into German: The roof was destroyed by the storm.",
            source: "The roof was destroyed by the storm.",
            answer: "Das Dach wurde vom Sturm zerstört.",
            altAnswers: ["Das Dach wurde von dem Sturm zerstört.", "Das Dach wurde durch den Sturm zerstört."],
            explanation: "\"Von\" + dative masculine: \"vom Sturm\".",
          },
          {
            type: "listen-choose",
            audio: "Die Straße wird gerade repariert.",
            question: "What did you hear?",
            options: ["Die Straße wird gerade repariert.", "Die Straße ist gerade repariert.", "Die Straße wird gerade repariert werden.", "Die Straße wurde gerade repariert."],
            correctIndex: 0,
            explanation: "Present passive, one \"wird\".",
          },
        ],
      },
    ],
    exercises: [
      { type: "translate", direction: "en-es", prompt: "A learner wrote \"Die Schule wird renoviert werden.\" Translate the corrected sentence into German: The school is being renovated.", source: "The school is being renovated.", answer: "Die Schule wird renoviert.", altAnswers: ["Die Schule wird gerade renoviert."], explanation: "One \"wird\" + participle." },
      { type: "translate", direction: "en-es", prompt: "A learner wrote \"Das Auto ist gerade repariert.\" Translate the corrected sentence into German: The car is being repaired right now.", source: "The car is being repaired right now.", answer: "Das Auto wird gerade repariert.", explanation: "A process: \"wird\", not \"ist\"." },
      { type: "translate", direction: "en-es", prompt: "A learner wrote \"Die Fenster wird geputzt.\" Translate the corrected sentence into German: The windows are being cleaned.", source: "The windows are being cleaned.", answer: "Die Fenster werden geputzt.", altAnswers: ["Die Fenster werden gerade geputzt."], explanation: "Plural subject: \"werden\"." },
      { type: "translate", direction: "en-es", prompt: "A learner wrote \"Der Brief wurde geschrieben von meiner Schwester.\" Translate the corrected sentence into German: The letter was written by my sister.", source: "The letter was written by my sister.", answer: "Der Brief wurde von meiner Schwester geschrieben.", explanation: "The participle goes to the very end." },
      { type: "translate", direction: "en-es", prompt: "A learner wrote \"Den Kuchen wird gebacken.\" Translate the corrected sentence into German: The cake is being baked.", source: "The cake is being baked.", answer: "Der Kuchen wird gebacken.", explanation: "The passive subject is nominative: \"der Kuchen\"." },
      { type: "translate", direction: "en-es", prompt: "A learner wrote \"Ich weiß, dass das Paket wurde gebracht.\" Translate the corrected sentence into German: I know that the parcel was delivered.", source: "I know that the parcel was delivered.", answer: "Ich weiß, dass das Paket gebracht wurde.", altAnswers: ["Ich weiß, dass das Paket geliefert wurde."], explanation: "Subordinate clause: \"wurde\" last." },
      { type: "translate", direction: "en-es", prompt: "A learner wrote \"Die Brücke wurde in 1890 gebaut.\" Translate the corrected sentence into German: The bridge was built in 1890.", source: "The bridge was built in 1890.", answer: "Die Brücke wurde 1890 gebaut.", altAnswers: ["Die Brücke wurde im Jahr 1890 gebaut.", "1890 wurde die Brücke gebaut."], explanation: "No \"in\" before a year." },
      { type: "translate", direction: "en-es", prompt: "A learner wrote \"Das Essen wird von der Koch gekocht.\" Translate the corrected sentence into German: The food is cooked by the chef.", source: "The food is cooked by the chef.", answer: "Das Essen wird vom Koch gekocht.", altAnswers: ["Das Essen wird von dem Koch gekocht.", "Das Essen wird von der Köchin gekocht."], explanation: "\"Von\" + dative: \"vom Koch\" (masculine)." },
      { type: "fill-blank", prompt: "A learner wrote \"Die Kinder wird abgeholt.\" Write the German for the bold words.", en: "The children [are] picked up.", sentence: "Die Kinder ___ abgeholt.", answer: "werden", explanation: "Plural: \"werden\"." },
      { type: "fill-blank", prompt: "A learner wrote \"Das Fest wird gefeiert in Juni.\" Write the German for the bold words.", en: "The festival is [celebrated in June].", sentence: "Das Fest wird ___.", answer: "im Juni gefeiert", explanation: "\"Im Juni\" before the participle; months take \"im\"." },
      { type: "multiple-choice", question: "Which sentence is correct?", options: ["Die Stadt wurde vom Erdbeben zerstört.", "Die Stadt wurde von das Erdbeben zerstört.", "Die Stadt ist vom Erdbeben zerstört werden.", "Die Stadt wurde zerstört vom Erdbeben."], correctIndex: 0, explanation: "\"Vom\" (dative), participle at the end." },
      { type: "word-order", prompt: "Put the words in order to say: The window was smashed by a ball.", words: ["Das Fenster", "wurde", "von", "einem Ball", "eingeschlagen."], translation: "The window was smashed by a ball.", explanation: "Agent before the participle." },
      { type: "dictation", audio: "Das Dach wurde vom Sturm zerstört.", explanation: "\"Vom\" = von dem." },
      { type: "speak", text: "Die Schule wird renoviert.", prompt: "Say it in German: The school is being renovated.", explanation: "One \"wird\" + participle." },
    ],
  },
  {
    slug: "b1-passive-extra-6",
    level: "DE-B1",
    number: 6,
    optional: true,
    title: "Extra Practice: Dialogue Lab, In the Workshop",
    summary: "A mechanic explains what is being repaired and what was done.",
    duration: "10 min",
    sections: [
      {
        heading: "Recap: at the garage",
        body: [
          "Ayşe picks up her car at Herr Becker's workshop. He explains with the passive what is done and what was done: \"Die Bremsen wurden erneuert, das Öl wurde gewechselt, und die Reifen werden gerade noch geprüft.\" Ayşe asks with the passive too: \"Wurde auch das Licht kontrolliert?\"",
        ],
        examples: [
          { es: "Die Bremsen wurden erneuert.", en: "The brakes were replaced." },
          { es: "Das Öl wurde gewechselt.", en: "The oil was changed." },
          { es: "Die Reifen werden gerade geprüft.", en: "The tyres are being checked right now." },
          { es: "Wurde auch das Licht kontrolliert?", en: "Were the lights checked too?" },
          { es: "Das Auto wird bis 17 Uhr fertig gemacht.", en: "The car will be got ready by 5 pm." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "The oil was changed.",
            answer: "Das Öl wurde gewechselt.",
            explanation: "\"Wechseln\" → \"gewechselt\".",
          },
          {
            type: "listen-choose",
            audio: "Die Reifen werden gerade geprüft.",
            question: "What does it mean?",
            options: ["The tyres are being checked right now.", "The tyres were checked.", "The tyres need checking.", "The tyres have just been changed."],
            correctIndex: 0,
            explanation: "\"Werden gerade geprüft\": present passive, right now.",
          },
        ],
      },
    ],
    exercises: [
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "What was repaired?", answer: "Was wurde repariert?", explanation: "Past passive question." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "The brakes were replaced.", answer: "Die Bremsen wurden erneuert.", altAnswers: ["Die Bremsen wurden ausgetauscht.", "Die Bremsen wurden gewechselt."], explanation: "Plural: \"wurden\"." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "The car is being washed now.", answer: "Das Auto wird jetzt gewaschen.", altAnswers: ["Der Wagen wird jetzt gewaschen.", "Das Auto wird gerade gewaschen."], explanation: "Present passive." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "Were the tyres checked?", answer: "Wurden die Reifen geprüft?", altAnswers: ["Wurden die Reifen kontrolliert?", "Wurden die Reifen überprüft?"], explanation: "Yes/no question: \"Wurden\" first." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "The bill is sent by email.", answer: "Die Rechnung wird per E-Mail geschickt.", altAnswers: ["Die Rechnung wird per Mail geschickt.", "Die Rechnung wird per E-Mail verschickt."], explanation: "\"Per E-Mail\": by email." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "A new battery was installed.", answer: "Eine neue Batterie wurde eingebaut.", explanation: "\"Einbauen\" → \"eingebaut\"." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "The car will be ready at five.", answer: "Das Auto ist um fünf fertig.", altAnswers: ["Das Auto wird um fünf fertig sein.", "Der Wagen ist um fünf fertig.", "Das Auto ist um fünf Uhr fertig."], explanation: "A state (ready), so \"sein\" here, not the passive." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "The lights were also checked.", answer: "Das Licht wurde auch kontrolliert.", altAnswers: ["Die Lichter wurden auch kontrolliert.", "Die Beleuchtung wurde auch kontrolliert.", "Das Licht wurde auch geprüft."], explanation: "Past passive." },
      { type: "fill-blank", prompt: "Write the German for the bold words.", en: "The windscreen [was] cleaned.", sentence: "Die Windschutzscheibe ___ gereinigt.", answer: "wurde", explanation: "Singular past." },
      { type: "fill-blank", prompt: "Write the German for the bold words.", en: "Your car [is being] repaired.", sentence: "Ihr Auto ___ gerade repariert.", answer: "wird", explanation: "Present passive." },
      { type: "matching", instructions: "Match the German with the English.", pairs: [{ left: "die Bremse", right: "brake" }, { left: "der Reifen", right: "tyre" }, { left: "das Öl", right: "oil" }, { left: "die Werkstatt", right: "workshop, garage" }, { left: "die Batterie", right: "battery" }], explanation: "Car vocabulary." },
      { type: "word-order", prompt: "Put the words in order to say: The oil was changed yesterday.", words: ["Das Öl", "wurde", "gestern", "gewechselt."], translation: "The oil was changed yesterday.", explanation: "Past passive." },
      { type: "dictation", audio: "Die Bremsen wurden erneuert.", explanation: "Plural past passive." },
      { type: "speak", text: "Wurde auch das Licht kontrolliert?", prompt: "Ask the mechanic in German: Were the lights checked too?", explanation: "Question: \"Wurde\" first." },
    ],
  },
  {
    slug: "b1-passive-extra-7",
    level: "DE-B1",
    number: 7,
    optional: true,
    title: "Extra Practice: Your Recipe in the Passive",
    summary: "Write a family recipe step by step with Zuerst wird...",
    duration: "10 min",
    sections: [
      {
        heading: "Recap: recipes as processes",
        body: [
          "A recipe can be written in three ways: imperative (\"Schneiden Sie die Zwiebeln\"), infinitive (\"Zwiebeln schneiden\") or passive (\"Die Zwiebeln werden geschnitten\"). The passive sounds like a description of how it's done in your family: \"Bei uns wird die Soße immer am Vortag gekocht\". Order the steps with \"zuerst\", \"dann\", \"danach\", \"zum Schluss\".",
        ],
        examples: [
          { es: "Zuerst werden die Kartoffeln geschält.", en: "First the potatoes are peeled." },
          { es: "Dann werden die Zwiebeln klein geschnitten.", en: "Then the onions are chopped finely." },
          { es: "Danach wird alles in der Pfanne gebraten.", en: "After that everything is fried in the pan." },
          { es: "Bei uns wird die Soße immer am Vortag gekocht.", en: "In our family the sauce is always made the day before." },
          { es: "Zum Schluss wird alles mit Petersilie bestreut.", en: "Finally everything is sprinkled with parsley." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "First the potatoes are peeled.",
            answer: "Zuerst werden die Kartoffeln geschält.",
            explanation: "Plural: \"werden\"; \"schälen\" → \"geschält\".",
          },
          {
            type: "listen-choose",
            audio: "Bei uns wird die Soße immer am Vortag gekocht.",
            question: "What does it mean?",
            options: ["In our family the sauce is always made the day before.", "We always cook the sauce on the day.", "The sauce was cooked yesterday.", "Our sauce is cooked for a whole day."],
            correctIndex: 0,
            explanation: "\"Am Vortag\": the day before.",
          },
        ],
      },
    ],
    exercises: [
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "Then the onions are chopped.", answer: "Dann werden die Zwiebeln geschnitten.", altAnswers: ["Dann werden die Zwiebeln klein geschnitten.", "Danach werden die Zwiebeln geschnitten."], explanation: "Plural: \"werden\"." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "The water is brought to the boil.", answer: "Das Wasser wird zum Kochen gebracht.", explanation: "Fixed phrase: \"zum Kochen bringen\"." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "The pasta is cooked for ten minutes.", answer: "Die Nudeln werden zehn Minuten gekocht.", altAnswers: ["Die Nudeln werden zehn Minuten lang gekocht.", "Die Pasta wird zehn Minuten gekocht."], explanation: "\"Die Nudeln\" plural: \"werden\"." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "The meat is fried in butter.", answer: "Das Fleisch wird in Butter gebraten.", explanation: "\"Braten\" → \"gebraten\"." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "The eggs are beaten.", answer: "Die Eier werden geschlagen.", altAnswers: ["Die Eier werden verquirlt."], explanation: "\"Schlagen\" → \"geschlagen\"." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "Finally the cake is decorated.", answer: "Zum Schluss wird der Kuchen dekoriert.", altAnswers: ["Zum Schluss wird der Kuchen verziert.", "Am Ende wird der Kuchen dekoriert."], explanation: "Step word first." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "Salt and pepper are added.", answer: "Salz und Pfeffer werden dazugegeben.", altAnswers: ["Salz und Pfeffer werden hinzugefügt.", "Es werden Salz und Pfeffer dazugegeben."], explanation: "Two nouns: plural \"werden\"." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "The soup is served hot.", answer: "Die Suppe wird heiß serviert.", explanation: "\"Serviert\": no ge-." },
      { type: "fill-blank", prompt: "Write the German for the bold words.", en: "The dough [is] rolled out.", sentence: "Der Teig ___ ausgerollt.", answer: "wird", explanation: "Singular." },
      { type: "fill-blank", prompt: "Write the German for the bold words.", en: "The apples are [peeled] and cut.", sentence: "Die Äpfel werden ___ und geschnitten.", answer: "geschält", explanation: "\"Schälen\" → \"geschält\"." },
      { type: "word-order", prompt: "Put the words in order to say: After that everything is mixed well.", words: ["Danach", "wird", "alles", "gut", "gemischt."], translation: "After that everything is mixed well.", explanation: "\"Alles\" is singular: \"wird\"." },
      { type: "multiple-choice", question: "Which recipe step is correct?", options: ["Dann werden die Tomaten gewaschen.", "Dann wird die Tomaten gewaschen.", "Dann die Tomaten werden gewaschen.", "Dann werden die Tomaten waschen."], correctIndex: 0, explanation: "Step word, \"werden\", subject, participle." },
      { type: "dictation", audio: "Zuerst werden die Kartoffeln geschält.", explanation: "Plural present passive." },
      { type: "speak", text: "Zum Schluss wird alles mit Petersilie bestreut.", prompt: "Say it in German: Finally everything is sprinkled with parsley.", explanation: "\"Bestreuen\" → \"bestreut\" (no ge-)." },
    ],
  },
  {
    slug: "b1-passive-extra-8",
    level: "DE-B1",
    number: 8,
    optional: true,
    title: "Extra Practice: Werden, Three Ways",
    summary: "Become, future or passive: spot which werden you have and translate it.",
    duration: "10 min",
    sections: [
      {
        heading: "Recap: one verb, three jobs",
        body: [
          "\"Werden\" alone or with an adjective or noun means become: \"Es wird kalt\", \"Sie wird Ärztin\". With an infinitive at the end it makes the future: \"Ich werde morgen anrufen\". With a participle at the end it makes the passive: \"Das Haus wird renoviert\". Always look at the last word of the clause to decide.",
        ],
        examples: [
          { es: "Im Herbst wird es früh dunkel.", en: "In autumn it gets dark early." },
          { es: "Meine Schwester wird Lehrerin.", en: "My sister is becoming a teacher." },
          { es: "Wir werden nächstes Jahr umziehen.", en: "We will move next year." },
          { es: "Die Straße wird nächste Woche gesperrt.", en: "The road is being closed next week." },
          { es: "Er wird bestimmt müde sein.", en: "He'll surely be tired." },
          { es: "Hier wird nicht geraucht.", en: "There's no smoking here." },
        ],
        checkpoint: [
          { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "It's getting cold.", answer: "Es wird kalt.", explanation: "\"Werden\" + adjective: become." },
          { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "The road is being closed.", answer: "Die Straße wird gesperrt.", explanation: "\"Werden\" + participle: passive." },
          { type: "listen-choose", audio: "Wir werden nächstes Jahr umziehen.", question: "What does it mean?", options: ["We will move next year.", "We were moved last year.", "We are becoming movers.", "We moved last year."], correctIndex: 0, explanation: "Infinitive at the end: future." },
        ],
      },
    ],
    exercises: [
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "My brother wants to become a doctor.", answer: "Mein Bruder will Arzt werden.", altAnswers: ["Mein Bruder möchte Arzt werden."], explanation: "\"Werden\" + noun: become." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "I will call you tomorrow.", answer: "Ich werde dich morgen anrufen.", altAnswers: ["Ich werde Sie morgen anrufen.", "Ich werde euch morgen anrufen."], explanation: "Future: \"werden\" + infinitive." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "The windows are cleaned every month.", answer: "Die Fenster werden jeden Monat geputzt.", altAnswers: ["Die Fenster werden jeden Monat gereinigt.", "Jeden Monat werden die Fenster geputzt."], explanation: "Passive: participle at the end." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "The children are getting tired.", answer: "Die Kinder werden müde.", explanation: "Become + adjective." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "The museum will open in May.", answer: "Das Museum wird im Mai öffnen.", altAnswers: ["Das Museum wird im Mai eröffnen.", "Das Museum öffnet im Mai."], explanation: "Future with an infinitive." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "The museum is being opened in May.", answer: "Das Museum wird im Mai eröffnet.", altAnswers: ["Das Museum wird im Mai geöffnet."], explanation: "Participle: passive." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "She became very famous.", answer: "Sie wurde sehr berühmt.", altAnswers: ["Sie ist sehr berühmt geworden."], explanation: "Past of become: \"wurde\"." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "The bridge was built in 1900.", answer: "Die Brücke wurde 1900 gebaut.", altAnswers: ["Die Brücke wurde im Jahr 1900 gebaut."], explanation: "\"Wurde\" + participle: past passive." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "It will be late.", answer: "Es wird spät werden.", altAnswers: ["Es wird spät."], explanation: "Future of become: \"wird ... werden\"." },
      { type: "fill-blank", prompt: "Write the German for the bold words.", en: "The letters [are] sent today.", sentence: "Die Briefe ___ heute verschickt.", answer: "werden", explanation: "Plural passive." },
      { type: "fill-blank", prompt: "Write the German for the bold words.", en: "I [will] help you.", sentence: "Ich ___ dir helfen.", answer: "werde", explanation: "Future, first person." },
      { type: "word-order", prompt: "Put the words in order to say: The car is being repaired today.", words: ["Das Auto", "wird", "heute", "repariert."], translation: "The car is being repaired today.", explanation: "Passive: participle last." },
      { type: "multiple-choice", question: "Which sentence means: She is becoming a nurse.", options: ["Sie wird Krankenpflegerin.", "Sie wird Krankenpflegerin sein.", "Sie wurde Krankenpflegerin.", "Sie wird gepflegt."], correctIndex: 0, explanation: "Present of become." },
      { type: "dictation", audio: "Im Winter wird es früh dunkel.", explanation: "\"Werden\" + adjective." },
      { type: "speak", text: "Die Straße wird nächste Woche gesperrt.", prompt: "Say it in German: The road is being closed next week.", explanation: "Passive." },
    ],
  },
  {
    slug: "b1-passive-extra-9",
    level: "DE-B1",
    number: 9,
    optional: true,
    title: "Extra Practice: Fix the Paragraph, Signs with Errors",
    summary: "Correct notices full of passive mistakes.",
    duration: "10 min",
    sections: [
      {
        heading: "Recap: the usual sign mistakes",
        body: [
          "Notices are full of passives, and the same mistakes keep appearing: the wrong form of \"werden\" for plural subjects (\"Die Türen wird geschlossen\"), the participle in the wrong place, an extra \"geworden\", or \"von\" without its dative. Check the subject, then \"werden\", then the participle at the end.",
        ],
        examples: [
          { es: "Die Türen werden um 22 Uhr geschlossen.", en: "The doors are locked at 10 p.m." },
          { es: "Der Müll wird montags abgeholt.", en: "The rubbish is collected on Mondays." },
          { es: "Fahrräder im Flur werden entfernt.", en: "Bicycles in the hallway will be removed." },
          { es: "Das Treppenhaus wird am Freitag gereinigt.", en: "The stairwell is cleaned on Friday." },
          { es: "Der Kurs wurde vom Lehrer abgesagt.", en: "The course was cancelled by the teacher." },
        ],
        checkpoint: [
          { type: "translate", direction: "en-es", prompt: "Correct the sign \"Die Türen wird um 22 Uhr geschlossen.\" Translate: The doors are locked at 10 p.m.", source: "The doors are locked at 10 p.m.", answer: "Die Türen werden um 22 Uhr geschlossen.", altAnswers: ["Um 22 Uhr werden die Türen geschlossen."], explanation: "Plural subject: \"werden\"." },
          { type: "translate", direction: "en-es", prompt: "Correct the sign \"Der Müll wird abgeholt montags.\" Translate: The rubbish is collected on Mondays.", source: "The rubbish is collected on Mondays.", answer: "Der Müll wird montags abgeholt.", altAnswers: ["Montags wird der Müll abgeholt."], explanation: "Participle at the end." },
        ],
      },
    ],
    exercises: [
      { type: "translate", direction: "en-es", prompt: "Correct the sign \"Die Heizung wird morgen repariert geworden.\" Translate: The heating is being repaired tomorrow.", source: "The heating is being repaired tomorrow.", answer: "Die Heizung wird morgen repariert.", explanation: "Present passive needs no extra participle." },
      { type: "translate", direction: "en-es", prompt: "Correct the sign \"Die Fenster wird jeden Freitag geputzt.\" Translate: The windows are cleaned every Friday.", source: "The windows are cleaned every Friday.", answer: "Die Fenster werden jeden Freitag geputzt.", altAnswers: ["Jeden Freitag werden die Fenster geputzt."], explanation: "Plural: \"werden\"." },
      { type: "translate", direction: "en-es", prompt: "Correct the sign \"Das Bad wird renoviert von die Firma Huber.\" Translate: The bathroom is being renovated by the Huber company.", source: "The bathroom is being renovated by the Huber company.", answer: "Das Bad wird von der Firma Huber renoviert.", explanation: "\"Von\" + dative, participle last." },
      { type: "translate", direction: "en-es", prompt: "Correct the sign \"Hier wird nicht parken.\" Translate: No parking here.", source: "No parking here.", answer: "Hier wird nicht geparkt.", altAnswers: ["Hier darf nicht geparkt werden."], explanation: "Passive needs the participle." },
      { type: "translate", direction: "en-es", prompt: "Correct the sign \"Der Aufzug wurde gestern reparieren.\" Translate: The lift was repaired yesterday.", source: "The lift was repaired yesterday.", answer: "Der Aufzug wurde gestern repariert.", altAnswers: ["Der Fahrstuhl wurde gestern repariert."], explanation: "\"Wurde\" + participle." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "Bicycles in the hallway will be removed.", answer: "Fahrräder im Flur werden entfernt.", altAnswers: ["Fahrräder im Hausflur werden entfernt."], explanation: "Plural passive." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "The office is closed on Saturday.", answer: "Das Büro ist am Samstag geschlossen.", altAnswers: ["Am Samstag ist das Büro geschlossen.", "Das Büro wird am Samstag geschlossen."], explanation: "A state: \"ist geschlossen\"." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "Parcels are accepted at reception.", answer: "Pakete werden an der Rezeption angenommen.", altAnswers: ["Pakete werden am Empfang angenommen."], explanation: "\"Annehmen\" → \"angenommen\"." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "The meeting was cancelled by the boss.", answer: "Die Besprechung wurde vom Chef abgesagt.", altAnswers: ["Das Meeting wurde vom Chef abgesagt.", "Die Besprechung wurde von der Chefin abgesagt."], explanation: "\"Vom\" = \"von dem\"." },
      { type: "fill-blank", prompt: "Write the German for the bold words.", en: "The stairs [are] cleaned on Fridays.", sentence: "Die Treppen ___ freitags gereinigt.", answer: "werden", explanation: "Plural subject." },
      { type: "fill-blank", prompt: "Write the German for the bold words.", en: "The water is [turned off] today.", sentence: "Das Wasser wird heute ___.", answer: "abgestellt", altAnswers: ["abgedreht"], explanation: "Participle last." },
      { type: "word-order", prompt: "Put the words in order to say: The rubbish is collected on Tuesdays.", words: ["Der Müll", "wird", "dienstags", "abgeholt."], translation: "The rubbish is collected on Tuesdays.", explanation: "Participle last." },
      { type: "multiple-choice", question: "Which sign is correct?", options: ["Die Tür wird um 20 Uhr abgeschlossen.", "Die Tür werden um 20 Uhr abgeschlossen.", "Die Tür wird abgeschlossen um 20 Uhr.", "Die Tür wird um 20 Uhr abschließen."], correctIndex: 0, explanation: "Singular \"wird\", participle last." },
      { type: "listen-choose", audio: "Fahrräder im Flur werden entfernt.", question: "What does the notice say?", options: ["Bicycles in the hallway will be removed.", "Bicycles may be left in the hallway.", "The hallway is being repaired.", "Bicycles were stolen from the hallway."], correctIndex: 0, explanation: "\"Entfernen\": remove." },
      { type: "speak", text: "Der Müll wird montags abgeholt.", prompt: "Say it in German: The rubbish is collected on Mondays.", explanation: "Participle last." },
    ],
  },
  {
    slug: "b1-passive-extra-10",
    level: "DE-B1",
    number: 10,
    optional: true,
    title: "Extra Practice: Dictation, How We Recycle",
    summary: "A dictated text about Mülltrennung in the passive.",
    duration: "10 min",
    sections: [
      {
        heading: "Recap: Mülltrennung",
        body: [
          "In Germany rubbish is sorted carefully: paper goes in \"die blaue Tonne\", packaging in \"der gelbe Sack\" or \"die gelbe Tonne\", food waste in \"die Biotonne\" and everything else in \"der Restmüll\". Glass is taken to \"der Glascontainer\" and bottles with \"das Pfand\" are returned to the shop. Describing this system is a classic passive text.",
        ],
        examples: [
          { es: "Papier wird in die blaue Tonne geworfen.", en: "Paper is thrown in the blue bin." },
          { es: "Verpackungen werden im gelben Sack gesammelt.", en: "Packaging is collected in the yellow bag." },
          { es: "Glas wird nach Farben getrennt.", en: "Glass is separated by colour." },
          { es: "Pfandflaschen werden im Supermarkt zurückgegeben.", en: "Deposit bottles are returned at the supermarket." },
          { es: "Die Biotonne wird jede Woche geleert.", en: "The organic waste bin is emptied every week." },
        ],
        checkpoint: [
          { type: "dictation", audio: "Papier wird in die blaue Tonne geworfen.", explanation: "Singular passive." },
          { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "Glass is separated by colour.", answer: "Glas wird nach Farben getrennt.", altAnswers: ["Das Glas wird nach Farben getrennt.", "Glas wird nach Farbe getrennt."], explanation: "\"Trennen\" → \"getrennt\"." },
        ],
      },
    ],
    exercises: [
      { type: "dictation", audio: "Verpackungen werden im gelben Sack gesammelt.", explanation: "Plural passive." },
      { type: "dictation", audio: "Pfandflaschen werden im Supermarkt zurückgegeben.", explanation: "\"Zurückgeben\" → \"zurückgegeben\"." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "Rubbish is sorted carefully in Germany.", answer: "In Deutschland wird Müll sorgfältig getrennt.", altAnswers: ["Müll wird in Deutschland sorgfältig getrennt.", "In Deutschland wird der Müll sorgfältig getrennt.", "In Deutschland wird Müll genau getrennt."], explanation: "\"Mülltrennung\": separating rubbish." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "Food waste is put in the organic bin.", answer: "Essensreste werden in die Biotonne geworfen.", altAnswers: ["Essensreste kommen in die Biotonne.", "Lebensmittelreste werden in die Biotonne geworfen."], explanation: "Plural passive." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "The bins are emptied every two weeks.", answer: "Die Tonnen werden alle zwei Wochen geleert.", altAnswers: ["Die Mülltonnen werden alle zwei Wochen geleert."], explanation: "\"Alle zwei Wochen\": every two weeks." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "Glass is taken to the bottle bank.", answer: "Glas wird zum Glascontainer gebracht.", altAnswers: ["Glas wird in den Glascontainer gebracht.", "Das Glas wird zum Glascontainer gebracht."], explanation: "\"Bringen\" → \"gebracht\"." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "Paper is recycled.", answer: "Papier wird recycelt.", altAnswers: ["Das Papier wird recycelt.", "Papier wird wiederverwertet."], explanation: "\"Recyceln\" → \"recycelt\"." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "Batteries are collected separately.", answer: "Batterien werden getrennt gesammelt.", altAnswers: ["Batterien werden extra gesammelt."], explanation: "Plural passive." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "The yellow bag is collected on Thursday.", answer: "Der gelbe Sack wird am Donnerstag abgeholt.", altAnswers: ["Der gelbe Sack wird donnerstags abgeholt."], explanation: "\"Abholen\" → \"abgeholt\"." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "Old clothes are put in the container.", answer: "Alte Kleidung wird in den Container gegeben.", altAnswers: ["Alte Kleidung wird in den Altkleidercontainer gegeben.", "Alte Kleider werden in den Container gegeben.", "Alte Kleidung wird in den Container geworfen."], explanation: "\"Kleidung\" is singular: \"wird\"." },
      { type: "fill-blank", prompt: "Write the German for the bold words.", en: "The bottles [are returned].", sentence: "Die Flaschen werden ___.", answer: "zurückgegeben", explanation: "Separable participle." },
      { type: "fill-blank", prompt: "Write the German for the bold words.", en: "Plastic [is] collected in the yellow bin.", sentence: "Plastik ___ in der gelben Tonne gesammelt.", answer: "wird", explanation: "Singular." },
      { type: "word-order", prompt: "Put the words in order to say: Paper is thrown in the blue bin.", words: ["Papier", "wird", "in die", "blaue Tonne", "geworfen."], translation: "Paper is thrown in the blue bin.", explanation: "Participle last." },
      { type: "listen-choose", audio: "Die Biotonne wird jede Woche geleert.", question: "What happens every week?", options: ["The organic bin is emptied.", "The organic bin is cleaned.", "The yellow bag is collected.", "The bottles are returned."], correctIndex: 0, explanation: "\"Leeren\": empty." },
      { type: "speak", text: "Bei uns wird der Müll genau getrennt.", prompt: "Say it in German: At our place the rubbish is sorted precisely.", explanation: "\"Bei uns\": at our place." },
    ],
  },
  {
    slug: "b1-passive-extra-11",
    level: "DE-B1",
    number: 11,
    optional: true,
    title: "Extra Practice: Inventions and Discoveries",
    summary: "Ask and answer Wann wurde... erfunden? questions.",
    duration: "10 min",
    sections: [
      {
        heading: "Recap: history in the Präteritum passive",
        body: [
          "History is told with \"wurde/wurden\" + participle: \"Das Telefon wurde 1876 erfunden\". Useful participles: \"erfunden\" (invented), \"entdeckt\" (discovered), \"entwickelt\" (developed), \"gegründet\" (founded), \"gebaut\" (built). Years stand alone or with \"im Jahr\", never with a bare \"in\". The inventor comes in with \"von\" + dative.",
        ],
        examples: [
          { es: "Wann wurde das Auto erfunden?", en: "When was the car invented?" },
          { es: "Das Auto wurde 1886 von Carl Benz erfunden.", en: "The car was invented in 1886 by Carl Benz." },
          { es: "Amerika wurde 1492 entdeckt.", en: "America was discovered in 1492." },
          { es: "Der Buchdruck wurde von Gutenberg entwickelt.", en: "Printing was developed by Gutenberg." },
          { es: "Die Firma wurde im Jahr 1923 gegründet.", en: "The company was founded in 1923." },
        ],
        checkpoint: [
          { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "When was the telephone invented?", answer: "Wann wurde das Telefon erfunden?", explanation: "Question word, \"wurde\", subject, participle." },
          { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "The company was founded in 1923.", answer: "Die Firma wurde 1923 gegründet.", altAnswers: ["Die Firma wurde im Jahr 1923 gegründet.", "Das Unternehmen wurde 1923 gegründet."], explanation: "No bare \"in\" before a year." },
        ],
      },
    ],
    exercises: [
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "The car was invented by Carl Benz.", answer: "Das Auto wurde von Carl Benz erfunden.", explanation: "\"Von\" + inventor." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "When was penicillin discovered?", answer: "Wann wurde das Penicillin entdeckt?", altAnswers: ["Wann wurde Penicillin entdeckt?"], explanation: "\"Entdecken\" → \"entdeckt\"." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "Penicillin was discovered in 1928.", answer: "Das Penicillin wurde 1928 entdeckt.", altAnswers: ["Penicillin wurde 1928 entdeckt.", "Penicillin wurde im Jahr 1928 entdeckt."], explanation: "Year without \"in\"." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "The Berlin Wall was built in 1961.", answer: "Die Berliner Mauer wurde 1961 gebaut.", altAnswers: ["Die Berliner Mauer wurde im Jahr 1961 gebaut.", "Die Mauer wurde 1961 gebaut."], explanation: "\"Bauen\" → \"gebaut\"." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "Who was the light bulb invented by?", answer: "Von wem wurde die Glühbirne erfunden?", explanation: "\"Von wem\": by whom." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "The first computers were developed in the 1940s.", answer: "Die ersten Computer wurden in den 1940er-Jahren entwickelt.", altAnswers: ["Die ersten Computer wurden in den Vierzigerjahren entwickelt.", "Die ersten Computer wurden in den 1940er Jahren entwickelt."], explanation: "Plural: \"wurden\"." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "The university was founded in 1386.", answer: "Die Universität wurde 1386 gegründet.", altAnswers: ["Die Universität wurde im Jahr 1386 gegründet.", "Die Uni wurde 1386 gegründet."], explanation: "\"Gründen\" → \"gegründet\"." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "Where was the bicycle invented?", answer: "Wo wurde das Fahrrad erfunden?", explanation: "\"Wo\" + \"wurde\"." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "X-rays were discovered by Röntgen.", answer: "Die Röntgenstrahlen wurden von Röntgen entdeckt.", altAnswers: ["Röntgenstrahlen wurden von Röntgen entdeckt.", "Die Röntgenstrahlen wurden von Wilhelm Röntgen entdeckt."], explanation: "Plural: \"wurden\"." },
      { type: "fill-blank", prompt: "Write the German for the bold words.", en: "The radio was [invented] in the 19th century.", sentence: "Das Radio wurde im 19. Jahrhundert ___.", answer: "erfunden", explanation: "Irregular participle of \"erfinden\"." },
      { type: "fill-blank", prompt: "Write the German for the bold words.", en: "The first trains [were] built in England.", sentence: "Die ersten Züge ___ in England gebaut.", answer: "wurden", explanation: "Plural past." },
      { type: "word-order", prompt: "Put the words in order to say: When was the city founded?", words: ["Wann", "wurde", "die Stadt", "gegründet?"], translation: "When was the city founded?", explanation: "Participle last." },
      { type: "multiple-choice", question: "Which sentence is correct?", options: ["Das Telefon wurde 1876 erfunden.", "Das Telefon wurde in 1876 erfunden.", "Das Telefon wird 1876 erfunden worden.", "Das Telefon wurde 1876 erfindet."], correctIndex: 0, explanation: "Year alone, participle \"erfunden\"." },
      { type: "listen-choose", audio: "Der Buchdruck wurde von Gutenberg entwickelt.", question: "What does it mean?", options: ["Printing was developed by Gutenberg.", "Gutenberg printed a book.", "Printing is being developed.", "The book was printed for Gutenberg."], correctIndex: 0, explanation: "\"Von\" + agent." },
      { type: "speak", text: "Wann wurde das Auto erfunden?", prompt: "Say it in German: When was the car invented?", explanation: "Past passive question." },
    ],
  },
  {
    slug: "b1-passive-extra-12",
    level: "DE-B1",
    number: 12,
    optional: true,
    title: "Extra Practice: Man or Passive?",
    summary: "Choose the more natural form for speech or writing.",
    duration: "10 min",
    sections: [
      {
        heading: "Recap: spoken man, written passive",
        body: [
          "Both \"man\" and the passive hide the person who acts. In conversation \"man\" sounds lighter: \"Hier spricht man Deutsch\". In notices, reports and instructions the passive sounds more formal: \"Hier wird Deutsch gesprochen\". Remember that \"man\" takes a singular verb and the object stays accusative: \"Man repariert den Wagen\" becomes \"Der Wagen wird repariert\".",
        ],
        examples: [
          { es: "Man isst hier viel Fisch.", en: "People eat a lot of fish here." },
          { es: "Hier wird viel Fisch gegessen.", en: "A lot of fish is eaten here." },
          { es: "Wie schreibt man das?", en: "How do you spell that?" },
          { es: "Anträge werden online gestellt.", en: "Applications are submitted online." },
          { es: "Man hat mir nichts gesagt.", en: "Nobody told me anything." },
        ],
        checkpoint: [
          { type: "translate", direction: "en-es", prompt: "Translate into German with man (conversation).", source: "How do you say that in German?", answer: "Wie sagt man das auf Deutsch?", explanation: "Natural in speech." },
          { type: "translate", direction: "en-es", prompt: "Translate into German with the passive (a notice).", source: "Applications are submitted online.", answer: "Anträge werden online gestellt.", altAnswers: ["Die Anträge werden online gestellt."], explanation: "Formal written style." },
        ],
      },
    ],
    exercises: [
      { type: "translate", direction: "en-es", prompt: "Translate into German with man.", source: "People drink a lot of beer here.", answer: "Hier trinkt man viel Bier.", altAnswers: ["Man trinkt hier viel Bier."], explanation: "Singular verb with \"man\"." },
      { type: "translate", direction: "en-es", prompt: "Translate into German with the passive.", source: "A lot of beer is drunk here.", answer: "Hier wird viel Bier getrunken.", altAnswers: ["Viel Bier wird hier getrunken."], explanation: "\"Trinken\" → \"getrunken\"." },
      { type: "translate", direction: "en-es", prompt: "Translate into German with man.", source: "How do you spell your name?", answer: "Wie schreibt man Ihren Namen?", altAnswers: ["Wie schreibt man deinen Namen?"], explanation: "Spoken question with \"man\"." },
      { type: "translate", direction: "en-es", prompt: "Translate into German with the passive (a notice).", source: "Payment is made at the till.", answer: "An der Kasse wird bezahlt.", altAnswers: ["Bezahlt wird an der Kasse.", "Es wird an der Kasse bezahlt."], explanation: "Passive without a subject." },
      { type: "translate", direction: "en-es", prompt: "Translate into German with man.", source: "You can't park here.", answer: "Hier kann man nicht parken.", altAnswers: ["Man kann hier nicht parken.", "Hier darf man nicht parken."], explanation: "\"Man\" + modal." },
      { type: "translate", direction: "en-es", prompt: "Translate into German with the passive.", source: "The forms are checked by the office.", answer: "Die Formulare werden vom Amt geprüft.", altAnswers: ["Die Formulare werden vom Amt kontrolliert.", "Die Formulare werden von der Behörde geprüft."], explanation: "With an agent you need the passive." },
      { type: "translate", direction: "en-es", prompt: "Translate into German with man.", source: "Nobody asked me.", answer: "Man hat mich nicht gefragt.", altAnswers: ["Mich hat niemand gefragt.", "Niemand hat mich gefragt."], explanation: "\"Man\" in the Perfekt." },
      { type: "translate", direction: "en-es", prompt: "Translate into German with the passive.", source: "German is spoken here.", answer: "Hier wird Deutsch gesprochen.", explanation: "Classic sign." },
      { type: "translate", direction: "en-es", prompt: "Translate into German with man.", source: "In Bavaria people celebrate a lot.", answer: "In Bayern feiert man viel.", altAnswers: ["Man feiert in Bayern viel.", "In Bayern wird viel gefeiert."], explanation: "\"Man\" + singular verb." },
      { type: "fill-blank", prompt: "Write the German for the bold words.", en: "The car [is] repaired.", sentence: "Der Wagen ___ repariert.", answer: "wird", explanation: "\"Man repariert den Wagen\": the accusative object becomes the subject." },
      { type: "fill-blank", prompt: "Write the German for the bold words.", en: "[People] often say that.", sentence: "Das sagt ___ oft.", answer: "man", explanation: "Spoken style." },
      { type: "word-order", prompt: "Put the words in order to say: Here people work a lot.", words: ["Hier", "arbeitet", "man", "viel."], translation: "Here people work a lot.", explanation: "Verb second, \"man\" after it." },
      { type: "multiple-choice", question: "Which version suits an official notice best?", options: ["Anträge werden nur online angenommen.", "Man nimmt Anträge nur online, ne?", "Wir nehmen die Anträge halt online.", "Anträge nimmt man so online."], correctIndex: 0, explanation: "Formal: passive." },
      { type: "listen-choose", audio: "Wie schreibt man das?", question: "What does it mean?", options: ["How do you spell that?", "Who wrote that?", "How is that written by a man?", "Where do you write that?"], correctIndex: 0, explanation: "\"Man\": you, in general." },
      { type: "speak", text: "Hier wird Deutsch gesprochen.", prompt: "Say it in German: German is spoken here.", explanation: "Passive." },
    ],
  },
  {
    slug: "b1-passive-extra-13",
    level: "DE-B1",
    number: 13,
    optional: true,
    title: "Extra Practice: Mir wurde gesagt",
    summary: "The passive with a dative and no subject: Mir wurde geholfen, Uns wurde gesagt.",
    duration: "10 min",
    sections: [
      {
        heading: "Recap: the dative stays dative",
        body: [
          "Verbs with a dative object (\"helfen\", \"danken\", \"sagen\", \"erklären\", \"antworten\") keep the dative in the passive. The person never becomes the subject: \"Man hilft mir\" becomes \"Mir wird geholfen\", not \"Ich werde geholfen\". When there is no subject, \"werden\" stays in the third person singular.",
          "If a sentence has both a dative and an accusative, the accusative becomes the subject: \"Man hat uns die Regeln erklärt\" becomes \"Uns wurden die Regeln erklärt\".",
        ],
        examples: [
          { es: "Mir wurde geholfen.", en: "I was helped." },
          { es: "Uns wurde gesagt, dass der Zug ausfällt.", en: "We were told that the train is cancelled." },
          { es: "Ihm wird oft widersprochen.", en: "He's often contradicted." },
          { es: "Den Gästen wurde gedankt.", en: "The guests were thanked." },
          { es: "Uns wurden die Regeln erklärt.", en: "The rules were explained to us." },
        ],
        checkpoint: [
          { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "I was helped.", answer: "Mir wurde geholfen.", explanation: "Dative stays dative; never use the nominative pronoun." },
          { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "We were told nothing.", answer: "Uns wurde nichts gesagt.", altAnswers: ["Uns hat man nichts gesagt.", "Man hat uns nichts gesagt."], explanation: "\"Nichts\" is the subject: singular." },
          { type: "listen-choose", audio: "Uns wurde gesagt, dass der Zug ausfällt.", question: "What happened?", options: ["We were told that the train is cancelled.", "We told them the train is cancelled.", "We were helped onto the train.", "Our train was late."], correctIndex: 0, explanation: "\"Uns wurde gesagt\": we were told." },
        ],
      },
    ],
    exercises: [
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "She was helped quickly.", answer: "Ihr wurde schnell geholfen.", explanation: "\"Helfen\" + dative." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "We were told that the shop is closed.", answer: "Uns wurde gesagt, dass das Geschäft geschlossen ist.", altAnswers: ["Uns wurde gesagt, dass der Laden geschlossen ist.", "Man hat uns gesagt, dass das Geschäft geschlossen ist."], explanation: "\"Uns wurde gesagt\" + \"dass\"." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "I was told nothing.", answer: "Mir wurde nichts gesagt.", altAnswers: ["Man hat mir nichts gesagt."], explanation: "Dative \"mir\"." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "The volunteers were thanked.", answer: "Den Freiwilligen wurde gedankt.", altAnswers: ["Den Ehrenamtlichen wurde gedankt."], explanation: "\"Danken\" + dative plural." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "The task was explained to me.", answer: "Mir wurde die Aufgabe erklärt.", altAnswers: ["Die Aufgabe wurde mir erklärt."], explanation: "\"Die Aufgabe\" is the subject." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "The rules were explained to us.", answer: "Uns wurden die Regeln erklärt.", altAnswers: ["Die Regeln wurden uns erklärt."], explanation: "Plural subject: \"wurden\"." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "He was never answered.", answer: "Ihm wurde nie geantwortet.", explanation: "\"Antworten\" + dative." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "We were helped by our neighbours.", answer: "Uns wurde von unseren Nachbarn geholfen.", altAnswers: ["Uns wurde von den Nachbarn geholfen."], explanation: "Dative stays; agent with \"von\"." },
      { type: "translate", direction: "en-es", prompt: "Translate into German.", source: "The children were given a present.", answer: "Den Kindern wurde ein Geschenk gegeben.", altAnswers: ["Den Kindern wurde ein Geschenk geschenkt.", "Die Kinder bekamen ein Geschenk."], explanation: "\"Ein Geschenk\" is the subject." },
      { type: "fill-blank", prompt: "Write the German for the bold words.", en: "[I] was helped immediately.", sentence: "___ wurde sofort geholfen.", answer: "Mir", explanation: "Dative, not nominative." },
      { type: "fill-blank", prompt: "Write the German for the bold words.", en: "We [were] told everything.", sentence: "Uns ___ alles gesagt.", answer: "wurde", explanation: "\"Alles\" is singular." },
      { type: "word-order", prompt: "Put the words in order to say: He was helped at the station.", words: ["Ihm", "wurde", "am Bahnhof", "geholfen."], translation: "He was helped at the station.", explanation: "Dative first, participle last." },
      { type: "multiple-choice", question: "Which sentence means: I was told the date.", options: ["Mir wurde der Termin gesagt.", "Ich wurde der Termin gesagt.", "Mir wurden der Termin gesagt.", "Mich wurde der Termin gesagt."], correctIndex: 0, explanation: "Dative \"mir\", singular subject." },
      { type: "dictation", audio: "Mir wurde zum Glück sofort geholfen.", explanation: "\"Zum Glück\": luckily." },
      { type: "speak", text: "Uns wurde gesagt, dass der Zug ausfällt.", prompt: "Say it in German: We were told that the train is cancelled.", explanation: "Dative + passive." },
    ],
  },
  {
    slug: "b1-passive-extra-14",
    level: "DE-B1",
    number: 14,
    optional: true,
    title: "Extra Practice: Passive, Man or Active?",
    summary: "Mixed transformations in all directions.",
    duration: "10 min",
    sections: [
      {
        heading: "Recap: three ways to say it",
        body: [
          "Active names the person: \"Der Hausmeister repariert die Heizung\". \"Man\" hides the person in an everyday tone: \"Man repariert die Heizung\". The passive hides the person or adds them with \"von\": \"Die Heizung wird (vom Hausmeister) repariert\". Keep the tense: \"reparierte\" becomes \"wurde repariert\".",
        ],
        examples: [
          { es: "Der Hausmeister repariert die Heizung.", en: "The caretaker is repairing the heating." },
          { es: "Man repariert die Heizung.", en: "They're repairing the heating." },
          { es: "Die Heizung wird vom Hausmeister repariert.", en: "The heating is being repaired by the caretaker." },
          { es: "Die Stadt baute 2010 eine neue Schule.", en: "The town built a new school in 2010." },
          { es: "2010 wurde eine neue Schule gebaut.", en: "In 2010 a new school was built." },
        ],
        checkpoint: [
          { type: "translate", direction: "en-es", prompt: "Translate into German with the passive and von.", source: "The heating is being repaired by the caretaker.", answer: "Die Heizung wird vom Hausmeister repariert.", explanation: "\"Vom\" + agent." },
          { type: "translate", direction: "en-es", prompt: "Translate into German with man.", source: "They built a new school in 2010.", answer: "2010 baute man eine neue Schule.", altAnswers: ["Man baute 2010 eine neue Schule.", "2010 hat man eine neue Schule gebaut."], explanation: "\"Man\" + Präteritum." },
        ],
      },
    ],
    exercises: [
      { type: "translate", direction: "en-es", prompt: "Rewrite \"Man putzt die Küche.\" in the passive. Translate: The kitchen is being cleaned.", source: "The kitchen is being cleaned.", answer: "Die Küche wird geputzt.", altAnswers: ["Die Küche wird sauber gemacht."], explanation: "Object becomes subject." },
      { type: "translate", direction: "en-es", prompt: "Rewrite \"Die Briefe werden verschickt.\" with man. Translate: They send the letters.", source: "They send the letters.", answer: "Man verschickt die Briefe.", altAnswers: ["Man schickt die Briefe."], explanation: "Subject becomes accusative object." },
      { type: "translate", direction: "en-es", prompt: "Rewrite \"Die Firma entließ zwanzig Mitarbeiter.\" in the passive. Translate: Twenty employees were dismissed.", source: "Twenty employees were dismissed.", answer: "Zwanzig Mitarbeiter wurden entlassen.", altAnswers: ["Es wurden zwanzig Mitarbeiter entlassen."], explanation: "Präteritum stays Präteritum." },
      { type: "translate", direction: "en-es", prompt: "Rewrite \"Das Bild wurde von Klimt gemalt.\" in the active. Translate: Klimt painted the picture.", source: "Klimt painted the picture.", answer: "Klimt malte das Bild.", altAnswers: ["Klimt hat das Bild gemalt."], explanation: "Agent becomes subject." },
      { type: "translate", direction: "en-es", prompt: "Translate into German with the passive.", source: "The new hall was opened by the mayor.", answer: "Die neue Halle wurde vom Bürgermeister eröffnet.", altAnswers: ["Die neue Halle wurde von der Bürgermeisterin eröffnet."], explanation: "\"Von\" + dative." },
      { type: "translate", direction: "en-es", prompt: "Translate into German with man.", source: "They don't sell newspapers here any more.", answer: "Hier verkauft man keine Zeitungen mehr.", altAnswers: ["Man verkauft hier keine Zeitungen mehr."], explanation: "\"Keine ... mehr\"." },
      { type: "translate", direction: "en-es", prompt: "Translate into German in the active.", source: "My neighbour waters the plants.", answer: "Meine Nachbarin gießt die Pflanzen.", altAnswers: ["Mein Nachbar gießt die Pflanzen.", "Meine Nachbarin gießt die Blumen."], explanation: "\"Gießen\": water plants." },
      { type: "translate", direction: "en-es", prompt: "Translate into German with the passive.", source: "The plants are watered by my neighbour.", answer: "Die Pflanzen werden von meiner Nachbarin gegossen.", altAnswers: ["Die Pflanzen werden von meinem Nachbarn gegossen."], explanation: "\"Gießen\" → \"gegossen\"." },
      { type: "translate", direction: "en-es", prompt: "Translate into German with the passive.", source: "I was helped by a stranger.", answer: "Mir wurde von einem Fremden geholfen.", altAnswers: ["Mir wurde von einer Fremden geholfen."], explanation: "Dative stays dative." },
      { type: "translate", direction: "en-es", prompt: "Translate into German with man.", source: "They told us nothing.", answer: "Man hat uns nichts gesagt.", altAnswers: ["Man sagte uns nichts."], explanation: "\"Man\" + dative \"uns\"." },
      { type: "fill-blank", prompt: "Write the German for the bold words.", en: "The road [was] closed.", sentence: "Die Straße ___ gesperrt.", answer: "wurde", explanation: "\"Man sperrte die Straße\" in the Präteritum passive." },
      { type: "fill-blank", prompt: "Write the German for the bold words.", en: "[They] check the tickets.", sentence: "___ kontrolliert die Fahrkarten.", answer: "Man", explanation: "Passive turned back into \"man\"." },
      { type: "word-order", prompt: "Put the words in order to say: The room is cleaned by the hotel staff.", words: ["Das Zimmer", "wird", "vom", "Hotelpersonal", "geputzt."], translation: "The room is cleaned by the hotel staff.", explanation: "\"Vom\" + agent, participle last." },
      { type: "multiple-choice", question: "Which is the passive of: Der Koch bereitet das Essen zu.", options: ["Das Essen wird vom Koch zubereitet.", "Das Essen wird den Koch zubereitet.", "Der Koch wird das Essen zubereiten.", "Das Essen wurde vom Koch zubereiten."], correctIndex: 0, explanation: "Present stays present." },
      { type: "listen-choose", audio: "2010 wurde eine neue Schule gebaut.", question: "What does it mean?", options: ["In 2010 a new school was built.", "In 2010 a new school will be built.", "A new school is built every year.", "In 2010 the school became new."], correctIndex: 0, explanation: "\"Wurde gebaut\": was built." },
      { type: "speak", text: "Die Heizung wird vom Hausmeister repariert.", prompt: "Say it in German: The heating is being repaired by the caretaker.", explanation: "Passive with \"von\"." },
    ],
  },
];
