// Synced from cheneygross-afk/lengo:src/lib/lessons/de-b1-u20.ts by scripts/sync-content.mjs -- edit it there, not here.
import type { Lesson, WriteExercise } from "./types";
// German B1, Unit 20: Adjectives as Nouns and Participles as Adjectives.

export const DE_B1_U20: Lesson[] = [
  {
    slug: "b1-adjectives-as-nouns",
    level: "DE-B1",
    number: 1,
    title: "Adjectives as Nouns: Der Deutsche, Ein Deutscher",
    summary: "People-words that are really adjectives with a capital letter and adjective endings: der Deutsche, ein Deutscher, die Angestellten, meine Bekannte, ein Verwandter.",
    duration: "15 min",
    sections: [
      {
        heading: "An adjective with the noun left out",
        body: [
          "German can turn an adjective into a noun for a person: \"der Deutsche\" is really \"der deutsche Mann\" with the noun dropped, \"die Kranke\" is the sick woman, \"die Erwachsenen\" are the grown-ups. The word is capitalised like any noun, but it keeps adjective endings, so its ending changes with the article and case exactly as in Unit 19.",
          "The most important ones: \"der / die Deutsche\" (German), \"der / die Angestellte\" (employee), \"der / die Bekannte\" (acquaintance, friend), \"der / die Verwandte\" (relative), \"der / die Erwachsene\" (adult), \"der / die Jugendliche\" (young person, teenager), \"der / die Kranke\" (sick person), \"der / die Arbeitslose\" (unemployed person), \"der / die Fremde\" (stranger), \"der / die Reisende\" (traveller).",
          "Note that \"Deutsche\" is the only nationality that works like this. Others are normal nouns: \"der Engländer\", \"die Engländerin\", \"der Franzose\".",
        ],
        examples: [
          { es: "Der Deutsche am Nebentisch hat uns geholfen.", en: "The German man at the next table helped us." },
          { es: "Meine Mutter ist Angestellte bei einer Bank.", en: "My mother is an employee at a bank." },
          { es: "Die Erwachsenen essen im Wohnzimmer, die Kinder in der Küche.", en: "The adults are eating in the living room, the children in the kitchen." },
          { es: "Viele Jugendliche haben kein Interesse an Politik.", en: "Many young people have no interest in politics." },
          { es: "Ein Bekannter von mir arbeitet bei Siemens.", en: "An acquaintance of mine works at Siemens." },
          { es: "Der Kranke muss im Bett bleiben.", en: "The sick man has to stay in bed." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "The adults are drinking coffee.",
            answer: "Die Erwachsenen trinken Kaffee.",
            explanation: "Plural after \"die\": weak -en, just like an adjective.",
          },
          {
            type: "multiple-choice",
            question: "How do you say: Many young people live here?",
            options: ["Hier wohnen viele Jugendliche.", "Hier wohnen viele Jugendlichen.", "Hier wohnen viele jugendliche.", "Hier wohnen viele Jugendlicher."],
            correctIndex: 0,
            explanation: "After \"viele\": strong -e, and capitalised because it's used as a noun.",
          },
        ],
      },
      {
        heading: "Der Deutsche, ein Deutscher, Deutsche",
        body: [
          "The endings follow the three patterns you know. After \"der\": \"der Deutsche\", \"den Deutschen\", \"dem Deutschen\", \"die Deutschen\". After \"ein\": \"ein Deutscher\" (masc. nom., -er!), \"einen Deutschen\", \"einem Deutschen\". No article: \"Deutsche\" (plural), \"mit Deutschen\".",
          "Feminine: \"die Deutsche\" / \"eine Deutsche\" (one German woman), dative \"der / einer Deutschen\". So \"die Deutsche\" is one woman, \"die Deutschen\" are the Germans (plural). \"Ich bin Deutscher\" is said by a man, \"Ich bin Deutsche\" by a woman (no article before nationality after \"sein\").",
          "Traps: *ein Deutsche* (a man) must be \"ein Deutscher\"; *die Bekannte* for plural acquaintances must be \"die Bekannten\"; *viele Deutschen* must be \"viele Deutsche\".",
        ],
        examples: [
          { es: "Er ist Deutscher, sie ist Österreicherin.", en: "He's German, she's Austrian." },
          { es: "Ich bin Deutsche, aber ich wohne in Wien.", en: "I'm German, but I live in Vienna. (a woman)" },
          { es: "Ich habe gestern einen Deutschen im Zug kennengelernt.", en: "Yesterday I met a German guy on the train." },
          { es: "Die Deutschen trinken viel Mineralwasser.", en: "Germans drink a lot of mineral water." },
          { es: "Viele Deutsche machen Urlaub in Spanien.", en: "Lots of Germans go on holiday in Spain." },
          { es: "Sie ist mit einem Deutschen verheiratet.", en: "She's married to a German." },
        ],
        checkpoint: [
          {
            type: "fill-blank",
            prompt: "Write the German for the bold words.",
            en: "I met [a German] on the train. (a man)",
            sentence: "Ich habe im Zug ___ kennengelernt.",
            answer: "einen Deutschen",
            explanation: "Accusative masculine after \"einen\": -en, as for any adjective.",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "He's German.",
            answer: "Er ist Deutscher.",
            explanation: "No article, masculine nominative: strong -er.",
          },
          {
            type: "listen-choose",
            audio: "Die Deutschen trinken viel Mineralwasser.",
            question: "What does it mean?",
            options: ["Germans drink a lot of mineral water.", "The German woman drinks a lot of mineral water.", "A German drinks a lot of mineral water.", "German water is very mineral."],
            correctIndex: 0,
            explanation: "\"Die Deutschen\" (-en) is plural; one woman would be \"die Deutsche\" with \"trinkt\".",
          },
        ],
      },
      {
        heading: "Bekannte, Verwandte, Angestellte in all cases",
        body: [
          "The same system for other people-words: \"mein Bekannter\" (a male acquaintance, after \"mein\" = -er), \"meine Bekannte\" (female), \"meine Bekannten\" (plural); \"mit meinem Bekannten\"; \"ein Verwandter von mir\"; \"unsere Angestellten\"; \"Angestellte bekommen ein Weihnachtsgeld\".",
          "\"Ein Bekannter von mir\" is a very common way to introduce someone you know but who isn't a close friend: German distinguishes \"ein Freund\" (a close friend) from \"ein Bekannter\" more than English does.",
          "Some nouns made from participles also belong here: \"der / die Vorsitzende\" (chair), \"der / die Auszubildende\" (trainee, short \"Azubi\"), \"der / die Vorgesetzte\" (superior, boss), \"der / die Studierende\" (student).",
        ],
        examples: [
          { es: "Ein Bekannter von mir sucht eine Wohnung.", en: "An acquaintance of mine is looking for a flat." },
          { es: "Wir feiern Weihnachten mit allen Verwandten.", en: "We celebrate Christmas with all our relatives." },
          { es: "Die Firma hat zweihundert Angestellte.", en: "The company has two hundred employees." },
          { es: "Ich habe mit meiner Vorgesetzten gesprochen.", en: "I spoke to my boss. (a woman)" },
          { es: "Unser neuer Auszubildender heißt Leon.", en: "Our new trainee is called Leon." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "An acquaintance of mine is looking for a job.",
            answer: "Ein Bekannter von mir sucht einen Job.",
            altAnswers: ["Eine Bekannte von mir sucht einen Job.", "Ein Bekannter von mir sucht eine Stelle.", "Eine Bekannte von mir sucht eine Stelle.", "Ein Bekannter von mir sucht Arbeit.", "Eine Bekannte von mir sucht Arbeit."],
            explanation: "After \"ein\" in the masculine nominative: -er; a woman is \"eine Bekannte\".",
          },
          {
            type: "speak",
            text: "Wir feiern Weihnachten mit allen Verwandten.",
            prompt: "Say it in German: We celebrate Christmas with all our relatives.",
            tip: "\"Verwandten\": stress -WAND-.",
            explanation: "Dative plural after \"allen\": -en.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "I'm German. (a woman)",
        answer: "Ich bin Deutsche.",
        explanation: "No article, feminine nominative: -e.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "My boyfriend is German.",
        answer: "Mein Freund ist Deutscher.",
        explanation: "No article, masculine nominative: -er.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "The company has fifty employees.",
        answer: "Die Firma hat fünfzig Angestellte.",
        altAnswers: ["Das Unternehmen hat fünfzig Angestellte.", "Die Firma hat fünfzig Mitarbeiter."],
        explanation: "No article, plural: strong -e.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "She's talking to a relative.",
        answer: "Sie spricht mit einem Verwandten.",
        altAnswers: ["Sie spricht mit einer Verwandten.", "Sie redet mit einem Verwandten.", "Sie redet mit einer Verwandten."],
        explanation: "Dative after \"einem\" / \"einer\": -en.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "Teenagers often sleep until midday.",
        answer: "Jugendliche schlafen oft bis Mittag.",
        altAnswers: ["Jugendliche schlafen oft bis mittags.", "Die Jugendlichen schlafen oft bis Mittag."],
        explanation: "No article, plural: -e.",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "[The Germans] love bread.",
        sentence: "___ lieben Brot.",
        answer: "Die Deutschen",
        explanation: "Plural after \"die\": -en.",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "[An acquaintance] of mine lives in Köln. (a man)",
        sentence: "___ von mir wohnt in Köln.",
        answer: "Ein Bekannter",
        explanation: "Masculine nominative after \"ein\": -er.",
      },
      {
        type: "multiple-choice",
        question: "Which sentence is correct?",
        options: ["Ich habe viele Deutsche kennengelernt.", "Ich habe viele Deutschen kennengelernt.", "Ich habe viele deutsche kennengelernt.", "Ich habe viele Deutscher kennengelernt."],
        correctIndex: 0,
        explanation: "After \"viele\": strong -e.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: The sick woman needs rest.",
        words: ["Die", "Kranke", "braucht", "Ruhe."],
        translation: "The sick woman needs rest.",
        explanation: "\"Die Kranke\": feminine singular (singular verb \"braucht\").",
      },
      {
        type: "dictation",
        audio: "Ein Bekannter von mir sucht eine Wohnung.",
        explanation: "\"Ein Bekannter\": -er after \"ein\".",
      },
      {
        type: "speak",
        text: "Ich habe einen Deutschen kennengelernt.",
        prompt: "Say it in German: I've met a German guy.",
        tip: "\"Deutschen\": eu like oy.",
        explanation: "Masculine accusative: -en.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "Adults pay ten euros, children five.",
        answer: "Erwachsene zahlen zehn Euro, Kinder fünf.",
        altAnswers: ["Erwachsene bezahlen zehn Euro, Kinder fünf.", "Für Erwachsene kostet es zehn Euro, für Kinder fünf."],
        explanation: "No article, plural: \"Erwachsene\".",
      },
    ],
  },
  {
    slug: "b1-das-gute-etwas-neues",
    level: "DE-B1",
    number: 2,
    title: "Das Gute, Etwas Neues, Nichts Besonderes",
    summary: "Neuter nominalisations for ideas: das Gute, das Wichtigste ist..., etwas Neues, nichts Besonderes, viel Gutes, alles Gute.",
    duration: "14 min",
    sections: [
      {
        heading: "Das Gute, das Wichtigste: neuter for ideas",
        body: [
          "A neuter adjective-noun stands for a thing or an idea: \"das Gute\" (the good thing, what's good), \"das Schöne daran\" (the nice thing about it), \"das Neue\" (what's new), \"das Wichtigste\" (the most important thing). English often needs thing or what's: \"Das Wichtigste ist, dass du gesund bist\" = The most important thing is that you're healthy.",
          "They take normal neuter endings: \"das Gute\", \"im Allgemeinen\" (in general), \"nach dem Essen\" isn't one (that's a verb), but \"vom Besten\" and \"zum Schluss das Beste\" are.",
          "Superlatives are especially common: \"das Beste\", \"das Schlimmste\" (the worst thing), \"das Einzige\" (the only thing), \"das Letzte\" (the last thing). After them a relative clause uses \"was\": \"Das Beste, was mir passiert ist\".",
        ],
        examples: [
          { es: "Das Gute an meinem Job ist die Flexibilität.", en: "The good thing about my job is the flexibility." },
          { es: "Das Wichtigste ist, dass alle gesund sind.", en: "The most important thing is that everyone is healthy." },
          { es: "Das Schlimmste war das Warten.", en: "The worst thing was the waiting." },
          { es: "Das Schöne daran ist, dass wir mehr Zeit haben.", en: "The nice thing about it is that we have more time." },
          { es: "Das ist das Beste, was ich je gegessen habe.", en: "That's the best thing I've ever eaten." },
          { es: "Im Allgemeinen bin ich zufrieden.", en: "In general I'm satisfied." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "The most important thing is health.",
            answer: "Das Wichtigste ist die Gesundheit.",
            explanation: "Neuter superlative as a noun: \"das Wichtigste\", capitalised.",
          },
          {
            type: "fill-blank",
            prompt: "Write the German for the bold words.",
            en: "[The worst thing] was the noise.",
            sentence: "___ war der Lärm.",
            answer: "Das Schlimmste",
            explanation: "\"Das Schlimmste\": neuter, capitalised.",
          },
        ],
      },
      {
        heading: "Etwas Neues, nichts Besonderes, viel Gutes",
        body: [
          "After \"etwas\" (something), \"nichts\" (nothing), \"viel\" (much), \"wenig\" (little) and \"genug\", the adjective becomes a capitalised neuter noun with the strong ending -es: \"etwas Neues\" (something new), \"nichts Besonderes\" (nothing special), \"viel Gutes\" (a lot of good), \"wenig Neues\".",
          "In the dative it's -em: \"mit etwas Neuem\", \"von nichts Gutem\". After \"alles\" (everything) the ending is weak -e: \"alles Gute\" (all the best), \"alles Neue\", \"Alles Liebe\" (love, at the end of a letter).",
          "The classic error is lowercase: *etwas neues*. Write \"etwas Neues\". Exception: \"andere\" can stay lowercase: \"etwas anderes\" (something else), although \"etwas Anderes\" is also allowed.",
        ],
        examples: [
          { es: "Gibt es etwas Neues?", en: "Is there any news? / Anything new?" },
          { es: "Am Wochenende haben wir nichts Besonderes gemacht.", en: "We didn't do anything special at the weekend." },
          { es: "Ich wünsche dir alles Gute zum Geburtstag!", en: "All the best for your birthday!" },
          { es: "Die neue Chefin hat schon viel Gutes bewirkt.", en: "The new boss has already done a lot of good." },
          { es: "Ich möchte heute mal etwas anderes essen.", en: "I'd like to eat something different today." },
          { es: "Alles Liebe, deine Lena", en: "Love, Lena" },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "We didn't do anything special.",
            answer: "Wir haben nichts Besonderes gemacht.",
            altAnswers: ["Wir machten nichts Besonderes."],
            explanation: "\"Nichts\" + capitalised adjective with -es.",
          },
          {
            type: "multiple-choice",
            question: "How do you write: something new?",
            options: ["etwas Neues", "etwas neues", "etwas Neue", "etwas Neuen"],
            correctIndex: 0,
            explanation: "After \"etwas\": capital letter and -es.",
          },
          {
            type: "speak",
            text: "Ich wünsche dir alles Gute!",
            prompt: "Say it in German: I wish you all the best! (to a friend)",
            tip: "\"Wünsche\": ü like ee with rounded lips.",
            explanation: "After \"alles\": weak -e.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "Is there any news?",
        answer: "Gibt es etwas Neues?",
        altAnswers: ["Gibt's was Neues?", "Gibt es was Neues?"],
        explanation: "\"Etwas Neues\": something new; colloquially \"was Neues\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "The good thing about the flat is the location.",
        answer: "Das Gute an der Wohnung ist die Lage.",
        explanation: "\"Das Gute an\" + dative: the good thing about.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "All the best for the exam!",
        answer: "Alles Gute für die Prüfung!",
        altAnswers: ["Viel Glück bei der Prüfung!", "Alles Gute zur Prüfung!"],
        explanation: "\"Alles Gute\": weak -e after \"alles\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "I'd like to learn something new.",
        answer: "Ich möchte etwas Neues lernen.",
        altAnswers: ["Ich würde gern etwas Neues lernen."],
        explanation: "\"Etwas Neues\" as the object.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "That's the only thing I know.",
        answer: "Das ist das Einzige, was ich weiß.",
        explanation: "\"Das Einzige\" + relative \"was\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "Nothing special happened.",
        answer: "Es ist nichts Besonderes passiert.",
        altAnswers: ["Nichts Besonderes ist passiert.", "Es passierte nichts Besonderes."],
        explanation: "\"Nichts Besonderes\" with -es.",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "I'd like [something sweet].",
        sentence: "Ich hätte gern ___.",
        answer: "etwas Süßes",
        altAnswers: ["was Süßes"],
        explanation: "After \"etwas\": capitalised + -es.",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "[The best thing] was the food.",
        sentence: "___ war das Essen.",
        answer: "Das Beste",
        explanation: "Superlative as a neuter noun.",
      },
      {
        type: "multiple-choice",
        question: "Which ending of a letter is correct?",
        options: ["Alles Liebe, Mia", "Alles Liebes, Mia", "Alle Liebe, Mia", "Alles liebe, Mia"],
        correctIndex: 0,
        explanation: "After \"alles\": weak -e, capitalised.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: The most important thing is that you're happy.",
        words: ["Das", "Wichtigste", "ist,", "dass", "du", "glücklich", "bist."],
        translation: "The most important thing is that you're happy.",
        explanation: "\"Das Wichtigste ist, dass...\" + verb last.",
      },
      {
        type: "listen-choose",
        audio: "Wir haben nichts Besonderes gemacht.",
        question: "What does it mean?",
        options: ["We didn't do anything special.", "We did something special.", "We did nothing at all.", "We haven't done anything yet."],
        correctIndex: 0,
        explanation: "\"Nichts Besonderes\" = nothing special.",
      },
      {
        type: "dictation",
        audio: "Gibt es etwas Neues?",
        explanation: "\"Etwas Neues\": capital N.",
      },
    ],
  },
  {
    slug: "b1-contrast-clinic-der-deutsche-ein-deutscher",
    level: "DE-B1",
    number: 3,
    title: "Contrast Clinic: Der Deutsche / Ein Deutscher",
    summary: "The same people-word after der, ein and no article in all cases: mein Bekannter / meine Bekannte / meine Bekannten; mit einem Bekannten.",
    duration: "13 min",
    sections: [
      {
        heading: "Masculine: -e, -er, -en",
        body: [
          "Take \"Bekannter\" (male acquaintance). Nominative: \"der Bekannte\" / \"ein Bekannter\" / \"mein Bekannter\". Accusative: \"den Bekannten\" / \"einen Bekannten\". Dative: \"dem Bekannten\" / \"einem Bekannten\". Only the nominative changes with the article.",
          "Compare a normal noun: \"der Freund\" / \"ein Freund\" stays the same. With adjective-nouns you have to watch the ending every time.",
        ],
        examples: [
          { es: "Der Bekannte von Jonas ist Arzt.", en: "Jonas's acquaintance is a doctor." },
          { es: "Ein Bekannter hat mir die Wohnung empfohlen.", en: "An acquaintance recommended the flat to me." },
          { es: "Ich habe einen Bekannten gefragt.", en: "I asked an acquaintance." },
          { es: "Ich war mit einem Bekannten im Kino.", en: "I went to the cinema with an acquaintance." },
          { es: "Kennst du den Deutschen, der neben dir wohnt?", en: "Do you know the German guy who lives next to you?" },
        ],
        checkpoint: [
          {
            type: "fill-blank",
            prompt: "Write the German for the bold words.",
            en: "[An acquaintance] recommended the doctor to me.",
            sentence: "___ hat mir den Arzt empfohlen.",
            answer: "Ein Bekannter",
            altAnswers: ["Eine Bekannte"],
            explanation: "Masculine nominative after \"ein\": -er.",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "I asked an acquaintance.",
            answer: "Ich habe einen Bekannten gefragt.",
            altAnswers: ["Ich habe eine Bekannte gefragt.", "Ich fragte einen Bekannten."],
            explanation: "Accusative after \"einen\": -en.",
          },
        ],
      },
      {
        heading: "Feminine and plural",
        body: [
          "Feminine is simpler: \"die / eine / meine Bekannte\" in the nominative and accusative, \"der / einer / meiner Bekannten\" in the dative and genitive. Plural: \"die / meine Bekannten\", but with no article \"Bekannte\": \"Ich habe Bekannte in Wien\".",
          "So \"meine Bekannte\" is one woman and \"meine Bekannten\" are several people. The difference is one letter, so listen and write carefully.",
        ],
        examples: [
          { es: "Meine Bekannte aus Wien kommt zu Besuch.", en: "My friend from Vienna is coming to visit. (a woman)" },
          { es: "Meine Bekannten aus Wien kommen zu Besuch.", en: "My friends from Vienna are coming to visit." },
          { es: "Ich habe Verwandte in Kanada.", en: "I have relatives in Canada." },
          { es: "Wir haben bei einer Verwandten übernachtet.", en: "We stayed the night with a relative. (a woman)" },
          { es: "Die Angestellten der Firma streiken.", en: "The company's employees are on strike." },
        ],
        checkpoint: [
          {
            type: "listen-choose",
            audio: "Meine Bekannten kommen zu Besuch.",
            question: "What does it mean?",
            options: ["My acquaintances are coming to visit.", "My acquaintance (a woman) is coming to visit.", "An acquaintance of mine came to visit.", "My acquaintance is visiting them."],
            correctIndex: 0,
            explanation: "\"Meine Bekannten\" (-en) + plural verb \"kommen\": several people.",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "I have relatives in Canada.",
            answer: "Ich habe Verwandte in Kanada.",
            explanation: "No article, plural: strong -e.",
          },
          {
            type: "speak",
            text: "Meine Bekannte aus Wien kommt zu Besuch.",
            prompt: "Say it in German: My friend from Vienna is coming to visit. (a woman)",
            tip: "\"Wien\": long ie, w like English v.",
            explanation: "\"Meine Bekannte\": one woman, singular verb \"kommt\".",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "A relative of mine lives in Hamburg. (a man)",
        answer: "Ein Verwandter von mir wohnt in Hamburg.",
        altAnswers: ["Ein Verwandter von mir lebt in Hamburg."],
        explanation: "Masculine nominative after \"ein\": -er.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "The relative from Hamburg is coming tomorrow. (a man)",
        answer: "Der Verwandte aus Hamburg kommt morgen.",
        explanation: "After \"der\": -e.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "We visited our relatives.",
        answer: "Wir haben unsere Verwandten besucht.",
        altAnswers: ["Wir besuchten unsere Verwandten."],
        explanation: "Plural after \"unsere\": -en.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "She works with a German. (a man)",
        answer: "Sie arbeitet mit einem Deutschen.",
        altAnswers: ["Sie arbeitet mit einem Deutschen zusammen."],
        explanation: "Dative after \"einem\": -en.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "My boss (a woman) is on holiday.",
        answer: "Meine Vorgesetzte ist im Urlaub.",
        altAnswers: ["Meine Chefin ist im Urlaub.", "Meine Vorgesetzte ist in Urlaub."],
        explanation: "\"Meine Vorgesetzte\": feminine singular, -e.",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "I gave [the employee] the key. (a man)",
        sentence: "Ich habe ___ den Schlüssel gegeben.",
        answer: "dem Angestellten",
        explanation: "Dative after \"dem\": -en.",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "He's [an employee] at the post office.",
        sentence: "Er ist ___ bei der Post.",
        answer: "Angestellter",
        explanation: "No article after \"sein\" for a job: strong -er.",
      },
      {
        type: "multiple-choice",
        question: "Which means: my (female) acquaintance?",
        options: ["meine Bekannte", "meine Bekannten", "mein Bekannter", "meinen Bekannten"],
        correctIndex: 0,
        explanation: "\"Meine Bekannte\": feminine singular.",
      },
      {
        type: "multiple-choice",
        question: "Which means: a German (man, nominative)?",
        options: ["ein Deutscher", "ein Deutsche", "ein Deutschen", "einer Deutsche"],
        correctIndex: 0,
        explanation: "After \"ein\" in the masculine nominative: -er.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: We stayed with relatives.",
        words: ["Wir", "haben", "bei", "Verwandten", "übernachtet."],
        translation: "We stayed with relatives.",
        explanation: "No article, dative plural: -en.",
      },
      {
        type: "dictation",
        audio: "Ich war mit einem Bekannten im Kino.",
        explanation: "\"Mit einem Bekannten\": dative -en.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "All employees get a bonus.",
        answer: "Alle Angestellten bekommen einen Bonus.",
        altAnswers: ["Alle Angestellten bekommen eine Prämie.", "Alle Mitarbeiter bekommen einen Bonus."],
        explanation: "After \"alle\": weak -en.",
      },
    ],
  },
  {
    slug: "b1-participles-as-adjectives",
    level: "DE-B1",
    number: 4,
    title: "Participles as Adjectives",
    summary: "Partizip II for a finished action (das gekochte Ei) and Partizip I for an ongoing one (der wartende Kunde), both with normal adjective endings.",
    duration: "14 min",
    sections: [
      {
        heading: "Partizip II: something already done",
        body: [
          "You already know the Partizip II from the Perfekt: \"gekocht\", \"geschlossen\", \"gebraucht\". Put it before a noun and it works like any adjective, with the same endings: \"das gekochte Ei\" (the boiled egg), \"die geschlossene Tür\" (the closed door), \"gebrauchte Möbel\" (used furniture).",
          "The meaning is passive and finished: the egg has been boiled, the door has been closed. Think of it as a short relative clause: \"das Ei, das gekocht wurde\" becomes \"das gekochte Ei\".",
        ],
        examples: [
          { es: "Ich esse morgens ein gekochtes Ei.", en: "I eat a boiled egg in the morning." },
          { es: "Die Tür war geschlossen. Vor der geschlossenen Tür stand ein Paket.", en: "The door was closed. A parcel was standing in front of the closed door." },
          { es: "Wir haben gebrauchte Möbel gekauft.", en: "We bought used furniture." },
          { es: "Das reparierte Fahrrad steht im Keller.", en: "The repaired bike is in the cellar." },
          { es: "Bitte schicken Sie uns das ausgefüllte Formular.", en: "Please send us the completed form." },
        ],
        checkpoint: [
          {
            type: "fill-blank",
            prompt: "Write the German for the bold words.",
            en: "We bought [used furniture].",
            sentence: "Wir haben ___ gekauft.",
            answer: "gebrauchte Möbel",
            explanation: "Plural, no article: strong -e.",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "Please send us the completed form.",
            answer: "Bitte schicken Sie uns das ausgefüllte Formular.",
            altAnswers: ["Schicken Sie uns bitte das ausgefüllte Formular."],
            explanation: "\"Ausgefüllt\" + neuter accusative after \"das\": -e.",
          },
        ],
      },
      {
        heading: "Partizip I: something happening now",
        body: [
          "The Partizip I is the infinitive + d: \"warten\" gives \"wartend\", \"steigen\" gives \"steigend\", \"kochen\" gives \"kochend\". Before a noun it takes adjective endings: \"der wartende Kunde\" (the waiting customer), \"die steigenden Preise\" (the rising prices), \"kochendes Wasser\" (boiling water).",
          "The meaning is active and ongoing: the customer is waiting right now. Compare \"kochendes Wasser\" (water that is boiling) with \"gekochtes Wasser\" (water that has been boiled). At B1 keep these to one word before the noun; long participle phrases come later.",
        ],
        examples: [
          { es: "Der wartende Kunde ist schon ungeduldig.", en: "The waiting customer is already impatient." },
          { es: "Die steigenden Preise machen vielen Leuten Sorgen.", en: "The rising prices worry a lot of people." },
          { es: "Gießen Sie kochendes Wasser über den Tee.", en: "Pour boiling water over the tea." },
          { es: "Im folgenden Text geht es um Arbeit.", en: "The following text is about work." },
          { es: "Ein schlafendes Kind ist ganz ruhig.", en: "A sleeping child is very quiet." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "Which means: the rising prices?",
            options: ["die steigenden Preise", "die gestiegenen Preise", "die steigende Preise", "die gesteigte Preise"],
            correctIndex: 0,
            explanation: "Ongoing: Partizip I \"steigend\", plural after \"die\": -en.",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "Pour boiling water over the tea.",
            answer: "Gießen Sie kochendes Wasser über den Tee.",
            altAnswers: ["Gieß kochendes Wasser über den Tee."],
            explanation: "\"Kochend\" + neuter, no article: strong -es.",
          },
          {
            type: "speak",
            text: "Der wartende Kunde ist schon ungeduldig.",
            prompt: "Say it in German: The waiting customer is already impatient.",
            tip: "\"Wartende\": stress on the first syllable, WAR-ten-de.",
            explanation: "Partizip I \"wartend\" + -e after \"der\".",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "I eat a boiled egg every morning.",
        answer: "Ich esse jeden Morgen ein gekochtes Ei.",
        explanation: "Finished action: Partizip II, neuter after \"ein\": -es.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "The repaired bike is in the cellar.",
        answer: "Das reparierte Fahrrad steht im Keller.",
        altAnswers: ["Das reparierte Fahrrad ist im Keller.", "Das reparierte Rad steht im Keller."],
        explanation: "\"Repariert\" + -e after \"das\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "The rising prices worry many people.",
        answer: "Die steigenden Preise machen vielen Leuten Sorgen.",
        altAnswers: ["Die steigenden Preise machen vielen Menschen Sorgen."],
        explanation: "Ongoing: \"steigend\", plural after \"die\": -en.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "A sleeping child is very quiet.",
        answer: "Ein schlafendes Kind ist ganz ruhig.",
        altAnswers: ["Ein schlafendes Kind ist sehr ruhig."],
        explanation: "\"Schlafend\" + neuter after \"ein\": -es.",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "A parcel was standing in front of [the closed door].",
        sentence: "Vor ___ stand ein Paket.",
        answer: "der geschlossenen Tür",
        explanation: "Dative after \"vor\" (where?), feminine after \"der\": -en.",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "[The waiting customers] are getting impatient.",
        sentence: "___ werden ungeduldig.",
        answer: "Die wartenden Kunden",
        explanation: "Partizip I, plural after \"die\": -en.",
      },
      {
        type: "multiple-choice",
        question: "Which means: water that has been boiled?",
        options: ["gekochtes Wasser", "kochendes Wasser", "kochende Wasser", "gekocht Wasser"],
        correctIndex: 0,
        explanation: "Finished action: Partizip II \"gekocht\"; neuter, no article: -es.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: We bought a used car.",
        words: ["Wir", "haben", "ein", "gebrauchtes", "Auto", "gekauft."],
        translation: "We bought a used car.",
        explanation: "\"Ein gebrauchtes Auto\": neuter accusative after \"ein\": -es.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: The following text is about work.",
        words: ["Im", "folgenden", "Text", "geht", "es", "um", "Arbeit."],
        translation: "The following text is about work.",
        explanation: "\"Im folgenden Text\": dative after \"im\": -en.",
      },
      {
        type: "listen-choose",
        audio: "Das ausgefüllte Formular liegt auf dem Tisch.",
        question: "What does it mean?",
        options: ["The completed form is on the table.", "The form is being filled in on the table.", "Fill in the form on the table.", "The empty form is on the table."],
        correctIndex: 0,
        explanation: "\"Ausgefüllt\" = already filled in.",
      },
      {
        type: "dictation",
        audio: "Gießen Sie kochendes Wasser über den Tee.",
        explanation: "\"Kochendes\": infinitive + d + ending -es.",
      },
      {
        type: "speak",
        text: "Wir haben gebrauchte Möbel gekauft.",
        prompt: "Say it in German: We bought used furniture.",
        tip: "\"Möbel\": round your lips for the ö.",
        explanation: "Partizip II \"gebraucht\" + plural -e.",
      },
    ],
  },
  {
    slug: "b1-themed-review-unpaid-invoice",
    level: "DE-B1",
    number: 5,
    title: "Themed Review: Die offene Rechnung",
    summary: "A small business chases an unpaid invoice: die gesendete Mahnung, der zuständige Angestellte, polite Konjunktiv II and the passive.",
    duration: "15 min",
    sections: [
      {
        heading: "Die Mahnung",
        body: [
          "Frau Ott runs a small print shop. A customer hasn't paid an invoice (\"eine Rechnung\") for six weeks. She sends a reminder (\"eine Mahnung\"). An unpaid invoice is \"eine offene Rechnung\" or \"eine unbezahlte Rechnung\".",
          "Watch the participles: \"die gesendete Mahnung\" (the reminder that has been sent), \"der fällige Betrag\" (the amount due), \"die gelieferten Plakate\" (the posters that were delivered). And the passive: \"Die Rechnung wurde am 3. März verschickt.\"",
        ],
        examples: [
          { es: "Die Rechnung wurde am 3. März verschickt.", en: "The invoice was sent on 3 March." },
          { es: "Leider ist die Rechnung noch offen.", en: "Unfortunately the invoice is still unpaid." },
          { es: "Die gelieferten Plakate waren in Ordnung.", en: "The posters we delivered were fine." },
          { es: "Bitte überweisen Sie den fälligen Betrag bis Freitag.", en: "Please transfer the amount due by Friday." },
          { es: "Unsere erste Mahnung ist leider unbeantwortet geblieben.", en: "Unfortunately our first reminder went unanswered." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "The invoice was sent on 3 March.",
            answer: "Die Rechnung wurde am 3. März verschickt.",
            altAnswers: ["Die Rechnung wurde am dritten März verschickt.", "Die Rechnung wurde am 3. März geschickt."],
            explanation: "Präteritum passive: \"wurde\" + Partizip II.",
          },
          {
            type: "listen-choose",
            audio: "Leider ist die Rechnung noch offen.",
            question: "What does it mean?",
            options: ["Unfortunately the invoice is still unpaid.", "Unfortunately the shop is still open.", "The invoice has been paid, luckily.", "Unfortunately we haven't sent the invoice yet."],
            correctIndex: 0,
            explanation: "\"Eine offene Rechnung\" is an unpaid one.",
          },
        ],
      },
      {
        heading: "Am Telefon: höflich, aber klar",
        body: [
          "Frau Ott calls the customer's office. She asks for the person responsible: \"Könnte ich bitte mit dem zuständigen Angestellten sprechen?\" \"Zuständig\" means responsible for something; \"der Zuständige\" is the person in charge.",
          "Polite Konjunktiv II keeps the tone friendly: \"Könnten Sie das bitte prüfen?\", \"Ich wäre Ihnen dankbar, wenn...\", \"Es wäre gut, wenn der Betrag bis Freitag überwiesen würde.\" The passive keeps the focus on the money, not on who is to blame.",
        ],
        examples: [
          { es: "Könnte ich bitte mit dem Zuständigen sprechen?", en: "Could I please speak to the person in charge?" },
          { es: "Könnten Sie das bitte prüfen?", en: "Could you please check that?" },
          { es: "Ich wäre Ihnen dankbar, wenn Sie bis Freitag zahlen würden.", en: "I'd be grateful if you paid by Friday." },
          { es: "Der Betrag wird sofort überwiesen.", en: "The amount is being transferred right away." },
          { es: "Die Rechnung ist wohl verloren gegangen.", en: "The invoice must have got lost." },
        ],
        checkpoint: [
          {
            type: "fill-blank",
            prompt: "Write the German for the bold words.",
            en: "Could I please speak to [the employee in charge]? (a man)",
            sentence: "Könnte ich bitte mit ___ sprechen?",
            answer: "dem zuständigen Angestellten",
            explanation: "Dative after \"mit dem\": -en on both words.",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "Could you please check that?",
            answer: "Könnten Sie das bitte prüfen?",
            altAnswers: ["Könnten Sie das bitte überprüfen?", "Könnten Sie bitte das prüfen?"],
            explanation: "Polite Konjunktiv II: \"könnten\".",
          },
          {
            type: "speak",
            text: "Ich wäre Ihnen dankbar, wenn Sie bis Freitag zahlen würden.",
            prompt: "Say it in German: I'd be grateful if you paid by Friday.",
            tip: "Keep \"würden\" at the very end of the wenn-clause.",
            explanation: "Konjunktiv II for a polite request.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "Please transfer the amount due by Friday.",
        answer: "Bitte überweisen Sie den fälligen Betrag bis Freitag.",
        altAnswers: ["Überweisen Sie bitte den fälligen Betrag bis Freitag.", "Bitte überweisen Sie den offenen Betrag bis Freitag."],
        explanation: "Masculine accusative after \"den\": -en.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "The amount is being transferred right away.",
        answer: "Der Betrag wird sofort überwiesen.",
        altAnswers: ["Der Betrag wird gleich überwiesen."],
        explanation: "Present passive: \"wird\" + Partizip II.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "The delivered posters were fine.",
        answer: "Die gelieferten Plakate waren in Ordnung.",
        altAnswers: ["Die gelieferten Poster waren in Ordnung."],
        explanation: "Partizip II as an adjective, plural after \"die\": -en.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "Could I please speak to the person in charge?",
        answer: "Könnte ich bitte mit dem Zuständigen sprechen?",
        altAnswers: ["Könnte ich bitte den Zuständigen sprechen?", "Könnte ich bitte mit der Zuständigen sprechen?"],
        explanation: "\"Der Zuständige\": an adjective used as a noun; dative -en.",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "[The reminder we sent] went unanswered.",
        sentence: "___ ist unbeantwortet geblieben.",
        answer: "Die gesendete Mahnung",
        altAnswers: ["Die geschickte Mahnung", "Die verschickte Mahnung"],
        explanation: "Partizip II, feminine after \"die\": -e.",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "The invoice [was sent] in March.",
        sentence: "Die Rechnung ___ im März verschickt.",
        answer: "wurde",
        explanation: "Präteritum passive: \"wurde\".",
      },
      {
        type: "multiple-choice",
        question: "Which is the most polite?",
        options: ["Könnten Sie den Betrag bitte bis Freitag überweisen?", "Überweisen Sie den Betrag bis Freitag!", "Sie müssen den Betrag bis Freitag überweisen.", "Der Betrag muss bis Freitag da sein."],
        correctIndex: 0,
        explanation: "Konjunktiv II + \"bitte\" is the polite form.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: Unfortunately the invoice is still unpaid.",
        words: ["Leider", "ist", "die", "Rechnung", "noch", "offen."],
        translation: "Unfortunately the invoice is still unpaid.",
        explanation: "\"Leider\" first, verb second.",
      },
      {
        type: "listen-choose",
        audio: "Die Rechnung ist wohl verloren gegangen.",
        question: "What does the customer say?",
        options: ["The invoice must have got lost.", "The invoice was paid long ago.", "The invoice is wrong.", "The invoice will be sent again."],
        correctIndex: 0,
        explanation: "\"Verloren gehen\" = get lost; \"wohl\" = probably.",
      },
      {
        type: "dictation",
        audio: "Könnten Sie das bitte prüfen?",
        explanation: "\"Könnten\" with ö: Konjunktiv II.",
      },
      {
        type: "speak",
        text: "Bitte überweisen Sie den fälligen Betrag bis Freitag.",
        prompt: "Say it in German: Please transfer the amount due by Friday.",
        tip: "\"Überweisen\": stress on -wei-.",
        explanation: "Formal imperative + adjective ending -en.",
      },
    ],
  },
  {
    slug: "b1-circuit-job-ads",
    level: "DE-B1",
    number: 6,
    title: "Circuit: Job Ads",
    summary: "Rotate the language of German job ads: engagierte/n Mitarbeiter/in, Auszubildende, Angestellte, abgeschlossene Ausbildung, (m/w/d).",
    duration: "13 min",
    sections: [
      {
        heading: "Wir suchen...",
        body: [
          "German job ads (\"Stellenanzeigen\") have a fixed style. They often start with \"Wir suchen\" + accusative: \"Wir suchen eine engagierte Mitarbeiterin / einen engagierten Mitarbeiter\". To include everyone they write \"eine/n engagierte/n Mitarbeiter/in (m/w/d)\": männlich, weiblich, divers.",
          "Adjective-nouns are everywhere here: \"Auszubildende\" (trainees, short \"Azubis\"), \"Angestellte\" (employees), \"Interessierte\" (interested people). They avoid choosing between a male and a female form in the plural.",
        ],
        examples: [
          { es: "Wir suchen einen engagierten Mitarbeiter (m/w/d).", en: "We're looking for a committed employee (m/f/d)." },
          { es: "Wir suchen ab sofort zwei Auszubildende.", en: "We're looking for two trainees, starting immediately." },
          { es: "Die Firma hat 50 Angestellte.", en: "The company has 50 employees." },
          { es: "Interessierte melden sich bitte bei Frau Ott.", en: "Anyone interested, please contact Ms Ott." },
          { es: "Wir bieten ein junges Team und flexible Arbeitszeiten.", en: "We offer a young team and flexible working hours." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "We're looking for two trainees.",
            answer: "Wir suchen zwei Auszubildende.",
            altAnswers: ["Wir suchen zwei Azubis."],
            explanation: "Plural, no article: strong -e.",
          },
          {
            type: "fill-blank",
            prompt: "Write the German for the bold words.",
            en: "We're looking for [a committed employee]. (a man)",
            sentence: "Wir suchen ___.",
            answer: "einen engagierten Mitarbeiter",
            explanation: "Accusative after \"einen\": -en.",
          },
        ],
      },
      {
        heading: "Ihr Profil",
        body: [
          "The second half of the ad lists what they expect: \"Sie haben eine abgeschlossene Ausbildung\" (a completed vocational training), \"gute Deutschkenntnisse\", \"erste Berufserfahrung\". Notice \"abgeschlossen\": a Partizip II used as an adjective.",
          "Then what they offer: \"Wir bieten ein unbefristetes Arbeitsverhältnis\" (a permanent contract), \"eine leistungsgerechte Bezahlung\" (pay that reflects performance). The ad ends with how to apply: \"Bitte schicken Sie Ihre vollständigen Unterlagen an...\"",
        ],
        examples: [
          { es: "Sie haben eine abgeschlossene Ausbildung als Koch.", en: "You have completed training as a cook." },
          { es: "Sie bringen erste Berufserfahrung mit.", en: "You have some work experience." },
          { es: "Gute Deutschkenntnisse sind erforderlich.", en: "Good German is required." },
          { es: "Wir bieten ein unbefristetes Arbeitsverhältnis.", en: "We offer a permanent contract." },
          { es: "Bitte schicken Sie Ihre vollständigen Unterlagen per E-Mail.", en: "Please send your complete application documents by email." },
        ],
        checkpoint: [
          {
            type: "listen-choose",
            audio: "Sie haben eine abgeschlossene Ausbildung.",
            question: "What does the ad expect?",
            options: ["Completed vocational training", "Training that starts soon", "No training at all", "A closed company"],
            correctIndex: 0,
            explanation: "\"Abgeschlossen\" = completed.",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "We offer a permanent contract.",
            answer: "Wir bieten ein unbefristetes Arbeitsverhältnis.",
            altAnswers: ["Wir bieten einen unbefristeten Vertrag.", "Wir bieten einen unbefristeten Arbeitsvertrag."],
            explanation: "Neuter accusative after \"ein\": -es.",
          },
          {
            type: "speak",
            text: "Wir suchen ab sofort zwei Auszubildende.",
            prompt: "Say it in German: We're looking for two trainees, starting immediately.",
            tip: "\"Auszubildende\": AUS-zu-bil-den-de.",
            explanation: "Adjective-noun in the plural with no article: -e.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "The company has 50 employees.",
        answer: "Die Firma hat 50 Angestellte.",
        altAnswers: ["Die Firma hat fünfzig Angestellte.", "Das Unternehmen hat 50 Angestellte.", "Die Firma hat 50 Mitarbeiter."],
        explanation: "Number + adjective-noun with no article: -e.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "You have completed training as a cook.",
        answer: "Sie haben eine abgeschlossene Ausbildung als Koch.",
        explanation: "\"Abgeschlossen\" + feminine accusative after \"eine\": -e.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "Good German is required.",
        answer: "Gute Deutschkenntnisse sind erforderlich.",
        altAnswers: ["Gute Deutschkenntnisse sind notwendig."],
        explanation: "Plural, no article: strong -e.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "Please send your complete documents by email.",
        answer: "Bitte schicken Sie Ihre vollständigen Unterlagen per E-Mail.",
        altAnswers: ["Schicken Sie bitte Ihre vollständigen Unterlagen per E-Mail."],
        explanation: "Plural after \"Ihre\": -en.",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "[Anyone interested] please contact Ms Ott.",
        sentence: "___ melden sich bitte bei Frau Ott.",
        answer: "Interessierte",
        explanation: "Adjective-noun, plural with no article: -e.",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "We offer [a young team].",
        sentence: "Wir bieten ___.",
        answer: "ein junges Team",
        explanation: "Neuter accusative after \"ein\": -es.",
      },
      {
        type: "multiple-choice",
        question: "What does (m/w/d) in a job ad mean?",
        options: ["The job is open to men, women and non-binary people.", "The job is part-time.", "The job is only for women.", "The job starts Monday, Wednesday or Thursday."],
        correctIndex: 0,
        explanation: "männlich / weiblich / divers.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: You have some work experience.",
        words: ["Sie", "bringen", "erste", "Berufserfahrung", "mit."],
        translation: "You have some work experience.",
        explanation: "\"Mitbringen\" is separable: \"mit\" goes to the end.",
      },
      {
        type: "listen-choose",
        audio: "Interessierte melden sich bitte bei Frau Ott.",
        question: "What should you do if you're interested?",
        options: ["Contact Ms Ott", "Visit the shop", "Send nothing", "Wait for a call"],
        correctIndex: 0,
        explanation: "\"Sich melden bei\" = contact.",
      },
      {
        type: "dictation",
        audio: "Wir suchen einen engagierten Mitarbeiter.",
        explanation: "\"Einen engagierten\": accusative -en on both.",
      },
      {
        type: "speak",
        text: "Wir bieten ein junges Team und flexible Arbeitszeiten.",
        prompt: "Say it in German: We offer a young team and flexible working hours.",
        tip: "\"Flexible\": stress on -xi-.",
        explanation: "\"Ein junges Team\": -es; \"flexible Arbeitszeiten\": plural, no article, -e.",
      },
    ],
  },
  {
    slug: "b1-talk-about-you-friends-and-relatives",
    level: "DE-B1",
    number: 7,
    title: "Talk About You: Friends and Relatives",
    summary: "Talk about the people around you: ein Bekannter von mir, meine Verwandten in..., die Kleinen, ein guter Freund.",
    duration: "12 min",
    sections: [
      {
        heading: "Who's who",
        body: [
          "German separates \"ein Freund\" / \"eine Freundin\" (a close friend, sometimes a partner) from \"ein Bekannter\" / \"eine Bekannte\" (someone you know). \"Ein guter Freund von mir\" is a good friend; \"mein Freund\" often means my boyfriend.",
          "Family uses adjective-nouns too: \"meine Verwandten\" (my relatives), \"die Kleinen\" (the little ones, the kids), \"die Alten\" (the old folks, informal). \"Ein Verwandter von mir\" is one relative, a man.",
        ],
        examples: [
          { es: "Ein guter Freund von mir wohnt in Leipzig.", en: "A good friend of mine lives in Leipzig." },
          { es: "Ein Bekannter von mir arbeitet bei der Bahn.", en: "Someone I know works for the railway." },
          { es: "Meine Verwandten in Polen sehe ich nur selten.", en: "I rarely see my relatives in Poland." },
          { es: "Die Kleinen schlafen schon.", en: "The little ones are already asleep." },
          { es: "Meine beste Freundin kenne ich seit der Schule.", en: "I've known my best friend since school." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "A good friend of mine lives in Leipzig.",
            answer: "Ein guter Freund von mir wohnt in Leipzig.",
            altAnswers: ["Ein guter Freund von mir lebt in Leipzig.", "Eine gute Freundin von mir wohnt in Leipzig."],
            explanation: "Masculine nominative after \"ein\": -er.",
          },
          {
            type: "listen-choose",
            audio: "Die Kleinen schlafen schon.",
            question: "Who is asleep?",
            options: ["The children", "The old people", "The small dogs", "The neighbours"],
            correctIndex: 0,
            explanation: "\"Die Kleinen\" = the little ones, the kids.",
          },
        ],
      },
      {
        heading: "Telling a little story",
        body: [
          "To talk about someone, give one fact and one detail: \"Ein Bekannter von mir ist Lehrer. Er hat mir geholfen, eine Wohnung zu finden.\" Use relative clauses to add more: \"Ich habe eine Verwandte, die in Kanada lebt.\"",
          "Adjective-nouns also help you describe people: \"Sie ist die Jüngste in der Familie\", \"Mein Onkel ist der Lustigste von allen\".",
        ],
        examples: [
          { es: "Ich habe eine Verwandte, die in Kanada lebt.", en: "I have a relative who lives in Canada. (a woman)" },
          { es: "Meine Schwester ist die Jüngste in der Familie.", en: "My sister is the youngest in the family." },
          { es: "Mein Onkel ist der Lustigste von allen.", en: "My uncle is the funniest of all." },
          { es: "Am Wochenende treffe ich mich mit ein paar Bekannten.", en: "At the weekend I'm meeting a few people I know." },
          { es: "Ein Bekannter hat mir geholfen, eine Wohnung zu finden.", en: "Someone I know helped me find a flat." },
        ],
        checkpoint: [
          {
            type: "fill-blank",
            prompt: "Write the German for the bold words.",
            en: "My sister is [the youngest] in the family.",
            sentence: "Meine Schwester ist ___ in der Familie.",
            answer: "die Jüngste",
            explanation: "Superlative used as a noun, feminine: \"die Jüngste\".",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "At the weekend I'm meeting a few acquaintances.",
            answer: "Am Wochenende treffe ich mich mit ein paar Bekannten.",
            altAnswers: ["Am Wochenende treffe ich ein paar Bekannte."],
            explanation: "Dative plural after \"mit\": -en.",
          },
          {
            type: "speak",
            text: "Ein Bekannter von mir arbeitet bei der Bahn.",
            prompt: "Say it in German: Someone I know works for the railway.",
            tip: "\"Bekannter\": stress on -kann-.",
            explanation: "\"Ein Bekannter\": masculine nominative -er.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "I rarely see my relatives in Poland.",
        answer: "Meine Verwandten in Polen sehe ich nur selten.",
        altAnswers: ["Ich sehe meine Verwandten in Polen nur selten.", "Ich sehe meine Verwandten in Polen selten.", "Meine Verwandten in Polen sehe ich selten."],
        explanation: "Plural after \"meine\": -en.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "My uncle is the funniest of all.",
        answer: "Mein Onkel ist der Lustigste von allen.",
        explanation: "Superlative as a noun: \"der Lustigste\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "I have a relative who lives in Canada. (a woman)",
        answer: "Ich habe eine Verwandte, die in Kanada lebt.",
        altAnswers: ["Ich habe eine Verwandte, die in Kanada wohnt."],
        explanation: "\"Eine Verwandte\" + relative clause with \"die\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "I've known my best friend since school. (a woman)",
        answer: "Meine beste Freundin kenne ich seit der Schule.",
        altAnswers: ["Ich kenne meine beste Freundin seit der Schule."],
        explanation: "\"Seit\" + present tense for something still true.",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "[Someone I know] helped me find a flat. (a man)",
        sentence: "___ hat mir geholfen, eine Wohnung zu finden.",
        answer: "Ein Bekannter",
        altAnswers: ["Eine Bekannte"],
        explanation: "Masculine nominative after \"ein\": -er.",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "I often visit [my relatives].",
        sentence: "Ich besuche oft ___.",
        answer: "meine Verwandten",
        explanation: "Plural after \"meine\": -en.",
      },
      {
        type: "multiple-choice",
        question: "\"Ein Bekannter von mir\" is...",
        options: ["a man you know, not necessarily a close friend", "your boyfriend", "your brother", "a stranger"],
        correctIndex: 0,
        explanation: "\"Bekannter\" = acquaintance.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: The little ones are already asleep.",
        words: ["Die", "Kleinen", "schlafen", "schon."],
        translation: "The little ones are already asleep.",
        explanation: "Adjective-noun, plural after \"die\": -en.",
      },
      {
        type: "dictation",
        audio: "Ein guter Freund von mir wohnt in Leipzig.",
        explanation: "\"Ein guter Freund\": -er after \"ein\".",
      },
      {
        type: "speak",
        text: "Meine Verwandten in Polen sehe ich nur selten.",
        prompt: "Say it in German: I rarely see my relatives in Poland.",
        tip: "\"Verwandten\": stress on -wand-.",
        explanation: "Object first for emphasis, verb second.",
      },
      {
        type: "speak",
        text: "Meine Schwester ist die Jüngste in der Familie.",
        prompt: "Talk about your family. Say: My sister is the youngest in the family.",
        tip: "\"Jüngste\": round lips for the ü.",
        explanation: "Superlative as a noun.",
      },
    ],
  },
  {
    slug: "b1-fill-the-story-annual-report",
    level: "DE-B1",
    number: 8,
    title: "Fill the Story: The Annual Report",
    summary: "A company report in gaps: die Angestellten, die gestiegenen Kosten, das Erreichte, etwas Neues and the Präteritum passive.",
    duration: "14 min",
    sections: [
      {
        heading: "Das vergangene Jahr",
        body: [
          "Read the start of the annual report (\"der Jahresbericht\") of a small bakery chain: \"Das vergangene Jahr war nicht leicht. Die gestiegenen Kosten für Energie und Mehl waren ein großes Problem. Trotzdem wurden zwei neue Filialen eröffnet und zehn neue Angestellte wurden eingestellt.\"",
          "Notice the Präteritum passive (\"wurden eröffnet\", \"wurden eingestellt\"): reports focus on what happened, not on who did it. And the participles: \"das vergangene Jahr\", \"die gestiegenen Kosten\".",
        ],
        examples: [
          { es: "Das vergangene Jahr war nicht leicht.", en: "The past year wasn't easy." },
          { es: "Die gestiegenen Kosten waren ein großes Problem.", en: "The increased costs were a big problem." },
          { es: "Zwei neue Filialen wurden eröffnet.", en: "Two new branches were opened." },
          { es: "Zehn neue Angestellte wurden eingestellt.", en: "Ten new employees were hired." },
          { es: "Die Preise wurden leicht erhöht.", en: "The prices were raised slightly." },
        ],
        checkpoint: [
          {
            type: "fill-blank",
            prompt: "Write the German for the bold words.",
            en: "[The increased costs] were a big problem.",
            sentence: "___ waren ein großes Problem.",
            answer: "Die gestiegenen Kosten",
            explanation: "Partizip II (finished), plural after \"die\": -en.",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "Two new branches were opened.",
            answer: "Zwei neue Filialen wurden eröffnet.",
            altAnswers: ["Es wurden zwei neue Filialen eröffnet."],
            explanation: "Präteritum passive: \"wurden\" + Partizip II.",
          },
        ],
      },
      {
        heading: "Das Erreichte und etwas Neues",
        body: [
          "The report goes on: \"Wir sind stolz auf das Erreichte. Allen Angestellten danken wir für ihre Arbeit. Im nächsten Jahr planen wir etwas Neues: ein Café mit Frühstück.\"",
          "\"Das Erreichte\" (what has been achieved) is a Partizip II used as a neuter noun, just like \"das Gute\". \"Etwas Neues\" takes -es and a capital letter. \"Allen Angestellten\" is dative plural: -en.",
        ],
        examples: [
          { es: "Wir sind stolz auf das Erreichte.", en: "We are proud of what we have achieved." },
          { es: "Allen Angestellten danken wir für ihre Arbeit.", en: "We thank all employees for their work." },
          { es: "Im nächsten Jahr planen wir etwas Neues.", en: "Next year we're planning something new." },
          { es: "Das Wichtigste ist die Qualität.", en: "The most important thing is quality." },
          { es: "Der Umsatz wurde um fünf Prozent gesteigert.", en: "Turnover was increased by five percent." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "We are proud of what we have achieved.",
            answer: "Wir sind stolz auf das Erreichte.",
            explanation: "\"Das Erreichte\": Partizip II as a neuter noun.",
          },
          {
            type: "listen-choose",
            audio: "Im nächsten Jahr planen wir etwas Neues.",
            question: "What is planned for next year?",
            options: ["Something new", "Nothing special", "The same as this year", "Fewer branches"],
            correctIndex: 0,
            explanation: "\"Etwas Neues\" = something new.",
          },
          {
            type: "speak",
            text: "Allen Angestellten danken wir für ihre Arbeit.",
            prompt: "Say it in German: We thank all employees for their work.",
            tip: "Dative first, then the verb in second place.",
            explanation: "\"Danken\" + dative: \"allen Angestellten\".",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "[The past year] wasn't easy.",
        sentence: "___ war nicht leicht.",
        answer: "Das vergangene Jahr",
        altAnswers: ["Das letzte Jahr"],
        explanation: "Partizip II \"vergangen\", neuter after \"das\": -e.",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "Ten new employees [were hired].",
        sentence: "Zehn neue Angestellte ___ eingestellt.",
        answer: "wurden",
        explanation: "Plural subject: \"wurden\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "We are proud of [what we have achieved].",
        sentence: "Wir sind stolz auf ___.",
        answer: "das Erreichte",
        explanation: "Neuter noun from the Partizip II.",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "Next year we're planning [something new].",
        sentence: "Im nächsten Jahr planen wir ___.",
        answer: "etwas Neues",
        explanation: "\"Etwas\" + capital + -es.",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "We thank [all employees] for their work.",
        sentence: "Wir danken ___ für ihre Arbeit.",
        answer: "allen Angestellten",
        altAnswers: ["allen Mitarbeitern"],
        explanation: "\"Danken\" + dative plural: -en.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "The prices were raised slightly.",
        answer: "Die Preise wurden leicht erhöht.",
        altAnswers: ["Die Preise wurden etwas erhöht."],
        explanation: "Präteritum passive.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "The most important thing is quality.",
        answer: "Das Wichtigste ist die Qualität.",
        explanation: "Superlative as a neuter noun.",
      },
      {
        type: "multiple-choice",
        question: "Which completes it? Die ___ Kosten waren ein Problem. (costs that have gone up)",
        options: ["gestiegenen", "steigenden", "gestiegene", "steigende"],
        correctIndex: 0,
        explanation: "Finished: Partizip II; plural after \"die\": -en.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: Turnover was increased by five percent.",
        words: ["Der", "Umsatz", "wurde", "um", "fünf", "Prozent", "gesteigert."],
        translation: "Turnover was increased by five percent.",
        explanation: "\"Wurde\" second, participle last.",
      },
      {
        type: "listen-choose",
        audio: "Zehn neue Angestellte wurden eingestellt.",
        question: "What happened?",
        options: ["Ten new employees were hired.", "Ten employees left.", "Ten employees will be hired.", "Ten branches were opened."],
        correctIndex: 0,
        explanation: "\"Einstellen\" = hire; \"wurden\" = past passive.",
      },
      {
        type: "dictation",
        audio: "Das vergangene Jahr war nicht leicht.",
        explanation: "\"Vergangene\": Partizip II as an adjective.",
      },
      {
        type: "speak",
        text: "Wir sind stolz auf das Erreichte.",
        prompt: "Say it in German: We are proud of what we have achieved.",
        tip: "\"Erreichte\": er-REICH-te, ch as in \"ich\".",
        explanation: "\"Stolz auf\" + accusative.",
      },
    ],
  },
  {
    slug: "b1-themed-review-culture-shock",
    level: "DE-B1",
    number: 9,
    title: "Themed Review: Culture Shock",
    summary: "What surprised a newcomer to Germany: das Merkwürdigste war..., die Deutschen, nichts Besonderes, plus adjective endings.",
    duration: "15 min",
    sections: [
      {
        heading: "Ana erzählt",
        body: [
          "Ana came from Brazil to Freiburg a year ago. She writes: \"Das Merkwürdigste war am Anfang der Sonntag. Alle Geschäfte waren geschlossen! Die Deutschen gehen sonntags spazieren oder treffen Verwandte. Für meine Nachbarn war das nichts Besonderes, aber für mich war es etwas ganz Neues.\"",
          "Look at the adjective-nouns: \"das Merkwürdigste\" (the strangest thing), \"die Deutschen\" (the Germans), \"nichts Besonderes\", \"etwas ganz Neues\". And \"alle Geschäfte waren geschlossen\": a Partizip II after \"sein\", no ending.",
        ],
        examples: [
          { es: "Das Merkwürdigste war am Anfang der Sonntag.", en: "At first the strangest thing was Sunday." },
          { es: "Alle Geschäfte waren geschlossen.", en: "All the shops were closed." },
          { es: "Die Deutschen gehen sonntags gern spazieren.", en: "Germans like to go for a walk on Sundays." },
          { es: "Für meine Nachbarn war das nichts Besonderes.", en: "For my neighbours that was nothing special." },
          { es: "Für mich war es etwas ganz Neues.", en: "For me it was something completely new." },
        ],
        checkpoint: [
          {
            type: "fill-blank",
            prompt: "Write the German for the bold words.",
            en: "At first [the strangest thing] was Sunday.",
            sentence: "___ war am Anfang der Sonntag.",
            answer: "Das Merkwürdigste",
            altAnswers: ["Das Seltsamste", "Das Komischste"],
            explanation: "Superlative as a neuter noun: \"das ...ste\".",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "For my neighbours that was nothing special.",
            answer: "Für meine Nachbarn war das nichts Besonderes.",
            altAnswers: ["Für meine Nachbarn war es nichts Besonderes."],
            explanation: "\"Nichts\" + capital + -es.",
          },
        ],
      },
      {
        heading: "Mülltrennung und Pünktlichkeit",
        body: [
          "Ana goes on: \"Dann der Müll! Es gibt eine gelbe Tonne, eine blaue Tonne, eine braune Tonne... Gebrauchte Flaschen bringt man zum Supermarkt zurück. Ein Bekannter hat mir alles erklärt. Und wenn man um acht Uhr eingeladen ist, kommt man um acht, nicht um halb neun!\"",
          "This is a good model for your own story: say what was strange, give an example, and say how you feel now: \"Inzwischen finde ich das ganz normal.\"",
        ],
        examples: [
          { es: "Es gibt eine gelbe Tonne für Plastik.", en: "There's a yellow bin for plastic." },
          { es: "Gebrauchte Flaschen bringt man zum Supermarkt zurück.", en: "You take used bottles back to the supermarket." },
          { es: "Ein Bekannter hat mir alles erklärt.", en: "Someone I know explained everything to me." },
          { es: "Wenn man um acht eingeladen ist, kommt man um acht.", en: "If you're invited for eight, you arrive at eight." },
          { es: "Inzwischen finde ich das ganz normal.", en: "By now I find that completely normal." },
        ],
        checkpoint: [
          {
            type: "listen-choose",
            audio: "Gebrauchte Flaschen bringt man zum Supermarkt zurück.",
            question: "What do you do with used bottles?",
            options: ["Take them back to the supermarket", "Throw them in the yellow bin", "Keep them at home", "Buy new ones"],
            correctIndex: 0,
            explanation: "\"Zurückbringen\" = take back.",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "Someone I know explained everything to me.",
            answer: "Ein Bekannter hat mir alles erklärt.",
            altAnswers: ["Eine Bekannte hat mir alles erklärt."],
            explanation: "\"Ein Bekannter\": masculine nominative -er.",
          },
          {
            type: "speak",
            text: "Inzwischen finde ich das ganz normal.",
            prompt: "Say it in German: By now I find that completely normal.",
            tip: "\"Inzwischen\": stress on -zwi-.",
            explanation: "Time word first, verb second.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "All the shops were closed.",
        answer: "Alle Geschäfte waren geschlossen.",
        altAnswers: ["Alle Läden waren geschlossen.", "Alle Geschäfte waren zu."],
        explanation: "Partizip II after \"sein\": no ending.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "Germans like to go for a walk on Sundays.",
        answer: "Die Deutschen gehen sonntags gern spazieren.",
        altAnswers: ["Sonntags gehen die Deutschen gern spazieren.", "Die Deutschen gehen am Sonntag gern spazieren."],
        explanation: "\"Die Deutschen\": plural after \"die\": -en.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "For me it was something completely new.",
        answer: "Für mich war es etwas ganz Neues.",
        altAnswers: ["Für mich war das etwas ganz Neues.", "Für mich war es etwas völlig Neues."],
        explanation: "\"Etwas\" + capital + -es.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "There's a yellow bin for plastic.",
        answer: "Es gibt eine gelbe Tonne für Plastik.",
        explanation: "Feminine accusative after \"eine\": -e.",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "You take [used bottles] back to the supermarket.",
        sentence: "___ bringt man zum Supermarkt zurück.",
        answer: "Gebrauchte Flaschen",
        altAnswers: ["Leere Flaschen"],
        explanation: "Partizip II as an adjective; plural, no article: -e.",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "I was invited by [a German]. (a woman)",
        sentence: "Ich wurde von ___ eingeladen.",
        answer: "einer Deutschen",
        explanation: "Dative after \"von einer\": -en.",
      },
      {
        type: "multiple-choice",
        question: "Which is correct?",
        options: ["Die Deutschen sind pünktlich.", "Die Deutsche sind pünktlich.", "Die Deutscher sind pünktlich.", "Deutschen sind pünktlich."],
        correctIndex: 0,
        explanation: "Plural after \"die\": -en.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: If you're invited for eight, you arrive at eight.",
        words: ["Wenn", "man", "um", "acht", "eingeladen", "ist,", "kommt", "man", "um", "acht."],
        translation: "If you're invited for eight, you arrive at eight.",
        explanation: "Wenn-clause first, verb last; then the main verb comes straight after the comma.",
      },
      {
        type: "listen-choose",
        audio: "Das Merkwürdigste war am Anfang der Sonntag.",
        question: "What does Ana say?",
        options: ["At first, Sunday was the strangest thing.", "Sunday is her favourite day.", "At first she worked on Sundays.", "Sunday was nothing special."],
        correctIndex: 0,
        explanation: "\"Das Merkwürdigste\" = the strangest thing.",
      },
      {
        type: "dictation",
        audio: "Für meine Nachbarn war das nichts Besonderes.",
        explanation: "\"Nichts Besonderes\": capital B, ending -es.",
      },
      {
        type: "speak",
        text: "Das Merkwürdigste war am Anfang der Sonntag.",
        prompt: "Tell your own story. Start with: At first the strangest thing was Sunday.",
        tip: "\"Merkwürdigste\": MERK-wür-dig-ste.",
        explanation: "Superlative as a noun to introduce what surprised you.",
      },
    ],
  },
];

export const DE_B1_U20_WRITING: WriteExercise = {
  type: "write",
  prompt: "Write a short text (80-150 words) for a blog for newcomers: describe the people around you in Germany or in your town (friends, acquaintances, relatives, colleagues) and say what surprised you most when you arrived. Use adjectives as nouns and at least one participle as an adjective.",
  minWords: 80,
  maxWords: 150,
  rubric: [
    "Uses adjectives as nouns with the right endings (\"ein Bekannter\", \"meine Verwandten\", \"die Deutschen\")",
    "Uses \"etwas\" / \"nichts\" + adjective (\"etwas Neues\", \"nichts Besonderes\") or \"das ...ste\" (\"das Merkwürdigste\")",
    "Uses at least one participle as an adjective (\"geschlossene Geschäfte\", \"die steigenden Preise\")",
    "Clear structure: who the people are, what surprised you, how you feel now",
  ],
  modelAnswer: "Ich wohne seit einem Jahr in Freiburg. Am Anfang kannte ich niemanden, aber jetzt habe ich ein paar gute Freunde. Ein Bekannter von mir arbeitet in einer Bäckerei und hat mir viel über die Stadt erzählt. Meine Verwandten leben in Brasilien, und ich telefoniere jeden Sonntag mit ihnen. Das Merkwürdigste war für mich am Anfang der Sonntag: Alle Geschäfte waren geschlossen! Für die Deutschen ist das nichts Besonderes, aber für mich war es etwas ganz Neues. Auch der Müll war ein Abenteuer. Gebrauchte Flaschen bringt man zum Supermarkt zurück, und für Plastik gibt es eine gelbe Tonne. Eine Kollegin hat mir alles erklärt. Inzwischen finde ich das ganz normal, und die ruhigen Sonntage gefallen mir sogar.",
  explanation: "The model introduces the people around the writer with adjective-nouns (\"ein Bekannter\", \"meine Verwandten\", \"die Deutschen\"), describes the surprise with \"das Merkwürdigste\", \"nichts Besonderes\" and \"etwas ganz Neues\", and uses the participle \"gebrauchte Flaschen\" as an adjective. It ends by saying how the writer feels now.",
};
