// Synced from cheneygross-afk/lengo:src/lib/lessons/de-b2-u14-extra.ts by scripts/sync-content.mjs -- edit it there, not here.
import type { Lesson } from "./types";
// German B2, Unit 14 extra practice: Modal Verbs: Subjective Meaning.

export const DE_B2_U14_EXTRA: Lesson[] = [
  {
    slug: "b2-subjective-modals-extra-1",
    level: "DE-B2",
    number: 1,
    optional: true,
    title: "Extra Practice: The Perfect Infinitive",
    summary: "Form the perfect infinitive after modals: gemacht haben or gegangen sein, and the passive gemacht worden sein.",
    duration: "12 min",
    sections: [
      {
        heading: "Recap: participle + haben or sein",
        body: [
          "The perfect infinitive is the participle + the infinitive of the auxiliary the verb uses in the Perfekt: \"gemacht haben\", \"gesehen haben\", but \"gegangen sein\", \"gefahren sein\", \"gewesen sein\", \"passiert sein\".",
          "After a subjective modal it moves to the end as one block: \"Sie muss es vergessen haben.\" \"Er dürfte schon angekommen sein.\" Passive: participle + \"worden sein\": \"Das Bild soll gestohlen worden sein.\"",
        ],
        examples: [
          { es: "Sie muss es vergessen haben.", en: "She must have forgotten it." },
          { es: "Er dürfte schon angekommen sein.", en: "He has probably arrived already." },
          { es: "Das kann nicht passiert sein.", en: "That can't have happened." },
          { es: "Das Bild soll gestohlen worden sein.", en: "The painting is said to have been stolen." },
          { es: "Sie könnten den Weg verloren haben.", en: "They could have lost their way." },
        ],
        checkpoint: [
          {
            type: "fill-blank",
            prompt: "Write the German for the bold words.",
            en: "He has probably [arrived] already.",
            sentence: "Er dürfte schon ___.",
            answer: "angekommen sein",
            explanation: "\"Ankommen\" takes \"sein\".",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "She must have forgotten it.",
            answer: "Sie muss es vergessen haben.",
            explanation: "\"Vergessen\" takes \"haben\".",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "That can't [have happened].",
        sentence: "Das kann nicht ___.",
        answer: "passiert sein",
        altAnswers: ["geschehen sein"],
        explanation: "\"Passieren\" takes \"sein\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "They could have [lost their way].",
        sentence: "Sie könnten den Weg ___.",
        answer: "verloren haben",
        explanation: "\"Verlieren\" takes \"haben\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "The painting is said to [have been stolen].",
        sentence: "Das Bild soll ___.",
        answer: "gestohlen worden sein",
        explanation: "Passive perfect infinitive: \"gestohlen worden sein\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "She must [have fallen asleep] in front of the TV.",
        sentence: "Sie muss vor dem Fernseher ___.",
        answer: "eingeschlafen sein",
        explanation: "\"Einschlafen\": change of state → \"sein\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "He must have driven too fast.",
        answer: "Er muss zu schnell gefahren sein.",
        explanation: "\"Fahren\" (motion) takes \"sein\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "You must have made a mistake.",
        answer: "Du musst einen Fehler gemacht haben.",
        altAnswers: ["Sie müssen einen Fehler gemacht haben.", "Ihr müsst einen Fehler gemacht haben."],
        explanation: "\"Machen\" takes \"haben\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "The letter is probably lost.",
        answer: "Der Brief dürfte verloren gegangen sein.",
        altAnswers: ["Der Brief ist wahrscheinlich verloren gegangen.", "Der Brief dürfte verloren gegangen sein!", "Der Brief ist wohl verloren gegangen."],
        explanation: "\"Verloren gehen\" takes \"sein\": \"verloren gegangen sein\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "The house is said to have been built in 1890.",
        answer: "Das Haus soll 1890 gebaut worden sein.",
        explanation: "Passive rumour: \"soll ... gebaut worden sein\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "He can't have been at home.",
        answer: "Er kann nicht zu Hause gewesen sein.",
        altAnswers: ["Er kann nicht daheim gewesen sein."],
        explanation: "\"Gewesen sein\".",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: She must have been very happy.",
        words: ["Sie", "muss", "sehr", "glücklich", "gewesen", "sein."],
        translation: "She must have been very happy.",
        explanation: "\"Gewesen sein\" at the end.",
      },
      {
        type: "multiple-choice",
        question: "Which perfect infinitive is correct for bleiben?",
        options: ["geblieben sein", "geblieben haben", "gebleibt haben", "gebleibt sein"],
        correctIndex: 0,
        explanation: "\"Er ist geblieben\" → \"geblieben sein\".",
      },
      {
        type: "listen-choose",
        audio: "Das Bild soll gestohlen worden sein.",
        question: "What does it mean?",
        options: ["The painting is said to have been stolen.", "The painting should have been stolen.", "The painting is being stolen.", "Someone wanted to steal the painting."],
        correctIndex: 0,
        explanation: "\"Soll ... gestohlen worden sein\" = is said to have been stolen.",
      },
      {
        type: "dictation",
        audio: "Er dürfte schon angekommen sein.",
        explanation: "\"Angekommen sein\": perfect infinitive with sein.",
      },
      {
        type: "speak",
        text: "Er muss zu schnell gefahren sein.",
        prompt: "Say it in German: He must have driven too fast.",
        explanation: "\"Gefahren sein\".",
      },
    ],
  },
  {
    slug: "b2-subjective-modals-extra-2",
    level: "DE-B2",
    number: 2,
    optional: true,
    title: "Extra Practice: Soll or Will?",
    summary: "Decide who makes the claim: other people (soll) or the subject of the sentence (will).",
    duration: "12 min",
    sections: [
      {
        heading: "Recap: who is the source?",
        body: [
          "\"Soll\": other people say it (rumour, report, hearsay). \"Er soll im Gefängnis gewesen sein\" = people say he was in prison.",
          "\"Will\": the subject says it about him- or herself, and the speaker doubts it. \"Er will nie im Gefängnis gewesen sein\" = he claims never to have been in prison.",
          "Test: replace with a full sentence. \"Man sagt, dass er ...\" → \"soll\". \"Er behauptet, dass er ...\" → \"will\".",
        ],
        examples: [
          { es: "Er soll im Gefängnis gewesen sein.", en: "He is said to have been in prison." },
          { es: "Er will nie im Gefängnis gewesen sein.", en: "He claims never to have been in prison." },
          { es: "Sie soll fünf Sprachen sprechen.", en: "She is said to speak five languages." },
          { es: "Sie will fünf Sprachen sprechen.", en: "She claims to speak five languages." },
        ],
        checkpoint: [
          {
            type: "fill-blank",
            prompt: "Write the German for the bold words.",
            en: "Max says that he speaks five languages: Max [claims to] speak five languages.",
            sentence: "Max ___ fünf Sprachen sprechen.",
            answer: "will",
            explanation: "Max himself makes the claim → \"will\".",
          },
          {
            type: "fill-blank",
            prompt: "Write the German for the bold words.",
            en: "Everybody says that she was in prison: she [is said to] have been in prison.",
            sentence: "Sie ___ im Gefängnis gewesen sein.",
            answer: "soll",
            explanation: "Other people say it → \"soll\".",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "The newspaper writes that the mayor took bribes: the mayor [is said to] have taken bribes.",
        sentence: "Der Bürgermeister ___ Bestechungsgeld angenommen haben.",
        answer: "soll",
        explanation: "The newspaper is the source → \"soll\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "The mayor says he never took any money: he [claims] never to have taken any money.",
        sentence: "Der Bürgermeister ___ nie Geld angenommen haben.",
        answer: "will",
        explanation: "The subject's own claim → \"will\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "My son [claims to] have done his homework already.",
        sentence: "Mein Sohn ___ die Hausaufgaben schon gemacht haben.",
        answer: "will",
        explanation: "He says it himself, and the parent doubts it.",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "The new café [is supposed to] be very good.",
        sentence: "Das neue Café ___ sehr gut sein.",
        answer: "soll",
        explanation: "Other people's opinion → \"soll\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "She claims to speak five languages.",
        answer: "Sie will fünf Sprachen sprechen.",
        altAnswers: ["Sie behauptet, fünf Sprachen zu sprechen."],
        explanation: "\"Will\" = the subject claims.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "He is said to have been in prison.",
        answer: "Er soll im Gefängnis gewesen sein.",
        altAnswers: ["Er soll im Knast gewesen sein.", "Man sagt, er sei im Gefängnis gewesen."],
        explanation: "\"Soll\" + \"gewesen sein\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "The suspect claims to have been in Munich that evening.",
        answer: "Der Verdächtige will an dem Abend in München gewesen sein.",
        altAnswers: ["Der Verdächtige will an diesem Abend in München gewesen sein.", "Der Verdächtige will an jenem Abend in München gewesen sein.", "Die Verdächtige will an dem Abend in München gewesen sein.", "Die Verdächtige will an diesem Abend in München gewesen sein."],
        explanation: "The suspect's own alibi → \"will\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Er will nichts davon gewusst haben.",
        answer: "He claims not to have known anything about it.",
        altAnswers: ["He claims to have known nothing about it.", "He claims he didn't know anything about it.", "He claims he knew nothing about it."],
        explanation: "Not wants to have known: \"will\" + perfect infinitive = claims.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Die Firma soll bald schließen.",
        answer: "The company is said to be closing soon.",
        altAnswers: ["Apparently the company is closing soon.", "The company is supposed to be closing soon.", "Apparently the company will close soon.", "The company is said to be closing down soon."],
        explanation: "Subjective \"soll\" = is said to.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: He claims to have known nothing.",
        words: ["Er", "will", "nichts", "gewusst", "haben."],
        translation: "He claims to have known nothing.",
        explanation: "\"Will\" + perfect infinitive.",
      },
      {
        type: "multiple-choice",
        question: "\"Sie will die Beste in ihrem Jahrgang gewesen sein.\" Who says she was the best?",
        options: ["She does.", "Her teachers do.", "Everybody does.", "The speaker does, and is sure."],
        correctIndex: 0,
        explanation: "\"Will\" = the subject's own claim.",
      },
      {
        type: "listen-choose",
        audio: "Sie soll fünf Sprachen sprechen.",
        question: "What does it mean?",
        options: ["She is said to speak five languages.", "She claims to speak five languages.", "She should speak five languages.", "She wants to speak five languages."],
        correctIndex: 0,
        explanation: "\"Soll\" = people say.",
      },
      {
        type: "dictation",
        audio: "Der Bürgermeister will nie Geld angenommen haben.",
        explanation: "\"Will\" + \"angenommen haben\".",
      },
      {
        type: "speak",
        text: "Er will nie im Gefängnis gewesen sein.",
        prompt: "Say it in German: He claims never to have been in prison.",
        explanation: "\"Will\" + \"gewesen sein\".",
      },
    ],
  },
  {
    slug: "b2-subjective-modals-extra-3",
    level: "DE-B2",
    number: 3,
    optional: true,
    title: "Extra Practice: Celebrity Gossip",
    summary: "Read and write celebrity rumours with soll and the Konjunktiv I.",
    duration: "13 min",
    sections: [
      {
        heading: "Recap: two ways to pass on gossip",
        body: [
          "Gossip magazines love \"soll\": \"Die Sängerin soll sich von ihrem Mann getrennt haben.\" Newspapers often prefer the Konjunktiv I with a source: \"Laut einem Freund habe sie sich getrennt.\" \"Ein Insider sagt, das Paar sei schon seit Monaten zerstritten.\"",
          "Useful words: \"sich trennen\" (to split up), \"heimlich\" (secretly), \"schwanger\" (pregnant), \"das Comeback\", \"zerstritten sein\" (to have fallen out), \"laut\" + dative (according to), \"ein Insider\", \"dementieren\" (to deny officially).",
        ],
        examples: [
          { es: "Die Sängerin soll sich von ihrem Mann getrennt haben.", en: "The singer is said to have split up with her husband." },
          { es: "Laut einem Freund habe sie sich schon im Mai getrennt.", en: "According to a friend, she split up back in May." },
          { es: "Das Paar soll heimlich geheiratet haben.", en: "The couple are said to have married secretly." },
          { es: "Ein Insider sagt, die Band sei zerstritten.", en: "An insider says the band has fallen out." },
          { es: "Sein Manager hat das Gerücht dementiert.", en: "His manager denied the rumour." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into German.",
            source: "The couple are said to have married secretly.",
            answer: "Das Paar soll heimlich geheiratet haben.",
            explanation: "\"Soll\" + \"geheiratet haben\".",
          },
          {
            type: "fill-blank",
            prompt: "Write the German for the bold words.",
            en: "An insider says the band [has fallen out].",
            sentence: "Ein Insider sagt, die Band ___ zerstritten.",
            answer: "sei",
            explanation: "Konjunktiv I of \"sein\" for reported speech.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "The actor [is said to be planning] a comeback.",
        sentence: "Der Schauspieler ___ ein Comeback planen.",
        answer: "soll",
        explanation: "Rumour → \"soll\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "According to a friend, she [is] pregnant.",
        sentence: "Laut einer Freundin ___ sie schwanger.",
        answer: "sei",
        explanation: "Konjunktiv I: \"sie sei\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "The singer [is said to have bought] a castle in Bavaria.",
        sentence: "Der Sänger ___ ein Schloss in Bayern.",
        answer: "soll gekauft haben",
        explanation: "\"Soll\" + perfect infinitive.",
      },
      {
        type: "fill-blank",
        prompt: "Write the German for the bold words.",
        en: "His manager [denied] the rumour.",
        sentence: "Sein Manager hat das Gerücht ___.",
        answer: "dementiert",
        explanation: "\"Dementieren\" = to deny officially.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "The singer is said to have split up with her husband.",
        answer: "Die Sängerin soll sich von ihrem Mann getrennt haben.",
        explanation: "Reflexive \"sich trennen\": the pronoun stays after \"soll\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "According to an insider, the couple have been arguing for months.",
        answer: "Laut einem Insider streitet das Paar schon seit Monaten.",
        altAnswers: ["Laut einem Insider streite das Paar schon seit Monaten.", "Laut einem Insider streitet sich das Paar schon seit Monaten.", "Laut einem Insider streite sich das Paar schon seit Monaten.", "Einem Insider zufolge streitet das Paar schon seit Monaten."],
        explanation: "\"Laut\" + dative; \"seit\" + present tense.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "The footballer is said to earn ten million a year.",
        answer: "Der Fußballer soll zehn Millionen im Jahr verdienen.",
        altAnswers: ["Der Fußballspieler soll zehn Millionen im Jahr verdienen.", "Der Fußballer soll zehn Millionen pro Jahr verdienen.", "Der Fußballspieler soll zehn Millionen pro Jahr verdienen."],
        explanation: "Present rumour: \"soll\" + infinitive.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into German.",
        source: "The band has fallen out.",
        answer: "Die Band ist zerstritten.",
        altAnswers: ["Die Band hat sich zerstritten."],
        explanation: "\"Zerstritten sein\" or \"sich zerstreiten\".",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: The couple are said to have married secretly.",
        words: ["Das", "Paar", "soll", "heimlich", "geheiratet", "haben."],
        translation: "The couple are said to have married secretly.",
        explanation: "\"Soll\" in position 2, perfect infinitive at the end.",
      },
      {
        type: "multiple-choice",
        question: "Rewrite with soll: Man sagt, der Sänger sei krank gewesen.",
        options: ["Der Sänger soll krank gewesen sein.", "Der Sänger soll krank sein gewesen.", "Der Sänger sollte krank gewesen haben.", "Der Sänger will krank gewesen sein."],
        correctIndex: 0,
        explanation: "\"Man sagt, er sei ... gewesen\" = \"Er soll ... gewesen sein\".",
      },
      {
        type: "multiple-choice",
        question: "Which headline only reports the rumour, without confirming it?",
        options: ["Star-Paar soll sich getrennt haben", "Star-Paar hat sich getrennt", "Star-Paar muss sich trennen", "Star-Paar will sich trennen"],
        correctIndex: 0,
        explanation: "\"Soll ... haben\" = it's said; the others state facts, obligations or intentions.",
      },
      {
        type: "listen-choose",
        audio: "Der Sänger soll ein Schloss in Bayern gekauft haben.",
        question: "What's the rumour?",
        options: ["The singer bought a castle in Bavaria.", "The singer should buy a castle in Bavaria.", "The singer wants to buy a castle in Bavaria.", "The singer sold his castle in Bavaria."],
        correctIndex: 0,
        explanation: "\"Soll ... gekauft haben\" = is said to have bought.",
      },
      {
        type: "dictation",
        audio: "Sein Manager hat das Gerücht dementiert.",
        explanation: "\"Dementieren\": to deny officially.",
      },
      {
        type: "speak",
        text: "Die Schauspielerin soll heimlich geheiratet haben.",
        prompt: "Pass on the rumour in German: The actress is said to have married secretly.",
        explanation: "\"Soll\" + \"geheiratet haben\".",
      },
    ],
  },
];
