// Synced from cheneygross-afk/lengo:src/lib/lessons/de-c2.ts by scripts/sync-content.mjs -- edit it there, not here.
import type { Lesson } from "./types";
import type { UnitOutline } from "./units";
import { buildGermanLevel, type GermanUnitDef } from "./de-units";

// German C2: generated by scripts/gen-german-level.ts from
// docs/german-course/syllabus-c2.md and the unit files
// (de-c2-u<NN>.ts, de-c2-u<NN>-extra.ts). Don't edit by hand;
// re-run the script when a unit file is added.
const UNITS: GermanUnitDef[] = [
];

const LEVEL = buildGermanLevel("C2", UNITS);
export const DE_C2_LESSONS: Lesson[] = LEVEL.lessons;
export const DE_C2_UNITS: UnitOutline[] = LEVEL.units;
