// Synced from cheneygross-afk/lengo:src/lib/lessons/de-culture.ts by scripts/sync-content.mjs -- edit it there, not here.
import type { Lesson } from "./types";
import type { UnitOutline } from "./units";
import { buildGermanLevel, type GermanUnitDef } from "./de-units";
import { DE_CULTURE_U01, DE_CULTURE_U01_WRITING } from "./de-culture-u01";
import { DE_CULTURE_U02, DE_CULTURE_U02_WRITING } from "./de-culture-u02";
import { DE_CULTURE_U03, DE_CULTURE_U03_WRITING } from "./de-culture-u03";

// German Culture: generated by scripts/gen-german-level.ts from
// docs/german-course/syllabus-culture.md and the unit files
// (de-culture-u<NN>.ts, de-culture-u<NN>-extra.ts). Don't edit by hand;
// re-run the script when a unit file is added.
const UNITS: GermanUnitDef[] = [
  { id: "u01", title: "Feste & Food Culture", description: "Can talk about the German festive calendar and the rituals of the German table, from Kaffee und Kuchen to Abendbrot, and behave like a guest who knows the unwritten rules.", lessons: DE_CULTURE_U01, writing: DE_CULTURE_U01_WRITING },
  { id: "u02", title: "Football, Film & Music", description: "Can follow and join everyday talk about football, German-language film and music, and recognise the expressions they have lent to everyday German.", lessons: DE_CULTURE_U02, writing: DE_CULTURE_U02_WRITING },
  { id: "u03", title: "Customs & Social Rules", description: "Can greet, address, visit and live next to people the German way, and understand the unwritten rules of punctuality, quiet hours, recycling, Feierabend and small talk.", lessons: DE_CULTURE_U03, writing: DE_CULTURE_U03_WRITING },
];

const LEVEL = buildGermanLevel("Culture", UNITS);
export const DE_CULTURE_LESSONS: Lesson[] = LEVEL.lessons;
export const DE_CULTURE_UNITS: UnitOutline[] = LEVEL.units;
