// Synced from cheneygross-afk/lengo:src/lib/lessons/en-a2-u16-extra.ts by scripts/sync-content.mjs -- edit it there, not here.
import type { Lesson } from "./types";

// Extra practice (optional) lessons for EN-A2 unit u16.

export const EN_A2_U16_EXTRA: Lesson[] = [
  // ---------------------------------------------------------------------
  {
    slug: "en-a2-adverbs-drill-1",
    optional: true,
    level: "EN-A2",
    number: 1,
    title: "Práctica extra: adverbios en -ly",
    summary: "Práctica de la formación de los adverbios: la ortografía de \"-ly\" (\"easily\", \"happily\", \"carefully\"), los irregulares \"well\", \"fast\", \"hard\" y \"late\", y los errores *very good, *fastly y \"hardly\" por \"hard\".",
    duration: "10 min",
    sections: [
      {
        heading: "Recordatorio: la ortografía de -ly",
        body: [
          "Adjetivo + \"-ly\" = adverbio: \"slow\" → \"slowly\", \"quiet\" → \"quietly\". Consonante + \"y\" cambia a \"-ily\": \"happy\" → \"happily\", \"easy\" → \"easily\". Los de \"-le\" pierden la \"e\": \"gentle\" → \"gently\". Los de \"-ic\" añaden \"-ally\": \"automatic\" → \"automatically\".",
          "Los adjetivos en \"-ful\" quedan con doble \"l\": \"careful\" → \"carefully\", \"beautiful\" → \"beautifully\".",
        ],
        examples: [
          { es: "He opened the door quietly.", en: "Abrió la puerta sin hacer ruido." },
          { es: "She smiled happily.", en: "Sonrió con alegría." },
          { es: "I passed the test easily.", en: "Aprobé el examen fácilmente." },
          { es: "The door closes automatically.", en: "La puerta se cierra automáticamente." },
          { es: "Please listen carefully.", en: "Por favor, escucha con atención." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "¿Cuál es el adverbio de \"happy\"?",
            options: ["happily", "happyly", "happly", "happy"],
            correctIndex: 0,
            explanation: "Consonante + \"y\": la \"y\" pasa a \"i\" y se añade \"-ly\": \"happily\".",
          },
          {
            type: "fill-blank",
            prompt: "Escribe en inglés las palabras en negrita.",
            sentence: "Please listen ___.",
            answer: "carefully",
            altAnswers: ["closely", "attentively"],
            en: "Por favor, escucha [con atención].",
            explanation: "\"Careful\" + \"-ly\" = \"carefully\", con doble \"l\". «Con atención» se dice con un solo adverbio.",
          },
        ],
      },
      {
        heading: "Recordatorio: well, fast, hard, late",
        body: [
          "El adverbio de \"good\" es \"well\": \"She sings well\", nunca *She sings good. \"Fast\", \"hard\", \"late\" y \"early\" son iguales como adjetivo y como adverbio: \"He drives fast\" (*fastly no existe), \"They work hard\".",
          "Trampas: \"hardly\" no es el adverbio de \"hard\": significa «apenas». Y \"lately\" no es «tarde», sino «últimamente».",
        ],
        examples: [
          { es: "Tom plays tennis very well.", en: "Tom juega muy bien al tenis." },
          { es: "He runs very fast.", en: "Corre muy rápido." },
          { es: "I work hard, but I don't earn much.", en: "Trabajo duro, pero gano poco." },
          { es: "The train arrived late again.", en: "El tren llegó tarde otra vez." },
          { es: "She was so tired that she could hardly walk.", en: "Estaba tan cansada que apenas podía caminar." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "Corrige: *She speaks French very good.",
            options: ["She speaks French very well.", "She speaks French very goodly.", "She speaks very well French.", "She speaks French very nice."],
            correctIndex: 0,
            explanation: "Después de un verbo de acción va el adverbio: \"well\". Y va detrás del objeto: \"speaks French very well\".",
          },
          {
            type: "translate",
            direction: "es-en",
            prompt: "Traduce al inglés.",
            source: "Corre muy rápido.",
            answer: "He runs very fast.",
            altAnswers: ["She runs very fast.", "He runs really fast.", "She runs really fast.", "He runs very quickly.", "She runs very quickly."],
            explanation: "\"Fast\" es adverbio sin \"-ly\": *fastly no existe. \"Quickly\" también es correcto, pero para la velocidad al correr \"fast\" es lo más natural.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "He opened the door ___.",
        answer: "quietly",
        altAnswers: ["silently"],
        en: "Abrió la puerta [sin hacer ruido].",
        explanation: "«Sin hacer ruido» es \"quietly\" (\"quiet\" + \"-ly\").",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "She smiled ___.",
        answer: "happily",
        en: "Sonrió [con alegría].",
        explanation: "\"Happy\" termina en consonante + \"y\": \"happily\", con \"i\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Mi abuela maneja muy despacio.",
        answer: "My grandmother drives very slowly.",
        altAnswers: ["My grandma drives very slowly.", "My grandmother drives really slowly.", "My grandma drives really slowly."],
        explanation: "«Despacio» describe cómo maneja: adverbio \"slowly\". \"Drives slow\" se oye, pero \"slowly\" es la forma correcta.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Tom juega muy bien al tenis.",
        answer: "Tom plays tennis very well.",
        altAnswers: ["Tom plays very good tennis.", "Tom plays tennis really well."],
        explanation: "\"Plays tennis\" + \"well\": el adverbio va detrás del objeto. También vale \"plays very good tennis\", con el adjetivo delante del sustantivo.",
      },
      {
        type: "multiple-choice",
        question: "¿Cómo se escribe el adverbio de \"terrible\"?",
        options: ["terribly", "terriblely", "terribley", "terribally"],
        correctIndex: 0,
        explanation: "Los adjetivos en \"-le\" pierden la \"e\" y añaden \"-y\": \"terribly\", \"gently\", \"possibly\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "El tren llegó tarde otra vez.",
        answer: "The train arrived late again.",
        altAnswers: ["The train was late again.", "The train came late again.", "The train got in late again."],
        explanation: "«Tarde» es \"late\", sin \"-ly\". \"Lately\" significa «últimamente».",
      },
      {
        type: "matching",
        instructions: "Une cada palabra con su significado.",
        pairs: [
          { left: "good", right: "bueno" },
          { left: "well", right: "bien" },
          { left: "hard", right: "duro / mucho" },
          { left: "hardly", right: "apenas" },
          { left: "late", right: "tarde" },
          { left: "lately", right: "últimamente" },
        ],
        explanation: "\"Hardly\" y \"lately\" no son los adverbios de \"hard\" y \"late\": son palabras distintas.",
      },
      {
        type: "multiple-choice",
        question: "Corrige: *My brother drives very fastly.",
        options: ["My brother drives very fast.", "My brother drives very fastily.", "My brother drives very quick.", "My brother very fast drives."],
        correctIndex: 0,
        explanation: "\"Fast\" es adjetivo y adverbio: *fastly no existe.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Trabajo duro, pero gano poco.",
        answer: "I work hard, but I don't earn much.",
        altAnswers: [
          "I work hard but I don't earn much.",
          "I work hard, but I earn very little.",
          "I work hard, but I don't make much money.",
          "I work hard, but I don't earn a lot.",
          "I work hard, but I earn little.",
        ],
        explanation: "«Trabajar duro» es \"work hard\". Con \"hardly\" la frase diría «apenas trabajo».",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "She was so tired that she could ___ walk.",
        answer: "hardly",
        altAnswers: ["barely"],
        en: "Estaba tan cansada que [apenas] podía caminar.",
        explanation: "«Apenas» es \"hardly\" (o \"barely\"). Va entre \"could\" y el verbo, y no se añade \"not\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "La puerta se cierra automáticamente.",
        answer: "The door closes automatically.",
        altAnswers: ["The door shuts automatically."],
        explanation: "\"Automatic\" + \"-ally\" = \"automatically\". «Se cierra» no lleva reflexivo: \"closes\".",
      },
      {
        type: "word-order",
        prompt: "Ordena las palabras.",
        words: ["She", "explained", "everything", "very", "clearly."],
        translation: "Lo explicó todo muy claramente.",
        explanation: "Verbo + objeto + adverbio: \"explained everything very clearly\". «Claro» como adverbio es \"clearly\".",
      },
      {
        type: "multiple-choice",
        question: "¿Qué significa \"I hardly know him\"?",
        options: ["Apenas lo conozco.", "Lo conozco muy bien.", "Lo conozco desde hace mucho.", "Me cuesta conocerlo."],
        correctIndex: 0,
        explanation: "\"Hardly\" es «apenas», «casi no». No tiene nada que ver con «duro» ni con «mucho».",
      },
      {
        type: "listen-choose",
        audio: "He always gets up early and works hard.",
        question: "¿Qué has oído?",
        options: [
          "Siempre se levanta temprano y trabaja duro.",
          "Siempre se levanta tarde y apenas trabaja.",
          "Nunca se levanta temprano, pero trabaja duro.",
          "Siempre se levanta temprano, pero casi no trabaja.",
        ],
        correctIndex: 0,
        explanation: "\"Early\" (temprano) y \"hard\" (duro) son adverbios sin \"-ly\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Los niños están jugando tranquilamente en el jardín.",
        answer: "The kids are playing quietly in the garden.",
        altAnswers: [
          "The children are playing quietly in the garden.",
          "The kids are playing quietly in the yard.",
          "The children are playing quietly in the yard.",
          "The kids are playing calmly in the garden.",
          "The children are playing calmly in the garden.",
        ],
        explanation: "«Tranquilamente» es \"quietly\" (o \"calmly\"). Modo antes que lugar: \"quietly in the garden\".",
      },
      {
        type: "dictation",
        audio: "They walked slowly and talked quietly.",
        explanation: "Dos adverbios regulares: \"slowly\" y \"quietly\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Toca el piano de maravilla.",
        answer: "She plays the piano beautifully.",
        altAnswers: [
          "He plays the piano beautifully.",
          "She plays the piano wonderfully.",
          "He plays the piano wonderfully.",
          "She plays the piano really well.",
          "He plays the piano really well.",
          "She plays the piano very well.",
          "He plays the piano very well.",
        ],
        explanation: "«De maravilla», hablando de música, es \"beautifully\" (doble \"l\"). El adverbio va detrás de \"the piano\".",
      },
      {
        type: "speak",
        text: "She speaks English well, but she writes it badly.",
        tip: "\"Badly\" se dice /BAD-li/, con la \"a\" abierta, como en «padre». La \"-ly\" es corta y sin acento.",
        explanation: "\"Well\" y \"badly\": los adverbios de \"good\" y \"bad\", detrás del objeto.",
      },
    ],
  },
  // ---------------------------------------------------------------------
  {
    slug: "en-a2-adverb-position-drill-1",
    optional: true,
    level: "EN-A2",
    number: 2,
    title: "Práctica extra: el orden de la frase",
    summary: "Práctica del orden de las palabras: el verbo y su objeto no se separan (\"I like football very much\"), los adverbios de frecuencia van delante del verbo principal y el tiempo va al final o al principio.",
    duration: "10 min",
    sections: [
      {
        heading: "Recordatorio: el verbo y el objeto van juntos",
        body: [
          "En español decimos «me gusta mucho esta ciudad» o «habla muy bien italiano». En inglés, el adverbio no puede meterse entre el verbo y su objeto: \"I like this city very much\", \"She speaks Italian very well\". *I like very much this city es el error más típico de la unidad.",
          "Con \"like\" y \"love\", \"really\" delante del verbo es muy natural y evita el problema: \"I really like your house\".",
        ],
        examples: [
          { es: "I like this city very much.", en: "Me gusta mucho esta ciudad." },
          { es: "I really like your house.", en: "Me gusta mucho tu casa." },
          { es: "She speaks Italian very well.", en: "Habla muy bien italiano." },
          { es: "He plays the piano very well.", en: "Toca muy bien el piano." },
          { es: "Thank you very much for your help.", en: "Muchas gracias por tu ayuda." },
        ],
        checkpoint: [
          {
            type: "word-order",
            prompt: "Ordena las palabras.",
            words: ["I", "like", "this", "city", "very", "much"],
            translation: "Me gusta mucho esta ciudad.",
            explanation: "\"Like\" + \"this city\" juntos, y \"very much\" al final.",
          },
          {
            type: "multiple-choice",
            question: "Corrige: *She plays very well the piano.",
            options: ["She plays the piano very well.", "She very well plays the piano.", "She plays the piano very good.", "She plays very good the piano."],
            correctIndex: 0,
            explanation: "Verbo + objeto + adverbio: \"plays the piano very well\". Y el adverbio es \"well\", no \"good\".",
          },
        ],
      },
      {
        heading: "Recordatorio: frecuencia, lugar y tiempo",
        body: [
          "Los adverbios de frecuencia (\"always\", \"usually\", \"often\", \"sometimes\", \"never\") van delante del verbo principal (\"I always drink tea\"), detrás de \"be\" (\"I'm never at home\") y entre el auxiliar y el verbo (\"I can never find my keys\", \"I don't usually go out\").",
          "Al final de la frase, el orden es cómo → dónde → cuándo: \"I study English at home every night\". El tiempo también puede ir al principio: \"Every night I study English at home\".",
        ],
        examples: [
          { es: "I always drink tea in the afternoon.", en: "Siempre tomo té por la tarde." },
          { es: "I'm never at home on Saturdays.", en: "Nunca estoy en casa los sábados." },
          { es: "I can never find my keys.", en: "Nunca encuentro mis llaves." },
          { es: "We went to the movies yesterday.", en: "Fuimos al cine ayer." },
          { es: "I study English at home every night.", en: "Estudio inglés en casa todas las noches." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "¿Cómo se dice «Nunca estoy en casa los sábados»?",
            options: ["I'm never at home on Saturdays.", "I never am at home on Saturdays.", "I'm at home never on Saturdays.", "Never I'm at home on Saturdays."],
            correctIndex: 0,
            explanation: "Con \"be\", el adverbio de frecuencia va detrás: \"I'm never at home\".",
          },
          {
            type: "word-order",
            prompt: "Ordena las palabras.",
            words: ["We", "usually", "have", "lunch", "at", "one"],
            translation: "Normalmente almorzamos a la una.",
            explanation: "\"Usually\" delante del verbo principal (\"have\"), y la hora al final.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "word-order",
        prompt: "Ordena las palabras.",
        words: ["She", "speaks", "Italian", "very", "well"],
        translation: "Habla muy bien italiano.",
        explanation: "\"Speaks Italian\" no se separa; \"very well\" va detrás.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Me gusta mucho tu casa.",
        answer: "I like your house very much.",
        altAnswers: ["I really like your house.", "I like your house a lot.", "I love your house."],
        explanation: "\"Very much\" o \"a lot\" al final, o \"really\" delante del verbo. Nunca *I like very much your house.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Siempre tomo té por la tarde.",
        answer: "I always drink tea in the afternoon.",
        altAnswers: ["I always have tea in the afternoon.", "In the afternoon I always drink tea.", "In the afternoon I always have tea."],
        explanation: "\"Always\" delante del verbo principal: \"always drink\". *I drink always tea separa el verbo del objeto.",
      },
      {
        type: "word-order",
        prompt: "Ordena las palabras.",
        words: ["He", "is", "always", "tired", "in", "the", "morning"],
        altOrders: [["In", "the", "morning", "he", "is", "always", "tired"]],
        translation: "Siempre está cansado por la mañana.",
        explanation: "Con \"be\", \"always\" va detrás: \"is always tired\". El tiempo puede ir al final o al principio.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Fuimos al cine ayer.",
        answer: "We went to the movies yesterday.",
        altAnswers: ["Yesterday we went to the movies.", "We went to the cinema yesterday.", "Yesterday we went to the cinema.", "We went to the movie theater yesterday."],
        explanation: "Lugar (\"to the movies\") antes que tiempo (\"yesterday\"). «Ir al cine» es \"go to the movies\" en Estados Unidos.",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "We ___ go out on Fridays.",
        answer: "often",
        altAnswers: ["usually", "frequently"],
        en: "[A menudo] salimos los viernes.",
        explanation: "«A menudo» es \"often\", y va delante del verbo principal: \"We often go out\".",
      },
      {
        type: "word-order",
        prompt: "Ordena las palabras.",
        words: ["I", "can", "never", "find", "my", "keys"],
        translation: "Nunca encuentro mis llaves.",
        explanation: "Con un auxiliar (\"can\"), el adverbio va en medio: \"can never find\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Mi jefe habla español bastante bien.",
        answer: "My boss speaks Spanish pretty well.",
        altAnswers: ["My boss speaks Spanish quite well.", "My boss speaks Spanish fairly well.", "My boss speaks pretty good Spanish.", "My boss speaks quite good Spanish."],
        explanation: "\"Speaks Spanish\" + \"pretty well\": el adverbio detrás del objeto. «Bastante bien» es \"pretty well\" o \"quite well\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Estudio inglés en casa todas las noches.",
        answer: "I study English at home every night.",
        altAnswers: ["Every night I study English at home.", "I study English at home every evening.", "Every evening I study English at home."],
        explanation: "Objeto (\"English\"), lugar (\"at home\") y tiempo (\"every night\"), en ese orden. El tiempo también puede abrir la frase.",
      },
      {
        type: "multiple-choice",
        question: "¿Qué frase tiene un error?",
        options: ["I don't like very much coffee.", "I don't like coffee very much.", "I don't really like coffee.", "I don't like coffee at all."],
        correctIndex: 0,
        explanation: "\"Very much\" no puede ir entre \"like\" y \"coffee\". Las otras tres son correctas.",
      },
      {
        type: "multiple-choice",
        question: "¿Cómo se dice «A veces como en la oficina»?",
        options: ["I sometimes eat at the office.", "I eat sometimes at the office.", "I eat at sometimes the office.", "Sometimes eat I at the office."],
        correctIndex: 0,
        explanation: "\"Sometimes\" delante del verbo principal. También puede ir al principio: \"Sometimes I eat at the office\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Diego nunca llega tarde.",
        answer: "Diego is never late.",
        altAnswers: ["Diego never arrives late.", "Diego never comes late.", "Diego's never late."],
        explanation: "«Llegar tarde» es \"be late\": con \"be\", \"never\" va detrás. Con \"arrive\", delante: \"never arrives late\".",
      },
      {
        type: "word-order",
        prompt: "Ordena las palabras.",
        words: ["My", "mother", "cooks", "dinner", "every", "evening"],
        altOrders: [["Every", "evening", "my", "mother", "cooks", "dinner"]],
        translation: "Mi madre prepara la cena todas las tardes.",
        explanation: "\"Cooks dinner\" juntos y el tiempo al final (o al principio).",
      },
      {
        type: "listen-choose",
        audio: "She always does her homework carefully.",
        question: "¿Qué has oído?",
        options: [
          "Siempre hace la tarea con cuidado.",
          "Nunca hace la tarea con cuidado.",
          "A veces hace la tarea rápido.",
          "Siempre hace la tarea tarde.",
        ],
        correctIndex: 0,
        explanation: "\"Always\" delante de \"does\", y \"carefully\" al final, detrás de \"her homework\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Ella entiende muy bien el problema.",
        answer: "She understands the problem very well.",
        altAnswers: ["She understands the problem really well."],
        explanation: "Nunca *She understands very well the problem: el objeto va pegado al verbo y el adverbio detrás.",
      },
      {
        type: "dictation",
        audio: "We often play football in the park on Sundays.",
        explanation: "\"Often\" delante del verbo, luego objeto (\"football\"), lugar (\"in the park\") y tiempo (\"on Sundays\").",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Normalmente no veo la tele por la noche.",
        answer: "I don't usually watch TV at night.",
        altAnswers: [
          "I usually don't watch TV at night.",
          "I don't normally watch TV at night.",
          "I normally don't watch TV at night.",
          "I don't usually watch TV in the evening.",
          "I don't usually watch television at night.",
          "At night I don't usually watch TV.",
        ],
        explanation: "\"Usually\" entre \"don't\" y el verbo; \"I usually don't\" también se oye mucho. «Ver la tele» es \"watch TV\", sin \"the\".",
      },
      {
        type: "speak",
        text: "Thank you very much for your help.",
        tip: "La \"th\" de \"thank\" es suave, con la lengua entre los dientes. \"Very much\" se dice seguido, sin pausa.",
        explanation: "\"Thank you very much\": \"very much\" siempre detrás de \"thank you\", nunca *thank very much you.",
      },
    ],
  },
  // ---------------------------------------------------------------------
  {
    slug: "en-a2-ed-ing-drill-1",
    optional: true,
    level: "EN-A2",
    number: 3,
    title: "Práctica extra: bored o boring",
    summary: "Práctica de los adjetivos en \"-ed\" (cómo te sientes: \"bored\", \"tired\", \"interested\") y en \"-ing\" (lo que lo provoca: \"boring\", \"tiring\", \"interesting\"), y de los falsos amigos \"embarrassed\" y \"excited\".",
    duration: "10 min",
    sections: [
      {
        heading: "Recordatorio: -ed para la persona, -ing para la causa",
        body: [
          "La forma en \"-ed\" dice cómo se siente alguien: \"I was bored\" (me aburrí), \"She's tired\" (está cansada). La forma en \"-ing\" describe lo que provoca ese sentimiento: \"The meeting was boring\" (la reunión fue aburrida), \"The job is tiring\" (el trabajo es cansado).",
          "El error clásico: *I'm boring para decir «estoy aburrido». Eso significa «soy una persona aburrida». Con «estoy» casi siempre va \"-ed\"; con «es» (la cosa), \"-ing\".",
        ],
        examples: [
          { es: "I was really bored at the meeting.", en: "Me aburrí mucho en la reunión." },
          { es: "The meeting was really boring.", en: "La reunión fue muy aburrida." },
          { es: "Are you interested in the job?", en: "¿Te interesa el trabajo?" },
          { es: "The job sounds interesting.", en: "El trabajo suena interesante." },
          { es: "The children were excited about the party.", en: "Los niños estaban ilusionados con la fiesta." },
          { es: "It was an exciting game.", en: "Fue un partido emocionante." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "¿Cómo se dice «Estoy aburrido»?",
            options: ["I'm bored.", "I'm boring.", "I'm bore.", "I have bored."],
            correctIndex: 0,
            explanation: "Cómo te sientes: \"-ed\". \"I'm boring\" es «soy aburrido» (una persona sosa), y los sentimientos van con \"be\", no con \"have\".",
          },
          {
            type: "fill-blank",
            prompt: "Escribe en inglés las palabras en negrita.",
            sentence: "The lesson was really ___.",
            answer: "interesting",
            en: "La clase fue muy [interesante].",
            explanation: "La clase es lo que provoca el interés, así que va \"-ing\": \"interesting\".",
          },
        ],
      },
      {
        heading: "Recordatorio: falsos amigos y preposiciones",
        body: [
          "\"Embarrassed\" es «avergonzado», no «embarazada» (eso es \"pregnant\"). \"Embarrassing\" es «vergonzoso». \"Excited\" es «ilusionado» o «emocionado», y \"exciting\", «emocionante».",
          "Preposiciones fijas: \"interested in\", \"worried about\", \"excited about\", \"tired of\" (harto de), \"bored with\", \"disappointed with\".",
        ],
        examples: [
          { es: "I was so embarrassed when I fell.", en: "Me dio mucha vergüenza cuando me caí." },
          { es: "My aunt is pregnant.", en: "Mi tía está embarazada." },
          { es: "We're excited about the weekend.", en: "Estamos ilusionados con el fin de semana." },
          { es: "I'm tired of waiting.", en: "Estoy harto de esperar." },
          { es: "She was disappointed with her grade.", en: "Se decepcionó con su nota." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "Te equivocas de nombre delante de todos. ¿Qué dices?",
            options: ["I'm so embarrassed!", "I'm so pregnant!", "I'm so embarrassing!", "I'm so excited!"],
            correctIndex: 0,
            explanation: "«Qué vergüenza» es \"I'm so embarrassed\". \"Embarrassing\" sería la situación; \"pregnant\" es «embarazada».",
          },
          {
            type: "translate",
            direction: "es-en",
            prompt: "Traduce al inglés.",
            source: "Estoy harto de este trabajo.",
            answer: "I'm tired of this job.",
            altAnswers: ["I'm sick of this job.", "I'm fed up with this job.", "I'm sick and tired of this job."],
            explanation: "«Estar harto de» es \"be tired of\" (o \"sick of\", \"fed up with\"). Ojo: \"tired of\", no *tired from.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Estaba muy aburrida en la fiesta.",
        answer: "I was very bored at the party.",
        altAnswers: ["I was really bored at the party.", "I was so bored at the party.", "She was very bored at the party.", "She was really bored at the party.", "She was so bored at the party."],
        explanation: "Cómo se sentía la persona: \"bored\". Con \"boring\" dirías que ella era una persona aburrida.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "La fiesta fue muy aburrida.",
        answer: "The party was very boring.",
        altAnswers: ["The party was really boring.", "The party was so boring."],
        explanation: "La fiesta es la causa del aburrimiento: \"boring\".",
      },
      {
        type: "multiple-choice",
        question: "¿Qué frase tiene un error?",
        options: ["I'm very interesting in music.", "I'm very interested in music.", "Music is very interesting.", "This song is interesting."],
        correctIndex: 0,
        explanation: "La persona que siente interés es \"interested\". \"Interesting\" es para la cosa que interesa (la música, la canción).",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "My job is very ___, so I sleep well.",
        answer: "tiring",
        altAnswers: ["exhausting"],
        en: "Mi trabajo es muy [cansado], así que duermo bien.",
        explanation: "El trabajo es lo que cansa: \"tiring\". «Estoy cansado» sería \"I'm tired\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Los niños están muy emocionados con el viaje.",
        answer: "The children are very excited about the trip.",
        altAnswers: ["The kids are very excited about the trip.", "The children are really excited about the trip.", "The kids are really excited about the trip.", "The children are so excited about the trip.", "The children are very excited for the trip.", "The kids are very excited for the trip."],
        explanation: "«Emocionado» o «ilusionado» es \"excited\" (\"-ed\", porque es cómo se sienten) y va con \"about\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Fue un partido muy emocionante.",
        answer: "It was a very exciting game.",
        altAnswers: ["It was a really exciting game.", "It was a very exciting match.", "It was a really exciting match."],
        explanation: "El partido es lo que emociona: \"exciting\". En Estados Unidos «partido» es \"game\"; en el Reino Unido, \"match\".",
      },
      {
        type: "multiple-choice",
        question: "¿Cómo se dice «Mi hermana está embarazada»?",
        options: ["My sister is pregnant.", "My sister is embarrassed.", "My sister is embarrassing.", "My sister is excited."],
        correctIndex: 0,
        explanation: "«Embarazada» es \"pregnant\". \"Embarrassed\" es «avergonzada»: un falso amigo peligroso.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Pasé mucha vergüenza en la entrevista.",
        answer: "I was very embarrassed at the interview.",
        altAnswers: ["I was really embarrassed at the interview.", "I was so embarrassed at the interview.", "I was very embarrassed in the interview.", "I was really embarrassed in the interview.", "I was so embarrassed in the interview.", "I was very embarrassed during the interview.", "I was really embarrassed during the interview.", "I was so embarrassed during the interview.", "I felt very embarrassed at the interview.", "I felt really embarrassed at the interview.", "I felt so embarrassed at the interview."],
        explanation: "«Pasar vergüenza» es \"be embarrassed\" (\"-ed\", cómo te sentiste). Recuerda la ortografía: doble \"r\" y doble \"s\".",
      },
      {
        type: "matching",
        instructions: "Une cada adjetivo con su significado.",
        pairs: [
          { left: "bored", right: "que se aburre" },
          { left: "boring", right: "que aburre" },
          { left: "embarrassed", right: "avergonzado" },
          { left: "pregnant", right: "embarazada" },
          { left: "excited", right: "ilusionado" },
          { left: "disappointed", right: "decepcionado" },
        ],
        explanation: "\"-ed\" para la persona que siente, \"-ing\" para la causa. \"Embarrassed\" no es «embarazada».",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "I'm ___ about my daughter. She isn't home yet.",
        answer: "worried",
        altAnswers: ["concerned"],
        en: "Estoy [preocupada] por mi hija. Todavía no está en casa.",
        explanation: "«Preocupado por» es \"worried about\": \"-ed\" porque es cómo te sientes, y la preposición es \"about\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "¿Te interesa el fútbol?",
        answer: "Are you interested in football?",
        altAnswers: ["Are you interested in soccer?"],
        explanation: "«Me interesa algo» cambia de estructura: \"I'm interested in something\". La persona es el sujeto y la preposición es \"in\".",
      },
      {
        type: "multiple-choice",
        question: "Un amigo escribe *I'm very exciting about the concert. ¿Cuál es la frase correcta?",
        options: ["I'm very excited about the concert.", "I'm very exciting about the concert.", "I'm very excite about the concert.", "I'm very excited of the concert."],
        correctIndex: 0,
        explanation: "Él siente la ilusión: \"excited\". \"Exciting\" sería el concierto. Y la preposición es \"about\", no \"of\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Los resultados fueron sorprendentes.",
        answer: "The results were surprising.",
        explanation: "Los resultados provocan la sorpresa: \"surprising\". \"Surprised\" sería la gente que se sorprendió.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Estoy harta de esperar el autobús.",
        answer: "I'm tired of waiting for the bus.",
        altAnswers: ["I'm sick of waiting for the bus.", "I'm fed up with waiting for the bus.", "I'm sick and tired of waiting for the bus."],
        explanation: "\"Tired of\" + verbo en \"-ing\": \"tired of waiting\". Y «esperar algo» es \"wait for something\".",
      },
      {
        type: "listen-choose",
        audio: "The movie was so boring that I fell asleep.",
        question: "¿Qué has oído?",
        options: [
          "La película era tan aburrida que me dormí.",
          "Estaba tan aburrido que me fui del cine.",
          "La película era tan emocionante que no dormí.",
          "Estaba tan cansado que me dormí en el cine.",
        ],
        correctIndex: 0,
        explanation: "\"The movie was so boring\": la película (la causa) es \"boring\". \"Fell asleep\" es «me dormí».",
      },
      {
        type: "dictation",
        audio: "I'm not interested in politics.",
        explanation: "\"Interested in\": la persona que siente interés lleva \"-ed\" y la preposición es \"in\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Estamos decepcionados con el hotel.",
        answer: "We're disappointed with the hotel.",
        altAnswers: ["We're disappointed in the hotel.", "We're disappointed by the hotel."],
        explanation: "Cómo nos sentimos: \"disappointed\" (sin plural), normalmente con \"with\".",
      },
      {
        type: "speak",
        text: "I'm so excited about the weekend!",
        tip: "\"Excited\" se dice /ik-SAI-tid/, con el acento en la segunda sílaba. La \"-ed\" suena /id/ porque va detrás de una \"t\".",
        explanation: "\"Excited about\": «ilusionado con». Sin \"-ing\": la persona siente la ilusión.",
      },
    ],
  },
  // ---------------------------------------------------------------------
  {
    slug: "en-a2-too-enough-drill-1",
    optional: true,
    level: "EN-A2",
    number: 4,
    title: "Práctica extra: too y enough con adjetivos",
    summary: "Práctica de \"too\" + adjetivo (\"too expensive\"), adjetivo + \"enough\" (\"big enough\", nunca *enough big), \"too… to\" y \"enough to\", y la diferencia entre \"too\" y \"very\".",
    duration: "10 min",
    sections: [
      {
        heading: "Recordatorio: too + adjetivo, adjetivo + enough",
        body: [
          "\"Too\" + adjetivo es «demasiado» y señala un problema: \"too expensive\", \"too hot\". Nunca *too much + adjetivo: \"too much\" va solo con sustantivos (\"too much sugar\"). \"Very\" es solo «muy», sin problema: \"very expensive, but I'll buy it\".",
          "\"Enough\" va DETRÁS del adjetivo (\"big enough\", \"warm enough\") pero DELANTE del sustantivo (\"enough money\", \"enough chairs\"). *Enough big es el error más común.",
        ],
        examples: [
          { es: "This bag is too heavy for me.", en: "Esta bolsa es demasiado pesada para mí." },
          { es: "The soup is very hot, but it's delicious.", en: "La sopa está muy caliente, pero está deliciosa." },
          { es: "The soup is too hot. I can't eat it.", en: "La sopa está demasiado caliente. No puedo comerla." },
          { es: "The bed isn't long enough.", en: "La cama no es lo bastante larga." },
          { es: "Do we have enough chairs?", en: "¿Tenemos suficientes sillas?" },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "Corrige: *This bag is too much heavy.",
            options: ["This bag is too heavy.", "This bag is very much heavy.", "This bag is enough heavy.", "This bag is heavy too much."],
            correctIndex: 0,
            explanation: "Con un adjetivo, solo \"too\": \"too heavy\". \"Too much\" es para sustantivos incontables.",
          },
          {
            type: "fill-blank",
            prompt: "Escribe en inglés las palabras en negrita.",
            sentence: "The coffee isn't ___.",
            answer: "strong enough",
            en: "El café no está [lo bastante fuerte].",
            explanation: "Adjetivo + \"enough\": \"strong enough\", nunca *enough strong.",
          },
        ],
      },
      {
        heading: "Recordatorio: too… to, enough to, for + persona",
        body: [
          "Para decir qué no se puede hacer (o qué sí) se añade \"to\" + verbo: \"too tired to drive\" (demasiado cansado para manejar), \"old enough to vote\" (con edad para votar). El español dice «para manejar», pero el inglés dice \"to drive\", nunca *for drive.",
          "A quién afecta se dice con \"for\" + persona: \"This coat is too big for me\" (este abrigo me queda demasiado grande).",
        ],
        examples: [
          { es: "It's too cold to go to the beach.", en: "Hace demasiado frío para ir a la playa." },
          { es: "I'm too busy to talk right now.", en: "Estoy demasiado ocupado para hablar ahora mismo." },
          { es: "He's old enough to travel alone.", en: "Tiene edad suficiente para viajar solo." },
          { es: "The box is light enough to carry.", en: "La caja es lo bastante ligera para llevarla." },
          { es: "This bike is too small for my brother.", en: "Esta bici es demasiado pequeña para mi hermano." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "es-en",
            prompt: "Traduce al inglés.",
            source: "Estoy demasiado ocupado para ir al gimnasio.",
            answer: "I'm too busy to go to the gym.",
            explanation: "\"Too busy\" + \"to\" + verbo: \"too busy to go\", no *for go.",
          },
          {
            type: "multiple-choice",
            question: "¿Cómo se dice «Esta camiseta me queda demasiado pequeña»?",
            options: ["This T-shirt is too small for me.", "This T-shirt is too small to me.", "This T-shirt is too much small for me.", "This T-shirt is small enough for me."],
            correctIndex: 0,
            explanation: "«Me queda pequeña» es \"is too small for me\": \"too\" + adjetivo + \"for\" + persona.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Este carro es demasiado caro para nosotros.",
        answer: "This car is too expensive for us.",
        explanation: "\"Too expensive\" (demasiado caro) y \"for us\" (para nosotros).",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "The room is ___ for six people.",
        answer: "big enough",
        altAnswers: ["large enough"],
        en: "La habitación es [lo bastante grande] para seis personas.",
        explanation: "Adjetivo + \"enough\": \"big enough\". *Enough big es un error.",
      },
      {
        type: "multiple-choice",
        question: "¿Qué frase tiene un error?",
        options: ["She isn't enough old to drive.", "She isn't old enough to drive.", "She's too young to drive.", "She's old enough to drive."],
        correctIndex: 0,
        explanation: "\"Enough\" va detrás del adjetivo: \"old enough\". Las otras tres son correctas.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Hace demasiado calor para correr.",
        answer: "It's too hot to run.",
        altAnswers: ["It's too hot to go running.", "It's too hot for running."],
        explanation: "«Hace calor» es \"it's hot\", y «demasiado… para» + verbo es \"too…\" + \"to\" + verbo.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "No tenemos suficientes sillas.",
        answer: "We don't have enough chairs.",
        altAnswers: ["We haven't got enough chairs."],
        explanation: "Con un sustantivo, \"enough\" va delante: \"enough chairs\".",
      },
      {
        type: "multiple-choice",
        question: "Vas al restaurante aunque es caro. ¿Qué dices?",
        options: ["It's very expensive, but the food is great.", "It's too expensive, but the food is great.", "It's too much expensive, but the food is great.", "It's expensive enough, but the food is great."],
        correctIndex: 0,
        explanation: "Si vas igual, es \"very expensive\". \"Too expensive\" significa que es un problema y no vas.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "La música está demasiado alta.",
        answer: "The music is too loud.",
        explanation: "«Alta» hablando de volumen es \"loud\", no \"high\". \"Too\" + adjetivo: \"too loud\".",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "You're ___ to understand.",
        answer: "old enough",
        en: "Eres [lo bastante mayor] para entenderlo.",
        explanation: "«Lo bastante mayor» es \"old enough\": adjetivo + \"enough\" + \"to\" + verbo.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Esta mochila es demasiado pequeña para mi portátil.",
        answer: "This backpack is too small for my laptop.",
        altAnswers: ["This bag is too small for my laptop.", "This rucksack is too small for my laptop."],
        explanation: "\"Too small\" + \"for\" + la cosa o persona afectada: \"too small for my laptop\".",
      },
      {
        type: "word-order",
        prompt: "Ordena las palabras.",
        words: ["I'm", "too", "tired", "to", "study", "tonight"],
        altOrders: [["Tonight", "I'm", "too", "tired", "to", "study"]],
        translation: "Estoy demasiado cansado para estudiar esta noche.",
        explanation: "\"Too tired to study\": \"too\" + adjetivo + \"to\" + verbo. El tiempo va al final o al principio.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "No tiene edad para ver esa película.",
        answer: "He isn't old enough to watch that movie.",
        altAnswers: ["She isn't old enough to watch that movie.", "He isn't old enough to see that movie.", "She isn't old enough to see that movie.", "He isn't old enough to watch that film.", "She isn't old enough to watch that film.", "He is not old enough to watch that movie.", "He's not old enough to watch that movie.", "She's not old enough to watch that movie."],
        explanation: "«Tener edad para» es \"be old enough to\": la edad va con \"be\", y \"enough\" detrás de \"old\".",
      },
      {
        type: "multiple-choice",
        question: "Un compañero escribe *I don't have enough money for buy it. ¿Cuál es la frase correcta?",
        options: ["I don't have enough money to buy it.", "I don't have money enough to buy it.", "I don't have enough money for buy it.", "I don't have too money to buy it."],
        correctIndex: 0,
        explanation: "\"Enough\" delante del sustantivo (\"enough money\") y \"to\" + verbo para el propósito: \"to buy it\", no *for buy.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "El agua no está lo bastante caliente para una ducha.",
        answer: "The water isn't hot enough for a shower.",
        altAnswers: ["The water isn't warm enough for a shower.", "The water is not hot enough for a shower.", "The water is not warm enough for a shower."],
        explanation: "\"Hot enough\" (adjetivo + \"enough\") y \"for\" + sustantivo: \"for a shower\".",
      },
      {
        type: "listen-choose",
        audio: "These shoes are too small. Do you have a bigger size?",
        question: "¿Qué has oído?",
        options: [
          "Estos zapatos son demasiado pequeños. ¿Tiene una talla más grande?",
          "Estos zapatos son muy pequeños, pero me los llevo.",
          "Estos zapatos son lo bastante grandes. Me los llevo.",
          "Estos zapatos son demasiado grandes. ¿Tiene una talla más pequeña?",
        ],
        correctIndex: 0,
        explanation: "\"Too small\" es «demasiado pequeños» y \"a bigger size\", «una talla más grande».",
      },
      {
        type: "dictation",
        audio: "It's too late to go to the supermarket.",
        explanation: "\"Too late to go\": \"too\" + adjetivo + \"to\" + verbo. Fíjate en que \"too\" y \"to\" suenan igual pero se escriben distinto.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Es demasiado pronto para saberlo.",
        answer: "It's too early to know.",
        altAnswers: ["It's too soon to know.", "It's too early to tell.", "It's too soon to tell.", "It's too early to say.", "It's too soon to say."],
        explanation: "«Demasiado pronto» es \"too early\" o \"too soon\", y «para saberlo» es \"to know\" (o \"to tell\", muy natural aquí).",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "¿Tienes tiempo suficiente?",
        answer: "Do you have enough time?",
        altAnswers: ["Have you got enough time?"],
        explanation: "Con un sustantivo, \"enough\" va delante: \"enough time\", aunque en español digamos «tiempo suficiente».",
      },
      {
        type: "speak",
        text: "This jacket is warm enough for the winter.",
        tip: "\"Enough\" se dice /i-NAF/: la \"gh\" final suena como una \"f\". El acento va en la segunda sílaba.",
        explanation: "\"Warm enough\": adjetivo + \"enough\", y \"for\" + sustantivo para decir para qué sirve.",
      },
    ],
  },
];
