// Synced from cheneygross-afk/lengo:src/lib/lessons/en-a1-u5-extra.ts by scripts/sync-content.mjs -- edit it there, not here.
import type { Lesson } from "./types";

// Extra practice (optional) lessons for EN-A1 unit u5.

export const EN_A1_U5_EXTRA: Lesson[] = [
  // ---------------------------------------------------------------------
  // Extra 1. His, her, its, their
  // ---------------------------------------------------------------------
  {
    slug: "en-a1-his-her-their-drill-1",
    level: "EN-A1",
    optional: true,
    number: 1,
    title: "Práctica: his, her, its, their",
    summary: "Traduce «su» y «sus» según quién es el dueño: \"his\", \"her\", \"its\", \"their\" o \"your\". Y no confundas \"its\" con \"it's\".",
    duration: "10 min",
    sections: [
      {
        heading: "Recordatorio: «su» depende del dueño",
        body: [
          "En español «su» sirve para todo. En inglés depende de quién es el dueño: de él, \"his\"; de ella, \"her\"; de una cosa o un animal, \"its\"; de ellos o ellas, \"their\"; de usted o ustedes, \"your\".",
          "Lo que importa es el dueño, no la cosa: «Ana y su hermano» es \"Ana and her brother\" (el hermano es de Ana), nunca *Ana and his brother. Y el posesivo nunca lleva plural: \"their books\", no *theirs books.",
        ],
        examples: [
          { es: "Ana and her brother", en: "Ana y su hermano" },
          { es: "Tom and his sister", en: "Tom y su hermana" },
          { es: "The cat is eating its food.", en: "El gato está comiendo su comida." },
          { es: "My neighbors and their children", en: "Mis vecinos y sus hijos" },
          { es: "Mr. Lopez, is this your phone?", en: "Señor Lopez, ¿este es su teléfono?" },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "es-en",
            prompt: "Traduce al inglés.",
            source: "Emma está con su padre.",
            answer: "Emma is with her father.",
            altAnswers: ["Emma is with her dad."],
            explanation: "El padre es de Emma (una mujer): \"her father\". El género de \"father\" no importa.",
          },
          {
            type: "multiple-choice",
            question: "¿Cómo se dice «Carlos y su hermana»?",
            options: ["Carlos and his sister", "Carlos and her sister", "Carlos and their sister", "Carlos and its sister"],
            correctIndex: 0,
            explanation: "La hermana es de Carlos (un hombre): \"his sister\". Se mira al dueño, no a la hermana.",
          },
        ],
      },
      {
        heading: "Its o it's, their o they're",
        body: [
          "\"Its\" (sin apóstrofo) es «su» de una cosa o un animal: \"The city and its parks\". \"It's\" (con apóstrofo) es \"it is\": \"It's cold\".",
          "Lo mismo con \"their\" (su, de ellos), \"they're\" (\"they are\") y \"there\" (allí): suenan igual, pero se escriben distinto.",
        ],
        examples: [
          { es: "The company has its office in Lima.", en: "La empresa tiene su oficina en Lima." },
          { es: "It's a big city.", en: "Es una ciudad grande." },
          { es: "Their house is near the park.", en: "Su casa (de ellos) está cerca del parque." },
          { es: "They're at school.", en: "Están en el colegio." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "¿Cuál es correcta?",
            options: ["The hotel has its own beach.", "The hotel has it's own beach.", "The hotel has his own beach.", "The hotel has their own beach."],
            correctIndex: 0,
            explanation: "El dueño es una cosa (el hotel): \"its\", sin apóstrofo. \"It's\" significa \"it is\".",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Ana y su hermano trabajan en un banco.",
        answer: "Ana and her brother work in a bank.",
        altAnswers: ["Ana and her brother work at a bank."],
        explanation: "El hermano es de Ana: \"her brother\". Y con dos personas el verbo no lleva \"-s\": \"work\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Tom está con su madre.",
        answer: "Tom is with his mother.",
        altAnswers: ["Tom is with his mom."],
        explanation: "La madre es de Tom: \"his mother\", aunque la madre sea mujer.",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "The children love ___ teacher.",
        answer: "their",
        en: "Los niños adoran a [su] maestra.",
        explanation: "El dueño son \"the children\" (plural): \"their teacher\".",
      },
      {
        type: "multiple-choice",
        question: "¿Cuál es correcta?",
        options: ["Their books are on the table.", "Theirs books are on the table.", "Their's books are on the table.", "There books are on the table."],
        correctIndex: 0,
        explanation: "Los posesivos no tienen plural: \"their books\". \"There\" significa «allí».",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "The dog is sleeping in ___ bed.",
        answer: "its",
        altAnswers: ["his", "her"],
        en: "El perro está durmiendo en [su] cama.",
        explanation: "Para un animal se usa \"its\". Con las mascotas mucha gente dice también \"his\" o \"her\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Señora Brown, ¿este es su bolso?",
        answer: "Mrs. Brown, is this your bag?",
        altAnswers: ["Mrs. Brown, is this your purse?", "Ms. Brown, is this your bag?", "Ms. Brown, is this your purse?", "Mrs. Brown, is this your handbag?"],
        explanation: "Cuando «su» es de usted, en inglés es \"your\". El inglés no tiene una forma especial de respeto.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Mis vecinos y sus hijos están en el jardín.",
        answer: "My neighbors and their children are in the garden.",
        altAnswers: [
          "My neighbors and their kids are in the garden.",
          "My neighbors and their children are in the yard.",
          "My neighbors and their kids are in the yard.",
        ],
        explanation: "«Sus» de \"my neighbors\" (ellos): \"their children\".",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "Sofia is talking to ___ father.",
        answer: "her",
        en: "Sofia está hablando con [su] padre.",
        explanation: "El padre es de Sofia: \"her father\". *Sofia is talking to his father significaría el padre de otro hombre.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Carlos vive con su abuela.",
        answer: "Carlos lives with his grandmother.",
        altAnswers: ["Carlos lives with his grandma."],
        explanation: "La abuela es de Carlos: \"his grandmother\". Y \"lives\" con \"-s\" de tercera persona.",
      },
      {
        type: "matching",
        instructions: "Une cada posesivo con su significado.",
        pairs: [
          { left: "his", right: "su (de él)" },
          { left: "her", right: "su (de ella)" },
          { left: "its", right: "su (de una cosa o un animal)" },
          { left: "their", right: "su (de ellos o ellas)" },
          { left: "your", right: "su (de usted)" },
        ],
        explanation: "Un solo «su» en español, cinco posibilidades en inglés: todo depende del dueño.",
      },
      {
        type: "word-order",
        prompt: "Ordena las palabras.",
        words: ["Diego", "and", "his", "wife", "love", "their", "new", "house."],
        translation: "Diego y su esposa adoran su casa nueva.",
        explanation: "La esposa es de Diego (\"his wife\"); la casa es de los dos (\"their house\").",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Su carro es azul. (el carro de ella)",
        answer: "Her car is blue.",
        explanation: "El carro es de ella: \"her car\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Sus hijos son muy simpáticos. (los hijos de él)",
        answer: "His children are very nice.",
        altAnswers: [
          "His kids are very nice.",
          "His sons are very nice.",
          "His children are very friendly.",
          "His kids are very friendly.",
          "His sons are very friendly.",
        ],
        explanation: "Los hijos son de él: \"his children\". \"His\" no cambia aunque \"children\" sea plural. Y «simpático» no es *sympathetic: es \"nice\" o \"friendly\".",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "I like this city. ___ parks are beautiful.",
        answer: "Its",
        en: "Me gusta esta ciudad. [Sus] parques son preciosos.",
        explanation: "El dueño es la ciudad (una cosa): \"its\", sin apóstrofo. \"It's\" sería \"it is\".",
      },
      {
        type: "listen-choose",
        audio: "His sister is a doctor.",
        question: "¿De quién es la hermana?",
        options: ["De un hombre.", "De una mujer.", "De varias personas.", "De la persona que habla."],
        correctIndex: 0,
        explanation: "\"His\" indica que el dueño es un hombre: la hermana de él.",
      },
      {
        type: "dictation",
        audio: "Their daughter is in her room.",
        explanation: "\"Their\" (de ellos) y \"her\" (de ella, la hija). \"Their\" suena igual que \"there\" y \"they're\".",
      },
    ],
  },

  // ---------------------------------------------------------------------
  // Extra 2. Genitive 's
  // ---------------------------------------------------------------------
  {
    slug: "en-a1-genitive-s-drill-1",
    level: "EN-A1",
    optional: true,
    number: 2,
    title: "Práctica: el genitivo 's",
    summary: "De «el carro de mi padre» a \"my father's car\": practica el 's con personas, con plurales como \"my parents'\" y con \"children's\".",
    duration: "10 min",
    sections: [
      {
        heading: "Recordatorio: dueño + 's + cosa",
        body: [
          "Para decir de quién es algo, el inglés pone primero al dueño con \"'s\" y después la cosa: «el carro de mi padre» es \"my father's car\". La traducción palabra por palabra *the car of my father suena muy rara.",
          "El artículo «el» desaparece: \"Ana's phone\", nunca *the Ana's phone. Y \"my\" va con el dueño: \"my sister's room\".",
        ],
        examples: [
          { es: "my father's car", en: "el carro de mi padre" },
          { es: "Ana's phone", en: "el teléfono de Ana" },
          { es: "my sister's room", en: "la habitación de mi hermana" },
          { es: "Tom's girlfriend", en: "la novia de Tom" },
          { es: "It's Diego's birthday.", en: "Es el cumpleaños de Diego." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "es-en",
            prompt: "Traduce al inglés.",
            source: "Es el teléfono de Diego.",
            answer: "It's Diego's phone.",
            altAnswers: ["It's Diego's cell phone.", "It's Diego's mobile."],
            explanation: "Dueño + \"'s\" + cosa: \"Diego's phone\", sin \"the\" delante.",
          },
          {
            type: "multiple-choice",
            question: "¿Cuál es la forma natural de decir «el perro de mi vecino»?",
            options: ["my neighbor's dog", "the dog of my neighbor", "my neighbor dog", "the my neighbor's dog"],
            correctIndex: 0,
            explanation: "Con personas se usa \"'s\": \"my neighbor's dog\". *The dog of my neighbor es una copia del español.",
          },
        ],
      },
      {
        heading: "Plurales: parents' y children's",
        body: [
          "Si el dueño es un plural que acaba en \"-s\", solo se añade el apóstrofo: \"my parents' house\" (la casa de mis padres), \"the girls' room\" (la habitación de las chicas).",
          "Si el plural es irregular y no acaba en \"-s\", se añade \"'s\" normal: \"the children's toys\", \"the men's room\", \"people's names\".",
          "Al hablar, \"parent's\" y \"parents'\" suenan igual; la diferencia solo se ve al escribir.",
        ],
        examples: [
          { es: "my parents' house", en: "la casa de mis padres" },
          { es: "the girls' room", en: "la habitación de las chicas" },
          { es: "the children's toys", en: "los juguetes de los niños" },
          { es: "my grandparents' farm", en: "la granja de mis abuelos" },
        ],
        checkpoint: [
          {
            type: "fill-blank",
            prompt: "Escribe en inglés las palabras en negrita.",
            sentence: "The ___ room is very big.",
            answer: "boys'",
            en: "La habitación [de los chicos] es muy grande.",
            explanation: "\"Boys\" es un plural con \"-s\": solo se añade el apóstrofo, \"boys'\".",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Es la bicicleta de mi hermano.",
        answer: "It's my brother's bike.",
        altAnswers: ["It's my brother's bicycle."],
        explanation: "\"My brother's bike\": el dueño con \"'s\" delante de la cosa.",
      },
      {
        type: "multiple-choice",
        question: "¿Cuál es la forma natural de decir «el carro de mi padre»?",
        options: ["my father's car", "the car of my father", "my father car", "the my father's car"],
        correctIndex: 0,
        explanation: "Dueño + \"'s\" + cosa, sin artículo: \"my father's car\".",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "This is ___ room.",
        answer: "Diego's",
        en: "Esta es la habitación [de Diego].",
        explanation: "«De Diego» es \"Diego's\", delante de la cosa.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "La casa de mis padres es pequeña.",
        answer: "My parents' house is small.",
        explanation: "\"Parents\" acaba en \"-s\": solo se añade el apóstrofo, \"parents'\".",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "The ___ toys are everywhere.",
        answer: "children's",
        altAnswers: ["kids'"],
        en: "Los juguetes [de los niños] están por todas partes.",
        explanation: "\"Children\" es un plural irregular sin \"-s\", así que lleva \"'s\": \"children's\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "¿Cómo se llama la novia de Tom?",
        answer: "What is Tom's girlfriend's name?",
        altAnswers: ["What is the name of Tom's girlfriend?"],
        explanation: "«¿Cómo se llama...?» es \"What is ... name?\". «La novia de Tom» es \"Tom's girlfriend\", y su nombre, \"Tom's girlfriend's name\".",
      },
      {
        type: "multiple-choice",
        question: "¿Cómo se dice «la oficina de mis jefes» (dos jefes)?",
        options: ["my bosses' office", "my boss's office", "my bosses's office", "my bosses office"],
        correctIndex: 0,
        explanation: "\"Bosses\" es plural con \"-s\": solo apóstrofo, \"bosses'\". \"My boss's office\" sería de un solo jefe.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Es el cumpleaños de Lucia.",
        answer: "It's Lucia's birthday.",
        explanation: "\"Lucia's birthday\". El sujeto \"it\" es obligatorio y no hay \"the\" delante de \"Lucia's\".",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "We are at my ___ house.",
        answer: "grandmother's",
        altAnswers: ["grandma's"],
        en: "Estamos en casa [de mi abuela].",
        explanation: "«En casa de mi abuela» es \"at my grandmother's house\" (en conversación, a veces solo \"at my grandmother's\").",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Los amigos de mi hija son de Perú.",
        answer: "My daughter's friends are from Peru.",
        explanation: "Una hija: \"my daughter's\". El verbo va en plural porque \"friends\" es plural.",
      },
      {
        type: "word-order",
        prompt: "Ordena las palabras.",
        words: ["Emma's", "brother", "is", "a", "doctor."],
        translation: "El hermano de Emma es médico.",
        explanation: "\"Emma's brother\": dueño + \"'s\" + persona. Y la profesión lleva \"a\": \"a doctor\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "La habitación de las niñas es rosa.",
        answer: "The girls' room is pink.",
        explanation: "Varias niñas: \"girls\" + apóstrofo, \"the girls' room\". Aquí \"the\" va con \"girls\", no con \"room\".",
      },
      {
        type: "multiple-choice",
        question: "Carlos y Ana tienen un perro juntos. ¿Cómo se dice «el perro de Carlos y Ana»?",
        options: ["Carlos and Ana's dog", "the dog of Carlos and Ana", "Carlos and Ana dog", "the Carlos and Ana's dog"],
        correctIndex: 0,
        explanation: "Si las dos personas comparten la cosa, el \"'s\" va solo en la última: \"Carlos and Ana's dog\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Mi profesor se llama señor Smith.",
        answer: "My teacher's name is Mr. Smith.",
        altAnswers: ["My teacher is Mr. Smith.", "My teacher is called Mr. Smith."],
        explanation: "«Se llama» es \"name is\": \"My teacher's name is...\". Nunca *My teacher calls himself.",
      },
      {
        type: "matching",
        instructions: "Une cada expresión con su significado.",
        pairs: [
          { left: "my sister's car", right: "el carro de mi hermana" },
          { left: "my sisters' car", right: "el carro de mis hermanas" },
          { left: "the children's books", right: "los libros de los niños" },
          { left: "my friend's house", right: "la casa de mi amigo" },
        ],
        explanation: "\"'s\" para un dueño o para plurales irregulares; solo apóstrofo para plurales con \"-s\".",
      },
      {
        type: "listen-choose",
        audio: "The children's room is next to the kitchen.",
        question: "¿De quién es la habitación?",
        options: ["De los niños.", "Del cocinero.", "De los padres.", "De la abuela."],
        correctIndex: 0,
        explanation: "\"The children's room\" es la habitación de los niños.",
      },
      {
        type: "dictation",
        audio: "This is Tom's phone, and that is Ana's.",
        altAnswers: ["This is Tom's phone, and that's Ana's."],
        explanation: "\"Ana's\" solo, sin repetir \"phone\", significa «el de Ana».",
      },
    ],
  },

  // ---------------------------------------------------------------------
  // Extra 3. Prepositions of place
  // ---------------------------------------------------------------------
  {
    slug: "en-a1-prepositions-place-drill-1",
    level: "EN-A1",
    optional: true,
    number: 3,
    title: "Práctica: in, on, at, under, next to",
    summary: "Dónde está cada cosa: \"in the kitchen\", \"on the table\", \"on the wall\", \"under the bed\", \"next to the door\", y \"at home\", \"at work\", \"at the bus stop\".",
    duration: "10 min",
    sections: [
      {
        heading: "Recordatorio: in, on, under, next to, behind",
        body: [
          "«En» tiene varias traducciones. \"In\" es dentro (\"in the box\", \"in the kitchen\"); \"on\" es encima o sobre una superficie (\"on the table\", \"on the wall\", \"on the floor\"). El error típico es *in the table.",
          "Otras: \"under\" (debajo de), \"next to\" (al lado de), \"behind\" (detrás de), \"between\" (entre) y \"near\" (cerca de). Fíjate en que \"next to\" y \"behind\" no llevan \"of\": *next of the door es incorrecto.",
        ],
        examples: [
          { es: "The milk is in the fridge.", en: "La leche está en el refrigerador." },
          { es: "Your notebook is on the table.", en: "Tu cuaderno está en la mesa." },
          { es: "There is a picture on the wall.", en: "Hay un cuadro en la pared." },
          { es: "The shoes are under the bed.", en: "Los zapatos están debajo de la cama." },
          { es: "The lamp is next to the sofa.", en: "La lámpara está al lado del sofá." },
          { es: "The cat is behind the door.", en: "El gato está detrás de la puerta." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "¿Cuál es correcta?",
            options: ["The photo is on the wall.", "The photo is in the wall.", "The photo is at the wall.", "The photo is of the wall."],
            correctIndex: 0,
            explanation: "La pared es una superficie: \"on the wall\". \"In the wall\" significaría dentro de la pared.",
          },
          {
            type: "translate",
            direction: "es-en",
            prompt: "Traduce al inglés.",
            source: "Tu cuaderno está en la mesa.",
            answer: "Your notebook is on the table.",
            explanation: "Encima de la mesa: \"on the table\", nunca *in the table.",
          },
        ],
      },
      {
        heading: "Recordatorio: at home, at work, at the bus stop",
        body: [
          "\"At\" se usa para un punto o un lugar donde haces algo: \"at home\", \"at work\", \"at school\" (sin \"the\"), y \"at the bus stop\", \"at the airport\", \"at the door\".",
          "Errores típicos: *in home, *in the work, *in the bus stop. En los transportes grandes se dice \"on\": \"on the bus\", \"on the train\", \"on the plane\".",
        ],
        examples: [
          { es: "I'm at home.", en: "Estoy en casa." },
          { es: "My brother is at work.", en: "Mi hermano está en el trabajo." },
          { es: "We're at the bus stop.", en: "Estamos en la parada del autobús." },
          { es: "The children are on the bus.", en: "Los niños están en el autobús." },
        ],
        checkpoint: [
          {
            type: "fill-blank",
            prompt: "Escribe en inglés las palabras en negrita.",
            sentence: "My brother is ___ work.",
            answer: "at",
            en: "Mi hermano está [en el] trabajo.",
            explanation: "«En el trabajo» es \"at work\", con \"at\" y sin \"the\".",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "multiple-choice",
        question: "¿Cómo se dice «Los niños están en casa»?",
        options: ["The kids are at home.", "The kids are in home.", "The kids are in the home.", "The kids are on home."],
        correctIndex: 0,
        explanation: "«En casa» es \"at home\", sin \"the\". *In home es un error muy típico.",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "There is a clock ___ the wall.",
        answer: "on",
        en: "Hay un reloj [en] la pared.",
        explanation: "Lo que está colgado en la pared está \"on the wall\" (sobre la superficie).",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Estoy en la parada del autobús.",
        answer: "I'm at the bus stop.",
        explanation: "Un punto concreto: \"at the bus stop\". *In the bus stop es incorrecto.",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "The shoes are ___ the bed.",
        answer: "under",
        altAnswers: ["underneath"],
        en: "Los zapatos están [debajo de] la cama.",
        explanation: "«Debajo de» es \"under\", sin \"of\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Mi padre está en la cocina.",
        answer: "My father is in the kitchen.",
        altAnswers: ["My dad is in the kitchen."],
        explanation: "Dentro de una habitación: \"in the kitchen\".",
      },
      {
        type: "multiple-choice",
        question: "Tu hija tiene clase hoy. ¿Cómo dices «Está en el colegio»?",
        options: ["She's at school.", "She's on school.", "She's to school.", "She's by school."],
        correctIndex: 0,
        explanation: "\"At school\", igual que \"at home\" y \"at work\", sin \"the\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "La lámpara está al lado del sofá.",
        answer: "The lamp is next to the sofa.",
        altAnswers: ["The lamp is next to the couch.", "The lamp is beside the sofa.", "The lamp is beside the couch."],
        explanation: "«Al lado de» es \"next to\", sin \"of\": nunca *next of the sofa.",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "The children are ___ the bus.",
        answer: "on",
        en: "Los niños están [en] el autobús.",
        explanation: "Con el autobús, el tren o el avión se usa \"on\": \"on the bus\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "El gato está detrás de la puerta.",
        answer: "The cat is behind the door.",
        explanation: "«Detrás de» es \"behind\", sin \"of\".",
      },
      {
        type: "matching",
        instructions: "Une cada expresión con su significado.",
        pairs: [
          { left: "on the wall", right: "en la pared" },
          { left: "in the kitchen", right: "en la cocina" },
          { left: "at work", right: "en el trabajo" },
          { left: "under the table", right: "debajo de la mesa" },
          { left: "next to the window", right: "al lado de la ventana" },
        ],
        explanation: "Tres maneras de decir «en» (\"on\", \"in\", \"at\") según el lugar.",
      },
      {
        type: "word-order",
        prompt: "Ordena las palabras.",
        words: ["The", "keys", "are", "next", "to", "the", "phone."],
        translation: "Las llaves están al lado del teléfono.",
        explanation: "\"Next to\" + \"the phone\". «Del» se traduce solo como \"the\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Mis padres están en el aeropuerto.",
        answer: "My parents are at the airport.",
        altAnswers: ["My parents are in the airport."],
        explanation: "Con lugares como el aeropuerto o la estación se suele usar \"at\": \"at the airport\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Hay un perro debajo del carro.",
        answer: "There is a dog under the car.",
        altAnswers: ["There's a dog underneath the car.", "A dog is under the car."],
        explanation: "\"There is\" + \"a dog\" + \"under the car\". «Hay» es \"there is\", nunca *it has.",
      },
      {
        type: "multiple-choice",
        question: "¿Cuál es correcta?",
        options: ["The bank is next to the hotel.", "The bank is next of the hotel.", "The bank is next the hotel.", "The bank is in next to the hotel."],
        correctIndex: 0,
        explanation: "\"Next to\" va siempre con \"to\", nunca con \"of\".",
      },
      {
        type: "listen-choose",
        audio: "Your jacket is on the chair, behind the door.",
        question: "¿Dónde está la chaqueta?",
        options: ["En la silla, detrás de la puerta.", "Debajo de la silla, detrás de la puerta.", "En la silla, al lado de la puerta.", "En la puerta, detrás de la silla."],
        correctIndex: 0,
        explanation: "\"On the chair\" es en la silla y \"behind the door\", detrás de la puerta.",
      },
      {
        type: "dictation",
        audio: "My phone is in my bag, under the books.",
        explanation: "\"In\" (dentro del bolso) y \"under\" (debajo de los libros).",
      },
      {
        type: "speak",
        text: "I'm at home. My phone is on the table.",
        tip: "En \"at home\" la \"h\" se pronuncia con aire, como una «j» suave: «at jóum».",
        explanation: "\"At home\" sin \"the\", y \"on the table\" para una superficie.",
      },
    ],
  },

  // ---------------------------------------------------------------------
  // Extra 4. Numbers and prices
  // ---------------------------------------------------------------------
  {
    slug: "en-a1-numbers-prices-drill-1",
    level: "EN-A1",
    optional: true,
    number: 4,
    title: "Práctica: números y precios",
    summary: "Distingue \"thirteen\" de \"thirty\" y \"fifteen\" de \"fifty\", dicta números de teléfono, di precios como \"$4.99\" y \"£12.50\" y escribe \"two hundred\" sin -s.",
    duration: "11 min",
    sections: [
      {
        heading: "Recordatorio: -teen o -ty",
        body: [
          "\"Thirteen\" (13) y \"thirty\" (30) se parecen mucho. La pista es el acento: \"thirTEEN\", \"fourTEEN\", \"fifTEEN\" llevan el golpe al final y una \"ee\" larga; \"THIRty\", \"FORty\", \"FIFty\", al principio.",
          "\"Hundred\" y \"thousand\" no llevan -s después de un número: \"two hundred dollars\", nunca *two hundreds. En Reino Unido se dice \"and\" antes de las decenas (\"a hundred and twenty\"); en EE. UU. se suele omitir (\"one hundred twenty\").",
        ],
        examples: [
          { es: "thirteen, thirty", en: "trece, treinta" },
          { es: "fifteen, fifty", en: "quince, cincuenta" },
          { es: "She's sixteen.", en: "Ella tiene dieciséis años." },
          { es: "two hundred dollars", en: "doscientos dólares" },
          { es: "a hundred and twenty", en: "ciento veinte" },
        ],
        checkpoint: [
          {
            type: "listen-choose",
            audio: "He's sixteen.",
            question: "¿Cuántos años tiene?",
            options: ["16", "60", "6", "66"],
            correctIndex: 0,
            explanation: "\"SixTEEN\" lleva el acento al final y una \"ee\" larga: 16. \"Sixty\" (60) se acentúa al principio.",
          },
          {
            type: "multiple-choice",
            question: "¿Cómo se escribe en inglés «trescientos dólares»?",
            options: ["three hundred dollars", "three hundreds dollars", "three hundred dollar", "three hundreds of dollars"],
            correctIndex: 0,
            explanation: "\"Hundred\" no lleva -s detrás de un número, pero \"dollars\" sí va en plural.",
          },
        ],
      },
      {
        heading: "Recordatorio: teléfonos y precios",
        body: [
          "En los números de teléfono las cifras se dicen una a una, y el cero suele ser \"oh\": 405 es \"four oh five\". En Reino Unido, para dos cifras iguales se dice \"double\": 77 es \"double seven\".",
          "En los precios se escribe el símbolo delante y se dice la moneda detrás: \"$4.99\" es \"four ninety-nine\" o \"four dollars and ninety-nine cents\"; \"£12.50\" es \"twelve pounds fifty\". El decimal lleva punto, no coma.",
        ],
        examples: [
          { es: "four oh five", en: "cuatro cero cinco (405)" },
          { es: "double seven", en: "siete siete (77)" },
          { es: "It's four ninety-nine.", en: "Son 4,99 (dólares)." },
          { es: "It costs twelve pounds fifty.", en: "Cuesta doce libras con cincuenta." },
          { es: "How much are these shoes?", en: "¿Cuánto cuestan estos zapatos?" },
        ],
        checkpoint: [
          {
            type: "fill-blank",
            prompt: "Escribe en inglés las palabras en negrita.",
            sentence: "The room number is two ___ six.",
            answer: "oh",
            altAnswers: ["zero"],
            en: "El número de la habitación es dos [cero] seis.",
            explanation: "En números que se dicen cifra a cifra, el cero suele ser \"oh\": \"two oh six\".",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "listen-choose",
        audio: "It's thirteen dollars.",
        question: "¿Cuánto cuesta?",
        options: ["$13", "$30", "$3", "$33"],
        correctIndex: 0,
        explanation: "\"ThirTEEN\" lleva el acento al final: 13. \"Thirty\" (30) se acentúa al principio.",
      },
      {
        type: "listen-choose",
        audio: "My grandmother is fifty.",
        question: "¿Cuántos años tiene la abuela?",
        options: ["50", "15", "5", "55"],
        correctIndex: 0,
        explanation: "\"FIFty\" se acentúa al principio y acaba rápido: 50. \"Fifteen\" (15) tiene una \"ee\" larga al final.",
      },
      {
        type: "listen-choose",
        audio: "That's four ninety-nine.",
        question: "¿Cuánto es?",
        options: ["$4.99", "$14.90", "$4.19", "$9.49"],
        correctIndex: 0,
        explanation: "En los precios se dicen los dólares y luego los centavos: \"four ninety-nine\" es $4.99.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Cuesta doce libras con cincuenta.",
        answer: "It costs twelve pounds fifty.",
        altAnswers: [
          "It's twelve pounds fifty.",
          "It costs £12.50.",
          "It's £12.50.",
          "It costs twelve pounds and fifty pence.",
          "It's twelve pounds and fifty pence.",
          "It costs twelve fifty.",
          "It's twelve fifty.",
        ],
        explanation: "\"Twelve pounds fifty\": la moneda se dice después de la primera cifra. El sujeto \"it\" es obligatorio.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Mi abuela tiene ochenta y cinco años.",
        answer: "My grandmother is eighty-five years old.",
        altAnswers: ["My grandmother is eighty-five.", "My grandma is eighty-five years old.", "My grandma is eighty-five."],
        explanation: "La edad va con \"be\": \"is eighty-five\", nunca *has eighty-five years. Las decenas y las unidades van con guion.",
      },
      {
        type: "multiple-choice",
        question: "¿Qué número es \"a hundred and twenty\"?",
        options: ["120", "1,020", "102", "100"],
        correctIndex: 0,
        explanation: "\"A hundred\" (100) \"and twenty\" (20): 120. El \"and\" es típico del inglés británico.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "El libro cuesta quince dólares.",
        answer: "The book costs fifteen dollars.",
        altAnswers: ["The book is fifteen dollars.", "The book costs $15.", "The book is $15."],
        explanation: "\"Costs\" con -s (tercera persona) y \"dollars\" en plural. Pronuncia \"fifTEEN\" con acento al final para que no suene a \"fifty\".",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "This phone costs ___ dollars.",
        answer: "seven hundred",
        altAnswers: ["700"],
        en: "Este teléfono cuesta [setecientos] dólares.",
        explanation: "\"Seven hundred\", sin -s: nunca *seven hundreds.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "¿Cuánto cuestan estos zapatos?",
        answer: "How much are these shoes?",
        altAnswers: ["How much do these shoes cost?"],
        explanation: "«¿Cuánto cuestan?» es \"How much are...?\" o \"How much do... cost?\". \"Shoes\" es plural: \"are\" y \"these\".",
      },
      {
        type: "multiple-choice",
        question: "Oyes \"double seven\" en un número de teléfono. ¿Qué cifras son?",
        options: ["77", "27", "7", "70"],
        correctIndex: 0,
        explanation: "\"Double\" significa que la cifra se repite: \"double seven\" es 77.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Hay dos mil personas en el concierto.",
        answer: "There are two thousand people at the concert.",
        altAnswers: ["Two thousand people are at the concert.", "There are 2,000 people at the concert."],
        explanation: "\"Two thousand\", sin -s. \"People\" es plural, así que \"there are\". En un evento se dice \"at the concert\".",
      },
      {
        type: "matching",
        instructions: "Une cada número con su significado.",
        pairs: [
          { left: "thirteen", right: "trece" },
          { left: "thirty", right: "treinta" },
          { left: "fourteen", right: "catorce" },
          { left: "forty", right: "cuarenta" },
          { left: "nineteen", right: "diecinueve" },
          { left: "ninety", right: "noventa" },
        ],
        explanation: "\"-teen\" va del 13 al 19 y \"-ty\" son las decenas. Ojo: \"forty\" se escribe sin \"u\", aunque \"four\" y \"fourteen\" la tengan.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "La chaqueta cuesta 49,99 dólares.",
        answer: "The jacket costs $49.99.",
        altAnswers: [
          "The jacket is $49.99.",
          "The jacket costs forty-nine ninety-nine.",
          "The jacket is forty-nine ninety-nine.",
          "The jacket costs forty-nine dollars and ninety-nine cents.",
          "The jacket is forty-nine dollars and ninety-nine cents.",
        ],
        explanation: "En inglés el decimal lleva punto: $49.99, no $49,99. El símbolo va delante del número.",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "My son is ___ years old.",
        answer: "fourteen",
        altAnswers: ["14"],
        en: "Mi hijo tiene [catorce] años.",
        explanation: "\"Fourteen\" (14), con acento al final. No lo confundas con \"forty\" (40).",
      },
      {
        type: "dictation",
        audio: "How much is it? It's sixteen dollars.",
        altAnswers: ["How much is it? It is sixteen dollars.", "How much is it? It's $16."],
        explanation: "\"How much is it?\" es la pregunta del precio. \"SixTEEN\" con acento al final.",
      },
      {
        type: "speak",
        text: "Fourteen, forty. Seventeen, seventy.",
        tip: "En \"fourteen\" y \"seventeen\", acentúa el final y alarga la \"ee\". En \"forty\" y \"seventy\", acentúa el principio.",
        explanation: "La diferencia entre \"-teen\" y \"-ty\" está en el acento.",
      },
    ],
  },

  // ---------------------------------------------------------------------
  // Extra 5. Telling the time
  // ---------------------------------------------------------------------
  {
    slug: "en-a1-time-drill-1",
    level: "EN-A1",
    optional: true,
    number: 5,
    title: "Práctica: decir la hora",
    summary: "What time is it? Practica \"It's two o'clock\", \"half past\", \"quarter past\", \"quarter to\", la forma digital y \"at\" + hora.",
    duration: "11 min",
    sections: [
      {
        heading: "Recordatorio: \"It's\" + la hora",
        body: [
          "La hora siempre empieza por \"It's\", en singular: «son las dos» es \"It's two o'clock\". Nunca *It's the two, *Are the two ni *Is two.",
          "\"Past\" es «y» y \"to\" es «menos», y los minutos van primero: \"ten past two\" (2:10), \"half past two\" (2:30), \"quarter to three\" (2:45). Cuidado: «las dos y media» es \"half past two\", no *half past three. También puedes usar la forma digital: \"two thirty\".",
        ],
        examples: [
          { es: "It's two o'clock.", en: "Son las dos." },
          { es: "It's ten past two.", en: "Son las dos y diez." },
          { es: "It's half past two.", en: "Son las dos y media." },
          { es: "It's quarter to three.", en: "Son las tres menos cuarto." },
          { es: "It's two thirty.", en: "Son las dos y media." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "¿Cómo se dice «son las cuatro y media»?",
            options: ["It's half past four.", "It's half past five.", "Are the four and half.", "It's the four and half."],
            correctIndex: 0,
            explanation: "«Y media» es \"half past\" + la hora que ya ha pasado: \"half past four\". Siempre con \"It's\".",
          },
          {
            type: "translate",
            direction: "es-en",
            prompt: "Traduce al inglés.",
            source: "Son las seis en punto.",
            answer: "It's six o'clock.",
            altAnswers: ["It's six.", "It's 6:00."],
            explanation: "«En punto» es \"o'clock\". La hora va con \"it's\", en singular.",
          },
        ],
      },
      {
        heading: "Recordatorio: \"at\" + hora",
        body: [
          "Para decir a qué hora pasa algo se usa \"at\", sin artículo: «a las tres» es \"at three\", nunca *at the three.",
          "Para preguntar: \"What time is the class?\" o \"What time does the movie start?\".",
        ],
        examples: [
          { es: "The meeting is at three o'clock.", en: "La reunión es a las tres." },
          { es: "I have lunch at half past one.", en: "Como a la una y media." },
          { es: "What time is the class?", en: "¿A qué hora es la clase?" },
          { es: "The store opens at 9 a.m.", en: "La tienda abre a las 9 de la mañana." },
        ],
        checkpoint: [
          {
            type: "fill-blank",
            prompt: "Escribe en inglés las palabras en negrita.",
            sentence: "The meeting is ___ three o'clock.",
            answer: "at",
            en: "La reunión es [a las] tres.",
            explanation: "«A las» es solo \"at\": \"at three o'clock\", sin \"the\".",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Son las dos.",
        answer: "It's two o'clock.",
        altAnswers: ["It's two.", "It's 2:00."],
        explanation: "«Son las dos» es \"It's two o'clock\": singular y con \"it\". Nunca *Are the two.",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "It's quarter ___ ten.",
        answer: "to",
        altAnswers: ["of", "till"],
        en: "Son las diez [menos] cuarto.",
        explanation: "«Menos» es \"to\" (en EE. UU. también \"of\"): \"quarter to ten\" es 9:45.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Son las once y diez.",
        answer: "It's ten past eleven.",
        altAnswers: ["It's ten after eleven.", "It's eleven ten.", "It's 11:10."],
        explanation: "Los minutos primero y \"past\" para «y»: \"ten past eleven\". O la forma digital: \"eleven ten\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "¿A qué hora es la clase?",
        answer: "What time is the class?",
        altAnswers: ["What time is class?", "When is the class?", "When is class?"],
        explanation: "«¿A qué hora...?» es \"What time...?\", sin \"at\" delante en la pregunta normal.",
      },
      {
        type: "multiple-choice",
        question: "¿Qué hora es \"quarter past six\"?",
        options: ["6:15", "5:45", "6:45", "6:25"],
        correctIndex: 0,
        explanation: "\"Quarter past\" es «y cuarto»: las seis y cuarto, 6:15.",
      },
      {
        type: "listen-choose",
        audio: "It's twenty-five to eight.",
        question: "¿Qué hora es?",
        options: ["7:35", "8:25", "7:25", "8:35"],
        correctIndex: 0,
        explanation: "\"To\" es «menos»: las ocho menos veinticinco, es decir, 7:35.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Son las nueve menos cinco.",
        answer: "It's five to nine.",
        altAnswers: ["It's five of nine.", "It's eight fifty-five.", "It's 8:55."],
        explanation: "«Menos cinco» es \"five to\". En digital se dice la hora anterior: \"eight fifty-five\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Es la una y cuarto.",
        answer: "It's quarter past one.",
        altAnswers: [
          "It's a quarter past one.",
          "It's one fifteen.",
          "It's 1:15.",
          "It's quarter after one.",
          "It's a quarter after one.",
        ],
        explanation: "«Es la una» también va con \"it's\": la hora en inglés no cambia entre singular y plural.",
      },
      {
        type: "multiple-choice",
        question: "¿Cuál es correcta?",
        options: ["It's seven o'clock.", "It's the seven.", "Are the seven.", "Is seven o'clock."],
        correctIndex: 0,
        explanation: "\"It's\" + hora, sin artículo. *It's the seven y *Are the seven son copias de «son las siete».",
      },
      {
        type: "word-order",
        prompt: "Ordena las palabras.",
        words: ["The", "train", "leaves", "at", "half", "past", "six."],
        translation: "El tren sale a las seis y media.",
        altOrders: [["At", "half", "past", "six", "the", "train", "leaves."]],
        explanation: "\"At\" + \"half past six\". \"Leaves\" lleva -s porque el sujeto es \"the train\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Ceno a las ocho y media.",
        answer: "I have dinner at half past eight.",
        altAnswers: [
          "I have dinner at eight thirty.",
          "I have dinner at 8:30.",
          "I eat dinner at half past eight.",
          "I eat dinner at eight thirty.",
          "I eat dinner at 8:30.",
        ],
        explanation: "«Cenar» es \"have dinner\". «A las ocho y media» es \"at half past eight\" o \"at eight thirty\".",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "It's ten ___.",
        answer: "thirty",
        en: "Son las diez [y media].",
        explanation: "En la forma digital, «las diez y media» es \"ten thirty\" (10:30).",
      },
      {
        type: "matching",
        instructions: "Une cada hora con su significado.",
        pairs: [
          { left: "half past two", right: "las dos y media" },
          { left: "quarter past two", right: "las dos y cuarto" },
          { left: "quarter to two", right: "las dos menos cuarto" },
          { left: "two o'clock", right: "las dos en punto" },
          { left: "ten to two", right: "las dos menos diez" },
        ],
        explanation: "\"Past\" es «y» y \"to\" es «menos»; los minutos siempre van primero.",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "My English class starts ___ seven.",
        answer: "at",
        en: "Mi clase de inglés empieza [a las] siete.",
        explanation: "«A las» es \"at\", sin artículo: \"at seven\", nunca *at the seven.",
      },
      {
        type: "dictation",
        audio: "What time is it? It's quarter to eleven.",
        altAnswers: ["What time is it? It's a quarter to eleven.", "What time is it? It is quarter to eleven."],
        explanation: "\"Quarter to eleven\" son las once menos cuarto (10:45).",
      },
      {
        type: "speak",
        text: "It's half past two.",
        tip: "En \"half\" la \"l\" no se pronuncia: suena «jaf» en EE. UU. y «jaaf» en Reino Unido.",
        explanation: "\"Half past two\" son las dos y media.",
      },
      {
        type: "write",
        prompt: "Escríbele a un amigo tu plan para el sábado: di a qué hora haces al menos cuatro cosas.",
        minWords: 25,
        maxWords: 60,
        rubric: [
          "Usa \"at\" + hora sin artículo (\"at ten\", \"at half past one\").",
          "Usa al menos una hora con \"past\" o \"to\" y otra en forma digital.",
          "Cada frase tiene sujeto y el verbo correcto.",
        ],
        modelAnswer: "Hi Diego! On Saturday I get up at nine. I play tennis with my sister at half past ten. We have lunch at my parents' house at two fifteen. The movie starts at quarter to eight, and it finishes at ten. See you on Sunday!",
        explanation: "Revisa cada hora: \"at\" delante, sin \"the\", y \"past\" o \"to\" bien elegidos.",
      },
    ],
  },
];
