// Synced from cheneygross-afk/lengo:src/lib/lessons/en-a2-u04-extra.ts by scripts/sync-content.mjs -- edit it there, not here.
import type { Lesson } from "./types";

// Extra practice (optional) lessons for EN-A2 unit u04.

export const EN_A2_U04_EXTRA: Lesson[] = [  // ---------------------------------------------------------------------
  // Extra 1. Used to: form drill
  // ---------------------------------------------------------------------
  {
    slug: "en-a2-used-to-drill-1",
    optional: true,
    level: "EN-A2",
    number: 1,
    title: "Práctica extra: used to",
    summary: "Práctica intensiva de \"used to\" + verbo base, \"didn't use to\" y \"Did you use to...?\", con los errores más típicos.",
    duration: "10 min",
    sections: [
      {
        heading: "Repaso rápido: la forma de \"used to\"",
        body: [
          "\"Used to\" + verbo en forma base cuenta costumbres o situaciones del pasado que ya no son así: \"I used to play tennis\" («solía jugar al tenis» / «antes jugaba al tenis»).",
          "Afirmativa: \"used to\" (con \"-d\"). Negativa y pregunta: \"didn't use to\" y \"Did you use to...?\" (sin \"-d\", porque \"did\" ya marca el pasado). Errores típicos: *I didn't used to, *Did you used to.",
          "Detrás va el verbo base, nunca con \"-ing\": *I used to going es incorrecto. Y en la afirmativa no se olvida la \"-d\": *I use to play.",
        ],
        examples: [
          { es: "I used to play tennis.", en: "Antes jugaba al tenis. / Solía jugar al tenis." },
          { es: "She used to live in Lima.", en: "Ella vivía antes en Lima." },
          { es: "We didn't use to have a car.", en: "Antes no teníamos carro." },
          { es: "Did you use to wear glasses?", en: "¿Antes llevabas gafas?" },
          { es: "There used to be a cinema here.", en: "Aquí antes había un cine." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "¿Cuál es correcta?",
            options: ["I didn't use to like coffee.", "I didn't used to like coffee.", "I don't used to like coffee.", "I didn't use to liking coffee."],
            correctIndex: 0,
            explanation: "Con \"didn't\" se escribe \"use to\", sin \"-d\", y después el verbo base: \"like\".",
          },
          {
            type: "translate",
            direction: "es-en",
            prompt: "Traduce al inglés.",
            source: "Yo solía correr todas las mañanas.",
            answer: "I used to run every morning.",
            altAnswers: ["I used to go running every morning.", "I used to jog every morning.", "I used to go for a run every morning."],
            explanation: "\"Used to\" + verbo base: \"run\", no *running.",
          },
        ],
      },
      {
        heading: "Ojo: \"used to\" solo es pasado",
        body: [
          "\"Used to\" NO existe en presente con este sentido. «Suelo» se dice con el presente simple, a menudo con \"usually\": \"I usually walk to work\". *I use to walk to work es un error muy típico.",
          "Si la costumbre sigue hoy, no uses \"used to\": \"I used to smoke\" significa que ya no fumas.",
        ],
        examples: [
          { es: "I usually walk to work.", en: "Suelo ir andando al trabajo." },
          { es: "I used to walk to work.", en: "Antes iba andando al trabajo (ya no)." },
          { es: "He used to smoke, but he stopped.", en: "Antes fumaba, pero lo dejó." },
        ],
        checkpoint: [
          {
            type: "fill-blank",
            prompt: "Escribe en inglés las palabras en negrita.",
            sentence: "I ___ cook on Sundays.",
            answer: "usually",
            altAnswers: ["normally", "generally", "often"],
            en: "[Suelo] cocinar los domingos.",
            explanation: "«Suelo» (presente) = \"usually\" + presente simple. *I use to cook es incorrecto.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Mi papá solía trabajar en un banco.",
        answer: "My dad used to work in a bank.",
        altAnswers: ["My dad used to work at a bank.", "My father used to work in a bank.", "My father used to work at a bank."],
        explanation: "\"Used to\" (con \"-d\") + verbo base \"work\".",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "We ___ go camping every summer.",
        answer: "used to",
        en: "[Solíamos] ir de camping todos los veranos.",
        explanation: "Costumbre del pasado: \"used to\" + \"go\". La forma es la misma para todas las personas.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "¿Antes vivías cerca de aquí?",
        answer: "Did you use to live near here?",
        altAnswers: ["Did you use to live around here?", "Did you use to live close to here?", "Did you live near here before?", "Did you live around here before?"],
        explanation: "Pregunta: \"Did you use to\" (sin \"-d\") + verbo base. *Did you used to es un error común.",
      },
      {
        type: "multiple-choice",
        question: "Busca el error: *She use to have long hair. ¿Qué debería decir?",
        options: ["She used to have long hair.", "She uses to have long hair.", "She used to having long hair.", "She was used to have long hair."],
        correctIndex: 0,
        explanation: "En afirmativa siempre \"used to\", con \"-d\", para todas las personas: \"She used to have\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Antes no me gustaba el pescado.",
        answer: "I didn't use to like fish.",
        altAnswers: ["I never used to like fish.", "I didn't like fish before.", "I used to not like fish.", "I used not to like fish."],
        explanation: "Negativa: \"didn't use to\" + \"like\". Ojo: «me gustaba» se dice con \"I\" como sujeto: \"I like\".",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "There ___ be a school on this street.",
        answer: "used to",
        en: "Antes [había] una escuela en esta calle.",
        explanation: "«Antes había» = \"there used to be\". Nunca *there used to have.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Mis abuelos solían contarnos historias.",
        answer: "My grandparents used to tell us stories.",
        explanation: "\"Used to\" + \"tell\". «Contar una historia» es \"tell a story\", no *count.",
      },
      {
        type: "multiple-choice",
        question: "¿Cuál es correcta?",
        options: ["Did they use to play together?", "Did they used to play together?", "Used they to playing together?", "Do they used to play together?"],
        correctIndex: 0,
        explanation: "Pregunta en pasado con \"did\" + \"use to\" + verbo base.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Él antes fumaba, pero ahora hace deporte.",
        answer: "He used to smoke, but now he plays sports.",
        altAnswers: [
          "He used to smoke, but now he does sports.",
          "He used to smoke, but now he exercises.",
          "He used to smoke but now he plays sports.",
          "He used to smoke, but now he does sport.",
          "He used to smoke, but now he plays sport.",
          "He used to smoke, but now he works out.",
        ],
        explanation: "«Antes fumaba» (ya no) = \"used to smoke\". Lo de ahora, en presente simple con \"-s\": \"he plays\".",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "I didn't ___ eat vegetables when I was a kid.",
        answer: "use to",
        en: "De niño [no solía] comer verduras.",
        explanation: "Después de \"didn't\": \"use to\", sin \"-d\".",
      },
      {
        type: "multiple-choice",
        question: "«Suelo tomar té por la mañana.» ¿Cuál es correcta?",
        options: [
          "I usually have tea in the morning.",
          "I use to have tea in the morning.",
          "I used to have tea in the morning.",
          "I am used to have tea in the morning.",
        ],
        correctIndex: 0,
        explanation: "«Suelo» es presente: \"usually\" + presente simple. \"I used to have tea\" significaría que ya NO lo tomas.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "¿Dónde solías ir de vacaciones?",
        answer: "Where did you use to go on vacation?",
        altAnswers: ["Where did you use to go on holiday?", "Where did you use to go for vacation?", "Where did you use to go on holidays?"],
        explanation: "Palabra interrogativa + \"did\" + sujeto + \"use to\" + verbo base.",
      },
      {
        type: "word-order",
        prompt: "Ordena las palabras.",
        words: ["We", "didn't", "use", "to", "have", "a", "TV."],
        translation: "Antes no teníamos tele.",
        explanation: "\"Didn't use to\" + verbo base \"have\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Ella antes era muy tímida.",
        answer: "She used to be very shy.",
        altAnswers: ["She used to be really shy.", "She was very shy before.", "She was really shy before."],
        explanation: "\"Used to be\" para un estado que ya cambió. «Tímida» se dice normalmente \"shy\".",
      },
      {
        type: "matching",
        instructions: "Une cada frase con su significado.",
        pairs: [
          { left: "I used to swim.", right: "Antes nadaba (ya no)." },
          { left: "I usually swim.", right: "Suelo nadar (ahora)." },
          { left: "I didn't use to swim.", right: "Antes no nadaba." },
          { left: "Did you use to swim?", right: "¿Antes nadabas?" },
        ],
        explanation: "\"Used to\" = pasado que ya no es así; \"usually\" + presente = costumbre actual.",
      },
      {
        type: "listen-choose",
        audio: "I used to live in the city, but now I live in a small village.",
        question: "¿Dónde vive ahora?",
        options: ["En un pueblo pequeño.", "En la ciudad.", "En la ciudad y en un pueblo.", "No lo dice."],
        correctIndex: 0,
        explanation: "\"I used to live in the city\" = antes. \"Now I live in a small village\" = ahora.",
      },
      {
        type: "speak",
        text: "I used to play the piano.",
        tip: "\"Used to\" se pronuncia /YUS-tu/, con una «s» suave, no con «d»: la \"-d\" casi no se oye.",
        explanation: "En la pronunciación, \"use to\" y \"used to\" suenan igual; la diferencia solo se ve al escribir.",
      },
    ],
  },
  // ---------------------------------------------------------------------
  // Extra 2. Usually vs used to
  // ---------------------------------------------------------------------
  {
    slug: "en-a2-used-to-vs-usually-drill-1",
    optional: true,
    level: "EN-A2",
    number: 2,
    title: "Práctica extra: suelo o solía",
    summary: "«Suelo» frente a «solía»: \"usually\" + presente para las costumbres de hoy y \"used to\" para las del pasado.",
    duration: "10 min",
    sections: [
      {
        heading: "Repaso rápido: «soler» en presente y en pasado",
        body: [
          "«Suelo», «sueles», «suele»: presente simple, casi siempre con \"usually\" delante del verbo: \"I usually get up at seven\". Con \"he\", \"she\" e \"it\", el verbo lleva \"-s\": \"She usually gets up at seven\".",
          "«Solía», «solías»: \"used to\" + verbo base: \"I used to get up at seven\". También vale el pasado simple con \"usually\": \"I usually got up at seven\".",
          "El error típico es *I use to get up at seven para decir «suelo». En inglés \"use to\" solo aparece detrás de \"did\"/\"didn't\".",
          "Con \"be\", \"usually\" va DETRÁS del verbo: \"I'm usually tired\". En negativa: \"I don't usually...\" («no suelo»).",
        ],
        examples: [
          { es: "I usually get up at seven.", en: "Suelo levantarme a las siete." },
          { es: "I used to get up at seven.", en: "Solía levantarme a las siete." },
          { es: "She usually takes the bus.", en: "Ella suele tomar el autobús." },
          { es: "We don't usually eat out.", en: "No solemos comer fuera." },
          { es: "He's usually late.", en: "Él suele llegar tarde." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "«Suelo ir al gimnasio por la tarde.»",
            options: [
              "I usually go to the gym in the afternoon.",
              "I use to go to the gym in the afternoon.",
              "I used to go to the gym in the afternoon.",
              "I usually going to the gym in the afternoon.",
            ],
            correctIndex: 0,
            explanation: "«Suelo» (hoy) = \"usually\" + presente simple. \"Used to\" sería «solía» (ya no voy).",
          },
          {
            type: "translate",
            direction: "es-en",
            prompt: "Traduce al inglés.",
            source: "Solía ir al gimnasio por la tarde.",
            answer: "I used to go to the gym in the afternoon.",
            altAnswers: ["I used to go to the gym in the afternoons.", "I usually went to the gym in the afternoon.", "I usually went to the gym in the afternoons."],
            explanation: "«Solía» = \"used to\" + verbo base.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Suelo desayunar en casa.",
        answer: "I usually have breakfast at home.",
        altAnswers: ["I usually eat breakfast at home.", "I normally have breakfast at home.", "I normally eat breakfast at home.", "I generally have breakfast at home."],
        explanation: "«Suelo» = \"usually\" + presente. «Desayunar» = \"have breakfast\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Solía desayunar en una cafetería.",
        answer: "I used to have breakfast at a cafe.",
        altAnswers: [
          "I used to eat breakfast at a cafe.",
          "I used to have breakfast in a cafe.",
          "I used to eat breakfast in a cafe.",
          "I usually had breakfast at a cafe.",
          "I usually had breakfast in a cafe.",
          "I used to have breakfast at a coffee shop.",
        ],
        explanation: "«Solía» = \"used to\" + verbo base. «Desayunar» = \"have breakfast\" o \"eat breakfast\".",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "My brother ___ plays video games at night.",
        answer: "usually",
        altAnswers: ["normally", "generally"],
        en: "Mi hermano [suele] jugar a los videojuegos por la noche.",
        explanation: "«Suele» = \"usually\" + verbo con \"-s\": \"usually plays\".",
      },
      {
        type: "multiple-choice",
        question: "«Ella suele llevar gafas.»",
        options: ["She usually wears glasses.", "She use to wear glasses.", "She uses to wear glasses.", "She usually wear glasses."],
        correctIndex: 0,
        explanation: "Presente con \"usually\" y \"-s\" en tercera persona: \"wears\". *She uses to no existe.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "No solemos ver la tele.",
        answer: "We don't usually watch TV.",
        altAnswers: ["We usually don't watch TV.", "We don't usually watch television.", "We don't normally watch TV.", "We rarely watch TV."],
        explanation: "«No solemos» = \"don't usually\" + verbo base.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Antes no veíamos la tele.",
        answer: "We didn't use to watch TV.",
        altAnswers: ["We didn't use to watch television.", "We never used to watch TV.", "We didn't watch TV before.", "We used not to watch TV."],
        explanation: "«Antes no» = \"didn't use to\" (sin \"-d\") + verbo base.",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "When I lived in Lima, I ___ walk to work.",
        answer: "used to",
        en: "Cuando vivía en Lima, [solía] ir caminando al trabajo.",
        explanation: "Costumbre del pasado con el verbo en forma base: \"used to walk\". *I usually walk aquí estaría en presente.",
      },
      {
        type: "multiple-choice",
        question: "¿Qué frase significa que la persona YA NO hace eso?",
        options: ["I used to drink coffee.", "I usually drink coffee.", "I drink coffee every day.", "I'm drinking coffee."],
        correctIndex: 0,
        explanation: "\"Used to\" habla de algo que pasaba antes y ya no pasa.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "¿Qué sueles hacer los sábados?",
        answer: "What do you usually do on Saturdays?",
        altAnswers: ["What do you normally do on Saturdays?", "What do you usually do on Saturday?", "What do you generally do on Saturdays?"],
        explanation: "Pregunta en presente: \"do you usually do\". El primer \"do\" es el auxiliar y el segundo, el verbo «hacer».",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "¿Qué solías hacer los sábados?",
        answer: "What did you use to do on Saturdays?",
        altAnswers: ["What did you usually do on Saturdays?", "What did you use to do on Saturday?"],
        explanation: "Pregunta en pasado: \"did you use to\" + verbo base.",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "The bus is ___ late in the morning.",
        answer: "usually",
        altAnswers: ["normally", "often", "generally"],
        en: "El autobús [suele] llegar tarde por la mañana.",
        explanation: "Con \"be\", \"usually\" va detrás: \"is usually late\". En inglés no hace falta «llegar».",
      },
      {
        type: "multiple-choice",
        question: "Busca el error: *I use to read before I go to sleep. ¿Qué debería decir?",
        options: [
          "I usually read before I go to sleep.",
          "I used to reading before I go to sleep.",
          "I use to reading before I go to sleep.",
          "I uses to read before I go to sleep.",
        ],
        correctIndex: 0,
        explanation: "Es una costumbre de hoy (\"before I go to sleep\", en presente): \"I usually read\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Antes vivía con mis padres, pero ahora vivo solo.",
        answer: "I used to live with my parents, but now I live alone.",
        altAnswers: [
          "I used to live with my parents, but now I live on my own.",
          "I used to live with my parents but now I live alone.",
          "I used to live with my parents but now I live on my own.",
          "I used to live with my parents, but now I live by myself.",
        ],
        explanation: "Pasado que cambió: \"used to live\"; ahora: presente simple \"I live\". «Solo» (sin compañía) = \"alone\".",
      },
      {
        type: "matching",
        instructions: "Une cada frase con su traducción.",
        pairs: [
          { left: "She usually cooks.", right: "Ella suele cocinar." },
          { left: "She used to cook.", right: "Ella solía cocinar." },
          { left: "She doesn't usually cook.", right: "Ella no suele cocinar." },
          { left: "She didn't use to cook.", right: "Ella antes no cocinaba." },
        ],
        explanation: "Presente: \"usually\" / \"doesn't usually\". Pasado: \"used to\" / \"didn't use to\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Mi hija suele dormir ocho horas.",
        answer: "My daughter usually sleeps eight hours.",
        altAnswers: ["My daughter usually sleeps for eight hours.", "My daughter normally sleeps eight hours.", "My daughter normally sleeps for eight hours."],
        explanation: "\"My daughter\" = \"she\": verbo con \"-s\", \"usually sleeps\".",
      },
      {
        type: "listen-choose",
        audio: "I used to take the train, but now I usually drive.",
        question: "¿Cómo va normalmente ahora?",
        options: ["En carro.", "En tren.", "Caminando.", "En autobús."],
        correctIndex: 0,
        explanation: "\"Now I usually drive\" = ahora suele ir en carro. El tren era antes (\"used to\").",
      },
      {
        type: "write",
        prompt: "Escribe 4–6 frases comparando tu vida de niño con tu vida de ahora. Usa \"used to\" / \"didn't use to\" para el pasado y \"usually\" para el presente.",
        minWords: 40,
        maxWords: 80,
        rubric: [
          "Usa \"used to\" + verbo base al menos dos veces.",
          "Usa \"didn't use to\" al menos una vez (sin \"-d\").",
          "Usa \"usually\" + presente simple para tus costumbres de hoy.",
          "No escribe *I use to para el presente.",
        ],
        modelAnswer: "When I was a child, I used to live in a small town. I used to walk to school with my brother, and we usually played in the street after class. I didn't use to like vegetables. Now I live in a big city. I usually take the metro to work, and I usually cook vegetables for dinner. I love them now!",
        explanation: "\"Used to\" para lo que ya cambió; \"usually\" + presente para lo de hoy.",
      },
    ],
  },
  // ---------------------------------------------------------------------
  // Extra 3. Before / after + -ing, and sequencers
  // ---------------------------------------------------------------------
  {
    slug: "en-a2-before-after-drill-1",
    optional: true,
    level: "EN-A2",
    number: 3,
    title: "Práctica extra: before y after + -ing",
    summary: "Practica \"before\" y \"after\" con \"-ing\" o con una frase completa, y la diferencia entre \"after\" y \"after that\" al contar una historia.",
    duration: "10 min",
    sections: [
      {
        heading: "Repaso rápido: «antes de» y «después de»",
        body: [
          "«Antes de salir» = \"before leaving\" o \"before I left\". «Después de comer» = \"after eating\" o \"after we ate\". Detrás de \"before\" y \"after\" va un verbo en \"-ing\" o una frase con sujeto y verbo.",
          "Errores típicos: *after to eat, *before of leaving, *after eat. Ni \"to\" ni \"of\": solo \"before\"/\"after\" + \"-ing\".",
        ],
        examples: [
          { es: "Before leaving, I turned off the lights.", en: "Antes de salir, apagué las luces." },
          { es: "Before I left, I turned off the lights.", en: "Antes de salir, apagué las luces." },
          { es: "After eating, we watched a movie.", en: "Después de comer, vimos una película." },
          { es: "She went to bed after finishing her homework.", en: "Se acostó después de terminar los deberes." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "«Después de cenar, salimos.»",
            options: ["After having dinner, we went out.", "After to have dinner, we went out.", "After of having dinner, we went out.", "After have dinner, we went out."],
            correctIndex: 0,
            explanation: "\"After\" + \"-ing\": \"after having dinner\". Sin \"to\" ni \"of\".",
          },
        ],
      },
      {
        heading: "Repaso rápido: \"after\" o \"after that\"",
        body: [
          "\"After\" necesita algo detrás: \"after lunch\", \"after eating\", \"after I ate\". No puede ir solo al principio de una frase como «después»: *After, we went home suena incompleto.",
          "Para decir «después» / «luego» solo, usa \"after that\", \"then\" o \"afterwards\": \"We had lunch. After that, we went home.\" Para ordenar una historia: \"first\", \"then\", \"after that\", \"finally\".",
        ],
        examples: [
          { es: "We had lunch. After that, we went home.", en: "Comimos. Después, nos fuimos a casa." },
          { es: "First I showered, then I got dressed.", en: "Primero me duché y luego me vestí." },
          { es: "Finally, we arrived at the hotel.", en: "Por fin, llegamos al hotel." },
          { es: "We went for a walk afterwards.", en: "Después fuimos a dar un paseo." },
        ],
        checkpoint: [
          {
            type: "fill-blank",
            prompt: "Escribe en inglés las palabras en negrita.",
            sentence: "We visited the museum. ___, we had coffee.",
            answer: "After that",
            altAnswers: ["Then", "Afterwards", "Afterward", "Later"],
            en: "Visitamos el museo. [Después], tomamos un café.",
            explanation: "«Después» sin nada detrás = \"After that\" o \"Then\". \"After\" solo necesita un complemento.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Me lavé los dientes antes de acostarme.",
        answer: "I brushed my teeth before going to bed.",
        altAnswers: ["I brushed my teeth before I went to bed.", "Before going to bed, I brushed my teeth.", "Before I went to bed, I brushed my teeth.", "I cleaned my teeth before going to bed.", "I cleaned my teeth before I went to bed."],
        explanation: "\"Before\" + \"-ing\" (\"before going\") o + frase (\"before I went\"). Nunca *before to go.",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "After ___ the email, I closed my laptop.",
        answer: "sending",
        altAnswers: ["writing"],
        en: "Después de [enviar] el correo, cerré el portátil.",
        explanation: "Detrás de \"after\" el verbo va en \"-ing\": \"sending\".",
      },
      {
        type: "multiple-choice",
        question: "Busca el error: *Before of the class, I had a coffee. ¿Cuál es correcta?",
        options: ["Before the class, I had a coffee.", "Before to the class, I had a coffee.", "Before of class, I had a coffee.", "Before that the class, I had a coffee."],
        correctIndex: 0,
        explanation: "\"Before\" + nombre, sin \"of\": \"before the class\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Después de terminar el trabajo, fuimos a un bar.",
        answer: "After finishing work, we went to a bar.",
        altAnswers: [
          "After we finished work, we went to a bar.",
          "After finishing the work, we went to a bar.",
          "After we finished the work, we went to a bar.",
          "We went to a bar after finishing work.",
          "We went to a bar after we finished work.",
          "After finishing work we went to a bar.",
          "After work, we went to a bar.",
        ],
        explanation: "\"After\" + \"-ing\" o + frase. Ojo al orden: la coma va tras la primera parte si empiezas con \"After\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Ella siempre lee antes de dormir.",
        answer: "She always reads before going to sleep.",
        altAnswers: [
          "She always reads before she goes to sleep.",
          "She always reads before sleeping.",
          "She always reads before going to bed.",
          "She always reads before she goes to bed.",
          "She always reads before bed.",
          "She always reads before bedtime.",
        ],
        explanation: "También funciona en presente: \"before going to sleep\" o \"before she goes to sleep\".",
      },
      {
        type: "multiple-choice",
        question: "¿Qué frase está bien para contar una historia?",
        options: [
          "We had dinner. After that, we went dancing.",
          "We had dinner. After, we went dancing.",
          "We had dinner. After of that, we went dancing.",
          "We had dinner. After to that, we went dancing.",
        ],
        correctIndex: 0,
        explanation: "«Después» solo, al principio de una frase = \"After that\" (o \"Then\").",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "Wash your hands ___ eating.",
        answer: "before",
        en: "Lávate las manos [antes de] comer.",
        explanation: "«Antes de» = \"before\", sin \"of\". El verbo va en \"-ing\": \"eating\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Primero, compramos los billetes. Luego, subimos al tren.",
        answer: "First, we bought the tickets. Then, we got on the train.",
        altAnswers: [
          "First, we bought the tickets. Then we got on the train.",
          "First we bought the tickets. Then we got on the train.",
          "First, we bought the tickets. After that, we got on the train.",
          "First, we bought tickets. Then, we got on the train.",
          "First, we bought the tickets. Then, we boarded the train.",
          "First we bought the tickets, then we got on the train.",
        ],
        explanation: "Conectores de secuencia: \"First\", \"Then\". «Subir al tren» = \"get on the train\" (pasado \"got on\").",
      },
      {
        type: "word-order",
        prompt: "Ordena las palabras.",
        words: ["After", "watching", "the", "news,", "he", "went", "to", "bed."],
        translation: "Después de ver las noticias, se fue a la cama.",
        altOrders: [["He", "went", "to", "bed", "after", "watching", "the", "news."]],
        explanation: "\"After\" + \"-ing\" + complemento, coma, y la frase principal en pasado.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Llamé a Carlos antes de salir de casa.",
        answer: "I called Carlos before leaving home.",
        altAnswers: [
          "I called Carlos before I left home.",
          "I called Carlos before leaving the house.",
          "I called Carlos before I left the house.",
          "Before leaving home, I called Carlos.",
          "Before I left home, I called Carlos.",
          "I phoned Carlos before leaving home.",
          "I phoned Carlos before I left home.",
        ],
        explanation: "\"Before leaving\" o \"before I left\". «Salir de casa» = \"leave home\" (sin \"of\" ni \"from\").",
      },
      {
        type: "multiple-choice",
        question: "«Después de llegar al hotel, nos duchamos.» ¿Cuál NO es correcta?",
        options: [
          "After to arrive at the hotel, we showered.",
          "After arriving at the hotel, we showered.",
          "After we arrived at the hotel, we showered.",
          "When we got to the hotel, we showered.",
        ],
        correctIndex: 0,
        explanation: "*After to arrive es el calco de «después de llegar». Lo correcto: \"after arriving\" o \"after we arrived\".",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "___, the movie ended and we all went home.",
        answer: "Finally",
        altAnswers: ["In the end", "At last", "Eventually"],
        en: "[Al final], la película terminó y todos nos fuimos a casa.",
        explanation: "Para cerrar una secuencia: \"Finally\" o \"In the end\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Después de la fiesta, ayudamos a limpiar.",
        answer: "After the party, we helped clean up.",
        altAnswers: [
          "After the party, we helped to clean up.",
          "After the party, we helped clean.",
          "After the party, we helped to clean.",
          "After the party we helped clean up.",
          "We helped clean up after the party.",
          "We helped to clean up after the party.",
        ],
        explanation: "\"After\" + nombre: \"after the party\". «Ayudar a limpiar» = \"help clean up\" o \"help to clean up\".",
      },
      {
        type: "matching",
        instructions: "Une cada expresión con su significado.",
        pairs: [
          { left: "before leaving", right: "antes de salir" },
          { left: "after leaving", right: "después de salir" },
          { left: "after that", right: "después (de eso)" },
          { left: "first", right: "primero" },
          { left: "finally", right: "por último" },
        ],
        explanation: "\"Before\"/\"after\" + \"-ing\"; \"after that\" y \"finally\" ordenan los pasos de una historia.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Antes de empezar el examen, apagamos los teléfonos.",
        answer: "Before starting the exam, we turned off our phones.",
        altAnswers: [
          "Before the exam started, we turned off our phones.",
          "Before we started the exam, we turned off our phones.",
          "Before starting the exam, we switched off our phones.",
          "Before the exam started, we switched off our phones.",
          "Before we started the exam, we switched off our phones.",
          "Before starting the test, we turned off our phones.",
          "Before the test started, we turned off our phones.",
          "We turned off our phones before the exam started.",
          "We turned off our phones before starting the exam.",
        ],
        explanation: "\"Before\" + \"-ing\" o + frase. «Apagar» = \"turn off\". En inglés se dice \"our phones\" (con posesivo), no «los».",
      },
      {
        type: "listen-choose",
        audio: "After finishing her homework, Sofia called her friend.",
        question: "¿Qué hizo Sofia primero?",
        options: ["Terminó los deberes.", "Llamó a su amiga.", "Fue a casa de su amiga.", "Empezó los deberes con su amiga."],
        correctIndex: 0,
        explanation: "\"After finishing her homework\" = primero terminó los deberes; después llamó a su amiga.",
      },
      {
        type: "dictation",
        audio: "Before going to work, I always have a cup of coffee.",
        explanation: "\"Before\" + \"-ing\": \"before going\". «Una taza de café» = \"a cup of coffee\".",
      },
    ],
  },
];
