// Synced from cheneygross-afk/lengo:src/lib/lessons/en-a2-u08-extra.ts by scripts/sync-content.mjs -- edit it there, not here.
import type { Lesson } from "./types";

// Extra practice (optional) lessons for EN-A2 unit u08.

export const EN_A2_U08_EXTRA: Lesson[] = [
  // ---------------------------------------------------------------------
  {
    slug: "en-a2-comparatives-form-drill-1",
    optional: true,
    level: "EN-A2",
    number: 1,
    title: "Práctica extra: la forma del comparativo",
    summary: "Práctica intensiva de la forma del comparativo: \"-er\" o \"more\", la ortografía (\"bigger\", \"happier\", \"nicer\") y los errores típicos *more big, *more bigger, *biger.",
    duration: "10 min",
    sections: [
      {
        heading: "Recordatorio: cortos con \"-er\", largos con \"more\"",
        body: [
          "Los adjetivos de una sílaba añaden \"-er\": \"tall, taller\", \"cheap, cheaper\". Los de dos sílabas que terminan en \"-y\" cambian la \"-y\" por \"-ier\": \"happy, happier\", \"easy, easier\". Los demás adjetivos largos van con \"more\": \"more expensive\", \"more interesting\".",
          "Nunca se usan las dos cosas a la vez: *more bigger y *more easier no existen. Y «más grande» no es *more big: el adjetivo corto siempre lleva \"-er\".",
        ],
        examples: [
          { es: "My new phone is bigger.", en: "Mi teléfono nuevo es más grande. (incorrecto: *more big)" },
          { es: "This exercise is easier.", en: "Este ejercicio es más fácil. (incorrecto: *more easy)" },
          { es: "The train is more expensive.", en: "El tren es más caro." },
          { es: "Her new job is more interesting.", en: "Su nuevo trabajo es más interesante." },
          { es: "Today is colder than yesterday.", en: "Hoy hace más frío que ayer." },
        ],
        checkpoint: [
          {
            type: "fill-blank",
            prompt: "Escribe en inglés las palabras en negrita.",
            sentence: "Your phone is ___ than mine.",
            answer: "more modern",
            en: "Tu teléfono es [más moderno] que el mío.",
            explanation: "\"Modern\" tiene dos sílabas y no termina en \"-y\", así que va con \"more\": \"more modern\".",
          },
          {
            type: "multiple-choice",
            question: "«Esta calle es más larga.» ¿Cuál es correcta?",
            options: ["This street is longer.", "This street is more long.", "This street is more longer.", "This street is longest."],
            correctIndex: 0,
            explanation: "\"Long\" es corto: \"longer\". Ni *more long ni *more longer.",
          },
        ],
      },
      {
        heading: "Recordatorio: la ortografía de \"-er\"",
        body: [
          "Si el adjetivo termina en consonante-vocal-consonante, se duplica la última letra: \"big, bigger\", \"hot, hotter\", \"thin, thinner\". Si termina en \"-e\", solo se añade \"-r\": \"nice, nicer\", \"large, larger\". Si termina en \"-y\", se escribe \"-ier\": \"busy, busier\", \"early, earlier\".",
        ],
        examples: [
          { es: "It's hotter in August.", en: "Hace más calor en agosto." },
          { es: "She's thinner than before.", en: "Está más delgada que antes." },
          { es: "This hotel is nicer.", en: "Este hotel es más bonito." },
          { es: "I'm busier on Mondays.", en: "Estoy más ocupado los lunes." },
        ],
        checkpoint: [
          {
            type: "fill-blank",
            prompt: "Escribe en inglés las palabras en negrita.",
            sentence: "Today is ___ than yesterday.",
            answer: "hotter",
            en: "Hoy hace [más calor] que ayer.",
            explanation: "\"Hot\" termina en consonante-vocal-consonante, así que la \"t\" se duplica: \"hotter\", no *hoter.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "My new apartment is ___ than the old one.",
        answer: "bigger",
        altAnswers: ["larger"],
        en: "Mi apartamento nuevo es [más grande] que el viejo.",
        explanation: "\"Big\" duplica la \"g\": \"bigger\". Nunca *more big ni *biger.",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "This series is ___ than the book.",
        answer: "more interesting",
        en: "Esta serie es [más interesante] que el libro.",
        explanation: "\"Interesting\" es largo, así que va con \"more\". No existe *interestinger.",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "Lucia is ___ than her sister.",
        answer: "happier",
        en: "Lucia es [más feliz] que su hermana.",
        explanation: "\"Happy\" termina en \"-y\": la \"-y\" se convierte en \"-ier\". No digas *more happy ni *happyer.",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "The train is ___ than the bus.",
        answer: "more expensive",
        en: "El tren es [más caro] que el autobús.",
        explanation: "\"Expensive\" tiene tres sílabas: \"more expensive\". Nunca *expensiver.",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "The test was ___ than I expected.",
        answer: "easier",
        en: "El examen fue [más fácil] de lo que esperaba.",
        explanation: "\"Easy\" es de dos sílabas y termina en \"-y\": \"easier\". *More easy es un error muy común.",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "This bag is ___ than that one.",
        answer: "lighter",
        en: "Esta bolsa es [más ligera] que esa.",
        explanation: "\"Light\" es corto: \"lighter\". La \"gh\" no se pronuncia.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Mi habitación es más pequeña que la tuya.",
        answer: "My room is smaller than yours.",
        altAnswers: ["My bedroom is smaller than yours."],
        explanation: "\"Small\" es corto: \"smaller\". «La tuya» es \"yours\", sin artículo.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Este ejercicio es más difícil que el anterior.",
        answer: "This exercise is more difficult than the previous one.",
        altAnswers: ["This exercise is harder than the previous one.", "This exercise is more difficult than the last one.", "This exercise is harder than the last one.", "This exercise is more difficult than the one before.", "This exercise is harder than the one before."],
        explanation: "\"Difficult\" es largo: \"more difficult\". También puedes decir \"harder\". «El anterior» es \"the previous one\" o \"the last one\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Mi abuela está más ocupada que yo.",
        answer: "My grandmother is busier than me.",
        altAnswers: ["My grandmother is busier than I am.", "My grandma is busier than me.", "My grandma is busier than I am."],
        explanation: "\"Busy\" termina en \"-y\": \"busier\". Después de \"than\" se usa \"me\" (o \"I am\"), (\"than I\" solo suena muy formal).",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Este sofá es más cómodo.",
        answer: "This sofa is more comfortable.",
        altAnswers: ["This couch is more comfortable."],
        explanation: "\"Comfortable\" es largo: \"more comfortable\". Fíjate en la ortografía: \"-table\", no *-tible.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Mi hermano es más delgado que yo.",
        answer: "My brother is thinner than me.",
        altAnswers: ["My brother is thinner than I am.", "My brother is slimmer than me.", "My brother is slimmer than I am."],
        explanation: "\"Thin\" duplica la \"n\": \"thinner\". Una sola \"n\" (*thiner) es un error de ortografía.",
      },
      {
        type: "multiple-choice",
        question: "«Este auto es más grande.» ¿Cuál está bien escrita?",
        options: ["This car is bigger.", "This car is biger.", "This car is more big.", "This car is more bigger."],
        correctIndex: 0,
        explanation: "\"Big\" duplica la consonante final: \"bigger\". *More big y *more bigger son calcos del español.",
      },
      {
        type: "multiple-choice",
        question: "¿Cuál es correcta?",
        options: ["She's happier now.", "She's happyer now.", "She's more happier now.", "She's happiest now."],
        correctIndex: 0,
        explanation: "La \"-y\" se convierte en \"-ier\": \"happier\". \"Happiest\" es el superlativo, no el comparativo.",
      },
      {
        type: "multiple-choice",
        question: "¿Qué frase tiene un error?",
        options: ["This hotel is expensiver.", "This hotel is more expensive.", "This hotel is cheaper.", "This hotel is nicer."],
        correctIndex: 0,
        explanation: "\"Expensive\" es largo y va con \"more\": *expensiver no existe. \"Cheaper\" y \"nicer\" son correctos.",
      },
      {
        type: "matching",
        instructions: "Une cada adjetivo con su comparativo.",
        pairs: [
          { left: "thin", right: "thinner" },
          { left: "early", right: "earlier" },
          { left: "large", right: "larger" },
          { left: "dangerous", right: "more dangerous" },
        ],
        explanation: "\"Thin\" duplica la \"n\", \"early\" cambia la \"-y\" por \"-ier\", \"large\" solo añade \"-r\", y \"dangerous\" es largo y va con \"more\".",
      },
      {
        type: "listen-choose",
        audio: "My brother is taller than me.",
        question: "¿Qué significa lo que has oído?",
        options: ["Mi hermano es más alto que yo.", "Mi hermano es tan alto como yo.", "Mi hermano es el más alto.", "Mi madre es más alta que yo."],
        correctIndex: 0,
        explanation: "\"Taller than me\" es «más alto que yo». \"Brother\" es «hermano», no «madre».",
      },
      {
        type: "dictation",
        audio: "This one is cheaper and lighter.",
        explanation: "Dos comparativos cortos con \"-er\": \"cheaper\" y \"lighter\". «Este» es \"this one\".",
      },
    ],
  },
  // ---------------------------------------------------------------------
  {
    slug: "en-a2-comparative-than-drill-1",
    optional: true,
    level: "EN-A2",
    number: 2,
    title: "Práctica extra: más... que = ...er than",
    summary: "Frases completas con comparativo: \"than\" (nunca *that ni *as), \"than me\" / \"than him\", y \"much\" o \"a bit\" delante del comparativo. Errores típicos: *more tall that, *more better, *than I.",
    duration: "10 min",
    sections: [
      {
        heading: "Recordatorio: «que» es \"than\", y después va \"me\"",
        body: [
          "En una comparación, «que» siempre es \"than\": \"taller than\", \"more expensive than\". No es *that ni *as. Después de \"than\" se usa el pronombre de objeto: \"than me\", \"than him\", \"than her\", \"than us\", \"than them\". *Taller than I suena antiguo; si quieres, di \"taller than I am\".",
          "El sujeto nunca se omite y el verbo \"be\" tampoco: \"She is taller than me\", no *Is more tall that me.",
        ],
        examples: [
          { es: "She is taller than me.", en: "Ella es más alta que yo." },
          { es: "You're older than him.", en: "Eres mayor que él." },
          { es: "They work harder than us.", en: "Trabajan más que nosotros." },
          { es: "My car is faster than yours.", en: "Mi carro es más rápido que el tuyo." },
          { es: "Is the train cheaper than the bus?", en: "¿Es el tren más barato que el autobús?" },
        ],
        checkpoint: [
          {
            type: "fill-blank",
            prompt: "Escribe en inglés las palabras en negrita.",
            sentence: "Sofia is taller ___ her brother.",
            answer: "than",
            en: "Sofia es más alta [que] su hermano.",
            explanation: "«Que» en una comparación es \"than\". *Taller that es un calco del español.",
          },
          {
            type: "fill-blank",
            prompt: "Escribe en inglés las palabras en negrita.",
            sentence: "They work harder than ___.",
            answer: "us",
            altAnswers: ["we do"],
            en: "Trabajan más que [nosotros].",
            explanation: "Después de \"than\" va el pronombre de objeto: \"than us\". *Than we solo suena antiguo.",
          },
        ],
      },
      {
        heading: "Recordatorio: \"much\" y \"a bit\" delante del comparativo",
        body: [
          "«Mucho más» es \"much\" o \"a lot\" + comparativo: \"much taller\", \"a lot more expensive\". «Un poco más» es \"a bit\" o \"a little\" + comparativo: \"a bit older\", \"a little cheaper\".",
          "«Mucho mejor» es \"much better\": nunca *very better ni *more better. «Mucho peor» es \"much worse\".",
        ],
        examples: [
          { es: "This one is much better.", en: "Este es mucho mejor. (incorrecto: *more better, *very better)" },
          { es: "Her house is a lot bigger than mine.", en: "Su casa es mucho más grande que la mía." },
          { es: "I'm a bit older than you.", en: "Soy un poco mayor que tú." },
          { es: "The hotel was a little more expensive.", en: "El hotel fue un poco más caro." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "¿Cómo se dice «mucho mejor»?",
            options: ["much better", "very better", "more better", "much more good"],
            correctIndex: 0,
            explanation: "\"Better\" ya es comparativo y se refuerza con \"much\" o \"a lot\". \"Very\" solo va con el adjetivo normal (\"very good\").",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Ella es mucho más alta que yo.",
        answer: "She is much taller than me.",
        altAnswers: ["She is a lot taller than me.", "She is much taller than I am.", "She is a lot taller than I am."],
        explanation: "«Mucho más» es \"much\" o \"a lot\" + comparativo. Después de \"than\", \"me\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Tu teléfono es un poco más caro que el mío.",
        answer: "Your phone is a bit more expensive than mine.",
        altAnswers: ["Your phone is a little more expensive than mine.", "Your phone is slightly more expensive than mine."],
        explanation: "«Un poco más» es \"a bit\" o \"a little\" + comparativo. «El mío» es \"mine\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Carlos corre más rápido que nosotros.",
        answer: "Carlos runs faster than us.",
        altAnswers: ["Carlos runs faster than we do.", "Carlos runs quicker than us."],
        explanation: "\"Faster\" es el comparativo de \"fast\" (adjetivo y adverbio). Después de \"than\", \"us\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Tus hijos son mayores que los míos.",
        answer: "Your children are older than mine.",
        altAnswers: ["Your kids are older than mine."],
        explanation: "«Mayor» de edad es \"older\". «Los míos» es \"mine\", sin artículo ni plural.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Esta película es mucho mejor que la otra.",
        answer: "This movie is much better than the other one.",
        altAnswers: ["This film is much better than the other one.", "This movie is a lot better than the other one.", "This film is a lot better than the other one.", "This movie is much better than the other.", "This film is much better than the other."],
        explanation: "«Mucho mejor» es \"much better\" o \"a lot better\". *More better y *very better son errores.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Él es más joven que ella.",
        answer: "He is younger than her.",
        altAnswers: ["He is younger than she is."],
        explanation: "Después de \"than\" va \"her\", no *she. \"Than she is\" también es correcto.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Mi jefe es mucho más simpático que el tuyo.",
        answer: "My boss is much nicer than yours.",
        altAnswers: ["My boss is a lot nicer than yours.", "My boss is much friendlier than yours.", "My boss is a lot friendlier than yours.", "My boss is much kinder than yours."],
        explanation: "«Simpático» es \"nice\" (o \"friendly\"), no \"sympathetic\". «El tuyo» es \"yours\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Hoy estoy un poco más cansada que ayer.",
        answer: "I'm a bit more tired than yesterday.",
        altAnswers: ["I'm a little more tired than yesterday.", "Today I'm a bit more tired than yesterday.", "Today I'm a little more tired than yesterday.", "I'm a bit more tired today than yesterday.", "I'm a little more tired today than yesterday."],
        explanation: "\"Tired\" va con \"more\": \"more tired\". «Un poco» es \"a bit\" o \"a little\".",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "This road is much ___ than the highway.",
        answer: "more dangerous",
        en: "Esta carretera es mucho [más peligrosa] que la autopista.",
        explanation: "\"Dangerous\" es largo: \"more dangerous\". \"Much\" va delante de todo el comparativo.",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "The second test was a bit ___ than the first.",
        answer: "harder",
        altAnswers: ["more difficult"],
        en: "El segundo examen fue un poco [más difícil] que el primero.",
        explanation: "\"Harder\" o \"more difficult\"; nunca *more harder.",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "My cousin is three years older than ___.",
        answer: "me",
        altAnswers: ["I am"],
        en: "Mi primo es tres años mayor que [yo].",
        explanation: "Después de \"than\", el pronombre de objeto: \"than me\". Fíjate en \"three years older\": los años van delante del comparativo.",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "The weather here is ___ than in my country.",
        answer: "much worse",
        altAnswers: ["a lot worse"],
        en: "El tiempo aquí es [mucho peor] que en mi país.",
        explanation: "«Mucho peor» es \"much worse\" o \"a lot worse\". *More worse y *very worse son errores.",
      },
      {
        type: "multiple-choice",
        question: "«Es más alto que yo.» ¿Cuál es correcta?",
        options: ["He's taller than me.", "He's taller that me.", "He's taller as me.", "He's more taller than me."],
        correctIndex: 0,
        explanation: "«Que» es \"than\"; *that y *as no sirven aquí. Y \"taller\" no lleva \"more\".",
      },
      {
        type: "multiple-choice",
        question: "¿Cómo se dice «un poco más barato»?",
        options: ["a bit cheaper", "a little more cheap", "a bit more cheaper", "little cheaper"],
        correctIndex: 0,
        explanation: "\"A bit\" o \"a little\" + comparativo: \"a bit cheaper\". *More cheap y *more cheaper son errores.",
      },
      {
        type: "word-order",
        prompt: "Ordena las palabras.",
        words: ["My", "sister", "is", "much", "older", "than", "me"],
        translation: "Mi hermana es mucho mayor que yo.",
        explanation: "Sujeto + \"be\" + \"much\" + comparativo + \"than\" + pronombre de objeto.",
      },
      {
        type: "listen-choose",
        audio: "It's a lot colder than I thought.",
        question: "¿Qué significa lo que has oído?",
        options: ["Hace mucho más frío de lo que pensaba.", "Hace un poco más de frío de lo que pensaba.", "Hace tanto frío como pensaba.", "No hace tanto frío como pensaba."],
        correctIndex: 0,
        explanation: "\"A lot colder\" es «mucho más frío», y \"than I thought\" es «de lo que pensaba».",
      },
      {
        type: "dictation",
        audio: "She's a bit taller than him.",
        explanation: "\"A bit\" + \"taller\" + \"than him\". Después de \"than\" se oye \"him\", no \"he\".",
      },
    ],
  },
  // ---------------------------------------------------------------------
  {
    slug: "en-a2-superlatives-drill-1",
    optional: true,
    level: "EN-A2",
    number: 3,
    title: "Práctica extra: el superlativo",
    summary: "Práctica intensiva del superlativo: \"the\" + \"-est\" o \"the most\", y «del mundo» como \"in the world\" frente a «de mi vida» como \"of my life\". Errores típicos: *the most big, *the better of the world, el \"the\" olvidado.",
    duration: "10 min",
    sections: [
      {
        heading: "Recordatorio: \"the\" + \"-est\" o \"the most\"",
        body: [
          "El superlativo siempre lleva \"the\": \"the tallest\", \"the most expensive\". Los adjetivos cortos añaden \"-est\" (\"the biggest\", \"the happiest\", \"the nicest\") y los largos van con \"the most\" (\"the most beautiful\"). Los irregulares: \"the best\", \"the worst\", \"the farthest\".",
          "Dos errores típicos: olvidar \"the\" (*She is tallest) y mezclar el comparativo con el superlativo (*the better, *the more big).",
        ],
        examples: [
          { es: "He's the tallest in the class.", en: "Es el más alto de la clase." },
          { es: "It's the most expensive hotel in town.", en: "Es el hotel más caro de la ciudad." },
          { es: "That was the best day.", en: "Ese fue el mejor día. (incorrecto: *the better day)" },
          { es: "It's the biggest city in the country.", en: "Es la ciudad más grande del país." },
          { es: "She's the happiest person I know.", en: "Es la persona más feliz que conozco." },
        ],
        checkpoint: [
          {
            type: "fill-blank",
            prompt: "Escribe en inglés las palabras en negrita.",
            sentence: "She's ___ student in the class.",
            answer: "the best",
            en: "Es [la mejor] estudiante de la clase.",
            explanation: "El superlativo de \"good\" es \"the best\". *The better es el comparativo.",
          },
          {
            type: "multiple-choice",
            question: "«Es el edificio más antiguo de la ciudad.» ¿Cuál es correcta?",
            options: ["It's the oldest building in the city.", "It's the most old building of the city.", "It's the older building in the city.", "It's oldest building in the city."],
            correctIndex: 0,
            explanation: "\"Old\" es corto: \"the oldest\". El \"the\" es obligatorio, y «de la ciudad» es \"in the city\".",
          },
        ],
      },
      {
        heading: "Recordatorio: «de» es \"in\" con lugares y grupos, \"of\" con periodos",
        body: [
          "Después de un superlativo, «del mundo», «de la clase», «de mi familia» se dicen con \"in\": \"the best in the world\", \"the tallest in the class\", \"the youngest in my family\".",
          "Con periodos de tiempo y números, se usa \"of\": \"the best day of my life\", \"the hottest month of the year\", \"the oldest of the three\".",
        ],
        examples: [
          { es: "It's the best restaurant in the world.", en: "Es el mejor restaurante del mundo. (incorrecto: *of the world)" },
          { es: "He's the youngest in my family.", en: "Es el más joven de mi familia." },
          { es: "It was the worst day of my life.", en: "Fue el peor día de mi vida." },
          { es: "July is the hottest month of the year.", en: "Julio es el mes más caluroso del año." },
        ],
        checkpoint: [
          {
            type: "fill-blank",
            prompt: "Escribe en inglés las palabras en negrita.",
            sentence: "He's the tallest player ___ the team.",
            answer: "in",
            altAnswers: ["on"],
            en: "Es el jugador más alto [del] equipo.",
            explanation: "«Del equipo» es un grupo: \"in the team\" (también \"on the team\" en Estados Unidos). No *of the team.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "It's ___ city in the country.",
        answer: "the biggest",
        altAnswers: ["the largest"],
        en: "Es [la] ciudad [más grande] del país.",
        explanation: "\"Big\" duplica la \"g\": \"the biggest\". *The most big es un calco del español.",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "This is ___ restaurant in town.",
        answer: "the most expensive",
        en: "Este es [el] restaurante [más caro] de la ciudad.",
        explanation: "\"Expensive\" es largo: \"the most expensive\". Nunca *the expensivest.",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "It was the coldest day ___ the year.",
        answer: "of",
        en: "Fue el día más frío [del] año.",
        explanation: "Con periodos de tiempo (\"the year\", \"my life\") se usa \"of\".",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "Who is ___ person in your family?",
        answer: "the youngest",
        en: "¿Quién es [la] persona [más joven] de tu familia?",
        explanation: "\"Young\" es corto: \"the youngest\". No olvides el \"the\".",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "This is ___ exercise in the book.",
        answer: "the easiest",
        en: "Este es [el] ejercicio [más fácil] del libro.",
        explanation: "\"Easy\" cambia la \"-y\" por \"-iest\": \"the easiest\". *The most easy es un error.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Es la montaña más alta de Sudamérica.",
        answer: "It's the highest mountain in South America.",
        altAnswers: ["It's the tallest mountain in South America."],
        explanation: "«De Sudamérica» es un lugar: \"in South America\". Las montañas son \"high\" (o \"tall\").",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Fue la peor semana de mi vida.",
        answer: "It was the worst week of my life.",
        explanation: "El superlativo de \"bad\" es \"the worst\". «De mi vida» es \"of my life\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Mi hermano es el más listo de la familia.",
        answer: "My brother is the smartest in the family.",
        altAnswers: ["My brother is the cleverest in the family.", "My brother is the most intelligent in the family.", "My brother is the smartest one in the family.", "My brother is the smartest person in the family.", "My brother is the cleverest one in the family.", "My brother is the most intelligent one in the family."],
        explanation: "«De la familia» es un grupo: \"in the family\". \"Smart\" es corto: \"the smartest\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Es el hotel más famoso de la ciudad.",
        answer: "It's the most famous hotel in the city.",
        altAnswers: ["It's the most famous hotel in town."],
        explanation: "\"Famous\" es largo: \"the most famous\". «De la ciudad» es \"in the city\" o \"in town\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Es el día más importante del año.",
        answer: "It's the most important day of the year.",
        explanation: "«Del año» es un periodo: \"of the year\". \"Important\" va con \"the most\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "¿Cuál es el río más largo del mundo?",
        answer: "What is the longest river in the world?",
        altAnswers: ["Which is the longest river in the world?", "What's the longest river in the world?", "Which one is the longest river in the world?"],
        explanation: "«Del mundo» es \"in the world\", nunca *of the world. \"Long\" es corto: \"the longest\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Lucia es la más simpática de mis amigas.",
        answer: "Lucia is the nicest of my friends.",
        altAnswers: ["Lucia is the friendliest of my friends.", "Lucia is the kindest of my friends.", "Lucia is the nicest one of my friends."],
        explanation: "Con un grupo de personas concretas (\"my friends\", \"the three\") se usa \"of\". \"Nice\" solo añade \"-st\": \"the nicest\".",
      },
      {
        type: "multiple-choice",
        question: "«Es el mejor del mundo.» ¿Cuál es correcta?",
        options: ["He's the best in the world.", "He's the better of the world.", "He's the best of the world.", "He's the most good in the world."],
        correctIndex: 0,
        explanation: "Superlativo \"the best\" + \"in the world\". *The better es comparativo y *of the world es un calco.",
      },
      {
        type: "multiple-choice",
        question: "¿Cuál está bien escrita?",
        options: ["It was the hottest day of the year.", "It was the hotest day of the year.", "It was the most hot day of the year.", "It was the hottest day in the year."],
        correctIndex: 0,
        explanation: "\"Hot\" duplica la \"t\": \"the hottest\". Con \"the year\" se usa \"of\".",
      },
      {
        type: "multiple-choice",
        question: "¿Qué frase tiene un error?",
        options: ["She is tallest girl in the class.", "She is the tallest girl in the class.", "She is taller than her sister.", "She is the most popular girl in the class."],
        correctIndex: 0,
        explanation: "El superlativo siempre lleva \"the\": \"the tallest girl\". Las otras tres son correctas.",
      },
      {
        type: "matching",
        instructions: "Une cada frase con su significado.",
        pairs: [
          { left: "the best in the world", right: "el mejor del mundo" },
          { left: "the best of my life", right: "el mejor de mi vida" },
          { left: "the oldest in the family", right: "el mayor de la familia" },
          { left: "the oldest of the three", right: "el mayor de los tres" },
        ],
        explanation: "Lugares y grupos van con \"in\" (\"in the world\", \"in the family\"); periodos y números van con \"of\" (\"of my life\", \"of the three\").",
      },
      {
        type: "listen-choose",
        audio: "It's the most beautiful beach I've ever seen.",
        question: "¿Qué significa lo que has oído?",
        options: ["Es la playa más bonita que he visto en mi vida.", "Es una playa más bonita que la que vi.", "Es la playa más grande que he visto.", "Es tan bonita como la playa que vi."],
        correctIndex: 0,
        explanation: "\"The most beautiful\" es superlativo, y \"I've ever seen\" es «que he visto en mi vida».",
      },
      {
        type: "dictation",
        audio: "This is the cheapest hotel in the city.",
        explanation: "\"The cheapest\" + \"in the city\": lugar, así que \"in\".",
      },
    ],
  },
  // ---------------------------------------------------------------------
  {
    slug: "en-a2-as-as-drill-1",
    optional: true,
    level: "EN-A2",
    number: 4,
    title: "Práctica extra: as... as",
    summary: "Práctica intensiva de \"as... as\", \"not as... as\", \"the same as\" y \"different from\". Errores típicos: *as tall than, *so tall as en afirmativas, *the same that, *different of.",
    duration: "10 min",
    sections: [
      {
        heading: "Recordatorio: «tan... como» es \"as... as\"",
        body: [
          "«Tan alto como» es \"as tall as\": las dos palabras son \"as\". No es *as tall than ni *as tall like. En afirmativas tampoco se usa *so tall as; \"so\" solo aparece a veces en negativas (\"not so tall as\"), pero \"not as... as\" es lo más común.",
          "«No tan... como» es \"not as... as\": \"My car isn't as fast as yours\". Significa lo mismo que «menos... que».",
        ],
        examples: [
          { es: "My brother is as tall as my father.", en: "Mi hermano es tan alto como mi padre. (incorrecto: *as tall than)" },
          { es: "This exam was as hard as the last one.", en: "Este examen fue tan difícil como el anterior." },
          { es: "She isn't as old as me.", en: "Ella no es tan mayor como yo." },
          { es: "It's not as cold as yesterday.", en: "No hace tanto frío como ayer." },
          { es: "Your English is as good as mine.", en: "Tu inglés es tan bueno como el mío." },
        ],
        checkpoint: [
          {
            type: "fill-blank",
            prompt: "Escribe en inglés las palabras en negrita.",
            sentence: "She's as tall ___ her mother.",
            answer: "as",
            en: "Es tan alta [como] su madre.",
            explanation: "Con \"as\" delante del adjetivo, «como» es otra vez \"as\", nunca *than ni *like.",
          },
          {
            type: "multiple-choice",
            question: "«Soy tan alto como tú.» ¿Cuál es correcta?",
            options: ["I'm as tall as you.", "I'm as tall than you.", "I'm so tall as you.", "I'm as tall like you."],
            correctIndex: 0,
            explanation: "\"As\" + adjetivo + \"as\". *So tall as no se usa en afirmativas y *than va solo con comparativos.",
          },
        ],
      },
      {
        heading: "Recordatorio: \"the same as\" y \"different from\"",
        body: [
          "«Igual que», «lo mismo que», «la misma... que» es \"the same as\": \"the same as mine\", \"the same age as me\". No es *the same that ni *the same than.",
          "«Diferente de» es \"different from\" (en Estados Unidos también se oye \"different than\"). Nunca *different of.",
        ],
        examples: [
          { es: "Your bag is the same as mine.", en: "Tu bolso es igual que el mío. (incorrecto: *the same that)" },
          { es: "We're the same age.", en: "Tenemos la misma edad." },
          { es: "My job is different from yours.", en: "Mi trabajo es diferente del tuyo. (incorrecto: *different of)" },
          { es: "Life here is very different from life in Lima.", en: "La vida aquí es muy diferente de la vida en Lima." },
        ],
        checkpoint: [
          {
            type: "fill-blank",
            prompt: "Escribe en inglés las palabras en negrita.",
            sentence: "My phone is the same ___ yours.",
            answer: "as",
            en: "Mi teléfono es igual [que] el tuyo.",
            explanation: "\"The same\" siempre va con \"as\": *the same that es un calco del español.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Mi hermana es tan alta como mi madre.",
        answer: "My sister is as tall as my mother.",
        altAnswers: ["My sister is as tall as my mom."],
        explanation: "\"As tall as\": las dos palabras son \"as\". No uses *than.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Este libro no es tan bueno como el otro.",
        answer: "This book isn't as good as the other one.",
        altAnswers: ["This book isn't as good as the other.", "This book is not as good as the other one."],
        explanation: "«No tan... como» es \"not as... as\". «El otro» es \"the other one\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Tengo la misma camisa que tú.",
        answer: "I have the same shirt as you.",
        altAnswers: ["I've got the same shirt as you."],
        explanation: "\"The same\" + sustantivo + \"as\": \"the same shirt as you\". *The same shirt that you es un error.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Tu ciudad es muy diferente de la mía.",
        answer: "Your city is very different from mine.",
        altAnswers: ["Your city is really different from mine.", "Your city is very different than mine."],
        explanation: "«Diferente de» es \"different from\". *Different of no existe.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Ella no es tan alta como yo.",
        answer: "She isn't as tall as me.",
        altAnswers: ["She isn't as tall as I am.", "She is not as tall as me."],
        explanation: "\"Not as tall as\" + \"me\". Después del segundo \"as\" se usa el pronombre de objeto.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Mi bici es tan rápida como tu carro.",
        answer: "My bike is as fast as your car.",
        altAnswers: ["My bicycle is as fast as your car.", "My bike is as quick as your car."],
        explanation: "\"As fast as\": en afirmativa nunca *so fast as.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Mi trabajo no es tan interesante como el tuyo.",
        answer: "My job isn't as interesting as yours.",
        altAnswers: ["My job is not as interesting as yours.", "My work isn't as interesting as yours."],
        explanation: "\"Not as interesting as\" + \"yours\". Con \"as... as\" el adjetivo no cambia: no lleva \"-er\" ni \"more\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Su casa es igual que la nuestra.",
        answer: "Their house is the same as ours.",
        altAnswers: ["His house is the same as ours.", "Her house is the same as ours."],
        explanation: "«Igual que» es \"the same as\". «La nuestra» es \"ours\".",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "He isn't ___ as his brother.",
        answer: "as strong",
        en: "No es [tan fuerte] como su hermano.",
        explanation: "«Tan fuerte» es \"as strong\"; el segundo \"as\" ya está en la frase.",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "Is English very different ___ Spanish?",
        answer: "from",
        altAnswers: ["than"],
        en: "¿Es el inglés muy diferente [del] español?",
        explanation: "\"Different from\" (o \"different than\" en Estados Unidos). Nunca *different of.",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "My car is older than yours. = Your car isn't ___ mine.",
        answer: "as old as",
        en: "Mi auto es más viejo que el tuyo. = Tu auto no es [tan viejo como] el mío.",
        explanation: "\"Older than\" se puede decir al revés con \"not as old as\". Fíjate: con \"as... as\" se usa \"old\", no \"older\".",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "The bus is slower than the train. = The bus isn't ___ the train.",
        answer: "as fast as",
        altAnswers: ["as quick as"],
        en: "El autobús es más lento que el tren. = El autobús no es [tan rápido como] el tren.",
        explanation: "«Más lento que» equivale a «no tan rápido como»: \"not as fast as\".",
      },
      {
        type: "multiple-choice",
        question: "«Es diferente de la mía.» ¿Cuál es correcta?",
        options: ["It's different from mine.", "It's different of mine.", "It's different that mine.", "It's different as mine."],
        correctIndex: 0,
        explanation: "\"Different from\" es la forma estándar. *Different of es un calco de «diferente de».",
      },
      {
        type: "multiple-choice",
        question: "«Tengo la misma edad que tú.» ¿Cuál es correcta?",
        options: ["I'm the same age as you.", "I have the same age that you.", "I'm the same age than you.", "I have the same age as you."],
        correctIndex: 0,
        explanation: "La edad va con \"to be\" y \"the same\" va con \"as\": \"I'm the same age as you\".",
      },
      {
        type: "multiple-choice",
        question: "¿Qué frase tiene un error?",
        options: ["This room is as big than mine.", "This room is as big as mine.", "This room isn't as big as mine.", "This room is bigger than mine."],
        correctIndex: 0,
        explanation: "\"As big\" pide otro \"as\", no \"than\". \"Than\" solo va con comparativos (\"bigger than\").",
      },
      {
        type: "matching",
        instructions: "Une cada frase con su significado.",
        pairs: [
          { left: "as cheap as", right: "tan barato como" },
          { left: "not as cheap as", right: "no tan barato como" },
          { left: "the same price as", right: "el mismo precio que" },
          { left: "different from", right: "diferente de" },
        ],
        explanation: "\"As... as\" para la igualdad, \"not as... as\" para la desigualdad, \"the same as\" y \"different from\" para parecidos y diferencias.",
      },
      {
        type: "listen-choose",
        audio: "Your bag is the same as mine.",
        question: "¿Qué significa lo que has oído?",
        options: ["Tu bolso es igual que el mío.", "Tu bolso es diferente del mío.", "Tu bolso es más grande que el mío.", "Tu bolso es tan caro como el mío."],
        correctIndex: 0,
        explanation: "\"The same as mine\" es «igual que el mío».",
      },
      {
        type: "dictation",
        audio: "It's not as cold as yesterday.",
        altAnswers: ["It isn't as cold as yesterday."],
        explanation: "\"Not as cold as\": no hace tanto frío como ayer. Las dos palabras son \"as\".",
      },
    ],
  },
];
