// Synced from cheneygross-afk/lengo:src/lib/lessons/en-a2-u01.ts by scripts/sync-content.mjs -- edit it there, not here.
import type { Lesson } from "./types";

// English for Spanish speakers, A2 · El pasado simple (see en-a1.ts for the
// authoring conventions).
export const EN_A2_U01: Lesson[] = [
  // ---------------------------------------------------------------------
  {
    slug: "a2-was-were",
    level: "EN-A2",
    number: 1,
    title: "Was y were: el pasado de to be",
    summary: "El pasado de \"to be\": \"I was tired\", \"they were at home\", las negativas \"wasn't\" y \"weren't\", las preguntas y \"there was\" / \"there were\" para «había».",
    duration: "10 min",
    sections: [
      {
        heading: "Dos formas para todo: \"was\" y \"were\"",
        body: [
          "En A1 aprendiste \"am\", \"is\" y \"are\". En pasado solo hay dos formas: \"was\" para \"I\", \"he\", \"she\" e \"it\", y \"were\" para \"you\", \"we\" y \"they\".",
          "Una sola palabra inglesa cubre «era», «estaba», «fue» y «estuvo»: \"I was tired\" es «estaba cansado», y \"It was a good day\" es «fue un buen día». No tienes que elegir entre ser y estar, ni entre imperfecto e indefinido.",
          "Recuerda que \"you\" siempre va con \"were\", aunque hables con una sola persona: \"You were late\", nunca *You was late.",
        ],
        examples: [
          { es: "I was tired.", en: "Estaba cansado. / Estaba cansada." },
          { es: "She was a teacher.", en: "Era profesora." },
          { es: "It was a good day.", en: "Fue un buen día." },
          { es: "We were at home.", en: "Estábamos en casa." },
          { es: "You were late.", en: "Llegaste tarde. (Estabas atrasado.)" },
          { es: "They were in Mexico last year.", en: "Estuvieron en México el año pasado." },
        ],
        checkpoint: [
          {
            type: "fill-blank",
            prompt: "Escribe en inglés las palabras en negrita.",
            sentence: "We ___ at home.",
            answer: "were",
            en: "[Estábamos] en casa.",
            explanation: "\"We\", \"you\" y \"they\" van con \"were\". \"Was\" es para \"I\", \"he\", \"she\" e \"it\".",
          },
          {
            type: "translate",
            direction: "es-en",
            prompt: "Traduce al inglés.",
            source: "Ella era profesora.",
            answer: "She was a teacher.",
            explanation: "«Era» y «estaba» se dicen igual: \"was\". Y las profesiones llevan \"a\": \"a teacher\".",
          },
        ],
      },
      {
        heading: "La edad, el hambre y el frío: \"was\", no \"had\"",
        body: [
          "Igual que en presente se dice \"I am 30\" y no *I have 30 years, en pasado la edad va con \"was\": \"I was 10\" («tenía diez años»). Decir *I had 10 years es uno de los errores más típicos.",
          "Lo mismo pasa con las sensaciones que en español van con «tener»: «tenía hambre» es \"I was hungry\", «teníamos frío» es \"We were cold\", «tenía miedo» es \"I was scared\".",
          "Y no olvides el sujeto. «Hacía mucho frío» es \"It was very cold\", con \"it\". *Was very cold sin sujeto no es correcto.",
        ],
        examples: [
          { es: "I was ten in that photo.", en: "En esa foto tenía diez años." },
          { es: "He was hungry.", en: "Tenía hambre." },
          { es: "We were cold.", en: "Teníamos frío." },
          { es: "I was scared.", en: "Tenía miedo." },
          { es: "It was very cold.", en: "Hacía mucho frío." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "es-en",
            prompt: "Traduce al inglés.",
            source: "Yo tenía diez años.",
            answer: "I was ten.",
            altAnswers: ["I was 10.", "I was ten years old.", "I was 10 years old."],
            explanation: "La edad va con \"to be\": \"I was ten\" o \"I was ten years old\". *I had ten years es un calco del español.",
          },
          {
            type: "translate",
            direction: "es-en",
            prompt: "Traduce al inglés.",
            source: "Hacía mucho frío.",
            answer: "It was very cold.",
            altAnswers: ["It was really cold."],
            explanation: "El tiempo atmosférico lleva \"it\" como sujeto: \"It was very cold\". Nunca *Was very cold ni *It made cold.",
          },
        ],
      },
      {
        heading: "Negativas y preguntas",
        body: [
          "Para negar se añade \"not\": \"was not\" y \"were not\", que al hablar casi siempre se contraen en \"wasn't\" y \"weren't\". No hace falta ningún otro verbo auxiliar.",
          "Para preguntar se pone \"was\" o \"were\" delante del sujeto: \"Was she at work?\", \"Were you tired?\". Con palabra interrogativa: \"Where were you?\", \"How was the party?\".",
          "Las respuestas cortas repiten el verbo: \"Yes, she was\" / \"No, she wasn't\". Un simple \"Yes\" suena seco.",
        ],
        examples: [
          { es: "I wasn't at home.", en: "No estaba en casa." },
          { es: "They weren't happy.", en: "No estaban contentos." },
          { es: "Was she at work?", en: "¿Estaba en el trabajo?" },
          { es: "Yes, she was.", en: "Sí (estaba)." },
          { es: "Where were you?", en: "¿Dónde estabas?" },
          { es: "How was the party?", en: "¿Qué tal estuvo la fiesta?" },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "es-en",
            prompt: "Traduce al inglés.",
            source: "¿Dónde estabas?",
            answer: "Where were you?",
            explanation: "En la pregunta, \"were\" va delante del sujeto: \"Where were you?\". Con \"you\" siempre es \"were\".",
          },
          {
            type: "multiple-choice",
            question: "Te preguntan \"Was the movie good?\" y no te gustó. ¿Qué respondes?",
            options: ["No, it wasn't.", "No, it didn't.", "No, it weren't.", "No, was not."],
            correctIndex: 0,
            explanation: "La respuesta corta repite el verbo de la pregunta con su sujeto: \"No, it wasn't\". Con \"to be\" no se usa \"did\".",
          },
        ],
      },
      {
        heading: "«Había»: \"there was\" y \"there were\"",
        body: [
          "En A1 viste \"there is\" y \"there are\" para «hay». En pasado son \"there was\" (con singular) y \"there were\" (con plural): «había un gato» es \"There was a cat\", «había muchas personas» es \"There were a lot of people\".",
          "No digas *It was a cat ni *It had many people para «había». \"It was\" significa «era» o «estaba», y \"had\" es «tenía».",
          "Las negativas y preguntas siguen la regla de siempre: \"There wasn't any milk\", \"Were there many people?\".",
        ],
        examples: [
          { es: "There was a cat in the garden.", en: "Había un gato en el jardín." },
          { es: "There were a lot of people.", en: "Había mucha gente." },
          { es: "There wasn't any milk.", en: "No había leche." },
          { es: "Were there many people?", en: "¿Había mucha gente?" },
        ],
        checkpoint: [
          {
            type: "fill-blank",
            prompt: "Escribe en inglés las palabras en negrita.",
            sentence: "___ three students in the class.",
            answer: "There were",
            en: "[Había] tres estudiantes en la clase.",
            explanation: "«Había» con un plural es \"there were\". Con un singular sería \"there was\".",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Nosotros estábamos cansados.",
        answer: "We were tired.",
        explanation: "\"We\" va con \"were\", y «estábamos» no necesita ningún tiempo especial: es simplemente \"were\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Mi hermano tenía hambre.",
        answer: "My brother was hungry.",
        explanation: "«Tener hambre» es \"to be hungry\": \"My brother was hungry\", nunca *had hunger.",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "You ___ late.",
        answer: "were",
        en: "[Llegaste] tarde.",
        explanation: "En inglés «llegar tarde» se dice \"to be late\". Y \"you\" siempre va con \"were\", aunque sea una sola persona.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Había un perro en la calle.",
        answer: "There was a dog in the street.",
        altAnswers: ["There was a dog on the street."],
        explanation: "«Había» + singular es \"there was\". \"It was a dog\" significaría «era un perro».",
      },
      {
        type: "multiple-choice",
        question: "¿Cómo se dice «Cuando tenía cinco años, vivía en Lima»? Elige la primera parte correcta.",
        options: ["When I was five,", "When I had five years,", "When I had five,", "When was five,"],
        correctIndex: 0,
        explanation: "La edad va con \"to be\" y el sujeto es obligatorio: \"When I was five\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Ellos no estaban en casa.",
        answer: "They weren't at home.",
        altAnswers: ["They weren't home."],
        explanation: "La negativa de \"were\" es \"weren't\" (\"were not\"). No hace falta \"did\" con \"to be\".",
      },
      {
        type: "word-order",
        prompt: "Ordena las palabras.",
        words: ["Was", "the", "hotel", "expensive?"],
        translation: "¿El hotel era caro?",
        explanation: "En las preguntas, \"was\" va delante del sujeto: \"Was the hotel expensive?\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "¿Había mucha gente en la fiesta?",
        answer: "Were there a lot of people at the party?",
        altAnswers: ["Were there many people at the party?", "Were there lots of people at the party?"],
        explanation: "\"People\" es plural, así que se usa \"were there\". Y en una fiesta se está \"at the party\".",
      },
      {
        type: "listen-choose",
        audio: "It wasn't very cold.",
        question: "¿Qué has oído?",
        options: ["No hacía mucho frío.", "Hacía mucho frío.", "No tenía frío.", "No era muy caro."],
        correctIndex: 0,
        explanation: "\"It wasn't very cold\": \"wasn't\" es la negativa, y \"it\" indica que se habla del tiempo, no de una persona.",
      },
      {
        type: "speak",
        text: "Where were you yesterday?",
        tip: "\"Where\" y \"were\" se parecen, pero \"were\" es más corto y cerrado, casi /wɜr/. La \"w\" suena como la «u» de «huevo».",
        explanation: "\"Where were you yesterday?\" es una pregunta muy útil; practica la diferencia entre \"where\" y \"were\".",
      },
    ],
  },
  // ---------------------------------------------------------------------
  {
    slug: "a2-past-simple-regular-1",
    level: "EN-A2",
    number: 2,
    title: "El pasado simple: verbos regulares, parte 1 de 2",
    summary: "Verbo + -ed para hablar del pasado: \"I worked\", \"she worked\". Una sola forma para todas las personas y las expresiones \"yesterday\", \"last night\" y \"last week\".",
    duration: "10 min",
    sections: [
      {
        heading: "Verbo + -ed",
        body: [
          "El pasado simple de la mayoría de los verbos se forma añadiendo \"-ed\": \"work\" → \"worked\", \"play\" → \"played\", \"watch\" → \"watched\". Son los verbos regulares.",
          "Sirve para acciones terminadas en el pasado, como el pretérito indefinido del español: \"I worked yesterday\" es «trabajé ayer».",
          "En la siguiente lección verás algunos cambios de ortografía, como \"studied\" o \"stopped\". Aquí nos quedamos con los verbos que solo añaden \"-ed\".",
        ],
        examples: [
          { es: "I worked yesterday.", en: "Trabajé ayer." },
          { es: "We watched a movie.", en: "Vimos una película." },
          { es: "She called her mother.", en: "Llamó a su madre." },
          { es: "They played soccer.", en: "Jugaron al fútbol." },
          { es: "I cleaned the kitchen.", en: "Limpié la cocina." },
          { es: "He opened the window.", en: "Abrió la ventana." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "es-en",
            prompt: "Traduce al inglés.",
            source: "Limpié la cocina.",
            answer: "I cleaned the kitchen.",
            explanation: "Pasado regular: \"clean\" + \"-ed\" = \"cleaned\". Y el sujeto \"I\" es obligatorio.",
          },
        ],
      },
      {
        heading: "La misma forma para todas las personas",
        body: [
          "En español cada persona tiene su terminación: trabajé, trabajaste, trabajó, trabajamos... En inglés el pasado es igual para todos: \"I worked\", \"you worked\", \"she worked\", \"they worked\".",
          "Por eso no añadas una \"-s\" para la tercera persona: \"She worked\", nunca *She workeds ni *She works cuando hablas del pasado. La \"-s\" de \"he/she/it\" es solo del presente.",
          "Como el verbo no dice quién hizo la acción, el sujeto es todavía más importante: «trabajó» puede ser \"he worked\", \"she worked\" o \"you worked\".",
        ],
        examples: [
          { es: "I worked.", en: "Trabajé." },
          { es: "You worked.", en: "Trabajaste. / Trabajó usted." },
          { es: "She worked.", en: "Trabajó (ella)." },
          { es: "We worked.", en: "Trabajamos." },
          { es: "They worked.", en: "Trabajaron." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "¿Cómo se dice «Ana visitó a su abuela»?",
            options: ["Ana visited her grandmother.", "Ana visiteds her grandmother.", "Ana visits her grandmother.", "Ana visited his grandmother."],
            correctIndex: 0,
            explanation: "El pasado es igual para todas las personas: \"visited\", sin \"-s\". Y la abuela de Ana es \"her grandmother\", porque Ana es mujer.",
          },
          {
            type: "fill-blank",
            prompt: "Escribe en inglés las palabras en negrita.",
            sentence: "My father ___ in a bank.",
            answer: "worked",
            en: "Mi padre [trabajó] en un banco.",
            explanation: "En pasado no hay \"-s\" de tercera persona: \"my father worked\".",
          },
        ],
      },
      {
        heading: "\"Yesterday\", \"last night\", \"last week\"",
        body: [
          "Estas expresiones marcan el pasado: \"yesterday\" («ayer»), \"last night\" («anoche»), \"last week\" («la semana pasada»), \"last month\", \"last year\".",
          "Si hay una de ellas, el verbo tiene que ir en pasado. Un error frecuente es dejar el presente: *Yesterday I work a lot. Lo correcto es \"Yesterday I worked a lot\".",
          "Suelen ir al final de la frase (\"I called him last night\") o al principio (\"Last night I called him\"). Las dos posiciones son naturales.",
        ],
        examples: [
          { es: "I called him last night.", en: "Lo llamé anoche." },
          { es: "Last week we visited Tom.", en: "La semana pasada visitamos a Tom." },
          { es: "It rained yesterday.", en: "Ayer llovió." },
          { es: "She started a new job last month.", en: "Empezó un trabajo nuevo el mes pasado." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "es-en",
            prompt: "Traduce al inglés.",
            source: "Ayer llovió.",
            answer: "It rained yesterday.",
            altAnswers: ["Yesterday it rained."],
            explanation: "\"Yesterday\" pide pasado (\"rained\"), y la lluvia lleva el sujeto \"it\": nunca *Rained yesterday.",
          },
          {
            type: "translate",
            direction: "es-en",
            prompt: "Traduce al inglés.",
            source: "La semana pasada visitamos a Tom.",
            answer: "Last week we visited Tom.",
            altAnswers: ["We visited Tom last week."],
            explanation: "\"Last week\" sin artículo, y el verbo en pasado: \"visited\". En inglés no se pone nada equivalente a la «a» de «visitar a alguien».",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Trabajé mucho ayer.",
        answer: "I worked a lot yesterday.",
        altAnswers: ["Yesterday I worked a lot.", "I worked hard yesterday.", "Yesterday I worked hard."],
        explanation: "Con \"yesterday\" el verbo va en pasado: \"worked\". Nunca *Yesterday I work.",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "We ___ a movie last night.",
        answer: "watched",
        en: "Anoche [vimos] una película.",
        explanation: "\"Watch\" + \"-ed\" = \"watched\". Para películas y televisión se usa \"watch\", no \"see\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Ella llamó a su madre.",
        answer: "She called her mother.",
        altAnswers: ["She called her mom.", "She phoned her mother."],
        explanation: "\"Called\" sin \"-s\", y «su madre» de ella es \"her mother\".",
      },
      {
        type: "matching",
        instructions: "Une cada expresión con su significado.",
        pairs: [
          { left: "yesterday", right: "ayer" },
          { left: "last night", right: "anoche" },
          { left: "last week", right: "la semana pasada" },
          { left: "last year", right: "el año pasado" },
        ],
        explanation: "\"Last\" + periodo de tiempo, sin \"the\": \"last week\", \"last year\".",
      },
      {
        type: "multiple-choice",
        question: "¿Cuál es correcta?",
        options: ["Yesterday I played tennis.", "Yesterday I play tennis.", "Yesterday played tennis.", "Yesterday I playeds tennis."],
        correctIndex: 0,
        explanation: "Con \"yesterday\" se necesita el pasado (\"played\"), un sujeto (\"I\") y ninguna \"-s\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Ellos jugaron al fútbol el sábado.",
        answer: "They played soccer on Saturday.",
        altAnswers: ["They played football on Saturday.", "On Saturday they played soccer.", "On Saturday they played football."],
        explanation: "\"Play\" + \"-ed\" = \"played\". En Estados Unidos el fútbol es \"soccer\"; en el Reino Unido, \"football\".",
      },
      {
        type: "word-order",
        prompt: "Ordena las palabras.",
        words: ["He", "opened", "the", "window."],
        translation: "Abrió la ventana.",
        explanation: "Sujeto + verbo en pasado + complemento: \"He opened the window\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Mi hermana empezó un trabajo nuevo el mes pasado.",
        answer: "My sister started a new job last month.",
        altAnswers: ["Last month my sister started a new job."],
        explanation: "\"Start\" + \"-ed\" = \"started\". «El mes pasado» es \"last month\", sin \"the\". El adjetivo va delante: \"a new job\".",
      },
      {
        type: "dictation",
        audio: "I called my friend last night.",
        explanation: "\"Called\" termina en un sonido /d/ que se une a \"my\": escucha bien el final del verbo.",
      },
      {
        type: "speak",
        text: "We watched a movie last night.",
        tip: "\"Watched\" tiene una sola sílaba: /wɑtʃt/. No digas «guatchéd».",
        explanation: "La \"-ed\" casi nunca añade una sílaba; lo verás a fondo en la lección de pronunciación.",
      },
    ],
  },
  // ---------------------------------------------------------------------
  {
    slug: "a2-past-simple-regular-2",
    level: "EN-A2",
    number: 3,
    title: "El pasado simple: verbos regulares, parte 2 de 2",
    summary: "La ortografía de \"-ed\": \"lived\", \"studied\" pero \"played\", \"stopped\" y \"planned\". Práctica con un día, un viaje y un fin de semana.",
    duration: "11 min",
    sections: [
      {
        heading: "Verbos que terminan en -e: solo \"-d\"",
        body: [
          "Si el verbo ya termina en \"e\", solo se añade \"-d\": \"live\" → \"lived\", \"like\" → \"liked\", \"dance\" → \"danced\", \"arrive\" → \"arrived\".",
          "No escribas dos \"e\": *liveed o *arriveed son errores de ortografía.",
        ],
        examples: [
          { es: "I lived in Chile.", en: "Viví en Chile." },
          { es: "She liked the hotel.", en: "Le gustó el hotel." },
          { es: "We danced all night.", en: "Bailamos toda la noche." },
          { es: "The train arrived late.", en: "El tren llegó tarde." },
        ],
        checkpoint: [
          {
            type: "fill-blank",
            prompt: "Escribe en inglés las palabras en negrita.",
            sentence: "The train ___ late.",
            answer: "arrived",
            en: "El tren [llegó] tarde.",
            explanation: "\"Arrive\" ya termina en \"e\", así que solo se añade \"-d\": \"arrived\".",
          },
        ],
      },
      {
        heading: "Consonante + \"y\" → \"-ied\"",
        body: [
          "Si el verbo termina en consonante + \"y\", la \"y\" se cambia por \"i\" y se añade \"-ed\": \"study\" → \"studied\", \"try\" → \"tried\", \"carry\" → \"carried\".",
          "Si antes de la \"y\" hay una vocal, no cambia nada: \"play\" → \"played\", \"stay\" → \"stayed\", \"enjoy\" → \"enjoyed\". Un error típico es escribir *studyed o *plaied.",
        ],
        examples: [
          { es: "I studied English.", en: "Estudié inglés." },
          { es: "He tried the soup.", en: "Probó la sopa." },
          { es: "We stayed at a hotel.", en: "Nos quedamos en un hotel." },
          { es: "They enjoyed the trip.", en: "Disfrutaron del viaje." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "¿Cuál está bien escrita?",
            options: ["I studied for the exam.", "I studyed for the exam.", "I studed for the exam.", "I studieed for the exam."],
            correctIndex: 0,
            explanation: "\"Study\" termina en consonante + \"y\": la \"y\" pasa a \"i\" y se añade \"-ed\": \"studied\".",
          },
          {
            type: "translate",
            direction: "es-en",
            prompt: "Traduce al inglés.",
            source: "Nos quedamos en un hotel.",
            answer: "We stayed at a hotel.",
            altAnswers: ["We stayed in a hotel."],
            explanation: "\"Stay\" tiene una vocal antes de la \"y\", así que no cambia: \"stayed\".",
          },
        ],
      },
      {
        heading: "Doblar la consonante final",
        body: [
          "Los verbos cortos que terminan en consonante + vocal + consonante doblan la última letra: \"stop\" → \"stopped\", \"plan\" → \"planned\", \"shop\" → \"shopped\", \"chat\" → \"chatted\".",
          "En verbos de dos sílabas solo se dobla si el acento cae al final: \"prefer\" → \"preferred\", pero \"visit\" → \"visited\" y \"open\" → \"opened\".",
          "\"Travel\" es un caso especial: en Estados Unidos se escribe \"traveled\" y en el Reino Unido \"travelled\". Las dos formas son correctas.",
          "Nunca se doblan \"w\", \"x\" ni \"y\": \"snowed\", \"fixed\", \"played\".",
        ],
        examples: [
          { es: "The bus stopped.", en: "El autobús se detuvo." },
          { es: "We planned the trip.", en: "Planeamos el viaje." },
          { es: "They chatted for hours.", en: "Charlaron durante horas." },
          { es: "I visited my aunt.", en: "Visité a mi tía." },
          { es: "She traveled to Peru.", en: "Viajó a Perú." },
        ],
        checkpoint: [
          {
            type: "fill-blank",
            prompt: "Escribe en inglés las palabras en negrita.",
            sentence: "We ___ the trip together.",
            answer: "planned",
            en: "[Planeamos] el viaje juntos.",
            explanation: "\"Plan\" es consonante + vocal + consonante, así que se dobla la \"n\": \"planned\".",
          },
          {
            type: "translate",
            direction: "es-en",
            prompt: "Traduce al inglés.",
            source: "El autobús se detuvo.",
            answer: "The bus stopped.",
            explanation: "\"Stop\" dobla la \"p\": \"stopped\". Con una sola \"p\", *stoped es un error de ortografía.",
          },
        ],
      },
      {
        heading: "Todo junto: un día, un viaje, un fin de semana",
        body: [
          "Ahora puedes contar un día completo con verbos regulares: \"I worked until six, then I cooked dinner and watched TV.\"",
          "Al contar algo en pasado, mantén todos los verbos en pasado. Un error frecuente es empezar en pasado y pasar sin querer al presente: *We arrived and we visit the museum.",
        ],
        examples: [
          { es: "I worked until six and then I cooked dinner.", en: "Trabajé hasta las seis y después hice la cena." },
          { es: "We arrived in Cusco and visited the old town.", en: "Llegamos a Cusco y visitamos el casco antiguo." },
          { es: "On Saturday I stayed at home and relaxed.", en: "El sábado me quedé en casa y descansé." },
          { es: "It rained, so we stopped at a cafe.", en: "Llovió, así que paramos en un café." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "es-en",
            prompt: "Traduce al inglés.",
            source: "El sábado me quedé en casa y descansé.",
            answer: "On Saturday I stayed at home and relaxed.",
            altAnswers: ["On Saturday I stayed home and relaxed.", "I stayed at home on Saturday and relaxed.", "I stayed home on Saturday and relaxed.", "On Saturday I stayed at home and rested.", "On Saturday I stayed home and rested."],
            explanation: "Los dos verbos van en pasado: \"stayed\" (vocal + \"y\", no cambia) y \"relaxed\" (la \"x\" nunca se dobla).",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Estudié inglés anoche.",
        answer: "I studied English last night.",
        altAnswers: ["Last night I studied English."],
        explanation: "\"Study\" → \"studied\": consonante + \"y\" cambia a \"-ied\". Los idiomas van con mayúscula: \"English\".",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "They ___ the trip.",
        answer: "enjoyed",
        en: "[Disfrutaron] del viaje.",
        explanation: "\"Enjoy\" tiene vocal + \"y\", así que no cambia: \"enjoyed\". Además, \"enjoy\" no lleva preposición: «disfrutar de» es solo \"enjoy\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Viví en Chile dos años.",
        answer: "I lived in Chile for two years.",
        explanation: "\"Live\" termina en \"e\": solo se añade \"-d\". Para la duración se usa \"for\": \"for two years\".",
      },
      {
        type: "multiple-choice",
        question: "¿Cuál está bien escrita?",
        options: ["The car stopped.", "The car stoped.", "The car stopt.", "The car stopied."],
        correctIndex: 0,
        explanation: "\"Stop\" (consonante + vocal + consonante) dobla la consonante final: \"stopped\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Él probó la sopa.",
        answer: "He tried the soup.",
        altAnswers: ["He tasted the soup."],
        explanation: "\"Try\" → \"tried\": consonante + \"y\" se convierte en \"-ied\". \"Try\" es «probar» comida, y también «intentar».",
      },
      {
        type: "matching",
        instructions: "Une cada verbo con su pasado.",
        pairs: [
          { left: "dance", right: "danced" },
          { left: "carry", right: "carried" },
          { left: "shop", right: "shopped" },
          { left: "visit", right: "visited" },
        ],
        explanation: "\"Dance\" solo añade \"-d\"; \"carry\" cambia a \"-ied\"; \"shop\" dobla la \"p\"; \"visit\" no dobla porque el acento cae en la primera sílaba.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Llegamos a Cusco y visitamos el museo.",
        answer: "We arrived in Cusco and visited the museum.",
        altAnswers: ["We arrived in Cusco and we visited the museum."],
        explanation: "Se llega \"in\" a una ciudad (\"arrive in Cusco\"), no \"to\". Y los dos verbos van en pasado: \"arrived\" y \"visited\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Ella viajó a Perú el año pasado.",
        answer: "She traveled to Peru last year.",
        altAnswers: ["She travelled to Peru last year.", "Last year she traveled to Peru.", "Last year she travelled to Peru."],
        explanation: "\"Traveled\" (Estados Unidos) o \"travelled\" (Reino Unido): las dos ortografías son correctas.",
      },
      {
        type: "word-order",
        prompt: "Ordena las palabras.",
        words: ["They", "chatted", "for", "hours."],
        translation: "Charlaron durante horas.",
        explanation: "\"Chat\" dobla la \"t\": \"chatted\". «Durante» con una duración es \"for\".",
      },
      {
        type: "dictation",
        audio: "We stayed at a small hotel.",
        explanation: "\"Stayed\" se escribe con \"y\" porque antes de la \"y\" hay una vocal.",
      },
      {
        type: "write",
        prompt: "Escribe sobre un viaje que hiciste. Usa al menos cinco verbos regulares en pasado (por ejemplo \"traveled\", \"arrived\", \"stayed\", \"visited\", \"enjoyed\").",
        minWords: 30,
        maxWords: 70,
        rubric: [
          "Usa al menos cinco verbos regulares en pasado.",
          "Escribe bien \"-ed\", \"-ied\" y las consonantes dobles.",
          "Todas las frases tienen sujeto.",
          "No mezcla presente y pasado al contar el viaje.",
        ],
        modelAnswer: "Last summer I traveled to Mexico with my sister. We arrived in Mexico City on a Monday and stayed at a small hotel. We visited a lot of museums and tried the street food. One day it rained, so we stopped at a cafe and chatted for hours. We really enjoyed the trip.",
        explanation: "Revisa la ortografía de cada verbo: \"stayed\" (vocal + \"y\"), \"tried\" (consonante + \"y\"), \"stopped\" y \"chatted\" (consonante doble).",
      },
    ],
  },
  // ---------------------------------------------------------------------
  {
    slug: "a2-ed-pronunciation",
    level: "EN-A2",
    number: 4,
    title: "La pronunciación de -ed",
    summary: "Los tres sonidos de \"-ed\": /t/ en \"worked\", /d/ en \"played\" y /ɪd/ solo después de t o d, como en \"wanted\". Cómo evitar decir «work-ed».",
    duration: "10 min",
    sections: [
      {
        heading: "La \"-ed\" casi nunca es una sílaba",
        body: [
          "El error más típico de los hispanohablantes es leer \"-ed\" tal como se escribe, como una sílaba más: «work-ed», «play-ed», «watch-ed». En realidad, \"worked\" tiene una sola sílaba, igual que \"work\".",
          "La \"e\" de \"-ed\" casi siempre es muda. Lo que se oye es solo una consonante al final: /t/ o /d/.",
          "Solo hay una excepción: cuando el verbo termina en sonido /t/ o /d/, la \"-ed\" sí añade una sílaba, /ɪd/: \"wanted\", \"needed\".",
        ],
        examples: [
          { es: "worked", en: "trabajé (una sílaba: /wɜrkt/)" },
          { es: "played", en: "jugué (una sílaba: /pleɪd/)" },
          { es: "lived", en: "viví (una sílaba: /lɪvd/)" },
          { es: "wanted", en: "quise (dos sílabas: /ˈwɑntɪd/)" },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "¿Cuántas sílabas tiene \"played\"?",
            options: ["Una", "Dos", "Tres", "Depende de la persona"],
            correctIndex: 0,
            explanation: "\"Played\" se pronuncia /pleɪd/, una sola sílaba. Decir «pley-ed» es el error típico.",
          },
        ],
      },
      {
        heading: "/t/ y /d/",
        body: [
          "Después de sonidos sordos (sin vibración de la garganta), como /p/, /k/, /s/, /f/, /ʃ/ y /tʃ/, la \"-ed\" suena /t/: \"stopped\" /stɑpt/, \"worked\" /wɜrkt/, \"kissed\" /kɪst/, \"washed\" /wɑʃt/, \"watched\" /wɑtʃt/.",
          "Después de vocales y de los demás sonidos sonoros, como /l/, /n/, /v/, /z/, /g/ o /b/, suena /d/: \"played\", \"called\", \"cleaned\", \"lived\", \"used\".",
          "No hace falta memorizar la lista: si pones la mano en la garganta, notarás que el sonido sale solo. Lo importante es no añadir una vocal.",
        ],
        examples: [
          { es: "I stopped.", en: "Paré. (/t/)" },
          { es: "She washed the car.", en: "Lavó el auto. (/t/)" },
          { es: "We watched TV.", en: "Vimos la tele. (/t/)" },
          { es: "He called me.", en: "Me llamó. (/d/)" },
          { es: "They cleaned the house.", en: "Limpiaron la casa. (/d/)" },
        ],
        checkpoint: [
          {
            type: "listen-choose",
            audio: "She washed the car.",
            question: "¿Cómo suena el final de \"washed\"?",
            options: ["/t/, una sola sílaba", "/ɪd/, dos sílabas", "/d/, dos sílabas", "No se oye nada"],
            correctIndex: 0,
            explanation: "\"Washed\" es /wɑʃt/: después de /ʃ/ la \"-ed\" suena /t/ y no añade sílaba.",
          },
          {
            type: "speak",
            text: "He called me last night.",
            tip: "\"Called\" es /kɔld/, una sílaba. La /d/ final es breve; se une a \"me\".",
            explanation: "Después de /l/ la \"-ed\" suena /d/, sin vocal extra.",
          },
        ],
      },
      {
        heading: "/ɪd/: solo después de t o d",
        body: [
          "Si el verbo termina en sonido /t/ o /d/, añadir solo /t/ o /d/ no se oiría, así que aparece una sílaba nueva: \"want\" → \"wanted\" /ˈwɑntɪd/, \"need\" → \"needed\", \"visit\" → \"visited\", \"start\" → \"started\", \"decide\" → \"decided\".",
          "Esta es la única regla en la que \"-ed\" suena como sílaba. Si la aplicas a otros verbos, dirás «work-ed» y te costará que te entiendan.",
        ],
        examples: [
          { es: "I wanted a coffee.", en: "Quería un café." },
          { es: "We needed help.", en: "Necesitábamos ayuda." },
          { es: "They visited Rome.", en: "Visitaron Roma." },
          { es: "The movie started at eight.", en: "La película empezó a las ocho." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "¿En cuál de estos verbos la \"-ed\" añade una sílaba?",
            options: ["needed", "worked", "played", "watched"],
            correctIndex: 0,
            explanation: "\"Need\" termina en /d/, así que la \"-ed\" suena /ɪd/: \"need-ed\". En los demás, \"-ed\" es solo /t/ o /d/.",
          },
        ],
      },
      {
        heading: "No te comas la consonante final",
        body: [
          "El error contrario también es común: como el español casi no termina palabras en dos consonantes, muchos dicen \"work\" en lugar de \"worked\". Entonces la frase suena a presente.",
          "Truco: une la /t/ o la /d/ con la palabra siguiente si empieza por vocal. \"Worked at home\" suena «wor-kta-thome», y \"played a game\" suena «play-da-game».",
        ],
        examples: [
          { es: "I worked at home.", en: "Trabajé en casa." },
          { es: "We played a game.", en: "Jugamos un juego." },
          { es: "She asked a question.", en: "Hizo una pregunta." },
        ],
        checkpoint: [
          {
            type: "dictation",
            audio: "I worked at home yesterday.",
            explanation: "La /t/ de \"worked\" se une a \"at\". Si no la oyes, piensa: \"yesterday\" pide pasado.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "matching",
        instructions: "Une cada verbo con el sonido de su \"-ed\".",
        pairs: [
          { left: "watched", right: "/t/" },
          { left: "lived", right: "/d/" },
          { left: "started", right: "/ɪd/" },
        ],
        explanation: "/t/ después de sonidos sordos (/tʃ/ en \"watch\"), /d/ después de sonidos sonoros (/v/ en \"live\") e /ɪd/ después de /t/ o /d/.",
      },
      {
        type: "multiple-choice",
        question: "¿Cuál de estos verbos tiene dos sílabas?",
        options: ["decided", "danced", "cooked", "opened"],
        correctIndex: 0,
        explanation: "\"Decide\" termina en /d/, así que \"decided\" añade /ɪd/. \"Opened\" tiene dos sílabas porque \"open\" ya las tiene, y \"-ed\" no añade ninguna: /ˈoʊpənd/.",
      },
      {
        type: "listen-choose",
        audio: "We needed help.",
        question: "¿Qué has oído?",
        options: ["Necesitábamos ayuda.", "Necesitamos ayuda.", "No necesitamos ayuda.", "Necesitan ayuda."],
        correctIndex: 0,
        explanation: "\"Needed\" tiene dos sílabas: /ˈniːdɪd/. Esa sílaba final te dice que es pasado.",
      },
      {
        type: "listen-choose",
        audio: "I cooked dinner.",
        question: "¿Qué has oído?",
        options: ["Hice la cena.", "Hago la cena.", "Voy a hacer la cena.", "No hice la cena."],
        correctIndex: 0,
        explanation: "\"Cooked\" es /kʊkt/: la /t/ final es corta, pero marca el pasado.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Ella hizo una pregunta.",
        answer: "She asked a question.",
        explanation: "«Hacer una pregunta» es \"ask a question\", no *make a question. \"Asked\" se pronuncia /æskt/, una sílaba.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "La película empezó a las ocho.",
        answer: "The movie started at eight.",
        altAnswers: ["The movie started at 8.", "The film started at eight.", "The film started at 8.", "The movie began at eight.", "The movie began at 8."],
        explanation: "\"Started\" tiene dos sílabas porque \"start\" termina en /t/: /ˈstɑrtɪd/.",
      },
      {
        type: "speak",
        text: "We watched a movie and talked for hours.",
        tip: "\"Watched\" /wɑtʃt/ y \"talked\" /tɔkt/ tienen una sola sílaba. La \"l\" de \"talked\" es muda.",
        explanation: "Dos /t/ finales y ninguna sílaba extra: «watch-ed» o «talk-ed» suenan extraños.",
      },
      {
        type: "speak",
        text: "They visited their friends and wanted to stay.",
        tip: "Aquí sí hay sílaba extra: \"VIS-i-ted\", \"WAN-ted\". El acento sigue en la primera sílaba.",
        explanation: "\"Visit\" y \"want\" terminan en /t/, así que su \"-ed\" suena /ɪd/.",
      },
      {
        type: "dictation",
        audio: "She played the guitar and danced.",
        explanation: "\"Played\" /pleɪd/ y \"danced\" /dænst/: una sílaba cada uno, con /d/ y /t/ al final.",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "They ___ the house.",
        answer: "cleaned",
        en: "[Limpiaron] la casa.",
        explanation: "\"Cleaned\" se pronuncia /kliːnd/, una sílaba con /d/ final.",
      },
    ],
  },
  // ---------------------------------------------------------------------
  {
    slug: "a2-past-simple-did-1",
    level: "EN-A2",
    number: 5,
    title: "Negativas y preguntas con did, parte 1 de 2",
    summary: "La negativa del pasado: \"didn't\" + verbo en forma base. \"I didn't work\", \"she didn't call\", y por qué *I didn't worked está mal.",
    duration: "10 min",
    sections: [
      {
        heading: "\"Didn't\" + verbo base",
        body: [
          "En presente, la negativa se hace con \"don't\" o \"doesn't\". En pasado se usa \"didn't\" (\"did not\") para todas las personas: \"I didn't work\", \"she didn't work\", \"they didn't work\".",
          "Detrás de \"didn't\" va el verbo en su forma base, sin \"-ed\": \"I didn't call\", \"We didn't watch TV\".",
          "\"Didn't\" es lo normal al hablar y en mensajes; \"did not\" suena más formal o enfático.",
        ],
        examples: [
          { es: "I didn't work yesterday.", en: "Ayer no trabajé." },
          { es: "She didn't call me.", en: "No me llamó." },
          { es: "We didn't watch TV.", en: "No vimos la tele." },
          { es: "They didn't like the food.", en: "No les gustó la comida." },
          { es: "He didn't study for the exam.", en: "No estudió para el examen." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "es-en",
            prompt: "Traduce al inglés.",
            source: "Ayer no trabajé.",
            answer: "I didn't work yesterday.",
            altAnswers: ["Yesterday I didn't work."],
            explanation: "Negativa en pasado: \"didn't\" + forma base (\"work\"), sin \"-ed\".",
          },
        ],
      },
      {
        heading: "El pasado va una sola vez",
        body: [
          "\"Did\" ya es pasado: es el pasado de \"do\". Por eso el verbo principal vuelve a su forma base. Si dices \"I didn't worked\", estás marcando el pasado dos veces.",
          "Lo mismo vale para los verbos irregulares, que verás más adelante: aunque el pasado de \"go\" es \"went\", la negativa es \"She didn't go\", nunca *She didn't went.",
          "Piensa en \"didn't\" como en una etiqueta que dice «pasado y negativo». El resto de la frase no cambia: \"I worked\" → \"I didn't work\".",
        ],
        examples: [
          { es: "I worked. → I didn't work.", en: "Trabajé. → No trabajé." },
          { es: "She called. → She didn't call.", en: "Llamó. → No llamó." },
          { es: "He went out. → He didn't go out.", en: "Salió. → No salió." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "¿Cuál es correcta?",
            options: ["She didn't call me.", "She didn't called me.", "She don't called me.", "She no called me."],
            correctIndex: 0,
            explanation: "\"Didn't\" ya lleva el pasado, así que el verbo va en forma base: \"call\", no \"called\".",
          },
          {
            type: "fill-blank",
            prompt: "Escribe en inglés las palabras en negrita.",
            sentence: "He ___ out last night.",
            answer: "didn't go",
            altAnswers: ["did not go"],
            en: "Anoche [no salió].",
            explanation: "Con \"didn't\" el verbo va en forma base: \"didn't go\", nunca *didn't went.",
          },
        ],
      },
      {
        heading: "No digas *I no worked",
        body: [
          "En español basta con poner «no» delante del verbo. En inglés no: *I no worked o *She no called son incorrectos. La negativa necesita el auxiliar: \"I didn't work\".",
          "Tampoco sirve \"don't\" para el pasado: \"I don't work yesterday\" mezcla presente y pasado.",
        ],
        examples: [
          { es: "I didn't understand.", en: "No entendí." },
          { es: "We didn't wait.", en: "No esperamos." },
          { es: "It didn't rain.", en: "No llovió." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "es-en",
            prompt: "Traduce al inglés.",
            source: "No llovió.",
            answer: "It didn't rain.",
            explanation: "Se necesita sujeto (\"it\") y auxiliar (\"didn't\"): \"It didn't rain\". *No rained no es inglés.",
          },
        ],
      },
      {
        heading: "Con \"to be\", nada de \"did\"",
        body: [
          "\"Was\" y \"were\" hacen su negativa solos, como viste en la primera lección: \"I wasn't tired\", \"They weren't at home\". No digas *I didn't be tired.",
          "Regla rápida: si la frase afirmativa tiene \"was\" o \"were\", niega con \"wasn't\" o \"weren't\". Si tiene otro verbo en pasado, niega con \"didn't\" + forma base.",
        ],
        examples: [
          { es: "I wasn't hungry.", en: "No tenía hambre." },
          { es: "I didn't eat.", en: "No comí." },
          { es: "The hotel wasn't expensive.", en: "El hotel no era caro." },
          { es: "We didn't like the hotel.", en: "No nos gustó el hotel." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "¿Cómo se dice «No estaba cansada»?",
            options: ["I wasn't tired.", "I didn't tired.", "I didn't be tired.", "I no was tired."],
            correctIndex: 0,
            explanation: "\"Tired\" es un adjetivo, así que el verbo es \"to be\": la negativa es \"wasn't\", sin \"did\".",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Ella no me llamó.",
        answer: "She didn't call me.",
        explanation: "\"Didn't\" + forma base: \"didn't call\". Nunca *didn't called.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "No vimos la tele anoche.",
        answer: "We didn't watch TV last night.",
        altAnswers: ["We didn't watch television last night.", "Last night we didn't watch TV.", "We didn't watch the TV last night."],
        explanation: "«Ver la tele» es \"watch TV\", normalmente sin \"the\". La negativa: \"didn't watch\".",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "They ___ the food.",
        answer: "didn't like",
        altAnswers: ["did not like"],
        en: "[No les gustó] la comida.",
        explanation: "«Gustar» se dice con \"like\" y la persona como sujeto: \"They didn't like the food\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "No entendí la pregunta.",
        answer: "I didn't understand the question.",
        explanation: "\"Didn't\" + \"understand\". En inglés hace falta el sujeto \"I\".",
      },
      {
        type: "multiple-choice",
        question: "¿Cuál es correcta?",
        options: ["He didn't study for the exam.", "He didn't studied for the exam.", "He no studied for the exam.", "He doesn't studied for the exam."],
        correctIndex: 0,
        explanation: "Pasado negativo: \"didn't\" + forma base (\"study\").",
      },
      {
        type: "word-order",
        prompt: "Ordena las palabras.",
        words: ["We", "didn't", "wait", "for", "the", "bus."],
        translation: "No esperamos el autobús.",
        explanation: "«Esperar algo» es \"wait for\": \"We didn't wait for the bus\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "El hotel no era caro.",
        answer: "The hotel wasn't expensive.",
        explanation: "Con un adjetivo (\"expensive\") se usa \"to be\": la negativa es \"wasn't\", no \"didn't\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Mi hermano no estudió y no aprobó.",
        answer: "My brother didn't study and he didn't pass.",
        altAnswers: ["My brother didn't study and didn't pass.", "My brother didn't study, so he didn't pass.", "My brother didn't study and he didn't pass the exam.", "My brother didn't study and didn't pass the exam."],
        explanation: "Cada negativa lleva \"didn't\" + forma base: \"didn't study\", \"didn't pass\".",
      },
      {
        type: "listen-choose",
        audio: "I didn't open the window.",
        question: "¿Qué has oído?",
        options: ["No abrí la ventana.", "Abrí la ventana.", "No abro la ventana.", "No cerré la ventana."],
        correctIndex: 0,
        explanation: "\"Didn't open\": la negativa en pasado. \"Open\" es «abrir»; «cerrar» sería \"close\".",
      },
      {
        type: "speak",
        text: "I didn't work yesterday.",
        tip: "\"Didn't\" se pronuncia /ˈdɪdnt/: la segunda \"d\" casi se pega a la \"n\". Y \"work\" va sin \"-ed\".",
        explanation: "Pronunciar \"didn't\" con claridad es lo que hace que la frase suene negativa.",
      },
    ],
  },
  // ---------------------------------------------------------------------
  {
    slug: "a2-past-simple-did-2",
    level: "EN-A2",
    number: 6,
    title: "Negativas y preguntas con did, parte 2 de 2",
    summary: "Preguntas en pasado: \"Did you...?\" con respuestas cortas como \"Yes, I did\", y preguntas como \"Where did you go?\" o \"What did you eat?\".",
    duration: "11 min",
    sections: [
      {
        heading: "\"Did\" + sujeto + verbo base",
        body: [
          "Para preguntar en pasado se pone \"did\" delante del sujeto, y el verbo va en forma base: \"Did you work yesterday?\", \"Did she call you?\".",
          "En español basta con la entonación: «¿Trabajaste ayer?». En inglés hace falta \"did\". \"You worked yesterday?\" solo se usa para mostrar sorpresa, no como pregunta normal.",
          "Igual que en las negativas, el pasado va una sola vez, en \"did\": \"Did you watch the game?\", nunca *Did you watched...? ni *Did you went...?.",
        ],
        examples: [
          { es: "Did you work yesterday?", en: "¿Trabajaste ayer?" },
          { es: "Did she call you?", en: "¿Te llamó?" },
          { es: "Did they enjoy the party?", en: "¿Disfrutaron de la fiesta?" },
          { es: "Did you watch the game?", en: "¿Viste el partido?" },
          { es: "Did it rain?", en: "¿Llovió?" },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "es-en",
            prompt: "Traduce al inglés.",
            source: "¿Viste el partido?",
            answer: "Did you watch the game?",
            altAnswers: ["Did you watch the match?", "Did you see the game?", "Did you see the match?"],
            explanation: "\"Did\" + sujeto + forma base: \"Did you watch...?\". En Estados Unidos un partido es \"a game\"; en el Reino Unido, \"a match\".",
          },
          {
            type: "multiple-choice",
            question: "¿Cuál es correcta?",
            options: ["Did she call you?", "Did she called you?", "Does she called you?", "She called you did?"],
            correctIndex: 0,
            explanation: "\"Did\" lleva el pasado, así que el verbo va en forma base: \"call\".",
          },
        ],
      },
      {
        heading: "Respuestas cortas: \"Yes, I did\" / \"No, I didn't\"",
        body: [
          "A una pregunta con \"did\" se responde con el sujeto y \"did\" o \"didn't\": \"Did you call her?\" → \"Yes, I did\" o \"No, I didn't\".",
          "Fíjate en el cambio de persona: si te preguntan con \"you\", respondes con \"I\" (o con \"we\").",
          "No respondas repitiendo el verbo principal: *Yes, I called suena incompleto. Y no uses \"did\" para responder a una pregunta con \"was\": \"Was it good?\" → \"Yes, it was\".",
        ],
        examples: [
          { es: "Did you call her? Yes, I did.", en: "¿La llamaste? Sí." },
          { es: "Did he like it? No, he didn't.", en: "¿Le gustó? No." },
          { es: "Did they arrive on time? Yes, they did.", en: "¿Llegaron a tiempo? Sí." },
          { es: "Was it good? Yes, it was.", en: "¿Estuvo bien? Sí." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "Te preguntan \"Did you like the movie?\" y te gustó. ¿Qué respondes?",
            options: ["Yes, I did.", "Yes, I liked.", "Yes, you did.", "Yes, I was."],
            correctIndex: 0,
            explanation: "La respuesta corta repite el auxiliar de la pregunta: \"Yes, I did\". La pregunta usa \"you\" y la respuesta \"I\".",
          },
          {
            type: "fill-blank",
            prompt: "Escribe en inglés las palabras en negrita.",
            sentence: "Did Emma call? No, she ___.",
            answer: "didn't",
            altAnswers: ["did not"],
            en: "¿Llamó Emma? No, [no llamó].",
            explanation: "Respuesta corta negativa: sujeto + \"didn't\". No se repite el verbo \"call\".",
          },
        ],
      },
      {
        heading: "Preguntas con \"where\", \"what\", \"when\"...",
        body: [
          "Con palabra interrogativa el orden es: palabra interrogativa + \"did\" + sujeto + verbo base. \"Where did you go?\", \"What did you eat?\", \"When did they arrive?\".",
          "Dos errores típicos: olvidar \"did\" (*Where you went?) y poner el verbo en pasado (*Where did you went?). Ninguno de los dos es correcto.",
          "Con \"was\" y \"were\" no hay \"did\": \"Where were you?\", \"How was the trip?\".",
        ],
        examples: [
          { es: "Where did you go?", en: "¿Adónde fuiste?" },
          { es: "What did you eat?", en: "¿Qué comiste?" },
          { es: "When did they arrive?", en: "¿Cuándo llegaron?" },
          { es: "Why did she call?", en: "¿Por qué llamó?" },
          { es: "What time did the movie start?", en: "¿A qué hora empezó la película?" },
          { es: "How was the trip?", en: "¿Qué tal el viaje?" },
        ],
        checkpoint: [
          {
            type: "word-order",
            prompt: "Ordena las palabras.",
            words: ["Where", "did", "you", "go?"],
            translation: "¿Adónde fuiste?",
            explanation: "Palabra interrogativa + \"did\" + sujeto + forma base: \"Where did you go?\".",
          },
          {
            type: "translate",
            direction: "es-en",
            prompt: "Traduce al inglés.",
            source: "¿Cuándo llegaron ellos?",
            answer: "When did they arrive?",
            explanation: "\"When\" + \"did\" + \"they\" + \"arrive\" (forma base, sin \"-d\").",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "¿Qué comiste?",
        answer: "What did you eat?",
        explanation: "\"What\" + \"did\" + \"you\" + \"eat\". El verbo va en forma base, aunque la pregunta sea en pasado.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "¿Trabajaste ayer?",
        answer: "Did you work yesterday?",
        explanation: "En inglés la pregunta necesita \"did\" delante del sujeto: no basta con la entonación.",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "Did you call your mother? Yes, I ___.",
        answer: "did",
        en: "¿Llamaste a tu madre? Sí, [la llamé].",
        explanation: "La respuesta corta es \"Yes, I did\": se repite el auxiliar, no el verbo.",
      },
      {
        type: "multiple-choice",
        question: "¿Cuál es correcta?",
        options: ["Where did you study English?", "Where you studied English?", "Where did you studied English?", "Where studied you English?"],
        correctIndex: 0,
        explanation: "Palabra interrogativa + \"did\" + sujeto + forma base: \"Where did you study...?\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "¿A qué hora empezó la clase?",
        answer: "What time did the class start?",
        altAnswers: ["When did the class start?", "What time did the class begin?", "What time did class start?"],
        explanation: "«¿A qué hora...?» es \"What time...?\", seguido de \"did\" + sujeto + forma base.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "¿Por qué te llamó Carlos?",
        answer: "Why did Carlos call you?",
        explanation: "\"Why\" + \"did\" + \"Carlos\" + \"call\" + \"you\". El sujeto (Carlos) va entre \"did\" y el verbo.",
      },
      {
        type: "matching",
        instructions: "Une cada pregunta con su respuesta.",
        pairs: [
          { left: "Did you enjoy the trip?", right: "Yes, I did." },
          { left: "Was the hotel nice?", right: "Yes, it was." },
          { left: "Did they arrive late?", right: "No, they didn't." },
          { left: "Were you tired?", right: "No, I wasn't." },
        ],
        explanation: "La respuesta corta usa el mismo auxiliar que la pregunta: \"did\" con \"did\", \"was\" con \"was\", \"were\" con \"was\" o \"were\" según el sujeto.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "¿Dónde estuvieron ustedes el sábado?",
        answer: "Where were you on Saturday?",
        altAnswers: ["Where were you guys on Saturday?", "On Saturday where were you?"],
        explanation: "Con «estar» se usa \"were\", sin \"did\": \"Where were you?\". \"You\" vale para «ustedes».",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "¿Les gustó la comida?",
        answer: "Did they like the food?",
        altAnswers: ["Did you like the food?"],
        explanation: "«Gustar» se dice con \"like\" y la persona como sujeto: \"Did they like...?\" (o \"Did you like...?\" si «les» se refiere a ustedes).",
      },
      {
        type: "listen-choose",
        audio: "What did you do last night?",
        question: "¿Qué te preguntan?",
        options: ["¿Qué hiciste anoche?", "¿Qué haces esta noche?", "¿Qué vas a hacer esta noche?", "¿Dónde estuviste anoche?"],
        correctIndex: 0,
        explanation: "\"What did you do?\" = «¿qué hiciste?». El primer \"did\" es el auxiliar y \"do\" es el verbo «hacer».",
      },
      {
        type: "speak",
        text: "Where did you go last weekend?",
        tip: "\"Did you\" suele sonar «di-ya» o «di-yu» al hablar rápido. El acento cae en \"go\" y en \"weekend\".",
        explanation: "Es una de las preguntas más comunes del lunes: \"Where did you go last weekend?\".",
      },
    ],
  },
  // ---------------------------------------------------------------------
  {
    slug: "a2-past-time-expressions",
    level: "EN-A2",
    number: 7,
    title: "Yesterday, last y ago",
    summary: "Situar algo en el pasado: \"yesterday morning\", \"last week\" (no *the last week), \"in 2019\" y \"two years ago\" para «hace dos años».",
    duration: "10 min",
    sections: [
      {
        heading: "\"Yesterday\" + parte del día",
        body: [
          "Para las partes del día de ayer se pone la palabra directamente detrás de \"yesterday\": \"yesterday morning\" («ayer por la mañana»), \"yesterday afternoon\", \"yesterday evening\". No digas *yesterday in the morning.",
          "Para «anoche» se usa \"last night\". *Yesterday night se oye poco y suena raro a muchos nativos.",
          "Y para el día anterior a ayer: \"the day before yesterday\" («anteayer»).",
        ],
        examples: [
          { es: "I called her yesterday morning.", en: "La llamé ayer por la mañana." },
          { es: "We arrived yesterday afternoon.", en: "Llegamos ayer por la tarde." },
          { es: "It rained last night.", en: "Anoche llovió." },
          { es: "She visited us the day before yesterday.", en: "Nos visitó anteayer." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "es-en",
            prompt: "Traduce al inglés.",
            source: "Llegamos ayer por la tarde.",
            answer: "We arrived yesterday afternoon.",
            altAnswers: ["Yesterday afternoon we arrived.", "We arrived yesterday evening."],
            explanation: "«Ayer por la tarde» es \"yesterday afternoon\", sin \"in the\".",
          },
        ],
      },
      {
        heading: "\"Last\" sin \"the\"",
        body: [
          "«La semana pasada» es \"last week\", sin artículo. Lo mismo con \"last month\", \"last year\", \"last summer\", \"last Monday\".",
          "Ojo: \"the last week\" significa otra cosa: «la última semana» (de un curso, de las vacaciones) o «los últimos siete días». Por eso *I visited Rome the last week está mal para «la semana pasada».",
          "\"The last\" sí se usa para lo último de una serie: \"the last time\" («la última vez»), \"the last bus\" («el último autobús»).",
        ],
        examples: [
          { es: "I started the course last week.", en: "Empecé el curso la semana pasada." },
          { es: "We traveled to Spain last summer.", en: "Viajamos a España el verano pasado." },
          { es: "He called me last Monday.", en: "Me llamó el lunes pasado." },
          { es: "We missed the last bus.", en: "Perdimos el último autobús." },
          { es: "The last time I visited Lima was in 2019.", en: "La última vez que visité Lima fue en 2019." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "¿Cómo se dice «Me mudé el año pasado»?",
            options: ["I moved last year.", "I moved the last year.", "I moved the year last.", "I moved in last year."],
            correctIndex: 0,
            explanation: "\"Last year\" va sin \"the\" y sin preposición. \"The last year\" sería «el último año».",
          },
          {
            type: "fill-blank",
            prompt: "Escribe en inglés las palabras en negrita.",
            sentence: "We missed ___ bus.",
            answer: "the last",
            en: "Perdimos [el último] autobús.",
            explanation: "Para «el último» de una serie sí se usa \"the last\": \"the last bus\".",
          },
        ],
      },
      {
        heading: "\"In\", \"on\" y \"at\" con fechas pasadas",
        body: [
          "Con años, meses y estaciones se usa \"in\": \"in 2019\", \"in May\", \"in the summer\". Con días y fechas, \"on\": \"on Monday\", \"on May 5th\". Con horas, \"at\": \"at six\".",
          "Pero con \"last\", \"yesterday\" y \"ago\" no se pone preposición: \"last May\", no *in last May.",
        ],
        examples: [
          { es: "I moved to Miami in 2019.", en: "Me mudé a Miami en 2019." },
          { es: "She started on Monday.", en: "Empezó el lunes." },
          { es: "The party started at nine.", en: "La fiesta empezó a las nueve." },
          { es: "We visited them last May.", en: "Los visitamos en mayo del año pasado." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "es-en",
            prompt: "Traduce al inglés.",
            source: "Me mudé a Miami en 2019.",
            answer: "I moved to Miami in 2019.",
            altAnswers: ["In 2019 I moved to Miami."],
            explanation: "Con años se usa \"in\": \"in 2019\". «Mudarse» es \"move\" → \"moved\".",
          },
        ],
      },
      {
        heading: "«Hace dos años»: \"two years ago\"",
        body: [
          "Para «hace» + tiempo en pasado, el inglés pone \"ago\" detrás: \"two years ago\" («hace dos años»), \"a week ago\", \"ten minutes ago\".",
          "El orden es al revés que en español. No digas *ago two years ni, por supuesto, *hace two years. Y no uses \"make\" ni \"do\" para traducir «hace».",
          "\"Ago\" siempre va con el pasado simple: \"I started two months ago\".",
        ],
        examples: [
          { es: "I moved here two years ago.", en: "Me mudé aquí hace dos años." },
          { es: "She called ten minutes ago.", en: "Llamó hace diez minutos." },
          { es: "We visited Tom a week ago.", en: "Visitamos a Tom hace una semana." },
          { es: "It happened a long time ago.", en: "Pasó hace mucho tiempo." },
        ],
        checkpoint: [
          {
            type: "word-order",
            prompt: "Ordena las palabras.",
            words: ["She", "called", "ten", "minutes", "ago."],
            translation: "Llamó hace diez minutos.",
            explanation: "\"Ago\" va detrás de la cantidad de tiempo: \"ten minutes ago\".",
          },
          {
            type: "translate",
            direction: "es-en",
            prompt: "Traduce al inglés.",
            source: "Me mudé aquí hace dos años.",
            answer: "I moved here two years ago.",
            altAnswers: ["Two years ago I moved here."],
            explanation: "«Hace dos años» = \"two years ago\": primero el tiempo y después \"ago\".",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "La llamé ayer por la mañana.",
        answer: "I called her yesterday morning.",
        altAnswers: ["Yesterday morning I called her."],
        explanation: "\"Yesterday morning\", sin \"in the\". «La» como objeto de persona es \"her\".",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "I started the course ___.",
        answer: "last week",
        en: "Empecé el curso [la semana pasada].",
        explanation: "«La semana pasada» es \"last week\", sin \"the\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Ella empezó a trabajar aquí hace un mes.",
        answer: "She started working here a month ago.",
        altAnswers: ["She started to work here a month ago.", "She started working here one month ago.", "She started to work here one month ago.", "A month ago she started working here."],
        explanation: "«Hace un mes» = \"a month ago\", con \"ago\" detrás.",
      },
      {
        type: "multiple-choice",
        question: "¿Cuál es correcta?",
        options: ["We visited them three years ago.", "We visited them ago three years.", "We visited them before three years.", "We visited them hace three years."],
        correctIndex: 0,
        explanation: "\"Ago\" va detrás del tiempo: \"three years ago\". *Before three years es un calco que no se usa.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Anoche llovió mucho.",
        answer: "It rained a lot last night.",
        altAnswers: ["Last night it rained a lot.", "It rained hard last night.", "Last night it rained hard."],
        explanation: "«Anoche» es \"last night\". La lluvia necesita el sujeto \"it\".",
      },
      {
        type: "multiple-choice",
        question: "¿Qué significa \"the last week of the course\"?",
        options: ["La última semana del curso.", "La semana pasada del curso.", "El curso de la semana pasada.", "Hace una semana del curso."],
        correctIndex: 0,
        explanation: "\"The last\" es «el último» o «la última». «La semana pasada» sería \"last week\", sin \"the\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Viajamos a Colombia el verano pasado.",
        answer: "We traveled to Colombia last summer.",
        altAnswers: ["We travelled to Colombia last summer.", "Last summer we traveled to Colombia.", "Last summer we travelled to Colombia."],
        explanation: "\"Last summer\" sin \"the\" y sin \"in\". \"Traveled\" (EE. UU.) o \"travelled\" (Reino Unido).",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Fue la última vez.",
        answer: "It was the last time.",
        altAnswers: ["That was the last time."],
        explanation: "«La última vez» es \"the last time\": aquí sí lleva \"the\", porque es la última de una serie.",
      },
      {
        type: "matching",
        instructions: "Une cada expresión con su significado.",
        pairs: [
          { left: "the day before yesterday", right: "anteayer" },
          { left: "yesterday evening", right: "ayer por la noche (temprano)" },
          { left: "a long time ago", right: "hace mucho tiempo" },
          { left: "last Monday", right: "el lunes pasado" },
        ],
        explanation: "Ninguna de estas expresiones lleva preposición: se dice \"last Monday\", no *on last Monday.",
      },
      {
        type: "dictation",
        audio: "We moved to this city two years ago.",
        explanation: "\"Two years ago\": el tiempo primero y \"ago\" al final.",
      },
    ],
  },
  // ---------------------------------------------------------------------
  {
    slug: "a2-error-hunt-past-simple",
    level: "EN-A2",
    number: 8,
    title: "Caza de errores: el pasado simple",
    summary: "Repaso de la unidad: encuentra y corrige los errores típicos con \"was/were\", \"-ed\" y \"did\".",
    duration: "12 min",
    sections: [
      {
        heading: "Errores con \"did\"",
        body: [
          "El error número uno es marcar el pasado dos veces: *I didn't worked, *Did she called?. Recuerda: \"did\" ya es pasado, así que el verbo va en forma base.",
          "El segundo es olvidar \"did\": *Where you worked? o *I no worked. En preguntas y negativas con verbos normales, \"did\" es obligatorio.",
        ],
        examples: [
          { es: "I didn't work.", en: "No trabajé. (incorrecto: *I didn't worked.)" },
          { es: "Did she call?", en: "¿Llamó? (incorrecto: *Did she called?)" },
          { es: "Where did you work?", en: "¿Dónde trabajaste? (incorrecto: *Where you worked?)" },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "¿Cuál es la versión correcta de \"Did she called you?\"",
            options: ["Did she call you?", "Did she calls you?", "She did called you?", "Does she called you?"],
            correctIndex: 0,
            explanation: "Con \"did\" el verbo va en forma base: \"call\".",
          },
          {
            type: "translate",
            direction: "es-en",
            prompt: "Traduce al inglés.",
            source: "¿Dónde trabajaste el año pasado?",
            answer: "Where did you work last year?",
            explanation: "Palabra interrogativa + \"did\" + sujeto + forma base. Sin \"did\" (*Where you worked?) no es una pregunta correcta.",
          },
        ],
      },
      {
        heading: "Errores de tiempo: \"last\" y \"ago\"",
        body: [
          "*The last week no es «la semana pasada»: es \"last week\", sin \"the\". Y «hace dos años» es \"two years ago\", con \"ago\" detrás.",
          "Tampoco olvides poner el verbo en pasado cuando hay una expresión de pasado: *Yesterday I work está mal.",
        ],
        examples: [
          { es: "I visited Tom last week.", en: "Visité a Tom la semana pasada. (incorrecto: *the last week)" },
          { es: "She arrived two days ago.", en: "Llegó hace dos días. (incorrecto: *ago two days)" },
          { es: "Yesterday I worked from home.", en: "Ayer trabajé desde casa. (incorrecto: *Yesterday I work)" },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "es-en",
            prompt: "Traduce al inglés.",
            source: "Ella llegó hace dos días.",
            answer: "She arrived two days ago.",
            altAnswers: ["Two days ago she arrived."],
            explanation: "\"Two days ago\": el tiempo y después \"ago\". \"Arrive\" termina en \"e\", así que solo se añade \"-d\".",
          },
        ],
      },
      {
        heading: "Errores con \"to be\" y con el sujeto",
        body: [
          "La edad y las sensaciones van con \"was/were\": \"I was 20\", \"We were hungry\". Y «había» es \"there was/there were\".",
          "\"Agree\" (estar de acuerdo) es un verbo, no un adjetivo: «estaba de acuerdo» o «estuve de acuerdo» es \"I agreed\", no *I was agree.",
          "Y nunca omitas el sujeto: \"It was cold\", \"She worked late\", no *Was cold ni *Worked late.",
        ],
        examples: [
          { es: "I agreed with her.", en: "Estuve de acuerdo con ella." },
          { es: "I was twenty.", en: "Tenía veinte años." },
          { es: "There were five people.", en: "Había cinco personas." },
          { es: "It was cold.", en: "Hacía frío." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "es-en",
            prompt: "Traduce al inglés.",
            source: "Estuve de acuerdo con ella.",
            answer: "I agreed with her.",
            explanation: "«Estar de acuerdo» es el verbo \"agree\": en pasado, \"agreed\". *I was agree no es correcto.",
          },
        ],
      },
      {
        heading: "Errores de ortografía",
        body: [
          "Repasa las reglas: \"study\" → \"studied\" (no *studyed), \"play\" → \"played\" (no *plaied), \"stop\" → \"stopped\" (no *stoped), \"live\" → \"lived\" (no *liveed).",
        ],
        examples: [
          { es: "studied", en: "estudié" },
          { es: "played", en: "jugué" },
          { es: "stopped", en: "paré" },
          { es: "lived", en: "viví" },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "¿Qué frase no tiene errores de ortografía?",
            options: ["We planned the trip and stayed in Lima.", "We planed the trip and stayed in Lima.", "We planned the trip and staied in Lima.", "We planed the trip and staied in Lima."],
            correctIndex: 0,
            explanation: "\"Plan\" dobla la \"n\" (\"planned\") y \"stay\" conserva la \"y\" porque va después de una vocal (\"stayed\").",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "multiple-choice",
        question: "¿Cuál es la versión correcta de \"I didn't worked yesterday\"?",
        options: ["I didn't work yesterday.", "I didn't works yesterday.", "I no worked yesterday.", "I don't worked yesterday."],
        correctIndex: 0,
        explanation: "\"Didn't\" + forma base: \"didn't work\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "La semana pasada estudié mucho.",
        answer: "Last week I studied a lot.",
        altAnswers: ["I studied a lot last week.", "Last week I studied hard.", "I studied hard last week."],
        explanation: "\"Last week\" sin \"the\", y \"studied\" con \"-ied\" (consonante + \"y\").",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Cuando tenía veinte años, vivía en Buenos Aires.",
        answer: "When I was twenty, I lived in Buenos Aires.",
        altAnswers: ["When I was 20, I lived in Buenos Aires.", "When I was twenty years old, I lived in Buenos Aires.", "When I was 20 years old, I lived in Buenos Aires.", "I lived in Buenos Aires when I was twenty.", "I lived in Buenos Aires when I was 20."],
        explanation: "La edad va con \"was\" (no \"had\"), y para una situación terminada en el pasado basta el pasado simple: \"I lived\".",
      },
      {
        type: "multiple-choice",
        question: "¿Cuál es correcta?",
        options: ["Did you enjoy the concert?", "Did you enjoyed the concert?", "You enjoyed the concert did?", "Do you enjoyed the concert?"],
        correctIndex: 0,
        explanation: "\"Did\" + sujeto + forma base (\"enjoy\").",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "No estuvimos de acuerdo.",
        answer: "We didn't agree.",
        altAnswers: ["We disagreed."],
        explanation: "\"Agree\" es un verbo, así que la negativa en pasado es \"didn't agree\". *We weren't agree no es correcto.",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "___ a lot of people at the concert.",
        answer: "There were",
        en: "[Había] mucha gente en el concierto.",
        explanation: "«Había» con un plural (\"people\") es \"there were\". \"It was\" o \"It had\" no sirven.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "¿Qué estudió tu hermana?",
        answer: "What did your sister study?",
        explanation: "\"What\" + \"did\" + \"your sister\" + \"study\". No *What your sister studied?.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "El tren paró hace cinco minutos.",
        answer: "The train stopped five minutes ago.",
        altAnswers: ["Five minutes ago the train stopped."],
        explanation: "\"Stopped\" con doble \"p\", y \"five minutes ago\" con \"ago\" al final.",
      },
      {
        type: "word-order",
        prompt: "Ordena las palabras.",
        words: ["It", "was", "very", "hot", "last", "summer."],
        translation: "El verano pasado hizo mucho calor.",
        explanation: "El tiempo lleva \"it\" como sujeto, y \"last summer\" va sin \"the\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Ellos no llegaron a tiempo.",
        answer: "They didn't arrive on time.",
        explanation: "\"Didn't\" + forma base (\"arrive\"). «A tiempo» es \"on time\".",
      },
      {
        type: "listen-choose",
        audio: "Did you visit your parents last weekend?",
        question: "¿Qué te preguntan?",
        options: ["¿Visitaste a tus padres el fin de semana pasado?", "¿Visitaste a tus parientes el fin de semana pasado?", "¿Vas a visitar a tus padres este fin de semana?", "¿Visitaron tus padres el fin de semana pasado?"],
        correctIndex: 0,
        explanation: "\"Parents\" es «padres» (padre y madre), no «parientes», que en inglés es \"relatives\".",
      },
    ],
  },
  // ---------------------------------------------------------------------
  {
    slug: "a2-past-simple-in-practice",
    level: "EN-A2",
    number: 9,
    title: "El pasado simple en la práctica: tu fin de semana",
    summary: "La charla del lunes por la mañana: \"How was your weekend?\", \"What did you do?\" y cómo responder con naturalidad.",
    duration: "12 min",
    sections: [
      {
        heading: "\"How was your weekend?\"",
        body: [
          "El lunes, en el trabajo o en clase, es muy normal que te pregunten \"How was your weekend?\" («¿qué tal el fin de semana?»). Es una pregunta con \"was\", así que no lleva \"did\".",
          "Respuestas típicas: \"It was great\", \"It was good, thanks\", \"It was OK\", \"It was quiet\" («tranquilo»), \"It was busy\" («movido», «de mucho trabajo»). Fíjate en el sujeto \"it\".",
          "Lo natural es devolver la pregunta: \"How about you?\" o \"And you?\".",
        ],
        examples: [
          { es: "How was your weekend?", en: "¿Qué tal el fin de semana?" },
          { es: "It was great, thanks.", en: "Estuvo genial, gracias." },
          { es: "It was quiet.", en: "Fue tranquilo." },
          { es: "It was really busy.", en: "Fue muy movido." },
          { es: "How about you?", en: "¿Y tú?" },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "es-en",
            prompt: "Traduce al inglés.",
            source: "Estuvo genial, gracias. ¿Y tú?",
            answer: "It was great, thanks. How about you?",
            altAnswers: ["It was great, thanks. And you?", "It was great, thank you. How about you?", "It was great, thank you. And you?", "It was great, thanks. What about you?"],
            explanation: "El sujeto \"it\" es obligatorio: \"It was great\". Para devolver la pregunta, \"How about you?\" o \"And you?\".",
          },
        ],
      },
      {
        heading: "\"What did you do?\"",
        body: [
          "Después suele venir \"What did you do?\" («¿qué hiciste?») o \"Did you do anything fun?\" («¿hiciste algo divertido?»).",
          "Al responder, cambia \"you\" por \"I\" y usa el pasado: \"What did you do?\" → \"I stayed at home and watched a movie\". No repitas \"did\" en la respuesta afirmativa: \"I did stay at home\" solo se usa para insistir.",
          "Verbos regulares muy útiles para el fin de semana: \"stayed\", \"relaxed\", \"cooked\", \"cleaned\", \"visited\", \"played\", \"walked\", \"watched\", \"shopped\", \"tried\".",
        ],
        examples: [
          { es: "What did you do?", en: "¿Qué hiciste?" },
          { es: "I stayed at home and relaxed.", en: "Me quedé en casa y descansé." },
          { es: "I visited my parents.", en: "Visité a mis padres." },
          { es: "We cooked for some friends.", en: "Cocinamos para unos amigos." },
          { es: "We walked in the park.", en: "Paseamos por el parque." },
          { es: "I tried a new restaurant.", en: "Probé un restaurante nuevo." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "es-en",
            prompt: "Traduce al inglés.",
            source: "Visité a mis padres.",
            answer: "I visited my parents.",
            explanation: "\"Parents\" es «padres» (padre y madre). Cuidado: no significa «parientes», que es \"relatives\".",
          },
          {
            type: "multiple-choice",
            question: "Te preguntan \"What did you do on Saturday?\". ¿Qué respuesta es correcta y natural?",
            options: ["I cleaned the house.", "I did clean the house.", "I clean the house.", "Cleaned the house I did."],
            correctIndex: 0,
            explanation: "Se responde con el pasado simple y el sujeto \"I\": \"I cleaned the house\". No hace falta \"did\" en una respuesta afirmativa.",
          },
        ],
      },
      {
        heading: "Seguir la conversación",
        body: [
          "Para mostrar interés, haz preguntas cortas con \"did\" o \"was\": \"Did you enjoy it?\", \"Was it good?\", \"Where did you go?\".",
          "Y responde con respuestas cortas: \"Yes, I did\", \"Yes, it was\", \"No, not really\". Si algo no salió bien: \"It rained all weekend\", \"I didn't do much\" («no hice gran cosa»).",
        ],
        examples: [
          { es: "Did you enjoy it? Yes, I did.", en: "¿Lo disfrutaste? Sí." },
          { es: "Was it good? Yes, it was.", en: "¿Estuvo bien? Sí." },
          { es: "I didn't do much.", en: "No hice gran cosa." },
          { es: "It rained all weekend.", en: "Llovió todo el fin de semana." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "es-en",
            prompt: "Traduce al inglés.",
            source: "No hice gran cosa.",
            answer: "I didn't do much.",
            altAnswers: ["I didn't do a lot.", "I didn't do anything special."],
            explanation: "\"Didn't\" + \"do\" (forma base). \"Not much\" es la forma natural de decir «no gran cosa».",
          },
          {
            type: "fill-blank",
            prompt: "Escribe en inglés las palabras en negrita.",
            sentence: "Was the restaurant good? Yes, ___.",
            answer: "it was",
            en: "¿Estuvo bueno el restaurante? Sí, [estuvo bueno].",
            explanation: "La pregunta usa \"was\", así que la respuesta corta es \"Yes, it was\", no *Yes, it did.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "¿Qué tal tu fin de semana?",
        answer: "How was your weekend?",
        explanation: "«¿Qué tal...?» sobre el pasado es \"How was...?\". No lleva \"did\" porque el verbo es \"to be\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "¿Qué hiciste el sábado?",
        answer: "What did you do on Saturday?",
        explanation: "\"What did you do...?\": \"did\" es el auxiliar y \"do\" es el verbo «hacer». Con días se usa \"on\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "El domingo cocinamos para unos amigos.",
        answer: "On Sunday we cooked for some friends.",
        altAnswers: ["We cooked for some friends on Sunday.", "On Sunday we cooked for friends.", "We cooked for friends on Sunday."],
        explanation: "\"Cooked\" (una sílaba, /kʊkt/). «Unos amigos» puede ser \"some friends\" o simplemente \"friends\".",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "Did you enjoy the concert? Yes, I ___.",
        answer: "did",
        en: "¿Disfrutaste del concierto? Sí, [lo disfruté].",
        explanation: "Respuesta corta: \"Yes, I did\". La pregunta es con \"you\" y la respuesta con \"I\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Llovió todo el fin de semana, así que me quedé en casa.",
        answer: "It rained all weekend, so I stayed at home.",
        altAnswers: ["It rained all weekend, so I stayed home.", "It rained the whole weekend, so I stayed at home.", "It rained the whole weekend, so I stayed home."],
        explanation: "\"It rained\" con sujeto, y \"stayed\" con \"y\" (vocal + \"y\" no cambia).",
      },
      {
        type: "multiple-choice",
        question: "Tu compañero dice \"I visited my parents in Puebla.\" ¿Qué pregunta es la más natural para seguir la conversación?",
        options: ["Did you have a good time?", "Did you had a good time?", "You had a good time did?", "Do you had a good time?"],
        correctIndex: 0,
        explanation: "\"Did\" + sujeto + forma base: \"Did you have a good time?\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "¿Adónde fueron ustedes?",
        answer: "Where did you go?",
        explanation: "\"Where\" + \"did\" + \"you\" + \"go\" (forma base). \"You\" sirve para «ustedes».",
      },
      {
        type: "word-order",
        prompt: "Ordena las palabras.",
        words: ["We", "walked", "in", "the", "park", "on", "Sunday."],
        translation: "El domingo paseamos por el parque.",
        explanation: "«Pasear» es \"walk\" (o \"go for a walk\"): \"walked\" tiene una sola sílaba, /wɔkt/.",
      },
      {
        type: "listen-choose",
        audio: "It was quiet. I didn't do much.",
        question: "¿Qué tal fue su fin de semana?",
        options: ["Tranquilo, no hizo gran cosa.", "Muy movido, hizo muchas cosas.", "Ruidoso, no pudo dormir.", "Aburrido, trabajó todo el tiempo."],
        correctIndex: 0,
        explanation: "\"Quiet\" es «tranquilo» y \"I didn't do much\" es «no hice gran cosa».",
      },
      {
        type: "speak",
        text: "It was great, thanks. I stayed at home and relaxed. How about you?",
        tip: "\"Stayed\" /steɪd/ y \"relaxed\" /rɪˈlækst/: ninguna \"-ed\" añade sílaba. El acento de \"relaxed\" va en la segunda sílaba.",
        explanation: "Una respuesta completa y natural: valoración, lo que hiciste y la pregunta de vuelta.",
      },
      {
        type: "write",
        prompt: "Un compañero te pregunta \"How was your weekend? What did you do?\". Escribe tu respuesta: cuenta cómo fue, qué hiciste y qué no hiciste, y termina con una pregunta para él.",
        minWords: 35,
        maxWords: 80,
        rubric: [
          "Empieza con \"It was...\" para valorar el fin de semana.",
          "Usa al menos cuatro verbos regulares en pasado.",
          "Incluye al menos una negativa con \"didn't\" + forma base.",
          "Termina con una pregunta con \"did\" o \"was\".",
        ],
        modelAnswer: "It was really nice, thanks. On Saturday morning I cleaned the apartment and then I visited my parents. We cooked together and talked for hours. On Sunday it rained, so I stayed at home and watched a movie. I didn't do much, but I relaxed. How about you? Did you do anything fun?",
        explanation: "Revisa que cada frase tenga sujeto, que los verbos estén en pasado y que después de \"didn't\" y \"did\" el verbo vaya en forma base.",
      },
    ],
  },
];
