// Synced from cheneygross-afk/lengo:src/lib/lessons/en-a2-u02-extra.ts by scripts/sync-content.mjs -- edit it there, not here.
import type { Lesson } from "./types";

// Extra practice (optional) lessons for EN-A2 unit u02.

export const EN_A2_U02_EXTRA: Lesson[] = [  // ---------------------------------------------------------------------
  {
    slug: "en-a2-irregular-past-drill-1",
    optional: true,
    level: "EN-A2",
    number: 1,
    title: "Práctica extra: los irregulares más frecuentes",
    summary: "Práctica intensiva de los pasados irregulares más usados (\"went\", \"had\", \"saw\", \"made\", \"got\", \"came\", \"took\", \"gave\", \"said\", \"told\"...) y de la diferencia entre \"said\" y \"told\".",
    duration: "11 min",
    sections: [
      {
        heading: "Recordatorio: los diez de siempre",
        body: [
          "Estos verbos aparecen en casi cualquier conversación sobre el pasado: \"go\" → \"went\", \"have\" → \"had\", \"see\" → \"saw\", \"make\" → \"made\", \"get\" → \"got\", \"come\" → \"came\", \"take\" → \"took\", \"give\" → \"gave\", \"say\" → \"said\", \"tell\" → \"told\".",
          "No los regularices: *goed, *haved, *buyed o *taked no existen. Y recuerda que la forma irregular solo se usa en la afirmativa: \"I went\", pero \"I didn't go\" y \"Did you go?\".",
        ],
        examples: [
          { es: "We went to the beach.", en: "Fuimos a la playa." },
          { es: "I had a sandwich.", en: "Me comí un sándwich." },
          { es: "She got a new job.", en: "Consiguió un trabajo nuevo." },
          { es: "They came by car.", en: "Vinieron en coche." },
          { es: "He took a lot of photos.", en: "Sacó muchas fotos." },
        ],
        checkpoint: [
          {
            type: "fill-blank",
            prompt: "Escribe en inglés las palabras en negrita.",
            sentence: "My grandmother ___ me a watch.",
            answer: "gave",
            en: "Mi abuela me [dio] un reloj.",
            explanation: "\"Give\" es irregular: \"gave\". *gived no existe.",
          },
        ],
      },
      {
        heading: "Recordatorio: \"said\" o \"told\"",
        body: [
          "Los dos significan «dijo», pero se construyen distinto. \"Tell\" (\"told\") necesita a la persona justo detrás: \"She told me the truth\", \"He told us a story\".",
          "\"Say\" (\"said\") no lleva a la persona detrás; si la mencionas, va con \"to\": \"She said hello\", \"He said something to me\". Por eso *She said me es incorrecto.",
        ],
        examples: [
          { es: "She told me the news.", en: "Me contó la noticia." },
          { es: "He said goodbye.", en: "Dijo adiós." },
          { es: "They told us a story.", en: "Nos contaron una historia." },
          { es: "What did he say to you?", en: "¿Qué te dijo?" },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "¿Qué frase es correcta?",
            options: ["She told me her name.", "She said me her name.", "She told to me her name.", "She say me her name."],
            correctIndex: 0,
            explanation: "\"Tell\" lleva a la persona directamente detrás: \"told me\". \"Said\" no puede ir seguido de \"me\".",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "I ___ a strange noise.",
        answer: "heard",
        en: "[Oí] un ruido extraño.",
        explanation: "\"Hear\" es irregular: \"heard\" (suena /hɜrd/, como \"bird\"). *Heared no existe.",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "We ___ a lot of money on the trip.",
        answer: "spent",
        en: "[Gastamos] mucho dinero en el viaje.",
        explanation: "\"Spend\" (gastar dinero, pasar tiempo) → \"spent\".",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "He ___ to the store for some milk.",
        answer: "went",
        en: "[Fue] a la tienda a comprar leche.",
        explanation: "\"Go\" → \"went\". La forma no se parece nada al verbo base, por eso hay que memorizarla.",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "They ___ dinner at nine.",
        answer: "had",
        altAnswers: ["ate"],
        en: "[Cenaron] a las nueve.",
        explanation: "«Cenar» es \"have dinner\", y su pasado es \"had dinner\". También es correcto \"ate dinner\".",
      },
      {
        type: "multiple-choice",
        question: "¿Cuál es el pasado de \"buy\"?",
        options: ["bought", "buyed", "brought", "boughted"],
        correctIndex: 0,
        explanation: "\"Buy\" → \"bought\". No lo confundas con \"brought\" (pasado de \"bring\", traer).",
      },
      {
        type: "multiple-choice",
        question: "¿Cuál es el pasado de \"think\"?",
        options: ["thought", "thinked", "thank", "taught"],
        correctIndex: 0,
        explanation: "\"Think\" → \"thought\". \"Taught\" es el pasado de \"teach\" (enseñar).",
      },
      {
        type: "multiple-choice",
        question: "Completa: \"He ___ us about his trip.\"",
        options: ["told", "said", "talked us", "say"],
        correctIndex: 0,
        explanation: "La persona (\"us\") va justo detrás del verbo, así que es \"told\". *said us es incorrecto.",
      },
      {
        type: "matching",
        instructions: "Une cada verbo con su pasado.",
        pairs: [
          { left: "know", right: "knew" },
          { left: "write", right: "wrote" },
          { left: "eat", right: "ate" },
          { left: "drink", right: "drank" },
          { left: "leave", right: "left" },
          { left: "find", right: "found" },
        ],
        explanation: "Seis irregulares muy frecuentes. \"Knew\" se pronuncia como \"new\" (la \"k\" es muda) y \"ate\" suena /eɪt/, como \"eight\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Mi madre hizo la cena.",
        answer: "My mother made dinner.",
        altAnswers: ["My mom made dinner.", "My mother cooked dinner.", "My mom cooked dinner.", "My mother made the dinner.", "My mom made the dinner."],
        explanation: "Preparar comida es \"make\" → \"made\". *My mother did dinner no se dice.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Ellos vinieron a la boda.",
        answer: "They came to the wedding.",
        explanation: "\"Come\" → \"came\". *Comed no existe.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Sacamos muchas fotos en Roma.",
        answer: "We took a lot of photos in Rome.",
        altAnswers: ["We took a lot of pictures in Rome.", "We took many photos in Rome.", "We took many pictures in Rome.", "We took lots of photos in Rome.", "We took lots of pictures in Rome."],
        explanation: "«Sacar una foto» es \"take a photo\", y su pasado es \"took\". No uses *made photos.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Ella me dijo la verdad.",
        answer: "She told me the truth.",
        explanation: "\"Tell the truth\" es la expresión fija, y \"told\" lleva a la persona detrás: \"told me\". *She said me the truth es incorrecto.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Él dijo que estaba cansado.",
        answer: "He said that he was tired.",
        altAnswers: ["He said he was tired."],
        explanation: "Sin persona detrás se usa \"said\": \"He said (that) he was tired\". El \"that\" es opcional.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Recibí tu correo ayer.",
        answer: "I got your email yesterday.",
        altAnswers: ["Yesterday I got your email.", "I received your email yesterday.", "Yesterday I received your email.", "I got your e-mail yesterday.", "I received your e-mail yesterday."],
        explanation: "«Recibir» se dice muy a menudo \"get\" → \"got\". \"Received\" también es correcto, pero más formal.",
      },
      {
        type: "word-order",
        prompt: "Ordena las palabras.",
        words: ["I", "saw", "your", "brother", "at", "the", "station."],
        translation: "Vi a tu hermano en la estación.",
        altOrders: [["At", "the", "station", "I", "saw", "your", "brother."]],
        explanation: "\"See\" → \"saw\". En inglés no hay «a» personal: \"I saw your brother\", sin preposición.",
      },
      {
        type: "listen-choose",
        audio: "She left early and took a taxi.",
        question: "¿Qué has oído?",
        options: ["Se fue temprano y tomó un taxi.", "Llegó temprano y tomó un taxi.", "Se fue tarde y tomó un taxi.", "Se fue temprano y llamó a un taxi."],
        correctIndex: 0,
        explanation: "\"Left\" es el pasado de \"leave\" (irse) y \"took\" el de \"take\" (tomar).",
      },
      {
        type: "dictation",
        audio: "I bought a coffee and read the newspaper.",
        explanation: "\"Bought\" (de \"buy\") y \"read\": el pasado de \"read\" se escribe igual pero se pronuncia /red/, como \"red\".",
      },
    ],
  },
  // ---------------------------------------------------------------------
  {
    slug: "en-a2-irregular-past-drill-2",
    optional: true,
    level: "EN-A2",
    number: 2,
    title: "Práctica extra: más verbos irregulares",
    summary: "Segundo repaso de irregulares: \"lost\", \"found\", \"left\", \"felt\", \"kept\", \"sent\", \"spent\", \"paid\", \"fell\", \"broke\", \"forgot\", \"won\". Con las confusiones típicas: \"felt\" / \"fell\" y \"left\" / \"lived\".",
    duration: "11 min",
    sections: [
      {
        heading: "Recordatorio: grupos que se parecen",
        body: [
          "Muchos irregulares terminan en \"-t\": \"lose\" → \"lost\", \"leave\" → \"left\", \"feel\" → \"felt\", \"keep\" → \"kept\", \"send\" → \"sent\", \"spend\" → \"spent\".",
          "Otros cambian la vocal: \"fall\" → \"fell\", \"win\" → \"won\" (suena como \"one\"), \"break\" → \"broke\", \"forget\" → \"forgot\", \"find\" → \"found\".",
          "Ojo con la ortografía de \"pay\": su pasado es \"paid\", no *payed. (\"Say\" → \"said\" sigue el mismo patrón.)",
        ],
        examples: [
          { es: "I lost my wallet.", en: "Perdí la cartera." },
          { es: "She found it under the bed.", en: "Lo encontró debajo de la cama." },
          { es: "We paid fifty dollars.", en: "Pagamos cincuenta dólares." },
          { es: "He broke his arm.", en: "Se rompió el brazo." },
          { es: "Our team won the game.", en: "Nuestro equipo ganó el partido." },
          { es: "I forgot her birthday.", en: "Me olvidé de su cumpleaños." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "¿Cuál es el pasado de \"pay\"?",
            options: ["paid", "payed", "pait", "pied"],
            correctIndex: 0,
            explanation: "\"Pay\" → \"paid\", igual que \"say\" → \"said\". *Payed es un error de ortografía muy común.",
          },
        ],
      },
      {
        heading: "Recordatorio: parejas que se confunden",
        body: [
          "\"Felt\" es el pasado de \"feel\" (sentir): \"I felt sick\". \"Fell\" es el pasado de \"fall\" (caer): \"I fell down\".",
          "\"Left\" es el pasado de \"leave\" (irse, dejar): \"She left at six\". \"Lived\" es el pasado de \"live\" (vivir): \"She lived in Peru\". Suenan parecido para un hispanohablante, pero significan cosas muy distintas.",
          "\"Lost\" es perder algo (\"I lost my keys\"); para «perder» un tren o un autobús se usa \"missed\": \"I missed the bus\".",
        ],
        examples: [
          { es: "I felt tired.", en: "Me sentía cansado." },
          { es: "The glass fell on the floor.", en: "El vaso se cayó al suelo." },
          { es: "He left the house at seven.", en: "Salió de casa a las siete." },
          { es: "He lived in that house.", en: "Vivía en esa casa." },
          { es: "We missed the train.", en: "Perdimos el tren." },
        ],
        checkpoint: [
          {
            type: "fill-blank",
            prompt: "Escribe en inglés las palabras en negrita.",
            sentence: "My little brother ___ off his bike.",
            answer: "fell",
            en: "Mi hermano pequeño [se cayó] de la bici.",
            explanation: "«Caerse» es \"fall\" → \"fell\". \"Felt\" es de \"feel\" (sentir).",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "I ___ really happy that day.",
        answer: "felt",
        altAnswers: ["was"],
        en: "Ese día [me sentí] muy feliz.",
        explanation: "«Sentirse» es \"feel\" → \"felt\". No confundas con \"fell\" (caerse).",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "She ___ her phone on the bus.",
        answer: "left",
        en: "[Se dejó] el teléfono en el autobús.",
        explanation: "«Dejarse algo» en un lugar es \"leave\" → \"left\".",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "We ___ a postcard to our grandparents.",
        answer: "sent",
        en: "[Mandamos] una postal a nuestros abuelos.",
        explanation: "\"Send\" → \"sent\". *Sended no existe.",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "He ___ the money in a box.",
        answer: "kept",
        en: "[Guardaba] el dinero en una caja.",
        explanation: "«Guardar» en el sentido de conservar es \"keep\" → \"kept\". *Keeped no existe.",
      },
      {
        type: "multiple-choice",
        question: "¿Cómo se dice «Perdí el autobús»?",
        options: ["I missed the bus.", "I lost the bus.", "I losed the bus.", "I left the bus."],
        correctIndex: 0,
        explanation: "No llegar a tiempo a un transporte es \"miss\": \"I missed the bus\". \"Lost\" es para objetos que no encuentras.",
      },
      {
        type: "multiple-choice",
        question: "¿Cómo se pronuncia \"won\" (pasado de \"win\")?",
        options: ["Como \"one\"", "Como \"own\"", "Como \"won't\"", "Como \"when\""],
        correctIndex: 0,
        explanation: "\"Won\" suena exactamente igual que \"one\": /wʌn/.",
      },
      {
        type: "multiple-choice",
        question: "¿Qué frase es correcta?",
        options: ["I forgot my password.", "I forgotted my password.", "I forget my password yesterday.", "I forgetted my password."],
        correctIndex: 0,
        explanation: "\"Forget\" → \"forgot\". Con \"yesterday\" el verbo tiene que ir en pasado.",
      },
      {
        type: "matching",
        instructions: "Une cada verbo con su pasado.",
        pairs: [
          { left: "lose", right: "lost" },
          { left: "fall", right: "fell" },
          { left: "feel", right: "felt" },
          { left: "break", right: "broke" },
          { left: "win", right: "won" },
          { left: "spend", right: "spent" },
        ],
        explanation: "Fíjate en \"fall\" → \"fell\" y \"feel\" → \"felt\": son las dos formas que más se confunden.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Encontré mis llaves en la cocina.",
        answer: "I found my keys in the kitchen.",
        explanation: "\"Find\" → \"found\". En inglés se usa el posesivo (\"my keys\") donde el español suele decir «las llaves».",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Pagué la cuenta.",
        answer: "I paid the bill.",
        altAnswers: ["I paid the check."],
        explanation: "\"Pay\" → \"paid\" (nunca *payed). En un restaurante, «la cuenta» es \"the bill\" o, en Estados Unidos, \"the check\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Mi hijo rompió una ventana.",
        answer: "My son broke a window.",
        explanation: "\"Break\" → \"broke\". *Breaked no existe.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Ganamos el primer partido, pero perdimos el segundo.",
        answer: "We won the first game, but we lost the second one.",
        altAnswers: ["We won the first game but we lost the second.", "We won the first game but lost the second.", "We won the first game, but we lost the second.", "We won the first game, but lost the second.", "We won the first game but we lost the second one.", "We won the first game but lost the second one.", "We won the first game, but lost the second one.", "We won the first match but we lost the second.", "We won the first match but lost the second.", "We won the first match, but we lost the second.", "We won the first match, but lost the second.", "We won the first match but we lost the second one.", "We won the first match but lost the second one.", "We won the first match, but we lost the second one.", "We won the first match, but lost the second one."],
        explanation: "\"Win\" → \"won\", \"lose\" → \"lost\". Fíjate: «perder» un partido es \"lose\", no \"miss\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Ella se fue de Chile en 2015.",
        answer: "She left Chile in 2015.",
        altAnswers: ["In 2015 she left Chile."],
        explanation: "«Irse de un lugar» es \"leave\" + lugar, sin preposición: \"She left Chile\". No lo confundas con \"lived\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Pasamos dos semanas en la playa.",
        answer: "We spent two weeks at the beach.",
        altAnswers: ["We spent two weeks on the beach."],
        explanation: "«Pasar tiempo» es \"spend\" → \"spent\". No digas *passed two weeks.",
      },
      {
        type: "word-order",
        prompt: "Ordena las palabras.",
        words: ["He", "fell", "and", "broke", "his", "leg."],
        translation: "Se cayó y se rompió la pierna.",
        explanation: "\"Fell\" (de \"fall\") y \"broke\" (de \"break\"). Con partes del cuerpo el inglés usa el posesivo: \"his leg\".",
      },
      {
        type: "listen-choose",
        audio: "I felt better after the party.",
        question: "¿Qué has oído?",
        options: ["Me sentí mejor después de la fiesta.", "Me caí después de la fiesta.", "Me fui antes de la fiesta.", "Me sentía mal en la fiesta."],
        correctIndex: 0,
        explanation: "\"Felt\" (con t final) es «me sentí». \"Fell\" sería «me caí».",
      },
      {
        type: "dictation",
        audio: "She lost her bag but a man found it.",
        explanation: "\"Lost\" (de \"lose\") y \"found\" (de \"find\"): dos irregulares que suelen ir juntos.",
      },
    ],
  },
  // ---------------------------------------------------------------------
  {
    slug: "en-a2-did-base-form-drill-1",
    optional: true,
    level: "EN-A2",
    number: 3,
    title: "Práctica extra: did + verbo base",
    summary: "Práctica centrada en el error del pasado doble (*Did you went?, *I didn't saw): corrige frases y elige entre la forma base y el pasado con verbos irregulares.",
    duration: "10 min",
    sections: [
      {
        heading: "Recordatorio: el pasado se marca una sola vez",
        body: [
          "En la afirmativa, el verbo lleva el pasado: \"I went\", \"She saw it\". En la negativa y la pregunta, el pasado lo lleva \"did\", y el verbo vuelve a su forma base: \"I didn't go\", \"Did she see it?\".",
          "Truco: si ves \"did\" o \"didn't\" en la frase, el verbo principal NO puede ser \"went\", \"saw\", \"bought\", \"had\"... Tiene que ser \"go\", \"see\", \"buy\", \"have\".",
          "Esto es así incluso con verbos muy irregulares: \"I didn't have time\" (no *didn't had), \"Did you do it?\" (no *Did you did it?).",
        ],
        examples: [
          { es: "I went. / I didn't go.", en: "Fui. / No fui." },
          { es: "She saw it. / Did she see it?", en: "Lo vio. / ¿Lo vio?" },
          { es: "We had time. / We didn't have time.", en: "Tuvimos tiempo. / No tuvimos tiempo." },
          { es: "He did it. / Did he do it?", en: "Lo hizo. / ¿Lo hizo?" },
          { es: "They bought it. / They didn't buy it.", en: "Lo compraron. / No lo compraron." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "Alguien dice *I didn't saw him. ¿Cuál es la corrección?",
            options: ["I didn't see him.", "I don't saw him.", "I no saw him.", "I didn't seen him."],
            correctIndex: 0,
            explanation: "\"Didn't\" ya marca el pasado, así que el verbo va en forma base: \"see\".",
          },
          {
            type: "fill-blank",
            prompt: "Escribe en inglés las palabras en negrita.",
            sentence: "Did you ___ the tickets?",
            answer: "bring",
            en: "¿[Trajiste] las entradas?",
            explanation: "Después de \"did\" va el verbo base: \"bring\", no \"brought\".",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "multiple-choice",
        question: "Corrige: *Did you went to the party?",
        options: ["Did you go to the party?", "Did you goes to the party?", "Do you went to the party?", "You did go to the party?"],
        correctIndex: 0,
        explanation: "\"Did\" + sujeto + verbo base: \"Did you go...?\".",
      },
      {
        type: "multiple-choice",
        question: "Corrige: *She didn't came yesterday.",
        options: ["She didn't come yesterday.", "She doesn't came yesterday.", "She didn't comes yesterday.", "She not came yesterday."],
        correctIndex: 0,
        explanation: "\"Didn't\" + \"come\". Con \"yesterday\" el auxiliar tiene que ser \"didn't\", no \"doesn't\".",
      },
      {
        type: "multiple-choice",
        question: "Corrige: *What did he said?",
        options: ["What did he say?", "What he said?", "What did he says?", "What does he said?"],
        correctIndex: 0,
        explanation: "\"What did he say?\": \"say\" en forma base. *What he said? olvida el auxiliar.",
      },
      {
        type: "multiple-choice",
        question: "¿Qué frase es correcta?",
        options: ["We didn't eat much.", "We didn't ate much.", "We didn't eaten much.", "We don't ate much."],
        correctIndex: 0,
        explanation: "\"Didn't\" + \"eat\". \"Ate\" solo va en la afirmativa: \"We ate a lot\".",
      },
      {
        type: "multiple-choice",
        question: "¿Qué frase es correcta?",
        options: ["Where did they find it?", "Where did they found it?", "Where they found it?", "Where did they finded it?"],
        correctIndex: 0,
        explanation: "Palabra interrogativa + \"did\" + sujeto + verbo base: \"find\".",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "I ___ my homework last night.",
        answer: "did",
        en: "Anoche [hice] los deberes.",
        explanation: "Aquí \"did\" es el verbo «hacer» en pasado afirmativo. En la negativa sería \"I didn't do my homework\".",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "He didn't ___ the answer.",
        answer: "know",
        en: "Él no [sabía] la respuesta.",
        explanation: "Después de \"didn't\", forma base: \"know\", no \"knew\".",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "She ___ a new dress for the wedding.",
        answer: "bought",
        en: "[Se compró] un vestido nuevo para la boda.",
        explanation: "Es una afirmativa, así que el verbo va en pasado: \"bought\". Aquí no hay \"did\".",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "Did your team ___ yesterday?",
        answer: "win",
        en: "¿[Ganó] tu equipo ayer?",
        explanation: "Con \"did\" el verbo va en forma base: \"win\", no \"won\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "No tuvimos tiempo.",
        answer: "We didn't have time.",
        altAnswers: ["We didn't have any time.", "We didn't have enough time."],
        explanation: "\"Didn't have\", nunca *didn't had. El pasado ya está en \"didn't\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "¿Escribiste el correo?",
        answer: "Did you write the email?",
        altAnswers: ["Did you write the e-mail?"],
        explanation: "\"Did you write...?\": \"write\" en forma base, no \"wrote\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Ella no durmió en casa.",
        answer: "She didn't sleep at home.",
        explanation: "\"Didn't sleep\": forma base. \"Slept\" solo en la afirmativa.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "¿Qué hicieron tus amigos el sábado?",
        answer: "What did your friends do on Saturday?",
        altAnswers: ["What did your friends do Saturday?"],
        explanation: "\"What did your friends do?\": \"did\" es el auxiliar y \"do\" es «hacer» en forma base.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Mi padre no condujo; tomó el tren.",
        answer: "My father didn't drive; he took the train.",
        altAnswers: ["My dad didn't drive; he took the train.", "My father didn't drive. He took the train.", "My dad didn't drive. He took the train.", "My father didn't drive, he took the train.", "My dad didn't drive, he took the train."],
        explanation: "Negativa: \"didn't drive\" (base). Afirmativa: \"took\" (pasado). Y la segunda frase necesita el sujeto \"he\".",
      },
      {
        type: "word-order",
        prompt: "Ordena las palabras.",
        words: ["Did", "you", "understand", "the", "question?"],
        translation: "¿Entendiste la pregunta?",
        explanation: "\"Did\" + sujeto + verbo base (\"understand\", no \"understood\").",
      },
      {
        type: "listen-choose",
        audio: "They didn't tell us anything.",
        question: "¿Qué has oído?",
        options: ["No nos dijeron nada.", "No nos dicen nada.", "Nos lo contaron todo.", "No les dijimos nada."],
        correctIndex: 0,
        explanation: "\"They didn't tell us\": el sujeto es \"they\" y \"us\" es «nos». \"Didn't\" indica pasado.",
      },
      {
        type: "dictation",
        audio: "Did you see the game last night?",
        explanation: "\"Did you see...?\": verbo base después de \"did\". «Anoche» es \"last night\".",
      },
    ],
  },
  // ---------------------------------------------------------------------
  {
    slug: "en-a2-was-or-did-drill-1",
    optional: true,
    level: "EN-A2",
    number: 4,
    title: "Práctica extra: ¿was o did?",
    summary: "Práctica de contraste: \"was/were\" con adjetivos, lugares y edades, y \"did\" con los verbos de acción. Sin mezclas como *Did you tired? o *Was you go?",
    duration: "11 min",
    sections: [
      {
        heading: "Recordatorio: dos sistemas que no se mezclan",
        body: [
          "Si la frase usa \"to be\" (con un adjetivo, un lugar, una edad o un nombre), las preguntas y negativas se hacen con \"was\" / \"were\": \"Were you tired?\", \"She wasn't at home\".",
          "Si la frase tiene un verbo de acción (go, like, eat, see...), se usa \"did\": \"Did you go?\", \"She didn't like it\".",
          "Nunca los dos juntos ni cruzados: *Did you tired?, *Was you go?, *Were you like it? son errores típicos. Pregúntate: ¿hay un verbo de acción? Entonces \"did\". ¿No lo hay? Entonces \"was/were\".",
        ],
        examples: [
          { es: "Were you tired?", en: "¿Estabas cansado?" },
          { es: "Did you go out?", en: "¿Saliste?" },
          { es: "Was it expensive?", en: "¿Fue caro?" },
          { es: "Did you like it?", en: "¿Te gustó?" },
          { es: "She wasn't at work.", en: "No estaba en el trabajo." },
          { es: "She didn't work.", en: "No trabajó." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "¿Cómo se dice «¿Estabas nervioso?»?",
            options: ["Were you nervous?", "Did you nervous?", "Did you be nervous?", "Was you nervous?"],
            correctIndex: 0,
            explanation: "\"Nervous\" es un adjetivo, así que va con \"to be\": \"Were you nervous?\". Con \"you\", siempre \"were\".",
          },
          {
            type: "multiple-choice",
            question: "¿Cómo se dice «¿Te gustó el concierto?»?",
            options: ["Did you like the concert?", "Were you like the concert?", "Was you like the concert?", "Did you liked the concert?"],
            correctIndex: 0,
            explanation: "\"Like\" es un verbo de acción, así que la pregunta se hace con \"did\" + verbo base.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "___ you at the gym yesterday?",
        answer: "Were",
        en: "¿[Estuviste] en el gimnasio ayer?",
        explanation: "Para preguntar dónde estaba alguien se usa \"to be\": \"Were you at the gym?\".",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "___ you go to the gym yesterday?",
        answer: "Did",
        en: "¿[Fuiste] al gimnasio ayer?",
        explanation: "\"Go\" es un verbo de acción, así que la pregunta lleva \"did\": \"Did you go...?\".",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "The food ___ very good.",
        answer: "wasn't",
        altAnswers: ["was not"],
        en: "La comida [no estaba] muy buena.",
        explanation: "\"Good\" es un adjetivo: negativa con \"wasn't\". *The food didn't good no es correcto.",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "They ___ the food.",
        answer: "didn't like",
        altAnswers: ["did not like", "didn't enjoy", "did not enjoy"],
        en: "[No les gustó] la comida.",
        explanation: "\"Like\" es un verbo de acción: \"didn't like\". El sujeto en inglés es \"they\" (la persona a la que no le gusta).",
      },
      {
        type: "multiple-choice",
        question: "¿Qué pregunta es correcta?",
        options: ["Was the train late?", "Did the train late?", "Did the train was late?", "Were the train late?"],
        correctIndex: 0,
        explanation: "\"Late\" es un adjetivo: \"Was the train late?\". \"The train\" es singular, así que \"was\".",
      },
      {
        type: "multiple-choice",
        question: "¿Qué pregunta es correcta?",
        options: ["Did the train arrive late?", "Was the train arrive late?", "Was the train arrived late?", "Did the train arrived late?"],
        correctIndex: 0,
        explanation: "\"Arrive\" es un verbo de acción: \"Did the train arrive...?\", con verbo base.",
      },
      {
        type: "multiple-choice",
        question: "Te preguntan \"Did you enjoy the trip?\". ¿Qué respuesta corta es correcta?",
        options: ["Yes, I did.", "Yes, I was.", "Yes, I enjoyed.", "Yes, I do."],
        correctIndex: 0,
        explanation: "La pregunta lleva \"did\", así que la respuesta también: \"Yes, I did\".",
      },
      {
        type: "multiple-choice",
        question: "Te preguntan \"Were you scared?\". ¿Qué respuesta corta es correcta?",
        options: ["No, I wasn't.", "No, I didn't.", "No, I weren't.", "No, I don't."],
        correctIndex: 0,
        explanation: "La pregunta lleva \"were\", así que la respuesta usa \"to be\". Con \"I\" la forma es \"wasn't\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "¿Estabas en la oficina?",
        answer: "Were you in the office?",
        altAnswers: ["Were you at the office?"],
        explanation: "Lugar: \"to be\". \"Were you in the office?\", sin \"did\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "¿Fuiste a la oficina?",
        answer: "Did you go to the office?",
        explanation: "«Ir» es un verbo de acción: \"Did you go...?\". Compara con \"Were you in the office?\" («¿estabas en la oficina?»).",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "¿Tenías hambre?",
        answer: "Were you hungry?",
        explanation: "«Tener hambre» es \"to be hungry\", así que la pregunta usa \"were\", no \"did you have\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "¿Comiste algo?",
        answer: "Did you eat anything?",
        altAnswers: ["Did you eat something?", "Did you have anything to eat?", "Did you have something to eat?"],
        explanation: "\"Eat\" es un verbo de acción: \"Did you eat...?\". En preguntas se suele decir \"anything\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "El examen no fue fácil, pero aprobé.",
        answer: "The exam wasn't easy, but I passed.",
        altAnswers: ["The test wasn't easy, but I passed.", "The exam wasn't easy but I passed.", "The test wasn't easy but I passed.", "The exam wasn't easy, but I passed it.", "The test wasn't easy, but I passed it."],
        explanation: "\"Easy\" es un adjetivo: \"wasn't easy\". «Aprobar» es \"pass\", un verbo de acción: \"I passed\". Ojo: no es *approved.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "¿Dónde estuvieron tus padres y qué hicieron?",
        answer: "Where were your parents and what did they do?",
        altAnswers: ["Where were your parents, and what did they do?"],
        explanation: "«Estar» en un lugar: \"Where were your parents?\". «Hacer»: \"What did they do?\". Los dos sistemas en una pregunta.",
      },
      {
        type: "matching",
        instructions: "Une cada pregunta con su traducción.",
        pairs: [
          { left: "Was it fun?", right: "¿Fue divertido?" },
          { left: "Did you have fun?", right: "¿Te divertiste?" },
          { left: "Were you there?", right: "¿Estabas allí?" },
          { left: "Did you go there?", right: "¿Fuiste allí?" },
        ],
        explanation: "Adjetivos y lugares: \"was/were\". Verbos de acción (\"have fun\", \"go\"): \"did\".",
      },
      {
        type: "word-order",
        prompt: "Ordena las palabras.",
        words: ["Why", "were", "you", "so", "angry?"],
        translation: "¿Por qué estabas tan enfadado?",
        explanation: "\"Angry\" es un adjetivo: \"Why were you so angry?\", sin \"did\".",
      },
      {
        type: "listen-choose",
        audio: "Was the party good? Did many people come?",
        question: "¿Qué te preguntan?",
        options: ["Si la fiesta estuvo bien y si vino mucha gente.", "Si fuiste a la fiesta y con quién.", "Si la fiesta fue larga y si te quedaste.", "Si había comida en la fiesta."],
        correctIndex: 0,
        explanation: "\"Was the party good?\" (adjetivo, \"was\") y \"Did many people come?\" (verbo de acción, \"did\").",
      },
    ],
  },
  // ---------------------------------------------------------------------
  {
    slug: "en-a2-past-simple-translation-drill-1",
    optional: true,
    level: "EN-A2",
    number: 5,
    title: "Práctica extra: traduce el pasado",
    summary: "Traducción intensiva de frases cotidianas en pasado: regulares, irregulares, \"was/were\", negativas y preguntas, \"ago\" y la edad. Cuidado con el sujeto, que en inglés nunca falta.",
    duration: "12 min",
    sections: [
      {
        heading: "Recordatorio: lo que no se traduce palabra por palabra",
        body: [
          "El sujeto siempre aparece: «Llegó tarde» es \"He arrived late\" o \"She arrived late\", nunca *Arrived late. Si el español no lo dice, piensa quién es.",
          "«Hace dos años» va al revés: \"two years ago\", con \"ago\" al final. Nunca *ago two years ni *it makes two years.",
          "«Tenía veinte años», «tenía frío», «tenía razón» van con \"was\": \"I was twenty\", \"I was cold\", \"I was right\". Pero «tenía un perro» sí es \"had\": \"I had a dog\".",
        ],
        examples: [
          { es: "She arrived late.", en: "(Ella) llegó tarde." },
          { es: "I met him three years ago.", en: "Lo conocí hace tres años." },
          { es: "I was twenty when I moved.", en: "Tenía veinte años cuando me mudé." },
          { es: "We had a dog.", en: "Teníamos un perro." },
          { es: "It was late, so we took a taxi.", en: "Era tarde, así que tomamos un taxi." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "es-en",
            prompt: "Traduce al inglés.",
            source: "Ella se casó hace cinco años.",
            answer: "She got married five years ago.",
            explanation: "«Casarse» es \"get married\" → \"got married\". «Hace cinco años» es \"five years ago\", con \"ago\" al final.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Yo tenía doce años cuando aprendí a nadar.",
        answer: "I was twelve when I learned to swim.",
        altAnswers: ["I was twelve years old when I learned to swim.", "When I was twelve, I learned to swim.", "When I was twelve years old, I learned to swim.", "When I was twelve I learned to swim."],
        explanation: "La edad con \"was\" y «aprender a» es \"learn to\". (En inglés británico también se escribe \"learnt\".)",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Mi abuelo tenía una tienda pequeña.",
        answer: "My grandfather had a small store.",
        altAnswers: ["My grandfather had a small shop.", "My grandpa had a small store.", "My grandpa had a small shop.", "My grandfather had a little store.", "My grandfather had a little shop."],
        explanation: "Aquí «tener» es poseer, así que sí es \"had\". El adjetivo va delante: \"a small store\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Nos conocimos hace diez años.",
        answer: "We met ten years ago.",
        explanation: "«Conocerse» (por primera vez) es \"meet\" → \"met\". \"Ago\" va detrás del tiempo.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Hacía calor, así que fuimos a la piscina.",
        answer: "It was hot, so we went to the pool.",
        altAnswers: ["It was hot, so we went to the swimming pool.", "It was warm, so we went to the pool.", "It was warm, so we went to the swimming pool."],
        explanation: "\"It was hot\" necesita el sujeto \"it\". «Ir» → \"went\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "El mes pasado mi hermana empezó la universidad.",
        answer: "Last month my sister started college.",
        altAnswers: ["My sister started college last month.", "Last month my sister started university.", "My sister started university last month.", "Last month my sister began college.", "My sister began college last month.", "Last month my sister began university.", "My sister began university last month."],
        explanation: "«El mes pasado» es \"last month\", sin \"the\". En Estados Unidos se dice \"college\"; en Reino Unido, \"university\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "No encontré mi pasaporte.",
        answer: "I couldn't find my passport.",
        altAnswers: ["I didn't find my passport."],
        explanation: "\"Didn't find\" con verbo base. Lo más natural, cuando buscaste y no lo lograste, es \"I couldn't find\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "¿Cuánto pagaste por el billete?",
        answer: "How much did you pay for the ticket?",
        explanation: "\"How much did you pay...?\": \"did\" + verbo base \"pay\". «Billete» (de transporte) es \"ticket\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "¿Llovió mucho en tus vacaciones?",
        answer: "Did it rain a lot on your vacation?",
        altAnswers: ["Did it rain a lot during your vacation?", "Did it rain a lot on your holiday?", "Did it rain a lot during your holiday?", "Did it rain a lot on your holidays?", "Did it rain a lot during your holidays?"],
        explanation: "La lluvia también necesita sujeto: \"Did it rain?\". «Vacaciones» es \"vacation\" en Estados Unidos y \"holiday(s)\" en Reino Unido.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Mis amigos no estaban en casa, así que volví.",
        answer: "My friends weren't at home, so I went back.",
        altAnswers: ["My friends weren't home, so I went back.", "My friends weren't at home, so I came back.", "My friends weren't home, so I came back.", "My friends weren't at home, so I left.", "My friends weren't home, so I left."],
        explanation: "\"Weren't at home\" (to be) y \"went back\" (verbo de acción). «Volver» es \"go back\" o \"come back\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "La película fue muy aburrida y me dormí.",
        answer: "The movie was very boring and I fell asleep.",
        altAnswers: ["The film was very boring and I fell asleep.", "The movie was really boring and I fell asleep.", "The film was really boring and I fell asleep.", "The movie was very boring, and I fell asleep.", "The movie was so boring that I fell asleep.", "The movie was so boring I fell asleep."],
        explanation: "\"Boring\" (aburrido) con \"was\". «Dormirse» es \"fall asleep\" → \"fell asleep\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "¿A quién viste en el centro?",
        answer: "Who did you see downtown?",
        altAnswers: ["Who did you see in the city center?", "Who did you see in town?", "Who did you see in the center?", "Whom did you see downtown?"],
        explanation: "\"Who\" es aquí el complemento, así que hace falta \"did\": \"Who did you see?\". «El centro» de la ciudad es \"downtown\" en Estados Unidos.",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "They moved to Canada two years ___.",
        answer: "ago",
        en: "Se mudaron a Canadá [hace] dos años.",
        explanation: "«Hace» + tiempo se dice con \"ago\" al final: \"two years ago\".",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "When I was a child, I ___ scared of dogs.",
        answer: "was",
        en: "Cuando era niño, [tenía] miedo de los perros.",
        explanation: "«Tener miedo» es \"to be scared\": \"I was scared\". No *I had scared.",
      },
      {
        type: "multiple-choice",
        question: "¿Cómo se dice «Llegó hace una hora» hablando de Ana?",
        options: ["She arrived an hour ago.", "Arrived an hour ago.", "She arrived ago an hour.", "She arrived makes an hour."],
        correctIndex: 0,
        explanation: "Hace falta el sujeto (\"she\") y \"ago\" va detrás del tiempo: \"an hour ago\".",
      },
      {
        type: "word-order",
        prompt: "Ordena las palabras.",
        words: ["I", "didn't", "go", "to", "work", "because", "I", "was", "sick."],
        translation: "No fui a trabajar porque estaba enfermo.",
        altOrders: [["Because", "I", "was", "sick", "I", "didn't", "go", "to", "work."]],
        explanation: "\"Didn't go\" (verbo de acción) y \"was sick\" (adjetivo). El sujeto \"I\" se repite en cada parte.",
      },
      {
        type: "listen-choose",
        audio: "I lived in Lima when I was a child.",
        question: "¿Qué has oído?",
        options: ["Viví en Lima de niño.", "Me fui de Lima de niño.", "Vivo en Lima con mi hijo.", "Visité Lima de niño."],
        correctIndex: 0,
        explanation: "\"Lived\" (de \"live\", vivir), no \"left\" (irse). \"When I was a child\" es «cuando era niño».",
      },
      {
        type: "dictation",
        audio: "We bought a house three years ago.",
        explanation: "\"Bought\" (de \"buy\") y \"three years ago\" con \"ago\" al final.",
      },
      {
        type: "write",
        prompt: "Escribe sobre un día especial de tu pasado (un cumpleaños, un viaje, tu primer día de trabajo...). Di cuándo fue, cuántos años tenías, dónde estabas, qué hiciste y qué no hiciste.",
        minWords: 40,
        maxWords: 80,
        rubric: [
          "Usa \"was\" o \"were\" al menos dos veces (edad, lugar o sentimientos).",
          "Usa al menos tres verbos irregulares en pasado (\"went\", \"had\", \"saw\"...).",
          "Incluye una negativa con \"didn't\" + verbo base.",
          "Usa una expresión de tiempo como \"ago\" o \"last\".",
          "Todas las frases tienen sujeto.",
        ],
        modelAnswer: "My best birthday was ten years ago. I was twenty-five and I was in Mexico City with my friends. In the morning we went to a big market and I bought a hat. In the evening we had dinner in a small restaurant and my friends gave me a cake. I didn't want to go home. It was a perfect day.",
        explanation: "Combina los dos sistemas del pasado: \"was/were\" para la edad, los lugares y las sensaciones, y los verbos de acción en pasado (o con \"didn't\" + verbo base).",
      },
    ],
  },
];
