// Synced from cheneygross-afk/lengo:src/lib/lessons/en-a2-u17-extra.ts by scripts/sync-content.mjs -- edit it there, not here.
import type { Lesson } from "./types";

// Extra practice (optional) lessons for EN-A2 unit u17.

export const EN_A2_U17_EXTRA: Lesson[] = [
  // ---------------------------------------------------------------------
  // Extra 1. Movement prepositions drill
  // ---------------------------------------------------------------------
  {
    slug: "en-a2-movement-prepositions-drill-1",
    optional: true,
    level: "EN-A2",
    number: 1,
    title: "Práctica extra: preposiciones de movimiento",
    summary: "Práctica intensiva de \"into\", \"out of\", \"across\", \"through\", \"along\", \"past\", \"over\", \"under\", \"up\", \"down\" y \"toward\", con los calcos más típicos del español.",
    duration: "10 min",
    sections: [
      {
        heading: "Repaso rápido: la preposición dice hacia dónde",
        body: [
          "En inglés el verbo dice cómo te mueves (\"walk\", \"run\", \"drive\", \"swim\") y la preposición dice adónde: \"into\" (hacia dentro), \"out of\" (hacia fuera), \"across\" (de un lado a otro), \"through\" (a través de algo con volumen), \"along\" (a lo largo de), \"past\" (por delante de, sin parar), \"over\" (por encima de), \"under\" (por debajo de), \"up\" y \"down\" (subir y bajar), \"toward\" (hacia) y \"around\" (alrededor de).",
          "Por eso «cruzó la calle corriendo» es \"He ran across the street\" y «entró corriendo» es \"He ran in\": primero la manera, luego la dirección.",
        ],
        examples: [
          { es: "She ran into the house.", en: "Entró corriendo en la casa." },
          { es: "We drove through the tunnel.", en: "Atravesamos el túnel en coche." },
          { es: "They walked along the river.", en: "Caminaron a lo largo del río." },
          { es: "The ball went over the wall.", en: "La pelota pasó por encima del muro." },
          { es: "He walked toward the door.", en: "Caminó hacia la puerta." },
          { es: "Go down the stairs and turn right.", en: "Baja las escaleras y gira a la derecha." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "es-en",
            prompt: "Traduce al inglés.",
            source: "Los niños corrieron hacia el parque.",
            answer: "The kids ran toward the park.",
            altAnswers: ["The children ran toward the park.", "The kids ran towards the park.", "The children ran towards the park."],
            explanation: "La manera va en el verbo (\"ran\") y la dirección en la preposición: «hacia» es \"toward\" (o \"towards\").",
          },
          {
            type: "fill-blank",
            prompt: "Escribe en inglés las palabras en negrita.",
            sentence: "The cat ran ___ the table.",
            answer: "under",
            altAnswers: ["underneath"],
            en: "El gato corrió [por debajo de] la mesa.",
            explanation: "«Por debajo de» es \"under\". \"Over\" sería por encima.",
          },
        ],
      },
      {
        heading: "Los tres calcos de siempre",
        body: [
          "Uno: *enter in the room. \"Enter\" va sin preposición (\"enter the room\"); con \"go\" o \"come\" se usa \"into\": \"go into the room\". Dos: \"in\" es estar dentro y \"into\" es entrar; *He went in the room suena a que ya estaba dentro. Tres: «salir de» es \"out of\", con las dos palabras: *went out the room es incorrecto.",
          "Y recuerda: «cruzar la calle» puede ser \"cross the street\" o \"go across the street\"; las dos son correctas.",
        ],
        examples: [
          { es: "She entered the bank.", en: "Entró en el banco. (incorrecto: *entered in the bank)" },
          { es: "She went into the bank.", en: "Entró en el banco." },
          { es: "He took the keys out of his pocket.", en: "Sacó las llaves del bolsillo." },
          { es: "We crossed the bridge.", en: "Cruzamos el puente." },
          { es: "We went across the bridge.", en: "Cruzamos el puente." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "¿Cuál de estas frases tiene un error?",
            options: ["He entered in the room.", "He went into the room.", "He came into the room.", "He entered the room."],
            correctIndex: 0,
            explanation: "\"Enter\" no lleva preposición: \"entered the room\". *Entered in es un calco de «entrar en».",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "El avión voló por encima de las montañas.",
        answer: "The plane flew over the mountains.",
        altAnswers: ["The airplane flew over the mountains."],
        explanation: "«Por encima de», de un lado a otro, es \"over\". *Flew above the mountains se entiende, pero \"over\" es lo natural para el movimiento.",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "He came ___ the room and sat down.",
        answer: "into",
        en: "Entró [en] la habitación y se sentó.",
        explanation: "Con \"come\" o \"go\", el movimiento hacia dentro es \"into\". \"In the room\" sería estar dentro, no entrar.",
      },
      {
        type: "multiple-choice",
        question: "«Sacó el pasaporte del bolso.» ¿Cuál es correcta?",
        options: ["She took her passport out of her bag.", "She took her passport out her bag.", "She took her passport of her bag.", "She took her passport from out her bag."],
        correctIndex: 0,
        explanation: "«Sacar algo de» es \"take something out of\", con las dos palabras \"out of\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Subimos la colina a pie.",
        answer: "We walked up the hill.",
        altAnswers: ["We went up the hill on foot.", "We walked up the hill on foot.", "We went up the hill.", "We climbed the hill."],
        explanation: "«Subir» una colina o una escalera es \"go up\" o \"walk up\": la dirección la da \"up\".",
      },
      {
        type: "matching",
        instructions: "Une cada preposición con su significado.",
        pairs: [
          { left: "into", right: "hacia dentro de" },
          { left: "out of", right: "fuera de (saliendo)" },
          { left: "over", right: "por encima de" },
          { left: "under", right: "por debajo de" },
          { left: "toward", right: "hacia" },
        ],
        explanation: "Todas indican movimiento: \"into the box\", \"out of the car\", \"over the fence\", \"under the bridge\", \"toward the station\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Pasamos por delante de tu casa anoche.",
        answer: "We went past your house last night.",
        altAnswers: [
          "We drove past your house last night.",
          "We walked past your house last night.",
          "Last night we went past your house.",
          "Last night we drove past your house.",
          "Last night we walked past your house.",
        ],
        explanation: "«Pasar por delante de» es \"go past\" (o \"drive past\", \"walk past\"). No hace falta \"in front of\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Salió corriendo de la tienda.",
        answer: "He ran out of the store.",
        altAnswers: ["She ran out of the store.", "He ran out of the shop.", "She ran out of the shop."],
        explanation: "La manera en el verbo (\"ran\") y la salida en \"out of\". *Ran out the store es un error típico: falta \"of\".",
      },
      {
        type: "listen-choose",
        audio: "They walked along the river and across the bridge.",
        question: "¿Qué has oído?",
        options: ["Caminaron a lo largo del río y cruzaron el puente.", "Cruzaron el río y caminaron por el puente.", "Nadaron en el río por debajo del puente.", "Caminaron hacia el río y hacia el puente."],
        correctIndex: 0,
        explanation: "\"Along\" es «a lo largo de» y \"across\" es «de un lado a otro»: cruzaron el puente.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Bajó las escaleras corriendo.",
        answer: "She ran down the stairs.",
        altAnswers: ["He ran down the stairs.", "She ran downstairs.", "He ran downstairs."],
        explanation: "«Bajar corriendo» es \"run down\": el verbo dice cómo y \"down\" dice la dirección. *Went down the stairs running es un calco poco natural.",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "We drove ___ the lake and had a picnic.",
        answer: "around",
        altAnswers: ["round"],
        en: "Dimos la vuelta [alrededor del] lago e hicimos un picnic.",
        explanation: "«Alrededor de» es \"around\" (en el Reino Unido también \"round\").",
      },
      {
        type: "word-order",
        prompt: "Ordena las palabras.",
        words: ["The", "kids", "ran", "into", "the", "garden."],
        translation: "Los niños entraron corriendo en el jardín.",
        explanation: "Sujeto + verbo de manera (\"ran\") + preposición de dirección (\"into\") + lugar.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Cruza el puente y gira a la izquierda.",
        answer: "Cross the bridge and turn left.",
        altAnswers: ["Go across the bridge and turn left.", "Walk across the bridge and turn left."],
        explanation: "«Cruzar» es \"cross\" (sin preposición) o \"go across\". No digas *cross across.",
      },
      {
        type: "multiple-choice",
        question: "«Caminó hacia la salida.» ¿Cuál es correcta?",
        options: ["She walked toward the exit.", "She walked at the exit.", "She walked for the exit.", "She walked until the exit."],
        correctIndex: 0,
        explanation: "«Hacia» es \"toward\" (o \"towards\"). \"To the exit\" significaría que llegó hasta la salida.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "El perro saltó dentro del coche.",
        answer: "The dog jumped into the car.",
        altAnswers: ["The dog jumped in the car."],
        explanation: "Movimiento hacia dentro: \"into\". En conversación también se oye \"jumped in the car\".",
      },
      {
        type: "multiple-choice",
        question: "«El barco pasó por debajo del puente.» ¿Cuál es correcta?",
        options: ["The boat went under the bridge.", "The boat went down the bridge.", "The boat went below of the bridge.", "The boat went through the bridge."],
        correctIndex: 0,
        explanation: "«Por debajo de» es \"under\". \"Down the bridge\" sería bajar por el puente y \"through\" atravesarlo por dentro.",
      },
      {
        type: "dictation",
        audio: "Go through the tunnel and over the bridge.",
        explanation: "\"Through\" para atravesar el túnel y \"over\" para pasar por encima del puente.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Caminamos a lo largo de la playa hasta el hotel.",
        answer: "We walked along the beach to the hotel.",
        altAnswers: ["We walked along the beach as far as the hotel.", "We walked along the beach up to the hotel."],
        explanation: "«A lo largo de» es \"along\", y el destino va con \"to\".",
      },
    ],
  },
  // ---------------------------------------------------------------------
  // Extra 2. Arrive / go / get drill
  // ---------------------------------------------------------------------
  {
    slug: "en-a2-arrive-go-drill-1",
    optional: true,
    level: "EN-A2",
    number: 2,
    title: "Práctica extra: llegar a e ir a",
    summary: "Práctica intensiva de \"arrive in\", \"arrive at\", \"get to\" y \"go to\", y de las palabras que no llevan preposición: \"home\", \"here\", \"there\", \"downtown\", \"abroad\".",
    duration: "10 min",
    sections: [
      {
        heading: "Repaso rápido: \"arrive in\", \"arrive at\", \"get to\"",
        body: [
          "«Llegar a» nunca es *arrive to. Con ciudades, países y regiones: \"arrive in\" (\"arrive in Lima\"). Con edificios, estaciones, eventos y lugares concretos: \"arrive at\" (\"arrive at the airport\", \"arrive at the party\"). Y en conversación, con cualquier lugar: \"get to\" (\"get to work\", \"get to Lima\").",
          "«Ir a» es \"go to\": \"go to the bank\", \"go to work\" (sin artículo cuando piensas en la actividad: \"work\", \"school\", \"bed\", \"church\").",
        ],
        examples: [
          { es: "We arrived in Buenos Aires at night.", en: "Llegamos a Buenos Aires de noche." },
          { es: "She arrived at the office at nine.", en: "Llegó a la oficina a las nueve." },
          { es: "What time did you get to the hotel?", en: "¿A qué hora llegaste al hotel?" },
          { es: "I go to work by train.", en: "Voy al trabajo en tren." },
          { es: "The kids go to bed at eight.", en: "Los niños se van a la cama a las ocho." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "es-en",
            prompt: "Traduce al inglés.",
            source: "¿A qué hora llegaste a Nueva York?",
            answer: "What time did you arrive in New York?",
            altAnswers: ["What time did you get to New York?", "When did you arrive in New York?", "When did you get to New York?"],
            explanation: "Con una ciudad, \"arrive in\" o \"get to\". Nunca *arrive to New York.",
          },
          {
            type: "multiple-choice",
            question: "¿Cuál de estas frases tiene un error?",
            options: ["She arrived to school late.", "She arrived at school late.", "She got to school late.", "She was late for school."],
            correctIndex: 0,
            explanation: "*Arrive to no existe: con un lugar concreto como la escuela se dice \"arrive at\" o \"get to\".",
          },
        ],
      },
      {
        heading: "Sin preposición: home, here, there, downtown, abroad",
        body: [
          "\"Home\", \"here\", \"there\", \"downtown\", \"abroad\", \"upstairs\" y \"downstairs\" ya llevan la dirección dentro: \"go home\", \"get home\", \"arrive home\", \"come here\", \"go there\", \"go abroad\". Nunca *go to home, *arrive to home ni *go to there.",
          "Ojo: para estar (no ir) se dice \"at home\": \"I'm at home\" (en Estados Unidos también \"I'm home\").",
        ],
        examples: [
          { es: "I get home at six.", en: "Llego a casa a las seis." },
          { es: "Come here!", en: "¡Ven aquí!" },
          { es: "We went there last summer.", en: "Fuimos allí el verano pasado." },
          { es: "My cousin lives abroad.", en: "Mi primo vive en el extranjero." },
          { es: "She's at home today.", en: "Hoy está en casa." },
        ],
        checkpoint: [
          {
            type: "fill-blank",
            prompt: "Escribe en inglés las palabras en negrita.",
            sentence: "I'm going ___ now. See you tomorrow.",
            answer: "home",
            en: "Me voy [a casa] ahora. Hasta mañana.",
            explanation: "\"Go home\" sin \"to\" y sin artículo: \"home\" ya significa «a casa».",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "We arrived ___ Mexico City at noon.",
        answer: "in",
        en: "Llegamos [a] Ciudad de México al mediodía.",
        explanation: "Con una ciudad, \"arrive in\". *Arrive to es el error más típico de los hispanohablantes.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Ella llega a casa a las siete.",
        answer: "She gets home at seven.",
        altAnswers: ["She arrives home at seven.", "She comes home at seven.", "She gets home at seven o'clock.", "She arrives home at seven o'clock.", "She comes home at seven o'clock."],
        explanation: "«Llegar a casa» es \"get home\" o \"arrive home\", sin \"to\". No olvides la -s: \"gets\".",
      },
      {
        type: "multiple-choice",
        question: "«Mi hermano se fue al extranjero el año pasado.» ¿Cuál es correcta?",
        options: ["My brother went abroad last year.", "My brother went to abroad last year.", "My brother went to the abroad last year.", "My brother went in abroad last year."],
        correctIndex: 0,
        explanation: "\"Abroad\" va sin preposición y sin artículo, como \"home\": \"go abroad\", \"live abroad\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Fuimos allí en tren.",
        answer: "We went there by train.",
        altAnswers: ["We went there on the train.", "We took the train there."],
        explanation: "\"There\" no lleva \"to\": \"went there\", nunca *went to there. Y «en tren» es \"by train\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "¿Cómo llegaste al hotel?",
        answer: "How did you get to the hotel?",
        explanation: "Para «llegar a» en conversación, \"get to\" + lugar. En pasado, con \"did\" + \"get\".",
      },
      {
        type: "multiple-choice",
        question: "«Llegamos a Perú hace dos días.» ¿Cuál es correcta?",
        options: ["We arrived in Peru two days ago.", "We arrived to Peru two days ago.", "We arrived at Peru two days ago.", "We arrived Peru two days ago."],
        correctIndex: 0,
        explanation: "Países y ciudades llevan \"arrive in\". \"Arrive at\" es para lugares concretos, como un aeropuerto.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Mi hija se va a la cama a las nueve.",
        answer: "My daughter goes to bed at nine.",
        altAnswers: ["My daughter goes to bed at nine o'clock."],
        explanation: "\"Go to bed\" sin artículo, porque piensas en la actividad de dormir. *Goes to the bed suena a ir hasta el mueble.",
      },
      {
        type: "word-order",
        prompt: "Ordena las palabras.",
        words: ["We", "arrived", "at", "the", "station", "at", "six."],
        translation: "Llegamos a la estación a las seis.",
        explanation: "\"Arrive at\" + un lugar concreto, y \"at\" + la hora.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Ven a mi casa esta tarde.",
        answer: "Come to my house this afternoon.",
        altAnswers: ["Come to my place this afternoon.", "Come over to my house this afternoon.", "Come over this afternoon.", "Come to my house this evening.", "Come to my place this evening.", "Come over this evening."],
        explanation: "\"Come to\" + un lugar con posesivo: \"come to my house\". Solo \"home\" va sin \"to\", y aquí es «mi casa», no «a casa».",
      },
      {
        type: "listen-choose",
        audio: "I usually get to work at nine and get home at six.",
        question: "¿Qué has oído?",
        options: ["Llego al trabajo a las nueve y a casa a las seis.", "Salgo del trabajo a las nueve y de casa a las seis.", "Llego al trabajo a las seis y a casa a las nueve.", "Trabajo desde casa de nueve a seis."],
        correctIndex: 0,
        explanation: "\"Get to work\" es «llegar al trabajo» y \"get home\", «llegar a casa».",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "What time does the plane arrive ___ Miami?",
        answer: "in",
        en: "¿A qué hora llega el avión [a] Miami?",
        explanation: "Miami es una ciudad: \"arrive in Miami\". Con el aeropuerto sería \"arrive at the airport\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "El autobús llegó tarde.",
        answer: "The bus arrived late.",
        altAnswers: ["The bus was late.", "The bus got here late.", "The bus came late."],
        explanation: "Sin lugar, \"arrive\" va solo: \"arrived late\". También es muy natural \"The bus was late\".",
      },
      {
        type: "multiple-choice",
        question: "«¿A qué hora llegaste a casa anoche?» ¿Cuál es correcta?",
        options: ["What time did you get home last night?", "What time did you get to home last night?", "What time did you arrive to home last night?", "What time did you arrived home last night?"],
        correctIndex: 0,
        explanation: "\"Get home\" sin \"to\". Y después de \"did\", el verbo va en infinitivo: \"get\", no \"arrived\".",
      },
      {
        type: "dictation",
        audio: "How do I get to the train station?",
        explanation: "\"How do I get to...?\" es la pregunta normal para pedir el camino.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Nos vemos allí.",
        answer: "See you there.",
        altAnswers: ["I'll see you there.", "We'll see you there.", "Let's meet there."],
        explanation: "\"There\" sin preposición: \"see you there\", nunca *see you in there ni *see you to there.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Tom va a la escuela a las ocho y vuelve a casa a las tres.",
        answer: "Tom goes to school at eight and comes home at three.",
        altAnswers: [
          "Tom goes to school at eight and gets home at three.",
          "Tom goes to school at eight and comes back home at three.",
          "Tom goes to school at eight and returns home at three.",
          "Tom goes to school at eight and goes home at three.",
          "Tom goes to school at eight o'clock and comes home at three o'clock.",
        ],
        explanation: "\"Go to school\" sin artículo, y «volver a casa» es \"come home\" o \"get home\", sin \"to\".",
      },
    ],
  },
  // ---------------------------------------------------------------------
  // Extra 3. During / for / by / until drill
  // ---------------------------------------------------------------------
  {
    slug: "en-a2-time-prepositions-drill-1",
    optional: true,
    level: "EN-A2",
    number: 3,
    title: "Práctica extra: during, for, by y until",
    summary: "Contraste intensivo: \"for\" (cuánto tiempo) o \"during\" (cuándo), \"by\" (plazo) o \"until\" (hasta), y \"while\" con sujeto y verbo.",
    duration: "10 min",
    sections: [
      {
        heading: "Repaso rápido: \"for\" o \"during\"",
        body: [
          "\"For\" responde a «¿cuánto tiempo?» y va con una cantidad: \"for two hours\", \"for a week\". \"During\" responde a «¿cuándo?» y va con el nombre de un período o un evento: \"during the movie\", \"during the summer\". Por eso *during two hours es un error: con una cantidad, siempre \"for\".",
          "Si lo que sigue es sujeto + verbo, no se usa \"during\" sino \"while\": \"while I was sleeping\" («mientras dormía»).",
        ],
        examples: [
          { es: "We stayed there for three days.", en: "Nos quedamos allí tres días." },
          { es: "He called me during dinner.", en: "Me llamó durante la cena." },
          { es: "It snowed during the night.", en: "Nevó durante la noche." },
          { es: "She fell asleep while she was reading.", en: "Se durmió mientras leía." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "«Llovió durante dos días.» ¿Cuál es correcta?",
            options: ["It rained for two days.", "It rained during two days.", "It rained while two days.", "It rained since two days."],
            correctIndex: 0,
            explanation: "«Dos días» es una cantidad de tiempo, así que se usa \"for\". \"During\" necesita el nombre de un período o un evento.",
          },
        ],
      },
      {
        heading: "Repaso rápido: \"until\" o \"by\"",
        body: [
          "\"Until\" (o \"till\") es «hasta»: la acción continúa sin parar hasta ese momento: \"I'll be here until six\". \"By\" es un plazo: «para», «como muy tarde»: \"Send it by Friday\" (puede ser antes).",
          "El error típico es traducir «para el viernes» como *until Friday. Truco: si puedes decir «como muy tarde», es \"by\".",
        ],
        examples: [
          { es: "The pool is open until eight.", en: "La piscina está abierta hasta las ocho." },
          { es: "I'll wait until you get back.", en: "Esperaré hasta que vuelvas." },
          { es: "I need your answer by Monday.", en: "Necesito tu respuesta para el lunes." },
          { es: "We should be there by seven.", en: "Deberíamos estar allí a las siete como muy tarde." },
        ],
        checkpoint: [
          {
            type: "fill-blank",
            prompt: "Escribe en inglés las palabras en negrita.",
            sentence: "Please pay the bill ___ the end of the month.",
            answer: "by",
            en: "Por favor, paga la factura [para] final de mes.",
            explanation: "Un plazo («para», «como muy tarde») es \"by\". \"Until the end of the month\" significaría estar pagando sin parar hasta entonces.",
          },
          {
            type: "fill-blank",
            prompt: "Escribe en inglés las palabras en negrita.",
            sentence: "I'll be here ___ six, so call me before that.",
            answer: "until",
            altAnswers: ["till"],
            en: "Estaré aquí [hasta las] seis, así que llámame antes.",
            explanation: "La situación dura hasta ese momento: \"until six\".",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Nos quedamos en Roma durante una semana.",
        answer: "We stayed in Rome for a week.",
        altAnswers: ["We stayed in Rome for one week."],
        explanation: "«Una semana» es una cantidad de tiempo: \"for a week\". *During a week es el calco típico.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Se durmió durante la reunión.",
        answer: "He fell asleep during the meeting.",
        altAnswers: ["She fell asleep during the meeting."],
        explanation: "«La reunión» es un evento, así que se usa \"during\". «Dormirse» es \"fall asleep\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Tengo que devolver el libro el viernes como muy tarde.",
        answer: "I have to return the book by Friday.",
        altAnswers: [
          "I need to return the book by Friday.",
          "I must return the book by Friday.",
          "I have to give the book back by Friday.",
          "I need to give the book back by Friday.",
          "I have to return the book by Friday at the latest.",
          "I need to return the book by Friday at the latest.",
        ],
        explanation: "«Como muy tarde el viernes» es un plazo: \"by Friday\". *Until Friday significaría otra cosa.",
      },
      {
        type: "multiple-choice",
        question: "«La tienda está cerrada hasta el lunes.» ¿Cuál es correcta?",
        options: ["The store is closed until Monday.", "The store is closed by Monday.", "The store is closed for Monday.", "The store is closed to Monday."],
        correctIndex: 0,
        explanation: "La situación (cerrada) continúa hasta el lunes: \"until Monday\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Esperé hasta las once, pero no vino.",
        answer: "I waited until eleven, but he didn't come.",
        altAnswers: [
          "I waited until eleven, but she didn't come.",
          "I waited till eleven, but he didn't come.",
          "I waited till eleven, but she didn't come.",
          "I waited until eleven but he didn't come.",
          "I waited until eleven but she didn't come.",
          "I waited until eleven o'clock, but he didn't come.",
          "I waited until eleven o'clock, but she didn't come.",
        ],
        explanation: "La espera dura hasta ese momento: \"until eleven\" (o \"till eleven\").",
      },
      {
        type: "matching",
        instructions: "Une cada palabra con su uso.",
        pairs: [
          { left: "for", right: "una cantidad de tiempo" },
          { left: "during", right: "el nombre de un período o un evento" },
          { left: "by", right: "un plazo: como muy tarde" },
          { left: "until", right: "hasta ese momento, sin parar" },
          { left: "while", right: "mientras, con sujeto y verbo" },
        ],
        explanation: "\"For two hours\", \"during the class\", \"by Friday\", \"until six\", \"while I was eating\".",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "Nobody talked ___ the concert.",
        answer: "during",
        en: "Nadie habló [durante] el concierto.",
        explanation: "\"The concert\" es un evento, no una cantidad de tiempo: \"during\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Me dormí mientras leía.",
        answer: "I fell asleep while I was reading.",
        altAnswers: ["I fell asleep while reading.", "I fell asleep while I read."],
        explanation: "Con sujeto + verbo se usa \"while\", no \"during\": *during I was reading es incorrecto.",
      },
      {
        type: "multiple-choice",
        question: "«Tenemos que estar allí a las ocho como muy tarde.» ¿Cuál es correcta?",
        options: ["We have to be there by eight.", "We have to be there until eight.", "We have to be there for eight.", "We have to be there during eight."],
        correctIndex: 0,
        explanation: "«Como muy tarde» = \"by\". \"Until eight\" significaría quedarse allí hasta las ocho.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "La biblioteca está abierta hasta las diez de la noche.",
        answer: "The library is open until ten at night.",
        altAnswers: [
          "The library is open till ten at night.",
          "The library is open until ten p.m.",
          "The library is open until 10 p.m.",
          "The library is open until ten pm.",
          "The library is open until 10pm.",
          "The library is open till ten p.m.",
          "The library is open until ten in the evening.",
        ],
        explanation: "Abierta todo el tiempo hasta ese momento: \"until\". «De la noche» es \"at night\" o \"p.m.\".",
      },
      {
        type: "listen-choose",
        audio: "You can stay until Sunday, but you have to leave by noon.",
        question: "¿Qué has oído?",
        options: ["Puedes quedarte hasta el domingo, pero tienes que irte antes del mediodía.", "Puedes quedarte el domingo solo hasta el mediodía.", "Tienes que irte el domingo por la mañana temprano.", "Puedes quedarte hasta el mediodía del lunes."],
        correctIndex: 0,
        explanation: "\"Until Sunday\" es «hasta el domingo» y \"by noon\" es «al mediodía como muy tarde».",
      },
      {
        type: "word-order",
        prompt: "Ordena las palabras.",
        words: ["Finish", "your", "homework", "by", "Friday."],
        translation: "Termina la tarea para el viernes.",
        explanation: "El plazo va al final con \"by\": \"by Friday\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Trabajé en ese hotel durante seis meses.",
        answer: "I worked at that hotel for six months.",
        altAnswers: ["I worked in that hotel for six months."],
        explanation: "«Seis meses» es una cantidad: \"for six months\". Nunca *during six months.",
      },
      {
        type: "dictation",
        audio: "I'll wait here until you come back.",
        explanation: "\"Until\" + sujeto y verbo también es correcto: «hasta que vuelvas».",
      },
      {
        type: "multiple-choice",
        question: "¿Cuál de estas frases tiene un error?",
        options: ["We talked during three hours.", "We talked for three hours.", "We talked during the whole trip.", "We talked while we ate."],
        correctIndex: 0,
        explanation: "Con una cantidad de tiempo («tres horas») se usa \"for\", no \"during\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "¿Puedes enviarme las fotos para mañana?",
        answer: "Can you send me the photos by tomorrow?",
        altAnswers: ["Could you send me the photos by tomorrow?", "Can you send me the pictures by tomorrow?", "Could you send me the pictures by tomorrow?"],
        explanation: "«Para mañana» es un plazo: \"by tomorrow\". *Until tomorrow o *for tomorrow cambian el sentido.",
      },
    ],
  },
  // ---------------------------------------------------------------------
  // Extra 4. Adjective + preposition drill
  // ---------------------------------------------------------------------
  {
    slug: "en-a2-adjective-preposition-drill-1",
    optional: true,
    level: "EN-A2",
    number: 4,
    title: "Práctica extra: adjetivo + preposición",
    summary: "Práctica intensiva de \"good at\", \"afraid of\", \"interested in\", \"married to\", \"proud of\", \"tired of\", \"worried about\" y \"different from\", con el verbo en -ing detrás.",
    duration: "10 min",
    sections: [
      {
        heading: "Repaso rápido: la lista",
        body: [
          "Apréndelos como bloques: \"good at\" y \"bad at\" (no *good in), \"interested in\" (no *interested on), \"afraid of\" y \"scared of\" (no *afraid to), \"married to\" (no *married with), \"proud of\", \"tired of\" («harto de»), \"worried about\" (no *worried for), \"different from\" (no *different of), \"similar to\", \"famous for\" y \"angry with\" o \"angry at\" una persona.",
          "Y recuerda que el miedo y el interés van con \"be\": \"I'm afraid\", \"I'm interested\", no *I have fear ni *I have interest.",
        ],
        examples: [
          { es: "He's bad at remembering names.", en: "Es malo para recordar nombres." },
          { es: "I'm worried about my exam.", en: "Estoy preocupado por mi examen." },
          { es: "She's married to a pilot.", en: "Está casada con un piloto." },
          { es: "My city is very different from yours.", en: "Mi ciudad es muy diferente de la tuya." },
          { es: "Are you scared of spiders?", en: "¿Te dan miedo las arañas?" },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "«Estoy preocupado por mi examen.» ¿Cuál es correcta?",
            options: ["I'm worried about my exam.", "I'm worried for my exam.", "I'm worried by my exam.", "I'm preoccupied of my exam."],
            correctIndex: 0,
            explanation: "«Preocupado por» es \"worried about\". *Worried for es un calco del español.",
          },
          {
            type: "multiple-choice",
            question: "¿Cuál de estas frases tiene un error?",
            options: ["She's good in English.", "She's good at English.", "She's interested in English.", "She's bad at English."],
            correctIndex: 0,
            explanation: "«Bueno en» es \"good at\", nunca *good in.",
          },
        ],
      },
      {
        heading: "Repaso rápido: después de la preposición, -ing",
        body: [
          "Si detrás de la preposición va un verbo, lleva -ing: \"good at cooking\", \"afraid of flying\", \"tired of waiting\", \"interested in learning\". El español usa el infinitivo («harto de esperar»), pero el inglés no: *tired of wait y *interested in to learn son incorrectos.",
        ],
        examples: [
          { es: "She's good at fixing things.", en: "Se le da bien arreglar cosas." },
          { es: "I'm tired of cleaning.", en: "Estoy harta de limpiar." },
          { es: "He's afraid of making mistakes.", en: "Tiene miedo de cometer errores." },
        ],
        checkpoint: [
          {
            type: "fill-blank",
            prompt: "Escribe en inglés las palabras en negrita.",
            sentence: "She's not very good at ___ in English.",
            answer: "writing",
            en: "No se le da muy bien [escribir] en inglés.",
            explanation: "Detrás de \"at\" el verbo va en -ing: \"writing\", no \"write\" ni *to write.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Soy malo para los deportes.",
        answer: "I'm bad at sports.",
        altAnswers: ["I'm bad at sport.", "I'm not good at sports.", "I'm not good at sport."],
        explanation: "«Malo para» es \"bad at\", igual que \"good at\". No *bad in ni *bad for.",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "She's very interested ___ science.",
        answer: "in",
        en: "Está muy interesada [en] la ciencia.",
        explanation: "\"Interested in\", nunca *interested on. Y «la ciencia» en general va sin artículo: \"science\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Mi tía está casada con un médico.",
        answer: "My aunt is married to a doctor.",
        explanation: "\"Married to\", nunca *married with: el calco más típico de los hispanohablantes.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Tu bici es muy parecida a la mía.",
        answer: "Your bike is very similar to mine.",
        altAnswers: ["Your bicycle is very similar to mine.", "Your bike is really similar to mine.", "Your bike is a lot like mine."],
        explanation: "«Parecido a» es \"similar to\". «La mía» es \"mine\", sin artículo.",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "The kids are scared ___ the dark.",
        answer: "of",
        en: "Los niños tienen miedo [de] la oscuridad.",
        explanation: "\"Scared of\" y \"afraid of\" llevan \"of\", no \"to\" ni \"from\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Estamos orgullosos de nuestro equipo.",
        answer: "We're proud of our team.",
        altAnswers: ["We are very proud of our team."],
        explanation: "«Orgulloso de» es \"proud of\". El adjetivo no cambia en plural: \"proud\" vale para «orgullosos».",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Estoy harta de la lluvia.",
        answer: "I'm tired of the rain.",
        altAnswers: ["I'm sick of the rain.", "I'm fed up with the rain.", "I'm sick and tired of the rain."],
        explanation: "«Harto de» es \"tired of\" (o \"sick of\"). \"Tired\" solo, sin \"of\", es «cansado».",
      },
      {
        type: "matching",
        instructions: "Une cada expresión con su significado.",
        pairs: [
          { left: "bad at", right: "malo para" },
          { left: "worried about", right: "preocupado por" },
          { left: "married to", right: "casado con" },
          { left: "different from", right: "diferente de" },
          { left: "tired of", right: "harto de" },
        ],
        explanation: "Cinco bloques fijos; en los cinco la preposición inglesa es distinta de la española.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Nos interesa aprender chino.",
        answer: "We're interested in learning Chinese.",
        explanation: "«Nos interesa» = \"we're interested in\", y el verbo que sigue va en -ing: \"learning\".",
      },
      {
        type: "multiple-choice",
        question: "«Tiene miedo de conducir de noche.» ¿Cuál es correcta?",
        options: ["He's afraid of driving at night.", "He's afraid of drive at night.", "He has fear of driving at night.", "He's afraid to driving at night."],
        correctIndex: 0,
        explanation: "\"Be afraid of\" + verbo en -ing. El miedo se expresa con \"be\", no con \"have\".",
      },
      {
        type: "word-order",
        prompt: "Ordena las palabras.",
        words: ["My", "city", "is", "famous", "for", "its", "food."],
        translation: "Mi ciudad es famosa por su comida.",
        explanation: "\"Famous for\" + aquello por lo que es famosa. El posesivo de una ciudad es \"its\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Mi madre está enojada con mi hermano.",
        answer: "My mother is angry with my brother.",
        altAnswers: [
          "My mom is angry with my brother.",
          "My mother is angry at my brother.",
          "My mom is angry at my brother.",
          "My mother is mad at my brother.",
          "My mom is mad at my brother.",
          "My mum is angry with my brother.",
        ],
        explanation: "Con una persona: \"angry with\" o \"angry at\" (en Estados Unidos, también \"mad at\").",
      },
      {
        type: "listen-choose",
        audio: "I'm not very good at singing, but I'm interested in music.",
        question: "¿Qué has oído?",
        options: ["No canto muy bien, pero me interesa la música.", "Canto muy bien, pero no me interesa la música.", "No me interesa ni cantar ni la música.", "Soy bueno cantando y también en música."],
        correctIndex: 0,
        explanation: "\"Not very good at singing\" (no se me da bien cantar) e \"interested in music\" (me interesa la música).",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Este pueblo es famoso por su playa.",
        answer: "This town is famous for its beach.",
        altAnswers: ["This village is famous for its beach."],
        explanation: "\"Famous for\" = «famoso por». No *famous by.",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "Ana is really good ___ languages.",
        answer: "at",
        en: "A Ana se le dan muy bien [los] idiomas.",
        explanation: "\"Good at\" + aquello que se te da bien. Nunca *good in languages.",
      },
      {
        type: "multiple-choice",
        question: "¿Cuál de estas frases tiene un error?",
        options: ["Tom is married with a lawyer.", "Tom is married to a lawyer.", "Tom married a lawyer.", "Tom got married to a lawyer."],
        correctIndex: 0,
        explanation: "\"Married to\" (o \"marry\" sin preposición). *Married with es el calco de «casado con».",
      },
      {
        type: "dictation",
        audio: "I'm tired of waiting for the bus.",
        explanation: "\"Tired of\" + verbo en -ing (\"waiting\"), y \"wait for\" + lo que esperas.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Estoy preocupada por mi abuelo.",
        answer: "I'm worried about my grandfather.",
        altAnswers: ["I'm worried about my grandpa."],
        explanation: "\"Worried about\" + persona o cosa. *Worried for es incorrecto.",
      },
    ],
  },
  // ---------------------------------------------------------------------
  // Extra 5. Verb + preposition drill
  // ---------------------------------------------------------------------
  {
    slug: "en-a2-verb-preposition-drill-1",
    optional: true,
    level: "EN-A2",
    number: 5,
    title: "Práctica extra: verbo + preposición",
    summary: "Práctica intensiva de \"listen to\", \"wait for\", \"look at\", \"depend on\", \"think about\", \"ask for\", \"pay for\" y de los verbos que no llevan preposición: \"call\", \"enter\", \"discuss\", \"explain\".",
    duration: "10 min",
    sections: [
      {
        heading: "Repaso rápido: verbos que llevan preposición en inglés",
        body: [
          "Aunque en español no la lleven: \"listen to music\" (no *listen music), \"wait for the bus\" (no *wait the bus), \"look at the photo\", \"look for my keys\" (buscar), \"depend on\" (no *depend of), \"belong to\", \"think about\" o \"think of\" (no *think in), \"worry about\", \"agree with\", \"ask for\" (pedir algo) y \"pay for\" (pagar lo que compras).",
          "Sin complemento, la preposición desaparece: \"Listen!\", \"Wait!\", \"It depends.\".",
        ],
        examples: [
          { es: "Listen to your teacher.", en: "Escucha a tu profesor." },
          { es: "We're looking for a new apartment.", en: "Estamos buscando un apartamento nuevo." },
          { es: "Who does this umbrella belong to?", en: "¿De quién es este paraguas?" },
          { es: "I asked my neighbor for help.", en: "Le pedí ayuda a mi vecino." },
          { es: "Who paid for the taxi?", en: "¿Quién pagó el taxi?" },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "«Escucha a tu profesor.» ¿Cuál es correcta?",
            options: ["Listen to your teacher.", "Listen your teacher.", "Listen at your teacher.", "Hear to your teacher."],
            correctIndex: 0,
            explanation: "\"Listen\" necesita \"to\" delante de lo que escuchas. \"Hear\" es «oír» y nunca lleva \"to\".",
          },
          {
            type: "fill-blank",
            prompt: "Escribe en inglés las palabras en negrita.",
            sentence: "We're ___ a new apartment.",
            answer: "looking for",
            altAnswers: ["searching for"],
            en: "Estamos [buscando] un apartamento nuevo.",
            explanation: "«Buscar» es \"look for\". \"Look at\" sería mirar.",
          },
        ],
      },
      {
        heading: "Repaso rápido: verbos que NO llevan preposición",
        body: [
          "Al revés que en español: \"call my mother\" (no *call to), \"enter the room\" (no *enter in), \"discuss the problem\" (no *discuss about), \"marry someone\" (no *marry with), \"attend a meeting\" (no *attend to), \"answer the phone\" y \"ask someone\" (no *ask to someone).",
          "Con \"explain\", la cosa va directa y la persona lleva \"to\": \"Explain the rule to me\", nunca *Explain me the rule.",
        ],
        examples: [
          { es: "Can you explain the rule to me?", en: "¿Me puedes explicar la regla?" },
          { es: "I attended the meeting yesterday.", en: "Asistí a la reunión ayer." },
          { es: "My cousin married a Canadian.", en: "Mi prima se casó con un canadiense." },
          { es: "Answer the phone, please.", en: "Contesta el teléfono, por favor." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "¿Cuál de estas frases tiene un error?",
            options: ["We discussed about the trip.", "We discussed the trip.", "We talked about the trip.", "We argued about the trip."],
            correctIndex: 0,
            explanation: "\"Discuss\" ya incluye el «sobre»: \"discussed the trip\". \"Talk about\" y \"argue about\" sí llevan \"about\".",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Mira este cuadro.",
        answer: "Look at this painting.",
        altAnswers: ["Look at this picture."],
        explanation: "«Mirar algo» es \"look at\". *Look this painting está incompleto.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "¿Me puedes explicar la regla?",
        answer: "Can you explain the rule to me?",
        altAnswers: ["Could you explain the rule to me?", "Can you explain the rule?", "Could you explain the rule?"],
        explanation: "\"Explain\" + la cosa + \"to\" + la persona. *Explain me the rule es un error muy típico.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Entró en la oficina sin llamar.",
        answer: "He entered the office without knocking.",
        altAnswers: [
          "She entered the office without knocking.",
          "He went into the office without knocking.",
          "She went into the office without knocking.",
          "He walked into the office without knocking.",
          "She walked into the office without knocking.",
          "He came into the office without knocking.",
          "She came into the office without knocking.",
        ],
        explanation: "\"Enter\" va sin preposición (o \"go into\"). «Llamar a la puerta» es \"knock\", y después de \"without\" el verbo va en -ing.",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "Who does this umbrella ___?",
        answer: "belong to",
        en: "¿A quién [pertenece] este paraguas?",
        explanation: "«Pertenecer a» es \"belong to\". En la pregunta, \"to\" se queda al final.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "¿Quién pagó el taxi?",
        answer: "Who paid for the taxi?",
        altAnswers: ["Who paid for the cab?"],
        explanation: "Pagar algo que compras o usas es \"pay for\": \"paid for the taxi\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Le pedí ayuda a mi vecino.",
        answer: "I asked my neighbor for help.",
        altAnswers: ["I asked my neighbour for help."],
        explanation: "\"Ask\" + persona (sin \"to\") + \"for\" + lo que pides.",
      },
      {
        type: "multiple-choice",
        question: "«Asistí a la reunión ayer.» ¿Cuál es correcta?",
        options: ["I attended the meeting yesterday.", "I attended to the meeting yesterday.", "I assisted the meeting yesterday.", "I assisted to the meeting yesterday."],
        correctIndex: 0,
        explanation: "\"Attend\" va sin preposición. \"Assist\" es un falso amigo: significa «ayudar».",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "It ___ how much money we have.",
        answer: "depends on",
        en: "[Depende de] cuánto dinero tengamos.",
        explanation: "\"Depend on\", nunca *depend of. Y el sujeto \"it\" es obligatorio.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Mi prima se casó con un canadiense.",
        answer: "My cousin married a Canadian.",
        altAnswers: ["My cousin got married to a Canadian.", "My cousin married a Canadian man."],
        explanation: "\"Marry\" va sin preposición; con \"get married\" se usa \"to\". Nunca *married with.",
      },
      {
        type: "word-order",
        prompt: "Ordena las palabras.",
        words: ["I'm", "thinking", "about", "my", "trip", "to", "Peru."],
        translation: "Estoy pensando en mi viaje a Perú.",
        explanation: "«Pensar en» es \"think about\", no *think in.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "¿Estás de acuerdo con ella?",
        answer: "Do you agree with her?",
        explanation: "\"Agree\" es un verbo normal: \"Do you agree with...?\", nunca *Are you agree.",
      },
      {
        type: "matching",
        instructions: "Une cada verbo con su significado.",
        pairs: [
          { left: "belong to", right: "pertenecer a" },
          { left: "depend on", right: "depender de" },
          { left: "worry about", right: "preocuparse por" },
          { left: "ask for", right: "pedir" },
          { left: "attend", right: "asistir a" },
        ],
        explanation: "Cuatro llevan preposición (y no la que esperas); \"attend\" no lleva ninguna.",
      },
      {
        type: "listen-choose",
        audio: "Call me when you get home, and don't forget to answer my email.",
        question: "¿Qué has oído?",
        options: ["Llámame cuando llegues a casa y no olvides contestar mi correo.", "Llámame a casa y contesta mi llamada.", "Ven a casa cuando contestes mi correo.", "No me llames a casa; escríbeme un correo."],
        correctIndex: 0,
        explanation: "\"Call me\" (sin \"to\"), \"get home\" (sin \"to\") y \"answer my email\" (sin \"to\").",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Contesta el teléfono, por favor.",
        answer: "Answer the phone, please.",
        altAnswers: ["Please answer the phone.", "Pick up the phone, please.", "Please pick up the phone."],
        explanation: "\"Answer\" va directo: \"answer the phone\", \"answer the question\". No *answer to.",
      },
      {
        type: "multiple-choice",
        question: "¿Cuál de estas frases tiene un error?",
        options: ["I'll call to you tonight.", "I'll call you tonight.", "I'll phone you tonight.", "I'll give you a call tonight."],
        correctIndex: 0,
        explanation: "\"Call\" + persona, sin \"to\": \"I'll call you\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "No te preocupes por el dinero.",
        answer: "Don't worry about the money.",
        altAnswers: ["Don't worry about money."],
        explanation: "«Preocuparse por» es \"worry about\", no *worry for.",
      },
      {
        type: "dictation",
        audio: "Wait for me here. I'm looking for my keys.",
        explanation: "\"Wait for\" + persona y \"look for\" («buscar») + cosa.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Pregúntale a Sofia; ella lo sabe.",
        answer: "Ask Sofia; she knows.",
        altAnswers: ["Ask Sofia, she knows.", "Ask Sofia. She knows."],
        explanation: "\"Ask\" + persona, sin \"to\": *Ask to Sofia es un calco de «preguntarle a».",
      },
    ],
  },
  // ---------------------------------------------------------------------
  // Extra 6. In / on / at drill
  // ---------------------------------------------------------------------
  {
    slug: "en-a2-in-on-at-drill-1",
    optional: true,
    level: "EN-A2",
    number: 6,
    title: "Práctica extra: en = in, on o at",
    summary: "Práctica rápida y mezclada de \"in\", \"on\" y \"at\" para lugar y tiempo: \"on the bus\", \"in the car\", \"at work\", \"on Monday morning\", \"at night\", \"on the weekend\".",
    duration: "10 min",
    sections: [
      {
        heading: "Repaso rápido: lugar",
        body: [
          "\"In\" es dentro de un espacio: \"in the kitchen\", \"in the car\", \"in Lima\". \"On\" es sobre una superficie, un piso, un transporte grande o un medio: \"on the table\", \"on the third floor\", \"on the bus\", \"on TV\". \"At\" es un punto o el lugar de una actividad: \"at home\", \"at work\", \"at the door\", \"at the party\".",
          "Errores típicos: *in the bus (se dice \"on the bus\"), *in the work (\"at work\"), *in the wall (\"on the wall\").",
        ],
        examples: [
          { es: "Your glasses are on the kitchen table.", en: "Tus gafas están en la mesa de la cocina." },
          { es: "There's nobody in the office today.", en: "No hay nadie en la oficina hoy." },
          { es: "I'm on the bus.", en: "Estoy en el autobús." },
          { es: "She lives on the fifth floor.", en: "Vive en el quinto piso." },
          { es: "I'll see you at the door.", en: "Te veo en la puerta." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "«Estoy en el autobús.» ¿Cuál es correcta?",
            options: ["I'm on the bus.", "I'm in the bus.", "I'm at the bus.", "I'm by the bus."],
            correctIndex: 0,
            explanation: "Los transportes grandes llevan \"on\": \"on the bus\", \"on the train\". \"In\" es para el coche y el taxi.",
          },
          {
            type: "fill-blank",
            prompt: "Escribe en inglés las palabras en negrita.",
            sentence: "Your glasses are ___ the kitchen table.",
            answer: "on",
            en: "Tus gafas están [en] la mesa de la cocina.",
            explanation: "Sobre una superficie: \"on the table\".",
          },
        ],
      },
      {
        heading: "Repaso rápido: tiempo",
        body: [
          "\"In\" con meses, años, estaciones y partes del día: \"in May\", \"in 1995\", \"in the summer\", \"in the morning\". \"On\" con días y fechas: \"on Monday\", \"on May 3rd\", y también \"on Monday morning\" y \"on the weekend\" (en Estados Unidos). \"At\" con horas y \"at night\": \"at six\", \"at noon\", \"at night\".",
          "Sin preposición con \"next\", \"last\", \"this\", \"every\": \"next week\", \"last Friday\", \"every day\".",
        ],
        examples: [
          { es: "She was born in 1995.", en: "Nació en 1995." },
          { es: "See you on Monday morning.", en: "Nos vemos el lunes por la mañana." },
          { es: "The stars come out at night.", en: "Las estrellas salen por la noche." },
          { es: "We usually eat out on Fridays.", en: "Normalmente comemos fuera los viernes." },
          { es: "I'm starting a new job next month.", en: "Empiezo un trabajo nuevo el mes que viene." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "«Nació en 1995.» ¿Cuál es correcta?",
            options: ["She was born in 1995.", "She was born on 1995.", "She was born at 1995.", "She borned in 1995."],
            correctIndex: 0,
            explanation: "Los años llevan \"in\". Y «nacer» es \"be born\": \"was born\".",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "There's nobody ___ the office today.",
        answer: "in",
        altAnswers: ["at"],
        en: "No hay nadie [en] la oficina hoy.",
        explanation: "Dentro del edificio: \"in the office\". \"At the office\" (en el lugar de trabajo) también es correcto.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Mi cumpleaños es el 3 de mayo.",
        answer: "My birthday is on May 3rd.",
        altAnswers: [
          "My birthday is on May 3.",
          "My birthday is on the 3rd of May.",
          "My birthday is on May third.",
          "My birthday is on the third of May.",
          "My birthday is May 3rd.",
          "My birthday is May 3.",
          "My birthday is on 3 May.",
          "My birthday is on 3rd May.",
        ],
        explanation: "Las fechas concretas llevan \"on\": \"on May 3rd\". En inglés americano se dice \"May third\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Nos vemos el lunes por la mañana.",
        answer: "See you on Monday morning.",
        altAnswers: ["I'll see you on Monday morning.", "See you Monday morning.", "I'll see you Monday morning."],
        explanation: "Un día concreto con su parte del día lleva \"on\": \"on Monday morning\", no *in Monday morning.",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "The stars come out ___ night.",
        answer: "at",
        en: "Las estrellas salen [por la] noche.",
        explanation: "\"At night\", aunque sea \"in the morning\" y \"in the evening\".",
      },
      {
        type: "multiple-choice",
        question: "«Vive en el quinto piso.» ¿Cuál es correcta?",
        options: ["She lives on the fifth floor.", "She lives in the fifth floor.", "She lives at the fifth floor.", "She lives in the floor five."],
        correctIndex: 0,
        explanation: "Los pisos de un edificio llevan \"on\": \"on the fifth floor\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Te veo en la puerta a las ocho.",
        answer: "I'll see you at the door at eight.",
        altAnswers: ["See you at the door at eight.", "I'll meet you at the door at eight.", "I'll see you at the door at eight o'clock."],
        explanation: "Un punto de encuentro lleva \"at\" (\"at the door\") y la hora también (\"at eight\").",
      },
      {
        type: "matching",
        instructions: "Une cada preposición con su uso.",
        pairs: [
          { left: "in", right: "dentro de un espacio; meses y años" },
          { left: "on", right: "sobre una superficie; días y fechas" },
          { left: "at", right: "un punto o una actividad; horas" },
          { left: "by", right: "un medio de transporte sin artículo" },
        ],
        explanation: "Un solo «en» en español, cuatro preposiciones en inglés.",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "We usually eat out ___ Fridays.",
        answer: "on",
        en: "Normalmente comemos fuera [los] viernes.",
        explanation: "Los días de la semana llevan \"on\", también en plural: \"on Fridays\" («los viernes»).",
      },
      {
        type: "multiple-choice",
        question: "«En verano vamos a la playa.» ¿Cuál es correcta?",
        options: ["In the summer we go to the beach.", "On summer we go to the beach.", "At summer we go to the beach.", "In the summers we go to the beach."],
        correctIndex: 0,
        explanation: "Las estaciones llevan \"in\": \"in the summer\" o \"in summer\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Mis padres están en la playa.",
        answer: "My parents are at the beach.",
        altAnswers: ["My parents are on the beach."],
        explanation: "La playa como lugar de actividad: \"at the beach\". Si piensas en la arena, \"on the beach\". Nunca *in the beach.",
      },
      {
        type: "listen-choose",
        audio: "I'll be at the station at ten on Saturday morning.",
        question: "¿Qué has oído?",
        options: ["Estaré en la estación a las diez el sábado por la mañana.", "Estaré en la estación el sábado a las diez de la noche.", "Salgo de la estación a las diez el domingo.", "Llegaré a la estación el sábado a las dos."],
        correctIndex: 0,
        explanation: "\"At the station\" (lugar), \"at ten\" (hora) y \"on Saturday morning\" (día).",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Lo escuché en la radio.",
        answer: "I heard it on the radio.",
        altAnswers: ["I listened to it on the radio."],
        explanation: "Los medios llevan \"on\": \"on the radio\", \"on TV\", \"on the internet\".",
      },
      {
        type: "word-order",
        prompt: "Ordena las palabras.",
        words: ["My", "brother", "is", "at", "work", "until", "six."],
        translation: "Mi hermano está en el trabajo hasta las seis.",
        explanation: "\"At work\" sin artículo, y \"until\" para «hasta».",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "La reunión es a las tres de la tarde.",
        answer: "The meeting is at three in the afternoon.",
        altAnswers: ["The meeting is at three p.m.", "The meeting is at 3 p.m.", "The meeting is at three pm.", "The meeting is at 3pm.", "The meeting is at three o'clock in the afternoon."],
        explanation: "Las horas llevan \"at\" y «de la tarde» es \"in the afternoon\" o \"p.m.\".",
      },
      {
        type: "multiple-choice",
        question: "¿Cuál de estas frases tiene un error?",
        options: ["See you in Monday.", "See you on Monday.", "See you next Monday.", "See you at noon."],
        correctIndex: 0,
        explanation: "Los días llevan \"on\". Con \"next\" no hay preposición, y «al mediodía» es \"at noon\".",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "I left my phone ___ the taxi.",
        answer: "in",
        en: "Me dejé el teléfono [en] el taxi.",
        explanation: "Coche y taxi llevan \"in\"; autobús, tren y avión llevan \"on\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Hay alguien en la puerta.",
        answer: "There's someone at the door.",
        altAnswers: ["There's somebody at the door."],
        explanation: "La puerta como punto: \"at the door\". \"In the door\" sería dentro de la puerta.",
      },
      {
        type: "dictation",
        audio: "We met at a party in London in 2019.",
        explanation: "\"At a party\" (evento), \"in London\" (ciudad) e \"in 2019\" (año).",
      },
    ],
  },
];
