// Synced from cheneygross-afk/lengo:src/lib/lessons/en-a1-u8.ts by scripts/sync-content.mjs -- edit it there, not here.
import type { Lesson } from "./types";

// English for Spanish speakers, A1 · Unit 8 (see en-a1.ts for the whole
// level and the authoring conventions).
export const EN_A1_U8: Lesson[] = [
  {
    slug: "this-that-these-those",
    level: "EN-A1",
    number: 1,
    title: "This, that, these y those",
    summary: "Este, ese, estos y esos: cerca o lejos, singular o plural, \"this one\" y \"This is Ana\" al teléfono.",
    duration: "10 min",
    sections: [
      {
        heading: "This y that: cerca y lejos",
        body: [
          "\"This\" señala algo que está cerca de ti: \"this book\" es «este libro». \"That\" señala algo que está más lejos: \"that car\" es «ese coche» o «aquel coche». El inglés solo tiene dos distancias, no tres como el español.",
          "No tienen género: \"this\" vale para este, esta y esto; \"that\" vale para ese, esa, eso, aquel y aquella.",
        ],
        examples: [
          { es: "This book is very good.", en: "Este libro es muy bueno." },
          { es: "This house is old.", en: "Esta casa es vieja." },
          { es: "That car is new.", en: "Ese coche es nuevo." },
          { es: "That woman is my teacher.", en: "Aquella mujer es mi profesora." },
          { es: "What is this?", en: "¿Qué es esto?" },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "es-en",
            prompt: "Traduce al inglés.",
            source: "Este libro es muy bueno.",
            answer: "This book is very good.",
            altAnswers: ["This book is really good."],
            explanation: "«Este», algo cercano, es \"this\". No cambia con el género: \"this book\", \"this house\".",
          },
          {
            type: "fill-blank",
            prompt: "Escribe en inglés las palabras en negrita.",
            sentence: "___ car is new.",
            answer: "That",
            en: "[Ese] coche es nuevo.",
            explanation: "«Ese» y «aquel» son \"that\": algo que no está a tu lado.",
          },
        ],
      },
      {
        heading: "These y those: el plural",
        body: [
          "En plural, \"this\" se convierte en \"these\" (estos, estas) y \"that\" en \"those\" (esos, esas, aquellos, aquellas).",
          "Cuidado con la pronunciación: \"this\" tiene una i corta y relajada y termina en \"s\"; \"these\" tiene una i larga, como en \"see\", y termina en un sonido de \"z\". Si los pronuncias igual, nadie sabe si hablas de uno o de varios.",
          "Los adjetivos nunca van en plural: \"these red cars\", nunca *these reds cars.",
        ],
        examples: [
          { es: "These shoes are new.", en: "Estos zapatos son nuevos." },
          { es: "These apples are green.", en: "Estas manzanas son verdes." },
          { es: "Those people are my friends.", en: "Esas personas son mis amigos." },
          { es: "Those houses are very big.", en: "Aquellas casas son muy grandes." },
          { es: "I like these red cars.", en: "Me gustan estos coches rojos." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "¿Cómo se dice «estas manzanas»?",
            options: ["these apples", "this apples", "those apples", "these apple"],
            correctIndex: 0,
            explanation: "«Estas», cerca y en plural, es \"these\", y el sustantivo va en plural: \"apples\".",
          },
          {
            type: "translate",
            direction: "es-en",
            prompt: "Traduce al inglés.",
            source: "Esos chicos son mis primos.",
            answer: "Those boys are my cousins.",
            altAnswers: ["Those kids are my cousins.", "Those guys are my cousins."],
            explanation: "«Esos» es \"those\". «Primos» es \"cousins\", que vale para primos y primas.",
          },
        ],
      },
      {
        heading: "This one, that one",
        body: [
          "Cuando ya está claro de qué hablas, no repites el sustantivo: el inglés añade \"one\". «Quiero este» es \"I want this one\"; «prefiero ese» es \"I prefer that one\". La pregunta es \"Which one?\" (¿cuál?).",
          "\"This\" y \"that\" también funcionan solos para cosas que no nombras: \"What is this?\" (¿qué es esto?), \"I don't like that\" (eso no me gusta).",
        ],
        examples: [
          { es: "Which one?", en: "¿Cuál?" },
          { es: "I want this one.", en: "Quiero este." },
          { es: "I prefer that one.", en: "Prefiero ese." },
          { es: "What's that?", en: "¿Qué es eso?" },
          { es: "I don't like that.", en: "Eso no me gusta." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "es-en",
            prompt: "Traduce al inglés.",
            source: "Prefiero este.",
            answer: "I prefer this one.",
            altAnswers: ["I prefer this."],
            explanation: "Para no repetir el sustantivo se dice \"this one\". \"I prefer this\" se entiende, pero \"this one\" es lo natural cuando eliges entre varias cosas.",
          },
          {
            type: "translate",
            direction: "es-en",
            prompt: "Traduce al inglés.",
            source: "¿Qué es eso?",
            answer: "What is that?",
            explanation: "«Eso», algo que no está a tu lado, es \"that\". Y la pregunta necesita el verbo \"is\".",
          },
        ],
      },
      {
        heading: "Al teléfono y al presentar: \"This is...\"",
        body: [
          "Al teléfono, para decir quién eres, se usa \"This is Ana\" o \"It's Ana\", no \"I am Ana\". Para preguntar si hablas con alguien: \"Is this Carlos?\".",
          "Para presentar a alguien también se usa \"this\": \"This is my friend Tom\" equivale a «te presento a mi amigo Tom». Con varias personas: \"These are my parents\".",
        ],
        examples: [
          { es: "Hi, this is Ana.", en: "Hola, soy Ana. (al teléfono)" },
          { es: "Is this Carlos?", en: "¿Hablo con Carlos?" },
          { es: "This is my friend Tom.", en: "Te presento a mi amigo Tom." },
          { es: "These are my parents.", en: "Estos son mis padres." },
        ],
        checkpoint: [
          {
            type: "fill-blank",
            prompt: "Escribe en inglés las palabras en negrita.",
            sentence: "Hi, ___ is Sofia.",
            answer: "this",
            altAnswers: ["it"],
            en: "(Al teléfono) Hola, [soy] Sofia.",
            explanation: "Al teléfono uno se presenta con \"This is...\" o \"It's...\", no con \"I am...\".",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Esta es mi hermana Lucia.",
        answer: "This is my sister Lucia.",
        altAnswers: ["This is my sister, Lucia."],
        explanation: "Para presentar a alguien: \"This is...\". \"This\" no cambia aunque «esta» sea femenino.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Aquellas casas son muy grandes.",
        answer: "Those houses are very big.",
        altAnswers: ["Those houses are very large.", "Those houses are really big."],
        explanation: "«Aquellas», lejos y en plural, es \"those\". El adjetivo \"big\" no va en plural.",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "Are ___ your shoes?",
        answer: "these",
        en: "¿Son [estos] tus zapatos?",
        explanation: "«Estos», cerca y en plural, es \"these\", con i larga.",
      },
      {
        type: "matching",
        instructions: "Une cada palabra con su significado.",
        pairs: [
          { left: "this", right: "este / esta / esto" },
          { left: "that", right: "ese / aquel / eso" },
          { left: "these", right: "estos / estas" },
          { left: "those", right: "esos / aquellos" },
        ],
        explanation: "\"This\" y \"these\" para lo cercano; \"that\" y \"those\" para lo lejano.",
      },
      {
        type: "multiple-choice",
        question: "Estás al teléfono. ¿Cómo dices «hola, soy Diego»?",
        options: ["Hi, this is Diego.", "Hi, I'm being Diego.", "Hi, here Diego.", "Hi, that is Diego."],
        correctIndex: 0,
        explanation: "Al teléfono te presentas con \"This is...\" (o \"It's...\"). \"That is Diego\" señalaría a otra persona.",
      },
      {
        type: "word-order",
        prompt: "Ordena las palabras.",
        words: ["I", "don't", "like", "that", "one."],
        translation: "No me gusta ese.",
        explanation: "\"That one\" evita repetir el sustantivo.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "¿Cuánto cuesta esto?",
        answer: "How much is this?",
        altAnswers: ["How much does this cost?"],
        explanation: "«Esto» es \"this\". En una tienda, \"How much is this?\" es la pregunta más natural.",
      },
      {
        type: "listen-choose",
        audio: "These are my keys.",
        question: "¿Qué has oído?",
        options: ["Estas son mis llaves.", "Esta es mi llave.", "Esas son mis llaves.", "¿Son estas mis llaves?"],
        correctIndex: 0,
        explanation: "\"These\" (i larga, final en \"z\") es plural y cercano: «estas».",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Estos libros son interesantes.",
        answer: "These books are interesting.",
        explanation: "\"These\" + plural. El adjetivo \"interesting\" nunca lleva -s.",
      },
      {
        type: "speak",
        text: "This is my brother, and these are my sisters.",
        tip: "\"This\" tiene una i corta y termina en \"s\"; \"these\" tiene una i larga y termina en \"z\". Exagera la diferencia.",
        explanation: "\"This is\" para uno, \"these are\" para varios.",
      },
      {
        type: "dictation",
        audio: "Those are my friends.",
        explanation: "\"Those\" es el plural de \"that\": esos o aquellos.",
      },
    ],
  },
  {
    slug: "object-pronouns-imperative",
    level: "EN-A1",
    number: 2,
    title: "Pronombres de objeto y el imperativo",
    summary: "Me, him, her, us, them detrás del verbo (\"I love her\") y cómo dar órdenes e instrucciones: \"Open the door\", \"Don't run\", \"Let's go\".",
    duration: "12 min",
    sections: [
      {
        heading: "Me, you, him, her, it, us, them",
        body: [
          "Cuando la persona o la cosa recibe la acción, el inglés usa otras formas del pronombre: \"me\" (me, a mí), \"you\" (te, lo, la, a ti, a usted), \"him\" (lo, le, a él), \"her\" (la, le, a ella), \"it\" (lo, la, para cosas), \"us\" (nos) y \"them\" (los, las, les).",
          "La gran diferencia con el español es el orden: estos pronombres van siempre detrás del verbo. «La quiero» es \"I love her\", nunca *I her love. «Te llamo» es \"I call you\".",
          "Y no se mezclan con las formas de sujeto: \"I know her\", no \"I know she\".",
        ],
        examples: [
          { es: "I love her.", en: "La quiero." },
          { es: "She knows him.", en: "Lo conoce." },
          { es: "Can you help me?", en: "¿Me puedes ayudar?" },
          { es: "We call them every day.", en: "Los llamamos todos los días." },
          { es: "I like it.", en: "Me gusta." },
          { es: "They visit us on Sundays.", en: "Nos visitan los domingos." },
        ],
        checkpoint: [
          {
            type: "fill-blank",
            prompt: "Escribe en inglés las palabras en negrita.",
            sentence: "Can you help ___?",
            answer: "me",
            en: "¿[Me] puedes ayudar?",
            explanation: "El pronombre va detrás del verbo: \"help me\". Nunca *Can you me help?.",
          },
          {
            type: "translate",
            direction: "es-en",
            prompt: "Traduce al inglés.",
            source: "Te quiero.",
            answer: "I love you.",
            explanation: "Sujeto + verbo + objeto: \"I love you\". El orden del español («te» delante) no funciona en inglés.",
          },
        ],
      },
      {
        heading: "Después de preposiciones",
        body: [
          "Detrás de preposiciones como \"with\", \"for\", \"to\" o \"about\" también se usan estas formas: \"with me\" (conmigo), \"with you\" (contigo), \"for him\" (para él), \"for them\" (para ellos).",
          "Fíjate en cómo cambia todo según quién hace la acción: \"He likes her\" (ella le gusta a él) frente a \"She likes him\" (él le gusta a ella).",
        ],
        examples: [
          { es: "Come with me.", en: "Ven conmigo." },
          { es: "This is for you.", en: "Esto es para ti." },
          { es: "The gift is for them.", en: "El regalo es para ellos." },
          { es: "I talk to her every day.", en: "Hablo con ella todos los días." },
          { es: "He likes her.", en: "Ella le gusta a él." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "¿Cómo se dice «¿quieres venir conmigo?»?",
            options: ["Do you want to come with me?", "Do you want to come with I?", "Do you want come with me?", "Do you want to come me with?"],
            correctIndex: 0,
            explanation: "Detrás de \"with\" va \"me\", no \"I\". Y \"want\" necesita \"to\" delante del verbo.",
          },
          {
            type: "translate",
            direction: "es-en",
            prompt: "Traduce al inglés.",
            source: "Este regalo es para ellos.",
            answer: "This gift is for them.",
            altAnswers: ["This present is for them."],
            explanation: "Detrás de \"for\" se usa \"them\", no \"they\".",
          },
        ],
      },
      {
        heading: "El imperativo: \"Open the door\"",
        body: [
          "Para dar órdenes o instrucciones se usa el verbo en forma base, sin sujeto: \"Open the door\", \"Sit down\", \"Listen\". Es la misma forma para tú, usted y ustedes.",
          "Como no cambia, el tono lo pone \"please\", y en inglés se usa mucho más que «por favor» en español. \"Open the window\" a secas puede sonar brusco; \"Open the window, please\" o \"Please open the window\" es lo normal.",
        ],
        examples: [
          { es: "Open the door, please.", en: "Abre la puerta, por favor." },
          { es: "Sit down.", en: "Siéntate. / Siéntese." },
          { es: "Listen to me.", en: "Escúchame." },
          { es: "Please wait here.", en: "Espere aquí, por favor." },
          { es: "Call me tomorrow.", en: "Llámame mañana." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "es-en",
            prompt: "Traduce al inglés.",
            source: "Abre la ventana, por favor.",
            answer: "Open the window, please.",
            altAnswers: ["Please open the window."],
            explanation: "Imperativo: verbo en forma base, sin sujeto. \"Please\" puede ir al principio o al final.",
          },
        ],
      },
      {
        heading: "Don't run. Let's go.",
        body: [
          "Para prohibir se pone \"don't\" delante del verbo: \"Don't run\" (no corras), \"Don't touch it\" (no lo toques). Nunca *No run ni *Not run.",
          "Para proponer algo que hacemos juntos se usa \"let's\" + verbo: \"Let's go\" (vamos), \"Let's eat\" (comamos). Es la forma natural de decir «vamos a...» cuando propones un plan.",
        ],
        examples: [
          { es: "Don't run!", en: "¡No corras!" },
          { es: "Don't touch it.", en: "No lo toques." },
          { es: "Don't be late.", en: "No llegues tarde." },
          { es: "Let's go!", en: "¡Vamos!" },
          { es: "Let's eat something.", en: "Comamos algo." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "es-en",
            prompt: "Traduce al inglés.",
            source: "No corras.",
            answer: "Don't run.",
            altAnswers: ["Do not run."],
            explanation: "Imperativo negativo: \"don't\" + verbo. Nunca *No run.",
          },
          {
            type: "fill-blank",
            prompt: "Escribe en inglés las palabras en negrita.",
            sentence: "___ go to the beach!",
            answer: "Let's",
            en: "¡[Vamos] a la playa!",
            explanation: "Para proponer un plan juntos: \"Let's\" + verbo. \"We go to the beach\" sería solo una descripción.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Llámame mañana.",
        answer: "Call me tomorrow.",
        explanation: "Imperativo sin sujeto, y \"me\" detrás del verbo: \"call me\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "No lo toques.",
        answer: "Don't touch it.",
        altAnswers: ["Don't touch him.", "Do not touch it."],
        explanation: "\"Don't\" + verbo, y el pronombre detrás: \"touch it\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Ayúdanos, por favor.",
        answer: "Help us, please.",
        altAnswers: ["Please help us."],
        explanation: "«Nos» es \"us\", y va detrás del verbo.",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "I see ___ every day.",
        answer: "them",
        en: "[Los] veo todos los días.",
        explanation: "«Los» es \"them\" y va detrás del verbo: \"I see them\".",
      },
      {
        type: "multiple-choice",
        question: "¿Cómo se dice «la conozco» (a una mujer)?",
        options: ["I know her.", "I her know.", "I know she.", "I know to her."],
        correctIndex: 0,
        explanation: "Objeto detrás del verbo y con la forma de objeto: \"her\", no \"she\".",
      },
      {
        type: "word-order",
        prompt: "Ordena las palabras.",
        words: ["Don't", "forget", "your", "keys."],
        translation: "No olvides tus llaves.",
        explanation: "Imperativo negativo: \"Don't\" + verbo.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Comamos algo.",
        answer: "Let's eat something.",
        altAnswers: ["Let's have something to eat."],
        explanation: "Para proponer algo juntos: \"Let's\" + verbo.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Él la quiere, pero ella no lo quiere.",
        answer: "He loves her, but she doesn't love him.",
        altAnswers: ["He loves her but she doesn't love him."],
        explanation: "Sujeto \"he\", objeto \"him\"; sujeto \"she\", objeto \"her\". Y \"loves\" lleva -s en tercera persona.",
      },
      {
        type: "listen-choose",
        audio: "Sit down, please.",
        question: "¿Qué has oído?",
        options: ["Siéntate, por favor.", "Levántate, por favor.", "Espera aquí, por favor.", "No te sientes."],
        correctIndex: 0,
        explanation: "\"Sit down\" es «siéntate»; \"stand up\" sería «levántate».",
      },
      {
        type: "matching",
        instructions: "Une cada pronombre con su significado.",
        pairs: [
          { left: "me", right: "me, a mí" },
          { left: "him", right: "lo, le, a él" },
          { left: "us", right: "nos" },
          { left: "them", right: "los, las, les" },
        ],
        explanation: "Todos van detrás del verbo o de la preposición.",
      },
      {
        type: "speak",
        text: "Let's go! Don't be late.",
        tip: "\"Let's\" suena \"lets\", con una e corta. En \"don't\" la o es como la de \"go\".",
        explanation: "\"Let's\" propone un plan; \"don't\" prohíbe.",
      },
      {
        type: "dictation",
        audio: "Give me the book, please.",
        explanation: "\"Give me\": imperativo + \"me\" detrás del verbo.",
      },
    ],
  },
  {
    slug: "a1-spiral-review",
    level: "EN-A1",
    number: 3,
    title: "Repaso en espiral del A1",
    summary: "Todo lo visto hasta ahora en un mismo lugar: to be, presente simple y continuo, posesivos, números, la hora, preguntas, like, can y there is.",
    duration: "12 min",
    sections: [
      {
        heading: "To be y el presente simple",
        body: [
          "\"To be\" es ser y estar: \"I am\", \"you are\", \"he is\". También se usa para la edad, donde el español usa tener: \"I am 25\", nunca *I have 25 years.",
          "En el presente simple, la tercera persona lleva -s: \"she works\", \"he lives\". En negativas y preguntas aparece \"do\" o \"does\", y entonces el verbo pierde la -s: \"Does she work here?\", \"He doesn't live here\".",
          "Y nunca olvides el sujeto: \"It is cold\", \"She is a teacher\".",
        ],
        examples: [
          { es: "I am 25 years old.", en: "Tengo 25 años." },
          { es: "She works in a hospital.", en: "Trabaja en un hospital." },
          { es: "Does he live here?", en: "¿Vive aquí?" },
          { es: "They don't speak French.", en: "No hablan francés." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "es-en",
            prompt: "Traduce al inglés.",
            source: "Mi hermano tiene treinta años.",
            answer: "My brother is thirty.",
            altAnswers: ["My brother is 30.", "My brother is thirty years old.", "My brother is 30 years old."],
            explanation: "La edad se dice con \"to be\": \"he is thirty\". Nunca *has thirty years.",
          },
          {
            type: "fill-blank",
            prompt: "Escribe en inglés las palabras en negrita.",
            sentence: "Ana ___ in Madrid.",
            answer: "lives",
            en: "Ana [vive] en Madrid.",
            explanation: "Tercera persona del presente simple: \"lives\", con -s.",
          },
        ],
      },
      {
        heading: "Ahora o siempre: simple y continuo",
        body: [
          "El presente simple es para rutinas y verdades generales: \"I work every day\". El presente continuo (\"to be\" + -ing) es para lo que está pasando ahora: \"I'm working now\".",
          "Verbos como \"like\", \"love\", \"want\", \"know\" o \"have\" (de poseer) casi nunca van en continuo: \"I want a coffee\", no *I'm wanting a coffee.",
        ],
        examples: [
          { es: "I work every day.", en: "Trabajo todos los días." },
          { es: "I'm working now.", en: "Estoy trabajando ahora." },
          { es: "She usually walks to work, but today she's taking the bus.", en: "Normalmente va caminando al trabajo, pero hoy va en autobús." },
          { es: "I know the answer.", en: "Sé la respuesta." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "¿Cómo se dice «ahora está lloviendo»?",
            options: ["It's raining now.", "It rains now.", "Is raining now.", "It raining now."],
            correctIndex: 0,
            explanation: "Lo que pasa ahora va en presente continuo, con sujeto \"it\" y el verbo \"is\": \"It's raining\".",
          },
        ],
      },
      {
        heading: "Posesivos, números y la hora",
        body: [
          "«Su» no existe en inglés como palabra única: depende de quién es el dueño. \"His car\" es el coche de él; \"her car\" es el de ella; \"their car\" es el de ellos. Para decir «el coche de Ana» se usa \"Ana's car\".",
          "La hora se pregunta con \"What time is it?\" y se responde con \"it\": \"It's seven thirty\" o \"It's half past seven\".",
        ],
        examples: [
          { es: "This is her car.", en: "Este es su coche (de ella)." },
          { es: "That's Carlos's house.", en: "Esa es la casa de Carlos." },
          { es: "What time is it?", en: "¿Qué hora es?" },
          { es: "It's half past seven.", en: "Son las siete y media." },
          { es: "It costs fifteen dollars.", en: "Cuesta quince dólares." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "es-en",
            prompt: "Traduce al inglés.",
            source: "Este es el perro de mi hermana.",
            answer: "This is my sister's dog.",
            explanation: "«El perro de mi hermana» se dice con el genitivo: \"my sister's dog\". Nunca *the dog of my sister.",
          },
        ],
      },
      {
        heading: "Preguntas, like, can y there is",
        body: [
          "Las preguntas con palabra interrogativa siguen el orden pregunta + auxiliar + sujeto + verbo: \"Where do you live?\", \"What does she do?\".",
          "Recuerda las piezas de la última unidad: \"I like swimming\" (la persona es el sujeto), \"Can you swim?\" (sin \"do\") y \"Is there a bank near here?\" («hay» es \"there is\").",
        ],
        examples: [
          { es: "Where do you live?", en: "¿Dónde vives?" },
          { es: "What does she do?", en: "¿A qué se dedica?" },
          { es: "Do you like dancing?", en: "¿Te gusta bailar?" },
          { es: "Can you drive?", en: "¿Sabes conducir?" },
          { es: "Is there a pharmacy near here?", en: "¿Hay una farmacia cerca de aquí?" },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "es-en",
            prompt: "Traduce al inglés.",
            source: "¿Dónde trabaja tu padre?",
            answer: "Where does your father work?",
            altAnswers: ["Where does your dad work?"],
            explanation: "Pregunta + \"does\" + sujeto + verbo sin -s: \"Where does your father work?\".",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Es médica y trabaja en un hospital.",
        answer: "She is a doctor and she works in a hospital.",
        altAnswers: ["She is a doctor and works in a hospital.", "She's a doctor, and she works in a hospital."],
        explanation: "Sujeto obligatorio, \"a\" delante de la profesión y \"works\" con -s.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "No me gusta el café, pero me encanta el té.",
        answer: "I don't like coffee, but I love tea.",
        altAnswers: ["I don't like coffee but I love tea."],
        explanation: "La persona es el sujeto en las dos partes: \"I don't like\", \"I love\". Sin \"the\" para gustos generales.",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "___ a park near my house.",
        answer: "There is",
        altAnswers: ["There's"],
        en: "[Hay] un parque cerca de mi casa.",
        explanation: "«Hay» + singular es \"there is\". Nunca \"It has\".",
      },
      {
        type: "multiple-choice",
        question: "¿Cómo se dice «¿sabes cocinar?»?",
        options: ["Can you cook?", "Do you can cook?", "Do you know cook?", "Can you to cook?"],
        correctIndex: 0,
        explanation: "\"Can\" forma la pregunta sin \"do\" y va seguido del verbo sin \"to\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "¿Qué estás haciendo?",
        answer: "What are you doing?",
        explanation: "Lo que pasa ahora: presente continuo, con \"are\" delante del sujeto en la pregunta.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Su madre es profesora. (la madre de Carlos)",
        answer: "His mother is a teacher.",
        altAnswers: ["His mom is a teacher.", "His mum is a teacher."],
        explanation: "El dueño es Carlos, un hombre, así que «su» es \"his\". El posesivo concuerda con el dueño, no con la cosa.",
      },
      {
        type: "word-order",
        prompt: "Ordena las palabras.",
        words: ["What", "time", "do", "you", "get", "up?"],
        translation: "¿A qué hora te levantas?",
        explanation: "\"What time\" + \"do\" + sujeto + verbo.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Quisiera dos entradas, por favor.",
        answer: "I would like two tickets, please.",
        altAnswers: ["Can I have two tickets, please?", "Could I have two tickets, please?"],
        explanation: "\"I'd like\" es la forma educada de pedir. «Entrada» (de cine o de concierto) es \"ticket\".",
      },
      {
        type: "listen-choose",
        audio: "My sister doesn't like this one.",
        question: "¿Qué has oído?",
        options: ["A mi hermana no le gusta este.", "A mi hermana le gusta este.", "A mi hermana no le gusta ese.", "Mi hermana no tiene este."],
        correctIndex: 0,
        explanation: "\"Doesn't like\" es «no le gusta», y \"this one\" es «este».",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "Please call ___ tonight.",
        answer: "her",
        en: "Por favor, [llámala] esta noche.",
        explanation: "«La» (a ella) es \"her\", detrás del verbo \"call\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Son las ocho y cuarto.",
        answer: "It's a quarter past eight.",
        altAnswers: ["It's quarter past eight.", "It's eight fifteen.", "It is 8:15."],
        explanation: "La hora siempre con \"it\": \"It's a quarter past eight\" o, más sencillo, \"It's eight fifteen\".",
      },
      {
        type: "dictation",
        audio: "Is there a bus stop near here?",
        explanation: "\"Is there...?\" pregunta si hay algo.",
      },
    ],
  },
];
