// Synced from cheneygross-afk/lengo:src/lib/lessons/en-a1-u9.ts by scripts/sync-content.mjs -- edit it there, not here.
import type { Lesson } from "./types";

// English for Spanish speakers, A1 · Unit 9 (see en-a1.ts for the whole
// level and the authoring conventions).
export const EN_A1_U9: Lesson[] = [
  {
    slug: "a1-final-review-1",
    level: "EN-A1",
    number: 1,
    title: "Repaso final del nivel Fundamentos, parte 1 de 3",
    summary: "Un repaso exigente de todo el nivel, con frases más largas que mezclan varios temas a la vez.",
    duration: "12 min",
    sections: [
      {
        heading: "Las cinco trampas del hispanohablante",
        body: [
          "Antes de pasar al nivel Ganando fluidez, repasa los errores que más delatan a un hispanohablante: omitir el sujeto (*Is late en lugar de \"It is late\"), decir la edad con \"have\" (*I have 20 years), olvidar la -s de tercera persona (*she work), usar \"do\" con \"can\" (*Do you can...?) y traducir «hay» como \"it has\".",
          "Si controlas estos cinco puntos, tu inglés ya suena mucho más natural. Los ejercicios de esta lección los mezclan a propósito.",
        ],
        examples: [
          { es: "It is late.", en: "Es tarde." },
          { es: "I am 20.", en: "Tengo 20 años." },
          { es: "She works from home.", en: "Trabaja desde casa." },
          { es: "Can you help me?", en: "¿Me puedes ayudar?" },
          { es: "There is a problem.", en: "Hay un problema." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "es-en",
            prompt: "Traduce al inglés.",
            source: "Hace calor y hay mucha gente en la playa.",
            answer: "It is hot and there are a lot of people on the beach.",
            altAnswers: [
              "It's hot, and there are a lot of people on the beach.",
              "It is hot and there are a lot of people at the beach.",
              "It is hot and there are many people on the beach.",
              "It is hot and there are many people at the beach.",
            ],
            explanation: "Dos trampas en una frase: el tiempo necesita \"it\" y «hay» con plural es \"there are\". \"People\" ya es plural.",
          },
        ],
      },
      {
        heading: "El orden de las palabras",
        body: [
          "El inglés es mucho más rígido que el español con el orden: sujeto + verbo + objeto + lugar + tiempo. \"I see my friends at the park on Sundays\".",
          "Los adjetivos van delante del sustantivo y no tienen plural (\"two big houses\"), los pronombres de objeto van detrás del verbo (\"I call her\") y los adverbios de frecuencia van delante del verbo principal pero detrás de \"to be\": \"I always walk\", \"She is always late\".",
        ],
        examples: [
          { es: "We have two big dogs.", en: "Tenemos dos perros grandes." },
          { es: "I call her every Sunday.", en: "La llamo todos los domingos." },
          { es: "He always has breakfast at home.", en: "Siempre desayuna en casa." },
          { es: "She is never late.", en: "Nunca llega tarde." },
        ],
        checkpoint: [
          {
            type: "word-order",
            prompt: "Ordena las palabras.",
            words: ["She", "is", "never", "late", "for", "work."],
            translation: "Nunca llega tarde al trabajo.",
            explanation: "Con \"to be\", el adverbio de frecuencia va detrás: \"is never\".",
          },
          {
            type: "translate",
            direction: "es-en",
            prompt: "Traduce al inglés.",
            source: "Tienen tres coches rojos.",
            answer: "They have three red cars.",
            altAnswers: ["They've got three red cars.", "They have got three red cars."],
            explanation: "El adjetivo va delante y sin plural: \"red cars\", nunca *cars reds ni *reds cars.",
          },
        ],
      },
      {
        heading: "Palabras que engañan",
        body: [
          "Algunas palabras inglesas se parecen a palabras españolas pero significan otra cosa. \"Library\" es biblioteca (librería es \"bookstore\"), \"parents\" son los padres (parientes es \"relatives\") y \"actually\" significa «en realidad», no «actualmente».",
          "\"Embarrassed\" es «avergonzado», no «embarazada» (que es \"pregnant\"). Y el inglés \"sensible\" significa «sensato»; nuestro «sensible» se dice \"sensitive\".",
        ],
        examples: [
          { es: "I study at the library.", en: "Estudio en la biblioteca." },
          { es: "My parents live in Lima.", en: "Mis padres viven en Lima." },
          { es: "Actually, I'm from Chile.", en: "En realidad, soy de Chile." },
          { es: "I'm embarrassed.", en: "Me da vergüenza." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "¿Qué significa \"My parents are at the library\"?",
            options: ["Mis padres están en la biblioteca.", "Mis parientes están en la librería.", "Mis padres están en la librería.", "Mis parientes están en la biblioteca."],
            correctIndex: 0,
            explanation: "\"Parents\" son los padres y \"library\" es la biblioteca: dos falsos amigos clásicos.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Mi hermana tiene diecinueve años y estudia en Londres.",
        answer: "My sister is nineteen and she studies in London.",
        altAnswers: [
          "My sister is 19 and she studies in London.",
          "My sister is nineteen years old and she studies in London.",
          "My sister is 19 years old and she studies in London.",
          "My sister is nineteen and studies in London.",
          "My sister is 19 and studies in London.",
        ],
        explanation: "La edad con \"is\", y \"studies\" con -ies en tercera persona (consonante + y).",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "¿A qué hora empieza la clase?",
        answer: "What time does the class start?",
        altAnswers: ["What time does the class begin?", "When does the class start?", "What time does class start?"],
        explanation: "\"What time\" + \"does\" + sujeto + verbo sin -s.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "No hay leche en casa.",
        answer: "There is no milk at home.",
        altAnswers: ["There isn't any milk at home.", "There is no milk in the house.", "There isn't any milk in the house."],
        explanation: "\"Milk\" es incontable, así que va con \"there isn't any\" o \"there is no\".",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "My brother ___ speak German, but he can speak French.",
        answer: "can't",
        altAnswers: ["cannot"],
        en: "Mi hermano [no sabe] hablar alemán, pero sabe hablar francés.",
        explanation: "\"Can't\" es igual para todas las personas, sin \"doesn't\": nunca *He doesn't can.",
      },
      {
        type: "multiple-choice",
        question: "¿Cuál es la frase correcta?",
        options: [
          "Her husband doesn't work on Saturdays.",
          "Her husband don't work on Saturdays.",
          "Her husband doesn't works on Saturdays.",
          "His husband doesn't work on Saturdays.",
        ],
        correctIndex: 0,
        explanation: "Tercera persona: \"doesn't\" + verbo sin -s. Y el marido de ella es \"her husband\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Ahora estoy cocinando, ¿puedes llamarme más tarde?",
        answer: "I'm cooking now. Can you call me later?",
        altAnswers: [
          "I'm cooking right now, can you call me later?",
          "I'm cooking now, can you call me later?",
          "I'm cooking now. Could you call me later?",
          "I'm cooking right now. Can you call me later?",
          "I'm cooking now, could you call me later?",
        ],
        explanation: "Presente continuo para lo que pasa ahora, \"can\" sin \"do\" y \"me\" detrás del verbo.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "A Diego le gusta jugar al fútbol con sus amigos.",
        answer: "Diego likes playing soccer with his friends.",
        altAnswers: [
          "Diego likes playing football with his friends.",
          "Diego likes to play soccer with his friends.",
          "Diego likes to play football with his friends.",
        ],
        explanation: "\"Likes\" + -ing, y «sus» amigos de Diego es \"his friends\". Los deportes van sin artículo: \"play soccer\" (\"football\" en el Reino Unido).",
      },
      {
        type: "word-order",
        prompt: "Ordena las palabras.",
        words: ["Is", "there", "a", "good", "restaurant", "near", "here?"],
        translation: "¿Hay un buen restaurante cerca de aquí?",
        explanation: "Pregunta con \"Is there\", y el adjetivo \"good\" delante del sustantivo.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Estos zapatos son demasiado caros. Prefiero esos.",
        answer: "These shoes are too expensive. I prefer those.",
        altAnswers: ["These shoes are too expensive. I prefer those ones.", "These shoes are too expensive, I prefer those."],
        explanation: "\"These\" para lo cercano, \"those\" para lo lejano. «Demasiado» delante de un adjetivo es \"too\".",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "___ late, please.",
        answer: "Don't be",
        altAnswers: ["Do not be"],
        en: "[No llegues] tarde, por favor.",
        explanation: "«Llegar tarde» es \"be late\", y la prohibición es \"don't\" + verbo: \"Don't be late\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "En realidad, mis padres no viven aquí.",
        answer: "Actually, my parents don't live here.",
        explanation: "\"Actually\" es «en realidad» y \"parents\" son los padres. \"Don't\" porque el sujeto es plural.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "¿Cuántos hermanos tienes?",
        answer: "How many brothers and sisters do you have?",
        altAnswers: [
          "How many siblings do you have?",
          "How many brothers do you have?",
          "How many brothers and sisters have you got?",
          "How many siblings have you got?",
        ],
        explanation: "\"How many\" + plural + \"do you have?\". «Hermanos» en general es \"brothers and sisters\" o \"siblings\".",
      },
    ],
  },
  {
    slug: "a1-final-review-2",
    level: "EN-A1",
    number: 2,
    title: "Repaso final del nivel Fundamentos, parte 2 de 3",
    summary: "El último paso del nivel Fundamentos: presentarte, contar tu rutina por escrito y entender inglés hablado.",
    duration: "12 min",
    sections: [
      {
        heading: "Presentarte en inglés",
        body: [
          "Con lo que ya sabes puedes presentarte por completo: tu nombre (\"My name is...\"), tu edad (\"I am...\"), de dónde eres (\"I'm from...\"), dónde vives (\"I live in...\") y a qué te dedicas (\"I'm a nurse\", \"I work in a bank\").",
          "Recuerda el artículo con las profesiones: \"I'm a teacher\", no *I'm teacher. Y las nacionalidades y los idiomas van con mayúscula: \"I'm Mexican\", \"I speak Spanish\".",
        ],
        examples: [
          { es: "My name is Lucia.", en: "Me llamo Lucia." },
          { es: "I'm 32 and I'm from Colombia.", en: "Tengo 32 años y soy de Colombia." },
          { es: "I live in Bogota with my husband.", en: "Vivo en Bogotá con mi marido." },
          { es: "I'm a nurse.", en: "Soy enfermera." },
          { es: "I speak Spanish and a little English.", en: "Hablo español y un poco de inglés." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "es-en",
            prompt: "Traduce al inglés.",
            source: "Soy profesor y vivo en Buenos Aires.",
            answer: "I'm a teacher and I live in Buenos Aires.",
            altAnswers: ["I am a teacher and live in Buenos Aires.", "I'm a teacher, and I live in Buenos Aires."],
            explanation: "\"A\" delante de la profesión y el sujeto \"I\" en cada verbo.",
          },
        ],
      },
      {
        heading: "Contar tu rutina",
        body: [
          "Para la rutina se usa el presente simple con expresiones de tiempo: \"I get up at seven\", \"I have breakfast at half past seven\", \"I go to work by bus\".",
          "Para ordenar lo que haces, usa \"first\", \"then\" y \"after that\". Y los adverbios de frecuencia (\"always\", \"usually\", \"sometimes\", \"never\") van delante del verbo: \"I usually walk to work\".",
        ],
        examples: [
          { es: "I get up at seven.", en: "Me levanto a las siete." },
          { es: "First, I have a shower.", en: "Primero me ducho." },
          { es: "Then I have breakfast.", en: "Luego desayuno." },
          { es: "I usually go to work by bus.", en: "Normalmente voy al trabajo en autobús." },
          { es: "In the evening, I watch TV.", en: "Por la noche veo la tele." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "es-en",
            prompt: "Traduce al inglés.",
            source: "Normalmente ceno a las nueve.",
            answer: "I usually have dinner at nine.",
            altAnswers: ["I usually have dinner at 9.", "I usually eat dinner at nine.", "I usually eat dinner at 9.", "I normally have dinner at nine.", "Usually I have dinner at nine."],
            explanation: "\"Usually\" va delante del verbo, y «cenar» es \"have dinner\", sin artículo.",
          },
        ],
      },
      {
        heading: "Entender inglés hablado",
        body: [
          "Al escuchar, el inglés une las palabras y reduce las que no son importantes: \"What do you\" suena casi como una sola palabra, y \"can\" en una afirmativa suena /kən/. Concéntrate en las palabras acentuadas: los verbos, los sustantivos y las negaciones.",
          "Las negaciones (\"don't\", \"can't\", \"isn't\") siempre llevan acento, así que si oyes una sílaba fuerte en ese lugar, probablemente la frase es negativa.",
        ],
        examples: [
          { es: "What do you do?", en: "¿A qué te dedicas?" },
          { es: "I can come.", en: "Puedo venir." },
          { es: "I can't come.", en: "No puedo venir." },
          { es: "She doesn't eat meat.", en: "No come carne." },
        ],
        checkpoint: [
          {
            type: "listen-choose",
            audio: "What do you do?",
            question: "¿Qué te están preguntando?",
            options: ["¿A qué te dedicas?", "¿Qué estás haciendo?", "¿Qué quieres?", "¿Qué te gusta?"],
            correctIndex: 0,
            explanation: "\"What do you do?\" pregunta por tu trabajo. \"What are you doing?\" sería «¿qué estás haciendo?».",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Me llamo Carlos, tengo veintiocho años y soy de Perú.",
        answer: "My name is Carlos, I'm twenty-eight and I'm from Peru.",
        altAnswers: [
          "My name is Carlos, I'm 28 and I'm from Peru.",
          "My name's Carlos, I'm twenty-eight years old and I'm from Peru.",
          "My name is Carlos, I'm 28 years old, and I'm from Peru.",
          "I'm Carlos, I'm 28 and I'm from Peru.",
        ],
        explanation: "\"My name is\", la edad con \"I'm\" y \"I'm from\" para el origen. Sujeto en cada parte.",
      },
      {
        type: "dictation",
        audio: "I get up at seven and I have a shower.",
        explanation: "\"Get up\" es levantarse y \"have a shower\" es ducharse.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Mi marido trabaja en un banco, pero hoy está en casa.",
        answer: "My husband works in a bank, but today he is at home.",
        altAnswers: [
          "My husband works at a bank, but today he is at home.",
          "My husband works in a bank, but he is at home today.",
          "My husband works at a bank, but he is at home today.",
        ],
        explanation: "\"Works\" para su trabajo habitual, \"is at home\" para hoy. Y hace falta \"he\" en la segunda parte.",
      },
      {
        type: "listen-choose",
        audio: "She can't come today because she's working.",
        question: "¿Qué has oído?",
        options: [
          "Hoy no puede venir porque está trabajando.",
          "Hoy puede venir porque no trabaja.",
          "Hoy no puede venir porque está enferma.",
          "Mañana no puede venir porque trabaja.",
        ],
        correctIndex: 0,
        explanation: "\"Can't\" se oye fuerte, y \"she's working\" es presente continuo: lo que pasa ahora.",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "I ___ to work by bus.",
        answer: "usually go",
        altAnswers: ["normally go"],
        en: "[Normalmente voy] al trabajo en autobús.",
        explanation: "El adverbio de frecuencia va delante del verbo: \"usually go\". «Ir en autobús» es \"go by bus\".",
      },
      {
        type: "dictation",
        audio: "There are four people in my family.",
        explanation: "\"There are\" para un plural; \"people\" ya es plural.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Los sábados no trabajo; me gusta ir al cine con mis amigos.",
        answer: "I don't work on Saturdays; I like going to the movies with my friends.",
        altAnswers: [
          "I don't work on Saturdays. I like going to the movies with my friends.",
          "I don't work on Saturdays; I like to go to the movies with my friends.",
          "I don't work on Saturdays. I like to go to the movies with my friends.",
          "I don't work on Saturdays; I like going to the cinema with my friends.",
          "I don't work on Saturdays. I like going to the cinema with my friends.",
          "On Saturdays I don't work; I like going to the movies with my friends.",
          "On Saturdays I don't work. I like going to the movies with my friends.",
        ],
        explanation: "\"On Saturdays\" para algo habitual, \"like\" + -ing. «Ir al cine» es \"go to the movies\" (o \"the cinema\" en el Reino Unido).",
      },
      {
        type: "listen-choose",
        audio: "Is there a pharmacy near here?",
        question: "¿Qué te están preguntando?",
        options: ["¿Hay una farmacia cerca de aquí?", "¿Dónde está la farmacia?", "¿Tienes una farmacia?", "¿Hay muchas farmacias aquí?"],
        correctIndex: 0,
        explanation: "\"Is there...?\" pregunta si hay algo. \"Where is the pharmacy?\" sería «¿dónde está la farmacia?».",
      },
      {
        type: "multiple-choice",
        question: "Alguien te pregunta \"Where are you from?\". ¿Qué respondes?",
        options: ["I'm from Spain.", "I'm of Spain.", "I have from Spain.", "From Spain I am."],
        correctIndex: 0,
        explanation: "«Ser de» un lugar es \"to be from\": \"I'm from Spain\". Nunca *I'm of.",
      },
      {
        type: "write",
        prompt: "Preséntate en inglés: di cómo te llamas, cuántos años tienes, de dónde eres, a qué te dedicas y cuenta cómo es un día normal para ti (a qué hora te levantas, qué haces y qué te gusta hacer).",
        minWords: 50,
        maxWords: 110,
        rubric: [
          "Dice el nombre, la edad con \"I am\" (no \"I have\"), el origen y la profesión con \"a\".",
          "Describe la rutina en presente simple con horas (\"at seven\").",
          "Usa al menos un adverbio de frecuencia (\"usually\", \"always\", \"sometimes\").",
          "Incluye algo que le gusta hacer con \"like\" o \"love\" + -ing.",
          "Pone sujeto en todas las frases.",
        ],
        modelAnswer:
          "My name is Sofia. I'm 27 and I'm from Mexico, but I live in Chicago. I'm a nurse and I work in a big hospital. On weekdays I get up at six thirty. First I have a shower, then I have breakfast with my husband. I usually go to work by bus. I finish work at four, and in the evening I cook dinner. I love reading, and on Sundays I like walking in the park with my friends.",
        explanation: "Revisa los cinco puntos clave: sujeto en cada frase, \"I am\" para la edad, la -s de tercera persona, \"a\" con la profesión y el -ing detrás de \"like\".",
      },
      {
        type: "speak",
        text: "Hi! My name is Tom. I'm a teacher, and I live in London.",
        tip: "Acentúa las palabras importantes (\"Tom\", \"teacher\", \"London\") y deja débiles \"a\" y \"and\".",
        explanation: "Una presentación natural: nombre, profesión con \"a\" y dónde vives.",
      },
      {
        type: "dictation",
        audio: "Would you like to come with us?",
        explanation: "\"Would you like to\" + verbo para invitar, y \"us\" detrás de \"with\".",
      },
    ],
  },
];
