// Synced from cheneygross-afk/lengo:src/lib/lessons/en-a2-u06-extra.ts by scripts/sync-content.mjs -- edit it there, not here.
import type { Lesson } from "./types";

// Extra practice (optional) lessons for EN-A2 unit u06.

export const EN_A2_U06_EXTRA: Lesson[] = [
  // ---------------------------------------------------------------------
  {
    slug: "en-a2-just-already-yet-drill-1",
    optional: true,
    level: "EN-A2",
    number: 1,
    title: "Práctica extra: just, already y yet",
    summary: "Práctica intensiva de la posición y el significado de \"just\", \"already\" y \"yet\": «acabo de», «ya» y «todavía no».",
    duration: "10 min",
    sections: [
      {
        heading: "Recordatorio: \"just\" y \"already\" van en medio",
        body: [
          "«Acabo de» es \"just\" y «ya» (en afirmativas) es \"already\". Las dos van entre \"have\" y el participio: \"I've just eaten\", \"She's already left\". El error típico es ponerlas antes de \"have\": *I already have eaten, *I just have arrived.",
          "\"Already\" también puede ir al final (\"I've seen it already\"), pero nunca al principio como «ya». En inglés americano oirás también el pasado simple: \"I just ate\", \"She already left\".",
        ],
        examples: [
          { es: "I've just eaten.", en: "Acabo de comer. (incorrecto: *I just have eaten)" },
          { es: "She's already left.", en: "Ella ya se ha ido. (incorrecto: *Already she has left)" },
          { es: "We've just got home.", en: "Acabamos de llegar a casa." },
          { es: "I've seen that movie already.", en: "Ya he visto esa película." },
          { es: "They already paid.", en: "Ya pagaron. (muy americano)" },
        ],
        checkpoint: [
          {
            type: "word-order",
            prompt: "Ordena las palabras.",
            words: ["I've", "already", "sent", "the", "email."],
            translation: "Ya he enviado el correo.",
            altOrders: [["I've", "sent", "the", "email", "already."]],
            explanation: "\"Already\" va entre \"have\" y el participio, o al final de la frase. Nunca delante de \"have\".",
          },
          {
            type: "fill-blank",
            prompt: "Escribe en inglés las palabras en negrita.",
            sentence: "My brother has ___ arrived.",
            answer: "just",
            en: "Mi hermano [acaba de] llegar.",
            explanation: "Toda la idea de «acabar de» la lleva \"just\", entre \"has\" y el participio \"arrived\".",
          },
        ],
      },
      {
        heading: "Recordatorio: \"yet\" va al final",
        body: [
          "\"Yet\" se usa en negativas y preguntas, y va al FINAL: \"I haven't finished yet\" («todavía no he terminado»), \"Have you finished yet?\" («¿ya has terminado?»). No se usa en afirmativas: *I have finished yet no significa nada.",
          "«Todavía no» es \"not... yet\", no \"still not\" (aunque \"I still haven't finished\" existe y es correcto, con más énfasis). En las preguntas, «¿ya...?» es normalmente \"...yet?\"; \"already\" en una pregunta expresa sorpresa: \"Have you finished already?\" («¿ya has terminado? ¡Qué rápido!»).",
        ],
        examples: [
          { es: "I haven't finished yet.", en: "Todavía no he terminado. (incorrecto: *I have finished yet)" },
          { es: "Have you eaten yet?", en: "¿Ya has comido?" },
          { es: "She hasn't called yet.", en: "Ella todavía no ha llamado." },
          { es: "Not yet.", en: "Todavía no." },
          { es: "Has he finished already? That was quick!", en: "¿Ya ha terminado? ¡Qué rápido!" },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "¿Cómo se dice «todavía no hemos decidido»?",
            options: ["We haven't decided yet.", "We have decided yet.", "We haven't decided already.", "We yet haven't decided."],
            correctIndex: 0,
            explanation: "«Todavía no» es \"haven't\" + participio + \"yet\", con \"yet\" al final. \"Already\" no se usa en negativas.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Acabo de ver a Lucia.",
        answer: "I've just seen Lucia.",
        altAnswers: ["I just saw Lucia."],
        explanation: "«Acabo de ver» = \"I've just seen\". \"Just\" va entre \"have\" y el participio; en inglés americano también \"I just saw\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Ya han comido.",
        answer: "They've already eaten.",
        altAnswers: ["They've eaten already.", "They already ate.", "They've already had lunch.", "They already had lunch."],
        explanation: "\"Already\" entre \"have\" y \"eaten\". El sujeto \"they\" es obligatorio aunque en español no aparezca.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Todavía no he hablado con él.",
        answer: "I haven't talked to him yet.",
        altAnswers: ["I haven't spoken to him yet.", "I haven't talked with him yet.", "I haven't spoken with him yet.", "I still haven't talked to him.", "I still haven't spoken to him."],
        explanation: "«Todavía no» = \"haven't... yet\", con \"yet\" al final. *I haven't talked yet with him pone \"yet\" en un sitio raro.",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "Has the package arrived ___?",
        answer: "yet",
        en: "¿[Ya] ha llegado el paquete?",
        explanation: "«¿Ya...?» en una pregunta normal es \"...yet?\", al final. \"Already\" en la pregunta sonaría a sorpresa.",
      },
      {
        type: "multiple-choice",
        question: "¿Qué frase es correcta?",
        options: ["I've already eaten.", "I already have eaten.", "I've eaten yet.", "Already I've eaten."],
        correctIndex: 0,
        explanation: "\"Already\" va después de \"have\": \"I've already eaten\". *I already have eaten es el calco del orden español «ya he comido».",
      },
      {
        type: "word-order",
        prompt: "Ordena las palabras.",
        words: ["She", "hasn't", "answered", "yet."],
        translation: "Ella todavía no ha contestado.",
        explanation: "En negativas, \"yet\" cierra la frase: \"hasn't answered yet\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "¿Ya has reservado el hotel?",
        answer: "Have you booked the hotel yet?",
        altAnswers: ["Have you already booked the hotel?", "Have you booked the hotel already?", "Did you book the hotel yet?", "Did you already book the hotel?", "Have you reserved the hotel yet?", "Have you already reserved the hotel?", "Did you reserve the hotel yet?"],
        explanation: "La pregunta neutra lleva \"yet\" al final. «Reservar» un hotel es \"book\" (o \"reserve\"); no uses *reservate.",
      },
      {
        type: "multiple-choice",
        question: "¿Cómo se dice «todavía no he terminado»?",
        options: ["I haven't finished yet.", "I have finished yet.", "I haven't finished already.", "I don't have finished yet."],
        correctIndex: 0,
        explanation: "Negativa del presente perfecto: \"haven't\" + participio, y \"yet\" al final. *I have finished yet no es una negativa, y *I don't have finished mezcla dos negaciones.",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "We've ___ left the office.",
        answer: "just",
        en: "[Acabamos de] salir de la oficina.",
        explanation: "«Acabamos de salir» = \"We've just left\". No traduzcas «acabar» con \"finish\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "El autobús acaba de salir.",
        answer: "The bus has just left.",
        altAnswers: ["The bus just left.", "The bus has just gone.", "The bus just went."],
        explanation: "\"Has just\" + participio (\"left\"). Con un sujeto como \"the bus\" se suele escribir \"has\" sin contraer.",
      },
      {
        type: "listen-choose",
        audio: "I haven't seen it yet.",
        question: "¿Qué has oído?",
        options: ["Todavía no lo he visto.", "Ya lo he visto.", "Acabo de verlo.", "No lo vi."],
        correctIndex: 0,
        explanation: "\"Haven't... yet\" = «todavía no». Escucha la negación \"haven't\" y el \"yet\" final.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Ya lo sé.",
        answer: "I already know.",
        altAnswers: ["I know already.", "I already know that.", "I know that already."],
        explanation: "Con \"know\" (un verbo de estado) se usa el presente simple: \"I already know\". *I have already known it suena mal aquí.",
      },
      {
        type: "word-order",
        prompt: "Ordena las palabras.",
        words: ["Have", "you", "paid", "yet?"],
        translation: "¿Ya has pagado?",
        explanation: "Pregunta: \"Have\" + sujeto + participio + \"yet\" al final.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Mi hermana acaba de tener un bebé.",
        answer: "My sister has just had a baby.",
        altAnswers: ["My sister just had a baby."],
        explanation: "«Tener un bebé» es \"have a baby\"; el participio de \"have\" es \"had\": \"has just had\".",
      },
      {
        type: "dictation",
        audio: "They've already gone home.",
        explanation: "\"They've already gone home\": «ya se han ido a casa». Fíjate en \"already\" entre \"have\" y \"gone\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Todavía no están aquí.",
        answer: "They aren't here yet.",
        altAnswers: ["They're not here yet.", "They still aren't here.", "They're still not here."],
        explanation: "\"Yet\" también funciona con \"to be\" en negativa: \"They aren't here yet\". No hace falta el presente perfecto para usar \"yet\".",
      },
      {
        type: "multiple-choice",
        question: "¿Qué frase es correcta?",
        options: ["She hasn't called me yet.", "She hasn't called me already.", "She yet hasn't called me.", "She hasn't yet call me."],
        correctIndex: 0,
        explanation: "En negativa se usa \"yet\" (no \"already\") y va al final. El participio es \"called\".",
      },
      {
        type: "speak",
        text: "I've just started. I haven't finished yet.",
        tip: "\"Yet\" se pronuncia con la \"e\" corta de \"bed\", no como «yit».",
        explanation: "\"I've just started\" («acabo de empezar») y \"I haven't finished yet\" («todavía no he terminado»).",
      },
    ],
  },
  // ---------------------------------------------------------------------
  {
    slug: "en-a2-for-since-drill-1",
    optional: true,
    level: "EN-A2",
    number: 2,
    title: "Práctica extra: for y since, parte 1",
    summary: "Elegir \"for\" o \"since\" según la expresión de tiempo: \"for three years\", \"since 2020\", \"since Monday\", \"for ages\".",
    duration: "10 min",
    sections: [
      {
        heading: "Recordatorio: \"for\" + duración",
        body: [
          "\"For\" va con un periodo, una cantidad de tiempo: \"for ten minutes\", \"for two weeks\", \"for three years\", \"for a long time\", \"for ages\". Responde a «¿cuánto tiempo?».",
          "En español esto suele ser «desde hace» o «llevo + tiempo»: «desde hace tres años» es \"for three years\". El error típico es usar \"since\" con una cantidad: *since three years.",
        ],
        examples: [
          { es: "I've lived here for three years.", en: "Vivo aquí desde hace tres años. (incorrecto: *since three years)" },
          { es: "We've been waiting for twenty minutes.", en: "Llevamos veinte minutos esperando." },
          { es: "She's worked there for a long time.", en: "Ella trabaja allí desde hace mucho tiempo." },
          { es: "I haven't seen him for ages.", en: "Hace muchísimo que no lo veo." },
        ],
        checkpoint: [
          {
            type: "fill-blank",
            prompt: "Escribe en inglés las palabras en negrita.",
            sentence: "They've been married ___ fifteen years.",
            answer: "for",
            en: "Llevan casados [desde hace] quince años.",
            explanation: "\"Fifteen years\" es una cantidad de tiempo, así que va con \"for\".",
          },
        ],
      },
      {
        heading: "Recordatorio: \"since\" + punto de partida",
        body: [
          "\"Since\" va con el momento en que algo empezó: \"since 2020\", \"since Monday\", \"since ten o'clock\", \"since last summer\", \"since I was a child\". Responde a «¿desde cuándo?».",
          "Es el «desde» español sin «hace»: «desde el lunes» es \"since Monday\". El error típico es poner \"for\" con una fecha: *for 2019.",
        ],
        examples: [
          { es: "I've lived here since 2020.", en: "Vivo aquí desde 2020. (incorrecto: *for 2020)" },
          { es: "She's been sick since Monday.", en: "Ella está enferma desde el lunes." },
          { es: "We've been here since ten o'clock.", en: "Estamos aquí desde las diez." },
          { es: "I've known Tom since we were kids.", en: "Conozco a Tom desde que éramos niños." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "¿Cuál es la frase correcta?",
            options: ["He's been in Paris since March.", "He's been in Paris for March.", "He's in Paris since March.", "He's been in Paris since three months."],
            correctIndex: 0,
            explanation: "\"March\" es un punto de partida, así que \"since\". Con \"three months\" (cantidad) sería \"for\". Y hace falta el presente perfecto: \"has been\".",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "I've lived in this apartment ___ 2019.",
        answer: "since",
        en: "Vivo en este apartamento [desde] 2019.",
        explanation: "Un año concreto es un punto de partida: \"since 2019\".",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "She's been in the hospital ___ two weeks.",
        answer: "for",
        en: "Ella está en el hospital [desde hace] dos semanas.",
        explanation: "«Desde hace» + cantidad es \"for\": \"for two weeks\".",
      },
      {
        type: "multi-select",
        question: "¿Qué expresiones van con \"for\"?",
        options: ["three years", "2020", "Monday", "ages", "a long time", "last summer", "ten minutes"],
        correctIndexes: [0, 3, 4, 6],
        explanation: "\"For\" va con cantidades de tiempo: \"three years\", \"ages\", \"a long time\", \"ten minutes\". Los demás son momentos y van con \"since\".",
      },
      {
        type: "multi-select",
        question: "¿Qué expresiones van con \"since\"?",
        options: ["yesterday", "two hours", "I was a child", "this morning", "a week", "March"],
        correctIndexes: [0, 2, 3, 5],
        explanation: "\"Since\" va con el momento en que algo empezó: \"yesterday\", \"I was a child\", \"this morning\", \"March\". \"Two hours\" y \"a week\" son cantidades: \"for\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Trabajamos juntos desde hace seis meses.",
        answer: "We've worked together for six months.",
        altAnswers: ["We've been working together for six months."],
        explanation: "«Desde hace seis meses» = \"for six months\", con presente perfecto. *We work together since six months tiene dos errores.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "No la veo desde el verano pasado.",
        answer: "I haven't seen her since last summer.",
        explanation: "«Desde el verano pasado» es un punto de partida: \"since last summer\". El presente español («no la veo») se vuelve presente perfecto en inglés.",
      },
      {
        type: "multiple-choice",
        question: "¿Cómo se dice «vivo aquí desde hace tres años»?",
        options: ["I've lived here for three years.", "I've lived here since three years.", "I live here since three years.", "I live here for three years."],
        correctIndex: 0,
        explanation: "Cantidad de tiempo = \"for\", y el verbo va en presente perfecto, no en presente simple como en español.",
      },
      {
        type: "multiple-choice",
        question: "¿Cómo se dice «ella estudia inglés desde 2019»?",
        options: ["She's studied English since 2019.", "She's studied English for 2019.", "She studies English since 2019.", "She studied English for 2019."],
        correctIndex: 0,
        explanation: "\"2019\" es un punto de partida: \"since 2019\". *For 2019 es imposible, y el presente simple o el pasado cambian el sentido.",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "They've known each other ___ they were kids.",
        answer: "since",
        en: "Se conocen [desde que] eran niños.",
        explanation: "«Desde que» + frase es \"since\" + frase en pasado simple: \"since they were kids\".",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "We've been here ___ ages.",
        answer: "for",
        en: "Llevamos aquí [desde hace] muchísimo tiempo.",
        explanation: "\"Ages\" («siglos», mucho tiempo) es una cantidad: \"for ages\".",
      },
      {
        type: "matching",
        instructions: "Une cada expresión con su significado.",
        pairs: [
          { left: "for ten minutes", right: "desde hace diez minutos" },
          { left: "since ten o'clock", right: "desde las diez" },
          { left: "for a long time", right: "desde hace mucho tiempo" },
          { left: "since Monday", right: "desde el lunes" },
          { left: "since I was a child", right: "desde que era niño" },
        ],
        explanation: "\"For\" + cantidad («desde hace»); \"since\" + momento o frase («desde», «desde que»).",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Está lloviendo desde esta mañana.",
        answer: "It's been raining since this morning.",
        explanation: "«Desde esta mañana» = \"since this morning\". Para una acción que sigue, lo natural es \"has been raining\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Tengo este teléfono desde hace un año.",
        answer: "I've had this phone for a year.",
        altAnswers: ["I've had this phone for one year."],
        explanation: "«Tengo... desde hace» = \"I've had... for\". El presente perfecto de \"have\" es \"have had\".",
      },
      {
        type: "listen-choose",
        audio: "I've been here since Monday.",
        question: "¿Qué has oído?",
        options: ["Estoy aquí desde el lunes.", "Estuve aquí el lunes.", "Llevo aquí un mes.", "Vengo aquí los lunes."],
        correctIndex: 0,
        explanation: "\"Since Monday\" = «desde el lunes»; \"I've been here\" = «estoy aquí (desde entonces)».",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Mi hermano está en Chile desde marzo.",
        answer: "My brother has been in Chile since March.",
        explanation: "El presente español con «desde» es presente perfecto en inglés: \"has been in Chile since March\". *My brother is in Chile since March es el error típico.",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "He's been a teacher ___ twenty years.",
        answer: "for",
        en: "Es profesor [desde hace] veinte años.",
        explanation: "\"Twenty years\" es una cantidad: \"for twenty years\".",
      },
      {
        type: "dictation",
        audio: "We've been friends for a long time.",
        explanation: "\"For a long time\" = «desde hace mucho tiempo». «Somos amigos desde hace mucho» se dice en presente perfecto: \"We've been friends\".",
      },
    ],
  },
  // ---------------------------------------------------------------------
  {
    slug: "en-a2-for-since-drill-2",
    optional: true,
    level: "EN-A2",
    number: 3,
    title: "Práctica extra: for y since, parte 2",
    summary: "Traducir «hace X que...», «desde hace» y «llevo X años» al presente perfecto con \"for\" y \"since\", y preguntar con \"How long...?\".",
    duration: "10 min",
    sections: [
      {
        heading: "Recordatorio: «hace X que» y «llevo X» = presente perfecto + \"for\"",
        body: [
          "El español tiene tres maneras de decir lo mismo: «hace dos años que vivo aquí», «vivo aquí desde hace dos años» y «llevo dos años aquí». Las tres son UNA sola en inglés: \"I've lived here for two years\" (o \"I've been living here for two years\").",
          "Los errores típicos son el presente simple (*I live here since 2010) y \"to be\" con \"for\" (*I am here for two years, que suena a «estoy aquí por dos años», un plan). Usa siempre el presente perfecto: \"I've lived\", \"I've been\".",
        ],
        examples: [
          { es: "I've lived here for two years.", en: "Hace dos años que vivo aquí. / Llevo dos años aquí. (incorrecto: *I live here since two years)" },
          { es: "She's been in Peru for a month.", en: "Ella lleva un mes en Perú. (incorrecto: *She is in Peru for a month)" },
          { es: "We've been waiting for an hour.", en: "Llevamos una hora esperando." },
          { es: "I haven't seen him for years.", en: "Hace años que no lo veo." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "es-en",
            prompt: "Traduce al inglés.",
            source: "Hace un año que trabajo aquí.",
            answer: "I've worked here for a year.",
            altAnswers: ["I've been working here for a year.", "I've worked here for one year.", "I've been working here for one year."],
            explanation: "«Hace un año que trabajo» = presente perfecto + \"for a year\". No empieces con *It makes a year.",
          },
        ],
      },
      {
        heading: "Recordatorio: «¿cuánto tiempo hace que...?» = \"How long have you...?\"",
        body: [
          "«¿Cuánto tiempo hace que vives aquí?», «¿desde cuándo vives aquí?» y «¿cuánto llevas aquí?» se preguntan igual: \"How long have you lived here?\". El error típico es *Since how long...? o *How long do you live here?.",
          "La respuesta lleva \"for\" o \"since\": \"For two years\", \"Since 2022\".",
        ],
        examples: [
          { es: "How long have you lived here?", en: "¿Cuánto tiempo hace que vives aquí? (incorrecto: *Since how long do you live here?)" },
          { es: "How long have you known each other?", en: "¿Cuánto hace que se conocen?" },
          { es: "How long has she been sick?", en: "¿Desde cuándo está enferma?" },
          { es: "For two years. / Since 2022.", en: "Desde hace dos años. / Desde 2022." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "¿Cómo se pregunta «¿desde cuándo trabajas aquí?»?",
            options: ["How long have you worked here?", "Since how long do you work here?", "How long do you work here?", "Since when you work here?"],
            correctIndex: 0,
            explanation: "\"How long\" + presente perfecto. *Since how long no existe, y el presente simple preguntaría por tu horario.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Hace dos años que trabajo aquí.",
        answer: "I've worked here for two years.",
        altAnswers: ["I've been working here for two years."],
        explanation: "«Hace dos años que» + presente = presente perfecto + \"for two years\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Llevo una hora esperando.",
        answer: "I've been waiting for an hour.",
        altAnswers: ["I've waited for an hour.", "I've been waiting an hour.", "I've been waiting for one hour."],
        explanation: "«Llevo + tiempo + gerundio» = \"have been\" + -ing + \"for\". *I am waiting since an hour es el error típico.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "¿Cuánto tiempo hace que conoces a Tom?",
        answer: "How long have you known Tom?",
        explanation: "\"How long\" + presente perfecto. \"Know\" no se usa en continuo: *How long have you been knowing es incorrecto.",
      },
      {
        type: "multiple-choice",
        question: "¿Cómo se dice «vivo aquí desde 2010»?",
        options: ["I've lived here since 2010.", "I live here since 2010.", "I'm living here since 2010.", "I lived here since 2010."],
        correctIndex: 0,
        explanation: "Con \"since\" o \"for\" y una situación que sigue, el inglés usa presente perfecto, no presente simple ni continuo.",
      },
      {
        type: "multiple-choice",
        question: "¿Cómo se dice «llevo dos años aquí»?",
        options: ["I've been here for two years.", "I am here for two years.", "I have two years here.", "I'm here since two years."],
        correctIndex: 0,
        explanation: "«Llevo» no se traduce con \"have\" + sustantivo ni con \"am\": es \"I've been here for two years\".",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "___ have they been married?",
        answer: "How long",
        en: "[¿Cuánto tiempo] llevan casados?",
        explanation: "«¿Cuánto tiempo (hace que)...?» es \"How long...?\" con presente perfecto.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Hace años que no voy al cine.",
        answer: "I haven't been to the movies for years.",
        altAnswers: ["I haven't been to the movies in years.", "I haven't gone to the movies for years.", "I haven't gone to the movies in years.", "I haven't been to the cinema for years.", "I haven't been to the cinema in years.", "I haven't gone to the cinema for years.", "I haven't gone to the cinema in years."],
        explanation: "«Hace años que no...» = \"haven't... for years\" (en Estados Unidos también \"in years\"). «Ir al cine» es \"go to the movies\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Ella lleva tres meses en Madrid.",
        answer: "She's been in Madrid for three months.",
        explanation: "«Lleva tres meses en» = \"has been in... for three months\". *She is in Madrid for three months sonaría a un plan futuro.",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "We ___ in this house since 2015.",
        answer: "have lived",
        altAnswers: ["have been living", "'ve lived", "'ve been living"],
        en: "[Vivimos] en esta casa desde 2015.",
        explanation: "El presente español con «desde» se traduce con presente perfecto: \"have lived\" (o \"have been living\").",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Hace mucho que no hablamos.",
        answer: "We haven't talked for a long time.",
        altAnswers: ["We haven't spoken for a long time.", "We haven't talked in a long time.", "We haven't spoken in a long time.", "We haven't talked for ages.", "We haven't spoken for ages.", "We haven't talked in ages.", "We haven't spoken in ages."],
        explanation: "«Hace mucho que no» = negativa del presente perfecto + \"for a long time\" / \"for ages\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "¿Cuánto tiempo llevas en Estados Unidos?",
        answer: "How long have you been in the United States?",
        altAnswers: ["How long have you been in the US?", "How long have you been in the States?", "How long have you been in America?"],
        explanation: "«¿Cuánto llevas en...?» = \"How long have you been in...?\". \"The United States\" lleva \"the\".",
      },
      {
        type: "word-order",
        prompt: "Ordena las palabras.",
        words: ["How", "long", "have", "you", "had", "that", "car?"],
        translation: "¿Cuánto tiempo hace que tienes ese coche?",
        explanation: "\"How long\" + \"have\" + sujeto + participio (\"had\").",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Llevamos diez minutos esperando el autobús.",
        answer: "We've been waiting for the bus for ten minutes.",
        altAnswers: ["We've waited for the bus for ten minutes.", "We've been waiting ten minutes for the bus.", "We've been waiting for the bus ten minutes."],
        explanation: "\"Wait for the bus\" lleva \"for\" (esperar algo), y luego \"for ten minutes\" (la duración). Dos \"for\" distintos.",
      },
      {
        type: "listen-choose",
        audio: "How long have you lived here?",
        question: "¿Qué has oído?",
        options: ["¿Cuánto tiempo hace que vives aquí?", "¿Dónde vives?", "¿Cuánto tiempo viviste aquí?", "¿Te gusta vivir aquí?"],
        correctIndex: 0,
        explanation: "\"How long have you lived\" (presente perfecto) pregunta por algo que sigue: «¿cuánto hace que vives?».",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Diego estudia alemán desde hace un año.",
        answer: "Diego has studied German for a year.",
        altAnswers: ["Diego has been studying German for a year.", "Diego has studied German for one year.", "Diego has been studying German for one year."],
        explanation: "Presente perfecto + \"for a year\". Los idiomas van con mayúscula en inglés: \"German\".",
      },
      {
        type: "speak",
        text: "How long have you been here? I've been here for two years.",
        tip: "\"Been\" en inglés americano suena como «bin», corto.",
        explanation: "Pregunta con \"How long\" y respuesta con \"for\" + cantidad.",
      },
    ],
  },
  // ---------------------------------------------------------------------
  {
    slug: "en-a2-for-since-ago-drill-1",
    optional: true,
    level: "EN-A2",
    number: 4,
    title: "Práctica extra: for, since o ago",
    summary: "Contraste a tres bandas: \"ago\" con pasado simple frente a \"for\" y \"since\" con presente perfecto, y los errores *since two years y *I have arrived two days ago.",
    duration: "10 min",
    sections: [
      {
        heading: "Recordatorio: \"ago\" mira al pasado; \"for\" y \"since\" llegan hasta hoy",
        body: [
          "\"Ago\" significa «hace» y va con el pasado simple: \"I arrived two years ago\" («llegué hace dos años»). Siempre va DESPUÉS de la cantidad: *ago two years es incorrecto.",
          "\"For\" y \"since\" van con el presente perfecto porque la situación sigue: \"I've been here for two years\" («llevo dos años aquí»), \"I've been here since 2024\". Los errores típicos mezclan las dos ideas: *I came here since two years, *I have arrived two days ago.",
        ],
        examples: [
          { es: "I arrived two years ago.", en: "Llegué hace dos años. (incorrecto: *I have arrived two years ago)" },
          { es: "I've been here for two years.", en: "Llevo dos años aquí. (incorrecto: *I came here since two years)" },
          { es: "I've been here since 2024.", en: "Estoy aquí desde 2024." },
          { es: "She called ten minutes ago.", en: "Ella llamó hace diez minutos. (incorrecto: *ago ten minutes)" },
          { es: "She's been on the phone for ten minutes.", en: "Lleva diez minutos al teléfono." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "¿Cómo se dice «llegué hace dos semanas»?",
            options: ["I arrived two weeks ago.", "I arrived ago two weeks.", "I've arrived two weeks ago.", "I arrived since two weeks."],
            correctIndex: 0,
            explanation: "«Hace» + tiempo (momento terminado) es cantidad + \"ago\", con pasado simple.",
          },
          {
            type: "fill-blank",
            prompt: "Escribe en inglés las palabras en negrita.",
            sentence: "I haven't seen him ___ last Christmas.",
            answer: "since",
            en: "No lo veo [desde] la Navidad pasada.",
            explanation: "\"Last Christmas\" es un punto de partida: \"since\". Y la situación sigue (no lo veo), así que presente perfecto.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "multiple-choice",
        question: "¿Cómo se dice «vine aquí hace dos años»?",
        options: ["I came here two years ago.", "I came here since two years.", "I've come here two years ago.", "I came here for two years."],
        correctIndex: 0,
        explanation: "«Vine» es un momento terminado: pasado simple + \"ago\". \"Since\" y \"for\" van con el presente perfecto.",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "She moved to Bogota three years ___.",
        answer: "ago",
        en: "Ella se mudó a Bogotá [hace] tres años.",
        explanation: "«Hace tres años» con un verbo en pasado es \"three years ago\": \"ago\" al final.",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "She's lived in Bogota ___ three years.",
        answer: "for",
        en: "Ella vive en Bogotá [desde hace] tres años.",
        explanation: "Misma situación, pero vista desde hoy: presente perfecto + \"for\" + cantidad.",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "She's lived in Bogota ___ 2023.",
        answer: "since",
        en: "Ella vive en Bogotá [desde] 2023.",
        explanation: "Con un punto de partida (\"2023\") se usa \"since\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Empecé este trabajo hace seis meses.",
        answer: "I started this job six months ago.",
        explanation: "«Empecé hace» = pasado simple + \"ago\". *I have started this job six months ago es incorrecto.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Tengo este trabajo desde hace seis meses.",
        answer: "I've had this job for six months.",
        explanation: "«Tengo... desde hace» = presente perfecto + \"for\". Compara con la frase anterior: misma historia, otro tiempo verbal.",
      },
      {
        type: "multiple-choice",
        question: "¿Qué frase es correcta?",
        options: ["I've known her since 2020.", "I've known her since two years.", "I know her since 2020.", "I've known her two years ago."],
        correctIndex: 0,
        explanation: "\"Since\" + punto de partida + presente perfecto. *Since two years mezcla \"since\" con una cantidad, y \"ago\" no va con el presente perfecto.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Nos conocimos hace mucho tiempo.",
        answer: "We met a long time ago.",
        altAnswers: ["We met ages ago.", "We met many years ago."],
        explanation: "«Nos conocimos» es un momento del pasado: \"we met\" + \"a long time ago\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Nos conocemos desde hace mucho tiempo.",
        answer: "We've known each other for a long time.",
        altAnswers: ["We've known each other for ages.", "We have known each other a long time."],
        explanation: "«Nos conocemos» (situación que sigue) = \"We've known each other\" + \"for\". Compara con \"We met a long time ago\".",
      },
      {
        type: "multi-select",
        question: "¿Cuáles de estas frases son correctas?",
        options: ["I've been here for two days.", "I arrived two days ago.", "I've arrived two days ago.", "I'm here since two days.", "I've been here since Monday."],
        correctIndexes: [0, 1, 4],
        explanation: "\"For\" y \"since\" con presente perfecto; \"ago\" con pasado simple. *I've arrived two days ago y *I'm here since two days son los errores clásicos.",
      },
      {
        type: "word-order",
        prompt: "Ordena las palabras.",
        words: ["They", "got", "married", "five", "years", "ago."],
        translation: "Se casaron hace cinco años.",
        altOrders: [["Five", "years", "ago", "they", "got", "married."]],
        explanation: "\"Ago\" va después de la cantidad: \"five years ago\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "¿Cuándo compraste la casa? Hace un año.",
        answer: "When did you buy the house? A year ago.",
        altAnswers: ["When did you buy the house? One year ago."],
        explanation: "«¿Cuándo?» pide un momento, así que pasado simple (\"did you buy\") y respuesta con \"ago\".",
      },
      {
        type: "listen-choose",
        audio: "I've worked here since January.",
        question: "¿Qué has oído?",
        options: ["Trabajo aquí desde enero.", "Trabajé aquí hasta enero.", "Trabajé aquí hace un año.", "Voy a trabajar aquí en enero."],
        correctIndex: 0,
        explanation: "\"I've worked here since January\" = «trabajo aquí desde enero» (y sigo).",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Ella se fue hace una hora y todavía no ha vuelto.",
        answer: "She left an hour ago and hasn't come back yet.",
        altAnswers: ["She left an hour ago and she hasn't come back yet.", "She left an hour ago and hasn't returned yet.", "She left an hour ago and she hasn't returned yet.", "She left one hour ago and hasn't come back yet.", "She left one hour ago and she hasn't come back yet.", "She left an hour ago and still hasn't come back.", "She left an hour ago and she still hasn't come back."],
        explanation: "Dos tiempos en una frase: \"left... ago\" (momento pasado) y \"hasn't come back yet\" (situación que sigue).",
      },
      {
        type: "dictation",
        audio: "We moved here ten years ago.",
        explanation: "\"Moved\" es pasado simple y \"ten years ago\" lo sitúa en el pasado. Fíjate en que \"ago\" cierra la frase.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Vivo aquí desde hace diez años; me mudé en 2016.",
        answer: "I've lived here for ten years; I moved here in 2016.",
        altAnswers: ["I've lived here for ten years. I moved here in 2016.", "I've been living here for ten years; I moved here in 2016.", "I've lived here for ten years; I moved in 2016.", "I've been living here for ten years. I moved in 2016.", "I've lived here for ten years, I moved here in 2016.", "I've been living here for ten years. I moved here in 2016."],
        explanation: "\"For ten years\" con presente perfecto; \"in 2016\" (fecha terminada) con pasado simple. Con una fecha concreta no se usa \"ago\" ni \"since\".",
      },
    ],
  },
  // ---------------------------------------------------------------------
  {
    slug: "en-a2-pp-vs-past-drill-1",
    optional: true,
    level: "EN-A2",
    number: 5,
    title: "Práctica extra: presente perfecto o pasado, parte 1",
    summary: "Elegir presente perfecto o pasado simple según la expresión de tiempo: \"yesterday\", \"last year\", \"in 2015\" frente a \"ever\", \"this week\", \"today\" o sin tiempo.",
    duration: "10 min",
    sections: [
      {
        heading: "Recordatorio: tiempo terminado = pasado simple",
        body: [
          "Si la frase dice CUÁNDO pasó algo y ese momento ya terminó (\"yesterday\", \"last week\", \"in 2015\", \"two days ago\", \"when I was a child\"), el inglés usa el pasado simple, siempre: \"I went to the doctor yesterday\".",
          "Esto no cambia aunque en España se diga «ayer he ido al médico»: *I have gone yesterday es imposible en inglés. La palabra \"yesterday\" manda.",
        ],
        examples: [
          { es: "I went to the doctor yesterday.", en: "Ayer fui (he ido) al médico. (incorrecto: *I have gone yesterday)" },
          { es: "We saw them last week.", en: "Los vimos la semana pasada." },
          { es: "She moved to Quito in 2015.", en: "Ella se mudó a Quito en 2015." },
          { es: "I lived in Lima when I was a child.", en: "Viví en Lima cuando era niño." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "¿Cómo se dice «ayer he ido al médico» en inglés?",
            options: ["I went to the doctor yesterday.", "I have gone to the doctor yesterday.", "I've been to the doctor yesterday.", "I go to the doctor yesterday."],
            correctIndex: 0,
            explanation: "\"Yesterday\" es tiempo terminado: pasado simple (\"went\"), aunque en español de España se use «he ido».",
          },
        ],
      },
      {
        heading: "Recordatorio: tiempo sin terminar o sin decir = presente perfecto",
        body: [
          "Si el periodo sigue abierto (\"today\", \"this week\", \"this year\") o no se dice cuándo (\"ever\", \"never\", \"already\", \"yet\", \"just\", o simplemente nada), se usa el presente perfecto: \"I've worked a lot this week\", \"Have you ever eaten sushi?\".",
          "Esto vale también para los hablantes de Latinoamérica, que dirían «¿alguna vez comiste sushi?»: en inglés, «alguna vez» (\"ever\") pide presente perfecto. En inglés americano, cuando no hay tiempo (\"I lost my keys\") el pasado simple también es aceptable, pero el presente perfecto es siempre seguro.",
        ],
        examples: [
          { es: "I've worked a lot this week.", en: "Esta semana he trabajado mucho." },
          { es: "Have you ever eaten sushi?", en: "¿Has comido (comiste) sushi alguna vez?" },
          { es: "I've never been to Chile.", en: "Nunca he estado (estuve) en Chile." },
          { es: "I've lost my keys.", en: "He perdido las llaves. (también: \"I lost my keys\")" },
        ],
        checkpoint: [
          {
            type: "fill-blank",
            prompt: "Escribe en inglés las palabras en negrita.",
            sentence: "___ you ever eaten sushi?",
            answer: "Have",
            en: "¿[Has] comido sushi alguna vez?",
            explanation: "\"Ever\" («alguna vez») va con el presente perfecto: \"Have you ever...?\", aunque en tu español digas «comiste».",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "I ___ my grandmother last Sunday.",
        answer: "visited",
        en: "[Visité] a mi abuela el domingo pasado.",
        explanation: "\"Last Sunday\" es tiempo terminado: pasado simple.",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "I ___ my grandmother twice this month.",
        answer: "have visited",
        altAnswers: ["'ve visited"],
        en: "[He visitado] a mi abuela dos veces este mes.",
        explanation: "\"This month\" sigue abierto: presente perfecto.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Esta semana he trabajado mucho.",
        answer: "I've worked a lot this week.",
        altAnswers: ["This week I've worked a lot.", "I've worked hard this week.", "This week I've worked hard.", "I've been working a lot this week.", "I've been working hard this week."],
        explanation: "\"This week\" no ha terminado: presente perfecto. «Mucho» con un verbo es \"a lot\", al final.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "La semana pasada trabajé mucho.",
        answer: "I worked a lot last week.",
        altAnswers: ["Last week I worked a lot.", "I worked hard last week.", "Last week I worked hard."],
        explanation: "\"Last week\" ya terminó: pasado simple. Compara con \"this week\" en la frase anterior.",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "She ___ in Lima in 2015.",
        answer: "lived",
        en: "Ella [vivió] en Lima en 2015.",
        explanation: "Un año concreto (\"in 2015\") es tiempo terminado: pasado simple.",
      },
      {
        type: "multiple-choice",
        question: "¿Qué frase es correcta?",
        options: ["We saw that movie two weeks ago.", "We have seen that movie two weeks ago.", "We have seen that movie since two weeks.", "We see that movie two weeks ago."],
        correctIndex: 0,
        explanation: "\"Two weeks ago\" sitúa la acción en un momento terminado: pasado simple, nunca presente perfecto.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "He perdido las llaves.",
        answer: "I've lost my keys.",
        altAnswers: ["I lost my keys."],
        explanation: "Sin tiempo y con resultado presente (no tengo las llaves): presente perfecto. En inglés americano \"I lost my keys\" también se dice. Fíjate en \"my\": en inglés se dice de quién son las llaves.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Perdí las llaves ayer.",
        answer: "I lost my keys yesterday.",
        altAnswers: ["Yesterday I lost my keys."],
        explanation: "Con \"yesterday\" solo vale el pasado simple: \"lost\".",
      },
      {
        type: "matching",
        instructions: "Une cada expresión con el tiempo verbal que pide.",
        pairs: [
          { left: "yesterday", right: "ayer (pasado simple)" },
          { left: "this week", right: "esta semana (presente perfecto)" },
          { left: "in 2010", right: "en 2010 (pasado simple)" },
          { left: "ever", right: "alguna vez (presente perfecto)" },
          { left: "last month", right: "el mes pasado (pasado simple)" },
          { left: "just", right: "acabar de (presente perfecto)" },
        ],
        explanation: "Tiempo terminado (\"yesterday\", \"in 2010\", \"last month\") = pasado simple; tiempo abierto o sin fecha (\"this week\", \"ever\", \"just\") = presente perfecto.",
      },
      {
        type: "multi-select",
        question: "¿Con cuáles de estas expresiones se usa el pasado simple?",
        options: ["yesterday", "in 2015", "ever", "two days ago", "this week", "when I was a child"],
        correctIndexes: [0, 1, 3, 5],
        explanation: "\"Yesterday\", \"in 2015\", \"two days ago\" y \"when I was a child\" son momentos terminados. \"Ever\" y \"this week\" van con el presente perfecto.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "¿Has hablado con Lucia hoy?",
        answer: "Have you talked to Lucia today?",
        altAnswers: ["Have you spoken to Lucia today?", "Have you talked with Lucia today?", "Have you spoken with Lucia today?", "Did you talk to Lucia today?", "Did you speak to Lucia today?", "Did you talk with Lucia today?", "Did you speak with Lucia today?"],
        explanation: "\"Today\" sigue abierto, así que presente perfecto. (En inglés americano \"Did you talk to Lucia today?\" también se oye mucho.)",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Cuando era niña, vivía en el campo.",
        answer: "When I was a child, I lived in the country.",
        altAnswers: ["When I was a kid, I lived in the country.", "When I was a child, I lived in the countryside.", "When I was a kid, I lived in the countryside.", "When I was a girl, I lived in the country.", "When I was a girl, I lived in the countryside.", "When I was little, I lived in the country.", "When I was little, I lived in the countryside.", "I lived in the country when I was a child.", "I lived in the countryside when I was a child."],
        explanation: "«Cuando era niña» marca un periodo terminado: pasado simple. El imperfecto español («vivía») también es pasado simple en inglés.",
      },
      {
        type: "listen-choose",
        audio: "Have you seen Carlos this morning?",
        question: "¿Qué has oído?",
        options: ["¿Has visto a Carlos esta mañana?", "¿Viste a Carlos ayer por la mañana?", "¿Ves a Carlos por las mañanas?", "¿Vas a ver a Carlos esta mañana?"],
        correctIndex: 0,
        explanation: "\"Have you seen... this morning?\": presente perfecto porque la mañana todavía no ha terminado.",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "They ___ to Peru three times.",
        answer: "have been",
        altAnswers: ["'ve been"],
        en: "[Han ido] a Perú tres veces.",
        explanation: "Experiencias contadas hasta hoy, sin fecha: presente perfecto. Para «haber ido» a un sitio (y haber vuelto) se usa \"have been to\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Nunca he comido comida tailandesa.",
        answer: "I've never eaten Thai food.",
        altAnswers: ["I've never had Thai food.", "I've never tried Thai food.", "I have never eaten Thai food."],
        explanation: "\"Never\" + presente perfecto. En inglés hay una sola negación: *I haven't never eaten es incorrecto.",
      },
      {
        type: "multiple-choice",
        question: "¿Cómo se dice «el año pasado estuve en Cuba»?",
        options: ["I was in Cuba last year.", "I have been in Cuba last year.", "I've been to Cuba last year.", "I am in Cuba last year."],
        correctIndex: 0,
        explanation: "\"Last year\" es tiempo terminado: \"was\". \"I've been to Cuba\" sería correcto solo sin \"last year\".",
      },
      {
        type: "dictation",
        audio: "Did you go out last night?",
        explanation: "\"Last night\" pide pasado simple: \"Did you go out...?\". Fíjate en que \"go\" no cambia después de \"did\".",
      },
    ],
  },
  // ---------------------------------------------------------------------
  {
    slug: "en-a2-pp-vs-past-drill-2",
    optional: true,
    level: "EN-A2",
    number: 6,
    title: "Práctica extra: presente perfecto o pasado, parte 2",
    summary: "Diálogos: abrir con el presente perfecto (\"Have you ever...?\") y seguir con los detalles en pasado simple (\"I went in 2019. It was great\").",
    duration: "10 min",
    sections: [
      {
        heading: "Recordatorio: abrir en presente perfecto, detallar en pasado simple",
        body: [
          "En una conversación, la primera frase suele ser general y sin fecha: presente perfecto (\"Have you ever been to Rome?\", \"I've seen that movie\"). En cuanto entran los detalles (cuándo, cómo fue, con quién), se pasa al pasado simple: \"Yes, I went in 2019. It was great\".",
          "Es un patrón fijo: pregunta de experiencia en presente perfecto, respuesta con detalles en pasado simple. No sigas en presente perfecto: *I have gone in 2019, *It has been great.",
        ],
        examples: [
          { es: "Have you ever been to Rome? Yes, I went in 2019. It was great.", en: "¿Has estado alguna vez en Roma? Sí, fui en 2019. Fue genial." },
          { es: "I've seen that movie. I saw it with Ana.", en: "He visto esa película. La vi con Ana." },
          { es: "She's lost her phone. She left it in a taxi.", en: "Ha perdido el teléfono. Lo dejó en un taxi." },
          { es: "I've met him. We met at a wedding.", en: "Lo conozco. Nos conocimos en una boda." },
        ],
        checkpoint: [
          {
            type: "fill-blank",
            prompt: "Escribe en inglés las palabras en negrita.",
            sentence: "Have you ever been to Mexico? Yes, I ___ there in 2022.",
            answer: "went",
            altAnswers: ["was"],
            en: "¿Has estado alguna vez en México? Sí, [fui] en 2022.",
            explanation: "La pregunta es general (presente perfecto); la respuesta da la fecha (\"in 2022\"), así que pasado simple.",
          },
        ],
      },
      {
        heading: "Recordatorio: España y Latinoamérica, mismo inglés",
        body: [
          "En Latinoamérica el pasado simple se usa casi siempre («¿alguna vez fuiste a Roma?», «hoy comí con mi madre»); en España el perfecto se usa mucho («ayer he ido»). El inglés no sigue ni a uno ni a otro: sigue la regla del tiempo.",
          "«Alguna vez» y «nunca» (experiencia, sin fecha) piden presente perfecto aunque tu español use el pretérito: \"Have you ever been...?\", \"I've never seen...\". «Ayer», «en 2019», «hace un mes» piden pasado simple aunque tu español use «he ido».",
        ],
        examples: [
          { es: "Have you ever tried ceviche?", en: "¿Alguna vez probaste (has probado) el ceviche?" },
          { es: "I've never seen snow.", en: "Nunca vi (he visto) la nieve." },
          { es: "I had lunch with my mother yesterday.", en: "Ayer he comido (comí) con mi madre." },
          { es: "I've had lunch with my mother today.", en: "Hoy comí (he comido) con mi madre. (también: \"I had lunch with my mother today\")" },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "¿Cómo se dice «¿alguna vez probaste el ceviche?»?",
            options: ["Have you ever tried ceviche?", "Have you ever try ceviche?", "Has you ever tried ceviche?", "Do you ever tried ceviche?"],
            correctIndex: 0,
            explanation: "«Alguna vez» = \"ever\" + presente perfecto: \"Have you\" + participio (\"tried\").",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "A: ___ you ever tried paella? B: Yes, I tried it in Valencia.",
        answer: "Have",
        en: "A: ¿[Has] probado alguna vez la paella? B: Sí, la probé en Valencia.",
        explanation: "La pregunta de experiencia va en presente perfecto (\"Have you ever...?\"); el detalle (\"in Valencia\") va en pasado simple.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "¿Alguna vez fuiste a Roma? Sí, fui el año pasado.",
        answer: "Have you ever been to Rome? Yes, I went last year.",
        altAnswers: ["Have you ever been to Rome? Yes, I went there last year.", "Have you ever gone to Rome? Yes, I went last year.", "Have you ever been to Rome? Yes, I was there last year."],
        explanation: "«Alguna vez» pide presente perfecto (\"Have you ever been\") aunque el español diga «fuiste». «El año pasado» pide pasado simple.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "He visto esa serie. La vi en verano.",
        answer: "I've seen that show. I saw it in the summer.",
        altAnswers: ["I've seen that series. I saw it in the summer.", "I've seen that show. I saw it in summer.", "I've seen that series. I saw it in summer.", "I've seen that show. I watched it in the summer.", "I've seen that series. I watched it in the summer.", "I've seen that show. I watched it in summer.", "I've seen that series. I watched it in summer.", "I've seen that show. I saw it last summer.", "I've seen that series. I saw it last summer."],
        explanation: "Primera frase sin fecha: presente perfecto. Segunda con el momento (\"in the summer\"): pasado simple. «Serie» es \"show\" o \"series\" (nunca *serie).",
      },
      {
        type: "multiple-choice",
        question: "Tu amigo pregunta: \"Have you ever been to Japan?\". ¿Qué respuesta es correcta?",
        options: ["Yes, I went two years ago. It was amazing.", "Yes, I've gone two years ago. It has been amazing.", "Yes, I have been two years ago. It was amazing.", "Yes, I go two years ago. It is amazing."],
        correctIndex: 0,
        explanation: "Los detalles (\"two years ago\", cómo fue) van en pasado simple: \"went\", \"was\".",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "I've met your brother. We ___ at Ana's party.",
        answer: "met",
        en: "Conozco a tu hermano. Nos [conocimos] en la fiesta de Ana.",
        explanation: "\"I've met\" (sin fecha) y luego el detalle en pasado simple: \"we met at Ana's party\". \"Meet\" es irregular: \"met\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "¿Has leído este libro? Sí, lo leí hace años.",
        answer: "Have you read this book? Yes, I read it years ago.",
        altAnswers: ["Have you read this book? Yes, I read it ages ago.", "Have you read this book? Yes, I read it many years ago.", "Have you read this book? Yes, I read it a long time ago."],
        explanation: "\"Read\" se escribe igual en presente, pasado y participio, pero el pasado se pronuncia «red». Con \"ago\", pasado simple.",
      },
      {
        type: "word-order",
        prompt: "Ordena las palabras.",
        words: ["I've", "been", "to", "Peru.", "I", "went", "last", "year."],
        translation: "He estado en Perú. Fui el año pasado.",
        explanation: "Experiencia general en presente perfecto (\"I've been to Peru\"), detalle con fecha en pasado simple (\"I went last year\").",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Hoy he desayunado con Diego.",
        answer: "I had breakfast with Diego today.",
        altAnswers: ["I've had breakfast with Diego today.", "Today I had breakfast with Diego.", "Today I've had breakfast with Diego.", "I had breakfast with Diego this morning.", "I've had breakfast with Diego this morning."],
        explanation: "\"Today\" sigue abierto, así que las dos formas son correctas en inglés; en Estados Unidos se prefiere el pasado simple para algo ya terminado como el desayuno.",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "A: Have you finished the report? B: Yes, I ___ it yesterday.",
        answer: "finished",
        en: "A: ¿Has terminado el informe? B: Sí, lo [terminé] ayer.",
        explanation: "La pregunta sin fecha va en presente perfecto; la respuesta con \"yesterday\" va en pasado simple.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "¿Cuándo llegó ella? Llegó hace una hora.",
        answer: "When did she arrive? She arrived an hour ago.",
        altAnswers: ["When did she arrive? She arrived one hour ago.", "When did she get here? She got here an hour ago.", "When did she arrive? An hour ago.", "When did she get here? An hour ago."],
        explanation: "«¿Cuándo?» pide siempre pasado simple: \"When did she arrive?\" (*When has she arrived es incorrecto).",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Nunca he estado en Argentina, pero mi hermano fue en 2019.",
        answer: "I've never been to Argentina, but my brother went in 2019.",
        altAnswers: ["I've never been to Argentina, but my brother went there in 2019.", "I have never been to Argentina, but my brother was there in 2019."],
        explanation: "\"Never\" (experiencia) con presente perfecto; \"in 2019\" con pasado simple. Las dos mitades en una misma frase.",
      },
      {
        type: "listen-choose",
        audio: "I've lost my wallet. I left it on the bus.",
        question: "¿Qué has oído?",
        options: ["He perdido la cartera. La dejé en el autobús.", "Perdí la cartera ayer en el autobús.", "He encontrado una cartera en el autobús.", "Voy a dejar la cartera en el autobús."],
        correctIndex: 0,
        explanation: "\"I've lost\" (resultado presente) y \"I left it\" (el detalle, en pasado simple).",
      },
      {
        type: "fill-blank",
        prompt: "Escribe en inglés las palabras en negrita.",
        sentence: "Emma has moved to Boston. She ___ there last month.",
        answer: "moved",
        en: "Emma se ha mudado a Boston. [Se mudó] allí el mes pasado.",
        explanation: "Noticia sin fecha en presente perfecto, detalle con \"last month\" en pasado simple.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Traduce al inglés.",
        source: "Ya he comido. Comí a la una.",
        answer: "I've already eaten. I ate at one.",
        altAnswers: ["I already ate. I ate at one.", "I've already eaten. I ate at one o'clock.", "I already ate. I ate at one o'clock.", "I've eaten already. I ate at one.", "I've already had lunch. I ate at one.", "I've already had lunch. I had lunch at one."],
        explanation: "\"Already\" con presente perfecto; la hora concreta (\"at one\") con pasado simple.",
      },
      {
        type: "multiple-choice",
        question: "¿Qué frase es correcta?",
        options: ["I've seen her twice. The last time was in May.", "I've seen her twice. The last time has been in May.", "I saw her twice. The last time has been in May.", "I've seen her twice. The last time is in May."],
        correctIndex: 0,
        explanation: "\"Twice\" (hasta hoy) con presente perfecto; \"in May\" (momento terminado) con pasado simple: \"was\".",
      },
      {
        type: "write",
        prompt: "Escribe un mini diálogo de cuatro a seis frases: una persona pregunta \"Have you ever...?\" y la otra responde con detalles (cuándo, dónde, cómo fue).",
        minWords: 25,
        maxWords: 60,
        rubric: [
          "Una pregunta con \"Have you ever\" + participio.",
          "Una respuesta corta (\"Yes, I have\" / \"No, I haven't\").",
          "Al menos dos detalles en pasado simple (cuándo, dónde o cómo fue).",
        ],
        modelAnswer: "A: Have you ever been to New York? B: Yes, I have. I went there in 2023 with my sister. We stayed for five days and visited Central Park. It was amazing, but the food was really expensive. A: Have you ever seen a show on Broadway? B: No, I haven't. Maybe next time!",
        explanation: "Pregunta de experiencia en presente perfecto, detalles en pasado simple: ese es el patrón de toda la lección.",
      },
      {
        type: "speak",
        text: "Have you ever been to London? Yes, I went in 2018. It was great.",
        tip: "Marca bien la \"t\" final de \"went\" y de \"great\"; en español tendemos a comérnosla.",
        explanation: "Presente perfecto para abrir (\"Have you ever been\"), pasado simple para los detalles (\"went\", \"was\").",
      },
    ],
  },
];
