// Synced from cheneygross-afk/lengo:src/lib/lessons/en-b2-u02-extra.ts by scripts/sync-content.mjs -- edit it there, not here.
import type { Lesson } from "./types";

// Extra practice (optional) lessons for EN-B2 unit u02 (narrative tenses in
// practice). Drill-focused: a short recap, then lots of exercises.

export const EN_B2_U02_EXTRA: Lesson[] = [
  // ---------------------------------------------------------------------
  // Extra 1. Translating Spanish pasts
  // ---------------------------------------------------------------------
  {
    slug: "en-b2-narrative-translation-drill-1",
    optional: true,
    level: "EN-B2",
    number: 1,
    title: "Extra Practice: Translating Spanish Pasts",
    summary: "A dense translation drill: turn the «pretérito», «imperfecto», «pluscuamperfecto», «llevaba + gerundio» and «acababa de» into natural English story tenses.",
    duration: "12 min",
    sections: [
      {
        heading: "Quick recap: one Spanish form, several English choices",
        body: [
          "«Pretérito» (llegué, vi): past simple. «Pluscuamperfecto» (había salido): past perfect. «Llevaba dos horas esperando»: \"had been waiting for two hours\".",
          "The «imperfecto» needs a decision every time. Action in progress at that moment (llovía, estábamos cenando): past continuous. State (era, tenía, sabía, había): past simple. Repeated habit (íbamos cada verano): past simple, \"used to\" or \"would\" (but \"would\" only for actions, not states).",
          "Translate the meaning, not the form: first decide which layer of the story each verb belongs to.",
        ],
        examples: [
          { es: "It was raining and there was nobody in the street.", en: "Llovía y no había nadie en la calle." },
          { es: "We spent every summer at the beach.", en: "Pasábamos todos los veranos en la playa." },
          { es: "We would spend hours in the water.", en: "Pasábamos horas en el agua." },
          { es: "My grandfather had a dog called Toby.", en: "Mi abuelo tenía un perro que se llamaba Toby. (incorrecto: *would have)" },
          { es: "I had been looking for my keys for an hour.", en: "Llevaba una hora buscando las llaves." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "«Mi abuelo tenía un perro que se llamaba Toby.» Which is correct?",
            options: [
              "My grandfather had a dog called Toby.",
              "My grandfather would have a dog called Toby.",
              "My grandfather was having a dog called Toby.",
              "My grandfather used to having a dog called Toby.",
            ],
            correctIndex: 0,
            explanation: "Possession is a state, so the past simple. \"Would\" is only for repeated actions, and \"have\" for possession is never continuous.",
          },
        ],
      },
      {
        heading: "acababa de and estaba a punto de",
        body: [
          "«Acababa de» + infinitive is \"had just\" + past participle: «acababa de salir» is \"I had just left\". Do not translate it word for word (*I finished to leave) and do not use the continuous (*I was just leaving means «estaba saliendo»).",
          "Its opposite is «estaba a punto de»: \"was about to\" + base verb. \"I was about to leave when Luis showed up.\"",
        ],
        examples: [
          { es: "I had just left home when it started to rain.", en: "Acababa de salir de casa cuando empezó a llover." },
          { es: "She told me she had just come back from Peru.", en: "Me dijo que acababa de volver de Perú." },
          { es: "We had just sat down to eat when the doorbell rang.", en: "Acabábamos de sentarnos a comer cuando sonó el timbre." },
          { es: "I was about to leave when Luis showed up.", en: "Estaba a punto de irme cuando apareció Luis." },
        ],
        checkpoint: [
          {
            type: "fill-blank",
            prompt: "Write the bold words in English.",
            sentence: "The train ___ when we reached the platform.",
            answer: "had just left",
            altAnswers: ["had just gone", "had just pulled out"],
            en: "El tren [acababa de salir] cuando llegamos al andén.",
            explanation: "«Acababa de» + infinitive is \"had just\" + participle.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Acababa de salir de casa cuando empezó a llover.",
        answer: "I had just left home when it started to rain.",
        altAnswers: [
          "I had just left home when it started raining.",
          "I had just left the house when it started to rain.",
          "I had just left the house when it started raining.",
          "I had just left home when it began to rain.",
          "I had just left the house when it began to rain.",
          "I had just left home when it began raining.",
        ],
        explanation: "«Acababa de salir» is \"had just left\"; the rain starting is the next event, in the past simple.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Cuando éramos pequeños, pasábamos los veranos en el pueblo de mis abuelos.",
        answer: "When we were little, we spent our summers in my grandparents' village.",
        altAnswers: [
          "When we were little, we spent the summers in my grandparents' village.",
          "When we were little, we used to spend our summers in my grandparents' village.",
          "When we were little, we used to spend the summers in my grandparents' village.",
          "When we were little, we would spend our summers in my grandparents' village.",
          "When we were little, we would spend the summers in my grandparents' village.",
          "When we were kids, we spent our summers in my grandparents' village.",
          "When we were kids, we used to spend our summers in my grandparents' village.",
          "When we were children, we spent our summers in my grandparents' village.",
          "When we were children, we used to spend our summers in my grandparents' village.",
          "When we were little, we spent our summers in my grandparents' town.",
          "When we were little, we used to spend our summers in my grandparents' town.",
          "When we were kids, we would spend our summers in my grandparents' village.",
          "When we were little, we spent summers in my grandparents' village.",
        ],
        explanation: "«Éramos» is a state (past simple \"were\"); «pasábamos» is a habit (\"spent\", \"used to spend\" or \"would spend\"). Never *we were spending for a habit.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Eran las diez de la noche. Llovía y no había nadie en la calle.",
        answer: "It was ten o'clock at night. It was raining and there was nobody in the street.",
        altAnswers: [
          "It was ten o'clock at night. It was raining and there was nobody on the street.",
          "It was ten o'clock at night. It was raining and there was no one in the street.",
          "It was ten o'clock at night. It was raining and there was no one on the street.",
          "It was ten at night. It was raining and there was nobody in the street.",
          "It was ten at night. It was raining and there was nobody on the street.",
          "It was ten o'clock at night. It was raining, and there was nobody in the street.",
          "It was ten o'clock at night. It was raining, and there was nobody on the street.",
          "It was ten p.m. It was raining and there was nobody in the street.",
          "It was ten o'clock at night. It was raining and the street was empty.",
        ],
        explanation: "Three background «imperfectos», three choices: time and existence are states (\"It was\", \"there was\"); the rain was in progress (\"It was raining\").",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Llevaba media hora buscando las llaves cuando me di cuenta de que las tenía en el bolsillo.",
        answer: "I had been looking for my keys for half an hour when I realized they were in my pocket.",
        altAnswers: [
          "I had been looking for my keys for half an hour when I realized I had them in my pocket.",
          "I had been looking for the keys for half an hour when I realized they were in my pocket.",
          "I had been looking for the keys for half an hour when I realized I had them in my pocket.",
          "I had been searching for my keys for half an hour when I realized they were in my pocket.",
          "I had been searching for my keys for half an hour when I realized I had them in my pocket.",
          "I had been looking for my keys for half an hour when I realized that they were in my pocket.",
          "I had been looking for my keys for thirty minutes when I realized they were in my pocket.",
          "I'd been looking for my keys for half an hour when I realized they were in my pocket.",
        ],
        explanation: "«Llevaba media hora buscando»: \"had been looking for ... for half an hour\". «Me di cuenta»: \"realized\". «Las tenía» is a state: \"they were\" or \"I had them\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Mi abuela siempre nos hacía tortitas los domingos.",
        answer: "My grandmother always made us pancakes on Sundays.",
        altAnswers: [
          "My grandmother would always make us pancakes on Sundays.",
          "My grandmother always used to make us pancakes on Sundays.",
          "My grandmother used to make us pancakes on Sundays.",
          "My grandmother always made pancakes for us on Sundays.",
          "My grandmother would always make pancakes for us on Sundays.",
          "My grandma always made us pancakes on Sundays.",
          "My grandma would always make us pancakes on Sundays.",
          "My grandma used to make us pancakes on Sundays.",
          "My grandma always used to make us pancakes on Sundays.",
          "On Sundays my grandmother always made us pancakes.",
          "On Sundays, my grandmother would always make us pancakes.",
        ],
        explanation: "A repeated action in the past: past simple, \"used to\" or \"would\". «Hacer tortitas» is \"make pancakes\", not *do pancakes.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "No reconocí a Marta porque se había cortado el pelo.",
        answer: "I didn't recognize Marta because she had cut her hair.",
        altAnswers: [
          "I didn't recognize Marta because she had had her hair cut.",
          "I didn't recognize Marta because she had gotten a haircut.",
          "I didn't recognize Marta because she had got a haircut.",
          "I didn't recognize Marta because she'd cut her hair.",
          "I did not recognize Marta because she had cut her hair.",
        ],
        explanation: "The haircut came first: past perfect. English says \"her hair\", not *the hair. \"Had her hair cut\" makes clear a hairdresser did it.",
      },
      {
        type: "multiple-choice",
        question: "«Cuando sonó la alarma, ya estábamos fuera del edificio.» Which is correct?",
        options: [
          "When the alarm went off, we were already outside the building.",
          "When the alarm went off, we were already being outside the building.",
          "When the alarm was going off, we already left the building.",
          "When the alarm went off, we already were going out of the building.",
        ],
        correctIndex: 0,
        explanation: "«Estábamos fuera» is a state (where we were), so \"were\", not the continuous. An alarm \"goes off\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Todos los días iba en bici al trabajo, pero ese día tomé el autobús.",
        answer: "I rode my bike to work every day, but that day I took the bus.",
        altAnswers: [
          "I used to ride my bike to work every day, but that day I took the bus.",
          "I cycled to work every day, but that day I took the bus.",
          "I biked to work every day, but that day I took the bus.",
          "I went to work by bike every day, but that day I took the bus.",
          "Every day I rode my bike to work, but that day I took the bus.",
          "Every day I went to work by bike, but that day I took the bus.",
          "Every day I cycled to work, but that day I took the bus.",
          "I would ride my bike to work every day, but that day I took the bus.",
          "I rode my bike to work every day, but that day I caught the bus.",
          "I rode my bicycle to work every day, but that day I took the bus.",
        ],
        explanation: "«Iba» here is a habit (past simple, \"used to\" or \"would\"); «tomé» is a single event (past simple). «Tomar el autobús» is \"take the bus\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "She told me she ___ from Peru.",
        answer: "had just come back",
        altAnswers: ["had just returned", "had just gotten back", "had just got back"],
        en: "Me dijo que [acababa de volver] de Perú.",
        explanation: "«Acababa de volver» is \"had just come back\". The past perfect also fits the reported speech after \"told me\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Estaba a punto de irme cuando apareció Luis.",
        answer: "I was about to leave when Luis showed up.",
        altAnswers: [
          "I was about to leave when Luis appeared.",
          "I was about to leave when Luis turned up.",
          "I was about to leave when Luis arrived.",
          "I was just about to leave when Luis showed up.",
          "I was on the point of leaving when Luis showed up.",
        ],
        explanation: "«Estar a punto de» is \"be about to\" + base verb. «Aparecer» (a person arriving) is often \"show up\" or \"turn up\".",
      },
      {
        type: "matching",
        instructions: "Match each English sentence with its Spanish meaning.",
        pairs: [
          { left: "I had just eaten.", right: "Acababa de comer." },
          { left: "I had been eating for an hour.", right: "Llevaba una hora comiendo." },
          { left: "I was eating.", right: "Estaba comiendo." },
          { left: "I used to eat there.", right: "Antes comía allí." },
          { left: "I had already eaten.", right: "Ya había comido." },
        ],
        explanation: "Five Spanish pasts, five English forms. The key is the meaning: just finished, duration, in progress, old habit, earlier event.",
      },
      {
        type: "listen-choose",
        audio: "I used to work in a bank, but that year I was working in a hotel.",
        question: "What was true that year?",
        options: [
          "He had a temporary job in a hotel.",
          "He still worked in the bank.",
          "He worked in a bank and a hotel every year.",
          "He wanted to work in a hotel.",
        ],
        correctIndex: 0,
        explanation: "\"Used to work\" is the old situation; \"was working\" presents the hotel job as temporary, true for that period.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order.",
        words: ["I", "had", "just", "finished", "my", "coffee", "when", "she", "arrived."],
        translation: "Acababa de terminarme el café cuando llegó.",
        altOrders: [["When", "she", "arrived", "I", "had", "just", "finished", "my", "coffee"]],
        explanation: "\"Had just\" + participle for «acababa de», then the past simple for the next event.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Hacía un día precioso. Los niños jugaban en la playa y sus padres leían bajo una sombrilla.",
        answer: "It was a beautiful day. The children were playing on the beach and their parents were reading under an umbrella.",
        altAnswers: [
          "It was a beautiful day. The kids were playing on the beach and their parents were reading under an umbrella.",
          "It was a lovely day. The children were playing on the beach and their parents were reading under an umbrella.",
          "It was a lovely day. The kids were playing on the beach and their parents were reading under an umbrella.",
          "It was a beautiful day. The children were playing on the beach, and their parents were reading under an umbrella.",
          "It was a beautiful day. The kids were playing on the beach, and their parents were reading under an umbrella.",
          "It was a beautiful day. The children were playing on the beach and their parents were reading under a beach umbrella.",
          "It was a beautiful day. The children were playing on the beach and their parents were reading under a parasol.",
          "It was a gorgeous day. The children were playing on the beach and their parents were reading under an umbrella.",
          "It was a beautiful day. The children were playing on the beach while their parents were reading under an umbrella.",
          "It was a beautiful day. The children were playing on the beach while their parents read under an umbrella.",
        ],
        explanation: "The weather is a state (\"It was a beautiful day\", never *It made a beautiful day). Playing and reading were in progress at that moment: past continuous.",
      },
      {
        type: "dictation",
        audio: "We had just sat down to eat when the doorbell rang.",
        explanation: "\"Had just sat down\" (sit, sat, sat) for «acabábamos de sentarnos», then the interruption in the past simple.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Sabía que algo había pasado porque mi madre estaba llorando.",
        answer: "I knew something had happened because my mother was crying.",
        altAnswers: [
          "I knew that something had happened because my mother was crying.",
          "I knew something had happened because my mom was crying.",
          "I knew that something had happened because my mom was crying.",
          "I knew something had happened because my mum was crying.",
          "I could tell something had happened because my mother was crying.",
          "I could tell something had happened because my mom was crying.",
        ],
        explanation: "Three layers in one sentence: a state (\"knew\"), an earlier event (\"had happened\") and an action in progress (\"was crying\").",
      },
    ],
  },
  // ---------------------------------------------------------------------
  // Extra 2. would, used to or was doing?
  // ---------------------------------------------------------------------
  {
    slug: "en-b2-would-used-to-narrative-drill-1",
    optional: true,
    level: "EN-B2",
    number: 2,
    title: "Extra Practice: would, used to or was doing?",
    summary: "Drill past habits in stories: \"would\" and \"used to\" for repeated actions, only \"used to\" for states, and the past continuous for one-off or temporary backgrounds, not for habits.",
    duration: "10 min",
    sections: [
      {
        heading: "Quick recap: habits with used to and would",
        body: [
          "\"Used to\" + base verb works for past habits and past states: \"I used to go to my grandmother's every summer\", \"I used to have a dog\". It suggests the situation is over now.",
          "\"Would\" + base verb only works for repeated actions, once the past time is clear: \"Every summer we would go to the beach\". It never works for states: *I would have a dog and *I would live in Lima are wrong.",
          "Negatives and questions: \"didn't use to\" and \"Did you use to...?\", without -d. For a present habit («suelo»), use \"usually\": \"I usually walk to work\".",
        ],
        examples: [
          { es: "I used to go to my grandmother's every summer.", en: "Iba todos los veranos a casa de mi abuela." },
          { es: "We would play in the street until it got dark.", en: "Jugábamos en la calle hasta que oscurecía." },
          { es: "I used to have a dog called Max.", en: "Antes tenía un perro que se llamaba Max. (incorrecto: *I would have)" },
          { es: "I didn't use to like fish.", en: "Antes no me gustaba el pescado." },
          { es: "There used to be a movie theater on this street.", en: "Antes había un cine en esta calle." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "«Iba todos los veranos a casa de mi abuela.» Which is correct?",
            options: [
              "I used to go to my grandmother's every summer.",
              "I was going every summer to my grandmother's.",
              "I was used to go to my grandmother's every summer.",
              "I use to go to my grandmother's every summer.",
            ],
            correctIndex: 0,
            explanation: "A repeated habit takes \"used to\" (or \"would\" or the past simple), not the past continuous. \"Use to\" without -d is only for negatives and questions.",
          },
        ],
      },
      {
        heading: "The past continuous: temporary, not repeated",
        body: [
          "The past continuous is for an action in progress at one moment, or for a temporary situation: \"That summer I was working at a cafe\". It is not the normal tense for habits: *I was going every summer to my grandmother's sounds like a calque of «iba».",
          "In a story you often combine them: \"That year I was living in London, and I would go running in the park every morning\".",
        ],
        examples: [
          { es: "That summer I was working at a cafe.", en: "Aquel verano trabajaba en una cafetería." },
          { es: "That year I was living in London.", en: "Ese año vivía en Londres." },
          { es: "I would go running in the park every morning.", en: "Iba a correr al parque todas las mañanas." },
          { es: "I usually get up at seven.", en: "Suelo levantarme a las siete." },
        ],
        checkpoint: [
          {
            type: "fill-blank",
            prompt: "Write the bold words in English.",
            sentence: "That summer, I ___ at a cafe to save money.",
            answer: "was working",
            altAnswers: ["worked"],
            en: "Aquel verano, [trabajaba] en una cafetería para ahorrar dinero.",
            explanation: "A temporary situation during one summer: past continuous \"was working\" (the past simple \"worked\" is also possible).",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "When I was a kid, I ___ a cat called Luna.",
        answer: "had",
        altAnswers: ["used to have"],
        en: "De niño, [tenía] una gata que se llamaba Luna.",
        explanation: "Possession is a state: past simple \"had\" or \"used to have\", never *would have.",
      },
      {
        type: "multiple-choice",
        question: "Which sentence is NOT correct?",
        options: [
          "I would have a dog when I was little.",
          "I used to have a dog when I was little.",
          "I had a dog when I was little.",
          "I would walk my dog every evening.",
        ],
        correctIndex: 0,
        explanation: "\"Have\" (possession) is a state, so \"would\" is impossible. Walking the dog is a repeated action, so \"would walk\" is fine.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Antes vivíamos en el centro, pero ahora vivimos en las afueras.",
        answer: "We used to live downtown, but now we live in the suburbs.",
        altAnswers: [
          "We used to live in the city center, but now we live in the suburbs.",
          "We used to live in the center, but now we live in the suburbs.",
          "We used to live in the town center, but now we live in the suburbs.",
          "We used to live downtown, but now we live on the outskirts.",
          "We used to live in the city center, but now we live on the outskirts.",
          "We used to live in the center, but now we live on the outskirts.",
          "We used to live in the town center, but now we live on the outskirts.",
          "We used to live downtown, but we live in the suburbs now.",
          "We used to live in the city center, but we live in the suburbs now.",
          "We used to live in the center of town, but now we live in the suburbs.",
          "We used to live in the center of town, but now we live on the outskirts.",
        ],
        explanation: "\"Live\" here is a state, so \"used to live\", not *would live. «El centro» of a city is \"downtown\" in American English or \"the city center\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Mi padre nos llevaba al colegio todas las mañanas.",
        answer: "My father would take us to school every morning.",
        altAnswers: [
          "My father used to take us to school every morning.",
          "My father took us to school every morning.",
          "My dad would take us to school every morning.",
          "My dad used to take us to school every morning.",
          "My dad took us to school every morning.",
          "My father would drive us to school every morning.",
          "My father used to drive us to school every morning.",
          "My dad would drive us to school every morning.",
          "My dad used to drive us to school every morning.",
          "Every morning my father would take us to school.",
          "Every morning my dad used to take us to school.",
        ],
        explanation: "A repeated action: \"would take\", \"used to take\" or \"took\". *My father was taking us to school every morning is the calque to avoid.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Antes no me gustaban las verduras.",
        answer: "I didn't use to like vegetables.",
        altAnswers: ["I never used to like vegetables.", "I used to not like vegetables.", "I used to dislike vegetables.", "I used to hate vegetables.", "I didn't like vegetables before.", "I didn't use to like veggies."],
        explanation: "Negative: \"didn't use to\", without -d, because \"did\" already shows the past. \"Like\" is a state, so \"would\" is impossible.",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "She ___ be very shy, but now she's really outgoing.",
        answer: "used to",
        en: "[Antes] era muy tímida, pero ahora es muy extrovertida.",
        explanation: "\"Be shy\" is a state, so \"used to\", not \"would\". «Antes» + imperfect often becomes \"used to\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Cuando vivía en Londres, iba a correr al parque todas las mañanas.",
        answer: "When I lived in London, I used to go running in the park every morning.",
        altAnswers: [
          "When I lived in London, I would go running in the park every morning.",
          "When I lived in London, I went running in the park every morning.",
          "When I was living in London, I used to go running in the park every morning.",
          "When I was living in London, I would go running in the park every morning.",
          "When I was living in London, I went running in the park every morning.",
          "When I lived in London, I used to go jogging in the park every morning.",
          "When I lived in London, I went jogging in the park every morning.",
          "When I lived in London, I would go jogging in the park every morning.",
          "When I lived in London, I used to go for a run in the park every morning.",
          "When I lived in London, I would go for a run in the park every morning.",
          "When I lived in London, I went for a run in the park every morning.",
          "When I lived in London, I used to run in the park every morning.",
          "When I lived in London, I ran in the park every morning.",
        ],
        explanation: "«Vivía» is a state or temporary situation (\"lived\" or \"was living\"); «iba a correr» is a habit (\"used to go\", \"would go\" or \"went\").",
      },
      {
        type: "multiple-choice",
        question: "«Antes había un cine en esta calle.» Which is correct?",
        options: [
          "There used to be a movie theater on this street.",
          "There would be a movie theater on this street.",
          "There was being a movie theater on this street.",
          "It used to be a movie theater on this street.",
        ],
        correctIndex: 0,
        explanation: "«Antes había» is \"there used to be\". Existence is a state, so not \"would\", and «había» is \"there was\", never *it was.",
      },
      {
        type: "listen-choose",
        audio: "We'd stay up late and tell ghost stories.",
        question: "What does 'd mean here?",
        options: ["would (a repeated past action)", "had", "did", "should"],
        correctIndex: 0,
        explanation: "'d before a base verb (\"stay\") is \"would\": a past habit. Before a participle (\"we'd stayed\") it would be \"had\".",
      },
      {
        type: "matching",
        instructions: "Match each English form with its use.",
        pairs: [
          { left: "used to + verb", right: "hábitos y estados del pasado" },
          { left: "would + verb", right: "solo acciones repetidas del pasado" },
          { left: "was + -ing", right: "acción en curso o situación temporal" },
          { left: "usually + present", right: "hábitos actuales («suelo»)" },
        ],
        explanation: "\"Used to\" is the safe choice for any past habit or state; \"would\" only for actions; the continuous for one moment or a temporary period.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Ese invierno estaba aprendiendo a esquiar, así que iba a la montaña todos los fines de semana.",
        answer: "That winter I was learning to ski, so I went to the mountains every weekend.",
        altAnswers: [
          "That winter I was learning to ski, so I used to go to the mountains every weekend.",
          "That winter I was learning to ski, so I would go to the mountains every weekend.",
          "That winter, I was learning to ski, so I went to the mountains every weekend.",
          "That winter, I was learning to ski, so I would go to the mountains every weekend.",
          "That winter I was learning how to ski, so I went to the mountains every weekend.",
          "That winter I was learning how to ski, so I would go to the mountains every weekend.",
          "That winter I was learning to ski, so I went to the mountains on weekends.",
          "That winter I was learning to ski, so I went up to the mountains every weekend.",
        ],
        explanation: "A temporary activity that winter (\"was learning\") plus a habit within it (\"went\" or \"would go\"). Avoid *I was going to the mountains every weekend.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order.",
        words: ["Every", "Sunday,", "we", "would", "visit", "our", "cousins."],
        translation: "Todos los domingos visitábamos a nuestros primos.",
        altOrders: [["We", "would", "visit", "our", "cousins", "every", "Sunday"]],
        explanation: "\"Would\" + base verb for a repeated action, with the time expression giving the past context.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Suelo levantarme a las siete.",
        answer: "I usually get up at seven.",
        altAnswers: ["I normally get up at seven.", "I generally get up at seven.", "Usually I get up at seven.", "I usually wake up at seven."],
        explanation: "«Soler» in the present is \"usually\" + present simple. *I use to get up is a classic error: \"used to\" only exists in the past.",
      },
      {
        type: "multiple-choice",
        question: "«De joven, mi madre era profesora.» Which is correct?",
        options: [
          "My mother used to be a teacher when she was young.",
          "My mother would be a teacher when she was young.",
          "My mother was being a teacher when she was young.",
          "My mother used to being a teacher when she was young.",
        ],
        correctIndex: 0,
        explanation: "A past state: \"used to be\" (or simply \"was\"). \"Would be\" sounds conditional, and \"used to\" is followed by the base verb.",
      },
      {
        type: "dictation",
        audio: "My grandfather used to tell us the same jokes every Christmas.",
        explanation: "\"Used to\" + base verb for a repeated past action. In speech, \"used to\" sounds like \"yoosta\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "¿Tu hermano y tú se peleaban mucho de pequeños?",
        answer: "Did you and your brother use to fight a lot when you were little?",
        altAnswers: [
          "Did you and your brother fight a lot when you were little?",
          "Did you and your brother use to fight a lot when you were kids?",
          "Did you and your brother fight a lot when you were kids?",
          "Did you and your brother use to fight a lot as kids?",
          "Did you and your brother fight a lot as kids?",
          "Did you and your brother use to argue a lot when you were little?",
          "Did you and your brother argue a lot when you were little?",
          "Did you and your brother use to fight a lot when you were children?",
          "Did you and your brother use to fight a lot as children?",
        ],
        explanation: "Question: \"Did ... use to\" without -d. «Tu hermano y tú» is naturally \"you and your brother\" in English.",
      },
    ],
  },
];
