// Synced from cheneygross-afk/lengo:src/lib/lessons/en-b1-u12-extra.ts by scripts/sync-content.mjs -- edit it there, not here.
import type { Lesson } from "./types";

// Extra practice (optional) lessons for EN-B1 unit u12.

export const EN_B1_U12_EXTRA: Lesson[] = [
  {
    slug: "en-b1-could-was-able-drill-1",
    optional: true,
    level: "EN-B1",
    number: 1,
    title: "Extra Practice: Could or Managed To?",
    summary: "General ability in the past (could) or one specific success (was able to, managed to)? Multiple choice, gap-fill and translation of «podía», «pude» and «logré».",
    duration: "10 min",
    sections: [
      {
        heading: "Reminder: «podía» vs «pude»",
        body: [
          "\"Could\" = a general ability over a period of time: «podía», «sabía». \"When I was young, I could run fast.\"",
          "One specific success in the past (affirmative): use \"was/were able to\" or \"managed to\" + base form, not \"could\". «Por fin pude abrir la puerta» = \"I finally managed to open the door\" or \"I was finally able to open the door\". \"Managed to\" stresses that it was difficult.",
          "Two exceptions where \"could\" is fine for one moment: negatives (\"I couldn't open the door\") and senses and the mind (\"I could see the mountains\", \"I could hear music\"). And after \"managed to\", use the base form: *I managed to opening is wrong.",
        ],
        examples: [
          { es: "My dad could fix anything.", en: "Mi padre sabía arreglar cualquier cosa." },
          { es: "I finally managed to open the door.", en: "Por fin logré abrir la puerta. (incorrecto: \"I could open the door finally\")" },
          { es: "We were able to see the whole city from the tower.", en: "Pudimos ver toda la ciudad desde la torre." },
          { es: "She couldn't find her keys.", en: "No pudo encontrar las llaves." },
          { es: "I could hear the neighbors arguing.", en: "Oía a los vecinos discutir." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "«Después de tres intentos, logré aprobar el examen de manejar.» Which is the best translation?",
            options: [
              "After three tries, I managed to pass my driving test.",
              "After three tries, I could pass my driving test.",
              "After three tries, I managed to passing my driving test.",
              "After three tries, I could to pass my driving test.",
            ],
            correctIndex: 0,
            explanation: "One specific success after an effort: \"managed to\" + base form. \"Could\" would sound like a general ability.",
          },
          {
            type: "fill-blank",
            prompt: "Write the bold words in English.",
            sentence: "When she was six, she ___ play the violin.",
            answer: "could",
            altAnswers: ["was able to", "knew how to"],
            en: "Con seis años, [sabía] tocar el violín.",
            explanation: "A general ability over a period of her life: \"could\" + base form.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "multiple-choice",
        question: "Which sentence is correct?",
        options: [
          "The fire was huge, but everyone was able to escape.",
          "The fire was huge, but everyone could escape.",
          "The fire was huge, but everyone managed escape.",
          "The fire was huge, but everyone were able to escape.",
        ],
        correctIndex: 0,
        explanation: "One specific success: \"was able to\". \"Everyone\" is singular, so \"was\", not \"were\". \"Managed\" needs \"to\".",
      },
      {
        type: "multiple-choice",
        question: "Which sentence is correct?",
        options: [
          "I lost my wallet, but I managed to get home.",
          "I lost my wallet, but I could get home.",
          "I lost my wallet, but I managed to getting home.",
          "I lost my wallet, but I managed get home.",
        ],
        correctIndex: 0,
        explanation: "A difficult success on one occasion: \"managed to\" + base form \"get\".",
      },
      {
        type: "multiple-choice",
        question: "In which sentence is \"could\" correct?",
        options: [
          "From the plane, we could see the mountains.",
          "Yesterday I could finish the project on time.",
          "Last night the police could catch the thief.",
          "In the end, I could convince my parents.",
        ],
        correctIndex: 0,
        explanation: "With senses like \"see\" and \"hear\", \"could\" is natural for one moment. For the other specific successes, use \"was able to\" or \"managed to\".",
      },
      {
        type: "multiple-choice",
        question: "In which sentence is \"could\" correct?",
        options: [
          "I tried for an hour, but I couldn't start the car.",
          "I tried for an hour and finally I could start the car.",
          "After an hour, I could start the car at last.",
          "Luckily, I could start the car after an hour.",
        ],
        correctIndex: 0,
        explanation: "In the negative, \"couldn't\" is fine for one specific situation. In the affirmative, say \"I managed to start\" or \"I was able to start\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Mi abuela podía leer sin gafas a los noventa años.",
        answer: "My grandmother could read without glasses at ninety.",
        altAnswers: ["My grandmother could read without glasses when she was ninety.", "My grandmother could read without glasses at the age of ninety.", "My grandma could read without glasses at ninety.", "My grandma could read without glasses when she was ninety.", "At ninety, my grandmother could read without glasses.", "My grandmother was able to read without glasses at ninety.", "My grandmother was able to read without glasses when she was ninety."],
        explanation: "A general ability at that time of her life: \"could\". «Gafas» = \"glasses\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Por fin logramos encontrar estacionamiento.",
        answer: "We finally managed to find a parking space.",
        altAnswers: ["We finally managed to find parking.", "We finally managed to find a parking spot.", "We finally managed to find a place to park.", "We were finally able to find a parking space.", "We were finally able to find parking.", "We were finally able to find a parking spot.", "We were finally able to find a place to park.", "Finally we managed to find a parking space.", "Finally, we managed to find a parking space.", "At last we managed to find a parking space."],
        explanation: "«Logramos» on one occasion = \"managed to\" or \"were able to\", not \"could\". \"Finally\" goes before the main verb.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "No pude dormir anoche por el ruido.",
        answer: "I couldn't sleep last night because of the noise.",
        altAnswers: ["I wasn't able to sleep last night because of the noise.", "Last night I couldn't sleep because of the noise.", "Last night, I couldn't sleep because of the noise.", "I couldn't sleep last night due to the noise.", "I didn't manage to sleep last night because of the noise."],
        explanation: "Negative, so \"couldn't\" is perfectly natural for one night. «Por» + noun = \"because of\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "¿Pudiste hablar con el director?",
        answer: "Were you able to talk to the director?",
        altAnswers: ["Did you manage to talk to the director?", "Were you able to speak to the director?", "Did you manage to speak to the director?", "Were you able to speak with the director?", "Were you able to talk to the principal?", "Did you manage to talk to the principal?", "Were you able to speak to the principal?", "Did you manage to speak to the principal?", "Were you able to talk to the manager?", "Did you manage to talk to the manager?"],
        explanation: "Asking about one specific success: \"Were you able to...?\" or \"Did you manage to...?\" Note: a school's «director» is the \"principal\" in American English.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "El examen era difícil, pero conseguí terminarlo a tiempo.",
        answer: "The exam was difficult, but I managed to finish it on time.",
        altAnswers: ["The exam was hard, but I managed to finish it on time.", "The exam was difficult, but I was able to finish it on time.", "The exam was hard, but I was able to finish it on time.", "The exam was difficult but I managed to finish it on time.", "The exam was difficult, but I managed to finish it in time.", "The test was difficult, but I managed to finish it on time.", "The test was hard, but I managed to finish it on time."],
        explanation: "«Conseguí» = \"managed to\" + base form. \"On time\" = at the right time; \"in time\" = before it was too late.",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "The road was closed, but we ___ find another way.",
        answer: "managed to",
        altAnswers: ["were able to"],
        en: "La carretera estaba cortada, pero [conseguimos] encontrar otro camino.",
        explanation: "A specific success: \"managed to\" or \"were able to\", not \"could\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "Before the operation, he ___ walk without help.",
        answer: "couldn't",
        altAnswers: ["could not", "wasn't able to", "was not able to"],
        en: "Antes de la operación, [no podía] caminar sin ayuda.",
        explanation: "A general inability over a period: \"couldn't\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "It was so foggy that we ___ see the road.",
        answer: "could hardly",
        altAnswers: ["couldn't", "could not", "could barely", "were hardly able to"],
        en: "Había tanta niebla que [casi no podíamos] ver la carretera.",
        explanation: "«Casi no podíamos» = \"could hardly\" (or \"could barely\"). \"Hardly\" is already negative, so no \"not\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "Diego ___ get tickets, so we went to the concert.",
        answer: "was able to",
        altAnswers: ["managed to"],
        en: "Diego [pudo] conseguir entradas, así que fuimos al concierto.",
        explanation: "«Pudo» for one success = \"was able to\" or \"managed to\". \"Could get\" would suggest a general ability.",
      },
      {
        type: "matching",
        instructions: "Match each sentence with its meaning.",
        pairs: [
          { left: "I could swim when I was four.", right: "Sabía nadar con cuatro años." },
          { left: "I managed to swim to the island.", right: "Conseguí llegar nadando a la isla." },
          { left: "I couldn't swim because of the waves.", right: "No pude nadar por las olas." },
          { left: "I could see fish in the water.", right: "Se veían peces en el agua." },
        ],
        explanation: "General ability = \"could\"; one success = \"managed to\"; negative and senses = \"couldn't\" / \"could see\".",
      },
      {
        type: "word-order",
        prompt: "Put the words in order.",
        words: ["Did", "you", "manage", "to", "fix", "your", "bike?"],
        translation: "¿Conseguiste arreglar la bici?",
        explanation: "Past question: \"Did you manage to...?\" + base form. Not *Did you managed.",
      },
      {
        type: "listen-choose",
        audio: "In the end, we were able to get a table.",
        question: "What did you hear?",
        options: [
          "Al final, pudimos conseguir mesa.",
          "Al final, no pudimos conseguir mesa.",
          "Al final, podremos conseguir mesa.",
        ],
        correctIndex: 0,
        explanation: "\"Were able to\" = one specific success in the past, «pudimos».",
      },
      {
        type: "dictation",
        audio: "She managed to finish the marathon in four hours.",
        explanation: "\"Managed to\" + base form \"finish\": a difficult success on one occasion.",
      },
    ],
  },
  {
    slug: "en-b1-be-able-to-drill-1",
    optional: true,
    level: "EN-B1",
    number: 2,
    title: "Extra Practice: Will Be Able To",
    summary: "Ability in the tenses where \"can\" doesn't exist: will be able to, have been able to, to be able to, being able to. Transformation and error correction.",
    duration: "10 min",
    sections: [
      {
        heading: "Reminder: be able to fills the gaps",
        body: [
          "\"Can\" has only two forms: \"can\" and \"could\". For every other form of «poder», use \"be able to\": «podré» = \"will be able to\", «he podido» = \"have been able to\", «poder» after another verb = \"to be able to\", after a preposition = \"being able to\".",
          "So *I will can, *I have could, *I'd like to can and *I hope to can are all impossible. Two modals never go together, and \"can\" has no infinitive or participle.",
          "Small trap: don't forget \"to\" at the end: \"will be able to come\", not *will be able come.",
        ],
        examples: [
          { es: "I'll be able to help you tomorrow.", en: "Mañana podré ayudarte. (incorrecto: \"I will can help you\")" },
          { es: "I haven't been able to call her.", en: "No he podido llamarla. (incorrecto: \"I haven't could call her\")" },
          { es: "I'd love to be able to play the guitar.", en: "Me encantaría saber tocar la guitarra." },
          { es: "I hate not being able to sleep.", en: "Odio no poder dormir." },
          { es: "You might be able to get a discount.", en: "Puede que consigas un descuento." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "«Algún día podré hablar inglés perfectamente.» Which is correct?",
            options: [
              "One day I'll be able to speak English perfectly.",
              "One day I'll can speak English perfectly.",
              "One day I'll be able speak English perfectly.",
              "One day I'll could speak English perfectly.",
            ],
            correctIndex: 0,
            explanation: "Future ability: \"will be able to\" + base form. \"Will\" and \"can\" can't go together.",
          },
          {
            type: "fill-blank",
            prompt: "Write the bold words in English.",
            sentence: "Since I broke my arm, I ___ write.",
            answer: "haven't been able to",
            altAnswers: ["have not been able to"],
            en: "Desde que me rompí el brazo, [no he podido] escribir.",
            explanation: "\"Since\" + a situation that continues now: present perfect, \"haven't been able to\".",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "No podré ir a tu fiesta el sábado.",
        answer: "I won't be able to come to your party on Saturday.",
        altAnswers: ["I won't be able to go to your party on Saturday.", "I will not be able to come to your party on Saturday.", "I will not be able to go to your party on Saturday.", "I can't come to your party on Saturday.", "I can't go to your party on Saturday.", "I won't be able to come to your party this Saturday.", "I won't be able to make it to your party on Saturday."],
        explanation: "Future negative: \"won't be able to\". Notice English says \"come to your party\" when you go towards the listener.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "¿Has podido descansar este fin de semana?",
        answer: "Have you been able to rest this weekend?",
        altAnswers: ["Were you able to rest this weekend?", "Have you been able to relax this weekend?", "Were you able to relax this weekend?", "Did you manage to rest this weekend?", "Did you manage to relax this weekend?"],
        explanation: "«Has podido» = \"Have you been able to...?\" If the weekend is over, the past \"Were you able to...?\" is also natural.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Me gustaría poder viajar más.",
        answer: "I'd like to be able to travel more.",
        altAnswers: ["I would like to be able to travel more.", "I'd love to be able to travel more.", "I wish I could travel more."],
        explanation: "After \"would like\" you need an infinitive, and \"can\" has none: \"to be able to\". Not *I'd like to can.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Espero poder verte pronto.",
        answer: "I hope to be able to see you soon.",
        altAnswers: ["I hope I can see you soon.", "I hope I'll be able to see you soon.", "I hope I will be able to see you soon.", "I hope to see you soon.", "I hope I'll see you soon."],
        explanation: "«Espero poder» = \"I hope to be able to\" or, more simply, \"I hope I can\". Never *I hope to can.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Es genial poder trabajar desde casa.",
        answer: "It's great to be able to work from home.",
        altAnswers: ["Being able to work from home is great.", "It's great being able to work from home.", "It is great to be able to work from home."],
        explanation: "\"It's great to be able to...\" or \"Being able to... is great\". \"Can\" can't be an infinitive or an -ing form.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Cuando termines el curso, podrás hablar con cualquiera.",
        answer: "When you finish the course, you'll be able to talk to anyone.",
        altAnswers: ["When you finish the course, you will be able to talk to anyone.", "When you finish the course, you'll be able to speak to anyone.", "When you finish the course, you'll be able to talk to anybody.", "When you finish the course, you'll be able to speak to anybody.", "When you finish the course, you'll be able to talk with anyone.", "You'll be able to talk to anyone when you finish the course.", "When you've finished the course, you'll be able to talk to anyone."],
        explanation: "After \"when\" use the present (\"finish\"), and in the main clause \"will be able to\" for future ability.",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "If you practice every day, you ___ play this song in a month.",
        answer: "will be able to",
        altAnswers: ["'ll be able to"],
        en: "Si practicas todos los días, [podrás] tocar esta canción en un mes.",
        explanation: "Future ability: \"will be able to\". Not *will can.",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "I'm sorry I ___ answer your emails this week.",
        answer: "haven't been able to",
        altAnswers: ["have not been able to"],
        en: "Siento que [no haya podido] contestar tus correos esta semana.",
        explanation: "\"This week\" is not finished: present perfect, \"haven't been able to\". Not *haven't could.",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "I'm worried about not ___ find a job.",
        answer: "being able to",
        en: "Me preocupa no [poder] encontrar trabajo.",
        explanation: "After a preposition (\"about\") we need the -ing form: \"being able to\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "You need ___ swim to do this course.",
        answer: "to be able to",
        en: "Necesitas [saber] nadar para hacer este curso.",
        explanation: "\"Need\" + infinitive: \"to be able to\". «Saber» + infinitive for skills is often \"can\" or \"be able to\" in English.",
      },
      {
        type: "multiple-choice",
        question: "Correct the learner: *I have could finish my homework. Which is right?",
        options: [
          "I've been able to finish my homework.",
          "I've can finish my homework.",
          "I've been able finish my homework.",
          "I've been could finish my homework.",
        ],
        correctIndex: 0,
        explanation: "\"Can\" has no participle, so the present perfect is \"have been able to\".",
      },
      {
        type: "multiple-choice",
        question: "Correct the learner: *Maybe I will can help you later. Which is right?",
        options: [
          "Maybe I'll be able to help you later.",
          "Maybe I'll able to help you later.",
          "Maybe I'll be can help you later.",
          "Maybe I'll be able helping you later.",
        ],
        correctIndex: 0,
        explanation: "\"Will\" + \"be able to\" + base form. Don't forget \"be\": *I'll able to is wrong.",
      },
      {
        type: "multiple-choice",
        question: "Correct the learner: *I would like to can drive. Which is right?",
        options: [
          "I'd like to be able to drive.",
          "I'd like can drive.",
          "I'd like to could drive.",
          "I'd like being able drive.",
        ],
        correctIndex: 0,
        explanation: "\"Would like\" + infinitive \"to be able to\" + base form.",
      },
      {
        type: "matching",
        instructions: "Match each Spanish form with its English equivalent.",
        pairs: [
          { left: "will be able to", right: "podré" },
          { left: "have been able to", right: "he podido" },
          { left: "to be able to", right: "poder (después de otro verbo)" },
          { left: "being able to", right: "poder (después de una preposición)" },
        ],
        explanation: "\"Be able to\" gives \"can\" all the forms it is missing.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order.",
        words: ["Will", "you", "be", "able", "to", "come", "tomorrow?"],
        translation: "¿Podrás venir mañana?",
        explanation: "Future question: \"Will\" + subject + \"be able to\" + verb.",
      },
      {
        type: "listen-choose",
        audio: "She hasn't been able to sleep since the storm.",
        question: "What did you hear?",
        options: [
          "No ha podido dormir desde la tormenta.",
          "No podrá dormir después de la tormenta.",
          "No pudo dormir durante la tormenta.",
        ],
        correctIndex: 0,
        explanation: "\"Hasn't been able to\" + \"since\": present perfect, «no ha podido».",
      },
      {
        type: "dictation",
        audio: "I hope I'll be able to visit you next summer.",
        explanation: "\"I'll be able to\" = future ability. Listen for the weak \"to\" before \"visit\".",
      },
    ],
  },
  {
    slug: "en-b1-deduction-present-drill-1",
    optional: true,
    level: "EN-B1",
    number: 3,
    title: "Extra Practice: Must Be, Can't Be",
    summary: "Present deduction: must (I'm sure it's true), might / could / may (maybe), can't (I'm sure it's not true). Situation multiple choice and gap-fill.",
    duration: "10 min",
    sections: [
      {
        heading: "Reminder: how sure are you?",
        body: [
          "\"Must\" + verb = I'm almost sure it's true: \"The lights are off. They must be out.\" This is «debe de» in Spanish: «deben de haber salido» or «seguro que han salido».",
          "\"Might\", \"may\" or \"could\" + verb = it's possible: \"She might be at the gym.\" \"Can't\" + verb = I'm almost sure it's NOT true: \"He can't be hungry. He's just eaten.\"",
          "Two classic mistakes. The opposite of \"must\" for deduction is \"can't\", not *mustn't: *He mustn't be home is wrong. And \"can\" is not used for a guess about now: say \"It might be him\", not *It can be him.",
          "For something happening right now, use \"be + -ing\": \"She must be working\", \"They might be sleeping\".",
        ],
        examples: [
          { es: "You must be tired after the trip.", en: "Debes de estar cansado después del viaje." },
          { es: "That can't be Emma. She's in Paris.", en: "No puede ser Emma. Está en París. (incorrecto: \"That mustn't be Emma\")" },
          { es: "He might be stuck in traffic.", en: "Puede que esté atascado en el tráfico." },
          { es: "It could be a mistake.", en: "Podría ser un error." },
          { es: "They must be having dinner.", en: "Deben de estar cenando." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "Your friend's phone is ringing, but it's his brother's ringtone, and his brother is sitting next to you. What do you say?",
            options: [
              "It can't be his brother calling.",
              "It mustn't be his brother calling.",
              "It must be his brother calling.",
              "It doesn't have to be his brother calling.",
            ],
            correctIndex: 0,
            explanation: "You're sure it's not true, so \"can't\". \"Mustn't\" is for prohibition, not for deduction.",
          },
          {
            type: "fill-blank",
            prompt: "Write the bold words in English.",
            sentence: "Ana isn't answering. She ___ be in a meeting.",
            answer: "might",
            altAnswers: ["may", "could"],
            en: "Ana no contesta. [Puede que] esté en una reunión.",
            explanation: "«Puede que» = \"might\", \"may\" or \"could\" + base form. Not *can be.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "multiple-choice",
        question: "Lucia has been running for an hour in the sun. What do you say?",
        options: [
          "She must be thirsty.",
          "She can't be thirsty.",
          "She mustn't be thirsty.",
          "She must to be thirsty.",
        ],
        correctIndex: 0,
        explanation: "The evidence makes you almost sure: \"must\" + base form \"be\".",
      },
      {
        type: "multiple-choice",
        question: "The restaurant is completely empty on a Saturday night. What do you say?",
        options: [
          "The food can't be very good.",
          "The food mustn't be very good.",
          "The food doesn't must be very good.",
          "The food can't to be very good.",
        ],
        correctIndex: 0,
        explanation: "A negative deduction: \"can't be\". Never *mustn't be for deduction.",
      },
      {
        type: "multiple-choice",
        question: "Someone is knocking at the door. You aren't expecting anyone. What do you say?",
        options: [
          "It might be the neighbor.",
          "It can be the neighbor.",
          "It must to be the neighbor.",
          "It mights be the neighbor.",
        ],
        correctIndex: 0,
        explanation: "A possibility about now: \"might\" (or \"may\", \"could\"). \"Can\" is not used for a guess about a specific present situation.",
      },
      {
        type: "multiple-choice",
        question: "Tom's car is outside his house and the TV is on. What do you say?",
        options: [
          "He must be at home.",
          "He can't be at home.",
          "He must being at home.",
          "He has to being at home.",
        ],
        correctIndex: 0,
        explanation: "Strong evidence: \"must be\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Debes de estar muy orgulloso de tu hija.",
        answer: "You must be very proud of your daughter.",
        altAnswers: ["You must be really proud of your daughter.", "You must be so proud of your daughter."],
        explanation: "«Debes de» (deduction) = \"must\" + base form. «Orgulloso de» = \"proud of\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "No puede ser verdad. Lo vi ayer.",
        answer: "It can't be true. I saw him yesterday.",
        altAnswers: ["That can't be true. I saw him yesterday.", "It can't be true. I saw it yesterday.", "That can't be true. I saw it yesterday.", "It cannot be true. I saw him yesterday.", "It can't be true, I saw him yesterday.", "That can't be true, I saw him yesterday."],
        explanation: "Sure it's not true: \"can't be\". Not *mustn't be.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Puede que estén durmiendo.",
        answer: "They might be sleeping.",
        altAnswers: ["They may be sleeping.", "They could be sleeping.", "They might be asleep.", "They may be asleep.", "They could be asleep."],
        explanation: "Possible action now: \"might be\" + -ing. «Puede que» + subjunctive never becomes \"can\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Ese hombre debe de ser el profesor nuevo.",
        answer: "That man must be the new teacher.",
        altAnswers: ["That guy must be the new teacher.", "That man must be the new professor."],
        explanation: "«Debe de ser» = \"must be\". Adjective before the noun: \"the new teacher\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Seguro que Carlos está trabajando todavía.",
        answer: "Carlos must still be working.",
        altAnswers: ["Carlos must be still working.", "Carlos must be working still.", "I'm sure Carlos is still working.", "I am sure Carlos is still working."],
        explanation: "«Seguro que» as a deduction = \"must\". Action in progress: \"must be working\". \"Still\" usually goes after \"must\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "This ___ be the right address. There's no house here.",
        answer: "can't",
        altAnswers: ["cannot", "couldn't", "could not"],
        en: "Esta [no puede] ser la dirección correcta. Aquí no hay ninguna casa.",
        explanation: "Sure it's not true: \"can't\". Not *mustn't.",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "You've been studying all day. You ___ be exhausted.",
        answer: "must",
        en: "Llevas todo el día estudiando. [Debes de] estar agotado.",
        explanation: "Strong logical conclusion: \"must\" + base form.",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "Take an umbrella. It ___ rain later.",
        answer: "might",
        altAnswers: ["may", "could"],
        en: "Llévate un paraguas. [Puede que] llueva más tarde.",
        explanation: "A possibility: \"might\", \"may\" or \"could\" + base form. Not *can rain.",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "The baby is crying. She ___ hungry.",
        answer: "must be",
        en: "La bebé está llorando. [Debe de tener] hambre.",
        explanation: "«Tener hambre» = \"be hungry\", so «debe de tener hambre» = \"must be hungry\". Not *must have hunger.",
      },
      {
        type: "matching",
        instructions: "Match each sentence with its meaning.",
        pairs: [
          { left: "He must be at work.", right: "Seguro que está en el trabajo." },
          { left: "He might be at work.", right: "Puede que esté en el trabajo." },
          { left: "He can't be at work.", right: "Es imposible que esté en el trabajo." },
          { left: "He mustn't go to work.", right: "No debe ir a trabajar (está prohibido)." },
        ],
        explanation: "\"Must\" / \"might\" / \"can't\" are for deduction. \"Mustn't\" is about rules and prohibition, not deduction.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order.",
        words: ["You", "can't", "be", "serious!"],
        translation: "¡No puedes estar hablando en serio!",
        explanation: "\"You can't be serious!\" is a very common fixed phrase: I'm sure you're joking.",
      },
      {
        type: "listen-choose",
        audio: "They must be on vacation. The house has been empty for days.",
        question: "What did you hear?",
        options: [
          "Deben de estar de vacaciones. La casa lleva días vacía.",
          "Tienen que irse de vacaciones. La casa lleva días vacía.",
          "No pueden estar de vacaciones. La casa lleva días vacía.",
        ],
        correctIndex: 0,
        explanation: "\"Must be\" here is a deduction from evidence (the empty house), «deben de», not an obligation.",
      },
      {
        type: "speak",
        text: "That can't be right. Let me check again.",
        tip: "Stress \"can't\" and give it a full vowel, like in \"cat\". Unstressed \"can\" in a positive sentence is short and weak, so the stress tells the listener it is negative.",
        explanation: "\"Can't be\" = I'm sure it's not true.",
      },
    ],
  },
  {
    slug: "en-b1-deduction-past-drill-1",
    optional: true,
    level: "EN-B1",
    number: 4,
    title: "Extra Practice: Must Have Been",
    summary: "Past deduction with must have, might have and can't / couldn't have + past participle. Transformation from clues, translation of «debió de» and error correction.",
    duration: "10 min",
    sections: [
      {
        heading: "Reminder: modal + have + past participle",
        body: [
          "For guesses about the past, use modal + \"have\" + past participle. \"Must have\" = I'm sure it happened («debió de», «debe de haber»). \"Might have\" / \"may have\" / \"could have\" = maybe it happened («puede que haya»). \"Can't have\" / \"couldn't have\" = I'm sure it didn't happen («no puede haber»).",
          "\"Have\" never changes after a modal: *must had and *must has are wrong. And you need the participle, not the base form or the past simple: \"must have gone\", not *must have go or *must have went.",
          "«Debió de» is a deduction (\"must have\"), but «debió» without «de» can also mean an obligation that didn't happen, which is \"should have\". Read the context carefully. In speech: \"must've\" (MUST-uv), \"might've\", \"can't've\".",
        ],
        examples: [
          { es: "The streets are wet. It must have rained.", en: "Las calles están mojadas. Debe de haber llovido. (incorrecto: \"It must had rained\")" },
          { es: "She might have missed the bus.", en: "Puede que haya perdido el autobús." },
          { es: "He can't have seen us. He was asleep.", en: "No puede habernos visto. Estaba dormido." },
          { es: "They couldn't have known about the party.", en: "Es imposible que supieran lo de la fiesta." },
          { es: "You must have been very scared.", en: "Debiste de pasar mucho miedo." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "Which sentence is correct?",
            options: [
              "He must have forgotten our meeting.",
              "He must had forgotten our meeting.",
              "He must have forget our meeting.",
              "He must have forgot our meeting.",
            ],
            correctIndex: 0,
            explanation: "\"Must have\" + past participle \"forgotten\" (forget - forgot - forgotten).",
          },
          {
            type: "fill-blank",
            prompt: "Write the bold words in English.",
            sentence: "I can't find my keys. I ___ them at the office.",
            answer: "must have left",
            altAnswers: ["must've left"],
            en: "No encuentro las llaves. [Debo de haberlas dejado] en la oficina.",
            explanation: "A deduction about the past: \"must have\" + participle \"left\".",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Debió de costar mucho dinero.",
        answer: "It must have cost a lot of money.",
        altAnswers: ["That must have cost a lot of money.", "It must have been very expensive.", "It must've cost a lot of money.", "It must have cost lots of money."],
        explanation: "«Debió de» = deduction, \"must have\" + participle. \"Cost\" is the same in all three forms.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Puede que hayan salido a cenar.",
        answer: "They might have gone out for dinner.",
        altAnswers: ["They may have gone out for dinner.", "They could have gone out for dinner.", "They might have gone out to dinner.", "They may have gone out to dinner.", "They might have gone out to eat.", "They may have gone out to eat."],
        explanation: "«Puede que hayan» + participle = \"might have\" + participle. «Salir» to do something = \"go out\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "No puede haberlo hecho él. Estaba conmigo.",
        answer: "He can't have done it. He was with me.",
        altAnswers: ["He couldn't have done it. He was with me.", "He cannot have done it. He was with me.", "He can't have done it, he was with me.", "He couldn't have done it, he was with me."],
        explanation: "Sure it didn't happen: \"can't have\" or \"couldn't have\" + participle \"done\". Never *mustn't have.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Debiste de pasarlo muy bien en Japón.",
        answer: "You must have had a great time in Japan.",
        altAnswers: ["You must have had a really good time in Japan.", "You must have had a very good time in Japan.", "You must have had a lot of fun in Japan.", "You must have had a wonderful time in Japan.", "You must have had a good time in Japan.", "You must have enjoyed Japan a lot.", "You must have enjoyed yourself in Japan."],
        explanation: "«Pasarlo bien» = \"have a good time\"; the participle is \"had\": \"must have had\". The double \"have had\" is correct.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Es imposible que nos oyeran. Hablábamos muy bajo.",
        answer: "They couldn't have heard us. We were speaking very quietly.",
        altAnswers: ["They can't have heard us. We were speaking very quietly.", "They couldn't have heard us. We were talking very quietly.", "They can't have heard us. We were talking very quietly.", "They couldn't have heard us. We were speaking very softly.", "They couldn't have heard us, we were speaking very quietly.", "They can't have heard us, we were talking very quietly."],
        explanation: "«Es imposible que» about the past = \"couldn't have\" / \"can't have\" + participle.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "La puerta estaba abierta. Alguien debe de haber entrado.",
        answer: "The door was open. Someone must have come in.",
        altAnswers: ["The door was open. Somebody must have come in.", "The door was open. Someone must have gone in.", "The door was open. Someone must have got in.", "The door was open. Someone must have gotten in.", "The door was open. Someone must have entered.", "The door was open. Somebody must have gone in.", "The door was open. Somebody must have got in."],
        explanation: "Deduction from a clue: \"must have\" + participle. «Entrar» is usually \"come in\" or \"go in\" in everyday English.",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "Emma didn't answer my message. She ___ busy.",
        answer: "must have been",
        altAnswers: ["must've been"],
        en: "Emma no contestó mi mensaje. [Debía de estar] ocupada.",
        explanation: "Past deduction with \"be\": \"must have been\". Not *must was or *must have be.",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "He ___ the email. He replied to it an hour ago.",
        answer: "must have read",
        altAnswers: ["must've read"],
        en: "[Debe de haber leído] el correo. Lo contestó hace una hora.",
        explanation: "\"Read\" has the same spelling in all forms (but the past and participle sound like \"red\").",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "Diego ___ the thief. He was at home all night.",
        answer: "can't have been",
        altAnswers: ["couldn't have been", "cannot have been", "could not have been"],
        en: "Diego [no puede haber sido] el ladrón. Estuvo en casa toda la noche.",
        explanation: "Impossible in the past: \"can't have been\" or \"couldn't have been\". Not *mustn't have been.",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "I'm not sure where my wallet is. I ___ it in the taxi.",
        answer: "might have dropped",
        altAnswers: ["may have dropped", "could have dropped", "might've dropped", "might have left", "may have left", "could have left", "might have lost", "may have lost"],
        en: "No sé dónde está mi cartera. [Puede que se me haya caído] en el taxi.",
        explanation: "Not sure = \"might have\" + participle. «Se me cayó» is just \"I dropped it\" in English.",
      },
      {
        type: "multiple-choice",
        question: "Correct the learner: *She must have went home early. Which is right?",
        options: [
          "She must have gone home early.",
          "She must had gone home early.",
          "She must have go home early.",
          "She must went home early.",
        ],
        correctIndex: 0,
        explanation: "\"Must have\" + past participle: go - went - gone.",
      },
      {
        type: "multiple-choice",
        question: "Correct the learner: *He mustn't have seen the sign. (= Estoy seguro de que no vio la señal.) Which is right?",
        options: [
          "He can't have seen the sign.",
          "He mustn't saw the sign.",
          "He doesn't must have seen the sign.",
          "He can't had seen the sign.",
        ],
        correctIndex: 0,
        explanation: "The negative of deductive \"must have\" is \"can't have\" or \"couldn't have\", not \"mustn't have\".",
      },
      {
        type: "multiple-choice",
        question: "Your sister's eyes are red and there are tissues everywhere. What do you think?",
        options: [
          "She must have been crying.",
          "She should have been crying.",
          "She must had cried.",
          "She can't have cried.",
        ],
        correctIndex: 0,
        explanation: "Strong evidence about the recent past: \"must have been\" + -ing for an activity in progress.",
      },
      {
        type: "matching",
        instructions: "Match each sentence with its meaning.",
        pairs: [
          { left: "He must have left.", right: "Seguro que se ha ido." },
          { left: "He might have left.", right: "Puede que se haya ido." },
          { left: "He can't have left.", right: "Es imposible que se haya ido." },
          { left: "He should have left.", right: "Debería haberse ido." },
        ],
        explanation: "\"Must have\" / \"might have\" / \"can't have\" are deductions. \"Should have\" is criticism: it was a good idea but it didn't happen.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order.",
        words: ["You", "must", "have", "been", "really", "worried."],
        translation: "Debiste de estar muy preocupado.",
        explanation: "\"Must have been\" + adjective for a feeling in the past.",
      },
      {
        type: "listen-choose",
        audio: "She might've taken the wrong train.",
        question: "What did you hear?",
        options: [
          "Puede que haya tomado el tren equivocado.",
          "Debería haber tomado el otro tren.",
          "No puede haber tomado el tren equivocado.",
        ],
        correctIndex: 0,
        explanation: "\"Might've\" = \"might have\": a possibility about the past, «puede que haya».",
      },
      {
        type: "dictation",
        audio: "They must have been at the beach all day.",
        explanation: "\"Must have been\": deduction about the past. In fast speech it sounds like \"must-uv-bin\".",
      },
    ],
  },
  {
    slug: "en-b1-may-might-drill-1",
    optional: true,
    level: "EN-B1",
    number: 5,
    title: "Extra Practice: Maybe, May Be & Might",
    summary: "Possibility forms: may, might and could + verb versus maybe (an adverb) and may be (a verb). Gap-fill and transformation, with a focus on translating «quizás» and «puede que».",
    duration: "10 min",
    sections: [
      {
        heading: "Reminder: maybe vs may be vs might",
        body: [
          "\"Maybe\" (one word) = «quizás», «a lo mejor». It's an adverb, so the sentence still needs a normal verb: \"Maybe it will rain\", \"Maybe she's at home\".",
          "\"May be\" (two words) = modal \"may\" + verb \"be\": \"She may be at home\" = «puede que esté en casa». \"Might\" and \"could\" work the same way: \"She might be at home\".",
          "Common mistakes: *It maybe true (no verb, so write \"It may be true\" or \"Maybe it's true\"); *Maybe it rains tomorrow (for the future use \"will\": \"Maybe it will rain\", or simply \"It might rain\"); and *It can rain tomorrow for «puede que llueva».",
          "Spanish uses the subjunctive after «quizás» and «puede que». English doesn't: after \"maybe\" use a normal tense, after \"might\" use the base form.",
        ],
        examples: [
          { es: "Maybe it will snow tonight.", en: "Quizás nieve esta noche." },
          { es: "It might snow tonight.", en: "Puede que nieve esta noche. (incorrecto: \"It can snow tonight\")" },
          { es: "That may be true.", en: "Puede que sea verdad. (incorrecto: \"That maybe true\")" },
          { es: "Maybe that's true.", en: "A lo mejor es verdad." },
          { es: "We might not have time.", en: "Puede que no tengamos tiempo." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "Which sentence is correct?",
            options: [
              "He may be late.",
              "He maybe late.",
              "He may is late.",
              "He mays be late.",
            ],
            correctIndex: 0,
            explanation: "Two words: \"may\" + \"be\". *He maybe late has no verb.",
          },
          {
            type: "fill-blank",
            prompt: "Write the bold words in English.",
            sentence: "___ we can meet next week.",
            answer: "Maybe",
            altAnswers: ["Perhaps"],
            en: "[Quizás] podamos vernos la semana que viene.",
            explanation: "At the start of the sentence, before a subject and verb: \"Maybe\" (one word).",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "I'm not sure. It ___ a good idea.",
        answer: "may be",
        altAnswers: ["might be", "could be"],
        en: "No estoy seguro. [Puede que sea] una buena idea.",
        explanation: "After the subject \"It\" you need a verb: \"may be\" (two words) or \"might be\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "___ she's right.",
        answer: "Maybe",
        altAnswers: ["Perhaps"],
        en: "[A lo mejor] tiene razón.",
        explanation: "\"Maybe\" + a complete sentence (\"she's right\"). «Tener razón» = \"be right\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "Don't wait for me. I ___ come.",
        answer: "might not",
        altAnswers: ["may not"],
        en: "No me esperes. [Puede que no] vaya.",
        explanation: "Negative possibility: \"might not\" / \"may not\" + base form. Not *mightn't, which is rare in American English.",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "Bring a sweater. It ___ cold in the mountains.",
        answer: "might be",
        altAnswers: ["may be", "could be"],
        en: "Trae un jersey. [Puede que haga] frío en la montaña.",
        explanation: "«Hace frío» = \"it's cold\", so «puede que haga frío» = \"it might be cold\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Puede que llegue tarde esta noche.",
        answer: "I might be late tonight.",
        altAnswers: ["I may be late tonight.", "I might arrive late tonight.", "I may arrive late tonight.", "I might get home late tonight.", "Maybe I'll be late tonight.", "I could be late tonight.", "He might be late tonight.", "She might be late tonight.", "He might arrive late tonight.", "She might arrive late tonight.", "He may be late tonight.", "She may be late tonight."],
        explanation: "«Puede que» + subjunctive = \"might\" + base form. «Llegar tarde» is usually \"be late\". «Llegue» can be I, he or she.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Quizás tengan otro color.",
        answer: "Maybe they have another color.",
        altAnswers: ["They might have another color.", "They may have another color.", "Perhaps they have another color.", "Maybe they have a different color.", "They might have a different color.", "They may have a different color.", "Perhaps they have a different color."],
        explanation: "After \"maybe\" use a normal tense (\"they have\"), not a special subjunctive form. Or use \"might have\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Puede que no sea tan fácil.",
        answer: "It might not be so easy.",
        altAnswers: ["It may not be so easy.", "It might not be that easy.", "It may not be that easy.", "Maybe it isn't so easy.", "Maybe it's not that easy.", "Maybe it isn't that easy.", "Maybe it's not so easy.", "It might not be as easy."],
        explanation: "Negative possibility: \"might not be\". The subject \"it\" can't be omitted.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "A lo mejor vamos al cine mañana.",
        answer: "We might go to the movies tomorrow.",
        altAnswers: ["We may go to the movies tomorrow.", "Maybe we'll go to the movies tomorrow.", "Maybe we will go to the movies tomorrow.", "We might go to the cinema tomorrow.", "Maybe we'll go to the cinema tomorrow.", "Tomorrow we might go to the movies.", "Maybe we're going to the movies tomorrow.", "We could go to the movies tomorrow."],
        explanation: "Future possibility: \"might go\" or \"Maybe we'll go\". Not *Maybe we go tomorrow.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Puede que esté en lo cierto.",
        answer: "He may be right.",
        altAnswers: ["He might be right.", "She may be right.", "She might be right.", "You may be right.", "You might be right.", "Maybe he's right.", "Maybe she's right.", "Maybe you're right.", "He could be right.", "She could be right.", "You could be right.", "I may be right.", "I might be right."],
        explanation: "«Estar en lo cierto» = \"be right\". The Spanish subject could be him, her or you (usted), so all three are accepted.",
      },
      {
        type: "multiple-choice",
        question: "Correct the learner: *Maybe it rains tomorrow. Which is the most natural?",
        options: [
          "It might rain tomorrow.",
          "It can rain tomorrow.",
          "It maybe rains tomorrow.",
          "It might rains tomorrow.",
        ],
        correctIndex: 0,
        explanation: "For a future possibility, \"might\" + base form. \"Maybe it will rain\" is also fine, but not \"Maybe it rains\".",
      },
      {
        type: "multiple-choice",
        question: "Correct the learner: *It maybe the wrong address. Which is right?",
        options: [
          "It may be the wrong address.",
          "It maybe is the wrong address.",
          "It can be the wrong address.",
          "It may is the wrong address.",
        ],
        correctIndex: 0,
        explanation: "Two words, \"may be\": modal + verb. Or \"Maybe it's the wrong address\".",
      },
      {
        type: "multiple-choice",
        question: "In which sentence is the word written correctly?",
        options: [
          "Maybe we should ask someone.",
          "May be we should ask someone.",
          "We should may be ask someone.",
          "We may be should ask someone.",
        ],
        correctIndex: 0,
        explanation: "\"Maybe\" (one word) is an adverb that usually starts the sentence: \"Maybe we should...\"",
      },
      {
        type: "multiple-choice",
        question: "«Puede que nos mudemos a Canadá el año que viene.» Which is the best translation?",
        options: [
          "We might move to Canada next year.",
          "We can move to Canada next year.",
          "Maybe we move to Canada next year.",
          "We might to move to Canada next year.",
        ],
        correctIndex: 0,
        explanation: "\"Might\" + base form for a future possibility. \"We can move\" means we are able or allowed to, which is different.",
      },
      {
        type: "matching",
        instructions: "Match each sentence with its meaning.",
        pairs: [
          { left: "Maybe she's tired.", right: "A lo mejor está cansada." },
          { left: "She may not be tired.", right: "Puede que no esté cansada." },
          { left: "She must be tired.", right: "Debe de estar cansada." },
          { left: "She can't be tired.", right: "No puede estar cansada." },
        ],
        explanation: "\"Maybe\" and \"may be\" mean the same but have different grammar. \"Must\" = almost sure; \"can't\" = sure it's not true.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order.",
        words: ["Maybe", "they", "missed", "the", "flight."],
        translation: "Quizás perdieron el vuelo.",
        explanation: "\"Maybe\" + a normal past sentence. \"They might have missed the flight\" means the same.",
      },
      {
        type: "listen-choose",
        audio: "It may be too late to call her now.",
        question: "What did you hear?",
        options: [
          "Puede que sea demasiado tarde para llamarla ahora.",
          "Seguro que es demasiado tarde para llamarla ahora.",
          "Debería haberla llamado antes.",
        ],
        correctIndex: 0,
        explanation: "\"May be\" (two words here: modal + verb) = «puede que sea».",
      },
      {
        type: "dictation",
        audio: "Maybe we'll go camping if the weather is nice.",
        explanation: "\"Maybe\" (one word) + \"we'll go\" for the future. After \"if\", the present: \"is\".",
      },
    ],
  },
];
