// Synced from cheneygross-afk/lengo:src/lib/lessons/en-b1-u14-extra.ts by scripts/sync-content.mjs -- edit it there, not here.
import type { Lesson } from "./types";

// Extra practice (optional) lessons for EN-B1 unit u14.

export const EN_B1_U14_EXTRA: Lesson[] = [
  {
    slug: "en-b1-passive-form-drill-1",
    optional: true,
    level: "EN-B1",
    number: 1,
    title: "Extra Practice: Be + Participle",
    summary: "A form drill for the passive in the present and past simple: the right form of be, the right participle, and never forgetting be.",
    duration: "10 min",
    sections: [
      {
        heading: "Reminder: two parts, always",
        body: [
          "The passive always has two parts: \"be\" + past participle. Present: \"am/is/are\" + participle (\"It is made in Italy\"). Past: \"was/were\" + participle (\"It was made in 1990\").",
          "Spanish speakers often forget \"be\" because «se reparó» is one word: *The car repaired yesterday says that the car did the repairing. Correct: \"The car was repaired yesterday.\"",
          "\"Be\" agrees with the subject: \"The window was broken\", \"The windows were broken\".",
        ],
        examples: [
          { es: "The car was repaired yesterday.", en: "El carro se reparó ayer." },
          { es: "These shoes are made by hand.", en: "Estos zapatos están hechos a mano." },
          { es: "The windows were broken in the storm.", en: "Las ventanas se rompieron en la tormenta." },
          { es: "The email is sent every Monday.", en: "El correo se envía todos los lunes." },
          { es: "I was invited to the wedding.", en: "Me invitaron a la boda." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "Which sentence is correct?",
            options: ["The letter sent last week.", "The letter was sent last week.", "The letter was send last week.", "The letter is sended last week."],
            correctIndex: 1,
            explanation: "Past passive = \"was\" + past participle (\"sent\"). Without \"was\", the letter does the sending.",
          },
          {
            type: "fill-blank",
            prompt: "Write the bold words in English.",
            sentence: "The museum ___ every Monday.",
            answer: "is closed",
            en: "El museo [se cierra] todos los lunes.",
            explanation: "A regular fact: present passive, \"is\" + \"closed\".",
          },
        ],
      },
      {
        heading: "Reminder: the participle, not the base form or the past",
        body: [
          "The second part is the PAST PARTICIPLE (third column): build - built - built, write - wrote - written, steal - stole - stolen. Not *It was build and not *The house is builded.",
          "Regular verbs are easy: -ed (\"cleaned\", \"painted\"). With irregular verbs, check the third column: \"was written\", not *was wrote; \"was taken\", not *was took.",
          "Common Independence participles in the passive: made, built, sold, spoken, written, taken, given, found, stolen, broken, known, held, chosen, eaten, seen, drawn, sung.",
        ],
        examples: [
          { es: "The house was built in 1920.", en: "La casa se construyó en 1920." },
          { es: "This book was written in French.", en: "Este libro se escribió en francés." },
          { es: "The photo was taken in Lima.", en: "La foto se hizo en Lima." },
          { es: "My wallet was stolen on the bus.", en: "Me robaron la cartera en el autobús." },
          { es: "The winners were chosen at random.", en: "Los ganadores se eligieron al azar." },
        ],
        checkpoint: [
          {
            type: "matching",
            instructions: "Match each verb with its past participle.",
            pairs: [
              { left: "build", right: "built" },
              { left: "write", right: "written" },
              { left: "steal", right: "stolen" },
              { left: "choose", right: "chosen" },
            ],
            explanation: "The passive uses the third column: \"built\", \"written\", \"stolen\", \"chosen\".",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "El castillo se construyó en el siglo XV.",
        answer: "The castle was built in the fifteenth century.",
        altAnswers: ["The castle was built in the 15th century."],
        explanation: "Past passive: \"was built\". *Was build uses the base form; you need the participle.",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "These bags ___ in Portugal.",
        answer: "are made",
        en: "Estos bolsos [se fabrican] en Portugal.",
        explanation: "Plural subject (\"bags\") + present passive: \"are made\".",
      },
      {
        type: "multiple-choice",
        question: "Which sentence means «Me robaron la bici anoche»?",
        options: ["My bike stole last night.", "My bike was stolen last night.", "My bike was stole last night.", "My bike is stolen last night."],
        correctIndex: 1,
        explanation: "Past passive: \"was\" + \"stolen\" (participle). *My bike stole means the bike was the thief.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Las cartas se escribieron a mano.",
        answer: "The letters were written by hand.",
        explanation: "Plural subject, so \"were\". The participle of \"write\" is \"written\", not *wrote.",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "The bread ___ fresh every morning.",
        answer: "is baked",
        altAnswers: ["is made"],
        en: "El pan [se hace] fresco cada mañana.",
        explanation: "A daily routine about a thing: present passive, \"is baked\" or \"is made\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Me invitaron a la fiesta.",
        answer: "I was invited to the party.",
        altAnswers: ["They invited me to the party.", "I got invited to the party."],
        explanation: "«Me invitaron» with no clear subject is very natural as a passive with \"I\" as the subject: \"I was invited\".",
      },
      {
        type: "multiple-choice",
        question: "Which sentence is correct?",
        options: ["The new hospital was opened in May.", "The new hospital opened by the mayor in May.", "The new hospital was open by the mayor in May.", "The new hospital is opened last May."],
        correctIndex: 0,
        explanation: "Past passive needs \"was\" + participle \"opened\". \"Open\" is an adjective or base form, and \"last May\" needs the past.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "El paquete se entregó ayer.",
        answer: "The package was delivered yesterday.",
        altAnswers: ["The parcel was delivered yesterday.", "Yesterday the package was delivered.", "The package got delivered yesterday."],
        explanation: "Don't forget \"was\": *The package delivered yesterday is incomplete.",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "The keys ___ under the sofa.",
        answer: "were found",
        en: "Las llaves [se encontraron] debajo del sofá.",
        explanation: "Plural subject + past: \"were\" + \"found\" (find - found - found).",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Aquí no se acepta efectivo.",
        answer: "Cash isn't accepted here.",
        altAnswers: ["Cash is not accepted here.", "We don't accept cash here.", "They don't accept cash here.", "Cash isn't accepted.", "We don't take cash here."],
        explanation: "The thing (\"cash\") becomes the subject: \"Cash isn't accepted here.\" Cash is uncountable, so \"is\".",
      },
      {
        type: "multiple-choice",
        question: "Find the mistake: *The match was play in the rain. What is the correct form?",
        options: ["The match was played in the rain.", "The match played in the rain.", "The match was playing in the rain.", "The match is play in the rain."],
        correctIndex: 0,
        explanation: "The passive needs the participle: \"was played\". \"Was playing\" is active (the match was playing something).",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Las ventanas se limpian una vez al mes.",
        answer: "The windows are cleaned once a month.",
        altAnswers: ["The windows get cleaned once a month.", "The windows are washed once a month."],
        explanation: "Present passive with a plural subject: \"are cleaned\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "Her first song ___ in 2015.",
        answer: "was recorded",
        en: "Su primera canción [se grabó] en 2015.",
        explanation: "A finished time (\"in 2015\"): past passive, \"was recorded\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Los niños fueron rescatados por los bomberos.",
        answer: "The children were rescued by the firefighters.",
        altAnswers: ["The children were rescued by firefighters.", "The kids were rescued by the firefighters.", "The kids were rescued by firefighters.", "The children were rescued by the firemen."],
        explanation: "Spanish «fueron rescatados» is the same structure: \"were rescued\". The agent goes after \"by\".",
      },
      {
        type: "word-order",
        prompt: "Put the words in order.",
        words: ["The", "tickets", "were", "sold", "in", "ten", "minutes."],
        translation: "Las entradas se vendieron en diez minutos.",
        explanation: "Subject + \"were\" + participle \"sold\" + time.",
        altOrders: [["In", "ten", "minutes", "the", "tickets", "were", "sold."]],
      },
      {
        type: "listen-choose",
        audio: "The bridge was painted last year.",
        question: "What did you hear?",
        options: ["Pintaron el puente el año pasado.", "El puente se pinta cada año.", "El puente estaba pintando el año pasado.", "Van a pintar el puente el año que viene."],
        correctIndex: 0,
        explanation: "\"Was painted\" + \"last year\" is past passive: «se pintó» or «pintaron».",
      },
      {
        type: "dictation",
        audio: "This picture was drawn by my grandfather.",
        explanation: "\"Drawn\" is the participle of \"draw\" (draw - drew - drawn).",
      },
    ],
  },
  {
    slug: "en-b1-passive-tenses-drill-1",
    optional: true,
    level: "EN-B1",
    number: 2,
    title: "Extra Practice: Is Being Done, Has Been Done",
    summary: "A drill on the passive in the continuous, perfect and future, and after modals: is being built, has been made, will be done, must be finished.",
    duration: "11 min",
    sections: [
      {
        heading: "Reminder: change be, keep the participle",
        body: [
          "In every passive tense, only \"be\" changes. The last word is always the past participle: \"built\", \"made\", \"done\", \"finished\".",
          "Present continuous: \"is/are being\" + participle (\"The road is being repaired\"). Past continuous: \"was/were being\" + participle. Present perfect: \"has/have been\" + participle (\"The tickets have been sold\").",
          "Typical mistakes: *is being build, *has been make, *will be do. The fix is always the participle: \"being built\", \"been made\", \"be done\".",
        ],
        examples: [
          { es: "The road is being repaired.", en: "Están arreglando la carretera." },
          { es: "The house was being painted when we arrived.", en: "Estaban pintando la casa cuando llegamos." },
          { es: "All the tickets have been sold.", en: "Se han vendido todas las entradas." },
          { es: "The cake had been eaten before the party.", en: "Se habían comido la tarta antes de la fiesta." },
          { es: "A new school is being built near my house.", en: "Están construyendo un colegio nuevo cerca de mi casa." },
        ],
        checkpoint: [
          {
            type: "fill-blank",
            prompt: "Write the bold words in English.",
            sentence: "Sorry, your room is still ___.",
            answer: "being cleaned",
            en: "Lo siento, todavía [están limpiando] su habitación.",
            explanation: "An action in progress, passive: \"is being\" + \"cleaned\".",
          },
          {
            type: "multiple-choice",
            question: "Which sentence is correct?",
            options: ["The report has been finish.", "The report has been finished.", "The report has finished by Ana.", "The report has being finished."],
            correctIndex: 1,
            explanation: "Present perfect passive: \"has been\" + participle \"finished\".",
          },
        ],
      },
      {
        heading: "Reminder: future and modals",
        body: [
          "Future: \"will be\" + participle (\"The results will be announced tomorrow\"), or \"is/are going to be\" + participle (\"The old bridge is going to be replaced\").",
          "After any modal: modal + \"be\" + participle. \"It must be finished today\", \"It can be done online\", \"It should be kept in the fridge\", \"It might be canceled\".",
          "Not *must be finish, *can be do, *should be keep. And not *must to be: modals never take \"to\".",
        ],
        examples: [
          { es: "The results will be announced tomorrow.", en: "Los resultados se anunciarán mañana." },
          { es: "The old bridge is going to be replaced.", en: "Van a sustituir el puente viejo." },
          { es: "This form must be signed.", en: "Este formulario tiene que firmarse." },
          { es: "It can be done online.", en: "Se puede hacer por internet." },
          { es: "Milk should be kept in the fridge.", en: "La leche se debe guardar en la nevera." },
          { es: "The flight might be canceled.", en: "Puede que cancelen el vuelo." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "es-en",
            prompt: "Translate into English.",
            source: "Se puede pagar con tarjeta.",
            answer: "You can pay by card.",
            altAnswers: ["It can be paid by card.", "You can pay with a card.", "You can pay with card.", "You can pay by credit card.", "Payment can be made by card.", "You can pay with a credit card."],
            explanation: "With people's actions, English often uses \"you can\". The passive \"can be paid\" is also possible: modal + \"be\" + participle.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "A new stadium ___ in the city center.",
        answer: "is being built",
        en: "[Están construyendo] un estadio nuevo en el centro.",
        explanation: "In progress now: \"is being\" + \"built\". *Is being build uses the base form.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Mi carro ha sido reparado.",
        answer: "My car has been repaired.",
        altAnswers: ["My car has been fixed.", "They've repaired my car.", "They have repaired my car.", "They've fixed my car."],
        explanation: "Present perfect passive: \"has been\" + participle. Spanish «ha sido reparado» matches it exactly.",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "The winners ___ next Friday.",
        answer: "will be announced",
        altAnswers: ["are going to be announced", "will be named", "will be chosen"],
        en: "Los ganadores [se anunciarán] el viernes que viene.",
        explanation: "Future passive: \"will be\" + participle. *Will be announce is wrong.",
      },
      {
        type: "multiple-choice",
        question: "Which sentence means «Hay que terminar el trabajo antes del lunes»?",
        options: ["The work must be finished before Monday.", "The work must be finish before Monday.", "The work must finished before Monday.", "The work must to be finished before Monday."],
        correctIndex: 0,
        explanation: "Modal + \"be\" + participle: \"must be finished\". No \"to\" after \"must\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Se han cancelado todos los vuelos.",
        answer: "All the flights have been canceled.",
        altAnswers: ["All flights have been canceled.", "All of the flights have been canceled.", "They've canceled all the flights.", "They have canceled all the flights."],
        explanation: "«Se han + participio» = \"have been\" + participle. Plural subject, so \"have\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "When I got there, the patient ___ by two doctors.",
        answer: "was being examined",
        altAnswers: ["was being seen"],
        en: "Cuando llegué, dos médicos [estaban examinando] al paciente.",
        explanation: "Past continuous passive: \"was being\" + participle, for an action in progress in the past.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Este medicamento debe guardarse en un lugar fresco.",
        answer: "This medicine should be kept in a cool place.",
        altAnswers: ["This medicine must be kept in a cool place.", "This medication should be kept in a cool place.", "This medication must be kept in a cool place.", "This medicine should be stored in a cool place.", "This medicine must be stored in a cool place.", "This medication should be stored in a cool place.", "This medication must be stored in a cool place."],
        explanation: "Modal + \"be\" + participle: \"should be kept\" (keep - kept - kept). Not *should be keep.",
      },
      {
        type: "multiple-choice",
        question: "Which sentence is correct?",
        options: ["The museum is going to be renovated.", "The museum is going to renovated.", "The museum is going to be renovate.", "The museum going to be renovated."],
        correctIndex: 0,
        explanation: "\"Is going to be\" + participle. Every part is needed: \"is\", \"going to\", \"be\", \"renovated\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Están pintando la cocina, así que comemos fuera.",
        answer: "The kitchen is being painted, so we're eating out.",
        altAnswers: [
          "The kitchen is being painted, so we are eating out.",
          "They're painting the kitchen, so we're eating out.",
          "They are painting the kitchen, so we are eating out.",
          "The kitchen is being painted, so we're eating outside.",
          "The kitchen is being painted so we're eating out.",
          "They're painting the kitchen, so we're eating outside.",
        ],
        explanation: "«Están pintando» with no specific painters: \"is being painted\". «Comer fuera» (en un restaurante) is \"eat out\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "Don't worry, it ___ done online in five minutes.",
        answer: "can be",
        en: "No te preocupes, [se puede] hacer por internet en cinco minutos.",
        explanation: "«Se puede hacer» = \"can be done\": modal + \"be\" + participle.",
      },
      {
        type: "matching",
        instructions: "Match each passive form with its meaning.",
        pairs: [
          { left: "It is being repaired.", right: "Lo están arreglando." },
          { left: "It has been repaired.", right: "Lo han arreglado." },
          { left: "It will be repaired.", right: "Lo arreglarán." },
          { left: "It must be repaired.", right: "Hay que arreglarlo." },
          { left: "It had been repaired.", right: "Lo habían arreglado." },
        ],
        explanation: "Only \"be\" changes (is being, has been, will be, must be, had been); \"repaired\" stays the same.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Puede que retrasen el partido.",
        answer: "The match might be postponed.",
        altAnswers: [
          "The match may be postponed.",
          "The game might be postponed.",
          "The game may be postponed.",
          "The match might be delayed.",
          "The game might be delayed.",
          "The match may be delayed.",
          "The game may be delayed.",
          "The match could be postponed.",
          "The game could be postponed.",
          "They might postpone the match.",
          "They might postpone the game.",
          "They may postpone the game.",
        ],
        explanation: "Possibility + passive: \"might be\" + participle. «Retrasar» an event to another day is \"postpone\"; to a later time the same day, \"delay\".",
      },
      {
        type: "multiple-choice",
        question: "Find the mistake: *All the rooms has been booked. What is the correct form?",
        options: ["All the rooms have been booked.", "All the rooms has booked.", "All the rooms have been book.", "All the rooms have being booked."],
        correctIndex: 0,
        explanation: "\"Rooms\" is plural, so \"have been\" + participle \"booked\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "El problema todavía no se ha resuelto.",
        answer: "The problem hasn't been solved yet.",
        altAnswers: ["The problem has not been solved yet.", "The problem hasn't been resolved yet.", "The problem still hasn't been solved.", "The problem still hasn't been resolved.", "The problem has not been resolved yet."],
        explanation: "Negative present perfect passive: \"hasn't been\" + participle. \"Yet\" goes at the end; \"still\" goes before \"hasn't\".",
      },
      {
        type: "word-order",
        prompt: "Put the words in order.",
        words: ["The", "documents", "will", "be", "sent", "by", "email."],
        translation: "Los documentos se enviarán por correo electrónico.",
        explanation: "\"Will be\" + participle \"sent\". Here \"by email\" is the method, not the agent.",
      },
      {
        type: "listen-choose",
        audio: "The windows had been broken before the police arrived.",
        question: "What did you hear?",
        options: [
          "Habían roto las ventanas antes de que llegara la policía.",
          "Están rompiendo las ventanas antes de que llegue la policía.",
          "La policía rompió las ventanas al llegar.",
          "Romperán las ventanas antes de que llegue la policía.",
        ],
        correctIndex: 0,
        explanation: "\"Had been broken\" is past perfect passive: it happened before another past moment.",
      },
      {
        type: "dictation",
        audio: "The new library is being built right now.",
        explanation: "\"Is being built\": present continuous passive. \"Being\" and \"built\" are both stressed a little.",
      },
    ],
  },
  {
    slug: "en-b1-se-passive-drill-1",
    optional: true,
    level: "EN-B1",
    number: 3,
    title: "Extra Practice: Se Vende, Se Habla",
    summary: "A translation drill from Spanish «se» sentences (se vende, se construyó, se dice) into the English passive or into you, people and they.",
    duration: "10 min",
    sections: [
      {
        heading: "Reminder: «se» + thing = passive",
        body: [
          "When Spanish «se» talks about a thing (a house, a language, a product), English usually uses the passive with the thing as the subject: «Se vende casa» = \"House for sale\" or \"A house is being sold\"; «Aquí se habla inglés» = \"English is spoken here.\"",
          "Two typical mistakes: *It sells (a house doesn't sell anything) and *Is spoken English (English needs the subject first). And never translate «se» as \"itself\": *The church itself was built in 1500 means something else.",
          "The verb agrees with the thing: «Se venden pisos» = \"Apartments are sold\" (or, on a sign, \"Apartments for sale\").",
        ],
        examples: [
          { es: "English is spoken here.", en: "Aquí se habla inglés." },
          { es: "House for sale.", en: "Se vende casa." },
          { es: "The church was built in 1500.", en: "La iglesia se construyó en 1500." },
          { es: "These phones are made in China.", en: "Estos teléfonos se fabrican en China." },
          { es: "Paella is cooked in a wide pan.", en: "La paella se cocina en una sartén ancha." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "Which is the best translation of «Aquí se habla español»?",
            options: ["Spanish is spoken here.", "Is spoken Spanish here.", "Here speaks Spanish.", "Spanish speaks itself here."],
            correctIndex: 0,
            explanation: "The language is the subject of a passive: \"Spanish is spoken here.\" English never starts with *Is spoken.",
          },
          {
            type: "translate",
            direction: "es-en",
            prompt: "Translate into English.",
            source: "El puente se construyó en 1930.",
            answer: "The bridge was built in 1930.",
            explanation: "Past «se» + thing = \"was\" + participle. Not *The bridge built itself.",
          },
        ],
      },
      {
        heading: "Reminder: «se» + people in general = you, people, they",
        body: [
          "When «se» means people in general (impersonal), English often uses \"you\", \"people\" or \"they\" with an active verb: «Se come muy bien aquí» = \"You eat really well here\"; «Se dice que...» = \"People say that...\" or \"They say that...\".",
          "\"You\" = anyone, including me (rules, advice, how things work). \"People\" = people in general. \"They\" = the authorities, the company, the people in that place.",
          "Avoid *One eats well here in everyday English: it sounds very formal.",
        ],
        examples: [
          { es: "You eat really well here.", en: "Aquí se come muy bien." },
          { es: "People say it's going to be a hard winter.", en: "Se dice que va a ser un invierno duro." },
          { es: "How do you say this in English?", en: "¿Cómo se dice esto en inglés?" },
          { es: "They speak Portuguese in Brazil.", en: "En Brasil se habla portugués." },
          { es: "You can't smoke here.", en: "Aquí no se puede fumar." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "es-en",
            prompt: "Translate into English.",
            source: "¿Cómo se escribe tu apellido?",
            answer: "How do you spell your last name?",
            altAnswers: ["How do you spell your surname?", "How is your last name spelled?", "How is your surname spelled?", "How do you spell your family name?"],
            explanation: "«¿Cómo se escribe...?» letter by letter is \"How do you spell...?\". Here \"you\" means anyone.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "En Suiza se hablan cuatro idiomas.",
        answer: "Four languages are spoken in Switzerland.",
        altAnswers: ["In Switzerland, four languages are spoken.", "In Switzerland four languages are spoken.", "They speak four languages in Switzerland.", "People speak four languages in Switzerland.", "In Switzerland they speak four languages.", "In Switzerland, they speak four languages.", "In Switzerland, people speak four languages."],
        explanation: "Plural subject: \"Four languages are spoken\". Or with people: \"They speak four languages\".",
      },
      {
        type: "multiple-choice",
        question: "A sign on a car window says «Se vende». What is the English sign?",
        options: ["For sale", "It sells", "Sells itself", "Is sold"],
        correctIndex: 0,
        explanation: "On signs, «se vende» is \"For sale\". *It sells would mean the car sells something.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Este vino se produce en Chile.",
        answer: "This wine is produced in Chile.",
        altAnswers: ["This wine is made in Chile."],
        explanation: "«Se produce» + thing = present passive: \"is produced\" or \"is made\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "The hotel ___ in the 1990s.",
        answer: "was built",
        en: "El hotel [se construyó] en los años noventa.",
        explanation: "«Se construyó» = \"was built\". Not *built itself and not *was build.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Se dice que el restaurante es muy caro.",
        answer: "People say the restaurant is very expensive.",
        altAnswers: [
          "People say that the restaurant is very expensive.",
          "They say the restaurant is very expensive.",
          "They say that the restaurant is very expensive.",
          "It is said that the restaurant is very expensive.",
          "It's said that the restaurant is very expensive.",
          "The restaurant is said to be very expensive.",
        ],
        explanation: "«Se dice que» = \"People say that\" or \"They say that\" in everyday English. \"It is said that\" is more formal.",
      },
      {
        type: "multiple-choice",
        question: "Which is the most natural translation of «Aquí se vive muy bien»?",
        options: ["You live really well here.", "It lives very well here.", "Is lived very well here.", "Here lives itself very well."],
        correctIndex: 0,
        explanation: "«Se» with people in general: \"you\" + active verb. \"Live\" has no object, so the passive is impossible.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Se necesitan camareros.",
        answer: "Waiters are needed.",
        altAnswers: ["Waiters wanted.", "We need waiters.", "Waiters needed.", "Servers needed.", "Servers wanted.", "Servers are needed.", "We're looking for waiters."],
        explanation: "On a sign, «Se necesitan» is often \"... wanted\" or \"... needed\". In a sentence: \"Waiters are needed\" (plural, so \"are\").",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "How do ___ say «gracias» in Japanese?",
        answer: "you",
        en: "¿Cómo [se] dice «gracias» en japonés?",
        explanation: "«¿Cómo se dice...?» = \"How do you say...?\". The \"you\" is general: anyone.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Se encontraron dos cuadros en el sótano.",
        answer: "Two paintings were found in the basement.",
        altAnswers: ["Two pictures were found in the basement.", "Two paintings were found in the cellar.", "Two pictures were found in the cellar."],
        explanation: "Plural thing + past: \"were found\". The verb agrees with \"paintings\".",
      },
      {
        type: "multiple-choice",
        question: "Which translation of «Se cerró la tienda a las ocho» is correct?",
        options: ["The store was closed at eight.", "The store closed itself at eight.", "It closed the store at eight.", "Was closed the store at eight."],
        correctIndex: 0,
        explanation: "Passive with the thing as subject: \"The store was closed at eight.\" (\"The store closed at eight\" is also fine, but never *closed itself.)",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "No se puede entrar con perros.",
        answer: "You can't come in with dogs.",
        altAnswers: [
          "Dogs aren't allowed.",
          "Dogs are not allowed.",
          "You can't go in with dogs.",
          "You can't enter with dogs.",
          "Dogs aren't allowed in.",
          "Dogs aren't allowed inside.",
          "You can't bring dogs in.",
          "You can't bring dogs inside.",
          "No dogs allowed.",
        ],
        explanation: "Rules with «se puede / no se puede» are usually \"you can / you can't\". Or make the dogs the subject: \"Dogs aren't allowed.\"",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "Most of our vegetables ___ locally.",
        answer: "are grown",
        en: "La mayoría de nuestras verduras [se cultivan] en la zona.",
        explanation: "Plural subject + present passive: \"are grown\" (grow - grew - grown).",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "En mi país se cena muy tarde.",
        answer: "In my country, people have dinner very late.",
        altAnswers: [
          "In my country people have dinner very late.",
          "In my country, we have dinner very late.",
          "In my country we have dinner very late.",
          "In my country, people eat dinner very late.",
          "In my country, we eat dinner very late.",
          "People have dinner very late in my country.",
          "We have dinner very late in my country.",
          "In my country, you have dinner very late.",
          "In my country, people eat very late.",
          "In my country, we eat very late.",
        ],
        explanation: "«Se cena» has no object, so the passive is impossible. Use \"people\" or \"we\" (when you include yourself).",
      },
      {
        type: "matching",
        instructions: "Match each Spanish sentence with the best English version.",
        pairs: [
          { left: "Rooms for rent.", right: "Se alquilan habitaciones." },
          { left: "How do you pronounce this?", right: "¿Cómo se pronuncia esto?" },
          { left: "The tower was built in 1889.", right: "La torre se construyó en 1889." },
          { left: "People say it's haunted.", right: "Se dice que está encantado." },
        ],
        explanation: "«Se» + thing → passive or sign; «se» + people in general → \"you\" or \"people\".",
      },
      {
        type: "word-order",
        prompt: "Put the words in order.",
        words: ["Rice", "is", "grown", "in", "many", "parts", "of", "Asia."],
        translation: "El arroz se cultiva en muchas partes de Asia.",
        explanation: "Subject + \"is\" + participle + place. English needs the subject first.",
        altOrders: [["In", "many", "parts", "of", "Asia", "rice", "is", "grown."]],
      },
      {
        type: "listen-choose",
        audio: "How do you say this word in English?",
        question: "What did you hear?",
        options: ["¿Cómo se dice esta palabra en inglés?", "¿Cómo dijiste esta palabra en inglés?", "¿Qué significa esta palabra en inglés?", "¿Cómo se escribe esta palabra en inglés?"],
        correctIndex: 0,
        explanation: "General \"you\" in a question is Spanish impersonal «se»: «¿Cómo se dice...?». \"Spell\" would be «se escribe».",
      },
      {
        type: "dictation",
        audio: "Portuguese is spoken in Brazil and Angola.",
        explanation: "«Se habla» + language = \"is spoken\".",
      },
    ],
  },
  {
    slug: "en-b1-by-agent-drill-1",
    optional: true,
    level: "EN-B1",
    number: 4,
    title: "Extra Practice: When to Use By",
    summary: "A drill on the agent in passive sentences: when to add by + person, when to leave it out, and by versus with and made of.",
    duration: "10 min",
    sections: [
      {
        heading: "Reminder: include the agent only when it's new or important",
        body: [
          "We use \"by\" + agent only when the person or thing that did the action is important or interesting: \"The Mona Lisa was painted by Leonardo da Vinci.\"",
          "Leave the agent out when it is unknown, obvious or not important. *My wallet was stolen by someone, *English is spoken by people and *He was arrested by the police add nothing: \"My wallet was stolen\", \"English is spoken here\", \"He was arrested\".",
          "If the agent is the most important information, an active sentence is often better: \"My sister made this cake\" rather than \"This cake was made by my sister\" (both are correct).",
        ],
        examples: [
          { es: "The Mona Lisa was painted by Leonardo da Vinci.", en: "La Mona Lisa la pintó Leonardo da Vinci." },
          { es: "My wallet was stolen.", en: "Me robaron la cartera." },
          { es: "He was arrested last night.", en: "Lo detuvieron anoche." },
          { es: "The song was written by a sixteen-year-old girl.", en: "La canción la escribió una chica de dieciséis años." },
          { es: "The mail is delivered at ten.", en: "El correo se reparte a las diez." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "Which sentence is the most natural?",
            options: ["My car was stolen last night.", "My car was stolen by someone last night.", "My car was stolen by a person last night.", "Someone's car was stolen my car last night."],
            correctIndex: 0,
            explanation: "The thief is unknown, so leave out the agent. \"By someone\" adds no information.",
          },
          {
            type: "translate",
            direction: "es-en",
            prompt: "Translate into English.",
            source: "Este puente lo diseñó un arquitecto famoso.",
            answer: "This bridge was designed by a famous architect.",
            altAnswers: ["A famous architect designed this bridge."],
            explanation: "The agent is new and interesting, so keep it: \"by a famous architect\".",
          },
        ],
      },
      {
        heading: "Reminder: by, with, made of, made from",
        body: [
          "\"By\" + the person or thing that DID the action: \"The house was destroyed by a fire.\" \"With\" + the tool or instrument someone used: \"The door was opened with a key.\"",
          "Materials use \"made of\" (you can still see the material) or \"made from\" (it has changed): \"The table is made of wood\", \"Paper is made from wood.\" Not *made by wood or *made with wood.",
          "\"Made by\" + person or company: \"This guitar was made by my uncle.\" \"Made in\" + place: \"made in Japan\".",
        ],
        examples: [
          { es: "The house was destroyed by a fire.", en: "La casa fue destruida por un incendio." },
          { es: "The door was opened with a key.", en: "La puerta se abrió con una llave." },
          { es: "The table is made of wood.", en: "La mesa es de madera." },
          { es: "Cheese is made from milk.", en: "El queso se hace con leche." },
          { es: "This guitar was made by my uncle.", en: "Esta guitarra la hizo mi tío." },
        ],
        checkpoint: [
          {
            type: "fill-blank",
            prompt: "Write the bold words in English.",
            sentence: "This ring is made ___ silver.",
            answer: "of",
            en: "Este anillo es [de] plata.",
            explanation: "Material you can still see: \"made of\". Not *made by silver.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "multiple-choice",
        question: "Find the mistake: *The table is made by wood. What is the correct form?",
        options: ["The table is made of wood.", "The table is made with wood.", "The table is made from a wood.", "The table made of wood."],
        correctIndex: 0,
        explanation: "Material = \"made of\". \"By\" is for the person who made it.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Me robaron el celular en el metro.",
        answer: "My phone was stolen on the subway.",
        altAnswers: [
          "My phone was stolen on the metro.",
          "My phone was stolen on the underground.",
          "My cell phone was stolen on the subway.",
          "My mobile was stolen on the underground.",
          "Someone stole my phone on the subway.",
          "Someone stole my phone on the metro.",
          "I had my phone stolen on the subway.",
          "I had my phone stolen on the metro.",
          "My phone got stolen on the subway.",
          "My phone got stolen on the metro.",
        ],
        explanation: "We don't know the thief, so no agent: \"My phone was stolen\". Not *was stolen by someone.",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "The letter was written ___ a pencil.",
        answer: "with",
        en: "La carta se escribió [con] un lápiz.",
        explanation: "A tool or instrument takes \"with\". \"By\" is for the person who wrote it.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Cien años de soledad la escribió Gabriel García Márquez.",
        answer: "One Hundred Years of Solitude was written by Gabriel Garcia Marquez.",
        altAnswers: ["Gabriel Garcia Marquez wrote One Hundred Years of Solitude.", "One Hundred Years of Solitude was written by Gabriel García Márquez.", "Gabriel García Márquez wrote One Hundred Years of Solitude."],
        explanation: "The author is the important information, so keep \"by\" + agent. The name can be written with or without accents.",
      },
      {
        type: "multiple-choice",
        question: "Which sentence is the most natural?",
        options: ["The thief was arrested yesterday.", "The thief was arrested by the police yesterday.", "The thief was arrested by people yesterday.", "The thief arrested yesterday."],
        correctIndex: 0,
        explanation: "Only the police arrest people, so \"by the police\" is obvious. Leave it out.",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "The village was cut off ___ the snow.",
        answer: "by",
        en: "El pueblo quedó aislado [por] la nieve.",
        explanation: "The snow caused it, so it is the agent: \"by the snow\". Things and forces of nature can be agents too.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "El vino se hace con uvas.",
        answer: "Wine is made from grapes.",
        explanation: "The grapes change completely, so \"made from\". *Made by grapes and *made with grapes are not natural here.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "El ganador será elegido por el público.",
        answer: "The winner will be chosen by the audience.",
        altAnswers: ["The winner will be chosen by the public.", "The audience will choose the winner.", "The public will choose the winner.", "The winner will be picked by the audience.", "The winner will be selected by the audience."],
        explanation: "Here the agent is new and important (who decides?), so keep \"by the audience\".",
      },
      {
        type: "multiple-choice",
        question: "In which sentence would adding \"by people\" be pointless?",
        options: [
          "Spanish is spoken in twenty countries.",
          "The film was directed by Pedro Almodovar.",
          "The theory was developed by a young scientist.",
          "Our cat was saved by a neighbor.",
        ],
        correctIndex: 0,
        explanation: "\"By people\" in the first sentence would add nothing. In the others the agent is new information.",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "These chairs were made ___ my grandfather.",
        answer: "by",
        en: "Estas sillas fueron hechas [por] mi abuelo.",
        explanation: "Person who made something: \"made by\". Compare \"made of wood\" (material) and \"made in Italy\" (place).",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "La ciudad fue destruida por un terremoto en 1755.",
        answer: "The city was destroyed by an earthquake in 1755.",
        altAnswers: ["An earthquake destroyed the city in 1755.", "In 1755, the city was destroyed by an earthquake.", "In 1755 the city was destroyed by an earthquake."],
        explanation: "\"By\" + the cause (a natural force is a perfectly good agent).",
      },
      {
        type: "matching",
        instructions: "Match each phrase with its use.",
        pairs: [
          { left: "made by", right: "hecho por (persona o empresa)" },
          { left: "made of", right: "hecho de (material que se ve)" },
          { left: "made from", right: "hecho a partir de (material transformado)" },
          { left: "made in", right: "hecho en (lugar)" },
          { left: "opened with", right: "abierto con (herramienta)" },
        ],
        explanation: "Each preposition has its own job; Spanish «de», «con» and «por» don't map one-to-one.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "La ventana se rompió con una pelota.",
        answer: "The window was broken by a ball.",
        altAnswers: ["The window was broken with a ball.", "A ball broke the window.", "The window got broken by a ball."],
        explanation: "If the ball hit it by itself, it is the cause: \"by a ball\". If someone threw it on purpose, \"with a ball\" is possible too.",
      },
      {
        type: "multiple-choice",
        question: "Which sentence is correct?",
        options: ["The cake was cut with a knife.", "The cake was cut by a knife by Tom.", "The cake was cut by knife.", "The cake cut with a knife."],
        correctIndex: 0,
        explanation: "The knife is the tool, so \"with a knife\". The passive needs \"was\" + participle.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order.",
        words: ["The", "house", "was", "damaged", "by", "the", "storm."],
        translation: "La casa resultó dañada por la tormenta.",
        explanation: "\"By\" + the cause at the end of the passive sentence.",
      },
      {
        type: "listen-choose",
        audio: "This bowl is made of glass, and it was made in Mexico.",
        question: "What did you hear?",
        options: [
          "Este cuenco es de cristal y se hizo en México.",
          "Este cuenco lo hizo un mexicano con cristal.",
          "Este cuenco se hace con arena en México.",
          "Este cuenco es de México, pero el cristal no.",
        ],
        correctIndex: 0,
        explanation: "\"Made of\" = material, \"made in\" = place.",
      },
      {
        type: "dictation",
        audio: "The building was designed by a young architect.",
        explanation: "The agent is interesting, so it stays: \"by a young architect\".",
      },
    ],
  },
];
