// Synced from cheneygross-afk/lengo:src/lib/lessons/en-b2-u26-extra.ts by scripts/sync-content.mjs -- edit it there, not here.
import type { Lesson } from "./types";

// Extra practice (optional) lessons for EN-B2 unit u26 (word webs: personality,
// feelings, relationships, health, idioms, dependent prepositions, prefixes).
// Drill-focused: a short recap, then a long mixed set of exercises.

export const EN_B2_U26_EXTRA: Lesson[] = [
  // ---------------------------------------------------------------------
  // Extra 1. Personality and feelings
  // ---------------------------------------------------------------------
  {
    slug: "en-b2-personality-feelings-drill-1",
    optional: true,
    level: "EN-B2",
    number: 1,
    title: "Extra Practice: Personality and Feelings",
    summary: "Drill the false friends (\"sensible\" / \"sensitive\", \"embarrassed\" / \"pregnant\", \"sympathetic\") and the -ed / -ing pairs, so you never say *I'm boring when you mean «estoy aburrido».",
    duration: "10 min",
    sections: [
      {
        heading: "Quick recap: false friends",
        body: [
          "\"Sensible\" means «sensato» (practical, with good judgment). «Sensible» (easily hurt or moved) is \"sensitive\". \"Sympathetic\" means «comprensivo»; «simpático» is \"nice\" or \"friendly\".",
          "\"Embarrassed\" means «avergonzado, con vergüenza» (because something awkward happened). «Embarazada» is \"pregnant\". And \"nervous\" is «nervioso» when you are worried before something, not when you are excited: «nervioso» because of a good thing coming is often \"excited\".",
        ],
        examples: [
          { es: "It was a sensible choice.", en: "Fue una elección sensata." },
          { es: "Be careful what you say. He's very sensitive.", en: "Cuidado con lo que dices. Es muy sensible." },
          { es: "My boss was very sympathetic when my dad was ill.", en: "Mi jefe fue muy comprensivo cuando mi padre estuvo enfermo." },
          { es: "I was so embarrassed when I called her by the wrong name.", en: "Me dio muchísima vergüenza cuando la llamé por otro nombre." },
          { es: "I'm nervous about the interview.", en: "Estoy nervioso por la entrevista." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "Your friend is going to have a baby. Which sentence is correct?",
            options: ["She's pregnant.", "She's embarrassed.", "She's embarrassing.", "She's sensible."],
            correctIndex: 0,
            explanation: "«Embarazada» = \"pregnant\". \"Embarrassed\" means «avergonzada».",
          },
        ],
      },
      {
        heading: "Quick recap: -ed vs -ing",
        body: [
          "-ed adjectives describe how a person feels: \"I'm bored\", \"She was tired\", \"We were surprised\". -ing adjectives describe the thing (or person) that causes the feeling: \"The film was boring\", \"a tiring day\", \"surprising news\".",
          "So *I'm boring means «soy aburrido» (people find you dull), not «estoy aburrido». The same with \"interested / interesting\", \"confused / confusing\", \"excited / exciting\", \"annoyed / annoying\", \"embarrassed / embarrassing\".",
        ],
        examples: [
          { es: "I'm really bored. Let's go out.", en: "Estoy muy aburrido. Vamos a salir. (incorrecto: *I'm boring)" },
          { es: "The instructions were really confusing.", en: "Las instrucciones eran muy confusas." },
          { es: "I'm confused. Can you explain it again?", en: "Estoy confundido. ¿Puedes explicarlo otra vez?" },
          { es: "We're so excited about the concert!", en: "¡Estamos muy emocionados por el concierto!" },
          { es: "It was the most embarrassing moment of my life.", en: "Fue el momento más vergonzoso de mi vida." },
        ],
        checkpoint: [
          {
            type: "fill-blank",
            prompt: "Write the bold words in English.",
            sentence: "The match was so ___ that we couldn't stop watching.",
            answer: "exciting",
            altAnswers: ["thrilling", "gripping"],
            en: "El partido fue tan [emocionante] que no podíamos dejar de mirar.",
            explanation: "The match causes the feeling: -ing, \"exciting\". The people watching are \"excited\".",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Mi hijo es muy sensible: llora por cualquier cosa.",
        answer: "My son is very sensitive: he cries about anything.",
        altAnswers: ["My son is very sensitive. He cries about anything.", "My son is very sensitive: he cries at anything.", "My son is very sensitive. He cries at anything.", "My son is very sensitive: he cries over anything.", "My son is very sensitive. He cries over anything.", "My son is really sensitive: he cries about anything.", "My son is really sensitive. He cries about anything.", "My son is very sensitive: he cries about everything.", "My son is very sensitive. He cries about everything."],
        explanation: "«Sensible» = \"sensitive\". \"Sensible\" in English means «sensato».",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "I was so ___ that I fell asleep on the sofa at nine.",
        answer: "tired",
        altAnswers: ["exhausted"],
        en: "Estaba tan [cansado] que me quedé dormido en el sofá a las nueve.",
        explanation: "How a person feels = -ed: \"tired\". The day was \"tiring\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Lo más sensato es esperar.",
        answer: "The sensible thing is to wait.",
        altAnswers: ["The most sensible thing is to wait.", "The sensible thing to do is wait.", "The sensible thing to do is to wait.", "The most sensible thing to do is wait.", "The most sensible thing to do is to wait."],
        explanation: "«Sensato» = \"sensible\". Classic false friend.",
      },
      {
        type: "multiple-choice",
        question: "Correct the learner: *This book is very interested.",
        options: ["This book is very interesting.", "This book is very interest.", "This book is very interests.", "This book is very interestingly."],
        correctIndex: 0,
        explanation: "The book causes the interest: \"interesting\". You are \"interested in\" the book.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Me dio vergüenza porque se me olvidó su nombre.",
        answer: "I was embarrassed because I forgot her name.",
        altAnswers: ["I was embarrassed because I forgot his name.", "I was embarrassed because I'd forgotten her name.", "I was embarrassed because I'd forgotten his name.", "I felt embarrassed because I forgot her name.", "I felt embarrassed because I forgot his name.", "I was embarrassed because I forgot their name."],
        explanation: "«Me dio vergüenza» = \"I was embarrassed\". English uses \"be\" + -ed adjective, with the person as the subject.",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "Our teacher was very ___ when I told her about my problems at home.",
        answer: "sympathetic",
        altAnswers: ["understanding", "supportive"],
        en: "Nuestra profesora fue muy [comprensiva] cuando le conté mis problemas en casa.",
        explanation: "\"Sympathetic\" = «comprensivo». For «simpático», use \"nice\" or \"friendly\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Tu nuevo compañero de piso es muy simpático.",
        answer: "Your new roommate is really nice.",
        altAnswers: ["Your new roommate is very nice.", "Your new flatmate is really nice.", "Your new flatmate is very nice.", "Your new roommate is really friendly.", "Your new roommate is very friendly.", "Your new flatmate is really friendly.", "Your new flatmate is very friendly."],
        explanation: "«Simpático» = \"nice\" / \"friendly\", never *sympathetic. «Compañero de piso» = \"roommate\" (US) or \"flatmate\" (UK).",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "It's really ___ when people talk during a film.",
        answer: "annoying",
        altAnswers: ["irritating"],
        en: "Es muy [molesto] cuando la gente habla durante una película.",
        explanation: "The situation causes the feeling: \"annoying\". You feel \"annoyed\".",
      },
      {
        type: "matching",
        instructions: "Match the English with the Spanish.",
        pairs: [
          { left: "sensible", right: "sensato" },
          { left: "sensitive", right: "sensible" },
          { left: "sympathetic", right: "comprensivo" },
          { left: "embarrassed", right: "avergonzado" },
          { left: "pregnant", right: "embarazada" },
          { left: "nice", right: "simpático" },
        ],
        explanation: "Five classic false friends in one go. Learn them as pairs.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Estábamos muy emocionados porque nos íbamos de vacaciones.",
        answer: "We were really excited because we were going on vacation.",
        altAnswers: ["We were very excited because we were going on vacation.", "We were really excited because we were going on holiday.", "We were very excited because we were going on holiday.", "We were so excited because we were going on vacation.", "We were so excited because we were going on holiday."],
        explanation: "Happy anticipation = \"excited\". \"Emotional\" means «emocionado» in the sense of moved, near tears.",
      },
      {
        type: "multiple-choice",
        question: "Which sentence means «Estoy aburrido»?",
        options: ["I'm bored.", "I'm boring.", "I'm bore.", "I'm boredom."],
        correctIndex: 0,
        explanation: "How you feel = \"bored\". \"I'm boring\" means other people find you dull.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "La reunión fue agotadora y todos salimos agotados.",
        answer: "The meeting was exhausting and we all came out exhausted.",
        altAnswers: ["The meeting was exhausting and we all left exhausted.", "The meeting was exhausting, and we all came out exhausted.", "The meeting was exhausting, and we all left exhausted.", "The meeting was exhausting and we were all exhausted afterwards.", "The meeting was exhausting and we were all exhausted afterward.", "The meeting was exhausting and everyone left exhausted."],
        explanation: "Thing = \"exhausting\" (-ing); people = \"exhausted\" (-ed).",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "I always get ___ before I speak in public.",
        answer: "nervous",
        en: "Siempre me pongo [nervioso] antes de hablar en público.",
        explanation: "«Ponerse nervioso» = \"get nervous\". \"Get\" + adjective often translates «ponerse».",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Estoy confundida. El mapa es muy confuso.",
        answer: "I'm confused. The map is very confusing.",
        altAnswers: ["I'm confused. The map is really confusing.", "I'm confused. This map is very confusing.", "I'm confused. This map is really confusing."],
        explanation: "Person = \"confused\"; the thing that confuses = \"confusing\".",
      },
      {
        type: "word-order",
        prompt: "Put the words in order.",
        words: ["We", "were", "disappointed", "with", "the", "ending"],
        translation: "Nos decepcionó el final.",
        explanation: "Spanish makes the ending the subject («nos decepcionó»), but English uses the people + -ed: \"We were disappointed\". The ending was \"disappointing\".",
      },
      {
        type: "listen-choose",
        audio: "Don't worry about Tom. He's very sensible, so he won't do anything silly.",
        question: "What is Tom like?",
        options: ["Sensato.", "Sensible y llorón.", "Tímido.", "Simpático."],
        correctIndex: 0,
        explanation: "\"Sensible\" = «sensato»: he won't do anything silly.",
      },
      {
        type: "dictation",
        audio: "I felt embarrassed, but everyone was very sympathetic.",
        explanation: "\"Embarrassed\" (double r, double s) = «avergonzado»; \"sympathetic\" = «comprensivo».",
      },
    ],
  },

  // ---------------------------------------------------------------------
  // Extra 2. Relationship words
  // ---------------------------------------------------------------------
  {
    slug: "en-b2-relationships-words-drill-1",
    optional: true,
    level: "EN-B2",
    number: 2,
    title: "Extra Practice: Relationship Words",
    summary: "Drill \"get on with\", \"fall out\", \"break up\", \"go out with\", \"make up\" and \"get engaged / married\", and avoid three classic slips: *marry with, *discuss for «discutir», and \"parents\" for «parientes».",
    duration: "10 min",
    sections: [
      {
        heading: "Quick recap: the relationship verbs",
        body: [
          "\"Get on (well) with\" someone = «llevarse bien con» (American English also says \"get along with\"). \"Fall out with\" someone = stop being friends after an argument («enfadarse, pelearse con»). \"Make up\" = become friends again («hacer las paces, reconciliarse»).",
          "\"Go out with\" someone = have a romantic relationship («salir con»). \"Break up (with)\" = end it («cortar, romper con»). Then \"get engaged\" («prometerse») and \"get married\" («casarse»).",
        ],
        examples: [
          { es: "I get on really well with my brother-in-law.", en: "Me llevo muy bien con mi cuñado." },
          { es: "She fell out with her best friend over a boy.", en: "Se peleó con su mejor amiga por un chico." },
          { es: "They argued all morning, but they made up at lunch.", en: "Discutieron toda la mañana, pero hicieron las paces a la hora de comer." },
          { es: "How long have you been going out with him?", en: "¿Cuánto tiempo llevas saliendo con él?" },
          { es: "They got engaged in Paris.", en: "Se prometieron en París." },
        ],
        checkpoint: [
          {
            type: "fill-blank",
            prompt: "Write the bold words in English.",
            sentence: "Diego and Sofia ___ after five years together.",
            answer: "broke up",
            altAnswers: ["split up"],
            en: "Diego y Sofia [rompieron] después de cinco años juntos.",
            explanation: "\"Break up\" (past \"broke up\") = end a relationship. \"Split up\" means the same.",
          },
        ],
      },
      {
        heading: "Quick recap: marry, argue, relatives",
        body: [
          "\"Marry\" takes a direct object with no preposition: \"She married a doctor\". With \"get married\" or \"be married\", use \"to\": \"She got married to a doctor\", \"He's married to my cousin\". *Marry with and *married with are wrong.",
          "«Discutir» (have an argument) is \"argue\" or \"have an argument\". \"Discuss\" means «hablar de, tratar un tema» calmly, and it takes no preposition: \"discuss the plan\", not *discuss about. «Parientes» are \"relatives\"; \"parents\" are only your mother and father.",
        ],
        examples: [
          { es: "She married her childhood friend.", en: "Se casó con su amigo de la infancia. (incorrecto: *married with)" },
          { es: "My aunt is married to an American.", en: "Mi tía está casada con un estadounidense." },
          { es: "My neighbors argue every night.", en: "Mis vecinos discuten todas las noches." },
          { es: "We need to discuss the budget.", en: "Tenemos que hablar del presupuesto. (incorrecto: *discuss about)" },
          { es: "All my relatives came to the wedding.", en: "Todos mis parientes vinieron a la boda." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "Correct the learner: *My sister married with a Canadian last year.",
            options: ["My sister married a Canadian last year.", "My sister married to a Canadian last year.", "My sister got married with a Canadian last year.", "My sister was married with a Canadian last year."],
            correctIndex: 0,
            explanation: "\"Marry\" + person directly, or \"get married to\" + person. Never \"with\".",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Mis padres discuten mucho por la casa.",
        answer: "My parents argue a lot about the house.",
        altAnswers: ["My parents argue a lot over the house.", "My parents have a lot of arguments about the house.", "My parents fight a lot about the house.", "My parents fight a lot over the house."],
        explanation: "«Discutir» (an argument) = \"argue\", not *discuss. \"Argue about\" something.",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "Do you ___ with your colleagues?",
        answer: "get on",
        altAnswers: ["get along"],
        en: "¿Te [llevas bien] con tus compañeros de trabajo?",
        explanation: "\"Get on with\" (UK, US) / \"get along with\" (US) = «llevarse bien con».",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Se casaron en la playa.",
        answer: "They got married on the beach.",
        altAnswers: ["They got married at the beach."],
        explanation: "«Casarse» without an object = \"get married\". Not *They married themselves.",
      },
      {
        type: "multiple-choice",
        question: "«Mañana tenemos que hablar del contrato.» Which translation is correct?",
        options: ["We have to discuss the contract tomorrow.", "We have to discuss about the contract tomorrow.", "We have to argue the contract tomorrow.", "We have to discuss on the contract tomorrow."],
        correctIndex: 0,
        explanation: "\"Discuss\" + object directly: \"discuss the contract\". You can say \"talk about\", but never *discuss about.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Se pelearon hace un año y todavía no se hablan.",
        answer: "They fell out a year ago and they still don't speak to each other.",
        altAnswers: ["They fell out a year ago and they still aren't speaking to each other.", "They fell out a year ago and still don't speak to each other.", "They fell out a year ago and still aren't speaking to each other.", "They fell out a year ago and they still don't talk to each other.", "They fell out a year ago and still don't talk to each other.", "They fell out a year ago and they're still not speaking to each other.", "They fell out a year ago and they're still not talking to each other."],
        explanation: "«Pelearse» (stop being friends) = \"fall out\". «Se hablan» (each other) = \"speak to each other\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "We had a big argument, but we ___ the next morning.",
        answer: "made up",
        en: "Tuvimos una gran discusión, pero [hicimos las paces] a la mañana siguiente.",
        explanation: "\"Make up\" (past \"made up\") = «hacer las paces, reconciliarse».",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "En Navidad vienen todos nuestros parientes.",
        answer: "All our relatives come at Christmas.",
        altAnswers: ["All our relatives come for Christmas.", "All of our relatives come at Christmas.", "All of our relatives come for Christmas.", "At Christmas all our relatives come.", "At Christmas, all our relatives come.", "At Christmas all our relatives come over.", "All our relatives come over at Christmas.", "All our relatives come over for Christmas."],
        explanation: "«Parientes» = \"relatives\" (or \"family\"). \"Parents\" are only your mother and father.",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "My cousin is ___ to a famous chef.",
        answer: "married",
        en: "Mi primo está [casado] con un chef famoso.",
        explanation: "\"Be married to\" + person. Spanish «con» becomes \"to\" here.",
      },
      {
        type: "matching",
        instructions: "Match the English with the Spanish.",
        pairs: [
          { left: "get on with", right: "llevarse bien con" },
          { left: "fall out with", right: "pelearse con" },
          { left: "make up", right: "hacer las paces" },
          { left: "go out with", right: "salir con" },
          { left: "break up", right: "romper (una pareja)" },
          { left: "get engaged", right: "prometerse" },
        ],
        explanation: "Most relationship verbs are phrasal verbs. Learn them with their prepositions.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "¿Con quién está saliendo tu hermana?",
        answer: "Who is your sister going out with?",
        altAnswers: ["Who's your sister going out with?", "Who is your sister dating?", "Who's your sister dating?", "Who is your sister seeing?", "Who's your sister seeing?"],
        explanation: "In everyday questions the preposition goes at the end: \"Who... going out with?\" \"Date\" and \"see\" take a direct object.",
      },
      {
        type: "multiple-choice",
        question: "Correct the learner: *All my parents live in Mexico: my aunts, uncles, cousins...",
        options: ["All my relatives live in Mexico: my aunts, uncles, cousins...", "All my parentses live in Mexico: my aunts, uncles, cousins...", "All my familiars live in Mexico: my aunts, uncles, cousins...", "All my fathers live in Mexico: my aunts, uncles, cousins..."],
        correctIndex: 0,
        explanation: "«Parientes» = \"relatives\". \"Familiar\" is an adjective meaning «conocido».",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Se prometieron en verano y se casarán el año que viene.",
        answer: "They got engaged in the summer and they're getting married next year.",
        altAnswers: ["They got engaged in the summer and they'll get married next year.", "They got engaged in the summer and will get married next year.", "They got engaged in summer and they're getting married next year.", "They got engaged in summer and they'll get married next year.", "They got engaged in the summer and are getting married next year.", "They got engaged in the summer and they are going to get married next year.", "They got engaged in the summer and they're going to get married next year."],
        explanation: "\"Get engaged\" = «prometerse»; \"get married\" = «casarse». For a planned wedding, the present continuous is very natural.",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "She ___ with him because he never listened to her.",
        answer: "broke up",
        altAnswers: ["split up"],
        en: "[Cortó] con él porque nunca la escuchaba.",
        explanation: "\"Break up with\" someone = «cortar con» alguien.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Mi abuelo se casó con mi abuela cuando tenía veinte años.",
        answer: "My grandfather married my grandmother when he was twenty.",
        altAnswers: ["My grandfather married my grandmother when he was twenty years old.", "My grandpa married my grandma when he was twenty.", "My grandfather got married to my grandmother when he was twenty.", "My grandfather married my grandmother when she was twenty.", "My grandfather got married to my grandmother when she was twenty."],
        explanation: "\"Marry\" + person, with no preposition. Age with \"be\": \"he was twenty\", never *had twenty years.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order.",
        words: ["I've", "never", "fallen", "out", "with", "my", "sister"],
        translation: "Nunca me he peleado con mi hermana.",
        explanation: "\"Fall out with\": past participle \"fallen\". \"Never\" goes between \"have\" and the participle.",
      },
      {
        type: "listen-choose",
        audio: "We discussed the problem calmly and found a solution.",
        question: "How did they talk about the problem?",
        options: ["Hablaron con calma y encontraron una solución.", "Discutieron a gritos.", "Se pelearon y dejaron de hablarse.", "No hablaron del problema."],
        correctIndex: 0,
        explanation: "\"Discuss\" = «hablar de, tratar» a topic, usually calmly. An angry «discusión» is an \"argument\".",
      },
      {
        type: "dictation",
        audio: "They argued a lot, but they always made up.",
        explanation: "\"Argue\" = «discutir»; \"make up\" = «hacer las paces».",
      },
    ],
  },

  // ---------------------------------------------------------------------
  // Extra 3. Health words
  // ---------------------------------------------------------------------
  {
    slug: "en-b2-health-words-drill-1",
    optional: true,
    level: "EN-B2",
    number: 3,
    title: "Extra Practice: Health Words",
    summary: "Drill the health collocations: \"have a headache\", \"catch a cold\", \"take medicine\", \"a prescription\", \"recover from\", \"injury\" and \"wound\". Plus the traps: \"I have a cold\" vs \"I'm cold\", and «constipado» is NOT \"constipated\".",
    duration: "10 min",
    sections: [
      {
        heading: "Quick recap: colds, cold and «constipado»",
        body: [
          "\"I have a cold\" (or \"I've got a cold\") = «estoy resfriado / constipado». \"I'm cold\" = «tengo frío». You \"catch a cold\" («resfriarse, pillar un resfriado»).",
          "Careful: \"constipated\" means «estreñido», which is NOT what you want to tell your colleagues when you have a runny nose. «Estoy constipado» = \"I have a cold\".",
          "Pains: \"have a headache / stomachache / toothache / backache\" («dolor de cabeza / estómago / muelas / espalda»), or \"have a sore throat\" («dolor de garganta»). Use \"a\": *I have headache is wrong.",
        ],
        examples: [
          { es: "I think I'm catching a cold.", en: "Creo que me estoy resfriando." },
          { es: "Close the window. I'm cold.", en: "Cierra la ventana. Tengo frío." },
          { es: "She's got a terrible cold and can't come.", en: "Está muy constipada y no puede venir. (incorrecto: *constipated)" },
          { es: "I have a headache. Do you have any aspirin?", en: "Me duele la cabeza. ¿Tienes una aspirina?" },
          { es: "He's had a stomachache since lunch.", en: "Le duele el estómago desde la comida." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "You have a runny nose and you're sneezing. What do you say?",
            options: ["I have a cold.", "I'm cold.", "I'm constipated.", "I have cold."],
            correctIndex: 0,
            explanation: "\"I have a cold\" = «estoy resfriado». \"I'm cold\" = «tengo frío» and \"constipated\" = «estreñido».",
          },
        ],
      },
      {
        heading: "Quick recap: treatment and recovery",
        body: [
          "You \"take\" medicine or pills («tomar»), not *drink them (though you can \"drink\" a cough syrup). The doctor gives you a \"prescription\" («receta») for the \"pharmacy\" («farmacia»). You \"recover from\" an illness or \"get over\" it («recuperarse de»).",
          "An \"injury\" is damage to the body from an accident or sport («lesión»): \"a knee injury\"; the verb is \"injure\" or \"hurt\". A \"wound\" is a cut or hole in the skin, often from a weapon («herida»). Small everyday cuts are just \"cuts\".",
        ],
        examples: [
          { es: "Take two pills a day after meals.", en: "Tómate dos pastillas al día después de las comidas." },
          { es: "You need a prescription for these antibiotics.", en: "Necesitas receta para estos antibióticos." },
          { es: "He's still recovering from the operation.", en: "Todavía se está recuperando de la operación." },
          { es: "She missed the season because of a knee injury.", en: "Se perdió la temporada por una lesión de rodilla." },
          { es: "The nurse cleaned the wound.", en: "La enfermera limpió la herida." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "es-en",
            prompt: "Translate into English.",
            source: "¿Te has tomado la medicina?",
            answer: "Have you taken your medicine?",
            altAnswers: ["Did you take your medicine?", "Have you taken the medicine?", "Did you take the medicine?", "Have you taken your medication?", "Did you take your medication?"],
            explanation: "\"Take\" medicine, never *drink or *eat it.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "No puedo ir a la fiesta, estoy muy constipado.",
        answer: "I can't go to the party. I have a bad cold.",
        altAnswers: ["I can't go to the party. I've got a bad cold.", "I can't go to the party, I have a bad cold.", "I can't go to the party, I've got a bad cold.", "I can't go to the party. I have a terrible cold.", "I can't go to the party. I've got a terrible cold.", "I can't go to the party. I have a really bad cold.", "I can't go to the party; I have a bad cold.", "I can't go to the party because I have a bad cold.", "I can't go to the party because I've got a bad cold."],
        explanation: "«Constipado» = \"have a cold\". \"Constipated\" means «estreñido».",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "Put a coat on or you'll ___ a cold.",
        answer: "catch",
        altAnswers: ["get"],
        en: "Ponte un abrigo o [pillarás] un resfriado.",
        explanation: "\"Catch a cold\" = «resfriarse, pillar un resfriado».",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Tengo frío. ¿Puedes subir la calefacción?",
        answer: "I'm cold. Can you turn up the heating?",
        altAnswers: ["I'm cold. Can you turn the heating up?", "I'm cold. Could you turn up the heating?", "I'm cold. Could you turn the heating up?", "I'm cold. Can you turn up the heat?", "I'm cold. Can you turn the heat up?", "I'm cold. Could you turn up the heat?", "I'm cold. Could you turn the heat up?"],
        explanation: "«Tengo frío» = \"I'm cold\" (be + adjective), never *I have cold.",
      },
      {
        type: "multiple-choice",
        question: "Which sentence is correct?",
        options: ["I have a terrible headache.", "I have terrible headache.", "I have a terrible head pain.", "My head hurts me a lot."],
        correctIndex: 0,
        explanation: "\"Have a headache\", with \"a\". \"My head hurts\" also works, but without *me.",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "The doctor gave me a ___ for some antibiotics.",
        answer: "prescription",
        en: "El médico me dio una [receta] para unos antibióticos.",
        explanation: "A doctor's «receta» = \"prescription\". A cooking «receta» is a \"recipe\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Tardé un mes en recuperarme de la lesión.",
        answer: "It took me a month to recover from the injury.",
        altAnswers: ["It took me a month to get over the injury.", "It took me a month to recover from my injury.", "It took me a month to get over my injury."],
        explanation: "«Tardar» = \"it took me\" + time + \"to\". «Recuperarse de» = \"recover from\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Me duele mucho la garganta.",
        answer: "I have a really sore throat.",
        altAnswers: ["I have a very sore throat.", "I've got a really sore throat.", "I've got a very sore throat.", "My throat really hurts.", "My throat hurts a lot.", "My throat is really sore.", "My throat is very sore.", "I have a bad sore throat.", "I've got a bad sore throat."],
        explanation: "Throat pain is \"a sore throat\" (not *throatache). Or \"My throat hurts\", with no *me.",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "The soldier had a deep ___ in his leg.",
        answer: "wound",
        en: "El soldado tenía una [herida] profunda en la pierna.",
        explanation: "\"Wound\" (pronounced /wuːnd/) = «herida», especially from a weapon. A sports «lesión» is an \"injury\".",
      },
      {
        type: "matching",
        instructions: "Match the English with the Spanish.",
        pairs: [
          { left: "I have a cold.", right: "Estoy resfriado." },
          { left: "I'm cold.", right: "Tengo frío." },
          { left: "I'm constipated.", right: "Estoy estreñido." },
          { left: "a prescription", right: "una receta médica" },
          { left: "an injury", right: "una lesión" },
          { left: "a sore throat", right: "dolor de garganta" },
        ],
        explanation: "The first three are easy to mix up. Learn them together.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Se lesionó la espalda levantando una caja.",
        answer: "He injured his back lifting a box.",
        altAnswers: ["She injured her back lifting a box.", "He hurt his back lifting a box.", "She hurt her back lifting a box.", "He injured his back while lifting a box.", "She injured her back while lifting a box.", "He hurt his back while lifting a box.", "She hurt her back while lifting a box."],
        explanation: "«Lesionarse» = \"injure\" or \"hurt\". English uses a possessive with body parts: \"his back\", not *the back.",
      },
      {
        type: "multiple-choice",
        question: "Correct the learner: *You must drink these pills twice a day.",
        options: ["You must take these pills twice a day.", "You must eat these pills twice a day.", "You must take these pills two times for day.", "You must drink these pills two times a day."],
        correctIndex: 0,
        explanation: "\"Take\" pills or medicine. \"Twice a day\" = «dos veces al día».",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Ya está mucho mejor; se ha recuperado del todo.",
        answer: "She's much better now; she's fully recovered.",
        altAnswers: ["He's much better now; he's fully recovered.", "She's much better now. She's fully recovered.", "He's much better now. He's fully recovered.", "She's much better now; she's completely recovered.", "He's much better now; he's completely recovered.", "She's a lot better now; she's fully recovered.", "He's a lot better now; he's fully recovered.", "She's much better now; she has fully recovered.", "He's much better now; he has fully recovered."],
        explanation: "\"Recover\" can stand alone; \"fully\" or \"completely\" = «del todo».",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "Is there a ___ open near here? I need some cough syrup.",
        answer: "pharmacy",
        altAnswers: ["drugstore", "chemist's", "chemist"],
        en: "¿Hay alguna [farmacia] abierta por aquí? Necesito jarabe para la tos.",
        explanation: "«Farmacia» = \"pharmacy\" (also \"drugstore\" in the US, \"chemist's\" in the UK).",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Mi hijo tiene dolor de muelas desde ayer.",
        answer: "My son has had a toothache since yesterday.",
        altAnswers: ["My son's had a toothache since yesterday.", "My son has had toothache since yesterday."],
        explanation: "«Desde ayer» with a state that continues = present perfect: \"has had\", not *has since yesterday.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order.",
        words: ["I", "think", "I'm", "coming", "down", "with", "a", "cold"],
        translation: "Creo que me estoy resfriando.",
        explanation: "\"Come down with\" = start to get an illness («empezar a ponerse enfermo»).",
      },
      {
        type: "listen-choose",
        audio: "I've got a cold, so I'm staying in bed today.",
        question: "What's wrong with the speaker?",
        options: ["Está resfriado.", "Tiene frío.", "Está estreñido.", "Tiene una herida."],
        correctIndex: 0,
        explanation: "\"I've got a cold\" = «estoy resfriado».",
      },
      {
        type: "dictation",
        audio: "She's recovering from a serious knee injury.",
        explanation: "\"Recover from\" + illness or injury. \"Knee\" has a silent k.",
      },
    ],
  },

  // ---------------------------------------------------------------------
  // Extra 4. Dependent prepositions
  // ---------------------------------------------------------------------
  {
    slug: "en-b2-dependent-prepositions-drill-1",
    optional: true,
    level: "EN-B2",
    number: 4,
    title: "Extra Practice: Dependent Prepositions",
    summary: "Drill verb and adjective + preposition: \"depend on\", \"consist of\", \"married to\", \"good at\", \"afraid of\", \"interested in\", \"arrive in / at\". No more *depend of, *married with or *arrive to.",
    duration: "11 min",
    sections: [
      {
        heading: "Quick recap: verbs + preposition",
        body: [
          "Spanish prepositions don't translate one to one. \"Depend on\" («depender de»), \"consist of\" («consistir en»), \"rely on\" («contar con»), \"insist on\" («insistir en»), \"belong to\" («pertenecer a»), \"wait for\" («esperar a»), \"listen to\" («escuchar»), \"ask for\" («pedir»).",
          "\"Arrive\" never takes \"to\": \"arrive in\" a city or country, \"arrive at\" a building or place (the airport, the station, the hotel). \"Arrive home\" has no preposition at all.",
        ],
        examples: [
          { es: "It depends on the weather.", en: "Depende del tiempo. (incorrecto: *depends of)" },
          { es: "The test consists of three parts.", en: "El examen consta de tres partes." },
          { es: "She insisted on paying for dinner.", en: "Insistió en pagar la cena." },
          { es: "We arrived in Rome at midnight.", en: "Llegamos a Roma a medianoche. (incorrecto: *arrived to)" },
          { es: "We arrived at the hotel at one.", en: "Llegamos al hotel a la una." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "Correct the learner: *The price depends of the season.",
            options: ["The price depends on the season.", "The price depends from the season.", "The price depends in the season.", "The price depends to the season."],
            correctIndex: 0,
            explanation: "\"Depend on\", always. «Depender de» uses «de», but English uses \"on\".",
          },
        ],
      },
      {
        heading: "Quick recap: adjectives + preposition",
        body: [
          "\"Good / bad at\" a skill («bueno / malo en, para»), \"afraid / scared of\" («tener miedo de»), \"interested in\" («interesado en»), \"proud of\" («orgulloso de»), \"worried about\" («preocupado por»), \"similar to\" («parecido a»), \"different from\" («diferente de»), \"married to\" («casado con»).",
          "After a preposition, a verb takes -ing: \"good at cooking\", \"interested in learning\", \"afraid of flying\". Never the infinitive: *good at cook, *interested in learn.",
        ],
        examples: [
          { es: "She's really good at languages.", en: "Se le dan muy bien los idiomas." },
          { es: "I'm afraid of flying.", en: "Me da miedo volar." },
          { es: "Are you interested in joining the club?", en: "¿Te interesa unirte al club?" },
          { es: "We're very proud of you.", en: "Estamos muy orgullosos de ti." },
          { es: "Your phone is very similar to mine.", en: "Tu móvil se parece mucho al mío." },
        ],
        checkpoint: [
          {
            type: "fill-blank",
            prompt: "Write the bold words in English.",
            sentence: "My parents are always worried ___ money.",
            answer: "about",
            en: "Mis padres siempre están preocupados [por] el dinero.",
            explanation: "\"Worried about\", not *worried for (that means fearing for someone's safety).",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Mi felicidad no depende del dinero.",
        answer: "My happiness doesn't depend on money.",
        altAnswers: ["My happiness does not depend on money."],
        explanation: "\"Depend on\". And \"money\" in general takes no article.",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "The meal consisted ___ soup, fish and dessert.",
        answer: "of",
        en: "La comida consistió [en] sopa, pescado y postre.",
        explanation: "«Consistir en» = \"consist of\". Not *consist in for the parts of something.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "¿A qué hora llegaste al aeropuerto?",
        answer: "What time did you arrive at the airport?",
        altAnswers: ["What time did you get to the airport?", "When did you arrive at the airport?", "When did you get to the airport?"],
        explanation: "A building or place: \"arrive at\". Or use \"get to\", which is very common. Never *arrive to.",
      },
      {
        type: "multiple-choice",
        question: "Which sentence is correct?",
        options: ["We arrived in Mexico on Tuesday.", "We arrived to Mexico on Tuesday.", "We arrived at Mexico on Tuesday.", "We arrived Mexico on Tuesday."],
        correctIndex: 0,
        explanation: "A city or country: \"arrive in\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Mi hermana es muy buena en matemáticas.",
        answer: "My sister is very good at math.",
        altAnswers: ["My sister is really good at math.", "My sister is very good at maths.", "My sister is really good at maths.", "My sister is very good at mathematics.", "My sister is really good at mathematics."],
        explanation: "\"Good at\" + subject or skill. Not *good in or *good for.",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "Who does this bag ___?",
        answer: "belong to",
        en: "¿A quién [pertenece] esta bolsa?",
        explanation: "\"Belong to\" = «pertenecer a, ser de». The preposition goes at the end of the question.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Estoy muy orgulloso de mis alumnos.",
        answer: "I'm very proud of my students.",
        altAnswers: ["I'm really proud of my students.", "I'm so proud of my students.", "I'm very proud of my pupils.", "I'm really proud of my pupils."],
        explanation: "\"Proud of\" = «orgulloso de».",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "We ___ the bus for forty minutes.",
        answer: "waited for",
        en: "[Esperamos] el autobús durante cuarenta minutos.",
        explanation: "\"Wait for\" + person or thing. Spanish «esperar el autobús» has no preposition, but English needs \"for\".",
      },
      {
        type: "matching",
        instructions: "Match the English with the Spanish.",
        pairs: [
          { left: "depend on", right: "depender de" },
          { left: "consist of", right: "consistir en" },
          { left: "insist on", right: "insistir en" },
          { left: "married to", right: "casado con" },
          { left: "afraid of", right: "tener miedo de" },
          { left: "good at", right: "bueno en, para" },
        ],
        explanation: "Learn each verb or adjective together with its preposition.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "No me interesa ver esa película.",
        answer: "I'm not interested in seeing that movie.",
        altAnswers: ["I'm not interested in watching that movie.", "I'm not interested in seeing that film.", "I'm not interested in watching that film.", "I am not interested in seeing that movie.", "I am not interested in watching that movie."],
        explanation: "\"Interested in\" + -ing. Never *interested in see or *interested to see here.",
      },
      {
        type: "multiple-choice",
        question: "Correct the learner: *My best friend is married with a doctor.",
        options: ["My best friend is married to a doctor.", "My best friend is married a doctor.", "My best friend is married for a doctor.", "My best friend is marry with a doctor."],
        correctIndex: 0,
        explanation: "\"Be married to\" + person. Spanish «con» becomes \"to\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Insistió en acompañarme a casa.",
        answer: "He insisted on walking me home.",
        altAnswers: ["She insisted on walking me home.", "He insisted on taking me home.", "She insisted on taking me home.", "He insisted on coming home with me.", "She insisted on coming home with me.", "He insisted on going home with me.", "She insisted on going home with me.", "He insisted on driving me home.", "She insisted on driving me home."],
        explanation: "\"Insist on\" + -ing. \"Walk someone home\" = «acompañar a alguien a casa» on foot. No preposition before \"home\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "His new song is very different ___ his old ones.",
        answer: "from",
        altAnswers: ["to", "than"],
        en: "Su nueva canción es muy diferente [de] las antiguas.",
        explanation: "\"Different from\" is the safest choice everywhere; \"different to\" (UK) and \"different than\" (US) are also used.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Puedes contar conmigo.",
        answer: "You can count on me.",
        altAnswers: ["You can rely on me.", "You can depend on me."],
        explanation: "«Contar con» (trust) = \"count on\" / \"rely on\". Never *count with.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order.",
        words: ["She's", "scared", "of", "driving", "at", "night"],
        translation: "Le da miedo conducir de noche.",
        altOrders: [["At", "night", "she's", "scared", "of", "driving"]],
        explanation: "\"Scared of\" + -ing: \"scared of driving\". «De noche» = \"at night\".",
      },
      {
        type: "listen-choose",
        audio: "We finally arrived home at three in the morning.",
        question: "When did they get home?",
        options: ["A las tres de la madrugada.", "A las tres de la tarde.", "A las trece horas.", "Por la mañana temprano, a las seis."],
        correctIndex: 0,
        explanation: "\"Arrive home\" has no preposition. \"Three in the morning\" = «las tres de la madrugada».",
      },
      {
        type: "dictation",
        audio: "It all depends on how much time we have.",
        explanation: "\"Depend on\" + a clause with \"how much\", \"what\", \"whether\", etc.",
      },
    ],
  },

  // ---------------------------------------------------------------------
  // Extra 5. Everyday idioms
  // ---------------------------------------------------------------------
  {
    slug: "en-b2-idioms-drill-1",
    optional: true,
    level: "EN-B2",
    number: 5,
    title: "Extra Practice: Everyday Idioms",
    summary: "Drill common B2 idioms and their Spanish equivalents: \"a piece of cake\", \"break the ice\", \"under the weather\", \"once in a blue moon\", \"cost an arm and a leg\", \"sleep on it\" and \"rain cats and dogs\". Don't translate Spanish idioms word for word.",
    duration: "10 min",
    sections: [
      {
        heading: "Quick recap: idioms with Spanish equivalents",
        body: [
          "Idioms rarely translate word for word. «Ser pan comido» is \"be a piece of cake\" (*be eaten bread means nothing). «Costar un ojo de la cara» is \"cost an arm and a leg\". «Romper el hielo» is one of the few that match: \"break the ice\".",
          "\"Under the weather\" = a bit ill («pachucho, no encontrarse muy bien»). \"Once in a blue moon\" = very rarely («de higos a brevas, muy de vez en cuando»). \"Sleep on it\" = wait until tomorrow to decide («consultarlo con la almohada»). \"It's raining cats and dogs\" = «llueve a cántaros».",
        ],
        examples: [
          { es: "The exam was a piece of cake.", en: "El examen fue pan comido." },
          { es: "That bag must have cost an arm and a leg.", en: "Ese bolso habrá costado un ojo de la cara." },
          { es: "I'm feeling a bit under the weather today.", en: "Hoy estoy un poco pachucho." },
          { es: "We only eat out once in a blue moon.", en: "Solo comemos fuera de higos a brevas." },
          { es: "Don't decide now. Sleep on it.", en: "No decidas ahora. Consúltalo con la almohada." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "«Esto es pan comido.» Which is the natural English?",
            options: ["This is a piece of cake.", "This is eaten bread.", "This is a piece of bread.", "This is a cake walk of bread."],
            correctIndex: 0,
            explanation: "«Ser pan comido» = \"be a piece of cake\" (very easy). Never translate idioms word for word.",
          },
        ],
      },
      {
        heading: "Quick recap: using idioms naturally",
        body: [
          "Idioms are fixed: don't change the words. It's \"an arm and a leg\", not *a leg and an arm, and \"a piece of cake\", not *a cake piece. You can change the verb tense: \"It cost an arm and a leg\", \"We broke the ice\".",
          "Most of these are informal. Use them when chatting, not in a formal report.",
        ],
        examples: [
          { es: "She asked about his trip to break the ice.", en: "Le preguntó por su viaje para romper el hielo." },
          { es: "It's raining cats and dogs. Take an umbrella.", en: "Está lloviendo a cántaros. Llévate un paraguas." },
          { es: "Fixing the bike was a piece of cake.", en: "Arreglar la bici fue pan comido." },
        ],
        checkpoint: [
          {
            type: "fill-blank",
            prompt: "Write the bold words in English.",
            sentence: "My grandparents visit us ___.",
            answer: "once in a blue moon",
            altAnswers: ["very rarely", "rarely", "hardly ever"],
            en: "Mis abuelos nos visitan [de higos a brevas].",
            explanation: "\"Once in a blue moon\" = very rarely. The idiom is fixed: always \"blue\", and it goes at the end.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "La reparación del coche nos costó un ojo de la cara.",
        answer: "The car repair cost us an arm and a leg.",
        altAnswers: ["Repairing the car cost us an arm and a leg.", "The repair on the car cost us an arm and a leg.", "Fixing the car cost us an arm and a leg.", "The car repairs cost us an arm and a leg."],
        explanation: "«Costar un ojo de la cara» = \"cost an arm and a leg\". \"Cost\" is irregular: cost, cost, cost.",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "I won't go to the gym today. I'm a bit ___.",
        answer: "under the weather",
        altAnswers: ["ill", "sick", "unwell"],
        en: "Hoy no voy al gimnasio. Estoy un poco [pachucho].",
        explanation: "\"Under the weather\" = slightly ill.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Para él, aprender idiomas es pan comido.",
        answer: "For him, learning languages is a piece of cake.",
        altAnswers: ["Learning languages is a piece of cake for him.", "For him learning languages is a piece of cake."],
        explanation: "«Pan comido» = \"a piece of cake\". A verb as subject takes -ing: \"Learning languages\".",
      },
      {
        type: "multiple-choice",
        question: "Your friend says: \"I see my cousins once in a blue moon.\" How often does she see them?",
        options: ["Muy de vez en cuando.", "Una vez al mes.", "Cada luna llena.", "Todos los días."],
        correctIndex: 0,
        explanation: "\"Once in a blue moon\" = very rarely («de higos a brevas»).",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "No sabía qué decir para romper el hielo.",
        answer: "I didn't know what to say to break the ice.",
        explanation: "«Romper el hielo» = \"break the ice\": one idiom that matches Spanish exactly. «Para» + verb = \"to\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "Take your time. Why don't you ___?",
        answer: "sleep on it",
        en: "Tómate tu tiempo. ¿Por qué no lo [consultas con la almohada]?",
        explanation: "\"Sleep on it\" = wait a night before deciding.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Llovía a cántaros y no teníamos paraguas.",
        answer: "It was raining cats and dogs and we didn't have an umbrella.",
        altAnswers: ["It was raining cats and dogs, and we didn't have an umbrella.", "It was raining cats and dogs and we didn't have umbrellas.", "It was raining cats and dogs, and we didn't have umbrellas.", "It was raining cats and dogs and we didn't have any umbrellas.", "It was raining cats and dogs and we had no umbrella.", "It was pouring and we didn't have an umbrella.", "It was pouring, and we didn't have an umbrella.", "It was raining cats and dogs and we hadn't got an umbrella."],
        explanation: "«Llover a cántaros» = \"rain cats and dogs\" (or simply \"pour\"). Weather needs the subject \"it\".",
      },
      {
        type: "matching",
        instructions: "Match the English with the Spanish.",
        pairs: [
          { left: "a piece of cake", right: "pan comido" },
          { left: "cost an arm and a leg", right: "costar un ojo de la cara" },
          { left: "under the weather", right: "pachucho" },
          { left: "once in a blue moon", right: "de higos a brevas" },
          { left: "sleep on it", right: "consultarlo con la almohada" },
          { left: "rain cats and dogs", right: "llover a cántaros" },
        ],
        explanation: "Only \"break the ice\" matches Spanish word for word; most idioms need a completely different image.",
      },
      {
        type: "multiple-choice",
        question: "Which sentence is correct?",
        options: ["Those concert tickets cost an arm and a leg.", "Those concert tickets cost an eye of the face.", "Those concert tickets cost a leg and an arm.", "Those concert tickets cost an arm and leg."],
        correctIndex: 0,
        explanation: "Idioms are fixed: always \"an arm and a leg\", in that order and with both articles.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Mi padre cocina muy de vez en cuando.",
        answer: "My father cooks once in a blue moon.",
        altAnswers: ["My dad cooks once in a blue moon.", "My father cooks very rarely.", "My dad cooks very rarely.", "My father very rarely cooks.", "My dad very rarely cooks.", "My father hardly ever cooks.", "My dad hardly ever cooks.", "My father only cooks once in a blue moon.", "My dad only cooks once in a blue moon."],
        explanation: "\"Once in a blue moon\" goes at the end of the sentence. \"Very rarely\" or \"hardly ever\" are the neutral options.",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "The first day was awkward, but a game helped to ___ the ice.",
        answer: "break",
        en: "El primer día fue incómodo, pero un juego ayudó a [romper] el hielo.",
        explanation: "\"Break the ice\" = «romper el hielo».",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Hoy no me encuentro muy bien; me voy a quedar en casa.",
        answer: "I'm feeling a bit under the weather today; I'm going to stay at home.",
        altAnswers: ["I'm a bit under the weather today; I'm going to stay at home.", "I'm feeling a bit under the weather today, so I'm going to stay home.", "I'm feeling a bit under the weather today. I'm going to stay at home.", "I'm feeling a bit under the weather today. I'm going to stay home.", "I'm feeling under the weather today; I'm going to stay at home.", "I'm feeling under the weather today. I'm going to stay home.", "I'm not feeling very well today; I'm going to stay at home.", "I'm not feeling very well today. I'm going to stay home.", "I don't feel very well today; I'm going to stay at home.", "I don't feel very well today. I'm going to stay home.", "I'm not feeling very well today, so I'm going to stay home.", "I'm feeling a bit under the weather today; I'm going to stay home."],
        explanation: "\"Under the weather\" is the idiomatic option; \"not feeling very well\" is the neutral one.",
      },
      {
        type: "multiple-choice",
        question: "Which situation fits \"break the ice\"?",
        options: ["Telling a funny story at the start of a meeting with strangers.", "Breaking a glass by accident.", "Deciding something after one night.", "Paying a lot for something."],
        correctIndex: 0,
        explanation: "\"Break the ice\" = make people feel relaxed when they first meet.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "El examen de conducir no fue pan comido: suspendí dos veces.",
        answer: "The driving test wasn't a piece of cake: I failed twice.",
        altAnswers: ["The driving test wasn't a piece of cake. I failed twice.", "The driving test was no piece of cake: I failed twice.", "The driving test was no piece of cake. I failed twice.", "The driving test wasn't a piece of cake: I failed it twice.", "The driving test wasn't a piece of cake. I failed it twice.", "My driving test wasn't a piece of cake: I failed twice.", "My driving test wasn't a piece of cake. I failed twice."],
        explanation: "\"A piece of cake\" works in the negative too. «Suspender» = \"fail\".",
      },
      {
        type: "word-order",
        prompt: "Put the words in order.",
        words: ["Let", "me", "sleep", "on", "it", "first"],
        translation: "Déjame consultarlo primero con la almohada.",
        explanation: "\"Sleep on it\" = wait until the next day to decide.",
      },
      {
        type: "listen-choose",
        audio: "Their new house must have cost an arm and a leg.",
        question: "What does the speaker think about the house?",
        options: ["Que les costó carísima.", "Que la compraron muy barata.", "Que la construyeron ellos mismos.", "Que tiene muchas habitaciones."],
        correctIndex: 0,
        explanation: "\"Cost an arm and a leg\" = be very expensive. \"Must have cost\" = a deduction about the past.",
      },
      {
        type: "speak",
        text: "Don't worry, it's a piece of cake!",
        tip: "Link \"piece\" and \"of\" together with no pause, and stress \"cake\".",
        explanation: "\"It's a piece of cake\" = it's very easy.",
      },
    ],
  },

  // ---------------------------------------------------------------------
  // Extra 6. Prefixes
  // ---------------------------------------------------------------------
  {
    slug: "en-b2-word-formation-prefixes-drill-1",
    optional: true,
    level: "EN-B2",
    number: 6,
    title: "Extra Practice: Prefixes",
    summary: "Drill the negative prefixes \"un-\", \"in-\", \"im-\", \"il-\", \"ir-\" and \"dis-\", and the meaning prefixes \"mis-\", \"over-\", \"under-\" and \"re-\". Goodbye to *unpossible, *inresponsible and *dispossible.",
    duration: "11 min",
    sections: [
      {
        heading: "Quick recap: negative prefixes",
        body: [
          "\"Un-\" is the most common: \"unhappy\", \"unfair\", \"unusual\", \"unlikely\", \"unemployed\". \"Dis-\" goes with some adjectives and verbs: \"dishonest\", \"disagree\", \"dislike\", \"disappear\".",
          "\"In-\" changes before some letters: \"im-\" before p and m (\"impossible\", \"impatient\", \"immature\"), \"il-\" before l (\"illegal\", \"illogical\") and \"ir-\" before r (\"irresponsible\", \"irregular\"). Spanish does the same («imposible», «ilegal», «irresponsable»), so your Spanish instinct often helps here. *Unpossible and *inresponsible are wrong.",
          "But Spanish doesn't always match: «desconocido» is \"unknown\", «desempleado» is \"unemployed\", «incómodo» is \"uncomfortable\", and «infeliz» is \"unhappy\".",
        ],
        examples: [
          { es: "It's impossible to sleep with this noise.", en: "Es imposible dormir con este ruido. (incorrecto: *unpossible)" },
          { es: "Parking here is illegal.", en: "Aparcar aquí es ilegal." },
          { es: "That was a really irresponsible thing to do.", en: "Eso fue muy irresponsable. (incorrecto: *inresponsible)" },
          { es: "These shoes are really uncomfortable.", en: "Estos zapatos son muy incómodos." },
          { es: "I disagree with you.", en: "No estoy de acuerdo contigo." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "Which word is the opposite of \"patient\"?",
            options: ["impatient", "unpatient", "inpatient", "dispatient"],
            correctIndex: 0,
            explanation: "\"In-\" becomes \"im-\" before p: \"impatient\". (An \"inpatient\" is a person who stays in hospital.)",
          },
        ],
      },
      {
        heading: "Quick recap: mis-, over-, under-, re-",
        body: [
          "\"Mis-\" = wrongly: \"misunderstand\" («entender mal»), \"mispronounce\", \"misspell\". \"Over-\" = too much: \"overcooked\", \"oversleep\" («quedarse dormido»), \"overpriced\". \"Under-\" = not enough: \"undercooked\", \"underpaid\", \"underestimate\".",
          "\"Re-\" = again: \"rewrite\", \"rebuild\", \"reread\", \"restart\". Spanish often says «volver a» + verb where English uses \"re-\": «volver a leer» = \"reread\" (or \"read again\").",
        ],
        examples: [
          { es: "Sorry, I misunderstood the question.", en: "Perdona, entendí mal la pregunta." },
          { es: "People often mispronounce my name.", en: "La gente pronuncia mal mi nombre a menudo." },
          { es: "The pasta is overcooked.", en: "La pasta está pasada." },
          { es: "The chicken is undercooked. It's still pink.", en: "El pollo está poco hecho. Todavía está rosa." },
          { es: "I reread the email three times before sending it.", en: "Releí el correo tres veces antes de enviarlo." },
        ],
        checkpoint: [
          {
            type: "fill-blank",
            prompt: "Write the bold words in English.",
            sentence: "Be careful, you've ___ my surname. It has two t's.",
            answer: "misspelled",
            altAnswers: ["misspelt"],
            en: "Cuidado, has [escrito mal] mi apellido. Tiene dos tes.",
            explanation: "\"Mis-\" + \"spell\" = \"misspell\", with double s.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Es imposible terminar todo esto hoy.",
        answer: "It's impossible to finish all this today.",
        altAnswers: ["It's impossible to finish all of this today.", "It is impossible to finish all this today.", "It's impossible to get all this done today."],
        explanation: "\"Im-\" before p: \"impossible\". Never *unpossible.",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "Leaving a child alone in the car is completely ___.",
        answer: "irresponsible",
        en: "Dejar a un niño solo en el coche es totalmente [irresponsable].",
        explanation: "\"Ir-\" before r: \"irresponsible\", with -ible.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Mi tío lleva un año desempleado.",
        answer: "My uncle has been unemployed for a year.",
        altAnswers: ["My uncle has been out of work for a year.", "My uncle's been unemployed for a year.", "My uncle's been out of work for a year.", "My uncle has been jobless for a year."],
        explanation: "«Desempleado» = \"unemployed\" (un-, not *dis-). «Lleva un año» = \"has been... for a year\".",
      },
      {
        type: "multiple-choice",
        question: "Correct the learner: *It's inlegal to smoke in restaurants here.",
        options: ["It's illegal to smoke in restaurants here.", "It's unlegal to smoke in restaurants here.", "It's dislegal to smoke in restaurants here.", "It's ilegal to smoke in restaurants here."],
        correctIndex: 0,
        explanation: "\"Il-\" before l, and English keeps both l's: \"illegal\" (Spanish «ilegal» has only one).",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "I ___ and missed my first class.",
        answer: "overslept",
        en: "[Me quedé dormido] y me perdí la primera clase.",
        explanation: "\"Oversleep\" (past \"overslept\") = sleep too long («quedarse dormido»).",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "No me gusta nada su actitud.",
        answer: "I really dislike his attitude.",
        altAnswers: ["I really dislike her attitude.", "I don't like his attitude at all.", "I don't like her attitude at all.", "I really don't like his attitude.", "I really don't like her attitude.", "I dislike his attitude.", "I dislike her attitude.", "I really dislike their attitude.", "I don't like their attitude at all."],
        explanation: "\"Dislike\" = «no gustar». \"I don't like... at all\" is the most natural for «nada».",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Este restaurante es demasiado caro para lo que es.",
        answer: "This restaurant is overpriced.",
        altAnswers: ["This restaurant is too expensive for what it is.", "This restaurant is really overpriced.", "This restaurant is very overpriced.", "This restaurant is overpriced for what it is."],
        explanation: "\"Over-\" = too much: \"overpriced\" = more expensive than it should be.",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "It's very ___ for her to be late. She's always on time.",
        answer: "unusual",
        en: "Es muy [raro] que llegue tarde. Siempre es puntual.",
        explanation: "\"Unusual\" = «raro, poco habitual». \"Rare\" is more for things that seldom exist or happen.",
      },
      {
        type: "matching",
        instructions: "Match the English with the Spanish.",
        pairs: [
          { left: "impossible", right: "imposible" },
          { left: "illegal", right: "ilegal" },
          { left: "irregular", right: "irregular" },
          { left: "unknown", right: "desconocido" },
          { left: "uncomfortable", right: "incómodo" },
          { left: "disagree", right: "no estar de acuerdo" },
        ],
        explanation: "Some prefixes match Spanish (im-, il-, ir-), but «des-» and «in-» often become \"un-\" in English.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Creo que me has entendido mal.",
        answer: "I think you've misunderstood me.",
        altAnswers: ["I think you misunderstood me.", "I think you've misunderstood.", "I think you misunderstood."],
        explanation: "«Entender mal» = \"misunderstand\". Not *understand bad.",
      },
      {
        type: "multiple-choice",
        question: "Which word means «inmaduro»?",
        options: ["immature", "unmature", "inmature", "dismature"],
        correctIndex: 0,
        explanation: "\"In-\" becomes \"im-\" before m: \"immature\", with double m.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Tuvimos que volver a empezar el proyecto desde cero.",
        answer: "We had to restart the project from scratch.",
        altAnswers: ["We had to start the project again from scratch.", "We had to start the project over from scratch.", "We had to start the project from scratch again.", "We had to start over from scratch.", "We had to restart the project from zero.", "We had to start the project again from zero."],
        explanation: "«Volver a» + verb = \"re-\" + verb, or verb + \"again\". «Desde cero» = \"from scratch\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "The steak was ___, so I sent it back to the kitchen.",
        answer: "undercooked",
        altAnswers: ["underdone", "raw"],
        en: "El filete estaba [poco hecho], así que lo devolví a la cocina.",
        explanation: "\"Under-\" = not enough: \"undercooked\". Too much is \"overcooked\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Es poco probable que llueva mañana.",
        answer: "It's unlikely to rain tomorrow.",
        altAnswers: ["It's unlikely that it will rain tomorrow.", "It's unlikely it will rain tomorrow.", "It probably won't rain tomorrow.", "Rain is unlikely tomorrow.", "It isn't likely to rain tomorrow."],
        explanation: "«Poco probable» = \"unlikely\". Spanish subjunctive «llueva» becomes \"to rain\" or \"that it will rain\".",
      },
      {
        type: "word-order",
        prompt: "Put the words in order.",
        words: ["Never", "underestimate", "your", "opponents"],
        translation: "Nunca subestimes a tus rivales.",
        explanation: "\"Under-\" + \"estimate\" = «subestimar». The Spanish «a» before a person has no equivalent in English.",
      },
      {
        type: "listen-choose",
        audio: "The keys didn't just disappear. Someone must have moved them.",
        question: "What does the speaker think?",
        options: ["Que alguien cambió las llaves de sitio.", "Que las llaves se perdieron solas.", "Que nadie tocó las llaves.", "Que las llaves están rotas."],
        correctIndex: 0,
        explanation: "\"Disappear\" = «desaparecer» (dis- + appear). \"Must have moved\" = a confident deduction.",
      },
      {
        type: "dictation",
        audio: "It's unfair to judge people you don't know.",
        explanation: "\"Unfair\" = «injusto». Note un-, not *in-: *infair doesn't exist.",
      },
    ],
  },
];
