// Synced from cheneygross-afk/lengo:src/lib/lessons/en-c2-u25-extra.ts by scripts/sync-content.mjs -- edit it there, not here.
import type { Lesson } from "./types";

// Extra practice (optional) lessons for EN-C2 unit u25 (writing history).
// Drill-focused: a short recap, then lots of exercises.

export const EN_C2_U25_EXTRA: Lesson[] = [
  {
    slug: "en-c2-participle-clauses-drill-1",
    optional: true,
    level: "EN-C2",
    number: 1,
    title: "Extra Practice: Participle Clauses in Historical Writing",
    summary: "Drill present, past and perfect participle clauses (\"Having crossed the Alps...\", \"Founded in 1610...\") in historical sentences, fix dangling participles, and replace *After to cross with \"After crossing\".",
    duration: "12 min",
    sections: [
      {
        heading: "Quick recap: three kinds of participle clause",
        body: [
          "Participle clauses compress two sentences into one, and history writing uses them constantly. Present participle (-ing) for an action at the same time or a reason: \"Sensing danger, the envoy fled.\" Past participle for a passive meaning: \"Founded in 1610, the city grew rapidly.\" Perfect participle (\"having\" + participle) for an action completed before the main one: \"Having crossed the Alps, the army descended into Italy.\"",
          "Spanish has similar structures («Fundada en 1610, la ciudad...», «Tras cruzar los Alpes...»), but learners often translate «tras + infinitivo» or «después de + infinitivo» as *After to cross. English uses \"After crossing\" or \"Having crossed\", never \"to\" after a preposition.",
          "A passive perfect participle is \"having been\" + participle: \"Having been warned of the attack, the garrison was ready.\"",
        ],
        examples: [
          {
            es: "Sensing danger, the envoy left the city that night.",
            en: "Al presentir el peligro, el enviado abandonó la ciudad esa misma noche.",
          },
          {
            es: "Founded in 1610, the city grew rapidly.",
            en: "Fundada en 1610, la ciudad creció rápidamente.",
          },
          {
            es: "Having crossed the Alps, the army descended into Italy.",
            en: "Tras cruzar los Alpes, el ejército descendió a Italia.",
          },
          {
            es: "After crossing the border, the refugees were taken to a camp.",
            en: "Después de cruzar la frontera, los refugiados fueron llevados a un campo. (incorrecto: *After to cross)",
          },
          {
            es: "Having been warned of the attack, the garrison was ready.",
            en: "Advertida del ataque, la guarnición estaba preparada.",
          },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "es-en",
            prompt: "Translate into English.",
            source: "Tras firmar el acuerdo, los dos líderes dieron una rueda de prensa.",
            answer: "Having signed the agreement, the two leaders gave a press conference.",
            altAnswers: [
              "Having signed the agreement, the two leaders held a press conference.",
              "After signing the agreement, the two leaders gave a press conference.",
              "After signing the agreement, the two leaders held a press conference.",
              "After they had signed the agreement, the two leaders gave a press conference.",
              "After they had signed the agreement, the two leaders held a press conference.",
              "After they signed the agreement, the two leaders gave a press conference.",
              "After they signed the agreement, the two leaders held a press conference.",
              "Once they had signed the agreement, the two leaders gave a press conference.",
              "Once they had signed the agreement, the two leaders held a press conference.",
              "Having signed the agreement, both leaders gave a press conference.",
              "Having signed the agreement, both leaders held a press conference.",
              "After signing the agreement, both leaders gave a press conference.",
              "After signing the agreement, both leaders held a press conference.",
              "After they had signed the agreement, both leaders gave a press conference.",
              "After they had signed the agreement, both leaders held a press conference.",
              "After they signed the agreement, both leaders gave a press conference.",
              "After they signed the agreement, both leaders held a press conference.",
              "Once they had signed the agreement, both leaders gave a press conference.",
              "Once they had signed the agreement, both leaders held a press conference.",
            ],
            explanation: "«Tras + infinitivo» = \"Having\" + participle or \"After\" + -ing. Never *After to sign.",
          },
          {
            type: "fill-blank",
            prompt: "Write the bold words in English.",
            sentence: "___ in 1503, the tower is the oldest building in the town.",
            answer: "Built",
            altAnswers: ["Erected", "Constructed", "Completed"],
            en: "[Construida] en 1503, la torre es el edificio más antiguo de la ciudad.",
            explanation: "A past participle clause gives a passive meaning: the tower was built.",
          },
        ],
      },
      {
        heading: "Quick recap: dangling participles",
        body: [
          "The implied subject of a participle clause must be the subject of the main clause. *Having crossed the river, the weather changed suggests that the weather crossed the river. Fix it by making the right noun the subject (\"Having crossed the river, the troops noticed the weather changing\") or by using a full clause (\"After the troops had crossed the river, the weather changed\").",
          "Spanish tolerates this more, because the verb ending often makes the subject clear («Cruzado el río, cambió el tiempo»). In English the reader attaches the participle to the very next noun.",
          "Dangling participles are a classic examiner's target in C2 writing. Check every sentence that begins with an -ing or -ed clause: who is doing or receiving the action?",
        ],
        examples: [
          {
            es: "After the troops had crossed the river, the weather changed.",
            en: "Cuando las tropas cruzaron el río, cambió el tiempo. (incorrecto: *Having crossed the river, the weather changed)",
          },
          {
            es: "Walking through the old town, I noticed the medieval walls.",
            en: "Paseando por el casco antiguo, me fijé en las murallas medievales.",
          },
          {
            es: "Exhausted by the long siege, the defenders finally surrendered.",
            en: "Agotados por el largo asedio, los defensores acabaron rindiéndose.",
          },
          {
            es: "When we arrived at the fortress, the gates were locked.",
            en: "Al llegar a la fortaleza, las puertas estaban cerradas. (incorrecto: *Arriving at the fortress, the gates were locked)",
          },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "Which sentence is correct?",
            options: [
              "Having lost the election, the president resigned.",
              "Having lost the election, the resignation of the president followed.",
              "Having lost the election, it was time for the president to resign.",
              "Having lost the election, a new government was formed by the president.",
            ],
            correctIndex: 0,
            explanation: "The president lost the election, so \"the president\" must be the subject of the main clause. In the others the participle dangles.",
          },
          {
            type: "multiple-choice",
            question: "*Written in Latin, few people could read the decree. What is the best correction?",
            options: [
              "Written in Latin, the decree could be read by few people.",
              "Writing in Latin, few people could read the decree.",
              "Having written in Latin, few people could read the decree.",
              "Written in Latin, few people could have read the decree.",
            ],
            correctIndex: 0,
            explanation: "The decree was written in Latin, so \"the decree\" must be the subject after the comma.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Derrotado en la batalla, el rey huyó a Francia.",
        answer: "Defeated in battle, the king fled to France.",
        altAnswers: [
          "Defeated in battle, the king escaped to France.",
          "Defeated in the battle, the king fled to France.",
          "Defeated in the battle, the king escaped to France.",
          "Having been defeated in battle, the king fled to France.",
          "Having been defeated in battle, the king escaped to France.",
          "Having been defeated in the battle, the king fled to France.",
          "Having been defeated in the battle, the king escaped to France.",
          "Having lost the battle, the king fled to France.",
          "Having lost the battle, the king escaped to France.",
        ],
        explanation: "A past participle clause (\"Defeated\") = passive meaning. The king was defeated, so \"the king\" is the subject.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Después de conquistar la ciudad, los invasores levantaron una fortaleza.",
        answer: "After conquering the city, the invaders built a fortress.",
        altAnswers: [
          "After conquering the city, the invaders erected a fortress.",
          "After conquering the city, the invaders raised a fortress.",
          "After conquering the city, the invaders constructed a fortress.",
          "Having conquered the city, the invaders built a fortress.",
          "Having conquered the city, the invaders erected a fortress.",
          "Having conquered the city, the invaders raised a fortress.",
          "Having conquered the city, the invaders constructed a fortress.",
          "After they had conquered the city, the invaders built a fortress.",
          "After they had conquered the city, the invaders erected a fortress.",
          "After they had conquered the city, the invaders raised a fortress.",
          "After they had conquered the city, the invaders constructed a fortress.",
          "After they conquered the city, the invaders built a fortress.",
          "After they conquered the city, the invaders erected a fortress.",
          "After they conquered the city, the invaders raised a fortress.",
          "After they conquered the city, the invaders constructed a fortress.",
          "Once they had conquered the city, the invaders built a fortress.",
          "Once they had conquered the city, the invaders erected a fortress.",
          "Once they had conquered the city, the invaders raised a fortress.",
          "Once they had conquered the city, the invaders constructed a fortress.",
        ],
        explanation: "\"After\" + -ing or \"Having\" + participle. *After to conquer is the classic error: after a preposition English uses -ing.",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "___ to the throne at the age of twelve, the young king relied on his advisers.",
        answer: "Coming",
        altAnswers: ["Having come", "Succeeding", "Having succeeded"],
        en: "[Al llegar] al trono con doce años, el joven rey dependía de sus consejeros.",
        explanation: "Present participle for an action at the same time as the main clause or giving the background.",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "___ the city walls, the rebels opened the gates from inside.",
        answer: "Having climbed",
        altAnswers: ["After climbing", "Having scaled", "After scaling", "Climbing", "Scaling"],
        en: "[Tras escalar] las murallas de la ciudad, los rebeldes abrieron las puertas desde dentro.",
        explanation: "The perfect participle shows that the climbing was completed before the gates were opened.",
      },
      {
        type: "multiple-choice",
        question: "Which sentence contains a dangling participle?",
        options: [
          "Arriving in Rome, the cathedral bells were ringing.",
          "Arriving in Rome, the pilgrims heard the cathedral bells.",
          "When the pilgrims arrived in Rome, the bells were ringing.",
          "Having arrived in Rome, the pilgrims went to the cathedral.",
        ],
        correctIndex: 0,
        explanation: "The bells did not arrive in Rome. The subject after the comma must be the one who arrives.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Al no recibir respuesta, el embajador abandonó la corte.",
        answer: "Receiving no reply, the ambassador left the court.",
        altAnswers: [
          "Having received no reply, the ambassador left the court.",
          "Not receiving a reply, the ambassador left the court.",
          "Having had no reply, the ambassador left the court.",
          "Getting no reply, the ambassador left the court.",
          "Receiving no response, the ambassador left the court.",
          "Having received no response, the ambassador left the court.",
          "Not having received a reply, the ambassador left the court.",
          "Not having received any reply, the ambassador left the court.",
          "Not having had a reply, the ambassador left the court.",
          "When he received no reply, the ambassador left the court.",
        ],
        explanation: "A participle clause can express a reason. The negative goes before the participle: \"Not receiving a reply\", or more elegantly \"Receiving no reply\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Construida por los romanos, la calzada sigue usándose hoy.",
        answer: "Built by the Romans, the road is still used today.",
        altAnswers: [
          "Built by the Romans, the road is still in use today.",
          "Built by the Romans, the road is still being used today.",
          "Built by the Romans, the road is still used.",
          "Built by the Romans, the road is still in use.",
          "Built by the Romans, the Roman road is still used today.",
          "Built by the Romans, the Roman road is still in use today.",
          "Built by the Romans, the Roman road is still being used today.",
          "Built by the Romans, the Roman road is still used.",
          "Built by the Romans, the Roman road is still in use.",
          "Built by the Romans, the causeway is still used today.",
          "Built by the Romans, the causeway is still in use today.",
          "Built by the Romans, the causeway is still being used today.",
          "Built by the Romans, the causeway is still used.",
          "Built by the Romans, the causeway is still in use.",
        ],
        explanation: "Past participle clause (passive): the road was built. The present simple passive \"is still used\" describes a present state.",
      },
      {
        type: "multiple-choice",
        question: "*Having been elected, the first decision of the new mayor was to cut taxes. What is the best correction?",
        options: [
          "Having been elected, the new mayor's first decision was to cut taxes.",
          "Having been elected, the new mayor decided first of all to cut taxes.",
          "Having been elected, cutting taxes was the new mayor's first decision.",
          "Having been elected, it was decided by the new mayor to cut taxes.",
        ],
        correctIndex: 1,
        explanation: "The mayor was elected, so \"the new mayor\" must be the subject. A possessive (\"the new mayor's decision\") does not fix the dangling participle; the subject would still be \"decision\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Advertidos del peligro, los habitantes abandonaron el pueblo.",
        answer: "Warned of the danger, the inhabitants abandoned the village.",
        altAnswers: [
          "Warned of the danger, the inhabitants left the village.",
          "Warned of the danger, the inhabitants fled the village.",
          "Warned of the danger, the inhabitants deserted the village.",
          "Warned of the danger, the villagers abandoned the village.",
          "Warned of the danger, the villagers left the village.",
          "Warned of the danger, the villagers fled the village.",
          "Warned of the danger, the villagers deserted the village.",
          "Warned of the danger, the residents abandoned the village.",
          "Warned of the danger, the residents left the village.",
          "Warned of the danger, the residents fled the village.",
          "Warned of the danger, the residents deserted the village.",
          "Having been warned of the danger, the inhabitants abandoned the village.",
          "Having been warned of the danger, the inhabitants left the village.",
          "Having been warned of the danger, the inhabitants fled the village.",
          "Having been warned of the danger, the inhabitants deserted the village.",
          "Having been warned of the danger, the villagers abandoned the village.",
          "Having been warned of the danger, the villagers left the village.",
          "Having been warned of the danger, the villagers fled the village.",
          "Having been warned of the danger, the villagers deserted the village.",
          "Having been warned of the danger, the residents abandoned the village.",
          "Having been warned of the danger, the residents left the village.",
          "Having been warned of the danger, the residents fled the village.",
          "Having been warned of the danger, the residents deserted the village.",
          "Warned about the danger, the inhabitants abandoned the village.",
          "Warned about the danger, the inhabitants left the village.",
          "Warned about the danger, the inhabitants fled the village.",
          "Warned about the danger, the inhabitants deserted the village.",
          "Warned about the danger, the villagers abandoned the village.",
          "Warned about the danger, the villagers left the village.",
          "Warned about the danger, the villagers fled the village.",
          "Warned about the danger, the villagers deserted the village.",
          "Warned about the danger, the residents abandoned the village.",
          "Warned about the danger, the residents left the village.",
          "Warned about the danger, the residents fled the village.",
          "Warned about the danger, the residents deserted the village.",
          "Having been warned about the danger, the inhabitants abandoned the village.",
          "Having been warned about the danger, the inhabitants left the village.",
          "Having been warned about the danger, the inhabitants fled the village.",
          "Having been warned about the danger, the inhabitants deserted the village.",
          "Having been warned about the danger, the villagers abandoned the village.",
          "Having been warned about the danger, the villagers left the village.",
          "Having been warned about the danger, the villagers fled the village.",
          "Having been warned about the danger, the villagers deserted the village.",
          "Having been warned about the danger, the residents abandoned the village.",
          "Having been warned about the danger, the residents left the village.",
          "Having been warned about the danger, the residents fled the village.",
          "Having been warned about the danger, the residents deserted the village.",
        ],
        explanation: "\"Warned\" (or \"Having been warned\") = passive. Use \"warn of\" or \"warn about\" + danger.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Habiendo perdido el apoyo del ejército, el dictador dimitió.",
        answer: "Having lost the support of the army, the dictator resigned.",
        altAnswers: [
          "Having lost the support of the army, the dictator stepped down.",
          "Having lost the support of the army, the dictator stood down.",
          "Having lost the army's support, the dictator resigned.",
          "Having lost the army's support, the dictator stepped down.",
          "Having lost the army's support, the dictator stood down.",
          "After losing the support of the army, the dictator resigned.",
          "After losing the support of the army, the dictator stepped down.",
          "After losing the support of the army, the dictator stood down.",
          "After losing the army's support, the dictator resigned.",
          "After losing the army's support, the dictator stepped down.",
          "After losing the army's support, the dictator stood down.",
          "Having lost army support, the dictator resigned.",
          "Having lost army support, the dictator stepped down.",
          "Having lost army support, the dictator stood down.",
        ],
        explanation: "\"Having\" + past participle for a completed earlier action. «Dimitir» = \"resign\" or \"step down\", never *dimit.",
      },
      {
        type: "matching",
        instructions: "Match each participle clause with its meaning.",
        pairs: [
          {
            left: "Fearing reprisals, the witnesses stayed silent.",
            right: "Porque temían represalias",
          },
          {
            left: "Having signed the treaty, the envoys left.",
            right: "Después de haber firmado",
          },
          {
            left: "Abandoned by its allies, the city fell.",
            right: "Porque había sido abandonada",
          },
          {
            left: "Walking home, she saw the fire.",
            right: "Mientras volvía a casa",
          },
        ],
        explanation: "Participle clauses can mean because, after, or while. Context decides.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order.",
        words: ["Founded", "by", "merchants", "in", "1250,", "the", "guild", "controlled", "the", "wool", "trade", "for", "centuries"],
        translation: "Fundado por mercaderes en 1250, el gremio controló el comercio de la lana durante siglos",
        explanation: "Past participle clause first, then the subject that it describes (\"the guild\").",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Al ver que no tenía salida, el general se rindió.",
        answer: "Seeing that he had no way out, the general surrendered.",
        altAnswers: [
          "Seeing that he had no way out, the general gave himself up.",
          "Realizing that he had no way out, the general surrendered.",
          "Realizing that he had no way out, the general gave himself up.",
          "Realizing he had no way out, the general surrendered.",
          "Realizing he had no way out, the general gave himself up.",
          "Seeing he had no way out, the general surrendered.",
          "Seeing he had no way out, the general gave himself up.",
          "Seeing that there was no way out, the general surrendered.",
          "Seeing that there was no way out, the general gave himself up.",
          "Realizing that there was no way out, the general surrendered.",
          "Realizing that there was no way out, the general gave himself up.",
          "Seeing no way out, the general surrendered.",
          "Seeing no way out, the general gave himself up.",
          "Finding himself trapped, the general surrendered.",
          "Finding himself trapped, the general gave himself up.",
        ],
        explanation: "«Al + infinitivo» often becomes a present participle clause: \"Seeing...\", \"Realizing...\". «Salida» here is a way out, not *an exit.",
      },
      {
        type: "multiple-choice",
        question: "Choose the correct sentence.",
        options: [
          "After crossing the desert, the caravan reached the oasis.",
          "After to cross the desert, the caravan reached the oasis.",
          "After cross the desert, the caravan reached the oasis.",
          "After having cross the desert, the caravan reached the oasis.",
        ],
        correctIndex: 0,
        explanation: "After a preposition, use -ing (\"After crossing\") or \"After having crossed\". *After to cross copies «después de cruzar».",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Una vez terminada la guerra, el país se dedicó a reconstruir sus ciudades.",
        answer: "With the war over, the country set about rebuilding its cities.",
        altAnswers: [
          "With the war over, the country devoted itself to rebuilding its cities.",
          "With the war over, the country focused on rebuilding its cities.",
          "With the war over, the country concentrated on rebuilding its cities.",
          "With the war over, the country dedicated itself to rebuilding its cities.",
          "Once the war was over, the country set about rebuilding its cities.",
          "Once the war was over, the country devoted itself to rebuilding its cities.",
          "Once the war was over, the country focused on rebuilding its cities.",
          "Once the war was over, the country concentrated on rebuilding its cities.",
          "Once the war was over, the country dedicated itself to rebuilding its cities.",
          "Once the war had ended, the country set about rebuilding its cities.",
          "Once the war had ended, the country devoted itself to rebuilding its cities.",
          "Once the war had ended, the country focused on rebuilding its cities.",
          "Once the war had ended, the country concentrated on rebuilding its cities.",
          "Once the war had ended, the country dedicated itself to rebuilding its cities.",
          "Once the war ended, the country set about rebuilding its cities.",
          "Once the war ended, the country devoted itself to rebuilding its cities.",
          "Once the war ended, the country focused on rebuilding its cities.",
          "Once the war ended, the country concentrated on rebuilding its cities.",
          "Once the war ended, the country dedicated itself to rebuilding its cities.",
          "The war over, the country set about rebuilding its cities.",
          "The war over, the country devoted itself to rebuilding its cities.",
          "The war over, the country focused on rebuilding its cities.",
          "The war over, the country concentrated on rebuilding its cities.",
          "The war over, the country dedicated itself to rebuilding its cities.",
          "When the war was over, the country set about rebuilding its cities.",
          "When the war was over, the country devoted itself to rebuilding its cities.",
          "When the war was over, the country focused on rebuilding its cities.",
          "When the war was over, the country concentrated on rebuilding its cities.",
          "When the war was over, the country dedicated itself to rebuilding its cities.",
          "When the war had ended, the country set about rebuilding its cities.",
          "When the war had ended, the country devoted itself to rebuilding its cities.",
          "When the war had ended, the country focused on rebuilding its cities.",
          "When the war had ended, the country concentrated on rebuilding its cities.",
          "When the war had ended, the country dedicated itself to rebuilding its cities.",
          "When the war ended, the country set about rebuilding its cities.",
          "When the war ended, the country devoted itself to rebuilding its cities.",
          "When the war ended, the country focused on rebuilding its cities.",
          "When the war ended, the country concentrated on rebuilding its cities.",
          "When the war ended, the country dedicated itself to rebuilding its cities.",
          "After the war ended, the country set about rebuilding its cities.",
          "After the war ended, the country devoted itself to rebuilding its cities.",
          "After the war ended, the country focused on rebuilding its cities.",
          "After the war ended, the country concentrated on rebuilding its cities.",
          "After the war ended, the country dedicated itself to rebuilding its cities.",
          "After the war had ended, the country set about rebuilding its cities.",
          "After the war had ended, the country devoted itself to rebuilding its cities.",
          "After the war had ended, the country focused on rebuilding its cities.",
          "After the war had ended, the country concentrated on rebuilding its cities.",
          "After the war had ended, the country dedicated itself to rebuilding its cities.",
        ],
        explanation: "«Una vez terminada la guerra» has a different subject from the main clause, so a simple participle would dangle. Use \"With the war over\", an absolute clause, or a full clause with \"once\".",
      },
      {
        type: "write",
        prompt: "Combine these notes into one paragraph of 3-4 sentences, using at least three participle clauses (one present, one past, one perfect). Make sure none of them dangles. Notes: the monastery was founded in 1120 / monks copied manuscripts there / the monks feared the plague / they closed the gates in 1348 / the plague ended / the monastery reopened its library to scholars.",
        minWords: 45,
        maxWords: 90,
        rubric: [
          "Uses a present participle clause",
          "Uses a past participle clause",
          "Uses a perfect participle clause (\"having\" + participle)",
          "Every participle refers to the subject of its main clause",
        ],
        modelAnswer: "Founded in 1120, the monastery soon became famous for its scriptorium, where monks spent their days copying manuscripts. Fearing the plague, the monks closed the gates in 1348 and cut off contact with the town. Having survived the epidemic, they reopened their library to scholars, who came from all over Europe to consult its collection.",
        explanation: "\"Founded\" refers to the monastery, \"Fearing\" and \"Having survived\" refer to the monks, the subject of each main clause.",
      },
    ],
  },
];
