// Synced from cheneygross-afk/lengo:src/lib/lessons/en-c1-u04-extra.ts by scripts/sync-content.mjs -- edit it there, not here.
import type { Lesson } from "./types";

// Extra practice (optional) lessons for EN-C1 unit u04 (substitution,
// ellipsis and reference). Drill-focused: a short recap, then lots of
// exercises.

export const EN_C1_U04_EXTRA: Lesson[] = [
  // ---------------------------------------------------------------------
  // Extra 1. I think so / I hope not
  // ---------------------------------------------------------------------
  {
    slug: "en-c1-so-not-drill-1",
    optional: true,
    level: "EN-C1",
    number: 1,
    title: "Extra Practice: I Think So, I Hope Not, I'm Afraid So",
    summary: "Drill \"so\" and \"not\" after think, hope, expect, suppose, imagine, guess and be afraid, and stop translating «creo que sí» as *I think yes and «ya lo sé» as *I know it.",
    duration: "10 min",
    sections: [
      {
        heading: "Quick recap: so and not replace a whole clause",
        body: [
          "Where Spanish says «creo que sí», «espero que no», «me temo que sí», English uses \"so\" for a positive clause and \"not\" for a negative one: \"I think so\", \"I hope not\", \"I'm afraid so\". Never *I think yes, *I hope that no.",
          "In the negative, think, expect, suppose, imagine and believe normally move the negative to the verb: \"I don't think so\", \"I don't expect so\". \"I suppose not\" and \"I guess not\" are also common. \"I think not\" exists but sounds formal or very firm.",
          "Hope and be afraid only take \"not\": \"I hope not\", \"I'm afraid not\". *I don't hope so is wrong.",
          "«Ya lo sé» is \"I know\", with no object: *I know it sounds odd as a reply. «Te lo dije» is \"I told you so\" or \"I told you\". «Si es así» / «si no» are \"if so\" / \"if not\".",
        ],
        examples: [
          { es: "Is she coming? I don't think so.", en: "¿Viene ella? Creo que no." },
          { es: "Will it be expensive? I'm afraid so.", en: "¿Será caro? Me temo que sí." },
          { es: "Will they cancel the flight? I hope not.", en: "¿Cancelarán el vuelo? Espero que no." },
          { es: "You're late again. I know, I'm sorry.", en: "Llegas tarde otra vez. Ya lo sé, lo siento." },
          { es: "Are you free on Friday? If so, let's meet.", en: "¿Estás libre el viernes? Si es así, nos vemos." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "«—¿Vendrá Ana a la cena? —Creo que no.» Which reply is correct?",
            options: ["I don't think so.", "I think no.", "I think that no.", "I don't think it."],
            correctIndex: 0,
            explanation: "«Creo que no» is \"I don't think so\": the negative goes on \"think\" and \"so\" replaces the clause.",
          },
          {
            type: "fill-blank",
            prompt: "Write the bold words in English.",
            sentence: "Has the meeting been canceled? I'm afraid ___.",
            answer: "so",
            en: "¿Se ha cancelado la reunión? Me temo que [sí].",
            explanation: "«Me temo que sí» is \"I'm afraid so\". The negative would be \"I'm afraid not\".",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Creo que sí, pero no estoy seguro.",
        answer: "I think so, but I'm not sure.",
        altAnswers: [
          "I think so, but I am not sure.",
          "I believe so, but I'm not sure.",
          "I think so, but I'm not certain.",
        ],
        explanation: "«Creo que sí» is \"I think so\". *I think yes and *I think that yes are calques.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Me temo que no.",
        answer: "I'm afraid not.",
        explanation: "\"Be afraid\" takes \"not\": \"I'm afraid not\". It is the polite way to give bad news.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "—¿Has aprobado? —Eso espero.",
        answer: "Did you pass? I hope so.",
        altAnswers: [
          "Have you passed? I hope so.",
          "Did you pass? I hope so!",
          "Have you passed? I hope so!",
        ],
        explanation: "«Eso espero» is \"I hope so\". Do not translate «eso»: *I hope that and *I hope it are wrong here.",
      },
      {
        type: "multiple-choice",
        question: "«—Llegas tarde. —Ya lo sé.» Which reply is correct?",
        options: ["I know.", "I know it.", "I already know it.", "Yes, I know it."],
        correctIndex: 0,
        explanation: "As a reply to information, English says just \"I know\", with no object. \"I know it\" is used for a thing you know (a song, a place): \"Do you know this song? Yes, I know it\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "Will the shops be open on Sunday? I expect ___.",
        answer: "so",
        en: "¿Estarán abiertas las tiendas el domingo? Supongo que [sí].",
        explanation: "\"I expect so\" is a very common British way to say «supongo que sí». Americans also say \"I guess so\" or \"I suppose so\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "—¿Ganaremos? —Supongo que no.",
        answer: "Will we win? I suppose not.",
        altAnswers: [
          "Will we win? I don't suppose so.",
          "Will we win? I guess not.",
          "Will we win? I don't think so.",
          "Are we going to win? I suppose not.",
          "Are we going to win? I guess not.",
          "Are we going to win? I don't suppose so.",
          "Are we going to win? I don't think so.",
        ],
        explanation: "\"Suppose\" and \"guess\" can take \"not\" directly: \"I suppose not\", \"I guess not\". \"I don't suppose so\" is also correct.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Te lo dije.",
        answer: "I told you so.",
        altAnswers: ["I told you."],
        explanation: "«Te lo dije» is \"I told you so\" or simply \"I told you\". *I said it to you is not idiomatic.",
      },
      {
        type: "multiple-choice",
        question: "When is \"I think not\" the best choice?",
        options: [
          "When you want to sound firm or formal, for example refusing a suggestion.",
          "In any casual conversation, instead of \"I don't think so\".",
          "Only in questions.",
          "Never: it is not correct English.",
        ],
        correctIndex: 0,
        explanation: "\"I think not\" is correct but marked: it sounds formal, ironic or very firm. In everyday speech, \"I don't think so\" is the normal form.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "—¿Hace falta reservar? —No creo.",
        answer: "Do we need to book? I don't think so.",
        altAnswers: [
          "Do we need to make a reservation? I don't think so.",
          "Do we need to reserve? I don't think so.",
          "Do we have to book? I don't think so.",
          "Is it necessary to book? I don't think so.",
          "Do we need a reservation? I don't think so.",
          "Do I need to book? I don't think so.",
        ],
        explanation: "«No creo» is \"I don't think so\": the \"so\" cannot be left out (*I don't think).",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Me imagino que sí.",
        answer: "I imagine so.",
        altAnswers: ["I'd imagine so.", "I would imagine so.", "I suppose so.", "I expect so.", "I guess so."],
        explanation: "\"Imagine\" works like \"think\": \"I imagine so\", \"I don't imagine so\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "Are you free tomorrow? If ___, we can meet for lunch.",
        answer: "so",
        en: "¿Estás libre mañana? Si [es así], podemos vernos para comer.",
        explanation: "\"If so\" replaces the whole clause «si estás libre». The negative is \"if not\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Si no, tendremos que cancelar el viaje.",
        answer: "If not, we'll have to cancel the trip.",
        altAnswers: [
          "Otherwise, we'll have to cancel the trip.",
          "If not, we will have to call off the trip.",
          "If not, we'll have to cancel the journey.",
        ],
        explanation: "«Si no» referring back to a whole clause is \"if not\" (or \"otherwise\"), never *if no.",
      },
      {
        type: "multiple-choice",
        question: "«—¿Lloverá mañana? —Espero que no.» Which reply is correct?",
        options: ["I hope not.", "I don't hope so.", "I hope no.", "I hope that not."],
        correctIndex: 0,
        explanation: "\"Hope\" only takes \"not\" after it. *I don't hope so is a classic error.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Parece que sí.",
        answer: "It seems so.",
        altAnswers: ["So it seems.", "It looks like it.", "Apparently so.", "It would seem so.", "It appears so.", "So it appears."],
        explanation: "\"Seem\" and \"appear\" also take \"so\": \"It seems so\", \"So it seems\". *It seems that yes is a calque.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order.",
        words: ["I", "don't", "expect", "so", "but", "you", "never", "know"],
        translation: "No creo, pero nunca se sabe.",
        explanation: "\"I don't expect so\": the negative goes on \"expect\", and \"so\" replaces the clause.",
      },
      {
        type: "matching",
        instructions: "Match each English reply with its Spanish meaning.",
        pairs: [
          { left: "I'm afraid so.", right: "Me temo que sí." },
          { left: "I hope not.", right: "Espero que no." },
          { left: "I don't think so.", right: "Creo que no." },
          { left: "I guess so.", right: "Supongo que sí." },
          { left: "I know.", right: "Ya lo sé." },
          { left: "I told you so.", right: "Te lo dije." },
        ],
        explanation: "\"So\" and \"not\" replace the Spanish «que sí» and «que no». No \"yes\" or \"no\" in these replies.",
      },
      {
        type: "dictation",
        audio: "I'm afraid so. The flight has been canceled.",
        explanation: "\"I'm afraid so\" gives bad news politely.",
      },
      {
        type: "speak",
        text: "I hope so, but I wouldn't count on it.",
        tip: "Stress \"hope\" and \"count\". \"Wouldn't\" sounds like WOOD-nt.",
        explanation: "\"I wouldn't count on it\" means «yo no contaría con ello»: a polite way to show doubt.",
      },
    ],
  },
  // ---------------------------------------------------------------------
  // Extra 2. one/ones, do so, the same
  // ---------------------------------------------------------------------
  {
    slug: "en-c1-do-so-one-drill-1",
    optional: true,
    level: "EN-C1",
    number: 2,
    title: "Extra Practice: Do So, One, Ones, The Same",
    summary: "Drill \"one/ones\" after adjectives (the red one, the ones on the left), \"do so\", \"do it\" and \"so do I\", and \"the same\", and stop writing *the blacks or *I prefer the red.",
    duration: "12 min",
    sections: [
      {
        heading: "Quick recap: one and ones",
        body: [
          "Spanish can drop a noun and keep the article: «el rojo», «los grandes», «el de la izquierda». English needs \"one\" or \"ones\": \"the red one\", \"the big ones\", \"the one on the left\". Adjectives never take -s: *the blacks ones is wrong.",
          "After a possessive, use the pronoun, not \"one\": «el mío» is \"mine\", «el de Ana» is \"Ana's\". \"One\" replaces countable nouns only: with an uncountable noun, just leave the adjective (\"I prefer white wine to red\") or repeat the noun.",
        ],
        examples: [
          { es: "I don't like this shirt; I prefer the blue one.", en: "No me gusta esta camisa; prefiero la azul." },
          { es: "These shoes are too small. Do you have any bigger ones?", en: "Estos zapatos me quedan pequeños. ¿Tiene unos más grandes?" },
          { es: "Which one is yours? The one on the left.", en: "¿Cuál es el tuyo? El de la izquierda." },
          { es: "My laptop is old, but Ana's is new.", en: "Mi portátil es viejo, pero el de Ana es nuevo." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "«¿Qué zapatillas quieres, las negras o las blancas?» Which is correct?",
            options: [
              "Which sneakers do you want, the black ones or the white ones?",
              "Which sneakers do you want, the blacks ones or the whites ones?",
              "Which sneakers do you want, the blacks or the whites?",
              "Which sneakers do you want, the black ones or the white one?",
            ],
            correctIndex: 0,
            explanation: "Plural noun, so \"ones\"; adjectives never take -s in English.",
          },
        ],
      },
      {
        heading: "Quick recap: do so, so do I, the same",
        body: [
          "\"Do so\" replaces a verb phrase in formal English: \"Employees who wish to attend must do so by Friday\". In speech, \"do it\" or \"do that\" is more common for a specific action.",
          "To agree with someone, use so/neither + auxiliary + subject: \"So did I\", \"Neither have I\", \"So am I\". The auxiliary matches the first sentence. \"Me too\" and \"Me neither\" are informal and fine; *I did it too and *Me too (after a negative) are errors.",
          "«Lo mismo» is \"the same\": \"I'll have the same\", \"the same as you\".",
        ],
        examples: [
          { es: "Those who wish to apply should do so in writing.", en: "Quienes deseen presentar su candidatura deberán hacerlo por escrito." },
          { es: "I saw the final yesterday. So did I.", en: "Ayer vi la final. Yo también." },
          { es: "I've never been to Japan. Neither have I.", en: "Nunca he estado en Japón. Yo tampoco." },
          { es: "I'll have the same, please.", en: "Para mí lo mismo, por favor." },
        ],
        checkpoint: [
          {
            type: "fill-blank",
            prompt: "Write the bold words in English.",
            sentence: "I've never been to Japan. Neither ___ I.",
            answer: "have",
            en: "Nunca he estado en Japón. Yo [tampoco].",
            explanation: "The auxiliary of the first sentence (\"have\") is repeated: \"Neither have I\". \"Me neither\" is the informal option.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "No me gusta esta chaqueta; prefiero la gris.",
        answer: "I don't like this jacket; I prefer the gray one.",
        altAnswers: [
          "I don't like this jacket. I prefer the gray one.",
          "I don't like this jacket, I prefer the gray one.",
          "I don't like this jacket; I'd rather have the gray one.",
          "I don't like this jacket. I'd prefer the gray one.",
        ],
        explanation: "«La gris» is \"the gray one\". *I prefer the gray, without \"one\", sounds like you mean the color itself.",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "This laptop is really slow. I need a new ___.",
        answer: "one",
        en: "Este portátil va muy lento. Necesito [uno] nuevo.",
        explanation: "\"A new one\" replaces \"a new laptop\". Without \"one\" (*I need a new) the sentence is incomplete.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Le pedí que firmara el contrato, pero se negó a hacerlo.",
        answer: "I asked him to sign the contract, but he refused to do so.",
        altAnswers: [
          "I asked her to sign the contract, but she refused to do so.",
          "I asked him to sign the contract, but he refused to do it.",
          "I asked her to sign the contract, but she refused to do it.",
          "I asked him to sign the contract, but he refused.",
          "I asked her to sign the contract, but she refused.",
          "I asked him to sign the contract but he refused to do so.",
          "I asked her to sign the contract but she refused to do so.",
        ],
        explanation: "\"Do so\" replaces \"sign the contract\" in a neutral to formal style. \"Refused\" alone is also perfectly natural.",
      },
      {
        type: "multiple-choice",
        question: "«—Ayer vi la final. —Yo también.» Which reply is correct?",
        options: ["So did I.", "I did it too.", "So I did.", "Too did I."],
        correctIndex: 0,
        explanation: "\"So + auxiliary + subject\": \"So did I\" (past simple, so \"did\"). \"So I did\" means something else: «es verdad, lo hice».",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Quiero el mismo que tú.",
        answer: "I want the same one as you.",
        altAnswers: [
          "I want the same as you.",
          "I'd like the same one as you.",
          "I'd like the same as you.",
          "I'll have the same as you.",
          "I'll have the same one as you.",
        ],
        explanation: "«Lo mismo / el mismo que» is \"the same (one) as\", never *the same that.",
      },
      {
        type: "multiple-choice",
        question: "You are choosing between two shirts. Find the mistake: *I prefer the red. What should you say?",
        options: ["I prefer the red one.", "I prefer the reds.", "I prefer the red ones shirt.", "I prefer red one."],
        correctIndex: 0,
        explanation: "An adjective cannot stand alone after \"the\" to mean a thing: add \"one\" (\"the red one\"), unlike Spanish «el rojo».",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Estas galletas están buenísimas; ¿puedo tomar otra?",
        answer: "These cookies are delicious; can I have another one?",
        altAnswers: [
          "These cookies are delicious. Can I have another one?",
          "These cookies are delicious; can I have another?",
          "These cookies are delicious. Can I have another?",
          "These cookies are delicious; can I take another one?",
          "These biscuits are delicious; can I have another one?",
          "These biscuits are delicious. Can I have another one?",
          "These biscuits are delicious; can I have another?",
          "These cookies are really good; can I have another one?",
        ],
        explanation: "«Otra» is \"another one\" or just \"another\" (which, unlike adjectives, can stand alone).",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Los empleados que deseen inscribirse deberán hacerlo antes del viernes.",
        answer: "Employees who wish to register must do so before Friday.",
        altAnswers: [
          "Employees who wish to register must do so by Friday.",
          "Employees who wish to register should do so before Friday.",
          "Employees who wish to register should do so by Friday.",
          "Employees who wish to sign up must do so before Friday.",
          "Employees who wish to sign up must do so by Friday.",
          "Employees who want to register must do so by Friday.",
          "Employees wishing to register must do so by Friday.",
          "Employees who wish to enroll must do so by Friday.",
        ],
        explanation: "\"Do so\" is the formal way to avoid repeating \"register\". \"By Friday\" means «como muy tarde el viernes».",
      },
      {
        type: "matching",
        instructions: "Match each English phrase with its Spanish meaning.",
        pairs: [
          { left: "So did I.", right: "Yo también (lo hice)." },
          { left: "Neither did I.", right: "Yo tampoco (lo hice)." },
          { left: "I'll have the same.", right: "Para mí lo mismo." },
          { left: "the red one", right: "el rojo" },
          { left: "the ones on the left", right: "los de la izquierda" },
          { left: "mine", right: "el mío" },
        ],
        explanation: "English needs an auxiliary (so did I), \"one/ones\" (the red one) or a possessive pronoun (mine) where Spanish just keeps the article.",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "If you haven't paid yet, please ___ as soon as possible.",
        answer: "do so",
        altAnswers: ["do it", "do that", "pay"],
        en: "Si aún no ha pagado, por favor [hágalo] lo antes posible.",
        explanation: "\"Do so\" replaces \"pay\" in formal notices and emails.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "No me gustan las películas de terror, pero las de ciencia ficción me encantan.",
        answer: "I don't like horror movies, but I love science fiction ones.",
        altAnswers: [
          "I don't like horror films, but I love science fiction ones.",
          "I don't like horror movies, but I love sci-fi ones.",
          "I don't like horror films, but I love sci-fi ones.",
          "I don't like horror movies, but I love science fiction.",
          "I don't like horror films, but I love science fiction.",
          "I don't like horror movies, but I love sci-fi.",
          "I don't like horror films, but I love sci-fi.",
          "I don't like horror movies, but I love science fiction movies.",
          "I don't like horror films, but I love science fiction films.",
        ],
        explanation: "«Las de ciencia ficción» is \"science fiction ones\" (or just \"science fiction\", the genre). Note the English word order: \"I love X\", not «X me encantan».",
      },
      {
        type: "multiple-choice",
        question: "«—No me gusta el café. —A mí tampoco.» Which reply is correct?",
        options: ["Me neither.", "Me too.", "So do I.", "Neither don't I."],
        correctIndex: 0,
        explanation: "After a negative, agree with \"Me neither\" or \"Neither do I\". \"Me too\" and \"So do I\" agree with a positive sentence.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order.",
        words: ["I", "prefer", "the", "ones", "on", "the", "top", "shelf"],
        translation: "Prefiero los de la estantería de arriba.",
        explanation: "«Los de» + place is \"the ones on/in\" + place.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Mi carro es más viejo que el de mi hermano.",
        answer: "My car is older than my brother's.",
        altAnswers: ["My car is older than my brother's car."],
        explanation: "«El de mi hermano» is \"my brother's\". *The one of my brother is a calque.",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "I'm going to the party tonight. So ___ I.",
        answer: "am",
        en: "Voy a ir a la fiesta esta noche. Yo [también].",
        explanation: "The first sentence uses \"am\" (I'm going), so the reply is \"So am I\". *So do I is a common error here.",
      },
      {
        type: "dictation",
        audio: "I lost my umbrella, so I bought a new one.",
        explanation: "\"A new one\" replaces \"a new umbrella\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "¿Cuál prefieres, el grande o el pequeño?",
        answer: "Which one do you prefer, the big one or the small one?",
        altAnswers: [
          "Which do you prefer, the big one or the small one?",
          "Which one do you prefer, the big one or the little one?",
          "Which do you prefer, the large one or the small one?",
          "Which one do you prefer, the large one or the small one?",
          "Which one would you prefer, the big one or the small one?",
          "Which do you prefer, the big one or the little one?",
        ],
        explanation: "Every adjective needs its own \"one\": \"the big one or the small one\".",
      },
    ],
  },
  // ---------------------------------------------------------------------
  // Extra 3. Ellipsis after auxiliaries and "to"
  // ---------------------------------------------------------------------
  {
    slug: "en-c1-auxiliary-ellipsis-drill-1",
    optional: true,
    level: "EN-C1",
    number: 3,
    title: "Extra Practice: She Can't, But I Can / I Would Have",
    summary: "Drill short answers and contrasts that stop at the auxiliary (She hasn't, but I have; He might have been) or at \"to\" (I'd love to), and stop saying *but I yes or *I'd love.",
    duration: "12 min",
    sections: [
      {
        heading: "Quick recap: stop at the auxiliary",
        body: [
          "Spanish can contrast with «sí» and «no»: «Ella no sabe nadar, pero yo sí». English must repeat the auxiliary or modal and drop the rest: \"She can't swim, but I can\". *But I yes is impossible.",
          "Choose the auxiliary from the first clause: be > be, have > have, can > can, will > will. If there is no auxiliary (present or past simple), use do/does/did: \"He didn't go, but I did\".",
          "With modal perfects, keep the modal and \"have\": \"I would have\", \"He might have\". If the verb is \"be\", keep \"been\": \"Was he angry? He might have been\". In British English you will also hear \"I would have done\"; Americans just say \"I would have\".",
        ],
        examples: [
          { es: "She can't swim, but I can.", en: "Ella no sabe nadar, pero yo sí." },
          { es: "He didn't go to the meeting, but I did.", en: "Él no fue a la reunión, pero yo sí." },
          { es: "I haven't read it, but Tom has.", en: "Yo no lo he leído, pero Tom sí." },
          { es: "Was he angry? He might have been.", en: "¿Estaba enojado? Puede que sí." },
          { es: "They weren't invited, but we were.", en: "Ellos no estaban invitados, pero nosotros sí." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "«Él no fue a la reunión, pero yo sí.» Which is correct?",
            options: [
              "He didn't go to the meeting, but I did.",
              "He didn't go to the meeting, but I yes.",
              "He didn't go to the meeting, but I went it.",
              "He didn't go to the meeting, but I was.",
            ],
            correctIndex: 0,
            explanation: "Past simple has no auxiliary, so English uses \"did\": \"but I did\".",
          },
        ],
      },
      {
        heading: "Quick recap: stop at \"to\"",
        body: [
          "When the infinitive has already been mentioned, keep \"to\" and drop the verb: \"Do you want to come? I'd love to\", \"I didn't want to tell her, but I had to\". *I'd love and *I'd love too are errors.",
          "This works after want, would like, would love, need, have, try, plan, hope, mean, be going: \"I meant to, but I forgot\".",
        ],
        examples: [
          { es: "Would you like to join us? I'd love to.", en: "¿Quieres venir con nosotros? Me encantaría." },
          { es: "I didn't want to tell her, but I had to.", en: "No quería decírselo, pero tuve que hacerlo." },
          { es: "I meant to call you, but I forgot.", en: "Tenía intención de llamarte, pero se me olvidó." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "Find the mistake: *Would you like to come? I'd love too. What should it say?",
            options: ["I'd love to.", "I'd love.", "I'd love it to.", "I'd love so."],
            correctIndex: 0,
            explanation: "Keep the \"to\" of the infinitive: \"I'd love to\". \"Too\" (también) sounds the same, which is why the spelling mistake is so common.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Mi hermano no sabe cocinar, pero yo sí.",
        answer: "My brother can't cook, but I can.",
        altAnswers: [
          "My brother doesn't know how to cook, but I do.",
          "My brother cannot cook, but I can.",
          "My brother can't cook but I can.",
        ],
        explanation: "Repeat the modal: \"but I can\". If you use \"know how to\", the auxiliary is \"do\": \"but I do\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "—¿Quieres venir a cenar? —Me encantaría.",
        answer: "Do you want to come to dinner? I'd love to.",
        altAnswers: [
          "Would you like to come to dinner? I'd love to.",
          "Do you want to come for dinner? I'd love to.",
          "Would you like to come for dinner? I'd love to.",
          "Do you want to come over for dinner? I'd love to.",
          "Would you like to come over for dinner? I'd love to.",
        ],
        explanation: "«Me encantaría» answering an invitation is \"I'd love to\": the \"to\" stands for the whole infinitive.",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "I haven't seen the film yet, but my sister ___.",
        answer: "has",
        en: "Yo aún no he visto la película, pero mi hermana [sí].",
        explanation: "The first clause uses \"have\" (present perfect), so the contrast uses \"has\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Lo habría hecho si me lo hubieras pedido.",
        answer: "I would have if you had asked me.",
        altAnswers: [
          "I would have if you'd asked me.",
          "I would have if you had asked.",
          "I would have if you'd asked.",
          "I would have done it if you had asked me.",
          "I would have done it if you'd asked me.",
          "I would have done it if you'd asked.",
          "I would have done so if you had asked me.",
          "I would have done if you'd asked me.",
        ],
        explanation: "Ellipsis stops after \"would have\". \"I would have done it\" is also fine, and \"I would have done\" is British.",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "Do you want to come with us? ___, but I can't.",
        answer: "I'd like to",
        altAnswers: ["I'd love to", "I would like to", "I would love to"],
        en: "¿Quieres venir con nosotros? [Me gustaría], pero no puedo.",
        explanation: "\"I'd like to\" keeps \"to\" and drops \"come with you\". *I'd like, but I can't is incomplete.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "No pensaba venir, pero al final lo hice.",
        answer: "I wasn't planning to come, but in the end I did.",
        altAnswers: [
          "I wasn't planning to come, but I did in the end.",
          "I wasn't going to come, but in the end I did.",
          "I wasn't going to come, but I did in the end.",
          "I didn't plan to come, but in the end I did.",
          "I wasn't planning on coming, but in the end I did.",
          "I wasn't planning to come, but eventually I did.",
        ],
        explanation: "«Lo hice» after a past simple idea is just \"I did\". *I did it is possible but heavier.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "—¿Ha llegado ya Carlos? —Puede que sí.",
        answer: "Has Carlos arrived yet? He may have.",
        altAnswers: [
          "Has Carlos arrived yet? He might have.",
          "Has Carlos arrived yet? He could have.",
          "Has Carlos arrived yet? Maybe he has.",
          "Has Carlos arrived yet? Perhaps he has.",
          "Has Carlos arrived already? He may have.",
          "Has Carlos arrived already? He might have.",
        ],
        explanation: "The question uses \"has arrived\", so the modal answer is \"He may/might have\". The Spanish «sí» disappears.",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "Should I have called her? Yes, you ___.",
        answer: "should have",
        en: "¿Debería haberla llamado? Sí, [deberías haberlo hecho].",
        explanation: "Keep the modal and \"have\": \"you should have\". *Yes, you should is incomplete with a past meaning.",
      },
      {
        type: "multiple-choice",
        question: "\"Have you finished the report?\" What is the standard American short answer?",
        options: ["Yes, I have.", "Yes, I have done.", "Yes, I finished.", "Yes, I have it."],
        correctIndex: 0,
        explanation: "Americans stop at the auxiliary: \"Yes, I have\". \"Yes, I have done\" is heard in Britain but not in the US.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Ellos no estaban invitados, pero nosotros sí.",
        answer: "They weren't invited, but we were.",
        altAnswers: ["They were not invited, but we were.", "They weren't invited but we were."],
        explanation: "The first clause uses \"were\", so the contrast is \"but we were\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "No quería decírselo, pero tuve que hacerlo.",
        answer: "I didn't want to tell her, but I had to.",
        altAnswers: [
          "I didn't want to tell him, but I had to.",
          "I didn't want to tell them, but I had to.",
          "I didn't want to tell her but I had to.",
          "I didn't want to tell him but I had to.",
        ],
        explanation: "«Tuve que hacerlo» is \"I had to\": the \"to\" stands for \"tell her\".",
      },
      {
        type: "multiple-choice",
        question: "«—¿Estaba enojado? —Puede que lo estuviera.» Which reply is correct?",
        options: ["He might have been.", "He might have.", "He might be it.", "He might been."],
        correctIndex: 0,
        explanation: "The verb is \"be\", so keep \"been\": \"He might have been\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "He might be at home, but I doubt he ___.",
        answer: "is",
        en: "Puede que esté en casa, pero dudo que [esté].",
        explanation: "The verb is \"be\", so the ellipsis stops at \"is\": \"I doubt he is\".",
      },
      {
        type: "word-order",
        prompt: "Put the words in order.",
        words: ["She", "said", "she", "would", "finish", "it", "and", "she", "has"],
        translation: "Dijo que lo terminaría y lo ha hecho.",
        explanation: "\"And she has\" = \"and she has finished it\". The auxiliary changes to match the new time.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Iba a llamarte, pero no me dio tiempo.",
        answer: "I was going to call you, but I didn't have time.",
        altAnswers: [
          "I meant to call you, but I didn't have time.",
          "I was going to call you, but I ran out of time.",
          "I was going to call you, but I didn't get the chance.",
          "I was going to call you, but there wasn't time.",
        ],
        explanation: "No ellipsis needed here, but notice the pattern: \"I was going to\" could stand alone as a reply: \"Why didn't you call? I was going to\".",
      },
      {
        type: "dictation",
        audio: "I'd like to help, but I really don't think I can.",
        explanation: "Two ellipses: \"I'd like to\" (help) is complete, and \"I can\" means \"I can help\".",
      },
      {
        type: "speak",
        text: "I haven't been to Rome, but my sister has.",
        tip: "Stress the contrast: \"HAVEN'T\" and \"HAS\".",
        explanation: "The auxiliary carries the stress in contrasts, which helps the listener follow the ellipsis.",
      },
    ],
  },
  // ---------------------------------------------------------------------
  // Extra 4. Reference: this, that, it, such, the former/the latter
  // ---------------------------------------------------------------------
  {
    slug: "en-c1-reference-drill-1",
    optional: true,
    level: "EN-C1",
    number: 4,
    title: "Extra Practice: This, That, It, Such and Former/Latter",
    summary: "Drill the words that point back to earlier ideas: this, that, it, which, such, the former and the latter, respectively, and stop translating «lo cual» as *what.",
    duration: "12 min",
    sections: [
      {
        heading: "Quick recap: it, this, that and which",
        body: [
          "\"It\" continues the same topic without focus. \"This\" points back to a whole idea and gives it focus, often to comment on it: \"Prices rose by 20%. This forced many families to cut spending.\" If \"it\" could refer to two things, use \"this\" + noun: \"this decision\", \"this increase\".",
          "\"That\" refers back to what someone else has just said, or adds distance: \"If that's the case, we'll wait\", \"Why do you say that?\".",
          "«Lo cual» / «lo que» referring to a whole clause is \", which\": \"He failed the exam, which surprised me\". *He failed, what surprised me is a very common error.",
        ],
        examples: [
          { es: "The council closed the library. This angered local residents.", en: "El ayuntamiento cerró la biblioteca. Esto indignó a los vecinos." },
          { es: "He failed the exam, which surprised everyone.", en: "Reprobó el examen, lo cual sorprendió a todos." },
          { es: "If that's the case, we'll have to wait.", en: "Si ese es el caso, tendremos que esperar." },
          { es: "She refused to apologize, which made things worse.", en: "Se negó a disculparse, lo que empeoró las cosas." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "Find the mistake: *He arrived late, what annoyed everyone. What should it say?",
            options: [
              "He arrived late, which annoyed everyone.",
              "He arrived late, that annoyed everyone.",
              "He arrived late, it annoyed everyone.",
              "He arrived late, what it annoyed everyone.",
            ],
            correctIndex: 0,
            explanation: "A relative clause about the whole previous idea starts with \", which\". \"What\" means «lo que» only at the start of a noun clause (\"What annoyed me was...\").",
          },
        ],
      },
      {
        heading: "Quick recap: such, the former, the latter",
        body: [
          "\"Such\" + noun points back to a type of thing: \"such measures\", \"such behavior\", \"such a decision\". With a singular countable noun, \"a\" goes after \"such\": \"such a mess\", never *a such mess.",
          "\"The former\" and \"the latter\" refer to the first and the second of exactly two things already mentioned. They are formal; in speech, \"the first\" and \"the second\" or repeating the noun is fine. \"Respectively\" matches two lists in order: \"Ana and Tom won first and second prize, respectively\".",
          "\"The above\" and \"as mentioned above\" refer to earlier parts of a written text.",
        ],
        examples: [
          { es: "Such measures are unlikely to work.", en: "Es poco probable que este tipo de medidas funcionen." },
          { es: "I had never seen such a mess.", en: "Nunca había visto semejante desorden." },
          { es: "We could take the train or fly. The former is cheaper.", en: "Podríamos ir en tren o en avión. Lo primero es más barato." },
          { es: "As mentioned above, the results are not conclusive.", en: "Como se ha mencionado arriba, los resultados no son concluyentes." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "«Nunca había visto semejante desorden.» Which is correct?",
            options: [
              "I had never seen such a mess.",
              "I had never seen a such mess.",
              "I had never seen so mess.",
              "I had never seen such mess like this.",
            ],
            correctIndex: 0,
            explanation: "\"Such a\" + singular countable noun. The article goes after \"such\".",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Reprobó el examen, lo cual me sorprendió.",
        answer: "He failed the exam, which surprised me.",
        altAnswers: [
          "She failed the exam, which surprised me.",
          "He failed the test, which surprised me.",
          "She failed the test, which surprised me.",
        ],
        explanation: "«Lo cual» about a whole clause is \", which\", with a comma. *What surprised me would be wrong here.",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "The company cut salaries by 10%. ___ decision caused anger among staff.",
        answer: "This",
        altAnswers: ["That"],
        en: "La empresa recortó los sueldos un 10 %. [Esta] decisión provocó indignación entre el personal.",
        explanation: "\"This\" + a summarizing noun (\"this decision\") points back clearly to the whole previous sentence.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Ana y Lucia son médicas; la primera trabaja en Madrid y la segunda en Lima.",
        answer: "Ana and Lucia are doctors; the former works in Madrid and the latter in Lima.",
        altAnswers: [
          "Ana and Lucia are doctors; the former works in Madrid, the latter in Lima.",
          "Ana and Lucia are doctors; the former works in Madrid and the latter works in Lima.",
          "Ana and Lucia are doctors. The former works in Madrid and the latter in Lima.",
          "Ana and Lucia are doctors; the first works in Madrid and the second in Lima.",
          "Ana and Lucia are doctors; Ana works in Madrid and Lucia in Lima.",
          "Ana and Lucia are doctors; Ana works in Madrid and Lucia works in Lima.",
        ],
        explanation: "For two people or things, \"the former\" = the first, \"the latter\" = the second. The verb can be left out in the second clause.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Los precios subieron un 20 %. Esto obligó a muchas familias a recortar gastos.",
        answer: "Prices rose by 20%. This forced many families to cut spending.",
        altAnswers: [
          "Prices rose by 20%. This forced many families to cut their spending.",
          "Prices rose by 20%. This forced many families to cut back.",
          "Prices rose by 20%. This forced many families to cut costs.",
          "Prices went up by 20%. This forced many families to cut spending.",
          "Prices went up by 20%. This forced many families to cut back.",
          "Prices rose 20%. This forced many families to cut spending.",
          "Prices rose by 20%. This forced many families to reduce their spending.",
          "Prices rose by 20%, which forced many families to cut spending.",
        ],
        explanation: "\"This\" refers to the whole previous sentence (the rise in prices). \"It\" would be less clear.",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "We could take the train or fly. The ___ is cheaper, but flying is faster.",
        answer: "former",
        en: "Podríamos ir en tren o en avión. Lo [primero] es más barato, pero el avión es más rápido.",
        explanation: "\"The former\" = the first of two options (the train).",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Ana y Tom ganaron el primer y el segundo premio, respectivamente.",
        answer: "Ana and Tom won first and second prize, respectively.",
        altAnswers: [
          "Ana and Tom won first and second prize respectively.",
          "Ana and Tom won the first and second prizes, respectively.",
          "Ana and Tom won the first and second prizes respectively.",
          "Ana and Tom won first and second prizes, respectively.",
          "Ana and Tom won the first and the second prize, respectively.",
        ],
        explanation: "\"Respectively\" matches the two lists in order: Ana > first, Tom > second.",
      },
      {
        type: "multiple-choice",
        question: "\"The council closed the library and the pool. ___ angered local residents.\" Which word refers most clearly to the whole action?",
        options: ["This", "It", "What", "Which"],
        correctIndex: 0,
        explanation: "\"This\" summarizes the whole previous sentence. \"It\" could seem to refer to the pool, \"What\" cannot start this sentence, and \"Which\" needs a comma and the same sentence.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Como se ha mencionado arriba, los resultados no son concluyentes.",
        answer: "As mentioned above, the results are inconclusive.",
        altAnswers: [
          "As mentioned above, the results are not conclusive.",
          "As stated above, the results are inconclusive.",
          "As stated above, the results are not conclusive.",
          "As was mentioned above, the results are inconclusive.",
          "As noted above, the results are inconclusive.",
          "As noted above, the results are not conclusive.",
        ],
        explanation: "\"As mentioned above\" is the standard written formula. No \"it\" is needed: *As it has been mentioned is a calque.",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "He told me he had been promoted, but I didn't believe ___.",
        answer: "it",
        altAnswers: ["him"],
        en: "Me dijo que lo habían ascendido, pero no [me lo] creí.",
        explanation: "\"It\" refers to the information (he had been promoted). \"Him\" refers to the person, and is also natural.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "No tomó ninguna medida, lo que demuestra su falta de interés.",
        answer: "He took no action, which shows his lack of interest.",
        altAnswers: [
          "She took no action, which shows her lack of interest.",
          "He didn't take any action, which shows his lack of interest.",
          "She didn't take any action, which shows her lack of interest.",
          "He took no measures, which shows his lack of interest.",
          "He didn't take any measures, which shows his lack of interest.",
          "He took no action, which demonstrates his lack of interest.",
          "He took no action, which proves his lack of interest.",
          "She took no action, which proves her lack of interest.",
        ],
        explanation: "«Lo que» about the whole previous clause is \", which\". \"Action\" is usually uncountable here: \"took no action\".",
      },
      {
        type: "matching",
        instructions: "Match each English expression with its Spanish meaning.",
        pairs: [
          { left: "the former", right: "el primero (de dos)" },
          { left: "the latter", right: "el segundo (de dos)" },
          { left: "such a", right: "semejante" },
          { left: "respectively", right: "respectivamente" },
          { left: "the above", right: "lo anterior" },
          { left: ", which", right: "lo cual" },
        ],
        explanation: "These words point back to something already mentioned, so the reader does not need the noun again.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order.",
        words: ["She", "refused", "to", "apologize", "which", "made", "things", "worse"],
        translation: "Se negó a disculparse, lo que empeoró las cosas.",
        explanation: "\", which\" refers back to her whole refusal. In writing, put a comma before \"which\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Si ese es el caso, tendremos que esperar.",
        answer: "If that's the case, we'll have to wait.",
        altAnswers: [
          "If that is the case, we will have to wait.",
          "If so, we'll have to wait.",
          "In that case, we'll have to wait.",
          "If this is the case, we'll have to wait.",
        ],
        explanation: "\"That\" refers back to what has just been said: \"If that's the case\". \"If so\" is shorter.",
      },
      {
        type: "multiple-choice",
        question: "\"Coffee and tea both contain caffeine, but ___ has more.\" Which is the most natural and correct way to refer to coffee?",
        options: ["the former", "the formerly", "the latter", "the before"],
        correctIndex: 0,
        explanation: "Coffee is mentioned first, so \"the former\". \"The latter\" would mean tea.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "No esperaba una reacción así.",
        answer: "I didn't expect such a reaction.",
        altAnswers: [
          "I wasn't expecting such a reaction.",
          "I didn't expect a reaction like that.",
          "I wasn't expecting a reaction like that.",
          "I didn't expect that kind of reaction.",
          "I wasn't expecting that kind of reaction.",
          "I did not expect such a reaction.",
        ],
        explanation: "«Una reacción así» is \"such a reaction\" or \"a reaction like that\". Note the order: \"such a\", not *a such.",
      },
      {
        type: "dictation",
        audio: "Such measures are unlikely to work in the long term.",
        explanation: "\"Such\" + plural noun (\"measures\") refers back to a type of measure just described.",
      },
    ],
  },
];
