// Synced from cheneygross-afk/lengo:src/lib/lessons/en-c2-u05-extra.ts by scripts/sync-content.mjs -- edit it there, not here.
import type { Lesson } from "./types";

// Extra practice (optional) lessons for EN-C2 unit u05 (proverbs and sayings).
// Drill-focused: a short recap, then lots of exercises.

export const EN_C2_U05_EXTRA: Lesson[] = [
  {
    slug: "en-c2-proverbs-complete-adapt-drill-1",
    optional: true,
    level: "EN-C2",
    number: 1,
    title: "Extra Practice: Completing and Twisting Proverbs",
    summary: "Drill recognizing half-quoted proverbs (when in Rome..., the early bird...), their exact fixed wording, their real and false Spanish equivalents, and the twisted versions used in headlines and ads.",
    duration: "12 min",
    sections: [
      {
        heading: "Quick recap: half a proverb is enough",
        body: [
          "Native speakers often quote only the first half of a proverb and let the listener finish it: \"Well, when in Rome...\" (do as the Romans do), \"The early bird...\" (catches the worm), \"Speak of the devil...\" (and he shall appear), \"If the shoe fits...\" (wear it; \"if the cap fits\" in British English).",
          "The wording is fixed, often with old grammar: \"Too many cooks spoil the broth\", \"Don't count your chickens before they hatch\", \"Every cloud has a silver lining\", \"Where there's a will, there's a way\". Reordering (*There's a way where there's a will) or swapping words breaks it.",
          "Don't invent English proverbs from refranes. «A caballo regalado no le mires el diente» happens to match \"Don't look a gift horse in the mouth\", but «Camarón que se duerme se lo lleva la corriente» has no shrimp in English: say \"You snooze, you lose\".",
        ],
        examples: [
          { es: "Well, when in Rome...", en: "Bueno, donde fueres, haz lo que vieres..." },
          { es: "Don't count your chickens before they hatch.", en: "No vendas la piel del oso antes de cazarlo." },
          { es: "Too many cooks spoil the broth.", en: "Muchas manos en un plato hacen mucho garabato." },
          { es: "You snooze, you lose.", en: "Camarón que se duerme se lo lleva la corriente." },
          { es: "Don't look a gift horse in the mouth.", en: "A caballo regalado no le mires el diente." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "\"The early bird...\" What comes next?",
            options: ["catches the worm", "catches the fish", "flies the highest", "sings the loudest"],
            correctIndex: 0,
            explanation: "\"The early bird catches the worm\" is the English cousin of «A quien madruga, Dios le ayuda». Saying just \"the early bird...\" is enough.",
          },
          {
            type: "multiple-choice",
            question: "Which is the correct form?",
            options: [
              "Where there's a will, there's a way.",
              "Where there's a way, there's a will.",
              "When there's a will, there's a road.",
              "Where is a will, is a way.",
            ],
            correctIndex: 0,
            explanation: "The fixed form starts with determination (\"a will\") and ends with the solution (\"a way\"). Close to «Querer es poder».",
          },
        ],
      },
      {
        heading: "Real equivalents, false equivalents and twisted proverbs",
        body: [
          "Some refranes have close English twins: \"Like father, like son\" for «De tal palo, tal astilla»; \"Better late than never\" for «Más vale tarde que nunca». Others only partly match: «En boca cerrada no entran moscas» is closer to \"Least said, soonest mended\" or \"Silence is golden\" than to anything with flies.",
          "Headlines and ads love twisted proverbs: \"Where there's a will, there's a lawyer\", \"Too many cooks? Not in our kitchen\". The joke only works if the reader knows the original, so recognising the base form is the real skill.",
          "When a proverb has no equivalent, say the idea plainly rather than inventing one: «Cría cuervos y te sacarán los ojos» → \"Be careful who you help; they may turn on you\", or the idiom \"bite the hand that feeds you\".",
        ],
        examples: [
          { es: "Least said, soonest mended.", en: "En boca cerrada no entran moscas (aproximadamente)." },
          { es: "Where there's a will, there's a lawyer.", en: "Donde hay testamento, hay abogado (juego con «Querer es poder»)." },
          { es: "Absence makes the heart grow fonder.", en: "La ausencia aviva el cariño." },
          { es: "He bit the hand that fed him.", en: "Mordió la mano que le daba de comer." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "Which English proverb is the real equivalent of «Ojos que no ven, corazón que no siente»?",
            options: [
              "What the eye doesn't see, the heart doesn't grieve over.",
              "Eyes that don't see, heart that doesn't feel.",
              "Out of sight, out of heart.",
              "The eyes are the window to the soul.",
            ],
            correctIndex: 0,
            explanation: "The British proverb matches the Spanish one closely. The second option is a literal translation, the third a garbled version of \"Out of sight, out of mind\", and the fourth means something else.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "multiple-choice",
        question: "Complete the proverb: \"Don't put all your eggs...\"",
        options: ["in one basket", "in the same box", "on one plate", "in a single nest"],
        correctIndex: 0,
        explanation: "\"Don't put all your eggs in one basket\" = don't risk everything on one thing («no te lo juegues todo a una carta»).",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Bueno, ya sabes: donde fueres, haz lo que vieres.",
        answer: "Well, you know what they say: when in Rome, do as the Romans do.",
        altAnswers: [
          "Well, you know what they say: when in Rome.",
          "Well, you know: when in Rome, do as the Romans do.",
          "Well, you know: when in Rome.",
          "Well, as they say: when in Rome, do as the Romans do.",
          "Well, as they say: when in Rome.",
          "Well, when in Rome, do as the Romans do.",
          "Well, when in Rome.",
        ],
        explanation: "The English equivalent is \"When in Rome, do as the Romans do\", often cut to \"When in Rome...\". Translating «donde fueres» literally produces no proverb at all.",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "Too many cooks ___ the broth.",
        answer: "spoil",
        en: "Demasiados cocineros [estropean] el caldo (= «muchas manos en un plato hacen mucho garabato»).",
        explanation: "The proverb keeps the present simple \"spoil\" and the old-fashioned \"broth\" («caldo»).",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "No cantes victoria antes de tiempo: el partido aún no ha terminado.",
        answer: "Don't count your chickens before they hatch: the match isn't over yet.",
        altAnswers: [
          "Don't count your chickens before they hatch: the match hasn't finished yet.",
          "Don't count your chickens before they hatch: the match isn't over.",
          "Don't count your chickens before they hatch: the game isn't over yet.",
          "Don't count your chickens before they hatch: the game hasn't finished yet.",
          "Don't count your chickens before they hatch: the game isn't over.",
          "Don't count your chickens before they're hatched: the match isn't over yet.",
          "Don't count your chickens before they're hatched: the match hasn't finished yet.",
          "Don't count your chickens before they're hatched: the match isn't over.",
          "Don't count your chickens before they're hatched: the game isn't over yet.",
          "Don't count your chickens before they're hatched: the game hasn't finished yet.",
          "Don't count your chickens before they're hatched: the game isn't over.",
          "Don't count your chickens: the match isn't over yet.",
          "Don't count your chickens: the match hasn't finished yet.",
          "Don't count your chickens: the match isn't over.",
          "Don't count your chickens: the game isn't over yet.",
          "Don't count your chickens: the game hasn't finished yet.",
          "Don't count your chickens: the game isn't over.",
          "Don't celebrate too soon: the match isn't over yet.",
          "Don't celebrate too soon: the match hasn't finished yet.",
          "Don't celebrate too soon: the match isn't over.",
          "Don't celebrate too soon: the game isn't over yet.",
          "Don't celebrate too soon: the game hasn't finished yet.",
          "Don't celebrate too soon: the game isn't over.",
          "Don't celebrate too early: the match isn't over yet.",
          "Don't celebrate too early: the match hasn't finished yet.",
          "Don't celebrate too early: the match isn't over.",
          "Don't celebrate too early: the game isn't over yet.",
          "Don't celebrate too early: the game hasn't finished yet.",
          "Don't celebrate too early: the game isn't over.",
          "Don't speak too soon: the match isn't over yet.",
          "Don't speak too soon: the match hasn't finished yet.",
          "Don't speak too soon: the match isn't over.",
          "Don't speak too soon: the game isn't over yet.",
          "Don't speak too soon: the game hasn't finished yet.",
          "Don't speak too soon: the game isn't over.",
        ],
        explanation: "«No cantes victoria antes de tiempo» ≈ \"Don't count your chickens (before they hatch)\". \"Don't celebrate too soon\" is the plain version.",
      },
      {
        type: "multiple-choice",
        question: "A learner translates «Camarón que se duerme se lo lleva la corriente» as *The shrimp that sleeps is carried away by the current. What should they say?",
        options: [
          "You snooze, you lose.",
          "The early shrimp catches the current.",
          "Still waters run deep.",
          "Let sleeping dogs lie.",
        ],
        correctIndex: 0,
        explanation: "\"You snooze, you lose\" carries the same warning. \"Let sleeping dogs lie\" is a real proverb, but it means «no remuevas el asunto», and \"Still waters run deep\" is about quiet people.",
      },
      {
        type: "matching",
        instructions: "Match each English proverb to its Spanish equivalent.",
        pairs: [
          { left: "Better late than never.", right: "Más vale tarde que nunca." },
          { left: "Birds of a feather flock together.", right: "Dios los cría y ellos se juntan." },
          { left: "Practice makes perfect.", right: "La práctica hace al maestro." },
          { left: "Actions speak louder than words.", right: "Obras son amores, que no buenas razones." },
          { left: "Out of the frying pan into the fire.", right: "Salir de Guatemala para entrar en Guatepeor." },
          { left: "It never rains but it pours.", right: "Las desgracias nunca vienen solas." },
        ],
        explanation: "These pairs share the same idea, though the images are completely different. That is why literal translation fails.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Ya sabes lo que dicen: a la tercera va la vencida.",
        answer: "You know what they say: third time's the charm.",
        altAnswers: [
          "You know what they say: third time lucky.",
          "You know what they say: the third time's the charm.",
          "You know what they say: third time's a charm.",
          "As they say: third time lucky.",
          "As they say: third time's the charm.",
          "As they say: the third time's the charm.",
          "As they say: third time's a charm.",
        ],
        explanation: "«A la tercera va la vencida» = \"third time lucky\" (British) or \"third time's the charm\" (American).",
      },
      {
        type: "multiple-choice",
        question: "A headline reads: WHERE THERE'S A WILL, THERE'S A LAWYER. What is the joke?",
        options: [
          "It twists \"Where there's a will, there's a way\"; here \"will\" also means a legal document («testamento»).",
          "It twists \"Where there's smoke, there's fire\"; lawyers cause trouble.",
          "It twists \"Where there's a will, there's a way\"; lawyers are very determined people.",
          "It twists \"Every cloud has a silver lining\"; inheritances are good news.",
        ],
        correctIndex: 0,
        explanation: "The pun plays on two meanings of \"will\": determination («voluntad») and a legal document («testamento»). Wherever there is an inheritance, lawyers appear.",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "Every cloud has a silver ___.",
        answer: "lining",
        en: "Toda nube tiene un [forro] de plata (= «no hay mal que por bien no venga»).",
        explanation: "\"Lining\" («forro») is the inner layer of a coat; the image is the bright edge around a dark cloud. The proverb is often shortened to \"There's a silver lining\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Más vale prevenir que curar, así que lleva paraguas.",
        answer: "Better safe than sorry, so take an umbrella.",
        altAnswers: [
          "Better safe than sorry, so bring an umbrella.",
          "Better to be safe than sorry, so take an umbrella.",
          "Better to be safe than sorry, so bring an umbrella.",
          "Prevention is better than cure, so take an umbrella.",
          "Prevention is better than cure, so bring an umbrella.",
        ],
        explanation: "Both \"Better safe than sorry\" and \"Prevention is better than cure\" work. In everyday talk the first is more common.",
      },
      {
        type: "multiple-choice",
        question: "Which version is the real proverb?",
        options: [
          "Absence makes the heart grow fonder.",
          "Absence makes fonder the heart grow.",
          "The absence makes the heart grow more fond.",
          "Absence makes the heart to grow fonder.",
        ],
        correctIndex: 0,
        explanation: "\"Make\" + object + bare infinitive (\"grow\"), no article before the abstract noun \"absence\", and the comparative \"fonder\".",
      },
      {
        type: "multiple-choice",
        question: "Your friend keeps lifting the lid of a pot and complaining that the water won't boil. What do you say?",
        options: [
          "A watched pot never boils.",
          "Still waters run deep.",
          "Don't cry over spilt milk.",
          "Too many cooks spoil the broth.",
        ],
        correctIndex: 0,
        explanation: "\"A watched pot never boils\" = waiting anxiously makes time pass more slowly.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "No llores sobre la leche derramada; ya no tiene remedio.",
        answer: "Don't cry over spilled milk; there's nothing you can do about it now.",
        altAnswers: [
          "Don't cry over spilt milk; it can't be helped.",
          "Don't cry over spilt milk; it can't be undone.",
          "Don't cry over spilt milk; what's done is done.",
          "Don't cry over spilt milk; there's nothing you can do about it now.",
          "Don't cry over spilled milk; it can't be helped.",
          "Don't cry over spilled milk; it can't be undone.",
          "Don't cry over spilled milk; what's done is done.",
          "It's no use crying over spilt milk; there's nothing you can do about it now.",
          "It's no use crying over spilt milk; it can't be helped.",
          "It's no use crying over spilt milk; it can't be undone.",
          "It's no use crying over spilt milk; what's done is done.",
          "It's no use crying over spilled milk; there's nothing you can do about it now.",
          "It's no use crying over spilled milk; it can't be helped.",
          "It's no use crying over spilled milk; it can't be undone.",
          "It's no use crying over spilled milk; what's done is done.",
          "There's no use crying over spilt milk; there's nothing you can do about it now.",
          "There's no use crying over spilt milk; it can't be helped.",
          "There's no use crying over spilt milk; it can't be undone.",
          "There's no use crying over spilt milk; what's done is done.",
          "There's no use crying over spilled milk; there's nothing you can do about it now.",
          "There's no use crying over spilled milk; it can't be helped.",
          "There's no use crying over spilled milk; it can't be undone.",
          "There's no use crying over spilled milk; what's done is done.",
          "There's no point crying over spilt milk; there's nothing you can do about it now.",
          "There's no point crying over spilt milk; it can't be helped.",
          "There's no point crying over spilt milk; it can't be undone.",
          "There's no point crying over spilt milk; what's done is done.",
          "There's no point crying over spilled milk; there's nothing you can do about it now.",
          "There's no point crying over spilled milk; it can't be helped.",
          "There's no point crying over spilled milk; it can't be undone.",
          "There's no point crying over spilled milk; what's done is done.",
        ],
        explanation: "Spanish and English share this one: \"Don't cry over spilt milk\" or \"It's no use crying over spilt milk\" (\"spilled\" in American English).",
      },
      {
        type: "word-order",
        prompt: "Put the words in order.",
        words: ["Don't", "look", "a", "gift", "horse", "in", "the", "mouth."],
        translation: "A caballo regalado no le mires el diente.",
        explanation: "Here English and Spanish share the image. Note \"in the mouth\", not *at the teeth.",
      },
      {
        type: "listen-choose",
        audio: "Well, you know what they say about birds of a feather.",
        question: "What is the speaker suggesting?",
        options: [
          "That people who are alike tend to spend time together.",
          "That the people mentioned are free and independent.",
          "That bad news travels fast.",
          "That the people mentioned are very different from each other.",
        ],
        correctIndex: 0,
        explanation: "\"Birds of a feather (flock together)\" = «Dios los cría y ellos se juntan». Often used with a slightly critical tone.",
      },
      {
        type: "dictation",
        audio: "People who live in glass houses shouldn't throw stones.",
        explanation: "Don't criticize others for faults you have yourself; close to «Quien tiene tejado de vidrio, que no tire piedras al del vecino».",
      },
      {
        type: "speak",
        text: "Rome wasn't built in a day, so be patient with yourself.",
        tip: "\"Wasn't built in a day\" has a strong stress on \"day\". Link \"built in\" into one sound: BIL-tin.",
        explanation: "\"Rome wasn't built in a day\" is the English version of «No se ganó Zamora en una hora».",
      },
    ],
  },
];
