// Synced from cheneygross-afk/lengo:src/lib/lessons/en-c2-u08-extra.ts by scripts/sync-content.mjs -- edit it there, not here.
import type { Lesson } from "./types";

// Extra practice (optional) lessons for EN-C2 unit u08 (euphemism and indirect language).
// Drill-focused: a short recap, then lots of exercises.

export const EN_C2_U08_EXTRA: Lesson[] = [
  // ---------------------------------------------------------------------
  // Extra 1. British understatement and indirectness
  // ---------------------------------------------------------------------
  {
    slug: "en-c2-understatement-drill-1",
    optional: true,
    level: "EN-C2",
    number: 1,
    title: "Extra Practice: British Understatement and Indirectness",
    summary: "Decode what British speakers really mean by \"not bad\", \"quite good\", \"with respect\", \"I hear what you say\" and \"a bit of a problem\", and practise softening your own messages instead of answering too directly.",
    duration: "12 min",
    sections: [
      {
        heading: "Quick recap: say less, mean more",
        body: [
          "British English (and, to a lesser degree, American English) prefers to say less than it means. \"Not bad\" is real praise; \"a bit of a problem\" is a serious problem; \"I'm not entirely convinced\" means «no estoy de acuerdo»; \"That's an interesting idea\" often means «no me gusta nada».",
          "Some phrases mean almost the opposite of their surface. \"With the greatest respect\" introduces strong disagreement. \"I hear what you say\" means «te he oído, pero no voy a cambiar de opinión». \"I'll bear it in mind\" frequently means «no lo voy a hacer».",
          "\"Quite\" is a trap. In British English \"quite good\" usually means «bastante bien, sin más» (a little disappointing); in American English it is closer to «muy bien». Tone of voice decides, so listen for it.",
        ],
        examples: [
          { es: "The food was not bad at all.", en: "La comida estaba bastante buena. (elogio sincero)" },
          { es: "We have a bit of a problem with the roof.", en: "Tenemos un problema serio con el tejado." },
          { es: "With the greatest respect, I think you've misread the data.", en: "Con todo el respeto, creo que has interpretado mal los datos. (desacuerdo fuerte)" },
          { es: "I hear what you're saying, but the deadline stays.", en: "Entiendo lo que dices, pero el plazo no cambia." },
          { es: "That's certainly an interesting idea.", en: "Es una idea... curiosa. (probablemente no le gusta)" },
          { es: "I'm not entirely convinced it will work.", en: "No me convence que vaya a funcionar." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "After your presentation, your British manager says: \"Well, that was quite good.\" What does she most likely mean?",
            options: [
              "It was acceptable, but she expected more.",
              "It was excellent and she is impressed.",
              "It was completely unacceptable.",
              "She did not pay attention to it.",
            ],
            correctIndex: 0,
            explanation: "In British English \"quite good\" with a flat tone usually means «correcto, sin más». A British speaker who is impressed says \"really good\", \"excellent\" or, ironically, \"not bad at all\".",
          },
          {
            type: "translate",
            direction: "es-en",
            prompt: "Translate into English.",
            source: "Me temo que hay un pequeño problema con tu informe.",
            answer: "I'm afraid there's a bit of a problem with your report.",
            altAnswers: [
              "I'm afraid there's a slight problem with your report.",
              "I'm afraid there's a small problem with your report.",
              "I'm afraid there is a bit of a problem with your report.",
              "I'm afraid there is a slight problem with your report.",
              "I'm afraid there is a small problem with your report.",
              "I'm afraid there's a minor problem with your report.",
              "I'm afraid there's a small issue with your report.",
              "I'm afraid there's a slight issue with your report.",
              "I'm afraid there's a bit of an issue with your report.",
            ],
            explanation: "\"I'm afraid\" softens bad news, and \"a bit of a problem\" understates it. Your listener will understand that it needs attention.",
          },
        ],
      },
      {
        heading: "Softening your own message",
        body: [
          "Spanish speakers are often perceived as blunt in English, not because of what they say but because they leave out the softeners. Compare «Esto está mal» with \"I think this might need another look.\"",
          "The main tools: hedges (\"I think\", \"perhaps\", \"it seems\"), modals (\"might\", \"could\", \"would\"), understatement (\"not ideal\", \"slightly\", \"a little\"), negative questions (\"Wouldn't it be better to...?\") and turning orders into suggestions (\"You might want to...\").",
          "Use them in proportion. One or two softeners make you sound diplomatic; five in one sentence sound evasive or sarcastic.",
        ],
        examples: [
          { es: "That's not ideal.", en: "Eso no es lo ideal. (es decir: es un problema)" },
          { es: "You might want to check the figures again.", en: "Quizá convendría que revisaras las cifras. (es decir: revísalas)" },
          { es: "Wouldn't it be better to wait until Monday?", en: "¿No sería mejor esperar al lunes?" },
          { es: "I was a little surprised not to be invited.", en: "Me sorprendió un poco que no me invitaran. (es decir: me molestó)" },
          { es: "It might not be the best time to raise prices.", en: "Puede que no sea el mejor momento para subir los precios." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "Which is the most diplomatic way to tell a colleague that his draft contains mistakes?",
            options: [
              "I think there might be one or two things worth looking at again.",
              "Your draft is full of mistakes.",
              "You must correct the mistakes in your draft.",
              "There are mistakes. Correct them, please.",
            ],
            correctIndex: 0,
            explanation: "Hedge (\"I think\", \"might\"), understate (\"one or two things\") and frame the order as a suggestion (\"worth looking at again\"). \"Please\" alone does not soften an order in English.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "matching",
        instructions: "Match each British phrase with what it usually means.",
        pairs: [
          { left: "With the greatest respect...", right: "Creo que estás muy equivocado." },
          { left: "I hear what you say.", right: "No pienso cambiar de opinión." },
          { left: "That's a very brave proposal.", right: "Es una propuesta temeraria." },
          { left: "I'll bear it in mind.", right: "Probablemente no lo haré." },
          { left: "Not bad at all.", right: "Está muy bien." },
          { left: "Could we consider some other options?", right: "No me gusta tu idea." },
        ],
        explanation: "Each phrase means more, or something different, from its literal words. \"Brave\" in a meeting often suggests «arriesgado, quizá insensato».",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "No estoy del todo convencido de que sea buena idea.",
        answer: "I'm not entirely convinced it's a good idea.",
        altAnswers: [
          "I'm not entirely convinced that it's a good idea.",
          "I'm not completely convinced it's a good idea.",
          "I'm not completely convinced that it's a good idea.",
          "I'm not totally convinced it's a good idea.",
          "I'm not totally convinced that it's a good idea.",
          "I'm not fully convinced it's a good idea.",
          "I'm not fully convinced that it's a good idea.",
          "I'm not entirely sure it's a good idea.",
          "I'm not entirely sure that it's a good idea.",
          "I'm not entirely convinced it is a good idea.",
          "I'm not entirely convinced that it is a good idea.",
        ],
        explanation: "\"Not entirely convinced\" is the classic polite disagreement: the speaker means «no estoy de acuerdo», but leaves you room to save face.",
      },
      {
        type: "multiple-choice",
        question: "A British colleague says your plan is \"a very brave decision\". What is the best interpretation?",
        options: [
          "He thinks it is risky and probably unwise.",
          "He admires your courage and fully supports it.",
          "He thinks it is boring and safe.",
          "He has not understood the plan.",
        ],
        correctIndex: 0,
        explanation: "In a work context \"brave\" or \"courageous\" often means «arriesgado» or even «una locura». It is understatement used as a warning.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Quizá convendría que revisaras el presupuesto antes de enviarlo.",
        answer: "You might want to check the budget before sending it.",
        altAnswers: [
          "You might want to check the budget before you send it.",
          "You might want to review the budget before sending it.",
          "You might want to review the budget before you send it.",
          "You may want to check the budget before sending it.",
          "You may want to check the budget before you send it.",
          "You may want to review the budget before sending it.",
          "You may want to review the budget before you send it.",
          "Perhaps you should check the budget before sending it.",
          "Perhaps you should check the budget before you send it.",
          "Perhaps you should review the budget before sending it.",
          "Perhaps you should review the budget before you send it.",
          "It might be worth checking the budget before sending it.",
          "It might be worth checking the budget before you send it.",
          "It might be worth reviewing the budget before you send it.",
          "Maybe you should check the budget before sending it.",
          "Maybe you should check the budget before you send it.",
          "You might want to go over the budget before sending it.",
          "You might want to go over the budget before you send it.",
        ],
        explanation: "\"You might want to...\" is a polite instruction disguised as a suggestion. Note: \"revise\" usually means «modificar» or «repasar para un examen», so «revisar» here is \"check\" or \"review\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "The hotel was ___, but the beach was wonderful.",
        answer: "not ideal",
        altAnswers: ["far from ideal", "less than ideal", "not great", "not the best"],
        en: "El hotel [no era lo ideal], pero la playa era maravillosa.",
        explanation: "\"Not ideal\" or \"less than ideal\" understates a real problem. Saying the hotel was \"terrible\" would sound much stronger in English than «no era lo ideal» does in Spanish.",
      },
      {
        type: "multiple-choice",
        question: "Your boss says: \"I hear what you're saying, but we'll stick with the original plan.\" What is the best reply?",
        options: [
          "Understood. I'll go ahead as planned.",
          "So you agree with me?",
          "Then why don't you change the plan?",
          "No, you don't hear me. Listen again.",
        ],
        correctIndex: 0,
        explanation: "\"I hear what you're saying\" acknowledges your view and closes the discussion. Taking it as agreement, or insisting, sounds naive or confrontational.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Me sorprendió un poco que nadie me avisara del cambio.",
        answer: "I was a little surprised that nobody told me about the change.",
        altAnswers: [
          "I was a little surprised that no one told me about the change.",
          "I was a little surprised nobody told me about the change.",
          "I was a little surprised no one told me about the change.",
          "I was a bit surprised that nobody told me about the change.",
          "I was a bit surprised that no one told me about the change.",
          "I was a bit surprised nobody told me about the change.",
          "I was a bit surprised no one told me about the change.",
          "I was slightly surprised that nobody told me about the change.",
          "I was slightly surprised nobody told me about the change.",
          "I was a little surprised that nobody warned me about the change.",
          "I was a little surprised that nobody let me know about the change.",
          "I was a bit surprised that nobody let me know about the change.",
          "I was a little surprised not to be told about the change.",
          "I was a little surprised that nobody had told me about the change.",
          "I was a bit surprised that nobody had told me about the change.",
        ],
        explanation: "\"A little surprised\" is the polite British way to complain. «Avisar» is \"tell\" or \"let know\" here; \"warn\" suggests danger, and *advise me of the change is far too formal.",
      },
      {
        type: "multiple-choice",
        question: "Which reply to \"Could you possibly finish this by Friday?\" refuses politely?",
        options: [
          "I'd love to, but I'm not sure I can manage it by Friday.",
          "No, I can't.",
          "Impossible. I'm busy.",
          "You should ask somebody else.",
        ],
        correctIndex: 0,
        explanation: "A polite refusal shows goodwill (\"I'd love to\"), hedges (\"I'm not sure\") and avoids the word \"no\". A bare \"No, I can't\" sounds rude in British English.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "¿No sería mejor esperar a que lleguen los resultados?",
        answer: "Wouldn't it be better to wait for the results to come in?",
        altAnswers: [
          "Wouldn't it be better to wait until the results come in?",
          "Wouldn't it be better to wait for the results?",
          "Wouldn't it be better to wait until the results arrive?",
          "Wouldn't it be better to wait for the results to arrive?",
          "Wouldn't it be better to wait until the results are in?",
          "Wouldn't it be better to wait until we get the results?",
          "Wouldn't it be better to wait until we have the results?",
          "Would it not be better to wait for the results?",
          "Would it not be better to wait until the results come in?",
          "Would it not be better to wait for the results to come in?",
        ],
        explanation: "A negative question (\"Wouldn't it be better...?\") is a gentle way to disagree. After \"until\" use the present (\"until the results come in\"), not *until the results will come.",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "___, I think your figures are wrong.",
        answer: "With respect",
        altAnswers: ["With all due respect", "With the greatest respect", "With all respect"],
        en: "[Con todo el respeto], creo que tus cifras están mal.",
        explanation: "\"With (all due) respect\" warns that strong disagreement follows. In British English, \"with the greatest respect\" can sound almost insulting.",
      },
      {
        type: "multiple-choice",
        question: "A guest says: \"The soup was a little on the salty side.\" What does she mean?",
        options: [
          "The soup was too salty.",
          "The soup was perfectly seasoned.",
          "She would like more salt.",
          "The salt was served on the side.",
        ],
        correctIndex: 0,
        explanation: "\"A little on the + adjective + side\" («tirando a...») softens a complaint. The real message: there was too much salt.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Puede que no sea el mejor momento para pedir un aumento.",
        answer: "It might not be the best time to ask for a raise.",
        altAnswers: [
          "It may not be the best time to ask for a raise.",
          "It might not be the best moment to ask for a raise.",
          "It may not be the best moment to ask for a raise.",
          "It might not be the best time to ask for a pay rise.",
          "It may not be the best time to ask for a pay rise.",
          "It might not be the best moment to ask for a pay rise.",
          "It might not be the best time to ask for a pay raise.",
          "It may not be the best time to ask for a pay raise.",
          "This might not be the best time to ask for a raise.",
          "This may not be the best time to ask for a raise.",
          "This might not be the best time to ask for a pay rise.",
          "Now might not be the best time to ask for a raise.",
          "Now may not be the best time to ask for a raise.",
          "Now might not be the best time to ask for a pay rise.",
        ],
        explanation: "\"Might not be the best time\" is the polite way to say «no es momento». American English says \"a raise\"; British English says \"a pay rise\". *Ask for a rise of salary is a calque.",
      },
      {
        type: "matching",
        instructions: "Match each blunt statement with its understated version.",
        pairs: [
          { left: "It's terrible.", right: "It's not the best." },
          { left: "I'm furious.", right: "I'm a little disappointed." },
          { left: "You're wrong.", right: "I'm not sure that's quite right." },
          { left: "Do it now.", right: "When you have a moment, could you...?" },
          { left: "It's a disaster.", right: "We've had a bit of a setback." },
        ],
        explanation: "Understatement lowers the intensity of every word, and the listener raises it back. The understated version carries the same message more politely.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Lo tendré en cuenta, gracias.",
        answer: "I'll bear it in mind, thanks.",
        altAnswers: [
          "I'll bear that in mind, thanks.",
          "I'll bear it in mind, thank you.",
          "I'll bear that in mind, thank you.",
          "I'll keep it in mind, thanks.",
          "I'll keep that in mind, thanks.",
          "I'll keep it in mind, thank you.",
          "I'll keep that in mind, thank you.",
          "I'll take it into account, thanks.",
          "I'll take that into account, thanks.",
          "I'll take it into account, thank you.",
          "I'll take that into account, thank you.",
          "Thanks, I'll bear it in mind.",
          "Thanks, I'll bear that in mind.",
          "Thanks, I'll keep that in mind.",
          "Thank you, I'll bear that in mind.",
        ],
        explanation: "\"I'll bear it in mind\" («lo tendré en cuenta») can be sincere, but in British English it is often a polite way to dismiss advice. *I'll have it in account is a calque.",
      },
      {
        type: "listen-choose",
        audio: "It's not the end of the world, but it's not exactly what we were hoping for.",
        question: "How does the speaker feel about the result?",
        options: [
          "Disappointed, but trying not to sound dramatic.",
          "Delighted and relieved.",
          "Completely devastated.",
          "Indifferent; it was what they expected.",
        ],
        correctIndex: 0,
        explanation: "\"Not exactly what we were hoping for\" is understatement for «decepcionante», and \"not the end of the world\" keeps the tone calm.",
      },
      {
        type: "write",
        prompt: "A colleague has sent you a project proposal with a serious flaw: the budget is far too low. Write a short, diplomatic reply in British style that makes the problem clear without sounding blunt.",
        minWords: 50,
        maxWords: 100,
        rubric: [
          "Starts with something positive about the proposal.",
          "Raises the budget problem with hedges and understatement (\"a bit\", \"might\", \"not entirely\").",
          "Turns the request into a suggestion (\"You might want to...\", \"Could we...?\").",
          "The real message (the budget must change) is still clear.",
        ],
        modelAnswer: "Thanks for sending this over. I really like the overall structure, and the timeline looks very realistic. I'm not entirely convinced the budget is quite right, though. My worry is that the figure for staff might be a little on the low side, given the scope of the work. You might want to have another look at it before we share it with the client. Happy to go through it together if that would help.",
        explanation: "The model praises first, hedges the criticism (\"not entirely convinced\", \"a little on the low side\") and closes with an offer of help. A British reader will understand that the budget must be revised.",
      },
      {
        type: "speak",
        text: "I'm not entirely sure that's quite right, but I might be wrong.",
        tip: "Understatement lives in the intonation: keep the voice soft and slightly rising on \"quite right\" and \"wrong\", and don't stress \"not\" heavily.",
        explanation: "Hedged disagreement with a face-saving tag (\"but I might be wrong\") is typical of British meetings.",
      },
    ],
  },
];
