// Synced from cheneygross-afk/lengo:src/lib/lessons/en-c2-u10-extra.ts by scripts/sync-content.mjs -- edit it there, not here.
import type { Lesson } from "./types";

// Extra practice (optional) lessons for EN-C2 unit u10 (business idioms and register).
// Drill-focused: a short recap, then lots of exercises.

export const EN_C2_U10_EXTRA: Lesson[] = [
  // ---------------------------------------------------------------------
  // Extra 1. Business verb-noun collocations
  // ---------------------------------------------------------------------
  {
    slug: "en-c2-business-collocations-drill-1",
    optional: true,
    level: "EN-C2",
    number: 1,
    title: "Extra Practice: Business Verb-Noun Collocations",
    summary: "Drill the verb + noun pairs of business English (make a profit, run a business, meet a deadline, reach an agreement, raise capital, launch a product, take over a company, hold a meeting) and the «hacer» and «realizar» calques that creep into emails.",
    duration: "12 min",
    sections: [
      {
        heading: "Quick recap: hacer, realizar and the verbs English actually uses",
        body: [
          "«Hacer» splits into several English verbs: you \"make\" a profit, a loss, money, a deal, an offer, an appointment; you \"do\" business, a job, research; you \"place\" an order. *Do a profit and *make business are classic errors.",
          "«Realizar» is almost never \"realize\", which means «darse cuenta». A meeting is \"held\", a survey or an audit is \"carried out\" or \"conducted\", a payment is \"made\", a project is \"carried out\" or \"completed\", a sale is \"made\" or \"closed\".",
          "Other key pairs: \"run\" or \"manage\" a business («llevar un negocio»), \"set up\" or \"start\" a company («montar una empresa»), \"raise\" capital or funds («captar capital»), \"launch\" a product, \"meet\" a deadline or a target, \"reach\" or \"strike\" an agreement, \"take over\" a company («absorber, adquirir»), \"cut\" costs.",
        ],
        examples: [
          { es: "The company made a profit for the first time last year.", en: "La empresa obtuvo beneficios por primera vez el año pasado. (incorrecto: *did a profit)" },
          { es: "We've been doing business with them for ten years.", en: "Llevamos diez años haciendo negocios con ellos. (incorrecto: *making business)" },
          { es: "The board meeting will be held on Thursday.", en: "La reunión del consejo se celebrará el jueves. (incorrecto: *realized)" },
          { es: "She runs a small design business.", en: "Lleva un pequeño negocio de diseño." },
          { es: "They raised two million euros from investors.", en: "Captaron dos millones de euros de inversores." },
          { es: "A larger rival took over the firm in 2023.", en: "Un rival más grande absorbió la empresa en 2023." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "Which sentence is natural business English?",
            options: [
              "We will hold a meeting with the suppliers next week.",
              "We will realize a meeting with the suppliers next week.",
              "We will do a meeting with the suppliers next week.",
              "We will celebrate a meeting with the suppliers next week.",
            ],
            correctIndex: 0,
            explanation: "Meetings are \"held\" (or simply \"We'll meet the suppliers\"). *Realize a meeting and *celebrate a meeting are calques of «realizar» and «celebrar».",
          },
          {
            type: "translate",
            direction: "es-en",
            prompt: "Translate into English.",
            source: "Este trimestre hemos obtenido muchos beneficios.",
            answer: "We've made a big profit this quarter.",
            altAnswers: [
              "We've made a large profit this quarter.",
              "We've made a lot of profit this quarter.",
              "We've made a healthy profit this quarter.",
              "We've made a good profit this quarter.",
              "We've made big profits this quarter.",
              "We've made large profits this quarter.",
              "We've made huge profits this quarter.",
              "We've made a huge profit this quarter.",
              "We've made a lot of money this quarter.",
              "This quarter we've made a big profit.",
              "This quarter we've made big profits.",
              "We have made a big profit this quarter.",
              "We've made substantial profits this quarter.",
              "We've made a substantial profit this quarter.",
            ],
            explanation: "«Obtener beneficios» is \"make a profit\" (or \"make profits\"). \"Benefits\" are «ventajas» or «prestaciones», not «beneficios económicos».",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Si no cumplimos el objetivo de ventas, habrá recortes.",
        answer: "If we don't meet the sales target, there will be cuts.",
        altAnswers: [
          "If we don't hit the sales target, there will be cuts.",
          "If we don't reach the sales target, there will be cuts.",
          "If we don't achieve the sales target, there will be cuts.",
          "If we miss the sales target, there will be cuts.",
          "If we fail to meet the sales target, there will be cuts.",
          "If we don't meet our sales target, there will be cuts.",
          "If we don't hit our sales target, there will be cuts.",
          "If we miss our sales target, there will be cuts.",
          "There will be cuts if we don't meet the sales target.",
          "There will be cuts if we miss the sales target.",
          "If we don't meet the sales target, there'll be cuts.",
          "If we don't meet the sales target, there will be cutbacks.",
        ],
        explanation: "Targets and deadlines are \"met\", \"hit\" or \"reached\"; the opposite is \"miss\". *Fulfil the target is a calque of «cumplir».",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "We'd like to ___ for 500 units.",
        answer: "place an order",
        altAnswers: ["put in an order", "make an order"],
        en: "Nos gustaría [hacer un pedido] de 500 unidades.",
        explanation: "«Hacer un pedido» is \"place an order\" (informally \"put in an order\"). \"Make an order\" is sometimes heard but sounds less professional.",
      },
      {
        type: "matching",
        instructions: "Match each collocation with its Spanish equivalent.",
        pairs: [
          { left: "set up a company", right: "montar una empresa" },
          { left: "raise capital", right: "captar capital" },
          { left: "launch a product", right: "lanzar un producto" },
          { left: "cut costs", right: "reducir gastos" },
          { left: "close a deal", right: "cerrar un trato" },
          { left: "go bankrupt", right: "quebrar" },
        ],
        explanation: "Only \"launch\" and \"close\" mirror the Spanish verb. «Montar» is \"set up\", «captar» is \"raise\" and «quebrar» is \"go bankrupt\" (or \"go bust\").",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Las dos empresas llegaron a un acuerdo después de meses de negociaciones.",
        answer: "The two companies reached an agreement after months of negotiations.",
        altAnswers: [
          "The two companies reached an agreement after months of negotiation.",
          "The two companies came to an agreement after months of negotiations.",
          "The two companies came to an agreement after months of negotiation.",
          "The two companies struck a deal after months of negotiations.",
          "The two companies struck a deal after months of negotiation.",
          "The two companies reached a deal after months of negotiations.",
          "The two companies reached a deal after months of negotiation.",
          "The two firms reached an agreement after months of negotiations.",
          "The two firms reached an agreement after months of negotiation.",
          "After months of negotiations, the two companies reached an agreement.",
          "After months of negotiation, the two companies reached an agreement.",
          "The two companies reached an agreement after months of talks.",
          "After months of talks, the two companies reached an agreement.",
        ],
        explanation: "«Llegar a un acuerdo» is \"reach\" or \"come to an agreement\", or \"strike a deal\". *Arrive at an agreement exists, but it is much less common.",
      },
      {
        type: "multiple-choice",
        question: "Correct the learner's email: *We realized a survey of 2,000 customers.",
        options: [
          "We carried out a survey of 2,000 customers.",
          "We made a survey of 2,000 customers.",
          "We realized a survey to 2,000 customers.",
          "We did realize a survey of 2,000 customers.",
        ],
        correctIndex: 0,
        explanation: "Surveys, studies and audits are \"carried out\" or \"conducted\". \"Realize\" means «darse cuenta» or, in finance, «materializar una ganancia».",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Mi padre llevó la tienda durante treinta años.",
        answer: "My father ran the shop for thirty years.",
        altAnswers: [
          "My father ran the store for thirty years.",
          "My dad ran the shop for thirty years.",
          "My dad ran the store for thirty years.",
          "My father managed the shop for thirty years.",
          "My father managed the store for thirty years.",
          "My father ran the shop for 30 years.",
          "My father had the shop for thirty years.",
          "My father had the store for thirty years.",
        ],
        explanation: "«Llevar un negocio» is \"run\" a business (past: \"ran\"). *Carried the shop is a calque of «llevar».",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "The start-up is trying to ___ to expand into Asia.",
        answer: "raise funds",
        altAnswers: ["raise money", "raise capital", "raise funding", "raise finance", "secure funding"],
        en: "La empresa emergente intenta [captar fondos] para expandirse en Asia.",
        explanation: "Money from investors is \"raised\": \"raise funds\", \"raise capital\", \"raise money\". *Capture funds is a calque of «captar».",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Un grupo estadounidense absorbió la empresa el año pasado.",
        answer: "An American group took over the company last year.",
        altAnswers: [
          "A US group took over the company last year.",
          "An American group took the company over last year.",
          "A US group took the company over last year.",
          "An American group acquired the company last year.",
          "A US group acquired the company last year.",
          "An American group bought the company last year.",
          "A US group bought the company last year.",
          "An American group took over the firm last year.",
          "Last year an American group took over the company.",
          "Last year a US group took over the company.",
          "An American conglomerate took over the company last year.",
        ],
        explanation: "«Absorber» or «adquirir» a company is \"take over\" or \"acquire\" (noun: \"a takeover\"). *Absorbed the company sounds like a sponge.",
      },
      {
        type: "multiple-choice",
        question: "Choose the right verb: \"Our company has been ___ a lot of business with Latin America.\"",
        options: ["doing", "making", "having", "realizing"],
        correctIndex: 0,
        explanation: "You \"do business\" (with someone). *Make business is a «hacer» calque, and \"make\" goes with the results: \"make money\", \"make a profit\".",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Vamos a lanzar el nuevo modelo en primavera.",
        answer: "We're going to launch the new model in the spring.",
        altAnswers: [
          "We're going to launch the new model in spring.",
          "We're launching the new model in the spring.",
          "We're launching the new model in spring.",
          "We will launch the new model in the spring.",
          "We will launch the new model in spring.",
          "We'll launch the new model in spring.",
          "We'll launch the new model in the spring.",
          "We're going to bring out the new model in the spring.",
          "We're going to bring out the new model in spring.",
          "We're going to release the new model in the spring.",
          "We're going to release the new model in spring.",
          "We plan to launch the new model in the spring.",
          "We plan to launch the new model in spring.",
        ],
        explanation: "Products are \"launched\", \"brought out\" or \"released\", as in Spanish «lanzar». Seasons can take \"the\" or not: \"in (the) spring\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "Unfortunately, the company ___ in its first year.",
        answer: "made a loss",
        altAnswers: ["made a big loss", "made losses", "lost money", "ran at a loss", "posted a loss", "recorded a loss", "reported a loss"],
        en: "Por desgracia, la empresa [tuvo pérdidas] en su primer año.",
        explanation: "\"Make a loss\" is the opposite of \"make a profit\". In financial reports you will also see \"post\" or \"report a loss\". *Had losses is understandable but unidiomatic.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Tenemos que reducir gastos sin despedir a nadie.",
        answer: "We need to cut costs without firing anyone.",
        altAnswers: [
          "We need to cut costs without laying anyone off.",
          "We need to cut costs without making anyone redundant.",
          "We need to cut costs without letting anyone go.",
          "We have to cut costs without firing anyone.",
          "We have to cut costs without laying anyone off.",
          "We have to cut costs without making anyone redundant.",
          "We have to cut costs without letting anyone go.",
          "We need to reduce costs without firing anyone.",
          "We need to reduce costs without laying anyone off.",
          "We have to reduce costs without firing anyone.",
          "We have to reduce costs without laying anyone off.",
          "We need to cut costs without dismissing anyone.",
          "We need to cut spending without laying anyone off.",
        ],
        explanation: "\"Cut costs\" («reducir gastos»). For «despedir» business English prefers \"lay off\" or \"make redundant\" (British) when jobs disappear; \"fire\" suggests the person did something wrong.",
      },
      {
        type: "multiple-choice",
        question: "Which sentence would you write in a formal email?",
        options: [
          "Payment must be made within 30 days of the invoice date.",
          "Payment must be done within 30 days of the invoice date.",
          "Payment must be realized within 30 days of the invoice date.",
          "Payment must be paid within 30 days of the invoice date.",
        ],
        correctIndex: 0,
        explanation: "Payments are \"made\" («realizar un pago»). *Payment must be paid is redundant, and *done or *realized are calques of «realizar».",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Pedí cita con el asesor fiscal para el lunes.",
        answer: "I made an appointment with the tax adviser for Monday.",
        altAnswers: [
          "I made an appointment with the tax advisor for Monday.",
          "I made an appointment with the tax consultant for Monday.",
          "I booked an appointment with the tax adviser for Monday.",
          "I booked an appointment with the tax advisor for Monday.",
          "I made an appointment with the accountant for Monday.",
          "I booked an appointment with the accountant for Monday.",
          "I made an appointment with my tax adviser for Monday.",
          "I made an appointment with my tax advisor for Monday.",
          "I made an appointment with my accountant for Monday.",
          "I scheduled an appointment with the tax adviser for Monday.",
          "I scheduled an appointment with the tax advisor for Monday.",
        ],
        explanation: "«Pedir cita» is \"make\" or \"book an appointment\". *Asked for a date sounds romantic: a \"date\" is «una cita amorosa» or «una fecha».",
      },
      {
        type: "word-order",
        prompt: "Put the words in order.",
        words: ["We", "worked", "all", "weekend", "to", "meet", "the", "deadline."],
        translation: "Trabajamos todo el fin de semana para cumplir el plazo.",
        explanation: "\"Meet a deadline\" («cumplir un plazo»). Its opposite is \"miss a deadline\".",
      },
      {
        type: "listen-choose",
        audio: "After the merger, the new management decided to streamline operations and cut costs.",
        question: "What did the new management decide?",
        options: [
          "To make the business more efficient and spend less.",
          "To hire more staff and expand.",
          "To sell the company to a competitor.",
          "To merge with another firm.",
        ],
        correctIndex: 0,
        explanation: "\"Streamline operations\" («racionalizar procesos») and \"cut costs\" both point to efficiency. The merger had already happened.",
      },
      {
        type: "write",
        prompt: "Write a short email to a client confirming a meeting next week and updating them on the project. Use at least four business collocations from this lesson (for example: hold a meeting, meet the deadline, place an order, reach an agreement, cut costs).",
        minWords: 60,
        maxWords: 110,
        rubric: [
          "Confirms the meeting: day, time and place.",
          "Uses at least four correct verb + noun collocations.",
          "Avoids «realizar» and «hacer» calques (*realize a meeting, *do a profit).",
          "Professional, friendly register with a clear closing.",
        ],
        modelAnswer: "Dear Ms Turner,\n\nI'm writing to confirm that the project meeting will be held at our offices on Tuesday at 10 a.m. I'm pleased to say that we are on track to meet the March deadline, and our supplier has agreed to cut costs on the packaging. Once we reach an agreement on the final design, we will be able to place the order for the first 5,000 units.\n\nPlease let me know if you would like to add anything to the agenda.\n\nBest regards,\nDiego Romero",
        explanation: "The model uses \"be held\", \"meet the deadline\", \"cut costs\", \"reach an agreement\" and \"place the order\" in a natural, professional email.",
      },
    ],
  },
];
