// Synced from cheneygross-afk/lengo:src/lib/lessons/en-c2-u15-extra.ts by scripts/sync-content.mjs -- edit it there, not here.
import type { Lesson } from "./types";

// Extra practice (optional) lessons for EN-C2 unit u15 (presentations and
// negotiation). Drill-focused: a short recap, then lots of exercises.

export const EN_C2_U15_EXTRA: Lesson[] = [
  {
    slug: "en-c2-signposting-stress-drill-1",
    optional: true,
    level: "EN-C2",
    number: 1,
    title: "Extra Practice: Signposting and Sentence Stress",
    summary: "Drill the signposts that guide an audience through a talk (\"moving on to\", \"to put this in context\", \"the key takeaway is\") together with the stress pattern that makes them work: weak function words, strong new information. Avoid calques like *passing to the next point and flat, syllable-timed delivery.",
    duration: "12 min",
    sections: [
      {
        heading: "Quick recap: the signposts of a talk",
        body: [
          "A talk has a skeleton, and signposts make it audible. Opening the map: \"I've divided my talk into three parts.\" Moving on: \"Moving on to...\", \"Let's turn now to...\", \"That leads me to...\". Zooming out: \"To put this in context...\", \"To give you a sense of scale...\". Recapping: \"So far, we've seen that...\". Landing: \"The key takeaway is...\", \"If you remember one thing from today, ...\".",
          "Watch the calques. «Pasando al siguiente punto» is \"Moving on to the next point\", not *passing to the next point. «Para que se hagan una idea» is \"to give you an idea\" or \"to give you a sense of\", not *so that you make an idea. «En resumidas cuentas» is \"in short\" or \"the bottom line is\", not *in summarized accounts.",
          "Signposts are short and frequent in English. A Spanish-style long transitional sentence (\"Once we have analyzed the first aspect, we will now proceed to...\") sounds stiff; \"Right. Now let's look at costs.\" sounds confident.",
        ],
        examples: [
          { es: "Moving on to the next point: the budget.", en: "Pasando al siguiente punto: el presupuesto." },
          { es: "To put this in context, that's twice what we spent last year.", en: "Para ponerlo en contexto, es el doble de lo que gastamos el año pasado." },
          { es: "To give you a sense of scale, that's about forty trucks a day.", en: "Para que se hagan una idea de la magnitud, son unos cuarenta camiones al día." },
          { es: "So far, we've seen that demand is growing.", en: "Hasta ahora, hemos visto que la demanda está creciendo." },
          { es: "The key takeaway is that speed matters more than price.", en: "La idea clave es que la rapidez importa más que el precio." },
          { es: "I'll come back to that in a minute.", en: "Volveré sobre eso en un momento." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "You want to show the audience how big a number really is. Which signpost fits?",
            options: [
              "To give you a sense of scale, ...",
              "Passing to the scale, ...",
              "So that you make an idea, ...",
              "In summarized accounts, ...",
            ],
            correctIndex: 0,
            explanation: "\"To give you a sense of scale\" (or \"To put this in perspective\") introduces a comparison that makes a figure concrete. The other options are calques from Spanish.",
          },
          {
            type: "translate",
            direction: "es-en",
            prompt: "Translate into English.",
            source: "En resumidas cuentas, necesitamos más tiempo.",
            answer: "In short, we need more time.",
            altAnswers: [
              "In a nutshell, we need more time.",
              "The bottom line is that we need more time.",
              "The bottom line is we need more time.",
              "In brief, we need more time.",
              "To sum up, we need more time.",
              "Long story short, we need more time.",
              "In a word, we need more time.",
            ],
            explanation: "«En resumidas cuentas» is \"in short\", \"in a nutshell\" or \"the bottom line is\". Never translate it word for word.",
          },
        ],
      },
      {
        heading: "Stress the new information",
        body: [
          "In English, the main stress of a phrase falls on its last content word by default, and it moves to whatever word is new or contrasting. In a signpost, the signpost itself is old news; the topic it introduces is new. So: \"Moving on to the BUDGET.\" \"That leads me to my THIRD point.\" \"The key takeaway is SPEED.\"",
          "Function words in a signpost are reduced: \"to\" becomes /tə/, \"the\" is quick, \"that\" in \"the key takeaway is that...\" becomes /ðət/. Stressing them (*MOVING ON TO THE budget, with equal weight on every syllable) is the syllable-timed delivery that makes Spanish speakers sound flat or robotic.",
          "Contrast pulls the stress: \"We didn't cut PRICES; we cut COSTS.\" \"Last year it was a PROBLEM. This year it's a CRISIS.\" Pause briefly before the key word and give it extra length and a higher pitch.",
        ],
        examples: [
          { es: "Let's turn now to the results.", en: "Pasemos ahora a los resultados. (acento en \"results\")" },
          { es: "That leads me to my third point.", en: "Eso me lleva a mi tercer punto. (acento en \"third\")" },
          { es: "We didn't cut prices; we cut costs.", en: "No bajamos los precios; recortamos los costes. (contraste: \"prices\" / \"costs\")" },
          { es: "If you remember one thing from today, remember this.", en: "Si recuerdan una sola cosa de hoy, que sea esta." },
          { es: "It isn't a technical problem. It's a people problem.", en: "No es un problema técnico. Es un problema de personas." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "In \"That leads me to my third point\", which word normally carries the main stress?",
            options: ["third", "to", "me", "my"],
            correctIndex: 0,
            explanation: "\"Point\" is predictable in a talk; \"third\" is the new information, so it gets the main stress. Pronouns and prepositions stay weak.",
          },
          {
            type: "listen-choose",
            audio: "We didn't cut prices; we cut costs.",
            question: "Which two words should carry the strongest stress?",
            options: ["prices and costs", "didn't and cut", "we and we", "cut and cut"],
            correctIndex: 0,
            explanation: "The sentence contrasts two objects, so the stress falls on them: PRICES and COSTS. The repeated verb \"cut\" is old information.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Pasando al siguiente punto: la competencia.",
        answer: "Moving on to the next point: the competition.",
        altAnswers: [
          "Moving on to the next point: competition.",
          "Moving on to the next point: our competitors.",
          "Moving on to the next point: the competitors.",
          "Moving on to my next point: the competition.",
          "Let's move on to the next point: the competition.",
          "Turning to the next point: the competition.",
        ],
        explanation: "«Pasar a» in a talk is \"move on to\" or \"turn to\", never *pass to.",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "___, that's more than our entire marketing budget for the year.",
        answer: "To put this in perspective",
        altAnswers: ["To put this in context", "To put that in perspective", "To put that in context", "To put it in perspective", "To put it in context"],
        en: "[Para ponerlo en perspectiva], es más que todo nuestro presupuesto de marketing del año.",
        explanation: "\"To put this in perspective\" or \"in context\" introduces a comparison that makes a figure meaningful.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Hasta ahora, hemos visto que los costes están bajo control.",
        answer: "So far, we've seen that costs are under control.",
        altAnswers: [
          "So far we have seen that costs are under control.",
          "Up to now, we've seen that costs are under control.",
          "So far, we've seen that our costs are under control.",
          "Up to this point, we've seen that costs are under control.",
        ],
        explanation: "A short recap with \"So far, we've seen...\" uses the present perfect because it sums up the talk up to now.",
      },
      {
        type: "multiple-choice",
        question: "You want to end your talk with the one idea you want people to keep. Which is the most natural?",
        options: [
          "The key takeaway is that small changes add up.",
          "The key take-out of all is that small changes add up.",
          "As final conclusion, small changes add up.",
          "Concluding, I would like to finalize saying small changes add up.",
        ],
        correctIndex: 0,
        explanation: "\"The key takeaway is...\" is the standard business signpost. «Como conclusión final» is \"in conclusion\" or \"to conclude\", and *finalize saying is a calque.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Para que se hagan una idea, eso equivale a tres campos de fútbol.",
        answer: "To give you an idea, that's the equivalent of three soccer fields.",
        altAnswers: [
          "To give you an idea, that's the equivalent of three football pitches.",
          "To give you an idea, that's equivalent to three soccer fields.",
          "To give you an idea, that's equivalent to three football pitches.",
          "To give you a sense of scale, that's the equivalent of three soccer fields.",
          "To give you a sense of scale, that's equivalent to three soccer fields.",
          "To give you an idea, that's about three soccer fields.",
          "To give you an idea, that's the size of three soccer fields.",
          "To give you an idea, that's the size of three football pitches.",
          "To give you an idea, that's equal to three soccer fields.",
        ],
        explanation: "«Para que se hagan una idea» is \"to give you an idea\", not *so that you make an idea. American English says \"soccer field\", British \"football pitch\".",
      },
      {
        type: "multiple-choice",
        question: "Where does the main stress fall in \"Let's turn now to the results\"?",
        options: ["results", "to", "the", "let's"],
        correctIndex: 0,
        explanation: "\"Results\" is the new topic and the last content word, so it carries the main stress. \"To\" and \"the\" are reduced to weak forms.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "No es un problema de dinero; es un problema de tiempo.",
        answer: "It isn't a money problem; it's a time problem.",
        altAnswers: [
          "It's not a money problem; it's a time problem.",
          "It isn't a problem of money; it's a problem of time.",
          "It's not a problem of money; it's a problem of time.",
          "It isn't about money; it's about time.",
          "It's not about money; it's about time.",
          "The problem isn't money; it's time.",
        ],
        explanation: "English uses a noun as a modifier: \"a money problem\", \"a time problem\". In speech, stress MONEY and TIME, the contrasting words, not \"problem\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the bold words in English.",
        sentence: "I'll ___ to that later, when we look at the figures.",
        answer: "come back",
        altAnswers: ["return", "get back", "go back"],
        en: "[Volveré] sobre eso más tarde, cuando veamos las cifras.",
        explanation: "\"I'll come back to that\" postpones a point politely. «Volver sobre» is \"come back to\", not *return over.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order.",
        words: ["If", "you", "remember", "one", "thing", "from", "today,", "remember", "this."],
        translation: "Si recuerdan una sola cosa de hoy, que sea esta.",
        explanation: "A classic landing signpost. Pause after \"today\" and stress THIS: it is the cue for the key message.",
      },
      {
        type: "matching",
        instructions: "Match each signpost with its function.",
        pairs: [
          { left: "I've divided my talk into three parts.", right: "presentar la estructura" },
          { left: "Moving on to costs...", right: "cambiar de tema" },
          { left: "To put this in context...", right: "dar perspectiva a una cifra" },
          { left: "So far, we've seen that...", right: "resumir a mitad de la charla" },
          { left: "The key takeaway is...", right: "destacar la idea principal" },
        ],
        explanation: "A well-signposted talk uses all five functions: map, transition, context, recap and takeaway.",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Esto me lleva a la cuestión más delicada: los despidos.",
        answer: "This leads me to the most sensitive issue: layoffs.",
        altAnswers: [
          "That leads me to the most sensitive issue: layoffs.",
          "This brings me to the most sensitive issue: layoffs.",
          "That brings me to the most sensitive issue: layoffs.",
          "This leads me to the most delicate issue: layoffs.",
          "That brings me to the most delicate issue: layoffs.",
          "This brings me to the most delicate issue: layoffs.",
          "That leads me to the most delicate issue: layoffs.",
          "This brings me to the most sensitive issue: job cuts.",
          "That brings me to the most sensitive issue: job cuts.",
          "This brings me to the most sensitive question: layoffs.",
          "That brings me to the most sensitive question: layoffs.",
        ],
        explanation: "\"That brings/leads me to...\" links one section to the next. «Delicado» is \"sensitive\" or \"delicate\"; «despidos» are \"layoffs\" or \"job cuts\".",
      },
      {
        type: "multiple-choice",
        question: "A colleague delivers \"Moving on to the budget\" giving every syllable the same length and force. What is the main problem?",
        options: [
          "It sounds flat: the weak words should be reduced so that \"budget\" stands out.",
          "It is grammatically wrong: it should be \"Moving to the budget\".",
          "It is too informal for a presentation.",
          "\"Budget\" should be stressed on the second syllable.",
        ],
        correctIndex: 0,
        explanation: "English is stress-timed. Reduce \"to the\" and let BUDGET carry the stress (on its first syllable: BUD-get).",
      },
      {
        type: "translate",
        direction: "es-en",
        prompt: "Translate into English.",
        source: "Antes de pasar a las preguntas, permítanme resumir los tres puntos principales.",
        answer: "Before we move on to questions, let me summarize the three main points.",
        altAnswers: [
          "Before we move on to questions, let me sum up the three main points.",
          "Before we go on to questions, let me summarize the three main points.",
          "Before moving on to questions, let me summarize the three main points.",
          "Before moving on to questions, let me sum up the three main points.",
          "Before we turn to questions, let me summarize the three main points.",
          "Before we move on to the questions, let me summarize the three main points.",
          "Before we take questions, let me summarize the three main points.",
          "Before we move on to questions, let me recap the three main points.",
          "Before we move on to questions, allow me to summarize the three main points.",
        ],
        explanation: "\"Let me\" + verb is the natural way to say «permítanme» in a talk; \"allow me to\" is more formal. Note \"summarize\" with no preposition: never *summarize about.",
      },
      {
        type: "dictation",
        audio: "To put this in context, that's twice what we spent last year.",
        explanation: "Listen for the weak forms: \"to\" /tə/, \"in\" and \"that's\" run together, and the stress falls on CONTEXT, TWICE, SPENT and LAST YEAR.",
      },
      {
        type: "speak",
        text: "It isn't a technical problem. It's a people problem.",
        tip: "Stress TECHNICAL in the first sentence and PEOPLE in the second; keep \"problem\" low both times. Pause between the two sentences.",
        explanation: "When the noun repeats, the stress moves to the contrasting modifier. Stressing \"problem\" would hide the contrast.",
      },
      {
        type: "write",
        prompt: "Write the transition section of a short talk (60-90 words). Recap the first part (sales fell), put a figure in context, and move on to your second part (what you propose).",
        minWords: 60,
        maxWords: 90,
        rubric: [
          "A short recap with \"So far\" or similar",
          "A context signpost (\"To put this in context\", \"To give you a sense of scale\")",
          "A clear transition to the next part (\"That brings me to\", \"Moving on to\")",
          "Short, natural sentences, no calques",
        ],
        modelAnswer: "So far, we've seen that sales fell by eighteen percent in the second half of the year. To put this in context, that's roughly what we lost during the whole of the pandemic. And it happened in six months. So the question is not whether we act, but how. That brings me to the second part of my talk: what I'm proposing. There are three changes, and I'll take them one by one.",
        explanation: "Notice how each signpost is short and is followed immediately by new information, which is where the stress falls.",
      },
    ],
  },
];
