// Synced from cheneygross-afk/lengo:src/lib/lessons/fr-a1.ts by scripts/sync-content.mjs -- edit it there, not here.
import type { Lesson } from "./types";
import type { UnitOutline } from "./units";
import { buildFrenchLevel, type FrenchUnitDef } from "./fr-units";
import { FR_A1_U01, FR_A1_U01_WRITING } from "./fr-a1-u01";
import { FR_A1_U01_EXTRA } from "./fr-a1-u01-extra";
import { FR_A1_U02, FR_A1_U02_WRITING } from "./fr-a1-u02";
import { FR_A1_U03, FR_A1_U03_WRITING } from "./fr-a1-u03";
import { FR_A1_U03_EXTRA } from "./fr-a1-u03-extra";
import { FR_A1_U04, FR_A1_U04_WRITING } from "./fr-a1-u04";
import { FR_A1_U05, FR_A1_U05_WRITING } from "./fr-a1-u05";
import { FR_A1_U05_EXTRA } from "./fr-a1-u05-extra";
import { FR_A1_U06, FR_A1_U06_WRITING } from "./fr-a1-u06";
import { FR_A1_U06_EXTRA } from "./fr-a1-u06-extra";
import { FR_A1_U07, FR_A1_U07_WRITING } from "./fr-a1-u07";
import { FR_A1_U07_EXTRA } from "./fr-a1-u07-extra";
import { FR_A1_U08, FR_A1_U08_WRITING } from "./fr-a1-u08";
import { FR_A1_U08_EXTRA } from "./fr-a1-u08-extra";
import { FR_A1_U09, FR_A1_U09_WRITING } from "./fr-a1-u09";
import { FR_A1_U10, FR_A1_U10_WRITING } from "./fr-a1-u10";

// French A1: generated by scripts/gen-french-level.ts from
// docs/french-course/syllabus-a1.md and the unit files
// (fr-a1-u<NN>.ts, fr-a1-u<NN>-extra.ts). Don't edit by hand;
// re-run the script when a unit file is added.
const UNITS: FrenchUnitDef[] = [
  { id: "u01", title: "Être, Articles & Adjectives", description: "Greet people, introduce yourself, say who and what people are, and describe them with adjectives that agree.", lessons: FR_A1_U01, extra: FR_A1_U01_EXTRA, writing: FR_A1_U01_WRITING },
  { id: "u02", title: "Sounds of French", description: "Hear and pronounce the sounds that make French French, link words the way natives do, and read words aloud from their spelling.", lessons: FR_A1_U02, writing: FR_A1_U02_WRITING },
  { id: "u03", title: "Present-Tense -ER Verbs & Avoir", description: "Talk about what you do every day, what you have and how you feel, and say what you do not do.", lessons: FR_A1_U03, extra: FR_A1_U03_EXTRA, writing: FR_A1_U03_WRITING },
  { id: "u04", title: "Everyday Irregulars", description: "Say where you go, what you do, where you come from and what you take, and use can, want and must with a second verb.", lessons: FR_A1_U04, writing: FR_A1_U04_WRITING },
  { id: "u05", title: "Questions, Negation & C'est", description: "Ask every kind of question, say never, no longer, nothing and nobody, say what there is, and choose between c'est and il est.", lessons: FR_A1_U05, extra: FR_A1_U05_EXTRA, writing: FR_A1_U05_WRITING },
  { id: "u06", title: "Possessives, Numbers & Time", description: "Say what belongs to whom, talk about your family, count, handle prices and phone numbers, tell the time, and talk about food in quantities.", lessons: FR_A1_U06, extra: FR_A1_U06_EXTRA, writing: FR_A1_U06_WRITING },
  { id: "u07", title: "Dates, Weather & Places", description: "Give the date, talk about the weather and the seasons, and say which city or country you live in, go to and come from.", lessons: FR_A1_U07, extra: FR_A1_U07_EXTRA, writing: FR_A1_U07_WRITING },
  { id: "u08", title: "Likes & Key Irregular Verbs", description: "Talk about what you like and dislike, make plans and invitations, say what you have just done, and use the most common remaining irregular verbs.", lessons: FR_A1_U08, extra: FR_A1_U08_EXTRA, writing: FR_A1_U08_WRITING },
  { id: "u09", title: "This & That, and the Beginner Level So Far", description: "Point things out, say where things are, give simple instructions and directions, describe your day, and pull the whole Beginner level together.", lessons: FR_A1_U09, writing: FR_A1_U09_WRITING },
  { id: "u10", title: "Beginner Final Review", description: "Show that you can handle every Beginner topic together and pass a DELF A1-style test of listening, reading and writing.", lessons: FR_A1_U10, writing: FR_A1_U10_WRITING },
];

const LEVEL = buildFrenchLevel("A1", UNITS);
export const FR_A1_LESSONS: Lesson[] = LEVEL.lessons;
export const FR_A1_UNITS: UnitOutline[] = LEVEL.units;
