// Synced from cheneygross-afk/lengo:src/lib/lessons/fr-a1-u07-extra.ts by scripts/sync-content.mjs -- edit it there, not here.
import type { Lesson } from "./types";

// French A1, Unit 7 extra practice: Dates, Weather & Places.
export const FR_A1_U07_EXTRA: Lesson[] = [
  {
    slug: "a1-dates-places-extra-1",
    level: "FR-A1",
    number: 1,
    optional: true,
    title: "Extra Practice: Dates, Weather & Places, Part 1 of 2",
    summary: "Say and write dates, birthdays and holidays: Noël, le 14 juillet, le Nouvel An.",
    duration: "10 min",
    sections: [
      {
        heading: "Recap: dates and holidays",
        body: [
          "A date is \"le\" + a plain number + the month, no capitals: \"le 25 décembre\". Only the first is an ordinal: \"le premier janvier\". 'On' a date needs no extra word: \"La fête est le 21 juin.\"",
          "Holidays to know: \"Noël\" (Christmas, \"à Noël\" = at Christmas), \"le Nouvel An\" (New Year), \"le 14 juillet\" (Bastille Day, the national holiday), \"la fête de la Musique\" (21 June), \"Pâques\" (Easter, \"à Pâques\"). Wish someone well with \"Joyeux anniversaire !\", \"Joyeux Noël !\", \"Bonne année !\".",
        ],
        examples: [
          { es: "Noël, c'est le 25 décembre.", en: "Christmas is on December 25th." },
          { es: "Le Nouvel An, c'est le premier janvier.", en: "New Year's Day is January 1st." },
          { es: "À Noël, nous sommes chez mes grands-parents.", en: "At Christmas we're at my grandparents'." },
          { es: "Le 14 juillet, il y a un feu d'artifice.", en: "On the 14th of July there are fireworks." },
          { es: "Joyeux anniversaire, Julie !", en: "Happy birthday, Julie!" },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "Christmas is on December 25th.",
            answer: "Noël, c'est le 25 décembre.",
            altAnswers: ["Noël est le 25 décembre.", "Noël, c'est le vingt-cinq décembre.", "Noël est le vingt-cinq décembre."],
            explanation: "\"Le\" + number + month; no word for 'on'.",
          },
          {
            type: "multiple-choice",
            question: "It's the 1st of January and you meet your neighbour. What do you say?",
            options: ["Bonne année !", "Joyeux anniversaire !", "Bon anniversaire de l'an !", "Joyeuse année !"],
            correctIndex: 0,
            explanation: "New Year wishes are \"Bonne année !\". \"Joyeux\" goes with \"Noël\" and \"anniversaire\".",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "My birthday is on May 1st.",
        answer: "Mon anniversaire est le premier mai.",
        altAnswers: ["Mon anniversaire, c'est le premier mai.", "Mon anniversaire est le 1er mai.", "Mon anniversaire, c'est le 1er mai."],
        explanation: "The first of the month is \"le premier\", never \"le un\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "When is your birthday? (to a friend)",
        answer: "C'est quand, ton anniversaire ?",
        altAnswers: ["Ton anniversaire, c'est quand ?", "Quand est ton anniversaire ?", "C'est quand ton anniversaire ?", "Quand est-ce que c'est, ton anniversaire ?"],
        explanation: "\"C'est quand, ton anniversaire ?\" is the natural spoken question.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "It's the 14th of July.",
        answer: "On est le 14 juillet.",
        altAnswers: ["On est le quatorze juillet.", "Nous sommes le 14 juillet.", "Nous sommes le quatorze juillet.", "C'est le 14 juillet.", "C'est le quatorze juillet."],
        explanation: "\"Le\" + plain number + month: never \"le juillet 14\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "At Christmas we're in Strasbourg.",
        answer: "À Noël, nous sommes à Strasbourg.",
        altAnswers: ["À Noël nous sommes à Strasbourg.", "À Noël, on est à Strasbourg.", "Nous sommes à Strasbourg à Noël.", "On est à Strasbourg à Noël."],
        explanation: "'At Christmas' is \"à Noël\"; \"Noël\" takes a capital as a holiday name.",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "The concert is [on June 21st].",
        sentence: "Le concert est ___.",
        answer: "le 21 juin",
        altAnswers: ["le vingt et un juin"],
        explanation: "\"Le\" + number + month. 21 is \"vingt et un\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "Happy birthday, Thomas!",
        answer: "Joyeux anniversaire, Thomas !",
        altAnswers: ["Bon anniversaire, Thomas !"],
        explanation: "\"Joyeux anniversaire\" and \"bon anniversaire\" are both used.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "The holidays start on July 4th.",
        answer: "Les vacances commencent le 4 juillet.",
        altAnswers: ["Les vacances commencent le quatre juillet."],
        explanation: "\"Les vacances\" is plural, so the verb is \"commencent\".",
      },
      {
        type: "multiple-choice",
        question: "How do you write 'Wednesday, March 3rd' in French?",
        options: ["mercredi 3 mars", "Mercredi, Mars 3", "mercredi le troisième mars", "mercredi, 3ème mars"],
        correctIndex: 0,
        explanation: "Day, number, month, all lowercase in the middle of a sentence, with a plain number.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "New Year's Day is a Thursday.",
        answer: "Le Nouvel An est un jeudi.",
        altAnswers: ["Le jour de l'An est un jeudi.", "Le premier janvier est un jeudi.", "Le Nouvel An, c'est un jeudi."],
        explanation: "\"Un jeudi\" = a Thursday. Days are lowercase.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: On the 14th of July there are fireworks.",
        words: ["Le", "14", "juillet,", "il", "y", "a", "un", "feu", "d'artifice."],
        translation: "On the 14th of July there are fireworks.",
        explanation: "\"Un feu d'artifice\" is a fireworks display, singular in French.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "We're going to my grandparents' at Easter.",
        answer: "Nous allons chez mes grands-parents à Pâques.",
        altAnswers: ["On va chez mes grands-parents à Pâques.", "À Pâques, nous allons chez mes grands-parents.", "À Pâques, on va chez mes grands-parents."],
        explanation: "\"À Pâques\" = at Easter; \"chez\" + people = at / to their place.",
      },
      {
        type: "listen-choose",
        audio: "On est le premier avril.",
        question: "What does it mean?",
        options: ["It's April 1st.", "It's the first week of April.", "It's April 10th.", "It's the end of April."],
        correctIndex: 0,
        explanation: "\"Le premier avril\" = April 1st (April Fool's Day, \"le poisson d'avril\").",
      },
      {
        type: "dictation",
        audio: "Joyeux Noël et bonne année !",
        explanation: "\"Joyeux Noël\" (masculine), \"bonne année\" (feminine).",
      },
      {
        type: "speak",
        text: "Mon anniversaire, c'est le trente et un octobre.",
        prompt: "Say it in French: My birthday is October 31st.",
        explanation: "31 is \"trente et un\": no hyphens around \"et\".",
      },
    ],
  },
  {
    slug: "a1-dates-places-extra-2",
    level: "FR-A1",
    number: 2,
    optional: true,
    title: "Extra Practice: Dates, Weather & Places, Part 2 of 2",
    summary: "Weather and seasons across the French-speaking world, from Quebec winters to summer in Dakar.",
    duration: "10 min",
    sections: [
      {
        heading: "Recap: weather and seasons",
        body: [
          "Weather is \"il fait\" + adjective (\"il fait chaud\", \"il fait froid\", \"il fait beau\"), \"il pleut\" and \"il neige\" for rain and snow, and \"il y a du / des\" for sun, wind and clouds. Temperatures: \"il fait 30 degrés\", \"il fait moins dix\".",
          "Seasons: \"en été\", \"en automne\", \"en hiver\", but \"au printemps\". Places: \"au Québec\", \"au Sénégal\", \"en Belgique\", \"en Suisse\", \"à Montréal\".",
        ],
        examples: [
          { es: "Au Québec, il fait moins vingt en hiver.", en: "In Quebec it's minus twenty in winter." },
          { es: "À Dakar, il fait chaud toute l'année.", en: "In Dakar it's hot all year round." },
          { es: "En Belgique, il pleut souvent.", en: "In Belgium it often rains." },
          { es: "En Suisse, il neige beaucoup en hiver.", en: "In Switzerland it snows a lot in winter." },
          { es: "À Nice, il y a du soleil presque tous les jours.", en: "In Nice it's sunny almost every day." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "In Belgium it often rains.",
            answer: "En Belgique, il pleut souvent.",
            altAnswers: ["En Belgique il pleut souvent.", "Il pleut souvent en Belgique."],
            explanation: "\"En Belgique\" (feminine); \"souvent\" after the verb.",
          },
          {
            type: "listen-choose",
            audio: "Il fait doux au printemps.",
            question: "What does it mean?",
            options: ["It's mild in spring.", "It's sweet in spring.", "It's hot in summer.", "It's cold in spring."],
            correctIndex: 0,
            explanation: "For weather, \"doux\" means mild (for food it means sweet).",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "In Quebec it snows a lot.",
        answer: "Au Québec, il neige beaucoup.",
        altAnswers: ["Au Québec il neige beaucoup.", "Il neige beaucoup au Québec."],
        explanation: "\"Le Québec\" is masculine: \"au Québec\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "In Dakar it's hot in summer.",
        answer: "À Dakar, il fait chaud en été.",
        altAnswers: ["À Dakar il fait chaud en été.", "Il fait chaud à Dakar en été.", "En été, il fait chaud à Dakar."],
        explanation: "City with \"à\", heat with \"il fait\", summer with \"en\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "It's sunny in Marseille.",
        answer: "Il y a du soleil à Marseille.",
        altAnswers: ["Il fait du soleil à Marseille.", "À Marseille, il y a du soleil."],
        explanation: "Sun is something there is: \"il y a du soleil\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "It's minus ten in Montreal.",
        answer: "Il fait moins dix à Montréal.",
        altAnswers: ["Il fait moins dix degrés à Montréal.", "À Montréal, il fait moins dix."],
        explanation: "\"Il fait moins dix\": temperatures keep \"il fait\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "[In spring] it rains in Brussels.",
        sentence: "___, il pleut à Bruxelles.",
        answer: "Au printemps",
        explanation: "Spring is the one season with \"au\".",
      },
      {
        type: "multiple-choice",
        question: "Which sentence means 'The weather is bad in Lille'?",
        options: ["Il fait mauvais à Lille.", "Il est mauvais à Lille.", "C'est mauvais temps à Lille.", "Il a mauvais à Lille."],
        correctIndex: 0,
        explanation: "\"Il fait mauvais\": weather always takes \"il fait\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "There's no wind today.",
        answer: "Il n'y a pas de vent aujourd'hui.",
        altAnswers: ["Aujourd'hui, il n'y a pas de vent.", "Il ne fait pas de vent aujourd'hui."],
        explanation: "After the negative, \"du vent\" becomes \"de vent\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "In Switzerland it's cold in winter.",
        answer: "En Suisse, il fait froid en hiver.",
        altAnswers: ["En Suisse il fait froid en hiver.", "Il fait froid en Suisse en hiver.", "En hiver, il fait froid en Suisse."],
        explanation: "Two \"en\"s: feminine country and a season starting with a vowel sound.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: In autumn it's cloudy in Paris.",
        words: ["En", "automne,", "il", "y", "a", "des", "nuages", "à", "Paris."],
        translation: "In autumn it's cloudy in Paris.",
        explanation: "Clouds are \"des nuages\" with \"il y a\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "What's the weather like in Geneva?",
        answer: "Quel temps fait-il à Genève ?",
        altAnswers: ["Il fait quel temps à Genève ?", "Quel temps il fait à Genève ?"],
        explanation: "\"Quel temps fait-il ?\" with the city after \"à\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "I'm cold because it's snowing.",
        answer: "J'ai froid parce qu'il neige.",
        altAnswers: ["J'ai froid, parce qu'il neige."],
        explanation: "A person feeling cold is \"avoir froid\"; the weather is \"il neige\".",
      },
      {
        type: "matching",
        instructions: "Match the French to the English.",
        pairs: [
          { left: "il fait frais", right: "it's cool" },
          { left: "il fait doux", right: "it's mild" },
          { left: "il y a du brouillard", right: "it's foggy" },
          { left: "il neige", right: "it's snowing" },
          { left: "il fait mauvais", right: "the weather's bad" },
        ],
        explanation: "\"Il fait\" for general weather and temperature, \"il y a du\" for fog, sun and wind.",
      },
      {
        type: "dictation",
        audio: "Il fait beau en été.",
        explanation: "\"En été\": the n of \"en\" links into \"été\".",
      },
      {
        type: "speak",
        text: "Au Québec, il fait très froid en hiver.",
        prompt: "Say it in French: In Quebec it's very cold in winter.",
        explanation: "\"Au Québec\", \"il fait froid\", \"en hiver\".",
      },
    ],
  },
  {
    slug: "a1-dates-places-extra-3",
    level: "FR-A1",
    number: 3,
    optional: true,
    title: "Extra Practice: Error Hunt: Dates, Prepositions & Contractions",
    summary: "Find and fix the classic slips: à le, en Canada, le juillet 14, il est froid.",
    duration: "10 min",
    sections: [
      {
        heading: "Recap: the four classic slips",
        body: [
          "1. \"À le\" and \"à les\" never appear: they become \"au\" and \"aux\" (\"de le\" / \"de les\" become \"du\" / \"des\"). 2. Masculine countries take \"au\", not \"en\": \"au Canada\". 3. Dates go le + number + month: \"le 14 juillet\". 4. Weather is \"il fait froid\", not \"il est froid\".",
          "Each exercise below gives you a learner's wrong sentence: write the correct French.",
        ],
        examples: [
          { es: "Je vais au parc.", en: "I'm going to the park. (not \"à le parc\")" },
          { es: "Il habite au Canada.", en: "He lives in Canada. (not \"en Canada\")" },
          { es: "On est le 14 juillet.", en: "It's the 14th of July. (not \"le juillet 14\")" },
          { es: "Il fait froid.", en: "It's cold. (not \"il est froid\")" },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "A learner wrote \"Je parle à les enfants.\" Write it correctly: I'm talking to the children.",
            answer: "Je parle aux enfants.",
            explanation: "\"À + les\" always contracts to \"aux\".",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "A learner wrote \"Il est chaud aujourd'hui.\" Write it correctly: It's hot today.",
            answer: "Il fait chaud aujourd'hui.",
            altAnswers: ["Aujourd'hui, il fait chaud."],
            explanation: "Weather heat is \"il fait chaud\".",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "A learner wrote \"Nous habitons en Japon.\" Write it correctly: We live in Japan.",
        answer: "Nous habitons au Japon.",
        altAnswers: ["On habite au Japon."],
        explanation: "\"Le Japon\" is masculine: \"au Japon\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "A learner wrote \"Mon anniversaire est le mars 12.\" Write it correctly: My birthday is March 12th.",
        answer: "Mon anniversaire est le 12 mars.",
        altAnswers: ["Mon anniversaire est le douze mars.", "Mon anniversaire, c'est le 12 mars.", "Mon anniversaire, c'est le douze mars."],
        explanation: "Number before month: \"le 12 mars\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "A learner wrote \"Elle vient de le Mexique.\" Write it correctly: She comes from Mexico.",
        answer: "Elle vient du Mexique.",
        explanation: "\"De + le\" = \"du\", and \"le Mexique\" is masculine.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "A learner wrote \"On est le un juin.\" Write it correctly: It's June 1st.",
        answer: "On est le premier juin.",
        altAnswers: ["Nous sommes le premier juin.", "C'est le premier juin.", "On est le 1er juin."],
        explanation: "The 1st is \"le premier\"; every other day is a plain number.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "A learner wrote \"Je vais à France en Mai.\" Write it correctly: I'm going to France in May.",
        answer: "Je vais en France en mai.",
        explanation: "Two slips: feminine countries take \"en\", and months have no capital.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "A learner wrote \"Ils jouent à le foot.\" Write it correctly: They play football.",
        answer: "Ils jouent au foot.",
        altAnswers: ["Elles jouent au foot.", "Ils jouent au football.", "Elles jouent au football."],
        explanation: "\"Jouer à\" + \"le foot\" = \"au foot\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "A learner wrote \"En printemps, il pleut.\" Write it correctly: In spring it rains.",
        answer: "Au printemps, il pleut.",
        altAnswers: ["Au printemps il pleut.", "Il pleut au printemps."],
        explanation: "Spring takes \"au\"; the other seasons take \"en\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "A learner wrote \"Je suis Anglaise et je parle Anglais.\" Write it correctly: I'm English and I speak English.",
        answer: "Je suis anglaise et je parle anglais.",
        altAnswers: ["Je suis anglais et je parle anglais."],
        explanation: "Nationality adjectives and languages are lowercase.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "A learner wrote \"Le chat de les voisins est noir.\" Write it correctly: The neighbours' cat is black.",
        answer: "Le chat des voisins est noir.",
        altAnswers: ["Le chat des voisines est noir."],
        explanation: "\"De + les\" = \"des\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "A learner wrote \"Il y a du soleil mais il est froid.\" Write it correctly: It's sunny but it's cold.",
        answer: "Il y a du soleil mais il fait froid.",
        altAnswers: ["Il y a du soleil, mais il fait froid."],
        explanation: "The first half is right; the second needs \"il fait froid\".",
      },
      {
        type: "multiple-choice",
        question: "Only one sentence is correct. Which one?",
        options: ["Mes amis viennent des États-Unis.", "Mes amis viennent de les États-Unis.", "Mes amis viennent de États-Unis.", "Mes amis viennent aux États-Unis."],
        correctIndex: 0,
        explanation: "'From the United States' is \"des États-Unis\" (de + les).",
      },
      {
        type: "multiple-choice",
        question: "Only one sentence is correct. Which one?",
        options: ["Le samedi, je vais au marché.", "Le samedi, je vais à le marché.", "Le Samedi, je vais au marché.", "Sur samedi, je vais au marché."],
        correctIndex: 0,
        explanation: "\"Le samedi\" (every Saturday) lowercase, and \"au marché\".",
      },
      {
        type: "listen-choose",
        audio: "Je viens du Canada.",
        question: "What did you hear?",
        options: ["Je viens du Canada.", "Je viens de Canada.", "Je viens au Canada.", "Je viens en Canada."],
        correctIndex: 0,
        explanation: "\"Du Canada\": de + le, the correct form for a masculine country.",
      },
      {
        type: "speak",
        text: "Elle habite au Canada, à Québec.",
        prompt: "Say it in French: She lives in Canada, in Quebec City.",
        explanation: "\"Au Canada\" (masculine country), \"à Québec\" (the city).",
      },
    ],
  },
  {
    slug: "a1-dates-places-extra-4",
    level: "FR-A1",
    number: 4,
    optional: true,
    title: "Extra Practice: Story Detective: A Postcard from Nice",
    summary: "Read a holiday postcard and answer questions on dates, weather and places, then write a reply.",
    duration: "12 min",
    sections: [
      {
        heading: "The postcard",
        body: [
          "Read Camille's postcard to her friend Hugo: \"Nice, le 12 août. Salut Hugo ! Je suis à Nice avec ma famille. Il fait très chaud : il fait 32 degrés ! Il y a du soleil tous les jours, mais ce soir il y a un orage. Le matin, nous allons à la plage ; l'après-midi, nous restons à l'hôtel. Mes cousins viennent des États-Unis et ils parlent anglais et un peu français. Samedi, nous allons en Italie, à Gênes. Je rentre à Paris le premier septembre. Bises, Camille.\"",
          "Everything in it comes from this unit: the date with \"le\", \"il fait\" + temperature, \"il y a du soleil\", \"à la plage\" and \"à l'hôtel\", origin with \"des\", and \"en Italie, à Gênes\".",
        ],
        examples: [
          { es: "Nice, le 12 août.", en: "Nice, August 12th." },
          { es: "Il fait très chaud : il fait 32 degrés !", en: "It's very hot: it's 32 degrees!" },
          { es: "Le matin, nous allons à la plage.", en: "In the mornings we go to the beach." },
          { es: "Mes cousins viennent des États-Unis.", en: "My cousins come from the United States." },
          { es: "Je rentre à Paris le premier septembre.", en: "I'm going back to Paris on September 1st." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "What's the weather like in Nice, according to Camille?",
            options: ["Hot and sunny, with a storm tonight.", "Mild and cloudy.", "Rainy every day.", "Cold but sunny."],
            correctIndex: 0,
            explanation: "\"Il fait très chaud\", \"il y a du soleil tous les jours\", \"ce soir il y a un orage\".",
          },
          {
            type: "multiple-choice",
            question: "When does Camille go back to Paris?",
            options: ["On September 1st.", "On August 12th.", "On Saturday.", "On September 12th."],
            correctIndex: 0,
            explanation: "\"Le premier septembre\" = September 1st.",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "On Saturday we're going to Italy.",
            answer: "Samedi, nous allons en Italie.",
            altAnswers: ["Samedi nous allons en Italie.", "Samedi, on va en Italie.", "Nous allons en Italie samedi.", "On va en Italie samedi."],
            explanation: "\"Samedi\" alone = this Saturday; \"en Italie\" for a feminine country.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "multiple-choice",
        question: "Where do Camille's cousins come from?",
        options: ["The United States", "Italy", "Nice", "England"],
        correctIndex: 0,
        explanation: "\"Ils viennent des États-Unis.\"",
      },
      {
        type: "multiple-choice",
        question: "What does the family do in the afternoons?",
        options: ["They stay at the hotel.", "They go to the beach.", "They go to Italy.", "They visit the cousins."],
        correctIndex: 0,
        explanation: "\"L'après-midi, nous restons à l'hôtel.\" (\"Rester\" = to stay.)",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "I'm in Nice with my family.",
        answer: "Je suis à Nice avec ma famille.",
        explanation: "City with \"à\"; \"la famille\" is feminine, so \"ma famille\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "It's 32 degrees!",
        answer: "Il fait 32 degrés !",
        altAnswers: ["Il fait trente-deux degrés !"],
        explanation: "Temperatures: \"il fait\" + number + \"degrés\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "There's a storm this evening.",
        answer: "Ce soir, il y a un orage.",
        altAnswers: ["Il y a un orage ce soir.", "Ce soir il y a un orage."],
        explanation: "\"Un orage\" = a storm, with \"il y a\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "In the morning we go to the beach.",
        answer: "Le matin, nous allons à la plage.",
        altAnswers: ["Le matin, on va à la plage.", "Le matin nous allons à la plage.", "Nous allons à la plage le matin.", "On va à la plage le matin."],
        explanation: "\"Le matin\" = in the mornings, as a routine; \"à la plage\" doesn't contract.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "My cousins speak a bit of French.",
        answer: "Mes cousins parlent un peu français.",
        altAnswers: ["Mes cousins parlent un peu le français.", "Mes cousines parlent un peu français.", "Mes cousins parlent un peu de français."],
        explanation: "\"Un peu\" goes after the verb; the language is lowercase.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "We're going to Genoa, in Italy.",
        answer: "Nous allons à Gênes, en Italie.",
        altAnswers: ["On va à Gênes, en Italie."],
        explanation: "City \"à Gênes\", feminine country \"en Italie\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "Hugo writes back: Here in Paris, [it's raining]!",
        sentence: "Ici, à Paris, ___ !",
        answer: "il pleut",
        explanation: "Rain has its own verb: \"il pleut\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "Hugo writes back: It's cold in Paris and it's grey.",
        answer: "Il fait froid à Paris et il fait gris.",
        altAnswers: ["À Paris, il fait froid et il fait gris.", "Il fait froid à Paris et le ciel est gris.", "Il fait froid et gris à Paris."],
        explanation: "\"Il fait gris\" is the everyday way to say it's grey (overcast).",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "Hugo writes back: I'm going to Belgium on August 20th.",
        answer: "Je vais en Belgique le 20 août.",
        altAnswers: ["Je vais en Belgique le vingt août.", "Le 20 août, je vais en Belgique."],
        explanation: "\"En Belgique\" (feminine), \"le 20 août\" (le + number + month).",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: See you on September 1st!",
        words: ["À", "bientôt,", "le", "premier", "septembre !"],
        translation: "See you on September 1st!",
        explanation: "\"Le premier septembre\" for the 1st.",
      },
      {
        type: "listen-choose",
        audio: "Je rentre à Paris le premier septembre.",
        question: "What does it mean?",
        options: ["I'm going back to Paris on September 1st.", "I'm going to Paris for the first time in September.", "I'm going back to Paris in September for a week.", "I'm leaving Paris on September 1st."],
        correctIndex: 0,
        explanation: "\"Rentrer\" = go back home; \"le premier septembre\" = September 1st.",
      },
      {
        type: "speak",
        text: "Il y a du soleil tous les jours !",
        prompt: "Say it in French: It's sunny every day!",
        explanation: "\"Il y a du soleil\" + \"tous les jours\" (the s of \"tous\" is silent).",
      },
    ],
  },
  {
    slug: "a1-dates-places-extra-5",
    level: "FR-A1",
    number: 5,
    optional: true,
    title: "Extra Practice: Contrast Clinic: À, En, Au or Aux?",
    summary: "Cities, feminine, masculine and plural countries in minimal pairs, going to and coming from.",
    duration: "10 min",
    sections: [
      {
        heading: "Recap: one table to remember",
        body: [
          "In or to: city \"à\" (à Rome), feminine or vowel country \"en\" (en Grèce, en Iran), masculine country \"au\" (au Brésil), plural country \"aux\" (aux Pays-Bas).",
          "From: city \"de\" / \"d'\" (de Rome, d'Oslo), feminine country \"de\" / \"d'\" with no article (de Grèce, d'Iran), masculine \"du\" (du Brésil), plural \"des\" (des Pays-Bas).",
        ],
        examples: [
          { es: "Je vais à Rome, en Italie.", en: "I'm going to Rome, in Italy." },
          { es: "Je viens de Rome, d'Italie.", en: "I come from Rome, from Italy." },
          { es: "Il habite au Brésil.", en: "He lives in Brazil." },
          { es: "Il vient du Brésil.", en: "He comes from Brazil." },
          { es: "Elles vont aux Pays-Bas.", en: "They're going to the Netherlands." },
          { es: "Elles viennent des Pays-Bas.", en: "They come from the Netherlands." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "I'm going to Greece.",
            answer: "Je vais en Grèce.",
            explanation: "\"La Grèce\" is feminine: \"en Grèce\".",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "I come from Greece.",
            answer: "Je viens de Grèce.",
            explanation: "Feminine country: 'from' is \"de\" with no article.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "She lives in Portugal.",
        answer: "Elle habite au Portugal.",
        explanation: "Masculine country: \"au\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "She comes from Portugal.",
        answer: "Elle vient du Portugal.",
        explanation: "Masculine country: \"du\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "We're going to China.",
        answer: "Nous allons en Chine.",
        altAnswers: ["On va en Chine."],
        explanation: "\"La Chine\" is feminine: \"en Chine\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "We come from China.",
        answer: "Nous venons de Chine.",
        altAnswers: ["On vient de Chine."],
        explanation: "Feminine country: plain \"de\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "They work in the United States.",
        answer: "Ils travaillent aux États-Unis.",
        altAnswers: ["Elles travaillent aux États-Unis."],
        explanation: "Plural country: \"aux\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "He's going to Iran.",
        answer: "Il va en Iran.",
        explanation: "\"L'Iran\" is masculine but starts with a vowel, so \"en Iran\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "My colleague comes from Oslo.",
        answer: "Mon collègue vient d'Oslo.",
        altAnswers: ["Ma collègue vient d'Oslo."],
        explanation: "City before a vowel: \"d'Oslo\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "Are you going [to Morocco] or [to Tunisia]?",
        sentence: "Tu vas au Maroc ou ___ ?",
        answer: "en Tunisie",
        explanation: "\"Le Maroc\" (masculine) takes \"au\"; \"la Tunisie\" (feminine) takes \"en\".",
      },
      {
        type: "multiple-choice",
        question: "Which sentence is correct?",
        options: ["Il va au Cambodge.", "Il va en Cambodge.", "Il va à Cambodge.", "Il va aux Cambodge."],
        correctIndex: 0,
        explanation: "\"Le Cambodge\" ends in -e but is masculine: \"au Cambodge\".",
      },
      {
        type: "multiple-choice",
        question: "Which sentence is correct?",
        options: ["Nous venons d'Allemagne.", "Nous venons de l'Allemagne.", "Nous venons du Allemagne.", "Nous venons en Allemagne."],
        correctIndex: 0,
        explanation: "After \"venir de\", feminine countries drop the article: \"d'Allemagne\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "I live in Lyon, in France.",
        answer: "J'habite à Lyon, en France.",
        explanation: "City \"à\", feminine country \"en\".",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: They come from the Netherlands and live in Belgium.",
        words: ["Ils", "viennent", "des", "Pays-Bas", "et", "habitent", "en", "Belgique."],
        translation: "They come from the Netherlands and live in Belgium.",
        explanation: "\"Des Pays-Bas\" (plural, from), \"en Belgique\" (feminine, in).",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "The plane arrives from Japan at 6 p.m.",
        answer: "L'avion arrive du Japon à dix-huit heures.",
        altAnswers: ["L'avion arrive du Japon à 18 heures.", "L'avion arrive du Japon à 18h.", "L'avion arrive du Japon à six heures du soir."],
        explanation: "\"Du Japon\" (masculine, from); the 24-hour clock for timetables.",
      },
      {
        type: "listen-choose",
        audio: "Elle va au Brésil.",
        question: "What does it mean?",
        options: ["She's going to Brazil.", "She comes from Brazil.", "She's leaving Brazil.", "She lives in Brazil."],
        correctIndex: 0,
        explanation: "\"Aller au\" = go to. From would be \"du Brésil\".",
      },
      {
        type: "dictation",
        audio: "Je viens d'Espagne.",
        explanation: "Feminine country after \"venir de\": \"d'Espagne\".",
      },
      {
        type: "speak",
        text: "Je viens du Canada, mais j'habite en Suisse.",
        prompt: "Say it in French: I come from Canada, but I live in Switzerland.",
        explanation: "\"Du Canada\" for origin, \"en Suisse\" for where you live.",
      },
    ],
  },
];
