// Synced from cheneygross-afk/lengo:src/lib/lessons/fr-b1-u02.ts by scripts/sync-content.mjs -- edit it there, not here.
import type { Lesson, WriteExercise } from "./types";

// French B1, Unit 2: The Present Subjunctive: Regular Forms.

export const FR_B1_U02_WRITING: WriteExercise = {
  type: "write",
  prompt: "You're going away for a week and a friend is staying in your flat to look after it. Write a note (80-150 words) explaining what they have to do and what the general rules are: watering plants, the cat, the bins, the neighbours, when to lock up. Use \"il faut que\" with regular verbs for specific instructions and \"il faut\" + infinitive for general rules.",
  minWords: 80,
  maxWords: 150,
  rubric: [
    "Gives at least four instructions with \"il faut que tu\" + a regular subjunctive (\"que tu arroses\", \"que tu sortes\", \"que tu fermes\", \"que tu attendes\")",
    "Uses \"il faut\" + infinitive for at least one general rule (\"il faut fermer la porte à clé\")",
    "Includes a \"nous\" or \"vous\" form in -ions / -iez, or a third person (\"il faut que les voisins...\", \"il faut qu'on...\")",
    "Uses at least one audible -ir / -re subjunctive (\"que tu sortes\", \"que tu lises\", \"que tu mettes\", \"que tu dormes\")",
  ],
  modelAnswer: "Salut Romain ! Merci mille fois de garder l'appartement. Tout est très simple. D'abord, il faut que tu donnes à manger au chat matin et soir, et il faut que tu changes son eau. Il faut que tu arroses les plantes du balcon tous les deux jours. Le mardi soir, il faut que tu sortes les poubelles. Si le voisin du dessous sonne, il faut que tu lui dises que je rentre dimanche. Le soir, il ne faut pas laisser le chat sortir, et il faut toujours fermer la porte à clé. Si tu pars le week-end, il faut que tu mettes le chauffage sur 18 degrés. Et surtout, il faut que tu dormes bien et que tu profites de la terrasse ! On s'appelle dimanche. Bisous, Margaux",
  explanation: "Each specific instruction uses \"il faut que tu\" + subjunctive: -er verbs sound like the present (\"que tu donnes\", \"que tu arroses\"), while -ir / -re verbs are audible (\"que tu sortes\", \"que tu dises\", \"que tu mettes\", \"que tu dormes\"). General rules use \"il faut\" + infinitive (\"il faut toujours fermer la porte\"). \"Il ne faut pas\" means you mustn't.",
};

export const FR_B1_U02: Lesson[] = [
  {
    slug: "b1-subjunctive-forms-1",
    level: "FR-B1",
    number: 1,
    title: "The Present Subjunctive: Regular Forms, Part 1 of 2",
    summary: "Meet the subjunctive mood: what it is, why French needs it after \"il faut que\", and how to build the singular and ils forms from the present.",
    duration: "15 min",
    sections: [
      {
        heading: "What is a mood?",
        body: [
          "Until now, every verb you've conjugated was in the indicative: the mood for stating facts (\"tu ranges ta chambre\", \"il est parti\", \"nous irons\"). The subjunctive is a different mood. It isn't a tense: it doesn't say when something happens. It says how the speaker presents the action: as something necessary, wanted, feared, doubted, rather than as a plain fact.",
          "The subjunctive almost never stands alone. It appears in a clause introduced by \"que\", after a trigger in the main clause. The first and most common trigger is \"il faut que\" (it's necessary that, someone has to): \"Il faut que tu ranges ta chambre.\" (You have to tidy your room.)",
          "English has a few fossil subjunctives ('I insist that he be on time', 'if I were you'), but mostly it uses \"to\" + infinitive: I need you to call. French can't do that: you need \"que\" + a full clause with a subject and a subjunctive verb: \"il faut que tu appelles\".",
        ],
        examples: [
          { es: "Il faut que tu ranges ta chambre.", en: "You have to tidy your room." },
          { es: "Il faut que je travaille ce soir.", en: "I have to work tonight." },
          { es: "Il faut qu'il téléphone au propriétaire.", en: "He has to call the landlord." },
          { es: "Il faut que tu parles au prof.", en: "You need to talk to the teacher." },
          { es: "Il faut qu'elles rentrent avant minuit.", en: "They have to be home before midnight." },
          { es: "Il faut que je lave la voiture.", en: "I need to wash the car." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "You have to tidy your room. (to a child)",
            answer: "Il faut que tu ranges ta chambre.",
            explanation: "\"Il faut que\" + subject + subjunctive. For -er verbs the tu form ends in -es, like the present.",
          },
          {
            type: "multiple-choice",
            question: "How do you say: I need you to talk to the teacher? (to a friend)",
            options: [
              "Il faut toi parler au prof.",
              "J'ai besoin toi de parler au prof.",
              "Il faut que tu parles au prof.",
              "Il faut tu parler au prof.",
            ],
            correctIndex: 2,
            explanation: "French can't copy I need you to + verb: use \"il faut que tu\" + subjunctive.",
          },
        ],
      },
      {
        heading: "The recipe: the ils form minus -ent",
        body: [
          "Here's how to build the subjunctive of a regular verb. Take the ils form of the present: \"ils parlent\". Remove -ent: \"parl-\". Add the endings -e, -es, -e, -ent: \"que je parle, que tu parles, qu'il parle, qu'ils parlent\".",
          "This recipe is powerful because it works for many verbs that look irregular in the infinitive: \"ils finissent\" → \"que je finisse\"; \"ils partent\" → \"que je parte\"; \"ils écrivent\" → \"que j'écrive\"; \"ils mettent\" → \"que je mette\". If you know the ils form of the present, you can build the subjunctive.",
          "Note \"que\" becomes \"qu'\" before \"il\", \"elle\", \"ils\", \"elles\" and \"on\": \"il faut qu'il parte\", \"il faut qu'on range\".",
        ],
        examples: [
          { es: "ils parlent → que je parle", en: "they speak → that I speak" },
          { es: "ils finissent → que tu finisses", en: "they finish → that you finish" },
          { es: "ils partent → qu'il parte", en: "they leave → that he leave" },
          { es: "ils écrivent → qu'elle écrive", en: "they write → that she write" },
          { es: "Il faut qu'on range le salon.", en: "We need to tidy the living room." },
          { es: "Il faut qu'ils finissent avant six heures.", en: "They have to finish before six." },
        ],
        checkpoint: [
          {
            type: "fill-blank",
            prompt: "Write the French for the bold words.",
            en: "He [has to leave] early.",
            sentence: "Il faut qu'il ___ tôt.",
            answer: "parte",
            explanation: "Ils partent → part- + -e: \"qu'il parte\". You hear the t, unlike in \"il part\".",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "They have to finish before six.",
            answer: "Il faut qu'ils finissent avant six heures.",
            altAnswers: [
              "Il faut qu'elles finissent avant six heures.",
              "Il faut qu'ils finissent avant 18 heures.",
              "Il faut qu'ils aient fini avant six heures.",
            ],
            explanation: "Ils finissent → finiss- + -ent. The ils form looks like the present.",
          },
        ],
      },
      {
        heading: "Il faut que vs il faut + infinitive",
        body: [
          "You learned \"il faut\" + infinitive at the Elementary level: \"il faut partir\" (we/one must leave). It states a general necessity without naming who. As soon as you name the person, French switches to \"que\" + subjunctive: \"il faut que tu partes\", \"il faut que Manon parte\".",
          "In the negative, \"il ne faut pas que tu partes\" means you mustn't leave, not you don't have to. That's an important false friend with English: you don't have to is \"tu n'es pas obligé de\" or \"ce n'est pas la peine de\".",
        ],
        examples: [
          { es: "Il faut partir maintenant.", en: "We have to leave now." },
          { es: "Il faut que Manon parte maintenant.", en: "Manon has to leave now." },
          { es: "Il faut manger cinq fruits et légumes par jour.", en: "You should eat five fruits and vegetables a day." },
          { es: "Il faut que tu manges plus de légumes.", en: "You need to eat more vegetables." },
          { es: "Il ne faut pas que tu oublies ton passeport.", en: "You mustn't forget your passport." },
          { es: "Tu n'es pas obligé de m'attendre.", en: "You don't have to wait for me." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "You mustn't forget your passport. (to a friend)",
            answer: "Il ne faut pas que tu oublies ton passeport.",
            altAnswers: ["Tu ne dois pas oublier ton passeport.", "N'oublie pas ton passeport."],
            explanation: "\"Il ne faut pas que\" = mustn't. \"Oublier\" → \"que tu oublies\".",
          },
          {
            type: "speak",
            text: "Il faut que tu parles au prof.",
            prompt: "Say it in French: You need to talk to the teacher. (to a friend)",
            explanation: "\"Il faut que\" + \"tu parles\": the -es is silent.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "I have to work tonight.",
        answer: "Il faut que je travaille ce soir.",
        altAnswers: ["Je dois travailler ce soir."],
        explanation: "\"Il faut que je\" + subjunctive; \"travailler\" → \"que je travaille\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "He has to call the landlord.",
        answer: "Il faut qu'il téléphone au propriétaire.",
        altAnswers: ["Il faut qu'il appelle le propriétaire.", "Il doit téléphoner au propriétaire."],
        explanation: "\"Que\" → \"qu'\" before \"il\"; \"téléphoner à\" + person.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "We have to leave now.",
        answer: "Il faut partir maintenant.",
        altAnswers: [
          "Il faut qu'on parte maintenant.",
          "Il faut que nous partions maintenant.",
          "On doit partir maintenant.",
          "Nous devons partir maintenant.",
        ],
        explanation: "A general must leave: \"il faut\" + infinitive. Naming the subject needs \"que\" + subjunctive.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "Manon has to leave now.",
        answer: "Il faut que Manon parte maintenant.",
        altAnswers: ["Manon doit partir maintenant."],
        explanation: "A named person → \"il faut que\" + subjunctive: \"parte\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "You need to [write] to your grandmother. (to a friend)",
        sentence: "Il faut que tu ___ à ta grand-mère.",
        answer: "écrives",
        explanation: "Ils écrivent → écriv- + -es.",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "She has to [put] her coat on.",
        sentence: "Il faut qu'elle ___ son manteau.",
        answer: "mette",
        explanation: "Ils mettent → mett- + -e: \"qu'elle mette\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "We need to [tidy] the living room.",
        sentence: "Il faut qu'on ___ le salon.",
        answer: "range",
        explanation: "With \"on\", the verb takes the il form: \"qu'on range\".",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: You need to eat more vegetables.",
        words: ["Il", "faut", "que", "tu", "manges", "plus", "de", "légumes."],
        translation: "You need to eat more vegetables.",
        explanation: "\"Il faut que\" + \"tu manges\" (subjunctive, same sound as the present).",
      },
      {
        type: "multiple-choice",
        question: "Which sentence means you don't have to wait for me?",
        options: [
          "Tu n'es pas obligé de m'attendre.",
          "Il ne faut pas que tu m'attendes.",
          "Il faut que tu m'attendes.",
          "Il faut m'attendre.",
        ],
        correctIndex: 0,
        explanation: "\"Il ne faut pas que\" means mustn't; don't have to is \"ne pas être obligé de\".",
      },
      {
        type: "listen-choose",
        audio: "Il faut qu'il parte.",
        question: "What did you hear?",
        options: ["Il faut qu'il part.", "Il faut partir.", "Il faut qu'il parte.", "Il faut qu'ils partent."],
        correctIndex: 2,
        explanation: "You hear the t: \"parte\", the subjunctive.",
      },
      {
        type: "dictation",
        audio: "Il faut que tu ranges ta chambre.",
        explanation: "\"Que tu ranges\": the subjunctive of an -er verb sounds like the present.",
      },
      {
        type: "speak",
        text: "Il ne faut pas que tu oublies ton passeport.",
        prompt: "Say it in French: You mustn't forget your passport. (to a friend)",
        explanation: "\"Il ne faut pas que\" = mustn't.",
      },
    ],
  },
  {
    slug: "b1-pattern-subjunctive-er-verbs",
    level: "FR-B1",
    number: 2,
    title: "Pattern Practice: Subjunctive of -er Verbs",
    summary: "Drill the subjunctive of regular -er verbs after \"il faut que\", where the singular and ils forms sound exactly like the present.",
    duration: "12 min",
    sections: [
      {
        heading: "Il faut que je range, que tu ranges",
        body: [
          "For -er verbs, the four forms \"que je range, que tu ranges, qu'il range, qu'ils rangent\" are spelled and pronounced exactly like the present. That's good news: you already know them. The only clue that it's a subjunctive is the \"que\" and the trigger before it.",
          "Because they sound the same, the risk is in writing: don't forget the -es for \"tu\" and the -ent for \"ils\". These are household-chore verbs you'll use all the time: \"ranger\" (to tidy), \"laver\" (to wash), \"nettoyer\" (to clean), \"passer l'aspirateur\" (to vacuum), \"vider le lave-vaisselle\" (to empty the dishwasher), \"arroser les plantes\" (to water the plants).",
        ],
        examples: [
          { es: "Il faut que je range le garage ce week-end.", en: "I have to tidy the garage this weekend." },
          { es: "Il faut que tu laves tes vêtements de sport.", en: "You need to wash your sports kit." },
          { es: "Il faut qu'il passe l'aspirateur dans l'entrée.", en: "He has to vacuum the hall." },
          { es: "Il faut qu'elles rangent leurs jouets.", en: "They have to put their toys away." },
          { es: "Il faut que tu vides le lave-vaisselle.", en: "You need to empty the dishwasher." },
          { es: "Il faut qu'on arrose les plantes.", en: "We need to water the plants." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "You need to empty the dishwasher. (to a friend)",
            answer: "Il faut que tu vides le lave-vaisselle.",
            altAnswers: ["Tu dois vider le lave-vaisselle."],
            explanation: "\"Vider\" → \"que tu vides\": same sound as the present, -es in writing.",
          },
          {
            type: "fill-blank",
            prompt: "Write the French for the bold words.",
            en: "They have to [put away] their toys.",
            sentence: "Il faut qu'elles ___ leurs jouets.",
            answer: "rangent",
            explanation: "Ils/elles form of the subjunctive = present form: \"rangent\".",
          },
        ],
      },
      {
        heading: "Nettoyer, travailler, téléphoner, rentrer",
        body: [
          "Verbs in -oyer and -uyer change y to i before a silent ending: \"ils nettoient\" → \"que je nettoie, que tu nettoies, qu'il nettoie, qu'ils nettoient\". The same happens with \"essuyer\" (to wipe): \"que tu essuies\". (You'll see the nous form \"nettoyions\" in Part 2.)",
          "Most -er verbs are completely regular: \"travailler\" → \"que je travaille\", \"téléphoner\" → \"que tu téléphones\", \"rentrer\" → \"qu'il rentre\", \"aider\" → \"qu'elle aide\", \"préparer\", \"cuisiner\", \"changer\", \"manger\".",
        ],
        examples: [
          { es: "Il faut que je nettoie la salle de bains.", en: "I need to clean the bathroom." },
          { es: "Il faut que tu essuies la table.", en: "You need to wipe the table." },
          { es: "Il faut qu'il travaille samedi.", en: "He has to work on Saturday." },
          { es: "Il faut que tu téléphones à ta sœur.", en: "You need to ring your sister." },
          { es: "Il faut qu'ils rentrent avant la nuit.", en: "They need to get back before dark." },
          { es: "Il faut que j'aide mon père à déménager.", en: "I have to help my dad move." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "I need to clean the bathroom.",
            answer: "Il faut que je nettoie la salle de bains.",
            altAnswers: ["Je dois nettoyer la salle de bains.", "Il faut que je nettoie la salle de bain."],
            explanation: "Ils nettoient → \"que je nettoie\": y becomes i before a silent e.",
          },
          {
            type: "word-order",
            prompt: "Put the words in order to say: You need to ring your sister.",
            words: ["Il", "faut", "que", "tu", "téléphones", "à", "ta", "sœur."],
            translation: "You need to ring your sister.",
            explanation: "\"Téléphoner à\" + person; \"que tu téléphones\".",
          },
        ],
      },
      {
        heading: "House rules",
        body: [
          "\"Il faut que\" is perfect for house rules among flatmates or in a family. Use \"il faut que tout le monde...\" for everyone (singular verb!), \"il faut qu'on...\" for us, or name each person.",
          "Remember the difference: \"il faut ranger la cuisine\" (general: the kitchen has to be tidied) vs \"il faut que Thomas range la cuisine\" (Thomas specifically).",
        ],
        examples: [
          { es: "Il faut que tout le monde range sa vaisselle.", en: "Everyone has to put their dishes away." },
          { es: "Il faut que Thomas vide la poubelle le lundi.", en: "Thomas has to empty the bin on Mondays." },
          { es: "Il faut qu'on ferme la porte à clé le soir.", en: "We have to lock the door at night." },
          { es: "Il faut que la dernière personne ferme les fenêtres.", en: "The last person has to close the windows." },
          { es: "Il faut que chacun lave ses draps.", en: "Everyone has to wash their own sheets." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "Everyone has to put their dishes away.",
            answer: "Il faut que tout le monde range sa vaisselle.",
            altAnswers: ["Il faut que chacun range sa vaisselle."],
            explanation: "\"Tout le monde\" takes a singular verb: \"range\".",
          },
          {
            type: "speak",
            text: "Il faut qu'on ferme la porte à clé le soir.",
            prompt: "Say it in French: We have to lock the door at night.",
            explanation: "\"Qu'on ferme\": \"on\" takes the il form.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "I have to tidy the garage this weekend.",
        answer: "Il faut que je range le garage ce week-end.",
        altAnswers: ["Je dois ranger le garage ce week-end.", "Il faut que je range le garage ce weekend."],
        explanation: "\"Que je range\" = same as the present.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "He has to vacuum the hall.",
        answer: "Il faut qu'il passe l'aspirateur dans l'entrée.",
        altAnswers: ["Il doit passer l'aspirateur dans l'entrée."],
        explanation: "\"Passer l'aspirateur\" = to vacuum; \"qu'il passe\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "You need to wash your sports kit. (to a friend)",
        answer: "Il faut que tu laves tes affaires de sport.",
        altAnswers: ["Il faut que tu laves tes vêtements de sport.", "Tu dois laver tes affaires de sport."],
        explanation: "\"Que tu laves\": don't forget the -es.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "They need to get back before dark.",
        answer: "Il faut qu'ils rentrent avant la nuit.",
        altAnswers: ["Il faut qu'elles rentrent avant la nuit."],
        explanation: "\"Rentrent\" in the ils form, same as the present.",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "You need to [wipe] the table. (to a child)",
        sentence: "Il faut que tu ___ la table.",
        answer: "essuies",
        explanation: "-uyer verbs change y to i: \"que tu essuies\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "We need to [water] the plants.",
        sentence: "Il faut qu'on ___ les plantes.",
        answer: "arrose",
        explanation: "\"On\" takes the il form: \"arrose\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "Thomas has to [empty] the bin on Mondays.",
        sentence: "Il faut que Thomas ___ la poubelle le lundi.",
        answer: "vide",
        explanation: "Specific person → \"que\" + subjunctive.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: I have to help my dad move.",
        words: ["Il", "faut", "que", "j'aide", "mon", "père", "à", "déménager."],
        translation: "I have to help my dad move.",
        explanation: "\"Aider quelqu'un à\" + infinitive; \"que j'aide\".",
      },
      {
        type: "multiple-choice",
        question: "Which is correctly spelled?",
        options: [
          "Il faut que tu ranges ta chambre.",
          "Il faut que tu range ta chambre.",
          "Il faut que tu rangent ta chambre.",
          "Il faut que tu ranger ta chambre.",
        ],
        correctIndex: 0,
        explanation: "The tu form always ends in -es in the subjunctive of -er verbs.",
      },
      {
        type: "listen-choose",
        audio: "Il faut qu'ils rentrent avant minuit.",
        question: "What does it mean?",
        options: [
          "They come back before midnight.",
          "They came back before midnight.",
          "They have to be back before midnight.",
          "We have to be back before midnight.",
        ],
        correctIndex: 2,
        explanation: "\"Il faut qu'ils rentrent\": they have to come back.",
      },
      {
        type: "dictation",
        audio: "Il faut que tu nettoies la cuisine.",
        explanation: "\"Nettoies\": y becomes i before the silent -es.",
      },
      {
        type: "speak",
        text: "Il faut que je nettoie la salle de bains.",
        prompt: "Say it in French: I need to clean the bathroom.",
        tip: "\"Nettoie\" ends in a \"wa\" sound.",
        explanation: "Same pronunciation as the present \"je nettoie\".",
      },
    ],
  },
  {
    slug: "b1-pattern-subjunctive-ir-re-verbs",
    level: "FR-B1",
    number: 3,
    title: "Pattern Practice: Subjunctive of -ir and -re Verbs",
    summary: "Practise the -ir and -re verbs whose subjunctive you can actually hear: finisse, choisisse, parte, dorme, sorte, vende, attende, lise, écrive, dise, mette, connaisse.",
    duration: "13 min",
    sections: [
      {
        heading: "-ir verbs: finisse, parte, dorme",
        body: [
          "With -ir verbs the ils form gives you a stem with a pronounced consonant, and that consonant appears in every subjunctive form. \"Finir\": ils finissent → \"que je finisse\" (you hear -iss-, unlike \"je finis\"). \"Choisir\" → \"que je choisisse\". \"Réussir\" → \"que tu réussisses\".",
          "The \"partir\" group (partir, sortir, dormir, sentir, servir) drops a consonant in the singular present (\"je pars\", \"je dors\") but keeps it in the ils form: \"ils partent\" → \"que je parte\", \"ils dorment\" → \"que je dorme\", \"ils sortent\" → \"qu'il sorte\".",
        ],
        examples: [
          { es: "Il faut que je finisse ce dossier aujourd'hui.", en: "I have to finish this file today." },
          { es: "Il faut que tu choisisses une date.", en: "You need to choose a date." },
          { es: "Il faut qu'il réussisse son examen.", en: "He has to pass his exam." },
          { es: "Il faut que tu dormes plus.", en: "You need to sleep more." },
          { es: "Il faut qu'elle sorte le chien.", en: "She needs to take the dog out." },
          { es: "Il faut que je parte à huit heures.", en: "I have to leave at eight." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "You need to sleep more. (to a friend)",
            answer: "Il faut que tu dormes plus.",
            altAnswers: ["Il faut que tu dormes davantage.", "Tu dois dormir plus."],
            explanation: "Ils dorment → \"que tu dormes\": the m is pronounced, unlike \"tu dors\".",
          },
          {
            type: "fill-blank",
            prompt: "Write the French for the bold words.",
            en: "He has to [pass] his exam.",
            sentence: "Il faut qu'il ___ son examen.",
            answer: "réussisse",
            explanation: "Ils réussissent → réussiss- + -e. \"Réussir un examen\" = to pass an exam.",
          },
        ],
      },
      {
        heading: "-re verbs: vende, attende, lise, écrive, dise, mette",
        body: [
          "Regular -re verbs keep their d: \"ils vendent\" → \"que je vende\", \"ils attendent\" → \"que tu attendes\", \"ils répondent\" → \"qu'il réponde\", \"ils descendent\" → \"que je descende\".",
          "Several common -re verbs have a stem that isn't obvious from the infinitive, which is why the ils form is your key: \"lire\" → ils lisent → \"que je lise\"; \"écrire\" → ils écrivent → \"que j'écrive\"; \"dire\" → ils disent → \"que je dise\"; \"mettre\" → ils mettent → \"que je mette\"; \"connaître\" → ils connaissent → \"que je connaisse\".",
          "Never build the subjunctive from the infinitive: \"*qu'il vendre\", \"*que je lire\" are classic errors.",
        ],
        examples: [
          { es: "Il faut que je vende ma vieille voiture.", en: "I have to sell my old car." },
          { es: "Il faut que tu attendes ton frère.", en: "You have to wait for your brother." },
          { es: "Il faut qu'il réponde à ce mail.", en: "He needs to answer this email." },
          { es: "Il faut que tu lises ce roman !", en: "You must read this novel!" },
          { es: "Il faut que j'écrive à la banque.", en: "I need to write to the bank." },
          { es: "Il faut que tu lui dises la vérité.", en: "You have to tell her the truth." },
          { es: "Il faut qu'elle mette une veste, il fait froid.", en: "She needs to put a jacket on, it's cold." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "You have to tell her the truth. (to a friend)",
            answer: "Il faut que tu lui dises la vérité.",
            altAnswers: ["Tu dois lui dire la vérité."],
            explanation: "Ils disent → \"que tu dises\"; \"lui\" before the verb.",
          },
          {
            type: "fill-blank",
            prompt: "Write the French for the bold words.",
            en: "I need to [write] to the bank.",
            sentence: "Il faut que j'___ à la banque.",
            answer: "écrive",
            explanation: "Ils écrivent → \"que j'écrive\".",
          },
          {
            type: "multiple-choice",
            question: "Which form is correct?",
            options: [
              "Il faut qu'il vendre sa moto.",
              "Il faut qu'il vende sa moto.",
              "Il faut qu'il vend sa moto.",
              "Il faut qu'il vendes sa moto.",
            ],
            correctIndex: 1,
            explanation: "Ils vendent → vend- + -e. Never build the subjunctive from the infinitive.",
          },
        ],
      },
      {
        heading: "Connaître and the big picture",
        body: [
          "\"Connaître\" → ils connaissent → \"que je connaisse\": \"il faut que tu connaisses mes parents\" (you have to meet my parents). The same pattern works for \"paraître\", \"reconnaître\", \"disparaître\".",
          "Here's the whole table in one breath: \"finisse, choisisse, réussisse, parte, sorte, dorme, vende, attende, réponde, lise, écrive, dise, mette, connaisse\". Every one comes from the ils form. You'll also notice they're all audible: the subjunctive of these verbs sounds different from the present in the singular.",
        ],
        examples: [
          { es: "Il faut que tu connaisses mes parents.", en: "You have to meet my parents." },
          { es: "Il faut qu'il reconnaisse son erreur.", en: "He has to admit his mistake." },
          { es: "Il faut que je réfléchisse.", en: "I need to think about it." },
          { es: "Il faut qu'on réponde avant vendredi.", en: "We have to reply before Friday." },
          { es: "Il faut que tu descendes les poubelles.", en: "You need to take the rubbish down." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "I need to think about it.",
            answer: "Il faut que je réfléchisse.",
            altAnswers: ["Il faut que j'y réfléchisse.", "Je dois réfléchir.", "Je dois y réfléchir."],
            explanation: "Ils réfléchissent → \"que je réfléchisse\".",
          },
          {
            type: "speak",
            text: "Il faut que tu connaisses mes parents.",
            prompt: "Say it in French: You have to meet my parents. (to a friend)",
            tip: "\"Connaisses\" has a clear s sound before the end.",
            explanation: "Ils connaissent → \"que tu connaisses\".",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "I have to sell my old car.",
        answer: "Il faut que je vende ma vieille voiture.",
        altAnswers: ["Je dois vendre ma vieille voiture."],
        explanation: "Ils vendent → \"que je vende\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "You have to wait for your brother. (to a child)",
        answer: "Il faut que tu attendes ton frère.",
        altAnswers: ["Tu dois attendre ton frère."],
        explanation: "\"Attendre\" takes a direct object: no \"pour\". \"Que tu attendes\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "He needs to answer this email.",
        answer: "Il faut qu'il réponde à ce mail.",
        altAnswers: [
          "Il faut qu'il réponde à cet e-mail.",
          "Il doit répondre à ce mail.",
          "Il faut qu'il réponde à ce courriel.",
        ],
        explanation: "\"Répondre à\"; ils répondent → \"qu'il réponde\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "She needs to put a jacket on.",
        answer: "Il faut qu'elle mette une veste.",
        altAnswers: ["Elle doit mettre une veste."],
        explanation: "Ils mettent → \"qu'elle mette\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "You need to [choose] a date. (to a friend)",
        sentence: "Il faut que tu ___ une date.",
        answer: "choisisses",
        explanation: "Ils choisissent → \"que tu choisisses\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "She needs to [take] the dog [out].",
        sentence: "Il faut qu'elle ___ le chien.",
        answer: "sorte",
        explanation: "Ils sortent → \"qu'elle sorte\"; the t is audible.",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "You must [read] this book! (to a friend)",
        sentence: "Il faut que tu ___ ce livre !",
        answer: "lises",
        explanation: "Ils lisent → \"que tu lises\".",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: I have to finish this file today.",
        words: ["Il", "faut", "que", "je", "finisse", "ce", "dossier", "aujourd'hui."],
        translation: "I have to finish this file today.",
        explanation: "Ils finissent → \"que je finisse\".",
      },
      {
        type: "matching",
        instructions: "Match each infinitive with its subjunctive (que je...).",
        pairs: [
          { left: "lire", right: "lise" },
          { left: "écrire", right: "écrive" },
          { left: "dire", right: "dise" },
          { left: "mettre", right: "mette" },
          { left: "connaître", right: "connaisse" },
          { left: "dormir", right: "dorme" },
        ],
        explanation: "Each subjunctive stem comes from the ils form of the present.",
      },
      {
        type: "listen-choose",
        audio: "Il faut que tu dormes.",
        question: "What did you hear?",
        options: ["Il faut que tu dors.", "Il faut que tu dormes.", "Il faut dormir.", "Il faut que tu sortes."],
        correctIndex: 1,
        explanation: "You hear the m in \"dormes\": that's the subjunctive.",
      },
      {
        type: "dictation",
        audio: "Il faut qu'il réponde à ce mail.",
        explanation: "Ils répondent → \"qu'il réponde\".",
      },
      {
        type: "speak",
        text: "Il faut que je parte à huit heures.",
        prompt: "Say it in French: I have to leave at eight.",
        tip: "Pronounce the t of \"parte\".",
        explanation: "Ils partent → \"que je parte\".",
      },
    ],
  },
  {
    slug: "b1-minimal-pairs-il-finit-quil-finisse",
    level: "FR-B1",
    number: 4,
    title: "Minimal Pairs: Il finit / Qu'il finisse",
    summary: "Train your ear to hear the subjunctive: the final consonant that the present drops and the subjunctive pronounces.",
    duration: "12 min",
    sections: [
      {
        heading: "The silent consonant comes back",
        body: [
          "In the present singular of many -ir and -re verbs, the final consonant is silent: \"il part\" sounds like \"par\", \"il dort\" like \"dor\", \"il lit\" like \"li\". In the subjunctive, the ending -e makes that consonant audible: \"qu'il parte\" [part], \"qu'il dorme\" [dɔʁm], \"qu'il lise\" [liz].",
          "So for these verbs, one sound tells you which mood you're hearing. Listen for the consonant at the end: no consonant, it's the present; a consonant, it's the subjunctive (or the ils form, which you'll tell apart by the subject).",
          "When you speak, really pronounce that consonant. If you say \"il faut qu'il par\", a French speaker will understand, but it sounds like a mistake.",
        ],
        examples: [
          { es: "Il part demain.", en: "He's leaving tomorrow." },
          { es: "Il faut qu'il parte demain.", en: "He has to leave tomorrow." },
          { es: "Il dort mal.", en: "He sleeps badly." },
          { es: "Il faut qu'il dorme.", en: "He needs to sleep." },
          { es: "Il lit le journal.", en: "He's reading the paper." },
          { es: "Il faut qu'il lise le contrat.", en: "He needs to read the contract." },
        ],
        checkpoint: [
          {
            type: "listen-choose",
            audio: "Il faut qu'il dorme.",
            question: "What did you hear?",
            options: ["Il faut qu'il dort.", "Il faut dormir.", "Il faut qu'il dorme.", "Il faut qu'il sorte."],
            correctIndex: 2,
            explanation: "The m is pronounced: \"dorme\", subjunctive after \"il faut que\".",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "He needs to read the contract.",
            answer: "Il faut qu'il lise le contrat.",
            altAnswers: ["Il doit lire le contrat."],
            explanation: "Ils lisent → \"qu'il lise\", with an audible z sound.",
          },
        ],
      },
      {
        heading: "Écrit / écrive, met / mette, finit / finisse",
        body: [
          "More pairs: \"il écrit\" [ekʁi] / \"qu'il écrive\" [ekʁiv]; \"il met\" [mɛ] / \"qu'il mette\" [mɛt]; \"il dit\" [di] / \"qu'il dise\" [diz]; \"il finit\" [fini] / \"qu'il finisse\" [finis]; \"il sort\" / \"qu'il sorte\"; \"il attend\" / \"qu'il attende\"; \"il connaît\" / \"qu'il connaisse\".",
          "For the -ir verbs like \"finir\", the subjunctive is a syllable longer: \"fi-nisse\" vs \"fi-ni\". For \"mettre\" and \"attendre\" it's the final t or d that appears.",
        ],
        examples: [
          { es: "Il écrit beaucoup.", en: "He writes a lot." },
          { es: "Il faut qu'il écrive une lettre de motivation.", en: "He has to write a cover letter." },
          { es: "Elle met la table.", en: "She's setting the table." },
          { es: "Il faut qu'elle mette la table.", en: "She needs to set the table." },
          { es: "Il finit à six heures.", en: "He finishes at six." },
          { es: "Il faut qu'il finisse avant six heures.", en: "He has to finish before six." },
          { es: "Il faut qu'elle attende.", en: "She has to wait." },
        ],
        checkpoint: [
          {
            type: "listen-choose",
            audio: "Il faut qu'elle mette la table.",
            question: "What did you hear?",
            options: [
              "Il faut qu'elle met la table.",
              "Elle met la table.",
              "Il faut mettre la table.",
              "Il faut qu'elle mette la table.",
            ],
            correctIndex: 3,
            explanation: "The t of \"mette\" is audible: subjunctive.",
          },
          {
            type: "fill-blank",
            prompt: "Write the French for the bold words.",
            en: "He has to [finish] before six.",
            sentence: "Il faut qu'il ___ avant six heures.",
            answer: "finisse",
            explanation: "Ils finissent → \"qu'il finisse\": one syllable more than \"il finit\".",
          },
          {
            type: "word-order",
            prompt: "Put the words in order to say: He has to write a cover letter.",
            words: ["Il", "faut", "qu'il", "écrive", "une", "lettre", "de", "motivation."],
            translation: "He has to write a cover letter.",
            explanation: "Ils écrivent → \"qu'il écrive\", with an audible v.",
          },
        ],
      },
      {
        heading: "Your turn to say them",
        body: [
          "Practise the pairs out loud: \"il part / qu'il parte\", \"il dort / qu'il dorme\", \"il lit / qu'il lise\", \"il écrit / qu'il écrive\", \"il met / qu'il mette\", \"il finit / qu'il finisse\". Exaggerate the final consonant at first; it will soften naturally.",
          "Remember that -er verbs give you no such clue: \"il range\" and \"qu'il range\" sound the same. That's why the -ir and -re verbs are the ones that reveal whether a French speaker is using the subjunctive.",
        ],
        examples: [
          { es: "Il faut qu'il sorte les poubelles.", en: "He needs to take the bins out." },
          { es: "Il faut qu'elle dise oui.", en: "She has to say yes." },
          { es: "Il faut qu'il connaisse le code.", en: "He needs to know the door code." },
          { es: "Il faut qu'on attende le bus.", en: "We have to wait for the bus." },
          { es: "Il faut qu'il range sa chambre.", en: "He has to tidy his room." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "She has to say yes.",
            answer: "Il faut qu'elle dise oui.",
            altAnswers: ["Elle doit dire oui."],
            explanation: "Ils disent → \"qu'elle dise\".",
          },
          {
            type: "speak",
            text: "Il faut qu'il sorte les poubelles.",
            prompt: "Say it in French: He needs to take the bins out.",
            tip: "Pronounce the t of \"sorte\".",
            explanation: "Ils sortent → \"qu'il sorte\".",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "listen-choose",
        audio: "Il faut qu'il parte.",
        question: "What did you hear?",
        options: ["Il faut qu'il part.", "Il faut qu'il parle.", "Il faut qu'il parte.", "Il faut partir."],
        correctIndex: 2,
        explanation: "The t is audible: \"parte\".",
      },
      {
        type: "listen-choose",
        audio: "Il lit le journal.",
        question: "What did you hear?",
        options: [
          "Il faut qu'il lise le journal.",
          "Il lisait le journal.",
          "Il lit le journal.",
          "Ils lisent le journal.",
        ],
        correctIndex: 2,
        explanation: "No z sound at the end of \"lit\": the present.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "He's leaving tomorrow.",
        answer: "Il part demain.",
        explanation: "A plain fact: present indicative.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "He has to leave tomorrow.",
        answer: "Il faut qu'il parte demain.",
        altAnswers: ["Il doit partir demain."],
        explanation: "After \"il faut que\", the subjunctive: \"parte\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "He needs to sleep.",
        answer: "Il faut qu'il dorme.",
        altAnswers: ["Il doit dormir."],
        explanation: "Ils dorment → \"qu'il dorme\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "She has to [wait].",
        sentence: "Il faut qu'elle ___.",
        answer: "attende",
        explanation: "Ils attendent → \"qu'elle attende\"; the d is audible.",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "He needs to [know] the door code.",
        sentence: "Il faut qu'il ___ le code.",
        answer: "connaisse",
        explanation: "Ils connaissent → \"qu'il connaisse\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "She [writes] a lot.",
        sentence: "Elle ___ beaucoup.",
        answer: "écrit",
        explanation: "A fact: present indicative, final t silent.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: She needs to set the table.",
        words: ["Il", "faut", "qu'elle", "mette", "la", "table."],
        translation: "She needs to set the table.",
        explanation: "Ils mettent → \"qu'elle mette\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "We have to wait for the bus.",
        answer: "Il faut qu'on attende le bus.",
        altAnswers: ["Il faut que nous attendions le bus.", "On doit attendre le bus.", "Nous devons attendre le bus."],
        explanation: "\"Attendre\" takes a direct object; \"qu'on attende\".",
      },
      {
        type: "dictation",
        audio: "Il faut qu'elle écrive à sa mère.",
        explanation: "\"Écrive\": the v is pronounced in the subjunctive.",
      },
      {
        type: "speak",
        text: "Il faut qu'il finisse avant six heures.",
        prompt: "Say it in French: He has to finish before six.",
        tip: "\"Finisse\" has three syllables: fi-ni-sse.",
        explanation: "Ils finissent → \"qu'il finisse\".",
      },
    ],
  },
  {
    slug: "b1-subjunctive-forms-2",
    level: "FR-B1",
    number: 5,
    title: "The Present Subjunctive: Regular Forms, Part 2 of 2",
    summary: "Complete the table with the nous and vous forms in -ions and -iez, watch the double-i spellings, and choose between il faut + infinitive and il faut que + subjunctive.",
    duration: "14 min",
    sections: [
      {
        heading: "Que nous parlions, que vous finissiez",
        body: [
          "The nous and vous forms of the subjunctive take the endings -ions and -iez. For regular verbs, the stem is the same as the nous form of the present: \"nous parlons\" → \"que nous parlions\", \"nous finissons\" → \"que vous finissiez\", \"nous attendons\" → \"que nous attendions\".",
          "If those forms look familiar, it's because they're identical to the imparfait: \"nous parlions\" can be imparfait (we were talking) or subjunctive (that we talk). The trigger \"que\" + \"il faut\" tells you which one it is.",
          "The full table for \"parler\": \"que je parle, que tu parles, qu'il parle, que nous parlions, que vous parliez, qu'ils parlent\".",
        ],
        examples: [
          { es: "Il faut que nous parlions.", en: "We need to talk." },
          { es: "Il faut que vous finissiez ce soir.", en: "You have to finish tonight." },
          { es: "Il faut que nous attendions le plombier.", en: "We have to wait for the plumber." },
          { es: "Il faut que vous lisiez les consignes.", en: "You need to read the instructions." },
          { es: "Il faut que nous partions tôt demain.", en: "We have to leave early tomorrow." },
          { es: "Il faut que vous écriviez votre nom ici.", en: "You need to write your name here." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "We need to talk.",
            answer: "Il faut que nous parlions.",
            altAnswers: ["Il faut qu'on parle.", "Nous devons parler.", "On doit parler."],
            explanation: "Nous parlons → \"que nous parlions\": the nous subjunctive = the imparfait form.",
          },
          {
            type: "fill-blank",
            prompt: "Write the French for the bold words.",
            en: "You need to [write] your name here. (formal)",
            sentence: "Il faut que vous ___ votre nom ici.",
            answer: "écriviez",
            explanation: "Nous écrivons → \"que vous écriviez\".",
          },
        ],
      },
      {
        heading: "Double i: étudiions, riiez",
        body: [
          "Verbs whose stem ends in -i (\"étudier\", \"oublier\", \"crier\", \"rire\", \"sourire\") produce a double i in the nous and vous forms: stem \"étudi-\" + \"-ions\" = \"que nous étudiions\"; \"ri-\" + \"-iez\" = \"que vous riiez\". It looks strange, but it's correct, and the same happens in the imparfait.",
          "Verbs in -oyer and -uyer bring back the y in nous and vous: \"que je nettoie\" but \"que nous nettoyions\", \"que vous essuyiez\". In speech, the double i or \"yi\" sounds like a slightly longer i.",
        ],
        examples: [
          { es: "Il faut que nous étudiions ce chapitre.", en: "We need to study this chapter." },
          { es: "Il ne faut pas que vous oubliiez vos clés.", en: "You mustn't forget your keys." },
          { es: "Il faut que vous riiez un peu, ça fait du bien !", en: "You need to laugh a bit, it does you good!" },
          { es: "Il faut que nous nettoyions la terrasse.", en: "We need to clean the terrace." },
          { es: "Il faut que vous essuyiez vos chaussures.", en: "You need to wipe your shoes." },
        ],
        checkpoint: [
          {
            type: "fill-blank",
            prompt: "Write the French for the bold words.",
            en: "We need to [study] this chapter.",
            sentence: "Il faut que nous ___ ce chapitre.",
            answer: "étudiions",
            explanation: "Stem \"étudi-\" + \"-ions\" = double i: \"étudiions\".",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "You mustn't forget your keys. (to several people)",
            answer: "Il ne faut pas que vous oubliiez vos clés.",
            altAnswers: ["Vous ne devez pas oublier vos clés.", "N'oubliez pas vos clés."],
            explanation: "\"Oubli-\" + \"-iez\" gives a double i: \"oubliiez\".",
          },
        ],
      },
      {
        heading: "General rule or specific person?",
        body: [
          "Now the choice. \"Il faut\" + infinitive states a general necessity: \"il faut partir\" (it's time to go / we must go), \"il faut réserver\" (you have to book). It doesn't name anyone.",
          "\"Il faut que\" + subjunctive names who has to do it: \"il faut que vous partiez\" (you have to leave), \"il faut que Thomas réserve\". If the person is obvious from context you can often use either; but as soon as you want to point at someone, you need \"que\".",
          "You can also put a pronoun with \"falloir\": \"il me faut un stylo\" (I need a pen). But \"*il me faut partir\" is old-fashioned; in modern speech, \"il faut que je parte\".",
        ],
        examples: [
          { es: "Il faut réserver à l'avance.", en: "You have to book in advance." },
          { es: "Il faut que vous réserviez à l'avance.", en: "You need to book in advance." },
          { es: "Il faut partir, il est tard.", en: "We have to go, it's late." },
          { es: "Il faut que vous partiez, on ferme.", en: "You have to leave, we're closing." },
          { es: "Pour réussir, il faut travailler.", en: "To succeed, you have to work." },
          { es: "Il faut que vous travailliez plus.", en: "You need to work harder." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "You have to leave, we're closing. (formal)",
            answer: "Il faut que vous partiez, on ferme.",
            altAnswers: ["Il faut que vous partiez, nous fermons.", "Vous devez partir, on ferme."],
            explanation: "A specific person: \"il faut que vous\" + \"partiez\".",
          },
          {
            type: "multiple-choice",
            question: "Which sentence states a general rule?",
            options: [
              "Il faut que vous réserviez à l'avance.",
              "Il faut que Thomas réserve.",
              "Il faut réserver à l'avance.",
              "Il faut qu'on réserve.",
            ],
            correctIndex: 2,
            explanation: "\"Il faut\" + infinitive names no one: a general rule.",
          },
          {
            type: "speak",
            text: "Il faut que nous partions tôt demain.",
            prompt: "Say it in French: We have to leave early tomorrow.",
            explanation: "Nous partons → \"que nous partions\".",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "You have to finish tonight. (to colleagues)",
        answer: "Il faut que vous finissiez ce soir.",
        altAnswers: ["Vous devez finir ce soir."],
        explanation: "Nous finissons → \"que vous finissiez\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "We have to wait for the plumber.",
        answer: "Il faut que nous attendions le plombier.",
        altAnswers: [
          "Il faut qu'on attende le plombier.",
          "Nous devons attendre le plombier.",
          "On doit attendre le plombier.",
        ],
        explanation: "\"Attendions\": nous form of the subjunctive.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "You need to read the instructions. (formal)",
        answer: "Il faut que vous lisiez les consignes.",
        altAnswers: ["Il faut que vous lisiez les instructions.", "Vous devez lire les consignes."],
        explanation: "Nous lisons → \"que vous lisiez\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "You have to book in advance.",
        answer: "Il faut réserver à l'avance.",
        altAnswers: ["Il faut réserver en avance."],
        explanation: "A general rule: \"il faut\" + infinitive.",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "We need to [clean] the terrace.",
        sentence: "Il faut que nous ___ la terrasse.",
        answer: "nettoyions",
        explanation: "-oyer verbs bring back the y in the nous form: \"nettoyions\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "You need to [laugh] a bit! (to friends)",
        sentence: "Il faut que vous ___ un peu !",
        answer: "riiez",
        explanation: "\"Ri-\" + \"-iez\" = \"riiez\", with a double i.",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "To succeed, you [have to work].",
        sentence: "Pour réussir, ___.",
        answer: "il faut travailler",
        explanation: "A general truth: \"il faut\" + infinitive.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: You need to work harder.",
        words: ["Il", "faut", "que", "vous", "travailliez", "plus."],
        translation: "You need to work harder.",
        explanation: "Nous travaillons → \"que vous travailliez\" (ill + iez).",
      },
      {
        type: "multiple-choice",
        question: "Which form is the subjunctive of « nous oublions »?",
        options: ["que nous oublions", "que nous oublieons", "que nous oubliions", "que nous oubliyons"],
        correctIndex: 2,
        explanation: "\"Oubli-\" + \"-ions\" gives a double i.",
      },
      {
        type: "listen-choose",
        audio: "Il faut que nous parlions.",
        question: "What does it mean?",
        options: ["We need to talk.", "We were talking.", "We are talking.", "We will talk."],
        correctIndex: 0,
        explanation: "\"Il faut que\" makes \"parlions\" a subjunctive: we need to talk. Without \"il faut que\", \"nous parlions\" would be the imparfait.",
      },
      {
        type: "dictation",
        audio: "Il faut que vous essuyiez vos chaussures.",
        explanation: "\"Essuyiez\": the y comes back in the vous form.",
      },
      {
        type: "speak",
        text: "Il faut que vous réserviez à l'avance.",
        prompt: "Say it in French: You need to book in advance. (formal)",
        explanation: "Specific \"vous\" → \"il faut que vous réserviez\".",
      },
    ],
  },
  {
    slug: "b1-transformations-indicative-to-subjunctive",
    level: "FR-B1",
    number: 6,
    title: "Transformations: From Indicative to Subjunctive",
    summary: "Take present-tense statements and put them after \"il faut que\", step by step, in every person.",
    duration: "13 min",
    sections: [
      {
        heading: "Step by step",
        body: [
          "The transformation has three steps. 1. Find the ils form of the present (\"ils rangent\", \"ils lisent\"). 2. Take off -ent to get the stem (\"rang-\", \"lis-\"). 3. Add the right ending for your subject: -e, -es, -e, -ions, -iez, -ent. For nous and vous, use the nous stem (\"nous attendons\" → \"attend-\").",
          "Then put it after \"il faut que\": \"Tu ranges ta chambre.\" → \"Il faut que tu ranges ta chambre.\" \"Vous attendez.\" → \"Il faut que vous attendiez.\" \"Ils lisent.\" → \"Il faut qu'ils lisent.\"",
        ],
        examples: [
          { es: "Tu ranges ta chambre. → Il faut que tu ranges ta chambre.", en: "You tidy your room. → You have to tidy your room." },
          { es: "Vous attendez ici. → Il faut que vous attendiez ici.", en: "You wait here. → You have to wait here." },
          { es: "Ils lisent le règlement. → Il faut qu'ils lisent le règlement.", en: "They read the rules. → They have to read the rules." },
          { es: "Elle part tôt. → Il faut qu'elle parte tôt.", en: "She leaves early. → She has to leave early." },
          { es: "Nous finissons ce soir. → Il faut que nous finissions ce soir.", en: "We finish tonight. → We have to finish tonight." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "You have to wait here. (formal)",
            answer: "Il faut que vous attendiez ici.",
            altAnswers: ["Vous devez attendre ici."],
            explanation: "Vous attendez → \"que vous attendiez\".",
          },
          {
            type: "fill-blank",
            prompt: "Write the French for the bold words.",
            en: "She leaves early. → She [has to leave] early.",
            sentence: "Il faut qu'elle ___ tôt.",
            answer: "parte",
            explanation: "Elle part → \"qu'elle parte\".",
          },
        ],
      },
      {
        heading: "Exam week",
        body: [
          "Let's apply it to a student's week before exams. Statements first: « Je révise tous les soirs. Tu dors peu. Nous lisons nos notes. Vous répondez aux questions. Ils choisissent un sujet. »",
          "Now the necessities: « Il faut que je révise tous les soirs. Il faut que tu dormes plus. Il faut que nous lisions nos notes. Il faut que vous répondiez aux questions. Il faut qu'ils choisissent un sujet. » Notice which ones change sound: \"dormes\", \"lisions\", \"répondiez\", \"choisissent\" (same as the present for ils).",
        ],
        examples: [
          { es: "Il faut que je révise tous les soirs.", en: "I have to revise every evening." },
          { es: "Il faut que tu dormes plus.", en: "You need to sleep more." },
          { es: "Il faut que nous lisions nos notes.", en: "We need to read our notes." },
          { es: "Il faut que vous répondiez à toutes les questions.", en: "You have to answer all the questions." },
          { es: "Il faut qu'ils choisissent un sujet.", en: "They have to choose a topic." },
          { es: "Il faut qu'on réussisse cet examen.", en: "We have to pass this exam." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "You have to answer all the questions. (to a class)",
            answer: "Il faut que vous répondiez à toutes les questions.",
            altAnswers: ["Vous devez répondre à toutes les questions."],
            explanation: "Vous répondez → \"que vous répondiez\".",
          },
          {
            type: "word-order",
            prompt: "Put the words in order to say: We need to read our notes.",
            words: ["Il", "faut", "que", "nous", "lisions", "nos", "notes."],
            translation: "We need to read our notes.",
            explanation: "Nous lisons → \"que nous lisions\".",
          },
        ],
      },
      {
        heading: "With pronouns and negatives",
        body: [
          "Pronouns stay in the same place, just before the verb: \"Tu lui écris.\" → \"Il faut que tu lui écrives.\" \"Vous les attendez.\" → \"Il faut que vous les attendiez.\"",
          "For a negative, you can negate \"falloir\" (\"il ne faut pas que tu partes\" = you mustn't leave) or the subjunctive verb (\"il faut que tu ne dises rien\" = you must say nothing). The first is much more common.",
        ],
        examples: [
          { es: "Tu lui écris. → Il faut que tu lui écrives.", en: "You write to him. → You need to write to him." },
          { es: "Vous les attendez. → Il faut que vous les attendiez.", en: "You wait for them. → You have to wait for them." },
          { es: "Il ne faut pas que tu sortes ce soir.", en: "You mustn't go out tonight." },
          { es: "Il faut que tu ne dises rien à personne.", en: "You must say nothing to anyone." },
          { es: "Il faut qu'on leur téléphone.", en: "We need to ring them." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "You need to write to him. (to a friend)",
            answer: "Il faut que tu lui écrives.",
            altAnswers: ["Tu dois lui écrire."],
            explanation: "The pronoun \"lui\" stays before the verb; \"que tu écrives\".",
          },
          {
            type: "speak",
            text: "Il ne faut pas que tu sortes ce soir.",
            prompt: "Say it in French: You mustn't go out tonight. (to a friend)",
            explanation: "\"Il ne faut pas que\" + \"sortes\".",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "You have to tidy your room. (to a child)",
        answer: "Il faut que tu ranges ta chambre.",
        altAnswers: ["Tu dois ranger ta chambre."],
        explanation: "Tu ranges → \"que tu ranges\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "They have to read the rules.",
        answer: "Il faut qu'ils lisent le règlement.",
        altAnswers: ["Il faut qu'elles lisent le règlement.", "Ils doivent lire le règlement."],
        explanation: "Ils lisent → \"qu'ils lisent\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "We have to finish tonight.",
        answer: "Il faut que nous finissions ce soir.",
        altAnswers: ["Il faut qu'on finisse ce soir.", "Nous devons finir ce soir.", "On doit finir ce soir."],
        explanation: "Nous finissons → \"que nous finissions\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "I have to revise every evening.",
        answer: "Il faut que je révise tous les soirs.",
        altAnswers: ["Je dois réviser tous les soirs."],
        explanation: "\"Que je révise\": -er verb, same as the present.",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "They have to [choose] a topic.",
        sentence: "Il faut qu'ils ___ un sujet.",
        answer: "choisissent",
        explanation: "Ils choisissent: the ils subjunctive is the same as the present.",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "You have to [wait for them]. (formal)",
        sentence: "Il faut que vous ___.",
        answer: "les attendiez",
        explanation: "Pronoun before the verb; \"attendiez\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "We have to [pass] this exam.",
        sentence: "Il faut qu'on ___ cet examen.",
        answer: "réussisse",
        explanation: "\"On\" + il form: \"réussisse\".",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: You mustn't go out tonight.",
        words: ["Il", "ne", "faut", "pas", "que", "tu", "sortes", "ce", "soir."],
        translation: "You mustn't go out tonight.",
        explanation: "\"Il ne faut pas que\" = mustn't.",
      },
      {
        type: "multiple-choice",
        question: "Transform « Vous dormez peu » into a necessity.",
        options: [
          "Il faut que vous dormez plus.",
          "Il faut que vous dormes plus.",
          "Il faut que vous dormiez plus.",
          "Il faut vous dormir plus.",
        ],
        correctIndex: 2,
        explanation: "Vous form: nous stem \"dorm-\" + \"-iez\".",
      },
      {
        type: "listen-choose",
        audio: "Il faut que vous répondiez.",
        question: "What does it mean?",
        options: ["You have to reply.", "You are replying.", "You were replying.", "Reply!"],
        correctIndex: 0,
        explanation: "\"Il faut que vous répondiez\": subjunctive after il faut que.",
      },
      {
        type: "dictation",
        audio: "Il faut qu'ils choisissent un sujet.",
        explanation: "The ils subjunctive looks like the present: \"choisissent\".",
      },
      {
        type: "speak",
        text: "Il faut que vous attendiez ici.",
        prompt: "Say it in French: You have to wait here. (formal)",
        explanation: "Vous attendez → \"que vous attendiez\".",
      },
    ],
  },
  {
    slug: "b1-minimal-pairs-nous-parlons-parlions",
    level: "FR-B1",
    number: 7,
    title: "Minimal Pairs: Nous parlons / Que nous parlions",
    summary: "Hear and spell the contrast between the nous and vous forms of the present and the subjunctive, and notice the link with the imparfait.",
    duration: "12 min",
    sections: [
      {
        heading: "-ons or -ions? -ez or -iez?",
        body: [
          "In the nous and vous forms, the present and the subjunctive differ by one small sound: the [j] of the i. \"Nous parlons\" [paʁlɔ̃] vs \"que nous parlions\" [paʁljɔ̃]. \"Vous finissez\" [finise] vs \"que vous finissiez\" [finisje]. It's like the y sound in English \"yes\" slipped in before the ending.",
          "That y-sound is your marker. Without it: present. With it: subjunctive (or imparfait). Practise saying \"parlons / parlions\" slowly: par-lons, par-li-ons → par-lyons.",
        ],
        examples: [
          { es: "Nous partons demain.", en: "We're leaving tomorrow." },
          { es: "Il faut que nous partions demain.", en: "We have to leave tomorrow." },
          { es: "Vous finissez à quelle heure ?", en: "What time do you finish?" },
          { es: "Il faut que vous finissiez avant midi.", en: "You have to finish before noon." },
          { es: "Nous attendons le taxi.", en: "We're waiting for the taxi." },
          { es: "Il faut que nous attendions le taxi.", en: "We have to wait for the taxi." },
        ],
        checkpoint: [
          {
            type: "listen-choose",
            audio: "Il faut que nous partions demain.",
            question: "What did you hear?",
            options: [
              "Il faut que nous partions demain.",
              "Il faut que nous partons demain.",
              "Nous partons demain.",
              "Il faut partir demain.",
            ],
            correctIndex: 0,
            explanation: "You hear the y sound in \"partions\": subjunctive.",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "We have to leave tomorrow.",
            answer: "Il faut que nous partions demain.",
            altAnswers: ["Il faut qu'on parte demain.", "Nous devons partir demain.", "On doit partir demain."],
            explanation: "Nous partons → \"que nous partions\".",
          },
        ],
      },
      {
        heading: "Same form as the imparfait",
        body: [
          "For regular verbs, the nous and vous subjunctive forms are spelled exactly like the imparfait: \"nous parlions\", \"vous finissiez\". Context tells them apart. \"Quand nous étions petits, nous parlions anglais\" (imparfait: we used to speak). \"Il faut que nous parlions\" (subjunctive: we need to talk).",
          "This is useful: if you know the imparfait, you already know the nous and vous subjunctive of regular verbs. (Careful: this won't be true for the irregular verbs of Unit 3, like \"être\": \"nous étions\" but \"que nous soyons\".)",
        ],
        examples: [
          { es: "Avant, nous parlions tous les jours.", en: "We used to talk every day." },
          { es: "Il faut que nous parlions de l'avenir.", en: "We need to talk about the future." },
          { es: "Vous dormiez quand j'ai appelé ?", en: "Were you asleep when I called?" },
          { es: "Il faut que vous dormiez au moins huit heures.", en: "You need to sleep at least eight hours." },
          { es: "Nous lisions des BD quand nous étions petits.", en: "We used to read comics when we were little." },
          { es: "Il faut que nous lisions ce rapport.", en: "We need to read this report." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "In which sentence is « parlions » a subjunctive?",
            options: [
              "Avant, nous parlions tous les jours.",
              "Nous parlions quand il est arrivé.",
              "Il faut que nous parlions à ton père.",
              "Quand nous étions jeunes, nous parlions espagnol.",
            ],
            correctIndex: 2,
            explanation: "After \"il faut que\", \"parlions\" is a subjunctive. In the others it's the imparfait.",
          },
          {
            type: "fill-blank",
            prompt: "Write the French for the bold words.",
            en: "You need to [sleep] at least eight hours. (formal)",
            sentence: "Il faut que vous ___ au moins huit heures.",
            answer: "dormiez",
            explanation: "\"Dormiez\" is both imparfait and subjunctive; here \"il faut que\" makes it a subjunctive.",
          },
        ],
      },
      {
        heading: "Writing them right",
        body: [
          "In dictation, the trap is spelling: \"que nous partions\", not \"*partons\"; \"que vous attendiez\", not \"*attendez\". If there's an \"il faut que\" before it, you need the i.",
          "And the reverse trap: don't add an i to a plain present. \"Nous partons demain\" (fact, present) has no i.",
        ],
        examples: [
          { es: "Il faut que vous attendiez ici.", en: "You need to wait here." },
          { es: "Vous attendez depuis longtemps ?", en: "Have you been waiting long?" },
          { es: "Il faut que nous choisissions un restaurant.", en: "We need to choose a restaurant." },
          { es: "Nous choisissons toujours le même.", en: "We always choose the same one." },
          { es: "Il faut que vous répondiez avant vendredi.", en: "You need to reply before Friday." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "Have you been waiting long? (formal)",
            answer: "Vous attendez depuis longtemps ?",
            altAnswers: ["Est-ce que vous attendez depuis longtemps ?", "Attendez-vous depuis longtemps ?"],
            explanation: "A plain question in the present: no i.",
          },
          {
            type: "speak",
            text: "Il faut que nous choisissions un restaurant.",
            prompt: "Say it in French: We need to choose a restaurant.",
            tip: "Slip a y sound in: choisi-ssyons.",
            explanation: "Nous choisissons → \"que nous choisissions\".",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "listen-choose",
        audio: "Vous finissez à quelle heure ?",
        question: "What did you hear?",
        options: [
          "Il faut que vous finissiez à quelle heure ?",
          "Vous finissiez à quelle heure ?",
          "Vous finissez à quelle heure ?",
          "Vous finirez à quelle heure ?",
        ],
        correctIndex: 2,
        explanation: "No y sound: \"finissez\", the present.",
      },
      {
        type: "listen-choose",
        audio: "Il faut que vous dormiez.",
        question: "What did you hear?",
        options: ["Il faut que vous dormez.", "Il faut que vous dormiez.", "Vous dormez.", "Il faut dormir."],
        correctIndex: 1,
        explanation: "You hear the y sound: \"dormiez\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "We need to talk about the future.",
        answer: "Il faut que nous parlions de l'avenir.",
        altAnswers: [
          "Il faut qu'on parle de l'avenir.",
          "Il faut que nous parlions du futur.",
          "Nous devons parler de l'avenir.",
        ],
        explanation: "\"Que nous parlions\": subjunctive.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "We used to talk every day.",
        answer: "Avant, nous parlions tous les jours.",
        altAnswers: ["Nous parlions tous les jours.", "Avant, on parlait tous les jours.", "On parlait tous les jours."],
        explanation: "Here \"parlions\" is the imparfait: a past habit.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "You need to reply before Friday. (formal)",
        answer: "Il faut que vous répondiez avant vendredi.",
        altAnswers: ["Vous devez répondre avant vendredi."],
        explanation: "Nous répondons → \"que vous répondiez\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "We're waiting for the taxi.",
        answer: "Nous attendons le taxi.",
        altAnswers: ["On attend le taxi."],
        explanation: "A fact: present, no i.",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "We need to [choose] a restaurant.",
        sentence: "Il faut que nous ___ un restaurant.",
        answer: "choisissions",
        explanation: "Nous choisissons → \"choisissions\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "We always [choose] the same one.",
        sentence: "Nous ___ toujours le même.",
        answer: "choisissons",
        explanation: "A fact: present, no i.",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "You need to [wait] here. (formal)",
        sentence: "Il faut que vous ___ ici.",
        answer: "attendiez",
        explanation: "After \"il faut que\": \"attendiez\".",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: We need to read this report.",
        words: ["Il", "faut", "que", "nous", "lisions", "ce", "rapport."],
        translation: "We need to read this report.",
        explanation: "Nous lisons → \"que nous lisions\".",
      },
      {
        type: "dictation",
        audio: "Il faut que nous partions tôt.",
        explanation: "\"Partions\" with an i: subjunctive after \"il faut que\".",
      },
      {
        type: "speak",
        text: "Il faut que vous finissiez avant midi.",
        prompt: "Say it in French: You have to finish before noon. (formal)",
        explanation: "\"Finissiez\": the y sound marks the subjunctive.",
      },
    ],
  },
  {
    slug: "b1-error-hunt-subjunctive-forms",
    level: "FR-B1",
    number: 8,
    title: "Error Hunt: Subjunctive Forms",
    summary: "Find and fix the most common subjunctive mistakes: the indicative after il faut que, the infinitive as a stem, invented forms and English calques.",
    duration: "13 min",
    sections: [
      {
        heading: "Indicative where the subjunctive belongs",
        body: [
          "The most frequent mistake is simply forgetting to switch moods: \"*il faut que tu finis\" should be \"il faut que tu finisses\"; \"*il faut que nous parlons\" should be \"il faut que nous parlions\". With -er verbs in the singular the error is invisible in speech, but it shows in \"nous\" and \"vous\" and in all audible verbs.",
          "Every time you write \"il faut que\", check the next verb: does it have -isse, -ions, -iez, a pronounced consonant?",
        ],
        examples: [
          { es: "Il faut que tu finisses tes devoirs.", en: "You have to finish your homework." },
          { es: "Il faut que nous parlions à la directrice.", en: "We need to talk to the head teacher." },
          { es: "Il faut que vous sortiez par l'arrière.", en: "You need to go out the back way." },
          { es: "Il faut qu'il lise le mode d'emploi.", en: "He needs to read the instructions." },
          { es: "Il faut que je réponde tout de suite.", en: "I have to reply straight away." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "You have to finish your homework. (to a child)",
            answer: "Il faut que tu finisses tes devoirs.",
            altAnswers: ["Tu dois finir tes devoirs."],
            explanation: "Not \"*que tu finis\": the subjunctive is \"finisses\".",
          },
          {
            type: "fill-blank",
            prompt: "Write the French for the bold words.",
            en: "We need to [talk] to the head teacher.",
            sentence: "Il faut que nous ___ à la directrice.",
            answer: "parlions",
            explanation: "Not \"*parlons\": after \"il faut que\", the nous form ends in -ions.",
          },
        ],
      },
      {
        heading: "Wrong stems",
        body: [
          "\"*Qu'il vendre\" builds from the infinitive; the stem comes from \"ils vendent\": \"qu'il vende\". \"*Que je fine\" invents a stem: \"finir\" → \"ils finissent\" → \"que je finisse\". \"*Que je lire\" → \"que je lise\"; \"*qu'il mett\" → \"qu'il mette\" (don't forget the -e).",
          "Another invented form: \"*que tu écrises\" by analogy with \"lise\". The ils form is \"écrivent\", so \"que tu écrives\".",
        ],
        examples: [
          { es: "Il faut qu'il vende son appartement.", en: "He has to sell his flat." },
          { es: "Il faut que je finisse avant midi.", en: "I have to finish before noon." },
          { es: "Il faut que tu écrives ton adresse.", en: "You need to write your address." },
          { es: "Il faut qu'il mette ses lunettes.", en: "He needs to put his glasses on." },
          { es: "Il faut que je lise ce document.", en: "I need to read this document." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "He has to sell his flat.",
            answer: "Il faut qu'il vende son appartement.",
            altAnswers: ["Il doit vendre son appartement."],
            explanation: "Not \"*qu'il vendre\": the stem comes from \"ils vendent\".",
          },
          {
            type: "multiple-choice",
            question: "Which form is correct?",
            options: ["que tu écrises", "que tu écris", "que tu écrives", "que tu écrire"],
            correctIndex: 2,
            explanation: "Ils écrivent → \"écriv-\" + \"-es\".",
          },
        ],
      },
      {
        heading: "English calques",
        body: [
          "English speakers often try to copy to + infinitive or for + person: \"*il faut que tu de partir\" mixes two structures (\"il faut partir\" and \"il faut que tu partes\"); \"*il faut toi partir\" copies you need to leave word for word. Neither exists.",
          "Choose one of the two correct structures: general → \"il faut partir\"; specific person → \"il faut que tu partes\". You can also use \"devoir\": \"tu dois partir\".",
        ],
        examples: [
          { es: "Il faut que tu partes.", en: "You have to leave." },
          { es: "Tu dois partir.", en: "You must leave." },
          { es: "Il faut partir.", en: "We have to go." },
          { es: "Il faut que tes parents signent ce papier.", en: "Your parents need to sign this paper." },
          { es: "Il faut que vous remplissiez ce formulaire.", en: "You need to fill in this form." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "You have to leave. (to a friend)",
            answer: "Il faut que tu partes.",
            altAnswers: ["Tu dois partir."],
            explanation: "Not \"*il faut toi partir\" or \"*il faut que tu de partir\".",
          },
          {
            type: "speak",
            text: "Il faut que vous remplissiez ce formulaire.",
            prompt: "Say it in French: You need to fill in this form. (formal)",
            explanation: "\"Remplir\" → nous remplissons → \"que vous remplissiez\".",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "You need to go out the back way. (formal)",
        answer: "Il faut que vous sortiez par l'arrière.",
        altAnswers: [
          "Il faut que vous sortiez par derrière.",
          "Vous devez sortir par derrière.",
          "Vous devez sortir par l'arrière.",
        ],
        explanation: "Not \"*sortez\": the vous subjunctive ends in -iez.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "I have to reply straight away.",
        answer: "Il faut que je réponde tout de suite.",
        altAnswers: ["Je dois répondre tout de suite.", "Il faut que je réponde immédiatement."],
        explanation: "Ils répondent → \"que je réponde\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "He needs to put his glasses on.",
        answer: "Il faut qu'il mette ses lunettes.",
        altAnswers: ["Il doit mettre ses lunettes."],
        explanation: "Not \"*qu'il met\": subjunctive \"mette\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "Your parents need to sign this paper.",
        answer: "Il faut que tes parents signent ce papier.",
        altAnswers: [
          "Il faut que vos parents signent ce papier.",
          "Tes parents doivent signer ce papier.",
          "Vos parents doivent signer ce papier.",
        ],
        explanation: "Plural subject: \"signent\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "I need to [read] this document.",
        sentence: "Il faut que je ___ ce document.",
        answer: "lise",
        explanation: "Not \"*que je lire\": ils lisent → \"lise\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "I have to [finish] before noon.",
        sentence: "Il faut que je ___ avant midi.",
        answer: "finisse",
        explanation: "Not \"*que je fine\": ils finissent → \"finisse\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "You need to [fill in] this form. (formal)",
        sentence: "Il faut que vous ___ ce formulaire.",
        answer: "remplissiez",
        explanation: "Not \"*remplissez\": -iez after il faut que.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: You have to leave.",
        words: ["Il", "faut", "que", "tu", "partes."],
        translation: "You have to leave.",
        explanation: "One structure only: \"il faut que\" + subject + subjunctive.",
      },
      {
        type: "multiple-choice",
        question: "Which sentence is correct?",
        options: [
          "Il faut que nous attendions.",
          "Il faut que nous attendons.",
          "Il faut nous attendre que.",
          "Il faut que nous de attendre.",
        ],
        correctIndex: 0,
        explanation: "The nous subjunctive: \"attendions\".",
      },
      {
        type: "multiple-choice",
        question: "Which sentence is wrong?",
        options: [
          "Il faut que tu finis ton assiette.",
          "Il faut que tu finisses ton assiette.",
          "Il faut finir son assiette.",
          "Tu dois finir ton assiette.",
        ],
        correctIndex: 0,
        explanation: "\"*Que tu finis\" uses the indicative: it must be \"que tu finisses\".",
      },
      {
        type: "listen-choose",
        audio: "Il faut que vous remplissiez ce formulaire.",
        question: "What does it mean?",
        options: [
          "You need to fill in this form.",
          "You filled in this form.",
          "You are filling in this form.",
          "Fill in this form, please.",
        ],
        correctIndex: 0,
        explanation: "\"Il faut que vous\" + subjunctive: you need to.",
      },
      {
        type: "dictation",
        audio: "Il faut qu'il vende sa voiture.",
        explanation: "\"Vende\" comes from \"ils vendent\".",
      },
      {
        type: "speak",
        text: "Il faut que tu finisses tes devoirs.",
        prompt: "Say it in French: You have to finish your homework. (to a child)",
        explanation: "\"Finisses\", not \"finis\".",
      },
    ],
  },
  {
    slug: "b1-contrast-clinic-fact-or-necessity",
    level: "FR-B1",
    number: 9,
    title: "Contrast Clinic: Fact or Necessity?",
    summary: "The same verb in two moods: the indicative after \"je sais que\" and \"il dit que\" for facts, the subjunctive after \"il faut que\" for what must happen.",
    duration: "13 min",
    sections: [
      {
        heading: "Je sais que tu pars / Il faut que tu partes",
        body: [
          "\"Que\" doesn't trigger the subjunctive by itself. What matters is the verb before it. \"Je sais que tu pars demain\" states a fact you know: indicative \"pars\". \"Il faut que tu partes demain\" presents the departure as a necessity, not a fact: subjunctive \"partes\".",
          "Verbs of knowing, saying, seeing and thinking (\"savoir\", \"dire\", \"voir\", \"penser\", \"croire\", \"être sûr\") introduce facts, so they take the indicative. \"Il faut que\" introduces something that isn't yet real: subjunctive.",
        ],
        examples: [
          { es: "Je sais que tu pars demain.", en: "I know you're leaving tomorrow." },
          { es: "Il faut que tu partes demain.", en: "You have to leave tomorrow." },
          { es: "Je vois que tu lis beaucoup.", en: "I can see you read a lot." },
          { es: "Il faut que tu lises plus.", en: "You need to read more." },
          { es: "Je pense qu'il dort.", en: "I think he's asleep." },
          { es: "Il faut qu'il dorme.", en: "He needs to sleep." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "I know you're leaving tomorrow. (to a friend)",
            answer: "Je sais que tu pars demain.",
            explanation: "\"Savoir que\" introduces a fact: indicative \"pars\".",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "You have to leave tomorrow. (to a friend)",
            answer: "Il faut que tu partes demain.",
            altAnswers: ["Tu dois partir demain."],
            explanation: "\"Il faut que\" → subjunctive \"partes\".",
          },
        ],
      },
      {
        heading: "Il dit qu'elle range / Il faut qu'elle range",
        body: [
          "With -er verbs, the two moods sound identical in the singular: \"il dit qu'elle range sa chambre\" (he says she's tidying her room) and \"il faut qu'elle range sa chambre\" (she has to tidy her room). You can only tell from the trigger.",
          "In the nous and vous forms, or with audible verbs, the difference reappears: \"il dit que vous attendez\" vs \"il faut que vous attendiez\"; \"il dit qu'elle écrit\" vs \"il faut qu'elle écrive\".",
        ],
        examples: [
          { es: "Il dit qu'elle range sa chambre.", en: "He says she's tidying her room." },
          { es: "Il faut qu'elle range sa chambre.", en: "She has to tidy her room." },
          { es: "Le médecin dit que vous dormez mal.", en: "The doctor says you sleep badly." },
          { es: "Il faut que vous dormiez mieux.", en: "You need to sleep better." },
          { es: "Elle dit que nous partons trop tard.", en: "She says we leave too late." },
          { es: "Il faut que nous partions plus tôt.", en: "We need to leave earlier." },
        ],
        checkpoint: [
          {
            type: "fill-blank",
            prompt: "Write the French for the bold words.",
            en: "The doctor says you [sleep] badly. (formal)",
            sentence: "Le médecin dit que vous ___ mal.",
            answer: "dormez",
            explanation: "\"Dire que\" reports a fact: indicative \"dormez\".",
          },
          {
            type: "fill-blank",
            prompt: "Write the French for the bold words.",
            en: "You need to [sleep] better. (formal)",
            sentence: "Il faut que vous ___ mieux.",
            answer: "dormiez",
            explanation: "\"Il faut que\" → subjunctive \"dormiez\".",
          },
        ],
      },
      {
        heading: "Indicative states what is, subjunctive what must be",
        body: [
          "A good way to remember: the indicative describes the world as it is; the subjunctive describes the world as someone needs or wants it to be. \"Je sais qu'il réussit toujours\" (fact). \"Il faut qu'il réussisse cette fois\" (necessity, not yet real).",
          "In the next units you'll see many more triggers of the subjunctive (wishes, emotions, doubt), and the same logic applies.",
        ],
        examples: [
          { es: "Je sais qu'il réussit toujours ses examens.", en: "I know he always passes his exams." },
          { es: "Il faut qu'il réussisse cet examen.", en: "He has to pass this exam." },
          { es: "Je suis sûr qu'elle connaît la réponse.", en: "I'm sure she knows the answer." },
          { es: "Il faut qu'elle connaisse la réponse.", en: "She needs to know the answer." },
          { es: "On voit qu'ils travaillent dur.", en: "You can see they're working hard." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "Which sentence needs the subjunctive?",
            options: [
              "Je sais qu'il ___ toujours. (réussir)",
              "Je suis sûr qu'il ___ . (réussir)",
              "Il faut qu'il ___ cet examen. (réussir)",
              "On voit qu'il ___ bien. (réussir)",
            ],
            correctIndex: 2,
            explanation: "Only \"il faut que\" triggers the subjunctive; knowing, being sure and seeing introduce facts.",
          },
          {
            type: "speak",
            text: "Il faut qu'elle connaisse la réponse.",
            prompt: "Say it in French: She needs to know the answer.",
            explanation: "\"Il faut que\" → \"connaisse\".",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "I can see you read a lot. (to a friend)",
        answer: "Je vois que tu lis beaucoup.",
        explanation: "\"Voir que\" + indicative: a fact.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "You need to read more. (to a friend)",
        answer: "Il faut que tu lises plus.",
        altAnswers: ["Il faut que tu lises davantage.", "Tu dois lire plus."],
        explanation: "\"Il faut que\" + subjunctive \"lises\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "He says she's tidying her room.",
        answer: "Il dit qu'elle range sa chambre.",
        explanation: "\"Dire que\" + indicative.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "She has to tidy her room.",
        answer: "Il faut qu'elle range sa chambre.",
        altAnswers: ["Elle doit ranger sa chambre."],
        explanation: "Same sound, but here \"range\" is a subjunctive.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "I'm sure she knows the answer.",
        answer: "Je suis sûr qu'elle connaît la réponse.",
        altAnswers: [
          "Je suis sûre qu'elle connaît la réponse.",
          "Je suis sûr qu'elle sait la réponse.",
          "Je suis sûre qu'elle sait la réponse.",
        ],
        explanation: "\"Être sûr que\" + indicative.",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "I know you [are waiting]. (formal)",
        sentence: "Je sais que vous ___.",
        answer: "attendez",
        explanation: "Fact → indicative.",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "You [have to wait]. (formal)",
        sentence: "Il faut que vous ___.",
        answer: "attendiez",
        explanation: "Necessity → subjunctive.",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "He has to [pass] this exam.",
        sentence: "Il faut qu'il ___ cet examen.",
        answer: "réussisse",
        explanation: "Necessity → subjunctive.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: We need to leave earlier.",
        words: ["Il", "faut", "que", "nous", "partions", "plus", "tôt."],
        translation: "We need to leave earlier.",
        explanation: "\"Il faut que\" → \"partions\".",
      },
      {
        type: "multiple-choice",
        question: "Complete: « Je pense que vous ___ trop. » (travailler)",
        options: ["travailliez", "travailler", "travaillent", "travaillez"],
        correctIndex: 3,
        explanation: "\"Penser que\" in the affirmative introduces a statement: indicative.",
      },
      {
        type: "listen-choose",
        audio: "Il dit que vous partez demain.",
        question: "What does it mean?",
        options: [
          "He says you have to leave tomorrow.",
          "You have to leave tomorrow.",
          "He wants you to leave tomorrow.",
          "He says you're leaving tomorrow.",
        ],
        correctIndex: 3,
        explanation: "\"Partez\" (no y sound) after \"il dit que\": a reported fact.",
      },
      {
        type: "dictation",
        audio: "Il faut que nous partions plus tôt.",
        explanation: "\"Partions\": subjunctive after \"il faut que\".",
      },
      {
        type: "speak",
        text: "Je sais que tu pars demain.",
        prompt: "Say it in French: I know you're leaving tomorrow. (to a friend)",
        explanation: "\"Savoir que\" + indicative.",
      },
    ],
  },
];
