// Synced from cheneygross-afk/lengo:src/lib/lessons/fr-b1-u06-extra.ts by scripts/sync-content.mjs -- edit it there, not here.
import type { Lesson } from "./types";

// French B1, Unit 6 extra practice: Doubt, Opinion & Impersonal Expressions.
export const FR_B1_U06_EXTRA: Lesson[] = [
  {
    slug: "b1-doubt-opinion-extra-1",
    level: "FR-B1",
    number: 1,
    optional: true,
    title: "Extra Practice: Doubt, Opinion & Impersonal Expressions, Part 1 of 3",
    summary: "New opinion sentences in the affirmative (indicative) and the negative (subjunctive).",
    duration: "12 min",
    sections: [
      {
        heading: "Recap: je pense que / je ne pense pas que",
        body: [
          "Affirmative \"penser\", \"croire\", \"trouver\" and \"être sûr\" present an idea as true: indicative (\"je pense qu'il a raison\"). Negative, or with \"douter\", they present it as doubtful: subjunctive (\"je ne pense pas qu'il ait raison\", \"je doute qu'il ait raison\"). The mood depends on the opinion verb, not on the English.",
        ],
        examples: [
          { es: "Je trouve que ce quartier est très calme.", en: "I think this neighbourhood is very quiet." },
          { es: "Je ne trouve pas que ce quartier soit très calme.", en: "I don't think this neighbourhood is very quiet." },
          { es: "Mon frère croit que le restaurant est fermé.", en: "My brother thinks the restaurant is closed." },
          { es: "Je doute que le restaurant soit fermé un samedi.", en: "I doubt the restaurant is closed on a Saturday." },
          { es: "Nous ne sommes pas sûrs que tu puisses entrer sans billet.", en: "We're not sure you can get in without a ticket." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "I don't think this neighbourhood is very quiet.",
            answer: "Je ne trouve pas que ce quartier soit très calme.",
            altAnswers: ["Je ne pense pas que ce quartier soit très calme.", "Je ne crois pas que ce quartier soit très calme."],
            explanation: "Negative opinion → \"soit\".",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "My brother thinks the restaurant is closed.",
            answer: "Mon frère croit que le restaurant est fermé.",
            altAnswers: ["Mon frère pense que le restaurant est fermé."],
            explanation: "Affirmative croire → indicative \"est\".",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "I think the bakery opens at seven.",
        answer: "Je crois que la boulangerie ouvre à sept heures.",
        altAnswers: ["Je pense que la boulangerie ouvre à sept heures.", "Je crois que la boulangerie ouvre à 7 heures.", "Je pense que la boulangerie ouvre à 7 heures."],
        explanation: "Affirmative → indicative \"ouvre\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "I don't think the bakery opens on Sundays.",
        answer: "Je ne crois pas que la boulangerie ouvre le dimanche.",
        altAnswers: ["Je ne pense pas que la boulangerie ouvre le dimanche."],
        explanation: "Negative → subjunctive \"ouvre\" (same form as the present for ouvrir).",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "She thinks her boss is fair.",
        answer: "Elle trouve que son chef est juste.",
        altAnswers: ["Elle pense que son chef est juste.", "Elle trouve que son patron est juste.", "Elle pense que son patron est juste."],
        explanation: "Affirmative → \"est\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "She doesn't think her boss is fair.",
        answer: "Elle ne trouve pas que son chef soit juste.",
        altAnswers: ["Elle ne pense pas que son chef soit juste.", "Elle ne trouve pas que son patron soit juste.", "Elle ne pense pas que son patron soit juste."],
        explanation: "Negative → \"soit\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "I doubt they have enough time.",
        answer: "Je doute qu'ils aient assez de temps.",
        altAnswers: ["Je doute qu'elles aient assez de temps."],
        explanation: "\"Douter que\" + \"aient\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "We're sure you'll like Marseille. (to a friend)",
        answer: "Nous sommes sûrs que tu aimeras Marseille.",
        altAnswers: ["On est sûrs que tu aimeras Marseille.", "Nous sommes sûrs que tu vas aimer Marseille.", "On est sûrs que tu vas aimer Marseille.", "Nous sommes sûres que tu aimeras Marseille."],
        explanation: "Certainty → indicative future.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "I'm not sure he can come.",
        answer: "Je ne suis pas sûr qu'il puisse venir.",
        altAnswers: ["Je ne suis pas sûre qu'il puisse venir.", "Je ne suis pas certain qu'il puisse venir.", "Je ne suis pas certaine qu'il puisse venir."],
        explanation: "Doubt → \"puisse\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "Do you think my French is getting better? (to a friend)",
        answer: "Tu trouves que mon français s'améliore ?",
        altAnswers: ["Tu penses que mon français s'améliore ?", "Est-ce que tu trouves que mon français s'améliore ?", "Vous trouvez que mon français s'améliore ?"],
        explanation: "An everyday question with intonation keeps the indicative.",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "I don't think they [want] to sell the house.",
        sentence: "Je ne pense pas qu'ils ___ vendre la maison.",
        answer: "veuillent",
        explanation: "Vouloir → \"veuillent\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "I think [it's going to] rain.",
        sentence: "Je crois qu'___ pleuvoir.",
        answer: "il va",
        explanation: "Affirmative → indicative futur proche.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: I doubt the restaurant is closed on a Saturday.",
        words: ["Je doute", "que le restaurant", "soit fermé", "un samedi."],
        translation: "I doubt the restaurant is closed on a Saturday.",
        explanation: "\"Douter que\" + \"soit\".",
      },
      {
        type: "multiple-choice",
        question: "Which sentence is correct?",
        options: ["Je ne crois pas qu'elle fasse du sport.", "Je ne crois pas qu'elle fait du sport.", "Je crois qu'elle fasse du sport.", "Je doute qu'elle fait du sport."],
        correctIndex: 0,
        explanation: "Negative croire → \"fasse\"; affirmative croire → \"fait\"; douter → \"fasse\".",
      },
      {
        type: "listen-choose",
        audio: "Je ne pense pas qu'il sache conduire.",
        question: "What does it mean?",
        options: ["I don't think he can drive.", "I think he can't drive.", "I don't know if he drives.", "He doesn't think I can drive."],
        correctIndex: 0,
        explanation: "\"Sache\" = subjunctive of savoir; savoir conduire = to know how to drive.",
      },
      {
        type: "dictation",
        audio: "Je ne trouve pas que ce soit cher.",
        explanation: "\"Ce soit\" after negative trouver.",
      },
      {
        type: "speak",
        text: "Je doute qu'ils aient assez de temps.",
        prompt: "Say it in French: I doubt they have enough time.",
        tip: "Liaison: qu'ils_aient [kilzɛ].",
        explanation: "\"Douter que\" + \"aient\".",
      },
    ],
  },
  {
    slug: "b1-doubt-opinion-extra-2",
    level: "FR-B1",
    number: 2,
    optional: true,
    title: "Extra Practice: Doubt, Opinion & Impersonal Expressions, Part 2 of 3",
    summary: "Il est + adjective + que + subjunctive vs il est + adjective + de + infinitive.",
    duration: "12 min",
    sections: [
      {
        heading: "Recap: que for a person, de for everyone",
        body: [
          "\"Il est\" + adjective + \"que\" + subjunctive aims the judgement at someone: \"il est important que tu boives\". \"Il est\" + adjective + \"de\" + infinitive states a general truth: \"il est important de boire\". In speech, \"c'est\" replaces \"il est\" with the same grammar after it.",
        ],
        examples: [
          { es: "Il est essentiel de bien dormir avant un examen.", en: "It's essential to sleep well before an exam." },
          { es: "Il est essentiel que Manon dorme bien avant son examen.", en: "It's essential for Manon to sleep well before her exam." },
          { es: "Il est rare de voir des cerfs si près de la route.", en: "It's rare to see deer so close to the road." },
          { es: "C'est normal que tu sois nerveux.", en: "It's normal for you to be nervous." },
          { es: "Il est impossible de stationner devant l'école.", en: "It's impossible to park in front of the school." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "It's essential to sleep well before an exam.",
            answer: "Il est essentiel de bien dormir avant un examen.",
            altAnswers: ["C'est essentiel de bien dormir avant un examen.", "Il est essentiel de dormir bien avant un examen."],
            explanation: "General → de + infinitive.",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "It's essential for Manon to sleep well before her exam.",
            answer: "Il est essentiel que Manon dorme bien avant son examen.",
            altAnswers: ["C'est essentiel que Manon dorme bien avant son examen."],
            explanation: "A specific person → que + \"dorme\".",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "It's normal for you to be nervous. (to a friend)",
        answer: "C'est normal que tu sois nerveux.",
        altAnswers: ["Il est normal que tu sois nerveux.", "C'est normal que tu sois nerveuse.", "Il est normal que tu sois nerveuse."],
        explanation: "\"Normal que\" + \"sois\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "It's normal to be nervous.",
        answer: "C'est normal d'être nerveux.",
        altAnswers: ["Il est normal d'être nerveux.", "C'est normal d'être nerveuse."],
        explanation: "General → \"d'être\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "It's impossible to park in front of the school.",
        answer: "Il est impossible de stationner devant l'école.",
        altAnswers: ["Il est impossible de se garer devant l'école.", "C'est impossible de se garer devant l'école.", "C'est impossible de stationner devant l'école."],
        explanation: "General → de + infinitive.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "It's urgent for you to call the doctor. (to a friend)",
        answer: "Il est urgent que tu appelles le médecin.",
        altAnswers: ["C'est urgent que tu appelles le médecin.", "Il est urgent que vous appeliez le médecin."],
        explanation: "\"Urgent que\" + \"appelles\" (double l).",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "It's rare to see deer so close to the road.",
        answer: "Il est rare de voir des cerfs si près de la route.",
        altAnswers: ["C'est rare de voir des cerfs si près de la route.", "Il est rare de voir des cerfs aussi près de la route."],
        explanation: "General → \"de voir\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "It's rare for my grandfather to go out at night.",
        answer: "Il est rare que mon grand-père sorte le soir.",
        altAnswers: ["C'est rare que mon grand-père sorte le soir.", "Il est rare que mon grand-père sorte la nuit."],
        explanation: "A specific person → \"sorte\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "It's necessary for us to change our plans.",
        answer: "Il est nécessaire que nous changions nos projets.",
        altAnswers: ["Il est nécessaire qu'on change nos projets.", "Il est nécessaire que nous changions nos plans."],
        explanation: "\"Nécessaire que\" + \"changions\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "It's a shame to waste so much food.",
        answer: "C'est dommage de gaspiller autant de nourriture.",
        altAnswers: ["Il est dommage de gaspiller autant de nourriture.", "C'est dommage de gâcher autant de nourriture."],
        explanation: "General → \"de gaspiller\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "It's preferable [to arrive] ten minutes early.",
        sentence: "Il est préférable ___ dix minutes en avance.",
        answer: "d'arriver",
        explanation: "General → de + infinitive, elided.",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "It's important that the children [learn] to swim.",
        sentence: "Il est important que les enfants ___ à nager.",
        answer: "apprennent",
        explanation: "Ils subjunctive of apprendre: \"apprennent\".",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: It's important for you to drink more water.",
        words: ["Il est", "important", "que tu", "boives", "plus d'eau."],
        translation: "It's important for you to drink more water.",
        explanation: "\"Important que\" + \"boives\".",
      },
      {
        type: "multiple-choice",
        question: "Which sentence is correct?",
        options: ["Il est difficile de trouver un taxi ici.", "Il est difficile trouver un taxi ici.", "Il est difficile que trouver un taxi ici.", "Il est difficile à trouver un taxi ici."],
        correctIndex: 0,
        explanation: "\"Il est\" + adjective + \"de\" + infinitive.",
      },
      {
        type: "listen-choose",
        audio: "Il est rare qu'il fasse si chaud en avril.",
        question: "What does it mean?",
        options: ["It's rare for it to be so hot in April.", "It's rarely hot in April.", "It was very hot in April.", "It's rare to be hot in April."],
        correctIndex: 0,
        explanation: "\"Il est rare que\" + \"fasse\" (weather).",
      },
      {
        type: "dictation",
        audio: "C'est normal que tu sois nerveux.",
        explanation: "\"Tu sois\": s for tu.",
      },
      {
        type: "speak",
        text: "Il est important que les enfants apprennent à nager.",
        prompt: "Say it in French: It's important that children learn to swim.",
        explanation: "\"Important que\" + \"apprennent\".",
      },
    ],
  },
  {
    slug: "b1-doubt-opinion-extra-3",
    level: "FR-B1",
    number: 3,
    optional: true,
    title: "Extra Practice: Doubt, Opinion & Impersonal Expressions, Part 3 of 3",
    summary: "Probable vs possible, peut-être que and il se peut que in new sentences.",
    duration: "12 min",
    sections: [
      {
        heading: "Recap: likely, possible, maybe",
        body: [
          "\"Il est probable / certain / clair que\" + indicative (often future). \"Il est possible / peu probable que\" and \"il se peut que\" + subjunctive. \"Peut-être que\" + indicative, or \"peut-être\" after the verb.",
        ],
        examples: [
          { es: "Il est probable que la réunion finira tard.", en: "The meeting will probably finish late." },
          { es: "Il se peut que la réunion finisse tard.", en: "The meeting may finish late." },
          { es: "Peut-être que la réunion finira tard.", en: "Maybe the meeting will finish late." },
          { es: "Il est peu probable qu'ils gagnent ce soir.", en: "They're unlikely to win tonight." },
          { es: "Ils vont peut-être gagner ce soir.", en: "They might win tonight." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French. (use il se peut)",
            source: "The meeting may finish late.",
            answer: "Il se peut que la réunion finisse tard.",
            explanation: "\"Il se peut que\" + \"finisse\".",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French. (use il est probable)",
            source: "The meeting will probably finish late.",
            answer: "Il est probable que la réunion finira tard.",
            altAnswers: ["Il est probable que la réunion va finir tard."],
            explanation: "\"Probable\" → indicative future.",
          },
          {
            type: "listen-choose",
            audio: "Il est peu probable qu'ils gagnent ce soir.",
            question: "What does it mean?",
            options: ["They're unlikely to win tonight.", "They'll probably win tonight.", "They might win a little tonight.", "They didn't win tonight."],
            correctIndex: 0,
            explanation: "\"Peu probable\" = unlikely → subjunctive.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French. (use il est possible)",
        source: "The flight might be cancelled.",
        answer: "Il est possible que le vol soit annulé.",
        altAnswers: ["C'est possible que le vol soit annulé."],
        explanation: "\"Possible\" → \"soit\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French. (use peut-être que)",
        source: "Maybe the flight will be cancelled.",
        answer: "Peut-être que le vol sera annulé.",
        altAnswers: ["Peut-être que le vol va être annulé."],
        explanation: "\"Peut-être que\" + indicative.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French. (use il est certain)",
        source: "The flight will certainly be late.",
        answer: "Il est certain que le vol sera en retard.",
        altAnswers: ["Il est certain que le vol aura du retard.", "Il est certain que le vol va être en retard."],
        explanation: "\"Certain\" → indicative future.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "They might win tonight.",
        answer: "Ils vont peut-être gagner ce soir.",
        altAnswers: ["Ils gagneront peut-être ce soir.", "Peut-être qu'ils vont gagner ce soir.", "Peut-être qu'ils gagneront ce soir.", "Il se peut qu'ils gagnent ce soir.", "Il est possible qu'ils gagnent ce soir."],
        explanation: "Peut-être with the indicative, or a possibility trigger with the subjunctive.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French. (use il est peu probable)",
        source: "She's unlikely to remember my name.",
        answer: "Il est peu probable qu'elle se souvienne de mon nom.",
        altAnswers: ["Il est peu probable qu'elle se rappelle mon nom."],
        explanation: "\"Peu probable\" → \"se souvienne\" (two-stem like venir).",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French. (use il est clair)",
        source: "It's clear he doesn't want to come.",
        answer: "Il est clair qu'il ne veut pas venir.",
        altAnswers: ["C'est clair qu'il ne veut pas venir."],
        explanation: "\"Clair\" → indicative \"veut\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "He may have lost his keys.",
        answer: "Il a peut-être perdu ses clés.",
        altAnswers: ["Peut-être qu'il a perdu ses clés.", "Il a peut-être perdu ses clefs."],
        explanation: "\"Peut-être\" between auxiliary and participle.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French. (use il se peut)",
        source: "I might be late tomorrow.",
        answer: "Il se peut que je sois en retard demain.",
        explanation: "\"Il se peut que\" + \"sois\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "It's possible the shop [has] your size.",
        sentence: "Il est possible que le magasin ___ votre taille.",
        answer: "ait",
        explanation: "\"Possible\" → \"ait\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "Maybe [she's] at her mother's.",
        sentence: "Peut-être qu'___ chez sa mère.",
        answer: "elle est",
        explanation: "\"Peut-être que\" + indicative.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: The flight might be cancelled.",
        words: ["Il est", "possible", "que le vol", "soit", "annulé."],
        translation: "The flight might be cancelled.",
        explanation: "\"Possible\" → \"soit\".",
      },
      {
        type: "multi-select",
        question: "Which sentences are correct?",
        options: ["Il est probable qu'il neigera.", "Il est possible qu'il neige.", "Peut-être qu'il neige.", "Il se peut qu'il neigera.", "Il est peu probable qu'il neige."],
        correctIndexes: [0, 1, 2, 4],
        explanation: "\"Il se peut que\" needs the subjunctive \"neige\", not the future.",
      },
      {
        type: "dictation",
        audio: "Il se peut que je sois en retard demain.",
        explanation: "\"Je sois\": s for je.",
      },
      {
        type: "speak",
        text: "Il est probable que la réunion finira tard.",
        prompt: "Say it in French: The meeting will probably finish late. (use il est probable)",
        explanation: "\"Probable\" → future \"finira\".",
      },
    ],
  },
  {
    slug: "b1-doubt-opinion-extra-4",
    level: "FR-B1",
    number: 4,
    optional: true,
    title: "Extra Practice: Real-World Mission, A Letter to the Mairie",
    summary: "Write to the town hall about local problems with il est urgent que, je ne pense pas que ce soit normal que and other judgements.",
    duration: "13 min",
    sections: [
      {
        heading: "Recap: a formal complaint",
        body: [
          "A letter to the mairie (town hall) uses vous and the formal \"il est\" frames: \"il est urgent que la mairie répare...\", \"il est inadmissible que...\" (it is unacceptable that), \"je ne pense pas que ce soit normal que...\". Close with \"Je vous prie d'agréer, Madame la Maire, mes salutations distinguées\" or the simpler \"Cordialement\". Hope stays indicative: \"j'espère que vous prendrez des mesures\".",
        ],
        examples: [
          { es: "Madame la Maire, je vous écris au sujet de l'éclairage de la rue Victor-Hugo.", en: "Dear Madam Mayor, I'm writing to you about the street lighting on rue Victor-Hugo." },
          { es: "Il est urgent que la mairie répare les lampadaires.", en: "The town hall urgently needs to repair the street lamps." },
          { es: "Je ne pense pas que ce soit normal que les enfants rentrent de l'école dans le noir.", en: "I don't think it's right that children come home from school in the dark." },
          { es: "Il est inadmissible que rien ne soit fait depuis six mois.", en: "It's unacceptable that nothing has been done for six months." },
          { es: "J'espère que vous prendrez rapidement des mesures.", en: "I hope you'll take action quickly." },
          { es: "Je vous prie d'agréer, Madame la Maire, mes salutations distinguées.", en: "Yours faithfully." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "The town hall urgently needs to repair the street lamps.",
            answer: "Il est urgent que la mairie répare les lampadaires.",
            explanation: "\"Il est urgent que\" + subjunctive \"répare\".",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "I hope you'll take action quickly. (formal)",
            answer: "J'espère que vous prendrez rapidement des mesures.",
            altAnswers: ["J'espère que vous prendrez des mesures rapidement.", "J'espère que vous allez prendre rapidement des mesures.", "J'espère que vous allez prendre des mesures rapidement."],
            explanation: "Espérer + future; \"prendre des mesures\" = to take action.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "I'm writing to you about the noise in the park. (formal)",
        answer: "Je vous écris au sujet du bruit dans le parc.",
        altAnswers: ["Je vous écris à propos du bruit dans le parc."],
        explanation: "\"Au sujet de\" / \"à propos de\" = about, regarding.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "I don't think it's right that the park is open until two in the morning.",
        answer: "Je ne pense pas que ce soit normal que le parc soit ouvert jusqu'à deux heures du matin.",
        altAnswers: ["Je ne trouve pas que ce soit normal que le parc soit ouvert jusqu'à deux heures du matin.", "Je ne crois pas que ce soit normal que le parc soit ouvert jusqu'à deux heures du matin."],
        explanation: "Two subjunctives in a row: \"ce soit\" (negative opinion) and \"le parc soit\" (normal que).",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "It's unacceptable that nothing has been done.",
        answer: "Il est inadmissible que rien ne soit fait.",
        altAnswers: ["C'est inadmissible que rien ne soit fait."],
        explanation: "Judgement → subjunctive; \"rien ne\" as subject.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "It's important that the town hall listens to the residents.",
        answer: "Il est important que la mairie écoute les habitants.",
        altAnswers: ["Il est important que la mairie écoute les riverains."],
        explanation: "\"Important que\" + \"écoute\"; no 'to' after écouter.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "It's possible that an accident will happen.",
        answer: "Il est possible qu'un accident arrive.",
        altAnswers: ["Il est possible qu'un accident se produise.", "Il se peut qu'un accident arrive.", "Il se peut qu'un accident se produise."],
        explanation: "Possibility → subjunctive.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "It's clear the bins are not emptied often enough.",
        answer: "Il est clair que les poubelles ne sont pas vidées assez souvent.",
        altAnswers: ["Il est évident que les poubelles ne sont pas vidées assez souvent."],
        explanation: "Certainty → indicative \"sont\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "We want the town hall to put a pedestrian crossing in front of the school.",
        answer: "Nous voulons que la mairie mette un passage piéton devant l'école.",
        altAnswers: ["Nous souhaitons que la mairie mette un passage piéton devant l'école.", "Nous voulons que la mairie installe un passage piéton devant l'école.", "Nous souhaitons que la mairie installe un passage piéton devant l'école.", "Nous voulons que la mairie mette un passage pour piétons devant l'école."],
        explanation: "\"Vouloir que\" + \"mette\" (from ils mettent).",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "Yours sincerely, (in a formal letter)",
        answer: "Cordialement,",
        altAnswers: ["Cordialement", "Je vous prie d'agréer mes salutations distinguées.", "Veuillez agréer mes salutations distinguées."],
        explanation: "\"Cordialement\" is the modern neutral sign-off; the long formula is traditional.",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "It's urgent that the town hall [does] something.",
        sentence: "Il est urgent que la mairie ___ quelque chose.",
        answer: "fasse",
        explanation: "\"Urgent que\" + \"fasse\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "I doubt the residents [are] satisfied.",
        sentence: "Je doute que les habitants ___ satisfaits.",
        answer: "soient",
        explanation: "\"Douter que\" + \"soient\".",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: I'm writing to you about the street lighting.",
        words: ["Je vous écris", "au sujet", "de l'éclairage", "de la rue."],
        translation: "I'm writing to you about the street lighting.",
        explanation: "\"Au sujet de\" introduces the topic of the letter.",
      },
      {
        type: "multiple-choice",
        question: "Which closing is right for a letter to the mayor?",
        options: ["Je vous prie d'agréer, Madame la Maire, mes salutations distinguées.", "Gros bisous, Madame la Maire !", "Je t'embrasse, Madame la Maire.", "À plus, Madame la Maire."],
        correctIndex: 0,
        explanation: "The traditional formal closing; the others are for friends.",
      },
      {
        type: "listen-choose",
        audio: "Il est inadmissible que rien ne soit fait.",
        question: "What does it mean?",
        options: ["It's unacceptable that nothing is being done.", "It's impossible to do nothing.", "Nothing is acceptable.", "It's unacceptable to do nothing."],
        correctIndex: 0,
        explanation: "\"Inadmissible que\" + subjunctive \"soit fait\".",
      },
      {
        type: "dictation",
        audio: "Il est urgent que la mairie répare les lampadaires.",
        explanation: "\"Répare\" (subjunctive, same as present).",
      },
      {
        type: "speak",
        text: "J'espère que vous prendrez rapidement des mesures.",
        prompt: "Say it in French: I hope you'll take action quickly. (formal)",
        explanation: "Espérer + future \"prendrez\".",
      },
    ],
  },
  {
    slug: "b1-doubt-opinion-extra-5",
    level: "FR-B1",
    number: 5,
    optional: true,
    title: "Extra Practice: Error Hunt, Pourvu que and Impersonals",
    summary: "Fix wrong moods after pourvu que, il est probable que and peut-être que.",
    duration: "12 min",
    sections: [
      {
        heading: "Recap: the three most-missed moods",
        body: [
          "\"Pourvu que\" always takes the subjunctive (*pourvu qu'il fera beau → pourvu qu'il fasse beau). \"Il est probable que\" takes the indicative (*il est probable qu'il vienne → qu'il viendra), while \"il est possible que\" takes the subjunctive. \"Peut-être que\" takes the indicative (*peut-être qu'il soit → peut-être qu'il est).",
        ],
        examples: [
          { es: "Pourvu qu'il fasse beau pour le mariage !", en: "Let's hope it's nice for the wedding!" },
          { es: "Il est probable qu'il viendra avec sa femme.", en: "He'll probably come with his wife." },
          { es: "Il est possible qu'il vienne avec sa femme.", en: "He might come with his wife." },
          { es: "Peut-être qu'il est déjà parti.", en: "Maybe he's already left." },
          { es: "Il est peu probable que nous ayons des places.", en: "We're unlikely to get seats." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "A learner wrote \"Pourvu qu'il fera beau pour le mariage !\" Write it correctly: Let's hope it's nice for the wedding!",
            source: "Let's hope it's nice for the wedding!",
            answer: "Pourvu qu'il fasse beau pour le mariage !",
            altAnswers: ["Pourvu qu'il fasse beau pour le mariage."],
            explanation: "\"Pourvu que\" + subjunctive \"fasse\".",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "A learner wrote \"Peut-être qu'il soit déjà parti.\" Write it correctly: Maybe he's already left.",
            source: "Maybe he's already left.",
            answer: "Peut-être qu'il est déjà parti.",
            altAnswers: ["Il est peut-être déjà parti."],
            explanation: "\"Peut-être que\" + indicative.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "A learner wrote \"Il est probable qu'il vienne avec sa femme.\" Write it correctly: He'll probably come with his wife. (use il est probable)",
        source: "He'll probably come with his wife.",
        answer: "Il est probable qu'il viendra avec sa femme.",
        altAnswers: ["Il est probable qu'il va venir avec sa femme."],
        explanation: "\"Probable\" → indicative.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "A learner wrote \"Il est possible qu'il viendra.\" Write it correctly: He might come.",
        source: "He might come. (use il est possible)",
        answer: "Il est possible qu'il vienne.",
        altAnswers: ["C'est possible qu'il vienne."],
        explanation: "\"Possible\" → subjunctive.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "A learner wrote \"Il se peut que nous serons en retard.\" Write it correctly: We may be late.",
        source: "We may be late. (use il se peut)",
        answer: "Il se peut que nous soyons en retard.",
        altAnswers: ["Il se peut qu'on soit en retard."],
        explanation: "\"Il se peut que\" + \"soyons\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "A learner wrote \"Il est important de que tu manges.\" Write it correctly: It's important for you to eat.",
        source: "It's important for you to eat. (to a friend)",
        answer: "Il est important que tu manges.",
        altAnswers: ["C'est important que tu manges."],
        explanation: "Either \"de\" + infinitive or \"que\" + subjunctive, never both.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "A learner wrote \"Il est clair qu'il ait tort.\" Write it correctly: It's clear he's wrong.",
        source: "It's clear he's wrong.",
        answer: "Il est clair qu'il a tort.",
        altAnswers: ["C'est clair qu'il a tort."],
        explanation: "\"Clair\" → indicative \"a\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "A learner wrote \"Il est temps que nous partons.\" Write it correctly: It's time we left.",
        source: "It's time we left.",
        answer: "Il est temps que nous partions.",
        altAnswers: ["Il est temps qu'on parte."],
        explanation: "\"Il est temps que\" + subjunctive \"partions\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "A learner wrote \"Ça m'étonnerait qu'il a raison.\" Write it correctly: I doubt he's right.",
        source: "I doubt he's right. (use ça m'étonnerait)",
        answer: "Ça m'étonnerait qu'il ait raison.",
        explanation: "\"Ça m'étonnerait que\" + \"ait\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "A learner wrote \"Je me doute qu'il soit fatigué.\" Write it correctly: I can imagine he's tired.",
        source: "I can imagine he's tired. (use se douter)",
        answer: "Je me doute qu'il est fatigué.",
        explanation: "\"Se douter que\" (to suspect) + indicative.",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "We're unlikely to [get] seats.",
        sentence: "Il est peu probable que nous ___ des places.",
        answer: "ayons",
        explanation: "\"Peu probable\" → \"ayons\" (no i after y).",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "Fingers crossed she [remembers] my birthday!",
        sentence: "Pourvu qu'elle ___ de mon anniversaire !",
        answer: "se souvienne",
        explanation: "\"Pourvu que\" + \"se souvienne\".",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: It's time we left.",
        words: ["Il est", "temps", "que nous", "partions."],
        translation: "It's time we left.",
        explanation: "\"Il est temps que\" + subjunctive.",
      },
      {
        type: "matching",
        instructions: "Match each frame with the mood it takes.",
        pairs: [
          { left: "pourvu que", right: "subjunctive (fingers crossed)" },
          { left: "peut-être que", right: "indicative (maybe)" },
          { left: "il est probable que", right: "indicative (likely)" },
          { left: "il se peut que", right: "subjunctive (may)" },
        ],
        explanation: "Two look like doubt but take the indicative: peut-être que and probable.",
      },
      {
        type: "listen-choose",
        audio: "Il est peu probable que nous ayons des places.",
        question: "What does it mean?",
        options: ["We're unlikely to get seats.", "We'll probably get seats.", "We have few seats.", "We might have had seats."],
        correctIndex: 0,
        explanation: "\"Peu probable\" = unlikely.",
      },
      {
        type: "dictation",
        audio: "Pourvu qu'il fasse beau pour le mariage !",
        explanation: "\"Fasse\" after pourvu que.",
      },
      {
        type: "speak",
        text: "Il est probable qu'il viendra avec sa femme.",
        prompt: "Say it in French: He'll probably come with his wife. (use il est probable)",
        explanation: "\"Probable\" → indicative future.",
      },
    ],
  },
  {
    slug: "b1-doubt-opinion-extra-6",
    level: "FR-B1",
    number: 6,
    optional: true,
    title: "Extra Practice: From Je pense que to Je ne pense pas que",
    summary: "Transformations that flip the mood: make each opinion negative or doubtful and change the verb.",
    duration: "12 min",
    sections: [
      {
        heading: "Recap: one change, two ripples",
        body: [
          "When you negate the opinion verb, two things change: the negation itself and the mood of the second verb. \"Je pense qu'il dit la vérité\" → \"je ne pense pas qu'il dise la vérité\". With \"être sûr\": \"je suis sûr qu'elle peut\" → \"je ne suis pas sûr qu'elle puisse\". With \"douter\", there's no negation but the same subjunctive: \"je doute qu'il dise la vérité\".",
        ],
        examples: [
          { es: "Je pense qu'il dit la vérité. → Je ne pense pas qu'il dise la vérité.", en: "I think he's telling the truth. → I don't think he's telling the truth." },
          { es: "Je suis sûr qu'elle peut nous aider. → Je ne suis pas sûr qu'elle puisse nous aider.", en: "I'm sure she can help us. → I'm not sure she can help us." },
          { es: "Je crois qu'ils viennent en train. → Je doute qu'ils viennent en train.", en: "I think they're coming by train. → I doubt they're coming by train." },
          { es: "Je trouve que tu conduis bien. → Je ne trouve pas que tu conduises bien.", en: "I think you drive well. → I don't think you drive well." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "I don't think he's telling the truth.",
            answer: "Je ne pense pas qu'il dise la vérité.",
            altAnswers: ["Je ne crois pas qu'il dise la vérité."],
            explanation: "Dire → \"dise\" (from ils disent).",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "I don't think you drive well. (to a friend)",
            answer: "Je ne trouve pas que tu conduises bien.",
            altAnswers: ["Je ne pense pas que tu conduises bien.", "Je ne crois pas que tu conduises bien."],
            explanation: "Conduire → \"conduises\".",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "I'm not sure she can help us.",
        answer: "Je ne suis pas sûr qu'elle puisse nous aider.",
        altAnswers: ["Je ne suis pas sûre qu'elle puisse nous aider.", "Je ne suis pas certain qu'elle puisse nous aider.", "Je ne suis pas certaine qu'elle puisse nous aider."],
        explanation: "\"Ne pas être sûr que\" + \"puisse\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "I'm sure she can help us.",
        answer: "Je suis sûr qu'elle peut nous aider.",
        altAnswers: ["Je suis sûre qu'elle peut nous aider.", "Je suis sûr qu'elle pourra nous aider.", "Je suis sûre qu'elle pourra nous aider."],
        explanation: "Certainty → indicative.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "I doubt they're coming by train.",
        answer: "Je doute qu'ils viennent en train.",
        altAnswers: ["Je doute qu'elles viennent en train."],
        explanation: "\"Douter que\" + \"viennent\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "I don't think it's going to snow.",
        answer: "Je ne pense pas qu'il neige.",
        altAnswers: ["Je ne crois pas qu'il neige."],
        explanation: "No future after a negative opinion: present subjunctive \"neige\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "We don't think the shop sells batteries.",
        answer: "Nous ne pensons pas que le magasin vende des piles.",
        altAnswers: ["On ne pense pas que le magasin vende des piles.", "Nous ne croyons pas que le magasin vende des piles.", "On ne croit pas que le magasin vende des piles."],
        explanation: "Vendre → \"vende\", with an audible d.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "I don't think you're going the right way. (to a friend)",
        answer: "Je ne pense pas que tu ailles dans la bonne direction.",
        altAnswers: ["Je ne crois pas que tu ailles dans la bonne direction.", "Je ne pense pas que tu prennes le bon chemin.", "Je ne crois pas que tu prennes le bon chemin."],
        explanation: "Aller → \"ailles\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "She doesn't think we know the address.",
        answer: "Elle ne pense pas que nous connaissions l'adresse.",
        altAnswers: ["Elle ne pense pas qu'on connaisse l'adresse.", "Elle ne croit pas que nous connaissions l'adresse.", "Elle ne croit pas qu'on connaisse l'adresse."],
        explanation: "Connaître → \"connaissions\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "I think they understand French.",
        answer: "Je pense qu'ils comprennent le français.",
        altAnswers: ["Je crois qu'ils comprennent le français.", "Je pense qu'elles comprennent le français."],
        explanation: "Affirmative → indicative (same form as the subjunctive for ils).",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "I don't think she [writes] to her parents often.",
        sentence: "Je ne pense pas qu'elle ___ souvent à ses parents.",
        answer: "écrive",
        explanation: "Écrire → \"écrive\" (from ils écrivent).",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "I'm not sure the museum [is open] today.",
        sentence: "Je ne suis pas sûr que le musée ___ aujourd'hui.",
        answer: "soit ouvert",
        explanation: "\"Soit\" + participle used as adjective.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: I don't think he's telling the truth.",
        words: ["Je ne pense pas", "qu'il", "dise", "la vérité."],
        translation: "I don't think he's telling the truth.",
        explanation: "Negative opinion → \"dise\".",
      },
      {
        type: "multiple-choice",
        question: "Transform into the negative: \"Je crois qu'elle a raison.\"",
        options: ["Je ne crois pas qu'elle ait raison.", "Je ne crois pas qu'elle a raison.", "Je crois qu'elle n'ait pas raison.", "Je ne crois qu'elle ait raison."],
        correctIndex: 0,
        explanation: "Negate the opinion verb with ne...pas and switch to \"ait\".",
      },
      {
        type: "listen-choose",
        audio: "Nous ne pensons pas que le magasin vende des piles.",
        question: "What did you hear?",
        options: ["que le magasin vende", "que le magasin vend", "que le magasin vende pas", "que le magasin rende"],
        correctIndex: 0,
        explanation: "\"Vende\" ends with a pronounced d [vɑ̃d].",
      },
      {
        type: "dictation",
        audio: "Je ne pense pas qu'il dise la vérité.",
        explanation: "\"Dise\" with s, pronounced [diz].",
      },
      {
        type: "speak",
        text: "Je ne suis pas sûr qu'elle puisse nous aider.",
        prompt: "Say it in French: I'm not sure she can help us.",
        explanation: "\"Puisse\" after doubt.",
      },
    ],
  },
  {
    slug: "b1-doubt-opinion-extra-7",
    level: "FR-B1",
    number: 7,
    optional: true,
    title: "Extra Practice: Impersonals, Wishes and Certainty",
    summary: "Mixed practice with all the unit's triggers: impersonal judgements, wishes with pourvu que and que, certainty and doubt.",
    duration: "13 min",
    sections: [
      {
        heading: "Recap: the unit in five frames",
        body: [
          "Certainty (indicative): il est vrai / clair / probable que, je suis sûr que, je pense que. Doubt (subjunctive): je doute que, je ne pense pas que, ça m'étonnerait que. Judgement (subjunctive or de + infinitive): il est normal / important / rare que. Necessity (subjunctive): il vaut mieux, il est temps, il suffit que. Wish (subjunctive): pourvu que, que + subjunctive.",
        ],
        examples: [
          { es: "Il est clair que la ville a changé.", en: "Clearly the town has changed." },
          { es: "Ça m'étonnerait qu'ils reviennent un jour.", en: "I doubt they'll ever come back." },
          { es: "Il est normal que les loyers soient chers ici.", en: "It's normal for rents to be high here." },
          { es: "Il suffit que tu m'envoies un message.", en: "All you need to do is send me a message." },
          { es: "Que la fête commence !", en: "Let the party begin!" },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "All you need to do is send me a message. (to a friend)",
            answer: "Il suffit que tu m'envoies un message.",
            altAnswers: ["Tu n'as qu'à m'envoyer un message.", "Il suffit de m'envoyer un message."],
            explanation: "\"Il suffit que\" + \"envoies\".",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "Let the party begin!",
            answer: "Que la fête commence !",
            altAnswers: ["Que la fête commence."],
            explanation: "\"Que\" + subjunctive for a wish.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "Clearly the town has changed.",
        answer: "Il est clair que la ville a changé.",
        altAnswers: ["C'est clair que la ville a changé.", "Il est évident que la ville a changé."],
        explanation: "\"Clair\" → indicative passé composé.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French. (use ça m'étonnerait)",
        source: "I doubt they'll ever come back.",
        answer: "Ça m'étonnerait qu'ils reviennent un jour.",
        altAnswers: ["Ça m'étonnerait qu'elles reviennent un jour."],
        explanation: "\"Ça m'étonnerait que\" + \"reviennent\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "It's normal for rents to be high here.",
        answer: "Il est normal que les loyers soient chers ici.",
        altAnswers: ["C'est normal que les loyers soient chers ici.", "Il est normal que les loyers soient élevés ici.", "C'est normal que les loyers soient élevés ici."],
        explanation: "\"Normal que\" + \"soient\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "You'd better book a table. (to a friend)",
        answer: "Il vaut mieux que tu réserves une table.",
        altAnswers: ["Il vaut mieux réserver une table.", "Tu ferais mieux de réserver une table."],
        explanation: "\"Il vaut mieux que\" + \"réserves\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "Let's hope the neighbours aren't too noisy!",
        answer: "Pourvu que les voisins ne soient pas trop bruyants !",
        altAnswers: ["Pourvu que les voisins ne fassent pas trop de bruit !"],
        explanation: "\"Pourvu que\" + negative subjunctive.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "I'm sure it's the right address.",
        answer: "Je suis sûr que c'est la bonne adresse.",
        altAnswers: ["Je suis sûre que c'est la bonne adresse.", "Je suis certain que c'est la bonne adresse.", "Je suis certaine que c'est la bonne adresse."],
        explanation: "Certainty → \"c'est\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "It's time the children went to bed.",
        answer: "Il est temps que les enfants aillent se coucher.",
        altAnswers: ["Il est temps que les enfants se couchent.", "Il est temps que les enfants aillent au lit."],
        explanation: "\"Il est temps que\" + \"aillent\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "It's rare for him to say thank you.",
        answer: "Il est rare qu'il dise merci.",
        altAnswers: ["C'est rare qu'il dise merci."],
        explanation: "\"Rare que\" + \"dise\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "It's probable that the price [will go down].",
        sentence: "Il est probable que le prix ___.",
        answer: "baissera",
        altAnswers: ["va baisser"],
        explanation: "\"Probable\" → indicative future.",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "May you [be] happy together!",
        sentence: "Que vous ___ heureux ensemble !",
        answer: "soyez",
        explanation: "\"Que\" + \"soyez\" (no i after y).",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: It's time the children went to bed.",
        words: ["Il est temps", "que les enfants", "aillent", "se coucher."],
        translation: "It's time the children went to bed.",
        explanation: "\"Il est temps que\" + \"aillent\".",
      },
      {
        type: "multi-select",
        question: "Which sentences take the indicative?",
        options: ["Il est clair que...", "Il suffit que...", "Je suis sûr que...", "Pourvu que...", "Il est probable que..."],
        correctIndexes: [0, 2, 4],
        explanation: "Clair, sûr and probable → indicative; il suffit que and pourvu que → subjunctive.",
      },
      {
        type: "listen-choose",
        audio: "Que vous soyez heureux ensemble !",
        question: "What does it mean?",
        options: ["May you be happy together!", "You are happy together!", "Are you happy together?", "That you were happy together."],
        correctIndex: 0,
        explanation: "Bare \"que\" + subjunctive = a wish.",
      },
      {
        type: "dictation",
        audio: "Il est normal que les loyers soient chers ici.",
        explanation: "\"Soient\" with -ent: plural subject.",
      },
      {
        type: "speak",
        text: "Pourvu que les voisins ne soient pas trop bruyants !",
        prompt: "Say it in French: Let's hope the neighbours aren't too noisy!",
        explanation: "\"Pourvu que\" + negative subjunctive.",
      },
    ],
  },
  {
    slug: "b1-doubt-opinion-extra-8",
    level: "FR-B1",
    number: 8,
    optional: true,
    title: "Extra Practice: Advice for a Trip to Paris",
    summary: "Translate a travel blog's advice for Paris sentence by sentence: il vaut mieux que, il est conseillé de, il est rare que.",
    duration: "13 min",
    sections: [
      {
        heading: "Recap: advice frames",
        body: [
          "Travel advice uses impersonal frames: \"il est conseillé de\" + infinitive (it's advisable to), \"il vaut mieux\" + infinitive or \"que\" + subjunctive, \"il est préférable de\", and judgements like \"il est rare que\" + subjunctive. The general versions take the infinitive; advice to \"vous\" takes que + subjunctive.",
        ],
        examples: [
          { es: "Il est conseillé de réserver les musées en ligne.", en: "It's advisable to book museums online." },
          { es: "Il vaut mieux que vous preniez le métro aux heures creuses.", en: "It's better if you take the metro at off-peak times." },
          { es: "Il est rare que les serveurs parisiens soient très bavards.", en: "Parisian waiters are rarely very chatty." },
          { es: "Il est préférable d'éviter les Champs-Élysées le samedi.", en: "It's best to avoid the Champs-Elysees on Saturdays." },
          { es: "Il faut que vous goûtiez un vrai croissant au beurre.", en: "You have to try a real butter croissant." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "It's advisable to book museums online.",
            answer: "Il est conseillé de réserver les musées en ligne.",
            altAnswers: ["Il est conseillé de réserver les musées sur internet.", "Il est recommandé de réserver les musées en ligne."],
            explanation: "General advice: \"il est conseillé de\" + infinitive.",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "It's better if you take the metro at off-peak times. (to readers)",
            answer: "Il vaut mieux que vous preniez le métro aux heures creuses.",
            altAnswers: ["Il vaut mieux prendre le métro aux heures creuses."],
            explanation: "\"Il vaut mieux que\" + \"preniez\"; \"les heures creuses\" = off-peak.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "Parisian waiters are rarely very chatty. (use il est rare)",
        answer: "Il est rare que les serveurs parisiens soient très bavards.",
        altAnswers: ["C'est rare que les serveurs parisiens soient très bavards."],
        explanation: "\"Il est rare que\" + \"soient\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "You have to try a real butter croissant. (to readers)",
        answer: "Il faut que vous goûtiez un vrai croissant au beurre.",
        altAnswers: ["Vous devez goûter un vrai croissant au beurre.", "Il faut goûter un vrai croissant au beurre."],
        explanation: "\"Il faut que\" + \"goûtiez\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "It's best to avoid the big stations at rush hour.",
        answer: "Il est préférable d'éviter les grandes gares aux heures de pointe.",
        altAnswers: ["Il vaut mieux éviter les grandes gares aux heures de pointe."],
        explanation: "General: de + infinitive; \"les heures de pointe\" = rush hour.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "It's important that you keep your bag in front of you in the metro.",
        answer: "Il est important que vous gardiez votre sac devant vous dans le métro.",
        explanation: "\"Important que\" + \"gardiez\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "It's possible the Louvre is closed on Tuesdays.",
        answer: "Il est possible que le Louvre soit fermé le mardi.",
        altAnswers: ["Il se peut que le Louvre soit fermé le mardi."],
        explanation: "\"Possible\" → \"soit\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "It's true that Paris is expensive, but there are free museums.",
        answer: "Il est vrai que Paris est cher, mais il y a des musées gratuits.",
        altAnswers: ["C'est vrai que Paris est cher, mais il y a des musées gratuits."],
        explanation: "\"Vrai\" → indicative.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "It's normal for the queues to be long in summer.",
        answer: "Il est normal que les files d'attente soient longues en été.",
        altAnswers: ["C'est normal que les files d'attente soient longues en été.", "Il est normal que les queues soient longues en été."],
        explanation: "\"Normal que\" + \"soient\"; \"longues\" agrees with files.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "All you need to do is buy a weekly pass.",
        answer: "Il suffit d'acheter un passe hebdomadaire.",
        altAnswers: ["Il suffit d'acheter un pass hebdomadaire.", "Il suffit que vous achetiez un passe hebdomadaire.", "Vous n'avez qu'à acheter un passe hebdomadaire."],
        explanation: "General: \"il suffit de\" + infinitive.",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "Let's hope you [have] nice weather!",
        sentence: "Pourvu que vous ___ beau temps !",
        answer: "ayez",
        explanation: "\"Pourvu que\" + \"ayez\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "It's advisable [to tip] in restaurants, but it's not compulsory.",
        sentence: "Il est conseillé ___ un pourboire au restaurant, mais ce n'est pas obligatoire.",
        answer: "de laisser",
        explanation: "\"Laisser un pourboire\" = to leave a tip.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: It's best to avoid the Champs-Elysees on Saturdays.",
        words: ["Il est", "préférable", "d'éviter", "les Champs-Élysées", "le samedi."],
        translation: "It's best to avoid the Champs-Elysees on Saturdays.",
        explanation: "General: de + infinitive.",
      },
      {
        type: "multiple-choice",
        question: "Which sentence gives advice to the reader (vous) rather than a general rule?",
        options: ["Il vaut mieux que vous marchiez.", "Il vaut mieux marcher.", "Il est conseillé de marcher.", "Il est préférable de marcher."],
        correctIndex: 0,
        explanation: "Only \"que vous\" + subjunctive targets the reader.",
      },
      {
        type: "listen-choose",
        audio: "Il est conseillé de réserver les musées en ligne.",
        question: "What does it mean?",
        options: ["It's advisable to book museums online.", "Museums advise you to book online.", "You can't book museums online.", "Online museums are advisable."],
        correctIndex: 0,
        explanation: "\"Il est conseillé de\" = it's advisable to.",
      },
      {
        type: "dictation",
        audio: "Il faut que vous goûtiez un vrai croissant au beurre.",
        explanation: "\"Goûtiez\": -iez for vous; û in goûter.",
      },
      {
        type: "speak",
        text: "Il vaut mieux que vous preniez le métro aux heures creuses.",
        prompt: "Say it in French: It's better if you take the metro at off-peak times.",
        explanation: "\"Preniez\" from the nous stem.",
      },
    ],
  },
  {
    slug: "b1-doubt-opinion-extra-9",
    level: "FR-B1",
    number: 9,
    optional: true,
    title: "Extra Practice: Fact, Judgement or Possibility?",
    summary: "Choose the mood in each sentence and explain it: fact or certainty, judgement, or possibility and doubt.",
    duration: "12 min",
    sections: [
      {
        heading: "Recap: three labels",
        body: [
          "Label each sentence before you write the verb. Fact or certainty (savoir, être sûr, vrai, clair, probable, peut-être que, se douter): indicative. Judgement or necessity (normal, important, dommage, rare, il faut, il vaut mieux): subjunctive. Possibility or doubt (possible, il se peut, peu probable, douter, ne pas penser): subjunctive.",
        ],
        examples: [
          { es: "Je sais que le bureau est fermé.", en: "I know the office is closed." },
          { es: "C'est dommage que le bureau soit fermé.", en: "It's a shame the office is closed." },
          { es: "Il se peut que le bureau soit fermé.", en: "The office may be closed." },
          { es: "Il est évident que tu fais des progrès.", en: "Obviously you're making progress." },
          { es: "Je doute que tu fasses assez de progrès.", en: "I doubt you're making enough progress." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "\"C'est dommage que le bureau soit fermé.\" Why the subjunctive?",
            options: ["It's a judgement (dommage).", "It's a possibility.", "It's a fact.", "Because the office is closed in the future."],
            correctIndex: 0,
            explanation: "Judgement triggers the subjunctive even for a known fact.",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "Obviously you're making progress. (to a friend)",
            answer: "Il est évident que tu fais des progrès.",
            altAnswers: ["C'est évident que tu fais des progrès.", "Il est clair que tu fais des progrès."],
            explanation: "Certainty → indicative \"fais\".",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "I doubt you're making enough progress. (to a friend)",
            answer: "Je doute que tu fasses assez de progrès.",
            explanation: "Doubt → \"fasses\".",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "I know the office is closed.",
        answer: "Je sais que le bureau est fermé.",
        explanation: "Fact → indicative.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "The office may be closed. (use il se peut)",
        answer: "Il se peut que le bureau soit fermé.",
        explanation: "Possibility → subjunctive.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "It's strange that she hasn't got a phone.",
        answer: "C'est bizarre qu'elle n'ait pas de téléphone.",
        altAnswers: ["C'est étrange qu'elle n'ait pas de téléphone.", "Il est étrange qu'elle n'ait pas de téléphone.", "Il est bizarre qu'elle n'ait pas de téléphone."],
        explanation: "Judgement → \"ait\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "It's likely she's lost her phone. (use il est probable)",
        answer: "Il est probable qu'elle a perdu son téléphone.",
        explanation: "Likely → indicative passé composé.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "Maybe she's at the gym.",
        answer: "Peut-être qu'elle est à la salle de sport.",
        altAnswers: ["Elle est peut-être à la salle de sport.", "Peut-être qu'elle est à la salle de gym.", "Elle est peut-être à la salle de gym."],
        explanation: "\"Peut-être que\" → indicative.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "It's essential that everyone knows the rules.",
        answer: "Il est essentiel que tout le monde connaisse les règles.",
        altAnswers: ["C'est essentiel que tout le monde connaisse les règles.", "Il est essentiel que chacun connaisse les règles."],
        explanation: "Necessity → \"connaisse\" (tout le monde is singular).",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "I suspected you were tired. (use se douter, to a friend)",
        answer: "Je me doutais que tu étais fatigué.",
        altAnswers: ["Je me doutais que tu étais fatiguée."],
        explanation: "\"Se douter que\" → indicative.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "It's unlikely the bank will lend us money.",
        answer: "Il est peu probable que la banque nous prête de l'argent.",
        explanation: "Unlikely → subjunctive \"prête\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "It's a pity you [can't] stay longer. (to a friend)",
        sentence: "C'est dommage que tu ___ rester plus longtemps.",
        answer: "ne puisses pas",
        explanation: "Judgement → \"ne puisses pas\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "It's certain that the price [will go up].",
        sentence: "Il est certain que le prix ___.",
        answer: "augmentera",
        altAnswers: ["va augmenter"],
        explanation: "Certainty → future.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: It's unlikely the bank will lend us money.",
        words: ["Il est", "peu probable", "que la banque", "nous prête", "de l'argent."],
        translation: "It's unlikely the bank will lend us money.",
        explanation: "\"Peu probable\" → subjunctive.",
      },
      {
        type: "matching",
        instructions: "Match each sentence with its label.",
        pairs: [
          { left: "Je sais qu'il pleut.", right: "fact: indicative" },
          { left: "C'est dommage qu'il pleuve.", right: "judgement: subjunctive" },
          { left: "Il se peut qu'il pleuve.", right: "possibility: subjunctive" },
          { left: "Il est probable qu'il pleuvra.", right: "likelihood: indicative" },
        ],
        explanation: "Label first, then choose the mood.",
      },
      {
        type: "listen-choose",
        audio: "Il est essentiel que tout le monde connaisse les règles.",
        question: "What did you hear?",
        options: ["que tout le monde connaisse", "que tout le monde connaît", "que tout le monde connaissent", "que tout le monde reconnaisse"],
        correctIndex: 0,
        explanation: "Singular subject, subjunctive \"connaisse\".",
      },
      {
        type: "dictation",
        audio: "C'est bizarre qu'elle n'ait pas de téléphone.",
        explanation: "\"N'ait pas\": subjunctive of avoir with t.",
      },
      {
        type: "speak",
        text: "Il est peu probable que la banque nous prête de l'argent.",
        prompt: "Say it in French: It's unlikely the bank will lend us money.",
        explanation: "\"Peu probable\" → subjunctive.",
      },
    ],
  },
  {
    slug: "b1-doubt-opinion-extra-10",
    level: "FR-B1",
    number: 10,
    optional: true,
    title: "Extra Practice: Dictation, Long Impersonal Sentences",
    summary: "Write down long sentences with il est + adjective + que and silent subjunctive endings, then translate new ones.",
    duration: "13 min",
    sections: [
      {
        heading: "Recap: hear the frame, write the ending",
        body: [
          "In long impersonal sentences the frame tells you the mood before the verb arrives: \"il est important que\", \"il est possible que\" → subjunctive; \"il est probable que\", \"il est clair que\" → indicative. Then the subject tells you the silent ending: -e, -es, -ent. Write the frame, find the subject, then spell the verb.",
        ],
        examples: [
          { es: "Il est important que les élèves rendent leurs devoirs à temps.", en: "It's important that pupils hand in their homework on time." },
          { es: "Il est possible que mes cousins arrivent un peu plus tard.", en: "My cousins may arrive a little later." },
          { es: "Il est probable que la piscine fermera pendant les travaux.", en: "The pool will probably close during the works." },
          { es: "Il est dommage que tu n'aimes pas le fromage.", en: "It's a shame you don't like cheese." },
          { es: "Il est clair que nos voisins ont refait leur cuisine.", en: "Clearly our neighbours have redone their kitchen." },
        ],
        checkpoint: [
          {
            type: "dictation",
            audio: "Il est possible que mes cousins arrivent un peu plus tard.",
            explanation: "\"Mes cousins\" → \"arrivent\" with -ent.",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "It's a shame you don't like cheese. (to a friend)",
            answer: "Il est dommage que tu n'aimes pas le fromage.",
            altAnswers: ["C'est dommage que tu n'aimes pas le fromage.", "Dommage que tu n'aimes pas le fromage."],
            explanation: "\"Dommage que\" + \"aimes\" (-es for tu).",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "The pool will probably close during the works. (use il est probable)",
            answer: "Il est probable que la piscine fermera pendant les travaux.",
            altAnswers: ["Il est probable que la piscine va fermer pendant les travaux."],
            explanation: "\"Probable\" → future.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "dictation",
        audio: "Il est important que les élèves rendent leurs devoirs à temps.",
        explanation: "\"Rendent\": -ent for les élèves.",
      },
      {
        type: "dictation",
        audio: "Il est clair que nos voisins ont refait leur cuisine.",
        explanation: "Indicative after \"clair\": \"ont refait\".",
      },
      {
        type: "dictation",
        audio: "Il est rare que ma sœur oublie un anniversaire.",
        explanation: "\"Oublie\" with -e: singular subject.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "It's important that pupils hand in their homework on time.",
        answer: "Il est important que les élèves rendent leurs devoirs à temps.",
        altAnswers: ["C'est important que les élèves rendent leurs devoirs à temps.", "Il est important que les élèves rendent leurs devoirs à l'heure."],
        explanation: "\"Rendre\" = to hand in; subjunctive \"rendent\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "My sister rarely forgets a birthday. (use il est rare)",
        answer: "Il est rare que ma sœur oublie un anniversaire.",
        altAnswers: ["C'est rare que ma sœur oublie un anniversaire."],
        explanation: "\"Rare que\" + \"oublie\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "It's possible that the doctors will strike next week.",
        answer: "Il est possible que les médecins fassent grève la semaine prochaine.",
        altAnswers: ["Il se peut que les médecins fassent grève la semaine prochaine.", "C'est possible que les médecins fassent grève la semaine prochaine."],
        explanation: "\"Faire grève\" = to strike; subjunctive \"fassent\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "It's necessary for you to fill in this form. (to a client)",
        answer: "Il est nécessaire que vous remplissiez ce formulaire.",
        altAnswers: ["Il faut que vous remplissiez ce formulaire."],
        explanation: "\"Remplissiez\" (from ils remplissent).",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "It's normal for the children to be tired after school.",
        answer: "Il est normal que les enfants soient fatigués après l'école.",
        altAnswers: ["C'est normal que les enfants soient fatigués après l'école."],
        explanation: "\"Soient fatigués\": plural agreement twice.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "It's true that the trains are often late in winter.",
        answer: "Il est vrai que les trains sont souvent en retard en hiver.",
        altAnswers: ["C'est vrai que les trains sont souvent en retard en hiver."],
        explanation: "\"Vrai\" → indicative \"sont\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "It's urgent that the tenants [leave] the building.",
        sentence: "Il est urgent que les locataires ___ l'immeuble.",
        answer: "quittent",
        explanation: "\"Quittent\": plural subjunctive, silent -ent.",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "It's impossible for us [to be] there before nine.",
        sentence: "Il est impossible que nous ___ là avant neuf heures.",
        answer: "soyons",
        explanation: "\"Soyons\": no i after y.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: It's normal for the children to be tired.",
        words: ["Il est", "normal", "que les enfants", "soient", "fatigués."],
        translation: "It's normal for the children to be tired.",
        explanation: "\"Normal que\" + \"soient\".",
      },
      {
        type: "listen-choose",
        audio: "Il est possible que les médecins fassent grève.",
        question: "What does it mean?",
        options: ["The doctors may go on strike.", "The doctors are on strike.", "The doctors will definitely strike.", "It's possible to strike as a doctor."],
        correctIndex: 0,
        explanation: "\"Possible que\" + \"fassent grève\".",
      },
      {
        type: "dictation",
        audio: "Il est nécessaire que vous remplissiez ce formulaire.",
        explanation: "\"Remplissiez\": double s, then -iez.",
      },
      {
        type: "speak",
        text: "Il est vrai que les trains sont souvent en retard en hiver.",
        prompt: "Say it in French: It's true that the trains are often late in winter.",
        explanation: "\"Vrai\" → indicative.",
      },
    ],
  },
];
