// Synced from cheneygross-afk/lengo:src/lib/lessons/fr-b1-u19-extra.ts by scripts/sync-content.mjs -- edit it there, not here.
import type { Lesson } from "./types";

// French B1, Unit 19 extra practice: The Passive Voice and On.

export const FR_B1_U19_EXTRA: Lesson[] = [
  {
    slug: "b1-passive-extra-1",
    level: "FR-B1",
    number: 1,
    optional: true,
    title: "Extra Practice: The Passive and On, Part 1 of 3",
    summary: "More practice with present and passé composé passives, keeping the participle in agreement with the subject.",
    duration: "12 min",
    sections: [
      {
        heading: "Recap: est / a été + agreeing participle",
        body: [
          "Present passive: \"est\" / \"sont\" + participle (\"Le marché est installé tous les samedis\"). Passé composé passive: \"a été\" / \"ont été\" + participle (\"Le marché a été installé ce matin\"). \"Été\" never changes; the main participle agrees with the subject, like an adjective.",
          "Watch feminine and plural subjects: \"la route a été fermée\", \"les tables ont été installées\", \"les élèves ont été félicités\".",
        ],
        examples: [
          { es: "Le marché est installé tous les samedis sur la place.", en: "The market is set up on the square every Saturday." },
          { es: "Les poubelles sont ramassées le mardi.", en: "The bins are collected on Tuesdays." },
          { es: "La vieille gare a été transformée en musée.", en: "The old station has been turned into a museum." },
          { es: "Les élèves ont été félicités par le directeur.", en: "The pupils were congratulated by the head teacher." },
          { es: "Ma valise a été perdue à Roissy.", en: "My suitcase was lost at Roissy airport." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "The bins are collected on Tuesdays.",
            answer: "Les poubelles sont ramassées le mardi.",
            altAnswers: ["Les poubelles sont collectées le mardi."],
            explanation: "Present passive for a regular action; \"ramassées\" agrees with les poubelles.",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "My suitcase was lost.",
            answer: "Ma valise a été perdue.",
            altAnswers: ["On a perdu ma valise."],
            explanation: "\"A été perdue\": feminine agreement.",
          },
          {
            type: "multiple-choice",
            question: "Which sentence is correct?",
            options: ["Les tables ont été installées.", "Les tables ont étées installées.", "Les tables sont été installées.", "Les tables ont été installé."],
            correctIndex: 0,
            explanation: "\"Ont été\" + \"installées\" (feminine plural). \"Été\" never agrees.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "The old station has been turned into a museum.",
        answer: "La vieille gare a été transformée en musée.",
        altAnswers: ["L'ancienne gare a été transformée en musée."],
        explanation: "\"Transformée\" agrees with la gare.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "The pupils were congratulated.",
        answer: "Les élèves ont été félicités.",
        altAnswers: ["Les élèves ont été félicitées."],
        explanation: "Masculine plural by default: \"félicités\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "The streets are cleaned every night.",
        answer: "Les rues sont nettoyées toutes les nuits.",
        altAnswers: ["Les rues sont nettoyées chaque nuit."],
        explanation: "Present passive, feminine plural agreement.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "The window was broken.",
        answer: "La fenêtre a été cassée.",
        altAnswers: ["On a cassé la fenêtre."],
        explanation: "An event → \"a été cassée\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "These cheeses are made in Normandy.",
        answer: "Ces fromages sont fabriqués en Normandie.",
        altAnswers: ["Ces fromages sont faits en Normandie.", "Ces fromages sont produits en Normandie."],
        explanation: "\"Fabriqués\" agrees with ces fromages.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "The meeting has been postponed.",
        answer: "La réunion a été reportée.",
        explanation: "\"Reporter\" = to postpone; feminine agreement.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "The flowers were picked this morning.",
        answer: "Les fleurs ont été cueillies ce matin.",
        explanation: "Irregular participle \"cueilli\" + -es.",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "The children [were vaccinated] last year.",
        sentence: "Les enfants ___ l'année dernière.",
        answer: "ont été vaccinés",
        explanation: "\"Ont été\" + \"vaccinés\" (masculine plural).",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "The film [is shown] in the original version.",
        sentence: "Le film ___ en version originale.",
        answer: "est projeté",
        altAnswers: ["est diffusé", "est montré"],
        explanation: "Present passive for a regular arrangement.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: The bridge was opened by the mayor.",
        words: ["Le", "pont", "a été", "inauguré", "par", "le", "maire."],
        translation: "The bridge was opened by the mayor.",
        explanation: "\"A été inauguré\" + par.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "Breakfast is served until ten.",
        answer: "Le petit-déjeuner est servi jusqu'à dix heures.",
        altAnswers: ["Le petit-déjeuner est servi jusqu'à 10 heures.", "Le petit déjeuner est servi jusqu'à dix heures.", "Le petit déjeuner est servi jusqu'à 10 heures."],
        explanation: "Present passive; \"servi\" agrees with le petit-déjeuner.",
      },
      {
        type: "multiple-choice",
        question: "Which means 'The letter has been signed'?",
        options: ["La lettre a été signée.", "La lettre a signé.", "La lettre est signé.", "La lettre a été signé."],
        correctIndex: 0,
        explanation: "\"A été signée\" with feminine agreement.",
      },
      {
        type: "dictation",
        audio: "La vieille gare a été transformée en musée.",
        explanation: "\"Transformée\": silent agreement, but required in writing.",
      },
      {
        type: "speak",
        text: "Les poubelles sont ramassées le mardi.",
        prompt: "Say it in French: The bins are collected on Tuesdays.",
        explanation: "Present passive for a routine.",
      },
    ],
  },
  {
    slug: "b1-passive-extra-2",
    level: "FR-B1",
    number: 2,
    optional: true,
    title: "Extra Practice: The Passive and On, Part 2 of 3",
    summary: "More practice with passives in the imparfait, the future and the plus-que-parfait.",
    duration: "12 min",
    sections: [
      {
        heading: "Recap: était, sera, avait été",
        body: [
          "Imparfait passive (\"était\" + participle) for past descriptions and habits: \"Le château était entouré d'un fossé.\" Future (\"sera\"): \"Le stade sera agrandi.\" Plus-que-parfait (\"avait été\"): \"Quand on est arrivés, tout avait été rangé.\"",
          "Agreement doesn't change with the tense: \"la salle était décorée\", \"les billets seront vendus\", \"la décision avait été prise\".",
        ],
        examples: [
          { es: "Le château était entouré d'un fossé.", en: "The castle was surrounded by a moat." },
          { es: "Autrefois, les enfants étaient punis pour un rien.", en: "In the old days, children were punished for nothing." },
          { es: "Le stade sera agrandi avant les Jeux.", en: "The stadium will be extended before the Games." },
          { es: "Quand on est arrivés, tout avait été rangé.", en: "When we arrived, everything had been tidied away." },
          { es: "Les billets seront vendus à partir de lundi.", en: "Tickets will go on sale from Monday." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "The stadium will be extended.",
            answer: "Le stade sera agrandi.",
            explanation: "Future passive: \"sera agrandi\".",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "Everything had been tidied away.",
            answer: "Tout avait été rangé.",
            explanation: "Plus-que-parfait passive; \"tout\" is masculine singular.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "In the past, letters were written by hand.",
        answer: "Autrefois, les lettres étaient écrites à la main.",
        altAnswers: ["Avant, les lettres étaient écrites à la main."],
        explanation: "Past habit → \"étaient écrites\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "Tickets will go on sale on Monday.",
        answer: "Les billets seront mis en vente lundi.",
        altAnswers: ["Les billets seront vendus à partir de lundi.", "Les billets seront en vente lundi.", "Les billets seront mis en vente à partir de lundi."],
        explanation: "Future passive: \"seront mis en vente\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "The room was decorated with flowers.",
        answer: "La salle était décorée de fleurs.",
        altAnswers: ["La salle était décorée avec des fleurs.", "La salle a été décorée de fleurs."],
        explanation: "A description → \"était décorée\"; de with a state.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "The decision had already been made.",
        answer: "La décision avait déjà été prise.",
        explanation: "\"Avait déjà été prise\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "The results will be sent by email.",
        answer: "Les résultats seront envoyés par mail.",
        altAnswers: ["Les résultats seront envoyés par e-mail.", "Les résultats seront envoyés par courriel."],
        explanation: "Future passive with masculine plural agreement.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "The town was surrounded by walls.",
        answer: "La ville était entourée de remparts.",
        altAnswers: ["La ville était entourée de murs.", "La ville était entourée de murailles."],
        explanation: "A state in the past → imparfait + de.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "The road will be closed all weekend.",
        answer: "La route sera fermée tout le week-end.",
        explanation: "\"Sera fermée\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "When the police arrived, the money [had been hidden].",
        sentence: "Quand la police est arrivée, l'argent ___.",
        answer: "avait été caché",
        explanation: "Plus-que-parfait passive for something earlier.",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "In the past, the house [was heated] with wood.",
        sentence: "Autrefois, la maison ___ au bois.",
        answer: "était chauffée",
        explanation: "Past habit → \"était chauffée\".",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: The new hospital will be built here.",
        words: ["Le", "nouvel", "hôpital", "sera", "construit", "ici."],
        translation: "The new hospital will be built here.",
        explanation: "\"Nouvel\" before a vowel; future passive.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "The guests had been invited for eight o'clock.",
        answer: "Les invités avaient été invités pour huit heures.",
        altAnswers: ["Les invités avaient été conviés pour huit heures.", "Les invités avaient été invités pour 20 heures."],
        explanation: "Plus-que-parfait passive; plural agreement.",
      },
      {
        type: "multiple-choice",
        question: "Which sentence describes a past habit?",
        options: [
          "Le pain était livré tous les matins.",
          "Le pain a été livré ce matin.",
          "Le pain sera livré demain.",
          "Le pain avait été livré avant midi.",
        ],
        correctIndex: 0,
        explanation: "Imparfait \"était livré\" + \"tous les matins\" = a habit.",
      },
      {
        type: "listen-choose",
        audio: "Les billets seront vendus à partir de lundi.",
        question: "What does it mean?",
        options: ["Tickets will be on sale from Monday.", "Tickets were sold on Monday.", "Tickets are sold out from Monday.", "Tickets had been sold by Monday."],
        correctIndex: 0,
        explanation: "\"Seront vendus\": future.",
      },
      {
        type: "speak",
        text: "Quand on est arrivés, tout avait été rangé.",
        prompt: "Say it in French: When we arrived, everything had been tidied away.",
        explanation: "Passé composé for the arrival, plus-que-parfait passive for what came before.",
      },
    ],
  },
  {
    slug: "b1-passive-extra-3",
    level: "FR-B1",
    number: 3,
    optional: true,
    title: "Extra Practice: The Passive and On, Part 3 of 3",
    summary: "More practice using on in place of the passive, including for I was told, we were asked, she was given.",
    duration: "12 min",
    sections: [
      {
        heading: "Recap: on + active verb",
        body: [
          "In speech, \"on\" + an active verb replaces most passives: \"On a réparé l'ascenseur\" (The lift has been fixed). With verbs that take \"à\" + person (\"dire\", \"donner\", \"demander\", \"offrir\", \"envoyer\", \"expliquer\"), \"on\" is the only way: \"On m'a dit\", \"On nous a demandé\", \"On lui a offert\".",
          "The object pronoun comes before the auxiliary: \"on m'a\", \"on t'a\", \"on lui a\", \"on nous a\", \"on vous a\", \"on leur a\".",
        ],
        examples: [
          { es: "On a enfin réparé l'ascenseur.", en: "The lift has finally been fixed." },
          { es: "On m'a dit d'attendre ici.", en: "I was told to wait here." },
          { es: "On nous a servi un excellent dîner.", en: "We were served an excellent dinner." },
          { es: "On lui a offert des fleurs.", en: "She was given flowers." },
          { es: "On leur a expliqué les règles.", en: "The rules were explained to them." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "I was told to wait here.",
            answer: "On m'a dit d'attendre ici.",
            explanation: "\"Dire à quelqu'un de\" → \"on m'a dit de\".",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "We were served a delicious dinner.",
            answer: "On nous a servi un délicieux dîner.",
            altAnswers: ["On nous a servi un dîner délicieux."],
            explanation: "\"Servir quelque chose à quelqu'un\" → \"on nous a servi\".",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "She was given flowers.",
        answer: "On lui a offert des fleurs.",
        altAnswers: ["On lui a donné des fleurs."],
        explanation: "No passive with an indirect object: \"on lui a offert\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "The rules were explained to us.",
        answer: "On nous a expliqué les règles.",
        explanation: "\"Expliquer à\" → \"on nous a expliqué\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "I was asked for my ticket.",
        answer: "On m'a demandé mon billet.",
        altAnswers: ["On m'a demandé mon ticket."],
        explanation: "\"Demander à quelqu'un\" → \"on m'a demandé\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French using on.",
        source: "The lift has been fixed.",
        answer: "On a réparé l'ascenseur.",
        explanation: "\"On\" + active is the spoken alternative to \"l'ascenseur a été réparé\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "They were sent a letter.",
        answer: "On leur a envoyé une lettre.",
        explanation: "\"Envoyer à\" → \"on leur a envoyé\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "You were promised a refund. (polite)",
        answer: "On vous a promis un remboursement.",
        explanation: "\"Promettre à\" → \"on vous a promis\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French using on.",
        source: "My wallet has been stolen.",
        answer: "On m'a volé mon portefeuille.",
        altAnswers: ["On a volé mon portefeuille."],
        explanation: "\"On m'a volé\" = someone stole from me.",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "[He was shown] the way.",
        sentence: "___ le chemin.",
        answer: "On lui a montré",
        explanation: "\"Montrer à\" → \"on lui a montré\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "[We were asked] to leave.",
        sentence: "___ de partir.",
        answer: "On nous a demandé",
        explanation: "\"Demander à quelqu'un de partir\".",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: I was taught to swim at five.",
        words: ["On", "m'a", "appris", "à", "nager", "à cinq ans."],
        translation: "I was taught to swim at five.",
        explanation: "\"Apprendre à quelqu'un à faire\" → \"on m'a appris à\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "We were told the truth.",
        answer: "On nous a dit la vérité.",
        explanation: "\"Dire quelque chose à quelqu'un\" → \"on nous a dit\".",
      },
      {
        type: "multiple-choice",
        question: "Which sentence is correct for 'I was offered a coffee'?",
        options: ["On m'a offert un café.", "J'ai été offert un café.", "J'étais offert un café.", "Un café m'a offert."],
        correctIndex: 0,
        explanation: "\"Offrir à\": the person can't be the passive subject.",
      },
      {
        type: "listen-choose",
        audio: "On leur a expliqué les règles.",
        question: "What does it mean?",
        options: ["The rules were explained to them.", "They explained the rules.", "We explained the rules to him.", "The rules were explained to us."],
        correctIndex: 0,
        explanation: "\"Leur\" = to them.",
      },
      {
        type: "speak",
        text: "On m'a dit d'attendre ici.",
        prompt: "Say it in French: I was told to wait here.",
        explanation: "\"On m'a dit de\" + infinitive.",
      },
    ],
  },
  {
    slug: "b1-passive-extra-4",
    level: "FR-B1",
    number: 4,
    optional: true,
    title: "Extra Practice: Real-World Mission, The Newspaper Article",
    summary: "Write a short faits divers report (local news) with passives: who was arrested, injured, rescued, and what will be done.",
    duration: "13 min",
    sections: [
      {
        heading: "Recap: the style of a fait divers",
        body: [
          "\"Un fait divers\" is a short local news story: a theft, an accident, a rescue. The style relies on the passive without agent: \"Un homme a été blessé\", \"Les pompiers ont été appelés\", \"Une enquête a été ouverte\" (An investigation has been opened), \"Le suspect sera jugé en mars\".",
          "Typical verbs: \"blesser\", \"secourir\" (to rescue, participle \"secouru\"), \"transporter à l'hôpital\", \"interpeller\" (to arrest, police jargon), \"évacuer\", \"retrouver\", \"placer en garde à vue\" (to take into custody).",
        ],
        examples: [
          { es: "Un cycliste a été blessé hier matin à Nantes.", en: "A cyclist was injured yesterday morning in Nantes." },
          { es: "Il a été transporté à l'hôpital par les pompiers.", en: "He was taken to hospital by the fire brigade." },
          { es: "Deux randonneurs ont été secourus en montagne.", en: "Two hikers were rescued in the mountains." },
          { es: "Une enquête a été ouverte.", en: "An investigation has been opened." },
          { es: "Le conducteur a été placé en garde à vue.", en: "The driver was taken into custody." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "Two hikers were rescued.",
            answer: "Deux randonneurs ont été secourus.",
            altAnswers: ["Deux randonneuses ont été secourues."],
            explanation: "\"Secourir\" → participle \"secouru\", plural \"secourus\".",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "An investigation has been opened.",
            answer: "Une enquête a été ouverte.",
            explanation: "\"Ouverte\": feminine agreement, audible t.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "A cyclist was injured yesterday.",
        answer: "Un cycliste a été blessé hier.",
        altAnswers: ["Une cycliste a été blessée hier."],
        explanation: "Passé composé passive without agent.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "She was taken to hospital.",
        answer: "Elle a été transportée à l'hôpital.",
        altAnswers: ["Elle a été emmenée à l'hôpital.", "On l'a transportée à l'hôpital.", "On l'a emmenée à l'hôpital."],
        explanation: "\"Transportée\" agrees with elle.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "The building was evacuated.",
        answer: "Le bâtiment a été évacué.",
        altAnswers: ["L'immeuble a été évacué."],
        explanation: "\"A été évacué\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "The fire brigade were called at midnight.",
        answer: "Les pompiers ont été appelés à minuit.",
        altAnswers: ["On a appelé les pompiers à minuit."],
        explanation: "\"Appeler\" has a direct object, so the passive works.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "The suspect will be tried in June.",
        answer: "Le suspect sera jugé en juin.",
        explanation: "Future passive: \"sera jugé\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "The stolen paintings were found in a garage.",
        answer: "Les tableaux volés ont été retrouvés dans un garage.",
        explanation: "\"Volés\" as an adjective; \"ont été retrouvés\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "The driver had been drinking.",
        answer: "Le conducteur avait bu.",
        altAnswers: ["Le conducteur avait bu de l'alcool."],
        explanation: "Not a passive: plus-que-parfait active \"avait bu\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "The driver [was taken into custody].",
        sentence: "Le conducteur ___ en garde à vue.",
        answer: "a été placé",
        explanation: "\"Placer en garde à vue\": police language.",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "The road [had been closed] because of the ice.",
        sentence: "La route ___ à cause du verglas.",
        answer: "avait été fermée",
        explanation: "Plus-que-parfait passive.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: The victim was rescued by a neighbour.",
        words: ["La", "victime", "a été", "secourue", "par", "un", "voisin."],
        translation: "The victim was rescued by a neighbour.",
        explanation: "\"Victime\" is always feminine: \"secourue\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "Nobody was injured.",
        answer: "Personne n'a été blessé.",
        explanation: "\"Personne ne\" + passive; masculine singular agreement.",
      },
      {
        type: "multiple-choice",
        question: "Which sentence sounds like a newspaper?",
        options: [
          "Un individu a été interpellé vers 23 heures.",
          "Ils ont chopé un type vers 23 heures.",
          "On a arrêté un mec vers 23 heures.",
          "Un individu interpelle vers 23 heures.",
        ],
        correctIndex: 0,
        explanation: "Passive + \"individu\" + \"interpellé\": newspaper register.",
      },
      {
        type: "dictation",
        audio: "Deux randonneurs ont été secourus en montagne.",
        explanation: "\"Secourus\" agrees with deux randonneurs.",
      },
      {
        type: "speak",
        text: "Une enquête a été ouverte.",
        prompt: "Say it in French: An investigation has been opened.",
        explanation: "\"Ouverte\": the t is pronounced.",
      },
    ],
  },
  {
    slug: "b1-passive-extra-5",
    level: "FR-B1",
    number: 5,
    optional: true,
    title: "Extra Practice: Error Hunt, Passive and On",
    summary: "Fix learners' passive mistakes: missing agreement, avoir instead of être, and impossible English-style passives like *j'ai été dit.",
    duration: "12 min",
    sections: [
      {
        heading: "Recap: the three classic errors",
        body: [
          "Error 1, missing agreement: *La maison a été vendu* → \"La maison a été vendue\". Error 2, the wrong auxiliary: *La lettre a envoyée* (no \"été\") → \"La lettre a été envoyée\"; *Le pont est été construit* → \"Le pont a été construit\".",
          "Error 3, passives from indirect objects: *J'ai été dit que...* → \"On m'a dit que...\"; *Elle a été donnée un livre* → \"On lui a donné un livre\".",
        ],
        examples: [
          { es: "La maison a été vendue en juin.", en: "The house was sold in June." },
          { es: "La lettre a été envoyée hier.", en: "The letter was sent yesterday." },
          { es: "Le pont a été construit en 1920.", en: "The bridge was built in 1920." },
          { es: "On m'a dit que tu déménageais.", en: "I was told you were moving." },
          { es: "On lui a donné un livre.", en: "She was given a book." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Fix the error and translate. Wrong version: « La maison a été vendu. »",
            source: "The house was sold.",
            answer: "La maison a été vendue.",
            explanation: "Agreement with la maison: \"vendue\".",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Fix the error and translate. Wrong version: « J'ai été dit que tu déménageais. »",
            source: "I was told you were moving.",
            answer: "On m'a dit que tu déménageais.",
            altAnswers: ["On m'a dit que vous déménagiez."],
            explanation: "\"Dire à\" has no passive: \"on m'a dit\".",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Fix the error and translate. Wrong version: « Le pont est été construit en 1920. »",
        source: "The bridge was built in 1920.",
        answer: "Le pont a été construit en 1920.",
        explanation: "The passé composé of être is \"a été\", never *est été*.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Fix the error and translate. Wrong version: « La lettre a envoyée hier. »",
        source: "The letter was sent yesterday.",
        answer: "La lettre a été envoyée hier.",
        explanation: "The passive needs \"été\": \"a été envoyée\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Fix the error and translate. Wrong version: « Elle a été donnée un livre. »",
        source: "She was given a book.",
        answer: "On lui a donné un livre.",
        altAnswers: ["On lui a offert un livre."],
        explanation: "\"Donner à\": use \"on lui a donné\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Fix the error and translate. Wrong version: « Les voleurs ont été arrêté. »",
        source: "The thieves were arrested.",
        answer: "Les voleurs ont été arrêtés.",
        explanation: "Plural agreement: \"arrêtés\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Fix the error and translate. Wrong version: « Nous avons été demandés de partir. »",
        source: "We were asked to leave.",
        answer: "On nous a demandé de partir.",
        explanation: "\"Demander à quelqu'un de\": no passive.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Fix the error and translate. Wrong version: « La réunion sera annulé. »",
        source: "The meeting will be cancelled.",
        answer: "La réunion sera annulée.",
        explanation: "Feminine agreement: \"annulée\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Fix the error and translate. Wrong version: « Ce livre a été écrit de Victor Hugo. »",
        source: "This book was written by Victor Hugo.",
        answer: "Ce livre a été écrit par Victor Hugo.",
        explanation: "An action → \"par\". \"De\" is for states and feelings.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Fix the error and translate. Wrong version: « J'ai été montré la chambre. »",
        source: "I was shown the room.",
        answer: "On m'a montré la chambre.",
        explanation: "\"Montrer à\" → \"on m'a montré\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "The windows [had been opened].",
        sentence: "Les fenêtres ___.",
        answer: "avaient été ouvertes",
        explanation: "\"Avaient été\" + \"ouvertes\" (feminine plural).",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: He is respected by everyone.",
        words: ["Il", "est", "respecté", "de", "tous."],
        translation: "He is respected by everyone.",
        explanation: "A feeling → \"de tous\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Fix the error and translate. Wrong version: « On ont réparé la voiture. »",
        source: "The car has been repaired.",
        answer: "On a réparé la voiture.",
        altAnswers: ["La voiture a été réparée."],
        explanation: "\"On\" always takes a singular verb: \"on a\".",
      },
      {
        type: "multiple-choice",
        question: "Which sentence is correct?",
        options: [
          "Les enfants ont été invités à la fête.",
          "Les enfants ont été invité à la fête.",
          "Les enfants sont été invités à la fête.",
          "Les enfants ont étés invités à la fête.",
        ],
        correctIndex: 0,
        explanation: "\"Ont été\" + plural participle; \"été\" never changes.",
      },
      {
        type: "listen-choose",
        audio: "La lettre a été envoyée hier.",
        question: "What did you hear?",
        options: ["La lettre a été envoyée hier.", "La lettre a envoyé hier.", "La lettre est envoyée hier.", "La lettre était envoyée hier."],
        correctIndex: 0,
        explanation: "Listen for \"a été\": é-té.",
      },
      {
        type: "speak",
        text: "On m'a dit que tu déménageais.",
        prompt: "Say it in French: I was told you were moving.",
        explanation: "\"On m'a dit que\" + imparfait.",
      },
    ],
  },
  {
    slug: "b1-passive-extra-6",
    level: "FR-B1",
    number: 6,
    optional: true,
    title: "Extra Practice: Dialogue Lab, Moving Day",
    summary: "Movers and owners on moving day: Tout a été emballé ? On a cassé un vase ! Practise the passive and on in a lively dialogue.",
    duration: "12 min",
    sections: [
      {
        heading: "Recap: the dialogue",
        body: [
          "Mme Lefèvre is moving from Lille to Rennes. She checks with Karim, the head mover (\"le déménageur\"), using the passive for what has been done and \"on\" for what the team did: \"Tout a été emballé ? — Oui, les cartons ont été fermés et étiquetés. Mais... on a cassé un vase. — Quoi ? Le vase qui m'avait été offert par ma mère ?\"",
          "Notice \"qui m'avait été offert\": the vase is the subject (it was given to me), so the passive works with the thing as subject, while the person stays indirect (\"m'\").",
        ],
        examples: [
          { es: "Tout a été emballé ?", en: "Has everything been packed?" },
          { es: "Les cartons ont été fermés et étiquetés.", en: "The boxes have been sealed and labelled." },
          { es: "Désolé, on a cassé un vase.", en: "Sorry, we've broken a vase." },
          { es: "Le piano sera livré demain matin.", en: "The piano will be delivered tomorrow morning." },
          { es: "C'est le vase qui m'avait été offert par ma mère !", en: "It's the vase my mother had given me!" },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "Has everything been packed?",
            answer: "Tout a été emballé ?",
            altAnswers: ["Est-ce que tout a été emballé ?", "Tout est emballé ?", "On a tout emballé ?"],
            explanation: "\"Tout\" is masculine singular: \"emballé\".",
          },
          {
            type: "multiple-choice",
            question: "The mover admits his team broke something. What does he say?",
            options: ["Désolé, on a cassé un vase.", "Désolé, un vase a cassé par nous.", "Désolé, on a été cassé un vase.", "Désolé, un vase est cassé par on."],
            correctIndex: 0,
            explanation: "\"On a cassé\": natural spoken active with on = we.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "The boxes have been labelled.",
        answer: "Les cartons ont été étiquetés.",
        altAnswers: ["On a étiqueté les cartons."],
        explanation: "\"Étiquetés\" agrees with les cartons.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "The piano will be delivered tomorrow.",
        answer: "Le piano sera livré demain.",
        explanation: "Future passive.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "The fridge hasn't been emptied!",
        answer: "Le frigo n'a pas été vidé !",
        altAnswers: ["Le réfrigérateur n'a pas été vidé !", "On n'a pas vidé le frigo !"],
        explanation: "\"Ne... pas\" around \"a\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "We were told the lorry would be late.",
        answer: "On nous a dit que le camion serait en retard.",
        explanation: "\"On nous a dit\" + conditional for future in the past.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "The books were put in the small boxes.",
        answer: "Les livres ont été mis dans les petits cartons.",
        altAnswers: ["On a mis les livres dans les petits cartons."],
        explanation: "Irregular participle \"mis\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "The keys will be handed over at noon.",
        answer: "Les clés seront remises à midi.",
        explanation: "\"Remettre\" → \"remises\" (feminine plural).",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "It's the vase my mother had given me.",
        answer: "C'est le vase que ma mère m'avait offert.",
        altAnswers: ["C'est le vase qui m'avait été offert par ma mère.", "C'est le vase que ma mère m'avait donné."],
        explanation: "Active with \"que\" is simplest; the passive keeps the vase as subject.",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "[We've broken] a glass, sorry!",
        sentence: "___ un verre, désolé !",
        answer: "On a cassé",
        explanation: "\"On a cassé\" = we've broken.",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "The furniture [had been wrapped] in blankets.",
        sentence: "Les meubles ___ dans des couvertures.",
        answer: "avaient été emballés",
        altAnswers: ["avaient été enveloppés"],
        explanation: "Plus-que-parfait passive.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: The boxes have been sealed and labelled.",
        words: ["Les", "cartons", "ont été", "fermés", "et", "étiquetés."],
        translation: "The boxes have been sealed and labelled.",
        explanation: "One \"ont été\" for both participles.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "Has the sofa been loaded?",
        answer: "Le canapé a été chargé ?",
        altAnswers: ["Est-ce que le canapé a été chargé ?", "On a chargé le canapé ?"],
        explanation: "Passé composé passive in a question.",
      },
      {
        type: "multiple-choice",
        question: "What does « Les cartons seront déchargés au deuxième étage » mean?",
        options: ["The boxes will be unloaded on the second floor.", "The boxes were unloaded on the second floor.", "The boxes are being loaded on the second floor.", "The boxes had been unloaded on the second floor."],
        correctIndex: 0,
        explanation: "\"Seront déchargés\": future passive.",
      },
      {
        type: "listen-choose",
        audio: "Désolé, on a cassé un vase.",
        question: "What does it mean?",
        options: ["Sorry, we've broken a vase.", "Sorry, a vase has been bought.", "Sorry, someone has hidden a vase.", "Sorry, the vase was already broken."],
        correctIndex: 0,
        explanation: "\"On a cassé\" = we've broken.",
      },
      {
        type: "speak",
        text: "Tout a été emballé ?",
        prompt: "Say it in French: Has everything been packed?",
        explanation: "Passé composé passive with tout.",
      },
    ],
  },
  {
    slug: "b1-passive-extra-7",
    level: "FR-B1",
    number: 7,
    optional: true,
    title: "Extra Practice: Your Recipe with On",
    summary: "Talk about how a dish is made in your family with on: on coupe, on ajoute, on laisse cuire...",
    duration: "12 min",
    sections: [
      {
        heading: "Recap: recipes with on",
        body: [
          "When you describe how something is usually done, \"on\" + present is the natural French: \"Chez nous, on fait la ratatouille comme ça : on coupe les légumes, on les fait revenir, on ajoute les tomates et on laisse cuire une heure.\"",
          "Useful verbs: \"couper\" (to cut), \"éplucher\" (to peel), \"faire revenir\" (to brown), \"ajouter\", \"mélanger\" (to mix), \"verser\" (to pour), \"laisser cuire\" (to leave to cook), \"servir\". A finished state can use être + participle: \"Quand c'est cuit, on sert.\"",
        ],
        examples: [
          { es: "D'abord, on épluche les pommes de terre.", en: "First, you peel the potatoes." },
          { es: "On coupe les oignons en petits morceaux.", en: "You cut the onions into small pieces." },
          { es: "On les fait revenir dans un peu d'huile.", en: "You brown them in a little oil." },
          { es: "On ajoute la crème et on mélange bien.", en: "You add the cream and mix well." },
          { es: "Quand c'est cuit, on sert tout de suite.", en: "When it's cooked, you serve it straight away." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French using on.",
            source: "First, you peel the apples.",
            answer: "D'abord, on épluche les pommes.",
            altAnswers: ["D'abord on épluche les pommes.", "Tout d'abord, on épluche les pommes."],
            explanation: "General you in instructions → \"on\".",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French using on.",
            source: "You add the sugar and mix.",
            answer: "On ajoute le sucre et on mélange.",
            explanation: "Repeat \"on\" before each verb.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French using on.",
        source: "In my family, we make crêpes every Sunday.",
        answer: "Dans ma famille, on fait des crêpes tous les dimanches.",
        altAnswers: ["Chez nous, on fait des crêpes tous les dimanches.", "Dans ma famille, on fait des crêpes chaque dimanche."],
        explanation: "\"On\" = nous for a family habit.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French using on.",
        source: "You cut the vegetables into cubes.",
        answer: "On coupe les légumes en cubes.",
        altAnswers: ["On coupe les légumes en dés."],
        explanation: "\"Couper en\" + shape.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French using on.",
        source: "You pour the batter into the pan.",
        answer: "On verse la pâte dans la poêle.",
        explanation: "\"La pâte\" = batter or dough.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French using on.",
        source: "You leave it to cook for twenty minutes.",
        answer: "On laisse cuire vingt minutes.",
        altAnswers: ["On laisse cuire pendant vingt minutes.", "On le laisse cuire vingt minutes.", "On la laisse cuire vingt minutes."],
        explanation: "\"Laisser cuire\" = to leave to cook.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French using on.",
        source: "You brown the onions in butter.",
        answer: "On fait revenir les oignons dans du beurre.",
        altAnswers: ["On fait dorer les oignons dans du beurre."],
        explanation: "\"Faire revenir\" = to brown, to fry gently.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French using on.",
        source: "My grandmother taught me this recipe.",
        answer: "Ma grand-mère m'a appris cette recette.",
        explanation: "Active with a named subject: the most natural choice.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "This dish is served with rice.",
        answer: "Ce plat est servi avec du riz.",
        altAnswers: ["On sert ce plat avec du riz."],
        explanation: "Present passive or \"on sert\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "[You mix] the eggs and the flour.",
        sentence: "___ les œufs et la farine.",
        answer: "On mélange",
        explanation: "\"On mélange\": general instructions.",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "When it's cooked, [you serve it] hot.",
        sentence: "Quand c'est cuit, ___ chaud.",
        answer: "on le sert",
        altAnswers: ["on la sert", "on sert"],
        explanation: "\"On le sert\": object pronoun before the verb.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: You add a little salt at the end.",
        words: ["On", "ajoute", "un peu", "de", "sel", "à la fin."],
        translation: "You add a little salt at the end.",
        explanation: "\"Un peu de\" + noun.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French using on.",
        source: "We always eat it with friends.",
        answer: "On le mange toujours avec des amis.",
        altAnswers: ["On la mange toujours avec des amis.", "On le mange toujours entre amis.", "On la mange toujours entre amis."],
        explanation: "\"On\" = we; \"toujours\" after the verb.",
      },
      {
        type: "multiple-choice",
        question: "Which is the most natural way to say 'You peel the carrots' in a recipe you're explaining aloud?",
        options: ["On épluche les carottes.", "Les carottes sont épluchées par vous.", "Les carottes ont été épluchées.", "On a été épluché les carottes."],
        correctIndex: 0,
        explanation: "\"On\" + present for spoken instructions.",
      },
      {
        type: "dictation",
        audio: "On coupe les oignons en petits morceaux.",
        explanation: "\"On coupe\": singular verb with on.",
      },
      {
        type: "speak",
        text: "Chez nous, on fait la ratatouille avec beaucoup d'ail.",
        prompt: "Say it in French: In our family, we make ratatouille with lots of garlic.",
        explanation: "\"Chez nous, on\" for a family habit.",
      },
    ],
  },
  {
    slug: "b1-passive-extra-8",
    level: "FR-B1",
    number: 8,
    optional: true,
    title: "Extra Practice: The Passive in All Tenses",
    summary: "A quick round of passives in the present, passé composé, imparfait, future and plus-que-parfait, with no hints.",
    duration: "12 min",
    sections: [
      {
        heading: "Recap: the five tenses of être",
        body: [
          "\"Est\" (present), \"a été\" (passé composé), \"était\" (imparfait), \"sera\" (future), \"avait été\" (plus-que-parfait), plus \"serait\" (conditional). The participle agrees with the subject in every one.",
          "Choose the tense from the English and the time words: is/are + done → present; was done (event) → \"a été\"; was done (habit, description) → \"était\"; will be → \"sera\"; had been → \"avait été\".",
        ],
        examples: [
          { es: "Les colis sont triés la nuit.", en: "Parcels are sorted at night." },
          { es: "La lettre a été envoyée lundi.", en: "The letter was sent on Monday." },
          { es: "Le village était protégé par des remparts.", en: "The village was protected by ramparts." },
          { es: "La loi sera votée en juin.", en: "The law will be voted on in June." },
          { es: "La salle avait été louée pour la soirée.", en: "The hall had been hired for the evening." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "The law will be voted on in June.",
            answer: "La loi sera votée en juin.",
            explanation: "Future passive; \"votée\" agrees with la loi.",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "The hall had been hired.",
            answer: "La salle avait été louée.",
            explanation: "Plus-que-parfait passive.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "Parcels are sorted at night.",
        answer: "Les colis sont triés la nuit.",
        explanation: "Present passive for a routine.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "The concert was recorded.",
        answer: "Le concert a été enregistré.",
        explanation: "One event → \"a été\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "The village was protected by ramparts.",
        answer: "Le village était protégé par des remparts.",
        explanation: "A past description → \"était\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "The new line will be opened in 2030.",
        answer: "La nouvelle ligne sera inaugurée en 2030.",
        altAnswers: ["La nouvelle ligne sera ouverte en 2030."],
        explanation: "Future passive.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "The keys had been forgotten on the table.",
        answer: "Les clés avaient été oubliées sur la table.",
        explanation: "Plus-que-parfait; \"oubliées\" agrees.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "The shops are closed on Sundays.",
        answer: "Les magasins sont fermés le dimanche.",
        explanation: "A state / habit → present.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "Three houses were destroyed by the storm.",
        answer: "Trois maisons ont été détruites par la tempête.",
        explanation: "\"Détruites\": feminine plural, audible t.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "The bread used to be baked in a wood oven.",
        answer: "Le pain était cuit dans un four à bois.",
        explanation: "Past habit → \"était cuit\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "The winners [will be announced] tonight.",
        sentence: "Les gagnants ___ ce soir.",
        answer: "seront annoncés",
        explanation: "Future: \"seront annoncés\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "The project [would be finished] faster with more money.",
        sentence: "Le projet ___ plus vite avec plus d'argent.",
        answer: "serait terminé",
        altAnswers: ["serait fini"],
        explanation: "Conditional of être: \"serait\".",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: The concert had been cancelled.",
        words: ["Le", "concert", "avait", "été", "annulé."],
        translation: "The concert had been cancelled.",
        explanation: "\"Avait été annulé\".",
      },
      {
        type: "multiple-choice",
        question: "Which tense fits « Quand je suis arrivé, la porte ___ déjà ___ »?",
        options: ["avait / été fermée", "a / été fermée", "sera / fermée", "est / fermée"],
        correctIndex: 0,
        explanation: "Before another past event → plus-que-parfait: \"avait déjà été fermée\".",
      },
      {
        type: "listen-choose",
        audio: "La salle avait été louée pour la soirée.",
        question: "What does it mean?",
        options: ["The hall had been hired for the evening.", "The hall will be hired for the evening.", "The hall was being hired for the evening.", "The hall is hired every evening."],
        correctIndex: 0,
        explanation: "\"Avait été\": plus-que-parfait.",
      },
      {
        type: "speak",
        text: "Trois maisons ont été détruites par la tempête.",
        prompt: "Say it in French: Three houses were destroyed by the storm.",
        tip: "Pronounce the t of détruites.",
        explanation: "Passé composé passive with feminine plural agreement.",
      },
    ],
  },
  {
    slug: "b1-passive-extra-9",
    level: "FR-B1",
    number: 9,
    optional: true,
    title: "Extra Practice: Fix the Paragraph, Signs with Errors",
    summary: "Correct notices and adverts written by a careless sign-maker: missing agreements, wrong auxiliaries and English-style passives.",
    duration: "12 min",
    sections: [
      {
        heading: "Recap: the notices to fix",
        body: [
          "A shop owner in Montpellier made these signs: *Magasin fermé le lundi et les jours férié.* *Les chiens ne sont pas admis, sauf les chiens guide.* *Les retours sont accepté sous 30 jours.* *Les clients sont demandés de ne pas toucher.* *La caisse sera fermée à 19 h, merci de votre compréhension.*",
          "The errors: \"fériés\" (plural agreement with les jours), \"chiens guides\", \"acceptés\" (agreement with les retours), and \"Les clients sont demandés\" is an English-style passive: write \"On demande aux clients de ne pas toucher\" or \"Prière de ne pas toucher\". The last sign is correct.",
        ],
        examples: [
          { es: "Magasin fermé le lundi et les jours fériés.", en: "Shop closed on Mondays and public holidays." },
          { es: "Les chiens ne sont pas admis, sauf les chiens guides.", en: "No dogs allowed, except guide dogs." },
          { es: "Les retours sont acceptés sous 30 jours.", en: "Returns are accepted within 30 days." },
          { es: "On demande aux clients de ne pas toucher.", en: "Customers are asked not to touch." },
          { es: "La caisse sera fermée à 19 heures.", en: "The till will close at 7 pm." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Fix the sign and translate. Wrong version: « Les retours sont accepté sous 30 jours. »",
            source: "Returns are accepted within 30 days.",
            answer: "Les retours sont acceptés sous 30 jours.",
            altAnswers: ["Les retours sont acceptés sous trente jours."],
            explanation: "Agreement with les retours: \"acceptés\".",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Fix the sign and translate. Wrong version: « Les clients sont demandés de ne pas toucher. »",
            source: "Customers are asked not to touch.",
            answer: "On demande aux clients de ne pas toucher.",
            altAnswers: ["Prière de ne pas toucher.", "Il est demandé aux clients de ne pas toucher."],
            explanation: "\"Demander à\": the person can't be the passive subject.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Fix the sign and translate. Wrong version: « Magasin fermé le lundi et les jours férié. »",
        source: "Shop closed on Mondays and public holidays.",
        answer: "Magasin fermé le lundi et les jours fériés.",
        explanation: "\"Fériés\" agrees with les jours.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Fix the sign and translate. Wrong version: « Les vélos sont interdit dans la cour. »",
        source: "Bikes are not allowed in the courtyard.",
        answer: "Les vélos sont interdits dans la cour.",
        explanation: "Plural agreement: \"interdits\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Fix the sign and translate. Wrong version: « Piscine fermé pour travaux. »",
        source: "Pool closed for renovation.",
        answer: "Piscine fermée pour travaux.",
        explanation: "\"Piscine\" is feminine: \"fermée\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Fix the sign and translate. Wrong version: « Les visiteurs sont dits de rester sur le chemin. »",
        source: "Visitors are asked to stay on the path.",
        answer: "On demande aux visiteurs de rester sur le chemin.",
        altAnswers: ["Prière de rester sur le chemin.", "Les visiteurs sont priés de rester sur le chemin.", "Merci de rester sur le chemin."],
        explanation: "\"Dire à\" has no passive. \"Être prié de\" (to be requested to) is a fixed formal exception.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Fix the ad and translate. Wrong version: « Appartement rénové en 2024, cuisine équipé. »",
        source: "Flat renovated in 2024, fitted kitchen.",
        answer: "Appartement rénové en 2024, cuisine équipée.",
        explanation: "\"Cuisine\" is feminine: \"équipée\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Fix the sign and translate. Wrong version: « Cette porte doit être fermé. »",
        source: "This door must be kept shut.",
        answer: "Cette porte doit être fermée.",
        altAnswers: ["Cette porte doit rester fermée."],
        explanation: "Passive infinitive with agreement: \"être fermée\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Fix the ad and translate. Wrong version: « Voiture à vendre, révisé le mois dernier. »",
        source: "Car for sale, serviced last month.",
        answer: "Voiture à vendre, révisée le mois dernier.",
        explanation: "\"Révisée\" agrees with voiture.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Fix the sign and translate. Wrong version: « Les enfants doivent être accompagné d'un adulte. »",
        source: "Children must be accompanied by an adult.",
        answer: "Les enfants doivent être accompagnés d'un adulte.",
        altAnswers: ["Les enfants doivent être accompagnés par un adulte."],
        explanation: "Plural agreement; \"accompagner\" describing a state takes \"de\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "Smoking [is forbidden] in the building.",
        sentence: "Il ___ de fumer dans le bâtiment.",
        answer: "est interdit",
        explanation: "Impersonal \"il est interdit de\" + infinitive.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: Staff only, access forbidden to the public.",
        words: ["Réservé", "au", "personnel,", "accès", "interdit", "au public."],
        translation: "Staff only, access forbidden to the public.",
        explanation: "Participles as adjectives: \"réservé\", \"interdit\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Write the French notice.",
        source: "The car park will be closed on Saturday.",
        answer: "Le parking sera fermé samedi.",
        altAnswers: ["Le parking sera fermé ce samedi."],
        explanation: "Future passive.",
      },
      {
        type: "multiple-choice",
        question: "Which notice is correct?",
        options: ["Les animaux ne sont pas acceptés.", "Les animaux ne sont pas accepté.", "Les animaux n'ont pas été acceptés pas.", "Les animaux ne sont pas acceptées."],
        correctIndex: 0,
        explanation: "\"Animaux\" is masculine plural: \"acceptés\".",
      },
      {
        type: "listen-choose",
        audio: "Les retours sont acceptés sous trente jours.",
        question: "What does it mean?",
        options: ["Returns are accepted within 30 days.", "Returns were accepted 30 days ago.", "No returns after 3 days.", "Returns will be refunded in 30 days."],
        correctIndex: 0,
        explanation: "\"Sous trente jours\" = within thirty days.",
      },
      {
        type: "speak",
        text: "On demande aux clients de ne pas toucher.",
        prompt: "Say it in French: Customers are asked not to touch.",
        explanation: "\"On demande à\" + person + \"de\" + infinitive.",
      },
    ],
  },
  {
    slug: "b1-passive-extra-10",
    level: "FR-B1",
    number: 10,
    optional: true,
    title: "Extra Practice: Dictation, How We Live in My Town",
    summary: "Write down and translate a description of a town's way of life with on and passives.",
    duration: "12 min",
    sections: [
      {
        heading: "Recap: the text",
        body: [
          "Inès describes Annecy: \"Ici, on vit dehors dès qu'il fait beau. Le lac est entouré de montagnes, et on s'y baigne de juin à septembre. Le centre est interdit aux voitures le week-end. Le marché a été rénové l'an dernier, et on y trouve les meilleurs fromages de la région. On dit que c'est la Venise des Alpes.\"",
          "When writing it down, check: \"on\" + singular verb, agreement after être (\"entouré\" with le lac, \"interdit\" with le centre, \"rénové\" with le marché), and \"y\" for the place.",
        ],
        examples: [
          { es: "Ici, on vit dehors dès qu'il fait beau.", en: "Here, people live outdoors as soon as the weather's nice." },
          { es: "Le lac est entouré de montagnes.", en: "The lake is surrounded by mountains." },
          { es: "Le centre est interdit aux voitures le week-end.", en: "The centre is closed to cars at weekends." },
          { es: "Le marché a été rénové l'an dernier.", en: "The market was renovated last year." },
          { es: "On dit que c'est la Venise des Alpes.", en: "They say it's the Venice of the Alps." },
        ],
        checkpoint: [
          {
            type: "dictation",
            audio: "Le lac est entouré de montagnes.",
            explanation: "\"Entouré de\": a state takes de.",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "Here, people live outdoors.",
            answer: "Ici, on vit dehors.",
            altAnswers: ["Ici, les gens vivent dehors."],
            explanation: "\"On vit\": general people.",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "The market was renovated last year.",
            answer: "Le marché a été rénové l'an dernier.",
            altAnswers: ["Le marché a été rénové l'année dernière.", "On a rénové le marché l'an dernier.", "On a rénové le marché l'année dernière."],
            explanation: "Passé composé passive.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "dictation",
        audio: "Ici, on vit dehors dès qu'il fait beau.",
        explanation: "\"On vit\": singular verb.",
      },
      {
        type: "dictation",
        audio: "Le centre est interdit aux voitures le week-end.",
        explanation: "\"Interdit\" agrees with le centre (masculine).",
      },
      {
        type: "dictation",
        audio: "On dit que c'est la Venise des Alpes.",
        explanation: "\"On dit que\": they say that.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "People swim in the lake in summer.",
        answer: "On se baigne dans le lac en été.",
        altAnswers: ["On nage dans le lac en été.", "L'été, on se baigne dans le lac."],
        explanation: "\"On se baigne\" for people in general.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "The old town is surrounded by canals.",
        answer: "La vieille ville est entourée de canaux.",
        explanation: "A state → \"de\"; \"entourée\" agrees with la vieille ville.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "You can find the best cheeses there.",
        answer: "On y trouve les meilleurs fromages.",
        explanation: "\"On y trouve\": y = there.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "The castle was built in the twelfth century.",
        answer: "Le château a été construit au douzième siècle.",
        altAnswers: ["Le château a été construit au XIIe siècle.", "Le château a été bâti au douzième siècle.", "Le château a été bâti au XIIe siècle."],
        explanation: "Passé composé passive for a historical event.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "The streets are decorated at Christmas.",
        answer: "Les rues sont décorées à Noël.",
        altAnswers: ["On décore les rues à Noël."],
        explanation: "Present passive for a regular event.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "We often go to the market on Saturdays.",
        answer: "On va souvent au marché le samedi.",
        altAnswers: ["Nous allons souvent au marché le samedi."],
        explanation: "\"On\" = we; \"le samedi\" for a habit.",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "A new bridge [will be built] next year.",
        sentence: "Un nouveau pont ___ l'année prochaine.",
        answer: "sera construit",
        explanation: "Future passive.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: The town is known for its lake.",
        words: ["La", "ville", "est", "connue", "pour", "son", "lac."],
        translation: "The town is known for its lake.",
        explanation: "\"Connue pour\" = known for.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "They say it's very expensive.",
        answer: "On dit que c'est très cher.",
        explanation: "General they → \"on dit que\".",
      },
      {
        type: "listen-choose",
        audio: "Le marché a été rénové l'an dernier.",
        question: "What does it mean?",
        options: ["The market was renovated last year.", "The market is renovated every year.", "The market will be renovated next year.", "The market had been renovated the year before."],
        correctIndex: 0,
        explanation: "\"A été rénové\" + \"l'an dernier\".",
      },
      {
        type: "speak",
        text: "Ici, on vit dehors dès qu'il fait beau.",
        prompt: "Say it in French: Here, people live outdoors as soon as the weather's nice.",
        explanation: "\"On vit\" + \"dès que\" + present.",
      },
    ],
  },
  {
    slug: "b1-passive-extra-11",
    level: "FR-B1",
    number: 11,
    optional: true,
    title: "Extra Practice: The Passive in Every Tense",
    summary: "Mixed practice in short news items: passives in every tense, with and without an agent.",
    duration: "12 min",
    sections: [
      {
        heading: "Recap: news headlines and briefs",
        body: [
          "News briefs (\"les brèves\") pack passives into a few lines: \"Un tableau de Monet a été vendu 30 millions d'euros. Il avait été découvert dans un grenier. Il sera exposé au musée d'Orsay.\"",
          "Each sentence picks its tense from the timeline: the main event (\"a été vendu\"), something earlier (\"avait été découvert\"), something to come (\"sera exposé\"), the background (\"était caché\").",
        ],
        examples: [
          { es: "Un tableau de Monet a été vendu 30 millions d'euros.", en: "A Monet painting was sold for 30 million euros." },
          { es: "Il avait été découvert dans un grenier en Bretagne.", en: "It had been discovered in an attic in Brittany." },
          { es: "Il était caché derrière une armoire depuis des années.", en: "It had been hidden behind a wardrobe for years." },
          { es: "Il sera exposé au musée d'Orsay dès le mois prochain.", en: "It will be exhibited at the Orsay museum from next month." },
          { es: "Les propriétaires ont été contactés par un expert.", en: "The owners were contacted by an expert." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "The painting had been discovered in an attic.",
            answer: "Le tableau avait été découvert dans un grenier.",
            explanation: "Earlier event → plus-que-parfait passive.",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "It will be exhibited in Paris.",
            answer: "Il sera exposé à Paris.",
            altAnswers: ["Elle sera exposée à Paris."],
            explanation: "Future passive.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "A painting was sold for ten million euros.",
        answer: "Un tableau a été vendu dix millions d'euros.",
        altAnswers: ["Un tableau a été vendu pour dix millions d'euros.", "Une peinture a été vendue dix millions d'euros."],
        explanation: "Passé composé passive; price follows directly.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "The owners were contacted by an expert.",
        answer: "Les propriétaires ont été contactés par un expert.",
        altAnswers: ["Les propriétaires ont été contactés par une experte."],
        explanation: "Plural agreement + par.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "The festival will be cancelled if it rains.",
        answer: "Le festival sera annulé s'il pleut.",
        explanation: "Si + present, main clause in the future passive.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "The bridge had been closed for two years.",
        answer: "Le pont avait été fermé pendant deux ans.",
        altAnswers: ["Le pont était fermé depuis deux ans."],
        explanation: "Plus-que-parfait passive with \"pendant\"; or a state with \"depuis\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "A new president has been elected.",
        answer: "Un nouveau président a été élu.",
        altAnswers: ["Une nouvelle présidente a été élue."],
        explanation: "Irregular participle \"élu\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "The match will be broadcast live.",
        answer: "Le match sera diffusé en direct.",
        altAnswers: ["Le match sera retransmis en direct."],
        explanation: "\"Diffuser\" / \"retransmettre\" = to broadcast.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "In the past, the castle was used as a prison.",
        answer: "Autrefois, le château était utilisé comme prison.",
        altAnswers: ["Avant, le château était utilisé comme prison.", "Autrefois, le château servait de prison."],
        explanation: "Past description → imparfait passive.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "Two climbers were rescued yesterday.",
        answer: "Deux alpinistes ont été secourus hier.",
        altAnswers: ["Deux grimpeurs ont été secourus hier."],
        explanation: "\"Secourus\": plural agreement.",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "The new metro line [will be opened] in 2028.",
        sentence: "La nouvelle ligne de métro ___ en 2028.",
        answer: "sera inaugurée",
        altAnswers: ["sera ouverte", "sera mise en service"],
        explanation: "Future passive with feminine agreement.",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "The works [had been finished] before the deadline.",
        sentence: "Les travaux ___ avant la date limite.",
        answer: "avaient été terminés",
        altAnswers: ["avaient été finis", "avaient été achevés"],
        explanation: "Plus-que-parfait passive.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: The prize will be awarded in Cannes.",
        words: ["Le", "prix", "sera", "décerné", "à", "Cannes."],
        translation: "The prize will be awarded in Cannes.",
        explanation: "\"Décerner\" = to award (a prize).",
      },
      {
        type: "multiple-choice",
        question: "What does « Le suspect avait été vu près de la banque » mean?",
        options: ["The suspect had been seen near the bank.", "The suspect has been seen near the bank.", "The suspect saw someone near the bank.", "The suspect will be seen near the bank."],
        correctIndex: 0,
        explanation: "\"Avait été vu\": plus-que-parfait passive.",
      },
      {
        type: "dictation",
        audio: "Il sera exposé au musée d'Orsay.",
        explanation: "\"Sera exposé\": future passive.",
      },
      {
        type: "speak",
        text: "Un tableau de Monet a été vendu trente millions d'euros.",
        prompt: "Say it in French: A Monet painting was sold for thirty million euros.",
        explanation: "Passé composé passive.",
      },
    ],
  },
  {
    slug: "b1-passive-extra-12",
    level: "FR-B1",
    number: 12,
    optional: true,
    title: "Extra Practice: Par or De?",
    summary: "A quick round on the agent after the passive: par for actions, de for states and feelings.",
    duration: "11 min",
    sections: [
      {
        heading: "Recap: action vs state",
        body: [
          "\"Par\" introduces the agent of a real action: \"Il a été mordu par un chien\" (bitten by a dog), \"La lettre a été écrite par mon avocat\".",
          "\"De\" goes with states and feelings: \"aimé de\", \"détesté de\", \"respecté de\", \"connu de\", \"entouré de\", \"couvert de\", \"rempli de\", \"accompagné de\", \"suivi de\" (followed by, in a list or programme). If English says with or of (covered with, full of), it's almost always \"de\".",
        ],
        examples: [
          { es: "Il a été mordu par un chien.", en: "He was bitten by a dog." },
          { es: "Ce chanteur est connu de tous les Français.", en: "This singer is known to everyone in France." },
          { es: "Le sol était couvert de feuilles.", en: "The ground was covered with leaves." },
          { es: "Le dîner sera suivi d'un concert.", en: "Dinner will be followed by a concert." },
          { es: "La maison a été détruite par un incendie.", en: "The house was destroyed by a fire." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "The ground was covered with snow.",
            answer: "Le sol était couvert de neige.",
            explanation: "A state → \"de\".",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "He was bitten by a dog.",
            answer: "Il a été mordu par un chien.",
            explanation: "An action → \"par\".",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "Dinner will be followed by a show.",
        answer: "Le dîner sera suivi d'un spectacle.",
        explanation: "In a programme, \"suivi de\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "This writer is known to everyone.",
        answer: "Cet écrivain est connu de tous.",
        altAnswers: ["Cet écrivain est connu de tout le monde.", "Cette écrivaine est connue de tous.", "Cette écrivaine est connue de tout le monde."],
        explanation: "\"Connu de\" for a state.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "The house was destroyed by a fire.",
        answer: "La maison a été détruite par un incendie.",
        explanation: "An action → \"par\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "The glass was full of water.",
        answer: "Le verre était rempli d'eau.",
        altAnswers: ["Le verre était plein d'eau."],
        explanation: "A state → \"de\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "The minister was accompanied by his wife.",
        answer: "Le ministre était accompagné de sa femme.",
        altAnswers: ["Le ministre était accompagné par sa femme.", "Le ministre était accompagné de son épouse."],
        explanation: "\"Accompagné de\" is usual for a state; \"par\" also possible.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "The project was approved by the board.",
        answer: "Le projet a été approuvé par le conseil.",
        explanation: "An action → \"par\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "She is admired by her students.",
        answer: "Elle est admirée de ses élèves.",
        altAnswers: ["Elle est admirée par ses élèves.", "Elle est admirée de ses étudiants.", "Elle est admirée par ses étudiants."],
        explanation: "Feelings → \"de\" (par is also accepted).",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "The wall is covered with posters.",
        answer: "Le mur est couvert d'affiches.",
        explanation: "\"Couvert de\" → \"d'affiches\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "The castle is surrounded [by] a park.",
        sentence: "Le château est entouré ___ parc.",
        answer: "d'un",
        explanation: "A state → \"de\": \"entouré d'un parc\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "The thief was caught [by] a passer-by.",
        sentence: "Le voleur a été attrapé ___ un passant.",
        answer: "par",
        explanation: "A real action → \"par\".",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: The street was full of tourists.",
        words: ["La", "rue", "était", "remplie", "de", "touristes."],
        translation: "The street was full of tourists.",
        explanation: "\"Remplie de\" for a state.",
      },
      {
        type: "multiple-choice",
        question: "Which preposition fits « Ce professeur est aimé ___ tous » ?",
        options: ["de", "par le", "à", "avec"],
        correctIndex: 0,
        explanation: "Feelings → \"de\": \"aimé de tous\".",
      },
      {
        type: "listen-choose",
        audio: "Le dîner sera suivi d'un concert.",
        question: "What does it mean?",
        options: ["Dinner will be followed by a concert.", "Dinner was followed by a concert.", "The concert follows dinner every night.", "A concert will be held during dinner."],
        correctIndex: 0,
        explanation: "\"Sera suivi de\": will be followed by.",
      },
      {
        type: "speak",
        text: "Le sol était couvert de feuilles.",
        prompt: "Say it in French: The ground was covered with leaves.",
        explanation: "\"Couvert de\" for a state.",
      },
    ],
  },
  {
    slug: "b1-passive-extra-13",
    level: "FR-B1",
    number: 13,
    optional: true,
    title: "Extra Practice: I Was Given, I Was Told",
    summary: "Fix a paragraph full of impossible English-style passives by turning them into on sentences.",
    duration: "12 min",
    sections: [
      {
        heading: "Recap: the paragraph to fix",
        body: [
          "Sam wrote about his first day as an intern in Lyon: *J'ai été donné un badge et j'ai été montré mon bureau. J'ai été dit que la réunion était à 10 h. Ensuite, j'ai été demandé de préparer une présentation. À midi, j'ai été offert un café par mon chef.*",
          "Every passive here comes from a verb with \"à\" + person, so all are impossible in French. Fixed: \"On m'a donné un badge et on m'a montré mon bureau. On m'a dit que la réunion était à 10 h. Ensuite, on m'a demandé de préparer une présentation. À midi, mon chef m'a offert un café.\" With a named agent (mon chef), use the active.",
        ],
        examples: [
          { es: "On m'a donné un badge.", en: "I was given a badge." },
          { es: "On m'a montré mon bureau.", en: "I was shown my desk." },
          { es: "On m'a dit que la réunion était à 10 heures.", en: "I was told the meeting was at 10." },
          { es: "On m'a demandé de préparer une présentation.", en: "I was asked to prepare a presentation." },
          { es: "Mon chef m'a offert un café.", en: "I was bought a coffee by my boss." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Fix Sam's sentence: « J'ai été donné un badge. »",
            source: "I was given a badge.",
            answer: "On m'a donné un badge.",
            explanation: "\"Donner à\" → \"on m'a donné\".",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Fix Sam's sentence: « J'ai été offert un café par mon chef. »",
            source: "My boss bought me a coffee.",
            answer: "Mon chef m'a offert un café.",
            altAnswers: ["Ma cheffe m'a offert un café."],
            explanation: "A named agent → simply use the active.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Fix the sentence: « J'ai été montré mon bureau. »",
        source: "I was shown my desk.",
        answer: "On m'a montré mon bureau.",
        explanation: "\"Montrer à\" → \"on m'a montré\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Fix the sentence: « J'ai été dit que la réunion était à 10 h. »",
        source: "I was told the meeting was at 10.",
        answer: "On m'a dit que la réunion était à 10 heures.",
        altAnswers: ["On m'a dit que la réunion était à 10 h.", "On m'a dit que la réunion était à dix heures."],
        explanation: "\"Dire à\" → \"on m'a dit\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Fix the sentence: « J'ai été demandé de préparer une présentation. »",
        source: "I was asked to prepare a presentation.",
        answer: "On m'a demandé de préparer une présentation.",
        explanation: "\"Demander à quelqu'un de\" → \"on m'a demandé de\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "We were sent the wrong documents.",
        answer: "On nous a envoyé les mauvais documents.",
        explanation: "\"Envoyer à\" → \"on nous a envoyé\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "She was promised a promotion.",
        answer: "On lui a promis une promotion.",
        explanation: "\"Promettre à\" → \"on lui a promis\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "They were taught French at school.",
        answer: "On leur a appris le français à l'école.",
        altAnswers: ["On leur a enseigné le français à l'école."],
        explanation: "\"Apprendre quelque chose à quelqu'un\" → \"on leur a appris\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "I was lent a laptop.",
        answer: "On m'a prêté un ordinateur portable.",
        altAnswers: ["On m'a prêté un portable.", "On m'a prêté un ordinateur."],
        explanation: "\"Prêter à\" → \"on m'a prêté\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "Were you told about the strike? (to a friend)",
        answer: "On t'a parlé de la grève ?",
        altAnswers: ["On t'a dit pour la grève ?", "Est-ce qu'on t'a parlé de la grève ?", "On t'a prévenu pour la grève ?", "On t'a prévenue pour la grève ?"],
        explanation: "\"Parler de quelque chose à quelqu'un\" → \"on t'a parlé de\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "[He was asked] for his badge at the entrance.",
        sentence: "___ son badge à l'entrée.",
        answer: "On lui a demandé",
        explanation: "\"Demander quelque chose à quelqu'un\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "[I was invited] to the team lunch.",
        sentence: "___ au déjeuner de l'équipe.",
        answer: "On m'a invité",
        altAnswers: ["On m'a invitée", "J'ai été invité", "J'ai été invitée"],
        explanation: "\"Inviter quelqu'un\" has a direct object: both \"on\" and the passive work.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: We were given a tour of the building.",
        words: ["On", "nous", "a", "fait", "visiter", "le bâtiment."],
        translation: "We were given a tour of the building.",
        explanation: "\"Faire visiter quelque chose à quelqu'un\" = to show someone round.",
      },
      {
        type: "multiple-choice",
        question: "Which sentence is correct for 'I was told to come early'?",
        options: ["On m'a dit de venir tôt.", "J'ai été dit de venir tôt.", "On m'a été dit de venir tôt.", "Je suis dit de venir tôt."],
        correctIndex: 0,
        explanation: "Only \"on m'a dit de\" works.",
      },
      {
        type: "listen-choose",
        audio: "On m'a demandé de préparer une présentation.",
        question: "What does it mean?",
        options: ["I was asked to prepare a presentation.", "I asked someone to prepare a presentation.", "We prepared a presentation.", "I was shown a presentation."],
        correctIndex: 0,
        explanation: "\"On m'a demandé de\" = I was asked to.",
      },
      {
        type: "speak",
        text: "On m'a donné un badge et on m'a montré mon bureau.",
        prompt: "Say it in French: I was given a badge and shown my desk.",
        explanation: "Two \"on m'a\" sentences: no passive with donner à or montrer à.",
      },
    ],
  },
  {
    slug: "b1-passive-extra-14",
    level: "FR-B1",
    number: 14,
    optional: true,
    title: "Extra Practice: Passive, On or Active?",
    summary: "Mixed practice choosing the most natural form for each situation: conversation, news report, notice or story.",
    duration: "12 min",
    sections: [
      {
        heading: "Recap: choosing the form",
        body: [
          "Speech, unknown agent: \"on\" (\"On m'a volé mon portable\"). Speech, known agent: active (\"Mon frère a cassé la télé\"). News or formal writing: passive, often without agent (\"Un portable a été volé\"). Notices: participle or passive (\"Fermé\", \"Les chiens ne sont pas admis\"). Indirect person: \"on\" only (\"On m'a dit\").",
          "When in doubt in conversation, use \"on\": it's never wrong and always natural.",
        ],
        examples: [
          { es: "On m'a volé mon portable dans le métro.", en: "My phone got stolen on the metro." },
          { es: "Mon frère a cassé la télé.", en: "My brother broke the TV." },
          { es: "Un portable a été volé dans une voiture.", en: "A phone was stolen from a car." },
          { es: "Les chiens ne sont pas admis.", en: "No dogs allowed." },
          { es: "On nous a dit d'attendre.", en: "We were told to wait." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Say it to a friend: My phone got stolen!",
            source: "My phone got stolen!",
            answer: "On m'a volé mon portable !",
            altAnswers: ["On m'a volé mon téléphone !", "On a volé mon portable !", "Mon portable a été volé !"],
            explanation: "In speech, \"on m'a volé\" is the natural choice.",
          },
          {
            type: "multiple-choice",
            question: "Which version suits a newspaper?",
            options: ["Un portable a été volé dans une voiture.", "On m'a piqué mon portable !", "Ils ont volé un portable, quoi.", "Un portable a volé dans une voiture."],
            correctIndex: 0,
            explanation: "News style: passive without agent.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Say it to a friend: My sister broke my glasses.",
        source: "My sister broke my glasses.",
        answer: "Ma sœur a cassé mes lunettes.",
        explanation: "Known agent in speech → active.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Write it as a news report: A bank was robbed yesterday.",
        source: "A bank was robbed yesterday.",
        answer: "Une banque a été braquée hier.",
        altAnswers: ["Une banque a été cambriolée hier.", "Une banque a été attaquée hier."],
        explanation: "News style: passive without agent.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Say it to a friend: We were told the flight was cancelled.",
        source: "We were told the flight was cancelled.",
        answer: "On nous a dit que le vol était annulé.",
        altAnswers: ["On nous a dit que le vol avait été annulé."],
        explanation: "\"Dire à\" → \"on nous a dit\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Write the notice: The lift is out of order.",
        source: "The lift is out of order.",
        answer: "L'ascenseur est en panne.",
        altAnswers: ["Ascenseur en panne."],
        explanation: "Notice: a simple state.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Write it formally: The museum was designed by Renzo Piano.",
        source: "The museum was designed by Renzo Piano.",
        answer: "Le musée a été conçu par Renzo Piano.",
        altAnswers: ["Le musée a été dessiné par Renzo Piano."],
        explanation: "The building is the topic, so the passive with par fits.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Say it to a friend: They've repainted the station.",
        source: "They've repainted the station.",
        answer: "On a repeint la gare.",
        altAnswers: ["Ils ont repeint la gare."],
        explanation: "Speech, unknown agent → \"on\" or informal \"ils\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "I was offered a job in Lille.",
        answer: "On m'a offert un poste à Lille.",
        altAnswers: ["On m'a proposé un poste à Lille.", "On m'a proposé un travail à Lille.", "On m'a offert un travail à Lille."],
        explanation: "\"Offrir / proposer à\" → \"on m'a\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Write the notice: The park will be closed on Monday.",
        source: "The park will be closed on Monday.",
        answer: "Le parc sera fermé lundi.",
        altAnswers: ["Le parc sera fermé ce lundi."],
        explanation: "Notice: future passive.",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "[Someone has taken] my umbrella!",
        sentence: "___ mon parapluie !",
        answer: "On a pris",
        altAnswers: ["Quelqu'un a pris", "On m'a pris"],
        explanation: "Unknown agent in speech → \"on\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "The suspect [was arrested] last night. (news)",
        sentence: "Le suspect ___ hier soir.",
        answer: "a été arrêté",
        altAnswers: ["a été interpellé"],
        explanation: "News → passive.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: The children were given sweets.",
        words: ["On", "a", "donné", "des", "bonbons", "aux", "enfants."],
        translation: "The children were given sweets.",
        explanation: "\"Donner à\" → \"on a donné... aux enfants\".",
      },
      {
        type: "multiple-choice",
        question: "Which sentence is impossible?",
        options: ["Les enfants ont été donnés des bonbons.", "On a donné des bonbons aux enfants.", "Des bonbons ont été donnés aux enfants.", "La maîtresse a donné des bonbons aux enfants."],
        correctIndex: 0,
        explanation: "The person after \"donner à\" can't become the passive subject.",
      },
      {
        type: "dictation",
        audio: "On m'a volé mon portable dans le métro.",
        explanation: "\"On m'a volé\": the everyday way to report a theft.",
      },
      {
        type: "speak",
        text: "On nous a dit d'attendre.",
        prompt: "Say it in French: We were told to wait.",
        explanation: "\"On nous a dit de\" + infinitive.",
      },
    ],
  },
];
