// Synced from cheneygross-afk/lengo:src/lib/lessons/fr-c1-u03-extra.ts by scripts/sync-content.mjs -- edit it there, not here.
import type { Lesson } from "./types";

// French C1, Unit 3 extra practice: Nominalization.

export const FR_C1_U03_EXTRA: Lesson[] = [
  {
    slug: "c1-nominalization-extra-1",
    level: "FR-C1",
    number: 1,
    optional: true,
    title: "Extra Practice: Nominalization, Part 1 of 3",
    summary: "Verb-to-noun derivation and gender drills in new sentences.",
    duration: "13 min",
    sections: [
      {
        heading: "Recap: suffix decides gender",
        body: [
          "-tion / -sion, -ée, -ance / -ence, -ure and -ade give feminine nouns (\"la réduction\", \"l'arrivée\", \"la croissance\", \"la fermeture\", \"la baignade\"). -ment and -age give masculine nouns (\"le licenciement\", \"le nettoyage\"), with six feminine -age exceptions: page, image, plage, cage, nage, rage.",
          "Suffix-less nouns must be learned: \"le choix\", \"l'achat\", \"le recul\", \"le report\" but \"la baisse\", \"la hausse\", \"la demande\", \"l'attente\", \"l'embauche\".",
        ],
        examples: [
          { es: "L'installation des panneaux solaires a pris une semaine.", en: "Installing the solar panels took a week." },
          { es: "Le classement des candidats sera publié demain.", en: "The candidates' ranking will be published tomorrow." },
          { es: "La sortie du film est prévue en octobre.", en: "The film is due out in October." },
          { es: "Le refus de la banque nous a obligés à tout revoir.", en: "The bank's refusal forced us to rethink everything." },
          { es: "La demande de logements sociaux explose.", en: "Demand for social housing is soaring." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French, using a noun.",
            source: "The bank's refusal surprised us.",
            answer: "Le refus de la banque nous a surpris.",
            altAnswers: ["Le refus de la banque nous a surprises.", "Le refus de la banque nous a étonnés."],
            explanation: "\"Refuser\" → \"le refus\" (masculine, no suffix).",
          },
          {
            type: "multiple-choice",
            question: "Which noun phrase is correct?",
            options: ["l'installation est terminée", "l'installation est terminé", "l'installement est terminé", "l'installage est terminé"],
            correctIndex: 0,
            explanation: "\"Installer\" → \"l'installation\" (feminine).",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French, using a noun.",
        source: "The organisation of the festival is very complicated.",
        answer: "L'organisation du festival est très compliquée.",
        explanation: "\"Organiser\" → \"l'organisation\" (feminine) → \"compliquée\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French, using a noun.",
        source: "The changing of the guard takes place at eleven.",
        answer: "La relève de la garde a lieu à onze heures.",
        altAnswers: ["Le changement de la garde a lieu à onze heures.", "Le changement de garde a lieu à onze heures.", "La relève de la garde a lieu à 11 heures."],
        explanation: "\"Changer\" → \"le changement\"; for guards, French also says \"la relève\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French, using a noun.",
        source: "The entrance to the museum is on the left.",
        answer: "L'entrée du musée est à gauche.",
        altAnswers: ["L'entrée du musée se trouve à gauche."],
        explanation: "\"Entrer\" → \"l'entrée\" (-ée, feminine).",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "[The washing] of the windows is done every month.",
        sentence: "___ des vitres est fait tous les mois.",
        answer: "Le lavage",
        altAnswers: ["Le nettoyage"],
        explanation: "\"Laver\" → \"le lavage\" (-age, masculine) → \"fait\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French, using a noun.",
        source: "The suffering of the victims is immense.",
        answer: "La souffrance des victimes est immense.",
        explanation: "\"Souffrir\" → \"la souffrance\" (-ance).",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French, using a noun.",
        source: "The purchase of a flat is a big decision.",
        answer: "L'achat d'un appartement est une grande décision.",
        altAnswers: ["L'achat d'un appartement est une décision importante."],
        explanation: "\"Acheter\" → \"l'achat\" (masculine).",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French, using a noun.",
        source: "The reading of the will took an hour.",
        answer: "La lecture du testament a duré une heure.",
        altAnswers: ["La lecture du testament a pris une heure."],
        explanation: "\"Lire\" → \"la lecture\" (-ure).",
      },
      {
        type: "multiple-choice",
        question: "Which noun is feminine?",
        options: ["la nage", "le passage", "le dressage", "le stage"],
        correctIndex: 0,
        explanation: "\"La nage\" is one of the six feminine -age exceptions.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French, using a noun.",
        source: "The departure of the coach is at seven.",
        answer: "Le départ du car est à sept heures.",
        altAnswers: ["Le départ de l'autocar est à sept heures.", "Le départ du car a lieu à sept heures.", "Le départ du car est à 7 heures."],
        explanation: "\"Partir\" → \"le départ\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French, using a noun.",
        source: "The wait was worth it.",
        answer: "L'attente en valait la peine.",
        altAnswers: ["L'attente valait la peine.", "L'attente a valu la peine."],
        explanation: "\"Attendre\" → \"l'attente\" (feminine).",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: The signing of the agreement is planned for Friday.",
        words: ["La signature", "de l'accord", "est prévue", "vendredi."],
        translation: "The signing of the agreement is planned for Friday.",
        explanation: "\"Signer\" → \"la signature\"; \"accorder\" → \"l'accord\".",
      },
      {
        type: "matching",
        instructions: "Match each verb with its noun.",
        pairs: [
          { left: "monter", right: "la montée" },
          { left: "dépendre", right: "la dépendance" },
          { left: "brûler", right: "la brûlure" },
          { left: "promener", right: "la promenade" },
          { left: "recruter", right: "le recrutement" },
        ],
        explanation: "-ée, -ance, -ure, -ade feminine; -ment masculine.",
      },
      {
        type: "listen-choose",
        audio: "Le démarrage du chantier est reporté.",
        question: "What does it mean?",
        options: ["The start of the building work has been postponed.", "The building site has been reported.", "The building work starts again.", "The building work has been finished."],
        correctIndex: 0,
        explanation: "\"Démarrer\" → \"le démarrage\"; \"reporté\" = postponed.",
      },
      {
        type: "speak",
        text: "La fermeture du magasin est prévue à vingt heures.",
        prompt: "Say it in French: The shop is due to close at 8 p.m.",
        explanation: "\"Fermer\" → \"la fermeture\".",
      },
    ],
  },
  {
    slug: "c1-nominalization-extra-2",
    level: "FR-C1",
    number: 2,
    optional: true,
    title: "Extra Practice: Nominalization, Part 2 of 3",
    summary: "Adjective-to-noun derivation and irregular verb-noun pairs in new sentences.",
    duration: "13 min",
    sections: [
      {
        heading: "Recap: qualities and irregular pairs",
        body: [
          "Adjectives give mostly feminine nouns: -ité (\"la fiabilité\"), -té (\"la fierté\"), -eur (\"la lenteur\"; but \"le bonheur\"), -esse (\"la faiblesse\"), -ise (\"la franchise\"), -ude (\"la certitude\"). -isme is masculine (\"l'optimisme\").",
          "Irregular verb-noun pairs: \"mourir → la mort\", \"naître → la naissance\", \"perdre → la perte\", \"vendre → la vente\", \"offrir → l'offre\", \"finir → la fin\", \"voir → la vue\", \"mettre → la mise\", \"prendre → la prise\".",
        ],
        examples: [
          { es: "La gratuité des musées le dimanche attire les familles.", en: "Free museum entry on Sundays attracts families." },
          { es: "La pauvreté recule lentement dans la région.", en: "Poverty is slowly falling in the region." },
          { es: "Sa maladresse nous fait toujours rire.", en: "His clumsiness always makes us laugh." },
          { es: "La vue depuis la terrasse est magnifique.", en: "The view from the terrace is magnificent." },
          { es: "La prise de poste aura lieu le 1er mars.", en: "The new job starts on 1 March." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French, using a noun.",
            source: "Poverty is falling slowly.",
            answer: "La pauvreté recule lentement.",
            altAnswers: ["La pauvreté baisse lentement.", "La pauvreté diminue lentement."],
            explanation: "\"Pauvre\" → \"la pauvreté\".",
          },
          {
            type: "fill-blank",
            prompt: "Write the French for the bold words.",
            en: "[The end] of the film is surprising.",
            sentence: "___ du film est surprenante.",
            answer: "La fin",
            explanation: "\"Finir\" → \"la fin\" (feminine) → \"surprenante\".",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French, using a noun.",
        source: "His honesty is beyond doubt.",
        answer: "Son honnêteté ne fait aucun doute.",
        altAnswers: ["Son honnêteté est hors de doute.", "Son honnêteté ne fait pas de doute."],
        explanation: "\"Honnête\" → \"l'honnêteté\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French, using a noun.",
        source: "The softness of this fabric is incredible.",
        answer: "La douceur de ce tissu est incroyable.",
        explanation: "\"Doux\" → \"la douceur\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French, using a noun.",
        source: "The flexibility of the timetable suits me.",
        answer: "La souplesse des horaires me convient.",
        altAnswers: ["La flexibilité des horaires me convient.", "La souplesse de l'emploi du temps me convient.", "La flexibilité de l'emploi du temps me convient."],
        explanation: "\"Souple\" → \"la souplesse\"; \"flexible\" → \"la flexibilité\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "[Loneliness] is a problem for many elderly people.",
        sentence: "___ est un problème pour beaucoup de personnes âgées.",
        answer: "La solitude",
        altAnswers: ["L'isolement"],
        explanation: "\"Seul\" → \"la solitude\" (-ude).",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French, using a noun.",
        source: "The death of the actor moved the whole country.",
        answer: "La mort de l'acteur a ému tout le pays.",
        altAnswers: ["La mort du comédien a ému tout le pays.", "Le décès de l'acteur a ému tout le pays."],
        explanation: "\"Mourir\" → \"la mort\" (or the formal \"le décès\").",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French, using a noun.",
        source: "Supply exceeds demand.",
        answer: "L'offre dépasse la demande.",
        altAnswers: ["L'offre est supérieure à la demande."],
        explanation: "\"Offrir\" → \"l'offre\"; \"demander\" → \"la demande\".",
      },
      {
        type: "multiple-choice",
        question: "Which noun is masculine?",
        options: ["le réalisme", "la fierté", "la lenteur", "la tendresse"],
        correctIndex: 0,
        explanation: "-isme → masculine.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French, using a noun.",
        source: "His stupidity cost us the contract.",
        answer: "Sa bêtise nous a coûté le contrat.",
        altAnswers: ["Sa stupidité nous a coûté le contrat."],
        explanation: "\"Bête\" → \"la bêtise\" (-ise).",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French, using a noun.",
        source: "The width of the corridor is two metres.",
        answer: "La largeur du couloir est de deux mètres.",
        altAnswers: ["Le couloir a une largeur de deux mètres."],
        explanation: "\"Large\" → \"la largeur\"; \"est de\" before a measurement.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French, using a noun.",
        source: "The loss of his job changed everything.",
        answer: "La perte de son emploi a tout changé.",
        altAnswers: ["La perte de son travail a tout changé.", "La perte de son poste a tout changé."],
        explanation: "\"Perdre\" → \"la perte\".",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: Her kindness touched me.",
        words: ["Sa", "gentillesse", "m'a", "touché."],
        translation: "Her kindness touched me.",
        altOrders: [],
        explanation: "\"Gentil\" → \"la gentillesse\" (-esse).",
      },
      {
        type: "matching",
        instructions: "Match each adjective with its noun.",
        pairs: [
          { left: "fragile", right: "la fragilité" },
          { left: "frais", right: "la fraîcheur" },
          { left: "sage", right: "la sagesse" },
          { left: "gourmand", right: "la gourmandise" },
          { left: "inquiet", right: "l'inquiétude" },
        ],
        explanation: "All feminine.",
      },
      {
        type: "listen-choose",
        audio: "La fraîcheur des produits est notre priorité.",
        question: "What does it mean?",
        options: ["The freshness of our produce is our priority.", "Cold products are our priority.", "Our products are kept cool as a priority.", "We prioritise frozen products."],
        correctIndex: 0,
        explanation: "\"Frais\" → \"la fraîcheur\" (freshness or coolness).",
      },
      {
        type: "speak",
        text: "J'admire sa franchise et sa générosité.",
        prompt: "Say it in French: I admire her frankness and her generosity.",
        explanation: "\"Franc\" → \"la franchise\"; \"généreux\" → \"la générosité\".",
      },
    ],
  },
  {
    slug: "c1-nominalization-extra-3",
    level: "FR-C1",
    number: 3,
    optional: true,
    title: "Extra Practice: Nominalization, Part 3 of 3",
    summary: "Clause-to-noun-phrase transformations: the subject becomes de + noun, the adverb an adjective, the object keeps its preposition.",
    duration: "14 min",
    sections: [
      {
        heading: "Recap: the three rules",
        body: [
          "1) Verb → noun, subject → \"de\" + noun or a possessive: \"Le maire a démissionné\" → \"la démission du maire\"; \"Il est parti\" → \"son départ\". 2) Adverb → agreeing adjective: \"fortement augmenté\" → \"la forte augmentation\". 3) Direct object → \"de\" (with the agent in \"par\"); indirect object keeps its preposition: \"participer à\" → \"la participation à\".",
          "The tense disappears; time moves into adjectives or dates (\"la récente hausse\", \"la hausse prévue en mai\").",
        ],
        examples: [
          { es: "Les températures ont brusquement chuté. → La brusque chute des températures.", en: "Temperatures dropped abruptly. → The abrupt drop in temperatures." },
          { es: "La ville a acheté le terrain. → L'achat du terrain par la ville.", en: "The town bought the land. → The town's purchase of the land." },
          { es: "Les jeunes s'intéressent à la politique. → L'intérêt des jeunes pour la politique.", en: "Young people take an interest in politics. → Young people's interest in politics." },
          { es: "Le chômage a récemment baissé. → La récente baisse du chômage.", en: "Unemployment has recently fallen. → The recent fall in unemployment." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Turn into a noun phrase: Les températures ont brusquement chuté.",
            source: "The abrupt drop in temperatures",
            answer: "La brusque chute des températures",
            altAnswers: ["La chute brusque des températures", "La brusque baisse des températures", "La baisse brusque des températures"],
            explanation: "\"Chuter\" → \"la chute\"; \"brusquement\" → \"brusque\".",
          },
          {
            type: "multiple-choice",
            question: "Which is the noun phrase for « La ville a vendu le château »?",
            options: ["la vente du château par la ville", "la vente de la ville par le château", "le vendage du château de la ville", "la vente du château à la ville"],
            correctIndex: 0,
            explanation: "Object → \"du château\", agent → \"par la ville\".",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Turn into a noun phrase: Les salaires ont légèrement augmenté.",
        source: "The slight rise in wages",
        answer: "La légère hausse des salaires",
        altAnswers: ["La légère augmentation des salaires"],
        explanation: "\"Légèrement\" → \"légère\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Turn into a noun phrase: Le Premier ministre est arrivé à Lille.",
        source: "The Prime Minister's arrival in Lille",
        answer: "L'arrivée du Premier ministre à Lille",
        explanation: "Subject → \"du Premier ministre\"; place keeps \"à\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Turn into a noun phrase: Les élèves ont massivement réussi le bac.",
        source: "Pupils' widespread success in the baccalauréat",
        answer: "La réussite massive des élèves au bac",
        altAnswers: ["Le succès massif des élèves au bac", "La réussite massive des élèves au baccalauréat"],
        explanation: "\"Réussir\" → \"la réussite\"; \"massivement\" → \"massive\"; \"réussir le bac\" → \"la réussite au bac\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "[The sharp fall in sales] worries the shop owners.",
        sentence: "___ inquiète les commerçants.",
        answer: "La forte baisse des ventes",
        altAnswers: ["Le net recul des ventes", "La nette baisse des ventes", "Le fort recul des ventes"],
        explanation: "\"Les ventes ont fortement baissé\" → \"la forte baisse des ventes\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Turn into a noun phrase: La région a rapidement réagi.",
        source: "The region's rapid reaction",
        answer: "La réaction rapide de la région",
        altAnswers: ["La rapide réaction de la région"],
        explanation: "\"Réagir\" → \"la réaction\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Turn into a noun phrase: Les habitants s'opposent au projet.",
        source: "Residents' opposition to the project",
        answer: "L'opposition des habitants au projet",
        explanation: "\"S'opposer à\" → \"l'opposition à\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French, using a noun phrase as subject.",
        source: "The council's recent decision has angered residents.",
        answer: "La récente décision du conseil a irrité les habitants.",
        altAnswers: ["La récente décision du conseil a mis les habitants en colère.", "La décision récente du conseil a irrité les habitants.", "La récente décision du conseil a fâché les habitants.", "La récente décision du conseil a exaspéré les habitants."],
        explanation: "\"Le conseil a récemment décidé\" → \"la récente décision du conseil\".",
      },
      {
        type: "multiple-choice",
        question: "Which noun phrase corresponds to « Elle a brillamment réussi »?",
        options: ["sa brillante réussite", "son brillamment réussite", "sa réussite brillamment", "son brillant réussir"],
        correctIndex: 0,
        explanation: "\"Brillamment\" → \"brillante\"; \"elle\" → \"sa\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Turn into a noun phrase: L'entreprise a supprimé 300 postes.",
        source: "The company's cutting of 300 jobs",
        answer: "La suppression de 300 postes par l'entreprise",
        altAnswers: ["La suppression de trois cents postes par l'entreprise"],
        explanation: "\"Supprimer\" → \"la suppression\"; agent \"par l'entreprise\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Turn into a noun phrase: Les citoyens font confiance aux médecins.",
        source: "Citizens' trust in doctors",
        answer: "La confiance des citoyens dans les médecins",
        altAnswers: ["La confiance des citoyens envers les médecins"],
        explanation: "\"Faire confiance à\" → \"la confiance dans / envers\".",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: The town's purchase of the land.",
        words: ["L'achat", "du terrain", "par", "la ville"],
        translation: "The town's purchase of the land.",
        explanation: "Object with \"de\", agent with \"par\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Turn into a noun phrase: Le vote a été reporté à mardi.",
        source: "The postponement of the vote to Tuesday",
        answer: "Le report du vote à mardi",
        altAnswers: ["Le report du vote au mardi"],
        explanation: "\"Reporter à\" → \"le report à\".",
      },
      {
        type: "listen-choose",
        audio: "La lente amélioration de la situation rassure les experts.",
        question: "What does it mean?",
        options: ["The slow improvement in the situation reassures experts.", "Experts are slowly improving the situation.", "The situation is improving too slowly for experts.", "Experts reassure people slowly."],
        correctIndex: 0,
        explanation: "\"La situation s'améliore lentement\" → \"la lente amélioration de la situation\".",
      },
      {
        type: "speak",
        text: "La forte hausse des loyers inquiète les étudiants.",
        prompt: "Say it in French: The sharp rise in rents worries students.",
        explanation: "Adverb → adjective: \"fortement\" → \"forte\".",
      },
    ],
  },
  {
    slug: "c1-nominalization-extra-4",
    level: "FR-C1",
    number: 4,
    optional: true,
    title: "Extra Practice: Nominal Headlines",
    summary: "Write and decode news headlines in nominal style.",
    duration: "13 min",
    sections: [
      {
        heading: "Recap: headline grammar",
        body: [
          "A French headline usually has no verb and no initial article: noun + complement (\"Hausse des loyers à Lyon\"), often with a topic and a colon (\"Grève à la SNCF : report du vote\"). Adverbs become adjectives (\"forte hausse\", \"légère baisse\", \"nouvelle mobilisation\").",
          "To decode, find the verb behind the noun, its subject (the de-complement or the topic), and the tense from context; many nouns hide a passive (\"Arrestation de deux suspects\" = two suspects have been arrested).",
        ],
        examples: [
          { es: "Inondations dans le Gard : évacuation de 300 habitants", en: "Floods in the Gard: 300 residents evacuated" },
          { es: "Rugby : victoire historique du XV de France", en: "Rugby: historic win for France" },
          { es: "Santé : pénurie de médecins dans les campagnes", en: "Health: shortage of doctors in rural areas" },
          { es: "Nouvelle hausse du prix du gaz en janvier", en: "Gas prices to rise again in January" },
          { es: "Lyon : inauguration du nouveau musée des Confluences", en: "Lyon: new Confluences museum opens" },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Rebuild the sentence behind the headline: Inondations dans le Gard : évacuation de 300 habitants.",
            source: "300 residents have been evacuated because of floods in the Gard.",
            answer: "Trois cents habitants ont été évacués à cause des inondations dans le Gard.",
            altAnswers: ["300 habitants ont été évacués à cause des inondations dans le Gard.", "Dans le Gard, 300 habitants ont été évacués à cause des inondations.", "Dans le Gard, trois cents habitants ont été évacués à cause des inondations."],
            explanation: "\"Évacuation\" → passive \"ont été évacués\".",
          },
          {
            type: "multiple-choice",
            question: "« Pénurie de médecins dans les campagnes » means:",
            options: ["Shortage of doctors in rural areas", "Doctors' strike in the countryside", "Doctors leave the cities for the country", "Rural doctors get a pay rise"],
            correctIndex: 0,
            explanation: "\"La pénurie\" = shortage.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Write a French headline (no verb) for:",
        source: "Unemployment rises in Normandy",
        answer: "Hausse du chômage en Normandie",
        altAnswers: ["Augmentation du chômage en Normandie", "Normandie : hausse du chômage", "Chômage : hausse en Normandie"],
        explanation: "Noun + complement + place, no initial article.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Write a French headline (no verb) for:",
        source: "Louvre closed because of a strike",
        answer: "Fermeture du Louvre pour cause de grève",
        altAnswers: ["Fermeture du Louvre en raison d'une grève", "Grève : fermeture du Louvre", "Louvre : fermeture pour cause de grève", "Fermeture du Louvre à cause d'une grève"],
        explanation: "\"Pour cause de\" + noun is a typical headline and notice phrase.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Write a French headline (no verb) for:",
        source: "New mayor of Marseille elected",
        answer: "Élection du nouveau maire de Marseille",
        altAnswers: ["Marseille : élection du nouveau maire", "Marseille : élection d'un nouveau maire"],
        explanation: "\"Élire\" → \"l'élection\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Rebuild the sentence behind the headline: Report du Tour de France d'une semaine.",
        source: "The Tour de France has been postponed by a week.",
        answer: "Le Tour de France a été reporté d'une semaine.",
        altAnswers: ["Le Tour de France est reporté d'une semaine."],
        explanation: "\"Report\" → \"a été reporté\"; \"de\" + duration.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Rebuild the sentence behind the headline: Forte progression des ventes de vélos électriques.",
        source: "Sales of electric bikes are rising sharply.",
        answer: "Les ventes de vélos électriques progressent fortement.",
        altAnswers: ["Les ventes de vélos électriques augmentent fortement.", "Les ventes de vélos électriques ont fortement progressé."],
        explanation: "\"Forte progression\" → \"progressent fortement\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words in the headline.",
        en: "Paris: [opening] of a new metro station",
        sentence: "Paris : ___ d'une nouvelle station de métro",
        answer: "ouverture",
        altAnswers: ["inauguration", "mise en service"],
        explanation: "No article at the start of a headline element.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Rebuild the sentence behind the headline: Rejet de la motion de censure.",
        source: "The motion of no confidence has been rejected.",
        answer: "La motion de censure a été rejetée.",
        explanation: "\"Rejet\" → passive \"a été rejetée\" (agreeing with \"la motion\").",
      },
      {
        type: "multiple-choice",
        question: "Which headline means 'Wine harvest starts early in Burgundy'?",
        options: [
          "Bourgogne : début précoce des vendanges",
          "Bourgogne : fin précoce des vendanges",
          "Bourgogne : les vendanges commenceront tard",
          "Bourgogne : report des vendanges",
        ],
        correctIndex: 0,
        explanation: "\"Début\" = start; \"précoce\" = early; \"les vendanges\" = grape harvest.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Write a French headline (no verb) for:",
        source: "Rent freeze in Paris",
        answer: "Gel des loyers à Paris",
        altAnswers: ["Paris : gel des loyers"],
        explanation: "\"Geler\" → \"le gel\" (also frost).",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Rebuild the sentence behind the headline: Nomination d'une nouvelle directrice à l'Opéra de Lyon.",
        source: "A new director has been appointed at the Lyon Opera.",
        answer: "Une nouvelle directrice a été nommée à l'Opéra de Lyon.",
        explanation: "\"Nomination\" → \"a été nommée\".",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to make the headline: Football: France's historic victory.",
        words: ["Football :", "victoire", "historique", "des Bleus"],
        translation: "Football: France's historic victory.",
        explanation: "Topic + colon + noun + adjective + complement.",
      },
      {
        type: "matching",
        instructions: "Match each headline noun with its meaning.",
        pairs: [
          { left: "la pénurie", right: "shortage" },
          { left: "le gel", right: "freeze" },
          { left: "la flambée", right: "surge" },
          { left: "le bilan", right: "toll / assessment" },
          { left: "la polémique", right: "controversy" },
        ],
        explanation: "Five nouns that appear in headlines every day.",
      },
      {
        type: "listen-choose",
        audio: "Tempête en Bretagne : lourd bilan matériel.",
        question: "What does it mean?",
        options: ["Storm in Brittany: heavy damage.", "Storm in Brittany: many dead.", "Storm warning for Brittany tomorrow.", "Brittany escapes the storm."],
        correctIndex: 0,
        explanation: "\"Bilan matériel\" = material damage, as opposed to \"bilan humain\" (casualties).",
      },
      {
        type: "speak",
        text: "Nouvelle hausse du prix du gaz en janvier.",
        prompt: "Read the headline aloud: Gas prices to rise again in January.",
        explanation: "\"Again\" → \"nouvelle\" before the noun.",
      },
    ],
  },
  {
    slug: "c1-nominalization-extra-5",
    level: "FR-C1",
    number: 5,
    optional: true,
    title: "Extra Practice: Denominalize for Clarity",
    summary: "Rewrite dense administrative sentences in plain French with verbs and clear agents.",
    duration: "14 min",
    sections: [
      {
        heading: "Recap: undoing the noun chains",
        body: [
          "Turn the main noun back into a verb, bring the agent back as subject, replace \"faire l'objet de\" and \"il est procédé à\" with active verbs, cut empty phrases (\"au niveau de\", \"en termes de\") and split long sentences.",
          "\"Le renouvellement de votre carte fera l'objet d'un envoi postal\" → \"Nous vous enverrons votre nouvelle carte par la poste.\"",
        ],
        examples: [
          { es: "Le renouvellement de votre carte fera l'objet d'un envoi postal.", en: "Your card renewal will be the subject of a postal dispatch." },
          { es: "Nous vous enverrons votre nouvelle carte par la poste.", en: "We'll post you your new card." },
          { es: "Il est procédé au relevé des compteurs le 5 de chaque mois.", en: "Meter reading is carried out on the 5th of each month." },
          { es: "Nous relevons les compteurs le 5 de chaque mois.", en: "We read the meters on the 5th of each month." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Rewrite in plain French: Il est procédé au relevé des compteurs le 5.",
            source: "We read the meters on the 5th.",
            answer: "Nous relevons les compteurs le 5.",
            altAnswers: ["On relève les compteurs le 5.", "Nous relevons les compteurs le cinq."],
            explanation: "\"Il est procédé au relevé\" → active \"nous relevons\".",
          },
          {
            type: "multiple-choice",
            question: "Which is the plainest version?",
            options: [
              "Appelez-nous si vous avez une question.",
              "Toute demande d'information fera l'objet d'un traitement téléphonique.",
              "Il est procédé au traitement des demandes par téléphone.",
              "La prise de contact téléphonique est recommandée en cas de questionnement.",
            ],
            correctIndex: 0,
            explanation: "An imperative with a clear verb.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Rewrite in plain French: La transmission de vos documents doit être effectuée avant le 15.",
        source: "Send us your documents before the 15th.",
        answer: "Envoyez-nous vos documents avant le 15.",
        altAnswers: ["Vous devez nous envoyer vos documents avant le 15.", "Transmettez-nous vos documents avant le 15.", "Envoyez vos documents avant le 15.", "Merci de nous envoyer vos documents avant le 15."],
        explanation: "\"La transmission... doit être effectuée\" → an imperative.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Rewrite in plain French: Votre réclamation fera l'objet d'un traitement dans les meilleurs délais.",
        source: "We'll deal with your complaint as soon as possible.",
        answer: "Nous traiterons votre réclamation dans les meilleurs délais.",
        altAnswers: ["Nous traiterons votre réclamation le plus vite possible.", "Nous allons traiter votre réclamation dans les meilleurs délais.", "Nous traiterons votre réclamation au plus vite."],
        explanation: "\"Faire l'objet d'un traitement\" → \"traiter\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Rewrite in plain French: Au niveau des horaires, il y a eu une modification.",
        source: "The timetable has changed.",
        answer: "Les horaires ont changé.",
        altAnswers: ["Les horaires ont été modifiés.", "Nous avons modifié les horaires."],
        explanation: "Cut \"au niveau de\"; \"une modification\" → \"ont changé\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words, with an active verb.",
        en: "[The town hall will repair] the road in May.",
        sentence: "___ la route en mai.",
        answer: "La mairie réparera",
        altAnswers: ["La mairie va réparer", "La municipalité réparera"],
        explanation: "\"La réparation de la route par la mairie\" → \"la mairie réparera la route\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Rewrite in plain French: La mise en conformité de l'installation électrique est à la charge du propriétaire.",
        source: "The owner must bring the wiring up to standard.",
        answer: "Le propriétaire doit mettre l'installation électrique aux normes.",
        altAnswers: ["Le propriétaire doit mettre l'installation électrique en conformité.", "C'est au propriétaire de mettre l'installation électrique aux normes.", "Le propriétaire doit faire mettre l'installation électrique aux normes."],
        explanation: "\"Être à la charge de\" → the person becomes the subject of \"devoir\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Rewrite in plain French: L'accès au parking est réservé aux détenteurs d'un badge.",
        source: "Only badge holders can use the car park.",
        answer: "Seuls les détenteurs d'un badge peuvent accéder au parking.",
        altAnswers: ["Seules les personnes qui ont un badge peuvent entrer dans le parking.", "Seuls les détenteurs d'un badge peuvent utiliser le parking.", "Il faut un badge pour accéder au parking.", "Il faut un badge pour entrer dans le parking."],
        explanation: "\"L'accès est réservé\" → \"seuls... peuvent accéder\".",
      },
      {
        type: "multiple-choice",
        question: "Which phrase adds nothing and can usually be cut?",
        options: ["au niveau de", "à cause de", "grâce à", "avant de"],
        correctIndex: 0,
        explanation: "\"Au niveau de\" is often an empty filler in bureaucratic and spoken French.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Rewrite in plain French: Il est procédé à la fermeture de la piscine pour cause de vidange.",
        source: "We're closing the pool to drain it.",
        answer: "Nous fermons la piscine pour la vider.",
        altAnswers: ["Nous fermons la piscine pour la vidanger.", "La piscine est fermée pour vidange.", "On ferme la piscine pour la vider.", "La piscine ferme pour être vidée."],
        explanation: "\"Il est procédé à la fermeture\" → \"nous fermons\"; \"pour cause de vidange\" → \"pour la vider\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Rewrite in plain French: Le non-respect de ces consignes entraînera l'exclusion du participant.",
        source: "If you don't follow these instructions, you'll be excluded.",
        answer: "Si vous ne respectez pas ces consignes, vous serez exclu.",
        altAnswers: ["Si vous ne respectez pas ces consignes, vous serez exclue.", "Si vous ne respectez pas ces consignes, vous serez exclus.", "Si vous ne suivez pas ces consignes, vous serez exclu.", "Si vous ne suivez pas ces consignes, vous serez exclue."],
        explanation: "\"Le non-respect\" → a si-clause with a negation; \"l'exclusion\" → passive \"serez exclu\".",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: We'll refund you within ten days.",
        words: ["Nous", "vous", "rembourserons", "sous dix jours."],
        translation: "We'll refund you within ten days.",
        explanation: "Plain version of \"Le remboursement interviendra sous dix jours\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Rewrite in plain French: En termes de sécurité, le port du casque est obligatoire.",
        source: "You must wear a helmet.",
        answer: "Vous devez porter un casque.",
        altAnswers: ["Il faut porter un casque.", "Le casque est obligatoire.", "Portez un casque."],
        explanation: "Cut \"en termes de sécurité\"; \"le port du casque\" → \"porter un casque\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Rewrite in plain French: Le paiement par carte bancaire fait l'objet d'un supplément de 2 %.",
        source: "There's a 2% surcharge if you pay by card.",
        answer: "Si vous payez par carte bancaire, il y a un supplément de 2 %.",
        altAnswers: ["Si vous payez par carte, il y a un supplément de 2 %.", "Nous ajoutons 2 % si vous payez par carte.", "Payer par carte coûte 2 % de plus."],
        explanation: "\"Le paiement par carte\" → \"si vous payez par carte\".",
      },
      {
        type: "listen-choose",
        audio: "Nous traiterons votre demande dans les meilleurs délais.",
        question: "What does it mean?",
        options: ["We'll deal with your request as soon as possible.", "Your request has been delayed.", "We'll treat you to the best deals.", "Your request will take the longest time."],
        correctIndex: 0,
        explanation: "\"Dans les meilleurs délais\" = as soon as possible.",
      },
      {
        type: "speak",
        text: "Nous vous enverrons votre nouvelle carte par la poste.",
        prompt: "Say it in plain French: We'll post you your new card.",
        explanation: "Agent \"nous\" + active verb \"enverrons\".",
      },
    ],
  },
  {
    slug: "c1-nominalization-extra-6",
    level: "FR-C1",
    number: 6,
    optional: true,
    title: "Extra Practice: Le Fait Que, Infinitives and Le + Adjective",
    summary: "Choose the right nominal structure in context: le fait que, a nominalised infinitive or le + adjective.",
    duration: "13 min",
    sections: [
      {
        heading: "Recap: three tools",
        body: [
          "\"Le fait que\" turns a whole clause into a noun phrase when no derived noun exists, with the subjunctive for evaluation (\"le fait qu'il ait menti me choque\") and the indicative for stated facts (\"du fait qu'il habite loin\").",
          "Some infinitives are nouns: \"le rire\", \"le devoir\", \"le pouvoir\", \"le savoir-faire\", \"le lever du soleil\". \"Le + adjective\" names an abstract idea: \"l'essentiel\", \"le plus dur\", \"le pire\", \"l'important, c'est que\" + subjunctive.",
        ],
        examples: [
          { es: "Le fait qu'elle ait accepté nous soulage.", en: "The fact that she's accepted is a relief to us." },
          { es: "Le savoir-vivre se perd, disent les anciens.", en: "Good manners are dying out, say the older generation." },
          { es: "Le plus dur est fait.", en: "The hardest part is done." },
          { es: "L'important, c'est que personne n'ait été blessé.", en: "What matters is that nobody was hurt." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "The hardest part is done.",
            answer: "Le plus dur est fait.",
            altAnswers: ["Le plus difficile est fait.", "Le plus dur est derrière nous."],
            explanation: "\"Le plus dur\" = the hardest part.",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "What matters is that nobody was hurt.",
            answer: "L'important, c'est que personne n'ait été blessé.",
            altAnswers: ["L'essentiel, c'est que personne n'ait été blessé.", "L'important est que personne n'ait été blessé.", "Ce qui compte, c'est que personne n'ait été blessé."],
            explanation: "\"L'important, c'est que\" + past subjunctive.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "The fact that he didn't apologise shocks me.",
        answer: "Le fait qu'il ne se soit pas excusé me choque.",
        altAnswers: ["Le fait qu'il ne se soit pas excusé me choque beaucoup.", "Le fait qu'il ne s'est pas excusé me choque."],
        explanation: "Reaction → past subjunctive of a pronominal verb.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "Because he speaks German, he got the job.",
        answer: "Du fait qu'il parle allemand, il a obtenu le poste.",
        altAnswers: ["Comme il parle allemand, il a obtenu le poste.", "Parce qu'il parle allemand, il a obtenu le poste.", "Du fait qu'il parle allemand, il a eu le poste.", "Comme il parle allemand, il a eu le poste."],
        explanation: "\"Du fait que\" + indicative = because.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "The worst thing is that he knew.",
        answer: "Le pire, c'est qu'il savait.",
        altAnswers: ["Le pire, c'est qu'il était au courant.", "Le pire est qu'il savait."],
        explanation: "\"Le pire, c'est que\" + indicative (a fact).",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "[Laughter] is good for your health.",
        sentence: "___ est bon pour la santé.",
        answer: "Le rire",
        explanation: "\"Le rire\": an infinitive used as a masculine noun.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "Most of the guests left before midnight.",
        answer: "L'essentiel des invités est parti avant minuit.",
        altAnswers: ["La plupart des invités sont partis avant minuit.", "L'essentiel des invités sont partis avant minuit."],
        explanation: "\"L'essentiel de\" or \"la plupart de\" = most of.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "It's our duty to vote.",
        answer: "C'est notre devoir de voter.",
        altAnswers: ["Voter est notre devoir.", "Voter, c'est notre devoir.", "Il est de notre devoir de voter."],
        explanation: "\"Le devoir\" (duty) is a nominalised infinitive.",
      },
      {
        type: "multiple-choice",
        question: "Which sentence is correct?",
        options: [
          "Le mieux serait de partir demain.",
          "La mieux serait de partir demain.",
          "Le mieux serait que partir demain.",
          "Le mieux serait que nous partons demain.",
        ],
        correctIndex: 0,
        explanation: "\"Le mieux serait de\" + infinitive.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "The fact that the trains are on strike complicates everything.",
        answer: "Le fait que les trains soient en grève complique tout.",
        altAnswers: ["Le fait qu'il y ait une grève des trains complique tout.", "Le fait que les cheminots soient en grève complique tout."],
        explanation: "\"Le fait que\" as subject of an evaluative verb → subjunctive.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "We watched the sunset from the beach.",
        answer: "Nous avons regardé le coucher du soleil depuis la plage.",
        altAnswers: ["On a regardé le coucher du soleil depuis la plage.", "Nous avons regardé le coucher de soleil depuis la plage.", "On a regardé le coucher de soleil depuis la plage.", "Nous avons regardé le coucher du soleil de la plage."],
        explanation: "\"Le coucher du soleil\": a nominalised infinitive.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: The most important thing is to stay calm.",
        words: ["Le plus important,", "c'est de", "rester", "calme."],
        translation: "The most important thing is to stay calm.",
        explanation: "\"Le plus important, c'est de\" + infinitive.",
      },
      {
        type: "matching",
        instructions: "Match each French phrase with its meaning.",
        pairs: [
          { left: "l'essentiel", right: "the main thing" },
          { left: "le plus dur", right: "the hardest part" },
          { left: "le savoir-faire", right: "know-how" },
          { left: "le fait que", right: "the fact that" },
        ],
        explanation: "Three nominal tools plus a set phrase.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "Purchasing power has fallen this year.",
        answer: "Le pouvoir d'achat a baissé cette année.",
        altAnswers: ["Le pouvoir d'achat a diminué cette année.", "Le pouvoir d'achat a reculé cette année."],
        explanation: "\"Le pouvoir d'achat\" = purchasing power.",
      },
      {
        type: "listen-choose",
        audio: "Le plus étonnant, c'est qu'il n'a rien dit.",
        question: "What does it mean?",
        options: ["The most surprising thing is that he said nothing.", "He was very surprised and said nothing.", "Nothing surprises him any more.", "He said the most surprising thing."],
        correctIndex: 0,
        explanation: "\"Le plus étonnant, c'est que\" + indicative (a fact).",
      },
      {
        type: "speak",
        text: "Le plus dur, c'est de se lever le matin.",
        prompt: "Say it in French: The hardest part is getting up in the morning.",
        explanation: "\"Le plus dur, c'est de\" + infinitive.",
      },
    ],
  },
];
