// Synced from cheneygross-afk/lengo:src/lib/lessons/fr-c1-u09-extra.ts by scripts/sync-content.mjs -- edit it there, not here.
import type { Lesson } from "./types";

// French C1, Unit 9 extra practice: Verbs with Prepositions.

export const FR_C1_U09_EXTRA: Lesson[] = [
  {
    slug: "c1-verb-prepositions-extra-1",
    level: "FR-C1",
    number: 1,
    optional: true,
    title: "Extra Practice: Verbs and Their Prepositions, Part 1 of 3",
    summary: "More practice with verbs that take à, and the choice between y, lui / leur and à lui / à elle.",
    duration: "14 min",
    sections: [
      {
        heading: "Recap: y, lui or à lui?",
        body: [
          "A thing after an à-verb becomes \"y\": \"j'y pense\", \"elle y a renoncé\". A person stays after the verb as \"à + stressed pronoun\" with most verbs (\"penser à lui\", \"tenir à elle\", \"s'intéresser à eux\", all pronominal verbs), but becomes \"lui / leur\" before the verb with communication verbs and with \"ressembler, obéir, plaire, nuire, sourire, appartenir à\".",
        ],
        examples: [
          { es: "Ton déménagement ? J'y pense tous les jours.", en: "Your move? I think about it every day." },
          { es: "Mes grands-parents ? Je pense souvent à eux.", en: "My grandparents? I often think of them." },
          { es: "Ce manteau ne lui plaît plus.", en: "She doesn't like this coat any more." },
          { es: "Le conseil municipal ? Je ne m'y intéresse guère.", en: "The town council? I'm hardly interested in it." },
          { es: "Adressez-vous à elle pour les remboursements.", en: "Speak to her about refunds." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "My grandparents? I often think of them.",
            answer: "Mes grands-parents ? Je pense souvent à eux.",
            explanation: "\"Penser à\" + people: \"à eux\" after the verb.",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "She doesn't like this flat.",
            answer: "Cet appartement ne lui plaît pas.",
            altAnswers: ["Elle n'aime pas cet appartement."],
            explanation: "\"Plaire à\" takes lui; the flat is the subject.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "The trip? We've given it up.",
        answer: "Le voyage ? Nous y avons renoncé.",
        altAnswers: ["Le voyage ? On y a renoncé."],
        explanation: "\"Renoncer à\" + a thing → y.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "He looks like his father.",
        answer: "Il ressemble à son père.",
        explanation: "\"Ressembler à\": the à is compulsory.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "He looks like him.",
        answer: "Il lui ressemble.",
        explanation: "\"Ressembler à\" belongs to the lui-verbs.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "I'm very attached to her.",
        answer: "Je tiens beaucoup à elle.",
        altAnswers: ["Je suis très attaché à elle.", "Je suis très attachée à elle.", "Je tiens énormément à elle."],
        explanation: "\"Tenir à\" + a person: \"à elle\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "The concert? Did you attend it? (to a friend)",
        answer: "Le concert ? Tu y as assisté ?",
        altAnswers: ["Le concert ? Est-ce que tu y as assisté ?", "Le concert ? Y as-tu assisté ?", "Le concert ? Tu y es allé ?", "Le concert ? Tu y es allée ?"],
        explanation: "\"Assister à\" + a thing → y before the auxiliary.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "The dog obeys them.",
        answer: "Le chien leur obéit.",
        explanation: "\"Obéir à\" takes leur.",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "Pollution [harms] everyone's health.",
        sentence: "La pollution ___ la santé de tous.",
        answer: "nuit à",
        explanation: "\"Nuire à\": transitive in English, à in French.",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "That old car [belongs to them].",
        sentence: "Cette vieille voiture ___.",
        answer: "leur appartient",
        explanation: "\"Appartenir à\" → leur before the verb.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "Be careful with him, he's very sensitive. (to a friend)",
        answer: "Fais attention à lui, il est très sensible.",
        altAnswers: ["Fais attention avec lui, il est très sensible."],
        explanation: "\"Faire attention à\" + a person: \"à lui\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "I'm getting used to it.",
        answer: "Je m'y habitue.",
        altAnswers: ["Je m'y fais."],
        explanation: "\"S'habituer à\" + a thing → y, between the reflexive and the verb.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: She never smiles at them.",
        words: ["Elle", "ne", "leur", "sourit", "jamais."],
        translation: "She never smiles at them.",
        explanation: "\"Sourire à\" → leur, inside the negation.",
      },
      {
        type: "multiple-choice",
        question: "Which sentence is correct?",
        options: ["Je pense à toi.", "Je te pense.", "J'y pense à toi.", "Je pense de toi."],
        correctIndex: 0,
        explanation: "\"Penser à\" + a person keeps à + stressed pronoun.",
      },
      {
        type: "listen-choose",
        audio: "Je ne m'y attendais pas.",
        question: "What does it mean?",
        options: ["I wasn't expecting it.", "I wasn't waiting there.", "I wasn't expecting him.", "I didn't go there."],
        correctIndex: 0,
        explanation: "\"S'attendre à\" + a thing → y.",
      },
      {
        type: "speak",
        text: "Mes grands-parents ? Je pense souvent à eux.",
        prompt: "Say it in French: My grandparents? I often think of them.",
        explanation: "\"Penser à eux\".",
      },
    ],
  },
  {
    slug: "c1-verb-prepositions-extra-2",
    level: "FR-C1",
    number: 2,
    optional: true,
    title: "Extra Practice: Verbs and Their Prepositions, Part 2 of 3",
    summary: "More practice with verbs that take de, and the choice between en and de lui / d'elle.",
    duration: "14 min",
    sections: [
      {
        heading: "Recap: en or de lui?",
        body: [
          "A thing, an idea or an infinitive after a de-verb becomes \"en\": \"je m'en souviens\", \"il s'en occupe\", \"profites-en\". A specific person stays after the verb as \"de + stressed pronoun\": \"je me souviens d'elle\", \"méfie-toi de lui\". An indefinite group can be \"en\": \"des bénévoles, on en a besoin\".",
        ],
        examples: [
          { es: "Le mot de passe ? Je ne m'en souviens jamais.", en: "The password? I can never remember it." },
          { es: "Mon oncle ? Je me méfie un peu de lui.", en: "My uncle? I'm a bit wary of him." },
          { es: "Les vacances, il faut en profiter.", en: "Holidays: you have to make the most of them." },
          { es: "Les enfants de ma voisine ? Je m'occupe d'eux le mardi.", en: "My neighbour's children? I look after them on Tuesdays." },
          { es: "Du soutien, elle en a vraiment besoin en ce moment.", en: "Support: she really needs it right now." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "The password? I can never remember it.",
            answer: "Le mot de passe ? Je ne m'en souviens jamais.",
            altAnswers: ["Le mot de passe ? Je ne m'en rappelle jamais.", "Le mot de passe ? Je ne me le rappelle jamais."],
            explanation: "\"Se souvenir de\" + a thing → en.",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "I look after them on Tuesdays.",
            answer: "Je m'occupe d'eux le mardi.",
            altAnswers: ["Je m'occupe d'elles le mardi."],
            explanation: "People after \"s'occuper de\": \"d'eux\" / \"d'elles\".",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "It depends on the price.",
        answer: "Ça dépend du prix.",
        altAnswers: ["Cela dépend du prix."],
        explanation: "\"Dépendre de\" + le prix = du prix.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "Our future depends on it.",
        answer: "Notre avenir en dépend.",
        explanation: "With a full subject, en can replace de + the thing: \"notre avenir en dépend\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "Don't make fun of her. (to a friend)",
        answer: "Ne te moque pas d'elle.",
        explanation: "\"Se moquer de\" + a person: \"d'elle\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "I don't care at all.",
        answer: "Je m'en moque complètement.",
        altAnswers: ["Je m'en fiche complètement.", "Je m'en moque totalement.", "Je m'en fiche totalement.", "Ça m'est complètement égal."],
        explanation: "Frozen en: \"je m'en moque\" / \"je m'en fiche\" = I don't care.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "We can't do without him.",
        answer: "Nous ne pouvons pas nous passer de lui.",
        altAnswers: ["On ne peut pas se passer de lui."],
        explanation: "\"Se passer de\" + a person: \"de lui\" after the infinitive.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "The sun is out: make the most of it! (to a friend)",
        answer: "Il fait beau : profites-en !",
        altAnswers: ["Il y a du soleil : profites-en !"],
        explanation: "Tu imperative + en: the s comes back, \"profites-en\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "The tickets? [I'll deal with it].",
        sentence: "Les billets ? ___.",
        answer: "Je m'en occupe",
        altAnswers: ["Je vais m'en occuper", "Je m'en charge"],
        explanation: "\"S'occuper de\" + things → en.",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "It's a period [I don't remember] well.",
        sentence: "C'est une période ___ bien.",
        answer: "dont je ne me souviens pas",
        explanation: "\"Se souvenir de\" → dont.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "He suspected it.",
        answer: "Il s'en doutait.",
        explanation: "\"Se douter de\" = to suspect; en for the idea.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "Good doctors? The region badly needs them.",
        answer: "De bons médecins ? La région en a cruellement besoin.",
        altAnswers: ["Des bons médecins ? La région en a cruellement besoin.", "De bons médecins ? La région en a grand besoin.", "De bons médecins ? La région en a vraiment besoin."],
        explanation: "An indefinite group of people → en.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: Be wary of them.",
        words: ["Méfiez-vous", "d'eux."],
        translation: "Be wary of them.",
        explanation: "\"Se méfier de\" + people: \"d'eux\".",
      },
      {
        type: "multiple-choice",
        question: "In careful written French, which is correct for: My sister? I remember her well.",
        options: ["Ma sœur ? Je me souviens bien d'elle.", "Ma sœur ? Je m'en souviens bien.", "Ma sœur ? Je lui souviens bien.", "Ma sœur ? Je me souviens bien à elle."],
        correctIndex: 0,
        explanation: "A specific person: \"d'elle\".",
      },
      {
        type: "listen-choose",
        audio: "Je m'en souviendrai.",
        question: "What does it mean?",
        options: ["I won't forget it.", "I remembered it.", "I'll remind you.", "I'll think about him."],
        correctIndex: 0,
        explanation: "Future of \"se souvenir de\" + en; often a warning.",
      },
      {
        type: "speak",
        text: "Ne t'inquiète pas, je m'en occupe.",
        prompt: "Say it in French (to a friend): Don't worry, I'll take care of it.",
        explanation: "\"S'en occuper\".",
      },
    ],
  },
  {
    slug: "c1-verb-prepositions-extra-3",
    level: "FR-C1",
    number: 3,
    optional: true,
    title: "Extra Practice: Verbs and Their Prepositions, Part 3 of 3",
    summary: "Verbs whose meaning changes with the preposition: penser, manquer, servir, tenir, jouer, croire.",
    duration: "14 min",
    sections: [
      {
        heading: "Recap: one verb, several meanings",
        body: [
          "\"Penser à\" (have in mind) / \"penser de\" (opinion). \"Manquer à\" (be missed by: the thing missed is the subject) / \"manquer de\" (lack) / \"manquer\" + object (miss a train). \"Servir à\" (purpose) / \"servir de\" (act as) / \"se servir de\" (use). \"Tenir à\" (value) / \"tenir de\" (take after). \"Jouer à\" (games) / \"jouer de\" (instruments). \"Croire qn\" / \"croire à\" (existence, value) / \"croire en\" (trust).",
        ],
        examples: [
          { es: "Que penses-tu de son dernier roman ?", en: "What do you think of her latest novel?" },
          { es: "Ma ville natale me manque de plus en plus.", en: "I miss my home town more and more." },
          { es: "Cette caisse en bois nous sert de table basse.", en: "We use this wooden crate as a coffee table." },
          { es: "Il joue de la batterie dans un groupe de rock.", en: "He plays drums in a rock band." },
          { es: "Personne ne croyait en lui, sauf sa mère.", en: "Nobody believed in him except his mother." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "I miss my home town.",
            answer: "Ma ville natale me manque.",
            explanation: "The town is missed, so it's the subject.",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "What do you think of her latest novel? (to a friend)",
            answer: "Que penses-tu de son dernier roman ?",
            altAnswers: ["Qu'est-ce que tu penses de son dernier roman ?", "Tu penses quoi de son dernier roman ?"],
            explanation: "Opinion: \"penser de\".",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "They miss us.",
        answer: "Nous leur manquons.",
        explanation: "We are missed: \"nous\" is the subject, \"leur\" the people who miss.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "This region lacks doctors.",
        answer: "Cette région manque de médecins.",
        explanation: "\"Manquer de\" + bare noun = to lack.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "She missed her flight.",
        answer: "Elle a manqué son vol.",
        altAnswers: ["Elle a raté son vol.", "Elle a manqué son avion.", "Elle a raté son avion."],
        explanation: "Miss a flight: direct object.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "What's this app for?",
        answer: "À quoi sert cette appli ?",
        altAnswers: ["À quoi sert cette application ?", "Ça sert à quoi, cette appli ?", "Cette appli sert à quoi ?", "Cette application sert à quoi ?"],
        explanation: "Purpose: \"servir à\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "My sister acted as interpreter.",
        answer: "Ma sœur a servi d'interprète.",
        altAnswers: ["Ma sœur a fait l'interprète.", "Ma sœur m'a servi d'interprète.", "Ma sœur nous a servi d'interprète."],
        explanation: "A role: \"servir de\" + bare noun.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "She takes after her grandmother.",
        answer: "Elle tient de sa grand-mère.",
        explanation: "\"Tenir de\" = take after.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "My son plays the piano and chess.",
        answer: "Mon fils joue du piano et aux échecs.",
        explanation: "Instrument: \"jouer de\"; game: \"jouer à\" (aux échecs).",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "I [believe in] this project.",
        sentence: "Je ___ ce projet.",
        answer: "crois à",
        altAnswers: ["crois en"],
        explanation: "Believing a thing will work: \"croire à\" (\"croire en\" is also heard).",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "[Remember to] water the plants. (to a friend)",
        sentence: "___ arroser les plantes.",
        answer: "Pense à",
        explanation: "\"Penser à\" + infinitive = remember to.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "I believe you.",
        answer: "Je te crois.",
        altAnswers: ["Je vous crois."],
        explanation: "\"Croire quelqu'un\": direct object.",
      },
      {
        type: "matching",
        instructions: "Match each sentence to its meaning.",
        pairs: [
          { left: "Tu me manques.", right: "I miss you." },
          { left: "Je te manque.", right: "You miss me." },
          { left: "Je manque de temps.", right: "I'm short of time." },
          { left: "J'ai manqué le début.", right: "I missed the beginning." },
        ],
        explanation: "Four constructions of manquer.",
      },
      {
        type: "multiple-choice",
        question: "What does \"Il se sert de ses amis\" mean?",
        options: ["He uses his friends.", "He serves his friends.", "He helps himself to his friends' food.", "His friends serve him."],
        correctIndex: 0,
        explanation: "\"Se servir de quelqu'un\" = to use a person.",
      },
      {
        type: "listen-choose",
        audio: "Je crois en toi.",
        question: "What does it mean?",
        options: ["I believe in you.", "I believe you.", "I think about you.", "I'm counting on you."],
        correctIndex: 0,
        explanation: "\"Croire en\" = to have faith in.",
      },
      {
        type: "speak",
        text: "Tu nous manques beaucoup.",
        prompt: "Say it in French (to a friend): We miss you a lot.",
        explanation: "\"Tu\" is the person missed.",
      },
    ],
  },
  {
    slug: "c1-verb-prepositions-extra-4",
    level: "FR-C1",
    number: 4,
    optional: true,
    title: "Extra Practice: Prepositional Verbs in Relative Clauses",
    summary: "Dont, auquel, à laquelle, à quoi, ce dont, sur qui and avec lequel in new sentences.",
    duration: "14 min",
    sections: [
      {
        heading: "Recap: the verb chooses the relative",
        body: [
          "Start from the verb's construction. De → \"dont\" (\"le livre dont je parle\"), \"ce dont\" without antecedent. À → \"auquel / à laquelle / auxquels\" for things, \"à qui\" for people, \"ce à quoi\" without antecedent. Other prepositions move to the front with \"qui\" (people) or \"lequel\": \"sur qui je compte\", \"avec lequel j'écris\". Never strand a preposition at the end.",
        ],
        examples: [
          { es: "C'est le quartier dont je rêvais.", en: "It's the neighbourhood I used to dream of." },
          { es: "L'émission à laquelle elle a participé passe ce soir.", en: "The show she took part in is on tonight." },
          { es: "Ce à quoi je ne m'habitue pas, c'est le bruit.", en: "What I can't get used to is the noise." },
          { es: "Le stylo avec lequel il a signé était un cadeau.", en: "The pen he signed with was a present." },
          { es: "Ma sœur est la personne sur qui je compte le plus.", en: "My sister is the person I rely on most." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "What I can't get used to is the noise.",
            answer: "Ce à quoi je ne m'habitue pas, c'est le bruit.",
            altAnswers: ["Ce à quoi je n'arrive pas à m'habituer, c'est le bruit.", "Ce à quoi je ne me fais pas, c'est le bruit."],
            explanation: "\"S'habituer à\" → \"ce à quoi\".",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "It's the neighbourhood I used to dream of.",
            answer: "C'est le quartier dont je rêvais.",
            explanation: "\"Rêver de\" → dont; imperfect for 'used to'.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "That's what I'm afraid of.",
        answer: "C'est ce dont j'ai peur.",
        altAnswers: ["Voilà ce dont j'ai peur.", "C'est ce que je crains."],
        explanation: "\"Avoir peur de\" → ce dont.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "The competition he took part in was very hard.",
        answer: "Le concours auquel il a participé était très difficile.",
        altAnswers: ["La compétition à laquelle il a participé était très difficile.", "Le concours auquel il a participé était très dur.", "La compétition à laquelle il a participé était très dure."],
        explanation: "\"Participer à\" → auquel / à laquelle.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "The colleague I share an office with is very quiet.",
        answer: "La collègue avec qui je partage mon bureau est très calme.",
        altAnswers: ["Le collègue avec qui je partage mon bureau est très calme.", "La collègue avec qui je partage un bureau est très calme.", "Le collègue avec qui je partage un bureau est très calme.", "Le collègue avec lequel je partage mon bureau est très calme.", "La collègue avec laquelle je partage mon bureau est très calme."],
        explanation: "\"Partager avec\" → \"avec qui\" at the front.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "Tell me what you need. (to a friend)",
        answer: "Dis-moi ce dont tu as besoin.",
        explanation: "\"Avoir besoin de\" → ce dont.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "These are the rules we must comply with.",
        answer: "Voici les règles auxquelles nous devons nous conformer.",
        altAnswers: ["Ce sont les règles auxquelles nous devons nous conformer.", "Voici les règles que nous devons respecter.", "Ce sont les règles que nous devons respecter.", "Voici les règles auxquelles on doit se conformer."],
        explanation: "\"Se conformer à\" → auxquelles; \"respecter\" (direct) → que.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "The friend I lent my car to has had an accident.",
        answer: "L'ami à qui j'ai prêté ma voiture a eu un accident.",
        altAnswers: ["L'amie à qui j'ai prêté ma voiture a eu un accident.", "L'ami auquel j'ai prêté ma voiture a eu un accident.", "L'amie à laquelle j'ai prêté ma voiture a eu un accident."],
        explanation: "\"Prêter quelque chose à quelqu'un\" → \"à qui\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "It's the computer [I work on].",
        sentence: "C'est l'ordinateur ___.",
        answer: "sur lequel je travaille",
        explanation: "\"Travailler sur\" → \"sur lequel\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "It's the result [we were hoping for].",
        sentence: "C'est le résultat ___.",
        answer: "que nous espérions",
        altAnswers: ["qu'on espérait"],
        explanation: "\"Espérer\" is direct ('hope for' has no preposition in French) → que.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "I don't know what he's thinking about.",
        answer: "Je ne sais pas à quoi il pense.",
        altAnswers: ["Je ne sais pas ce à quoi il pense."],
        explanation: "Indirect question \"à quoi il pense\", or the relative \"ce à quoi\".",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: the candidates among whom we will choose",
        words: ["les candidats", "parmi", "lesquels", "nous", "choisirons"],
        translation: "the candidates among whom we will choose",
        explanation: "After \"parmi\", only \"lesquels\", even for people.",
      },
      {
        type: "multiple-choice",
        question: "Which sentence is correct?",
        options: ["C'est le sujet dont il parle sans cesse.", "C'est le sujet qu'il parle sans cesse.", "C'est le sujet auquel il parle sans cesse.", "C'est le sujet de lequel il parle sans cesse."],
        correctIndex: 0,
        explanation: "\"Parler de\" → dont.",
      },
      {
        type: "matching",
        instructions: "Match each verb to its relative.",
        pairs: [
          { left: "se servir de", right: "l'outil dont je me sers" },
          { left: "réfléchir à", right: "la question à laquelle je réfléchis" },
          { left: "compter sur", right: "l'amie sur qui je compte" },
          { left: "utiliser", right: "l'outil que j'utilise" },
        ],
        explanation: "The relative copies the verb's construction.",
      },
      {
        type: "listen-choose",
        audio: "C'est quelqu'un sur qui on peut compter.",
        question: "What does it mean?",
        options: ["He's someone you can rely on.", "He's someone who can count.", "He's someone who relies on us.", "He's someone we counted on once."],
        correctIndex: 0,
        explanation: "\"Compter sur\" → \"sur qui\".",
      },
      {
        type: "speak",
        text: "Ce dont j'ai besoin, c'est d'une semaine de vacances.",
        prompt: "Say it in French: What I need is a week's holiday.",
        explanation: "\"Ce dont\" ... \"c'est de\".",
      },
    ],
  },
  {
    slug: "c1-verb-prepositions-extra-5",
    level: "FR-C1",
    number: 5,
    optional: true,
    title: "Extra Practice: Pronominal Idioms with En and Y",
    summary: "S'en aller, s'en sortir, s'en tenir à, s'en prendre à, s'y prendre, s'y connaître, en vouloir à and ne pas en revenir in everyday situations.",
    duration: "14 min",
    sections: [
      {
        heading: "Recap: frozen pronouns",
        body: [
          "In these idioms en and y replace nothing: \"s'en aller\" (leave), \"s'en sortir\" (cope), \"s'en tenir à\" (stick to), \"s'en prendre à\" (take it out on), \"en vouloir à\" (be angry with), \"s'en vouloir\" (blame yourself), \"s'y prendre\" (go about it), \"s'y connaître\" (know a lot about), \"ne pas en revenir\" (be amazed). Compound tenses use être for the pronominal ones; imperatives: \"va-t'en\", \"tenons-nous-en à\", \"ne m'en veux pas\".",
        ],
        examples: [
          { es: "On s'en va dans cinq minutes.", en: "We're leaving in five minutes." },
          { es: "Elles s'en sont bien sorties malgré la panne.", en: "They coped well despite the breakdown." },
          { es: "Il s'en est pris au serveur pour une erreur de la cuisine.", en: "He took it out on the waiter for a mistake by the kitchen." },
          { es: "Je ne sais pas comment m'y prendre avec ma fille.", en: "I don't know how to handle my daughter." },
          { es: "Elle n'en revenait pas de la gentillesse des habitants.", en: "She couldn't get over how kind the locals were." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "I don't know how to go about it.",
            answer: "Je ne sais pas comment m'y prendre.",
            explanation: "\"S'y prendre\" after \"comment\" + infinitive.",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "They coped well. (women)",
            answer: "Elles s'en sont bien sorties.",
            explanation: "\"S'en sortir\" with être; agreement with elles.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "Go away! (to several people)",
        answer: "Allez-vous-en !",
        explanation: "Vous imperative of \"s'en aller\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "I'm off, see you tomorrow.",
        answer: "Je m'en vais, à demain.",
        altAnswers: ["Je m'en vais, à demain !", "J'y vais, à demain.", "Bon, je m'en vais, à demain."],
        explanation: "\"S'en aller\" = to leave.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "Are you still angry with me? (to a friend)",
        answer: "Tu m'en veux encore ?",
        altAnswers: ["Tu m'en veux toujours ?", "Est-ce que tu m'en veux encore ?", "Est-ce que tu m'en veux toujours ?"],
        explanation: "\"En vouloir à quelqu'un\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "She blames herself for not coming.",
        answer: "Elle s'en veut de ne pas être venue.",
        explanation: "\"S'en vouloir de\" + negated past infinitive.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "Don't take it out on the children.",
        answer: "Ne t'en prends pas aux enfants.",
        altAnswers: ["Ne vous en prenez pas aux enfants."],
        explanation: "\"S'en prendre à\" + aux enfants.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "She knows a lot about cinema.",
        answer: "Elle s'y connaît en cinéma.",
        altAnswers: ["Elle s'y connaît bien en cinéma."],
        explanation: "\"S'y connaître en\" + field.",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "[Let's stick to] the essentials.",
        sentence: "___ à l'essentiel.",
        answer: "Tenons-nous-en",
        explanation: "Nous imperative of \"s'en tenir à\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "[You left it] too late. (to a friend)",
        sentence: "Tu ___ trop tard.",
        answer: "t'y es pris",
        altAnswers: ["t'y es prise"],
        explanation: "\"S'y prendre trop tard\" = to leave it too late.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "I can't believe she said yes!",
        answer: "Je n'en reviens pas qu'elle ait dit oui !",
        altAnswers: ["J'en reviens pas qu'elle ait dit oui !"],
        explanation: "\"Ne pas en revenir que\" + subjunctive.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "I don't hold it against them.",
        answer: "Je ne leur en veux pas.",
        explanation: "\"En vouloir à\" → leur en.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: He always gets by.",
        words: ["Il", "s'en", "sort", "toujours."],
        translation: "He always gets by.",
        explanation: "\"S'en sortir\" = to manage.",
      },
      {
        type: "multiple-choice",
        question: "Your friend apologises for forgetting your party. You say:",
        options: ["Ne t'en fais pas, je ne t'en veux pas.", "Ne t'en va pas, je ne t'en veux pas.", "Ne t'en prends pas, je ne t'en veux pas.", "Ne t'y prends pas, je ne t'en veux pas."],
        correctIndex: 0,
        explanation: "\"Ne t'en fais pas\" (don't worry) + \"je ne t'en veux pas\" (I'm not angry).",
      },
      {
        type: "listen-choose",
        audio: "Tenez-vous-en aux faits.",
        question: "What does it mean?",
        options: ["Stick to the facts.", "Hold on to the facts.", "Take the facts away.", "Keep the facts to yourself."],
        correctIndex: 0,
        explanation: "\"S'en tenir à\" = to stick to.",
      },
      {
        type: "speak",
        text: "Ne m'en veux pas, je dois y aller.",
        prompt: "Say it in French (to a friend): Don't be cross with me, I have to go.",
        explanation: "\"Ne m'en veux pas\" and \"y aller\" (to go, to leave).",
      },
    ],
  },
  {
    slug: "c1-verb-prepositions-extra-6",
    level: "FR-C1",
    number: 6,
    optional: true,
    title: "Extra Practice: Gap-Fill Text of Verb Patterns",
    summary: "A full email with every verb pattern to rebuild: the right preposition, or none, and the right pronoun.",
    duration: "15 min",
    sections: [
      {
        heading: "Recap and the text",
        body: [
          "This practice is one connected email from Julien, who has just moved from Lille to Toulouse, to his friend Sophie. Read it first in full; then, in the review, rebuild each sentence. For every verb, ask: direct, à, de, or another preposition? And if there's a pronoun: y, en, lui, à lui, de lui?",
        ],
        examples: [
          { es: "Chère Sophie, ça fait trois semaines que je suis à Toulouse et je commence à m'y habituer.", en: "Dear Sophie, I've been in Toulouse for three weeks and I'm starting to get used to it." },
          { es: "Lille me manque, surtout nos soirées du vendredi.", en: "I miss Lille, especially our Friday evenings." },
          { es: "Au travail, je m'occupe d'un projet auquel je tiens beaucoup.", en: "At work I'm handling a project that matters a lot to me." },
          { es: "Mon chef tient à ce que tout soit fini en juin, donc je m'efforce de ne pas prendre de retard.", en: "My boss insists that everything be finished in June, so I'm trying hard not to fall behind." },
          { es: "J'ai demandé à ma voisine de m'aider à monter les meubles : je ne m'y connais pas du tout en bricolage !", en: "I asked my neighbour to help me assemble the furniture: I know nothing about DIY!" },
          { es: "Tu m'en veux encore de ne pas être venu à ton anniversaire ? Je m'en veux énormément.", en: "Are you still angry with me for not coming to your birthday? I feel terrible about it." },
        ],
        checkpoint: [
          {
            type: "fill-blank",
            prompt: "Write the French for the bold words.",
            en: "I'm starting [to get used to it].",
            sentence: "Je commence ___.",
            answer: "à m'y habituer",
            explanation: "\"Commencer à\" + \"s'habituer à\" → \"à m'y habituer\".",
          },
          {
            type: "fill-blank",
            prompt: "Write the French for the bold words.",
            en: "[I miss Lille].",
            sentence: "___.",
            answer: "Lille me manque",
            explanation: "Lille is the subject of \"manquer\".",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "I'm handling a project [that matters a lot to me].",
        sentence: "Je m'occupe d'un projet ___.",
        answer: "auquel je tiens beaucoup",
        explanation: "\"Tenir à\" → auquel.",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "My boss [insists that] everything be finished in June.",
        sentence: "Mon chef ___ tout soit fini en juin.",
        answer: "tient à ce que",
        explanation: "\"Tenir à ce que\" + subjunctive.",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "I'm trying hard [not to fall] behind.",
        sentence: "Je m'efforce ___ prendre de retard.",
        answer: "de ne pas",
        explanation: "\"S'efforcer de\" + negated infinitive.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "I asked my neighbour to help me.",
        answer: "J'ai demandé à ma voisine de m'aider.",
        altAnswers: ["J'ai demandé à mon voisin de m'aider."],
        explanation: "\"Demander à quelqu'un de\" + infinitive.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "She helped me assemble the furniture.",
        answer: "Elle m'a aidé à monter les meubles.",
        altAnswers: ["Elle m'a aidée à monter les meubles."],
        explanation: "\"Aider quelqu'un à\": direct person.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "I know nothing about DIY.",
        answer: "Je ne m'y connais pas du tout en bricolage.",
        altAnswers: ["Je n'y connais rien en bricolage.", "Je ne m'y connais pas en bricolage."],
        explanation: "\"S'y connaître en\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "Are you still angry with me for not coming? (to a friend)",
        answer: "Tu m'en veux encore de ne pas être venu ?",
        altAnswers: ["Tu m'en veux encore de ne pas être venue ?", "Tu m'en veux toujours de ne pas être venu ?", "Tu m'en veux toujours de ne pas être venue ?"],
        explanation: "\"En vouloir à quelqu'un de\" + negated past infinitive.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "The flat is small but I'm making the most of the terrace.",
        answer: "L'appartement est petit mais je profite de la terrasse.",
        altAnswers: ["L'appartement est petit, mais je profite de la terrasse.", "L'appartement est petit mais je profite bien de la terrasse.", "L'appartement est petit, mais je profite bien de la terrasse."],
        explanation: "\"Profiter de\" + la terrasse.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "I'm waiting for the internet to be connected.",
        answer: "J'attends qu'on installe internet.",
        altAnswers: ["J'attends que la connexion internet soit installée.", "J'attends qu'internet soit installé.", "J'attends le raccordement à internet."],
        explanation: "\"Attendre\" is direct; with a clause, \"attendre que\" + subjunctive.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "Don't hesitate to visit me in May.",
        answer: "N'hésite pas à venir me voir en mai.",
        altAnswers: ["N'hésitez pas à venir me voir en mai.", "N'hésite pas à me rendre visite en mai.", "N'hésitez pas à me rendre visite en mai."],
        explanation: "\"Hésiter à\" + infinitive; \"rendre visite à\" for people.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "I'm thinking about you and the others.",
        answer: "Je pense à toi et aux autres.",
        explanation: "\"Penser à\" + people: \"à toi\", and the à is repeated before \"aux autres\".",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: I'm counting on you to come.",
        words: ["Je", "compte", "sur", "toi", "pour", "venir."],
        translation: "I'm counting on you to come.",
        explanation: "\"Compter sur quelqu'un pour\" + infinitive.",
      },
      {
        type: "multiple-choice",
        question: "Which sentence from Julien's email is correct?",
        options: ["Je me suis inscrit à un club de rando auquel participent des gens très sympas.", "Je me suis inscrit dans un club de rando auquel participent des gens très sympas.", "Je me suis inscrit à un club de rando que participent des gens très sympas.", "Je me suis inscrit à un club de rando dont participent des gens très sympas."],
        correctIndex: 0,
        explanation: "\"S'inscrire à\" a club; \"participer à\" → auquel (with stylistic inversion of the subject).",
      },
      {
        type: "listen-choose",
        audio: "Lille me manque beaucoup.",
        question: "What does it mean?",
        options: ["I miss Lille a lot.", "Lille misses me a lot.", "I'm missing a lot in Lille.", "Lille lacks a lot."],
        correctIndex: 0,
        explanation: "Lille is the subject: it is missed by me.",
      },
      {
        type: "speak",
        text: "Je commence à m'y habituer.",
        prompt: "Say it in French: I'm starting to get used to it.",
        explanation: "\"Commencer à\" + \"s'y habituer\".",
      },
    ],
  },
];
