// Synced from cheneygross-afk/lengo:src/lib/lessons/fr-c1-u04-extra.ts by scripts/sync-content.mjs -- edit it there, not here.
import type { Lesson } from "./types";

// French C1, Unit 4 extra practice: Infinitive & Participle Constructions.

export const FR_C1_U04_EXTRA: Lesson[] = [
  {
    slug: "c1-participles-infinitives-extra-1",
    level: "FR-C1",
    number: 1,
    optional: true,
    title: "Extra Practice: Participle and Infinitive Constructions, Part 1 of 3",
    summary: "Perfect participles and absolute clauses in new contexts.",
    duration: "13 min",
    sections: [
      {
        heading: "Recap: ayant, étant and the absolute clause",
        body: [
          "Perfect participle, same subject as the main clause: \"ayant\" + participle (\"ayant perdu ses clés, il a appelé un serrurier\"), \"étant\" + agreeing participle for être verbs (\"étant rentrée tard, elle a dormi jusqu'à midi\"), \"s'étant\" for pronominal verbs (\"s'étant trompés de route, ils sont arrivés en retard\").",
          "Absolute clause, own subject: noun + participle (\"le dîner terminé\", \"les invités partis\"), with \"étant\" / \"ayant\" when needed (\"la nuit étant tombée\", \"le maire ayant démissionné\"). \"Une fois\" can introduce it: \"une fois les valises faites\".",
        ],
        examples: [
          { es: "Ayant perdu ses clés, il a appelé un serrurier.", en: "Having lost his keys, he called a locksmith." },
          { es: "Étant rentrée tard, elle a dormi jusqu'à midi.", en: "Having got home late, she slept until noon." },
          { es: "S'étant trompés de route, ils sont arrivés en retard.", en: "Having taken the wrong road, they arrived late." },
          { es: "Le maire ayant démissionné, de nouvelles élections auront lieu.", en: "As the mayor has resigned, new elections will be held." },
          { es: "Une fois les valises faites, nous avons appelé un taxi.", en: "Once the cases were packed, we called a taxi." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French with a perfect participle.",
            source: "Having missed the train, she took a taxi.",
            answer: "Ayant raté le train, elle a pris un taxi.",
            altAnswers: ["Ayant manqué le train, elle a pris un taxi.", "Ayant loupé le train, elle a pris un taxi."],
            explanation: "\"Ayant\" + participle; same subject (\"elle\").",
          },
          {
            type: "fill-blank",
            prompt: "Write the French for the bold words.",
            en: "[Once the dinner was over], the guests went into the garden.",
            sentence: "___, les invités sont passés au jardin.",
            answer: "Le dîner terminé",
            altAnswers: ["Une fois le dîner terminé", "Le dîner fini", "Une fois le dîner fini", "Le repas terminé", "Une fois le repas terminé"],
            explanation: "Absolute clause: noun + participle.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French with a perfect participle.",
        source: "Having read the report, the minister made a statement.",
        answer: "Ayant lu le rapport, le ministre a fait une déclaration.",
        altAnswers: ["Ayant lu le rapport, la ministre a fait une déclaration.", "Après avoir lu le rapport, le ministre a fait une déclaration."],
        explanation: "\"Ayant lu\": completed before the main action.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French with a perfect participle.",
        source: "Having arrived early, the girls waited in the café.",
        answer: "Étant arrivées en avance, les filles ont attendu au café.",
        altAnswers: ["Arrivées en avance, les filles ont attendu au café.", "Étant arrivées tôt, les filles ont attendu au café.", "Arrivées tôt, les filles ont attendu au café."],
        explanation: "\"Étant\" + participle agreeing in the feminine plural.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French with a perfect participle.",
        source: "Not having understood the question, he didn't answer.",
        answer: "N'ayant pas compris la question, il n'a pas répondu.",
        altAnswers: ["N'ayant pas compris la question, il n'a rien répondu."],
        explanation: "Negation around \"ayant\": \"n'ayant pas\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French with a perfect participle.",
        source: "Having lost their way, the hikers called for help.",
        answer: "S'étant perdus, les randonneurs ont appelé les secours.",
        altAnswers: ["Ayant perdu leur chemin, les randonneurs ont appelé les secours.", "S'étant égarés, les randonneurs ont appelé les secours.", "S'étant perdus, les randonneurs ont appelé à l'aide."],
        explanation: "Pronominal: \"s'étant perdus\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French with an absolute clause.",
        source: "Once the children were asleep, we opened a bottle of wine.",
        answer: "Les enfants endormis, nous avons ouvert une bouteille de vin.",
        altAnswers: ["Une fois les enfants endormis, nous avons ouvert une bouteille de vin.", "Les enfants couchés, nous avons ouvert une bouteille de vin.", "Une fois les enfants couchés, nous avons ouvert une bouteille de vin.", "Une fois les enfants endormis, on a ouvert une bouteille de vin."],
        explanation: "Own subject → absolute clause.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French with an absolute clause.",
        source: "As night had fallen, we lit a fire.",
        answer: "La nuit étant tombée, nous avons allumé un feu.",
        altAnswers: ["La nuit tombée, nous avons allumé un feu.", "La nuit étant tombée, on a allumé un feu.", "Une fois la nuit tombée, nous avons allumé un feu."],
        explanation: "\"La nuit étant tombée\": own subject + \"étant\" + agreeing participle.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French with an absolute clause.",
        source: "As the company had gone bankrupt, the employees lost their jobs.",
        answer: "L'entreprise ayant fait faillite, les employés ont perdu leur emploi.",
        altAnswers: ["L'entreprise ayant fait faillite, les salariés ont perdu leur emploi.", "La société ayant fait faillite, les employés ont perdu leur emploi.", "L'entreprise ayant fait faillite, les employés ont perdu leur travail."],
        explanation: "Avoir verb with its own subject → \"ayant\" + participle.",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "[Having got up] at dawn, she was exhausted by noon.",
        sentence: "___ à l'aube, elle était épuisée à midi.",
        answer: "S'étant levée",
        explanation: "Pronominal, feminine: \"s'étant levée\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "[The decision taken], nobody could change it.",
        sentence: "___, personne ne pouvait la changer.",
        answer: "La décision prise",
        altAnswers: ["Une fois la décision prise"],
        explanation: "\"Prise\" agrees with \"la décision\".",
      },
      {
        type: "multiple-choice",
        question: "Which sentence is correct?",
        options: [
          "Les travaux étant terminés, le musée a rouvert.",
          "Les travaux ayant terminés, le musée a rouvert.",
          "Les travaux étant terminé, le musée a rouvert.",
          "Ayant terminé les travaux, le musée a rouvert.",
        ],
        correctIndex: 0,
        explanation: "\"Étant terminés\" agrees; the last one dangles (the museum didn't do the work).",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: Once the rain had stopped, we went out.",
        words: ["La", "pluie", "ayant", "cessé,", "nous", "sommes", "sortis."],
        translation: "Once the rain had stopped, we went out.",
        explanation: "\"Cesser\" takes avoir → \"ayant cessé\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French with a perfect participle.",
        source: "Having always lived in the country, he hates the city.",
        answer: "Ayant toujours vécu à la campagne, il déteste la ville.",
        altAnswers: ["Ayant toujours habité à la campagne, il déteste la ville."],
        explanation: "\"Toujours\" goes between \"ayant\" and the participle.",
      },
      {
        type: "listen-choose",
        audio: "Le directeur s'étant absenté, la réunion a été reportée.",
        question: "Why was the meeting postponed?",
        options: ["Because the director was away.", "Because the director cancelled it.", "Because the director was late.", "Because the director was ill."],
        correctIndex: 0,
        explanation: "\"S'étant absenté\" = having gone away / being absent.",
      },
      {
        type: "speak",
        text: "N'ayant pas reçu de réponse, je me permets de vous relancer.",
        prompt: "Say it in French (formal email): Not having received a reply, I'm following up.",
        explanation: "Classic formal email phrase with a perfect participle.",
      },
    ],
  },
  {
    slug: "c1-participles-infinitives-extra-2",
    level: "FR-C1",
    number: 2,
    optional: true,
    title: "Extra Practice: Participle and Infinitive Constructions, Part 2 of 3",
    summary: "Infinitive clauses and the infinitive as subject.",
    duration: "13 min",
    sections: [
      {
        heading: "Recap: same-subject infinitives and infinitive subjects",
        body: [
          "Same subject → infinitive instead of \"que\": \"je pense avoir raison\", \"elle dit l'avoir lu\", \"j'espère réussir\". Past infinitive for anteriority, after \"après\", and after \"pour\" for a cause (\"puni pour avoir triché\"); \"sans\" + present or past infinitive.",
          "Infinitive as subject (\"Mentir ne sert à rien\", \"Partir, c'est...\"), in instructions (\"Ne pas toucher\") and in deliberative questions (\"Que dire ?\", \"À quoi bon...\").",
        ],
        examples: [
          { es: "Je pense avoir raison.", en: "I think I'm right." },
          { es: "Elle dit l'avoir lu deux fois.", en: "She says she's read it twice." },
          { es: "L'élève a été puni pour avoir triché.", en: "The pupil was punished for cheating." },
          { es: "Mentir ne sert à rien.", en: "Lying is useless." },
          { es: "Que dire de plus ?", en: "What more is there to say?" },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French with an infinitive.",
            source: "She says she has already paid.",
            answer: "Elle dit avoir déjà payé.",
            altAnswers: ["Elle affirme avoir déjà payé.", "Elle dit qu'elle a déjà payé."],
            explanation: "Same subject → past infinitive; \"déjà\" between \"avoir\" and the participle.",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "Lying is useless.",
            answer: "Mentir ne sert à rien.",
            altAnswers: ["Mentir est inutile.", "Mentir, ça ne sert à rien.", "Il est inutile de mentir.", "Ça ne sert à rien de mentir."],
            explanation: "Infinitive subject.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French with an infinitive.",
        source: "I hope to see you soon.",
        answer: "J'espère te voir bientôt.",
        altAnswers: ["J'espère vous voir bientôt.", "J'espère te revoir bientôt.", "J'espère vous revoir bientôt.", "J'espère te voir bientôt !"],
        explanation: "\"Espérer\" + infinitive (no \"de\").",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French with an infinitive.",
        source: "He thinks he's made a mistake.",
        answer: "Il pense avoir fait une erreur.",
        altAnswers: ["Il croit avoir fait une erreur.", "Il pense s'être trompé.", "Il croit s'être trompé.", "Il pense avoir commis une erreur."],
        explanation: "Same subject → past infinitive.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French with an infinitive.",
        source: "The suspect denies being at the scene.",
        answer: "Le suspect nie avoir été sur les lieux.",
        altAnswers: ["Le suspect nie s'être trouvé sur les lieux.", "Le suspect nie avoir été présent sur les lieux."],
        explanation: "\"Nier\" + past infinitive.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "After sitting down, she opened her book.",
        answer: "Après s'être assise, elle a ouvert son livre.",
        explanation: "\"Après s'être\" + agreeing participle.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "The driver was arrested for running a red light.",
        answer: "Le conducteur a été arrêté pour avoir grillé un feu rouge.",
        altAnswers: ["Le conducteur a été interpellé pour avoir grillé un feu rouge.", "Le conducteur a été arrêté pour avoir brûlé un feu rouge.", "La conductrice a été arrêtée pour avoir grillé un feu rouge."],
        explanation: "Cause → \"pour avoir\" + participle.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "Waiting is the hardest part.",
        answer: "Attendre, c'est le plus difficile.",
        altAnswers: ["Attendre est le plus difficile.", "Le plus difficile, c'est d'attendre.", "L'attente est le plus difficile."],
        explanation: "Infinitive subject, often with \"c'est\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate this sign into French.",
        source: "Do not walk on the grass.",
        answer: "Ne pas marcher sur la pelouse.",
        altAnswers: ["Ne pas marcher sur l'herbe.", "Pelouse interdite."],
        explanation: "Negative infinitive.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French with a bare infinitive.",
        source: "What to say to him?",
        answer: "Que lui dire ?",
        altAnswers: ["Quoi lui dire ?"],
        explanation: "Deliberative infinitive; pronoun before the infinitive.",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "Thank you [for helping] me yesterday.",
        sentence: "Merci ___ hier.",
        answer: "de m'avoir aidé",
        altAnswers: ["de m'avoir aidée"],
        explanation: "\"Merci de\" + past infinitive.",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "[What's the point of] crying?",
        sentence: "___ pleurer ?",
        answer: "À quoi bon",
        explanation: "\"À quoi bon\" + infinitive.",
      },
      {
        type: "multiple-choice",
        question: "Which sentence expresses a purpose?",
        options: [
          "Il économise pour acheter une maison.",
          "Il a été félicité pour avoir acheté une maison.",
          "Il a été critiqué pour avoir acheté une maison.",
          "Il a été récompensé pour avoir sauvé une maison.",
        ],
        correctIndex: 0,
        explanation: "\"Pour\" + present infinitive = purpose; + past infinitive = cause.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: I don't remember having seen this film.",
        words: ["Je", "ne", "me", "souviens", "pas", "d'avoir", "vu", "ce", "film."],
        translation: "I don't remember having seen this film.",
        explanation: "\"Se souvenir d'avoir\" + participle.",
      },
      {
        type: "listen-choose",
        audio: "Il prétend n'avoir rien entendu.",
        question: "What does he claim?",
        options: ["That he heard nothing.", "That he heard everything.", "That nobody heard him.", "That he will hear nothing."],
        correctIndex: 0,
        explanation: "\"Prétendre\" + negative past infinitive: \"n'avoir rien entendu\".",
      },
      {
        type: "speak",
        text: "Partir, c'est mourir un peu.",
        prompt: "Say it in French: To leave is to die a little.",
        explanation: "Infinitive subject picked up by \"c'est\".",
      },
    ],
  },
  {
    slug: "c1-participles-infinitives-extra-3",
    level: "FR-C1",
    number: 3,
    optional: true,
    title: "Extra Practice: Participle and Infinitive Constructions, Part 3 of 3",
    summary: "Perception verbs and participle agreement before an infinitive.",
    duration: "13 min",
    sections: [
      {
        heading: "Recap: perception verbs, fait and laissé",
        body: [
          "Perception verbs and \"laisser\" + infinitive: \"J'entends les enfants rire\" / \"J'entends rire les enfants\"; pronoun before the main verb: \"Je les entends rire.\" Keep the noun before an infinitive that has its own object: \"J'ai vu Marc ouvrir la porte.\"",
          "Agreement test: does the preceding object perform the infinitive's action? Yes → agreement (\"la pianiste que j'ai entendue jouer\"). No → no agreement (\"la sonate que j'ai entendu jouer\"). \"Fait\" + infinitive never agrees; \"laissé\" + infinitive is invariable in modern spelling.",
        ],
        examples: [
          { es: "J'entends rire les enfants.", en: "I can hear the children laughing." },
          { es: "J'ai vu Marc ouvrir la porte.", en: "I saw Marc open the door." },
          { es: "La pianiste que j'ai entendue jouer était bouleversante.", en: "The pianist I heard playing was deeply moving." },
          { es: "La sonate que j'ai entendu jouer était de Debussy.", en: "The sonata I heard played was by Debussy." },
          { es: "Ils se sont fait piéger.", en: "They were tricked." },
        ],
        checkpoint: [
          {
            type: "fill-blank",
            prompt: "Write the French for the bold words.",
            en: "The birds [I saw] fly away were swallows.",
            sentence: "Les oiseaux que ___ s'envoler étaient des hirondelles.",
            answer: "j'ai vus",
            explanation: "The birds fly away → agreement.",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French (she).",
            source: "She let herself be tempted.",
            answer: "Elle s'est laissé tenter.",
            altAnswers: ["Elle s'est laissée tenter."],
            explanation: "Modern spelling: \"laissé\" invariable (the old agreement is tolerated).",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "I felt the ground shake.",
        answer: "J'ai senti le sol trembler.",
        altAnswers: ["J'ai senti trembler le sol.", "J'ai senti la terre trembler.", "J'ai senti trembler la terre."],
        explanation: "\"Sentir\" + infinitive; two word orders.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "We heard someone knock at the door.",
        answer: "Nous avons entendu quelqu'un frapper à la porte.",
        altAnswers: ["On a entendu quelqu'un frapper à la porte.", "Nous avons entendu frapper à la porte.", "On a entendu frapper à la porte."],
        explanation: "Perception verb + infinitive.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "Let her sleep!",
        answer: "Laisse-la dormir !",
        altAnswers: ["Laissez-la dormir !"],
        explanation: "\"Laisser\" + pronoun + infinitive.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "I watched them leave.",
        answer: "Je les ai regardés partir.",
        altAnswers: ["Je les ai regardées partir.", "Je les ai vus partir.", "Je les ai vues partir."],
        explanation: "They leave → agreement with \"les\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "The actresses [we saw] perform were superb.",
        sentence: "Les actrices que ___ jouer étaient superbes.",
        answer: "nous avons vues",
        altAnswers: ["on a vues"],
        explanation: "The actresses perform → feminine plural agreement.",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "The plays [we saw] performed were by Moliere.",
        sentence: "Les pièces que ___ jouer étaient de Molière.",
        answer: "nous avons vu",
        altAnswers: ["on a vu"],
        explanation: "The plays are performed → no agreement.",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "The trees [I saw] being cut down were very old.",
        sentence: "Les arbres que ___ abattre étaient très vieux.",
        answer: "j'ai vu",
        explanation: "The trees don't cut → no agreement.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French (she).",
        source: "She had her car repaired.",
        answer: "Elle a fait réparer sa voiture.",
        altAnswers: ["Elle a fait réparer sa voiture au garage."],
        explanation: "\"Faire\" + infinitive.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French (they, feminine).",
        source: "They got conned.",
        answer: "Elles se sont fait avoir.",
        altAnswers: ["Elles se sont fait arnaquer.", "Elles se sont fait escroquer."],
        explanation: "\"Fait\" + infinitive never agrees.",
      },
      {
        type: "multiple-choice",
        question: "Which sentence is correctly spelled?",
        options: [
          "Les chanteurs que j'ai entendus chanter venaient de Dakar.",
          "Les chanteurs que j'ai entendu chanter venaient de Dakar.",
          "Les chanteurs que j'ai entendue chanter venaient de Dakar.",
          "Les chanteurs que j'ai entendues chanter venaient de Dakar.",
        ],
        correctIndex: 0,
        explanation: "The singers sing → masculine plural agreement.",
      },
      {
        type: "multiple-choice",
        question: "Which sentence is correctly spelled?",
        options: [
          "Elle s'est fait couper les cheveux.",
          "Elle s'est faite couper les cheveux.",
          "Elle s'est faits couper les cheveux.",
          "Elle a fait se couper les cheveux.",
        ],
        correctIndex: 0,
        explanation: "\"Fait\" + infinitive: always invariable.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: I saw the children cross the street.",
        words: ["J'ai", "vu", "les", "enfants", "traverser", "la", "rue."],
        translation: "I saw the children cross the street.",
        explanation: "The infinitive has an object, so the noun goes before it.",
      },
      {
        type: "listen-choose",
        audio: "La chanson que j'ai entendu chanter était en créole.",
        question: "What was in Creole?",
        options: ["The song I heard sung.", "The singer I heard.", "The song I sang.", "The singer who heard me."],
        correctIndex: 0,
        explanation: "The song is sung → \"entendu\" (no agreement).",
      },
      {
        type: "speak",
        text: "Je les ai vus jouer à Montréal.",
        prompt: "Say it in French: I saw them play in Montreal.",
        explanation: "Perception verb + infinitive; pronoun before \"ai\".",
      },
    ],
  },
  {
    slug: "c1-participles-infinitives-extra-4",
    level: "FR-C1",
    number: 4,
    optional: true,
    title: "Extra Practice: Dangling Participles",
    summary: "Spotting and fixing participles and gérondifs with the wrong subject.",
    duration: "13 min",
    sections: [
      {
        heading: "Recap: who is doing the action?",
        body: [
          "A participle or gérondif at the start of a sentence refers to the subject of the main clause. \"*En sortant du métro, la pluie a commencé\" means the rain came out of the metro. Fix it by changing the subject (\"En sortant du métro, j'ai vu qu'il pleuvait\"), using a full clause (\"Quand je suis sorti du métro, la pluie a commencé\") or a noun (\"À ma sortie du métro, ...\").",
          "The same goes for \"étant\" and \"ayant\": \"*Étant malade, le médecin m'a prescrit des antibiotiques\" makes the doctor ill. Fix: \"Comme j'étais malade, le médecin m'a prescrit...\" or \"Étant malade, je suis allé chez le médecin, qui m'a prescrit...\"",
        ],
        examples: [
          { es: "En sortant du métro, j'ai vu qu'il pleuvait.", en: "Coming out of the metro, I saw it was raining." },
          { es: "Quand je suis sorti du métro, il a commencé à pleuvoir.", en: "When I came out of the metro, it started to rain." },
          { es: "Comme j'étais malade, le médecin m'a prescrit des antibiotiques.", en: "As I was ill, the doctor prescribed me antibiotics." },
          { es: "À mon arrivée, la réunion avait déjà commencé.", en: "When I arrived, the meeting had already started." },
          { es: "En attendant ta réponse, je t'embrasse.", en: "Looking forward to your reply, love." },
        ],
        checkpoint: [
          {
            type: "multiple-choice",
            question: "Which sentence is correct?",
            options: [
              "En ouvrant la porte, j'ai vu un chat.",
              "En ouvrant la porte, un chat est entré.",
              "Ouvrant la porte, un chat m'attendait.",
              "Ayant ouvert la porte, un chat est apparu.",
            ],
            correctIndex: 0,
            explanation: "Only in the first does the subject (\"je\") open the door.",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French without a dangling gérondif.",
            source: "When we landed, it was snowing.",
            answer: "Quand nous avons atterri, il neigeait.",
            altAnswers: ["Quand on a atterri, il neigeait.", "À notre atterrissage, il neigeait.", "Lorsque nous avons atterri, il neigeait.", "À l'atterrissage, il neigeait."],
            explanation: "\"*En atterrissant, il neigeait\" would dangle; use a clause or a noun.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French without a dangling gérondif.",
        source: "When I got home, the house was empty.",
        answer: "Quand je suis rentré, la maison était vide.",
        altAnswers: ["Quand je suis rentrée, la maison était vide.", "À mon retour, la maison était vide.", "En rentrant, j'ai trouvé la maison vide.", "Lorsque je suis rentré, la maison était vide.", "Lorsque je suis rentrée, la maison était vide."],
        explanation: "Subjects differ (je / la maison) → clause or noun, or change the main subject.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French without a dangling participle.",
        source: "As I was tired, my colleague drove.",
        answer: "Comme j'étais fatigué, c'est mon collègue qui a conduit.",
        altAnswers: ["Comme j'étais fatiguée, c'est mon collègue qui a conduit.", "Comme j'étais fatigué, mon collègue a conduit.", "Comme j'étais fatiguée, mon collègue a conduit.", "Comme j'étais fatigué, ma collègue a conduit.", "Comme j'étais fatiguée, ma collègue a conduit."],
        explanation: "\"*Étant fatigué, mon collègue a conduit\" would make the colleague tired.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French with a gérondif and the right subject.",
        source: "Crossing the bridge, we saw the cathedral.",
        answer: "En traversant le pont, nous avons vu la cathédrale.",
        altAnswers: ["En traversant le pont, on a vu la cathédrale.", "En traversant le pont, nous avons aperçu la cathédrale.", "En traversant le pont, on a aperçu la cathédrale."],
        explanation: "Same subject (\"nous\") → gérondif is fine.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French with a noun phrase.",
        source: "When she left, everyone applauded.",
        answer: "À son départ, tout le monde a applaudi.",
        altAnswers: ["Lors de son départ, tout le monde a applaudi.", "Quand elle est partie, tout le monde a applaudi."],
        explanation: "A noun (\"à son départ\") avoids the subject problem.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French without a dangling participle.",
        source: "Having checked the figures, the accountant found an error.",
        answer: "Ayant vérifié les chiffres, le comptable a trouvé une erreur.",
        altAnswers: ["Après avoir vérifié les chiffres, le comptable a trouvé une erreur.", "Ayant vérifié les chiffres, la comptable a trouvé une erreur.", "Après avoir vérifié les chiffres, la comptable a trouvé une erreur.", "Ayant vérifié les chiffres, le comptable a découvert une erreur."],
        explanation: "Same subject (the accountant) → correct.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French correctly.",
        source: "While I was cooking, the phone rang.",
        answer: "Pendant que je cuisinais, le téléphone a sonné.",
        altAnswers: ["Pendant que je faisais la cuisine, le téléphone a sonné.", "Alors que je cuisinais, le téléphone a sonné.", "Pendant que je préparais le repas, le téléphone a sonné."],
        explanation: "\"*En cuisinant, le téléphone a sonné\" dangles.",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "[When we arrived], the shop was closed.",
        sentence: "___, le magasin était fermé.",
        answer: "À notre arrivée",
        altAnswers: ["Quand nous sommes arrivés", "Quand on est arrivés", "Lorsque nous sommes arrivés", "Quand nous sommes arrivées"],
        explanation: "Noun phrase or full clause, not \"en arrivant\".",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "Reading the letter, [she started] to cry.",
        sentence: "En lisant la lettre, ___ à pleurer.",
        answer: "elle s'est mise",
        altAnswers: ["elle a commencé"],
        explanation: "The subject of the main clause must be the reader.",
      },
      {
        type: "multiple-choice",
        question: "Which sentence dangles?",
        options: [
          "Arrivés à l'hôtel, la chambre n'était pas prête.",
          "Arrivés à l'hôtel, nous avons appris que la chambre n'était pas prête.",
          "À notre arrivée à l'hôtel, la chambre n'était pas prête.",
          "Quand nous sommes arrivés à l'hôtel, la chambre n'était pas prête.",
        ],
        correctIndex: 0,
        explanation: "The room didn't arrive at the hotel.",
      },
      {
        type: "multiple-choice",
        question: "Which is the best fix for: *Étant en retard, le professeur m'a puni?",
        options: [
          "Comme j'étais en retard, le professeur m'a puni.",
          "Étant en retard, le professeur m'a puni moi.",
          "En étant en retard, le professeur m'a puni.",
          "Le professeur, étant en retard, m'a puni.",
        ],
        correctIndex: 0,
        explanation: "A full clause makes \"je\" the late one; the last option changes the meaning.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French correctly.",
        source: "Being a doctor, she knows the risks.",
        answer: "Étant médecin, elle connaît les risques.",
        altAnswers: ["Comme elle est médecin, elle connaît les risques.", "En tant que médecin, elle connaît les risques."],
        explanation: "Same subject (\"elle\") → correct participle.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: On leaving the cinema, we met Paul.",
        words: ["En", "sortant", "du", "cinéma,", "nous", "avons", "croisé", "Paul."],
        translation: "On leaving the cinema, we met Paul.",
        explanation: "The gérondif's subject is \"nous\".",
      },
      {
        type: "listen-choose",
        audio: "À ma sortie de l'hôpital, il faisait un temps magnifique.",
        question: "What does it mean?",
        options: [
          "When I left the hospital, the weather was wonderful.",
          "The weather was wonderful when I went into hospital.",
          "I left hospital because the weather was wonderful.",
          "The hospital was closed because of the weather.",
        ],
        correctIndex: 0,
        explanation: "\"À ma sortie\" = when I came out.",
      },
      {
        type: "speak",
        text: "En sortant du métro, j'ai vu qu'il pleuvait.",
        prompt: "Say it in French: Coming out of the metro, I saw it was raining.",
        explanation: "Same subject for the gérondif and the main verb.",
      },
    ],
  },
  {
    slug: "c1-participles-infinitives-extra-5",
    level: "FR-C1",
    number: 5,
    optional: true,
    title: "Extra Practice: Aspect Periphrases",
    summary: "Continuer à, cesser de, finir par, ne faire que, aller en + participle.",
    duration: "13 min",
    sections: [
      {
        heading: "Recap: beginning, continuing, ending",
        body: [
          "\"Continuer à / de\" (keep on), \"ne cesser de\" (formal: keep on), \"arrêter de\" (stop), \"se remettre à\" (start again), \"finir de\" (finish doing) vs \"finir par\" (end up doing), \"être en passe de\" (be about to, on the way to).",
          "Progress and repetition: \"être en train de\" (in the middle of, only when the emphasis matters), \"aller en\" + participle (gradual trend), \"ne faire que\" + infinitive (do nothing but / only), \"ne pas arrêter de\" (keep on, informal).",
        ],
        examples: [
          { es: "Elle a fini par accepter.", en: "She ended up accepting." },
          { es: "J'ai fini de ranger la cuisine.", en: "I've finished tidying the kitchen." },
          { es: "Il s'est remis à fumer.", en: "He's started smoking again." },
          { es: "L'entreprise est en passe de devenir leader du marché.", en: "The company is on its way to becoming the market leader." },
          { es: "Les tensions vont en s'aggravant.", en: "Tensions are steadily worsening." },
        ],
        checkpoint: [
          {
            type: "fill-blank",
            prompt: "Write the French for the bold words.",
            en: "After an hour, he [ended up] admitting everything.",
            sentence: "Au bout d'une heure, il a ___ tout avouer.",
            answer: "fini par",
            explanation: "\"Finir par\" = end up doing.",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "It started raining again.",
            answer: "Il s'est remis à pleuvoir.",
            altAnswers: ["Il a recommencé à pleuvoir.", "La pluie a repris."],
            explanation: "\"Se remettre à\" = start again.",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "Have you finished eating?",
        answer: "Tu as fini de manger ?",
        altAnswers: ["As-tu fini de manger ?", "Vous avez fini de manger ?", "Avez-vous fini de manger ?", "Est-ce que tu as fini de manger ?"],
        explanation: "\"Finir de\" = complete an activity.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "We ended up selling the house.",
        answer: "Nous avons fini par vendre la maison.",
        altAnswers: ["On a fini par vendre la maison.", "Nous avons fini par vendre notre maison.", "On a fini par vendre notre maison."],
        explanation: "\"Finir par\" = end up.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "She kept on working despite the noise.",
        answer: "Elle a continué à travailler malgré le bruit.",
        altAnswers: ["Elle a continué de travailler malgré le bruit.", "Elle n'a pas arrêté de travailler malgré le bruit."],
        explanation: "\"Continuer à / de\" + infinitive.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into formal French.",
        source: "The number of visitors keeps increasing.",
        answer: "Le nombre de visiteurs ne cesse d'augmenter.",
        altAnswers: ["Le nombre de visiteurs va en augmentant.", "Le nombre de visiteurs ne cesse de croître.", "Le nombre de visiteurs ne cesse pas d'augmenter."],
        explanation: "\"Ne cesser de\" (no \"pas\") or \"aller en augmentant\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "I've stopped drinking coffee.",
        answer: "J'ai arrêté de boire du café.",
        altAnswers: ["J'ai arrêté le café.", "J'ai cessé de boire du café."],
        explanation: "\"Arrêter de\" + infinitive. \"Du café\" stays: \"arrêter\" isn't a grammatical negation.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French with ne faire que.",
        source: "All she does is work.",
        answer: "Elle ne fait que travailler.",
        altAnswers: ["Elle ne fait rien d'autre que travailler.", "Elle passe son temps à travailler."],
        explanation: "\"Ne faire que\" = nothing but.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French with aller en.",
        source: "His condition is gradually improving.",
        answer: "Son état va en s'améliorant.",
        altAnswers: ["Son état s'améliore progressivement.", "Son état s'améliore peu à peu."],
        explanation: "Trend → \"aller en s'améliorant\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French naturally.",
        source: "I'm reading a novel by Annie Ernaux.",
        answer: "Je lis un roman d'Annie Ernaux.",
        altAnswers: ["Je suis en train de lire un roman d'Annie Ernaux."],
        explanation: "The simple present is the natural choice; \"en train de\" is possible but emphatic.",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "The project [is on the way to] succeeding.",
        sentence: "Le projet est ___ réussir.",
        answer: "en passe de",
        altAnswers: ["en voie de", "en train de"],
        explanation: "\"Être en passe de\" = on the way to.",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "The phone [kept ringing] all morning.",
        sentence: "Le téléphone ___ sonner toute la matinée.",
        answer: "n'a pas arrêté de",
        altAnswers: ["n'a cessé de", "n'a pas cessé de", "n'a fait que"],
        explanation: "\"Ne pas arrêter de\" = keep on.",
      },
      {
        type: "multiple-choice",
        question: "« J'ai fini de lire ton roman » means:",
        options: ["I've finished reading your novel.", "I ended up reading your novel.", "I stopped reading your novel halfway.", "I'm still reading your novel."],
        correctIndex: 0,
        explanation: "\"Finir de\" = complete; \"finir par\" = end up.",
      },
      {
        type: "matching",
        instructions: "Match each French phrase with its English meaning.",
        pairs: [
          { left: "se remettre à", right: "to start again" },
          { left: "finir par", right: "to end up" },
          { left: "ne cesser de", right: "to keep on (formal)" },
          { left: "être en passe de", right: "to be on the way to" },
        ],
        explanation: "Four aspect periphrases.",
      },
      {
        type: "listen-choose",
        audio: "Il ne fait que passer, il repart demain.",
        question: "What does it mean?",
        options: ["He's only passing through; he leaves tomorrow.", "He keeps coming back; he'll be here tomorrow.", "He never stops by; he leaves tomorrow.", "He's just left and will be back tomorrow."],
        correctIndex: 0,
        explanation: "\"Ne faire que passer\" = only passing through.",
      },
      {
        type: "speak",
        text: "Elle a fini par accepter notre proposition.",
        prompt: "Say it in French: She ended up accepting our proposal.",
        explanation: "\"Finir par\" + infinitive.",
      },
    ],
  },
  {
    slug: "c1-participles-infinitives-extra-6",
    level: "FR-C1",
    number: 6,
    optional: true,
    title: "Extra Practice: The Infinitive and English -ing",
    summary: "Translating -ing sentences into natural French.",
    duration: "14 min",
    sections: [
      {
        heading: "Recap: five questions for every -ing",
        body: [
          "(1) After a preposition? → infinitive (\"avant de partir\", \"sans rien dire\", \"au lieu de\"), past infinitive after \"après\"; only \"en\" takes the participle (\"en travaillant\"). (2) After a verb? → infinitive, with or without \"de\" / \"à\" (\"j'aime lire\", \"j'ai arrêté de fumer\", \"je passe mon temps à lire\").",
          "(3) As a subject? → infinitive or noun (\"Nager me détend\", \"La natation me détend\"). (4) After perception? → infinitive or \"qui\" + imperfect (\"je l'ai vu partir / qui partait\"). (5) Describing a position or a noun? → past participle (\"assis\", \"couché\") or relative clause. And a progressive tense → simple tense.",
        ],
        examples: [
          { es: "Il est parti sans rien dire.", en: "He left without saying anything." },
          { es: "Je passe mon temps à lire.", en: "I spend my time reading." },
          { es: "La natation me détend.", en: "Swimming relaxes me." },
          { es: "Je l'ai vue qui pleurait dans le couloir.", en: "I saw her crying in the corridor." },
          { es: "Le chat dormait, couché au soleil.", en: "The cat was asleep, lying in the sun." },
          { es: "Je t'écris de Marseille.", en: "I'm writing to you from Marseille." },
        ],
        checkpoint: [
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "Instead of waiting, let's start.",
            answer: "Au lieu d'attendre, commençons.",
            altAnswers: ["Plutôt que d'attendre, commençons.", "Au lieu d'attendre, on commence."],
            explanation: "\"Au lieu de\" + infinitive.",
          },
          {
            type: "translate",
            direction: "en-es",
            prompt: "Translate into French.",
            source: "The girl standing near the door is my niece.",
            answer: "La fille debout près de la porte est ma nièce.",
            altAnswers: ["La fille qui est debout près de la porte est ma nièce.", "La jeune fille debout près de la porte est ma nièce.", "La fille debout à côté de la porte est ma nièce."],
            explanation: "Position → \"debout\" (invariable).",
          },
        ],
      },
    ],
    exercises: [
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "Wash your hands before eating.",
        answer: "Lave-toi les mains avant de manger.",
        altAnswers: ["Lavez-vous les mains avant de manger.", "Se laver les mains avant de manger."],
        explanation: "\"Avant de\" + infinitive.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "I hate getting up early.",
        answer: "Je déteste me lever tôt.",
        altAnswers: ["J'ai horreur de me lever tôt.", "Je déteste me lever de bonne heure."],
        explanation: "Verb of liking + infinitive; reflexive pronoun matches \"je\".",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "She succeeded by working hard.",
        answer: "Elle a réussi en travaillant dur.",
        altAnswers: ["Elle a réussi en travaillant beaucoup.", "C'est en travaillant dur qu'elle a réussi."],
        explanation: "Means → \"en\" + participle.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "It's no use shouting.",
        answer: "Ça ne sert à rien de crier.",
        altAnswers: ["Il ne sert à rien de crier.", "Crier ne sert à rien.", "Inutile de crier.", "C'est inutile de crier."],
        explanation: "\"Ça ne sert à rien de\" + infinitive.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "He apologised for being late.",
        answer: "Il s'est excusé d'être arrivé en retard.",
        altAnswers: ["Il s'est excusé pour son retard.", "Il s'est excusé d'être en retard.", "Il s'est excusé de son retard."],
        explanation: "\"S'excuser de\" + past infinitive, or a noun.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "We're looking forward to seeing the sea.",
        answer: "Nous avons hâte de voir la mer.",
        altAnswers: ["On a hâte de voir la mer.", "Nous nous réjouissons de voir la mer."],
        explanation: "\"Avoir hâte de\" + infinitive.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "I heard him coming up the stairs.",
        answer: "Je l'ai entendu monter l'escalier.",
        altAnswers: ["Je l'ai entendu qui montait l'escalier.", "Je l'ai entendu monter les escaliers.", "Je l'ai entendu qui montait les escaliers."],
        explanation: "Perception + infinitive, or \"qui\" + imperfect.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "Is it worth reading?",
        answer: "Ça vaut la peine de le lire ?",
        altAnswers: ["Est-ce que ça vaut la peine de le lire ?", "Ça vaut le coup de le lire ?", "Est-ce que ça vaut le coup de le lire ?", "Ça vaut la peine d'être lu ?"],
        explanation: "\"Valoir la peine de\" + infinitive.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "There's a letter waiting for you on the table.",
        answer: "Il y a une lettre qui t'attend sur la table.",
        altAnswers: ["Il y a une lettre qui vous attend sur la table.", "Une lettre t'attend sur la table.", "Une lettre vous attend sur la table."],
        explanation: "-ing describing a noun → relative clause.",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "He's used to [living] alone.",
        sentence: "Il a l'habitude de ___ seul.",
        answer: "vivre",
        explanation: "\"Avoir l'habitude de\" + infinitive.",
      },
      {
        type: "fill-blank",
        prompt: "Write the French for the bold words.",
        en: "She spent the evening [watching] series.",
        sentence: "Elle a passé la soirée ___ des séries.",
        answer: "à regarder",
        explanation: "\"Passer du temps à\" + infinitive.",
      },
      {
        type: "multiple-choice",
        question: "How do you say: I'm writing to inform you...?",
        options: [
          "Je vous écris pour vous informer...",
          "Je suis en train d'écrire pour vous informer...",
          "Je suis écrivant pour vous informer...",
          "J'écris en vous informant...",
        ],
        correctIndex: 0,
        explanation: "A letter opening uses the simple present.",
      },
      {
        type: "word-order",
        prompt: "Put the words in order to say: He left without locking the door.",
        words: ["Il", "est", "parti", "sans", "fermer", "la", "porte", "à", "clé."],
        translation: "He left without locking the door.",
        explanation: "\"Sans\" + infinitive.",
      },
      {
        type: "translate",
        direction: "en-es",
        prompt: "Translate into French.",
        source: "My grandmother was sitting in her armchair, knitting.",
        answer: "Ma grand-mère était assise dans son fauteuil et tricotait.",
        altAnswers: ["Ma grand-mère était assise dans son fauteuil, en train de tricoter.", "Ma grand-mère tricotait, assise dans son fauteuil.", "Ma grand-mère, assise dans son fauteuil, tricotait."],
        explanation: "Position → \"assise\"; activity → imperfect.",
      },
      {
        type: "listen-choose",
        audio: "Au lieu de te plaindre, propose une solution.",
        question: "What does it mean?",
        options: ["Instead of complaining, suggest a solution.", "Before complaining, find a solution.", "By complaining, you'll find a solution.", "Complain, then suggest a solution."],
        correctIndex: 0,
        explanation: "\"Au lieu de\" + infinitive.",
      },
      {
        type: "speak",
        text: "Je l'ai vu partir sans dire au revoir.",
        prompt: "Say it in French: I saw him leave without saying goodbye.",
        explanation: "Perception + infinitive, \"sans\" + infinitive.",
      },
    ],
  },
];
