// Synced from cheneygross-afk/lengo:src/lib/lessons/fr-culture.ts by scripts/sync-content.mjs -- edit it there, not here.
import type { Lesson } from "./types";
import type { UnitOutline } from "./units";
import { buildFrenchLevel, type FrenchUnitDef } from "./fr-units";
import { FR_CULTURE_U01, FR_CULTURE_U01_WRITING } from "./fr-culture-u01";
import { FR_CULTURE_U02, FR_CULTURE_U02_WRITING } from "./fr-culture-u02";
import { FR_CULTURE_U03, FR_CULTURE_U03_WRITING } from "./fr-culture-u03";

// French Culture: generated by scripts/gen-french-level.ts from
// docs/french-course/syllabus-culture.md and the unit files
// (fr-culture-u<NN>.ts, fr-culture-u<NN>-extra.ts). Don't edit by hand;
// re-run the script when a unit file is added.
const UNITS: FrenchUnitDef[] = [
  { id: "u01", title: "Fêtes & Food Culture", description: "Can talk about the French festive calendar and the rituals of the French table, from the apéro to the dessert, and behave like a guest who knows the unwritten rules.", lessons: FR_CULTURE_U01, writing: FR_CULTURE_U01_WRITING },
  { id: "u02", title: "Football, Cinema & Chanson", description: "Can follow and join everyday talk about football, French film and French song, and recognise the expressions they have lent to everyday French.", lessons: FR_CULTURE_U02, writing: FR_CULTURE_U02_WRITING },
  { id: "u03", title: "Superstitions & Social Customs", description: "Can greet, compliment, thank and behave as a guest the French way, and recognise the superstitions and politeness rituals that shape everyday interaction.", lessons: FR_CULTURE_U03, writing: FR_CULTURE_U03_WRITING },
];

const LEVEL = buildFrenchLevel("Culture", UNITS);
export const FR_CULTURE_LESSONS: Lesson[] = LEVEL.lessons;
export const FR_CULTURE_UNITS: UnitOutline[] = LEVEL.units;
